### ISSUE TITLE
suport: post/windows/gather/enum_files.rb

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#10004]
now the fork 
https://github.com/hktalent/metasploit-framework/blob/master/modules/post/windows/gather/enum_files.rb
is suport
```
run post/windows/gather/enum_files FILE_GLOBS=*.dmp SEARCH_FROM=*
 run post/windows/gather/enum_files FILE_GLOBS=*.docx;*.docx;*.xls;*.xlsx SEARCH_FROM=*
```
but not suport 
 run post/windows/gather/enum_files FILE_GLOBS=*.(doc?|xls?) SEARCH_FROM=*
```
where is 
   client.fs.file.search
code file, thanks? 

```

**Comment by timwr** [comment]
client.fs.file.search is here: https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb#L78

Why not ask on Slack or IRC? Github is meant for issues not support.
