### ISSUE TITLE
Help for support metasploit for current jailbrekon iOS 11

### ISSUE THREAD

**Issue by MCApollo** [rapid7/metasploit-framework#10014]
I’m skipping the default support stuff and getting right to the point.
**Jailbroken iOS 11.2**
[Here is a YT video of it running!](https://youtu.be/i1AhOFvxFR8) 
Although I compiled it, I did not make the video.

I have compiled ruby for arm64 (iOS 11 forces all binaries to be arm64) and have a working ruby gems.
*I grabbed the lastest tar release and untar’d it.*
I ran gem install bundle and bundle install with issues, painfully got dependencies compiled and fix the issues. Bundle finished and I attempted to run msfconsole and got instant error. 

**This is not the GitHub clone, rather than a tar file grabbed from the metasploit release page**

>Traceback (most recent call last):

        5: from /usr/local/bin/msfconsole:47:in `<main>'

        4: from /usr/local/bin/msfconsole:47:in `require'

        3: from /opt/metasploit-framework/lib/metasploit/framework/command/console.rb:5:in `top (required)'

        2: from /opt/metasploit-framework/lib/metasploit/framework/command/console.rb:5:in `require'

        1: from /opt/metasploit-framework/lib/metasploit/framework/command.rb:7:in `top (required)'

>**/opt/metasploit-framework/lib/metasploit/framework/command.rb:7:in `require': cannot load such file -- active_support/dependencies/autoload (LoadError)**

A google search does nothing and is the reason for this post.
It *can* be an error on my part due to iOS requiring codesigning on everything due to the jailbreak not fully disabling codesigning checks. 

Trying to botch a fix, I looked at the version of metasploit that was released **7-ish** years ago, which can be seen here: http://svn.telesphoreo.org/trunk/data/metasploit3/

Make.sh has this line.
>"${PKG_TARG}-gcc" -o /usr/share/msf3/data/templates/template_armle_darwin.bin  /usr/share/msf3/data/templates/template.c

I give a shot at the same line and quickly discover a horror.
>template_armle_darwin.bin: Mach-O executable acorn

*This is a file from the same release from 7-ish years ago and I don’t know where the source code is.*

So here are my questions.
First off, thank *you* for even reading this in the first place.
Secondly, I’m don’t program ruby at all, I have no idea how to fix the LoadError; Any help on where the error could be fixed coming from? 
Lastly, where is the source code for *template_armle_darwin.bin?* And or is template.c needed?

**Comment by bcoles** [comment]
> First off, thank *you* for even reading this in the first place.

You're welcome.

> Secondly, I’m don’t program ruby at all, I have no idea how to fix the LoadError; Any help on where the error could be fixed coming from?

[`active_support/dependencies/autoload`](http://api.rubyonrails.org/classes/ActiveSupport/Autoload.html) is part of the Rails [ActiveSupport module](http://api.rubyonrails.org/classes/ActiveSupport.html) and used for loading dependencies. Presumably there's something wrong with your Rails or ActiveSupport gems.

Metasploit makes extensive use of `autoload`. [`Metasploit::Framework` class](https://github.com/rapid7/metasploit-framework/tree/master/lib/metasploit/framework.rb) extends `ActiveSupport::Autoload` class.

If you manage to resolve this issue, you may run into further issues with the remaining dependencies.

> Lastly, where is the source code for *template_armle_darwin.bin*? And or is template.c needed?

I have no idea if it's needed. As for the source; it's a mystery. #4017

**Comment by bcoles** [comment]
To clarify, I don't know what I'm talking about. Someone else may be able to assist further.

**Comment by MCApollo** [comment]
I fixed dependencies and msfconsole starts. TY to all <3

**Comment by timwr** [comment]
Excellent news @MCApollo !!!

I'd love to see this in action. Let me know if you can provide more information :)

**Comment by MCApollo** [comment]
I’ll make a reddit post to reddit.com/r/jailbreak after I iron out some things, but I’ll plan/try to release soon.
