### ISSUE TITLE
Metasploit could not conection database

### ISSUE THREAD

**Issue by Nekromant13** [rapid7/metasploit-framework#10117]
Hello, I have big problem with metasploit database. I have upgraded my distro and installed packages and I'm running now postgresql 10. As from now, i can see the postgresql service is active. I then run msfdb init and I get this

A database appears to be already configured, skipping initialization
I run msfconsole but then the connection error shows up:

Failed to connect to the database: could not connect to server: Connection refused Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?
finally if i type db_status i get
"postgresql selected, no connection"

On the forums it is written that you need to fix the postgresql file.conf, but I don't have this file, although all packages are installed.

I will be very grateful if someone will help me.

**Comment by theinfecteddrake** [comment]
I guess this issue already has an answer [here](https://kb.help.rapid7.com/discuss/59949cbc078ec3000f0d5b8f).
