### ISSUE TITLE
Metasploit doesn't start after update

### ISSUE THREAD

**Issue by hexben** [rapid7/metasploit-framework#10112]
Hi,

After running a successful msfupdate (with no errors), my Metasploit doesn't want to start. I am getting the following messages:

```
C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: already initialized constant RbNaCl::Sodium::Ve rsion::MINIMUM_LIBSODIUM_VERSION
C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnac
l/sodium/version.rb:10: warning: previous definition of MINIMUM_LIBSODIUM_VERSIO
N was here
C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnac
l/sodium/version.rb:11: warning: already initialized constant RbNaCl::Sodium::Ve
rsion::MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2
C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnac
l/sodium/version.rb:11: warning: previous definition of MINIMUM_LIBSODIUM_VERSIO
N_FOR_ARGON2 was here
C:/metasploit-framework/embedded/framework/lib/msf/core/module/platform.rb:61:in
 `find_platform': No classes in Msf::Module::Platform for apple_ios! (ArgumentEr
ror)
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:55:in `block in initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:53:in `each'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:53:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:40:in `new'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:40:in `from_a'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module/plat
form_list.rb:32:in `transform'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module.rb:1
22:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/payload.rb:
70:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/payload/lin
ux.rb:18:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/base/sessions/co
mmand_shell_options.rb:16:in `initialize'
        from C:/metasploit-framework/embedded/framework/modules/payloads/singles
/apple_ios/aarch64/shell_reverse_tcp.rb:77:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/payload_set
.rb:198:in `new'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/payload_set
.rb:198:in `add_module'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/loading.rb:73:in `on_module_load'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/base.rb:183:in `load_module'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/base.rb:238:in `block in load_modules'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/directory.rb:50:in `block (2 levels) in each_module_reference_name'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-
0.1.12/lib/rex/file.rb:133:in `block in find'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-
0.1.12/lib/rex/file.rb:132:in `catch'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-
0.1.12/lib/rex/file.rb:132:in `find'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/directory.rb:40:in `block in each_module_reference_name'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/directory.rb:30:in `foreach'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/directory.rb:30:in `each_module_reference_name'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/modules/loa
der/base.rb:237:in `load_modules'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/loading.rb:119:in `block in load_modules'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/loading.rb:117:in `each'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/loading.rb:117:in `load_modules'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/module_paths.rb:41:in `block in add_module_path'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/module_paths.rb:40:in `each'
        from C:/metasploit-framework/embedded/framework/lib/msf/core/module_mana
ger/module_paths.rb:40:in `add_module_path'
        from C:/metasploit-framework/embedded/framework/lib/msf/base/simple/fram
ework/module_paths.rb:50:in `block in init_module_paths'
        from C:/metasploit-framework/embedded/framework/lib/msf/base/simple/fram
ework/module_paths.rb:49:in `each'
        from C:/metasploit-framework/embedded/framework/lib/msf/base/simple/fram
ework/module_paths.rb:49:in `init_module_paths'
        from C:/metasploit-framework/embedded/framework/lib/msf/ui/console/drive
r.rb:219:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework
/command/console.rb:62:in `new'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework
/command/console.rb:62:in `driver'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework
/command/console.rb:48:in `start'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework
/command/base.rb:82:in `start'
        from C:/metasploit-framework/bin/../embedded/framework/msfconsole:48:in
`<main>'
```

Please note: 

I am running Windows 7 (32bits), with all the updates. 
Metasploit Framework was working fine before the msfupdate.
I have cleared my cookies as suggested by some user on google. 

Any help is appreciated.
Thanks
Ben

**Comment by busterb** [comment]
This backtrace doesn't appear to be from the current packages at all - we haven't shipped rbnacl in many months. It's definitely not in the current packages.

When did you last run 'msfupdate' ? I'd recommend you do it again.

**Comment by hexben** [comment]
I ran msfupdate for the first time about a week ago. 
Last night, I checked Windows Installation programs, and I realize 'msfupdate' installed me an older version (V 4.16.17.1) on top of the installed version 4.16.57.1. It was very strange to see both version were installed at the same time. I thought 'msfupdate' does only updates. Am I wrong?

I then uninstalled the older one 4.16.17.1, I realized a lot of files were missing, so I uninstalled 4.16.57.1 too. And had to re-do a brand new Install. 

When I tried to launch msfconsole, I got a long list of errors. I had to clear my cache, then re-started my machine twice. Finally this morning it works.

Could you tell me how often should I run 'msfupdate'?

Thanks in advance.
I am using:
Windows Installer Package (.msi)
Metasploit-framework v4.16.57

**Comment by IamA2004** [comment]
I try ./msfupdate showing error 

[*] Attempting to add remote 'upstream' to your local git repository.
error: remote upstream already exists.
[*] Added remote 'upstream' to your local git repository.
[-] ERROR: user.name is not set in your global git configuration
[-] Set it by running: 'git config --global user.name "NAME HERE"'

**Comment by bcoles** [comment]
> I try ./msfupdate showing error
> 
> [_] Attempting to add remote 'upstream' to your local git repository. error: remote upstream already exists. [_] Added remote 'upstream' to your local git repository. [-] ERROR: user.name is not set in your global git configuration [-] Set it by running: 'git config --global user.name "NAME HERE"'

```
git config --global user.name "IamA2004"
```

**Comment by IamA2004** [comment]
Thanks for help error fix 
But new error here How to solve this error

./msfconsole
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Metasploit tip: View a module's description using info, or the enhanced
version in your browser with info -d
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from ./msfconsole:23:in `<main>'

**Comment by bcoles** [comment]
> But new error here

Metasploit cannot find `/etc/resolv.conf`.

> How to solve this error

Termux is not a supported platform for Metasploit.
