### ISSUE TITLE
"illegal instruction" after typing msfconsole

### ISSUE THREAD

**Issue by Exotic-Algorithms** [rapid7/metasploit-framework#10139]
Im running it on Raspbian on the raspberry pi zero w.  I have installed and uninstalled three times and nothing is working to fix it.  I also tried running "ruby msfconsole" but that gave the same result.

**Comment by wvu-r7** [comment]
Post some logs and screenshots.

**Comment by nasirxo** [comment]
i got same thing on rpi zero w

**Comment by nasirxo** [comment]
![Uploading Screenshot_20220305-103418.png…]()

**Comment by bcoles** [comment]
Post some logs and screenshots.
