### ISSUE TITLE
scanner/smb/smb_login not working on internal host after route added

### ISSUE THREAD

**Issue by corrupt-technology** [rapid7/metasploit-framework#10134]
## Steps to reproduce

scanner/smb/smb_login not connecting to internal host after a route has been added.

msf auxiliary(scanner/portscan/tcp) > set PORTS 1,22,80,443,445,8080,8333
PORTS => 1,22,80,443,445,8080,8333
msf auxiliary(scanner/portscan/tcp) > set threads 5
threads => 5
msf auxiliary(scanner/portscan/tcp) > set RHOSTS 10.0.7.1
RHOSTS => 10.0.7.1
msf auxiliary(scanner/portscan/tcp) > run

[+] 10.0.7.1:             - 10.0.7.1:80 - TCP OPEN
[+] 10.0.7.1:             - 10.0.7.1:445 - TCP OPEN

msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.7.1:445          - 10.0.7.1:445 - Starting SMB login bruteforce
^C[*] Caught interrupt from the console...

just hangs here.. does not connect to host though the tcp scanner is able to.
## Expected behavior

What should happen?
should connect to host and run module against host.

## Current behavior

Does not connect to host though a route has been added and is able to connect with other modules.

[06/03/2018 07:10:51] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop

### Metasploit version

Framework: 4.16.59-dev-
Console  : 4.16.59-dev-

### I installed Metasploit with:

[x] Source install (please specify ruby version)
# ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

### OS

# cat /etc/issue
Ubuntu 14.04 LTS \n \l

**Comment by bcoles** [comment]
Just to confirm: are you really using Ruby version `1.9.3p484` ? This version is ancient and end-of-life. I also have my doubts that Metasploit works with any version of Ruby prior to 2.0; or even 2.2 for that matter.

Note that the Metasploit source directory contains a `.ruby-version` file which defaults to Ruby `2.5.1`. It's possible that if you're using a Ruby environment manager, such as rvm or rbenv, that it is silently switching version.
