### ISSUE TITLE
"msfvenom -l all" fails with undefined method `encryption_formats'

### ISSUE THREAD

**Issue by sbrun** [rapid7/metasploit-framework#10152]
## Steps to reproduce

I worked on updated the Kali package to the latest version 4.16.60
I tested:
```
msfvenom -l all
```
And 
``` 
msfvenom -l encrypt
```

## Current behavior
It fails with:
```
Traceback (most recent call last):
	3: from /usr/bin/msfvenom:363:in `<main>'
	2: from /usr/bin/msfvenom:363:in `each'
	1: from /usr/bin/msfvenom:385:in `block in <main>'
/usr/bin/msfvenom:257:in `dump_encrypt': undefined method `encryption_formats' for Msf::Simple::Buffer:Module (NoMethodError)
```
The "encryption_formats" is not defined in your branch 4.x but it's in the master branch.

To fix this in Kali, I picked up the encryption_formats definition from master branch and add it in file lib/msf/base/simple/buffer.rb 

### Metasploit version
4.16.60

### I installed Metasploit with:
- [ x] Kali package

### OS
Kali-dev

**Comment by jmartin-r7** [comment]
Sorry about the confusion, this was a miss on the a PR that refactored help and also happened to pick up some reference to experimental function in master.  Please revert import of `encryption_formats` and we should have a PR landed shortly to address this in 4.x.

**Comment by jmartin-r7** [comment]
Options not available on 4.x are now removed.
