### ISSUE TITLE
Uninitialized constant RequestError in post/windows/gather/screen_spy and potentially others

### ISSUE THREAD

**Issue by AddaxSoft** [rapid7/metasploit-framework#10161]
I'm trying to automate things and one of the scripts I run fails after the victim goes offline, how can I catch these ruby exceptions and handle them from there?

```
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.10/modules/post/windows/gather/screen_spy.rb:74:in `run'
[-] Post failed: NameError uninitialized constant Msf::Modules::Modblablalblalalblbla::MetasploitModule::RequestError
[-] Call stack:
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.10/modules/post/windows/gather/screen_spy.rb:78:in `rescue in block in run'
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.10/modules/post/windows/gather/screen_spy.rb:76:in `block in run'
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.10/modules/post/windows/gather/screen_spy.rb:74:in `times'
[-]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.10/modules/post/windows/gather/screen_spy.rb:74:in `run'
```

in my `msfconsole.rc`, I have some ruby code to wait for `stdapi` to load for example, 

```
<ruby>
    # Ensure that stdapi has been loaded before running
    flag = false
    for n in 1..20
        framework.sessions.each_pair do |sid,s|
            thost = s.session_host
                if s.ext.aliases['stdapi']
                                print_status("bingo - got stdapi...")
                flag = true
                break
                        else
                                print_status("Session #{sid} #{thost} active, but not yet configured")
                sleep(3)
                        end
        end
        if flag
            break
        end
    end
        if flag == false
            print_status("session never got stdapi - reloading resources")
            self.run_single("resource /root/.msf4/msfconsole.rc")
        end
</ruby>
```

is there a way I can catch the ruby exceptions inside this code ?

a more generic question would be: How to handle exception of AutoRunScript to recover in case of error

**Comment by Green-m** [comment]
How about pry? 
Add `binding.pry` in file to break and debug.

**Comment by AddaxSoft** [comment]
@Green-m, hmm but I don't want to debug, I just want to catch the exception and recover from it by re-initializing the whole script .. quick and dirty way :)

**Comment by wvu-r7** [comment]
http://rubylearning.com/satishtalim/ruby_exceptions.html

**Comment by AddaxSoft** [comment]
@wvu-r7 that's really not the question, the question is how can I catch the exception insided teh script not ruby in general

of course a way is to edit the core code bla bla, but i'm looking for something easier and can be scaled easily.

**Comment by wvu-r7** [comment]
```
[-] Post failed: NameError uninitialized constant Msf::Modules::Modblablalblalalblbla::MetasploitModule::RequestError
```

This actually looks like a bug. It should be `Rex::Post::Meterpreter::RequestError`, I imagine. You should not be catching this yourself.

**Comment by AddaxSoft** [comment]
@wvu-r7 ok then why closing the issue =) ?

**Comment by wvu-r7** [comment]
Because it's not the issue anymore. :-)

**Comment by wvu-r7** [comment]
Lol, I can reopen this under a different title. No need to create a new issue.

**Comment by wvu-r7** [comment]
@AddaxSoft: See if https://github.com/rapid7/metasploit-framework/pull/10165 fixes the issue for you.

Also, we don't do support or code help here. We use GitHub primarily for bug requests and the occasional feature request. Check out https://metasploit.com/help for a list of resources. IRC is pretty good. Thanks!
