### ISSUE TITLE
msfvenom error: invalid option

### ISSUE THREAD

**Issue by pkermani** [rapid7/metasploit-framework#10164]
## Steps to reproduce
when i issue..
root@kali:~# msfvenom -p android/meterpreter/reverse_tcp --payload-options

## Expected behavior
I expect to see the Options for the payload

## Current behavior
Currently mfsvenom displays the following:

Error: Invalid option
MsfVenom - a Metasploit standalone payload generator.
Also a replacement for msfpayload and msfencode.
Usage: /usr/bin/msfvenom [options] <var=val> ....

### OS
I am using 
Kali-Linux 2018.2 in a guest VM (VirtualBox) with WIndows 10 as a host system

Thanks for your help.

**Comment by wvu-r7** [comment]
Changed to `--list-options` in #10029. Breaking change, sorry.

**Comment by pkermani** [comment]
Thank you wvu-r7.
