### ISSUE TITLE
Payload installed but not opening on android

### ISSUE THREAD

**Issue by Krishsinghal123** [rapid7/metasploit-framework#10175]
## Steps to reproduce

How'd you do it?

1.  used msfvenom to generate the payload, specified LHOST and LPORT
2. The apk installs succesfully on the target but when I click on it it doesn't works(not running in background) nor does the meterpreter gets a session

It should have worked according to the sources, wonderhowto.com etc.
Target is android- 
1. Htc-4.4.2-kitkat
2. Samsung- 4.0.4

### preinstalled and updated Metasploit 

What OS are you running Metasploit on?
KALI version 2018.2

**Comment by wvu-r7** [comment]
Can the payload egress to the handler?

**Comment by Krishsinghal123** [comment]
I guess not. Tried again yesterday, the application wont install anymore.

**Comment by theinfecteddrake** [comment]
Basic permissions like `Allow installation from Untrusted Sources` given?

**Comment by Krishsinghal123** [comment]
@theinfecteddrake yes
@wvu-r7 I tried that a few days back, I was looking for answers before I posted here, earlier I was able to send the apk and it installed fine, but when I tried again it didn't install.

**Comment by krishna-cyber** [comment]
I have inject the payload manually so it may cause a mistake
