### ISSUE TITLE
msfconsole  msfvenom

### ISSUE THREAD

**Issue by biowulf2** [rapid7/metasploit-framework#10186]
hello 
i have problem with my kali 
when i use msfvenom and msfconsole give error and stops me doing my job i use kali nethunter on my phone and kali linux on my computer and two of them have this problem, The error :

/usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:72:in `not_after=': bignum too big to convert into `long' (RangeError)
        from /usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:72:in `generate_cert'
        from /usr/share/metasploit-framework/modules/payloads/stagers/android/reverse_https.rb:64:in `generate_jar'
        from /usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:27:in `generate'
        from /usr/share/metasploit-framework/lib/msf/core/payload.rb:200:in `size'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:158:in `block (2 levels) in recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:102:in `each_pair'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:102:in `block in recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:98:in `each_pair'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:98:in `recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:276:in `block in load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:273:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:273:in `load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `block in load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:115:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:115:in `load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:212:in `initialize'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /usr/bin/msfconsole:48:in `<main>'

please help me i beg you .

**Comment by bcoles** [comment]
Is your Metasploit up to date?

This issue should have been resolved in #9653 as per #9556

**Comment by biowulf2** [comment]
how to update ? help please

**Comment by bcoles** [comment]
Your error is in `lib/msf/core/payload/dalvik.rb` which was renamed to `lib/msf/core/payload/android.rb` in 2016 in dc43f59dcfd67784750a2a25f837bec4e8de45f5.

Update Metasploit.

**Comment by bcoles** [comment]
To update msf, run `msfupdate`

If using Metasploit Pro, refer to: https://metasploit.help.rapid7.com/docs/updating-metasploit

If using Metasploit development branch from Git, do: `git pull && bundle install`

If using Metasploit from your operating system packages, you may want to try `apt-get update && apt-get dist-upgrade` for Ubuntu based systems, or `yum update` for RHEL based systems.

**Comment by biowulf2** [comment]
i use it on my kali and nethunter

**Comment by bcoles** [comment]
To update msf, run `msfupdate`
