### ISSUE TITLE
Nokogiri

### ISSUE THREAD

**Issue by junkyzet** [rapid7/metasploit-framework#10197]
Someone help me 

Downloading nokogiri-1.8.0 revealed dependencies
not in the API or the lockfile (mini_portile2 (~>
2.2.0)).
Either installing with `--full-index` or running
`bundle update nokogiri` should fix the problem.

In Gemfile:
factory_girl_rails was resolved to 4.9.0, which
depends on
railties was resolved to 4.2.10, which depends
on
actionpack was resolved to 4.2.10, which
depends on
actionview was resolved to 4.2.10, which
depends on
rails-dom-testing was resolved to 1.0.9,
which depends on
            nokogiri

**Comment by busterb** [comment]
Not sure what situation you're in, but Metasploit hasn't used 'factory_girl_rails' for months. Try updating to a newer version.
