### ISSUE TITLE
migrate to a newer ruby_pg

### ISSUE THREAD

**Issue by blshkv** [rapid7/metasploit-framework#10234]
https://github.com/rapid7/metasploit-framework/blob/master/metasploit-framework.gemspec#L91
```
  # Used by the Metasploit data model, etc.
  # bound to 0.20 for Activerecord 4.2.8 deprecation warnings:
  # https://github.com/ged/ruby-pg/commit/c90ac644e861857ae75638eb6954b1cb49617090
  spec.add_runtime_dependency 'pg', '0.20.0'
```

many distros have moved to 0.21.0 or the latest 1.0.0.

Please consider migrating msf as well.

**Comment by blshkv** [comment]
FYI, I have tried to run msf with 0.21.0 and got the following warning:
```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
```

**Comment by kkirsche** [comment]
Does it make sense instead if we're going to do this work to just move to 1.0.0 which is the default `gem install pg` version?

**Comment by busterb** [comment]
We updated to 0.21 as of https://github.com/rapid7/metasploit-framework/pull/11387 . I believe 1.0+ is underway as well as part of a RoR 5.x upgrade.

**Comment by blshkv** [comment]
well, yeah. RoR 4.x is dead, so you should have really pushed 1.0+ instead.
It took 2 years to fix this bug report, RoR 5.x will be EOL in other 2 years probably.
