### ISSUE TITLE
Handler and payload options are conflated

### ISSUE THREAD

**Issue by ostby** [rapid7/metasploit-framework#10243]
use multi/handler
set payload multi/meterpreter/reverse_https
show advanced

Some of the payload options shown make sense. E.g. SessionRetryWait, since they affect the behavior of meterpreter running on the target system.

But other payload options shown make no sense. E.g. ReverseListenerBindAddress and IgnoreUnknownPayloads. Those aren't payload options. They don't affect the behavior of meterpreter running on the target system! They're handler options. They only affect the behavior of MSF running on the C2 server.

Mixing those all together and calling them all payload options is confusing and frustrating.

**Comment by ccondon-r7** [comment]
Closing this but adding a label that we'll use to surface general usability needs internally! Thank you!
