### ISSUE TITLE
Interactive processes don't work using the `sessions -C` command

### ISSUE THREAD

**Issue by asoto-r7** [rapid7/metasploit-framework#10261]
## Steps to reproduce

From a `meterpreter/x64/bind_tcp` payload on Win10 SP1 fully patched:

1. Run `execute -i -f xcopy.exe` or `execute -i -f net.exe`.  Note the output from the command, which was executed on the target.

2. Background meterpreter.

3. Run `sessions -C 'execute -i -f xcopy.exe' and `sessions -C 'execute -i -f net.exe'.  Note the error message.

## Expected behavior

The command should be executed on the target, with the output being returned.  In the event of a process which takes user input, the realtime input/output should be provided, one at a time.

## Current behavior

A traceback occurs.  The following message is printed to the user:
```
[-] Error running command execute: NoMethodError undefined method `fd' for nil:NilClass
```

Strangely, I don't see any details in `development.log`:

```
$ egrep -v "schema|CREATE|DROP" ~/.msf4/logs/development.log
$
```

### Metasploit version

msf5 > version
Framework: 5.0.0-dev-5a693aa89c
Console  : 5.0.0-dev-5a693aa89c

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

Parrot Linux 4.1

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

**Comment by adfoster-r7** [comment]
Closing in favor of https://github.com/rapid7/metasploit-framework/issues/15147
