### ISSUE TITLE
mimikatz

### ISSUE THREAD

**Issue by r00t-Taurus** [rapid7/metasploit-framework#10269]
When i load mimikatz (load mimikatz) and write command `mimikatz_command -f privilege::debug` ( for example) i get this `Demande d'ACTIVATION du privil�ge : SeDebugPrivilege : KO ; (0x00000514) K7K20NI0O AB>@>=0 =5 >1;0405B 2A5<8 =5>1E>48<K<8 ?@020<8 4>ABC?0.`
How to fix it?
OS Kali linux 2018.1

**Comment by OJ** [comment]
1) don't use the mimikatz extension unless Meterpreter is running on a very
old OS. Instead, use the kiwi extension.
2) the mimikatz command you're running requires the SeDebugPrivilege
privilege. If you don't have it, it won't work.

**Comment by r00t-Taurus** [comment]
I also want to clarify something, when i load kiwi, it load in memory?

**Comment by OJ** [comment]
It behaves the same as any other extension. They all load directly into
memory.
