### ISSUE TITLE
SSH modules writing to ~/.ssh/known_hosts

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#10266]
This has been annoying me for **quite** some time.

1. Run an SSH module
2. See that it wrote to `~/.ssh/known_hosts`
3. Get angry because you just used a scanner

Note that the cargo-culted SSH options hash we use already disables config and agent.

**Comment by h00die** [comment]
I'll also add that if you are testing multiple networks on an engagement with overlapping IP ranges, you will get a silent failure for ssh_login if there is a server ssh key mismatch. That's always annoyed the hell out of me.

**Comment by kkirsche** [comment]
Patch submitted @wvu-r7

**Comment by wvu-r7** [comment]
Hooray!
