### ISSUE TITLE
What should I do to fix this?-Metasploit

### ISSUE THREAD

**Issue by SaraDN** [rapid7/metasploit-framework#10281]
WARNING! The following modules could not be loaded!
[-]     C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.65/modules/auxiliary/dos/smb/smb_loris.rb: Msf::Modules::Error Failed to load module (dos/smb/smb_loris from C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.65/modules/auxiliary/dos/smb/smb_loris.rb) due to Invalid module (no MetasploitModule class or module name)﻿

Thank you!

**Comment by wvu-r7** [comment]
2.3.0 is quite old. Have you updated?

**Comment by bcoles** [comment]
I believe Metasploit aims to work on all supported versions of Ruby. [Ruby 2.3.0 EOL is scheduled for 2019-03-31](https://www.ruby-lang.org/en/downloads/branches/).

This module works for me with Metasploit 5.0.0-dev-d932c17 using Ruby 2.3.0 (on Linux).

**Comment by bcoles** [comment]
Metasploit Framework 4.16.65 on the other hand, is out of date. Latest is 4.17.1.

**Comment by SaraDN** [comment]
Thanks for advice! 👍 
Anyway, I think I'll better try to install it again as I really don't figure out what's wrong. I have watched a YouTube tutorial to install Metasploit and maybe it was a bad tutorial. I'm new to this :))

**Comment by busterb** [comment]
The problem is due to Windows not having a execute bit. Our original hack was to check the #! at the head of the module. Wonder if that would solve it here.

**Comment by fsacer** [comment]
pretty much resolved issue @wvu-r7, not sure why you'd even want to run metasploit on Windows
