### ISSUE TITLE
MSFCONSOLE Errno: :ENONEM

### ISSUE THREAD

**Issue by TheGlowman** [rapid7/metasploit-framework#10292]
Guys , i have this error when i'm oppening the mfsconsole in the terminal... 
Cannot allocate memory - infocmp (Errno: :ENOMEM) 
Please help ?

**Comment by bcoles** [comment]
`man errno`

**Comment by TheGlowman** [comment]
man errno ?

**Comment by bcoles** [comment]
https://www.google.com/search?q=what+is+a+man+page

http://man7.org/linux/man-pages/man3/errno.3.html

**Comment by TheGlowman** [comment]
oh but how do i allocate more space ?

**Comment by bcoles** [comment]
https://www.wikihow.com/Add-RAM
or
https://www.google.com/search?q=what+is+a+swap+file

**Comment by TheGlowman** [comment]
Ohh why didnt you said ram memory ... btw ty for the help .
