### ISSUE TITLE
metasploit-framework install error

### ISSUE THREAD

**Issue by dd404x** [rapid7/metasploit-framework#10308]
## Steps to reproduce

How'd you do it?

1. 
```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```
2.
![image](https://user-images.githubusercontent.com/19923974/42719156-11b5a380-8744-11e8-86da-d41a4dc5e2d8.png)

### OS

What OS are you running Metasploit on?
windows-app-kali linux
https://www.kali.org/news/kali-linux-in-the-windows-app-store/

**Comment by NiksonBinsk** [comment]
Are you try running `sudo apt-get upgrade` ?
