### ISSUE TITLE
post/windows/gather/credentials/vnc

### ISSUE THREAD

**Issue by h4ng3r** [rapid7/metasploit-framework#10321]
I'll fill all the template but I'd like to discus why "post/windows/gather/credentials/vnc" has the unpack stuff (value = data.unpack('H*')[0].to_s line 69) . This is displaying a wrong has and a wrong clear text password. I don't know if it's for fix problems with others VNC programs or just to avoid UTF8 chars. For WinVNC4 is better show the data without unpack or at least pack it again to decrypt the cleartext password.

Thanks

## Steps to reproduce

Pwn a machine with RealVNC 4 Enterprise (aka WinVNC4)

use post/windows/gather/credentials/vnc
set SESSION 1
run

## Expected behavior

Location: WinVNC4_HKLM => Hash: XXYYZZAABBCCDDEE => Password: $ClearTextPassword$ => Port: 5900

## Current behavior

Location: WinVNC4_HKLM => Hash: hex(XXYYZZAABBCCDDEE) => Password: $shit$ => Port: 5900

### Metasploit version

Framework: 5.0.0-dev-bb8fd45cb2
Console  : 5.0.0-dev-bb8fd45cb2

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (ruby 2.4.2p198)

### OS
Debian GNU/Linux 9 (4.9.0-6-amd64)

**Comment by h4ng3r** [comment]
Should I close the issue?

**Comment by ccondon-r7** [comment]
Yeah, I guess I'll close it for now.
