### ISSUE TITLE
Can't exit powershell_shell with "exit"

### ISSUE THREAD

**Issue by DanMcInerney** [rapid7/metasploit-framework#10324]
## Steps to reproduce

1. Start msfconsole with the RPC client enabled
2. Connect to RPC client
3. I'm using the msfrpc python library to connect so I load the PSH plugin and drop into a shell like so:

client.call('session.meterpreter_write', ['1', 'load powershell'])
client.call('session.meterpreter_write', ['1', 'powershell_shell'])
client.call('session.meterpreter_read', ['1'] will now output {b'data': b'PS > \x00'}

Great we're in a shell. Now how the hell do I close this thing? 
client.call('session.meterpreter_write', ['1', 'exit\n']) - doesn't work

If I were interacting with the shell via msfconsole then I'd just hit CTRL-C and when it asks "Terminate this channel? [y/N]" I'd hit y. But doing this same thing in Python doesn't work.

os.kill(<pid of msfconsole>, signal.SIGINT) - This leads to a pop up on the Windows box saying (paraphrased), "Powershell crashed, end program?". This also leads to the meterpreter session no longer working. Doesn't die, just doesn't give any output for any command.

## Expected behavior
Typing "exit" should drop you back into the meterpreter

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
Kali Rolling

**Comment by fsacer** [comment]
had same experience (not exitting on exit) on that one, Ctrl+C works though

**Comment by OJ** [comment]
Currently the extension doesn't support exiting in that manner. CTRL+c is
the only way to exit at this point.

**Comment by hotbloodaunt** [comment]
If "exit" not works and you don't want to use CTRL+C, then try to use CTRL+Z can background it. So you can skit it.

**Comment by init5-msft** [comment]
It's 2021 and powershell_shell STILL doesn't have an exit function. Sad.

**Comment by kaverdinho** [comment]
exit console

I think you guys are looking for this :)
