### ISSUE TITLE
Bug in upload_exec.rb for Linux

### ISSUE THREAD

**Issue by okazymyrov** [rapid7/metasploit-framework#10337]
## Steps to reproduce

How'd you do it?

1. use post/multi/manage/upload_exec
2. set LFILE /tmp/pl
3. set RFILE /root/pl
4. set SESSION 1
5. run

When the module is done the payload is not executed. The reason is in "./#{rfile}" (see https://github.com/rapid7/metasploit-framework/blob/master/modules/post/multi/manage/upload_exec.rb#L46). It should be (withoout ."/"):
```
cmd_exec("chmod 755 #{rfile} && #{rfile}", nil, 0)
```

The above fix works in my environment.

## Expected behavior

When both LFILE and RFILE are specified the file is executed.

## Current behavior

What happens instead?

A file is uploaded and deleted, but not executed.

### Metasploit version

Framework: 4.16.63-dev
Console  : 4.16.63-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

Kali Linux

**Comment by wvu-r7** [comment]
I don't think it should be without `./` unless the option is renamed to `RPATH`.

```
        OptPath.new('LFILE', [true,'Local file to upload and execute']),
        OptString.new('RFILE', [false,'Name of file on target (default is basename of LFILE)']),
```

As you can see from the option, it's supposed to be a filename, not an absolute path. Why don't we update the module to take `LPATH` and `RPATH`? `LFILE` is already assumed to be a path (relative accepted).

**Comment by wvu-r7** [comment]
I'd also argue being able to specify absolute paths for ~`RFILE`~ `RPATH` is better, since you might have `noexec` at CWD.

**Comment by okazymyrov** [comment]
I would also like to have an option, like `noexec`. At the same time, I think the options should be cross-platform (i.e., the module must behave the same on WIndows and on Unix).
