### ISSUE TITLE
Error 502 when accessing https://www.metasploit.com via <a> link

### ISSUE THREAD

**Issue by f1she3** [rapid7/metasploit-framework#10342]
## Steps to reproduce

Go to https://www.archlinux.org/packages/community/x86_64/metasploit/ (or test it locally) and click on the "upstream URL" section : a 502 bad gateway error occurs

## Expected behavior

The page should load normally

## Current behavior

the Error occurs but not when accessing the URL directly, strange !
The page loads when hitting enter on the URL area in Firefox 61.0.1  but not when reloading (F5)

### OS
Arch linux

**Comment by sempervictus** [comment]
This is an Arch repo maintainer issue if im reading it correctly.

**Comment by jmartin-r7** [comment]
There is currently an outage for https://www.metasploit.com, Rapid7 is working on addressing the issue.  This is not a framework bug. Closing the issue here.
