### ISSUE TITLE
Joomla Plugins

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#10359]
While writing docs, I noticed that the joomla plugins scanner has a wordlist thats 6yrs old.  Maybe it's time to either update that list, or just kill the module in favor of joomscan?  Thoughts anyone? Any takers? @Newpid0

**Comment by fsacer** [comment]
tbh never used the joomla scanner in metasploit also is worrying that there were no updates to joomscan for 5 months

**Comment by newpIDC** [comment]
Pretty sure the guy who wrote this module originally can no longer commit to public repos, which is sad. Joomscan is good the goal was just to put it in msf

**Comment by wvu-r7** [comment]
Is he in GitHub prison or something?
