### ISSUE TITLE
Regexp match error when mutiple slashes 

### ISSUE THREAD

**Issue by Green-m** [rapid7/metasploit-framework#10372]
## Steps to reproduce

I found a problem when developing cmd_*_tabs method.

```
str = "HKCU\\\\Software"
tab_word = "HKCU\\\\Software\\\\7-Zip"
tab_word  =~ /^#{str}/i  => nil
```

Relevant problem code in `lib/rex/ui/text/dispatcher_shell.rb` line 390 

```
    # Verify that our search string is a valid regex
    begin
      Regexp.compile(str,Regexp::IGNORECASE)
    rescue RegexpError
      str = Regexp.escape(str)
    end
......
    items.find_all { |e|
      e =~ /^#{str}/i
    # Prepend the rest of the command (or it all gets replaced!)
    }.map { |e|
      tab_words.dup.push(e).join(' ')
    }

```

When the `str = "HKCU\\\\Software"`, `tab_word = "HKCU\\\\Software\\\\7-Zip" `:

```
tab_word =~ Regexp.compile(str,Regexp::IGNORECASE) => nil
tab_word =~ Regexp.escape(str) => 0
```
` Regexp.compile(str,Regexp::IGNORECASE) ` would not throw exception, `str = Regexp.escape(str)` would not be executed either.

So I think there is a issue in the regexp match code in `lib/rex/ui/text/dispatcher_shell.rb`, especially on windows. 

### Metasploit version

Framework: 5.0.0-dev-00a748a92c
Console  : 5.0.0-dev-00a748a92c

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`

### OS

`Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux`

**Comment by Green-m** [comment]
Fixed by https://github.com/Green-m/metasploit-framework/blob/3f8906596d429dd1d5731e5c046a15762cebfc31/lib/rex/ui/text/dispatcher_shell.rb#L403

**Comment by bcoles** [comment]
The change mentioned above is not `nil` safe:

```ruby
e.downcase.start_with?(str.downcase) || e =~ /^#{str}/i
```

Also, is the regex match even necessary? Would this work?

```ruby
e.to_s.downcase.start_with?(str.downcase)
```

**Comment by Green-m** [comment]
@bcoles Thanks for your review of this code! 
I'm sure this code would not be influenced by the problem.
```
[198] pry(main)> test = []
=> []
[199] pry(main)> test.find_all{|e| e.downcase.start_with?('randomstring')}
=> []

```
Since `items` is init to `[]` here https://github.com/Green-m/metasploit-framework/blob/3f8906596d429dd1d5731e5c046a15762cebfc31/lib/rex/ui/text/dispatcher_shell.rb#L360
It always return a array.

Second question:

Ideally the regex match would not be necessary, but I keep it with `||` to avoid some unexpected scenes.
Maybe we could remove the regex match after giving this adequate test ? 
Glad to reveive your suggestion.
