### ISSUE TITLE
show IP in joomla page scanner

### ISSUE THREAD

**Issue by alexhalbi** [rapid7/metasploit-framework#10396]
[This line](https://github.com/rapid7/metasploit-framework/blob/7596366df057397e951f3f2bb621f8b6f0e169d2/modules/auxiliary/scanner/http/joomla_pages.rb#L66) could be changed to
```rb
print_good("#{note}: #{ip}#{tpath}#{page}")
```
to also show the IP address when scanning multiple hosts.

**Comment by wvu-r7** [comment]
Can you make a pull request, since you already have it tested? :)

**Comment by alexhalbi** [comment]
Sure, I just uploaded it! Pull Request #10403
