### ISSUE TITLE
Windows Backspace not Working in msfconsole and random number generates when setting RHOSTS option

### ISSUE THREAD

**Issue by Bohidharma** [rapid7/metasploit-framework#10393]
Hi i'm using a windows 7 and running metasploit version 4.17.0 on a 32 bit system. After i load into the msfconsole and run a db_nmap scan, anytime i try to type something else, i cannot backspace or delete my text if i make mistakes. Also when i try to set my RHOST option, it doesn't allow me write a full ipaddress. I tried pasting the ipaddress but it just put more random numbers when i try to write the dot "." for the ipaddress.

Don't know why i'm having this error!

**Comment by westwind027** [comment]
encounter the same issue, have u solve it?
