### ISSUE TITLE
Add command to create database cache entries in foreground.  

### ISSUE THREAD

**Issue by DaniloNC** [rapid7/metasploit-framework#10392]
## Steps to reproduce

I want to create an automatic built Docker image that will have an installed version of Metasploit with a pre-populated msfdb cache so I won't receive the message during:
```
[!] Module database cache not built yet, using slow search
```

How'd you do it?

On Kali:

1. apt install metasploit-framework -y
2. msfdb reinit
3. msfconsole
4. search ms08-067

The slow search message will show-up:
```
[!] Module database cache not built yet, using slow search
```
## Expected behavior

There should be a command (maybe a msfdb subcommand) that would create the database cache in foreground so ones can create a pre-populated docker/vagrant image.

## Current behavior

As far as I know, there is no way to script the creation of the database cache.

## System stuff

Kali Linux docker image

### Metasploit version

```
msf > version
Framework: 4.17.2-dev
Console  : 4.17.2-dev
```

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali linux docker image.

**Comment by theInfectedDrake** [comment]
Is `postgresql` service running?

**Comment by DaniloNC** [comment]
@theInfectedDrake the problem is not that the msfdb/Postgres does not work but that there is no easy way to script the creation of the database cache other than opening the msfconsole and waiting for it to finish.

Yes, the postgresql service is running.

**Comment by wvu-r7** [comment]
> 1. apt install metasploit-framework -y

AFAIK, the `4.x` branch doesn't use the updated module cache. `master` does, and the cache no longer comes from Postgres. Consider a source install... or just use our `Dockerfile` in this repo?

**Comment by wvu-r7** [comment]
@theInfectedDrake: I think the error message would be `Database not connected, using slow search` in that case.

**Comment by DaniloNC** [comment]
Thanks @wvu-r7, I will try to use the metasploit docker file on this repo.

Just for mine and possible others future reference, the automated metasploit docker image is available at https://hub.docker.com/r/metasploitframework/metasploit-framework/ or docker pull metasploitframework/metasploit-framework
