### ISSUE TITLE
Problem with installing gems

### ISSUE THREAD

**Issue by sucklaugh** [rapid7/metasploit-framework#10438]
Ive tried installing metasploit in termux app through auto installation then i tried running msfconsole it shows this error:

`WARNING: linker: /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pg-0.20.0/lib/pg_ext.so: unused DT entry: type 0x1d arg 0x1667`

**Comment by Auxilus** [comment]
@sucklaugh you need to remove the DT entry by `termux-elf-cleaner /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pg-0.20.0/lib/pg_ext.so`

**Comment by jmartin-r7** [comment]
Unfortunately termux is not an officially supported console environment at this time.  There is an active community working with it however. The issue linked here leads to lot of resources for getting up and running.

termux/termux-packages/issues/715

Closing this issue as we do not have current plans for official support at this time.
