### ISSUE TITLE
No session alert issued upon new shell

### ISSUE THREAD

**Issue by dazzahome** [rapid7/metasploit-framework#10431]
## Steps to reproduce

How'd you do it?

created a payload via msfvenom, basic windows/meterpreter/reverse_tcp (or any payload nothing fancy)
no alert being created that a new session is opened

## Expected behavior

to see a new session created alert

Bot1533660696365 : [*] Meterpreter session 4 opened (1.1.1.1:7778 -> 2.2.2.2:5776) at 2018-08-07 15:30:07 -0400

## Current behavior

session is created but no alert is visible 

## System stuff

Metasploit version

doesnt work on metasploit v5.0.0-dev-ed1451d

was working on metasploit v5.0.0-dev-6175455

### OS
ubuntu 16.05

**Comment by Green-m** [comment]
see this https://github.com/rapid7/metasploit-framework/issues/10129

**Comment by jmartin-r7** [comment]
Closing as duplicate of #10129, can confirm something changed and reporting is inconsistent, investigation of source needs time.
