### ISSUE TITLE
Add mount, unmount commands

### ISSUE THREAD

**Issue by Auxilus** [rapid7/metasploit-framework#10447]
`mount` and `unmount` commands for especially windows meterpreter can be pretty handy in some cases to map the remote drives on the fly without opening a shell channel.

example : `mount J \\path\to\drive`

**Comment by jmartin-r7** [comment]
Where would you expect this to be mounted?  Windows has it's own syntax for this type of behavior which should already be available using a command shell. [`net use e: \\usrsvr002\smithmark`](https://www.lifewire.com/net-use-command-2618096)

**Comment by wvu-r7** [comment]
It should be mounted locally for this to be of any use, IMHO. Mounting on the target, even if natively implemented in Meterpreter, doesn't gain us more than slightly improved usability.

**Comment by wvu-r7** [comment]
I would add that if this hypothetical `mount` command supported other platforms, it would be more useful to me. Meterpreter is about abstraction just as much as it is about usability.

**Comment by Auxilus** [comment]
is `rex/post/meterpreter/ui/console/command_dispatcher/core.rb` correct file to add these commands?

**Comment by ccondon-r7** [comment]
Hey y'all, I'm gonna close this for now, but it'll still be discoverable as an enhancement suggestion! Thanks much!
