### ISSUE TITLE
Metasploit crashing 90% of the time on start

### ISSUE THREAD

**Issue by purpl3-f0x** [rapid7/metasploit-framework#10453]
## Steps to reproduce

How'd you do it?

1. msfconsole
2. msfvenom

## Expected behavior

Initial startup of the two programs.

## Current behavior

Roughly 7-12 times when trying to start msfconsole or msfvenom, it crashes with this message:
![image](https://user-images.githubusercontent.com/42351007/44042285-e23fa792-9eed-11e8-8ba3-860ab83090cd.png)

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
None of the above; this was preinstalled on a VM I got from Offensive Security for the PWK course.

### OS

What OS are you running Metasploit on?
Kali Linux Rolling 2017.

**Comment by Green-m** [comment]
Maybe not enough memory, try increasing it.
If not, please post more detail and log.

**Comment by purpl3-f0x** [comment]
This VM has 8 GB of ram, and this happens even if MSF is the only thing running. I'm responding from work so I'll try to remember to get some logs when I get home.

**Comment by purpl3-f0x** [comment]
So after finally fixing the apt-get update issues with my Kali distro, and updating my msfconsole to the newest version, the issue seems to have vanished.
