### ISSUE TITLE
 Can't Run msfdb or msfupdate

### ISSUE THREAD

**Issue by leiferdjango** [rapid7/metasploit-framework#10495]
When I try to Run msfdb or msfupdate I get this error:

Screenshot Attached
![error-metaesploit](https://user-images.githubusercontent.com/42446502/44361651-5c356e80-a473-11e8-8706-2584f2fb18ce.png)

What should I do to solve it?

**Comment by RootUp** [comment]
I am not sure, will this help but please run below commands :  
`sudo bash /opt/metasploit-framework/ctlscript.sh restart` 

Then open `msfconsole` once launch run `msfupdate` inside `msf>`

**Comment by leiferdjango** [comment]
Thanks @RootUp for answer so soon

I did that but I cant find "ctlscript.sh" 

Screenshot Attached

![error-metasploit](https://user-images.githubusercontent.com/42446502/44366845-06c18780-a49c-11e8-8fce-d0f2b554c3cd.png)

**Comment by jmartin-r7** [comment]
This is likely an user ruby environment corrupting the path used with an omnibus based install.  If you installed form the nightly installer, the build includes an embedded ruby that needs to be found first in the path during execution of exported commands like `msfdb` and `msfupdate`.  Looking at the output `/usr/local/lib/site_ruby` is being found first.

This is not a bug in framework or the installer it is simply a user environment configuration issue.
