### ISSUE TITLE
PowerShell extension fails without PowerShell v2.0 installed on victim

### ISSUE THREAD

**Issue by smashery** [rapid7/metasploit-framework#10506]
## Steps to reproduce

On a fully-patched Windows 10 machine with the "Windows PowerShell v2.0" feature disabled:

1. Get a meterpreter shell on the system (tested with `windows/meterpreter_reverse_tcp`)
2. Load the PowerShell extension (or alternatively, include it in the initial stageless payload - behaviour was observed in both situations)
3. Run any command

## Expected behavior

Fall back to an available version of PowerShell

## Current behavior

I receive the following error on any command:

```
meterpreter > load powershell 
Loading extension powershell...Success.
meterpreter > powershell_shell 
PS > $a = 4
[-] core_channel_write: Operation failed: 2148734468
```

Attaching to the meterpreter process with a debugger, and breaking on first-chance CLR exceptions gives the following error as soon as a command is run:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Management.Automation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'`

### Metasploit version

5.0.0-dev-219668caae

### I installed Metasploit with:
- Source install (Ruby version 2.5.1p57)

### OS

`Linux Hackbox 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by sempervictus** [comment]
Maybe having a mono-built static ext would be easier, and avoid the constant hooks they keep putting into the native stuff.

**Comment by ccondon-r7** [comment]
I assume this is still an issue?

**Comment by germanh2** [comment]
Hello, I am working in some lab environments. I was able load powershell through meterpreter, however, the powershell_import returned the error "powershell_execute: Operation failed: The handle is invalid." Any updates on this issue?
