### ISSUE TITLE
Post interrupted by the console user

### ISSUE THREAD

**Issue by Roganced** [rapid7/metasploit-framework#10512]
Hello. I try to write gather module.
`::File.open(File.join(logs, 'gather', "info.txt"), "w") do |fd|
 
fd.puts(cmd_exec("cmd.exe /c systeminfo"))
  end`
But it only works from the second launch.
How can I add a delay... Sleep(10) for example?

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/issues/10465#issuecomment-414017359

Please use GitHub for bug reports, not programming help. Ask us on IRC.

That said, try what you said: `sleep(10)` is valid Ruby. You're already on the right track, presumably.
