### ISSUE TITLE
Error running command in msf

### ISSUE THREAD

**Issue by mxkxx** [rapid7/metasploit-framework#10511]
## Steps to reproduce

How'd you do it?

I was testing a payload on my cell phone (Android) and when i tried to upload a file i got an error message

[-] Error running command upload: Errno::ENOENT No such file or directory @ rb_file_s_stat

## Expected behavior

Meterpreter should upload the file

What should happen?

Metasploit should have uploaded the file

## Current behavior

It didnt upload the file. I got this error message instead

[-] Error running command upload: Errno::ENOENT No such file or directory @ rb_file_s_stat

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

## System stuff

¿?

### Metasploit version

Framework: 4.16.15-dev
Console  : 4.16.15-dev

### I installed Metasploit with:

- [ ] Kali package via apt

### OS

Debian 9, Kali

**Comment by wvu-r7** [comment]
Are you sure the file exists at the path you provided?
