### ISSUE TITLE
Uninstall Metasploit completely

### ISSUE THREAD

**Issue by Funeoz** [rapid7/metasploit-framework#10535]
I wanted to remove and reinstall Metasploit completely because I messed up with it.
But I couldn't find the uninstall script like this doc said : https://metasploit.help.rapid7.com/docs/uninstalling-metasploit . 
So I removed two folders at : 
`/home/.msf4` and `/opt/metasploit-framework`. 

So I tried to reinstall it with nightly installers : 
`curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall`

It returns me that that blocks me : 
`chmod 755 msfinstall && \ ./msfinstall % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 5525 100 5525 0 0 12672 0 --:--:-- --:--:-- --:--:-- 12672 Switching to root user to update the package Checking for and installing update.. Reading packets list... Done Building dependencies tree..
Reading state information... Done metasploit-framework is already the latest version (4.17.0+20180815103558.git.3.27bab54~1rapid7-1).`

So I'm blocked.

### Metasploit version
4.17.6-dev

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly)
- [] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Ubuntu

**Comment by wvu-r7** [comment]
```
sudo apt remove metasploit-framework
```

I have a preference for `purge`, but you can play it safe.

**Comment by Funeoz** [comment]
Thank you for that. So there's no more uninstall script for Linux because I searched it in all the folders of metasploit and couldn't find it.

**Comment by wvu-r7** [comment]
It's installed as a package, so it's managed by your package manager.

**Comment by ashu123-design** [comment]
I partially installed metasploit framework and exit.
Now I'm not able to delete it or install it.
Any solution

**Comment by reghenderson** [comment]
Same for me, I'm on windows
