### ISSUE TITLE
Helix

### ISSUE THREAD

**Issue by necrose99** [rapid7/metasploit-framework#10562]
DESCRIPTION="Embed Rust in your Ruby"
HOMEPAGE="https://usehelix.com"

allows Ruby to use rust or etc.. 

for some the rust fan boys might be useful in making payload modules and or making for faster rails.. 

nicety of rust for me is , if Metasploit is gening payloads can be compiled for lots of juicey targets.. 

might make the rust fan boys  mildy happier.. 

but with **cross**/**xargo** one can compile for 
all kinds of cell phones.. pc's windows' Linux etc.. targets...   Watering hole "Free" WIFI hot spot anyone... 
or even camera's... 
end of the day anything that helps for Better POWNAGE wins... 
being able to do much like GO-lang's gox while at it.. > have m'preter bins for all targets

**Comment by sempervictus** [comment]
Interesting. Noted, thank you.

**Comment by necrose99** [comment]
also packaged helix and submitted pull for Gentoo Rust overlay.  so @Pentoo can just add overlay for Gentoo Rust..  or a minimal Gentoo  chroot , emerge rpm layman git ... 

else can ebuild helix*.ebuild  rpm { else ebuid *.ebuild if only version , else need to cut/paste ver in.}
/var/tmp/portage/dev-ruby/helix/RPM..... dirs can scrape 
rpm  & rpm-spec and rpmspec to deb via a number of tools ...  alien if care to move to Kahli etc.  for testing purposes.   https://bitbucket.org/gdraheim/spec2deb

**Comment by necrose99** [comment]
https://github.com/artichoke/artichoke might be better since helix has been surplanted.. 

its the full blown ruby client , including WASM support.. wonders what  for msf payloads...
