### ISSUE TITLE
RPC API module.search is significantly slower than msfconsole's search command

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#10586]
## The Problem

The search command on msfconsole almost immediately shows the results, but when you search for the same thing using MsfRPC, it's significantly slower. The following demonstrates:

Search command from msfconsole:

![search_in_msfconsole](https://user-images.githubusercontent.com/1170914/45044960-37c2c000-b037-11e8-9456-21551859dd55.gif)

Search API from RPC:

![search_in_rpc](https://user-images.githubusercontent.com/1170914/45045062-853f2d00-b037-11e8-9203-0e31d26a49e5.gif)

As you can see, the performance difference is huge.

## Expected Behavior

The response time in RPC should be almost as quickly as msfconsole.

**Comment by timwr** [comment]
I guess only the search in msfconsole is using the cache:
e.g https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/modules.rb#L395
as opposed to:
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/rpc/v10/rpc_module.rb#L175

**Comment by dwelch-r7** [comment]
This was resolved with this PR #13998
