### ISSUE TITLE
something wrong using meterpreter?

### ISSUE THREAD

**Issue by leiferdjango** [rapid7/metasploit-framework#10588]
Hello guys! I need some help here, I think maybe this is probably a bug or Im just doing something wrong
 
When I start a session using meterpreter I upload a file with the name "comprometido.txt" from my Linux/VirtualPC to my Windows/Host to C:/  but when I go to my host and search for, isn't there, but as you see in the following image, is it in C:/ 

![path-2](https://user-images.githubusercontent.com/42446502/45076058-0689d480-b0b7-11e8-9e52-eb8489a6b025.png)

![path-3](https://user-images.githubusercontent.com/42446502/45076379-04744580-b0b8-11e8-85ba-c3796d7d5f04.png)

![path-1](https://user-images.githubusercontent.com/42446502/45075476-3cc65480-b0b5-11e8-8fc1-9a3eebefe443.png)

Then I upload the same file to the path C:/users/user/Desktop in my windows/host and now appears, as you can see the permissions are the same, and hidden files folders option is enable on windows, so why this is happening?

![path-4](https://user-images.githubusercontent.com/42446502/45076247-aba4ad00-b0b7-11e8-8f0a-9f0eddfb5971.png)

**Comment by timwr** [comment]
What user is meterpreter running as and what user are you viewing the file as?
E.g what's `meterpreter > getuid`?
You might need to migrate to another user/system.

**Comment by leiferdjango** [comment]
@timwr thanks for answer me so soon

How I do to migrate to another user?

**Comment by timwr** [comment]
`meterpreter > migrate`.
I feel like this is more technical support rather than an issue with metasploit.
It might be easier to help you if you join our IRC channel or slack group (info at metasploit.com).

**Comment by leiferdjango** [comment]
Sorry but i cant find anything about migrate user, just migrate process so, I still confusing about what to do in this case
