### ISSUE TITLE
NIghtly build not working on debian 9

### ISSUE THREAD

**Issue by synack420** [rapid7/metasploit-framework#10615]
## Steps to reproduce

Used the nightly installer as I always do, results below:

root@siege2:/etc/apt/sources.list.d# uname -a
Linux siege2 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux

## Expected behavior
Expected to install
What should happen?
Full install with no errors
## Current behavior
Will not install
What happens instead?

root@siege2:/etc/apt/sources.list.d# curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
>   chmod 755 msfinstall && \
>   ./msfinstall
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5525  100  5525    0     0  44110      0 --:--:-- --:--:-- --:--:-- 44200
Updating package cache..E: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/main/binary-amd64/Packages.gz  Writing more data than expected (419 > 418)
   Hashes of expected file:
    - Filesize:418 [weak]
    - SHA256:5c73ef95796b138af80d26dc2970ea69de72531f860e87f3e2da796a293ccc5f
    - SHA1:3e6174e9780fd4cf79d2d0e0c19b056cc1b5dd4c [weak]
    - MD5Sum:9f5759bb567a9e337a54c1873a266e47 [weak]
   Release file created at: Sun, 09 Sep 2018 10:23:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree
Reading state information... Done
N: Ignoring file 'msfinstall' in directory '/etc/apt/sources.list.d/' as it has no filename extension
E: Unable to locate package metasploit-framework

## System stuff
root@siege2:/etc/apt/sources.list.d# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [x ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
"Debian GNU/Linux 9 (stretch)"

**Comment by busterb** [comment]
As of 12 hours ago, we restored some incorrect settings on our CDN. It should be working now.

**Comment by synack420** [comment]
Nightly builds seem to be working smoothly now, thanks guys.
