### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by shaikhshaharukh** [rapid7/metasploit-framework#10613]
Termux .. android on Mobile

Ignoring file 'list.lis' in directory '/data/data/com.termux/files/usr/etc/apt/sources.list.d/' as it has an invalid filename extension

**Comment by wvu-r7** [comment]
Please talk to your package maintainer. We do not manage Termux. @Auxilus?

**Comment by shaikhshaharukh** [comment]
Thanks
