### ISSUE TITLE
DESKTIO DEAD KALI LINUX 2018.3

### ISSUE THREAD

**Issue by HcKdMicky7979** [rapid7/metasploit-framework#10646]
I've just installed kali linux 2018.3, and i had ran apt-get update && apt-get full-upgrade, and then i launched reboot. but then when i login into the OS, it takes me to an unresponsive desktop. i can't drag into it nothing, and if i do right-click it gaves me only three choices, (Change Wallpapaer; Monitor settings and settings).
and when i open terminal and do "mv /root/Example /root/Desktop, it gaves me no problem, but then there's nothing on Desktop, only if i type "ls".

**Comment by h00die** [comment]
Contact kali, this is metasploit. They have an irc channel that may be able to assist.
