### ISSUE TITLE
nsc.xml missing 

### ISSUE THREAD

**Issue by mohamed159753** [rapid7/metasploit-framework#10657]
why nexpose in telling me nsc.xml is missing and exit with code 0

ERROR] The nsc.xml configuration file was not found, but the database is available. Contact Technical Support.
2018-09-16T15:16:25 [ERROR] A critical error occured during initialization
2018-09-16T15:16:25 [ERROR] Error during server initialization.
2018-09-16T15:16:25 [INFO] Shutting down immediately
2018-09-16T15:16:26 [WARN] Error stopping quartz schedulers.
2018-09-16T15:16:26 [INFO] removing scheduled risk and history updater jobs
2018-09-16T15:16:26 [INFO] Shutting down config manager
2018-09-16T15:16:26 [INFO] Shutting down crypto system
2018-09-16T15:16:26 [WARN] Error shutting down database.
2018-09-16T15:16:26 [INFO] Shutting down command console
NeXpose security console exited with code 0

please I need your help 
*** I install nexpose from the official site

**Comment by bcoles** [comment]
You'll probably have better luck reaching out to the Nexpose support team for support with Nexpose.

* https://www.rapid7.com/for-customers/
* https://nexpose.help.rapid7.com/docs/support-technical-support-and-customer-care

The Metasploit issue tracker is for tracking issues with Metasploit.

**Comment by nibiwodong** [comment]
> 为什么nexpose告诉我nsc.xml丢失并退出代码0
> 
> 错误]找不到nsc.xml配置文件，但数据库可用。联系技术支持。
> 2018-09-16T15：16：25 [ERROR]初始化期间发生严重错误
> 2018-09-16T15：16：25 [ERROR]服务器初始化期间出错。
> 2018-09-16T15：16：25 [INFO]立即关闭
> 2018-09-16T15：16：26 [WARN]停止石英调度程序时出错。
> 2018-09-16T15：16：26 [INFO]删除计划的风险和历史记录更新程序作业
> 2018-09-16T15：16：26 [INFO]关闭配置管理器
> 2018-09-16T15：16：26 [INFO]关闭加密system 
> 2018-09-16T15：16：26 [WARN]关闭数据库时出错。
> 2018-09-16T15：16：26 [INFO]关闭命令控制台
> NeXpose安全控制台退出，代码为0
> 
> 我需要你的帮助
> ***我从官方网站安装nexpose

Hi, bro! Do you know the reason about nsc.xml missing?

**Comment by fbarriosCL** [comment]
Hello @nibiwodong  , in my case I solved it installing postgres,  ```apt-get -y install postgresql postgresql-contrib```

**Comment by 7ika4iisnap-hub** [comment]
> why nexpose in telling me nsc.xml is missing and exit with code 0
> 
> ERROR] The nsc.xml configuration file was not found, but the database is available. Contact Technical Support. 2018-09-16T15:16:25 [ERROR] A critical error occured during initialization 2018-09-16T15:16:25 [ERROR] Error during server initialization. 2018-09-16T15:16:25 [INFO] Shutting down immediately 2018-09-16T15:16:26 [WARN] Error stopping quartz schedulers. 2018-09-16T15:16:26 [INFO] removing scheduled risk and history updater jobs 2018-09-16T15:16:26 [INFO] Shutting down config manager 2018-09-16T15:16:26 [INFO] Shutting down crypto system 2018-09-16T15:16:26 [WARN] Error shutting down database. 2018-09-16T15:16:26 [INFO] Shutting down command console NeXpose security console exited with code 0
> 
> please I need your help *** I install nexpose from the official site

hello friend. i also have faced the same problem. can you please share the solution with us here.
Thank you.
