### ISSUE TITLE
Android Meterpreter "Shell" Command Giving error

### ISSUE THREAD

**Issue by rohitcoder** [rapid7/metasploit-framework#10678]
Everything is working properly but whenever i run "shell" command i throws error

`meterpreter > shell`
```
[-] Error running command shell: NameError undefined local variable or method `comspec' for #<Rex::Post::Meterpreter::Ui::Console::CommandDispatcher::Stdapi::Sys:0x007ff270dcd920>
Did you mean?  Complex
```

Any idea? How to solve this?

Other commands are working perfectly.

**Comment by wvu-r7** [comment]
It's fixed. Sorry for not noticing this sooner.

**Comment by rohitcoder** [comment]
I updated everything through "msfupdate" still i am getting this error. Any idea how to solve this?

**Comment by wvu-r7** [comment]
How did you install Metasploit? If you're using the package we provide, you should get it in a day. Otherwise you'll have to wait a week. You can apply the patch in #10685 if you're ambitious. It was simply a matter of using the old variable `path`.

**Comment by wvu-r7** [comment]
How did you install Metasploit? If you're using the package we provide, you should get it in a day. Otherwise you'll have to wait a week.

You can apply the patch in #10685 if you're ambitious. It was simply a matter of using the old variable `path`. Git users can update immediately.

**Comment by wvu-r7** [comment]
@rohitcoder: I hope you got the fix!

**Comment by rohitcoder** [comment]
@wvu-r7  Ohh, Sorry for late Update!
I fixed my problem thanks 👍

**Comment by wvu-r7** [comment]
Great!

**Comment by BilalArfi** [comment]
Tell me how did fix it , please

**Comment by wvu-r7** [comment]
By updating.

**Comment by BilalArfi** [comment]
Thanks bro
