### ISSUE TITLE
Cmd_exec doesn't pass a space

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#10694]
Hello. I'm trying to pass NT SERVICE\\Local
but i get:
No parameter found for option SERVICE\Local!
and i trying to pass:
cmd.exe -a "/c netsh advfirewall firewall add rule name="test malware" dir=in protocol=TCP localport=445 action=allow" - Doesn't Work

cmd.exe -a "/c netsh advfirewall firewall add rule name="testmalware" dir=in protocol=TCP localport=445 action=allow" - Work.

Why?

**Comment by bcoles** [comment]
It would be much easier to understand what you're trying to achieve if you provided the code you're using.

Like the last issue you posted, I can only assume you're executing within a module context.

Additionally, some output would be useful. A little more than "Doesn't work".

**Comment by Koraman** [comment]
`cmd_exec("cmd.exe /c netsh advfirewall firewall add rule name="test malware" dir=in protocol=TCP localport=445 action=allow")`
But it does not add a rule to firewall, because **"test malware"** has a space.
When i **remove space** and execute, **it is working**:
`cmd_exec("cmd.exe /c netsh advfirewall firewall add rule name="testmalware" dir=in protocol=TCP localport=445 action=allow")`

**Comment by bcoles** [comment]
I'm surprised that works at all. Your quotes `"` are mismatched.

Perhaps this will help:

```
modules/post/windows/recon/outbound_ports.rb:158:    output = cmd_exec('netsh',' advfirewall firewall add rule name="All ICMP v4" dir=in action=allow protocol=icmpv4:any,any')
modules/post/windows/manage/portproxy.rb:113:      cmd_exec("netsh","advfirewall firewall add rule name=\"Windows Service\" dir=in protocol=TCP action=allow localport=\"#{datastore['LOCAL_PORT']}\"")
```

**Comment by Koraman** [comment]
That works because i use two quotes (""test malware"").
A shield of this type \"Windows Service\" helped me.
Thank you very much!
