### ISSUE TITLE
Can you make Meterpreter shell for Windows support "cd C:\Users\"

### ISSUE THREAD

**Issue by pich4ya** [rapid7/metasploit-framework#10701]
## Steps to reproduce

meterpreter > cd C:\Users\
 > /
[-] stdapi_fs_chdir: Operation failed: The system cannot find the file specified.
meterpreter > cd C:\Users
[-] stdapi_fs_chdir: Operation failed: The system cannot find the file specified.

## Expected behavior

meterpreter > cd C:\Users\

and it should work.

## Current behavior

meterpreter > cd C:\Users
[-] stdapi_fs_chdir: Operation failed: The system cannot find the file specified.

### Metasploit version

Framework: 4.16.65-dev-d322148d8d6c6bf07b55d5769c6e720b40532c08
Console  : 4.16.65-dev-d322148d8d6c6bf07b55d5769c6e720b40532c08

### I installed Metasploit with:
- MacOS brew

### OS

MacOS

**Comment by wvu-r7** [comment]
Quote the string. It's an approximation of a shell using `Shellwords`.

```
cd 'C:\Users'
```

**Comment by anuraggawande** [comment]
@wvu-r7  is correct. Command should be in single quote. 

> cd C:\Windows

**Comment by chamodh1234** [comment]
> Quote the string. It's an approximation of a shell using `Shellwords`.
> 
> ```
> cd 'C:\Users'
> ```

This is correct really helpful for me. Appreciate.❤️

**Comment by Mat-log22** [comment]
cd "c:\users"
