### ISSUE TITLE
meterpreter session  closed. reason died

### ISSUE THREAD

**Issue by Ammar-backend** [rapid7/metasploit-framework#10757]
## Steps to reproduce

How'd you do it?
![image](https://user-images.githubusercontent.com/43895137/46570327-5aa80300-c95a-11e8-8aad-bea032bbe464.png)

## Expected behavior

What should happen?

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version
metasploit framework latest version last version 2018 4.17

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Kali Linux 64 Bit last virsion

**Comment by h00die** [comment]
Please provide additional details.
What OS is the target, is there AV, what payload are you using, what version of php? More details can better help narrow down where the problem may be.

**Comment by Ammar-backend** [comment]
the target is windwos x86 .there's no an AV . virsion php 7.2

**Comment by sozib03** [comment]
I am also facing a similar type of problem. the payload handler is not starting, and after giving one command in meterpreter, it's session is dying. What should I do? Need some help

**Comment by busterb** [comment]
There's just not enough here to really help, sorry.
