### ISSUE TITLE
ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A/usr/share/ruby/openssl/ssl.rb:280:in `accept'

### ISSUE THREAD

**Issue by akashsarpate** [rapid7/metasploit-framework#10752]
I am trying to run foreman install with chef plugin getting below error:

  foreman-installer \
  --enable-foreman-plugin-chef \
  --enable-foreman-plugin-tasks \
  --enable-foreman-proxy-plugin-chef \
  --foreman-proxy-plugin-chef-server-url="https://101.1.2.3/organizations/short_name" \
  --foreman-proxy-plugin-chef-client-name="client_name" \
  --foreman-proxy-plugin-chef-private-key="/etc/client.pem" \
  --no-enable-puppet \
  --foreman-server-ssl-crl=""

Error:-
E, [2018-10-05T07:48:04.878022 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:05.069863 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:09.061190 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: certificate verify failed
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:09.642194 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: certificate verify failed
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:10.499204 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:10.690788 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:11.081246 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: certificate verify failed
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:17.866047 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:18.057435 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv3 read client certificate A
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'
E, [2018-10-05T07:48:44.800239 ] ERROR -- : OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=error: certificate verify failed
        /usr/share/ruby/openssl/ssl.rb:280:in `accept'

This is on Oracle Linus 7.4

Can you please help?

**Comment by busterb** [comment]
I think you have the wrong project!
