### ISSUE TITLE
Android - Persistent backdoor with a backdoored app [Beginner question]

### ISSUE THREAD

**Issue by L-index** [rapid7/metasploit-framework#10764]
Hi.
I have backdoored an apk with msfvenom (it's a pong game).

Everything is good, the backdoor work but i try to make is persistent.

I've followed this tutorial:
https://null-byte.wonderhowto.com/how-to/create-persistent-back-door-android-using-kali-linux-0161280/
and changed the line: com.metasploit.stage/.MainActivity for my app.

Problem: Now the game is opening all the 20s.

I want to make it persistant and don't open again the app!
Sorry for my english.

Update: With hide_icon_app the sessions still open, the app don't start again but if the session dies there's no way back to reopen another session.

**Comment by ccondon-r7** [comment]
Hi there! This isn't a bug in Metasploit, so we're closing it. Slack is a better place to ask questions like this—feel free to join our community there: https://metasploit.com/slack

**Comment by karansharmahr** [comment]
Hey bro how had you edited the app can u tell me
