### ISSUE TITLE
Not an issue, just an info

### ISSUE THREAD

**Issue by iNoSec** [rapid7/metasploit-framework#10774]
Hi all metasploit users and dev!!!

Just a stupid question but how many times that take to have new feature like the evasion module in our public editon of msf??

I explain more clearly if need it, so the evasion module is  available in msf5 but not in the last nighly upadte of msf 4.17.16-dev- , so just to know how many times in general thats came out??

Thanks for all and sorry for this stupid question

**Comment by ccondon-r7** [comment]
Hi @iNoSec, since this is not an issue it's better if you ask on Slack or IRC instead (https://metasploit.com/slack). Metasploit's engineering leads believe that MSF 5 could be shipping in Kali by the end of the year, but there may need to be some flexibility there.

**Comment by iNoSec** [comment]
im not on kali and that wasnt my question ;) but im going on IRC so
