### ISSUE TITLE
Various database errors, db_nmap cannot execute due to lack of permissions

### ISSUE THREAD

**Issue by True-Demon** [rapid7/metasploit-framework#10799]
## Steps to reproduce
1. Perform a fresh installation of metasploit via the nightly-installer for any RPM system (tested on Fedora 28)
2. Assuming database setup works as intended (I had to manually create database entries and user roles) run msfconsole as the local user
3. Attempt a `db_nmap -sS w.x.y.z` and you are met with "you requested a scan type which requires root privileges" due to lack of socket permissions
4. Attempting to run msfconsole as root results in database connection errors because `msfdb init` does not allow root setup. 

## Expected behavior
db_nmap should work or msfconsole should connect to the msfdb successfully when run as root

## Current behavior
running msfconsole as the local user results in db_nmap command throwing a socket permission error
running msfconsole as the root user results in db_connect errors due to lack of roles, lack of postgres permissions
running `msfdb init` as root at the time of installation fails because you are not supposed to initialize the database as root

## System stuff
`uname -a` output:
Linux abyss 4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Metasploit version
Tested on latest 4.17 nightly rpm install and 5.0.0-dev-c1f5540e16

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [x] Omnibus installer (nightly)
- [x] Source install (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux])

### OS

Fedora 28

Ultimately what I am looking for is the proper solution to the issue according to the dev team's intent. On various debian-based releases, the nightly installer works just fine, as does installing a simple development branch straight from the git repo. I never experienced these issues running msfconsole as root from these systems, but my first foray into Fedora immediately caused all kinds of problems. 

Assuming db_nmap is not intended to be run from a local user because they don't have socket permissions by default, it should be expected that msfconsole and the database gets set up for use by the root user.

On the other hand, if the intent is to avoid msfconsole needing root permissions to run, there needs to be some way of elevating these permissions within msfconsole itself. I don't see any way it can be both.

Ordinarily, I can troubleshoot these issues myself, but since this broke on a fresh install of Fedora, I feel it needs to be addressed in the installer scripts. @ me if further details are needed.

**Comment by jrobles-r7** [comment]
Does setting the capabilities on nmap work?
`/usr/sbin/setcap cap_net_raw,cap_net_bind_service=+eip $(which nmap)`
