### ISSUE TITLE
Can't find new evasion module when update from osx.metasploit.com

### ISSUE THREAD

**Issue by evil7** [rapid7/metasploit-framework#10791]
## Steps to reproduce

How'd you do it?

1. `msfupdate` and `msfconsole` can't find the new evasion module.
2. add a git with this repo, try to pull the new commits and rebuild. can't find it too.

### Metasploit version

`metasploit v4.17.17-dev-9436821f344e217e9b394d12fb956fd70956c2af`

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

MacOS 10.14

## My question

Is that's module only in developing now?

How can I use the module or display it now?

Which framework version should I use to?

pls help. thx

**Comment by Green-m** [comment]
Oh, my friend, I know your name on Weibo, thanks for following Metasploit new features! 

Actually, `evasion` module is only valid for `msf5` version, that means you have to install it by `source install`.

Please try 
`git clone https://github.com/rapid7/metasploit-framework.git
cd metasploit-framework
bundle install 
`
Enjoy!

**Comment by evil7** [comment]
OK. now I knew that I shouldn't install msf with `brew` or pkg file to fast-install.
rebuild from sources now.
thx for reply.
and thx u know me hahaha XD

// no-reply

**Comment by iNoSec** [comment]
i can see we need some "friends" here to have the answer... I ask the same thing and i have an answer that say go on irc for this type of question...

Nice guys...
