### ISSUE TITLE
There is no evasion module

### ISSUE THREAD

**Issue by 1982Dmitry** [rapid7/metasploit-framework#10801]
OS: Ubuntu 18.04
Metasploit: v4.17.17-dev

I'm trying to use new evasion module.
`use evasion/windows/windows_defender_exe`

but I getting following error:
`[-] Failed to load module: evasion/windows/windows_defender_exe
`

What am I doing incorrectly?

**Comment by busterb** [comment]
See #10791 , you'll need to run from the 5.x branch from source for now.
