### ISSUE TITLE
Get GUI from meterpreter session

### ISSUE THREAD

**Issue by H5a337230** [rapid7/metasploit-framework#10806]
Hello
I have access to my victim`s system using meterpreter/reverse_https and also getsystem works on it.
What i want is that get GUI session to victim.

I used VNC but its really slow(me and my victim are not in same network and i have session over internet) also using RDP sounds crazy CUZ the created user will appear to whom using that system and if i login, the user will throw out.

Is there anyway to make RDP DO NOT doing this and also make created user invisible to others?

**Comment by OJ** [comment]
Please use Slack or IRC for help. Github is for bug reports.
