### ISSUE TITLE
docker script run error 

### ISSUE THREAD

**Issue by blue-bird1** [rapid7/metasploit-framework#10809]
## Steps to reproduce
How'd you do it?

1. git clone https://github.com/rapid7/metasploit-framework
2. .cd metasploit-framework && ./docker/bin/msfconsole 

## Expected behavior
in docer run msf 

## Current behavior
```
Step 23/23 : CMD ["./msfconsole", "-r", "docker/msfconsole.rc"]
 ---> Running in caf3c765b09b
Removing intermediate container caf3c765b09b
 ---> b5970cb36248
Successfully built b5970cb36248
Successfully tagged metasploit:dev
WARNING: Image for service ms was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Rails Error: Unable to access log file. Please ensure that /home/msf/.msf4/logs/production.log exists and is writable (ie, make it writable for userand group: chmod 0664 /home/msf/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Traceback (most recent call last):ork console...-
        16: from ./msfconsole:49:in `<main>'
        15: from /usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        14: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        13: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        12: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
        11: from /usr/src/metasploit-framework/lib/msf/ui/console/driver.rb:82:in `initialize'
        10: from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:74:in `create'
         9: from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:111:in `simplify'
         8: from /usr/src/metasploit-framework/lib/msf/base/config.rb:216:in `init'
         7: from /usr/src/metasploit-framework/lib/msf/base/config.rb:393:in `init'
         6: from /usr/local/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
         5: from /usr/local/lib/ruby/2.5.0/fileutils.rb:193:in `each'
         4: from /usr/local/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
         3: from /usr/local/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
         2: from /usr/local/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
         1: from /usr/local/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
/usr/local/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': Permission denied @ dir_s_mkdir - /home/msf/.msf4/logs (Errno::EACCES)
```
## System stuff
`Linux 4.4.0-117-generic #141-Ubuntu  x86_64 GNU/Linux`
`Docker version 18.06.1-ce, build e68fc7a`

### Metasploit version
`feb3cfe5ab61f9051e9a8f23ae253301fc0b34bd automatic module_metadata_base.json update`

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x ] Source install (please specify ruby version)
docker run, so I no know
### OS
linux  debian

**Comment by FireFart** [comment]
I assume you are running it as root. You can pass the `-u root` parameter to docker or docker-compose to run the container as root. The container runs a low privileged user and `~/.msf4` is mounted in the container. As your home directory is owned by root the container user can not write to it.

**Comment by blue-bird1** [comment]
> I assume you are running it as root. You can pass the `-u root` parameter to docker or docker-compose to run the container as root. The container runs a low privileged user and `~/.msf4` is mounted in the container. As your home directory is owned by root the container user can not write to it.

You are right.I think this should be added to the documentation?

**Comment by FireFart** [comment]
I'm currently working on a workaround so it will work out of the box

**Comment by FireFart** [comment]
@blue-bird1 the new version is now in master. Can you please try again if it now works for you?

**Comment by blue-bird1** [comment]
it work
