### ISSUE TITLE
Install MS from the source

### ISSUE THREAD

**Issue by 1982Dmitry** [rapid7/metasploit-framework#10811]
OS: Kali

I want to install MS from the source and use new EVASION module.
What I did:
```
git clone https://github.com/rapid7/metasploit-framework.git
cd metasploit-framework
bundle install 
```

but I'm getting following error:
`An error occurred while installing nokogiri (1.8.5), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.5'` succeeds before bundling.
`

I think it's related to ruby version or something.
What should I do? how can I install MS from the source on Kali.2018.3

**Comment by Green-m** [comment]
You need to install some dependencies for msf5, check https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
