### ISSUE TITLE
Tab completion with a single result doesn't use it

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#10850]
I've been noticing this for some weeks to months now.

```
msf5 auxiliary(scanner/ssh/libssh_auth_bypass) > sessions
sessions
msf5 auxiliary(scanner/ssh/libssh_auth_bypass) > sessions
```

This feels like a regression. It's incorrect behavior as far as most shells go.

Do you know anything about this, @Green-m?

**Comment by Green-m** [comment]
![tabs](https://user-images.githubusercontent.com/22535454/47340638-7426aa00-d6d1-11e8-9271-f8fa9fe1de37.gif)
Seems good on my machine, or did I misunderstand?

**Comment by timwr** [comment]
If it helps I can't reproduce this either.

**Comment by wvu-r7** [comment]
It is working now. Seems like some sort of Heisenbug. I'll reopen if I can produce repro for it. Thanks!

**Comment by wvu-r7** [comment]
For the record, it's this code that should do the right thing:

https://github.com/rapid7/metasploit-framework/blob/9b01f3deaf9a8f5c6b88ffd6a38f748ab816a5cf/lib/rex/ui/text/dispatcher_shell.rb#L408

**Comment by wvu-r7** [comment]
I still have this problem today. It's sporadic, and I can't figure it out, so I'm reopening this so we can track it in the future.

**Comment by wvu-r7** [comment]
This is still an issue, and it is annoying the everliving shit out of me.

**Comment by bcoles** [comment]
Removing the stale label. I'm not sure if this is still an issue. Someone who isn't me should probably take a look at this. I nominate @wvu-r7

**Comment by timwr** [comment]
Closing this because I think it's fixed.
