### ISSUE TITLE
meterpreter reg command doesn't support REG_MULTI_SZ

### ISSUE THREAD

**Issue by Feb30th** [rapid7/metasploit-framework#10859]
## Steps to reproduce

1. get a meterpreter shell from vm
2. try to write reg with /t REG_MULTI_SZ, notice me successfully but got mojibake in registry

### OS && Version

OS: Linux centos 3.10.0-862.el7.x86_64
meterpreter: win7 enterprise x64 7601

**Comment by Green-m** [comment]
Consider `enable_unicode_encoding` to avoid mojibake?

**Comment by Feb30th** [comment]
> Consider `enable_unicode_encoding` to avoid mojibake?

Thx for your answer, I'm so sorry that it does't work, -_-!. I think maybe it not supported in stdapi level?

**Comment by Green-m** [comment]
Maybe it's non-printable string in the registry? 
Do all the keys have the same problem?

**Comment by busterb** [comment]
The problem looks to be here: https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/stdapi/server/sys/registry/registry.c#L463

We're not treating REG_MULTI_SZ as a string, but instead falling to the default binary data handling.

MULTI_SZ needs its own code path because it is a list of unicode strings, null-separated, terminated by an additional NULL wide character.

**Comment by busterb** [comment]
If this was implemented on the msf side, Metasploit will need to perform the string encoding in 'meterpreter_registry_setvaldata' and other places.

**Comment by Green-m** [comment]
Yep agree with you, @busterb! I was checking that code yesterday, trying to find something out, thanks for your review!

**Comment by OJ** [comment]
Is the plan to implement this directly into Meterpreter instead?

**Comment by Feb30th** [comment]
I hop this bug will be fixed ^_^

**Comment by Green-m** [comment]
@Feb30th @busterb 
I have submitted a PR to fix it in https://github.com/rapid7/metasploit-payloads/pull/311 , please check it out.

@OJ 
Did you mean that move the `reg` command to `core` command? I did not get you actually.

**Comment by Feb30th** [comment]
> @Feb30th @busterb
> I have submitted a PR to fix it in [rapid7/metasploit-payloads#311](https://github.com/rapid7/metasploit-payloads/pull/311) , please check it out.
> 
> @OJ
> Did you mean that move the `reg` command to `core` command? I did not get you actually.

Thx, can I got the fix with command "msfupdate" ?

**Comment by Feb30th** [comment]
> @Feb30th
> For now, the `msfupdate` would install the stable version of msf4, that means you may have to wait even several days after that PR merged. Sorry for the delay.

Understand，don't mind it.

**Comment by Feb30th** [comment]
> @Feb30th
> For now, the `msfupdate` would install the stable version of msf4, that means you may have to wait even several days after that PR merged. Sorry for the delay.

Understand，don't mind it.
