### ISSUE TITLE
Wiki broken link

### ISSUE THREAD

**Issue by lg188** [rapid7/metasploit-framework#10868]
There's a youtube link on https://github.com/rapid7/metasploit-framework/wiki/2018-Roadmap
it should be https://www.youtube.com/watch?v=hvuy6A-ie1g instead of https://www.youtube.com/edit?o=U&video_id=hvuy6A-ie1g which is a page only the owner can see.

**Comment by wvu-r7** [comment]
Thank you. It has been changed in https://github.com/rapid7/metasploit-framework/wiki/2018-Roadmap/82de3bad989929a964b1237b1485c859a0bdd009, and I have credited you for the report.
