### ISSUE TITLE
Limitation: Meterpreter treats file sizes as 32 bit (for purpose of "ls","upload","download")

### ISSUE THREAD

**Issue by manduc4** [rapid7/metasploit-framework#10871]
## Steps to reproduce

Both meterpreter x64 Linux and meterpreter python on Linux guest:
do a "ls" on a dir that contains large files.
On python it will give an error, on Linux it will show wrong file sizes (might me mod 2^32).

## Current behavior
File sizes are wrong during "ls", file up/download fails.
On python it will give an error, on Linux it will show wrong file sizes (might me mod 2^32).

### Metasploit version
Framework: 4.17.18-dev-
Console  : 4.17.18-dev-

### I installed Metasploit with:
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

Debian 9

**Comment by OJ** [comment]
This is definitely a problem. I'm mid-way through some work to fix this on the Meterps, because the size values are all DWORD instead of QWORD.

**Comment by timwr** [comment]
Fixed with https://github.com/rapid7/metasploit-framework/pull/11193
