### ISSUE TITLE
meterpreter run persistence error payloads vrs 1.3.52

### ISSUE THREAD

**Issue by heralexmcx** [rapid7/metasploit-framework#10885]
## Steps to reproduce
I am in a session with meterpreter and i try use "run persistence" and show this error: Error in script: Errno::ENOENT No such file or directory @ realpath_rec - /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/metasploit-payloads-1.3.52

I tried use the command "gem install metasploit-payloads -v 1.3.52" and "-v 1.3.53" and dont worked, help pls.

### I installed Metasploit with:
-  Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
kali linux

**Comment by busterb** [comment]
This looks like Kali Linux-related. I'd check the support forums for them. Thanks!

Also, Meterpreter scripts are not supported.
