### ISSUE TITLE
strange issue : windows/dllinject/* Payloads 

### ISSUE THREAD

**Issue by realoriginal** [rapid7/metasploit-framework#10941]
I crafted together a reflective DLL, which works perfectly fine with the `post/windows/manage/reflective_dll_injection`, runs and performs the function intended.

However, when using the same DLL (its x86 to match the stager), the host process crashes after the DLL is staged. Its quite strange, being that the example reflective_dll from Stephen Fewer works, & (and still crashes, but runs). Could this be a problem with my DLL (is there something different about the manage module and the stager that I need to add to my DLL?) or possibly the stager?

I saw a few previous issues mentioning this problem with Empire DLL's, yet could not find a fix for the issue.

I've used both the nightly Metasploit versions on the latest kali rolling, as well as the one provided by Kali Linux itself.

Appreciate the response!

**Comment by bwatters-r7** [comment]
That does seem odd.  Typically, when I get something like that, it is invariably because I have left some sort of dependency in there (often because I forget to statically link).  Is there any chance that could be it?

**Comment by OJ** [comment]
Any chance you could share it somehow? Or is it private? Hard to say what could be wrong. Strange that it works with the post module but not elsewhere. How are you invoking it at the moment? Are you setting it as a custom payload or something?

**Comment by ccondon-r7** [comment]
Hi there! We're closing this issue because it has not been active in more than a year. If you'd like to reopen it, however, feel free to do so.
