### ISSUE TITLE
No active DB -- Credential data will not be saved!

### ISSUE THREAD

**Issue by syrius01** [rapid7/metasploit-framework#10946]
How can I set a DB in msfconsole so the working credentials gets saved?

Module: modules/auxiliary/scanner/http/splunk_web_login

 [+] SUCCESSFUL LOGIN. 'admin' : ''
 [!] No active DB -- Credential data will not be saved!

**Comment by elogada** [comment]
Tried switcingh PostgreSQL on?
`````
/etc/init.d/postgresql start
`````
...then initialize the database straight up.
`````
msfdb init
`````
Should be done.

**Comment by haxpak** [comment]
having  the same issue
when trying smb login (auxillary/scanner/smb/smb_login)

the postgress is connected and working fine for rest of the other things

**Comment by pranavperfect** [comment]
Bump. Have been having this issue.

**Comment by stuff2600** [comment]
seeing this on telnet_login :(

**Comment by piffd0s** [comment]
just restart  msfconsole after you init the database
