### ISSUE TITLE
Additional Languages To Payload Output Formats

### ISSUE THREAD

**Issue by Genaro-Chris** [rapid7/metasploit-framework#10959]
There is the need to add more languages like Apple's Swift language and Google's Go language to payload output for compatibility on Apple's products and machines running the Go language. This addition will help for the payloads undetectability on some machines running this languages.

**Comment by ccondon-r7** [comment]
Hiya! We're closing this because it isn't an active bug, but it'll still be searchable as a feature/enhancement suggestion! Thanks for the idea—we still may look at it in the future.
