### ISSUE TITLE
Timestomp: set the MACE timestamps recursively on a directory isn't working on Windows

### ISSUE THREAD

**Issue by 4ntonch3** [rapid7/metasploit-framework#10955]
Metasploit :v4.17.24, OS: Ubuntu 18.10. 
I used timestomp (payload: windows/meterpreter/reverse_tcp) to a windows 10 x64, build 17134
The option -r (Set the MACE timestamps recursively on a directory) doesn't change any timestamps of files in a directory.
The list of commands and outputs is shown below:
1. ls
![image](https://user-images.githubusercontent.com/45002685/48420845-572f4500-e76c-11e8-82c6-af6d135eb3b1.png)
2. cd .. 
ls
![image](https://user-images.githubusercontent.com/45002685/48420226-01a66880-e76b-11e8-9686-b68eecd87c98.png)
3. timestomp Desktop -r
![image](https://user-images.githubusercontent.com/45002685/48420281-184cbf80-e76b-11e8-8f31-77d3e0bd7300.png)
4. cd Desktop
ls
![image](https://user-images.githubusercontent.com/45002685/48420372-50540280-e76b-11e8-9d95-4e6e058fc2f8.png)
5. timestomp shell3.exe -v
![image](https://user-images.githubusercontent.com/45002685/48420445-81ccce00-e76b-11e8-8a5f-31df9985921f.png)

Files' timestamps are expected to change. But, according to the results, timestamps of files didn't change, so this option isn't working.

This option also isn't working on Windows 7 x64, SP1:
1. ls
![image](https://user-images.githubusercontent.com/45002685/48421196-0ff58400-e76d-11e8-93b4-34a08e029f04.png)
2. cd .. 
ls
![image](https://user-images.githubusercontent.com/45002685/48421222-1d127300-e76d-11e8-8737-fe2ae0918b1a.png)
3. timestomp Desktop -r
![image](https://user-images.githubusercontent.com/45002685/48421280-36b3ba80-e76d-11e8-8b4b-51ac6c47ef30.png)
4. cd Desktop
ls
![image](https://user-images.githubusercontent.com/45002685/48421293-3ddac880-e76d-11e8-8b92-c21bb588fa97.png)
5. timestomp shell3.exe -v
![image](https://user-images.githubusercontent.com/45002685/48421327-4f23d500-e76d-11e8-9ffc-954ef1d1f8cd.png)

**Comment by busterb** [comment]
I suspect I might have broken this in 2017 when rewriting to avoid any GPL code. Hmm: https://github.com/rapid7/metasploit-payloads/pull/163
