### ISSUE TITLE
Add Windows Gather User History module

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#10979]
Add post module to collect [PSReadline](https://blogs.technet.microsoft.com/heyscriptingguy/2014/06/18/better-powershell-history-management-with-psreadline/) history, plus anything else that may be of interest (`*_history.txt`), in a similar manner to [Linux Gather User History](https://github.com/rapid7/metasploit-framework/tree/master/modules/post/linux/gather/enum_users_history.rb).

`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt`

* https://twitter.com/nikhil_mitt/status/1062382974744887296
* https://docs.microsoft.com/en-us/powershell/module/psreadline/
* https://github.com/KalibRx/PoshHarvestPy/blob/master/poshharvest.py
* https://0xdf.gitlab.io/2018/11/08/powershell-history-file.html

**Comment by dgarvit** [comment]
@bcoles I would like to try to implement this! Can you help me with where to begin from?

**Comment by bcoles** [comment]
@dgarvit Take a look at some of the existing [Windows Post gather modules](https://github.com/rapid7/metasploit-framework/tree/master/modules/post/windows/gather), in particular those which deal with reading data from users' `AppData` directory.

Reading the history file should be as simple as reading the file for the current user, or, if the session is privileged, iterating through all users.

I'm not sure the most efficient way off the top of my head. However, 
there's a `Msf::Post::Windows::UserProfiles` [mixin](https://github.com/rapid7/metasploit-framework/tree/master/lib/msf/core/post/windows/user_profiles.rb) you can use, which will return the `AppData` 
directory path for each user.
