### ISSUE TITLE
`DisclosureDate` format is objectively, demonstrably, logically inferior to ISO date format

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#10974]
:+1: `YYYY-mm-dd` :+1:

:-1: anything else :-1:

**Comment by wvu-r7** [comment]
Honestly, we should just transition now. ISO dates work just fine in modules due to `Date.parse`.

The griping from `msftidy` is unnecessary. There may be other consumers that fail, but we shouldn't cater to them.

**Comment by busterb** [comment]
This is fixed in #10974, thanks!
