### ISSUE TITLE
2018-11-19 00:29:52.557 WIB [6902] FATAL:  terminating connection due to unexpected postmaster exit

### ISSUE THREAD

**Issue by XSecr3t** [rapid7/metasploit-framework#10986]
hello sorry for disturbing your activity

it really make me upset

i already re install my metasploit change from Metasploit_termux to metasploit Framework using this following guide 
> https://wiki.termux.com/wiki/Metasploit_Framework#Connect_to_Database

i use automatically instalation and found this error 
> 2018-11-19 00:29:52.557 WIB [6902] FATAL:  terminating connection due to unexpected postmaster exit

and every i run db_status always 
> postgresql selected, no connection

is there something wrong again and again with my termux? :( 

i think i already following instalation guide with right way,nothing else i do after automatic instalation
Description from termux wiki said "postgre automatic setting if you chose automatic instalation"

before i start msfconsole
i always start postgre using command
> pg_ctl -D $PREFIX/var/lib/postgresql start

and result said already accepting connection

but when i run msfconsole,before the banner metasploit show up that error Show up
> 2018-11-19 00:29:52.557 WIB [6902] FATAL:  terminating connection due to unexpected postmaster exit

what should i do :/

My OS lollipop 5.1
Device A1610

**Comment by busterb** [comment]
We cannot support Termux-specific issues here, sorry.
