### ISSUE TITLE
如何保存、加载渗透成功的会话？

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#10995]
如何保存、加载渗透成功的会话？
```
sessions -s mySsh -i 2
sessions -s mySsh2 -i 2-30
# all 所有成功的目标机器
sessions -s ms17_010

#加载、并自动激活、使其有效  load
sessions -L mySsh
sessions -L mySsh2

sessions -L ms17_010
```

**Comment by busterb** [comment]
Save and load only saves parameters, restoring sessions is not possible at this time, though if your session is Meterpreter, it can reconnect when msfconsole starts if you start a handler again.
