### ISSUE TITLE
migrate is not working in meterpreter?

### ISSUE THREAD

**Issue by agrawalsmart7** [rapid7/metasploit-framework#11008]
Hi,

My working environment is:-

Os:- Windows 10
Metasploit version:- v.4.17.25

Problem Description:-

I am facing this error when I migrate to any process. `migrate 1028`

`[-] Error running command migrate: NoMethodError undefined method 'pid' for nil:NilClass`

Can anyone suggest me something?

**Comment by masterka00** [comment]
I got the same issue when having a meterpreter shell on a kali linux target.

Metasploit version: 4.17.24-0kali1

**Comment by kirillwow** [comment]
See this issue since 4.17.6-dev-

**Comment by bwatters-r7** [comment]
Can you give some more information?
You seem to be using meterpreter, but how is it running?  Are you in a stand-alone meterpreter process, or in a DLL.  What processes are you moving in between?  Are they the same architecture?

**Comment by ccondon-r7** [comment]
Hi there! We're closing this because it has not been active in more than a year and we do not have enough information to reproduce the issue. If you'd like to give us the information we request in the issue form and re-open it, go ahead. Thanks!
