### ISSUE TITLE
Auxiliary module Emailer from meterpreter ?

### ISSUE THREAD

**Issue by valerianrossigneux** [rapid7/metasploit-framework#11004]
Hi, is it any possible to use an auxiliary module from within the meterpreter session?
I am using an autorun script that contains a bunch of instruction (such as migrate, dump creds, etc.) and at the end of that I want to send an email using auxiliary/client/smtp/emailer. 
Is that possible, I can't make it work.

Thanks,
Val

**Comment by ccondon-r7** [comment]
Hi there! We're closing this because it has not been active in more than a year. However, you can ask questions about Metasploit usage on Slack or IRC: https://metasploit.com/slack
