### ISSUE TITLE
Failed to load extension: No module of the name espia found

### ISSUE THREAD

**Issue by johhnry** [rapid7/metasploit-framework#11010]
## Steps to reproduce

Hello,

I am on Kali Linux v 3.30.1 using msfconsole `Framework Version: 4.17.17-dev` and Ruby `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
`

I am trying to start a meterpreter console and make a screenshot by hacking a raspberry pi (my own).
I am using msfvenom to generate a payload and I am transferring the .py file to the pi.

I succeeded starting the meterpreter console.
I am trying to load the espia module to take a screenshot but it doesn't work.

## Current behavior

```
meterpreter > use espia
Loading extension espia...
[-] Failed to load extension: No module of the name espia found
```

In the ~/.msf4/logs/framework.log :

`[11/24/2018 00:04:54] [e(0)] meterpreter: Failed to load extension: No module of the name espia found`

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

Thanks

**Comment by OJ** [comment]
Espia is a Windows only extension.

**Comment by johhnry** [comment]
Thanks for your answer.
Is there a way to take a screenshot on linux?

**Comment by busterb** [comment]
I believe there was some work, but you would use the command 'screenshot' instead of the espia extension. I believe it is implemented currently on Windows, Android and MacOS. I'm still not clear why 'espia' exists, since it seems to duplicate this functionality even in Windows meterpreter.

**Comment by johhnry** [comment]
@busterb 
Actually I tried to use `screenshot` but it doesn't work.

**Comment by q2dg** [comment]
It should be *very* convenient make a list in wiki about which extensions are compatible with which target systems (or, in other words, which extension ara available in which Meterpreter's OS version) to prevent frustration because this issue will be a source of problems to many people. Thanks
