### ISSUE TITLE
owa_login Msf::OptionValidateError

### ISSUE THREAD

**Issue by XemBryan** [rapid7/metasploit-framework#11028]
Script should use PASS_FILE that I specify using set PASS_FILE c:\\\users\\\me\\\desktop\\\file.txt command
I'm using double backslashes \\\

It actually produces an error:
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: PASS_FILE.

Framework: 4.16.61-dev
I installed Metasploit with default parameters.
OS: windows 10 pro

**Comment by busterb** [comment]
This version is from June. Can you update to a newer version?

**Comment by XemBryan** [comment]
Upgraded to  4.17.27 with same error:
Msf::OptionValidateError The following options failed to validate: PASS_FILE.

**Comment by wvu-r7** [comment]
And you're certain the file exists at that location? The backslashes are correct.

**Comment by busterb** [comment]
Note, you can also use `c:/users/me/desktop/file.txt` just as well. I don't think there's anything we can really do to help further, it's unable to open the file for some reason that we probably can't help in this ticket.
