### ISSUE TITLE
owa_login Msf::OptionValidateError

### ISSUE THREAD

**Issue by eXPlosionas** [rapid7/metasploit-framework#11021]
When i run owa_login I'm getting error:

Auxiliary failed: Msf::OptionValidateError The following options failed to validate: PASS_FILE.

The file is in c:\metasploit, so I'm using set PASS_FILE file.txt.
I also tried pass file on desktop using: set PASS_FILE 'c:\users\me\Desktop\file.txt' with same error.

Framework: 4.16.61-dev
OS: windows 10 pro

**Comment by h00die** [comment]
Try doubling the amount of `\` to `\\`

**Comment by eXPlosionas** [comment]
> Try doubling the amount of `\` to `\\`
Then ' is not necessary, because result will be:
msf auxiliary(scanner/http/owa_login) > set pass_file 'c:\\users\\me\\desktop\\file.txt'
pass_file => c:\\users\\me\\desktop\\file.txt

If I remove ' and  use \\ then same error : 
Auxiliary failed: Msf::OptionValidateError The following options failed to validate: PASS_FILE.
