### ISSUE TITLE
Consumption of a lot of RAM

### ISSUE THREAD

**Issue by wapik** [rapid7/metasploit-framework#11034]
When launching msfconsole, it starts for a long time, after launch it takes up 3 GB of RAM. How can I fix it?

os: debian 8

**Comment by busterb** [comment]
That is unusual, you'll have to say more about how you have it setup and what you are doing with it.

It should only need around 300 MB on startup in most environments.

**Comment by busterb** [comment]
When you created this issue in github, there were a lot of things it asked you for - like how you installed Metasploit, log files, etc. Seems like those got deleted somehow when you created this issue.

Maybe the output of `ps auxww |grep msfconsole` ?

For me, it shows it is using a bit less than 200 MB of real memory.

bcook     7040  6.4  0.6 825120 202500 pts/1   Sl+  13:32   0:04 /opt/metasploit-framework/bin/../embedded/bin/ruby /opt/metasploit-framework/bin/../embedded/framework/msfconsole

**Comment by wapik** [comment]
@busterb root@orange1:~# ps auxww |grep msfconsole
usr        914  0.0  0.0   4336   760 pts/0    S+   19:41   0:00 /bin/sh /usr/bin/msfconsole -r -
usr        925  1.4 68.7 3352244 2793360 pts/0 Sl+  19:41   2:34 /opt/metasploit-framework/bin/../embedded/bin/ruby /opt/metasploit-framework/bin/../embedded/framework/msfconsole -r -
root      4337  0.0  0.0  13952  2124 pts/1    S+   22:38   0:00 grep msfconsole
It works, but it took up all the RAM.

**Comment by busterb** [comment]
what is the output of the `log` command from within msfconsole?

Do you have custom configuration on startup inside of `~/.msf4/config` ?

Do you have custom modules installed under `~/.msf4/modules` ?

**Comment by wapik** [comment]
@busterb 
log
```
Call stack:
/opt/metasploit-framework/embedded/framework/lib/rex/proto/http/server.rb:300:in `on_client_data'
/opt/metasploit-framework/embedded/framework/lib/rex/proto/http/server.rb:161:in `block in start'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:48:in `on_client_data'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:199:in `block in monitor_clients'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `each'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `monitor_clients'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:73:in `block in start'
/opt/metasploit-framework/embedded/framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[11/29/2018 10:22:32] [w(0)] core: monitor_rsock: exception during read: IOError sysread for buffered IO

```
`~/.msf4/config`
and
`~/.msf4/modules`
is empty

**Comment by ccondon-r7** [comment]
Hi there! It's been a while since this issue was active, so we're going to close it out. If you'd like to reconfirm the issue and open it up again, feel free to do that. Cheers!
