### ISSUE TITLE
Documentation on writing new payloads and handlers

### ISSUE THREAD

**Issue by illera88** [rapid7/metasploit-framework#11041]
How can I find documentation on how to create a new payload (and his correspondent handler)?

Thank you

**Comment by bwatters-r7** [comment]
Unfortunately, we don't really have a lot of documentation in that regard.  Mostly people just grab something easy, like reverse_tcp and self-teach through source.  We would not mind if documentation happened, though.  While I've never written a payload, "Figuring out" payloads is on my to-do list over the next few months, but don't let that stop you from trying.  I am also very willing to help, if you would like to collab.
