### ISSUE TITLE
`show plugins` should show all available plugins not only the loaded ones

### ISSUE THREAD

**Issue by Auxilus** [rapid7/metasploit-framework#11051]
## Steps to reproduce

```
msf5 > show plugins
msf5 >
msf5 > load sqlmap
[*] Sqlmap plugin loaded
[*] Successfully loaded plugin: Sqlmap
msf5 > show plugins
Plugins
=======
  Name    Description                                                    
      ----        -----------
  Sqlmap  sqlmap plugin for Metasploit                                                                                                         
msf5 >
```

**Comment by wvu-r7** [comment]
Sounds about right to me.

**Comment by dgarvit** [comment]
I'd like to work on this enhancement feature! Since this is my first issue, it would be great to get some help!

**Comment by Auxilus** [comment]
@dgarvit cool! the `show_plugins` methods is located in `lib/msf/ui/console/command_dispatcher/modules.rb`, you can start your digging [here](https://github.com/rapid7/metasploit-framework/blob/9e110eb9fcfb73c7f60abbdd9cc8aa80273451a1/lib/msf/ui/console/command_dispatcher/modules.rb#L1112)
