### ISSUE TITLE
Metasploit script OptString wont take "?" in an URL

### ISSUE THREAD

**Issue by B4ngB4ng** [rapid7/metasploit-framework#11057]
## Steps to reproduce

How'd you do it?

OptString.new('TARGETURI', [true, 'Path to the path that config is stored ', '/onvif-http/snapshot?auth=YWRtaW46MTEK'])

everything including ? will be cut off the URL

-----

    register_options(
      [
        Opt::RPORT(80),
        OptString.new('TARGETURI', [true, 'Path to the path that config is stored ', '/onvif-http/snapshot?auth=YWRtaW46MTEK'])
      ])
  end

....

print_status("URL.path:#{target_uri.path}")
    uri = normalize_uri(target_uri.path)
    res = send_request_cgi({
      'uri'          => uri,
      'method'       => 'GET',
    })

    print_status("URI:#{uri}")

Output:

[*] URL.path:/onvif-http/snapshot
[*] URI:/onvif-http/snapshot
[*] RES:HTTP/1.1 401 Unauthorized

## Expected behavior

the full URL should be used 

## Current behavior

URL cut off after snapshot

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

v4.17.27-dev- 

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

**Comment by wvu-r7** [comment]
I assume you're writing a module? You should be using `vars_get`. `TARGETURI` is the base URI.

**Comment by B4ngB4ng** [comment]
thanks! working
