### ISSUE TITLE
msfrpc info and msfconsole info

### ISSUE THREAD

**Issue by IamRoadRunner** [rapid7/metasploit-framework#11074]
choice  windows/http/easyfilesharing_seh
when I use msfrpc:
    use module.info ,there is no default rport
when I use msfconsole:
   command info ,the basic options  ,rport default is 80 
Is't different?

**Comment by ccondon-r7** [comment]
Please see the issue template for a list of the information we need in order to confirm or investigate an issue. If you'd like to give us more information about your environment, the behavior you're experiencing, and how you installed Metasploit, feel free to reopen.
