### ISSUE TITLE
Metasploit trouble searching

### ISSUE THREAD

**Issue by sabajua** [rapid7/metasploit-framework#11108]
msf auxiliary(gather/shodan_search) > set QUERY "CAM"
QUERY => CAM
msf auxiliary(gather/shodan_search) > run

[-] Auxiliary failed: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 stat
e=error: certificate verify failed
[-] Call stack:
[-]   C:/metasploit-framework/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connec
t_nonblock'
[-]   C:/metasploit-framework/embedded/lib/ruby/2.3.0/net/http.rb:933:in `connec
t'
[-]   C:/metasploit-framework/embedded/lib/ruby/2.3.0/net/http.rb:863:in `do_sta
rt'
[-]   C:/metasploit-framework/embedded/lib/ruby/2.3.0/net/http.rb:852:in `start'

[-]   C:/metasploit-framework/embedded/lib/ruby/2.3.0/net/http.rb:1398:in `reque
st'
[-]   C:/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan
_search.rb:59:in `shodan_query'
[-]   C:/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan
_search.rb:109:in `run'
[*] Auxiliary module execution completed
msf auxiliary(gather/shodan_search) >
msf auxiliary(gather/shodan_search) >
What OS are you running Metasploit on?

windows 8 
can i fix it???

**Comment by busterb** [comment]
This appears to have been a temporary fault with the upstream service. A 'ceritificate verify failed' message usually means a certificate expired. Also, be sure to check your local system time to make sure it is correct.

**Comment by jepunband** [comment]
hi did anyone solved this please??

[-] Auxiliary failed: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:948:in `connect'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:876:in `start'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:59:in `shodan_query'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:109:in `run'
[*] Auxiliary module execution completed
