### ISSUE TITLE
OSX Webcam post-module : post/osx/manage/webcam - Bug

### ISSUE THREAD

**Issue by zazazo** [rapid7/metasploit-framework#11105]
## Steps to reproduce

<img width="1423" alt="screenshot 2018-12-11 at 22 03 40" src="https://user-images.githubusercontent.com/44822267/49809111-ad55cf00-fd90-11e8-984e-84ef9bde8e91.png">

<img width="1440" alt="screenshot 2018-12-11 at 22 03 56" src="https://user-images.githubusercontent.com/44822267/49809209-e8580280-fd90-11e8-8b9c-9bb04d4cd21d.png">

Victim is a Macbook Pro Mojave, not virtualized. Non-root meterpreter session. 

## Expected behavior

I should get the victim's webcam working with that module. 

## Current behavior

Bug - cf screenshot

### Metasploit version

4.17.29-dev

### I installed Metasploit with:

Built in Kali

### OS

Kali

**Comment by timwr** [comment]
That module is pretty old. We should deprecate it. Can you try `meterpreter > webcam_snap` on an osx session?

**Comment by timwr** [comment]
It's there for osx/x64/meterpreter/reverse_tcp sessions, but not for python/java/php sessions.
You can do `sessions -u <session id>` to upgrade a python session to an OSX session.

**Comment by zazazo** [comment]
Awesome! I managed to upgrade the session to an OXS session. 

But I tried webcam_snap and there is an error : 

<img width="893" alt="screenshot 2018-12-12 at 22 37 19" src="https://user-images.githubusercontent.com/44822267/49880339-8534a180-fe5e-11e8-9e15-ed1a9c7dbcd3.png">

Is there a way to debug? To display the error stack / error line? By the way the webcam worked with eggshell, another MacOS RAT. And after a while it stopped working.

**Comment by timwr** [comment]
Try the `log` command?

**Comment by zazazo** [comment]
Ok I checked the logs, unfortunately I'm not good in Ruby and couldn't find the reason of this error after examining the code.

**Comment by timwr** [comment]
You're on macOS Mojave right? I think there is a bug in webcam_snap on OSX 10.14 and above.

**Comment by zazazo** [comment]
Yep, mojave...

**Comment by ccondon-r7** [comment]
Hi there! We're closing this because it hasn't been active in a while. We will consider the module a candidate for deprecation. Thanks!
