### ISSUE TITLE
Metasploit SOCKS4a + proxychains not working

### ISSUE THREAD

**Issue by zazazo** [rapid7/metasploit-framework#11116]
On Metasploit, I have access to my victim with a reverse_tcp session. 

- Attacker : Kali (VirtualBox with a host-only interface `192.168.56.102/24`)
- Victim : MacOS with 2 interfaces (One for internet `1.1.2.95/8`, one for Virtualbox `192.168.56.1/24`)

I created a `auxiliary/server/socks4a` proxy on `port 1080` to reach the router of my Victim's `1.0.0.0/8` network. I also added a route on that interface with Metasploit, and it works fine when I run `auxiliary/scanner/portscan/tcp` on `1.1.1.1` (ip of the router). 

My issue is that the SOCKS4a proxy doesn't work. For example, outside of  Metasploit when I run `proxychains nmap 1.1.1.1` it gives me nothing. Also in Firefox after configuring the proxy I don't have access to internet.

<img width="624" alt="screenshot 2018-12-13 at 21 18 41" src="https://user-images.githubusercontent.com/44822267/49946530-c3df6000-ff21-11e8-97e4-b349ccfbdb75.png">

Can someone explain to me what is the problem? Here is the config.

- Attacker : Kali (Virtualbox with 1 interface Host-only so no access to internet)

<img width="735" alt="screenshot 2018-12-13 at 21 57 57" src="https://user-images.githubusercontent.com/44822267/49946738-2c2e4180-ff22-11e8-9ce4-da697ef34310.png">

- Victim : MacOS (not virtualized). 2 interfaces : en0 with internet access, vboxnet0 for the virtualbox interface.  

<img width="831" alt="screenshot 2018-12-13 at 21 21 42" src="https://user-images.githubusercontent.com/44822267/49946605-ea9d9680-ff21-11e8-8a47-284190aa4c26.png">
<img width="798" alt="screenshot 2018-12-13 at 21 21 30" src="https://user-images.githubusercontent.com/44822267/49946608-eb362d00-ff21-11e8-8779-bbdf8c552c69.png">

- Other useful stuff   

<img width="1243" alt="screenshot 2018-12-13 at 21 36 22" src="https://user-images.githubusercontent.com/44822267/49946785-49631000-ff22-11e8-9077-20f6c90107f8.png">

<img width="898" alt="screenshot 2018-12-13 at 21 18 17" src="https://user-images.githubusercontent.com/44822267/49946793-4c5e0080-ff22-11e8-8179-326137f94f15.png">
<img width="553" alt="screenshot 2018-12-13 at 21 19 09" src="https://user-images.githubusercontent.com/44822267/49946794-4c5e0080-ff22-11e8-8cec-b2711d750008.png">
<img width="554" alt="screenshot 2018-12-13 at 21 19 20" src="https://user-images.githubusercontent.com/44822267/49946795-4cf69700-ff22-11e8-8c4b-d901ed3c2871.png">
<img width="568" alt="screenshot 2018-12-13 at 21 32 10" src="https://user-images.githubusercontent.com/44822267/49946797-4cf69700-ff22-11e8-94bd-7a5a5be9140b.png">

<img width="761" alt="screenshot 2018-12-13 at 21 18 56" src="https://user-images.githubusercontent.com/44822267/49946806-5253e180-ff22-11e8-9fbe-78781a945564.png">

**Comment by fsacer** [comment]
pretty clear what's wrong here, you can't do a syn scan via socks proxy, so you need to specify `-sT -Pn` switches to do a connect scan and not pinging. You could also turn name resolutions off with -n.
