### ISSUE TITLE
android/meterpreter/reverse_* send_sms need multi line

### ISSUE THREAD

**Issue by iy0205** [rapid7/metasploit-framework#11158]
cannot send newline
fix plz

**Comment by timwr** [comment]
Have you tried `meterpreter > send_sms -t "New\nLine" -d +...`?

**Comment by timwr** [comment]
So the API actually supports it, but the `meterpreter > ` command line parsing does not, e.g you can work around this currently like so:
```
meterpreter > irb
[*] Starting IRB shell...
[*] You are in the "client" (session) object

>> android.send_sms("+5555", "new\nline", false)
=> "Transmission successful"
```
We can probably just a put a `text.gsub!('\n',"\n")` in there as a quick fix. (Although this means you won't be able to send the literal text `\n` :man_shrugging: , but using eval here seems excessive).

**Comment by iy0205** [comment]
and i want to access android.send_sms with resource file. do you have any solution?

**Comment by timwr** [comment]
Just wait for the fix to land I guess.
Or you can write a quick module to run android.send_sms, a good similar example is here:
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/android/manage/remove_lock.rb#L64

**Comment by timwr** [comment]
Sorry I read that as *without* a resource file.
Surely just put android.send_sms() in the <ruby> section of the resource file?
Jump on IRC/Slack and we'll guide you through it.
