### ISSUE TITLE
Add *nix Gather Grub Password module

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#11166]
Add `modules/post/multi/gather/grub_creds.rb` post module to collect passwords from grub bootloader config files.

Alternatively, lazily dump all lines that `start_with? 'password'` to console.

Examples:

```
password_pbkdf2 $USERNAME $ENC_PASSWORD
password --md5 $1$9sdflksdf/sdf44k
password --encrypted $1$9sdflksdf/sdf44k
password John 1234
```

**Paths**

```
/boot/grub/grub.conf
/boot/grub/grub.cfg
/etc/grub.conf
/etc/grub/grub.cfg
/etc/grub.d/00_header
/mnt/sysimage/boot/grub.conf
/mnt/boot/grub/grub.conf
/rpool/boot/grub/grub.cfg (solaris)
```

**References**

* http://web.archive.org/web/20180626073808/http://hashdump.org/wiki/linux/hardening/boot.html
* https://help.ubuntu.com/community/Grub2/Passwords#Password_Encryption

**Comment by dgarvit** [comment]
I'd like to work on this!

**Comment by aringo** [comment]
@bcoles http://hashdump.org/wiki/linux/hardening/boot.html redirects to porn.

**Comment by bcoles** [comment]
rofl so it does

![hasdump.org](https://user-images.githubusercontent.com/434827/53294821-8745b400-3842-11e9-9e57-6fd3cf7e8bae.png)
