### ISSUE TITLE
cisco_directory_traversal.rb regex is unnecessarily restrictive and missing vulnerable hosts

### ISSUE THREAD

**Issue by carnal0wnage** [rapid7/metasploit-framework#11162]
metasploit-framework/modules/auxiliary/scanner/http/cisco_directory_traversal.rb
  
line 45 in the is_assessible? function checks for res.body.include?("SSL VPN Service")  

I have found vulnerable servers NOT returning this string and thus the module marks them as inaccessible and doesnt continue checks.

recommend replacing res.body.include?("SSL VPN Service") with res.body.include?("+CSCOE+") or giving it an OR check for both.

Happy to submit a PR If you need me to.

**Comment by bcoles** [comment]
Seems reasonable. Is `+webvpn+` or `webvpnlogin` another viable candidate for matching?

(as per [auxiliary/scanner/http/cisco_ssl_vpn](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/http/cisco_ssl_vpn.rb))

**Comment by bcoles** [comment]
Fixed in #11500
