### ISSUE TITLE
Meterpreter has issues with large (> 4GB) files

### ISSUE THREAD

**Issue by timwr** [rapid7/metasploit-framework#11189]
This has actually been reported before but not on the framework repo:
https://github.com/rapid7/meterpreter/issues/204
https://github.com/rapid7/metasploit-payloads/issues/281

## Steps to reproduce

1. Get any meterpreter session (currently python)
1. Create a 4.1 gb file: `dd if=/dev/zero of=lol4gb bs=4M count=1025`
1. `meterpreter > ls` in the directory where you created `log4gb`

## Expected behavior

The ls command should complete and return the correct size

## Current behavior

```
meterpreter > ls
[-] stdapi_fs_ls: Operation failed: Unknown error
```

```
[01/01/2019 19:58:21] [e(0)] meterpreter: stdapi_fs_ls: Operation failed: Unknown error
[01/01/2019 19:58:21] [d(0)] meterpreter: Call stack:
/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:80:in `entries_with_info'
/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:629:in `list_path'
/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:735:in `cmd_ls'
```

### OS

Linux

**Comment by OJ** [comment]
This also impacts files downloads and whatnot, so we'd need to make sure we cover it off across the board. But yes, agreed, need to fix and need to make sure we don't break existing payloads with it!

**Comment by fsacer** [comment]
actually here is the related issue which was posted before on the main repo https://github.com/rapid7/metasploit-framework/issues/10871
