### ISSUE TITLE
python extension on linux

### ISSUE THREAD

**Issue by FunnyWolf** [rapid7/metasploit-framework#11197]
Python is a very exciting extension for meterpreter, but unfortunately it only works on windows. Do we have some guidance for compiling this extension  so that it can work on linux? 
From the  [metasploit-payloads](https://github.com/rapid7/metasploit-payloads/tree/master/c/meterpreter) ,only the guidance for compiling the windows platform is currently available
@OJ @busterb

**Comment by Green-m** [comment]
On Linux/Unix, meterpreter is not strong and powerful as on windows. We still have much work to do, including making some features only supported on windows available on *nix.
Welcome everyone to contributing to the project. :)

**Comment by FunnyWolf** [comment]
> On Linux/Unix, meterpreter is not strong and powerful as on windows. We still have much work to do, including making some features only supported on windows available on *nix.
> Welcome everyone to contributing to the project. :)

thanks to reply,we have powershell and python on windows now,but only stdapi on linux,i think python will be a good funtion and interface

**Comment by FunnyWolf** [comment]
> You might be interested in this: [rapid7/mettle#125](https://github.com/rapid7/mettle/pull/125)
> You could just replace Lua with python

thanks for your help，it is very helpful~
