### ISSUE TITLE
/usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by ellaJin** [rapid7/metasploit-framework#11202]
i used "msfvenom -l payloads" in kali linux but it happened

/usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!': can't modify frozen String (RuntimeError)
	from /usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `initialize'
	from /opt/metasploit/apps/pro/msf3/metasploit-framework.gemspec:118:in `new'
	from /opt/metasploit/apps/pro/msf3/metasploit-framework.gemspec:118:in `block in <main>'
	from /usr/lib/ruby/1.9.1/rubygems/specification.rb:1368:in `initialize'
	from /opt/metasploit/apps/pro/msf3/metasploit-framework.gemspec:18:in `new'
	from /opt/metasploit/apps/pro/msf3/metasploit-framework.gemspec:18:in `<main>'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:280:in `eval'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:280:in `rescue in block in load_gemspec'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:275:in `block in load_gemspec'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:273:in `chdir'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:273:in `load_gemspec'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:39:in `gemspec'
	from /opt/metasploit/apps/pro/Gemfile:30:in `evaluate'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:7:in `instance_eval'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:7:in `evaluate'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:18:in `build'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:135:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `load'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:107:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:7:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /opt/metasploit/apps/pro/msf3/config/boot.rb:26:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /opt/metasploit/apps/pro/msf3/lib/msfenv.rb:12:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /opt/metasploit/apps/pro/msf3/msfvenom:18:in `require_deps'
	from /opt/metasploit/apps/pro/msf3/msfvenom:36:in `init_framework'
	from /opt/metasploit/apps/pro/msf3/msfvenom:317:in `dump_payloads'
	from /opt/metasploit/apps/pro/msf3/msfvenom:390:in `block in <main>'
	from /opt/metasploit/apps/pro/msf3/msfvenom:387:in `each'
	from /opt/metasploit/apps/pro/msf3/msfvenom:387:in `<main>'

i don't know what's going on here...T.T  can anyone help me

**Comment by Green-m** [comment]
What's your env, Metasploit version, and ruby version? Seems like you use `ruby 1.9.1`, which may be too old.

**Comment by ellaJin** [comment]
> What's your env, Metasploit version, and ruby version? Seems like you use `ruby 1.9.1`, which may be too old.

my ruby version is 1.9.1.. so i have to update the ruby version??

**Comment by Green-m** [comment]
Yes, give it a try.
