### ISSUE TITLE
Add api into railgun

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#11208]
Please, add into advapi32 this api:
1)
https://docs.microsoft.com/en-us/windows/desktop/api/Aclapi/nf-aclapi-setsecurityinfo
DWORD SetSecurityInfo(
  HANDLE               handle,
  SE_OBJECT_TYPE       ObjectType,
  SECURITY_INFORMATION SecurityInfo,
  PSID                 psidOwner,
  PSID                 psidGroup,
  PACL                 pDacl,
  PACL                 pSacl
);
2)
https://docs.microsoft.com/en-us/windows/desktop/api/Aclapi/nf-aclapi-setnamedsecurityinfoa
DWORD SetNamedSecurityInfoA(
  LPSTR                pObjectName,
  SE_OBJECT_TYPE       ObjectType,
  SECURITY_INFORMATION SecurityInfo,
  PSID                 psidOwner,
  PSID                 psidGroup,
  PACL                 pDacl,
  PACL                 pSacl
);

**Comment by ccondon-r7** [comment]
Hi! We're closing this because it hasn't been active in a while and is not a bug, but Metasploit users can still see the enhancement request when they search for the `enhancement` label in our issues. Thanks for the suggestion!
