### ISSUE TITLE
post/windows/manage/enable_rdp. Error.

### ISSUE THREAD

**Issue by Koraman** [rapid7/metasploit-framework#11221]
We can't write key, if path not exist.
Add this:
registry_createkey(hide_user_key)

To this:
`print_status "\tHiding user from Windows Login screen"
hide_user_key = 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList'
registry_setvaldata(hide_user_key, username, 0, "REG_DWORD")`

**Comment by bcoles** [comment]
Dupe of #7056
