### ISSUE TITLE
Metasploit

### ISSUE THREAD

**Issue by vivianfrench2** [rapid7/metasploit-framework#11240]
For some reason, I am getting an error: 

Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

I am using Metasploit on my Kali Linux virtual machine.
I opened the ports 3000 and 5432 on my private regular machines IP. I am using Google Wifi. 

Maybe I have to get Google Wifi to recognize my virtual machine as a machine, I don't know. What do I do?

**Comment by Auxilus** [comment]
@vivianfrench2 the error due to failed database connection, do you have postgresql running?

**Comment by vivianfrench2** [comment]
How do I check to see if that is running?

**Comment by Auxilus** [comment]
you can you that by `pg_isready`

**Comment by vivianfrench2** [comment]
In root Kali, it says /var/run/postgresql:5432 - accepting connections. However, in Metasploit, it says /tmp:5432 - no response

**Comment by vivianfrench2** [comment]
I'm not even sure whether its running or not.

**Comment by Auxilus** [comment]
have you set up the database in `config/database.yml`?

**Comment by CyberKid1987** [comment]
cd $HOME
pkg install wget
wget https://Auxius.github.io/metasploit.sh
bash metasploit.sh
cd metasploit-framework
gem install bundler
gem install nokogiri -- --using-system-libraries
rm Gemfile.lock
bundle install
yard config --gem-install-yri
msfconsole

I fix it. Good work 👍

**Comment by vivianfrench2** [comment]
Thank you all, I did some research on the Internet and fixed the problem on my own. All I needed to do was type the code `service postgresql start `  It starts the database for me

**Comment by vivianfrench2** [comment]
I just have to do it everytime before I begin Metasploit

**Comment by acidphuck** [comment]
U need to setup the database first.
