### ISSUE TITLE
set jtr_type on cred

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#11260]
I'm working on adding some docs to analyze/jtr_*

At least the aix module requires `jtr_format` to be set to `des`
https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/analyze/jtr_aix.rb#L90

However, the current `creds` command doesn't allow for setting this parameter.  While it is most likely a SUPER RARE item to need to set, it still means I'll have to IRB to set it, when it could be an easy thing to set from the command line.

**Comment by h00die** [comment]
Oh, I thought about working on this, but #11264 is such a monster now that I was hoping someone else would do this so the efforts would work in parallel.

I'd also add that there isn't currently a way to display the `jtr_format` field.

**Comment by h00die** [comment]
Also thought that person may handle https://github.com/rapid7/metasploit-framework/pull/11264#issuecomment-455768970 while they're at it, someone more familiar with the data model stuff

**Comment by bcoles** [comment]
My bad. I thought this was one of the issues being resolved in #11264

**Comment by h00die** [comment]
Nah, while it may not seem like it, I'm trying *not* to do monster PRs that change 10+ things in one bang.  I'm favoring a post module to just push all the hashes I need.  Not as clean, but also makes this issue not a hold up

**Comment by h00die** [comment]
this is resolved in the 4th coming PR for the jtr modernization.
