### ISSUE TITLE
Problem when victim use vpn

### ISSUE THREAD

**Issue by StephanRq1** [rapid7/metasploit-framework#11266]
I use port forwarding on my modem and also i use noip in my kali machine. I use kwetza script to create evik apk using existing application like instagram. 

i use tcp meterpreter , when my victim open evil apk  without any vpn program evrything is ok. but when victim use an vpn application on the attacked mobile, meterpreter session's cant be created or closed immediately.

**Comment by ccondon-r7** [comment]
Hi there! This issue hasn't been active in a while, so we're closing it. If you'd like to re-confirm and re-open it, you can do so. Please be sure to give us all the information we request in the issue form. Thanks!
