### ISSUE TITLE
Issue with shell_to_meterpreter

### ISSUE THREAD

**Issue by nbccmurphy** [rapid7/metasploit-framework#11274]
Running on the latest version of Kali

When running use auxiliary/scanner/ssh/ssh_login

I can make a successful connection with SSH. Then when trying to run "sessions -u 1" I get a metasploit error on the shell_to_meterpreter. 

It's for school as im a student so this is the best I could do for an image. 

![img_1006](https://user-images.githubusercontent.com/43138779/51358006-ca6c7480-1a97-11e9-8f74-6f9f841f409a.JPG)

**Comment by Green-m** [comment]
Could you please post the log info in `~/.msf4/logs/framework.log` and more info such as your Metasploit version, ruby version, OS of the victim and so on.

This module works well on my machine.

**Comment by nbccmurphy** [comment]
framework
metasploit - 4.17.3-dev 
console - 4.17.3-dev 

ruby - 2.5.lp57

Victim - Windows 7 SP1
Port 22 ; 135 ; 139 ; 445 ; 5357 open. We using port 22 for the sake of the lab. 
This is a closed off VM setup, I can most likely get internet access if 100% needed if something needs updates 

![img_1007 1](https://user-images.githubusercontent.com/43138779/51393998-89b04200-1b0f-11e9-8cc8-663079aa1f5c.JPG)
![img_1008 1](https://user-images.githubusercontent.com/43138779/51394002-8ae16f00-1b0f-11e9-8453-4030a296e217.JPG)

**Comment by ccondon-r7** [comment]
Hi there! We're closing this issue because it hasn't been active in a while. If there's still an issue, feel free to re-open. Thanks!
