### ISSUE TITLE
msf5 crashes on kali 2018.4 with message "[FATAL] failed to allocate memory" or segmentation fault/hang on "show all"

### ISSUE THREAD

**Issue by conniest** [rapid7/metasploit-framework#11302]
## Steps to reproduce

Crash is unpredictable, but always occurs shortly after starting msf console via either "msfdb run" or "service postgresql start; msfconsole."    

## Expected behavior

That it doesn't crash

## Current behavior

A crash or a hang occurs sometimes immediately upon startup or sometimes after a short sequence of commands.

Most often, program dies with the message
"[FATAL] failed to allocate memory" 

Other times, it will simply hang and become unresponsive, or occasionally segmentation fault.
Occurs on both of my systems (one physical, one virtual) in the same way (systems details at end).

A crash occurs either right away or after a short sequence of commands.   Here is a typical example:
>    root@kalivm:~# msfdb run
>    msf5 > use auxiliary/scanner/smb/smb2
>    msf5 auxiliary(scanner/smb/smb2) > setg RHOSTS 10.10.10.103
>    RHOSTS => 10.10.10.103
>    msf5 auxiliary(scanner/smb/smb2) > run
>    [+] 10.10.10.103:445      - 10.10.10.103 supports SMB 2 [dialect 255.2] and has been online for 33 hours
>    **[FATAL] failed to allocate memory**
>

See following transcript for **segmentation fault** on "show all"
[show-all-segfault-transcript.txt](https://github.com/rapid7/metasploit-framework/files/2786025/show-all-segfault-transcript.txt)

### Metasploit version
> msf5 > version
> Framework: 5.0.1-dev
> Console  : 5.0.1-dev
> msf5 > 

Log file for System1: 
[framework.log](https://github.com/rapid7/metasploit-framework/files/2786047/framework.log)

Log file for System2:
[system2-framework.log](https://github.com/rapid7/metasploit-framework/files/2786064/system2-framework.log)

### I installed Metasploit with:
Came with kali 2018.4 + apt upgrade

- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

####System 1####
Physical
root@Secaudit:~: uname -a
Linux Secaudit 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
r
root@Secaudit:~: cat /proc/version
Linux version 4.19.0-kali1-amd64 (devel@kali.org) (gcc version 8.2.0 (Debian 8.2.0-13)) #1 SMP Debian 4.19.13-1kali1 (2019-01-03)

root@Secaudit:~: lsmem
...
Memory block size:       128M
Total online memory:      16G
Total offline memory:      0B

root@Secaudit:~: free -h
                    total        used        free      shared  buff/cache   available
Mem:           15Gi       1.7Gi       1.6Gi       8.3Gi        12Gi       5.3Gi
Swap:          15Gi          0B        15Gi

root@Secaudit:~: lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

#### System 2 ####
VM running on the physical machine above
root@kalivm:~: uname -a
Linux kalivm 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

root@kalivm:~: cat /proc/version
Linux version 4.19.0-kali1-amd64 (devel@kali.org) (gcc version 8.2.0 (Debian 8.2.0-13)) #1 SMP Debian 4.19.13-1kali1 (2019-01-03)

root@kalivm:~: lsmem
...
Memory block size:       128M
Total online memory:       8G
Total offline memory:      0B

root@kalivm:~: free -h
                   total        used        free      shared  buff/cache   available
Mem:          7.8Gi       1.1Gi       5.9Gi       196Mi       884Mi       6.3Gi
Swap:         4.3Gi          0B        4.3Gi

root@kalivm:~: lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       43 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz

**Comment by busterb** [comment]
Hi, do you have any ulimits enabled that would prevent a process from allocating memory?

I do see how to avoid that crash entirely though, and will take a stab at fixing it specifically. Can you verify if commenting out or deleting the line at /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:407 resolves the crash?

```
--- a/lib/rex/ui/text/shell.rb
+++ b/lib/rex/ui/text/shell.rb
@@ -404,7 +404,7 @@ protected
 
       str.gsub!(/%S/, framework.sessions.length.to_s)
       str.gsub!(/%J/, framework.jobs.length.to_s)
-      str.gsub!(/%L/, Rex::Socket.source_address("50.50.50.50"))
+      #str.gsub!(/%L/, Rex::Socket.source_address("50.50.50.50"))
       str.gsub!(/%D/, ::Dir.getwd)
       if framework.db.active
         str.gsub!(/%W/, framework.db.workspace.name)
```
