### ISSUE TITLE
I would like to understand how ruby can run Script PowerShell ? 

### ISSUE THREAD

**Issue by GreenEYESSS** [rapid7/metasploit-framework#11311]
how would you use Obfuscation and Inject a script into a PNG image?
would be good for the Pentest

https://github.com/peewpw/Invoke-PSImage

https://github.com/danielbohannon/Invoke-DOSfuscation

**Comment by jmartin-r7** [comment]
Issues are used to track bugs and feature requests in metasploit-framework.  Your question may be better posed on IRC or #slack, links to these community resources can be found at https://metasploit.com.
