### ISSUE TITLE
Metasploit error on Windows 7

### ISSUE THREAD

**Issue by VitalijKo** [rapid7/metasploit-framework#11324]
Hello! I have installed Metasploit on Windows 7.
When i go to CMD, go to Metasploit framework dir,
and type "msfconsole" or "msfconsole.bat", there is _error_.

I tryed to run msfconsole in CMD as administator,
make .bat or .cmd file, that runs msfconsole.
But it didn't worked...

Here's log:
E:/metasploit/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:18:in `require': incompatible library version - E:/metasploit/metasploit-framework/embedded/lib/ruby/2.4.0/x64-mingw32/stringio.so (LoadError)
        from E:/metasploit/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:18:in `<top (required)>'
        from E:/metasploit/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:1365:in `require'
        from E:/metasploit/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:1365:in `<module:Gem>'
        from E:/metasploit/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:116:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

Information:
OS: Windows 7 Ultimate x64
Metasploit: Windows installer latest version

**Comment by jmartin-r7** [comment]
This looks to be a compatibility issue with Ruby 2.4.3 as compiled and packaged.  We currently use binary installers made available by https://rubyinstaller.org/ for windows for the embedded packaging.  Testing shows the update to Ruby 2.5.3 that just landed for installers will also have this issue.

If you do not have a newer version of Windows available, a workaround is to install metasploit-framework in a Linux VM.  The can be done with virtualbox or vmware-player.

**Comment by busterb** [comment]
Yeah, since we rely on upstream binaries, there's not much we can do to continue support for Windows 7 if the Ruby binaries themselves do not.

**Comment by ImaginaryDevelopment** [comment]
is it possible to download older versions that did work?

**Comment by bcoles** [comment]
> 
> 
> is it possible to download older versions that did work?

Using Metasploit from the git repo, rather than the nightly installer, may or may not work with an older version of Ruby. Personally, I wouldn't advise it.

**Comment by Yogeshswami10** [comment]
in my windows 7 sp1 show this

C:\Users\Yogesh>msfconsole.bat
Traceback (most recent call last):
        7: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        6: from <internal:gem_prelude>:1:in `require'
        5: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubyge
ms.rb:1441:in `<top (required)>'
        4: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubyge
ms.rb:1441:in `require'
        3: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubyge
ms/core_ext/kernel_require.rb:8:in `<top (required)>'
        2: from C:/metasploit-framework/embedded/lib/ruby/site_ruby/2.7.0/rubyge
ms/core_ext/kernel_require.rb:8:in `require'
        1: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/monitor.rb:90:in
 `<top (required)>'
C:/metasploit-framework/embedded/lib/ruby/2.7.0/monitor.rb:90:in `require': inco
mpatible library version - C:/metasploit-framework/embedded/lib/ruby/2.7.0/x64-m
ingw32/monitor.so (LoadError)
