### ISSUE TITLE
Outputting evasion payload source code (instead of compiling)

### ISSUE THREAD

**Issue by dsx12** [rapid7/metasploit-framework#11365]
Instead of compiling into executable how do I download the payload's raw source code?

I need to do this to use this payload in other scripts.

**Comment by busterb** [comment]
There isn't a way currently, but that's a good feature request.

**Comment by dsx12** [comment]
If you make the contribution that would be epic.

**Comment by dgarvit** [comment]
I would like to work on this!

**Comment by space-r7** [comment]
Hey @dgarvit! Are you still planning on working on this?

**Comment by dgarvit** [comment]
Hey @space-r7, feel free to take this issue! :)

**Comment by space-r7** [comment]
Awesome! Thank you! :)
