### ISSUE TITLE
Msf for kali nethunter. 

### ISSUE THREAD

**Issue by CyberKid1987** [rapid7/metasploit-framework#11377]
root@kali:~# service postgresql start
[warn] No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).

I have not modify kernel. Any help?

**Comment by busterb** [comment]
Hi @CyberKid1987 this isn't really an issue we can fix. I'd suggest maybe checking https://bugs.kali.org/main_page.php to see if anyone has had this issue before.
