### ISSUE TITLE
Metasploit on Windows trying to load .so library

### ISSUE THREAD

**Issue by steinm07** [rapid7/metasploit-framework#11396]
## Steps to reproduce

I don't know how to reproduce, when I am running in on Fedora on my laptop, works all fine of course because .so libraries are for linux

## Expected behavior

Any Metasploit tool works

## Current behavior

Getting this output:
`16:11:52,02 C:\Users\NothingToSeeHere> msfvenom
Z:/Hax/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:18:in require: incompatible library version - Z:/Hax/metasploit-framework/embedded/lib/ruby/2.4.0/x64-mingw32/stringio.so (LoadError)
        from Z:/Hax/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:18:in <top (required)>
        from Z:/Hax/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:1365:in require
        from Z:/Hax/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:1365:in <module:Gem>
        from Z:/Hax/metasploit-framework/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:116:in <top (required)>
        from <internal:gem_prelude>:4:in require
        from <internal:gem_prelude>:4:in <internal:gem_prelude>`

### Metasploit version

5.0.6 (From the .msi file)

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Windows

**Comment by jmartin-r7** [comment]
What version of windows?

It was recently identified that the [installer bundle used](https://rubyinstaller.org/) to provided Ruby > 2.4 in the windows msi is not compatible with Windows 7.  Due to this support for older versions of windows using the nightly installers is not currently available.

**Comment by steinm07** [comment]
Windows 7, sadly.
