### ISSUE TITLE
smb_login returns STATUS_SUCCESS for expired/must change password.

### ISSUE THREAD

**Issue by omergafni** [rapid7/metasploit-framework#11406]
## Steps to reproduce

1. Set a domain user credentials with an expired password state.
2. Run the module.
3. Got 'Success' as result:
`[+] 172.16.3.1:445        - 172.16.3.1:445 - Success: 'domain\user:pass' Administrator`

## Expected behavior
I would expect the scanner to mark this login attempt as 'Correct credentials, but unable to login'.
`[*] 172.16.3.1:445        - 172.16.3.1:445 - Correct credentials, but unable to login: 'domain\user:pass'`

## Current behavior
Got a 'Success' as mentioned above.

## System stuff
This is where the STATUS_PASSWORD_MUST_CHANGE, STATUS_PASSWORD_EXPIRED marked as SUCCESS:

metasploit-framework\lib\metasploit\framework\login_scanner\smb.rb, line 120:
```            case status_code.name
              when 'STATUS_SUCCESS', 'STATUS_PASSWORD_MUST_CHANGE', 'STATUS_PASSWORD_EXPIRED'
                status = Metasploit::Model::Login::Status::SUCCESSFUL
              when 'STATUS_ACCOUNT_LOCKED_OUT'
                status = Metasploit::Model::Login::Status::LOCKED_OUT
              when 'STATUS_LOGON_FAILURE', 'STATUS_ACCESS_DENIED'
                status = Metasploit::Model::Login::Status::INCORRECT
              when *StatusCodes::CORRECT_CREDENTIAL_STATUS_CODES
                status = Metasploit::Model::Login::Status::DENIED_ACCESS
```

### Metasploit version
4.17.18-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali

**Comment by jmartin-r7** [comment]
This intended function as the determination is about if the supplied for guessed password is currently valid for the user.  In this case it is valid and successfully authenticated, then the service reported the user must take an action to continue.

This is semantics of course. however it is intended function and the most appropriate representation fo the state of the credential.

**Comment by wvu-r7** [comment]
See #9638.
