### ISSUE TITLE
Psexec in Msfconsole is not working 

### ISSUE THREAD

**Issue by komron01** [rapid7/metasploit-framework#11429]
## 
Using psexec is perfect via window, while when i try to get access from metasploit it is error ..ACCESS DENIED...
I use termux and msfconsole in there.
Victim's machine: Windows7
Started reverse TCP handler on 

10.23.143.122:4444
[*] 10.23.135.169:445 - Connecting to the server...
[*] 10.23.135.169:445 - Authenticating to 10.23.135.169:445|DOMAIN as user 'USERNAME'...
[*] 10.23.135.169:445 - Selecting PowerShell target
[*] 10.23.135.169:445 - Executing the payload...
[-] 10.23.135.169:445 - Service failed to start - ACCESS_DENIED

**Comment by busterb** [comment]
It looks like your access is denied. The username is probably not literally 'USERNAME', and the domain is not 'DOMAIN'.
