### ISSUE TITLE
creds crashes with undefined method `jtr_format' for nil:NilClass

### ISSUE THREAD

**Issue by DarwinSurvivor** [rapid7/metasploit-framework#11433]
## Steps to reproduce

How'd you do it?

1. I had a populated creds list (nothing exciting)
2. I ran `scanner/ssh/ssh_enumusers` on a custom users list (built from the creds list). Note: this list included a blank line if that's relavant
3. I ran the scanner and now my `creds` list is not working

## Expected behavior

The creds list should have been updated with existing users but a new service (ssh)

## Current behavior

The creds list is now broken for this workspace

### Metasploit version

Framework: 5.0.6-dev
Console  : 5.0.6-dev

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali Linux (fully updated as of time of posting)

Notes:
- My "default" workspace is unaffected
- If I export the workspace to a file, the creds section is empty
- The "creds" table in the postgresql database is *empty* (verified with psql), even though I had some credentials before the incident.
- There is nothing sensitive in this workspace (just playing around with metasploitable), so I'm happy to provide dumps and exports if that will help.

**Comment by DarwinSurvivor** [comment]
Could this be related to #11260 ?

**Comment by h00die** [comment]
Can you provide the output from the console? You can sanitize the IP, un, pass

**Comment by DarwinSurvivor** [comment]
Here's the stack trace from the creds command and the settings for the ssh_enum

I tried fixing the problem myself (closing/reopening and kicking postgres/etc) so I've unfortunately lost the original console output.

```
msf5 > creds
[-] Error while running command creds: undefined method `jtr_format' for nil:NilClass

Call stack:
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:508:in `block (2 levels) in creds_search'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:484:in `block in creds_search'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:438:in `creds_search'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:111:in `cmd_creds'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:502:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:453:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:49:in `<main>'
msf5 > 
```

```
msf5 auxiliary(scanner/ssh/ssh_enumusers) > show options 

Module options (auxiliary/scanner/ssh/ssh_enumusers):

   Name         Current Setting  Required  Description
   ----         ---------------  --------  -----------
   CHECK_FALSE  false            no        Check for false positives (random username)
   Proxies                       no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS       192.168.56.102   yes       The target address range or CIDR identifier
   RPORT        22               yes       The target port
   THREADS      4                yes       The number of concurrent threads
   THRESHOLD    10               yes       Amount of seconds needed before a user is considered found (timing attack only)
   USERNAME                      no        Single username to test (username spray)
   USER_FILE    users            no        File containing usernames, one per line


Auxiliary action:

   Name              Description
   ----              -----------
   Malformed Packet  Use a malformed packet


msf5 auxiliary(scanner/ssh/ssh_enumusers) > 
```

users file (yes the last line is blank):
```
public
anonymous
root
root
debian-sys-maint
guest
sys
klog
msfadmin
postgres
user
service

```

**Comment by h00die** [comment]
I'm able to confirm this.
Try #11434 as a fix.

**Comment by h00die** [comment]
if you care, basically when I updated the creds command to display the `jtr_format` section, I was unaware it was possible to have a cred with out a private (aka password).  So when I tried to pull `jtr_format` from `private` (which didn't exist), it gave the error.  The patch is simply to simply not assume private exists and give an empty string if it does, simple.

**Comment by DarwinSurvivor** [comment]
Thanks h00die, manually patching the creds.rb file according to that commit fixed my problem.

**Comment by h00die** [comment]
When the pull request lands to master, this ticket will auto-close
