### ISSUE TITLE
winrm_cmd doesn't output the host ip

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#11440]
`winrm_cmd` has a `print_error` or `print_good` however it doesn't print which host that information is coming from here: https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/winrm/winrm_cmd.rb#L41

Recommend adding a `#{peer}` or `#{ip}:#{rport}` to those print statements similar to https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/winrm/winrm_auth_methods.rb#L44

This was made obvious by the docs: https://github.com/rapid7/metasploit-framework/pull/11437/files#diff-0b52d8775387a438bb2c2f91d686bc59R27 so thanks to @Yashvendra for unintentionally identifying the issue.

While at it, I'd recommend changing `SAVE_OUTPUT` default value to `true`.  I'd rather store something that takes up almost no space than have to run it again (creating more logs, and more anomalies for defenders to catch).

**Comment by Yashvendra** [comment]
I would like to fix this issue. Setting up my lab, give me some time I'll fix it.

**Comment by busterb** [comment]
In the end, we also just removed SAVE_OUTPUT and made the module always store the loot and print the peer.
