### ISSUE TITLE
Wmap never finishes

### ISSUE THREAD

**Issue by vulnz** [rapid7/metasploit-framework#11471]
Using wmap plugin on 2 different websites plugin stops on "Using code 404' as not found and fails to produce any lines or activity after 3 hours

**Comment by busterb** [comment]
Hmm, it doesn't seem like there is much interest at the moment in supporting the wmap plugin. I wonder if we should remove it?

That said, could you attach logs, etc. so we can look into this a little more closely? Thanks.

**Comment by bcoles** [comment]
> Hmm, it doesn't seem like there is much interest at the moment in supporting the wmap plugin. I wonder if we should remove it?

The same could be said for `scripts/meterpreter/*` #11412

**Comment by BlaineOmega** [comment]
I am having the same issue. Would love to see a fix.

**Comment by willmeek** [comment]
> Hmm, it doesn't seem like there is much interest at the moment in supporting the wmap plugin. I wonder if we should remove it?
> 

I was evaulating Metasploit as a web endpoint pen testing framework. A quick google for guides lands you at this little guide - https://jonathansblog.co.uk/metasploit-for-website-pentest - if it's to be dropped then I guess someone should let the author know? :)

(I'm seeing hanging at File/Dir testing Using code '404' as not found. Running from a fairly unresponsive Kali Linux Virtualbox VM, as installing Metasploit locally on OSX had Sophos throw a wobbler)
