### ISSUE TITLE
Missing Priv Extension Commands in Meterpreter

### ISSUE THREAD

**Issue by fluit105** [rapid7/metasploit-framework#11488]
I'm using a reverse_tcp on an android device and I need to do a privilege escalation via 'getsystem' in Priv commands but it turns out that I have the Core, Stdapi and android commands but not the Priv ones. Why are they missing and how do I add them to the command list

**Comment by bcoles** [comment]
[getsystem](https://kb.help.rapid7.com/docs/how-does-the-getsystem-command-work) does not work on Android targets.

**Comment by fluit105** [comment]
That's weird because I saw a video using it

**Comment by OJ** [comment]
There's definitely no `priv` extension for Android. Sorry.
