### ISSUE TITLE
metasploit credential not in the bundle

### ISSUE THREAD

**Issue by IvnJzn** [rapid7/metasploit-framework#11495]
msfconsole
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        36: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        35: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        30: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        28: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        27: from /data/data/com.termux/files/home/metasploit-f

**Comment by IvnJzn** [comment]
*In termux

**Comment by Auxilus** [comment]
Hi @IvnJzn, please use https://github.com/termux/termux-packages/issues/715 for metasploit-framework on termux related issues, termux is not an officially supported platform for metasploit-framework.

**Comment by Auxilus** [comment]
there seems to be a fix https://github.com/termux/termux-packages/issues/715#issuecomment-468003094 please give it a try, and if it doesn't work report on https://github.com/termux/termux-packages/issues/715

**Comment by IvnJzn** [comment]
alright thanks! I'm just new, watching some udemy courses
