### ISSUE TITLE
msfdb init fails when attempting to start MSF web service on Windows

### ISSUE THREAD

**Issue by delfaaan** [rapid7/metasploit-framework#11494]
## Steps to reproduce

1. I ran msfdb.bat init on Windows 10 (Build 17763.316) with latest version of metasploit framework. Result of the command:

Creating database at C:/Users/username/.msf4/db
Starting database at C:/Users/username/.msf4/db...success
Creating database users
Writing client authentication configuration file C:/Users/username/.msf4/db/pg_hba.conf
Stopping database at C:/Users/username/.msf4/db
Starting database at C:/Users/username/.msf4/db...success
Creating initial database schema
[?] Initial MSF web service account username? [username]:
[?] Initial MSF web service account password? (Leave blank for random password):
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...failed
Failed to start MSF web service

2. I already comment out the msfdb file for run_cmd function like other issues had but no success.

3. This is what write into the file pg_hba.conf

host    "msf"      "msf"      127.0.0.1/32           md5
host    "msftest"  "msftest"  127.0.0.1/32           md5
host    "postgres"  "msftest"  127.0.0.1/32           md5
host    "template1"   all                127.0.0.1/32           trust
host    all             all                127.0.0.1/32           trust
host    all             all                ::1/128                trust

## Expected behavior

MSF web service started and online.

## Current behavior

Database initialization failed and PostgreSQL doesn't start.

## System stuff

Windows 10 (Build 17763.316)

### Metasploit version

Framework: 5.0.9-dev-d78a9978e065a38dae185a38832eb8ff14431d64
Console  : 5.0.9-dev-d78a9978e065a38dae185a38832eb8ff14431d64

### I installed Metasploit with:

The Windows installer at: https://windows.metasploit.com/metasploitframework-latest.msi

### OS

Windows 10 (Build 17763.316)

**Comment by GreenEYESSS** [comment]
use WSL Windows work fine 

1- sudo apt-get install metasploit-framework

2- service postgresql start

**Comment by delfaaan** [comment]
thanks for the suggestion, so there's no way to fix this with the windows installer?

**Comment by GreenEYESSS** [comment]
Look at this topic = https://github.com/rapid7/metasploit-framework/issues/11295

**Comment by busterb** [comment]
To solve this, we would need to have add an option to not daemonize the thin server. Confirmed an issue.

**Comment by GreenEYESSS** [comment]
but I think it's best to use WSL. It's nice to see linux on windows

**Comment by delfaaan** [comment]
@busterb Thanks for the help.

@GreenEYESSS Yeah, I tried that too, still struggling a little bit. Thanks though.

**Comment by heema123** [comment]
solved it by installing the postgres database from https://www.postgresql.org/download/windows/

**Comment by kchisarik** [comment]
so, this wont work on Windows at this point or am I missing something?

**Comment by kchisarik** [comment]
so, the web interface wont work on Windows at this point or am I missing something?

**Comment by MadCoderOne** [comment]
is this fixed or is there a workaround, or does the web interface just not work on Windows at this point (unless you pay Rapid7 for Pro), thanks in advance.

**Comment by calebTree** [comment]
Did you leave the "[?] Initial MSF web service account username? [username]:" blank? 
That has to have a value or it will fail as above.

**Comment by Maskhe** [comment]
I have run into same error

![TIM截图20200114161608](https://user-images.githubusercontent.com/30264078/72325976-37393f80-36e9-11ea-86c6-0ceefb10871b.png)

**Comment by 1UC1F3R616** [comment]
someone found the solution for this?

**Comment by adfoster-r7** [comment]
I believe this is still an issue with running Thin on Windows; However we no longer run the HTTP webservice by default so this is not a blocking issue for users now. Closing.
