### ISSUE TITLE
Describe your feature request or bug report, succinctly

### ISSUE THREAD

**Issue by AHvibrator** [rapid7/metasploit-framework#11509]
when i want to run msfcosole and ./msfvenom
I get this error:

[1] + 19895 suspended (signal)  ./msfconsole
[1]  + 19895 segmentation fault  ./msfconsole

### I installed Metasploit with:
Termux
### OS
Android
My target ,too

**Comment by Acidical** [comment]
Termux is not officially supported #11023

**Comment by AHvibrator** [comment]
Thanks for your help

**Comment by akiraaranii** [comment]
msfconsole

[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------
