### ISSUE TITLE
RHOSTS not resolving

### ISSUE THREAD

**Issue by aokerber** [rapid7/metasploit-framework#11502]
## Steps to reproduce

Set rhosts either with .txt file with IP addresses on a line or via Metasploit services -p ### -u -R.

Run an auxiliary module.  Metasploit fails to validate a file for RHOSTS.

How'd you do it?

1. Set rhosts either with .txt file with IP addresses on a line or via Metasploit services -p ### -u -R.
2. Run

## Expected behavior

Module should run with RHOSTS set.

## Current behavior
Get error
Auxiliary failed: option RHOSTS failed to validate.

### Metasploit version

Framework Version: 5.0.8-dev

### I installed Metasploit with:
- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Linux 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

Kali GNU/Linux Rolling \n \l

No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.1
Codename:	n/a

**Comment by bcoles** [comment]
This issue has been resolved in #11486

Please update your Metasploit.

**Comment by bcoles** [comment]
My bad. This is a different issue.

**Comment by Green-m** [comment]
Fixed in #11493, update please.

**Comment by tjnull** [comment]
The Kali Linux Dev Team has pushed out the new Metasploit Update today. 

https://pkg.kali.org/pkg/metasploit-framework
