### ISSUE TITLE
Auxiliary Module Socks4a fails to Validate RHOSTS

### ISSUE THREAD

**Issue by tjnull** [rapid7/metasploit-framework#11501]
## Steps to reproduce

How'd you do it?

I was trying to set a up a socks4a proxy server to relay connections to a target system for research. As I loaded the module and run the default options, I received this error:

msf5 > use auxiliary/server/socks4a
msf5 auxiliary(server/socks4a) > show options

Module options (auxiliary/server/socks4a):

   Name     Current Setting  Required  Description

   SRVHOST  0.0.0.0          yes       The address to listen on
   SRVPORT  1080             yes       The port to listen on.

Auxiliary action:

   Name   Description

   Proxy  
   
msf5 auxiliary(server/socks4a) > run
[-] Auxiliary failed: option RHOSTS failed to validate.

![image](https://user-images.githubusercontent.com/34779398/53615837-dfb3e300-3bad-11e9-9941-cad4e8f985fb.png)

## Expected behavior

msf post(autoroute) > use auxiliary/server/socks4a
msf auxiliary(socks4a) > show options

Module options (auxiliary/server/socks4a):

   Name     Current Setting  Required  Description

   SRVHOST  0.0.0.0          yes       The address to listen on
   SRVPORT  1080             yes       The port to listen on.

msf auxiliary(auxiliary/server/socks4a) > set SRVPORT 8080
SRVPORT => 8080
msf auxiliary(auxiliary/server/socks4a) > run
[*] Auxiliary module execution completed
[*] Starting the socks4a proxy server

This module has worked in previous versions of metasploit

## Current behavior

What happens instead?

The RHOSTS fails to validate the default values in the module. 

When I change my IP to the local subnet I get the same issue as stated earlier. 

### Metasploit version
Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

msf5 auxiliary(server/socks4a) > version
Framework: 5.0.8-dev
Console  : 5.0.8-dev
msf5 auxiliary(server/socks4a) > 

![image](https://user-images.githubusercontent.com/34779398/53615905-328d9a80-3bae-11e9-9da8-cdc6b4b08755.png)

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Linux kali 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux
OS Release Information: 
VERSION="2019.1"
VERSION_ID="2019.1"

![image](https://user-images.githubusercontent.com/34779398/53615934-54871d00-3bae-11e9-8f1e-314ee0f018d7.png)

**Comment by bcoles** [comment]
This issue has been resolved in #11486

Please update your Metasploit.

**Comment by tjnull** [comment]
Issue has officially resolved. The Kali Linux Dev Team just pushed out a new update today. Kali Linux users just need to run apt-get upgrade to upgrade to latest release

https://pkg.kali.org/pkg/metasploit-framework

![image](https://user-images.githubusercontent.com/34779398/53639743-11519c00-3bf8-11e9-943f-ccdbf53e538b.png)
