### ISSUE TITLE
Problem when I launch  ./msfconsole

### ISSUE THREAD

**Issue by xSam420** [rapid7/metasploit-framework#11512]
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        31: from ./msfconsole:48:in `<main>'
        30: from ./msfconsole:48:in `require'
        29: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'                                                         28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'                                                               26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'             25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:59:in `<top (required)>'               24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'                                                       22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'                                                              20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        18: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'                                                            17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-3.0.3/lib/metasploit/credential.rb:11:in `<top (required)>'                              14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit_data_models-3.0.5/lib/metasploit_data_models.rb:15:in `<top (required)>'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:32:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record.rb:130:in `<module:ActiveRecord>'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract_adapter.rb:3:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
         2: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'                     1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'                                /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require': dlopen failed: cannot locate symbol "rmpd_util_str_to_d" referenced by "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so"... - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)
        14: from ./msfconsole:48:in `<main>'
        13: from ./msfconsole:48:in `require'
        12: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'

        11: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        10: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
9: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
         8: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:59:in `<top (required)>'                7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'                                         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'                                                        5: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'                                                                4: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'
         3: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
         2: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
         1: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0xf0110d48> (NoMethodError)

**Comment by xSam420** [comment]
Pls help me ASAP

**Comment by bcoles** [comment]
There's a patch here:

https://github.com/termux/termux-packages/issues/715#issuecomment-468003094

As per:

https://github.com/rapid7/metasploit-framework/issues/11495#issuecomment-468007703

If the patch doesn't work, Termux has requested issues to be posted here:

https://github.com/termux/termux-packages/issues/715

**Comment by handsomebeast** [comment]
Do as before
