### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Selcukbasaran** [rapid7/metasploit-framework#11511]
I downloaded file. Now my antivirus app which is eset internet security says there is a virus in it. I dont know why but is it  safe?

**Comment by bcoles** [comment]
Could provide less information?

**Comment by Acidical** [comment]
If you are talking about Metasploit when you say "file" then it is safe, just add an exclusion. If you are not then give more information.

**Comment by ccondon-r7** [comment]
Make sure you take into account these notes about aniti-virus software, firewalls, etc.: https://metasploit.help.rapid7.com/docs/installing-the-metasploit-framework#section-disable-anti-virus-software
