### ISSUE TITLE
I can't run ./msfconsole

### ISSUE THREAD

**Issue by duckdingo12** [rapid7/metasploit-framework#11510]
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        31: from ./msfconsole:48:in `<main>'
        30: from ./msfconsole:48:in `require'
        29: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        28: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:59:in `<top (required)>'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.12.0/lib/backports/std_lib.rb:9:in `require'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:65:in `<class:DBManager>'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'

**Comment by bcoles** [comment]
There's a patch here:

https://github.com/termux/termux-packages/issues/715#issuecomment-468003094

As per:

https://github.com/rapid7/metasploit-framework/issues/11495#issuecomment-468007703

If the patch doesn't work, Termux has requested issues to be posted here:

https://github.com/termux/termux-packages/issues/715
