### ISSUE TITLE
Cannot require 'msf/core' - LoadError

### ISSUE THREAD

**Issue by petrexxy** [rapid7/metasploit-framework#11565]
Hi. Im having trouble using the `msf`/`msf/core` gem in ruby after installing the metasploit-framework. I am running Linux Mint (temporary testing etc) and followed many suggested fixes. I am able to require it locally until it attempts to require 'constants.rb' (in the lib directory).

1. I installed metasploit-framework and git cloned it
2. Installed all the ruby gems required (`bundle install` etc in the directory)
3. in `irb`, `require 'msf/core'` not working -> returns this error:

`irb(main):001:0> require 'msf/core'
Traceback (most recent call last):
        2: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
LoadError (cannot load such file -- msf/core)
irb(main):002:0> `

I am running the latest version of ruby for my repo and `gem` has been updated etc. `bundler` has also been updated. Any help would be very much appreciated. Thanks.

**Comment by petrexxy** [comment]
Update: I made some progress by copying everything inside `metasploit-framework/lib` to my /usr/lib/ruby/2.5.x folder but am getting issues with `rex` and `Rex::Text`, Output:

`NameError (uninitialized constant Rex::Text)`

**Comment by wvu-r7** [comment]
Why are you trying to do this? If you require an `irb` prompt, there's a command for that inside `msfconsole`.

**Comment by petrexxy** [comment]
@wvu-r7 yeah sorry, I've fixed the issue now. For some reason the `git clone` didn't work properly. Perhaps a corrupted one or something and I deleted it all and started again. It works now. Thanks.

**Comment by noraj** [comment]
```
$ msfconsole -q
msf5 > irb
[*] Starting IRB shell...
[*] You are in the "framework" object

[-] Error while running command irb: cannot load such file -- irb.rb
```

Seems not to work anymore.

**Comment by alzaki-cl** [comment]
On Kali Linux:
`/usr/lib/ruby/2.7.0`
`sudo git clone https://github.com/rapid7/metasploit-framework.git`
`sudo cp -r metasploit-framework/lib/* .`

Now I have @ripmeep's rex/text error but the 

> Cannot require 'msf/core' 

error is gone
