### ISSUE TITLE
web services not present in kali 2019.1 / msfdb?

### ISSUE THREAD

**Issue by joergri** [rapid7/metasploit-framework#11563]
## Steps to reproduce

launch msfdb, there is no web services stuff, msfdb init or reinit will not create web services, nor web service user name, password or api token

## Expected behavior

msfdb featuring full web services stuff in kali

## Current behavior

maybe I totally don´t see something I should see but could it be that in Kali 2019.1 even if freshly updated via apt that msfdb is an old version without support for the new metasploit web service?

### Metasploit version
all v5 in Kali since 2019.1

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [X ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Kali

**Comment by Acidical** [comment]
Try providing the output of `msfdb reinit --debug`
It is also possible there is a compatibility issue I am unaware of.

**Comment by joergri** [comment]
Hi, that is exactly the problem, there seems to be no --debug at all, neither there is no --component. So it may be an old version of msfdb. 

<img width="468" alt="Bildschirmfoto 2019-03-15 um 16 23 39" src="https://user-images.githubusercontent.com/37497834/54442427-eeb69b80-473e-11e9-83a4-1cb167833fde.png">

**Comment by busterb** [comment]
Kali linux supplies the version of `msfdb` with their package. You'll have to wait until someone adds msfdb support for the Kali version of postgresql, which has a different calling convention than upstream postgresql. The work needed is described here if you're interested: https://github.com/rapid7/metasploit-framework/wiki/Work-needed-to-allow-msfdb-to-use-postgresql-common

**Comment by busterb** [comment]
See https://github.com/rapid7/metasploit-framework/issues/11369 where we're tracking this
