### ISSUE TITLE
incompatible library version

### ISSUE THREAD

**Issue by HectorGrimm** [rapid7/metasploit-framework#11581]
installed Metasploit on Windows 7 , when done then run it, 
this error message appears :

Traceback (most recent call last):
        6: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        5: from <internal:gem_prelude>:2:in `require'
        4: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:116:in `<top (required)>'
        3: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:1365:in `<module:Gem>'
        2: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:1365:in `require'
        1: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:18:in `<top (required)>'
D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:18:in `require': incompatible library version - D:/metasploit-framework/embedded/lib/ruby/2.5.0/x64-mingw32/stringio.so (LoadError)

Information:
OS: Windows 7 Ultimate x64 Service Pack 1
Metasploit: Windows installer latest version

**Comment by busterb** [comment]
This is expected; we removed Windows 7 support from target builds because Ruby 2.5 upstream builds don't have support. You'll want to update to Windows 10 or use a Linux VM.

**Comment by sonwnja** [comment]
same you

**Comment by sonwnja** [comment]
![image](https://user-images.githubusercontent.com/15842446/54799508-903a7180-4c98-11e9-9836-e2cb3fa63e17.png)

**Comment by bcoles** [comment]
@sonwnja You'll need to update to Windows 10 or use a Linux VM.

**Comment by sonwnja** [comment]
Thx，I used another exe of metasploit ,that need product key，i got it
