### ISSUE TITLE
Add doc for plugins in framework

### ISSUE THREAD

**Issue by Green-m** [rapid7/metasploit-framework#11584]
It seems that there is no document for plugins such as `beholder`, `SessionNotifier`, I have to find the original PR to know how to use it. 

I suggest that we could add some documents to help the user achieve the goal easily like what modules do.

https://github.com/rapid7/metasploit-framework/pull/6878 
https://github.com/rapid7/metasploit-framework/pull/8102

**Comment by h00die** [comment]
I like this idea, the more docs the better.  however, I'm not sure the current framework `info -d` will work for this.  Even if its just a page added to the wiki that emulates our current markdown included in the framework, at least there would be documentation somewhere to point to.
