### ISSUE TITLE
Get RPC job result or Exception on RPC module.execute[auxiliary/scanner] in job.info and empty job.list

### ISSUE THREAD

**Issue by dan-leech** [rapid7/metasploit-framework#11596]
## Steps to reproduce
* [x]  Start the RPC service: `ruby msfrpcd -U user -P pass -S`
* [x]  Start a RCP client: `ruby msfrpc -U user -P pass -a 0.0.0.0 -S`
* [x]  In the client, do: `rpc.call('module.execute', 'auxiliary', 'scanner/http/wordpress_scanner', { "RHOSTS": "0.0.0.0" })`
* [x] Do: `rpc.call('job.info', job_id_from__the_previous_command_result)`
* [x] Get Exception here!!!
* [x]  Do: `rpc.call('job.list')`
* [x]  It should list all the jobs but it is empty

## Expected behavior

I want to take the job result somehow. Maybe I do something wrong and job has been done already...

## Current behavior

I get Exception:
```
Msf::RPC::ServerException (Msf::RPC::Exception Invalid Job ["lib/msf/core/rpc/v10/rpc_base.rb:25:in `error'", "lib/msf/core/rpc/v10/rpc_job.rb:33:in `rpc_stop'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])
```

### Metasploit version

`{"version"=>"5.0.13-dev-2bb0d84", "ruby"=>"2.6.1 x86_64-linux 2019-01-30", "api"=>"1.0"}`

### I installed Metasploit with:
- [x] Source install (please specify ruby version)
`"ruby"=>"2.6.1 x86_64-linux 2019-01-30"`
### OS

What OS are you running Metasploit on?
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
PRETTY_NAME="Linux Mint 18.2"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

**Comment by gcmurphy** [comment]
In case this helps at all - I'm new at this and hit this in `5.0.16-dev-0c7e589d`. 

However I noticed that if you scanned a larger address range (or do something to make the scheduled job run for longer) you can see it via `rpc.call('job.list')` and `rpc.call('job.info')`.  If the job is short lived it won't appear in the list of active jobs. This is similar how msfconsole works if you do `run -j`. 

From what I can tell it seems that the only way to obtain some of the results from the scan is via the `rpc.call('db.*)` family of calls. So you can do things like `db.hosts`, `db.services` and `db.vulns` as per [rpc_db.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/rpc/v10/rpc_db.rb). 

In my case I would like to have access  to the auxiliary scanner output (ideally in a useful format). It does not seem [currently possible](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/rpc/v10/rpc_module.rb#L675) to set `LocalOutput` either which would potentially allow at least the capture of the auxiliary scanner output to file at least. 

Would be interested in finding out if there's a way to do this from more experienced folks.

**Comment by dick129418** [comment]
@dan-leech the same error. solved yet?
