### ISSUE TITLE
RPC cannot console.create more then one

### ISSUE THREAD

**Issue by dan-leech** [rapid7/metasploit-framework#11600]
## Steps to reproduce
* [x]  Start the RPC service: `ruby msfrpcd -U user -P pass`
* [x]  Start a RCP client: `ruby msfrpc -U user -P pass -a 0.0.0.0`
* [x]  In the client, do: `rpc.call('console.create')`
* [x]  In the client, do: `rpc.call('console.create')`
* [x] Get Exception here!!!

## Expected behavior

I want to create second console instance like in docs.
(https://blog.ehcgroup.io/wp-content/uploads/2017/08/metasploit-rpc-api-guide-1.pdf)

## Current behavior

I get Exception:
```
Msf::RPC::ServerException (NoMethodError undefined method `migrated' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x000000000814db30> ["lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'", "lib/msf/ui/web/console.rb:52:in `initialize'", "lib/msf/ui/web/driver.rb:67:in `new'", "lib/msf/ui/web/driver.rb:67:in `create_console'", "lib/msf/core/rpc/v10/rpc_console.rb:29:in `rpc_create'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:33:in `catch'", "lib/ruby/2.6.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])
```

### Metasploit version

`{"version"=>"5.0.13-dev-2bb0d84", "ruby"=>"2.6.1 x86_64-linux 2019-01-30", "api"=>"1.0"}`

### I installed Metasploit with:
- [x] Source install (please specify ruby version)
`"ruby"=>"2.6.1 x86_64-linux 2019-01-30"`
### OS

What OS are you running Metasploit on?
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
PRETTY_NAME="Linux Mint 18.2"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial

**Comment by chielsprangers** [comment]
Hello,
Are you still getting this problem? I currently have the same problem, but also when trying to open the first console.

## System stuff

### Metasploit version
{b'version': b'5.0.14-dev-', b'ruby': b'2.5.3 x86_64-linux 2018-10-18', b'api': b'1.0'}

### I installed Metasploit with:
- [V] Source install (ruby 2.5.3)

### OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

Greetings, Chiel

**Comment by chielsprangers** [comment]
Reverting back to version 5.0.9 worked for me. So something must have changes between 5.0.9 and 5.0.13

**Comment by wjaxx** [comment]
> Reverting back to version 5.0.9 worked for me. So something must have changes between 5.0.9 and 5.0.13

I have the same issues when I start armitage.But Reverting back to version 5.0.9 cannot work for me.But when I reinstall msf4(version 4.17.51), the issues disappear.

**Comment by Mrlaminat** [comment]
I have the same issue for MSF 5.0.38.
Tried to install manually downgraded version, but it doesn't work. From this list (https://apt.metasploit.com/)

Can't install from onmibus rep, always get the error in ruby with connection timeout. 
`../ruby/2.6.0/socket.rb:64:in `connect': Connection timed out`

**Comment by mkienow-r7** [comment]
This appears to be an issue caused by the remote data service introduced in MSF5. As a temporary workaround you can run the command `db_disconnect` to disconnect from the remote data service, that is running locally, and use the database via the local data service instead.

**Comment by ver007** [comment]
Hello, have you updated this question?

**Comment by ver007** [comment]
[-] Metasploit Framework Exception: undefined method `migrated' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fda290a07e8>
[lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing', lib/msf/ui/web/console.rb:52:in `initialize', lib/msf/ui/web/driver.rb:67:in `new', lib/msf/ui/web/driver.rb:67:in `create_console', lib/msf/core/rpc/v10/rpc_console.rb:29:in `rpc_create', lib/msf/core/rpc/v10/service.rb:153:in `block in process', lib/ruby/2.5.0/timeout.rb:93:in `block in timeout', lib/ruby/2.5.0/timeout.rb:33:in `block in catch', lib/ruby/2.5.0/timeout.rb:33:in `catch', lib/ruby/2.5.0/timeout.rb:33:in `catch', lib/ruby/2.5.0/timeout.rb:108:in `timeout', lib/msf/core/rpc/v10/service.rb:153:in `process', lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri', lib/msf/core/rpc/v10/service.rb:72:in `block in start', lib/rex/proto/http/handler/proc.rb:38:in `on_request', lib/rex/proto/http/server.rb:368:in `dispatch_request', lib/rex/proto/http/server.rb:302:in `on_client_data', lib/rex/proto/http/server.rb:161:in `block in start', lib/rex/io/stream_server.rb:48:in `on_client_data', lib/rex/io/stream_server.rb:199:in `block in monitor_clients', lib/rex/io/stream_server.rb:197:in `each', lib/rex/io/stream_server.rb:197:in `monitor_clients', lib/rex/io/stream_server.rb:73:in `block in start', lib/rex/thread_factory.rb:22:in `block in spawn', lib/msf/core/thread_manager.rb:106:in `block in spawn']
[*] Warning: checkError(): java.lang.RuntimeException: undefined method `migrated' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fda290a07e8> at util.sl:51

**Comment by mkienow-r7** [comment]
@ver007 No updates, however, the above temporary workaround should help you.
