### ISSUE TITLE
issue in parrot os 

### ISSUE THREAD

**Issue by githiakalaban** [rapid7/metasploit-framework#11649]
## Steps to reproduce

How'd you do it?

1. ..[*] Bundler failed to load and returned this error:

   'cannot load such file -- bundler/setup'

[*] You may need to uninstall or upgrade bundler
.
am using the latest version of os parrot

What should happen?

## Current behavior

stopped working after updating veil ,both metasploit and veil

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### I installed Metasploit with:
preinstalled in parrot Os 
### OS

What OS are you running Metasploit on?parrot

**Comment by busterb** [comment]
There's not enough info here to help. If this is the preinstalled version in Parrot OS, please chat with the folks who maintain that. Thanks!

**Comment by githiakalaban** [comment]
thanks for help all the same the parrot Os team  made fixed today got it
fixed
