### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by MrNobodyTharusha** [rapid7/metasploit-framework#11659]
Please help me...

$ ./msfconsole
Segmentation fault
$

I reinstalled the termux but didn't work.

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
