### ISSUE TITLE
[ Contribution ] Reverse DNS TCP Payload For Linux

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#11654]
Good day,
I noticed you don't have a reverse DNS payload for linux so I completed a reverse (x86) DNS TCP payload for Linux. I have read the guide for setting up the dev environment. Are there any other specifications for how you like to have PRs submitted and format of code? 

So far the main obstacles are that : 

1.  I wrote the payload builder in python and will need to convert it to ruby. 
2.  I don't know ruby -- So I will need to learn it 
3. Currently it only works in x86 . I need to make a x64 version , but I will do that later. 

Are there anythings that I should be aware of or avoid ?
Is this something that you would be interested in having in the collection?

Thank you

**Comment by timwr** [comment]
1. The sooner you send the pull request the better, even if it's not ready.
2. Use metasm, e.g:  https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/windows/reverse_udp.rb
We'd definitely be interested in having it :)
Many thanks

**Comment by ApertureSecurity** [comment]
Ok , I am excited to hear that this is desirable. I was thinking that no one wanted ASM payloads or something anymore .

I will clean it up this weekend and see what I can make of it.

**Comment by ApertureSecurity** [comment]
Just providing an update.

Ok . I have a lot of it cleaned up . I even have parts in ruby made that work. As I understand, the module just needs to return the proper assembly right? I will post a link in a little bit . I think some additional work will be needed for completing it.

**Comment by ApertureSecurity** [comment]
Ok Update for tonight as promised. I have Ruby conversion going ok from what I understand. It doesn't like adding variables in what it thinks is a constant though.

main.rb:145: dynamic constant assignment
Payload = """
         ^

I will spend more time on it . I have a feeling the solution is a simple one.
Here is the code so far.
https://github.com/ApertureSecurity/KotikDNSPayload/blob/master/inprogress_reverse_tcp_dns.rb

What else needs to be done before this can be accepted?

**Comment by ccondon-r7** [comment]
Closing since OP's username has been deleted.
