### ISSUE TITLE
Couldn't find DOS e_magic

### ISSUE THREAD

**Issue by 1812587695** [rapid7/metasploit-framework#11651]
msf v5.0.13-dev

use payload/windows/shell_bind_tcp

generate -b '\x00\xff' -f msi -e x86/shikata_ga_nai -i 5 -k -x /root/Radmin_Viewer_3.5.2.1_CN.msi -o /root/1.msi

error：Couldn't find DOS e_magic.

**Comment by busterb** [comment]
I don't think we can inject into an MSI file, only a PE file. This is an expected behavior.
