### ISSUE TITLE
msfrpc can't store some information to database

### ISSUE THREAD

**Issue by n1ngod** [rapid7/metasploit-framework#11689]
## Steps to reproduce

1. First, i through "./msfrpcd -P test -S -f -a 0.0.0.0" to start a msf rpc services, of course it works
2. Then, i use pymetasploit library in python to connect it, it's also no problem, then i call "db.connect" to connect postgres, it create some schema in my postgres,it seems all right.
3.then  i execute rpc.call("auth.token_generate"), i know it will store the token to the database by document,but i can't get any information in table "api_keys", i really database is no problem, because when i get a meterpreter session, it can store session information to "sessions" table. Why token can't store to the "api_keys" table？what mistake did i make？what should i call the rpc service？

My python code：
In [2]: client = MsfRpcClient(password=‘test’)
In [3]: client.db.connect(username=‘postgres’, database=‘msf’,   host='127.0.0.1',password='test', port='5432', driver='postgres')
Out [3]: True
In [4]: client.call("auth.token_generate")
Out[4]: {'result': 'success', 'token': 'TEMP5221809879810272165168959285'}

I can't get token from "api_keys" table, Why?

**Comment by n1ngod** [comment]
All versions are up to date，and i through official docker image to use the metasploit.

**Comment by adfoster-r7** [comment]
Wasn't able to replicate; will close this for now as it might have been fixed
