### ISSUE TITLE
Can metasploit make the route forwarding global?

### ISSUE THREAD

**Issue by uemahra** [rapid7/metasploit-framework#11687]
Hello, great work u doing here, I use metasploit a lot, and when I got a shell I usually use 'autoroute' or 'route add' to make layer4 nmap scan direct to the msfconsole session, I'm wondering can this route add not only effect to a session but also effect the kali-linux? Can this been done or any other workaround, thks

**Comment by void-in** [comment]
You can use the auxiliary/server/socks* modules which will start a socks proxy server on the remote host that can be connected through any tool that can talk to a SOCKS proxy.

If you have further queries, fee free to jump in on the slack channel of Metasploit.
