### ISSUE TITLE
Cant initiate database Metasploit

### ISSUE THREAD

**Issue by MichelBitar99** [rapid7/metasploit-framework#11683]
Okay so I am running kali linux,
lately I might have messed up with some ruby settings to set up burpsuite or something... 
Anw I was facing some problems running metasploit, telling me a lot of gems were missing. I downgraded to ruby 2.4 using rvm, and now I can run metasploit however i cant initiate the database properly.
I did : 
`msfdb delete
msfdb init `

And i got the following : 

> [+] Starting database
[+] Creating database user 'msf'
[+] Creating databases 'msf'
[+] Creating databases 'msf_test'
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
Bundler::GemNotFound: Could not find pg-0.21.0 in any of the sources
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:91:in `block in materialize'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:85:in `map!'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/spec_set.rb:85:in `materialize'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:171:in `specs'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:238:in `specs_for'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/definition.rb:227:in `requested_specs'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:108:in `block in definition_method'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:20:in `setup'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler.rb:107:in `setup'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by busterb** [comment]
This looks like an issue with Kali linux. I'd recommend checking out their support forums for help. Thanks!
