### ISSUE TITLE
Cant access msfconsole 

### ISSUE THREAD

**Issue by bretana** [rapid7/metasploit-framework#11692]
root@202929:/opt/metasploit-framework# msfconsole 
/usr/lib/ruby/2.5.0/psych/versions.rb:4: warning: already initialized constant Psych::VERSION
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/versions.rb:5: warning: previous definition of VERSION was here
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/psych.so: warning: already initialized constant Psych::Parser::ANY
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/psych.so: warning: already initialized constant Psych::Parser::UTF8
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/usr/lib/ruby/2.5.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
/usr/lib/ruby/2.5.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/class_loader.rb:65: warning: previous definition of CACHE was here
/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
/usr/lib/ruby/2.5.0/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here
/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
/usr/lib/ruby/2.5.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
/usr/lib/ruby/2.5.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/usr/lib/ruby/2.5.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
/usr/lib/ruby/2.5.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
/usr/lib/ruby/2.5.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
/usr/lib/ruby/2.5.0/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/visitors/to_ruby.rb:334: warning: previous definition of SHOVEL was here
/usr/lib/ruby/2.5.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/usr/lib/ruby/2.5.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/var/lib/gems/2.5.0/gems/psych-3.1.0/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
Traceback (most recent call last):
	25: from /usr/local/bin/msfconsole:48:in `<main>'
	24: from /usr/local/bin/msfconsole:48:in `require'
	23: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	22: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	21: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	20: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	19: from /opt/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
	18: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	17: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	16: from /opt/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
	15: from /opt/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
	14: from /opt/metasploit-framework/lib/msf/core/framework.rb:64:in `<class:Framework>'
	13: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	12: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	11: from /opt/metasploit-framework/lib/msf/core/cert_provider.rb:2:in `<top (required)>'
	10: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	 9: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 8: from /var/lib/gems/2.5.0/gems/faker-1.9.1/lib/faker.rb:4:in `<top (required)>'
	 7: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	 6: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 5: from /usr/lib/ruby/2.5.0/psych.rb:19:in `<top (required)>'
	 4: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	 3: from /var/lib/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 2: from /usr/lib/ruby/2.5.0/psych/parser.rb:2:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/psych/parser.rb:33:in `<module:Psych>'
/usr/lib/ruby/2.5.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)

Use Ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

I do install gem, rvm and many, but still cant access.
Please help me

**Comment by manzoo16** [comment]
same with me.

**Comment by jmartin-r7** [comment]
This looks like you have an `PATH` issue that is impacting your gemset.  How did you install metasploit-framework?

**Comment by jmartin-r7** [comment]
Verified current [nightly installer](https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers) works as expected.  Closing as user env `PATH` issue.
