### ISSUE TITLE
osx keylog_recorder broken

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#11727]
Looks like its only capturing the return key.  I tried a regular shell as user, and root, same results.  Tried typing at a Terminal and Safari:
```
[*] Executing ruby command to start keylogger process.
[*] Ruby process executing with pid 3090
[*] Entering read loop
[*] Waiting 10 seconds.
[*] Sending USR1 signal to open TCP port...
[*] Dumping logs...
[*] 1 keystrokes captured
[*] [enter]
```
It captures all the times i hit enter correctly, but none of the alpha keys on 10.14.4.

**Comment by timwr** [comment]
I can have a look at landing this: https://github.com/rapid7/mettle/pull/118 
I suspect even 10.13.something has the same bug

**Comment by h00die** [comment]
Tried it on meterp as well:
```
msf5 post(osx/capture/keylog_recorder) > run

[*] Executing ruby command to start keylogger process.
[-] Post aborted due to failure: unknown: Ruby keylogger command failed with error 
[*] Post module execution completed
msf5 post(osx/capture/keylog_recorder) > sessions -l

Active sessions
===============

  Id  Name  Type                 Information                                                 Connection
  --  ----  ----                 -----------                                                 ----------
  3         meterpreter x64/osx  uid=501, gid=20, euid=501, egid=20 @ MacBook-Pro.r  1.1.1.1:4433 -> 2.2.2.2:251376 (2.2.2.2)

```

Just making notes of whats broken on OSX as i go through and make docs.  Its interesting it pulls the return key but not others.  May be a case of OSX updating to prevent this.  Will look back to find the PR, if nothing else I just want to make notes in the module/docs to say what it works and doesn't work on to avoid confusion

**Comment by h00die** [comment]
Not sure if this is related or not, but this morning OSX (no reboot/sleep/etc, left my shellz open all night) has a "Keyboard Setup Assistant" prompt.

**Comment by LSnitch** [comment]
Same problem on Windows target
