### ISSUE TITLE
Failed to load extension: x86_64-linux-musl/mimikatz not found

### ISSUE THREAD

**Issue by harry1080** [rapid7/metasploit-framework#11738]
Hello,

I am on Ubuntu 14  using msfconsole Framework Version: 5.0.18-dev-b674dc
load mimikatz, 
Loading extension mikatz...
[-] Failed to load extension: x86_64-linux-musl/mimikatz not found

I am trying to load the  mimikatz module ， but it doesn't work.

**Comment by busterb** [comment]
That's because there's no such thing. Exactly what it says on the tin!
