### ISSUE TITLE
hosts command will not work with CIDR smaller than /24

### ISSUE THREAD

**Issue by datorr2** [rapid7/metasploit-framework#11731]
Loaded up a large amount of hosts into database.  Using the `hosts` command displays pages of information.  I try to filter using `hosts 192.168.0.0/24` and it returns hosts in that subnet.  However, if I want the next adjacent one, if I use the command `hosts 192.168.0.0/23`, the command returns no hosts.  I also tried with `hosts 192.168.0.0/16`, and that does not work either.  However, /25 works.

Version: 5.0.16-dev- (installed from website, which added apt-repo)
OS: Ubuntu 18.04.2 LTS
Kernel: 4.19.0

**Comment by dwelch-r7** [comment]
hey @datorr2 I can't replicate this issue, are you still able to see the problem on the latest build?
if you can a minimal reproduciton set up would be super helpful, thanks!

**Comment by adfoster-r7** [comment]
I believe this is fixed now - closing
