### ISSUE TITLE
How to update ruby version to 2.5.0

### ISSUE THREAD

**Issue by Sylor-huang** [rapid7/metasploit-framework#11740]
I had installed ```Ruby 2.5.0 ```in my PC with rvm.

And now,after I install ```Metasploit``` in my computer, I want to run ```msfdb init ```, I got the error:

```
ruby lib version (2.3.3) doesn't match executable version (2.5.3) (RuntimeError)
```

I found that Metasploit  installed Ruby2.3.3 in my computer,but not used default 2.5.3.

I had try to ```rvm install 2.3.3```, but it  give me this error:

```
There was an error(7).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```
Then I run ```echo "export rvm_max_time_flag=20" >> ~/.rvmrc``` in terminal, it also does not work.

What should I do ? Or how to update the ```Metasploit``` ruby version?

Thanks so much.

**Comment by bcoles** [comment]
Ruby 2.3 EOL. Use Ruby 2.5.

`rvm` allows you to `use` a specified version of Ruby with the `use` command, like so:

```sh
rvm use 2.5.3
```

**Comment by Sylor-huang** [comment]
@bcoles  In fact , I had set``` rvm  use 2.5.0```, but ```Metasploit``` just use 2.3.3, how to resolving this conflict? Or as you say, I should update ruby from 2.5.0 to 2.5.3? Thanks.

**Comment by busterb** [comment]
Metasploit hasn't used 2.3.3 in a while. How did you download Metasploit?

I'm going to close this since it's not really an issue in our code on github.
