### ISSUE TITLE
Restore DNS_spoofing

### ISSUE THREAD

**Issue by DeaDHackS** [rapid7/metasploit-framework#11758]
## Steps to reproduce
How'd you do it?

1. Ran post/linux/manage/dns_spoofing.rb on my LINUX Machine.

I'm running the lastest Parrot OS Sec and i was testing some of the Post modules on my machine, but i ran dns_spoof and set origin_port to 80 (http) and redirect it to youtube.com.
Now however, when i ever i access a http website i get redirected, i try resetting my iptables
didn't work ... please help...

**Comment by bcoles** [comment]
Have you tried turning it off and on again?

**Comment by busterb** [comment]
Definitely reboot. Also read the module and what it does; that will probably help you understand how to undo it.

**Comment by DeaDHackS** [comment]
Thanks guys, and i did reboot and yes i did read the code its why i talked about iptables. But no luck.
