### ISSUE TITLE
msfconsole (nameerror)

### ISSUE THREAD

**Issue by alxiden** [rapid7/metasploit-framework#11757]
So I'm trying to run the msfconsole on the latest version of Kali lunix, and I can't tell if its a bug or I am just being dumb and missing the obvious but I get the following error message. 

"/opt/metasploit/apps/pro/vendor/bundle/ruby/2.5.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError) " 

I have already tried updating everything and making sure ruby is running on the latest versions, and looked at the controller but couldn't find anything wrong. I am fairly new to all this so im probably just missing the obvious.

thanks in advance for any help you guys can give.

**Comment by busterb** [comment]
This isn't anything related to Kali's or the open source version of Metasploit framework. From the error, it appears that you are instead using the commercial version of Metasploit with Kali Linux, which is not officially supported. I recommend using the Kali-shipped version instead, which you will find under /usr/bin/msfconsole
