### ISSUE TITLE
Metasploit database

### ISSUE THREAD

**Issue by hl11jp** [rapid7/metasploit-framework#11789]
I installed a nightly version of metaploit, after msfdb_init and I check db_status, it whows me 
![Screenshot from 2019-04-27 22-56-34](https://user-images.githubusercontent.com/21292391/56852019-caee9400-693f-11e9-8662-7fe845f88cff.png)
Instead of msf > db_status
[*] postgresql connected to msf_database
.
What shoud I do? Is it normal? Also the framework located at /opt/metasploit-framework/embedded/
### Metasploit version

Framework: 5.0.20-dev-
Console  : 5.0.20-dev-

### I installed Metasploit with:
- [*] Omnibus installer (nightly)

### OS

Ubuntu 18.04

**Comment by mkienow-r7** [comment]
@hl11jp This is normal and expected with the MSF5 release. Please see the "Database and automation APIs" section of the [Metasploit Framework 5.0 Released!](https://blog.rapid7.com/2019/01/10/metasploit-framework-5-0-released/) blog post for more details. You should have no issue working with Metasploit as shown in your screenshot, it should continue to function as expected. If you experience a specific issue related to using Metasploit with this configuration please open another issue.
