### ISSUE TITLE
metasploit-framework, msfconsole ERROR cmd!

### ISSUE THREAD

**Issue by thisisanurag** [rapid7/metasploit-framework#11793]
What OS are you running Metasploit on?
Windows 10
metasploit framework v5.0.20
-Successfully set PATH.
-Error after msfconsole.

![Screenshot (13)](https://user-images.githubusercontent.com/43112185/56920927-20fb3d00-6ae2-11e9-9eab-ca10f1b49bcc.png)

**Comment by busterb** [comment]
It appears that you are missing a file. Possibly because AV has deleted it?

**Comment by thisisanurag** [comment]
Yes Sir, it worked, I have now added it to exclusions, thanks a lot.

**Comment by thisisanurag** [comment]
> It appears that you are missing a file. Possibly because AV has deleted it?

Yes Sir, it worked, the AV was the problem, had to reinstall and add it to exclusions. Thanks a lot.
