### ISSUE TITLE
Windows_Error Gem Error 

### ISSUE THREAD

**Issue by GreatZardasht** [rapid7/metasploit-framework#11810]
Error installing windows_error:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/cache/windows_error-0.1.2.gem

OS

Termux (android Linux environment app)

Downloaded

Via git clone

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* https://github.com/termux/termux-packages/issues/715#issuecomment-469177911
