### ISSUE TITLE
ENUM_CHROME only decrypts on VM

### ISSUE THREAD

**Issue by RottenDirector** [rapid7/metasploit-framework#11814]
so uuhhh when running meterpreter reverse_tcp using veil-evasion i have enum chrome on autorun it downloads everything but dosent decrypt 69 sessions have been created downloaded chrome data and dosent decrypt there are no errors.

when i run my virus in my VM it downloads and decrypts  on WIN 10, WIN 8, WIN 7 and WIN XP

Please help me its been days ive tried everything

**Comment by bcoles** [comment]
It's great that you've provided a lot of information about your setup and scenario.

Unfortunately, your ramblings are indecipherable.
