### ISSUE TITLE
Problem when i launch msfconsole

### ISSUE THREAD

**Issue by Fulgurance** [rapid7/metasploit-framework#11839]
Hello, i'm Gentoo Linux user.
I have problem today when i launch msfconsole. It's strange, because i have 
faraday already installed...

**System info:**

`emerge --info
Portage 2.3.66 (python 3.6.8-final-0, default/linux/amd64/17.0/hardened/selinux, gcc-9.1.0, glibc-2.29-r2, 5.1.0-gentoo x86_64)
System uname: Linux-5.1.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-gentoo-2.6
KiB Mem:    16306392 total,   7987908 free
KiB Swap:   20971516 total,  20971516 free
Timestamp of repository gentoo: Mon, 13 May 2019 09:00:01 +0000
Head commit of repository gentoo: 283d962ef3d573bf5d142d32558623dc78a911e3
sh bash 5.0_p7
ld GNU ld (Gentoo 2.32 p2) 2.32.0
app-shells/bash:          5.0_p7::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.28.2-r1::gentoo
dev-lang/python:          2.7.16::gentoo, 3.6.8::gentoo, 3.7.3::gentoo
dev-util/cmake:           3.14.3::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.41.2::gentoo
sys-apps/sandbox:         2.17::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.16.1-r1::gentoo
sys-devel/binutils:       2.32-r1::gentoo
sys-devel/gcc:            9.1.0::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.0-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes

fulgurance-overlay
    location: /var/lib/layman/fulgurance-overlay
    sync-type: laymansync
    sync-uri: https://github.com/Fulgurance/Gentoo-Overlay.git
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -O2 -pipe -mmovbe -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2 -maes -mpclmul -mfsgsbase -mrdrnd -mfma -mbmi -mbmi2 -mf16c -mrdseed -madx -mprefetchwt1 -mclflushopt -mxsavec -mxsaves"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=skylake -O2 -pipe -mmovbe -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2 -maes -mpclmul -mfsgsbase -mrdrnd -mfma -mbmi -mbmi2 -mf16c -mrdseed -madx -mprefetchwt1 -mclflushopt -mxsavec -mxsaves"
DISTDIR="/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=skylake -O2 -pipe -mmovbe -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2 -maes -mpclmul -mfsgsbase -mrdrnd -mfma -mbmi -mbmi2 -mf16c -mrdseed -madx -mprefetchwt1 -mclflushopt -mxsavec -mxsaves"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs candy config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch preserve-libs protect-owned sandbox selinux sesandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=skylake -O2 -pipe -mmovbe -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2 -maes -mpclmul -mfsgsbase -mrdrnd -mfma -mbmi -mbmi2 -mf16c -mrdseed -madx -mprefetchwt1 -mclflushopt -mxsavec -mxsaves"
GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/ ftp://ftp.free.fr/mirrors/ftp.gentoo.org/ http://gentoo.modulix.net/gentoo/ http://gentoo.mirrors.ovh.net/gentoo-distfiles/ http://mirrors.soeasyto.com/distfiles.gentoo.org/ ftp://mirrors.soeasyto.com/distfiles.gentoo.org/"
LANG="fr_FR.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="fr fr_FR"
MAKEOPTS="-j9"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X acl acpi alsa amd64 bzip2 compat crypt cryptsetup custom-cflags custom-optimization cxx dbus device-mapper dhcpcd dri dri3 elogind experimental git glamor gstreamer hardened iconv initramfs ipv6 jpeg kde libtirpc lvm mp3 mp4 multilib ncurses networkmanager nls nptl ogg open_perms opengl openmp pam pcre peer_perms phonon pie plymouth png policykit pulseaudio readline seccomp selinux semantic-desktop ssl ssp tiff ubac udev udisks unconfined unicode vorbis vulkan wayland wifi wireless xattr xtpax zlib" ABI_X86="32 64" ALSA_CARDS="hda-intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput keyboard mouse" KERNEL="linux" L10N="fr fr-FR" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-1" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24" USERLAND="GNU" VIDEO_CARDS="intel i965 nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS`

**Error:**
```
` fulgurance@msi-gs73vr-6rf   ~  msfconsole                                 ✔  799  16:43:15  
/usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require': cannot load such file -- faraday (LoadError)
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `block in <top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/sawyer-0.8.2/lib/sawyer.rb:17:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/octokit-4.14.0/lib/octokit/connection.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/octokit-4.14.0/lib/octokit/client.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/octokit-4.14.0/lib/octokit.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/util/document_generator/pull_request_finder.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/util/document_generator.rb:7:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/ui/console/command_dispatcher/core.rb:23:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/ui/console/command_dispatcher.rb:117:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/ui/console/driver.rb:6:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/ui/console.rb:11:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/msf/ui.rb:11:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib64/ruby/gems/2.4.0/gems/backports-3.14.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/lib64/metasploit4.17/lib/metasploit/framework/command/console.rb:60:in `driver'
        from /usr/lib64/metasploit4.17/lib/metasploit/framework/command/console.rb:48:in `start'
        from /usr/lib64/metasploit4.17/lib/metasploit/framework/command/base.rb:82:in `start'
        from /usr/lib/metasploit/msfconsole:49:in `<main>'`
```

**Comment by busterb** [comment]
I can only suggest you work with the gentoo packagers, it's hard for us to support distro-dependent packages.

**Comment by blshkv** [comment]
@Fulgurance  make sure you have installed it using ```emerge metasploit``` and ```eselect``` the correct slot if you have few. Please file report at bugs.gentoo.org if you still have problems.

**Comment by yigitemres** [comment]
@Fulgurance Adding "spec.add_runtime_dependency 'faraday'" into $MSF_ROOT/metasploit-framework.gemspec file fixes the problem.

**Comment by TadashiComputer** [comment]
Sorry, but **spec.add_runtime_dependency 'faraday** is already in this file

**Comment by TadashiComputer** [comment]
This don't fix the problem unfortunatly
