### ISSUE TITLE
metasploit Pro server issue

### ISSUE THREAD

**Issue by duykhoa95** [rapid7/metasploit-framework#11858]
Current. i installed metasploit in windows server 2012 and i installed version 2019051301.  I am still having issues with the metasploit Pro server run dying. I updated to the latest version of Metasploit I tried running it but the service metasploit Pro server run for about 1 minute and then die. 
Is their any solution about this bug till now ??

**Comment by duykhoa95** [comment]
please, support for me .... :(((

**Comment by Chiggins** [comment]
@duykhoa95 If you have Metasploit Pro, you should be able to get customer support directly from Rapid7. 

https://www.rapid7.com/for-customers/

This is the issue tracker for the Metasploit Framework open source project, not an appropriate place for Metasploit Pro support.

**Comment by jmartin-r7** [comment]
Support for the Pro product is handled thru Rapid7 support.  See https://www.rapid7.com/for-customers/ to start a support request.
