### ISSUE TITLE
metasploit windows 7 32bit download 

### ISSUE THREAD

**Issue by H1-N1** [rapid7/metasploit-framework#11890]
hi! 
i searched on the internet but without any luke can someone provide a link to the last stable version of metasploit 32 bit thanks

**Comment by nixawk** [comment]
- https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
- https://windows.metasploit.com/metasploitframework-latest.msi

**Comment by H1-N1** [comment]
thanx for you repley
but this is 64bit i need 32bit

**Comment by bcoles** [comment]
Unfortunately Windows 7 is no longer supported. (Related: #11581, #11396, #11324)

Using Metasploit from the git repo, rather than the nightly installer, may or may not work with an older version of Ruby. Personally, I wouldn't advise it.

**Comment by H1-N1** [comment]
@bcoles 
**im just requesting a merrore to the old version of metasploit** 
**win7 suported or not in newer version dont matter**

**Comment by busterb** [comment]
We cannot support Windows 7 32-bit with Metasploit. Please choose a different / newer OS or run Metasploit in a VM.
