### ISSUE TITLE
QUESTION: Need technical details :-)

### ISSUE THREAD

**Issue by pussinboots1992** [rapid7/metasploit-framework#11910]
Can someone summarize in a fair amount of detail how the metsrv.dll is bootstraped by a stager/loader. I understand that the stager/loader connect to a metasploit handler over tcp (for example), it reads in the metsrv.dll and writes it into memory, it then passes a pointer to the metserv configuration (not sure how this works) and then the execution from my understanding hits the Init function in the dll which in turn passes the metserv configuration into the "server_setup" function of the metsrv.dll...But then I start to loose it...Can someone give a technical summary of what the call flow / bootstraping looks like for a reverse_tcp x64 meterpreter payload running on Windows ? The code is complex and I don't want to dive in before I have a basic understanding of how the loader/stager and the dll work.

**Comment by busterb** [comment]
Try watching this video https://vimeo.com/108076345
