### ISSUE TITLE
[Question] modules/auxiliary/scanner/http

### ISSUE THREAD

**Issue by noraj** [rapid7/metasploit-framework#11934]
I was wondering: Is that normal to have a Markdown file in `modules/auxiliary/scanner/http`?

Because `frontpage_credential_dump.md` seems to be the only .md file in `modules/auxiliary/scanner/` and is the only in `http/`. So it looks more like a lost file.

I may not be right. It's a question.

**Comment by Chiggins** [comment]
Yup, looks like you're right. Should've been put in `documentation/modules/auxiliary/scanner/http` instead. I'll get it moved shortly.
