### ISSUE TITLE
metasploit error in my computer

### ISSUE THREAD

**Issue by yashwanth18052003** [rapid7/metasploit-framework#11981]
hello, can any one help why is comming like that not understanding
![Capture](https://user-images.githubusercontent.com/51853464/59551082-c3d42180-8f91-11e9-929b-ee5179edaaf2.JPG)

**Comment by timwr** [comment]
Did your antivirus delete data/android/apk/classes.dex?
You'll need to fix your antivirus and reinstall metasploit.
