### ISSUE TITLE
msfdb start (or init): Attempting to start MSF web service...failed

### ISSUE THREAD

**Issue by totalmachine** [rapid7/metasploit-framework#11999]
content of my log file(.msf4/logs/msf-ws.log):

> /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
        from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
        from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
        from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require'
        from /usr/lib/ruby/gems/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
        from /usr/lib/ruby/gems/2.6.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/lib/ruby/gems/2.6.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
        from /opt/metasploit/msf-ws.ru:1:in `new'
        from /opt/metasploit/msf-ws.ru:1:in `<main>'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        from /usr/lib/ruby/gems/2.6.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        from /sbin/thin:23:in `load'
        from /sbin/thin:23:in `<main>'
> 

-------------------------------------------------------------------------------------------------------------------
Remark: considering this file /opt/metasploit/documentation/api/v1/root_api_doc.rb  exists and I changed owner of that file to my non-root user but still getting that same error as well when root was owner of whole metasploit folder (/opt/metasploit) and other sub-folders such as /opt/metasploit/documentation.....and so on
----------------------------------------------------------------------------------------------------------------------------
content of output of command 'msfdb start --debug':

> run_cmd: cmd=pg_ctl -o "-p 5433" -D /home/marko/.msf4/db status, input=, env={}
Database already started at /home/marko/.msf4/db
Attempting to start MSF web service...run_cmd: cmd=thin --rackup /opt/metasploit/msf-ws.ru --address localhost --port 5443 --ssl --ssl-key-file /home/marko/.msf4/msf-ws-key.pem --ssl-cert-file /home/marko/.msf4/msf-ws-cert.pem --ssl-disable-verify --environment production --daemonize --log /home/marko/.msf4/logs/msf-ws.log --pid /home/marko/.msf4/msf-ws.pid --tag msf-ws start, input=, env={}
Problem with HTTP get request /api/v1/msf/version, message: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)
web_service_online: expect_auth=true, response_msg={:response=>nil, :exception=>#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)>, :state=>:offline}
MSF web service doesn't appear to be online. Sleeping 5.0s until check 1/10`
>
--------------------------------------------------------------------------------------------------------------------------------
Remark: that message repeats x10 times at output
--------------------------------------------------------------------------------------------------------------------------------

What should I do?

**Comment by totalmachine** [comment]
My OS is blackarch 2019.06.03 installed on virtualbox 6.0.8 where's ghost OS is Ubuntu

**Comment by francisuk1989** [comment]
same issue https://github.com/rapid7/metasploit-framework/issues/11826

**Comment by mkienow-r7** [comment]
@totalmachine What version are you using?

**Comment by totalmachine** [comment]
> @totalmachine What version are you using?

I use free version and I figured out that web service can't be run in that version, by default, only in commercial version. Thx anyway.

**Comment by mkienow-r7** [comment]
@totalmachine That's not correct, there is a web service available in the open source version. See [Metasploit Web Service](https://github.com/rapid7/metasploit-framework/wiki/Metasploit-Web-Service)

**Comment by makinbakonpancakes** [comment]
Looking at the ArchLinux wiki, the database requires some extra steps to get set up. https://wiki.archlinux.org/index.php/Metasploit_Framework#Setting_up_the_database 

I also wasn't able to get it setup with the web service, just able to connect with msfconsole. I get the same error as you with msfdb command. Is this not using the config/database.yml file that I made like msfconsole is?

**Comment by i6o6i** [comment]
My OS is blackarch too. My msf can connect to msf eventually after I ran msfdb-blackarch as root.
`msfdb-blackarch init`

**Comment by g-goessel** [comment]
@totalmachine  if you're using blackarch you should try using the `msfdb-blackarch` command line.

**Comment by f-dj** [comment]
I experienced the same issue while running `msfdb init` on arch (not black arch).

The issue has something to do with how the documentation files are loaded. I don't have any knowledge about ruby nor how a generic solution for this issue is, but as a workaround, you can hardcode the location of the doc files into the source code:

1. Find out where metasploit is installed. For me (using AUR `metasploit-git` on arch, but I tried the regular `metasploit` package earlier as well) it was at `/opt/metasploit-git`. I will call it `METASPLOIT_INSTALL_DIR` from now on.
2. Find the relevant source file within your installation dir: `sudo grep -R "root_api_doc.rb" $METASPLOIT_INSTALL_DIR`. The relevant file is named `api_docs_servlet.rb` (I call it API_DOCS_SERVLET FILE)
3. Find out where the doc files are located. I used `sudo find /usr/share -name "root_api_doc.rb"`. In my case, they are located at `/usr/share/doc/metasploit-git/`. If they are not in `/usr/share` (I don't even know if this is possible), search at root level: `sudo find / -name "root_api_doc.rb`. (I call the it $DOC_LOCATION)
4. Create a local backup of the source file we are about to edit: cp $API_DOCS_SERVLET_FILE ~
5. Edit $API_DOCS_SERVLET_FILE. Change all the `load` lines that start with `documentation/...` to `$DOC_LOCATION/...`
6. Try running `msfdb init` again. It should work now  

It would be very nice if this was fixed in the future. I have no idea how ruby loads the files, but it should be changed so that it works in a generic way.

**Comment by cdowns71** [comment]
Evening, 
First I appreciate you posting this. Saved me a lot of time ;) I am adding what I found for the out and confirming you're fix is semi working which is good. Agreed the documentation in the ruby script should be pointing to a valid location or some exported env var ?

----
% cat /home/dualfade/.msf4/logs/msf-ws.log
Writing PID to /home/dualfade/.msf4/msf-ws.pid
Exiting!
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
----

So here I am and followed this on Blackarch latest --

Bundler version was incorrect and stated on aur --
% gem install bundler:1.17.3

Installed version --
% yay -Q metasploit    
metasploit-git 1:5.0.78.55159.f0630d7479-1

Find shared --
% sudo find /usr/share -name "root_api_doc.rb" 2>/dev/null
/usr/share/doc/metasploit-git/api/v1/root_api_doc.rb
19:15 dualfade@wormhole /opt/metasploit-git
% 

Edit ruby script --
sudo vim /opt/metasploit-git/lib/msf/core/web_services/servlet/api_docs_servlet.rb
Replace all Doc strings with correct location --
:%s/documentation/\/usr\/share\/doc\/metasploit-git\//g
:wq!

msfdb init
blah blah blah ---

It starts as you suggest :) But some odd error and a crapload of garbage in.
/home/dualfade/.msf4/logs/msf-ws.log

[!] MSF web service appears to be started, but may not operate as expected.
Please see /home/dualfade/.msf4/logs/msf-ws.log for additional details.

~!>D

**Comment by f-dj** [comment]
> Evening,
> First I appreciate you posting this. Saved me a lot of time ;) I am adding what I found for the out and confirming you're fix is semi working which is good. Agreed the documentation in the ruby script should be pointing to a valid location or some exported env var ?
> 
> % cat /home/dualfade/.msf4/logs/msf-ws.log
> Writing PID to /home/dualfade/.msf4/msf-ws.pid
> Exiting!
> /opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
> 
> So here I am and followed this on Blackarch latest --
> 
> Bundler version was incorrect and stated on aur --
> % gem install bundler:1.17.3
> 
> Installed version --
> % yay -Q metasploit
> metasploit-git 1:5.0.78.55159.f0630d7479-1
> 
> Find shared --
> % sudo find /usr/share -name "root_api_doc.rb" 2>/dev/null
> /usr/share/doc/metasploit-git/api/v1/root_api_doc.rb
> 
> Edit ruby script --
> sudo vim /opt/metasploit-git/lib/msf/core/web_services/servlet/api_docs_servlet.rb
> Replace all Doc strings with correct location --
> :%s/documentation//usr/share/doc/metasploit-git//g
> :wq!
> 
> msfdb init
> blah blah blah ---
> 
> It starts as you suggest :) But some odd error and a crapload of garbage in.
> /home/dualfade/.msf4/logs/msf-ws.log
> 
> [!] MSF web service appears to be started, but may not operate as expected.
> Please see /home/dualfade/.msf4/logs/msf-ws.log for additional details.
> 
> ~!>D

You're right, now that you say it, I saw many warnings. But as far as I could see, there were no actual erros. Maybe I have missed something though. If I find the time I may check it out again and try to find the cause of these warnings/errors. 

As I mentioned earlier, I have virtually no idea how this ruby stuff works. Maybe I'm being plain ignorant hardcoding the doc paths. I dont even know yet why the paths expected the doc files to be somewhere else.

**Comment by cdowns71** [comment]
It seams to me a variable of some form just declaring where the docs are would be better. The latest msf-git has all kinds of ruby related issues hah.

**Comment by mkienow-r7** [comment]
@cdowns71 Please share the errors from your `msf-ws.log` file.

**Comment by cdowns71** [comment]
Sure. 

On initial msfconsole launch --
10:02 dualfade@wormhole /home/dualfade
% msfconsole -q
/home/dualfade/.gem/ruby/2.7.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/home/dualfade/.gem/ruby/2.7.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:55: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
msf5 > /opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil

msf5 > db_status 
[*] Connected to postgres. Connection type: postgresql.
msf5 > 

Logs --
Listening on localhost:5443, CTRL+C to stop
2020-03-02 19:32:12 - ActiveRecord::ConnectionNotEstablished - ActiveRecord::ConnectionNotEstablished:
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:109:in `connection_pool'
	/opt/metasploit-git/lib/msf/core/db_manager/user.rb:10:in `users'
	/opt/metasploit-git/lib/msf/core/web_services/metasploit_api_app.rb:68:in `block in <class:MetasploitApiApp>'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `block in filter!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `each'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `filter!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:252:in `context'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:247:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
140653844364928:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46
140653844364928:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46
140653844364928:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:ssl/record/rec_layer_s3.c:1543:SSL alert number 46
2020-03-02 19:45:41 - ActiveRecord::ConnectionNotEstablished - ActiveRecord::ConnectionNotEstablished:
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:109:in `connection_pool'
	/opt/metasploit-git/lib/msf/core/db_manager/user.rb:10:in `users'
	/opt/metasploit-git/lib/msf/core/web_services/metasploit_api_app.rb:68:in `block in <class:MetasploitApiApp>'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `block in filter!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `each'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `filter!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:252:in `context'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:247:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	/opt/metasploit-git/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
140653844364928:error:1408F09C:SSL routines:ssl3_get_record:http request:ssl/record/ssl3_record.c:321:
140653844364928:error:1408F09C:SSL routines:ssl3_get_record:http request:ssl/record/ssl3_record.c:321:
Restarting ...
Writing PID to /home/dualfade/.msf4/msf-ws.pid

So the interesting thing is that I deleted the logs. touched the new msf-ws.log and I have no more errors when starting msfconsole. I only see the stdout from msfconsole -q.

I hope this helps. 
If you need anything else I am more than happy to help.

Chris.

**Comment by ByCoder-Depo** [comment]
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter
 pls help me
