### ISSUE TITLE
screenshot eventually times out on a windows meterpreter session

### ISSUE THREAD

**Issue by timwr** [rapid7/metasploit-framework#12001]
## Steps to reproduce

1. Get a windows meterpreter session (I'm testing on the latest Windows 10).
1. meterpreter > screenshare
1. The screen eventually stops updating (5~ minutes?)

## Current behavior

```
meterpreter > pwd
C:\
meterpreter > screenshare
[*] Preparing player...
[*] Opening player at: /metasploit-framework/alkHXYCW.html
[*] Streaming...
Opening in existing browser session.
[-] Error running command screenshare: Rex::TimeoutError Operation timed out.
meterpreter >
meterpreter > pwd
C:\
meterpreter > screenshot
[-] Error running command screenshot: Rex::TimeoutError Operation timed out.
meterpreter > pwd
C:\
```

Potentially there is also a memory leak, as task manager shows the process slowly eating up memory. It's interesting that the meterpreter session remains active after the screenshot begins to fail.

**Comment by gagan2330** [comment]
screenshare command is not  even showing any thing ..even after update
