### ISSUE TITLE
How ı write external python module

### ISSUE THREAD

**Issue by TrojKu98** [rapid7/metasploit-framework#12000]
I want to write external module with python 
but when ı import module i give error like that;

from metasploit import module

metasploit is not found 

What ı have to do please someone explain 

ı read documentation but ı didn't see what is the metasploit ?

**Comment by TrojKu98** [comment]
Update ////

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/wiki/Writing-External-Python-Modules

**Comment by wvu-r7** [comment]
An external module still runs in Metasploit. That's how it's able to pull in the `metasploit` library.
