### ISSUE TITLE
/job_processor.rb:24:in `rescue in block (2 levels) in start_processor_thread': undefined method `print_error' 

### ISSUE THREAD

**Issue by gbajson** [rapid7/metasploit-framework#12003]
## Steps to reproduce

How'd you do it?

1. I installed metasploit using the procedure from:
https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

2. Services are listening on the following ports:
```
tcp        0      0 127.0.0.1:5433          0.0.0.0:*               LISTEN      3263/postgres       
tcp        0      0 127.0.0.1:5443          0.0.0.0:*               LISTEN      3391/thin server (l 
```

3. After opening https://localhost:5443 I am getting a page with text:
Not Found

4. In mfs-ws.log I see the following exception:
```
Writing PID to /home/gbajson/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
#<Thread:0x0000000007957688@/opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/job_processor.rb:18 run> terminated with exception (report_on_exception is true):
/opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/job_processor.rb:24:in `rescue in block (2 levels) in start_processor_thread': undefined method `print_error' for #<JobProcessor:0x0000000007957728> (NoMethodError)
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/job_processor.rb:21:in `block (2 levels) in start_processor_thread'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/job_processor.rb:19:in `loop'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/job_processor.rb:19:in `block in start_processor_thread'
140576310789952:error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request:s23_srvr.c:397:
140576310789952:error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request:s23_srvr.c:397:
140576310789952:error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request:s23_srvr.c:397:
```

### Environment
```
gbajson@zauek:~$ msfconsole -v
Framework Version: 5.0.31-dev-
```

## Expected behavior

I should be able to open metasploit service page

## Current behavior
Page with "Not found" is opened

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version
```
gbajson@zauek:~$ msfconsole -v
Framework Version: 5.0.31-dev-
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [X] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
```
gbajson@zauek:~$ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 19.1 Tessa
Release:        19.1
Codename:       tessa
```

**Comment by mkienow-r7** [comment]
There is currently no document hosted at the root of the MSF web service. Check out the [Accessing the API section](https://github.com/rapid7/metasploit-framework/wiki/Metasploit-Web-Service#accessing-the-api) of the Metasploit Web Service wiki page for information on the endpoints you would access using a web browser.

**Comment by mehul2434** [comment]
Not work
