### ISSUE TITLE
Reloading a module alias fails, while reloading the OG module still works

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#12026]
```
msf5 > use auxiliary/scanner/smb/login
msf5 auxiliary(scanner/smb/login) > reload
[*] Reloading module...
[-] Failed to reload module:
msf5 auxiliary(scanner/smb/login) > use auxiliary/scanner/smb/smb_login
msf5 auxiliary(scanner/smb/smb_login) > reload
[*] Reloading module...
msf5 auxiliary(scanner/smb/smb_login) >
```

#11941

**Comment by wvu-r7** [comment]
Also, is there a way to get the original module name? I couldn't find it.

**Comment by wvu-r7** [comment]
I'm currently using `file_path`.

**Comment by acammack-r7** [comment]
Oof, good catch. I can't decided on what should happen if you reload a module for an alias that doesn't contain that alias after reloading. Ex:
```
msf5 auxiliary(scanner/smb/login) > edit
.... remove the auxiliary/scanner/smb/login alias .....
msf5 auxiliary(scanner/smb/login) > reload
???????
```
Best solution I can think of is print a warning and then load the module under the real name, but I could also see erroring out the reload.

Originally `fullname` was going to be the original/root module name, but when I changed my mind I didn't add another field hold it. I'll PR a fix.
