### ISSUE TITLE
 /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:150:in `run'

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#12055]
Mac OS
msf5 auxiliary(gather/shodan_search) > version
Framework: 5.0.29-dev-c80f6f9141f00b883a58cfb6a5ae6ef8a1789492
Console  : 5.0.29-dev-c80f6f9141f00b883a58cfb6a5ae6ef8a1789492

[*] Total: 2675 on 27 pages. Showing: 10 page(s)
[*] Collecting data, please wait...
[-] Auxiliary failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:150:in `run'
[*] Auxiliary module execution completed
<img width="921" alt="image" src="https://user-images.githubusercontent.com/18223385/60735592-a853a980-9f86-11e9-8155-d076b70fec32.png">

**Comment by mkienow-r7** [comment]
@hktalent What happens when you `set MAXPAGE 1` and `run`?

With my personal API key I'm only seeing results with `MAXPAGE` set to 1 any greater value and I get an unauthorized error:
```
msf5 auxiliary(gather/shodan_search) > run

[*] Total: 2798 on 28 pages. Showing: 2 page(s)
[*] Collecting data, please wait...
[-] Auxiliary aborted due to failure: bad-config: 401 Unauthorized. Your SHODAN_APIKEY is invalid
[*] Auxiliary module execution completed
```

**Comment by hktalent** [comment]
@mkienow-r7 
```
 version
Framework: 5.0.29-dev-c80f6f9141f00b883a58cfb6a5ae6ef8a1789492
Console  : 5.0.29-dev-c80f6f9141f00b883a58cfb6a5ae6ef8a1789492
```
<img width="399" alt="image" src="https://user-images.githubusercontent.com/18223385/60896846-a2690b80-a299-11e9-85b1-585c06def8b6.png">

**Comment by mkienow-r7** [comment]
Would you try running the module again using the default regex value (`set REGEX .*`), once with `set MAXPAGE 1` and once with `set MAXPAGE 10`?

**Comment by hktalent** [comment]
```
[*] Total: 3146 on 32 pages. Showing: 2 page(s)
[*] Collecting data, please wait...
[-] Auxiliary failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:150:in `run'
```
but 
set MAXPAGE 1 
is ok

**Comment by mkienow-r7** [comment]
@hktalent I wanted to followup with you regarding you closing the issue. Did you stop having the issue?
