### ISSUE TITLE
Metasploit not able to run july5

### ISSUE THREAD

**Issue by Kilo-411** [rapid7/metasploit-framework#12054]
Downloaded metasploit via Lazymux on termux.
Termux is been giving me error code 11. Need help on that proot problem also ..
Now this 
from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
