### ISSUE TITLE
Can't Bind Payload to Apk

### ISSUE THREAD

**Issue by 1sekai** [rapid7/metasploit-framework#12063]
![20190708_061257](https://user-images.githubusercontent.com/46434799/60774526-966d3480-a147-11e9-8413-41f4a7c4897c.jpg)
![20190708_061238](https://user-images.githubusercontent.com/46434799/60774527-9c631580-a147-11e9-854c-4dca78b1edd4.jpg)

**Comment by 1sekai** [comment]
Please Help!

**Comment by ccondon-r7** [comment]
Hi there, we don't have any official support for Termux. If you'd like to look at community documentation, there is some here:
https://wiki.termux.com/wiki/Metasploit_Framework
https://github.com/rapid7/metasploit-framework/issues/11023
