### ISSUE TITLE
metasploit problem wsl

### ISSUE THREAD

**Issue by fs-hunter** [rapid7/metasploit-framework#12071]
```
root@kali:~$ msfconsole
Traceback (most recent call last):Ork console...-
        24: from /usr/bin/msfconsole:49:in `<main>'
        23: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        22: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        21: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        20: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
        19: from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize'
        18: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        17: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        16: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        15: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        14: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        13: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        12: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules'
        11: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `each'
        10: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules'
         9: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
         8: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `each'
         7: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
         6: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `recalculate'
         5: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `each_pair'
         4: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:91:in `block in recalculate'
         3: from /usr/share/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
         2: from /usr/share/metasploit-framework/lib/msf/core/payload/android.rb:38:in `generate'
         1: from /usr/share/metasploit-framework/modules/payloads/singles/android/meterpreter_reverse_tcp.rb:44:in `generate_jar'
/usr/share/metasploit-framework/lib/msf/core/payload/android.rb:112:in `generate_jar': android/meterpreter.dex not found (RuntimeError)
root@kali:~$
```

**Comment by mkienow-r7** [comment]
@fs-hunter Please edit your issue using the template provided when you click the "New issue" button and provide all of the requested information. You can format the log entries by using triple backticks ``` before and after the entry. See [Creating and highlighting code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

**Comment by breaktop2019** [comment]
hi fs-hunter i have same problem, you fixed its? send mail to breakdesenvolvimentos or type here 
tks!

-] ***rtIng the Metasploit Framework console.../
[-] * WARNING: No database support: No database YAML file
[-] ***
Traceback (most recent call last):ork console.../
        24: from /usr/bin/msfconsole:49:in `<main>'
        23: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        22: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        21: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        20: from /usr/share/metasploit-framework/lib/metasploit/framework/command/con

**Comment by bcoles** [comment]
`android/meterpreter.dex not found (RuntimeError)` implies that the `android/meterpreter.dex` file was not found.

This is usually the result of using an outdated Metasploit package, or anti-virus software removing the file.

**Comment by Anonyomous2019** [comment]
> `android/meterpreter.dex not found (RuntimeError)`implica che il `android/meterpreter.dex`file non è stato trovato.
> 
> Questo di solito è il risultato dell'utilizzo di un pacchetto Metasploit obsoleto o della rimozione del file da parte di un software antivirus.

android/meterpreter.dex not found (RuntimeError)


When start msfconsole i ve reached this issue: android/meterpreter.dex not found (RuntimeError) (windows 10) (windows defender excludes metasploit)

**Comment by Anonyomous2019** [comment]
Need help guys

**Comment by Anonyomous2019** [comment]
> `android/meterpreter.dex not found (RuntimeError)`implica che il `android/meterpreter.dex`file non è stato trovato.
> 
> Questo di solito è il risultato dell'utilizzo di un pacchetto Metasploit obsoleto o della rimozione del file da parte di un software antivirus.

How can i install it?

**Comment by mkienow-r7** [comment]
@Anonyomous2019 [Add an exclusion to Windows Security](https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security)

**Comment by Anonyomous2019** [comment]
> @ Anonyomous2019 [Aggiungi un'esclusione alla sicurezza di Windows](https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security)

That's what i did bro

**Comment by mkienow-r7** [comment]
@Anonyomous2019 If you've added the exclusion and the file is missing you'll need to reinstall to the same location.

**Comment by Anonyomous2019** [comment]
> @ Anonyomous2019 Se hai aggiunto l'esclusione e il file è mancante, dovrai reinstallare nella stessa posizione per ripristinare tutti i file rimossi in precedenza.

I can reinstall it directly from the wizard, right?

**Comment by Anonyomous2019** [comment]
> @ Anonyomous2019 Se hai aggiunto l'esclusione e il file è mancante, dovrai reinstallare nella stessa posizione per ripristinare tutti i file rimossi in precedenza.

now it works

**Comment by crispin512** [comment]
Please tell can we download and paste the file in the location?

**Comment by mkienow-r7** [comment]
@crispin512 It might be easier to ensure anti-virus software isn't the cause of the issue before reinstall to the same location to restore any files previously removed.
