### ISSUE TITLE
KaliLinux: Framework Version 5.0.35-dev: Reflective DLL Rejection with meterpreter fails

### ISSUE THREAD

**Issue by RoseDeSable** [rapid7/metasploit-framework#12089]
Hello,
 my test scenario is the following:

- the target is a notebook with Windows 10

- meterpreter_reverse_winhttps (x86) is hidden in a 7zip-exe-archive with the aid of shellter

- the zip is the stage one to establisch a meterpreter on the target

- after the meterpreter in the zip is connected to my multi-handler, I try to make the reflective dll injection to establish a second meterpreter under a process, which lives the whole time, where the user's session exists !

    msf5 post(windows/manage/reflective_dll_inject) > run
    [*] Running module against <my target>
    [*] Injecting ....meterpreter_reverse_winhttps32.dll into 43448 ... <== is a x86 process
    [-] Post failed: NoMethodError undefined method `entries' for nil:NilClass
    [-] Call stack:
    [-] /usr/share/metasploit-framework/lib/msf/core/reflective_dll_loader.rb:55:in `parse_pe'
    [-] /usr/share/metasploit-framework/lib/msf/core/reflective_dll_loader.rb:24:in `load_rdi_dll'

Is this a failure, or has windows 10 a mechanism to block this kind of attack ? 

Metasploit runs under KaliLinux, how you see in the title.

**Comment by RoseDeSable** [comment]
Hello, 
 could it be, that metasploit dll-loader has a failure, because Stephen Fewer's test-dll runs ? I see its answer on the target: 

![grafik](https://user-images.githubusercontent.com/42828799/61296065-b05ae700-a7d9-11e9-83af-1f06de08d613.png)


Here is the output from meterpreter / metasploit

msf5 post(windows/manage/reflective_dll_inject) > run 
[*] Running module against ....
[*] Injecting /root/downloads/ReflectiveDLLInjection-master/bin/reflective_dll.dll into 58784 ...
[*] DLL injected. Executing ReflectiveLoader ...
[+] DLL injected and invoked.
[*] Post module execution completed

**Comment by wo4haoren** [comment]
You can not use the dll generated by msfvenom because it is not a reflective dll . Try this https://github.com/wo4haoren/ReflectiveDLLInjection .
