### ISSUE TITLE
New function suggestion:  userclone on windows

### ISSUE THREAD

**Issue by yzddmr6** [rapid7/metasploit-framework#12091]
In many cases, we can't add administrator users directly or even don not have the access to net.exe

But we can clone the privileges of existing administrator users by modifying the registry

In face some Chinese hackers had made the exp successfully

But it can not bypass the av and there is no source code

Many friends need it very much

Sooooooooooo  I think it may be added to msf

reference:
https://baike.baidu.com/item/%E5%85%8B%E9%9A%86%E5%B8%90%E5%8F%B7/6540415?fr=aladdin

https://www.cnblogs.com/s0ky1xd/p/5823985.html

**Comment by cn-kali-team** [comment]
I think the functions you mentioned are very similar to those of this module
我觉得你说的功能和这个模块的很像

[modules/post/windows/manage/rid_hijack.rb](https://github.com/rapid7/metasploit-framework/commit/3a281234dff7668556d4d75ce65dbf7def4bedbc)
