### ISSUE TITLE
vm box kali linux port

### ISSUE THREAD

**Issue by noobhacker1** [rapid7/metasploit-framework#12118]
Hello
i cant  open ports on kali linux vm box
what i did is :
1.  i opened ports 4444,443 and 80 tcp and udp on my router using the host ipv4
2.  i  wrote the same ip  in "DMZ Host IP Address" in router
3.  i opened the same ports in the settings of kali on virtual box
4.  opened the same ports too in the firewall
but canyouseeme.org says Error
plz help these images will explain more
sorry if my English was bad
![1](https://user-images.githubusercontent.com/52386096/61644219-9707de00-aca4-11e9-9cb4-b5282c8e450d.PNG)
![2](https://user-images.githubusercontent.com/52386096/61644220-97a07480-aca4-11e9-8b22-efbe6d6b2c3e.PNG)
![3](https://user-images.githubusercontent.com/52386096/61644221-97a07480-aca4-11e9-82bd-104d8a618803.PNG)
![4](https://user-images.githubusercontent.com/52386096/61644223-98390b00-aca4-11e9-94d4-f4cfd1d3b699.PNG)
![5](https://user-images.githubusercontent.com/52386096/61644226-98390b00-aca4-11e9-811e-932d9816b0a9.PNG)
![6](https://user-images.githubusercontent.com/52386096/61644227-98d1a180-aca4-11e9-9743-cef21a856ad5.PNG)
![7](https://user-images.githubusercontent.com/52386096/61644228-98d1a180-aca4-11e9-9a64-d9c5b1d28088.PNG)

**Comment by gnu-like** [comment]
@noobhacker1 `192.168.56.1` What ip is this?  if this is is your system ip & your kali ip is `10.0.2.15` so they are not in same range & class , you should set bridge in your kali network.

**Comment by noobhacker1** [comment]
@gnu-like 192.168.56.1 is the host ip
10.0.2.15 is kali ip 
Using bridge will disable the ports that in the settings of kali 
If i made it bridge will the firewall ports work with kali on virtual box?

**Comment by gnu-like** [comment]
> @gnu-like 192.168.56.1 is the host ip
> 10.0.2.15 is kali ip
> Using bridge will disable the ports that in the settings of kali
> If i made it bridge will the firewall ports work with kali on virtual box?
> Thank you.

I don't know what Do you want to do ?after seting bridge instead of virtual box setup port forward in your router. here is about **metasploit framework** ask more questions in [kali forum](https://forums.kali.org/)

**Comment by space-r7** [comment]
Hi @noobhacker1! This issue queue is for subjects related to Metasploit Framework specifically.

Please check [here](https://www.kali.org/community/) for communities that can help out with the problems you're having with Kali.
