### ISSUE TITLE
Add a new function Rex::Text.rand_password

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#12110]
When I write a post auth module, sometimes I need to generate a password. Instead of doing that manually, I'd like that to be part of Rex. This password generator should also support some of the typical password complexity requirements, for example: length, uppercase, lowercase, special characters, numbers, etc:

```ruby
pass = Rex::Text.rand_password(length: 8, uppercase: true, lowercase: true, numbers: true)
```

Something like that. It doesn't have to be implemented exactly like that.

**Comment by h00die** [comment]
Maybe also `special="@#$_&-+()/*"':;!?"` as well? Doesn't go with the book options, however you'd want to specify either a list or a blacklist of special chars for use. I'm actually leaning more towards just having a blacklist (kinda like how badchars works)

**Comment by wvu-r7** [comment]
@h00die: The random text methods already support badchar specification, so it'd have to be a very particular kind of blacklist. I'm leaning toward @wchen-r7's approach of supporting certain complexity requirements.

```
[1] pry(#<Msf::Framework>)> show-source Rex::Text.rand_text_english

From: /Users/wvu/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rex-text-0.2.22/lib/rex/text/rand.rb @ line 159:
Owner: #<Class:Rex::Text>
Visibility: public
Number of lines: 5

def self.rand_text_english(len, bad='')
  foo = []
  foo += (0x21 .. 0x7e).map{ |c| c.chr }
  rand_base(len, bad, *foo )
end
[2] pry(#<Msf::Framework>)> Rex::Text.rand_text_english(8)
=> "NX{z2:zm"
[3] pry(#<Msf::Framework>)> Rex::Text.rand_text_english(8, '@#$_&-+()/*"\':;!?')
=> "F1IHk0]n"
[4] pry(#<Msf::Framework>)>
```

**Comment by wvu-r7** [comment]
I've been enjoying using https://github.com/stympy/faker in my modules lately.

**Comment by wchen-r7** [comment]
They all sound pretty awesome.

**Comment by ccondon-r7** [comment]
@wvu-r7 This still sounds like not a bad idea! What's your gut say on effort to implement?

**Comment by wvu-r7** [comment]
Doesn't seem too difficult. Would be useful for account creation or password change bugs with specific password requirements.

**Comment by pingport80** [comment]
@wvu-r7 
Can you please assign me with this issue?

**Comment by pingport80** [comment]
Thanks!

**Comment by pingport80** [comment]
```
    def self.rand_pass(len=10, uppercase=true, lowercase=true, numbers=true)
      foo=[]
      upper=('A'..'Z').to_a
      lower=('a'..'z').to_a
      number=('0'..'10').to_a
      if uppercase
        foo+=upper
      end
      if lowercase
        foo+=lower
      end
      if numbers
        foo+=number
      end
      rand_text(len,'',*foo)
    end
```
I've added this function to /lib/rex/text/rand.rb. Using rand_text I'm generating the password. Made bad chars as empty string. Is this code in compliance with the library?

**Comment by pingport80** [comment]
```
    def self.rand_password(len=10, uppercase=true, lowercase=true, numbers=true, special=true)
      foo=[]
      upper=('A'..'Z').to_a
      lower=('a'..'z').to_a
      number=('0'..'10').to_a
      specials = ((32..47).to_a + (58..64).to_a + (91..96).to_a + (123..126).to_a).pack('U*').chars
      if uppercase
        foo+=upper
      end
      if lowercase
        foo+=lower
      end
      if numbers
        foo+=number
      end
      if special
      	foo+=specials
      end
      rand_text(len,'',*foo)
    end
```
I've added this function to lib/rex/text/rand.rb. Using rand_text() for generating password. Is this integrable with the other code? Also currently not removing bad characters, is there a need to remove bad characters while generating random strong password?

**Comment by pingport80** [comment]
Please let me know your thoughts.

**Comment by pingport80** [comment]
Please let me know you thoughts..

**Comment by adfoster-r7** [comment]
Closed by https://github.com/rapid7/rex-text/pull/41

**Comment by adfoster-r7** [comment]
I think there's potentially more bike shedding that could be done on this, such as supporting functionality for additional checks such as 'password must have at least 2 special characters', etc, but since there's not a module that needs that just yet - this is a good first step for support :+1:
