### ISSUE TITLE
meterprete screenshare for android is not working in the session.

### ISSUE THREAD

**Issue by gagan2330** [rapid7/metasploit-framework#12157]
hey ,whenever i start meterpreter session (screen share command is not working not showing anything )

**Comment by bwatters-r7** [comment]
We're going to need a lot more information on this to give a helpful answer.  
What version of Metasploit are you using?
What are you running it on?
What is your target OS and version?
What does the metasploit log say?
Is there an error written to the screen?

**Comment by azamet90** [comment]
> What version of Metasploit are you using?
 -----------------------------------kali linux to android samsung s7 with android 8
same here and there is no error message

**Comment by ccondon-r7** [comment]
Hi there! We're closing this issue because it hasn't been active in a while.

**Comment by FabxBs** [comment]
I comment this issue to explain this better, the session actually starts, but while opening in the browser, the status keeps changing from waiting to playing and doesn't display nothing. Basically the stream fails to starts and retries everytime

**Comment by Georgejnr01** [comment]
i having the same issue here.....anyone knows any reason why its like this???

**Comment by neroxyr** [comment]
Same here, it just kees changing the status so fast that nothing is displayed
