### ISSUE TITLE
Handler failed to bind to metasploit how to fix it exe file

### ISSUE THREAD

**Issue by user5001** [rapid7/metasploit-framework#12160]
please how to fix these kali linux 2019.2

**Comment by bcoles** [comment]
Please provide less information

**Comment by user5001** [comment]
how to fix metasploit in kali linux 2019.2 handler failed to bind

**Comment by ccondon-r7** [comment]
Closing this. If you're able to provide significantly more information, feel free to reopen! Take a look at our issue template for a list of the info we need from you. Cheers!
