### ISSUE TITLE
vuls.io scaning  tool plugin reqest. 

### ISSUE THREAD

**Issue by necrose99** [rapid7/metasploit-framework#12178]
https://vuls.io 
https://github.com/future-architect/vuls , 
noted also packaged on @pentoo or Gentoo + pentoo overlay
emerge app-admin/vuls 
 ... , 
(ebuild foo.ebuild..... rpm ) that and alien easy converts... 
vuls.io has webui also... 
using oval etc etc taxii feeds etc.. can scan github , network etc for cve vulns.. 
compiles on most platforms , BSD, Linux , Windows , Even IOT... 

[as a side order of fun , prior versions have compiled on ARM64/arm7hf .... 
meaning RPI3 or 4 , with metasploit and vuls as a dropin replacemnt of nexpose  on IOT is a very real deal... ]  meaning bashbuny , wifi pinaple , own kahli/pentoo linux on RPI or etc is very doable as value added recon..

**Comment by h00die** [comment]
Are you looking for a plugin to use vuls.io to do scanning, or a result importer (like how nessus results can be imported)?

**Comment by necrose99** [comment]
Yes for iot ie raspberrypi or rock64 , arm64 builds nicely..

Vuls.io repo is added to pentoo..   emerge app-admin/vuls. .
Vulsrepo webui also. Added.

Pentoo I've got a stalled stale port.. but can add back.. to online e soon.
Arm64-AMD 64 Windows/Linux crossdev gcc took some fair work in arm64 hosted
instance.

Anyway,  greenbone/openvas will run however  one can add other taxii feeds
to vuls.io,  ie alienvault's etc..
Nexpose wont as of yet has an arm64 sensors build..

And proff of vuln then use metasploit to prove it.

**Comment by h00die** [comment]
could you email a sanitized results file for us to look at and start building off of? If there's an xml/json or other machine readable format, that would be best.
msfdev@metasploit.com

**Comment by necrose99** [comment]
uses json files ie vulsrepo the web-ui parses them into graphs...

Wazuh/Ossec SIEM, (github also) uses vuls.io for its open source elastic
search SIEM.  For doing lan vulnerability scanning of hosts on blueteam
side.

Via ansible yml or prebuilt vm. Image.

Either qerrying lan vuls.io or on pentester tools,  especially rpi4/rpi3
etc , makes vuls.io a dropin replacemnt of nexpose,  for iot related
reconnaissance,  and if iot has crossdev or ct-ng,  can fire up metasploit
in a hurry.

[Nexpose ce , unfortunately hasn't a arm64 linux builds at the moment. ]

**Comment by necrose99** [comment]
pentoo has vuls in tree both www server / commandline client 
emerge www-vulsrepo , app-admin/vuls on pentoo live dvd or instsall to vm..
