### ISSUE TITLE
[F5 BIG-IP Cookie Disclosure] Keep the cookie and pool names

### ISSUE THREAD

**Issue by SkypLabs** [rapid7/metasploit-framework#12187]
Hello,

The module `modules/auxiliary/gather/f5_bigip_cookie_disclosure.rb`, which is used to enumerate BIG-IP load balancers' backend servers, stores those backend servers' addresses into the database as notes. However, the names of the cookies and of the pools are not kept even if they can contain useful information. As a few examples taken from a real data collection:

* Name of the company
* Hostnames
* Naming conventions
* Technologies of the backend servers (e.g. JBoss)
* Environment (e.g. production, staging)

As an improvement, it would be interesting to keep those information, especially when scanning a large set of remote hosts.

Thank you.

**Comment by h00die** [comment]
Seems logical, and the module is rather old so some other things (references) could be updated as well.
Would you feel comfortable submitting a PR with your changes, or do you have some examples you could give us to work off of?

**Comment by SkypLabs** [comment]
I haven't contributed to the Metasploit so far but it's something I wanted to do for a long time.

I will explore your API and submit a PR. It will be a good occasion for me to practice :+1:

**Comment by h00die** [comment]
hoping to get this done, waiting on @SkypLabs to help me configure my VM correctly.

**Comment by SkypLabs** [comment]
This feature has been added in https://github.com/rapid7/metasploit-framework/commit/7b11429b49c7e8cdc703d6a4f7ccd376a3237c8d.

Thanks again @h00die.
