### ISSUE TITLE
An approach of installing and updating metasploit-framework on msys2 or cygwin

### ISSUE THREAD

**Issue by 391861737** [rapid7/metasploit-framework#12206]
The `metasploit-framework.msi` installs the framework along with the entire msys2 environment which is unnecessarily needed when we have a msys2 platform installed already.  
And after some investigation and hardworking on building it from source on windows, I found it is nearly impossible to do that. Because the `pg-0.21.0-x64-mingw32` or `pg-0.21.0-x86-mingw32` requires ruby *< 2.5, >= 2.0*, while at the same time the metasploit-framework explicitly requires `pg-0.21.0`...  
So the only option left here is to install it using the msi package file built by omnibus. But I do not like the redundant msys2 bundled with it.
So I wrote a script to solve the problem and also provide an easy way to update it. But I do not know if this script is needed by others or not, so I'm here to see if there's any chance that I could be allowed to contribute this script here... 

[The script is here](https://github.com/391861737/msys2-msfupdate)

**Comment by 391861737** [comment]
Idk on which repository a PR of such a feature could be created, and where this script file should be laid. It'll be great if I could get some advice on this, and I'll be glad to create the PR!

**Comment by bwatters-r7** [comment]
This seems like something @jmartin-r7 might be interested in checking out.

**Comment by jmartin-r7** [comment]
We provide a method to create the windows build VM we use to create the msi here:
https://github.com/rapid7/metasploit-vagrant-builders

Our `build` process for metasploit can be found here:
https://github.com/rapid7/metasploit-omnibus

We are tracking an issue to remove the devkit that we currently bundle into the msi.  
https://github.com/rapid7/metasploit-omnibus/issues/97

**Comment by 391861737** [comment]
@jmartin-r7 That's cool! Thank you!

**Comment by jmartin-r7** [comment]
Closing this as not being addressed in this repo, feel free to add thoughts in rapid7/metasploit-omnibus#97
