### ISSUE TITLE
I could not use msfencode -e x86/fnstenv_mov -i at newest metasploit

### ISSUE THREAD

**Issue by Reslient** [rapid7/metasploit-framework#12237]
## Steps to reproduce

msfencode -e x86/fnstenv_mov -i inputbin -t perl -b \x00\x22'

HI I could not use as below mention newerst verion of Metasploit ? is there any equivalent what I have mention at msfvenom.Thanks alot

**Comment by timwr** [comment]
Something like `cat inputpin | msfvenom -p- -f perl -b "\x00\x22" -e x86/fnstenv_mod` ?

**Comment by ccondon-r7** [comment]
Hi there! We're closing this issue because it hasn't been active in a while.
