### ISSUE TITLE
Metsplot Database importing probelm 

### ISSUE THREAD

**Issue by majidali-jpg** [rapid7/metasploit-framework#12235]
i am using latest version of metasploit. But while importing database im am receaving this kind of problem....\\

msf5 > db_import Downloads/report-b11ac9c2-2527-420b-bbe2-30e8fb555544.xml
[-] Failed to import /root/Downloads/report-b11ac9c2-2527-420b-bbe2-30e8fb555544.xml: Could not automatically determine file type.

can anybody please resolve this i have tried every possibilities but got fail.
the report is downloaded from openvas.

**Comment by bcoles** [comment]
#7903
