### ISSUE TITLE
POST "Metasploit-Framework" installation returns this error after entering "msfconsole" 

### ISSUE THREAD

**Issue by AnonymousDarria** [rapid7/metasploit-framework#12242]
brad@brad-Latitude-E6320:/opt/metasploit-framework$ msfconsole
[*] Bundler failed to load and returned this error:

   'cannot load such file -- bundler/setup'

[*] You may need to uninstall or upgrade bundler
brad@brad-Latitude-E6320:/opt/metasploit-framework$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
brad@brad-Latitude-E6320:/opt/metasploit-framework$ sudo apt-get update
Ign:1 http://packages.linuxmint.com tina InRelease
Hit:2 http://packages.linuxmint.com tina Release                                  
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]       
Hit:4 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease           
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                        
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease                           
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]         
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]       
Fetched 252 kB in 1s (181 kB/s)                              
Reading package lists... Done
brad@brad-Latitude-E6320:/opt/metasploit-framework$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
brad@brad-Latitude-E6320:/opt/metasploit-framework$ msfconsole
[*] Bundler failed to load and returned this error:

   'cannot load such file -- bundler/setup'

[*] You may need to uninstall or upgrade bundler
brad@brad-Latitude-E6320:/opt/metasploit-framework$

**Comment by bcoles** [comment]
Perhaps `gem install bundler` ?

**Comment by kay6666** [comment]
E：无法打开锁定文件/ var / lib / apt / lists / lock - open（13：权限被拒绝）
E：无法锁定目录/ var / lib / apt / lists / 
我当时是直接sudo rm 删除这两个文件夹。
之后就能卸载重装了
