### ISSUE TITLE
Help me please my metasploit wont open

### ISSUE THREAD

**Issue by thehacker887** [rapid7/metasploit-framework#12248]
I "THINK" what caused it was an android reverse TCP payload im not sure thats the last thing i did when it was working. I am only 13 and im learning how to code and use this stuff so im not that good at it please help.

I keep getting this error which is below.

Traceback (most recent call last):ork console...|
        24: from /usr/bin/msfconsole:49:in `<main>'
        23: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        22: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        21: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        20: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
        19: from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize'
        18: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        17: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        16: from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        15: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        14: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        13: from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        12: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules'
        11: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `each'
        10: from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules'
         9: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
         8: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `each'
         7: from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
         6: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `recalculate'
         5: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:78:in `each_pair'
         4: from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:91:in `block in recalculate'
         3: from /usr/share/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
         2: from /usr/share/metasploit-framework/lib/msf/core/payload/android.rb:38:in `generate'
         1: from /usr/share/metasploit-framework/modules/payloads/singles/android/meterpreter_reverse_tcp.rb:44:in `generate_jar'
/usr/share/metasploit-framework/lib/msf/core/payload/android.rb:112:in `generate_jar': android/meterpreter.dex not found (RuntimeError)

I really dont know whats going on if someone would tell me what to do i will be so happy. Thank you

**Comment by timwr** [comment]
Did your antivirus delete meterpreter.dex?
You'll need to reinstall with antivirus disabled

**Comment by thehacker887** [comment]
Yes i did

**Comment by busterb** [comment]
Thanks, a file is missing on your system for some reason, so you will need to identify what it was and fix it. If you continue to have troubles (e.g. you cannot entirely uninstall AV), perhaps try installing into a fresh Linux virtual machine. It appears that this is Kali linux, so perhaps you do not have enough disk space available and Metasploit did not fully install? `apt install --reinstall metasploit-framework` will attempt to reinstall the latest version in Kali and should repair any missing files in the process.
