### ISSUE TITLE
[Suggestion] Add check for meterpreter.dex

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#12264]
A few issues have been posted relating to `android/meterpreter.dex not found (RuntimeError)`.

This file is vaporized by some anti-virus software. It might be worth the effort of adding a check to see if this file is missing and printing a nice error message.

This would be a more pleasant user experience and result in less support requests.

**Comment by busterb** [comment]
Thanks, good idea. Failure to generate a payload on boot should in general be a degraded experience rather than a system failure.
