### ISSUE TITLE
[Fedora] RPM Package Signature missing (GPG Check failed)

### ISSUE THREAD

**Issue by VainlyStrain** [rapid7/metasploit-framework#12260]
## Steps to reproduce

How'd you do it?

1. ...sudo dnf install metasploit-framework (after initial installation using the instructions here: https://fedoraproject.org/wiki/Metasploit_Penetration_Testing_Framework)
2. ...

Affected system: Fedora 29, metasploit-framework RPM version 5.0.46+20190830215202~1rapid7-1.el6.x86_64

## Expected behavior

Successful installation of the framework

## Current behavior

After downloading the package, the installing process fails due to missing signature.

Last metadata expiration check: 0:06:03 ago on Sat 31 Aug 2019 15:58:29 CEST.
Dependencies resolved.
===================================================================================================
 Package                  Arch       Version                                  Repository      Size
===================================================================================================
Installing:
 metasploit-framework     x86_64     5.0.46+20190830215202~1rapid7-1.el6      metasploit     205 M

Transaction Summary
===================================================================================================
Install  1 Package

Total download size: 205 M
Installed size: 457 M
Is this ok [y/N]: y
Downloading Packages:
metasploit-framework-5.0.46+20190830215202~1rapid7-1.el6.x86_64.rp 3.2 MB/s | 205 MB     01:04    
---------------------------------------------------------------------------------------------------
Total                                                              3.2 MB/s | 205 MB     01:04     
Package metasploit-framework-5.0.46+20190830215202~1rapid7-1.el6.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

### Metasploit version

metasploit-framework-5.0.46+20190830215202~1rapid7-1.el6.x86_64.rpm

### I installed Metasploit with:
- [ ] Omnibus installer (nightly)

### OS

Fedora 29

**Comment by jeffmcjunkin** [comment]
+1 on Ubuntu 18.04 x64:

```
jeff@blue:~$ sudo apt update
[...unrelated cruft...]
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease: The following signatures were invalid: EXPKEYSIG CDFB5FA52007B954 Metasploit <metasploit@rapid7.com>
W: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/InRelease  The following signatures were invalid: EXPKEYSIG CDFB5FA52007B954 Metasploit <metasploit@rapid7.com>
```

**Comment by Crumb93** [comment]
Is there a good way to find out if they've fixed their expired gpg key?

**Comment by busterb** [comment]
We updated GPG keys recently, but found in the process that some build systems need to be updated as well to handle the new keys. This will be updated as soon as we can get to it, definitely in progress.

**Comment by busterb** [comment]
The latest build adds the signatures with the newer signing keys for RPM packages, thanks for the note.
