### ISSUE TITLE
WARNING: The following packages cannot be authenticated!

### ISSUE THREAD

**Issue by sudorm1023** [rapid7/metasploit-framework#12270]
Installing metasploit-framework in  ubuntu16.04, it display the error:WARNING: The following packages cannot be authenticated!

![image](https://user-images.githubusercontent.com/46293337/64137433-d50f2a80-ce2a-11e9-8993-95b10c42edb9.png)
How to solve it?

**Comment by h00die** [comment]
Related to #12260 . Solution is wait a day or two for rapid7 to put out a new key

**Comment by rgooler** [comment]
Also stop using end of live'd OS releases. Ubuntu 16.04 was EoL in april.

**Comment by jeffmcjunkin** [comment]
I mean, I agree with moving to supported OS's, but 16.04 is supported through 2021: https://ubuntu.com/about/release-cycle

**Comment by busterb** [comment]
We updated GPG keys recently, but you will simply need to grab the updated installer file to get the latest key for Debian/Ubuntu. Follow the instructions on the wiki again and the issue should be resolved.
