### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by x0rz4** [rapid7/metasploit-framework#12285]
OS：Linux VM_0_15_centos 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> [root@centos ~]# ./msfinstall 
> Checking for and installing update..
> Adding metasploit-framework to your repository list..Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
> metasploit                                                                          | 2.9 kB  00:00:00     
> Resolving Dependencies
> --> Running transaction check
> ---> Package metasploit-framework.x86_64 0:5.0.47+20190906102426~1rapid7-1.el6 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ===========================================================================================================
>  Package                    Arch         Version                                    Repository        Size
> ===========================================================================================================
> Installing:
>  metasploit-framework       x86_64       5.0.47+20190906102426~1rapid7-1.el6        metasploit       205 M
> 
> Transaction Summary
> ===========================================================================================================
> Install  1 Package
> 
> Total size: 205 M
> Installed size: 457 M
> Downloading packages:
> 
> 
> Package metasploit-framework-5.0.47+20190906102426~1rapid7-1.el6.x86_64.rpm is not signed

1. Modify yum.conf
Path: vi /etc/yum.conf
Find gpgcheck = 1
Modify it to 0: gpgcheck = 0

**This method is useless.**

**Comment by busterb** [comment]
We updated GPG keys recently, but found in the process that some build systems need to be updated as well to handle the new keys. This will be updated as soon as we can get to it, definitely in progress. See #12260
