### ISSUE TITLE
service create not work.

### ISSUE THREAD

**Issue by Loperkan** [rapid7/metasploit-framework#12289]
When i use service_create in meterpreter.exe (builded by  msfvenom - work)
But, when i migrate to notepad.exe or other process, it isn't work, and return code "6" (handle not found, maybe)

**Comment by OJ** [comment]
You're trying to create a service from a non-admin session. In order to
create services you need to be elevated.

See
https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-createservicea

**Comment by Loperkan** [comment]
Even winlogon? I have rights.
