### ISSUE TITLE
send_request_cgi! redirection is only good for GET

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#12281]
`send_request_cgi!` is capable of redirecting but it's only ideal when the original request is GET. If it's something else, for example, a POST, then the redirected request is also a POST. 

Normally, if I originally send a POST request, the redirected version should be a GET request, not POST.

**Comment by wvu-r7** [comment]
Fixing this will fix the anti-pattern of avoiding `send_request_cgi!` and handling redirects manually.
