### ISSUE TITLE
[*] Metasploit requires the Bundler gem to be installed     $ gem install bundler

### ISSUE THREAD

**Issue by manirana1999** [rapid7/metasploit-framework#12306]
Suddenly stopped working, asking for gem, but not opening even after installig.

OS: Parrot (updated)
Ruby updated
![issue](https://user-images.githubusercontent.com/41586162/64616417-2787b280-d3fa-11e9-8c60-c736a2af6a1d.png)

**Comment by timwr** [comment]
Have you tried running `bundle install`?

**Comment by manirana1999** [comment]
Yes i did, that didn't work, but i found the solution.  I had to manually update gem.lock file and add latest entry of bundler version there. Thanks for reply.

**Comment by manirana1999** [comment]
Yes i did, that didn't work, but i found the solution.  I had to manually update gem.lock file and add latest entry of bundler version there. Thanks for reply.
