### ISSUE TITLE
Installer vs Git - how to add latest updates?

### ISSUE THREAD

**Issue by pandalatte** [rapid7/metasploit-framework#12307]
Hello everyone!

I've installed the latest MSF through one of the installers. It's now in /usr/bin and /opt
But how to I incorporate the latest pulls and updates (such as payloads and exps) from git ?
Should I remove it and reinstall through git clone? Thank you!

**Comment by space-r7** [comment]
If you're wanting to view/test the latest pull requests, then you should first set up Framework by cloning the repository. [Here's](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) a great tutorial that goes through the process of setting things up.
