### ISSUE TITLE
msfupdate error

### ISSUE THREAD

**Issue by M0dred** [rapid7/metasploit-framework#12329]
## Steps to reproduce

How'd you do it?

1. apt-get update

The following signatures were invalid: EXPKEYSIG CDFB5FA52007B954 Metasploit <metasploit@rapid7.com>

2. msfupdate

pdating package cache..W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease: The following signatures were invalid: EXPKEYSIG CDFB5FA52007B954 Metasploit <metasploit@rapid7.com>

What should happen?

his copy of metasploit-framework is more than two weeks old.
 Consider running 'msfupdate' to update to the latest version.

### Metasploit version
metasploit v5.0.43-dev- 

### OS

What OS are you running Metasploit on?

4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

**Comment by bcoles** [comment]
The key expired. #7336

```sh
sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys CDFB5FA52007B954
```

**Comment by M0dred** [comment]
Thanks, It's useful.

**Comment by space-r7** [comment]
Closing since this has been resolved.

**Comment by zo304** [comment]
thank you very much M0dred it's useful ^^

**Comment by brian30** [comment]
Thanks. Worked well.

**Comment by brokera** [comment]
> The key expired. #7336
> 
> ```shell
> sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys CDFB5FA52007B954
> ```

BackBox had the same key problem. Thanks to your prompt, the problem was solved.

**Comment by kenaley** [comment]
it didn't work
Adding metasploit-framework to your repository list..Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Updating package cache..W: http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://kali.download/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Failed to fetch http://http.kali.org/kali/dists/kali-rolling/InRelease  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
metasploit-framework is already the newest version (6.2.26+20221110112623~1rapid7-1).
The following packages were automatically installed and are no longer required:
  espeak-ng-data gir1.2-gstreamer-1.0 gir1.2-wnck-3.0 gsfonts imagemagick-6-common keyboard-configuration libfftw3-double3 liblqr-1-0 libmagickcore-6.q16-6
  libmagickwand-6.q16-6 libpipeline1 man-db
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 101 not upgraded.
