### ISSUE TITLE
Missing method `report_web_vuln` results in various exceptions.

### ISSUE THREAD

**Issue by elbowdonkey** [rapid7/metasploit-framework#12334]
## Steps to reproduce
1. run `msfconsole`
2. `load wmap`
3. Ensure you have a valid target
4. Ensure that your target has vulnerabilities that wmap can discover

## Expected behavior

wmap should be able to run the `auxiliary/scanner/http/brute_dirs` module without throwing exceptions related to the missing method `report_web_vuln`.

## Current behavior

Currently, the following exceptions are thrown:

```
Auxiliary failed: NoMethodError undefined method `report_web_vuln' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007fa1492f5610>
Call Stack:
  lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
  lib/msf/core/auxiliary/report.rb:363:in `report_web_vuln'
  modules/auxiliary/scanner/http/brute_dirs.rb:164:in `block (3 levels) in run_host'
```

And

```
Auxiliary failed: NoMethodError undefined method `id' for nil:NilClass
Call stack:
  lib/msf/core/auxiliary/report.rb:295:in `report_vuln'
  modules/auxiliary/scanner/http/trace.rb:47:in `run_host'
```

Both exceptions occur because there's no `report_web_vuln` in `lib/metasploit/framework/data_service/proxy/core.rb`, which is called from `lib/msf/core/auxiliary/report.rb` (and possibly other places).

### Metasploit version

4d9780f0703fac19cde6aa4ac2527066f0f7b85b

### I installed Metasploit with:

Installed from source.
Using ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin16]

### OS

macOS 10.12.6

**Comment by dwelch-r7** [comment]
Resolved in #12583 
not sure why it didn't auto resolve
