### ISSUE TITLE
bash: ./msfconsole: No such file or directory

### ISSUE THREAD

**Issue by ampf27** [rapid7/metasploit-framework#12331]
I have a script in a folder and when I try to run it from a terminal (both opened in that folder or anywhere else) by typing ./msfconsole -r 'path/to/the/script' or ./msfconsole -r 'path/to/the/script.rc' I get the message "bash: ./msfconsole: No such file or directory". I have tried to run with the <ruby> on the script too

I have the the kali 2019.3 version

What am I doing wrong? I have read your documentation but I don't understand what can be missing.

Thanks

**Comment by bcoles** [comment]
Is there a file called `msfconsole` in the current working directory? If so, does the file have the executable bit set?

I'm certain that this is not an issue with Metasploit. As such, reading the Metasploit documentation is not going to help.

**Comment by ampf27** [comment]
Thank you for your reply

I have run without the ./ and its fine now
