### ISSUE TITLE
session closed: reason died

### ISSUE THREAD

**Issue by mathanmithun** [rapid7/metasploit-framework#12348]
session closed: reason died

**Comment by bcoles** [comment]
The session has died and has been closed.

Perhaps the network connection dropped out.

Perhaps the process running the payload has died.

**Comment by mathanmithun** [comment]
no the net connection working good

**Comment by h00die** [comment]
To be fair, you didn't actually ask a question or try to tell about a potential but. You've given exactly 0 details about anything. @bcoles has tried to explain some of the potential reasons why your session could have died. Kudos to him for trying, but being that you have given no actual question on and given nothing to work off of, this is about the best you'll get. Perhaps read the Issues default text that you deleted, it will help us help you.

Also if you state the net connection is good, the only way you'd know that is to be running a network dump or mirror on the first switch on the target and msf side to be able to very that absolutely every packet sent was received. If you have that, please send us the ocap to verify.

**Comment by h00die** [comment]
For instance, is your question:
1. Why did my session die? (@bcoles attempted to answer that)
2. Why does my session die when I run keylog_dump
3. When I ran shutdown on the remote host my session died, but I'm not sure why
4. The Android phone went in an elevator how can I get my session back
5. Can this be reworded to `session closed: reason - died`
6. Why is my stager dying after the initial connect back
7. Can this be translated into German
8. My session died when migrating to another process on irix
9. My wifi died and this displayed on my windows computer and my target is a Mac
10. I ran sessions -K and this is displayed, and I'd like to thank everyone for cleanly killing off my memory resident meterpreter that I upgraded from Java 1.1
