### ISSUE TITLE
please solve this error

### ISSUE THREAD

**Issue by mathanmithun** [rapid7/metasploit-framework#12351]
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.10.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.4 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.10.4/gem_make.out

**Comment by busterb** [comment]
This would be a question for the Termux forums. Sorry, we don't have a way to test with Termux currently.
