### ISSUE TITLE
nokogiri error

### ISSUE THREAD

**Issue by mathanmithun** [rapid7/metasploit-framework#12350]
Could not find nokogiri-1.10.4 in any of the sources
Run `bundle install` to install missing gems.

**Comment by bwatters-r7** [comment]
Did you run `bundle install`?

**Comment by MoacirPetry** [comment]
Try delete the file "Gemfile.lock" and after that try the command: `bundle install`

**Comment by h00die** [comment]
also, try giving more details on what operating system you are running.  If this is termux, you'll have to ask them for help.

**Comment by jmartin-r7** [comment]
No additional details offered, closing as user env related, not a bug in framework project.
