### ISSUE TITLE
smb-enum users

### ISSUE THREAD

**Issue by calgaryy** [rapid7/metasploit-framework#12359]
## Steps to reproduce

How'd you do it?

1. ... run a scan
2. ... look at creds db
When scanning hosts on a network with this module, the "creds" db isn't populated.

## Expected behavior

When users are discovered, should be added to the creds db

## Current behavior

When users are discovered, are not added to the creds db

Framework Version: 5.0.41-dev

N.B. Figured this didn't really need all the system info

**Comment by fishsticksflafor** [comment]
Hello,
Oke I will do my best to get it done.
Looking for my book at the moment,
It's called "Metasploit for Dummy's" I still have a lot to learn... but I
will get this done
Thanks so much

Greetz Jeff

Op wo 25 sep. 2019 12:27 schreef calgary <notifications@github.com>:

**Comment by h00die** [comment]
It sure doesn't.
https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/smb/smb_enumusers.rb#L311
This could be a pretty quick addition for someone looking for an easy one.  Basically you could copy something like this: https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/smb/smb_login.rb#L185


However, it can also be argued that these usernames aren't creds, theyre usernames, and until they turn into more you wouldn't want them cluttering up the DB.

**Comment by 0x44434241** [comment]
Hello, I've submitted an initial PR above to store these credentials in the database.

**Comment by ccondon-r7** [comment]
@0x44434241 what's the PR number?

**Comment by ccondon-r7** [comment]
Hey @0x44434241, we'll see if we can take a look at your PR this week. PRs that solve open issues are some of my favorites—much appreciated :)

**Comment by 0x44434241** [comment]
Thanks for the reply! It's PR #12929 .

**Comment by space-r7** [comment]
Fixed in #12929.
