### ISSUE TITLE
gem fails to install mysqlite3

### ISSUE THREAD

**Issue by CodeWithLinc** [rapid7/metasploit-framework#12362]
SQLITE3 FAILURE
![Screenshot_20190925-182226](https://user-images.githubusercontent.com/55532988/65621503-2b9ffc80-dfc4-11e9-9656-f0b23417c3ed.png)

LOCATION OF FAILURE
![Screenshot_20190925-182350](https://user-images.githubusercontent.com/55532988/65621575-52f6c980-dfc4-11e9-8ab2-5e2b1a8ef4fd.png)

ACTUAL LOG (FAILURE)
![Screenshot_20190925-182951](https://user-images.githubusercontent.com/55532988/65621616-63a73f80-dfc4-11e9-95ec-ecd986959d60.png)

Please help....

**Comment by h00die** [comment]
It looks like you are using tremux. Metasploit does not support termux, please send all questions related to termux to the termux forums or other related help channels

**Comment by CodeWithLinc** [comment]
Thank you for your response!!! Sorry for the Delay!!!
