### ISSUE TITLE
execute-assembly

### ISSUE THREAD

**Issue by akefallonitis** [rapid7/metasploit-framework#12379]
I cant find any issue in execute-assembly for MSF

https://github.com/b4rtik/metasploit-execute-assembly

I propose to open one. Thanks

**Comment by bwatters-r7** [comment]
Are you saying you'd like to add an issue in https://github.com/b4rtik/metasploit-execute-assembly?  That's a different repo we do not control.

Are you asking to pull the features in that repo into metasploit?

**Comment by akefallonitis** [comment]
I know its a different repo :)

I was asking to merge it with metasploit repo !

**Comment by bwatters-r7** [comment]
I think we did this.....?  Thanks @h00die
