### ISSUE TITLE
Update metasploit v4 without moving to v5

### ISSUE THREAD

**Issue by alme5** [rapid7/metasploit-framework#12373]
Hello all. A little help if possible please. I am running Kali 2018 v1 with metasploit v4.17.9-dev. I don't want to update to version 5 because this is not fully compatible with Armitage and I really need this tool due to some courses I teach at my local community. I have noticed that version 4.17 keeps on updating with version 4.17.84 released few days ago (https://github.com/rapid7/metasploit-framework/releases/tag/4.17.84). My question is how do I update my current version of msf without upgrading to v5? apt install metasploit-framework upgrades the entire msf to v5 but I want to keep staying on v4 and receive the updates released. Thank you for your time.

**Comment by zeroSteiner** [comment]
You may need to transition to a git-checkout based install. This would give you much more control over the exact version you're running down to a specific commit. Steps for how to do this are in the wiki under [Setting Up a Metasploit Development Environment](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment). The process is a little more involved so beware.

Once you've done that though you should be able to use `git` to checkout the specific version you want based on the tag.

Once your environment is setup, you should be able to run the following:
```
git checkout 4.17.84
bundle install
./msfconsole
```

**Comment by jmartin-r7** [comment]
You may also build you own packages to install based on https://github.com/rapid7/metasploit-omnibus.

Do keep in mind `Armitage` is not officially supported no matter the version and 4.x will not continue indefinitely.
