### ISSUE TITLE
RPC (msgpack) requests takes up to 100 seconds; msfconsole front-end is unaffected

### ISSUE THREAD

**Issue by FenixH** [rapid7/metasploit-framework#12411]
## Steps to reproduce

How'd you do it?

1. Start msfrpcd server as a background process or through msfconsole. Both provide the same outcome. Its settings do not seem to matter.
2. Start a few background jobs. Each job seemingly increases the problem next to linearly. 
3. Make any authenticated RPC request (either with generated or permanent token)

In my case, if step 3 is a meterpreter shell command, the problem is significantly worse
(spawn a meterpreter shell on a machine (in my case, a windows/x64/meterpreter/bind_tcp on a windows 2008 R2); run a meterpreter command on the shell, e.g., "ifconfig").

## Expected behavior
The time required to execute a command and read its output should be similar for RPC and msfconsole front-end.

## Current behavior
All RPC requests are much slower with a few background jobs running. For example, listing jobs or sessions takes a few seconds instead of less than a second. The msfconsole front-end seems completely unaffected by these issues. 

This problem is especially large for meterpreter shell commands:

A meterpreter command that takes approximately a second to run on an msfconsole front-end can take up to/more than 100 seconds using RPC if a few background processes are running (with the RPC server running from within the msfconsole). In my case, three multi/handlers with default settings (but different LPORT values) is enough to increase the time for RPC meterpreter .write()/ .read() with about 20 seconds. The other RPC meterpreter shell endpoint with similar functionality such as .run_single() perform the same. The same commands in msfconsole provide next to instant feedback.

If no background jobs are started (step 2 in the list above), the execution time is similar for RPC and msfconsole front-end commands (as expected). The CPU/RAM utilization during a request is pretty much the same regardless if a few jobs are started or not (~50% CPU, ~6% RAM), so that does not seem to be the issue.

## System stuff
6K RAM, 3.5Ghz Xeon CPU

### Metasploit version
metasploit v5.0.13-dev 

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
Kali 2019.2

**Comment by FenixH** [comment]
This issue is not existing in the latest Kali/metasploit apt-version.

**Comment by zeval** [comment]
Currently facing the exact same issue on a container running Ubuntu 24.10 (rolling), Metasploit 6.4.43-dev.
