### ISSUE TITLE
msfconsole  error

### ISSUE THREAD

**Issue by M0dred** [rapid7/metasploit-framework#12449]
[-] ***rting the Metasploit Framework console.../
[-] * WARNING: No database support: FATAL:  password authentication failed for user "msf"
FATAL:  password authentication failed for user "msf"

[-] ***
### OS

What OS are you running Metasploit on?
3.16.0-4-686-pae #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) i686 GNU/Linux

**Comment by bwatters-r7** [comment]
This appears similar to https://github.com/rapid7/metasploit-framework/issues/9696

**Comment by The-mula** [comment]
root@termux[metasploit-framework]:
# msfconsole
[-] ***rting the MetaspLoit Framework console...\
[-] * WARNING: No database support: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

[-] ***
[*] Starting the Metasploit Framework console.../

**Comment by bcoles** [comment]
@The-mula 

Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715

**Comment by HolliPolliMitHumor** [comment]
> [-] ***rting the Metasploit Framework console.../
> [-] * WARNING: No database support: FATAL: password authentication failed for user "msf"
> FATAL: password authentication failed for user "msf"
> 
> [-] ***
> 
> ### OS
> What OS are you running Metasploit on?
> 3.16.0-4-686-pae #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) i686 GNU/Linux

--> Might be Nexpose. Uses the same port as metasploit. whatever comes up first gets to connect

**Comment by manish53393679** [comment]
after trying  many options , the only one which worked is update and upgrade the kali 

1. sudo apt-get update
2. sudo apt-get upgrade

thanx
