### ISSUE TITLE
While installing it says nokogiri not found 

### ISSUE THREAD

**Issue by Umair-mansuri** [rapid7/metasploit-framework#12447]
If you'd like to propose a feature, describe what you'd like to see. Mock ups of console views would be great.

If you're reporting a bug, please be sure to include the expected behavior, the observed behavior, and steps to reproduce the problem. Resource scripts, console copy-pastes, and any background on the environment would be appreciated.

For tips, see http://r-7.co/MSF-CONTRIB

**Comment by space-r7** [comment]
Hi @Umair-mansuri, it looks like you'll likely need to run the command, `bundle install` to fix this issue. If that does not work, please post more details regarding your installation.
