### ISSUE TITLE
Metasploit Error in win7

### ISSUE THREAD

**Issue by EITSxiaozhai** [rapid7/metasploit-framework#12504]
This problem is not found in win10, but in win7

Traceback (most recent call last):
        6: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        5: from <internal:gem_prelude>:2:in `require'
        4: from F:/metasploit-framework/embedded/lib/ruby/site_ruby/2.6.0/rubygems.rb:117:in `<top (required)>'
        3: from F:/metasploit-framework/embedded/lib/ruby/site_ruby/2.6.0/rubygems.rb:1362:in `<module:Gem>'
        2: from F:/metasploit-framework/embedded/lib/ruby/site_ruby/2.6.0/rubygems.rb:1362:in `require'
        1: from F:/metasploit-framework/embedded/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:18:in `<top (required)>'
F:/metasploit-framework/embedded/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:18:in `require': incompatible library version - F:/metasploit-framework/embedded/lib/ruby/2.6.0/x64-mingw32/stringio.so (LoadError)

Metasploit 5.0v All have this problem。

**Comment by bcoles** [comment]
Unfortunately Windows 7 is no longer supported. (Related: #11581, #11396, #11324)

Using Metasploit from the git repo, rather than the nightly installer, may or may not work with an older version of Ruby. Personally, I wouldn't advise it.

**Comment by kurtkraut2** [comment]
shame to rapid7 close support to windows 7 when it getting not support from microsoft neither, microsoft brougth rapid7 or u getting now the bitch of it??

**Comment by kurtkraut2** [comment]
rapid7 is no the bitch of microsoft? ending the support in the same time, they brought you??? SHAME TO U

**Comment by kurtkraut2** [comment]
rapid7 is now the bitch of microsoft? ending the support in the same time, they brought you??? SHAME TO U

**Comment by bcoles** [comment]
> 
> 
> rapid7 is now the bitch of microsoft? ending the support in the same time, they brought you??? SHAME TO U

The issue is due to the [Ruby installer](https://rubyinstaller.org/), which is apparently not compatible with Windows 7. See https://github.com/rapid7/metasploit-framework/issues/11396#issuecomment-464583014

Using Metasploit from the git repo, rather than the nightly installer, may or may not work with an older version of Ruby. Personally, I wouldn't advise it, nor would I advise running Ruby on Windows.

Or use Linux.
