### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by sbrun** [rapid7/metasploit-framework#12506]
Python 2.x will no longer be supported by their upstream developers in 2020.
Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).

Kali is tracking Debian Testing and is thus affected by this.

You should consider to switch the Python 2 scripts to Python 3.

Thanks

**Comment by xmunoz** [comment]
Here is a list of all the python files in this repository:
https://github.com/rapid7/metasploit-framework/search?l=python

I'll take a stab at this using an auto translator: https://docs.python.org/3.0/library/2to3.html
