### ISSUE TITLE
I don't have stdapi

### ISSUE THREAD

**Issue by Logancoldd** [rapid7/metasploit-framework#12514]
I have gotten multiple shells on many different boxes on both Kali and Mint. However, when I use meterpreter I cannot use stdapi commands and I cannot load stdapi. So naturally, I navigated to /usr/share/metasploit-framework/plugins to see what the problem was. I found I don't have the plugin. Is there a fix to this? I installed by using "apt" on Mint and it was preinstalled in Kali.

### OS

What OS are you running Metasploit on?
Linux Mint & Kali Linux

**Comment by bcoles** [comment]
Logs please.

`stdapi` is the standard API. You won't find it in the plugins folder.

Lack of `stdapi` implies that the session failed to initialise.
