### ISSUE TITLE
Error running metasploit !

### ISSUE THREAD

**Issue by youssrii** [rapid7/metasploit-framework#12518]
I got this error when try to launch metasploit 3 days ago.. i think it's related to ruby-gems stuff.
Any help would be greatly appreciated.

**root@dhcppc1**:~# _msfconsole_ 
Traceback (most recent call last):
	4: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
	3: from <internal:gem_prelude>:2:in `require'
	2: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:1309:in `<top (required)>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:1309:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:34:in `<top (required)>': uninitialized constant Gem::BasicSpecification (NameError)

### Metasploit version
Latest 

### I installed Metasploit with:
- [x] Kali package via apt

### OS
Kali linux 2019.3

**Comment by dustineichler** [comment]
likely an issue with however ruby was installed.

**Comment by youssrii** [comment]
via apt.. any ideas to fix that !
