### ISSUE TITLE
Trigger database events

### ISSUE THREAD

**Issue by pastaoficial** [rapid7/metasploit-framework#12520]
Hi all, I'm writing a plugin for the 5.x version with custom database events similar to [libnotify](https://github.com/rapid7/metasploit-framework/pull/9270)

but the events couldn't be triggered. Have you been working on this?

I tried without successful with:
* on_db_host
* on_db_host_state
* on_db_service

**Comment by wvu-r7** [comment]
@mkienow-r7: Any ideas here? I haven't looked at the DB hooks in a long time.

**Comment by mkienow-r7** [comment]
@pastaoficial @wvu-r7 Perhaps the details in #9270 would prove to be helpful?

**Comment by pastaoficial** [comment]
@mkienow-r7 I have a similar code but does not work. Probably these handlers are out of the 5.x version

[check this quote](https://github.com/rapid7/metasploit-framework/pull/9270#issuecomment-361720956)

**Comment by mkienow-r7** [comment]
I don't believe those events are currently sent over the wire in a remote data service use of MSF5. If you run `db_status` does it show you are connected to a remote data service on localhost? If so, does running the command `db_disconnect` once before loading your plugin change the behavior?

**Comment by pastaoficial** [comment]
the behavior doesn't change

db_status said:

I use the other plugin to check the events launched:
`[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.`

Checking with the plugin event_tester I have seen when on_db_hosts was dispatched in 4.x (prior to 13 maybe, sorry I don't remember the exact version) in 5.x there aren't these events

**Comment by mkienow-r7** [comment]
To confirm, you've performed the following steps before attempting to load your plugin? If so, then it is possible MSF5 broke compatibility with the database events and we should first aim to get those working again in the `local_db_service`, and then passing the events back over the wire with the `remote_data_service`.

```
msf5 > db_status 
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf5 > db_disconnect 
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
msf5 > db_disconnect 
Successfully disconnected from the data service: local_db_service.
```

**Comment by mkienow-r7** [comment]
I performed a quick test myself and the test plugin `test_dbevents` from #9270 appears to be working. Both the "New host" and "Host change" status messages are from the plugin code.

Drop back to 
```
msf5 > db_status 
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf5 > db_disconnect 
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
msf5 > db_status 
[*] Connected to msf. Connection type: postgresql.
```

Load the test plugin `test_dbevents` and add a new host:
```
msf5 > load test_dbevents
msf5 > hosts --add 1.1.1.1
[*] New host: #<Mdm::Host:0x00007f90f7cf2e40>
[*] Host change: #<Mdm::Host:0x00007f90f7cf2e40>, ostate: 
[*] Time: 2019-10-31 21:02:24 UTC Host: host=1.1.1.1
```

**Comment by pastaoficial** [comment]
You are alright :dancer: , after those commands I can see the database's events

```
msf5 > db_status                                                                                         
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: l
ocal-https-data-service.                                                                                 
msf5 > db_disconnect                                                                                     
Successfully disconnected from the data service: remote_data_service: (https://localhost:5443).
msf5 > db_status                      
[*] Connected to msf. Connection type: postgresql.
```

Now when I add a host:

```
msf5 > hosts -a 192.168.20.11               
Event fired: on_ui_command(hosts -a 192.168.20.11)
Event fired: on_db_host(#<Mdm::Host:0x0000000009846238>)                          
Event fired: on_db_host_state(#<Mdm::Host:0x0000000009846238>, )                  
[*] Time: 2019-11-01 14:31:59 UTC Host: host=192.168.20.11
```

so, to make a summary... the events aren't triggered with a remote database, right?

**Comment by pastaoficial** [comment]
> **Note**, the plugin does not work correctly when connected to the database via a `remote_data_service`:

thanks for the help, in a couple of days I will do a pull request

**Comment by mkienow-r7** [comment]
The events are likely firing on the remote side, but that is inside of the service started by `msfdb`. The plugin that registers itself as an event subscriber (`self.framework.events.add_db_subscriber`), however, is in the context of your `msfconsole`. We need to take a look at the data services architecture and design a means of extending it to support sending asynchronous event data to registered clients.
