### ISSUE TITLE
Scanner modules: explain that THREADS option only works with multiple hosts

### ISSUE THREAD

**Issue by cnotin** [rapid7/metasploit-framework#12521]
Brute-force modules based on `Auxiliary::Scanner`, such as smb_login or ssh_login, have a THREADS option:
https://github.com/rapid7/metasploit-framework/blob/641ecb65cac16accc127f9b2995c378a14e30f4b/lib/msf/core/auxiliary/scanner.rb#L21

Observation: it only starts multiple threads if there are many hosts to scan. It cannot start 10 threads against one host, and it cannot start 500 threads against just 10 hosts.
This can be counter-intuitive for some users, like me, and causes issues such as #4575
[Confirmed](https://github.com/rapid7/metasploit-framework/issues/4575#issuecomment-70725698) by @wchen-r7:
> So the function of THREADS is to allow MSF to try the module against multiple hosts at the same time, one thread per host

Suggestion:
* implement multiple threads for each host -> complicated as @wchen-r7 said:
> To achieve that the module will have to do this on its own

* or, we could make the description of "THREADS" more explicit. What do you think of this?
> The number of concurrent threads **(max 1 per rhost)**

If ok I can submit a PR

**Comment by wvu-r7** [comment]
I think a description change is good right now. Threading _properly_ is not a trivial undertaking in Framework.

**Comment by cnotin** [comment]
PR done :)
