### ISSUE TITLE
BLUEKEEP ERROR

### ISSUE THREAD

**Issue by L3TU5** [rapid7/metasploit-framework#12539]
![64778713-f2f92f80-d58e-11e9-937a-05c31251ea03](https://user-images.githubusercontent.com/53816989/68163592-29ce3f00-ff5b-11e9-9fc3-638c387a6215.png)

Is the problem in the groomsize or what?  Please help I've tried bunch of combinations but didn't succeed

**Comment by wvu-r7** [comment]
Usually, the "problem" is `GROOMBASE`. It says you're targeting VMware 14. Is that correct?

**Comment by wvu-r7** [comment]
Try changing `GROOMBASE` after finding NPP base in WinDbg.
