### ISSUE TITLE
Can't msf5 be used on win7 now

### ISSUE THREAD

**Issue by EITSxiaozhai** [rapid7/metasploit-framework#12540]
Can't msf5 be used on win7 now?
If not, it's too bad. I hope it can be used on win7

**Comment by wvu-r7** [comment]
Running Metasploit on Windows isn't supported very well. Also, you should be upgrading to Windows 10 by now. :)

I suggest a Linux virtual machine.

**Comment by bcoles** [comment]
Unfortunately Windows 7 is no longer supported. (Related: #11581, #11396, #11324)

Using Metasploit from the git repo, rather than the nightly installer, may or may not work with an older version of Ruby. Personally, I wouldn't advise it.
