### ISSUE TITLE
Add OSVDB reference to iis_internal_ip module

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#12558]
https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/http/iis_internal_ip.rb

Add OSVDB reference.  Nikto has it as the following:
```+ OSVDB-630: GET The web server may reveal its internal or real IP in the Location header via a request to / over HTTP/1.0```

**Comment by h00die** [comment]
Removing them because of bad links I can't dispute.  However, I think the solution is to remove the link.  When other tools still refer to them, it would be nice to be able to `search osvdb-630` and get the right module.  Especially since this module in particular has 0 references in it

**Comment by bcoles** [comment]
> Especially since this module in particular has 0 references in it

How about:

```ruby
['BID', '1499'],
['CVE', '2000-0649']
```
