### ISSUE TITLE
webcam_start: Operation failed: 1

### ISSUE THREAD

**Issue by abd791** [rapid7/metasploit-framework#12566]
Hi guys 
why this command dont work on android 9 ? 
I trid same command on androud 8 it worked fine but on android 9 dont work 
How to fix it ? 
webcam_snap -i 2 
[*] Starting...
[*] Stopped
[-] webcam_start: Operation failed: 1

**Comment by abd791** [comment]
No one can help?

**Comment by abd791** [comment]
@timwr  help me please

**Comment by timwr** [comment]
Which device? Have you checked the error with adb logcat?
I believe it's working on Android 9 but on some devices either:
1. The deprecated Camera API that we use (replaced by Camera2) is unsupported on the device.
2. The hack to use to display a preview surface isn't working.

**Comment by abd791** [comment]
> Which device? Have you checked the error with adb logcat?
> I believe it's working on Android 9 but on some devices either:
> 
> 1. The deprecated Camera API that we use (replaced by Camera2) is unsupported on the device.
> 2. The hack to use to display a preview surface isn't working.

I tested on 2 devices samsung a50 and m30s 
I don't know how to check adb logcat
Note: the comand webcam_snap working only if i open the app like screenshot command so how we  can fix it ?

**Comment by timwr** [comment]
Please learn how to use adb, it will help a lot. I suspect the issue is the preview surface if it only works while the app is open.

**Comment by abd791** [comment]
> Please learn how to use adb, it will help a lot. I suspect the issue is the preview surface if it only works while the app is open.

If the issue is the preview surface can i fix it and how can i fix it please?

**Comment by abd791** [comment]
@timwr

**Comment by timwr** [comment]
Can you post the adb logcat of the error please?

**Comment by abd791** [comment]
> Can you post the adb logcat of the error please?

Yes i can but please give me the coomand of adb logcat to get log of my application only not all apps

**Comment by abd791** [comment]
> Can you post the adb logcat of the error please?

Locked:1133: Caller "com.fw.appshare" (PID 10307, UID 1560) cannot open camera "0" from background' 11-15 16:34:15.026 1560 1635 W System.err: java.lang.reflect.InvocationTargetException 11-15 16:34:15.027 1560 1635 W System.err: at java.lang.reflect.Method.invoke(Native Method) 11-15 16:34:15.027 1560 1635 W System.err: at com.metasploit.meterpreter.android.webcam_start_android.execute(webcam_start_android.java:34) 11-15 16:34:15.027 1560 1635 W System.err: at com.metasploit.meterpreter.CommandManager.executeCommand(Unknown Source:14) 11-15 16:34:15.027 1560 1635 W System.err: at com.metasploit.meterpreter.HttpTransport.dispatch(Unknown Source:49) 11-15 16:34:15.028 1560 1635 W System.err: at com.metasploit.meterpreter.Meterpreter.startExecuting(Unknown Source:32) 11-15 16:34:15.028 1560 1635 W System.err: at com.metasploit.meterpreter.AndroidMeterpreter.<init>(AndroidMeterpreter.java:102) 11-15 16:34:15.028 1560 1635 W System.err: at java.lang.reflect.Constructor.newInstance0(Native Method) 11-15 16:34:15.028 1560 1635 W System.err: at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 11-15 16:34:15.029 1560 1635 W System.err: at androidpayload.stage.Meterpreter.start(Meterpreter.java:49) 11-15 16:34:15.029 1560 1635 W System.err: at java.lang.reflect.Method.invoke(Native Method) 11-15 16:34:15.029 1560 1635 W System.err: at com.fw.appshare.blqeg.Stqjg.a(Unknown Source:247) 11-15 16:34:15.029 1560 1635 W System.err: at com.fw.appshare.blqeg.Stqjg.main(Unknown Source:291) 11-15 16:34:15.029 1560 1635 W System.err: at com.fw.appshare.blqeg.d.run(Unknown Source:1) 11-15 16:34:15.030 1560 1635 W System.err: Caused by: java.lang.RuntimeException: Fail to connect to camera service 11-15 16:34:15.030 1560 1635 W System.err: at android.hardware.Camera.<init>(Camera.java:562) 11-15 16:34:15.030 1560 1635 W System.err: at android.hardware.Camera.open(Camera.java:399) 11-15 16:34:15.030 1560 1635 W System.err: ... 13 more 11-15 16:34:15.033 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:15.336 1560 1635 I chatty : uid=10307(com.fw.appshare) Thread-21 identical 2 lines 11-15 16:34:15.337 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:15.652 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:15.882 1560 1635 I chatty : uid=10307(com.fw.appshare) Thread-21 identical 2 lines 11-15 16:34:15.883 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:16.111 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:16.111 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:16.552 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.178 1560 1635 I chatty : uid=10307(com.fw.appshare) Thread-21 identical 4 lines 11-15 16:34:17.178 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.464 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.465 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.741 1560 1627 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.742 1560 1627 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.772 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:17.772 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:18.174 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false 11-15 16:34:18.175 1560 1635 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by timwr** [comment]
Intereresting: `cannot open camera "0" from background'`
This appears to be mentioned here: https://developer.android.com/guide/topics/media/camera
`Foreground Services Requirement - When does your app interact with the camera? On Android 9 (API level 28) and later, apps running in the background cannot access the camera. Therefore, you should use the camera either when your app is in the foreground or as part of a foreground service.`
Can you try injecting into a different application rather than com.fw.appshare?, e.g https://github.com/heavysixer/phonegap-camera-sample/blob/master/bin/CameraSample.apk

**Comment by abd791** [comment]
> Intereresting: `cannot open camera "0" from background'`
> This appears to be mentioned here: https://developer.android.com/guide/topics/media/camera
> `Foreground Services Requirement - When does your app interact with the camera? On Android 9 (API level 28) and later, apps running in the background cannot access the camera. Therefore, you should use the camera either when your app is in the foreground or as part of a foreground service.`
> Can you try injecting into a different application rather than com.fw.appshare?, e.g https://github.com/heavysixer/phonegap-camera-sample/blob/master/bin/CameraSample.apk

I tried injecting into a different app and i got the same issue 
Also i tried the payload only, with out injecting into an app, the command web snap works in first time but after i did restart phone i got meterpreter session but the command did not work again  so i think  the issue is in the payload itself with android 9 only becouse in android 8 works fine 
now how we can fix it please?

**Comment by abd791** [comment]
Also i noticed that  command record mic does no work you will get record file but without any voice only if i open the app or payload i can get record with sound

**Comment by timwr** [comment]
I'm actually not sure how to fix this.
We could try spawn some kind of non-visible UI before doing the webcam_snap, this is what we do already but it's clearly not working: https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/library/src/com/metasploit/meterpreter/android/webcam_start_android.java#L77

**Comment by abd791** [comment]
I mean is it possible to do an update for Metasploit for fix the issue soon ?

**Comment by timwr** [comment]
I don't think I can fix this quickly. You'll have to be patient

**Comment by abd791** [comment]
Ok thank you i will waiting for you

**Comment by sw1tch-bl4d3** [comment]
Had the same problem, fix is here https://github.com/rapid7/metasploit-framework/issues/12621

**Comment by abd791** [comment]
@timwr  any update about the issue??

**Comment by abd791** [comment]
@timwr

**Comment by girish1234-dotcom** [comment]
Same issue here operation failed 1 for every command please help

**Comment by girish1234-dotcom** [comment]
Any update yet??

**Comment by girish1234-dotcom** [comment]
@abd791 i found the cause. It’s because the android device blocks the permission of your payload app . Go to settings and give permission to camera or whatever command which says operation failed and you should be good to go.

**Comment by ashishm641** [comment]
> Hi guys 
> why this command dont work on android 9 ? 
> I trid same command on androud 8 it worked fine but on android 9 dont work 
> How to fix it ? 
> webcam_snap -i 2 
> [*] Starting...
> [*] Stopped
> [-] webcam_start: Operation failed: 1

I have same problem..how can I fix it??any update

**Comment by Arreyan** [comment]
The Webcam_snap command comes out to be very moody like a teenager on my devices, cause it some time works and sometimes exits by showing the  error (Operation failed:1)...lol.

**Comment by kunal3210** [comment]
@abd791 No this has not to do anything with the android version its just all about the app permissions. When i opened the app permissions for that specific app it turns out that the app doesn't have any permission granted while installing it. And then when i manually granted all the permissions, i could easily gain access to camera, mic, etc.

**Comment by psy451** [comment]
anyone can't solve this??
I have the same problem..

**Comment by ankitkaser** [comment]
I gotta solution about this, it happen bcz in letest Android version you should always be on payload interface not even background.

**Comment by mikelkarma** [comment]
https://github.com/mikelkarma/Meterpreter-Android
I solved the problem.
```
meterpreter > sysinfo
Computer        : localhost
OS              : Android 13 - Linux 4.19.191-perf-g3c7e48ca8847 (aarch64)
Architecture    : aarch64
System Language : pt_BR
Meterpreter     : dalvik/android
meterpreter > webcam_snap -i 2
[*] Starting...
[+] Got frame
[*] Stopped
Webcam shot saved to: /root/android/bOjFlXzC.jpeg
meterpreter > record_mic -d 5
[*] Starting...
[*] Stopped
Audio saved to: /root/android/TLbcSexf.wav
meterpreter >
```
