### ISSUE TITLE
portscan/syn faild on windows10

### ISSUE THREAD

**Issue by ratsafalig** [rapid7/metasploit-framework#12560]
i try scanner/portscan/syn module on windows10 to scan a ip addr,
and it just dont work,
and wireshark shows that it dont even send the 'tcp syn'package,but it work perfect when i changed to use scanner/portscan/tcp module,
what went wrong

**Comment by wvu-r7** [comment]
Are you root, or do you otherwise have raw socket capabilities?

**Comment by ratsafalig** [comment]
well thanks...i forget i didnot have raw socket capability
