### ISSUE TITLE
Can't connect to my Openvas (appliance) using MSF5 

### ISSUE THREAD

**Issue by ayadim** [rapid7/metasploit-framework#12596]
Hi every one as i motioned in the Title 

i want to connect my  MSF5 to openvas appliance using the openvas plugin 
 i try the simple command : 
msf5> openvas_connect admin ********* 192.168.1.229 9390

i try to scan my appliance i did not get any open port just port 80/443 for the web interface 

each time i try to connect via msf5 to openvas i get this message 

[*] Connecting to OpenVAS instance at 192.168.1.229:9390 with username admin...
[-] Error while running command openvas_connect: uninitialized constant OpenVASOMP::OMPConnectionError

Call stack:
/usr/share/metasploit-framework/plugins/openvas.rb:195:in `rescue in cmd_openvas_connect'
/usr/share/metasploit-framework/plugins/openvas.rb:189:in `cmd_openvas_connect'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:49:in `<main>'

## Current behavior

What happens instead?

### I installed Metasploit with:
- [ ] Kali package via apt
-

### OS

Kali linux

**Comment by bcoles** [comment]
Are you still receiving this error?

I was only able to reproduce the error when OpenVAS was not listening.

```
msf5 > load openvas
[*] Welcome to OpenVAS integration by kost and averagesecurityguy.
[*] 
[*] OpenVAS integration requires a database connection. Once the 
[*] database is ready, connect to the OpenVAS server using openvas_connect.
[*] For additional commands use openvas_help.
[*] 
[*] Successfully loaded plugin: OpenVAS
msf5 > openvas_connect admin admin 127.0.0.1 9390
[*] Connecting to OpenVAS instance at 127.0.0.1:9390 with username admin...
[-] Error while running command openvas_connect: uninitialized constant OpenVASOMP::OMPConnectionError

Call stack:
/root/Desktop/metasploit-framework/plugins/openvas.rb:195:in `rescue in cmd_openvas_connect'
/root/Desktop/metasploit-framework/plugins/openvas.rb:189:in `cmd_openvas_connect'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/root/Desktop/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/root/Desktop/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/root/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
msf5 > lsof -i :9390
[*] exec: lsof -i :9390

msf5 > service openvas-manager start
[*] exec: service openvas-manager start

msf5 > lsof -i :9390
[*] exec: lsof -i :9390

COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openvasmd 34750 root    4u  IPv4 733149      0t0  TCP localhost:9390 (LISTEN)
msf5 > openvas_connect admin admin 127.0.0.1 9390
[*] Connecting to OpenVAS instance at 127.0.0.1:9390 with username admin...
/var/lib/gems/2.5.0/gems/openvas-omp-0.0.4/lib/openvas-omp.rb:201: warning: Object#timeout is deprecated, use Timeout.timeout instead.
[+] OpenVAS connection successful
msf5 > 
```

**Comment by bcoles** [comment]
> i try to scan my appliance i did not get any open port just port 80/443 for the web interface

The OpenVAS plugin uses the TCP service on port 9390. If this port is not open (or firewalled) then you will not be able to connect to the TCP service, resulting in the above error.

Refer to the `Installation and Setup` section of https://wiki.networksecuritytoolkit.org/index.php/OpenVAS or `Getting started` section of https://wiki.archlinux.org/index.php/OpenVAS for more info.
