### ISSUE TITLE
smscarrier

### ISSUE THREAD

**Issue by azamet90** [rapid7/metasploit-framework#12608]
since im in mongolia i need the smscarrier mobicom but that option not have on this tool how to fix it?

**Comment by h00die** [comment]
You will need to determine the sms gateway and add it to here: https://github.com/rapid7/metasploit-framework/pull/8047/files#diff-948365300f80d9aca7f6dd48fe8d4659R8
To determine the gateway, I believe the trick is to text an email address.  This should get you the <yournumber>@<gateway> as the from.  Plug the gateway in to the msf file, then if it works, either post a PR or let us know and @sinn3r can update the list!

**Comment by azamet90** [comment]
> . Plug the gateway in to the msf file, then if it works, either post a PR or let us k

```
        GATEWAYS = {
          :alltel => 'sms.alltelwireless.com',   # Alltel
          :att    => 'txt.att.net',              # AT&T Wireless
          :boost  => 'sms.myboostmobile.com',    # Boost Mobile
          :cricket => 'sms.mycricket.com',       # Cricket Wireless
          # Sprint is commented out, because the gateways don't seem to work.
          # Gateways tried for Sprint:
          # messaging.sprintpcs.com
          # pm.sprint.com
          #:sprint  => 'messaging.sprintpcs.com', # Sprint
          :tmobile => 'tmomail.net',             # T-Mobile
          :verizon => 'vtext.com',               # Verizon
          :virgin  => 'vmobl.com',               # Virgin Mobile
          :google => 'msg.fi.google.com'         # Google Project Fi
        }
```



only this section is about that also?

**Comment by h00die** [comment]
I'm not sure. @sinn3r  any ideas?
