### ISSUE TITLE
FIX: Can't Install: Setup Wizard ended Prematurely

### ISSUE THREAD

**Issue by Odyssey2247** [rapid7/metasploit-framework#12600]
I get that error when I try to install metasploit(5.0.61) for windows (windows 10 home 10.0.18362.476) in fresh installation
To correct the error I did the following:
1.- open shell in administrator mode in the folder where the installer is located
2.- install metasploit with the arguments:

    > metasploitframework-latest.msi /L*v msf.log

3.- select another installation folder different from the default installation drive c: and continue with the installation

NOTE: Even if you select another installation folder, metasplot will be installed in the path C: \ metasplot-framework but without any error

**Comment by sploitmyhost** [comment]
Great solution to this problem. I have seen more people with that exact same issue.

**Comment by BhashanaHarischandra** [comment]
Same issue

**Comment by VisualStudioTCERJ** [comment]
worked !!

**Comment by rdubaiev** [comment]
Here's the output I get when I run it from powershell 

metasploitframework-latest.msi : The term 'metasploitframework-latest.msi' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ metasploitframework-latest.msi /L*v msf.log
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (metasploitframework-latest.msi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by surjith007** [comment]
I too have the same issue

**Comment by Shuva-Paul** [comment]
Try with following command,

 .\metasploitframework-latest.msi /L*v msf.log

**Comment by ttimasdf** [comment]
Thanks for the insight! Running with `.\metasploitframework-latest.msi /L*v msf.log` do print some log for me. However,  select another installation folder cannot simply let the installation proceed.

The workaround that finally works for me:

1. create an empty file called `metasploit-framework.zip` at a random folder.
2. move that file to the `C:\` drive root. (because the Explorer context menu do not let me create file here directly)
3. Grant **all** permissions (read, write, full control) to `Users` group of this file.
4. run `metasploitframework-latest.msi` as usual(double click), proceed with all default options.

**Comment by viniciusmarangoni** [comment]
I solved this problem by executing the msi installer as Administrator. I did it by opening an Administrator Command Prompt, navigating to the Downloads folder and executing the msi installer. 

No additional steps were necessary, like selecting a different installation directory (mentioned by joselbr2099) nor creating the .zip file (mentioned by ttimasdf)

**Comment by JustAnotherG** [comment]
I think this finally installed successfully for me after executing the .MSI in an administrator command prompt. I went to sleep and woke up to a successful install message. But I don't see any Windows icons or anything on the Start Menu. The installation and post installation could use some work. Give hints at least that it was installed successfully.

**Comment by ololoe** [comment]
> I think this finally installed successfully for me after executing the .MSI in an administrator command prompt. I went to sleep and woke up to a successful install message. But I don't see any Windows icons or anything on the Start Menu. The installation and post installation could use some work. Give hints at least that it was installed successfully.

Same shit. 6.0.45. Any idea how to install menu? Or bat files meanings?

**Comment by SharpClaw007** [comment]
> I solved this problem by executing the MSI installer as Administrator. I did it by opening an Administrator Command Prompt, navigating to the Downloads folder, and executing the MSI installer.
> 
> No additional steps were necessary, like selecting a different installation directory (mentioned by joselbr2099) nor creating the .zip file (mentioned by ttimasdf)

Worked like a charm. CD from administrator PowerShell into wherever the installer is, run the following command:

`.\metasploitframework-latest.msi /L*v msf.log`

And proceed through the installation process as normal.

**Comment by AnonymousRonin** [comment]
> I get that error when I try to install metasploit(5.0.61) for windows (windows 10 home 10.0.18362.476) in fresh installation To correct the error I did the following: 1.- open shell in administrator mode in the folder where the installer is located 2.- install metasploit with the arguments:
> 
> ```
> > metasploitframework-latest.msi /L*v msf.log
> ```
> 
> 3.- select another installation folder different from the default installation drive c: and continue with the installation
> 
> NOTE: Even if you select another installation folder, metasplot will be installed in the path C: \ metasplot-framework but without any error

I couldn't get it to go either. I'm actually trying to figure out why I was gonna down load it.  It's pretty much useless except for havin g al the exloits even though most of need work for them to be successfyl

**Comment by kojackplay** [comment]
rapaziada baixem a pasta pelo gifthub

 https://github.com/rapid7/metasploit-framework?tab=readme-ov-file 

após baixar basta abrir o cmd como adm 
usar esses comandos 
cd ..
cd..
cd users
cd ( escolhe o usuario )
cd desktop
metasploitframework-latest.msi /L*v msf.log

**Comment by JawadPy** [comment]
I'm here with version v6.4.20, i'd like to confirm that this solution lasts like a Toyota Corolla.

**Comment by bucketss** [comment]
msiexec /i metasploitframework-latest.msi /L*v msf.log

for anyone having problems
