### ISSUE TITLE
android/meterpreter/reverse_tcp not working on Oreo

### ISSUE THREAD

**Issue by IlyHo** [rapid7/metasploit-framework#12617]
## Steps to reproduce

How'd you do it?

1. Created the payload apk file with Phantom Evasion and Ngrok for Wan 
2. Started the handler
3. Installed and run the apk on the target device
4. The Meterpreter opens sessions which immediately dies 

Whether it is android or windows payloads my sessions immediately die. I've even tried stageless payloads without success.

## Expected behavior

Working meterpreter session

## Current behavior

The meterpreter session immediately closes. Reason:Died

### Metasploit version
metasploit v5.0.59-dev

### I installed Metasploit with:
- [x] Kali package via apt

### OS

Kali Linux 2019-3

![Screenshot from 2019-11-21 21-21-59](https://user-images.githubusercontent.com/57727414/69369719-8a06f580-0c6a-11ea-8f46-f08831ff7754.png)
![Screenshot from 2019-11-21 21-26-52](https://user-images.githubusercontent.com/57727414/69369983-07cb0100-0c6b-11ea-89cb-38df0c010312.png)

**Comment by timwr** [comment]
I can't reproduce this. I suspect you're not setting the correct LHOST in the handler (don't set 0.0.0.0 or 127.0.0.1, put the same LHOST you used when generating the payload with msfvenom).
