### ISSUE TITLE
record_mic not working on Android 9

### ISSUE THREAD

**Issue by sw1tchbl4d3r** [rapid7/metasploit-framework#12621]
## Steps to reproduce

1. msfvenome'd an android/meterpreter/reverse_tcp apk
2. installed and launched on Android Pie (9) - Device
3. execute (webcam_stream, webcam_snap or) record_mic in meterpreter

Phone is on Android 9
Attacker is on Fedora 31

## Expected behavior

It should execute those 3 Commands successfully

## Current behavior

webcam_snap and webcam_stream [solved]:
meterpreter: webcam_start: Operation failed: 1
Callstack: https://pastebin.com/YFwQ7ewV

record_mic
e.g. record_mic 3 puts out 1s long empty file
EDIT: If I try to record for 6s it gives me a 3 second long empty file. If I try 10 it gives me 5 etc. 
Callstack: None, no error in logs

### Metasploit version

Framework: 5.0.61-dev-
Console  : 5.0.61-dev-

### I installed Metasploit with:
- [x] Source install (ruby 2.6.5p114 (2019-10-01 revision 67812))

### OS
Linux 5.3.11-300.fc31.x86_64 / Fedora 31

**Comment by sw1tch-bl4d3** [comment]
Fixed by myself by adding:
`<uses-sdk android:minSdkVersion="22"
          android:targetSdkVersion="22"
          android:maxSdkVersion="29" />`
to the AndroidManifest.

Why does that fix it?
Previously the targetsdk was 23 or higher. But with targetsdk 23 and higher the app has to ask explicitely. This fixes it.

~sw1tchbl4d3

**Comment by sw1tch-bl4d3** [comment]
The answer above only works for webcam_stream and webcam_snap. NOT for the record_mic problem!

**Comment by azamet90** [comment]
i did not understand how you did fix the webcam_stream problem and i did not understand how to fix the mic_record problem

**Comment by sw1tch-bl4d3** [comment]
I extracted the android/meterpreter/reverse_tcp apk and there was no `<uses-sdk android:minSdkVersion="10" android:targetSdkVersion="17"/>` in it. There was no <uses-sdk> in it. If yours has this line then it probably has another cause.

**Comment by Abdulmanan0315** [comment]
Try to allow all the permissions from phone settings (due to the new policy from android 6+, apps should ask for permissions)
