### ISSUE TITLE
Nokogirl failed 

### ISSUE THREAD

**Issue by Andrey2006615** [rapid7/metasploit-framework#12635]
I have a problem . An error occurred while installing metasplit, at the end of the installation
An error flies when installing nokogirl help me !!! 
I downloaded everything according to the instructions

**Comment by MALW4R3** [comment]
me too

**Comment by MALW4R3** [comment]
![Screenshot_2019-11-29-20-52-59-85](https://user-images.githubusercontent.com/57804710/69873414-dc8b8600-12ea-11ea-8fc4-d57b6942c1e6.png)

**Comment by h00die** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
