### ISSUE TITLE
enable cors in MSF web service

### ISSUE THREAD

**Issue by karelbyte** [rapid7/metasploit-framework#12630]
Hello, thank you very much for this excellent tool, my problem is the following, I want to connect to the api using axios, but when I make the request I get cors error,
**Cross-origin request blocked: The same origin policy does not allow the reading of remote resources at https: // localhost: 5443 / api / v1 // workspaces. (Reason: CORS request not successful)**
how can i enable cors in MSF web service?

**Comment by dwelch-r7** [comment]
@karelbyte is this error coming from MSF or is your app throwing the error? I'm not overly familiar with CORS issues but can you double check the issue isn't a misconfiguration within axios

**Comment by karelbyte** [comment]
this.$axios.interceptors.request.use((config) => {
        config.headers.Accept = 'application/json'
        config.headers.Authorization = 'Bearer 87ffe97c6fa1679ea32015cff947b8905b07edebbde5a945054a22007f162d7468423eba8f571a2e'
        return config
      }, function (error) {
        return Promise.reject(error)
      })
      this.$axios.get(this.$urlCore.api + 'workspaces').then(res => {
        console.log(res.data)
      }).catch(er => {
        this.$noty.negative(er.response.data)
      })

**Comment by karelbyte** [comment]
it is the configuration that I use for the connection, when there are cors errors is that the server provider of the accounts, the headers for that function are not enabled

**Comment by karelbyte** [comment]
help please

**Comment by karelbyte** [comment]
when I go to https: // localhost: 5443 /api/  tells me in browser I have to add a security exception to see it because https is not safe, will I have to see that?

**Comment by karelbyte** [comment]
To be able to make orders to the api through  **insomnia**  I have to deactivate the valid certificate check, every time I think it is something with the https url that generates the metasploit

**Comment by busterb** [comment]
You could simply teach insomnia to use Metasploit's generated cert, located in ~/.msf4/msf-ws-cert.pem

You're not going to get a 3rd party cert signed by for 'localhost'.

**Comment by busterb** [comment]
See this for more info. It's a limitation of SSL certificates themselves, not something we can really help you with: https://github.com/getinsomnia/insomnia/issues/675

**Comment by karelbyte** [comment]
@dwelch-r7 Insomia is just a software that I use to test apis, I want to be able to place orders by axios, or failing that by curl, but in both cases it gives axios error it refreshes me cors error, and curl this returns me
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by karelbyte** [comment]
I have mounted the metasploidt on a local PC and configured to learn how to use it and create an app that communicates with the framework, I thought it could work like this or is it not possible?

**Comment by busterb** [comment]
It's definitely possible, you just need to teach your app either how to import the web service certificate, switch the web service calls to plaintext, or disable certificate validation. We cannot give you a root-trusted cert for the domain `localhost`

**Comment by busterb** [comment]
As a footnote, this is the kind of bug that pops up when you do try to work around something like connecting via https to localhost: https://twitter.com/SwiftOnSecurity/status/1202034106495832067

**Comment by cn-kali-team** [comment]
I have the same problem. Have you solved it

**Comment by M4jx** [comment]
This problem still occurs. The msfrpcd server lacks proper CORS related HTTP headers such as `Access-Control-Allow-Origin`.
Requesting 127.0.0.1:55553/api/1.0 from Postman or similar tools works because these tools doesn't have the same security as the browsers [see](https://stackoverflow.com/questions/57434665/blocked-by-cors-policy-on-the-browser-working-on-postman).

Example:
Postman/Insomnia => 127.0.0.1:55553 (msfrpcd server/api) Works ✅
127.0.0.1:80 (mysite) => 127.0.0.1:55553 (msfrpcd server/api) (CORS ERROR) ❌

The solution would be to make msfrpcd server return proper CORS related flags to be able to perform requests from the browsers.
