### ISSUE TITLE
Search returns incorrect aux module Check flag

### ISSUE THREAD

**Issue by adamgalway-r7** [rapid7/metasploit-framework#12660]
## Steps to reproduce
1. `search type:auxiliary`
2. `use 1083` (This uses the SIP Invite Spoof module, which is displayed as supporting check by Search)
3. `check`
4. You should get a message saying that "This module does not support check."

## Expected behavior

`This module does not support check` should be displayed in step 4

## Current behavior

Search returns incorrect aux module Check flag

## System stuff

As seen in PR [12627](https://github.com/rapid7/metasploit-framework/pull/12627), `info` used to incorrectly report that `check` was supported for Auxiliary modules that used the `Msf::Auxiliary::Scanner` mixin. Odds are the fix used in 12627 will need to be applied to the logic in `search` that determines if a module supports `check` for the same reason.

### Metasploit version

Framework: 5.0.63-dev-104710ca41
Console  : 5.0.63-dev-104710ca41

### I installed Metasploit with:
- [ ] Source install (ruby version 2.6.5)

### OS
MacOS 10.14.6

**Comment by wvu-r7** [comment]
Makes sense. Are you working on this, @adamgalway-r7? Or is @dwelch-r7?

https://github.com/rapid7/metasploit-framework/blob/104710ca41f6e306e41a604b378b01e6f70fca74/lib/msf/core/modules/metadata/obj.rb#L103-L104

#10341, #12627

**Comment by adamgalway-r7** [comment]
Above behaviour is caused by auxiliary modules incorrectly stating they support `check` due to their use of the `Scanner` module.  #12695 changed behaviour to only state that a module supports `check` if it is included in the modules' instance methods. This caused issues with other modules (i.e. ms17_010_eternalblue) due to there relying on mixins to implement `check`.

**Comment by wvu-r7** [comment]
Feel free to rework module-as-check in #12517 as necessary. Might want to sync with @acammack-r7. It's a mixin because the feature was provisional.
