### ISSUE TITLE
some commands not working ...

### ISSUE THREAD

**Issue by azamet90** [rapid7/metasploit-framework#12687]
using the latest version of metasploit and kali linux....
the problem is that some commands like record mic dump sms dump calllog ist not working im injecting payload to the gbwhatsapp then i get more compatibility with some phones... like huewai... standalone payload nothing can do on huewai... how to fix it?

**Comment by space-r7** [comment]
Could you post more information on the problems that you're experiencing? Please post command output, your Msf version, how you installed, etc.

**Comment by azamet90** [comment]
> Could you post more information on the problems that you're experiencing? Please post command output, your Msf version, how you installed, etc.

on some model phones it is not working timeout error it is giving it was preinstalled on my kali distro and the latest version i have... not only me have this problem i think you have this problem too right?
