### ISSUE TITLE
UUID Windows Meterpreter payloads failing automated testing

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-framework#12691]
Windows UUID payloads are failing automated testing.
The test uses the following format:
msfvenom payload creation, upload and callback/in with multi/handler.

The payloads appear to be created, uploaded, and run properly.  Then, they perform a callback and tcp handshake, but no data is sent after the handshake:
![image](https://user-images.githubusercontent.com/17987018/70450558-8f857d80-1a69-11ea-9712-fee59893e738.png)

The handler does not show that a callback was received:
![image](https://user-images.githubusercontent.com/17987018/70450776-ebe89d00-1a69-11ea-81d6-359f3bb44666.png)

This behavior was seen on 

windows/x64/meterpreter/bind_tcp_uuid
windows/x64/meterpreter/reverse_tcp_uuid
windows/meterpreter/bind_tcp_uuid
windows/meterpreter/reverse_tcp_uuid

**Comment by OJ** [comment]
Is this a recent regression?

**Comment by bwatters-r7** [comment]
They all passed November 28

**Comment by bwatters-r7** [comment]
I've got my hands full today, but if anyone wants to take a look, I'm curious if this was introduced in https://github.com/rapid7/metasploit-framework/pull/12668.  Might be worthwhile to check the commit before that one.

**Comment by busterb** [comment]
I think it'd be pretty cool if the 'Sanity Check' tests that run on every PR did UUID payloads too.

**Comment by busterb** [comment]
Looks like deb57a1df050491327f69cb2bdd995922752a611 is where it begins failing.

**Comment by busterb** [comment]
Found the issue, fixes incoming :)
