### ISSUE TITLE
error adding metasploit to termux

### ISSUE THREAD

**Issue by marknjoroge** [rapid7/metasploit-framework#12728]
hi I was trying to add metasploit using wget command and the response is always 'not found'. 
I've tried out other respiratories but I still get the same error. Please help. 
![Screenshot_20191215_142935_com termux](https://user-images.githubusercontent.com/55851750/70862011-5f494d80-1f47-11ea-9c0c-425b2456c6d1.jpg)

**Comment by bcoles** [comment]
There is a typo in the URL. Also, wgetting the repository won't do you much good.

Also, Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
