### ISSUE TITLE
Can't install metasploit

### ISSUE THREAD

**Issue by 11llewellyn** [rapid7/metasploit-framework#12722]
Every time I try to install with 
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

I get 
Err:1 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid/main amd64 metasploit-framework amd64 5.0.65+20191214112537~1rapid7-1
  Connection failed [IP: 127.0.0.1 8080]
E: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/pool/main/m/metasploit-framework/metasploit-framework_5.0.65+20191214112537~1rapid7-1_amd64.deb  Connection failed [IP: 127.0.0.1 8080]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
 I have tried apt-get update and added --fix-missing but with no success

**Comment by bcoles** [comment]
> Connection failed [IP: 127.0.0.1 8080]

**Comment by 11llewellyn** [comment]
but my Connection is stable and I'm running other programs fine

**Comment by bcoles** [comment]
You have a proxy configured somewhere. Perhaps `http_proxy` ?

**Comment by 11llewellyn** [comment]
I'm on no proxy 
HTTP_PROXY=http://127.0.0.1:8080/
http_proxy=http://127.0.0.1:8080/
no_proxy=
NO_PROXY=

**Comment by bcoles** [comment]
`unset http_proxy` or configure `no_proxy` correctly.

**Comment by 11llewellyn** [comment]
how do I do that?

**Comment by 11llewellyn** [comment]
now I'm getting this error
Adding metasploit-framework to your repository list..OK
Updating package cache..OK
Checking for and installing update..
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

**Comment by bcoles** [comment]
> E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

Perhaps you have a package manager running in another window? Or perhaps your system is performing background updates. Perhaps wait a couple of minutes.
