### ISSUE TITLE
Sandbox Escaper 0-Day for VMWare tools

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-framework#12734]
Looks like sanbox escaper dropped an 0-day using VMware tools installer file:
https://sandboxescaper.blogspot.com/2019/12/chasing-polar-bears-part-one.html
https://github.com/SandboxEscaper/chasingpolarbears/tree/master/vmwarebug

**Comment by h00die** [comment]
Blog is now invite only 😭

**Comment by bcoles** [comment]
> 
> 
> Blog is now invite only sob

http://web.archive.org/web/20191216190557/https://sandboxescaper.blogspot.com/2019/12/chasing-polar-bears-part-one.html

**Comment by gwillcox-r7** [comment]
Closing this as this is over 3 years old now and I've not seen any movement on this. If someone wants to add this in they can, but I imagine we may want to focus on more recent bugs?
