### ISSUE TITLE
telnet_login RegexpError unmatched close parenthesis: /root

### ISSUE THREAD

**Issue by lukinalutuna** [rapid7/metasploit-framework#12764]
## Steps to reproduce
Hi, I tried to use telnet_login with the username: root and blank passwords are allowed. 
I did this:
```
msf5 auxiliary(scanner/telnet/telnet_login) > set RHOSTS 192.168.188.26
RHOSTS => 192.168.188.26
msf5 auxiliary(scanner/telnet/telnet_login) > set STOP_ON_SUCCESS true
STOP_ON_SUCCESS => true
msf5 auxiliary(scanner/telnet/telnet_login) > set BLANK_PASSWORDS true
BLANK_PASSWORDS => true
msf5 auxiliary(scanner/telnet/telnet_login) > set USER_FILE /root/Desktop/adminname.txt
USER_FILE => /root/Desktop/adminname.txt
msf5 auxiliary(scanner/telnet/telnet_login) > set PASS_FILE /root/Desktop/adminpas.txt
PASS_FILE => /root/Desktop/adminpas.txt
msf5 auxiliary(scanner/telnet/telnet_login) > run
```
## Output is this:
```
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin: (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin:root (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin:admin (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin:1234 (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin:4567 (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin: (Incorrect: )
[-] 192.168.188.26:23     - 192.168.188.26:23 - LOGIN FAILED: admin:admin1234 (Incorrect: )
*] 192.168.188.26:23     - Error: 192.168.188.26: RegexpError unmatched close parenthesis: /root
 _           _         _            
| |         | |       | |           
| |     ___ | |__  ___| |_ ___ _ __ 
| |    \/ _ \| '_ \/ __| __\/ _ \ '__|
| |___| (_) | |_) \__ \ ||  __\/ |   
|______\___\/|_.__\/|___\/\__\___|_|   
                                    
                                    
's/
[*] 192.168.188.26:23     - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```
## Expected behavior
root should be used as the second username on the list in txt-File with blank password.

### Metasploit version

Framework: 5.0.63-dev
Console  : 5.0.63-dev

### I installed Metasploit with:
- [ x] Kali package via apt

### OS

Kali Rolling 2019.4

**Comment by h00die** [comment]
Can you post the results from logging in to telnet manually?  There are a lot of potential regexes (https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/lib/msf/core/auxiliary/login.rb#L36 , https://github.com/rapid7/metasploit-framework/blob/master/lib/metasploit/framework/telnet/client.rb#L154 , etc) that fire, and it would be helpful to have the input to see which are firing and what they may be failing on.

**Comment by lukinalutuna** [comment]
`root@lenovo:~# telnet 192.168.188.26 23
Trying 192.168.188.26...
Connected to 192.168.188.26.
Escape character is '^]'.

(none) login: root
 _           _         _            
| |         | |       | |           
| |     ___ | |__  ___| |_ ___ _ __ 
| |    / _ \| '_ \/ __| __/ _ \ '__|
| |___| (_) | |_) \__ \ ||  __/ |   
|______\___/|_.__/|___/\__\___|_|   
                                    
                                    
~ # ls -la
drwxrwxr-x   17 1005     1005           215 May 31  2019 .
drwxrwxr-x   17 1005     1005           215 May 31  2019 ..
drwxr-xr-x    5 root     root             0 Jan  1  1970 backup
drwxrwxr-x    2 1005     1005          1298 May 31  2019 bin
drwxr-xr-x    6 root     root             0 Oct 24  2015 dev
drwxrwxr-x    7 1005     1005           321 May 31  2019 etc
drwxrwxr-x    6 1005     1005            91 May 31  2019 home
lrwxrwxrwx    1 1005     1005             8 May 31  2019 init -> bin/init
drwxrwxr-x    4 1005     1005           944 May 31  2019 lib
drwxr-xr-x    2 root     root            40 Oct 24  2015 media
drwxrwxr-x    2 1005     1005            30 May 31  2019 mnt
drwxrwxr-x    2 1005     1005            44 May 31  2019 overlay
dr-xr-xr-x   53 root     root             0 Jan  1  1970 proc
drwxrwxr-x    2 1005     1005            30 May 31  2019 rom
drwxrwxr-x    2 1005     1005            30 May 31  2019 root
dr-xr-xr-x   11 root     root             0 Jan  1  1970 sys
lrwxrwxrwx    1 1005     1005             8 May 31  2019 tmp -> /var/tmp
drwxrwxr-x    4 1005     1005            40 May 31  2019 usr
drwxr-xr-x    7 root     root             0 Jan  1  1970 var
~ # 

`

**Comment by h00die** [comment]
is that a customer box or a hack challenge box (so i could download to look at fixing)?

**Comment by lukinalutuna** [comment]
It's just a small project I've been working on my own device. Just want to learn metasploit and how to break into a telnet. Sooo, is the error caused by the telnet_login module itself? Can someone point out what I did wrong? How can I correctly type into list.txt of the username? I only typed root, without any parentheses.

**Comment by h00die** [comment]
I believe it is an issue with the module or underlying libraries, not something you are doing.

**Comment by h00die** [comment]
what host OS, and msf version?
Would you be able to share the configs for this? I'd like to re-create it but my testing so far works fine.
However, Ubuntu is a pain to do root logins and no passwords, so if I'm going to switch OSes i'll switch to whatever you are using to ensure i get it to bug correctly.

**Comment by bcoles** [comment]
I was able to reproduce this using netcat.

```
msf5 auxiliary(scanner/telnet/telnet_login) > set blank_passwords true
blank_passwords => true
msf5 auxiliary(scanner/telnet/telnet_login) > set verbose true
verbose => true
msf5 auxiliary(scanner/telnet/telnet_login) > run

[*] 127.0.0.1:23          - Error: 127.0.0.1: RegexpError unmatched close parenthesis: /\/root
 _           _         _            
| |         | |       | |           
| |     ___ | |__  ___| |_ ___ _ __ 
| |    \/ _ \| '_ \/ __| __\/ _ \ '__|
| |___| (_) | |_) \__ \ ||  __\/ |   
|______\___\/|_.__\/|___\/\__\___|_|   
                                    
                                    
's/
[*] 127.0.0.1:23          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/telnet/telnet_login) > 
```

On netcat:

```
root@kali:~/Desktop/metasploit-framework# nc -lvp 23 
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Listening on :::23
Ncat: Listening on 0.0.0.0:23
Ncat: Connection from 127.0.0.1.
Ncat: Connection from 127.0.0.1:38473.
Login:
guest
/root
 _           _         _            
| |         | |       | |           
| |     ___ | |__  ___| |_ ___ _ __ 
| |    \/ _ \| '_ \/ __| __\/ _ \ '__|
| |___| (_) | |_) \__ \ ||  __\/ |   
|______\___\/|_.__\/|___\/\__\___|_|   
                                    
                                    
's
```

I typed `Login:`, and upon receiving the username, pasted the `logster` asciii art.

**Comment by bcoles** [comment]
lol

```ruby
  def password_prompt?(username=nil)
    return true if(@recvd =~ @password_regex)
    if username
      return true if( !(username.empty?) and @recvd =~ /#{username}'s/)      # <-- that aint right
    end
    return false
  end
```

**Comment by bcoles** [comment]
Fixed, but this code still looks pretty janky.

```
msf5 auxiliary(scanner/telnet/telnet_login) > edit lib/msf/core/auxiliary/login.rb
[*] Reloading /root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:13: warning: already initialized constant Msf::Auxiliary::Login::NULL
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:13: warning: previous definition of NULL was here
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:14: warning: already initialized constant Msf::Auxiliary::Login::CR
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:14: warning: previous definition of CR was here
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:15: warning: already initialized constant Msf::Auxiliary::Login::LF
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:15: warning: previous definition of LF was here
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:16: warning: already initialized constant Msf::Auxiliary::Login::EOL
/root/Desktop/metasploit-framework/lib/msf/core/auxiliary/login.rb:16: warning: previous definition of EOL was here
msf5 auxiliary(scanner/telnet/telnet_login) > git diff lib/msf/core/auxiliary/login.rb
[*] exec: git diff lib/msf/core/auxiliary/login.rb

diff --git a/lib/msf/core/auxiliary/login.rb b/lib/msf/core/auxiliary/login.rb
index b866b5091f..a7590e547d 100644
--- a/lib/msf/core/auxiliary/login.rb
+++ b/lib/msf/core/auxiliary/login.rb
@@ -136,7 +136,7 @@ module Auxiliary::Login
   def password_prompt?(username=nil)
     return true if(@recvd =~ @password_regex)
     if username
-      return true if( !(username.empty?) and @recvd =~ /#{username}'s/)
+      return true if !(username.empty?) && @recvd.to_s.include?("#{username}'s")
     end
     return false
   end
msf5 auxiliary(scanner/telnet/telnet_login) > run

[!] 127.0.0.1:23          - No active DB -- Credential data will not be saved!
[+] 127.0.0.1:23          - 127.0.0.1:23 - Login Successful: guest:
[*] 127.0.0.1:23          - Attempting to start session 127.0.0.1:23 with guest:
[*] Command shell session 12 opened (127.0.0.1:41993 -> 127.0.0.1:23) at 2019-12-28 23:46:01 -0500
[-] 127.0.0.1:23          - 127.0.0.1:23 - LOGIN FAILED: root: (Unable to Connect: )
[-] 127.0.0.1:23          - 127.0.0.1:23 - LOGIN FAILED: test: (Unable to Connect: )
[*] 127.0.0.1:23          - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/telnet/telnet_login) > 
```

**Comment by lukinalutuna** [comment]
I fixed the login.rb with
