### ISSUE TITLE
add android/meterpreter/bind_tcp payload

### ISSUE THREAD

**Issue by ghanshyam2005singh** [rapid7/metasploit-framework#12775]
If you'd like to propose a feature, describe what you'd like to see. Mock ups of console views would be great.

If you're reporting a bug, please be sure to include the expected behavior, the observed behavior, and steps to reproduce the problem. Resource scripts, console copy-pastes, and any background on the environment would be appreciated.

For tips, see http://r-7.co/MSF-CONTRIB

**Comment by ghanshyam2005singh** [comment]
I want to know how to bind payload in apk by android

**Comment by timwr** [comment]
@ghanshyam2005singh this was implemented but I'm not sure how stable it is: https://github.com/rapid7/metasploit-framework/compare/master...timwr:android_bind_tcp
https://github.com/rapid7/metasploit-payloads/compare/master...timwr:android_bind_tcp
