### ISSUE TITLE
osx reverse_tcp handler doesn't distinguish between stager and meterpreter connections

### ISSUE THREAD

**Issue by phra** [rapid7/metasploit-framework#12841]
## Steps to reproduce

How'd you do it?

1. [x] `msfconsole -r mac.rc`
1. [x] spawn a native max os x reverse_tcp staged payload
1. [x] `exit -y # exit without killing the agent`
1. [x] `msfconsole -r mac.rc`

Spawn a native mac os x staged reverse_tcp, exit the handler and restart it.
After the agent reconnects, the handler tries to stage again the payload instead of recognizing the fully loaded meterpreter

## Expected behavior

The handler distinguish the fully loaded meterpreter and skip the staging phase

## Current behavior

The agent goes zombie after the handler tried to stage again the payload

### Metasploit version

`Framework Version: 5.0.64-dev`

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

**Comment by phra** [comment]
@timwr after reading the code, i am not sure that this is osx specific, since i could only find mentions of orphaned sessions in the http/https handler.

- reverse_tcp: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/handler/reverse_tcp.rb#L157

- reverse_http: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/handler/reverse_http.rb#L378

**Comment by timwr** [comment]
This appears to be an issue on OSX and Linux reverse_tcp (but not http). It works fine on python/meterpreter/reverse_tcp (it sends the stage again, but at least it works). Java and Android I suspect it's fine too.
Not sure about Windows.

**Comment by phra** [comment]
if it's both linux and osx i suspect it's an issue with https://github.com/rapid7/mettle itself.

thanks for testing.

**Comment by timwr** [comment]
I can confirm this on linux/x64/meterpreter/reverse_tcp but I'm not sure exactly where it happens. After staging and disconnecting it's able to connect again and read from the socket, but it never processes commands again.
