### ISSUE TITLE
apt-get update Does not works / kali linux

### ISSUE THREAD

**Issue by lucasreina07** [rapid7/metasploit-framework#12866]
I have this problem entering the apt-get update command
![kali](https://user-images.githubusercontent.com/59820237/72761963-d065cb80-3bab-11ea-8082-a88dd3c81b39.PNG)

**Comment by h00die** [comment]
Interesting, it does have a "Release" file, but almost all (if not all) files are giving `File not found.''` within http://downloads.metasploit.com/data/releases/metasploit-framework/apt.  @bcook-r7 @wvu-r7 looks like a something rapid7 may need to address?

**Comment by lucasreina07** [comment]
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall




> Interesante, tiene un archivo "Release", pero casi todos (si no todos) los archivos se encuentran `File not found.''`dentro de http://downloads.metasploit.com/data/releases/metasploit-framework/apt . @ bcook-r7 @ wvu-r7 se parece a algo que 7 debe tener en cuenta?

It has not worked for me, and I downloaded and installed these files. I have used the automatic link and I still can't solve the MSF installation problem
