### ISSUE TITLE
Add username and hostname to client session_info

### ISSUE THREAD

**Issue by phra** [rapid7/metasploit-framework#12875]
It would be nice to display the username and hostname in the `Information` columns when running `session -x` command with mettle agents.

## Steps to reproduce

1. spawn a mettle agent (linux, mac os x, .. )
2. `session -x`

## Expected behavior

Under `Information` column:

`<USERNAME> @ <HOSTNAME> (uid, gid, euid, egid) @ <IP>`

## Current behavior

Under `Information` column:

`uid, gid, euid, egid @ <IP>`

**Comment by timwr** [comment]
I think I landed this prematurely as getlogin() is not working and not recommended on Linux:
https://linux.die.net/man/3/getlogin

**Comment by phra** [comment]
what do you mean? i developed the PR on linux and tested later on osx.

**Comment by timwr** [comment]
I'm seeing `no-login` as a username come up while testing on Linux. Could be something silly I'm doing though.

**Comment by timwr** [comment]
OSX is working fine, and a simple test program works (even when compiled with musl) ¯\\\_(ツ)_/¯
