### ISSUE TITLE
memcached_extractor returns only cold items for segmented LRU

### ISSUE THREAD

**Issue by tigre-bleu** [rapid7/metasploit-framework#12884]
## Steps to reproduce

Just perform a dump using metasploit module on a Memcached server with segmented LRU active.

1. use auxiliary/gather/memcached_extractor
2. run

## Expected behavior

̀`memcached_extractor` shall return all objects from the memcache, whatever the LRU status (**cold**, **warm**, **hot**).

## Current behavior

When segmented LRU is active, Memcached returns only the keys from the **cold** states. This is due to the use of the [`stats cachedump`](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/gather/memcached_extractor.rb#L58) command by the module which is limited to **cold** items (see [source code of memcached](https://github.com/memcached/memcached/blob/master/items.c#L593))

In a heavily used cache server, most items may be in **warm** or **hot** state.

## Fix Proposal

Currently the module uses the `stats cachedump` command with this **cold** state only limitation. An alternative exists: `lru_crawler metadump all` wich returns all the keys whatever the state but the regexp needs to be adapted.
LRU Segmented enablement status can be recovered with:

```
stats settings
(...)
STAT lru_segmented yes
(...)
END
```

### Metasploit version

5.0.18-dev

### OS

Kali

**Comment by noncenz** [comment]
PR #13468 submitted to address this issue.
