### ISSUE TITLE
Having problems with XAUTHORITY 

### ISSUE THREAD

**Issue by Keskebeu** [rapid7/metasploit-framework#12897]
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/
xdg-open: no method available for opening '/home/imsi/nDGHMuIr.html'

**Comment by wvu-r7** [comment]
How does this relate to Metasploit?

**Comment by Keskebeu** [comment]
Because it's not taking snap shots nor playing the stream with Google
chrome. So maybe some one could help me how to fix the issue with
--no-sandbox.

**Comment by wvu-r7** [comment]
What module is this? Or should I try to find it?

**Comment by wvu-r7** [comment]
Or, more specifically, what exactly are you trying to do?

**Comment by Keskebeu** [comment]
When I run webcam_stream that's what it comes up with, when I use Firefox
to stream it. When I use Google chrome it comes up to use with --no-sandbox
but I have not figured it out yet.

**Comment by Keskebeu** [comment]
I am trying to take a snap picture or stream from my phone that I have
injected MainActivity. All the other options work but taking a snap or
stream.

**Comment by Keskebeu** [comment]
![Screenshot from 2020-02-02 22-33-25](https://user-images.githubusercontent.com/25425432/73623904-bf39a780-460c-11ea-9539-f2b288b6fb44.png)
![Screenshot from 2020-02-02 22-34-22](https://user-images.githubusercontent.com/25425432/73623905-bf39a780-460c-11ea-9372-e5b9877e1e4b.png)

**Comment by wvu-r7** [comment]
Thank you for the details! I will take a look.

**Comment by wvu-r7** [comment]
What does `webcam_list` say?

**Comment by wvu-r7** [comment]
Are you running Metasploit as root?

**Comment by Keskebeu** [comment]
NVM I was able to fix the problem by not running msf as root. Otherwise
Google and Firefox will not stream. Plus the more times the target phone
clicks the MainActivity the better it is for the camera to work. So the
better idea is to inject it into another app which the target phone will
click the most. Thanks for trying to help me. I appreciate it.

**Comment by wvu-r7** [comment]
Yup, that'd do it. Glad you solved it yourself!
