### ISSUE TITLE
Metasploit won't start, help

### ISSUE THREAD

**Issue by Unison124** [rapid7/metasploit-framework#12899]
whenever I use the msfconsole command, it shows this and doesn't start

Traceback (most recent call last):ork console.../
        25: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
        24: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
        23: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
        22: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        21: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
        20: from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:161:in `initialize'
        19: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        18: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        17: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        16: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        15: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        14: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        13: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules'
        12: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `each'
        11: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules'
        10: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
         9: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `each'
         8: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
         7: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `recalculate'
         6: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `each_pair'
         5: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `block in recalculate'
         4: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `each_pair'
         3: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:186:in `block (2 levels) in recalculate'
         2: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload.rb:212:in `size'
         1: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload/android.rb:38:in `generate'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload/android.rb:117:in `generate_jar': android/apk/classes.dex not found (RuntimeError)

I've tried many things, just looking for a fix to this broblem

**Comment by space-r7** [comment]
This issue typically happens while installing Metasploit with anti-virus enabled. Try either reinstalling with anti-virus disabled or try installing Framework within a vm and use it from there.
