### ISSUE TITLE
gem install bundler - fails 

### ISSUE THREAD

**Issue by Mohithchowdary** [rapid7/metasploit-framework#12940]
![Screenshot_20200216-072843](https://user-images.githubusercontent.com/35984716/74598088-e5d9f280-5090-11ea-882d-c82a9cd0b3d1.jpg)
How to fix this issue.. please help me with this

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715

**Comment by Mohithchowdary** [comment]
The thing is - it isn't termux. I installed kali nethunter. It worked before i update the terminal. I don't think what's wrong now.

**Comment by bcoles** [comment]
> 
> 
> The thing is - it isn't termux. I installed kali nethunter. It worked before i update the terminal. I don't know what's wrong now.

Oh my bad. Looks like you have a cert issue.

**Comment by Mohithchowdary** [comment]
Yeah dude. Please help..

**Comment by Mohithchowdary** [comment]
How do i get this thing fixed?

**Comment by bcoles** [comment]
> 
> 
> Yeah dude. Please help..

You would have more luck asking the Kali team, especially if a system update broke the Ruby environment.

`bundler` is a Ruby gem. The `gem` utility is part of the Ruby environment.

**Comment by Mohithchowdary** [comment]
Alright..
