### ISSUE TITLE
msfdb init fails connecting to dockerized postgresql database

### ISSUE THREAD

**Issue by nsa** [rapid7/metasploit-framework#12986]
I'd like to use a postgresql docker container as my metasploit database but I am having some issues with it. Did I misunderstand the msfdb concept or I misconfigured something?

## Steps to reproduce

How'd you do it?

1. Started postgresql docker container `docker run --name msfdb -e POSTGRES_PASSWORD=supersecret -e POSTGRES_DB=msfdb postgres`
2. Modified ~/.msf4/database.yml file
```
development: &pgsql
  adapter: postgresql
  database: msfdb
  username: postgres
  password: supersecret
  host: 172.17.0.2
  port: 5432
  pool: 200
  timeout: 5

production: &production
  <<: *pgsql

test:
  <<: *pgsql
  database: msfdb
  username: postgres
  password: supersecret
```
3. Set RAIL_ENV to development with `export RAIL_ENV=development`

4. I tried `bundle exec msfdb init`

```
[?] Would you like to delete your existing data and configurations?: yes
Found a database at /home/█████/.msf4/db, checking to see if it is started
Using database port 5432 found in /home/█████/.msf4/database.yml
Starting database at /home/█████/.msf4/db...failed
2020-02-25 12:30:48.497 +03 [29565] LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
[?] Initial MSF web service account username? [█████]: msfweb
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...success
MSF web service started and online
Creating MSF web service user msfweb

    ############################################################
    ##              MSF Web Service Credentials               ##
    ##                                                        ##
    ##        Please store these credentials securely.        ##
    ##    You will need them to connect to the webservice.    ##
    ############################################################

MSF web service username: msfweb
MSF web service password: supersecret
MSF web service user API token: 010█████████████229d6a2f6


MSF web service configuration complete
The web service has been configured as your default data service in msfconsole with the name "local-https-data-service"

If needed, manually reconnect to the data service in msfconsole using the command:
db_connect --token 010██████████████████229d6a2f6 --cert /home/█████/.msf4/msf-ws-cert.pem --skip-verify https://localhost:5443

The username and password are credentials for the API account:
https://localhost:5443/api/v1/auth/account
```

## Expected behavior

I believe msfdb should have start metasploit database service.

## Current behavior

Metasploit database service doesn't start. The msfconsole can connect docker container via `db_connect`

```
msf5 > db_connect -y ~/.msf4/database.yml
/run/media/█████/Projects/git/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
/run/media/█████/Projects/git/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
Connected to the database specified in the YAML file.
msf5 > /run/media/█████/Projects/git/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil

msf5 > db_status
[*] Connected to msfdb. Connection type: postgresql.
```

Here is the `~/.msf4/db/log` file,
```
2020-02-25 12:28:40.258 +03 [28839] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.2.0, 64-bit
2020-02-25 12:28:40.259 +03 [28839] LOG:  listening on IPv6 address "::1", port 5432
2020-02-25 12:28:40.259 +03 [28839] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-02-25 12:28:40.262 +03 [28839] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
2020-02-25 12:28:40.262 +03 [28839] LOG:  database system is shut down
2020-02-25 12:30:48.493 +03 [29565] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.2.0, 64-bit
2020-02-25 12:30:48.494 +03 [29565] LOG:  listening on IPv6 address "::1", port 5432
2020-02-25 12:30:48.494 +03 [29565] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-02-25 12:30:48.497 +03 [29565] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
2020-02-25 12:30:48.497 +03 [29565] LOG:  database system is shut down
```

### Metasploit version

Metasploit version: **5.0.77-dev-ec828d3be2** - https://github.com/rapid7/metasploit-framework/commit/ec828d3be2f1a32da55d686f9bd1e8a81e720fa7

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

ruby -v: **`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]`**
bundler --version: **`Bundler version 2.1.4`**
gem --version: **`3.1.2`**

### OS

What OS are you running Metasploit on?

- Manjaro KDE Plasma with kernel: `Linux 4.19.102-1-MANJARO`

**Comment by Ashutosh-Kukreti** [comment]
I'm getting the same errors on my Manjaro KDE isn't it possible to ship metasploit as a snap,flatpak or appimage package.It is really sad that you can not even use linux tools on linux.

**Comment by nsa** [comment]
@Ashutosh-Kukreti, I kindly disagree to the last part of your comment. Minor issues like this might happen but on my side it works perfectly as expected on linux, on wsl and even on windows.

**Comment by Ashutosh-Kukreti** [comment]
@nsa I'm sorry but it is not working on my side at all and I'm really tried of searching for a solution,
Are you able to run it on Manjaro KDE with the latest update?

**Comment by Ashutosh-Kukreti** [comment]
My msf-ws.log
>Writing PID to /home/ak/.msf4/msf-ws.pid
Exiting!
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
	from /opt/metasploit/msf-ws.ru:1:in `new'
	from /opt/metasploit/msf-ws.ru:1:in `<main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
Writing PID to /home/ak/.msf4/msf-ws.pid
Exiting!
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
	from /opt/metasploit/msf-ws.ru:1:in `new'
	from /opt/metasploit/msf-ws.ru:1:in `<main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
Writing PID to /home/ak/.msf4/msf-ws.pid
Exiting!
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
	from /opt/metasploit/msf-ws.ru:1:in `new'
	from /opt/metasploit/msf-ws.ru:1:in `<main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
Writing PID to /home/ak/.msf4/msf-ws.pid
Exiting!
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
	from /opt/metasploit/msf-ws.ru:1:in `new'
	from /opt/metasploit/msf-ws.ru:1:in `<main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'
Writing PID to /home/ak/.msf4/msf-ws.pid
Exiting!
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
	from /opt/metasploit/lib/msf/core/web_services/servlet/api_docs_servlet.rb:2:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/lib/msf/core/web_services/metasploit_api_app.rb:7:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/metasploit/msf-ws.ru:17:in `block in <main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
	from /opt/metasploit/msf-ws.ru:1:in `new'
	from /opt/metasploit/msf-ws.ru:1:in `<main>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `load'
	from /opt/metasploit/vendor/bundle/ruby/2.7.0/bin/thin:23:in `<main>'


Database log from .msf4

> 2020-04-12 12:55:25.410 IST [4653] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130, 64-bit
2020-04-12 12:55:25.410 IST [4653] LOG:  listening on IPv6 address "::1", port 5433
2020-04-12 12:55:25.410 IST [4653] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2020-04-12 12:55:25.444 IST [4653] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5433.lock": Permission denied
2020-04-12 12:55:25.444 IST [4653] LOG:  database system is shut down
2020-04-12 12:55:27.635 IST [4667] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130, 64-bit
2020-04-12 12:55:27.636 IST [4667] LOG:  listening on IPv6 address "::1", port 5433
2020-04-12 12:55:27.636 IST [4667] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2020-04-12 12:55:27.670 IST [4667] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5433.lock": Permission denied
2020-04-12 12:55:27.670 IST [4667] LOG:  database system is shut down
2020-04-12 13:00:03.139 IST [4854] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (Arch Linux 9.2.1+20200130-2) 9.2.1 20200130, 64-bit
2020-04-12 13:00:03.139 IST [4854] LOG:  listening on IPv6 address "::1", port 5433
2020-04-12 13:00:03.139 IST [4854] LOG:  listening on IPv4 address "127.0.0.1", port 5433
2020-04-12 13:00:03.173 IST [4854] FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5433.lock": Permission denied
2020-04-12 13:00:03.173 IST [4854] LOG:  database system is shut down
