### ISSUE TITLE
[-] Failed to load module: auxiliary/scanner/msmail/exchange_enum

### ISSUE THREAD

**Issue by klionsec** [rapid7/metasploit-framework#13009]
After installing metasploit, it will be as soon as it is opened

**Comment by space-r7** [comment]
Please post `msfconsole` output and what version of Framework that you're using.

**Comment by ccondon-r7** [comment]
Hey @klionsec, we can't determine whether there's an issue with Metasploit (as opposed to an issue with your environment) with so little information. If you'd like to give us all the info we ask for in the issue form, feel free to reopen this! Cheers.
