### ISSUE TITLE
Msfvenom icon and name change help

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#13011]
Hello how can i change icon and change that apache bench utility to something different of the exe payload in msfvenom? or other programs on kali?

**Comment by bcoles** [comment]
You could try [ResHacker](http://www.angusj.com/resourcehacker/).

https://www.howtogeek.com/75983/stupid-geek-tricks-how-to-modify-the-icon-of-an-.exe-file/

**Comment by joen232413** [comment]
> You could try [ResHacker](http://www.angusj.com/resourcehacker/).
> 
> https://www.howtogeek.com/75983/stupid-geek-tricks-how-to-modify-the-icon-of-an-.exe-file/

ye ty but i want something in kali

**Comment by wvu-r7** [comment]
Try it in [Wine](https://en.wikipedia.org/wiki/Wine_(software)).
