### ISSUE TITLE
Failed to load extension: No module of the name extapi found

### ISSUE THREAD

**Issue by greed5566** [rapid7/metasploit-framework#13023]
## Steps to reproduce

How'd you do it?

1.When I got meterpreter from machine, I wanted to "use extapi" or load "extapi" 

meterpreter > use extapi
Loading extension extapi...
[-] Failed to load extension: No module of the name extapi found

please see attached
![圖片 1](https://user-images.githubusercontent.com/48907794/75863430-6cd1ed80-5e3b-11ea-9a49-48216abdad3c.jpg)

## Expected behavior
It should load extapi successfully 
What should happen?

## Current behavior

What happens instead?

[03/04/2020 04:05:23] [e(0)] meterpreter: Failed to load extension: No module of the name extapi found
[03/04/2020 04:05:23] [d(0)] meterpreter: Call stack:
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1304:in `block in cmd_load'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1283:in `each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1283:in `cmd_load'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1352:in `cmd_use'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:521:in `run_command'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:473:in `block in run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:467:in `each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:467:in `run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/shell.rb:146:in `run'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/msf/base/sessions/meterpreter.rb:573:in `_interact'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/interactive.rb:51:in `interact'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/msf/ui/console/command_dispatcher/core.rb:1367:in `cmd_sessions'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:521:in `run_command'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:473:in `block in run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:467:in `each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/dispatcher_shell.rb:467:in `run_single'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.17.49/msfconsole:49:in `<top (required)>'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `load'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `<main>'
![圖片 1](https://user-images.githubusercontent.com/48907794/75862934-a6562900-5e3a-11ea-9326-f83e0ea91667.jpg)

### I installed Metasploit with: Framework: 4.17.49-dev  Console  : 4.17.49-dev
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS
What OS are you running Metasploit on? kali 2019.2

**Comment by space-r7** [comment]
What's the target system? I believe that the `extapi` and `incognito` extensions are both Windows-only extensions.

**Comment by greed5566** [comment]
The target machine is Windows

**Comment by space-r7** [comment]
Which version of Windows? I've tested on Windows 7 x64.

**Comment by glotozz** [comment]
I have the same problem

**Comment by OJ** [comment]
So this is a native Meterpreter shell on windows?
Can you please post the output of `sysinfo` ?

**Comment by glotozz** [comment]
![image](https://user-images.githubusercontent.com/41844046/76939804-0ae1af80-6934-11ea-8c28-627dbab4c0a5.png)
