### ISSUE TITLE
vegrant

### ISSUE THREAD

**Issue by kaal-kali** [rapid7/metasploit-framework#13025]
rl -O https://raw.githubusercontent.com/rapid7/metasploitable3/master/Vagrantfile && vagrant up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1550  100  1550    0     0  43055      0 --:--:-- --:--:-- --:--:-- 43055
bash: vagrant: command not found
  please help in detail because i am begginer

**Comment by adfoster-r7** [comment]
You need to install [Vagrant](https://www.vagrantup.com/).

Some extra context:

[metasploitable3](https://github.com/rapid7/metasploitable3) is a VM built from the ground up that is intentionally vulnerable. The easiest way to get up and running is to have [Vagrant](https://www.vagrantup.com/) installed on your machine, then grab the vagrant file and run one of the prebuilt images:

```
mkdir metasploitable3-workspace
cd metasploitable3-workspace
curl -O https://raw.githubusercontent.com/rapid7/metasploitable3/master/Vagrantfile
```

At the time of writing, there are two VM definitions to choose from:

```
vagrant up ub1404
vagrant up win2k8
```

**Comment by adfoster-r7** [comment]
I'll close this issue for now, as installing vagrant should hopefully get you up and running :+1:
