### ISSUE TITLE
How can I fix this error in msf console

### ISSUE THREAD

**Issue by Sebultura2** [rapid7/metasploit-framework#13021]
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5896?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.2) and accepting
        TCP/IP connections on port 5896?

**Comment by nsa** [comment]
Could you please elaborate the issue?

**Comment by space-r7** [comment]
What version of Framework are you running, and how was it installed? Is there another service running on your system that is using that port?

**Comment by Sebultura2** [comment]
ready package frame came into img version i did not take any action

> Hangi Framework sürümünü kullanıyorsunuz ve nasıl kuruldu? Sisteminizde bu bağlantı noktasını kullanan başka bir hizmet var mı?

**Comment by ccondon-r7** [comment]
Hi there, we ask for a lot of information in our issue reporting form. If you'd like to give us all that info so we can understand how to reproduce the issue, then please feel free to reopen this!
