### ISSUE TITLE
Meterpreter session died when victim reconnect from cable connection to wifi

### ISSUE THREAD

**Issue by Gh0st0ne** [rapid7/metasploit-framework#13032]
I need advice. Is there some solution how create rev_tcp, rev_http or rev_https payload whitch automatic connect back when victim disconnect his laptop from lan cable connection and connect to wifi?  
Now the session is ureachable until he connect back the cable...

**Comment by ccondon-r7** [comment]
Hey @Gh0st0ne, it's usually better to ask questions in Slack: https://metasploit.com/slack

**Comment by wvu-r7** [comment]
If you're asking about reverse stagers, no, I don't think we support fallback `LHOST` addresses. If you're asking about payload roaming support, that is also not supported yet.
