### ISSUE TITLE
I dont want to use listed predefined payloads . Is it possible to use own payload apk as payload by using metasploit

### ISSUE THREAD

**Issue by Ahmad-Mustafaa** [rapid7/metasploit-framework#13043]
Hi I want to use my own apk as payload instead of built in payload which is automatically embed with custom apk . Is there any way to do it using my apk as payload using msfvenom. 
Regards !

**Comment by timwr** [comment]
You can use msfvenom to inject the android payload into any APK, please see the documentation here:
https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/android/meterpreter/injection.md

Are you asking if you can use msfvenom to inject a custom APK into another APK? You can do that manually with `apktool`.

**Comment by Ahmad-Mustafaa** [comment]
Hi , 
Is there any help available for `apktool` ? it will be very helpful if found any link or documentation

**Comment by timwr** [comment]
You can use Google to find it: https://ibotpeaches.github.io/Apktool/documentation/
