### ISSUE TITLE
Why msfconsole takes too long to print version?

### ISSUE THREAD

**Issue by nsa** [rapid7/metasploit-framework#13044]
## Steps to reproduce

1. `time ./msfconsole --version`

![image](https://user-images.githubusercontent.com/4787945/76153922-a8dbab80-60e4-11ea-8d14-ee7328c5d608.png)

It took nearly 8 seconds to print version.

## Expected behavior

I think printing the version should be quick.

## Current behavior

I believe ~8s is not fast enough just to print version.

### Metasploit version

I am using `master` branch, [this commit](https://github.com/rapid7/metasploit-framework/commit/b85cd9b682c121941b9f64d27d11f6d6433d4273) `b85cd9b
`

### I installed Metasploit with:
- [x] Source install

Ruby version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

### OS

What OS are you running Metasploit on?

Windows 10, WSL Ubuntu 18.04.

**Comment by wvu-r7** [comment]
Same reason as in #9723: Framework is being loaded first. Splitting off the code for `msfconsole`'s help or version is a little more involved than it was for `msfvenom`. This is something for @adfoster-r7's team to address.
