### ISSUE TITLE
smb_login module runtime error [ pth ]

### ISSUE THREAD

**Issue by klionsec** [rapid7/metasploit-framework#13075]
ACTION:
msf5 > setg Proxies socks4:172.31.111.166:1080
msf5 > setg ReverseAllowProxy true
msf5 > use auxiliary/scanner/smb/smb_login
msf5 > set rhosts 192.168.159.0/24
msf5 > set smbdomain TATE
msf5 > set smbuser ITNET
msf5 > set smbpass aad3b435b51404eeaad3b435b51404ee:949aa2dd01d31533c620d53dedec795b
msf5 > set threads 20
msf5 > run
msf5 auxiliary(scanner/smb/smb_login) > version 
Framework: 5.0.80-dev-
Console  : 5.0.80-dev-
msf5 auxiliary(scanner/smb/smb_login) >

LOG:

[-] 192.168.159.0/24:445  - Auxiliary failed: RuntimeError Mdm Object conversion failed FATAL:  remaining connection slots are reserved for non-replication superuser connections

[-] 192.168.159.0/24:445  - Call stack:
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:56:in `rescue in json_to_mdm_object'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:48:in `json_to_mdm_object'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/remote_credential_data_service.rb:13:in `creds'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:54:in `block in creds'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:52:in `creds'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/login_data_proxy.rb:44:in `invalidate_login'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:63:in `invalidate_login'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/smb/smb_login.rb:141:in `block in run_host'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:234:in `block in scan!'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:154:in `block in each_credential'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/smb/smb_login.rb:119:in `run_host'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:117:in `block (2 levels) in run'
[-] 192.168.159.0/24:445  -   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[-] Auxiliary failed: RuntimeError Problem with HTTP request for type/path: GET /api/v1/workspaces message: undefined method `request' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:63:in `json_to_mdm_object'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/remote_workspace_data_service.rb:34:in `workspaces'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/workspace_data_proxy.rb:7:in `block in find_workspace'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/workspace_data_proxy.rb:5:in `find_workspace'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/framework.rb:317:in `module_event'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/framework.rb:340:in `on_module_complete'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:188:in `block in method_missing'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:186:in `each'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:186:in `method_missing'

**Comment by ccondon-r7** [comment]
Hey @klionsec, we ask for a bunch of information in the issue template. Please don't ignore it! Fill out each section if you want to have the best chance of having someone being able to look at and reproduce your issue. Alternatively, if you don't want to do this, try Slack: https://metasploit.com/slack
