### ISSUE TITLE
MSF Web service cant be started & Cant start database

### ISSUE THREAD

**Issue by 3top1a** [rapid7/metasploit-framework#13084]
## Steps to reproduce

How'd you do it?

1) install on arch
2) try to make it work

## behavior

when i try to run `msfdb init`i get:
[X@X-systemproductname ~]$ msfdb init
[?] Would you like to delete your existing data and configurations?: n
Found a database at /home/X/.msf4/db, checking to see if it is started
Starting database at /home/X/.msf4/db...failed
2020-03-15 20:38:15.178 CET [17179] LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
[?] Initial MSF web service account username? [X]: 
[?] Initial MSF web service account password? (Leave blank for random password): 
Attempting to start MSF web service...failed
[!] MSF web service does not appear to be started.
Please see /home/X/.msf4/logs/msf-ws.log for additional details.

## The log:

https://pastebin.com/PGBqVLqH

### Metasploit version

Framework: 5.0.73-dev
Console  : 5.0.73-dev

### I installed Metasploit with:
- [*] Kali package via apt (pacman in arch)
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Manjaro (Arch)

**Comment by jmartin-r7** [comment]
Looking at the pastbin details your install is executing against `ruby 2.7.0`.  Metasploit framework does not yet support `Ruby 2.7`.  This may be a compatibility issue.  Can you test with `2.6.5`?

**Comment by jmartin-r7** [comment]
Please note the arch `pacman` package is not built tested or distributed directly by this project.  Current arch support is primarily for source code checkout against ruby 2.6.5.

**Comment by 3top1a** [comment]
> Looking at the pastbin details your install is executing against `ruby 2.7.0`. Metasploit framework does not yet support `Ruby 2.7`. This may be a compatibility issue. Can you test with `2.6.5`?

I tried using ruby 2.6.5 but i still got the error.

**Comment by cn-kali-team** [comment]
Try [this](https://github.com/rapid7/metasploit-framework/issues/12098#issuecomment-557930966)
edit `/usr/share/postgresql/postgresql.conf.sample` file, delete `#`
```
unix_socket_directories = '/tmp' # comma-separated list of directories
```
- run `export PGHOST=/tmp` and restart your database service reinit msf database

**Comment by 3top1a** [comment]
@cn-kali-team It didn't work

**Comment by sseal** [comment]
@3top1a 

I'm on Manjaro and built it from source, [this comment](https://github.com/rapid7/metasploit-framework/issues/11999#issuecomment-589173378) helped me fix this issue, in conjunction with @cn-kali-team suggestion.
take a look at `.msf4/logs/msf-ws.log` again, you'll see  an abundance of `LoadError` entries:

```
/opt/metasploit/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load': cannot load such file -- documentation/api/v1/root_api_doc.rb (LoadError)
```

I had this issue, and fixed it on my machine by editing the paths in `lib/msf/core/web_services/servlet/api_docs_servlet.rb` to point to the absolute path of the documentation

So, instead of:
```
load 'documentation/api/v1/root_api_doc.rb'
``` 

set up a environmental  variable with the correct absolute path (I put mine in my `.bashrc`):
```
export METASPLOIT_DOC_LOCATION=home/<my_user>/<my_projects>/metasploit-framework/documentation/api/v1
```
then
```
load ENV["METASPLOIT_DOC_LOCATION"]+'/root_api_doc.rb'
load ENV["METASPLOIT_DOC_LOCATION"]+'/auth_api_doc.rb'
load ENV["METASPLOIT_DOC_LOCATION"]+'/credential_api_doc.rb'
load ENV["METASPLOIT_DOC_LOCATION"]+'/db_export_api_doc.rb'
load ENV["METASPLOIT_DOC_LOCATION"]+'/event_api_doc.rb'
```
or something to that affect. It's ugly, but it worked for me. Hope that helps!

**Comment by 3top1a** [comment]
@sseal This worked, but now it can't connect to the database.
I'm getting errors from PostgreSQL, will fix later.

**Comment by 3top1a** [comment]
I reinstalled everything, redid every step and it worked.
Still have no idea how.
