### ISSUE TITLE
rpc console don't provides interaction with meterpreter session

### ISSUE THREAD

**Issue by ilyapashuk** [rapid7/metasploit-framework#13081]
when I use msfrpc console api to call command like 'sessions -i 1', I get: 'starting interaction with 1', but console object don't starts to be a meterpreter command line provider, it don't changes prompt and don't goes out from the busy state.
I know about session api methods, but I think that the rpc console should provide the console identical to the msfconsole's console and so it should provide meterpreter line access with it's api without need to call some other methods to access the session command line.

**Comment by ccondon-r7** [comment]
Hi there, can you please give us all the information we request in the issue form? It is difficult to diagnose issues otherwise. Thanks!

**Comment by timwr** [comment]
@ilyapashuk you need to use the `session.shell_write` / `session.shell_read` RPC apis to interact with a shell session, and the `session.meterpreter_write` / `session.meterpreter_read` RPC apis for meterpreter sessions.
I don't think there is a plan to support `sessions -i` within the console (or the `console.read` and `console.write` APIs) but if you're able to add/fix yourself that would be awesome.
