### ISSUE TITLE
Can't Run metasploit because of libcrypt.so.1: version `XCRYPT_2.0' not found

### ISSUE THREAD

**Issue by Peter123438** [rapid7/metasploit-framework#13088]
i don't remember what happened exactly but, i was trying to fix an error in the msfvenom tool for apk rebuilding with apktool, so i had to install a certain lib package (i forgot its name) but then i think it removed some other packages that are related to MSF.

i tried to run apt-get install metasploit-framework so it'll download automatically the missing packages (in case there were missing packages) but no signs for missing packages were shown.

## Expected behavior

i saw no other similar issues, so i expect nothing without a fix.

## Current behavior

whenever i try to use metasploit framework or msfvenom i get the error:

ruby: /lib64/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /lib/x86_64-linux-gnu/libruby-2.5.so.2.5).

## System stuff
i'm running Kali GNU/Linux 64 bit on my laptop with dual boot option.
CPU i5 1.8ghz
6 GB of ram DDR3

### Metasploit version
4.17.1 ( it was up to date )

### I installed Metasploit with:

Metasploit was already installed on my system.

### OS
Kali GNU/Linux rolling 
gnome version 3.34.2

**Comment by jmartin-r7** [comment]
Kali distributes their own fork of metasploit-framework.  The version you are reporting is a bit behind  (current release is 5.0.81), unless you are referring to Metasploit Pro (which is not currently supported on Kali). Also the ruby version it is compiled against is not part of the code this project maintains.  Consider requesting help in the [Kali forums](https://forums.kali.org/forum.php) with this as it looks to be an env issue.  I suspect something you installed overwrote the `$PATH` in your environment when executing `msfvenom`.
