### ISSUE TITLE
WARNING: No database support: No database YAML file

### ISSUE THREAD

**Issue by hackdefendr** [rapid7/metasploit-framework#13103]
## Steps to reproduce

How'd you do it?

1. From a base Debian docker image, I followed the instructions for installing Metasploit, found here: https://computingforgeeks.com/install-metasploit-framework-on-debian/
2. Run msfdb init and it creates the database.yml under /var/lib/postgresql/.msf4/
3. Run msfconsole and see this:
```
[-] ***rting the Metasploit Framework console...-
[-] * WARNING: No database support: No database YAML file
[-] ***
```
4. I locate the database.yml.example file under /opt/metasploit-framework/embedded/framework/config/, so I simply copied the created database.yml file from /var/lib/postgresql/.msf4 to the above config folder and msfconsole starts right up.

## Expected behavior

What should happen?  I am guessing since msfdb created the database.yml that msfconsole would also be able to locate it.

## Current behavior

What happens instead? msfconsole starts up without database support.

File: /var/lib/postgresql/.msf4/logs/msf-ws.log
```
Writing PID to /var/lib/postgresql/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/backends/tcp_server.rb:16:in `connect'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:63:in `block in start'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        from /opt/metasploit-framework/embedded/bin/thin:23:in `load'
        from /opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
```

### Metasploit version

metasploit v5.0.81-dev-

### I installed Metasploit with:
- [ ] Kali package via apt
- [ x] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on? Debian 10 (docker)

**Comment by jmartin-r7** [comment]
How did you start the docker container?

The reported issue notes suggest you were using the `postgresql` user to install run metasploit.  Since that user is likely setup with very limited access in the container, you may need to create a standard user with sudoer rights that you would use for installation, setup, and execution of metasploit.

**Comment by hackdefendr** [comment]
I only generated the database as the postgres user which made logical sense to me since it is the database user. Everything else was done as root, and running msfconsole as root. This seems like it is about msfconsole not knowing how to find the database.yml file where msfdb creates it.

**Comment by jmartin-r7** [comment]
Installation of the `deb` package needs `root`. `msfdb` must be called as the user that will run `msfconsole` and is specifically required to not be `root`.

**Comment by jmartin-r7** [comment]
Also keep in mind metasploit brings the database binaries so if another postgresql is holding the port services will need to be stopped for metasploit db services to control the port.

**Comment by hackdefendr** [comment]
I uninstalled postgres and now msfconsole complains:
```
[-] ***rting the Metasploit Framework console...\
[-] * WARNING: No database support: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5433?
[-] ***
```
I don't see any postgres binaries installed by msfinstall.  So I guess I should reinstall postgres manually?

**Comment by hackdefendr** [comment]
OK I found the postgres binaries, but how do I start the server? Do I need to create an init script?
