### ISSUE TITLE
Postgres modules not properly working: Unknown auth type '10' with bufer content: (SCRAM-SHA-256)

### ISSUE THREAD

**Issue by ATrashInTheWorld** [rapid7/metasploit-framework#13104]
## Steps to reproduce
1. Select any postgres module, (ex: auxiliary/scanner/postgres/postgres_version)
2. Enter the required information and run

## Victime
The victime is a **Redhat 7 VM** with **Postgresql 11**

## Expected behavior
To retrieve/give information if the conditions are met.

## Current behavior
It doesn't seem to be able to even attempt a login. I tried the credentials with hydra and everything worked fine.

### Metasploit version
Framework: 5.0.81-dev-
Console: 5.0.81-dev-

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
Kali GNU/Linux Rolling
Version: 2020.1

According to **auxiliary/scanner/postgres/postgres_version.rb** line **90**, it might "Something we don't know yet".

**Comment by h00die** [comment]
I believe this was fixed in #12976

**Comment by ATrashInTheWorld** [comment]
Therefore I am not sure. If this is the wanted output for the situation, we can close the issue.
But just to make sure, I tried the module and threw the error mentioned before. However, when I run a pure brute-force () with Hydra for example), it doesn't throw that. 
Out of curiosity, why?

**Comment by jmartin-r7** [comment]
This is likely due to metasploit lock `pg` version currently restricted to `pg (~> 0.20)`.  For now the solution is to note connection types not supported, at some point in the future this lock will be removed when Rails 5+ support is officially ready.
