### ISSUE TITLE
Error running command powershell_shell: ArgumentError wrong number of arguments (given 4, expected 5): 5.0.80-dev

### ISSUE THREAD

**Issue by baggybin** [rapid7/metasploit-framework#13108]
## Steps to reproduce

How'd you do it?

1. Load powershell within Meterpreter
2. Execute powershell_shell

Powershell_execute and import function correctly

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/5694867/77246414-e67d2000-6c1e-11ea-90af-477fb2077d12.png">

### Metasploit version

5.0.80-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

Kali Linux

**Comment by OJ** [comment]
What's the Windows version of the victim PC?

**Comment by OJ** [comment]
Ooops, nevermind.

**Comment by OJ** [comment]
I'm wondering if this is a gem version issue for some reason. Running this off current master works fine for me:
```
[*] Starting interaction with 861...
meterpreter > use powershell
Loading extension powershell...Success.
meterpreter > powershell_shell
PS > write-host $(whoami)
stackpivot\oj
```

**Comment by space-r7** [comment]
The fix for this is in the latest release, so an update to `5.0.81` should fix the issue.

**Comment by sublimesol** [comment]
@space-r7   how do you update to that ? Ive just reinstalled from scratch and its saying 5.0.80-0kali -

**Comment by space-r7** [comment]
I believe to update on Kali, it's just `apt-get install metasploit-framework`.

**Comment by sublimesol** [comment]
space-r7
Its apt update and then apt install metasploit-framework but it doesnt work its only downloading 5.0.80

Does that mean its not on the repo yet?

**Comment by h00die** [comment]
that could be the case.  May take a week for the repo maintainers to incorporate the new release.

**Comment by timwr** [comment]
Fixed by https://github.com/rapid7/metasploit-framework/pull/13069
