### ISSUE TITLE
Add payloads to msfvenom zsh completion

### ISSUE THREAD

**Issue by Jab2870** [rapid7/metasploit-framework#13117]
## Steps to reproduce

1. Use ZSH
2. Type msfvenom --payload \<tab\>

## Expected behavior

Ideally, it would list all of the payloads with their descriptions

## Current behavior

Nothing. I assume that this is because the `msfvenom --list payloads` command can take a long time to run.

## Proposed solution

My solution is to cache the output of that command to a file and use that to populate the tab completion.

I am using it in my personal dotfiles here: https://github.com/Jab2870/dotfiles/blob/master/shells/zsh/completion/_msfvenom#L211-L228

I would be happy to create a pull request if you are happy with this solution.

**Comment by adfoster-r7** [comment]
Closing this, as it's been landed now #13140
