### ISSUE TITLE
Error running command wdigest:mod_process::getVeryBasicModulesListForProcess : (0x00000005) ӝ¿쀠n.a. (wdigest KO)

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#13121]
Error running command wdigest:mod_process::getVeryBasicModulesListForProcess : (0x00000005) ӝ¿쀠n.a. (wdigest KO)

 mimikatz_command -f sekurlsa::searchPasswords
mod_process::getVeryBasicModulesListForProcess : (0x00000005) ӝ¿쀠
Donn褳 LSASS en erreur

**Comment by bwatters-r7** [comment]
Please give us a bit more information, like the version of windows and what command you ran to cause the error.  Also the last few lines in the developer log would be useful, too.

**Comment by ccondon-r7** [comment]
Hi there! If you want to give us the information we ask for, feel free to re-open this issue. Closing for now!
