### ISSUE TITLE
hosts -c address,tags

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#13125]
## Steps to reproduce
msf5 > hosts -c address,tags

## Expected behavior
List out hosts in the database with 2 columns: address and tags.

## Current behavior
[-] Error while running command hosts: undefined method `find_host_tags' for #<Msf::DBManager:0x00005604283884e8>
Did you mean?  add_host_tag

Call stack:
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:335:in `find_host_tags'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:557:in `block (3 levels) in cmd_hosts'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:549:in `map'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:549:in `block (2 levels) in cmd_hosts'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:547:in `block in cmd_hosts'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2125:in `block in each_host_range_chunk'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2106:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2106:in `each_host_range_chunk'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:544:in `cmd_hosts'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:49:in `<main>'

### Metasploit version
Framework: 5.0.80-dev
Console  : 5.0.80-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali 2020.2 running

**Comment by adamgalway-r7** [comment]
@leebaird This issue is now fixed, thanks for drawing our attention to it!
