### ISSUE TITLE
Database stats

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#13136]
## Feature request
msf5 > stats

## Expected behavior
Show the count of the total number of hosts, services, vulns, notes and loot in the current workspace.

**Comment by h00die** [comment]
I like this idea!

**Comment by adfoster-r7** [comment]
@leebaird That's a cool idea! Out of interest, how would this fit into your overall workflow? i.e. What would you be doing that leads you wanting to know the count of hosts, loot, etc, and what would you normally expect to do next with that knowledge next?

Just wanting to tease out all of the requirements here 🎉

**Comment by h00die** [comment]
For me it's when I'm working on modules, I think I could delete my workspace and make a new one, but typically while testing modules I start with `loot -d`, and the works. It would just be nice to have an easy count to make sure everything's good and clean

**Comment by leebaird** [comment]
Lets say that I'm scanning a Class C. Knowing the number of hosts that I have in the workspace, I could check that number against what the client has for live hosts.

**Comment by h00die** [comment]
After doing service scanning against that, it would be quick and easy to do x services per host through one command instead of two and then counting the lines
