### ISSUE TITLE
auxiliary/scanner/http/http_hsts.rb Is Broken With SSL Errors

### ISSUE THREAD

**Issue by tekwizz123** [rapid7/metasploit-framework#13163]
## Steps to reproduce

How'd you do it?

1. Open Tab 1 
2. Type "python3 -m http.server" and wait for the info that the server is running.
3 Open Tab 2
4. Load msfconsole
5. Type "use auxiliary/scanner/http/http_hsts" (sans quotes)
6. Type "set RHOSTS 127.0.0.1"
7. Type "set RPORT 8000"
8. Encounter the error "Error: 127.0.0.1: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state
=error: wrong version number"
9. Try other websites with port 443. Find that module also returns errors like "OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure"

```
msf5 auxiliary(scanner/http/http_hsts) > set RHOSTS 127.0.0.1
RHOSTS => 127.0.0.1
msf5 auxiliary(scanner/http/http_hsts) > set RPORT 8000
RPORT => 8000
msf5 auxiliary(scanner/http/http_hsts) > run

####################
# Request:
####################
GET / HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
Content-Type: application/x-www-form-urlencoded


SSL_connect returned=1 errno=0 state=error: wrong version number
[*] Error: 127.0.0.1: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state
=error: wrong version number
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/http/http_hsts) >
```

## Expected behavior

Module prints out whether or not the host has HSTS enabled or not.

## Current behavior

Module will occasionally fail on some hosts with the error "OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: sslv3 alert handshake failure" or "Error: 127.0.0.1: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state
=error: wrong version number". It also appears to be failing to properly handle redirects at the moment.

### Metasploit version

Framework: 5.0.83-dev-bf8a1fc706
Console  : 5.0.83-dev-bf8a1fc706
Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

### I installed Metasploit with:
Source install (please specify ruby version)

### OS

Windows 10 Pro Insider Edition with WSL2 running Ubuntu 18.04 LTS

**Comment by leegengyu** [comment]
Facing the same issue - @tekwizz123, could I ask how did you manage to resolve this please?
