### ISSUE TITLE
Delete 'unknown' services from the db.

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#13162]
## Feature request

services -U

Delete 'unknown' services from the db.

**Comment by acammack-r7** [comment]
Is there a reason that `services --delete -s unknown` doesn't work?

**Comment by jmartin-r7** [comment]
```
msf5 > services --delete -S unknown
Services
========

host            port  proto  name     state  info
----            ----  -----  ----     -----  ----
192.168.18.195  8443  tcp    unknown  open

[*] Deleted 1 services
```

**Comment by acammack-r7** [comment]
Cool. We could definitely document how to use that better, but I'll close this issue since a way to delete the unknown services already exists.
