### ISSUE TITLE
[-] Auxiliary failed: SocketError getaddrinfo: Address family for hostname not supported

### ISSUE THREAD

**Issue by hazelbronco** [rapid7/metasploit-framework#13181]
## Steps to reproduce

How'd you do it?

1. use auxiliary/gather/enum_dns
2. set domain example.com
3. run

This worked fine before 3 weeks.

## Expected behavior

Output of DNS Information

## Current behavior

[-] Auxiliary failed: SocketError getaddrinfo: Address family for hostname not supported
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:1246:in `send'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:1246:in `block (2 levels) in send_udp'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver/timeouts.rb:53:in `block in timeout'
[-]   /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
[-]   /usr/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
[-]   /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
[-]   /usr/lib/ruby/2.5.0/timeout.rb:33:in `catch'
[-]   /usr/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver/timeouts.rb:52:in `timeout'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:1244:in `block in send_udp'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:1242:in `each'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:1242:in `send_udp'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:978:in `send'
[-]   /usr/share/metasploit-framework/lib/net/dns/resolver.rb:894:in `query'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:95:in `dns_query'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:203:in `get_a'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:178:in `dns_wildcard_enabled?'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:61:in `run'
[*] Auxiliary module execution completed

### Metasploit version

Framework: 5.0.74-dev
Console  : 5.0.74-dev

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
- [X] Pre Installed in Parrot OS

### OS

PRETTY_NAME="Parrot GNU/Linux 4.8"
NAME="Parrot GNU/Linux"
ID=parrot
ID_LIKE=debian
VERSION="4.8"
VERSION_ID="4.8"
HOME_URL="https://www.parrotlinux.org/"
SUPPORT_URL="https://community.parrotlinux.org/"
BUG_REPORT_URL="https://nest.parrot.sh/"

### Kernel
5.4.0-4parrot1-amd64

**Comment by tekwizz123** [comment]
Hmm just tried testing this module and its working fine for me with no timeouts? I noticed you are running version 5.0.74-dev, but the latest at the time of writing is 5.0.83-dev-791b51228f according to my version:

```
msf5 auxiliary(gather/enum_dns) > version
Framework: 5.0.83-dev-791b51228f
Console  : 5.0.83-dev-791b51228f
```

Putting that aside for a second though, I did a bit of digging into your output and found https://stackoverflow.com/questions/5985470/ipv6-address-to-domain-name, which suggests that `getaddrinfo()` is meant to return a list of addresses to connect to and if it returns that error then it will try and match it against the list of address families your system currently supports. If your system doesn't support that address family (such as if IPv6 is not supported by your host and the address returned was an IPv6 address), then `getaddrinfo()` will fail with the error `Address family for hostname not supported` as you have been observing.

From this I'd say its possible that your system may not have been set up to support IPv6 and the address returned might have been an IPv6 address. You can test if your system supports IPv6 by using something such as https://test-ipv6.com/.

Hope that helps, and apologies if it doesn't!
