### ISSUE TITLE
 Why there is no Ruby Meterpreter ?

### ISSUE THREAD

**Issue by davispuh** [rapid7/metasploit-framework#13189]
We have Python and PHP Meterpreter but there's no Ruby Meterpreter why?

**Comment by OJ** [comment]
Because there's basically zero need for one given the current ones that are available.

What would a Ruby version add that we don't already have?

**Comment by timwr** [comment]
> We have Python and PHP Meterpreter but there's no Ruby Meterpreter why?

It's because you haven't written it yet. Please implement it and send a pull request :)

**Comment by davispuh** [comment]
> Because there's basically zero need for one given the current ones that are available.
> 
> What would a Ruby version add that we don't already have?

Using and writing Ruby instead of Python :smile: 



> > We have Python and PHP Meterpreter but there's no Ruby Meterpreter why?
> 
> It's because you haven't written it yet. Please implement it and send a pull request :)

I see, nice! I was wondering there might be some other reason as I actually might write it at some point :yum:
