### ISSUE TITLE
Unable to get  domain hashdump on windows server 2016

### ISSUE THREAD

**Issue by haxpak** [rapid7/metasploit-framework#13196]
[*] Session has Admin privs
[*] Session is on a Domain Controller
[*] Pre-conditions met, attempting to copy NTDS.dit
[*] Using NTDSUTIL method
[*] NTDS database copied to C:\Windows\Temp\OpHDxzAb\Active Directory\ntds.dit
[*] NTDS File Size: 33554432 bytes
[*] Repairing NTDS database after copy...
[*] 
Initiating REPAIR mode...
        Database: C:\Windows\Temp\OpHDxzAb\Active Directory\ntds.dit
  Temp. Database: TEMPREPAIR6884.EDB

Checking database integrity.

                     Scanning Status (% complete)

          0    10   20   30   40   50   60   70   80   90  100
          |----|----|----|----|----|----|----|----|----|----|
          ...................................................

Integrity check successful.

Note:
  It is recommended that you immediately perform a full backup
  of this database. If you restore a backup made before the
  repair, the database will be rolled back to the state
  it was in at the time of that backup.

Operation completed successfully in 4.157 seconds.

[-] Failed to properly parse database: extapi_ntds_parse: Operation failed: 1004
[-] Error 1004 is likely a jet database error because the ntds database is not in the regular format
[*] Deleting backup of NTDS.dit at C:\Windows\Temp\OpHDxzAb\Active Directory\ntds.dit
[*] Post module execution completed

I am running the metasploit:latest docker

**Comment by bwatters-r7** [comment]
This behavior is expected, hash storage changed in 2016.  See https://github.com/rapid7/metasploit-framework/pull/9211
I would suggest using mimikatz
