### ISSUE TITLE
add notes for port

### ISSUE THREAD

**Issue by s0i37** [rapid7/metasploit-framework#13190]
Hello
I just want to suggest to add a tiny improvement for `notes` command.
Currently it seems metasploit doesn't provide adding any notes for port, only for host. And it is really a big dissadvantage IMHO.
Please allow to creating notes for ports:
`notes -a -t custom -n "some note" 10.0.0.0/24 -p 443`
Thank you.

**Comment by cn-kali-team** [comment]
I checked the column of Notes database. I can't find the port column. You must create a service first and then associate the service ID with notes
```
msf5 > services  -a -s http -p 80 -r tcp 10.20.1.1
[*] Time: 2020-04-20 11:26:07 UTC Service: host=10.20.1.1 port=80 proto=tcp name=http
msf5 > notes -a 10.20.1.1 -n "new port" -t "auto" 
[*] Time: 2020-04-20 11:30:51 UTC Note: host=10.20.1.1 type=auto data=new port

```
- Modify the service_id column in the Notes database，Here is 6

|id|created_at|ntype|workspace_id|service_id|host_id|updated_at|critical|seen|data|vuln_id|
|--|----------|-----|------------|----------|-------|----------|--------|----|----|-------|
|572|2020-04-20 11:30:51|auto|1|6|780|2020-04-20 11:30:51|||BAhJIg1uZXcgcG9ydAY6BkVU
||

- Service column

|id|host_id|created_at|port|proto|state|name|updated_at|info|
|--|-------|----------|----|-----|-----|----|----------|----|
|6|780|2020-04-20 11:26:07|80|tcp|open|http|2020-04-20 11:26:07||

- Now run notes on the command line
```
msf5 > notes 

Notes
=====

 Time                     Host       Service  Port  Protocol  Type  Data
 ----                     ----       -------  ----  --------  ----  ----
 2020-04-20 11:30:51 UTC  10.20.1.1  http     80    tcp       auto  "new port"

msf5 > 

```
I hope it can help you. If you have any questions to answer, I am not familiar with the database structure of Metasploit. I need help to start writing and modifying this function. Is there anyone willing to help me?

**Comment by s0i37** [comment]
If notes table has service_id column why it hasn't implemented yes?
The `notes` command doesn't  support port key.
Also it doesn't allow to append many notes of one type:
```
msf5 > hosts -a 10.0.0.1
[*] Time: 2020-04-20 13:00:11 UTC Host: host=10.0.0.1
msf5 > services -a -r tcp -p 80 -s http 10.0.0.1
[*] Time: 2020-04-20 13:00:39 UTC Service: host=10.0.0.1 port=80 proto=tcp name=http
msf5 > services -a -r tcp -p 8080 -s http_alt 10.0.0.1
[*] Time: 2020-04-20 13:00:47 UTC Service: host=10.0.0.1 port=8080 proto=tcp name=http_alt
msf5 > notes -a -t auto -n site1.com 10.0.0.1
[*] Time: 2020-04-20 13:01:12 UTC Note: host=10.0.0.1 type=auto data=site1.com
msf5 > notes -a -t auto -n site2.com 10.0.0.1
[*] Time: 2020-04-20 13:01:12 UTC Note: host=10.0.0.1 type=auto data=site2.com
msf5 > services 10.0.0.1
Services
========

host      port  proto  name      state  info
----      ----  -----  ----      -----  ----
10.0.0.1  80    tcp    http      open   
10.0.0.1  8080  tcp    http_alt  open   

msf5 > notes 10.0.0.1

Notes
=====

 Time                     Host      Service  Port  Protocol  Type  Data
 ----                     ----      -------  ----  --------  ----  ----
 2020-04-20 13:01:12 UTC  10.0.0.1                           auto  "site2.com"
```
I don't know better alternatives of storing information about hosts/services/sites then metasploit. 
A thinkg it might be good improvement, moreover it not so difficult to implement

**Comment by s0i37** [comment]
The `notes` command returns `port` column, however doesn't support filtering notes with `-p` key.
And on the contrary - `vulns` command supports `-p` key but output doesn't contain `port` column.

**Comment by s0i37** [comment]
ping
