### ISSUE TITLE
Can not drop into shell

### ISSUE THREAD

**Issue by karleegrey** [rapid7/metasploit-framework#13198]
![Screenshot_2020-04-05-15-29-05-173_com termux](https://user-images.githubusercontent.com/63185472/78471899-4cef5b80-7752-11ea-886d-fbf5acb44ad2.jpg)
## Steps to reproduce

How'd you do it?

$ shell

## Expected behavior
It should drop me in Shell

## Current behavior
Error running command shell: ArgumentError wrong number of arguments (given 4, expected 5)

### Metasploit version
v5.0.80-dev

### OS
android pie
Termux Emulator

###request
Plz solve my error as soon as possible....🙏🙏🙏

**Comment by bwatters-r7** [comment]
Any chance this is related to https://github.com/rapid7/metasploit-framework/issues/13060

**Comment by ccondon-r7** [comment]
Hi there! Termux isn't a supported platform at this time. The community does have some documentation on running Metasploit on Termux, but we don't provide tech support on that, sorry! Best of luck.

**Comment by karleegrey** [comment]
Ohk thanks for reply..
But if is there any solution anyone find then please help me.. to get rid of this...

**Comment by bcoles** [comment]
> 
> 
> Ohk thanks for reply..
> But if is there any solution anyone find then please help me.. to get rid of this...

This is probably related to #13060 which was resolved in #13064 a few weeks ago. In which case, updating Metasploit should resolve the issue.

As you're using an unsupported platform (Termux), you may need to wait until the packages for Termux are updated. Alternatively, [the patch](https://github.com/rapid7/metasploit-framework/pull/13064/files) is very small, so you could try patching yourself.
