### ISSUE TITLE
Session closed: reason:died

### ISSUE THREAD

**Issue by karthik0901** [rapid7/metasploit-framework#13192]
Hi guys.. I install termux in android mobile and install ngrok and metaspolit and set payload and create my apk file and send it to my another phone ..when i install that in my teremux it shows "meterpreter session 1 opend" but within few seconds it show "session closed reason:died"..can anyone help me to sort out this.

**Comment by tekwizz123** [comment]
Hello @karthik0901, its kind of hard to tell whats going on given the limited information you have provided. Could you please do a full listing of the commands you have used to generate the payload and what happens when the connection comes back? This may help us to determine what the error is a bit more.

On a related note though, here are some common reasons the session can die:
1. AV picks up your payload and deletes it, thus closing the connection.
2. Something happens on the target environment that throws an error, thus causing the payload to fail.
3. Networking issues between you and the target.

**Comment by karthik0901** [comment]
Sir i have first install ngrok in their official webste and dwld termux in
playstore and i install metaspoilt in termux sir..

Then i follow these proceedings sir without a single change . I completed
almost 99% but in the last step it shows session dead.

https://jtechcode.blogspot.com/2019/12/install-metasploit-in-termux-and.html?m=1

This is the result sir could you please help me to sort it out.

**Comment by karthik0901** [comment]
How can i sort out this?

**Comment by tekwizz123** [comment]
Hi @karthik0901, as I can't see what commands you used in your testing scenario, I can't help you right now. The information you have provided is great but some commands in that tutorial do have to be adjusted somewhat so without seeing what you typed and how you adjusted them, its very hard for me to do a proper analysis.

Please create a new comment with the commands you used when testing and I'll be happy to assist you from there.

**Comment by karthik0901** [comment]
Sure sir. I am attached the video that i have done. Please check it sir



  Screenrecording_20200404_211044.mp4
<https://drive.google.com/file/d/1VPGKVeUqDr-dYjvvgHmW_9sB09M9T15W/view?usp=drivesdk>

  Screenrecording_20200404_211607.mp4
<https://drive.google.com/file/d/1VVmCWmUU4ro05_CoB9wvn8udKvYuxt1r/view?usp=drivesdk>

**Comment by ccondon-r7** [comment]
Hey @karthik0901, Termux is not an officially supported platform. You might be able to find some community documentation, though (for instance: https://wiki.termux.com/wiki/Metasploit_Framework). Best of luck!

**Comment by karthik0901** [comment]
Sir i need to bypass whatsapp account . Is there any commands to run in the
metasploit framework

**Comment by tekwizz123** [comment]
@karthik0901 Please do not ask for help with illegal activities here, we will not provide help for such matters. This issue has been closed as per @ccondon-r7's comment as Termux is not an officially supported platform.

**Comment by karthik0901** [comment]
Okay sir..sorry for that hope u have a good day
