### ISSUE TITLE
metasploit termux

### ISSUE THREAD

**Issue by dava45** [rapid7/metasploit-framework#13199]
If you'd like to propose a feature, describe what you'd like to see. Mock ups of console views would be great.

If you're reporting a bug, please be sure to include the expected behavior, the observed behavior, and steps to reproduce the problem. Resource scripts, console copy-pastes, and any background on the environment would be appreciated.

For tips, see http://r-7.co/MSF-CONTRIB

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
