### ISSUE TITLE
Metasploit Framework 5.0.84 Setup Wizard Ended Prematurely

### ISSUE THREAD

**Issue by apollosnyder** [rapid7/metasploit-framework#13202]
I am running Windows 10 Pro and I tried to install Metasploit Framework 5.0.84 and it gives me the error "Metasploit Framework 5.0.84 Setup Wizard Ended Prematurely."

How do I fix this?

**Comment by tekwizz123** [comment]
@apollosnyder Can you please tell us what source you used to install Metasploit Framework? There are several places you could have installed it from, such as Omnibus, from Git, from the Pro installers, etc. Additionally if you have any other logs or screenshots these would be helpful to see what errors might have occurred prior to this occurring; its possible some other error caused the Setup Wizard to terminate prematurely.

**Comment by apollosnyder** [comment]
I installed it from: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
If I go to the official site to download it, it takes me to the Git page of it. 

I get this error

![mf5 0 84](https://user-images.githubusercontent.com/54876111/78835456-33eae280-79be-11ea-8e7a-8d924ab17d29.png)

**Comment by tekwizz123** [comment]
Ok so to test I used a Windows 10 x64 machine and I grabbed the binary from https://windows.metasploit.com/metasploitframework-latest.msi. Before running it, in Windows Defender I added an exception by browsing to `Virus and Threat Protection Settings`, then scrolled down to `Exclusions` and selected `Add or Remove Exclusions`. I then clicked on the `Add an exclusion` button, and added `C:\metasploit-framework` to the exclusion list (after first creating this folder). This is what it should look like once its done:

![Exception added for msf-framework directory in windows defender](https://user-images.githubusercontent.com/2746189/78843338-26d2f100-79c8-11ea-977f-f424356437b7.PNG)

I then ran the program and changed the install directory from `C:\` to `C:\metasploit-framework` within the installer (look to the bottom when choosing which components to install, you should see that it lists the install directory as `C:\` and there is a button next to that to change the install directory).

At this point after a few minutes of the files being copied over I also got the same error you were encountering, however the files do seem to have been copied over:

![files are still there though from msf installer](https://user-images.githubusercontent.com/2746189/78843565-c4c6bb80-79c8-11ea-8431-fe2c6ba61618.PNG)

Considering the files were still copied over I tried to then run `msfconsole.bat` and it seems to be working fine:

![seems to be working despite the error](https://user-images.githubusercontent.com/2746189/78843971-fe4bf680-79c9-11ea-9351-aceb3b8cc358.PNG)

**Comment by apollosnyder** [comment]
I've also tried using https://windows.metasploit.com/metasploitframework-latest.msi to download it. I did everything you did up there: Making a folder `metasploit-framework` and adding it to `exclusions`. Then I ran the setup wizard, let it extract the files into `C:\metasploit-framework`, then it ended prematurely. I tried running `msfconsole.bat` and it gave me this:
 - Note: I tried running it as both standard user and administrator
 
![msfconsole dot bat](https://user-images.githubusercontent.com/54876111/78846189-f6e01980-79d8-11ea-8965-02bc6590d606.jpg)


Back in February, I was able to install it perfectly fine and it let me use the online version, too. But, why isn't it working right now on our computers?

**Comment by gwillcox-r7** [comment]
@apollosnyder In those examples you are trying to run `msfconsole.bat` from `C:\Windows\system32` and from `C:\Users\Apoll`. You need to do `cd C:\metasploit-framework` and then do `msfconsole.bat`.

**Comment by gwillcox-r7** [comment]
Closing this issue as there has been no updates from the author in 2 weeks.

**Comment by surjith007** [comment]
> @apollosnyder In those examples you are trying to run `msfconsole.bat` from `C:\Windows\system32` and from `C:\Users\Apoll`. You need to do `cd C:\metasploit-framework` and then do `msfconsole.bat`
As you told "gwillcox-r7" i ran `msfconsole.bat` from C:\metasploit-framework, but it ended
![m1](https://user-images.githubusercontent.com/66822153/84570006-08aeb600-ada8-11ea-95f3-a5b71cbf9428.PNG)

**Comment by dimablox** [comment]
im having the same issue :(

**Comment by sssseossss** [comment]
I have the same issue too. Clean Windows server 2016, Defender disabled.

**Comment by IAMinZoho** [comment]
Run CMD with elevated permissions and run this command:
metasploitframework-latest.msi /L*v msf.log

It will install Metasploit in C Drive with success!

**Comment by gwillcox-r7** [comment]
Locking issue as this is an older installer version at this point and we encourage people to open new issues and link to existing closed ones vs commenting on older issues. We can then reopen closed issues if needed in the event that there appears to be a case of an old issue not being appropriately fixed.
