### ISSUE TITLE
Cant able to extract and install tor browser in kali linux##

### ISSUE THREAD

**Issue by karthik0901** [rapid7/metasploit-framework#13203]
Im running my kali linux on vm virtualbox.
When im installing Tor browser on linux ,when i extract the file it won't extract instead it shows no such  file or directory found. 

### os

What OS are you running ?
Windows 10

**Comment by karthik0901** [comment]
![IMG_20200407_060010](https://user-images.githubusercontent.com/49391020/78618034-e4f65d80-7896-11ea-8492-e541f86fd159.jpg)

![IMG_20200407_060004](https://user-images.githubusercontent.com/49391020/78618059-f6d80080-7896-11ea-99b3-6e2bd3868b0a.jpg)

**Comment by OJ** [comment]
This has absolutely nothing to do with Metasploit.

**Comment by deviddk** [comment]
i am also face this problem
