### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Quessts** [rapid7/metasploit-framework#13219]
I tried installing metasploit on kali linux and this is what i keep getting
 unable to securely remove '/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/metasploit-payloads-1.3.87/data/meterpreter/ext_server_priv.x86.dll.dpkg-new': Permission denied

**Comment by gwillcox-r7** [comment]
@alnesef Try the following as the `root` user:

```
chmod 666 /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/metasploit-payloads-1.3.87/data/meterpreter/ext_server_priv.x86.dll.dpkg-new
```
This should set the file to be readable and writeable by everyone, which should allow the installer to remove the file.

In future please use the template that is included by default when submitting issues and fill out its various sections appropriately. This helps to replicate your issue better by setting up the same operating system, Ruby version, and environment, and speeds up the time it takes us to debug your issue.

**Comment by gwillcox-r7** [comment]
Closing this issue for now as there hasn't been any updates or response on this for over 3 months now.
