### ISSUE TITLE
Changing SERVICENAME on service_exe

### ISSUE THREAD

**Issue by BrunoMCBraga** [rapid7/metasploit-framework#13229]
I have been trying to deploy a Metasploit service payload on a Windows 10 VM. The idea is to replace the current binary for the service with mine. I noticed that it was failing with:

"The Service did not Respond to the Start or Control Request in a Timely Fashion"

I noticed that the default service name that RegisterServiceCtrlHandlerA is being called with SERVICENAME which is the default Msfvenom service name string embedded. I need to change this through command line. Otherwise, RegisterServiceCtrlHandlerA will always fail.

Following up on: 

https://github.com/rapid7/metasploit-framework/issues/4275 (perhaps unrelated but still related to tuning of internal strings and parameters)

Is it possible to specify the name of a service for service_exe payloads through msfvenom command line?

I see: https://github.com/rapid7/metasploit-framework/blob/d0ff7393e6a5b5b2f487d42cad1e3d4b000b526c/lib/msf/util/exe.rb#L634

but i don't know how to tune that opts parameter through the command line. Not a Metasploit developer. It seems that the servicename is just mapped from other parameter on the command line.

Would someone be so kind to point me the direction? I can replace with SED but if the service name is too big i may write too much on the binary.

Many thanks

**Comment by gwillcox-r7** [comment]
Hmm so I did some diving into this, and my understanding is that if we trace this back, you would normally use the `exe-service` option to generate a service EXE in `msfvenom`. Looking through the code for this, we can see that the backend code which handles this is this:

https://github.com/rapid7/metasploit-framework/blob/d0ff7393e6a5b5b2f487d42cad1e3d4b000b526c/lib/msf/util/exe.rb#L2137-L2143

Looking at the code for `to_win64pe_service` we can see it is defined in the same file:

https://github.com/rapid7/metasploit-framework/blob/d0ff7393e6a5b5b2f487d42cad1e3d4b000b526c/lib/msf/util/exe.rb#L657-L672

And the code for `to_win32pe_service` is similar:

https://github.com/rapid7/metasploit-framework/blob/d0ff7393e6a5b5b2f487d42cad1e3d4b000b526c/lib/msf/util/exe.rb#L624-L655

Note that both of these methods set `opts[:exe_type] = :service_exe` to indicate the exe is a service exe. Interestingly for x86 this is only applied if `opts[:sub_method]` is set. I'm not sure why this is done to be honest; this will likely require additional investigation.

If we temporarily ignore the x86 issue, we can see that in the event that the exe is determined to be a service exe, aka `opts[:exe_type]` is set to `:service_exe`, the function `exe_sub_method`will be called. Looking at `exe_sub_method` we can see the following:

https://github.com/rapid7/metasploit-framework/blob/d0ff7393e6a5b5b2f487d42cad1e3d4b000b526c/lib/msf/util/exe.rb#L535-L544

We can clearly see here that `opts[:servicename]` is being used yet nowhere so far in this chain has the user had any chance to set this data. Furthermore, as mentioned before, there is a chance that x86 payloads may not even be treated a service payload despite it calling `to_win32pe_service`, which given its name, its reasonable to expect that it should always generate a win32 PE that can be run as a service.

@BrunoMCBraga I'll mark this as a bug for now until further notice and talk to some of the other developers about this. It seems there are a few issues going on here that I'd like to double check a bit further, but the notes above should form my initial analysis of your question.

**Comment by BrunoMCBraga** [comment]
Hopefully i understood your words. It seemed to me that you were processing some option with the name of the service but looking back using my newbie] knowledge on the coding guidelines you guys use, i could not trace this back to to an input from the user.

I was wondering what option can i use to change the service name. 

Thanks in advance.

**Comment by gwillcox-r7** [comment]
@BrunoMCBraga Right now I do not believe there is a way for the user to change the service name. I am looking into adding some code to allow users to do this. This may take a few days as I have some other PRs that I am working on at the moment and trying to close, but once those are done I am planning to come back and fix this issue.

**Comment by gwillcox-r7** [comment]
@BrunoMCBraga sorry it took so long, but about to fix this with a PR now, should hopefully be coming in soon :)

**Comment by BrunoMCBraga** [comment]
This is great gwillcox-r7. Apologies for delayed response and thanks for pushing this forward :)
