### ISSUE TITLE
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=/sdcard/snapjs.jpg flg=0x10000000 }

### ISSUE THREAD

**Issue by greyhatsid** [rapid7/metasploit-framework#13226]
![20200410_155219](https://user-images.githubusercontent.com/63299565/78984684-7fc79400-7b44-11ea-897e-c0389bdc841d.jpg)

**Comment by gwillcox-r7** [comment]
@greyhatsid Can you provide more info about your environment and setup that you used for testing? Might help others with reproducing the issue

**Comment by timwr** [comment]
I suspect you simply need to install some kind of image gallery. Or we can modify the behaviour here: https://github.com/rapid7/rex-core/pull/8 (perhaps to call termux-open)
However Termux isn't officially supported some I'm closing this.
