### ISSUE TITLE
ipv6 and metasploit-framework

### ISSUE THREAD

**Issue by machinexa2** [rapid7/metasploit-framework#13228]
Hey creators, i use my ipv6 as lhost and sometimes as rhost. Will it work? If not then make support for ipv6. Also there is no page on :: https://github.com/rapid7/metasploit-framework/wiki :: about ipv6. So add a new page on the wiki about ipv6 and its support and FAQ related to ipv6.

**Comment by wvu-r7** [comment]
It's a little hit-or-miss. You may need the bracket syntax for IPv6: `[::1]`.
