### ISSUE TITLE
warning: deprecated object#=~is called on integer; it always returns nil

### ISSUE THREAD

**Issue by greyhatsid** [rapid7/metasploit-framework#13225]
![20200410_155543](https://user-images.githubusercontent.com/63299565/78984450-e00a0600-7b43-11ea-825d-477ac734a19e.jpg)
![20200410_155132](https://user-images.githubusercontent.com/63299565/78984510-05970f80-7b44-11ea-954f-5f3a14f6857f.jpg)

**Comment by h00die** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
