### ISSUE TITLE
pg_ctl: another server might be running;

### ISSUE THREAD

**Issue by greyhatsid** [rapid7/metasploit-framework#13224]
![20200410_155100](https://user-images.githubusercontent.com/63299565/78984244-68d47200-7b43-11ea-9bd2-aa86d45d1937.jpg)

**Comment by h00die** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715
