### ISSUE TITLE
Gather chrome cookies error

### ISSUE THREAD

**Issue by sharp312** [rapid7/metasploit-framework#13233]
## Steps to reproduce

How'd you do it?

1. Use post/multi/gather/chrome_cookies
2. set session
3. run

The target OS is my windows 10 virtual machine. The session im running the module on has system permissions. 64 bit

## Expected behavior

It should grab all the chrome cookies and store them in .msf4/loot

## Current behavior

I get an error that says: Post aborted due to failure: unknown: Failed to retrieve cookie data

### Metasploit version

Framework: 5.0.83-dev-
Console  : 5.0.83-dev-

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Ubuntu 18.04

**Comment by gwillcox-r7** [comment]
Hi @sharp312, are you using the professional version of Metasploit, also known as Metasploit Pro? Also it would help us if you could also post the version of Chrome you are testing and the version of Windows 10 you are running (ie v1809, v1909, etc) so we better attempt to reproduce this issue.

**Comment by sharp312** [comment]
> Hi @sharp312, are you using the professional version of Metasploit, also known as Metasploit Pro? Also it would help us if you could also post the version of Chrome you are testing and the version of Windows 10 you are running (ie v1809, v1909, etc) so we better attempt to reproduce this issue.

Hey @gwillcox-r7 I am running chrome version 81.0.4044.92 and windows 10 pro build 18363.657. I am not using Metasploit pro.

I'm not sure if the module is meant to do this but when I run it I can see a black command prompt window open for a short amount of time, or if I have chrome open and run it a new chrome tab opens with the url to the temporary html file
