### ISSUE TITLE
Metaploit not binding when starting listener

### ISSUE THREAD

**Issue by iii235** [rapid7/metasploit-framework#13278]
When I try to start a listener, I get a binding error. Can you tell me how to fix this error?

**Comment by h00die** [comment]
You've given almost no details, so it is very hard to give you a detailed answer. Most likely cases:
1. You picked an IP that you don't have access to
2. You picked a port already in use
3. You picked a port you don't have privilege to bind to

**Comment by iii235** [comment]
I use Kali linux. I know that I'm using the right ip and I'm using a free port. Can you show me how to get the privilege to bind to a port?

**Comment by h00die** [comment]
Unfortunately this is not the right place for that. This is for submitting bugs in metasploit, not learning how to use it. Please try slack or IRC, or a forum.
