### ISSUE TITLE
Divide Up Packrat #11998

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#13284]
This is an effort to divide up the packrat submission (#11998, #11719) and put the contents into individual modules, or ensure existing modules gather all the needed files.  Hopefully afterwards a script could be written to execute all of these to emulate the packrat submission.

of note these only worked on Windows for packrat
 
## email
- [ ] incredimail - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR3
- [x] outlook - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR35
- [ ] operamail - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR223
- [ ] postbox - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR281
- [x] thunderbird - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR573
- [ ] windowslivemail - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR744
## chat
- [ ] AIM - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR776
- [ ] digsby - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR834
- [ ] gadugadu - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR866
- [ ] ICQ - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR899
- [ ] miranda - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR957
- [x] nimbuzz - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR989
- [x] pidgin - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1013
- [ ] qq - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1070
- [x] skype - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1084
- [ ] tango - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1115
- [ ] tlen.pl - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1155
- [x] trillian - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1194
- [ ] viber - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1243
- [ ] xchat - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1273
## gaming
- [ ] xfire - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1305
## browsers
- [ ] chrome - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1347
- [ ] comodo - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1418
- [ ] coolnovo - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1524
- [x] firefox - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1545
- [ ] flock - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1643
- [ ] ie - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1679
- [ ] k-meleon - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1693
- [ ] maxthon - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1782
- [ ] opera - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1814
- [ ] srware - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1858
- [ ] safari - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1924
- [ ] seamonkey - https://github.com/rapid7/metasploit-framework/pull/11998/files#diff-bcdba70ca1877b43583af246f36a5b8aR1956

**Comment by h00die** [comment]
incredimail shut down on March 20, 2020. While you can still find installers, and they work, the product won't be able to 'finish registration', and therefore let you get to a gui to make emails.
@danhallsworth1 do you or your group have a copy of `msg.iml` you could share for testing?

**Comment by h00die** [comment]
outlook is done already: https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/outlook.rb

**Comment by h00die** [comment]
thunderbird gets creds, but not email. calling that half done: https://github.com/rapid7/metasploit-framework/blob/master/modules/post/multi/gather/thunderbird_creds.rb

**Comment by bcoles** [comment]
While you're at it, there's a few old `scripts` which are somewhat related. https://github.com/rapid7/metasploit-framework/issues/7789#issuecomment-463961145

* https://github.com/rapid7/metasploit-framework/blob/master/scripts/meterpreter/get_pidgin_creds.rb
* https://github.com/rapid7/metasploit-framework/blob/master/scripts/meterpreter/get_filezilla_creds.rb

**Comment by h00die** [comment]
also `post/multi/gather/pidgin_cred` and `post/multi/gather/filezilla_client_cred`

**Comment by h00die** [comment]
I think the biggest problem I see is packrat would pull files (which had creds), but then do nothing with them.  For many of these, the decryption is public (if not annoying), so it would be better for someone to implement the decryption in ruby and db the creds.  However, the draw to do such is most likely VERY low since (at least the apps not done yet, that ive looked at) have been EOL.

**Comment by h00die** [comment]
then again `multi/gather/thunderbird_creds` just pulls the files and says to use a 3rd party tool....

**Comment by smcintyre-r7** [comment]
FWIW I'd prefer to see an emphasis on consolidation rather than division. Modules that do similar things are more easily maintained within a single file, and if they can automatically enumerate the right thing to do (based on finding what's installed for example) then that removes one more thing the user has to handle.

**Comment by danhallsworth1** [comment]
@h00die if you're still wanting a copy of an incredimail file here's one I've just changed the extension to .txt so I can attach it here.
[msg.txt](https://github.com/rapid7/metasploit-framework/files/4510806/msg.txt)

**Comment by h00die** [comment]
I'm working on the `enum_xchat` module now, updating it through 8yrs of libs, and adding hexchat support (since xchat died 5yrs ago but hexchat is a fork).  Will also make it a multi module and add docs.

**Comment by wvu-r7** [comment]
See #15200.
