### ISSUE TITLE
Gemfile.lock pushed to master 5 days ago

### ISSUE THREAD

**Issue by R3dy** [rapid7/metasploit-framework#13310]
There is a Gemfile.lock in the main repo.  It's messing up my install, FYI.

**Comment by bcoles** [comment]
Metasploit has pushed a `Gemfile.lock` file for many years.

If there's an issue with dependencies, it would be useful to know which operating system you're using, how you're using metasploit (presumably from `master` branch), what version of Ruby you're using, and what dependency issues you're facing.

**Comment by R3dy** [comment]
No issue after I delete Gemfile.lock and re-bundle
