### ISSUE TITLE
Installation on Win10

### ISSUE THREAD

**Issue by Karss7** [rapid7/metasploit-framework#13335]
## Steps to reproduce

1. Download .msi (https://windows.metasploit.com/metasploitframework-latest.msi)
md5sum: `93aaecda414b41622b6f2eb91d788ad3`
2. During installation select the folder `D:\Utilits\metasploit\`

## Expected behavior

`D:\Utilits\metasploit\metasploit-framework\bin\` in PATH variable
Metasploit binaries in `D:\Utilits\metasploit\metasploit-framework\bin\`

## Current behavior

What happens instead?

`D:\Utilits\metasploit\metasploit-framework\bin\` in PATH variable
But binaries in `D:\metasploit-framework\bin`

### Metasploit version

Framework: `5.0.87-dev-1bec0a9c199735e9088ebfb0e6332fed5ab49db8`
Console  :` 5.0.87-dev-1bec0a9c199735e9088ebfb0e6332fed5ab49db8`

### OS

Windows 10 version 1903 (Build 18362.778)

**Comment by jmartin-r7** [comment]
Interesting, will test this further, this issue likely belongs in https://github.com/rapid7/metasploit-omnibus as that project builds installers.

**Comment by jmartin-r7** [comment]
Confirmed, the WIX installer is currently completely ignoring user selected installation path. This is likely an additional report of https://github.com/rapid7/metasploit-omnibus/issues/115.

Closing to favor tracking in packaging project.
