### ISSUE TITLE
Msfconsole not loading in termux

### ISSUE THREAD

**Issue by hood1** [rapid7/metasploit-framework#13337]
### I installed Metasploit with Termux but when I try starting it, it is showing this 
"CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal.so" not found". 
Please do help me out with this.

**Comment by gwillcox-r7** [comment]
Closing issue as Termux is not an officially supported platform.
