### ISSUE TITLE
Activerecord

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [rapid7/metasploit-framework#13355]
Linux kali 3.4.0-g85d04d0 #4 SMP PREEMPT Sat Mar 3 15:28:42 EET 2018 armv7l
The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Apr 28 13:34:47 UTC 2020 on pts/5
root@kali:~# service postgresql start
Starting PostgreSQL 12 database server: main.
root@kali:~# msfdb delete
Running in chroot, ignoring request: status
[i] Database already started
[+] Dropping databases 'msf'
[+] Dropping databases 'msf_test'
[+] Dropping database user 'msf'
[+] Deleting configuration file /usr/share/metasploit-framework/config/database.yml
Running in chroot, ignoring request: status
[+] Stopping database
Running in chroot, ignoring request: stop
root@kali:~# msfdb init
Running in chroot, ignoring request: status
[i] Database already started
[+] Creating database user 'msf'
[+] Creating databases 'msf'
[+] Creating databases 'msf_test'
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
root@kali:~#

Im using os kali nethunter

**Comment by adfoster-r7** [comment]
This is a warning created by Ruby 2.7 and activerecord 4.2.11.1 - for more details see https://github.com/rapid7/metasploit-framework/issues/12809

It can safely be ignored for now, and will be fixed in the future.
