### ISSUE TITLE
rm_rf method in lib/msf/core/file.rb is misleading

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-framework#13369]
## Steps to reproduce

How'd you do it?

1. Create a folder on a remote linux target
2.Place another folder in that folder
3. Run `rm_rf` from the file.rb library
4. Watch it not delete the directory
5. Repeat steps 1 & 2
6. run cmd_exec("rm -rf "\"#{path}"\")
7. Watch it succeed.

This happens because if you check out `rm_rf`, you can see:
```
  #
  # Delete remote directories
  #
  # @param remote_dirs [Array<String>] List of remote directories to
  #   delete
  # @return [void]
  def rm_rf(*remote_dirs)
    remote_dirs.each do |remote|
      if session.type == "meterpreter"
        session.fs.dir.rmdir(remote) if exist?(remote)
      else
        if session.platform == 'windows'
          cmd_exec("rd /s /q \"#{remote}\"")
        else
          cmd_exec("rm -rf \"#{remote}\"")
        end
      end
    end
  end
  alias :file_rm :rm_f
  alias :dir_rm :rm_rf
```

If you have a meterpreter session, it calls `session.fs.dir.rmdir` which in a Linux meterpreter goes through to the eio library which calls `rmdir` from `unistd` (https://linux.die.net/man/3/rmdir).  That's not equivalent to `rm -rf`, which is what is called if you have a shell session.  Specifically, `rmdir` will fail if it is not empty, which is sort of the point of `-rf`.

Either we should just remove the meterpreter condition in rm_rf and always call cmd_exec, or we should see if there's a way to make the meterpreter case and the shell case act in a similar fashion.
You can see an example of that confusion causing problems here: https://github.com/rapid7/metasploit-framework/pull/13290

**Comment by wvu-r7** [comment]
Since #9369 was landed after #8279, I think this one's my fault. Since only _some_ of the Meterpreters support recursive directory deletion, I think the safest course of action may be to defer to command execution until we can implement recursive deletion for all Meterpreters.

**Comment by smcintyre-r7** [comment]
:100: I would definitely like to have a feature matrix. It would be immensely useful.

**Comment by wvu-r7** [comment]
Honestly, `rmdir` is also misleading in a Meterpreter context, since it depends on the implementation.

**Comment by smcintyre-r7** [comment]
I looked into the behavior here across different Meterpreters and this is what I found:

| Meterpreter | Platform | Deletes non-empty directories? |
|-|-|-|
| windows | windows |  yes |
| java | linux | no |
| java | windows | no |
| mettle | linux | no |
| php | linux | no |
| python | linux | yes |

I would be in favor of updating Java, PHP and Mettle to just always delete the tree recursively and do what Windows and Python do. This would mean that the user wouldn't need to worry about what the Meterpreter / platform is while also handling the most common use case.

Alternatively, a recursive flag or a new rmtree function could be added that would do it recursively. This option would require touching all of the Meterpreter implementations though.

Generally, given that Windows was the O.G Meterpreter and it is the most feature-complete it makes sense to use it as the reference implementation. That's probably why Python behaves like it in this case.

Thoughts?

**Comment by wvu-r7** [comment]
I will believe anything you say, Spencer.

**Comment by smcintyre-r7** [comment]
Hooray, this now done. The 3 Meterpreter implementations (PHP, Java, Mettle) that did not delete their contents recursively now do so.
