### ISSUE TITLE
Error loading with msfconsole

### ISSUE THREAD

**Issue by pyroot99** [rapid7/metasploit-framework#13377]
## Steps to reproduce

whenever I am using msfconsole im getting this error 

`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil`

### Metasploit version

Framework: 5.0.86-dev
Console  : 5.0.86-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

Kali Linux

**Comment by gwillcox-r7** [comment]
@pyroot99 This issue should be fixed in `5.0.88-dev`, please upgrade to that version and test again. Closing as this is a known issue that has been addressed. If the issue still persists, feel free to open this issue again.

**Comment by pyroot99** [comment]
How can I update it to `5.0.88-dev` I tried `apt update && apt upgrade` it doesnt seem to update metasploit-framework

**Comment by bcoles** [comment]
> 
> 
> How can I update it to `5.0.88-dev` I tried `apt update && apt upgrade` it doesnt seem to update metasploit-framework

Metasploit updates are available through the usual update channels.

If you're using Metasploit from the git repository, you can simply `git pull`.

If you've installed Metasploit using an operating system package manager, you'll need to wait until the package maintainer pushes an updated package.

`msfupdate` can be used to update Metasploit.
