### ISSUE TITLE
ruby version conflict during install

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [rapid7/metasploit-framework#13378]
Hello, when i try to install it with ruby 2.6.6 , some dependencies tells they need ruby < 2.5;
and when i try with ruby 2.4 (which is < 2.5) : metasploit tells me it need a ruby > 2.5 :/ 

## Steps to reproduce

How'd you do it?

1. install ruby ruby 2.6.6 + devkits
2. git clone https://github.com/rapid7/metasploit-framework.git
3. cd metasploit-framework
4. gem install bundler
5. bundle install

## Current behavior

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    metasploit-framework was resolved to 5.0.87, which depends on
metasploit_data_models (~> 3.0.10) was resolved to 3.0.10, which depends
on
        pg was resolved to 0.21.0, which depends on
          ruby (< 2.5) x64-mingw32

    sqlite3 (~> 1.3.0) was resolved to 1.3.13, which depends on
      ruby (>= 1.8.7) x64-mingw32

Could not find gem 'ruby (< 2.5)', which is required by gem 'sqlite3 (~>
1.3.0)', in any of the relevant sources:
  the local ruby installation
```

### Metasploit version

fresh clone 

### I tried to install Metasploit with:
- [x] Source install (with ruby 2.6.6)

### OS

Windows 10

**Comment by AlanFoster** [comment]
@mIcHyAmRaNe There's a simple installer for Metasploit here that might be worth checking out - https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#installing-metasploit-on-windows

It comes with all of the dependencies that you need

**Comment by mIcHyAmRaNe** [comment]
@AlanFoster thank you, i know but i prefer sources...
and even if there are an alternative, get running metasploit from sources exist so it should work.

will see what developers will answer about the conflict, i think i have to upgrade sqlite3 in requirement file but dont know if using sqlite3 newer than 1.3.0 will cause issues
