### ISSUE TITLE
Error can start metasploit but get an error

### ISSUE THREAD

**Issue by FaizTechIndo** [rapid7/metasploit-framework#13389]
Help me
i want to start metasploit but
I see an error like this :

/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil

 When starting and closing metasploit

### Metasploit version
Framework: 5.0.86-dev
Console  : 5.0.86-dev

### I installed Metasploit with:
- [ ] Parrot package via apt

### OS

What OS are you running Metasploit on?
Parrot Linux

**Comment by gwillcox-r7** [comment]
These warnings were fixed with 5.0.87 and occur as you are running a version of Ruby 2.7, which causes depreciation errors as some of the functions Metasploit uses are marked as depreciated in Ruby 2.7. 

To quote @bcoles: 

> Metasploit updates are available through the usual update channels.
>
> If you're using Metasploit from the git repository, you can simply git pull.
>
> If you've installed Metasploit using an operating system package manager, you'll need to wait until the package maintainer pushes an updated package.
>
> msfupdate can be used to update Metasploit.
