### ISSUE TITLE
Suggestion: remove "Actions" from module with only one action (which is also the default one) to prevent confusion

### ISSUE THREAD

**Issue by cnotin** [rapid7/metasploit-framework#13403]
## Steps to reproduce

1. `use auxiliary/server/dhcp`
2. `show actions`

## Expected behavior

There shouldn't be any "action" for module with only one action (which is also the default one)

## Current behavior

We see the "Service" action but... What does it do? Should I set it? Why is there only one? I think it's confusing...

```terminal
msf5 auxiliary(server/dhcp) > show actions

Auxiliary actions:

   Name     Description
   ----     -----------
   Service  
```

Here is the action creation:
https://github.com/rapid7/metasploit-framework/blob/4a853beb8d8be4369cdef67d3d655385d1edfa00/modules/auxiliary/server/dhcp.rb#L20-L28

But it doesn't seem to be used afterwards.

Several other modules are concerned (non-exhaustive list), for example "ftp" or "fakedns" under auxiliary/server

Let me know what you think, and if you like it I can propose a PR to clean it.

**Comment by wvu-r7** [comment]
It should have a `Description` hash set.

**Comment by cnotin** [comment]
Yes that's another possibility. But even when there's only one action? Is it the chosen convention?

**Comment by wvu-r7** [comment]
I mean it already has that hash, and it should be set to describe the action.

**Comment by wvu-r7** [comment]
Even if you have only one option, it is useful to describe what you are going to do in the module. Removing it unconditionally sounds like a bad idea.

**Comment by wvu-r7** [comment]
`Service` is just poorly named and described.

**Comment by cnotin** [comment]
Ok I can try to add description to other modules too. I've seen a couple with a single action and no description

**Comment by wvu-r7** [comment]
Yeah, that's just bad practice.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/blob/01a220ec21de4fab71bc4f6a28ebdaeed6843a75/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb#L31-L33

For instance, I find the description here useful. That said, I probably should have expanded it more. The implication is you're dumping from vmdir, but that could definitely be explicit, since not everyone reads the **module** description.

**Comment by cnotin** [comment]
Sure :)
I wasn't sure if the convention was to have "Actions" defined only when there were several possible (hence the suggestion to remove), or in all cases. Fine then ;)

**Comment by cnotin** [comment]
I'll propose a PR later to add better descriptions for those modules

**Comment by wvu-r7** [comment]
If you don't define it, there will be no listed action. Kind of a missed opportunity to be descriptive in the action you will perform. That's all. :)

**Comment by wvu-r7** [comment]
So maybe we can hide the table if there are no actions, but I prefer to add one if there isn't one.

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/pull/13301/files#r419855409

**Comment by wvu-r7** [comment]
Oh, nvm, it's already hidden if there's none.
