### ISSUE TITLE
when i want to install metasploit by command prompt then this was happend.

### ISSUE THREAD

**Issue by Annonymin12** [rapid7/metasploit-framework#13425]
C:\Windows\system32>cd..

C:\Windows>cd..

C:\>cd metasploit

C:\metasploit>console.bat
The system cannot find the path specified.

C:\metasploit>gem install rvm
Could not find rake-12.3.2 in any of the sources
Run `bundle install` to install missing gems.

C:\metasploit>

![Screenshot (30)](https://user-images.githubusercontent.com/65062872/81479568-d7414880-9245-11ea-8947-36430c002400.png)

**Comment by bcoles** [comment]
`rvm` is not a gem.

Also, dependencies should have been installed when you installed Metasploit. How did you install Metasploit?
