### ISSUE TITLE
develop or improve metasploit module (project)

### ISSUE THREAD

**Issue by hanx8** [rapid7/metasploit-framework#13428]
I would like to join a project in development, or make a new project from a Metasploit module.
They could help me, also the steps to follow, it is for a thesis work.

**Comment by FunnyWolf** [comment]
> I would like to join a project in development, or make a new project from a Metasploit module.
> They could help me, also the steps to follow, it is for a thesis work.

https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment maybe you need this

**Comment by hanx8** [comment]
Thank you, I will do the indicated.

**Comment by gwillcox-r7** [comment]
I would also recommend looking at https://github.com/rapid7/metasploit-framework/wiki/Contributing-to-Metasploit, https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md, and https://github.com/rapid7/metasploit-framework/wiki/Code-Of-Conduct. These should all be required reading before contributing. 

If you require any further assistance, please reach out on our Slack channel at http://metasploit.slack.com/ and drop a line into the #contributors channel, where there are plenty of people that will be happy to help you out :) I'm Grant Willcox on the Slack if you would like to contact me on there.

Closing this issue as I think this should be enough info to get you going and should answer the original question of where to start as a contributor. 👍
