### ISSUE TITLE
why does msfrpc service execute task with single thread

### ISSUE THREAD

**Issue by akkuman** [rapid7/metasploit-framework#13462]
When I call the rpc, I find that it's single thread. If I want to modify the default action, where should  I edit in msf source?

## Steps to reproduce

How'd you do it?

1. I sleep 20 second in function rpc_auxiliary like below

```
  # Returns a list of auxiliary module names. The 'auxiliary/' prefix will not be included.
  #
  # @return [Hash] A list of auxiliary module names. It contains the following key:
  #  * 'modules' [Array<string>] Auxiliary module names, for example: ['vsploit/pii/web_pii']
  # @example Here's how you would use this from the client:
  #  rpc.call('module.auxiliary')
  def rpc_auxiliary
    sleep(20)
    { "modules" => self.framework.auxiliary.keys }
  end
```

2. I rpc.call('module.auxiliary') and rpc.call('core.version')

## Expected behavior

rpc.call('core.version') should return response immediately

## Current behavior

rpc.call('core.version') need to wait for rpc.call('module.auxiliary') to return.

### Metasploit version

5.0.87-dev-2dc26db9e1

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (please specify ruby version)

"ruby": "2.6.6 x86_64-linux 2020-03-31",

### OS

linux with kernel 5.4.35

**Comment by adfoster-r7** [comment]
Hi there @akkuman - it would help us greatly if you provided additional steps on how to replicate/debug this issue. Thanks!

**Comment by FunnyWolf** [comment]
> When I call the rpc, I find that it's single thread. If I want to modify the default action, where should I edit in msf source?

i think it is very hard to change msfrpc to muit thread, it base on msf plugin, i recommend to use msf-json-rpc , and you can change the thin cmd in lib/msf/util/service_helper.rb(add --threaded)

**Comment by akkuman** [comment]
@FunnyWolf thanks for you reply, but from my reading of resource, the json-rpc is actually calling rpc, just a layer from msgpack to json.

And I try your solution, it have the same problem. I update the issue.

**Comment by akkuman** [comment]
@adfoster-r7 thanks, I have updated the issue

**Comment by akkuman** [comment]
> > When I call the rpc, I find that it's single thread. If I want to modify the default action, where should I edit in msf source?
> 
> i think it is very hard to change msfrpc to muit thread, it base on msf plugin, i recommend to use msf-json-rpc , and you can change the thin cmd in lib/msf/util/service_helper.rb(add --threaded)

sorry, I found it can solve my problem by --threaded. I just tested it and forgot to add it. Now it's up to my expectations. Thank you very much

**Comment by akkuman** [comment]
@FunnyWolf And I found the culprit of the problem. In https://github.com/rapid7/rex-core/blob/master/lib/rex/io/stream_server.rb#L65, if it start a service, it only have one thread to handle these request, all requests are in the queue

**Comment by FunnyWolf** [comment]
> @FunnyWolf And I found the culprit of the problem. In https://github.com/rapid7/rex-core/blob/master/lib/rex/io/stream_server.rb#L65, if it start a service, it only have one thread to handle these request, all requests are in the queue

aha~,if you change rex-core,you need to change gem lib when update msf,it is a nightmare~
