### ISSUE TITLE
Metasploit RHOST and LHOST ?

### ISSUE THREAD

**Issue by hantepe01** [rapid7/metasploit-framework#13509]
Hi folks ! I was trying to create a trojan virus for testing but I am confused. When I input my LHOST and LPORT it is okey for local machines, but what should I do for make that work at other machines ? I tried to open an 1111 port on my modem, so I created that trojan with R parameters, 1111 port and my remote ip.

In addition, when I open that trojan from my virtual machine, when I check my 1111 port on my remote ip, results showing me that it is closed, what is wrong can u tell ?

Kali Linux 2020.2

**Comment by bcoles** [comment]
https://www.youtube.com/watch?v=53zkBvL4ZB4
