### ISSUE TITLE
screenshot lib load target error?

### ISSUE THREAD

**Issue by kitty8904** [rapid7/metasploit-framework#13507]
kali linux

1. x64process memory metasploit load

2. x64process ->  screenshot.x64.dll not load

3. x64process ->  screenshot.x86.dll load

//64bit target process//
//usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.1/data
/meterpreter/

//screenshot.x64.dll -> delete

//64bit target process screenshot -> but x86.dll load //
meterpreter > screenshot
[-] Error running command screenshot: Rex::RuntimeError screenshot.x86.dll not found

Loading screenshot.x86.DLL in a 64-bit process?

**Comment by gwillcox-r7** [comment]
Hello Kitty8904, 

Can you post the output of what `locate screenshot` shows on your system? Here is what it shows for me:

```
  locate screenshot
/home/gwillcox/.rvm/gems/ruby-2.6.6/gems/metasploit-payloads-1.4.1/data/meterpreter/screenshot.x64.dll
/home/gwillcox/.rvm/gems/ruby-2.6.6/gems/metasploit-payloads-1.4.1/data/meterpreter/screenshot.x86.dll
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/metasploit-payloads-1.4.1/data/meterpreter/screenshot.x64.dll
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/metasploit-payloads-1.4.1/data/meterpreter/screenshot.x86.dll
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/metasploit-payloads-1.4.2/data/meterpreter/screenshot.x64.dll
/home/gwillcox/.rvm/gems/ruby-2.6.6@metasploit-framework/gems/metasploit-payloads-1.4.2/data/meterpreter/screenshot.x86.dll
/home/gwillcox/git/metasploit-framework/modules/auxiliary/scanner/vmware/vmware_screenshot_stealer.rb
/usr/share/bash-completion/completions/gnome-screenshot
```
I'd also recommend trying to run `bundle install` again and see if that solves anything.
