### ISSUE TITLE
Missing dependency: irb

### ISSUE THREAD

**Issue by noraj** [rapid7/metasploit-framework#13513]
## Steps to reproduce

It seems that irb dependency is missing from the gemspec.

```
$ msfconsole -q
msf5 > irb
[*] Starting IRB shell...
[*] You are in the "framework" object

[-] Error while running command irb: cannot load such file -- irb.rb
```

## Expected behavior

```$ msfconsole -q
msf5 > irb
[*] Starting IRB shell...
[*] You are in the "framework" object
>>
```

## Current behavior

In a distribution like ArchLinux, metasploit is packaged as a bundled version in opt, using only and exactly whats msf declares from the gemspec. So As irb is not declared as a runtime dependencies
it's not possible to use the irb command to load a irb shell with msf environment.

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:

ArchLinux [metasploit](https://www.archlinux.org/packages/community/x86_64/metasploit/) 5.0.88

## Related issue

[FS#66480 - [metasploit] irb.rb not found](https://bugs.archlinux.org/task/66480)

## Workaround

The workaround is to load irb from the system.

```
$ msfconsole -q
msf5 > irb -e '$LOAD_PATH << "/usr/lib/ruby/gems/2.7.0/gems/irb-1.2.1/lib/"'
msf5 > irb
[*] Starting IRB shell...
[*] You are in the "framework" object

irb: warn: can't alias jobs from irb_jobs.
>>
```

## Fix

In gemspec

```
spec.add_runtime_dependency 'irb'
```

Fix proposal #13514

**Comment by adfoster-r7** [comment]
This fix is landed now, thanks again :+1:
