### ISSUE TITLE
linux meterpreter reverse tcp payloads fails to reconnect after restarting metasploit

### ISSUE THREAD

**Issue by dellasorte** [rapid7/metasploit-framework#13527]
Payload fails to reconnect after restarting handler. 
It happening randomly I suppose... but I observing it on all these payloads 

linux/x86/meterpreter_reverse_tcp
linux/x86/meterpreter/reverse_tcp
linux/x64/meterpreter_reverse_tcp
linux/x64/meterpreter/reverse_tcp

And  my best reproducing experience is next:

1. Payload 
`msfvenom -p linux/x64/meterpreter_reverse_tcp LHOST=127.0.0.1 LPORT=4444 -f elf -o meterpreter_x64 `

2. Generated file is being launched as service :
```
[Unit]
Description=Meterpreter Reverse TCP (x64)
After=network.target
[Service]
ExecStart=/usr/local/bin/meterpreter_x64 
ExecReload=/usr/local/bin/meterpreter_x64
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always
[Install]
WantedBy=multi-user.target
Alias=meterpreter.service
```

3. Handler 
```
msfconsole
handler -p linux/x64/meterpreter_reverse_tcp -P 4444 -H 127.0.0.1
```

4.  Now when I interacting with session if something happens and my terminal session was closed unexpectedly all next attempts to reopen session will fail   

```
[*] Meterpreter session 1 opened (127.0.0.1:4444 -> 127.0.0.1:37874) at 2020-05-27 14:44:25 +0000
Active sessions
===============

  Id  Name  Type                   Information  Connection
  --  ----  ----                   -----------  ----------
  1         meterpreter x64/linux               127.0.0.1:4444 -> 127.0.0.1:37874 (127.0.0.1)
```

similar issue was described here
https://github.com/rapid7/metasploit-framework/issues/6842

I've catched some packets with wireshark trying to understand the nature of this quite annoying issue.. 

Its Still running and trying to connect ..
```
61	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	34226 → 4444 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=0 WS=128
62	127.0.0.1	127.0.0.1	127.0.0.1	TCP	54	4444 → 34226 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
65	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	34242 → 4444 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=0 WS=128
66	127.0.0.1	127.0.0.1	127.0.0.1	TCP	54	4444 → 34242 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
100	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	34252 → 4444 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=0 WS=128h
```

At this moment handler was launched and hasndshaking goes now
```
101	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	4444 → 34252 [SYN, ACK] Seq=0 Ack=1 Win=65160 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=127.0.0.1 WS=128
102	127.0.0.1	127.0.0.1	127.0.0.1	TCP	66	34252 → 4444 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=127.0.0.1 TSecr=127.0.0.1
103	127.0.0.1	127.0.0.1	127.0.0.1	TCP	637	4444 → 34252 [PSH, ACK] Seq=1 Ack=1 Win=65280 Len=571 TSval=127.0.0.1 TSecr=127.0.0.1

```
from now this 66 bytes packet is the only packet we are gettin from meterpreter
```
104	127.0.0.1	127.0.0.1	127.0.0.1	TCP	66	34252 → 4444 [ACK] Seq=1 Ack=572 Win=30464 Len=0 TSval=127.0.0.1 TSecr=127.0.0.1
206	127.0.0.1	127.0.0.1	127.0.0.1	TCP	161	4444 → 34252 [PSH, ACK] Seq=572 Ack=1 Win=65280 Len=95 TSval=127.0.0.1 TSecr=127.0.0.1
207	127.0.0.1	127.0.0.1	127.0.0.1	TCP	161	4444 → 34252 [FIN, PSH, ACK] Seq=667 Ack=1 Win=65280 Len=95 TSval=127.0.0.1 TSecr=127.0.0.1
```

```
As far as meterpreter not responding, and we want it to restart I presing Ctrl+D in handler console
208	127.0.0.1	127.0.0.1	127.0.0.1	TCP	66	34252 → 4444 [ACK] Seq=1 Ack=667 Win=30464 Len=0 TSval=127.0.0.1 TSecr=127.0.0.1
209	127.0.0.1	127.0.0.1	127.0.0.1	TCP	66	34252 → 4444 [FIN, ACK] Seq=1 Ack=763 Win=30464 Len=0 TSval=127.0.0.1 TSecr=127.0.0.1
210	127.0.0.1	127.0.0.1	127.0.0.1	TCP	66	4444 → 34252 [ACK] Seq=763 Ack=2 Win=65280 Len=0 TSval=127.0.0.1 TSecr=127.0.0.1
```

Connection closed, session finished, process supposed to be killed and then launched again (because restart=always is defined for service)
But process just continue doing retries same way as it was.

**211	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	34448 → 4444 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=0 WS=128
212	127.0.0.1	127.0.0.1	127.0.0.1	TCP	54	4444 → 34448 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
216	127.0.0.1	127.0.0.1	127.0.0.1	TCP	74	34462 → 4444 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=127.0.0.1 TSecr=0 WS=128
217	127.0.0.1	127.0.0.1	127.0.0.1	TCP	54	4444 → 34462 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0**

Any ideas? advices?  Is that a bug or I doing something wrong??
Also if you leaving session it will die soon and reconnect back again.  And after a while you can see this 
```
[*] Started reverse TCP handler on 127.0.0.1:4444
[*] Meterpreter session 2 opened (127.0.0.1:4444 -> 127.0.0.1:34512) at 2020-05-28 12:21:26 +0000
[*] 127.0.0.1 - Meterpreter session 2 closed.  Reason: Died
[*] Meterpreter session 3 opened (127.0.0.1:4444 -> 127.0.0.1:35214) at 2020-05-28 12:23:27 +0000
[*] 127.0.0.1 - Meterpreter session 3 closed.  Reason: Died
[*] Meterpreter session 4 opened (127.0.0.1:4444 -> 127.0.0.1:36030) at 2020-05-28 12:25:28 +0000
[*] 127.0.0.1 - Meterpreter session 4 closed.  Reason: Died
[*] Meterpreter session 5 opened (127.0.0.1:4444 -> 127.0.0.1:36956) at 2020-05-28 12:27:29 +0000
[*] 127.0.0.1 - Meterpreter session 5 closed.  Reason: Died
[*] Meterpreter session 6 opened (127.0.0.1:4444 -> 127.0.0.1:37780) at 2020-05-28 12:29:30 +0000
[*] 127.0.0.1 - Meterpreter session 6 closed.  Reason: Died
[*] Meterpreter session 7 opened (127.0.0.1:4444 -> 127.0.0.1:38838) at 2020-05-28 12:32:12 +0000
[*] 127.0.0.1 - Meterpreter session 7 closed.  Reason: Died
[*] Meterpreter session 8 opened (127.0.0.1:4444 -> 127.0.0.1:40022) at 2020-05-28 12:35:16 +0000

```

**Comment by dellasorte** [comment]
I have compared two SYN packets of working and dead sessions samples . The seems to be identical except one value "Window size value" . for a working session it is 64240 but for dead session its 29200. May be this could help.somehow

**Comment by timwr** [comment]
@dellasorte I think I've seen a similar issue while debugging and backgrounding/killing payloads but I'm unsure how to reproduce it.
Are you able to provide a way to reproduce this issue without running it as a service?

**Comment by dellasorte** [comment]
@timwr 
Last time I mat it - i was using termux connected with ssh to remote metasploit, handling remote reverse tcp session linux/x64, running shell or exec commands. then termux app just crashed. When i reconnected this issue appeared.

I think staging payloads have more chance to fall into that state than stageless

 Also now i know the syn packets it send when connecting are ok. But after connection established it always replies with zero length, supposedly syn-ack packet to any further communication attempts.
