### ISSUE TITLE
Meterpreter session closed and it shows the reason as died

### ISSUE THREAD

**Issue by rudraa99** [rapid7/metasploit-framework#13536]
I did everything i can, i created the payload and installedbl it in my iphone personaly bt aftr i open the payload my kali linux wont show anythn, no command line nothing please help this is frustrating
![15907401746657695996183430797905](https://user-images.githubusercontent.com/62317214/83237605-cd5e9580-a1b2-11ea-84ed-cdc1f79842f2.jpg)

**Comment by rudraa99** [comment]
> I did everything i can, i created the payload and installedbl it in my iphone personaly bt aftr i open the payload my kali linux wont show anythn, no command line nothing please help this is frustrating
> ![15907401746657695996183430797905](https://user-images.githubusercontent.com/62317214/83237605-cd5e9580-a1b2-11ea-84ed-cdc1f79842f2.jpg)

There is no meterpreter also

**Comment by OJ** [comment]
You need to give a lot more information please:
 * Victim OS/version
* Configuration for your payload
* Configuration for your listener

I don't see "sending stage.." in your listener output, which implies a stageless connection. Are you using stageless payloads?

**Comment by kondavamshiKrishna** [comment]
Sir I have also being fasing that problem , 

I send the apk to victim divice and installed it , I also seen run command apk list , but after some time it shows session died,  what to do to connect for more time?
