### ISSUE TITLE
msfconsole gets killed before starting

### ISSUE THREAD

**Issue by Th4ntis** [rapid7/metasploit-framework#13556]
Running on a fully updated Ubuntu 18.04 VPS that has nothing more than a WebServer running.

Step 1. Ran the free installer:
```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```
Step 2. Ran msfconsole:
```
:~$ msfconsole 
-----------------------------------------------------------------------------------
The pg and/or activerecord gem version has changed, meaning deprecated pg constants
may no longer be in use, so try deleting this file to see if the
'The PGconn, PGresult, and PGError constants are deprecated...' message has gone:
/opt/metasploit-framework/embedded/framework/lib/pg/deprecated_constants.rb
-----------------------------------------------------------------------------------

Killedarting thE Metasploit Framework console...\
```
Step 3. Checked the Logs:
```
:~$ cat .msf4/logs/framework.log 
[06/03/2020 21:30:07] [e(0)] core: Possible corrupt user metadata store, attempting restore
[06/03/2020 21:30:07] [d(0)] core: Created user based module store
```
Step 4. Checked for update:
```
:~$ msfupdate
Switching to root user to update the package
Adding metasploit-framework to your repository list..OK
Updating package cache..OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree       
Reading state information... Done
metasploit-framework is already the newest version (5.0.92+20200603102428~1rapid7-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by gwillcox-r7** [comment]
Hello @Th4ntis was there anything else in the logs? Based on that it seems that there was a corrupt file and then it was replaced with a new fresh file, so its possible you may just need to try loading `msfconsole` again?

If this is not the case then is there anyway you can provide more info on your environment etc? A quick look at previous instances of similar crashes suggests running `dmesg | grep "Out of memory"` might help eliminate the case where `msfconsole` is crashing cause it is out of memory.

**Comment by Th4ntis** [comment]
> Hello @Th4ntis was there anything else in the logs? Based on that it seems that there was a corrupt file and then it was replaced with a new fresh file, so its possible you may just need to try loading `msfconsole` again?
> 
> If this is not the case then is there anyway you can provide more info on your environment etc? A quick look at previous instances of similar crashes suggests running `dmesg | grep "Out of memory"` might help eliminate the case where `msfconsole` is crashing cause it is out of memory.

I have attempted running msfconsole again and still dies. I think you are right, it is a memory issue
```
:~$ dmesg | grep "Out of memory"
[ 2337.091458] Out of memory: Killed process 2023 (ruby) total-vm:440652kB, anon-rss:152824kB, file-rss:0kB, shmem-rss:0kB
[ 2456.275401] Out of memory: Killed process 2087 (ruby) total-vm:440684kB, anon-rss:152468kB, file-rss:688kB, shmem-rss:0kB
[ 2631.817385] Out of memory: Killed process 7941 (ruby) total-vm:440956kB, anon-rss:152716kB, file-rss:0kB, shmem-rss:0kB
[ 2689.851529] Out of memory: Killed process 7966 (ruby) total-vm:440640kB, anon-rss:154608kB, file-rss:0kB, shmem-rss:0kB
[ 3219.647693] Out of memory: Killed process 8538 (ruby) total-vm:440568kB, anon-rss:154424kB, file-rss:0kB, shmem-rss:0kB
[ 3373.399005] Out of memory: Killed process 8912 (ruby) total-vm:440964kB, anon-rss:150776kB, file-rss:0kB, shmem-rss:0kB
[ 3564.484541] Out of memory: Killed process 9002 (ruby) total-vm:440956kB, anon-rss:153704kB, file-rss:0kB, shmem-rss:0kB
[ 5691.379812] Out of memory: Killed process 9579 (ruby) total-vm:444908kB, anon-rss:158560kB, file-rss:0kB, shmem-rss:0kB
[ 5776.304335] Out of memory: Killed process 9615 (ruby) total-vm:444684kB, anon-rss:158428kB, file-rss:0kB, shmem-rss:0kB
[13129.705116] Out of memory: Killed process 10121 (ruby) total-vm:444756kB, anon-rss:159948kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by gwillcox-r7** [comment]
No problem, let me know if you are still not able to fix this after updating the amount of memory on the host system.

**Comment by Th4ntis** [comment]
> No problem, let me know if you are still not able to fix this after updating the amount of memory on the host system.

That was the issue. Added more memory and it's all fixed. Something so minor I didn't think to look at. Thank you.

**Comment by gwillcox-r7** [comment]
No problem @Th4nat0s, glad you managed to get it working! 🥳
