### ISSUE TITLE
Screenshare session not working on android meterpreter reverse_tcp

### ISSUE THREAD

**Issue by Fabio-Git-dev** [rapid7/metasploit-framework#13560]
## Steps to reproduce

Created the backdoor, opened it, tried the screenshare command, and the page shows continiously:
waiting... playing... waiting... playing... 

## Expected behavior
Should reproduce a real-time screen opf the victim
What should happen?
mentioned above
## Current behavior
![image](https://user-images.githubusercontent.com/30447649/83907939-89e1c980-a766-11ea-95e0-32960d64219f.png)

What happens instead?
The state changes constantly 

### Metasploit version
5.0.91 dev

### I installed Metasploit with:
Already included in the distro, updated with apt full-upgrade 

### OS
Kali linux 2020.x

**Comment by timwr** [comment]
The Android screenshot command only works when the application is injected into another application, and when that application is in the foreground. This is presumably why the screenshare command is behaving like this.

**Comment by Defaltx** [comment]
So you're telling me that it won't work with a basic msfvenom backdoor?

**Comment by Chotu75** [comment]
> So you're telling me that it won't work with a basic msfvenom backdoor?

no you have to embed payload apk to original apk

**Comment by Tulasinathreddy** [comment]
same issue for me also in my android termux meterpreter it saying waiting....... playing...... waiting....... playing.......

i am able to see this in my chrome..
![Screenshot_20201020-092357_Chrome](https://user-images.githubusercontent.com/34623886/96538478-3e176300-12b6-11eb-839c-13bc7408ec0e.png)

**Comment by PraveenGadag** [comment]
I am also getting same problem

**Comment by aarya1417** [comment]
so how do we embed the payload to original apk

**Comment by conceptuando** [comment]
I have the same problem. How is the APK embedded? Thanks.

**Comment by krisdowis** [comment]
What's your problem

**Comment by WeAreAnonymous47** [comment]
it will only work when the user id using that app. will not work in android background

**Comment by Elevete12** [comment]
> ## Steps to reproduce
> Created the backdoor, opened it, tried the screenshare command, and the page shows continiously: waiting... playing... waiting... playing...
> 
> ## Expected behavior
> Should reproduce a real-time screen opf the victim What should happen? mentioned above
> 
> ## Current behavior
> ![image](https://user-images.githubusercontent.com/30447649/83907939-89e1c980-a766-11ea-95e0-32960d64219f.png)
> 
> What happens instead? The state changes constantly
> 
> ## System stuff
> ### Metasploit version
> 5.0.91 dev
> 
> ### I installed Metasploit with:
> Already included in the distro, updated with apt full-upgrade
> 
> ### OS
> Kali linux 2020.x

i also have the same problem can you help me how to fix it?

**Comment by salka9** [comment]
did anyone fix the  problem?

**Comment by h00die** [comment]
likely a permissions problem, I've added this to #19154 to keep track.

This is also a closed ticket, which means it has already been fixed. If you have a new problem, open a new ticket.
