### ISSUE TITLE
Evil-droid binded App Permission issue

### ISSUE THREAD

**Issue by mobile3310** [rapid7/metasploit-framework#13564]
## Steps to reproduce

How'd you do it?

1. ...I bind an App with a payload. Done successfully but when i installed it in the phone it takes no permission. it provide then only a meterpreter session but perform nothing. when I execute shell command, it executed but while giving other commands like CD / cd sdcard and then ls it simply says "permission denied"   
2. ...Pls let me know what is missing at auto binding by Evil-droid? why it doesnt ask for permissions?

 AN UPDATE TO THE PROBLEM

I installed the the App where I had injected payload through Evil-Droid. At "Install" it says no permission required to install this app. But as I got further and then opened the App to get further. The app then asked me for location and storage permission. I permitted both location and storage. After this I was only able to:

  a.  shell, cd /, cd  sdcard and ls.
  b.  I was able to download files from sdcard

BUT

  c.  No success to "dump_calllog" dump bla bla bla
  d.  Non of the command working from "meterpretter" prompt other than shell
  e.  After few minutes sessions become dead
  f.   After clicking on the app's icon in the phone it should connect again but no return
        (It may be noted that if someone makes a payload app without binding in Evil-Droid 
        and doesn't hide it after installation in the phone, clicking on it's icon enables you to 
        connect time and again if meterpreter session dies)

**Comment by march0s1as** [comment]
same problem here

**Comment by gwillcox-r7** [comment]
This sounds like it may be an issue more specific to Evil-Droid. Have you tried raising an issue on their issue tracker at https://github.com/M4sc3r4n0/Evil-Droid?

**Comment by mobile3310** [comment]
> This sounds like it may be an issue more specific to Evil-Droid. Have you tried raising an issue on their issue tracker at https://github.com/M4sc3r4n0/Evil-Droid?

No friend I am not aware of how to put it with them. Your  link providing me guidance and I am going to put it there as well. It may be or may not be specific issue of Evil-Droid because issue is coming after embedding the payload which may be a standard process as I think but not strict to it and agreed with you. Thank you for respond and help.

**Comment by march0s1as** [comment]
Hi. My problem was solved.

I downloaded another APK and got access to the permissions (camera, sdcard, etc ...)

**Comment by gwillcox-r7** [comment]
Closing this issue as there appears to be a known workaround and I've not seen any updates to this issue in several months.
