### ISSUE TITLE
Msfconsole stuck in sending stage

### ISSUE THREAD

**Issue by gurucharan127** [rapid7/metasploit-framework#13574]
## Steps to reproduce

How'd you do it?

1. created a payload on msfvenom and opened the payload it in windows
2. while listening in msfconsole it gets stuck in sending stage and keeps printing sending stage until stopped msfconsole or payload from task manager

## Expected behavior

After sending stage a session should open
## Current behavior

keeps printing- sending stage

### Metasploit version
5.0.19

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:

- [ ] Source install (ruby version - 2.7.0
<img width="960" alt="VirtualBox_klinux_08_06_2020_21_26_25" src="https://user-images.githubusercontent.com/56298314/84054870-a170ba80-a9d1-11ea-903c-69906cc3ba33.png">
<img width="960" alt="VirtualBox_klinux_08_06_2020_21_26_50" src="https://user-images.githubusercontent.com/56298314/84054952-c6fdc400-a9d1-11ea-8c42-5cfa8af56828.png">

)

### OS

What OS are you running Metasploit on?
KaliLinux

**Comment by h00die** [comment]
Metasploit 4.0.5 is ancient.  Maybe older than ancient circa [2011](https://blog.rapid7.com/2011/08/01/metasploit-40-released/).  I'm going to recommend installing a newer branch created within the last 5yrs, even better maybe this year.
