### ISSUE TITLE
metasploit-payloads bundle not installing on Termux

### ISSUE THREAD

**Issue by Josecer10** [rapid7/metasploit-framework#13586]
==================
=       ATNTSJOSE      =
==================

EL PROBLEMA O ERROR ES ---> BUNDLER <---
Al ejecutar msfconsole, en termux para terminar de instalar Metasploit dice un error. Creo que está mal el código del documento o el documento no existe.

Expliquenme que debo hacer para terminar de instalar Metasploit bien y completo, me falta esto se llama (Bundler). 

De antemano gracias muchas gracias.

Este mensaje aparece en rojo:

`Bundler::GemspecError: Could not read gem at    /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/cache/metasploit-payloads-1.3.86.gem.
It may be corrupted.                            An error occurred while installing              metasploit-payloads (1.3.86), and Bundler cannot
continue.                                       Make sure that `gem install metasploit-payloads
-v '1.3.86' --source 'https://rubygems.org/'`   succeeds before bundling.

     Esto aparece en blanco:   
 In Gemfile:                                     metasploit-framework was resolved to 5.0.83,
which depends on                                    metasploit-payload`

Imagen:
![Screenshot_20200610-022649](https://user-images.githubusercontent.com/53112769/84243067-47eab780-aac7-11ea-9ce8-d233f0a4a1fc.png)

**Comment by Josecer10** [comment]
Muchas gracias le agradezco voy a intentar a hacerlo.

El español está bien.

**Comment by gwillcox-r7** [comment]
Estoy cerrando este problema ya que no ha habido ninguna actualización en dos semanas.

**Comment by TKMX-NC-TKMX** [comment]
Al crear el payload para Android meterpreter y establecer la comunicación tcp asignar los puertos y el host y establecer la ruta designada ...sale que acceda a la configuración de ssl 
(OPENSSL_CONF ) y asigne los permisos adecuados al metasploit .
