### ISSUE TITLE
Error while installing io-console (0.5.6)

### ISSUE THREAD

**Issue by Kapil231** [rapid7/metasploit-framework#13595]
I just updated the metasploit and it shows me error while running msfconsole.

![Screenshot from 2020-06-11 05-18-14](https://user-images.githubusercontent.com/66197179/84369312-4a96fb00-abf4-11ea-96cc-1ddb45788fed.png)

![Screenshot from 2020-06-11 05-19-07](https://user-images.githubusercontent.com/66197179/84369306-47037400-abf4-11ea-9db1-fe16097065e1.png)

**Comment by gwillcox-r7** [comment]
Have you tried running `gem install io-console -v '0.5.6' --source 'https://rubygems.org'` as per the output of that error message?

Also reordering your images since they are out of order.

**Comment by Kapil231** [comment]
I installed a separate package for ruby development and the problem resolved.

**Comment by BenKettlewell** [comment]
For fellow travelers who find themselves here with no answer....

`cd /usr/share/metasploit-framework; apt-get install libruby2.7 ruby2.7-dev; bundle install`

If you hit permission problems just add sudo

**Comment by AntonMingov** [comment]
On macOS, you can install Xcode, it worked in my case.
`xcode-select --install`

**Comment by crisperpo** [comment]
> On macOS, you can install Xcode, it worked in my case.
> 
> `xcode-select --install`

This helped me too
