### ISSUE TITLE
ruby 2.7.1p83--warning: deprecated Object#=~ is called on Integer; it always returns nil  

### ISSUE THREAD

**Issue by DDnie19** [rapid7/metasploit-framework#13591]
## Steps to reproduce
Versions:
![Screenshot 2020-06-10 21:18:02](https://user-images.githubusercontent.com/54387749/84272457-00fcd080-ab60-11ea-9e5b-08aae0dba8a8.png)

When I first run msfdb init
reline 0.1.3 is the default, but does not support dependencies
I deleted reline 0.1.3 and downloaded reline 0.1.4
Sorry, there was no screenshot at the time, I found google search history at that time
Probably like this
"You have already activated reline 0.1.3, but your Gemfile requires reline 0.1.4. Since reline is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports reline as a default gem . (Gem::LoadError)"

Later, proceed to msfdb init
The following error occurred:

![Screenshot 2020-06-10 21:02:56](https://user-images.githubusercontent.com/54387749/84271040-28529e00-ab5e-11ea-9734-9956bc444443.png)

**Comment by veganjay** [comment]
Same thing here.  I installed Kali 2020.2 from ISO on June 12, 2020.

To fix the "reline 0.1.3" issue:

> "You have already activated reline 0.1.3, but your Gemfile requires reline 0.1.4. Since reline is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports reline as a default gem . (Gem::LoadError)"

I ran:

```
cd /usr/lib/ruby/gems/2.7.0/specifications/default
rm reline-0.1.3.gemspec
gem install -v0.1.4 reline
```

When I ran *msfdb init*, I got the deprecation warning:
```
# msfdb init
[+] Starting database
[+] Creating database user 'msf'
[+] Creating databases 'msf'
[+] Creating databases 'msf_test'
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection
_adapters/abstract_adapter.rb:84: warning: deprecated Object#=~ is called on Integer; it always returns nil
```

And when I run *msf console*, I got another deprecation warning:

```
# msfconsole
-----------------------------------------------------------------------------------
The pg and/or activerecord gem version has changed, meaning deprecated pg constants
may no longer be in use, so try deleting this file to see if the
'The PGconn, PGresult, and PGError constants are deprecated...' message has gone:
/usr/share/metasploit-framework/lib/pg/deprecated_constants.rb
-----------------------------------------------------------------------------------
```

**Comment by hffaust** [comment]
I am having the same issue with the default installed metasploit on a fresh Kali 2020.2 install. I proceeded to ignore the warning, so far no issues. I took a screenshot of the message that was displayed. I believe it is the same message @DDnie19 is referring to that he didn't take at the time. 
<img width="1011" alt="Screenshot 2020-06-24 17 20 51" src="https://user-images.githubusercontent.com/15644021/85629108-3d8bfa00-b63f-11ea-9100-d6c60911d284.png">

**Comment by DDnie19** [comment]
> I am having the same issue with the default installed metasploit on a fresh Kali 2020.2 install. I proceeded to ignore the warning, so far no issues. I took a screenshot of the message that was displayed. I believe it is the same message @DDnie19 is referring to that he didn't take at the time.
> <img alt="Screenshot 2020-06-24 17 20 51" width="1011" src="https://user-images.githubusercontent.com/15644021/85629108-3d8bfa00-b63f-11ea-9100-d6c60911d284.png">

Yeah,same message.After deleting the old version (reline 0.1.3), install (reline 0.1.4), 
 that it will not affect (msf) normal use.

**Comment by shllshckd** [comment]
Same issue here, thanks @veganjay!

**Comment by gwillcox-r7** [comment]
Closing this issue as their appears to be a known workaround which has been confirmed to work and work is currently underway to support Ruby 2.7 throughout Metasploit Framework.
