### ISSUE TITLE
Git clone Ubuntu

### ISSUE THREAD

**Issue by eFrostByte** [rapid7/metasploit-framework#13609]
I'm trying to run metasploit in Ubuntu 18.04. I have cloned the repo but the commands don't seem to work. I should have done something else before it?

**Comment by bcoles** [comment]
That depends what "doesn't work" means. But yeah, you'll probably need to install some OS packages and run `bundle install`. Check this out:

* https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

You don't need to worry about this git stuff. Something like this will likely be sufficient.

```
sudo apt update && sudo apt install -y git autoconf build-essential libpcap-dev libpq-dev zlib1g-dev libsqlite3-dev

cd /path/to/metasploit-framwork/
bundle install
```

**Comment by h0die** [comment]
Ubuntu is bullshit!

**Comment by harmjay** [comment]
Ubunty is unsupported.
