### ISSUE TITLE
Metasploit Payload is not installed

### ISSUE THREAD

**Issue by ASMFahim71** [rapid7/metasploit-framework#13614]
I have injected the android/meterpreter/reverse_tcp Payload apk in some random apk like FacebookLite,UberLite etc!

My apk files are perfectly created
But when I try to install them in an Android device it says, "App is not installed "
I tried several times,but got nothing!

Is there any why to install them in any  Android device and how to bypass the google play security? 

I'm using Metasploit in Kali Linux 2020 which in an updated version of msf!

Victim Android Version 6.0.1

**Comment by bc0les** [comment]
> Is there any why to install them in any Android device and how to bypass the google play security?
You can disable it, if you have access to smartphone. I don't see other ways

> I have injected the android/meterpreter/reverse_tcp Payload apk in some random apk like FacebookLite,UberLite etc!
Try another apk.

**Comment by th3mistokles** [comment]
same error

**Comment by harmjay** [comment]
Android 6 isn't supported, sorry.

**Comment by th3mistokles** [comment]
> Android 6 isn't supported, sorry.

6-7-8-9 isn't supported ? what are the supported versions?

**Comment by ASMFahim71** [comment]
still no solution :'(

**Comment by th3mistokles** [comment]
I request it to be solved urgently.

**Comment by adfoster-r7** [comment]
@th3mistokles If you provide replication steps, or a link to the guide you're following, we can run through the scenario and try to replicate the error you're facing

**Comment by th3mistokles** [comment]
> @th3mistokles If you provide replication steps, or a link to the guide you're following, we can run through the scenario and try to replicate the error you're facing

I did not understand exactly what you mean.

**Comment by adfoster-r7** [comment]
To help unblock this issue, please:

- Comment with links to documentation on how to set up an environment, and provide exact software version numbers to use
- Or comment guided steps on how to set up our environment for testing this issue

**Comment by th3mistokles** [comment]
> To help unblock this issue, please:
> 
> * Comment with links to documentation on how to set up an environment, and provide exact software version numbers to use
> * Or comment guided steps on how to set up our environment for testing this issue

Hello again,
I recorded a video showing this problem. Please check

https://gofile.io/d/ZbsTXL
