### ISSUE TITLE
This module isn't work, is it? https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/manage/sdel.rb

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-framework#13622]

**Comment by h00die** [comment]
I don't know, maybe you tried it and have some input on if it does or not?

**Comment by Narutto2011** [comment]
No, i try, but nothing happen.

**Comment by h00die** [comment]
If you spoke to report an issue, ease use the issue template to provide us enough information to properly replicate the issue

**Comment by bcoles** [comment]
Please provide console output showing what options you used and what output the module produced.
