### ISSUE TITLE
You have bug in enable_rdp.

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-framework#13621]
In string 155. (HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList) we set path, and use  registry_setvaldata(hide_user_key, username, 0, "REG_DWORD"), for create. 
But if computer isn't have key UserList, or SpecialAccounts, we can't create key.

We must use create_key(hide_user_key), before setvaldata.
Please, fix it.

**Comment by bcoles** [comment]
Dupe of #11221
