### ISSUE TITLE
Architectural issues on scripts.

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-framework#13624]
For example, get this script: https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/checkvm.rb

Why we  use session.sys.process.get_processes four times?
Why we can't wrote it in variable and use once?
It is very heavily loads the network.

**Comment by bcoles** [comment]
You're right, it's not very efficient and could be improved.

**Comment by h0die** [comment]
This is bullshit!

**Comment by h0die** [comment]
p.s it doesn't work, you made a mistake in string 43.

**Comment by bc0les** [comment]
You have mistake in 131 string.
