### ISSUE TITLE
How i can hack facebook or instagram profile?

### ISSUE THREAD

**Issue by pifeg86924** [rapid7/metasploit-framework#13679]

**Comment by bcoles** [comment]
Do your parents know what you're up to?

**Comment by pifeg86924** [comment]
It is forbidden?

**Comment by bcoles** [comment]
> 
> 
> It is forbidden?

Hacking your own Facebook and Instagram is acceptable. The easiest way to hack your own Facebook or Instagram account is to login with your username and password.

If you find a way to hack someone else's Facebook or Instagram account, you can report the issue to Facebook who may pay you for your efforts as part of their bug bounty program.

You can learn more about Facebook's bug bounty program here:

* https://www.facebook.com/whitehat
* https://hackerone.com/facebook

**Comment by pifeg86924** [comment]
And my girlfriend?

**Comment by bcoles** [comment]
> 
> 
> And my girlfriend?

Yes, you're allowed to hack your socks.

**Comment by pifeg86924** [comment]
What?
