### ISSUE TITLE
How i can hack windows xp?

### ISSUE THREAD

**Issue by pifeg86924** [rapid7/metasploit-framework#13682]

**Comment by DPRK-KimJongUn** [comment]
Time travel to 2008

**Comment by pifeg86924** [comment]
In 2020?

**Comment by bcoles** [comment]
The easiest way to hack Windows XP is to login with a valid username and password.

The Metasploit issue tracker is for tracking issues with Metasploit.

In future, perhaps someone on IRC or Slack can help you out with your question:

* https://www.metasploit.com/help
