### ISSUE TITLE
How to find guy through ip?

### ISSUE THREAD

**Issue by sesic36** [rapid7/metasploit-framework#13684]

**Comment by DPRK-KimJongUn** [comment]
Ask guy where he lives.

**Comment by sesic36** [comment]
Through metasploit.

**Comment by sesic36** [comment]
Are you from dprk?

**Comment by DPRK-KimJongUn** [comment]
If you tell me your address I tell you mine.

**Comment by sesic36** [comment]
i'm from switzerland

**Comment by bcoles** [comment]
There are plenty of guys on the internet. You'll probably have more luck with a dating website.

**Comment by sesic36** [comment]
No, I need an asshole and a warface.

**Comment by bcoles** [comment]
> No, I need an asshole and a warface.

Try [Full Metal Jacket (1987)](https://www.imdb.com/title/tt0093058/).
