### ISSUE TITLE
How i can get access to my smartphone?

### ISSUE THREAD

**Issue by pifeg86924** [rapid7/metasploit-framework#13680]

**Comment by DPRK-KimJongUn** [comment]
Stop wasting these awesome people's time with either 1) your stupid trolling or 2) your idiocracy. If your parents do indeed know what you're doing, as you allude, then they're terrible parents. Go read a book.

**Comment by bcoles** [comment]
Smart phones usually use a PIN code or biometrics (such as fingerprint or facial structure) for authentication. Refer to the manual provided by the manufacturer.

The Metasploit issue tracker is for tracking issues with Metasploit.

In future, perhaps someone on IRC or Slack can help you out with your question:

* https://www.metasploit.com/help
