### ISSUE TITLE
OJ, you already close SMBleed topic. Now close SMBLost. This is a bullshit.

### ISSUE THREAD

**Issue by h0die** [rapid7/metasploit-framework#13711]

**Comment by ccondon-r7** [comment]
Please stop. We're reporting you to GitHub.

**Comment by h0die** [comment]
@ccondon-r7, i'm sorry, but how is see, oj close many topics:
https://github.com/rapid7/metasploit-framework/issues/13625
https://github.com/rapid7/metasploit-framework/issues/13615

This is bad, isn't it?
