### ISSUE TITLE
When I am running msfconsole it is showing "Could not find io-console-0.5.6 in any of the sources"

### ISSUE THREAD

**Issue by FaizanNehal** [rapid7/metasploit-framework#13744]
I was using a vnc auxiliary module when my metasploit suddenly stopped and it exited. Now when I am running msfconsole it is howing the following error message
`
Could not find io-console-0.5.6 in any of the sources
Run bundle install to install missing gems.
`
When I am trying to run 'bundle install' it is showing the following error meassage
`Could not locate Gemfile`

I have googled alot then found out that I have to open metasploit-framework directory to run this command. so I went into the directory and then executed this command, but it is showing the following error message.

`
faizan@10:/usr/share/metasploit-framework$ bundle install
There was an error while trying to write to /usr/share/metasploit-framework/.bundle/config. It is likely that you need to grant write permissions for that path.
`

I am stretching my head for hours now, what could have gone wrong. Please help me

**Comment by FaizanNehal** [comment]
![Capture](https://user-images.githubusercontent.com/45764507/85212687-b0128680-b36e-11ea-85f4-a850fa4cca0c.PNG)

**Comment by FaizanNehal** [comment]
chmod on the config file is also not working and showing an error message.

**Comment by bcoles** [comment]
`bundle install` needs to be executed from within the `metasploit-framwork` directory. It also requires elevated privileges.

```
sudo bundle install
```

**Comment by bcoles** [comment]
Also, it looks like you're using the Metasploit package on Kali, in which case there is possibly an issue with the package as distributed by Kali.

You can also try:

```
sudo gem install io-console
```

**Comment by FaizanNehal** [comment]
> `bundle install` needs to be executed from within the `metasploit-framwork` directory. It also requires elevated privileges.
> 
> ```
> sudo bundle install
> ```

Yes I was also trying it but it was saying that this would break the application for non-root users. Should I execute it? it is safe

**Comment by FaizanNehal** [comment]
> Also, it looks like you're using the Metasploit package on Kali, in which case there is possibly an issue with the package as distributed by Kali.
> 
> You can also try:
> 
> ```
> sudo gem install io-console
> ```

Thank you Thank you Thank you!
You are an amazing legend, Thanks for the quick reply and help.
My problem is solved.
Thanks

**Comment by cyrusnderitu** [comment]
I had the same issue but it worked out for me by downloading the rubylib in the metasploit-framework dir

 apt-get install libruby2.7

**Comment by thecipher17** [comment]
> > `bundle install` needs to be executed from within the `metasploit-framwork` directory. It also requires elevated privileges.
> > ```
> > sudo bundle install
> > ```
> 
> Yes I was also trying it but it was saying that this would break the application for non-root users. Should I execute it? it is safe

yes u can....its just warn u bcoz u r using sudo command.

**Comment by thecipher17** [comment]
> I had the same issue but it worked out for me by downloading the rubylib in the metasploit-framework dir
> 
> apt-get install libruby2.7

yeehhh...It worked for me too..Thanks dude

**Comment by Zinkuth** [comment]
> I had the same issue but it worked out for me by downloading the rubylib in the metasploit-framework dir
> 
> apt-get install libruby2.7

It worked, thanks!

**Comment by BenKettlewell** [comment]
Didn't work for me until I added:
`apt-get install ruby2.7-dev`

**Comment by kpua** [comment]
> Didn't work for me until I added:
> 
> ```
> apt-get install ruby2.7-dev
> ```

Спасибо друг, именно ты меня и спас :)

**Comment by cyrusnderitu** [comment]
No problem ,.. Happy to help
