### ISSUE TITLE
I get this error when I try to run metasploit on windows

### ISSUE THREAD

**Issue by Quessts** [rapid7/metasploit-framework#13760]
I get this error when I open metasploit for the first time.
C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
-----------------------------------------------------------------------------------
The pg and/or activerecord gem version has changed, meaning deprecated pg constants
may no longer be in use, so try deleting this file to see if the
'The PGconn, PGresult, and PGError constants are deprecated...' message has gone:
C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.92/lib/pg/deprecated_constants.rb
-----------------------------------------------------------------------------------

**Comment by adfoster-r7** [comment]
Hi, both warnings warning can be safely ignored

Updating to the latest latest version of Metasploit will fix the second warning you are receiving
