### ISSUE TITLE
VHOST Not Supported within multi/ftp/pureftp_bash_env_exec

### ISSUE THREAD

**Issue by hothefa1998** [rapid7/metasploit-framework#13771]
Hey guys, 
I was using the module ulti/ftp/pureftpd_bash_env_exec to test ftp of a website. Everything is going smoothly except for one thing. I need to set the vhost (website.com) because once I set the rhost, the metasploit resolves it to the ip which is not vulberable. The problem is there is no vhost option in this module.

ulti/ftp/pureftpd_bash_env_exec

**Comment by gwillcox-r7** [comment]
Hmm well FTP is always a direct connection to an IP, so @wvu-r7 pointed out in a discussion we had about this, there isn't really much point to adding a VHOST, that is more for HTTP modules. Ideally what you should be doing is resolving the IP address of the target yourself, which should be the same as `Hosts` header in HTTP.

Ideally we should make it more clear which modules support which options. I've added this to our list of things to improve the documentation of, so thanks for pointing this out :)

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/blob/0308d3822cb08f0c84ce2f147a553d1d8ccd7096/lib/rex/proto/http/client_request.rb#L420-L438
