### ISSUE TITLE
vmware_http_login does not seem to work properly

### ISSUE THREAD

**Issue by Litter117** [rapid7/metasploit-framework#13777]
Local System:
    Linux mint 19.03 64bit

Target System:
   ESXI 6.5 

Metasploit Version:
   Framework: 5.0.95-dev-
   Console  : 5.0.95-dev-

note :  Account number, password, ip are correct

Module Error:
msf5 > use auxiliary/scanner/vmware/vmware_http_login
msf5 auxiliary(scanner/vmware/vmware_http_login) > set rhosts 192.168.159.150
msf5 auxiliary(scanner/vmware/vmware_http_login) > set username root
msf5 auxiliary(scanner/vmware/vmware_http_login) > set password admin!@#45
msf5 auxiliary(scanner/vmware/vmware_http_login) > set bruteforce_speed 3
msf5 auxiliary(scanner/vmware/vmware_http_login) > set blank_passwords true
msf5 auxiliary(scanner/vmware/vmware_http_login) > run

[+] 192.168.159.150:443 - Identified VMware ESXi 6.5.0 build-8294253
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

**Comment by gwillcox-r7** [comment]
Hello @kilonsec, please follow the module template in future. Specifically the part about including the logs. Its going to be very hard to tell what actually went wrong here based purely off of your output here. Also this removes a lot of back and forth between the two of us to get the information needed for us to debug the issue. That being said, for starters, please try dumping the last 1000 lines of the output of `cat ~/.msf4/logs/framework.log`.

Also, looking at the output my initial impression would be to do the following:

1. Browse to `modules/auxiliary/scanner/vmware/vmware_http_login.rb`.
2. Find the function titled `run_host`
3. Change it to this:

```
  def run_host(ip)
    return unless is_vmware?
    each_user_pass { |user, pass|
      print_status("Logging in with #{user}:#{pass}")
      result = vim_do_login(user, pass)
      print_status(result.to_s)
      case result
      when :success
        print_good "#{rhost}:#{rport} - Successful Login! (#{user}:#{pass})"
        report_cred(ip: rhost, port: rport, user: user, password: pass, proof: result)
        return if datastore['STOP_ON_SUCCESS']
      when :fail
        print_error "#{rhost}:#{rport} - Login Failure (#{user}:#{pass})"
      end
    }
  end
```

**Comment by chick0n** [comment]
Works with ESXi 5.5.0
Doesnt work with ESXi 6.5.0 or higher.

**Comment by gwillcox-r7** [comment]
> Works with ESXi 5.5.0
> Doesnt work with ESXi 6.5.0 or higher.

Do you happen to have any output that could be used to debug this further? Ideally the output should show what version of Metasploit you are running as well as the version of Ruby you are running. By happenstance do you also know if ESXi 6.0 is affected as well (right now given the previous poster's information we know it doesn't work on ESXi 6.5.0, and from your information it sounds like it may have been some API change if its affecting versions later than ESXi 6.5.0 as well, but it would be good to determine when the issue first occured).
