### ISSUE TITLE
Where is the ctlscript.sh?

### ISSUE THREAD

**Issue by mark0100** [rapid7/metasploit-framework#13791]
I used the nightly installer from https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers to install the metasploi-framework on Ubuntu 20.04.

All seems well except that i can't find the ctlscript.sh file after installation. It seems to be missing.
It looks like it's also missing in the code section here on github.

Where can i find this ctlscript.sh file?

**Comment by jmartin-r7** [comment]
Metasploit framework does not contain a `ctlscript.sh`.  Once the packages is installed call `msfconsole` now available on your path.

**Comment by mark0100** [comment]
Ok that explains the missing file 😁, but how do i manage the still running services (i.e. postgres, web) after exiting the msfconsole?
All the documentation says you do that with ctlscript.sh

**Comment by jmartin-r7** [comment]
It is possible you are reading documentation for [Metasploit Pro](https://www.rapid7.com/products/metasploit/download/pro/).

Metasploit Framework does not provide a web ui.  RESTful api services can be enabled per details [here](https://github.com/rapid7/metasploit-framework/wiki/Metasploit-Web-Service) and RPC services and be started with the sections related to Framework [here](https://metasploit.help.rapid7.com/docs/rpc-api)

**Comment by mark0100** [comment]
Yes you are right, I was reading the Pro documentation. Thank you for pointing that out to me.

I made a simple shell script for stopping the postgres and thin server after exiting msfconsole. This will do.

**Comment by mark0100** [comment]
closed.
