### ISSUE TITLE
Metasploit installer 5.0.96 "project.cab" corrupt ?

### ISSUE THREAD

**Issue by adearya69** [rapid7/metasploit-framework#13794]
Hello guys...
I have problem installation metasploit on windows 10 education. How to fix it?
![IMG_20200702_010921](https://user-images.githubusercontent.com/53147593/86277346-bcb19d00-bc00-11ea-8446-5033c4e471ba.jpg)

**Comment by gwillcox-r7** [comment]
@adearya69 Did you disable AV or instruct the AV to ignore the installation directory? It looks like it may have caught the file and removed it during installation?
