### ISSUE TITLE
not able to create payload  android/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by tarunpasrija19** [rapid7/metasploit-framework#13809]
![meter1](https://user-images.githubusercontent.com/65336849/86603531-bbe28780-bfc1-11ea-8084-b7699651c30a.PNG)

**Comment by tarunpasrija19** [comment]
what does it means ? invaild cyber

**Comment by tarunpasrija19** [comment]
why invaild template ?

**Comment by busterb** [comment]
You've got a space in your filename for the template, msfvenom reads what you typed for the template as '-x Cyber', which doesn't exist. Either rename the file without a space, or put quotes around the filename.
