### ISSUE TITLE
Unable to install on Windows 10 Enterprise.

### ISSUE THREAD

**Issue by blakeboy01** [rapid7/metasploit-framework#13803]
## Steps to reproduce

By installing using the Nightly Installer.

## Expected behavior

Installs without erroring and stopping prematurely.

## Current behavior

Errors, stops prematurely, error: 1603 or 2203

MSI (c) (64:4C) [09:21:14:257]: Note: 1: 1708 
MSI (c) (64:4C) [09:21:14:257]: Note: 1: 2205 2:  3: Error 
MSI (c) (64:4C) [09:21:14:257]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1708 
MSI (c) (64:4C) [09:21:14:257]: Note: 1: 2205 2:  3: Error 
MSI (c) (64:4C) [09:21:14:257]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (64:4C) [09:21:14:257]: Product: Metasploit-framework v5.0.97 -- Installation failed.

MSI (c) (64:4C) [09:21:14:258]: Windows Installer installed the product. Product Name: Metasploit-framework v5.0.97. Product Version: 5.0.97.1. Product Language: 1033. Manufacturer: Rapid7 Release Engineering <r7_re@rapid7.com>. Installation success or error status: 1603.

### Metasploit version

Latest

### I installed Metasploit with:
- [ ] Kali package via apt
- [✓ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Windows 10 Enterprise.

**Comment by yukar1z0e** [comment]
Windows 10 Professional also met the same issue
