### ISSUE TITLE
invalid payload: android/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by tarunpasrija19** [rapid7/metasploit-framework#13808]
![meter](https://user-images.githubusercontent.com/65336849/86602017-b421e380-bfbf-11ea-9ea5-74b6c12c99fa.PNG)

**Comment by tarunpasrija19** [comment]
HELP ME !!!!!!!!!!!!!!

**Comment by dwelch-r7** [comment]
you need to set the payload to `android/meterpreter/reverse_tcp` notice the underscore not the `-` that you have

**Comment by tarunpasrija19** [comment]
showing error invalid cyber
![meter1](https://user-images.githubusercontent.com/65336849/86603257-67d7a300-bfc1-11ea-832b-81209f8c288c.PNG)

**Comment by tarunpasrija19** [comment]
what does it means ?

**Comment by bcoles** [comment]
> 
> 
> what does it means ?

It means you need to quote your arguments.

**Comment by radha7krishnan** [comment]
Same problem what we can do please help as
![Uploading IMG_20210902_123950.jpg…]()

**Comment by Salahbahdi2004** [comment]
> HELP ME !!!!!!!!!!!!!!

Did you find a solution?

**Comment by Kingzki** [comment]
Invalid payload  andriod/meterpreter/reverse_tcp

**Comment by bcoles** [comment]
> Invalid payload andriod/meterpreter/reverse_tcp

`android`

**Comment by Kingzki** [comment]
I have done everything right but meterpreter shell could not be opened even after I install the apk

**Comment by Rafaymughal661** [comment]
![Screenshot_20221208_200212](https://user-images.githubusercontent.com/86525540/206480770-d46adf9e-cd45-436d-8a0a-d771ff8a6b49.jpg)
How to fix this error
Help mee...

**Comment by Bhagat-Aadmi** [comment]
invalid payload: android/meterpreter/revers_tcp

**Comment by bcoles** [comment]
> invalid payload: android/meterpreter/revers_tcp

`reverse_tcp`
