### ISSUE TITLE
meterpreter can't screenshot

### ISSUE THREAD

**Issue by khalidalwalid** [rapid7/metasploit-framework#13819]
do you know guys what happened here?

I cant use some commands in meterpreter, one of them is screenshot..
![cant sreenshot](https://user-images.githubusercontent.com/33023197/86805949-613f3f00-c046-11ea-89c8-079c55d4ad23.png)

**Comment by h00die** [comment]
I think you don't have permission to either write a file or take a screenshot.

**Comment by khalidalwalid** [comment]
why?
may I change that permission?

**Comment by khalidalwalid** [comment]
Why? is that because of firewall or something?

**Comment by h00die** [comment]
You'll have to debug that yourself, I'm not on target

**Comment by khalidalwalid** [comment]
okey, I'll try

**Comment by timwr** [comment]
@khalidalwalid if i had to guess you don't have permission to write to your current directory.
You can see the directory with `meterpreter > lpwd` and change it with `meterpreter > lcd`.
