### ISSUE TITLE
apktool not found

### ISSUE THREAD

**Issue by tarunpasrija19** [rapid7/metasploit-framework#13813]
![apktool](https://user-images.githubusercontent.com/65336849/86609474-9a859980-bfc9-11ea-9c35-f517ec985985.PNG)

**Comment by bcoles** [comment]
`msfvenom` requires `apktool` to be in your `$PATH`.

It looks like you're struggling with Metasploit fundamentals.

The Metasploit issue tracker is for tracking issues with Metasploit.

In future, perhaps someone on IRC or Slack can help you out with your question:

* https://www.metasploit.com/help

Closing this issue. If you believe this issue has been closed in error, please provide any relevant output and logs which may be useful in diagnosing the issue.
