### ISSUE TITLE
Metasploit throws error while trying to run Ruby

### ISSUE THREAD

**Issue by ProxyProgrammer** [rapid7/metasploit-framework#13838]
```
Traceback (most recent call last):
	5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
	4: from <internal:gem_prelude>:1:in `require'
	3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1372:in `<top (required)>'
	2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1372:in `require'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:58:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:84:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
```

i just upgraded my os to the lastest version of Kali Linux and im getting this error above i have tried installing ruby and upgrading my packages and even downgrading the version of ruby but nothing. Any suggestions would help, Thank You

**Comment by busterb** [comment]
Try renaming `/usr/local/lib/site_ruby` to something else, or delete it entirely. It looks like you have local gems installed that may be incompatible with the base Kali OS.

This is probably more of a Kali Linux question, not a Metasploit question; Kali maintains its own fork of Metasploit independent of this project. It shouldn't be possible to break it by installing local ruby gems, but that's the best advice I can give you for now.

**Comment by drake22-sv** [comment]
i ran into the following error after updating and upgrading my kali on 11 September 2020, please i need help, can't find good answers elsewhere. 
 msfconsole
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:84:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
	from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:58:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems.rb:1241:in `require'
	from /usr/lib/ruby/2.3.0/rubygems.rb:1241:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
