### ISSUE TITLE
wlan_geolocate Unable to get local issuer certificate

### ISSUE THREAD

**Issue by azizmaiden** [rapid7/metasploit-framework#13840]
I got the following versions: Framework: 5.0.86-dev Console: 5.0.86-dev

The os that metasploit is installed are windows 10.

I get a meterpreter session with an android device (genymotion virtual machine) device and desktop are on the same network and also device has enabled gps with pre-defined lat & long and when I enter the following command in meterpreter:

run post/multi/gather/wlan_geolocate APIKEY=my google map API key (clean, without quotes or anything else) GEOLOCATE=true

I get the result in the photo with the error as I describe in the title, does anyone know if its a version SSL problem or something? how and where to search to fix this problem?

![B8Ogf](https://user-images.githubusercontent.com/47272573/87227042-ae9e1200-c3a0-11ea-88a0-1a2e7da9314c.png)

**Comment by gwillcox-r7** [comment]
@azizmaiden This looks like the module wasn't able to verify the SSL certificate of some website, which given the module I presume is the Google Map API server. You can try run it again but use `set VERBOSE true` and see if it prints out any more detailed informtion.

**Comment by azizmaiden** [comment]
@gwillcox-r7 I also tried with VERBOSE=true but it didn't printed more details still the same output as above. i tried to figure something related to SSL inside framework log file as you said also, and the related lines with SSL are these:

`[06/15/2020 09:06:48] [e(0)] core: C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/modules/auxiliary/scanner/ssl/bleichenbacher_oracle.rb failed to load due to the following error: Errno::ENOENT No such file or directory @ rb_sysopen - C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/modules/auxiliary/scanner/ssl/bleichenbacher_oracle.rb Call stack: C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/modules/loader/directory.rb:77:in `initialize' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/modules/loader/directory.rb:77:in `open' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/modules/loader/directory.rb:77:in `read_module_content' (eval):56:in `read_module_content_with_decryption' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/modules/loader/base.rb:127:in `load_module' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/module_manager/cache.rb:91:in `block in load_cached_module' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/module_manager/cache.rb:86:in `each' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/module_manager/cache.rb:86:in `load_cached_module' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/msf/core/module_set.rb:45:in `create' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:311:in `block (3 levels) in update_all_module_details' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:308:in `each' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:308:in `block (2 levels) in update_all_module_details' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:305:in `each' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:305:in `block in update_all_module_details' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection' C:/metasploit/apps/pro/engine/lib/msf/core/db_manager/module_cache.rb:268:in `update_all_module_details' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/metasploit-framework-5.0.86/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing' C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/service.rb:275:in `block in rpc_service' C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument' C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/application/notifications.rb:32:in `instrument' C:in `instrument' C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/service.rb:229:in `rpc_service' C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/service.`

Again i'm new to metasploit framework and cannot figure much i hope it helps...

**Comment by gwillcox-r7** [comment]
Hmm those lines don't seem to have anything to do with your current module, which is odd. If you provide the unfiltered output there should be at least a few lines of output where it actually runs the module. If your just filtering it out based on the mention of ssl, then that isn't going to be as helpful as you'll likely be filtering out other bits of information that may help us in determining what the issue is here.

**Comment by gwillcox-r7** [comment]
@azizmaiden We recently made updates to this module to fix an error where things would fail if an invalid API key was provided. Could you try updating your Metasploit to the most recent release, note the version, and then try again?

**Comment by azizmaiden** [comment]
@gwillcox-r7 i updated to latest version: v5.0.101-dev

same error occurs as before...

**Comment by gwillcox-r7** [comment]
> @gwillcox-r7 i updated to latest version: v5.0.101-dev
> 
> same error occurs as before...

@azizmaiden The latest version at the time of writing is presently `v6.0.1-dev-2305da2638`, if you clone it from the GitHub repository (the versions available from Kali and other distros is an older version whilst Metasploit version 6 is undergoing stability tests).
