### ISSUE TITLE
Can  I install it in my phone?

### ISSUE THREAD

**Issue by saihum** [rapid7/metasploit-framework#13851]
## Relevant information

I have a redmi 6A with android 9.. armv7 structure.. can I download it in termux and use

**Comment by bcoles** [comment]
Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux. @busterb or @timwr may be able to offer some guidance.

Refer to the following for more information:

* https://wiki.termux.com/wiki/Metasploit_Framework
* termux/termux-packages/issues/715

**Comment by saihum** [comment]
Thanks,it worked
