### ISSUE TITLE
How do I fix msfconsole command and related tools not being added to the system %PATH% variable

### ISSUE THREAD

**Issue by ZenTheDev** [rapid7/metasploit-framework#13862]
I installed metasploit as usual and after it finished I attempted to run msfconsole, instead of this working as expected I actually got the error: `'msfconsole' is not recognized as an internal or external command,
operable program or batch file.`

I am fairly certain this means that the msfconsole command was not added to the system %PATH% variable. How do I fix this. My antivirus is not running so the installation should've added msfconsole to the system %PATH% variable.

What I have tried: I have uninstalled and reinstalled already and I have ran console from administrator.

**Comment by bcoles** [comment]
I have no idea if Metasploit adds itself to the system `%PATH%` by default; however, you can easily add the Metasploit path in the same way you would add any other path to the system path. That is, add the path to `PATH` in the system environment variable. The appropriate GUI can be found via `Advanced System Settings` or searching `Edit the system environment variables`; then `Advanced` tab; `Environment Variables` button. The `PATH` variable can be found under `System Variables`. Paths are separated by semicolons `;`.
