### ISSUE TITLE
Msfconsole: invalid argument @rb_sysopen

### ISSUE THREAD

**Issue by girhgzm** [rapid7/metasploit-framework#13864]
**msfconsole output:**

Traceback (most recent call last):ork console...|sole...\
        30: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
        29: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
        28: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
        27: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        26: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
        25: from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:159:in `initialize'
        24: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        23: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        22: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        21: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        20: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        19: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        18: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules'
        17: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:133:in `each'
        16: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules'
        15: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
        14: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:256:in `each'
        13: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
        12: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `recalculate'
        11: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:109:in `each_pair'
        10: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `block in recalculate'
         9: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:122:in `each_pair'
         8: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:186:in `block (2 levels) in recalculate'
         7: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload.rb:212:in `size'
         6: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload/android.rb:42:in `generate'
         5: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload/android.rb:134:in `generate_jar'
         4: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-zip-0.1.3/lib/rex/zip/jar.rb:125:in `add_files'
         3: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-zip-0.1.3/lib/rex/zip/jar.rb:125:in `each'
         2: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-zip-0.1.3/lib/rex/zip/jar.rb:134:in `block in add_files'
         1: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-zip-0.1.3/lib/rex/zip/jar.rb:134:in `open'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-zip-0.1.3/lib/rex/zip/jar.rb:134:in `initialize': Invalid argument @ rb_sysopen - /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml (Errno::EINVAL)

**Output of bundle install:**
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Traceback (most recent call last):
        1: from /usr/local/bin/bundle:23:in `<main>'
/usr/local/bin/bundle:23:in `load': cannot load such file -- /var/lib/gems/2.5.0/gems/bundler-2.1.4/exe/bundle (LoadError)

I have completely no idea how to fix this since none of the methods I looked up works. I have tried **sudo gem update --system** as a lot suggested it.

ruby version:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

Using Ubuntu on Windows
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by bcoles** [comment]
There seems to have been [a few similar issues reported related to `AndroidManifest.xml`](https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+AndroidManifest.xml), although they were reported in `msfvenom` rather than `msfconsole`.

Someone did report the same issue in `msfconsole` yesterday (but didn't create a new issue). https://github.com/rapid7/metasploit-framework/issues/8956#issuecomment-660438413

The `data/android/apk/AndroidManifest.xml` file does exist on my dev system (Kali):

```
# locate AndroidManifest.xml
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
/var/lib/gems/2.5.0/gems/metasploit-payloads-1.4.1/data/android/apk/AndroidManifest.xml
/var/lib/gems/2.5.0/gems/metasploit-payloads-1.4.2/data/android/apk/AndroidManifest.xml
/var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.1/data/android/apk/AndroidManifest.xml
/var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.2/data/android/apk/AndroidManifest.xml
/var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
# file /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml: Android binary XML
```


The issue is triggered when loading modules. For some reason `generate` / `generate_jar` are called in `lib/msf/core/payload/android.rb` during `msfconsole` startup, and generating a jar file requires this `AndroidManifest.xml` file to exists.

Perhaps this file was vaporized by anti-virus software. Is there anything in your anti-virus software logs? You could try disabling anti-virus software and reinstalling the `metasploit-payloads` gem.

**Comment by girhgzm** [comment]
> There seems to have been [a few similar issues reported related to `AndroidManifest.xml`](https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+AndroidManifest.xml), although they were reported in `msfvenom` rather than `msfconsole`.
> 
> Someone did report the same issue in `msfconsole` yesterday (but didn't create a new issue). [#8956 (comment)](https://github.com/rapid7/metasploit-framework/issues/8956#issuecomment-660438413)
> 
> The `data/android/apk/AndroidManifest.xml` file does exist on my dev system (Kali):
> 
> ```
> # locate AndroidManifest.xml
> /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
> /var/lib/gems/2.5.0/gems/metasploit-payloads-1.4.1/data/android/apk/AndroidManifest.xml
> /var/lib/gems/2.5.0/gems/metasploit-payloads-1.4.2/data/android/apk/AndroidManifest.xml
> /var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.1/data/android/apk/AndroidManifest.xml
> /var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.2/data/android/apk/AndroidManifest.xml
> /var/lib/gems/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
> # file /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml
> /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-1.4.4/data/android/apk/AndroidManifest.xml: Android binary XML
> ```
> 
> The issue is triggered when loading modules. For some reason `generate` / `generate_jar` are called in `lib/msf/core/payload/android.rb` during `msfconsole` startup, and generating a jar file requires this `AndroidManifest.xml` file to exists.
> 
> Perhaps this file was vaporized by anti-virus software. Is there anything in your anti-virus software logs? You could try disabling anti-virus software and reinstalling the `metasploit-payloads` gem.

ok i will try
