### ISSUE TITLE
Embedded payload 

### ISSUE THREAD

**Issue by jamesmiller9048** [rapid7/metasploit-framework#13908]
Is there any module or any method to embedded a payload into a gif, mkv, or jpeg etc.

**Comment by void-in** [comment]
You can't embed executable code with data formats such as gif, mkv, or jpeg. You can certainly use some packers in order to embed an executable with these formats but then the resulting file will be an executable file as well.

Please use the Metasploit slack channel for support queries.

**Comment by jamesmiller9048** [comment]
Sorry didn't get what your saying 
Is there there any link where can I find it

**Comment by bcoles** [comment]
> 
> 
> Sorry didn't get what your saying
> Is there there any link where can I find it

* https://www.metasploit.com/help
