### ISSUE TITLE
burp suite proxy issue

### ISSUE THREAD

**Issue by jamesmiller9048** [rapid7/metasploit-framework#13907]
I'm using mozilla firefox i changed my proxy settings to manual proxy and filled in my local ip and port number as 8080 and then ticked the checkbox (use this proxy for all protocols)
I can't load any websites now It says "proxy server is refusing connections" 
I used the proxy setting to capture in burp suite intercept box

**Comment by bcoles** [comment]
Sir this is a Wendy's

**Comment by jamesmiller9048** [comment]
> Sir this is a Wendy's

sorry didn't get what you are saying

**Comment by h00die** [comment]
this is a metasploit github.  you asked about networking, firefox, and burp.  None of those are metasploit.  You should ask these questions in the appropriate place, like on the kali forum, on burp's support page etc.

What @bcoles was saying was that you were asking the wrong people the wrong things, like ordering a big mac at a wendys.

**Comment by jamesmiller9048** [comment]
Sorry I'm new to this 
Can you please send me the link of burp suite

**Comment by bcoles** [comment]
> 
> 
> Sorry I'm new to this
> Can you please send me the link of burp suite

You can solve your problem without contacting the Burp Suite developers. I believe in you.

**Comment by jamesmiller9048** [comment]
Thanx man.. @bcoles
