### ISSUE TITLE
can't install metasploit from debian bundle

### ISSUE THREAD

**Issue by ilyapashuk** [rapid7/metasploit-framework#13917]
when tring to apt update after adding your repo to sources.list and importing keys, I get:
unexpected file size, 429 != 430, and apt refuses to use this index file.

**Comment by adfoster-r7** [comment]
Unfortunately there's not enough information here to help. What operating system, and install guide were you following?

**Comment by RA80533** [comment]
@ilyapashuk, does the error say anything about a mirror sync occurring?
