### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by devilmen80** [rapid7/metasploit-framework#13938]
Hello.

I am injecting payload in original apk with msfvenom.

When I run msfconsole some modules like dump_sms don't work.

I was able to understand that is question of permissions

When I install apk infected on my phone it doesn't ask me any permission...

Someone have solution to this problem?

**Comment by timwr** [comment]
@devilmen80 if you're targeting the more recent Android versions (> 8?) you will need to inject into an app that requests the permissions at runtime. We might be able to add a way of requesting the permissions at runtime or first app launch.
