### ISSUE TITLE
Metasploit bcrypt Issue (Windows)

### ISSUE THREAD

**Issue by KarmicElk** [rapid7/metasploit-framework#13933]
## Steps to reproduce

Windows 10 2004 build 19041.388
CommandoVM version 2020.2

1. Unable to run Metasploit latest build installed via MSI installer downloaded directly from windows.metasploit.com. 
2. I get this error when trying to run msfconsole:

Bundler could not find compatible versions for gem "bcrypt":
  In Gemfile:
    metasploit-framework x64-mingw32 was resolved to 5.0.101, which depends on
      bcrypt (= 3.1.12) x64-mingw32

Could not find gem 'bcrypt (= 3.1.12)', which is required by gem 'metasploit-framework', in any of the sources.

## Expected behavior

Msfconsole should run

## Current behavior

Msfconsole does not run

### Metasploit version

Metasploit-framework v5.0.101

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Windows 10 2004 build 19041.388
CommandoVM version 2020.2

![2020-08-02 22_39_26-Window](https://user-images.githubusercontent.com/49791682/89146503-27603c00-d511-11ea-9f90-6f741ef6750e.png)

**Comment by dwelch-r7** [comment]
Potentially will be resolved by #13894

**Comment by Melody15** [comment]
Just solved this according to this [article](https://blog.csdn.net/weixin_43286366/article/details/107682038)

Change the file: 
\metasploit-framework\embedded\framework\metasploit-framework.gemspec, line 56
from: spec.add_runtime_dependency 'bcrypt', '3.1.12'
to: spec.add_runtime_dependency 'bcrypt', '~> 3.1.12'

**Comment by KarmicElk** [comment]
@Melody15 That worked, thanks!

**Comment by sresanajai** [comment]
It worked.Thanks a lot....
