### ISSUE TITLE
metasploit framework not working(gem bundle and bcrypt error)

### ISSUE THREAD

**Issue by sresanajai** [rapid7/metasploit-framework#13937]
when run the command msfconsole it shows:
Bundler could not find compatible versions for gem "bcrypt":
  In Gemfile:
    metasploit-framework x64-mingw32 was resolved to 5.0.102, which depends on sysrandom x64-mingw32

  Could not find gem 'bcrypt (=3.1.12)', which is required by gem 'metasploit-framework', in any of the sources.
anyone please help.

**Comment by bcoles** [comment]
Perhaps this will help:

https://github.com/rapid7/metasploit-framework/issues/13933#issuecomment-667881372

**Comment by jmartin-r7** [comment]
This is resolved by #13894, sorry https://github.com/rapid7/metasploit-omnibus/pull/131 should have noted the dependency.

**Comment by gwillcox-r7** [comment]
Closing issue as there is a verified fix for this bug.
