### ISSUE TITLE
Expand `~` in upload and download commands in meterpreter

### ISSUE THREAD

**Issue by alichtman** [rapid7/metasploit-framework#13948]
## Summary

I would expect that these two commands behave the same, however, they do not.

![image](https://user-images.githubusercontent.com/20600565/89502721-0acf3880-d78b-11ea-8b06-588431cdc6cd.png)

EDIT: This might be a bug?

```bash
$ msfconsole -v
Framework Version: 5.0.101-dev
```

### Motivation

Better UX.

**Comment by wvu-r7** [comment]
Not a bug. I noted at one point that tilde completion worked, but tilde expansion did not. I also said I'd fix it three times since 2018. 🙃
