### ISSUE TITLE
Cannot execute commands via -x parameter in msfpro console

### ISSUE THREAD

**Issue by Pl0414141** [rapid7/metasploit-framework#13972]
I want execute the following command without entering into the msfpro console

pro_discover 127.0.0.1 -p 1-65535

I have tried the following commands but no one success

msfpro -- -q -x 'pro_discover;127.0.0.1'
msfpro -- -q -x "pro_discover","127.0.0.1"
msfpro -- -q -x '"pro_discover 127.0.0.1"'
msfpro -- -q -x 'pro_discover 127.0.0.1'
msfpro -- -q -x "pro_discover" "127.0.0.1"

Anyone can help me?
Thanks

Full Output:

root@ubuntu:/home/scan/Desktop/msfrpc-client/examples# msfpro -- -q -x 'pro_discover;127.0.0.1'
[*] Starting Metasploit Console...
[+] 
[+] Metasploit Pro extensions have been activated
[+] 
[*] Successfully loaded plugin: pro
[-] No target IP addresses were specified
[-] Unknown command: 127.0.0.1.
msf-pro > exit
root@ubuntu:/home/scan/Desktop/msfrpc-client/examples# msfpro -- -q -x "pro_discover","127.0.0.1"
[*] Starting Metasploit Console...
[+] 
[+] Metasploit Pro extensions have been activated
[+] 
[*] Successfully loaded plugin: pro
[-] Unknown command: pro_discover,127.0.0.1.
msf-pro > 
root@ubuntu:/home/scan/Desktop/msfrpc-client/examples# msfpro -- -q -x '"pro_discover 127.0.0.1"'
[*] Starting Metasploit Console...
[+] 
[+] Metasploit Pro extensions have been activated
[+] 
[*] Successfully loaded plugin: pro
[-] Parse error: Unmatched double quote: "\"pro_discover"
msf-pro > exit
root@ubuntu:/home/scan/Desktop/msfrpc-client/examples# msfpro -- -q -x "pro_discover" "127.0.0.1"
[*] Starting Metasploit Console...
[+] 
[+] Metasploit Pro extensions have been activated
[+] 
[*] Successfully loaded plugin: pro
[-] No target IP addresses were specified

**Comment by dwelch-r7** [comment]
Support for the Pro product is handled through Rapid7 support. See https://www.rapid7.com/for-customers/ to start a support request.
