### ISSUE TITLE
updating to latest version in Parrot OS 4.9.1

### ISSUE THREAD

**Issue by acarpenter757** [rapid7/metasploit-framework#13987]
## Relevant information

What's the best way to update to the latest version?  I'm using Parrot OS 4.9.1

**Comment by dwelch-r7** [comment]
Hi, this isn't really an issue for us here, parrot packages their own version of Metasploit Framework I believe this command is what you should use though `apt install metasploit-framework` if that doesn't work please ask the Parrot OS community

**Comment by eslamelhadedy** [comment]
i have the same problem
