### ISSUE TITLE
How to run task chain in MetaSploit PRO manually through console

### ISSUE THREAD

**Issue by Pl0414141** [rapid7/metasploit-framework#13981]
Under msfpro web console we can create task chains but, how can we execute thorough metascript or cmd?

For example

msfpro -- -r myscript.rc

myscript.rc contents >>

<ruby>
run_single("mytaskchain_1")
....
</ruby>

**Comment by dwelch-r7** [comment]
Support for the Pro product is handled through Rapid7 support. See https://www.rapid7.com/for-customers/ to start a support request.
