### ISSUE TITLE
msf5 > msfvenom [-] Unknown command: msfvenom.

### ISSUE THREAD

**Issue by saran-gangster** [rapid7/metasploit-framework#13993]
**Issue**

 i have typed msfvenom to create a .exe file
i have been excepted to get the .exe file
but in return  it is say's that msfvenom is not recognized has internal or external command

## System stuff
windows 8.1
### Metasploit version
Framework: 5.0.100-dev-53a97f811832f22104d4dc8770f099f73c9ba4dd
Console  : 5.0.100-dev-53a97f811832f22104d4dc8770f099f73c9ba4dd

### I installed Metasploit with:

Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

What OS are you running Metasploit on?
windows 8.1

**Comment by dwelch-r7** [comment]
You don't use msfvenom from within the framework console, it's a standalone program, you need to exit the console to use it

**Comment by azadgithub0** [comment]
msf6>Unknown command: msfvenom.  how to solve

**Comment by bcoles** [comment]
> 
> 
> msf6>Unknown command: msfvenom. how to solve

https://github.com/rapid7/metasploit-framework/issues/13993#issuecomment-673456030
