### ISSUE TITLE
[Bug]Can't install Metasploit in Termux

### ISSUE THREAD

**Issue by RealGJ** [rapid7/metasploit-framework#14017]
I'm not sure what is the problem but, Whenever I try to install metasploit in Termux (Android) following error popups:

Traceback (most recent call last):
        1: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
<internal:gem_prelude>:1:in `require': cannot load such file -- rubygems.rb (LoadError)
dpkg: error processing package metasploit (--configure):
 installed metasploit package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 metasploit
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

See screenshots: https://photos.app.goo.gl/RDP9srfmvhsWEN2h6

**Comment by whitedays2007** [comment]
**Can't install metasploit in Termux?**

**Comment by whitedays2007** [comment]
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1) 

The solution is very simple

**Comment by whitedays2007** [comment]
Termux Solution: `rm -rf $PREFIX/var/lib/dpkg/info/*`
Then apt update is fine.

**Comment by RealGJ** [comment]
@whitedays2007 Thank you for Reply and Help. Now msfconsole Command isn't working!!

**Comment by whitedays2007** [comment]
If you cannot use the metasploit installed in the unstable-repo repository, you can use the official project     

Termux command：      
update...     
`apt update && apt upgrade -y`     
requirements:    
**Some requirement libraries may not be written in, you can research by yourself what requirement libraries are still missing**      
`apt install ruby postgresql clang python2 python git`       
Clone:     
`git clone https://github.com/rapid7/metasploit-framework`
bundle:
`cd metasploit-framework/`
`gem install bundle`
`gem install bundler`
`bundle install`

start:     
`ruby msfconsole`     
**If not, leave a message**

**Comment by freakyguilty** [comment]
Still have ruby incompitable

**Comment by quayegodfred** [comment]
Guys please help am having a problem in installing metasploit

**Comment by unixquuw** [comment]
Hiya. The creator of the termux, removed the metasploit package. 
![IMG_20210607_072712](https://user-images.githubusercontent.com/79478046/120963756-72b32e80-c762-11eb-9ea7-2b2d726548ac.jpg) You need to use third-party tool such as metasploit installers for termux in order to get it working.

**Comment by manojb877** [comment]
Traceback (most recent call last):
        29: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'
        28: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        25: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        24: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        23: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        22: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        21: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails.rb:17:in `<top (required)>'
        20: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails.rb:17:in `require'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/railtie.rb:4:in `<top (required)>'
        18: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/railtie.rb:4:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:9:in `<top (required)>'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:10:in `<module:I18n>'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:11:in `<class:Railtie>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:127:in `config'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:223:in `config'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:223:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie/configuration.rb:3:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie/configuration.rb:3:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/configuration.rb:4:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/configuration.rb:4:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object.rb:13:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:8:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:8:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so" load segment[7]: p_offset (0x11000) + p_filesz (0x408) ( = 0x11408) past end of file (0x11408) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
$Traceback (most recent call last):
        29: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'
        28: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        25: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        24: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        23: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        22: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        21: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails.rb:17:in `<top (required)>'
        20: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails.rb:17:in `require'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/railtie.rb:4:in `<top (required)>'
        18: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/railtie.rb:4:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:9:in `<top (required)>'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:10:in `<module:I18n>'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/i18n_railtie.rb:11:in `<class:Railtie>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:127:in `config'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:223:in `config'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie.rb:223:in `require'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie/configuration.rb:3:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/railtie/configuration.rb:3:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/configuration.rb:4:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-5.2.6/lib/rails/configuration.rb:4:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object.rb:13:in `require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:8:in `<top (required)>'
         4: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/json.rb:8:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so" load segment[7]: p_offset (0x11000) + p_filesz (0x408) ( = 0x11408) past end of file (0x11408) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal/util.so (LoadError)
$

**Comment by Akaaasaaah** [comment]
How to Fix this Error?
I'm using Android 6.0 (Non Rooted phone)
Can anyone help me please to fix this error.

Advance Thanks

**Comment by Badial5** [comment]
> Termux Solution: `rm -rf $PREFIX/var/lib/dpkg/info/*`
> Then apt update is fine.

How? Can you teach step by step way to do that?

**Comment by hollaly** [comment]
HOw do i fix this pls?
cd metasploit-framework
$ gem install bundle
WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6ffffef5 arg 0x45c
WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x1d arg 0x106
WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6ffffffe arg 0x55c
WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6fffffff arg 0x1
WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6ffffef5 arg 0xfe94
WARNING: linker: libruby.so.2.7: unused DT entry: type 0x1d arg 0x8201
WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6ffffffe arg 0x16ec0
WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6fffffff arg 0x3

**Comment by h00die** [comment]
> HOw do i fix this pls? cd metasploit-framework $ gem install bundle WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6ffffef5 arg 0x45c WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x1d arg 0x106 WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6ffffffe arg 0x55c WARNING: linker: /data/data/com.termux/files/usr/bin/ruby: unused DT entry: type 0x6fffffff arg 0x1 WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6ffffef5 arg 0xfe94 WARNING: linker: libruby.so.2.7: unused DT entry: type 0x1d arg 0x8201 WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6ffffffe arg 0x16ec0 WARNING: linker: libruby.so.2.7: unused DT entry: type 0x6fffffff arg 0x3

by not using termux, or asking the termux people how to fix it.

**Comment by PrabhLuthra** [comment]
msfconsole
The program msfconsole is not installed. Install it by executing:
 pkg install metasploit, after running pkg in unstable-repo

**Comment by PrabhLuthra** [comment]
The program msfconsole is not installed. Install it by executing:
 pkg install metasploit, after running pkg in unstable-repo

**Comment by IamA2004** [comment]
Some one help me I type msfconsole

Error 👇

Metasploit tip: When in a module, use back to go back to the top level
prompt
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'

**Comment by Alctron99** [comment]
I'm installing Metasploit on Termux, and this window appears. How do I bypass it? ───Installation was incomplete──────┐ ──│ │──── │Connection was disconnected. │ │Your system has not been modified. │ │To install this tool at a later │ │ time, please run this installer │ │ again. │ │


Who can help me plz

**Comment by lylabw916-bit** [comment]
- [ ] ![Screenshot_20260511_001345_com.termux.jpg](https://github.com/user-attachments/assets/0bc2f50f-12be-4494-bbb2-eab2ba698290)

**Comment by h00die** [comment]
please see the fix here: https://github.com/rapid7/metasploit-framework/issues/14017#issuecomment-885415662
