### ISSUE TITLE
msfb init failed

### ISSUE THREAD

**Issue by synergie91** [rapid7/metasploit-framework#14059]
I am new to MSF and have setup Kali on WSL2. Upon trying to run msfdb init, I receive the below error - a search finds this is due to WSL2 not supporting systemd.

~$ sudo msfdb init
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[+] Starting database
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[i] The database appears to be already configured, skipping initialization

**Comment by GetRektBoy724** [comment]
ok this is the problem with WSL
just try to install an kali vm 
or you can just not to use the msfdb
