### ISSUE TITLE
 What is needed to build metasploit from source code in BSD?

### ISSUE THREAD

**Issue by insanitus** [rapid7/metasploit-framework#14058]
## Summary

- What problem(s) did you run into that caused you to request additional documentation? 
 I don't found the documentation how to install metasploit from source code

- What questions do you think we should answer? 
 What libraries is need it to install metasploit in other O.S. from source code?  
 What is need it to check for build metasploit in my O.S?

Some recommended topics to cover:

- The dependency and libraries require to build it from scratch
 

### Motivation

Why should we document this?  Because the information is not in the
documentation.

Who will benefit from it?
 The users from other Operative System 

## Steps to resolve this issue

- [ ] One of the requirements is to **install Ruby** in your O.S. 
  - [Try to download Ruby from the official website](https://www.ruby-lang.org/en/downloads/)
[ ] Check if Ruby are installed correctly in your O.S. 

- [ ] Install Postgres 
   - [Try to download Postgres  from the official website](https://www.postgresql.org/download/)
[ ] Check if Postgres is working in your O.S.

- [ ] Download the metasploit code
  - [metasploit-code](https://github.com/rapid7/metasploit-framework)

Thanks in advance and have a good day (n__n)

**Comment by FunnyWolf** [comment]
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment   maybe you need this~

**Comment by gwillcox-r7** [comment]
If you are just looking for the information you listed above r.e how to install Ruby, Postgres and download the Metasploit code then the information at the link that @FunnyWolf mentioned, which has now been moved to https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html, should be sufficient.

If you are looking for info on how our installers are built using Omnibus, then I'd recommend looking over at https://github.com/rapid7/metasploit-omnibus which should document most of how these are built.

Closing this as the original request has already been completed.
