### ISSUE TITLE
can not find /github/rapid7/metasploit-framework/lib/Rex/Encoder/NDR.uwstring, where is it from?

### ISSUE THREAD

**Issue by taomujian** [rapid7/metasploit-framework#14057]
I want to see the NDR.uwstring fuction,but i can not find in /lib/Rex/ module, where is it from?

**Comment by cn-kali-team** [comment]
> I want to see the NDR.uwstring fuction,but i can not find in /lib/Rex/ module, where is it from?

rex-encoder是Metasploit的一个支持库，在源码里是看不到的，要独立安装。
执行bundle install重新安装依赖库，应该可以在ruby的gems目录找到rex-encoder
像：
> /home/kali-team/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rex-encoder-0.1.4/lib/rex

[rex-encoder](https://github.com/rapid7/rex-encoder)
rex-encoder is a supporting Library of Metasploit, which can't be seen in the source code and needs to be installed independently.
Execute `bundle install` to reinstall the dependent library, You should be able to find `rex-encoder` in Ruby's Gems directory
like:
> /home/kali-team/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rex-encoder-0.1.4/lib/rex

**Comment by taomujian** [comment]
好的，谢谢
