### ISSUE TITLE
Metasploit installs to incorrect Hard Drive

### ISSUE THREAD

**Issue by Reelix** [rapid7/metasploit-framework#14071]
## Steps to reproduce

How'd you do it?

1. Download https://windows.metasploit.com/metasploitframework-latest.msi
2. Attempt to install Metasploit to `R:\Utilities\`

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Metasploit gets installed under `R:\Utilities\`

## Current behavior

Metasploit gets installed in the root directory of `M:\`

### Metasploit version

Framework: 6.0.4-dev-760aba0ace4cd3ce88c65af154fb70df57d09ea1
Console  : 6.0.4-dev-760aba0ace4cd3ce88c65af154fb70df57d09ea1

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Windows 10

### Additional Information

I have 4 Hard Drives: `C:\ - Local Disk`, `G:\ - 'Reelix - Games'`, `M:\ - 'Reelix - Media'` and `R:\ - 'Reelix - Misc'` (That contains a Utilities folder at `R:\Utilities\`  
  
This issue has persisted in an identical fashion between attempted reinstallations making sure that the correct location was chosen during installation.

**Comment by GetRektBoy724** [comment]
it was hard tho to know the problem from an omnibus installer....
if you keep getting this problem...
try to install a kali vm

**Comment by franferrax** [comment]
Hi, I think this should be reported in the `metasploit-omnibus` repository. Even more, it seems to be actually reported in rapid7/metasploit-omnibus#115.

**Comment by David-OConnor** [comment]
Same! Please re-open. Not fixed.

**Comment by Muriel-Gasparini** [comment]
Same here.
