### ISSUE TITLE
`Msf::Sessions::CommandShell.binary_exists` uses `which` to find paths of executable files

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#14077]
https://github.com/rapid7/metasploit-framework/issues/12345#issuecomment-533506519

`Msf::Sessions::CommandShell.binary_exists` uses `which` to find paths of executable files:

```ruby
  #
  # Check if there is a binary in PATH env
  #
  def binary_exists(binary)
    print_status("Trying to find binary(#{binary}) on target machine")
    binary_path = shell_command_token("which #{binary}").to_s.strip
    if binary_path.eql?("#{binary} not found")
      print_error(binary_path)
      return nil
    else
      print_status("Found #{binary} at #{binary_path}")
      return binary_path
    end
  end
```

This is not a portable solution.

Additionally, `if binary_path.eql?("#{binary} not found")` is an unsafe indicator of success. The output of `which` can vary on different shells and may vary by locale.

Additionally, the argument is not quoted, which won't end well in the unlikely event that the executable name contains spaces, as each part of the file name will be treated as a separate command.

`command -v '#{binary}'` is [POSIX compliant](https://pubs.opengroup.org/onlinepubs/009695399/utilities/command.html) and usually preferred over `which`; however, handling of `stdout` and `stderr` is inconsistent throughout the framework. Often both `stdout` and `stderr` are returned to Metasploit, which may complicated matters.

Another alternative is `type -P '#{binary}'`.

As usual, the answer is complicated:

* https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
* https://github.com/koalaman/shellcheck/issues/1162

[Elsewhere in the framework](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/common.rb), `command -v` is used to check if an executable exists, but does not return the path:

```ruby
  #
  # Checks if the `cmd` is installed on the system
  # @return [Boolean]
  #
  def command_exists?(cmd)
    if session.platform == 'windows'
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/where_1
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if
      cmd_exec("cmd /c where /q #{cmd} & if not errorlevel 1 echo true").to_s.include? 'true'
    else
      cmd_exec("command -v #{cmd} && echo true").to_s.include? 'true'
    end
  rescue
    raise "Unable to check if command `#{cmd}' exists"
  end
```

**Comment by pingport80** [comment]
I guess `command -v` returns path.
```
pingport80@kali:~/rapid7/metasploit-framework/lib/msf/base/sessions$ command -v poweroff 
/usr/sbin/poweroff
```

**Comment by bcoles** [comment]
> 
> 
> I guess `command -v` returns path.
> 
> ```
> pingport80@kali:~/rapid7/metasploit-framework/lib/msf/base/sessions$ command -v poweroff 
> /usr/sbin/poweroff
> ```

Yes. [Elsewhere in the framework](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/common.rb), `command -v` is used to check if an executable exists, but does not return the path:

```ruby
  #
  # Checks if the `cmd` is installed on the system
  # @return [Boolean]
  #
  def command_exists?(cmd)
    if session.platform == 'windows'
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/where_1
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if
      cmd_exec("cmd /c where /q #{cmd} & if not errorlevel 1 echo true").to_s.include? 'true'
    else
      cmd_exec("command -v #{cmd} && echo true").to_s.include? 'true'
    end
  rescue
    raise "Unable to check if command `#{cmd}' exists"
  end
```

**Comment by pingport80** [comment]
Okay!
