### ISSUE TITLE
installer ended prematurely,doesnt matter what location i choose

### ISSUE THREAD

**Issue by bukyapavankumar** [rapid7/metasploit-framework#14080]
## Steps to reproduce

How'd you do it?

1. install latest nightly windows installer (mine v6.0.4 at the time)
2. waited 10-15 min but it give me error installer ended prematurely 

### OS
 windows 10 2004 (64 bit)

**Comment by GetRektBoy724** [comment]
metasploit framework doesnt work on windows well
try to install a kali vm :)

**Comment by bukyapavankumar** [comment]
This issue is still present . somehave have a fix?
