### ISSUE TITLE
zsh: command not found: msfconsole

### ISSUE THREAD

**Issue by vitguld** [rapid7/metasploit-framework#14098]
Hi,

Installed Metasploit on my macOS Catalina from the rapid7 website - dpkg installation,
and when trying to run `msfconsole` the terminal displays the following error: `zsh: command not found: msfconsole`

**Comment by qadirsuh** [comment]
how to fix this? I am still getting this. 

MacOS Ventura 13.2.1 (Apple M2 Pro chip)

**Comment by qadirsuh** [comment]
Solved it via

command 1
`cd /opt/metasploit-framework/bin/`
command 2
`./msfconsole`
