### ISSUE TITLE
Apk Signing Error

### ISSUE THREAD

**Issue by Bhaviktutorials** [rapid7/metasploit-framework#14097]
Hello Sir,
I am Getting Error in Metasploit Signing Feature 
It shows The apk is Sign But in actual It Detect In System 
So can Say me what to do?

**Comment by Chotu75** [comment]
you have to manually sign apk with apktool.. follow this guide https://youtu.be/xoHV17u3CIQ

**Comment by Bhaviktutorials** [comment]
Ohk now understood
