### ISSUE TITLE
I have a problem with metasploit

### ISSUE THREAD

**Issue by papibdn** [rapid7/metasploit-framework#14102]
gem install bundler -v'~>1.16' when i tape this i receive ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.
Help me please

**Comment by gwillcox-r7** [comment]
You don't have permissions to install the gem file, most likely cause you installed Ruby as the `root` user, so that directory has permissions set on it so that only the `root` user can access it. You should try running `sudo gem install bundler -v'~>1.16'` and see if that solves your issue.

**Comment by gwillcox-r7** [comment]
Closing this issue as there has been no response after 17 days and I believe this issue has been resolved.
