### ISSUE TITLE
Can't load my module-Offensive Security Metasploit tutorial- WRITING YOUR OWN SECURITY SCANNER

### ISSUE THREAD

**Issue by jnvr** [rapid7/metasploit-framework#14108]
I'm trying to load the module presented in the tutorial "https://www.offensive-security.com/metasploit-unleashed/writing-scanner/ ", when i restart msfconsole i get 

>[-] WARNING! The following modules could not be loaded!
[-] 	/usr/share/metasploit-framework/modules/auxiliary/scanner/simple_tcp.rb
[-] Please see /root/.msf4/logs/framework.log for details.

After going to the framework.log it appears 

> [09/08/2020 17:51:39] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/simple_tcp.rb failed to load - SyntaxError /usr/share/metasploit-framework/modules/auxiliary/scanner/simple_tcp.rb:2: syntax error, unexpected `super', expecting ';' or '\n'
...y::Scanner def initialize super( 'Name' => 'My custom TCP sc...
...                          ^~~~~
/usr/share/metasploit-framework/modules/auxiliary/scanner/simple_tcp.rb:12: syntax error, unexpected `end', expecting end-of-input
        end
        ^~~
what should I do? I am literally copy-pasting the code from the link presented earlier into notepad and then to the "simple_tcp.rb" file itself, in the same spot they mension during the tutorial.

Thanks in Advance.

**Comment by dwelch-r7** [comment]
Unfortunately the tutorial you're following appears to be really old and has syntax issues in the code, you should take a look at how other scanner modules in metasploit work and you could perhaps adapt the tutorial to work with the current version

**Comment by jnvr** [comment]
ok, thanks. Btw do u happen to know any tutorials u would recommend to someone trying to learn stuff about security and/or hacking

**Comment by bcoles** [comment]
> 
> 
> ok, thanks. Btw do u happen to know any tutorials u would recommend to someone trying to learn stuff about security and/or hacking

* Security Engineering (Third Edition) (Ross Anderson) - https://www.cl.cam.ac.uk/~rja14/book.html
* Information Warfare (Second Edition) (Winn Schwartau)  - https://www.amazon.com/Information-Warfare-Winn-Schwartau-ebook/dp/B00428LB4U
* Hacking Exposed (series) - https://www.amazon.com/Hacking-Exposed-7-Stuart-McClure/dp/0071780289

**Comment by gwillcox-r7** [comment]
Closing this issue as the question has been answered by @dwelch-r7.
