### ISSUE TITLE
Services search does not respect current workspace

### ISSUE THREAD

**Issue by rtpt-lucasvater** [rapid7/metasploit-framework#14119]
When working with different workspaces inside the msfconsole, usually using the `services` command limits the results to the current workspace as expected. This is not the case with the `-S` parameter used for search. Instead matches in all workspaces are returned.

## Steps to reproduce

Create two workspaces with different services and then do a service search:

1. Open `msfconsole` and connect a database
2. `hosts -a 127.0.0.1`
3. `services -a -s default_service -p 1234 127.0.0.1`
4. `workspace -a test`
5. `hosts -a 127.0.0.2`
6. `services -a -s test_service -p 1234 127.0.0.2`
7. `services -S service`

## Were you following a specific guide/tutorial or reading documentation?

No

## Expected behavior

Only one service in the current workspace (test) should be returned:

```
Services
========

host       port  proto  name             state  info
----       ----  -----  ----             -----  ----
127.0.0.2  1234  tcp    test_service     open 
```

## Current behavior

Services in both workspaces are returned:

```
Services
========

host       port  proto  name             state  info
----       ----  -----  ----             -----  ----
127.0.0.1  1234  tcp    default_service  open   
127.0.0.2  1234  tcp    test_service     open
```

### Metasploit version

6.0.5-dev-6a011fe1ee

**Comment by adamgalway-r7** [comment]
Verified
