### ISSUE TITLE
msfconsole doesn't show the interpreter after session opens

### ISSUE THREAD

**Issue by ebrahimkarimi** [rapid7/metasploit-framework#14114]
![metasploit interpreter doesn't show up](https://user-images.githubusercontent.com/22417241/92659366-7a49c200-f30d-11ea-8a3f-e7d8f6813e8a.jpg)
after session established we expect to have the shell to command the connection but it hangs!
msfconsole --version
5.0.99-dev and also tried latest version yet on kali 2020.3 which is 5.0.101-dev
still the same!

**Comment by GetRektBoy724** [comment]
need more information please...
can you give me the last 1k line of ~/.msf4/logs/framework.log ???
what operating system is your victim running?
and the last question...WHY DO YOU USE generic/shell_reverse_tcp

**Comment by GetRektBoy724** [comment]
and also your actions were wrong

**Comment by GetRektBoy724** [comment]
you should type "use multi/handler" first
and type your variables like lhost,lport,and payload
but you dont even choose a payload...you use a default payload

**Comment by timwr** [comment]
@ebrahimkarimi you'll need to provide more information, such as how you generated the payload.
You may also need to do `set payload ....` before running the module (unless you're actually expecting a generic shell session).

**Comment by ebrahimkarimi** [comment]
i'm so sorry  @GetRektBoy724 abd @timwr for late response i don't know why didn't i get notified!
so the target os is Android which is my phone with Android 9
and i did set the payload this time but nothing changes.
![Screenshot_2020-09-25_04-30-34](https://user-images.githubusercontent.com/22417241/94251800-b0c83500-fee8-11ea-9d9b-2376e3f8d4c6.png)
and here is the log file you asked for
[framework.log](https://github.com/rapid7/metasploit-framework/files/5281909/framework.log)

**Comment by timwr** [comment]
@ebrahimkarimi how are you generating the payload? msfvenom? Can you show the command you use?
`set LHOST 0.0.0.0` is most likely the problem. You need to set LHOST to the same host/ip you use when you create the payload.

**Comment by ebrahimkarimi** [comment]
> @ebrahimkarimi how are you generating the payload? msfvenom? Can you show the command you use?
> `set LHOST 0.0.0.0` is most likely the problem. You need to set LHOST to the same host/ip you use when you create the payload. 
> 
> 

i use msfvenom to generate it and lhost 0.0.0.0 is not a problem cause i use ngrok and i open the required port in firewalld and also ive done all of these before!

**Comment by timwr** [comment]
`set LHOST 0.0.0.0` is a problem. You need to set it otherwise you can't interact with the payload after it stages which is probably what you're seeing here.
You can use `set ReverseListenerBindAddress 127.0.0.1` to ensure it works with ngrok.
Try set LHOST to the LHOST you used in msfvenom, I think it will solve this problem.

**Comment by ebrahimkarimi** [comment]
I've set LHOST to 0.0.0.0 and it works if it wasn't working, it wouldn't open the session at the first place

**Comment by GetRektBoy724** [comment]
so actually......
what is your problem???
is the connection died after making the session???
You already get the meterpreter.....whats the problem??
do you have new problem??
please tell me... :)
