### ISSUE TITLE
Nodejs Meterpreter (Revive not duplicate)

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#14116]
I just Want To Revive This #9494 
PLEASE DONT CLOSE

**Comment by OJ** [comment]
I'm closing this, just like the last time, because this doesn't add anything beyond what is listed in #9494.

Please can you stop opening new issues that don't add any value. Thanks.

**Comment by GetRektBoy724** [comment]
ok ok
