### ISSUE TITLE
# Chinese file name recursive download error

### ISSUE THREAD

**Issue by sunlewuyou** [rapid7/metasploit-framework#14128]
# Chinese file name recursive download error 
![image](https://user-images.githubusercontent.com/19728435/93001217-1d921580-f560-11ea-9502-adc5065a8668.png)

_Originally posted by @sunlewuyou in https://github.com/rapid7/metasploit-framework/issues/13798#issuecomment-691520263_

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/93001344-f0923280-f560-11ea-91e9-18a285cae566.png)

**Comment by sunlewuyou** [comment]
## logs 
```
[09/13/2020 14:39:52] [e(0)] meterpreter: Error running command download: Encoding::CompatibilityError incompatible character encodings: UTF-8 and ASCII-8BIT
[09/13/2020 14:39:52] [d(0)] meterpreter: Call stack:
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:540:in `block (2 levels) in cmd_download'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:321:in `block in download'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:282:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:282:in `download'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:539:in `block in cmd_download'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:491:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb:491:in `cmd_download'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:153:in `run'
/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:583:in `_interact'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/interactive.rb:51:in `interact'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/core.rb:1569:in `cmd_sessions'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:158:in `run'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

**Comment by bcoles** [comment]
Thanks for the detailed information. This does look like a bug.

Although I wasn't able to reproduce it on a Kali test system.

```
meterpreter > download 贏得*
[*] mirroring  : .\贏得 -> ./贏得
[*] downloading: .\贏得\贏得.exe -> ./贏得/贏得.exe
[*] download   : .\贏得\贏得.exe -> ./贏得/贏得.exe
[*] downloading: .\贏得\贏得.txt -> ./贏得/贏得.txt
[*] download   : .\贏得\贏得.txt -> ./贏得/贏得.txt
[*] mirrored   : .\贏得 -> ./贏得
meterpreter > ls -la 贏得
Listing: 贏得
===============

Mode              Size     Type  Last modified              Name
----              ----     ----  -------------              ----
100777/rwxrwxrwx  1449008  fil   2020-09-13 09:55:21 -0400  贏得.exe
100666/rw-rw-rw-  1449008  fil   2020-09-13 10:00:31 -0400  贏得.txt

meterpreter > 
```

```
meterpreter > cd 贏得
meterpreter > download *
[*] downloading: .\贏得.exe -> ./贏得.exe
[*] download   : .\贏得.exe -> ./贏得.exe
[*] downloading: .\贏得.txt -> ./贏得.txt
[*] download   : .\贏得.txt -> ./贏得.txt
meterpreter > 
```

**Comment by sunlewuyou** [comment]
> Thanks for the detailed information. This does look like a bug.
> 
> Although I wasn't able to reproduce it on a Kali test system.
> 
> ```
> meterpreter > download 贏得*
> [*] mirroring  : .\贏得 -> ./贏得
> [*] downloading: .\贏得\贏得.exe -> ./贏得/贏得.exe
> [*] download   : .\贏得\贏得.exe -> ./贏得/贏得.exe
> [*] downloading: .\贏得\贏得.txt -> ./贏得/贏得.txt
> [*] download   : .\贏得\贏得.txt -> ./贏得/贏得.txt
> [*] mirrored   : .\贏得 -> ./贏得
> meterpreter > ls -la 贏得
> Listing: 贏得
> ===============
> 
> Mode              Size     Type  Last modified              Name
> ----              ----     ----  -------------              ----
> 100777/rwxrwxrwx  1449008  fil   2020-09-13 09:55:21 -0400  贏得.exe
> 100666/rw-rw-rw-  1449008  fil   2020-09-13 10:00:31 -0400  贏得.txt
> 
> meterpreter > 
> ```
> 
> ```
> meterpreter > cd 贏得
> meterpreter > download *
> [*] downloading: .\贏得.exe -> ./贏得.exe
> [*] download   : .\贏得.exe -> ./贏得.exe
> [*] downloading: .\贏得.txt -> ./贏得.txt
> [*] download   : .\贏得.txt -> ./贏得.txt
> meterpreter > 
> ```
> 

Thank you for your attention and reply! I look forward to your help to solve this problem. Do I need to provide other logs?

**Comment by sunlewuyou** [comment]
@bcoles This problem seems to be an exception caused by the database.
![SQL_UTF8](https://user-images.githubusercontent.com/19728435/93456483-54757c00-f910-11ea-91d1-962eff38091c.png)

**Comment by gwillcox-r7** [comment]
Hmm this is an interesting case as it appears to only happen under certain conditions. @sunlewuyou here are some tests I did which show that using `*` almost always seems to cause an error but supplying the file name itself doesn't seem to cause an error and one can still download the file normally:

```
meterpreter > pwd
C:\Users\test\Desktop\艾弗
meterpreter > download 艾尺.txt
[*] Downloading: 艾尺.txt -> 艾尺.txt
[*] download   : 艾尺.txt -> 艾尺.txt
meterpreter > download *
[*] downloading: .\艾尺.txt -> ./艾尺.txt
[-] Error running command download: Encoding::CompatibilityError incompatible character encodings: UTF-8 and ASCII-8BIT
meterpreter > download 艾*
[*] downloading: .\艾尺.txt -> ./艾尺.txt
[-] Error running command download: Encoding::CompatibilityError incompatible character encodings: UTF-8 and ASCII-8BIT
meterpreter > download 艾弗.txt
[*] Downloading: 艾弗.txt -> 艾弗.txt
[*] download   : 艾弗.txt -> 艾弗.txt
meterpreter > 
```

**Comment by sunlewuyou** [comment]
@gwillcox-r7 
Yes, it is guessed that it is a database-related problem, and the error will not be triggered after disconnecting the database connection.

**Comment by gwillcox-r7** [comment]
@sunlewuyou Hmm interesting that this is only occurring with the database connected, as that does help narrow down the root cause of this bug a bit more. Will have to do some more testing when I have the chance to take a look at this again. Ultimately though this may be a bit more complex of an issue than a simple encoding change from what I've been gathering r.e talks with my colleagues as modules seems to mix and match encoding as they please, so we will need to be careful not to cause any unintended side effects.
