### ISSUE TITLE
HELP-PLZ--msfconsole unable to load after updating and upgrading kali on 11 September.2020,see error text below/screenshot

### ISSUE THREAD

**Issue by drake22-sv** [rapid7/metasploit-framework#14133]
i'm currently
![Screenshot (167)](https://user-images.githubusercontent.com/69860498/93108264-7ff72d00-f6aa-11ea-9563-95abfab25dd8.png)

 stucked and need some assistance, can't find answer anywhere!.

 msfconsole
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:84:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)
	from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:58:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems.rb:1241:in `require'
	from /usr/lib/ruby/2.3.0/rubygems.rb:1241:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

**Comment by GetRektBoy724** [comment]
heyyy change the label to bug pls

**Comment by GetRektBoy724** [comment]
what kali version do you run??

**Comment by GetRektBoy724** [comment]
and can you provide the whole file of ~/.msf4/framework.log ???

**Comment by adfoster-r7** [comment]
It looks like you might be running an old version of Ruby or Kali.

What is the output of:

```
ruby -v
```

And:

```
lsb_release -a
```

**Comment by GetRektBoy724** [comment]
ahh thankfully god there is a pro in here :)

**Comment by GetRektBoy724** [comment]
if you want to update metasploit framework please use from apt
