### ISSUE TITLE
I Try To Create An Encoder Module And Can You Check At My Code ???

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#14148]
I Try To Make An Encoder
It is a base64 encoder with AMSI bypass code included 
and anybody who see this question...Can You Check At My Code ???
Code Link : https://pastebin.com/raw/qkTz69UU
Any Answer Is Appreciated :)

**Comment by timwr** [comment]
@GetRektBoy724 I'm not sure what you're trying to achieve but this is an issue tracker for issues, and it's not really the place for technical support.
I'm happy to discuss this on Slack or irc, if you're trying to bypass AMSI I suspect this technique may still work with minor tweaks: https://github.com/rapid7/metasploit-framework/pull/12724
