### ISSUE TITLE
Metasploit NET HELPMSG error

### ISSUE THREAD

**Issue by Shahazad8317** [rapid7/metasploit-framework#14165]
Hi all 

I have facing this issue please help me

![IMG_20200921_224311_451.png](https://user-images.githubusercontent.com/64717119/93798836-ee645e00-fc5b-11ea-89b2-82aec2ba7d6a.png)

**Comment by adfoster-r7** [comment]
It looks like your anti virus may be interfering the installer.

I would recommend using a Kali virtual machine to use Metasploit Framework:

https://www.offensive-security.com/kali-linux-vm-vmware-virtualbox-image-download/
