### ISSUE TITLE
metasploit erro NET HELPMSG 

### ISSUE THREAD

**Issue by Shahazad8317** [rapid7/metasploit-framework#14164]
Dear Sir/Madam  
         
                 I have facing some issue on metasploit on my Windows 10 Laptop 

![Screenshot (16)](https://user-images.githubusercontent.com/64717119/93785899-41361980-fc4c-11ea-9984-55e0935cbe48.png)

**Comment by GetRektBoy724** [comment]
hmmm sorry to say this but metasploit framework didnt work well on windows
try to install an kali virtualbox,that would be nicer tho
