### ISSUE TITLE
Username and password of Web service

### ISSUE THREAD

**Issue by browncrane** [rapid7/metasploit-framework#14182]
## Summary

Where to find the user password? How to create or reset one?

## Relevant information

When going through https://github.com/rapid7/metasploit-framework/wiki/Metasploit-Web-Service#accessing-the-api

, by visiting `https://<address>:<port>/api/v1/auth/account ` the server provide a page, and suggest me to visit 
`https://<address>:<port>/api/v1/auth/login` but I don't remember the user name and password. Don't know how to keep going. Since  most APIs need a bearer token.

**Comment by cn-kali-team** [comment]
在你初始化数据库的时候，也就是执行msfdb reinit之后会让你设置web的用户名和密码的，你可能当时没注意到。

When you initialize the database, that is, after executing msfdb reinit, you will set the user name and password of the web, which you may not have noticed at that time.

**Comment by browncrane** [comment]
我注意到有这个步骤，并且当时选了随机密码。现在有办法找回那个随机密码吗？或者需要删除重来一遍？

I noticed this step and chose a random password at the time. Is there a way to retrieve that random password now? Or need to delete and do it again?

**Comment by jmartin-r7** [comment]
The random password will be stored in you local user config file found in `~/.msf4/config`

An example from a tests system.
```
$ cat ~/.msf4/config
[framework/database]
default_db=local-https-data-service

[framework/database/local-https-data-service]
url=https://localhost:5443
cert=/home/vagrant/.msf4/msf-ws-cert.pem
skip_verify=true
api_token=a93e5011db5ac0157fb6540346a2adb5f6d36db538229c095125c50721df34ed4b87ca448ac70bea
```
