### ISSUE TITLE
Sum hash is diferent on ubuntu 20.04

### ISSUE THREAD

**Issue by Saeron** [rapid7/metasploit-framework#14196]
Err:18 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid/main amd64 Packages
  La suma hash difiere
  Hashes of expected file:
   - Filesize:418 [weak]
   - SHA256:c5f4b4d2957c2e626d2d04d5ec04f26719c2d5d7198599b8ff15a890f7004117
   - SHA1:27b836cdca1de5358b45228e650452be4e274437 [weak]
   - MD5Sum:882e98ea687652c30ac8816b0733076d [weak]
  Hashes of received file:
   - SHA256:6fa78286eddf1c1c45a863a454cb55b627cf4070035c9b3841153b2c41cb24b8
   - SHA1:adb3cff82432d570c4273f571042cd1d2d813cc2 [weak]
   - MD5Sum:b560d1d30ba20ef54b44187c51fb9685 [weak]
   - Filesize:418 [weak]
  Last modification reported: Mon, 28 Sep 2020 11:03:32 +0000
  Release file created at: Tue, 29 Sep 2020 11:04:27 +0000

**Comment by GetRektBoy724** [comment]
need more information pls
what os are you running ???

**Comment by Saeron** [comment]
> need more information pls
> what os are you running ???

I told you in the title ubuntu 20.04, what more info do you need?

**Comment by GetRektBoy724** [comment]
is better if you download the metasploit installer that located in this github
you can follow this tutorial https://computingforgeeks.com/how-to-install-metasploit-framework-on-ubuntu-18-04-debian-9/

**Comment by GetRektBoy724** [comment]
and also its a lot more better if you have seperate OS for hacking only

**Comment by Saeron** [comment]
Thank you for the warning, but belived or not I am not hacker, I am triying to become web app developer and I was interested to see the more common fails. However I dind't install this update and I already remove the repo. I will try to install fron github if I have more time to learn. Thanks for everything I just want to warn people because I know if hash is diferent it can be dangerous, bur other people doesn't.

**Comment by GetRektBoy724** [comment]
ohh ok

**Comment by GetRektBoy724** [comment]
you can close this issue now

**Comment by timwr** [comment]
@GetRektBoy724 can you please make sure your future comments are both useful and accurate before posting them?
