### ISSUE TITLE
msfdb start (.msf4) need postgres start and stop ?

### ISSUE THREAD

**Issue by panpansh** [rapid7/metasploit-framework#14310]
WSL Debian => Windows 10
###### Web Service OK.
-----------------------------
restarting the system.
$ ./msfdb start
```
Starting database at /home/k7/.msf4/db...failed
2020-10-25 12:14:44.771 CET [125] LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
MSF web service PID file found, but no active process running as PID 820
Deleting MSF web service PID file /home/k7/.msf4/msf-ws.pid
Attempting to start MSF web service...failed
[!] MSF web service appears to be started, but may not operate as expected.

Please see /home/k7/.msf4/logs/msf-ws.log for additional details.
```
$ cat /home/k7/.msf4/logs/msf-ws.log
```
[...]
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
2020-10-25 12:16:38 - PG::ConnectionBad - could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5433?
[...]
```
$ sudo service postgresql start && sudo service postgresql stop
```
[ ok ] Starting PostgreSQL 11 database server: main.
[ ok ] Stopping PostgreSQL 11 database server: main.
```
$ ./msfdb start
```
Starting database at /home/k7/.msf4/db...success
Attempting to start MSF web service...success
MSF web service started and online
```

Would someone kindly explain to me please ?

**Comment by smcintyre-r7** [comment]
Yeah so Metasploit uses a database for it's persistent data storage that among other things allows users to track useful information that's gathered while using Metasploit. This would include things like identified systems, vulnerabilities and gathered credentials. 

That data back end used by Metasploit is the PostgreSQL database. There's a web service backend, but that's a layer on top of PostgreSQL. You can find more information on this in the wiki under the [msfdb: Database Features](https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit) page.

**Comment by panpansh** [comment]
@smcconnell-r7 thank you for taking the time to answer me and explain how it works.
However I don't understand why I need **start && stop** postgres before msfdb start.
Wishing you a good weekend.
