### ISSUE TITLE
How to save metasploit module outputs to text file

### ISSUE THREAD

**Issue by prince911** [rapid7/metasploit-framework#14327]
if you are use auxiliary/scanner and you want save outputs to text file

wahit is command ??

**Comment by bcoles** [comment]
You can spool console output to file with the `spool` command.

```
msf6 > help spool
Usage: spool <off>|<filename>

Example:
  spool /tmp/console.log

msf6 > 
```

Many modules will automatically store retrieved loot to your `~/.msf/loot` directory too.

**Comment by prince911** [comment]
i don have path console.log in /tmp 
i use kali linux

**Comment by smcintyre-r7** [comment]
The spool command will create that file for you so it doesn't need to exist. If you want the logs placed somewhere else just change the argument to where you'd like them.

**Comment by IkerSolozabal** [comment]
Use command

`spool  [file]`

Run commands, and when finished just run

`spool exit`

Once you stopped, you can check on your file the output

**Comment by hikiko999** [comment]
> Use command
> 
> `spool [file]`
> 
> Run commands, and when finished just run
> 
> `spool exit`
> 
> Once you stopped, you can check on your file the output

* for future readers: correction do spool **off** not spool **exit** - i was doing this for a while wondering why it was creating a spool file named exit, you just have to spool off to disable it
