### ISSUE TITLE
incorrect handling on non latin words in meterpreter

### ISSUE THREAD

**Issue by ilyapashuk** [rapid7/metasploit-framework#14320]
## Steps to reproduce

1. connect to windows machine with help of meterpreter
2. go to some dir with cyrilic file names and call ls

## Expected behavior
sea filenames in console

## Current behavior

sea some amount of encoded data like $U$ something
if use it in cd command instead of real name all works.

### Metasploit version

6.0.12

## Additional Information

host os is win10 1803

**Comment by timwr** [comment]
Can you provide more information?
What kind of meterpreter session and what payload (windows? python? java?)
What was the exact file name? 
Can you paste the entire console output so we can reproduce it? If not can you provide screenshots (including the output of `sessions -v`)?

**Comment by ilyapashuk** [comment]
meterpreter is windows/meterpreter/reverse_tcp
![meter](https://user-images.githubusercontent.com/40538919/97680844-636f5280-1aa8-11eb-9016-07c8c7162980.png)

and real names for this dirs "админ" and "все пользователи", I don't know about case and ordering.

**Comment by dwelch-r7** [comment]
@ilyapashuk I don't know if it just looks that way for me or not but that image is blank, just a black screen

**Comment by agalway-r7** [comment]
> @ilyapashuk I don't know if it just looks that way for me or not but that image is blank, just a black screen

Same. @ilyapashuk could you paste the console output and the output of `debug` (baring in mind to remove any sensitive info), so we can look into this?

**Comment by gwillcox-r7** [comment]
Due to a lack of an update on this in 3 weeks, I am going to attic this for the moment. @ilyapashuk if you do get the chance to update this issue with the required information, please feel free to do so and then ping us and we can reopen this issue once the required information is added.
