### ISSUE TITLE
formulae.brew.sh/api/cask/metasploit.json URL throws 404. 

### ISSUE THREAD

**Issue by TheseArmsRSnakes** [rapid7/metasploit-framework#14376]
Hi, if you're reading this you're awesome. I'm lazy and would prefer it if brew managed my metasploit install. However metasploit doesn't want to cooperate.

```
hostname % brew install metasploit
Updating Homebrew...
==> Downloading https://osx.metasploit.com/metasploit-framework-6.0.11+202010121
##O=#  #                                                                      
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.0.11+20201012102846-1rapid7-1.pkg

```

Manually navigating to 
`https://formulae.brew.sh/api/cask/metasploit.json` then provided URL, `https://osx.metasploit.com/metasploit-framework-6.0.11+20201012102846-1rapid7-1.pkg` renders `An error occurred while processing your request. Reference #132.247519b8.1605034736.2a5ea5c `

Thanks!

**Comment by adfoster-r7** [comment]
Looks like the version needs to be updated within the brew cask repository:
https://github.com/Homebrew/homebrew-cask/blame/d5ad3c4d939d4820cb52f3c872111c829bb31f92/Casks/metasploit.rb#L2

To use the latest release:
https://osx.metasploit.com/

**Comment by adfoster-r7** [comment]
https://github.com/Homebrew/homebrew-cask/pull/92584

**Comment by adfoster-r7** [comment]
We'll most likely need a long term solution for this, as this will become an issue again in the future
