### ISSUE TITLE
auxiliary/analyze/apply_pot throwing NameError

### ISSUE THREAD

**Issue by grese** [rapid7/metasploit-framework#14380]
# auxiliary/analyze/apply_pot throwing NameError

## Description

The _auxiliary/analyze/apply_pot_ module throws a _NameError_ saying `undefined local variable or method 'new_john_cracker'`, which points to line 53 of _apply_pot.rb_. The same error occurs no matter what the options are set to.

## Steps to reproduce

1. Launch msfconsole
2. msf6 > `auxiliary/analyze/apply_pot`
3. Configure some options (optional)
4. msf6 > `run`

## Expected behavior

The module should use the .pot file to crack password hashes in the creds database.

## Current behavior

The error can be seen in the screenshot below.

![image](https://user-images.githubusercontent.com/4702431/98776100-30c83280-23a3-11eb-9666-e382f9be2b9e.png)

### Metasploit version

Metasploit Framework Version: 6.0.15-dev
OS: Kali 2020.4

###  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[analyze/apply_pot]
WORKSPACE=
VERBOSE=false
CONFIG=
CRACKER_PATH=
FORK=1
POT=
DeleteTempFiles=true
OptimizeKernel=true
ShowCommand=true
loglevel=3

[framework/ui/console]
ActiveModule=auxiliary/analyze/apply_pot
```

</details>

###  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
707    use auxiliary/analyze/apply_pot
708    run
709    set loglevel 3
710    debug
```

</details>

###  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[11/11/2020 01:36:25] [e(0)] core: Auxiliary failed - NameError undefined local variable or method `new_john_cracker' for #<Msf::Modules::Auxiliary__Analyze__Apply_pot::MetasploitModule:0x0000557db1be3c80>
```

</details>

### Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

###  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[11/11/2020 01:36:25] [e(0)] core: Auxiliary failed - NameError undefined local variable or method `new_john_cracker' for #<Msf::Modules::Auxiliary__Analyze__Apply_pot::MetasploitModule:0x0000557db1be3c80>
```

</details>

###  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

###  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.15-dev
Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

**Comment by bcoles** [comment]
@h00die `new_john_cracker` is probably meant to be `new_password_cracker`.

```diff
diff --git a/modules/auxiliary/analyze/apply_pot.rb b/modules/auxiliary/analyze/apply_pot.rb
index 6cdb835a51..cd556284c7 100644
--- a/modules/auxiliary/analyze/apply_pot.rb
+++ b/modules/auxiliary/analyze/apply_pot.rb
@@ -50,7 +50,7 @@ class MetasploitModule < Msf::Auxiliary
   end
 
   def run
-    cracker = new_john_cracker
+    cracker = new_password_cracker
 
     lookups = []
 
```

Although there may be more issues beyond this.

**Comment by grese** [comment]
> @h00die `new_john_cracker` is probably meant to be `new_password_cracker`.
> 
> ```diff
> diff --git a/modules/auxiliary/analyze/apply_pot.rb b/modules/auxiliary/analyze/apply_pot.rb
> index 6cdb835a51..cd556284c7 100644
> --- a/modules/auxiliary/analyze/apply_pot.rb
> +++ b/modules/auxiliary/analyze/apply_pot.rb
> @@ -50,7 +50,7 @@ class MetasploitModule < Msf::Auxiliary
>    end
>  
>    def run
> -    cracker = new_john_cracker
> +    cracker = new_password_cracker
>  
>      lookups = []
>  
> ```
> 
> Although there may be more issues beyond this.

Yeah, I tried that... It appears to need a little more work than that :)

**Comment by h00die** [comment]
looks like I overlooked this file when adding in the hashcat functionality, looking into it now

**Comment by grese** [comment]
@h00die, @smcintyre-r7 - Thanks for the speedy turnaround, guys! Awesome :)
