### ISSUE TITLE
Unable To Upload My Persistance Script In My Device

### ISSUE THREAD

**Issue by ifunanya55** [rapid7/metasploit-framework#14385]
I am able to access my victim's device and sdcard right now which is my device, but I want to create it persistent. I am currently on msf6 on kali linux from microsoft store. Anytime I run the upload command, it throws this error
[-] 4 : Operation failed: 1

I have already created the .sh script and not able to upload it to my victims device. And I am also sure about its directory.

**Comment by adfoster-r7** [comment]
@ifunanya55 Does this issue exist with Metasploit 5.0.101?

**Comment by ifunanya55** [comment]
I don't know if it exists with msf5 since am not able to download previous versions of metasploit right

> @ifunanya55 Does this issue exist with Metasploit 5.0.101?

**Comment by just-hack** [comment]
> I am able to access my victim's device and sdcard right now which is my device, but I want to create it persistent. I am currently on msf6 on kali linux from microsoft store. Anytime I run the upload command, it throws this error
> [-] 4 : Operation failed: 1
> 
> I have already created the .sh script and not able to upload it to my victims device. And I am also sure about its directory.

bro have you solve this issue ?? even i am also getting same > [-] 4 : Operation failed: 1 error in upload, play and download command in meterpreter. 

if you get is bro just ping me on whatsApp +917977821437

**Comment by OmiceyO** [comment]
Same thing for me. No way to upload or download anything.

**Comment by ifunanya55** [comment]
> @ifunanya55 Does this issue exist with Metasploit 5.0.101?

I don't know if it exist with msf5. I myself is also trying to download msf5 to test it out.

**Comment by ifunanya55** [comment]
> > I am able to access my victim's device and sdcard right now which is my device, but I want to create it persistent. I am currently on msf6 on kali linux from microsoft store. Anytime I run the upload command, it throws this error
> > [-] 4 : Operation failed: 1
> > I have already created the .sh script and not able to upload it to my victims device. And I am also sure about its directory.
> 
> bro have you solve this issue ?? even i am also getting same > [-] 4 : Operation failed: 1 error in upload, play and download command in meterpreter.
> 
> if you get it bro just ping me on whatsApp +917977821437

I haven't solved it yet :( still don't know how to go about it

**Comment by ifunanya55** [comment]
> Same thing for me. No way to upload or download anything.

Well I think it's a bug and no metasploit official is yet to reply to my post on how to go about it lol

**Comment by dwelch-r7** [comment]
@ifunanya55 Please stop spamming other issues asking for us to look at this one, we have a lot of issues and PRs we need to look at right now with varying priorities.

**Comment by ifunanya55** [comment]
> @ifunanya55 Please stop spamming other issues asking for us to look at this one, we have a lot of issues and PRs we need to look at right now with varying priorities.

did it to get attention, and I have gotten one now thanks. Been 14 days now 👍
