### ISSUE TITLE
msfconsole ignores EICAR canary until long after its useful

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#14415]
A bunch of users have reported issues with a missing `.dex` file causing Metasploit `msfconsole` to fail to start. Instead `msfconsole` dies with a long backtrace.

Here's one example issue I can be bothered to track down (there are many):

* https://github.com/rapid7/metasploit-framework/issues/13134#issuecomment-651786446

This issue is due to anti-virus eating the `.dex` file. In theory, corruption of Metasploit files by anti-virus was meant to have been detected by the `is_eicar_corrupted?` canary.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/util/exe.rb#L2179-L2196

(Also, this `is_eicar_corrupted?` method is poorly written. It checks if the file exists twice.)

The problem is that this method is called here:

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/core/framework.rb#L42

But the canary warning is ignored. This proves to be fatal.

A few lines later `module_manager` is loaded. The crash due to missing `.dex` file occurs somewhere in here while iterating through module paths.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/core/framework.rb#L58

Some time latter, `cmd_banner` gets called to display the banner, version and help tips. Only then does `msfconsole` bother to check if the canary is happy.

https://github.com/rapid7/metasploit-framework/blob/025950ec0b8454da30b040f9a9798e1dd17d6705/lib/msf/ui/console/command_dispatcher/core.rb#L258-L265

This sequence of events needs to be reworked.

**Comment by dwelch-r7** [comment]
I believe the main problem here has been unintentionally fixed by landing the zeitwerk PR #14202 
But I'm still going to address the rest of the issues here
