### ISSUE TITLE
Erro de upload do Metasploit: [-] 4: Falha na operação: 1

### ISSUE THREAD

**Issue by FelipeSp666** [rapid7/metasploit-framework#14436]
alguem sabe como corrigir este erro ao tentar fazer upload teste.sh da persistencia para o android da vitima ?

PRINT:
 
https://abre.ai/4operationfailed1

**Comment by bcoles** [comment]
You probably do not have permission to upload to the selected directory. You can change directory with the `cd` command.

* `cd /storage/emulated/0`
* `cd /sdcard/android/data`
* `cd /data`

**Comment by FelipeSp666** [comment]
não, funcou esse metodo...
