### ISSUE TITLE
No session opened , Keeps constant on ( Started reverse TCP handler on 192.168.x.xx:4444)

### ISSUE THREAD

**Issue by jayakumar23** [rapid7/metasploit-framework#14434]
Important Notes
1- The goal is to penetration test on the victim's Android phone via payload

2- Victim's phone = Is my phone (I'm testing myself)

3- I use port 4444

Create a payload using TheFatRat 

![PicsArt_11-26-05 48 29](https://user-images.githubusercontent.com/74779160/100350742-53e41a80-3010-11eb-8703-14a78b7b14d2.jpg)

When i install a payload i created using fatrat nothing was happen im struggling for past 2 day anyone one plzz help me

**Comment by h00die** [comment]
did you open the payload after installing it?
also, w/o knowing how the payload was generated (options, etc) it's hard to help.

**Comment by jayakumar23** [comment]
> did you open the payload after installing it?
> also, w/o knowing how the payload was generated (options, etc) it's hard to help.

Yes im open the payload but nothing happen in there

**Comment by h00die** [comment]
> w/o knowing how the payload was generated (options, etc) it's hard to help.

**Comment by jayakumar23** [comment]
![IMG_20201127_120438](https://user-images.githubusercontent.com/74779160/100426176-76c90a00-30b6-11eb-89d3-25eb04304c66.jpg)
![PicsArt_11-27-12 00 46](https://user-images.githubusercontent.com/74779160/100426224-847e8f80-30b6-11eb-8799-f0f467ef2dcf.png)

Payload created using Fatra

![Screenshot 2020-11-27 00:38:59](https://user-images.githubusercontent.com/74779160/100426310-a5df7b80-30b6-11eb-93c5-00f34fd695a8.png)

Backdooring orginal apk

![PicsArt_11-27-12 01 35](https://user-images.githubusercontent.com/74779160/100426497-f656d900-30b6-11eb-80ab-2ae491150b9c.jpg)
![PicsArt_11-27-12 02 19](https://user-images.githubusercontent.com/74779160/100426502-f8209c80-30b6-11eb-8760-a985835c3eb2.jpg)
![Screenshot 2020-11-27 00:49:22](https://user-images.githubusercontent.com/74779160/100426506-f8b93300-30b6-11eb-84d6-2f5b569e817b.png)

When i run the msfconsole 

![PicsArt_11-27-12 03 24](https://user-images.githubusercontent.com/74779160/100426548-0d95c680-30b7-11eb-9f46-6d67963bfbc5.jpg)



> > w/o knowing how the payload was generated (options, etc) it's hard to help.

**Comment by jayakumar23** [comment]
> > w/o knowing how the payload was generated (options, etc) it's hard to help.

![Screenshot_2020-11-27-11-35-52-39](https://user-images.githubusercontent.com/74779160/100426724-5d748d80-30b7-11eb-86be-b3f97fe62298.jpg)
 
Apk install in my Mobile

**Comment by bcoles** [comment]
It looks like you're running Metasploit inside a NATed virtual machine with an IP address in the `192.168.x.x` range.

The NAT environment is shared between the host operating system and the virtual machines. You phone will not be on this network unless it is connected via a wireless connection to an access point inside the NATed environment.

You will need to change the virtual machine network adapter from NAT to Bridged. You will then need to regenerate the payload with the correct IP address for the bridged interface.

**Comment by jayakumar23** [comment]
> It looks like you're running Metasploit inside a NATed virtual machine with an IP address in the `192.168.x.x` range.
> 
> The NAT environment is shared between the host operating system and the virtual machines. You phone will not be on this network unless it is connected via a wireless connection to an access point inside the NATed environment.
> 
> You will need to change the virtual machine network adapter from NAT to Bridged. You will then need to regenerate the payload with the correct IP address for the bridged interface.

I'm can't understand what should i need to do plz help me iam struggling for past 5 days

**Comment by bcoles** [comment]
![image](https://user-images.githubusercontent.com/434827/100443667-3ee5b500-30fe-11eb-8363-2240bb849405.png)

**Comment by jayakumar23** [comment]
> It looks like you're running Metasploit inside a NATed virtual machine with an IP address in the `192.168.x.x` range.
> 
> The NAT environment is shared between the host operating system and the virtual machines. You phone will not be on this network unless it is connected via a wireless connection to an access point inside the NATed environment.
> 
> You will need to change the virtual machine network adapter from NAT to Bridged. You will then need to regenerate the payload with the correct IP address for the bridged interface.


![IMG_20201127_175607](https://user-images.githubusercontent.com/74779160/100449589-33809280-30da-11eb-977c-82e03c19f4bd.jpg)


By using bridged i have created a new payload using a correct ip 


![IMG_20201127_175537](https://user-images.githubusercontent.com/74779160/100449711-63c83100-30da-11eb-866a-6107cb448d88.jpg)


When i run the msfconsole still nothing happen .. 

I have installed a new payload into my mobile and opened but no session are open plz help me sir

**Comment by bcoles** [comment]
Make sure the android device can access `192.168.1.2`. You could test connecting to `192.168.1.2:4444` with a web browser on the device.

> By using bridged i have created a new payload using a correct ip

Make sure you're using the correct IP address and port. Your previous screenshots show you were using port `8080` for the payload, but now you're using `4444` for the listener.

This issue is most likely with your setup.

The Metasploit issue tracker is for tracking issues with Metasploit.

Perhaps someone on IRC or Slack can help you out with your question:

* https://www.metasploit.com/help

**Comment by jayakumar23** [comment]
> Make sure the android device can access `192.168.1.2`. You could test connecting to `192.168.1.2:4444` with a web browser on the device.
> 
> > By using bridged i have created a new payload using a correct ip
> 
> Make sure you're using the correct IP address and port. Your previous screenshots show you were using port `8080` for the payload, but now you're using `4444` for the listener.
> 
> This issue is most likely with your setup.
> 
> The Metasploit issue tracker is for tracking issues with Metasploit.
> 
> Perhaps someone on IRC or Slack can help you out with your question:
> 
> * https://www.metasploit.com/help

Sorry for disturbing you but what Port i need to use and how to find my port

**Comment by bcoles** [comment]
> what Port i need to use and how to find my port

The `lport` you set when creating the payload must be the same as the `lport` you use for `multi/handler`.

**Comment by jayakumar23** [comment]
> > what Port i need to use and how to find my port
> 
> The `lport` you set when creating the payload must be the same as the `lport` you use 

> > what Port i need to use and how to find my port
> 
> The `lport` you set when creating the payload must be the same as the `lport` you use for `multi/handler`.

I have used a same lport but iam not connect to the device

**Comment by timwr** [comment]
@jayakumar23 this appears to be a networking problem rather than a bug in metasploit. I would suggest you first practice by hosting a simple website (you can use `python -m SimpleHTTPServer` to host a website from the command line) and ensure you can access it on your Android device. You can also try with `ping`. Some routers/wifi networks don't allow hosts to access each other and are isolated.
If you need more help you can ping me on slack and I'll try walk you through it.

**Comment by Yadhu009** [comment]
The thing is my android phone is not connecting to my payload ipadress when i search ip in webbrowser how can i solve that

**Comment by bcoles** [comment]
> The thing is my android phone is not connecting to my payload ipadress when i search ip in webbrowser how can i solve that

Ensure you're using the correct IP address. Ensure the Android device can route network traffic to the web server hosting the payload. Ensure the web server is running on an accessible network interface and is not blocked by firewall rules.

**Comment by Tushar1144** [comment]
> Important Notes 1- The goal is to penetration test on the victim's Android phone via payload
> 
> 2- Victim's phone = Is my phone (I'm testing myself)
> 
> 3- I use port 4444
> 
> Create a payload using TheFatRat
> 
> ![PicsArt_11-26-05 48 29](https://user-images.githubusercontent.com/74779160/100350742-53e41a80-3010-11eb-8703-14a78b7b14d2.jpg)
> 
> When i install a payload i created using fatrat nothing was happen im struggling for past 2 day anyone one plzz help me

That same problem produced on my Kali machine 
Can you help me

**Comment by bcoles** [comment]
> That same problem produced on my Kali machine
> Can you help me

This issue was closed two years ago. There is insufficient information to reproduce the issue which was extremely vague and lacked technical details.

The original issue appeared to be user error. Multiple solutions were proposed in this thread.

**Comment by Tushar1144** [comment]
After I googled it I found that metasploit requires at least 4gb of ram.  Later when I made virtual box ram 4 GB then metasploit started working fine.

**Comment by GeovannyManga** [comment]
Hola, justo me paso lo mismo del muchacho de las primeras preguntas de este sitio, pero en mi caso tengo wsl kali linux, como puedo hacer que se conecte a red normal en lugar de NAT?

**Comment by w2tchm3n** [comment]
the same happen to me, i don't know how to fix that i have tried everything !

**Comment by VIKRAMXXHH** [comment]
pls help i also face this problem

**Comment by GeovannyManga** [comment]
Al pareceer el problema se debe a que lo tenemos en maquinas virtuales y asi no permite ponerlo como red normal, solo se puede hacer mediante la instalacion del sistema operativo nativo y no maquina virutal, esa es la informacion que tengo, quiza si sea posible pero de momento no veo la forma
