### ISSUE TITLE
Lazy Script installing TOOL issue

### ISSUE THREAD

**Issue by EinsteinJr9** [rapid7/metasploit-framework#14440]
After installing Lazy Script successfully I tried to install one of the available tools, but an error shows up.
chmod : cannot access:
- 'INSTALL.sh'
- 'execute.py'
or shows that the tool was not installed. I'm sure that if I could overpass this problem Lazy script would become one of the most useful Tools!!!

**Comment by bcoles** [comment]
I'm sure Lazy script is a useful tool. Tell the developers I said hi.

**Comment by EinsteinJr9** [comment]
> I'm sure Lazy script is a useful tool. Tell the developers I said hi.

I didn't get why did you close the issue tho ...

**Comment by bcoles** [comment]
> 
> 
> > I'm sure Lazy script is a useful tool. Tell the developers I said hi.
> 
> I didn't get why did you close the issue tho ...

Sir, this is a Wendy's.

Perhaps you were looking for https://github.com/arismelachroinos/lscript
