### ISSUE TITLE
Windows installer: Cannot choose install dir

### ISSUE THREAD

**Issue by Artivain** [rapid7/metasploit-framework#14457]
## Steps to reproduce

I downloaded the latest Nightly installer from GitHub, and when I try to install it, it asks for install path, I choose C:/metasploit.

I tried 2 times, both installed in D:/metasploit-framework.

## Were you following a specific guide/tutorial or reading documentation?

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

## Expected behavior

Install to C:/metasploit

## Current behavior

Install to D:/metasploit-framework

### Metasploit version

metasploit-framework 6.0.19+20201202162704-1rapid7

**Comment by TheOngelma** [comment]
I had the exactly same happen to me. Tried to install it into C:, it ended up on my E: Drive.

Version 6.0.22

**Comment by Reelix** [comment]
This issue has been around for awhile now, unfortunately - Ref: #14071

**Comment by dwelch-r7** [comment]
This is being tracked over here: https://github.com/rapid7/metasploit-omnibus/issues/115

**Comment by Mikivirus1** [comment]
Any fix to this?
