### ISSUE TITLE
Metasploite psql: error: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by Sunilzzz** [rapid7/metasploit-framework#14455]
<!psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"?
createuser: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"?
createdb: error: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"?)
 
![Screenshot_20201202_203304](https://user-images.githubusercontent.com/63790785/100890149-efc4c900-34dd-11eb-9115-e1fa909dd2e3.jpg)
>

**Comment by manofeveryreligion** [comment]
Refer To The Following

https://www.percona.com/blog/2020/06/05/10-common-postgresql-errors/

**Comment by osmgg2** [comment]
ERROR: Could not connect. No such file or directory  

this error happend when after uploading the login.php to the server which is www.byethost17.com/
and then by opening the following page it not worked
http://stemassiut.byethost17.com/3_support/dyn/users_/login.php
