### ISSUE TITLE
telnet_login Module in Metasploit

### ISSUE THREAD

**Issue by roosterx86** [rapid7/metasploit-framework#14504]
Greetings all,
I am trying to telnet into a VLE (virtual lab environment) for a project, but I keep running into the same errors.
Each time I try to run the module, I get a "The following options failed to validate: USER_FILE, PASS_FILE.

## Steps to reproduce

I followed the steps verbatim with the link below from Offensive Security.
I also tried setting the IP to a single IP and not the "/24" option. Both failed.
I also tried using the path to the desktop, and also the way that the captures text shows.

## Were you following a specific guide/tutorial or reading documentation?

https://www.offensive-security.com/metasploit-unleashed/scanner-telnet-auxiliary-modules/

## Expected behavior

The system should force a telnet connection and capture the user name and password.

## Current behavior

Auxiliary failed: Msf::OptionValidateError The following options failed to validate: USER_FILE, PASS_FILE.

### Metasploit version

4.16.18-dev-5cdd364

## Additional Information

unable to update as this is a virtual machine provided by my university for running labs.

```
msf auxiliary(telnet_login) > show options

Module options (auxiliary/scanner/telnet/telnet_login):

   Name              Current Setting   Required  Description
   ----              ---------------   --------  -----------
   BLANK_PASSWORDS   false             no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                 yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false             no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false             no        Add all passwords in the current database to the list
   DB_ALL_USERS      false             no        Add all users in the current database to the list
   PASSWORD                            no        A specific password to authenticate with
   PASS_FILE         passwords.txt     no        File containing passwords, one per line
   RHOSTS            10.139.46.121/24  yes       The target address range or CIDR identifier
   RPORT             23                yes       The target port (TCP)
   STOP_ON_SUCCESS   false             yes       Stop guessing when a credential works for a host
   THREADS           254               yes       The number of concurrent threads
   USERNAME                            no        A specific username to authenticate as
   USERPASS_FILE                       no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false             no        Try the username as the password for all users
   USER_FILE         users.txt         no        File containing usernames, one per line
   VERBOSE           false             yes       Whether to print output for all attempts

msf auxiliary(telnet_login) > set USER_FILE users.txt
USER_FILE => users.txt
msf auxiliary(telnet_login) > set RHOSTS 10.139.46.121
RHOSTS => 10.139.46.121
msf auxiliary(telnet_login) > set PASS_FILE passwords.txt
PASS_FILE => passwords.txt
msf auxiliary(telnet_login) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: USER_FILE, PASS_FILE.
msf auxiliary(telnet_login) >
```

**Comment by h00die** [comment]
Try giving full paths for those files

**Comment by roosterx86** [comment]
Same result. 
![Screen Shot 2020-12-12 at 1 52 02 PM](https://user-images.githubusercontent.com/75883293/101994691-723d4d80-3c81-11eb-8f6f-5e0d16418e1f.png)

**Comment by adfoster-r7** [comment]
```
Metasploit version
4.16.18-dev-5cdd364
```

This is quite an old version of Metasploit framework. Is this still an issue with Metasploit 6?

**Comment by adfoster-r7** [comment]
I thought I had replicated this, but after fixing the typo I had made in the file path it works as expected:

![image](https://user-images.githubusercontent.com/60357436/102342343-044e9a00-3f91-11eb-94d6-09ead1da7794.png)

I don't know if the original problem is user error when providing a valid path or if it's a bug that's been fixed since Metasploit 4 was released

**Comment by adfoster-r7** [comment]
Unrelated to the original issue I did notice that custom banners will break the login mechanism if it contains the substring `username:`

```
echo "Please login with username: firstname_lastname\n" > /etc/issue.net
```
