### ISSUE TITLE
Is there a way to get the return result from the RPC CALL meterpreter_run_single("test commond") command after running

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [rapid7/metasploit-framework#14503]
Is there a way to get the return result from the RPC CALL meterpreter_run_single("test commond") command after running, I just want to get the running result of "test commond".

Through meterpreter_read I cannot get the specified command. Such as the individual result of 'pwd' . help me!thanks!
```bash
>>  rpc.call('session.meterpreter_run_single', 1, 'pwd')
=> {"result"=>"success"}
>>  rpc.call('session.meterpreter_run_single', 1, 'lpwd')
=> {"result"=>"success"}
>>  rpc.call('session.meterpreter_read', '1')
=> {"data"=>"C:\\Users\\test\\Downloads\n/media/w/a0c409d4-9f6b-40e4-9699-c5f4062fc536/localgitserver/metasploit-framework\n"}

```

**Comment by adfoster-r7** [comment]
Unfortunately not, the rpc functionality always returns the same value and is not configurable:

https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/lib/msf/core/rpc/v10/rpc_session.rb#L279

You will have to use `session.meterpreter_read` function to read the value as you have shown

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 不幸的是，rpc功能始终返回相同的值，并且不可配置：
> 
> https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/lib/msf/core/rpc/v10/rpc_session.rb#L279
> 
> 您将必须使用`session.meterpreter_read`function读取显示的值

thanks!
