### ISSUE TITLE
cmd/unix/reverse_awk spins CPU after user exit

### ISSUE THREAD

**Issue by egypt** [rapid7/metasploit-framework#14510]
While testing payloads for #14509 I noticed cmd/unix/reverse_awk spins CPU after user exit.

## Steps to reproduce

- `use payload/cmd/unix/reverse_awk`
- `generate -f raw`
- copy the command
- `to_handler`
- paste the command into a terminal somewhere
- interact with the session: `sessions -1`
- `id` or something to make sure it's real
- `exit` or ctrl-c
- see the session close

## Expected behavior

clean exit

## Current behavior

If you `exit`, the payload continues to call back. If you ctrl-c, it doesn't call back anymore but the process is still there. Either way, my fan spins up

## Metasploit version

Tested in #14509 as mentioned. Verified that the same issue exists on current master, 7b31d332dc4d9d4520f01c247950b26e135408bf

**Comment by bcoles** [comment]
Welp. Likely introduced by #10035 to fix #9750. Context: https://github.com/rapid7/metasploit-framework/issues/9750#issuecomment-375806688

**Comment by timwr** [comment]
I can grab this, looks straightforward
