### ISSUE TITLE
meterpreter>download failed on target

### ISSUE THREAD

**Issue by alekione** [rapid7/metasploit-framework#14526]
hi.. I'm new and still eager to learn more on kali linux..but my issue is that after getting a connection on the target phone,using meterpreter,i can't download files. it keeps on failing every time.
I've repeated it several times with no successful. I'm using msf6 on kalilinux 2020.4 , vmware workstation 16 player on windows 10.
please help

**Comment by alekione** [comment]
here the images
![Uploading IMG_20201216_203304.jpg…]()
![Uploading IMG_20201216_203219.jpg…]()

**Comment by smcintyre-r7** [comment]
The images aren't coming through. What would be more helpful is actually posting the command output and the logs. Given the lack of details though but knowing that it's on a phone, I'm guessing there's a permission error at hand.

**Comment by alekione** [comment]
> The images aren't coming through. What would be more helpful is actually posting the command output and the logs. Given the lack of details though but knowing that it's on a phone, I'm guessing there's a permission error at hand.

sorry for taking long to reply..but here are the results..hope i'll find help

    meterpreter > download /sdcard/DCIM
[*] mirroring  : /sdcard/DCIM/.tmfs -> /root/DCIM/.tmfs
[*] downloading: /sdcard/DCIM/.tmfs/sk_v.dat -> /root/DCIM/.tmfs/sk_v.dat
[*] failed     : /sdcard/DCIM/.tmfs/sk_v.dat -> /root/DCIM/.tmfs/sk_v.dat
[*] mirrored   : /sdcard/DCIM/.tmfs -> /root/DCIM/.tmfs
[*] mirroring  : /sdcard/DCIM/Camera -> /root/DCIM/Camera
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_155809.jpg -> /root/DCIM/Camera/IMG_20201118_155809.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_155809.jpg -> /root/DCIM/Camera/IMG_20201118_155809.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_051843.jpg -> /root/DCIM/Camera/IMG_20201118_051843.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_051843.jpg -> /root/DCIM/Camera/IMG_20201118_051843.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_155831.jpg -> /root/DCIM/Camera/IMG_20201118_155831.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_155831.jpg -> /root/DCIM/Camera/IMG_20201118_155831.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_155835.jpg -> /root/DCIM/Camera/IMG_20201118_155835.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_155835.jpg -> /root/DCIM/Camera/IMG_20201118_155835.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_155841.jpg -> /root/DCIM/Camera/IMG_20201118_155841.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_155841.jpg -> /root/DCIM/Camera/IMG_20201118_155841.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_155936.jpg -> /root/DCIM/Camera/IMG_20201118_155936.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_155936.jpg -> /root/DCIM/Camera/IMG_20201118_155936.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_175931.jpg -> /root/DCIM/Camera/IMG_20201118_175931.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_175931.jpg -> /root/DCIM/Camera/IMG_20201118_175931.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201118_175936.jpg -> /root/DCIM/Camera/IMG_20201118_175936.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201118_175936.jpg -> /root/DCIM/Camera/IMG_20201118_175936.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201119_175044.jpg -> /root/DCIM/Camera/IMG_20201119_175044.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201119_175044.jpg -> /root/DCIM/Camera/IMG_20201119_175044.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201119_175050.jpg -> /root/DCIM/Camera/IMG_20201119_175050.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201119_175050.jpg -> /root/DCIM/Camera/IMG_20201119_175050.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124427.jpg -> /root/DCIM/Camera/IMG_20201121_124427.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124427.jpg -> /root/DCIM/Camera/IMG_20201121_124427.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124430.jpg -> /root/DCIM/Camera/IMG_20201121_124430.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124430.jpg -> /root/DCIM/Camera/IMG_20201121_124430.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124433.jpg -> /root/DCIM/Camera/IMG_20201121_124433.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124433.jpg -> /root/DCIM/Camera/IMG_20201121_124433.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124434.jpg -> /root/DCIM/Camera/IMG_20201121_124434.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124434.jpg -> /root/DCIM/Camera/IMG_20201121_124434.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124439.jpg -> /root/DCIM/Camera/IMG_20201121_124439.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124439.jpg -> /root/DCIM/Camera/IMG_20201121_124439.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124442.jpg -> /root/DCIM/Camera/IMG_20201121_124442.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124442.jpg -> /root/DCIM/Camera/IMG_20201121_124442.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124445.jpg -> /root/DCIM/Camera/IMG_20201121_124445.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124445.jpg -> /root/DCIM/Camera/IMG_20201121_124445.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124447.jpg -> /root/DCIM/Camera/IMG_20201121_124447.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124447.jpg -> /root/DCIM/Camera/IMG_20201121_124447.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124449.jpg -> /root/DCIM/Camera/IMG_20201121_124449.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124449.jpg -> /root/DCIM/Camera/IMG_20201121_124449.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201121_124451.jpg -> /root/DCIM/Camera/IMG_20201121_124451.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201121_124451.jpg -> /root/DCIM/Camera/IMG_20201121_124451.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201126_191606.jpg -> /root/DCIM/Camera/IMG_20201126_191606.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201126_191606.jpg -> /root/DCIM/Camera/IMG_20201126_191606.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201126_191608.jpg -> /root/DCIM/Camera/IMG_20201126_191608.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201126_191608.jpg -> /root/DCIM/Camera/IMG_20201126_191608.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201228_140100.jpg -> /root/DCIM/Camera/IMG_20201228_140100.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201228_140100.jpg -> /root/DCIM/Camera/IMG_20201228_140100.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201228_214839.jpg -> /root/DCIM/Camera/IMG_20201228_214839.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201228_214839.jpg -> /root/DCIM/Camera/IMG_20201228_214839.jpg
[*] downloading: /sdcard/DCIM/Camera/IMG_20201203_161532.jpg -> /root/DCIM/Camera/IMG_20201203_161532.jpg
[*] failed     : /sdcard/DCIM/Camera/IMG_20201203_161532.jpg -> /root/DCIM/Camera/IMG_20201203_161532.jpg

**Comment by timwr** [comment]
This is fixed by https://github.com/rapid7/metasploit-payloads/pull/449
