### ISSUE TITLE
Cannot uninstall MSF on ubuntu, docs doesn't match with my setup

### ISSUE THREAD

**Issue by xzivzs** [rapid7/metasploit-framework#14533]
# I'm trying to perform a clean uninstall of MSF. 
System: Ubuntu 20.04.1 LTS
I'm using metasploit-framework v6.0.23

## When reading the documentation https://docs.rapid7.com/metasploit/uninstalling-metasploit/ , I'm not seeing the same things in my current metasploit-framework folder.

Here is my current folder: /opt/metasploit-framework/ . From there I only have > bin , embedded, LICENCE, LICENCES, version-manifest.

How can I uninstall properly MSF from my system ?

Cheers!

**Comment by abrac** [comment]
Uninstall it with your package manager. In Ubuntu:

```
sudo apt remove metasplooit-framework
```
