### ISSUE TITLE
Knockpy

### ISSUE THREAD

**Issue by BugHunter01** [rapid7/metasploit-framework#14536]
# python3 knockpy.py                                                     1 ⨯
  File "knockpy.py", line 53
    print """
  _  __                 _                
 | |/ /                | |   """+__version__+"""            
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
  _  __                 _                
 | |/ /                | |   """+__version__+""")?
                                                   

how can i solve this problem.

**Comment by bcoles** [comment]
I'm guessing `knockpy.py` was written in Python 2 and thus uses `print ""` style rather than `print("")` (which works for both Python2 and Python3).

Also, you're posting in the wrong neighborhood. This is the Metasploit issue tracker.
