### ISSUE TITLE
Meterpreter session shows download fail

### ISSUE THREAD

**Issue by Dj2o** [rapid7/metasploit-framework#14546]
I learned hacking in the termux app and tested various tools, not being downloaded from the meterpreter since the metasploit
![Screenshot_20201224-012245](https://user-images.githubusercontent.com/64633599/103032336-ffd64280-4589-11eb-929a-269d1de65e6e.png)
 update a few days ago. Please help me 😞

**Comment by ShadowHackrs** [comment]
same problem

**Comment by timwr** [comment]
This is fixed by https://github.com/rapid7/metasploit-payloads/pull/449

**Comment by joew4093** [comment]
HAVE YOU BEEN IN SEARCH FOR GENUINE HACKER'S ONLINE?. HAVE YOU LOST YOUR MONEY TO BINARY OPTION SCAM OR ANY ONLINE SCAM WHATSOEVER?. WELL, YOU HAVE FOUND REDEMPTION IN HACKTRUTH TEAM CONTACT THEM VIA HACK.TRUTH77@GMAIL.COM
