### ISSUE TITLE
![IMG_20201231_094441](https://user-images.githubusercontent.com/68526692/103394175-ebc3af80-4b4c-11eb-8b3b-13040a5fc0b3.jpg)

### ISSUE THREAD

**Issue by vamshikrishna112211** [rapid7/metasploit-framework#14569]
![IMG_20201231_094441](https://user-images.githubusercontent.com/68526692/103394175-ebc3af80-4b4c-11eb-8b3b-13040a5fc0b3.jpg)
Why failed to bind??

_Originally posted by @vamshikrishna112211 in https://github.com/rapid7/metasploit-framework/issues/12786#issuecomment-752837771_

**Comment by bcoles** [comment]
Presumably the value you have set for `LHOST` is not a valid IP address for any of your network interfaces.

The options you're looking for are `ReverseListenerBindAddress` and`ReverseListenerBindPort`.

Set `LHOST` and `LPORT` to your public IP and public port. Set `ReverseListenerBindAddress` and `ReverseListenerBindPort` to your local IP and local port.

```
set LHOST <your public IP address which your target will connect to>
set ReverseListenerBindAddress <your local IP address for a network interface>
```

If you don't set `ReverseListenerBindAddress`, and it can't bind to `LHOST`, it'll fall back on `0.0.0.0`. Make sure everything is routing correctly, and make sure your payload can egress to your handler.

Reference:

* https://www.corelan.be/index.php/2014/01/04/metasploit-meterpreter-and-nat/
