### ISSUE TITLE
$BIN/ruby $FRAMEWORK/$cmd "$@

### ISSUE THREAD

**Issue by lyh-ship** [rapid7/metasploit-framework#14560]
MacBook-Pro dirtycow-master % proxychains4 msfconsole
[proxychains] config file found: /Users/lyh/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
/opt/metasploit-framework/bin/msfconsole: line 116: 16452 Segmentation fault: 11  $BIN/ruby $FRAMEWORK/$cmd "$@"

It is normal for me to execute msfconsole directly, and an error is reported when executing proxychains4 msfconsole
$BIN/ruby $FRAMEWORK/$cmd "$@"
System version mac 10.15.5

How to solve？？？？？

**Comment by bcoles** [comment]
Is there more to that error message?

Are there any errors in the `framework.log` file?

> How to solve？？？？？

Try without `proxychains`.
