### ISSUE TITLE
when i tried to create a injected payload then i got this error please solve someone and give me answere 

### ISSUE THREAD

**Issue by Lakhangaikwad** [rapid7/metasploit-framework#14573]
Error: undefined method `[]' for nil:NilClass

**Comment by h00die** [comment]
You'll need to provide lots more information for someone to debug.
What command did you run, with what parameters did you use.
I would suggest running the command again that caused this error. Copy and past the command line and all output.
If it involves another file, like an APK, please let us know where it came from
