### ISSUE TITLE
auxiliary: client/sms/send_text

### ISSUE THREAD

**Issue by jepunband** [rapid7/metasploit-framework#14571]
Hello, 

I'm trying to send sms using this module "auxiliary: client/sms/send_text". I'm using Google as the carrier. The message/sms gets out to gmail inbox but the sms is not going/reaching to phone number(s). I cannot try other carriers because i'm not registered to it.

Any advice on this please?

**Comment by h00die** [comment]
The carrier should be the phone/sms carrier. Who is your sms/phone service provider?

**Comment by jepunband** [comment]
it's none of the US carriers. Not listed in the module.  :(

**Comment by h00die** [comment]
In that case, it will not work for you.

**Comment by jepunband** [comment]
Is there a way to add carrier option & gateway, if possible where to edit this?

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/proto/sms/model.rb#L8

If you find working information for your provider, feel free to submit a PR to update, or post the details here and someone can add it.
