### ISSUE TITLE
Can't get latest sms using dump_sms

### ISSUE THREAD

**Issue by ig-terminal** [rapid7/metasploit-framework#14570]
After connection get establish when is type dump_sms i get older sms. But I need new sms of victim.
Take example 
>>dumo_sms
Sms successful dumped 
01-10-2020
.
.
.
.
.
.
01-09-2020
But today's date is 01-01-2021.
What should I do ?

**Comment by timwr** [comment]
What's the issue here? Is the date wrong or are you unable to download the most recent SMS messages?

**Comment by Ajey1** [comment]
> After connection get establish when is type dump_sms i get older sms. But I need new sms of victim.
> Take example
> 
> > > dumo_sms
> > > Sms successful dumped
> > > 01-10-2020
> > > .
> > > .
> > > .
> > > .
> > > .
> > > .
> > > 01-09-2020
> > > But today's date is 01-01-2021.
> > > What should I do ?

Yes me too have same problem do u have any solution for this problem

**Comment by Ajey1** [comment]
I can't get recent sms while using dump_sms at metasploit
