### ISSUE TITLE
I get this when I run Metasploit. 

### ISSUE THREAD

**Issue by rnvtwri** [rapid7/metasploit-framework#14574]
When I run Metasploit

Executing “sudo msfdb init && msfconsole”
[i] Database already started
[i] The database appears to be already configured, skipping initialization
Could not find reline-0.1.5 in any of the sources
Run bundle install to install missing gems.

When i run bundle install
root@arnav:~# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application
for all non-root users on this machine.
Could not locate Gemfile

I also cannot run Armitage

**Comment by h00die** [comment]
Duplicate
