### ISSUE TITLE
msfpro fails to launch with error

### ISSUE THREAD

**Issue by MylesMor** [rapid7/metasploit-framework#14586]
## Steps to reproduce

How'd you do it?

1. Be on Kali Linux 2020.4, having installed Metasploit Pro using the installer downloaded from the website.
2. Type `msfpro`
3. Fails with the error: 
```
Traceback (most recent call last):
        1: from /opt/metasploit/apps/pro/engine/msfpro:14:in `<main>'
/opt/metasploit/apps/pro/engine/msfpro:14:in `require': no implicit conversion of Pathname into String (TypeError)
```

4. Typing `sudo msfpro` instead causes it to hang indefinitely (have waited 10 mins with no further messages).

![image](https://user-images.githubusercontent.com/17624338/103714315-4a0de980-4fb6-11eb-84cd-9803f769784b.png)

## Expected behavior

Metasploit Pro Console should launch. Would also like to clarify that the web GUI works fine.

## Current behavior

The error as described above.

### Metasploit version

6.0.20-dev

**Comment by MylesMor** [comment]
After waiting for longer, `sudo msfpro` finally worked. Not sure if the error without the sudo is meant to appear, so will leave this issue open for someone to comment on.

**Comment by gwillcox-r7** [comment]
The issue tracker here is solely for Metasploit Framework, the open source version of Metasploit Pro. If you feel you are still experiencing issues or would like to raise this up with the support team for Metasploit Pro, please contact support via the customer portal at https://www.rapid7.com/for-customers/.
