### ISSUE TITLE
Nokogiri install bug

### ISSUE THREAD

**Issue by M0nster420** [rapid7/metasploit-framework#14588]
I try to run "bundle install" and I get this

![Screenshot_20210105_230709_com termux](https://user-images.githubusercontent.com/76930392/103731604-25f8db00-4fab-11eb-8e4f-53b8c71053c0.jpg)

**Comment by Abhishek8r456** [comment]
'rm -rf Gemfile.lock'
This command will delete gemlock file and then run 'bundle install' 
If this work thank me on @Abhishek.p4252 instagram 🙏

**Comment by M0nster420** [comment]
It worked, thank you, but I have this issue now :/

**Comment by inhdyaii** [comment]
are you found a way to run metasploit I'am looking in 4 day and not found any thing

**Comment by bcoles** [comment]
> 
> 
> are you found a way to run metasploit I'am looking in 4 day and not found any thing

Termux is not officially supported. #11023

However, Metasploit reportedly does work with Termux.

Refer to the following for more information:

    https://wiki.termux.com/wiki/Metasploit_Framework
    termux/termux-packages/issues/715

**Comment by adfoster-r7** [comment]
Closing for now as this issue is specific to Termux which is not officially supported

**Comment by inhdyaii** [comment]
So whatever I tried will not succeed but there is at least an alternative

في الجمعة، ١٩ فبراير، ٢٠٢١ ٥:٥١ م adfoster-r7 <notifications@github.com>
كتب:
