### ISSUE TITLE
Ubuntu - Metasploit framework  __Ruby not installed 

### ISSUE THREAD

**Issue by markba8** [rapid7/metasploit-framework#14591]
Hello, 

  New to Linux, 1-10 scale I'd be a 4.

When I run the msfconsole command, the following error occurs:
**/usr/bin/msfconsole : 109: /opt/metasploit-framework/bin/../embedded/bin/ruby: not found**

## Steps to reproduce

How'd you do it?

1. ... see above 
2. ...Windows - created Virtual box Ubuntu 20.10 virtual PC. Downloaded installation package from Rapid 7 

## Were you following a specific guide/tutorial or reading documentation? 
Some what, as in referencing various web articles on installing. Eventually, used the "files" icon on Ubuntu desktop, then to downloads, double clicked on the metasploit download and it came up with a GUI. Clicked install, and it installed. 

## Expected behavior
After typing msfconsole from inside the directory /opt/metasploit-framework/bin, Metasploit should open up. 

## Current behavior
error message appears instead saying that `/opt/metasploit-framework/bin/../embedded/bin/ruby` could not be found.

### Metasploit version
6.0.25+20210106112144~1rapid-1_i386.deb

## Additional Information
![metasploit error  ](https://user-images.githubusercontent.com/77109217/103902419-80d42480-50c8-11eb-8119-7354dc7f0ec9.JPG)

Thank you, 
Mark B. 
markba8@gmail.com

**Comment by gwillcox-r7** [comment]
@markba8 Just tided up your issue report to make it at little easier to read: you had some template lines still remaining that were meant to be replaced with your own comments.

**Comment by fardeen-ahmed** [comment]
@markba8 with due respect, 109 error is when code having some issues, some files or from client side not properly installed ruby. Retry installing ruby again, try doing it from rpm/dpkg packages from website directly. This may help sorting problem.

**Comment by fardeen-ahmed** [comment]
Also, you can try these steps on terminal regarding Pre-requisties and Installation :

**Installing the Pre-requisites.**
    
    1) adduser msfdev
    2) adduser msfdev sudo
    3) apt-get update
    4) apt-get -y install autoconf bison build-essential curl git-core libapr1 libaprutil1 libcurl4-openssl-dev libgmp3-dev libpcap-dev libpq-dev libreadline6-dev libsqlite3-dev libssl-dev libsvn1 libtool libxml2 libxml2-dev libxslt-dev libyaml-dev locate ncurses-dev openssl wget xsel zlib1g zlib1g-dev

**For Installation, Use msfdev for install**

    1) su - msfdev
    2) wget https://raw.githubusercontent.com/iam1980/metasploit-vps-installer/master/msf_vps_installer.sh
    3) bash msf_vps_installer.sh

Hope this fixes installation part from client side. Thank You....!!!!

**Comment by gwillcox-r7** [comment]
Closing this issue as this is a problem with not having Ruby installed, not a problem with Metasploit itself, and @fardeen-ahmed has provided info on how to fix this.
