### ISSUE TITLE
Installation in termux

### ISSUE THREAD

**Issue by h4ck5** [rapid7/metasploit-framework#14655]
Metasploit is not installing in termux 

apt-get update && apt-get upgrade

apt-get install unstable-repo

apt-get install metasploit

**Comment by Say0kiihN00b** [comment]
Unable locate package Metasploit

ahhhhhh

**Comment by clay404** [comment]
> Metasploit is not installing in termux
> 
> apt-get update && apt-get upgrade
> 
> apt-get install unstable-repo
> 
> apt-get install metasploit

**Comment by clay404** [comment]
How to  unbable to locate package metasploit

**Comment by adfoster-r7** [comment]
Unfortunately there's not enough error details to provide any help here. The bot above has linked to notes on using Metasploit with Termux which may help further. Closing for now.
