### ISSUE TITLE
from pcaprub to webrick error (ruby 3)

### ISSUE THREAD

**Issue by geyslan** [rapid7/metasploit-framework#14660]
## Steps to reproduce

How'd you do it?

After clone `git@github.com:rapid7/metasploit-framework.git`

1. `./msfconsole`
```
Could not find pcaprub-0.13.0 in any of the sources
Run `bundle install` to install missing gems.
```
2. `bundle install`
```
Fetching gem metadata from https://rubygems.org/.........
pcaprub-0.13.0 requires ruby version ~> 2.0, which is incompatible with the current version, ruby 3.0.0p0
```
3. `bundle update`
```
...
Using pcaprub 0.12.4 (was 0.13.0)
...
```
At step three the bundle did a downgrade of pcaprub.

4. `./msfconsole`
```
/home/uzu/.rvm/gems/ruby-3.0.0/gems/metasploit_data_models-4.1.1/lib/metasploit_data_models.rb:6:in `require': cannot load such file -- webrick (LoadError)
	from /home/uzu/.rvm/gems/ruby-3.0.0/gems/metasploit_data_models-4.1.1/lib/metasploit_data_models.rb:6:in `<top (required)>'
	from /home/uzu/.rvm/gems/ruby-3.0.0/gems/metasploit-credential-4.0.3/lib/metasploit/credential.rb:11:in `require'
	from /home/uzu/.rvm/gems/ruby-3.0.0/gems/metasploit-credential-4.0.3/lib/metasploit/credential.rb:11:in `<top (required)>'
	from /home/uzu/projs/metasploit-framework/lib/metasploit/framework.rb:12:in `require'
	from /home/uzu/projs/metasploit-framework/lib/metasploit/framework.rb:12:in `<top (required)>'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:79:in `require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:79:in `rescue in block in require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:57:in `block in require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler.rb:173:in `require'
	from /home/uzu/projs/metasploit-framework/config/application.rb:10:in `<top (required)>'
	from /home/uzu/projs/metasploit-framework/config/environment.rb:2:in `require'
	from /home/uzu/projs/metasploit-framework/config/environment.rb:2:in `<top (required)>'
	from /home/uzu/projs/metasploit-framework/lib/msfenv.rb:17:in `require'
	from /home/uzu/projs/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
	from ./msfconsole:18:in `require'
	from ./msfconsole:18:in `<main>'
/home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:66:in `require': cannot load such file -- metasploit-framework (LoadError)
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /home/uzu/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/bundler.rb:173:in `require'
	from /home/uzu/projs/metasploit-framework/config/application.rb:10:in `<top (required)>'
	from /home/uzu/projs/metasploit-framework/config/environment.rb:2:in `require'
	from /home/uzu/projs/metasploit-framework/config/environment.rb:2:in `<top (required)>'
	from /home/uzu/projs/metasploit-framework/lib/msfenv.rb:17:in `require'
	from /home/uzu/projs/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
	from ./msfconsole:18:in `require'
	from ./msfconsole:18:in `<main>'
```
### Metasploit version

`commit 10a3c12c04671b2e66e4fee51edca44f427a97e2 (HEAD -> master, upstream/master)`

### Additional information
```
❯ uname -a
Linux hb 5.10.10-arch1-1 #1 SMP PREEMPT Sat, 23 Jan 2021 23:59:48 +0000 x86_64 GNU/Linux
```
```
❯ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
```

**Comment by adfoster-r7** [comment]
At this time Ruby 3.0.0 is not officially supported at this time, if possible I'd recommend using Ruby 2.7 :+1:

**Comment by geyslan** [comment]
> At this time Ruby 3.0.0 is not officially supported, if possible I'd recommend using Ruby 2.7 +1

It's true. Working now with ruby 2.7.2.

I'll let the issue open for maintainers will.

**Comment by adfoster-r7** [comment]
Thanks for the bug report! I have a feeling this issue might be raised a few more times in the future so I've added a bot response for now whilst we look into upgrading Metasploit to work with Ruby 3.0.0 :+1:

**Comment by YellowHacx23** [comment]
Ok but can i ask a question
When do you think Metaslloit will be upgraded to work with Ruby 3.0.0 like March?

**Comment by rakraju** [comment]
> > At this time Ruby 3.0.0 is not officially supported, if possible I'd recommend using Ruby 2.7 +1
> 
> It's true. Working now with ruby 2.7.2.
> 
> I'll let the issue open for maintainers will.

How to downgrade to ruby 2.7.2 in termux

**Comment by gushmazuko** [comment]
> > > At this time Ruby 3.0.0 is not officially supported, if possible I'd recommend using Ruby 2.7 +1
> > 
> > 
> > It's true. Working now with ruby 2.7.2.
> > I'll let the issue open for maintainers will.
> 
> How to downgrade to ruby 2.7.2 in termux

You can build `ruby 2.7.2` from source from here: https://github.com/termux/termux-packages/tree/38204aa2c81155ffa845c167de926d1723868a8d following this [guide ](https://asciinema.org/a/5BsCbNoCzNFEgcH8vh8975MLm?autoplay=1&speed=2.5). You will also need replace theses file: [ncurses](https://raw.githubusercontent.com/termux/termux-packages/master/packages/ncurses/build.sh)  and [ca-certificates](https://raw.githubusercontent.com/termux/termux-packages/master/packages/ca-certificates/build.sh). 

Or just install a package from my repository https://github.com/gushmazuko/metasploit_in_termux/tree/master/dists/gushmazuko/main/binary-aarch64 and prevent ruby updating with command:
```bash
apt-mark hold ruby
```
