### ISSUE TITLE
Update issue on Termux

### ISSUE THREAD

**Issue by 26chk** [rapid7/metasploit-framework#14689]
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via git
[*] Note: Updating from bleeding edge
[-] ERROR: user.name is not set in your global git configuration
[-] Set it by running: 'git config --global user.name "NAME HERE"'

![Screenshot_20210201_192737](https://user-images.githubusercontent.com/61009000/106452969-910ed200-64c3-11eb-81f2-ea22cf49adb6.jpg)

**Comment by adfoster-r7** [comment]
The error message indicates that you need to configure your git client before running `msfupdate` again

```
[] Note: Updating from bleeding edge
[-] ERROR: user.name is not set in your global git configuration
[-] Set it by running: 'git config --global user.name "NAME HERE"'
```

**Comment by 26chk** [comment]
ok

**Comment by armalitedev** [comment]
adding sudo before the command worked for me
