### ISSUE TITLE
Metasploit Vulnerability name color rendering problem

### ISSUE THREAD

**Issue by 26chk** [rapid7/metasploit-framework#14709]
Color rendering problem

![Screenshot_20210202_234535](https://user-images.githubusercontent.com/61009000/106624814-03a9ab80-65b1-11eb-95cb-03649a3fc5ae.jpg)
![Screenshot_20210202_234556](https://user-images.githubusercontent.com/61009000/106624842-0a382300-65b1-11eb-9858-9a9e71b063dc.jpg)

**Comment by adfoster-r7** [comment]
Thanks for raising an issue. Just to confirm, is this issue resolved when resizing your terminal?

**Comment by 26chk** [comment]
> 感谢您提出问题。只是为了确认，调整终端大小时是否可以解决此问题？

yes it work
