### ISSUE TITLE
difference between post/windows/manage/exec_powershell,post/windows/manage/powershell/exec_powershell,and post/windows/manage/powershell/load_script

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#14716]
## Summary
what is the difference between post/windows/manage/exec_powershell,post/windows/manage/powershell/exec_powershell,and post/windows/manage/powershell/load_script?
i know that all of them can be used to execute powershell script or command,but i dont found any different

**Comment by smcintyre-r7** [comment]
Well `post/windows/manage/exec_powershell` and `post/windows/manage/powershell/exec_powershell` look very similar. The second has additional options, and they use different mixin methods so I'm thinking the second is likely intended as a replacement for the first.

The `post/windows/manage/powershell/load_script` module on the other hand looks like it's primary purpose is running multiple scripts from a folder.

It looks like there's some room for improvement here.

**Comment by GetRektBoy724** [comment]
ahhh ok thx for the quick explanation @smcintyre-r7
