### ISSUE TITLE
Metasploit cannot be used in Ruby3.0the work

### ISSUE THREAD

**Issue by 26chk** [rapid7/metasploit-framework#14737]
when I update Ruby and start metasploit, It does not work

![Screenshot_20210211_081507](https://user-images.githubusercontent.com/61009000/107589578-47e81c00-6c41-11eb-8df6-03367c14dc78.jpg)

**Comment by capunk2708** [comment]
![Screenshot_20210211_071438](https://user-images.githubusercontent.com/74790361/107590309-c8f3e300-6c42-11eb-97bf-0bfc7adf1304.jpg)

**Comment by capunk2708** [comment]
![Screenshot_20210211_071411](https://user-images.githubusercontent.com/74790361/107590344-df01a380-6c42-11eb-89fd-63754b01a583.jpg)

**Comment by capunk2708** [comment]
![Screenshot_20210210_082240](https://user-images.githubusercontent.com/74790361/107590381-f6d92780-6c42-11eb-88db-33a974d957d4.jpg)
