### ISSUE TITLE
mysql_login does only 3 attemps in brute force

### ISSUE THREAD

**Issue by Areturn** [rapid7/metasploit-framework#14736]
## Steps to reproduce

![image](https://user-images.githubusercontent.com/25275823/107471772-a2816980-6ba8-11eb-9c01-95cb46a0abb9.png)

os: kali2.0 5.5.0-kali2-amd64

### Metasploit version

Framework: 6.0.28-dev
Console  : 6.0.28-dev
Pro      : 4.19.0-2021020101

**Comment by adfoster-r7** [comment]
Looks like the login scanner stops after failing to connect 3 times, and there's no notification to the user that this has happened:
https://github.com/rapid7/metasploit-framework/blob/f456c965ff2f36f07b7f48c93ae50a06230cb720/lib/metasploit/framework/login_scanner/base.rb#L245-L251

In the database logs I can see the request does reach the target though:
> 2021-02-10 10:42:21 45 [Warning] Aborted connection 45 to db: 'unconnected' user: 'unauthenticated' host: '172.17.0.1' (This connection closed normally without authentication)

I've tested with this version of mariadb:
> docker run --rm -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mariadb:10.5.8

Would have to try earlier versions incase this is a protocol issue

**Comment by adfoster-r7** [comment]
Looks like this has been happening for a while, seems to have occurred in this ticket too: https://github.com/rapid7/metasploit-framework/issues/12891
