### ISSUE TITLE
msf reinstall error

### ISSUE THREAD

**Issue by Steve-God** [rapid7/metasploit-framework#14745]
┌──(root💀Steve)-[~/桌面]
└─# msfconsole                                                        10 ⨯
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      io-console (~> 0.5)
      Available/installed versions of this gem:
      - 0.5.7
      - 0.5.6
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Unable to find a spec satisfying metasploit-framework (>= 0) in the set. Perhaps the lockfile is corrupted?
Run `bundle install` to install missing gems.

**Comment by bcoles** [comment]
What does "reinstall" mean in this context? Are you using the cloned repository from GitHub?

You could try `git checkout Gemfile.lock && bundle install`.

Also, Metasploit does not yet support Ruby version 3.x.

**Comment by drwetter** [comment]
I had almost the same problem (io-console 0.5.8 vs. 0.5.6) too under kali linux. Reason was I didn't fully update kali but was just updating the metaspolit-framework (msfupdate is not the method of choice there).

gem uninstall for the older version didn't work. ``apt-get upgrade`` did though.

**Comment by gwillcox-r7** [comment]
Closing this issue due to a lack of information from the submitter.
