### ISSUE TITLE
Metasploit problem how can I fix it

### ISSUE THREAD

**Issue by BLUE-444** [rapid7/metasploit-framework#14746]
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `<top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/metasploit-credential-4.0.3/lib/metasploit/credential.rb:11:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/metasploit-credential-4.0.3/lib/metasploit/credential.rb:11:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:47:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:47:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/msfconsole:47:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:47:in `<main>'

**Comment by dorianmariefr** [comment]
This warning is because the original poster was using an outdated version of bundler: 1.17.3, 2.3.10 is the latest https://rubygems.org/gems/bundler
