### ISSUE TITLE
Why is db_import so slow?

### ISSUE THREAD

**Issue by ad0nis** [rapid7/metasploit-framework#14763]
## Summary

Why is db_import so slow?

## Relevant information

After scanning a client network with nmap, and outputting in xml format, when I then db_import that scan, it takes an exceptional amount of time to import some scans, multiplied by the size of the client's network. Is there any way to speed this up? I don't see CPU or memory getting thrashed on my VM, so it makes me wonder if the file is just being parsed inefficiently?

Was considering submitting this as a bug or feature request, but figured the best place to start was a question to gain understanding of the current state of things.

**Comment by h00die** [comment]
Can you give some more concrete information? How big is the network (approx hosts, ports per host), how big is the XML file, what database engine are you using (local postgres?), Approx how long is it running (4hrs vs 5min).  This will help start to diagnose if this is normal or not.

**Comment by h00die** [comment]
Also some approx system specs may help as well. Rpi vs laptop vs workstation vs server

**Comment by jeffmcjunkin** [comment]
FWIW I've seen the same behavior. With very recent `metasploit-framework` on Debian and Ubuntu, 64-bit Intel host (6-core 8th gen i7 as well as remote Xeon VPS systems) , it's about half a second per host at best, which is tedious for large lists. Here's a recent example of a nmap scan with the vulners plugin, with `external-alive.txt` containing ~120 hosts:
```
nmap -iL external-alive.txt -p redacted_list_of_open_ports -sV -A --script "safe or default or vulners" -oA nmap_external_full_vulners --script-args mincvss=5 -Pn
```

Another scan was of 113 internal /24 ranges with a more targeted scan, and I remember that one taking over an hour to import. I don't have any sharable XML results, unfortunately, for testing purposes.

**Comment by ad0nis** [comment]
I think @jeffmcjunkin's example is more-or-less perfect. This happens with any network that consists of more than a handful of /24's, whether the nmap is run with a -A top-1000 ports or just scanning 445. All imports are slow, to the point where some of my team doesn't understand why I use db_import at all because the import is almost always slow enough to go do something else for a few hours, or even to walk away from over-night, depending on the size of the scope. This happens in VMs with 4 cores and 8GB of RAM pretty reliably. VMs are running on NVMe or SSD in most situations. DB is local postgress, running on current-ish kali release.

**Comment by parsingstuff** [comment]
db_import seems to be doing thousands of (unnecessary?) SELECTS when importing, making importing even a handful of hosts very slow. Example: 

    SELECT "services".* FROM "services" WHERE "services"."host_id" = $1 AND (name is not null and name != '' and info is not null and info != '') ORDER BY services.port, services.proto

From a file containing strace output: 

    strings /tmp/st-msf.out | egrep 'sendto.*SELECT' | \
    perl -pe 's,\\0,,g' | perl -nle 'print $1 if /(SELECT.*?)", \d+/' | \
    grep -v 'SELECT 1' | \
    egrep -i 'select.*services.*from.*services.*where.*services.*host_id' | \
    wc -l
    22133

Interesting that when db_nmap is run from msfconsole it doesn't seem to have this problem.

**Comment by adfoster-r7** [comment]
@parsingstuff Thanks for the extra datapoint! :+1:

We looked into this recently, and we think it might be possible to cut the import time down by a lot if we updated the db_import logic to bulk insert the imported data into the database once, rather than individually inserting each record sequentially. When we've completed the work of upgrading Metasploit from Rails 5 to 6, we might be able to use the Rails 6 new [insert_all](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-insert_all) API to achieve this. We're keeping track of the Ruby 3/Rails 6 upgrade effort here - https://github.com/rapid7/metasploit-framework/issues/14666

If you spot any quick wins in the interim though, a PR would be great! 🎉

**Comment by parsingstuff** [comment]
One more data point, I ran the import with 

    ruby -rprofile

Here's the first few lines of the profile output: 

      %   cumulative   self              self     total
     time   seconds   seconds    calls  ms/call  ms/call  name
    599.12 295878.72  295878.72  2058848   143.71   143.71  IO.select
      4.76 298227.45   2348.73 115822930     0.02     0.03  ActiveRecord::QueryMethods#get_value
      2.66 299543.34   1315.89 45783408     0.03     0.22  ActiveRecord::Relation::Merger#merge
      2.63 300840.53   1297.19 311939412     0.00     0.00  Hash#[]
      2.59 302121.58   1281.05 43819455     0.03     6.21  Array#each
      2.10 303156.70   1035.12 74647176     0.01     0.72  Class#new
      2.09 304186.84   1030.14 20070167     0.05     0.19  ActiveRecord::Result#hash_rows
      1.88 305113.43    926.59 20712670     0.04     1.00  ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#exec_query
      1.71 305958.82    845.39 21530598     0.04     0.60  Arel::Visitors::Reduce#visit
      1.71 306802.84    844.01 17442301     0.05     0.24  ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#get_oid_type
      1.71 307645.96    843.13 153482090     0.01     0.01  Hash#fetch
      1.36 308318.75    672.79  1635123     0.41     0.41  PG::Connection#exec_params
      1.00 308810.98    492.23 24255830     0.02     0.04  Arel::Collectors::Composite#<<
      0.95 309280.86    469.87 13625966     0.03     0.16  ActiveRecord::QueryMethods#preprocess_order_args
      0.94 309743.87    463.01 33207308     0.01     0.04  ActiveModel::LazyAttributeHash#[]
      0.88 310177.55    433.68 20441289     0.02     0.10  Concurrent::Map#fetch
      0.85 310596.80    419.25 27798925     0.02     0.02  Arel::Collectors::PlainString#<<
      0.82 311003.27    406.47 21705378     0.02     1.15  ActiveRecord::Querying#find_by_sql
      0.82 311406.43    403.16  3543131     0.11     0.20  ActiveRecord::ConnectionAdapters::Quoting#_type_cast
      0.80 311803.44    397.01  8578660     0.05     0.09  ActiveModel::LazyAttributeHash#assign_default_value
      0.79 312194.19    390.75 17458603     0.02     0.03  Array#hash
      0.79 312582.45    388.26  1635196     0.24     2.12  ActiveRecord::QueryMethods#build_arel
      0.77 312962.88    380.44 17442554     0.02     0.16  ActiveRecord::Type::TypeMap#fetch
      0.77 313342.53    379.65 31648237     0.01     0.03  Kernel#dup
      0.73 313705.21    362.68 31677420     0.01     0.02  Kernel#initialize_dup
      0.71 314056.71    351.50  4419549     0.08     0.45  Hash#each_key
      0.70 314400.21    343.50 100417107     0.00     0.00  Module#===

My guess is the ActiveRecord::QueryMethods#get_value method is the main culprit here. Not sure what's going on, just seems like a lot of work to insert new info into the db.

**Comment by adfoster-r7** [comment]
Improvements to the `db_import` functionality should be possible now with our [Rails 6.1 upgrade](https://github.com/rapid7/metasploit-framework/pull/15493), which gives us access to a new [insert_all](https://apidock.com/rails/v6.0.0/ActiveRecord/Persistence/ClassMethods/insert_all) method.

I don't have an ETA for when we could start this work, as we're in the middle of finishing inflight projects right now - but we should definitely aim to spend cycles on this :+1:

**Comment by adfoster-r7** [comment]
For anyone impacted by this, out of interest what is the result of this command for you within msfconsole?

> irb -e "puts JSON.pretty_generate({ counts: { workspace: Mdm::Workspace.count, hosts: Mdm::Host.count, vulns: Mdm::Vuln.count, notes: Mdm::Note.count, services: Mdm::Service.count }, workspace_examples: Mdm::Workspace.take(10).map { |workspace| { workspace_id: workspace.id, hosts: workspace.hosts.count, vulns: workspace.vulns.count, notes: workspace.notes.count, services: workspace.services.count } } })"

---

For instance, this is my output:
```
msf6 > irb -e "puts JSON.pretty_generate({ counts: { workspace: Mdm::Workspace.count, hosts: Mdm::Host.count, vulns: Mdm::Vuln.count, notes: Mdm::Note.count, services: Mdm::Service.count }, workspace_examples: Mdm::Workspace.take(10).map { |workspace| { workspace_id: workspace.id, hosts: workspace.hosts.count, vulns: workspace.vulns.count, notes: workspace.notes.count, services: workspace.services.count } } })"
{
  "counts": {
    "workspace": 2,
    "hosts": 3,
    "vulns": 578,
    "notes": 7,
    "services": 48
  },
  "workspace_examples": [
    {
      "workspace_id": 1,
      "hosts": 2,
      "vulns": 290,
      "notes": 5,
      "services": 27
    },
    {
      "workspace_id": 2,
      "hosts": 1,
      "vulns": 288,
      "notes": 2,
      "services": 21
    }
  ]
}
```

We found some some optimisation optimization efforts for consoles that have lots of workspaces and would like to verify this is the issue folk is running into

**Comment by parsingstuff** [comment]
msf6 > irb -e "puts JSON.pretty_generate({ counts: { workspace: 
Mdm::Workspace.count, hosts: Mdm::Host.count, vulns: Mdm::Vuln.count, notes: 
Mdm::Note.count, services: Mdm::Service.count }, workspace_examples: 
Mdm::Workspace.take(10).map { |workspace| { workspace_id: workspace.id, hosts: 
workspace.hosts.count, vulns: workspace.vulns.count, notes: 
workspace.notes.count, services: workspace.services.count } } })"
{
   "counts": {
     "workspace": 1,
     "hosts": 353631,
     "vulns": 19,
     "notes": 411197,
     "services": 2495570
   },
   "workspace_examples": [
     {
       "workspace_id": 1,
       "hosts": 353631,
       "vulns": 19,
       "notes": 411197,
       "services": 2495570
     }
   ]
}

Only 1 workspace here, so not sure if this helps.

Jim

**Comment by dwelch-r7** [comment]
Hey @parsingstuff my PR here https://github.com/rapid7/metasploit-framework/issues/14763 has landed and we believe it should help with some of the slowness you're experiencing with `db_import` it should be available in the next release of Metasploit Framework which should be `6.1.19`

**Comment by parsingstuff** [comment]
Seems to be working much better, thank you!

**Comment by adfoster-r7** [comment]
@parsingstuff Awesome, thanks!

Out of interest, how much time is it taking now? We have an inbuilt `time` command that should hopefully give a specific time measurement:

```
 time db_import ~/imports/m3_report.xml
[*] Importing 'NeXpose XML Report' data
[*] Import: Parsing with 'Nokogiri v1.12.5'
[*] Importing host 192.168.18.118
... omitted ...
[+] Command "db_import ~/Downloads/m3_report.xml" completed in 6.335982000018703 seconds
```

If it's still too high, I believe we should be able to chop that time down more

**Comment by parsingstuff** [comment]
msf6 > time db_import /tmp/10.XX.XX.0-24.xml
    [*] Importing 'Nmap XML' data
    [*] Import: Parsing with 'Nokogiri v1.12.5'
    [*] Importing host 10.XX.XX.1
    [*] Importing host 10.XX.XX.33
    [*] Importing host 10.XX.XX.101
    [*] Importing host 10.XX.XX.220
    [*] Importing host 10.XX.XX.228
    [*] Importing host 10.XX.XX.237
    [*] Importing host 10.XX.XX.239
    [*] Successfully imported /tmp/10.XX.XX.0-24.xml
    [+] Command "db_import /tmp/10.XX.XX.0-24.xml" completed in 18.71921693533659 seconds

Still a bit on the slow side, but usable now.

**Comment by adfoster-r7** [comment]
Awesome, thanks! Will close this for now.

Let me know if you're still having issues @jeffmcjunkin / @ad0nis and we can reopen this if need be :+1:

**Comment by jeffmcjunkin** [comment]
Very late confirmation, but re-importing those older XML files on the latest MSF as of today was much faster, so I think closing this issue is justified. Thanks for the mention, @adfoster-r7 👍
