### ISSUE TITLE
how to install Ruby 2.7.x?

### ISSUE THREAD

**Issue by Daigo1317** [rapid7/metasploit-framework#14791]
At the moment i have ruby 3.0.0, but it is not compatible with metasploit, so i was wondering how to downgrade to 2.7.x

**Comment by bcoles** [comment]
You can download Ruby from the [Ruby homepage](https://www.ruby-lang.org/). Information related to installing Ruby can be found on the [Installing Ruby](https://www.ruby-lang.org/en/documentation/installation/) page.

There may be a package for older versions of Ruby in the package manager for your operating system.

If you're using multiple versions of Ruby it may be a good idea to use a solution such as `rvm` or `rbenv` to handle multiple Ruby environments.

The Metasploit issue tracker is for tracking issues with Metasploit.

Perhaps someone on IRC or Slack can help you out with your questions in future:

* https://www.metasploit.com/help

**Comment by Daigo1317** [comment]
I forgot to say one thing ... thermal use so there is no specific guide to install the package .... there is only to download the latest version
