### ISSUE TITLE
auxiliary/scanner/http/owa_ews_login

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#14804]
## Steps to reproduce
msfconsole
use auxiliary/scanner/http/owa_ews_login
set ad_domain acme.org
set pass_file /tmp/passwords.txt
set username lee
set rhost 10.0.0.10
run

## Were you following a specific guide/tutorial or reading documentation?
https://pentestlab.blog/2019/09/05/microsoft-exchange-password-spraying/

## Expected behavior
[+] 10.0.0.10:443 - Successful login: lee:password

## Current behavior
Did not show successful login.

### Metasploit version
6.0.30-dev

## Additional Information
Kali Linux 2020.4 rolling fulling patched.

**Comment by adfoster-r7** [comment]
@leebaird Do you happen to have steps on how to create a target that's vulnerable to this module to help replicate this issue? :+1:
