### ISSUE TITLE
uninitialized constant ELM327HWBridgeRelay::ELM327Relay::MSF_LICENSE (NameError)

### ISSUE THREAD

**Issue by chenxiaohe** [rapid7/metasploit-framework#14810]
When I run with  "sudo ruby elm327_relay.rb -s /dev/ttyS0"
  I got the response like this:
![image](https://user-images.githubusercontent.com/20987383/109129844-094b7900-778c-11eb-8fe7-105d85696448.png)
my metasploit version is metasploit v6.0.30-dev and my ruby version is ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
 could you tell me how to solve it ?

**Comment by bcoles** [comment]
#14839
