### ISSUE TITLE
How to change session checkin value?

### ISSUE THREAD

**Issue by curi0usJack** [rapid7/metasploit-framework#14828]
What is the correct way of changing the CheckIn value of an existing meterpreter agent? Looking for the parallel to Cobalt Strikes "sleep 0" command.

Thank you.

**Comment by smcintyre-r7** [comment]
Well there is a `sleep` command in Meterpreter that will cause the session to be dormant for the specified period of time before reconnecting. It's a one time thing though and from Metasploit's perspective the session is closed and the restablished.

Our sessions are currently all synchronous and are incapable of the random delays and periodic checkins that other agents support. The reason for this is that it's necessary for Metasploit's sessions to facilitate operations like forwarding network traffic and running post modules (which are effectively a series of commands / API invocations passed to the session as opposed to a block of code that's uploaded and executed).

We have a discussion in #14492 where we talk about the potential of implementing asynchronous sessions, but it's not work that we've started yet.
