### ISSUE TITLE
Run "elm327_relay.rb -s /dev/ttyS0“ then Get Error ”uninitialized constant ELM327HWBridgeRelay::ELM327Relay::MSF_LICENSE (NameError)“

### ISSUE THREAD

**Issue by zhlu32** [rapid7/metasploit-framework#14839]
## Steps to reproduce

How'd you do it?

1. cd /usr/share/metasploit-framework/tools/hardware
2. ruby elm327_relay.rb -s /dev/ttyS0 

## Were you following a specific guide/tutorial or reading documentation?

I study a course with url "https://www.hackers-arise.com/post/2017/09/06/metasploit-basics-car-hacking-with-metasploit"

## Expected behavior

Start a 127.0.0.1 Server Success

## Current behavior

![image](https://user-images.githubusercontent.com/3273178/109607761-b1ce5400-7b63-11eb-9e89-57e24c0d2232.png)

### Metasploit version

Framework Version: 6.0.31-dev

**Comment by bcoles** [comment]
You probably don't have the required Ruby gems installed.

https://github.com/rapid7/metasploit-framework/blob/053853a86c986705f12a8c0ad54f1b9947c1ce71/tools/hardware/elm327_relay.rb#L12-L18

```sh
$ gem install serialport
```

More info:

https://blog.rapid7.com/2017/02/08/car-hacking-on-the-cheap/

**Comment by bcoles** [comment]
Confirmed.

This issue doesn't exist when launching the executable from a clone of the git repository, but does exist on my Kali install using the `metasploit-framework` package.

```
[2021-03-02 01:59:19] root@kali:~/Desktop/metasploit-framework/tools/hardware# ruby elm327_relay.rb 
/var/lib/gems/2.7.0/gems/serialport-1.3.1/lib/serialport.rb:25: warning: rb_safe_level_2_warning will be removed in Ruby 3.0
/var/lib/gems/2.7.0/gems/serialport-1.3.1/lib/serialport.rb:25: warning: rb_secure will be removed in Ruby 3.0
Unable to connect to serial port.  See -h for help
[2021-03-02 01:59:22] root@kali:~/Desktop/metasploit-framework/tools/hardware# cd /usr/share/metasploit-framework/tools/hardware
[2021-03-02 01:59:28] root@kali:/usr/share/metasploit-framework/tools/hardware# ruby elm327_relay.rb 
Traceback (most recent call last):
	2: from elm327_relay.rb:420:in `<main>'
	1: from elm327_relay.rb:420:in `new'
elm327_relay.rb:109:in `initialize': uninitialized constant ELM327HWBridgeRelay::ELM327Relay::MSF_LICENSE (NameError)
[2021-03-02 01:59:32] root@kali:/usr/share/metasploit-framework/tools/hardware# 
```

At a guess, this is due to a path issue failing to pull in the required dependencies, here somewhere:

https://github.com/rapid7/metasploit-framework/blob/053853a86c986705f12a8c0ad54f1b9947c1ce71/tools/hardware/elm327_relay.rb#L33-L40

**Comment by zhlu32** [comment]
> Confirmed.
> 
> This issue doesn't exist when launching the executable from a clone of the git repository, but does exist on my Kali install using the `metasploit-framework` package.
> 
> ```
> [2021-03-02 01:59:19] root@kali:~/Desktop/metasploit-framework/tools/hardware# ruby elm327_relay.rb 
> /var/lib/gems/2.7.0/gems/serialport-1.3.1/lib/serialport.rb:25: warning: rb_safe_level_2_warning will be removed in Ruby 3.0
> /var/lib/gems/2.7.0/gems/serialport-1.3.1/lib/serialport.rb:25: warning: rb_secure will be removed in Ruby 3.0
> Unable to connect to serial port.  See -h for help
> [2021-03-02 01:59:22] root@kali:~/Desktop/metasploit-framework/tools/hardware# cd /usr/share/metasploit-framework/tools/hardware
> [2021-03-02 01:59:28] root@kali:/usr/share/metasploit-framework/tools/hardware# ruby elm327_relay.rb 
> Traceback (most recent call last):
> 	2: from elm327_relay.rb:420:in `<main>'
> 	1: from elm327_relay.rb:420:in `new'
> elm327_relay.rb:109:in `initialize': uninitialized constant ELM327HWBridgeRelay::ELM327Relay::MSF_LICENSE (NameError)
> [2021-03-02 01:59:32] root@kali:/usr/share/metasploit-framework/tools/hardware# 
> ```
> 
> At a guess, this is due to a path issue failing to pull in the required dependencies, here somewhere:
> 
> https://github.com/rapid7/metasploit-framework/blob/053853a86c986705f12a8c0ad54f1b9947c1ce71/tools/hardware/elm327_relay.rb#L33-L40

I add some output test line,which show all right. Help!!!
![image](https://user-images.githubusercontent.com/3273178/109630062-72156580-7b7f-11eb-886c-d26715d173e5.png)
![image](https://user-images.githubusercontent.com/3273178/109630324-bb65b500-7b7f-11eb-9e09-5ca4cf824ea6.png)

**Comment by adfoster-r7** [comment]
Confirmed on Kali:
```
kali@kali:/usr/share/metasploit-framework/tools/hardware$ ruby elm327_relay.rb 
Traceback (most recent call last):
        2: from elm327_relay.rb:420:in `<main>'
        1: from elm327_relay.rb:420:in `new'
elm327_relay.rb:109:in `initialize': uninitialized constant ELM327HWBridgeRelay::ELM327Relay::MSF_LICENSE (NameError)
```

Not sure if this particular issue is related to upgrade issues - similar to: https://github.com/rapid7/metasploit-framework/issues/14796

**Comment by dwelch-r7** [comment]
This issue has already been resolved, the version of framework shipping with kali is an older one so once that gets updated the problem should go away on kali too
