### ISSUE TITLE
Metasploit: Handler failed to bind to XXXXXXXXX

### ISSUE THREAD

**Issue by mrchoppa030** [rapid7/metasploit-framework#14858]
Im new in this kali thing and I created a Powershell Payload with veil (number 22). After I set my LHOST to my IP adress, I started the metaspoit like this
`msfconsole --resource /var/lib/veil/output/handlers/test2.rc`
after a little bit loading, it said 
`[-] Handler failed to bind to **(my IP hehe)**:8080:-  -
[*] Started reverse TCP handler on 0.0.0.0:8080`

Sooo yeah, I really dont know what to do now. Thanks for the help and sry if my english is bad^^

**Comment by bcoles** [comment]
Presumably the value you have set for `LHOST` is not a valid IP address for any of your network interfaces.

The options you're looking for are `ReverseListenerBindAddress` and`ReverseListenerBindPort`.

Set `LHOST` and `LPORT` to your public IP and public port. Set `ReverseListenerBindAddress` and `ReverseListenerBindPort` to your local IP and local port.

```
set LHOST <your public IP address which your target will connect to>
set ReverseListenerBindAddress <your local IP address for a network interface>
```

If you don't set `ReverseListenerBindAddress`, and it can't bind to `LHOST`, it'll fall back on `0.0.0.0`. Make sure everything is routing correctly, and make sure your payload can egress to your handler.

That's all. Please take support to IRC or e-mail in the future. GitHub is primarily for code contributions, bug reports, and feature requests. Thanks!

Reference:

* https://www.corelan.be/index.php/2014/01/04/metasploit-meterpreter-and-nat/
