### ISSUE TITLE
nexpose_connect with user or password containing @ failed failed to login

### ISSUE THREAD

**Issue by dungabc6886** [rapid7/metasploit-framework#14865]
1.Change the password nexpose that contains the @ character
2.use nexpose_connect with the syntax nexpose_connec user: pass @ host: port ok or nexpose_connec user pass host port ok are not able to login

**Comment by adfoster-r7** [comment]
Thanks for raising an issue. I believe a work around is to use the following connection method:
```
nexpose_connect username password host port
```

Instead of:
```
nexpose_connect username:password@host[:port]
```

Let me know if that helps :+1:

**Comment by adfoster-r7** [comment]
Thanks again for raising the issue. This should be resolved in version 6.0.38, but let me know if you run into any difficulties :+1:

**Comment by dungabc6886** [comment]
Sorry, I have just checked my email now,
syntax nexpose_connect username password host port
This gives not enough data error

Vào Th 3, 30 thg 3, 2021 vào lúc 21:54 adfoster-r7 <
***@***.***> đã viết:

**Comment by brono4** [comment]
how resut password in nexpose for kali linux

**Comment by dung-tv** [comment]
> how resut password in nexpose for kali linux

nexpose's password is within the scope of nexpose. You can refer to the documentation [https://docs.rapid7.com/nexpose/resetting-a-password/](url)
