### ISSUE TITLE
he value specified for PAYLOAD is not valid.

### ISSUE THREAD

**Issue by Fasertio** [rapid7/metasploit-framework#14889]
Hi, I'm trying to set a payload but I get this result:
![2021-03-13 19_13_55-Window](https://user-images.githubusercontent.com/44972257/111039806-4cfedd80-8430-11eb-8b78-961c3bdf0fce.png)

**Comment by bcoles** [comment]
The value specified for `PAYLOAD` is not valid.

List available payloads with `show PAYLOADs` or `set PAYLOAD <tab><tab>`.
