### ISSUE TITLE
post/windows/gather/enum_ad_computers: ArgumentError invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [rapid7/metasploit-framework#14955]
Problem:  Byte \xAE results in ArgumentError invalid byte sequence in UTF-8
```
run post/windows/gather/enum_ad_computers

[-] Post failed: ArgumentError invalid byte sequence in UTF-8
[-] Call stack:
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:413:in `split'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:413:in `block in chunk_values'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each_with_index'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `map'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `chunk_values'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:395:in `row_to_s'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:125:in `block in to_s'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:121:in `each'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:121:in `to_s'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_ad_computers.rb:143:in `run'
```

Workaround:
https://github.com/rapid7/metasploit-framework/blob/7020b983cfe36165d1d4dcffa63a79917ab6aed8/modules/post/windows/gather/enum_ad_computers.rb#L120
replace with
```
row << field.gsub("\xAE",'')
```

```
run post/windows/gather/enum_ad_computers

Domain Computers
================

 dNSHostName         distinguishedName                                  description  operatingSystem                 operatingSystemServicePack
 -----------         -----------------                                  -----------  ---------------                 --------------------------
 DC01.examplead.lan  CN=DC01,OU=Domain Controllers,DC=examplead,DC=lan               Windows Server 2008 Datacenter  Service Pack 1
```

Since I think that is merely a workaround, I did not create a pull request

For debugging purposes I added:
```
        print("#{field}:#{field.each_byte.map { |b| b.to_s(16) }.join}\n")
```

>DC01.examplead.lan:444330312e6578616d706c6561642e6c616e
>CN=DC01,OU=Domain >Controllers,DC=examplead,DC=lan:434e3d444330312c4f553d446f6d61696e20436f6e74726f6c6c6572732c44433d6578616d70>6c6561642c44433d6c616e
>:
>Windows Server� 2008 Datacenter:57696e646f777320536572766572ae2032303038204461746163656e746572
>Service Pack 1:53657276696365205061636b2031

So, for my specific case the byte \xae is the problem

I think the actual solution would be a transcoding from whatever is used in AD environment to utf8, just dropping the byte is not the right way

**Comment by adfoster-r7** [comment]
Thanks for the detailed error report :+1:

I haven't replicated this yet, but it's also interesting to there's a work around in this file for this character already
https://github.com/rapid7/metasploit-framework/commit/e914061745ae3a174e4c04304eb2aea14f720aa7

**Comment by T35R6braPwgDJKq** [comment]
Yeah in deed it is interesting why this never happened before, since it would **have to**. Unless the behaviour of `<<` changed (at least to me it seems that `<<` is the reason for this error)

**Comment by pingport80** [comment]
> row << field.gsub("\xAE",'')

I was working on something similar, can you test `row << field.force_encoding("IBM863")`, if it works.
```
irb(main):040:0> puts "Windows Server\xAE 2008".force_encoding("IBM863")
Windows Server« 2008
=> nil

```

**Comment by abhay-khattar** [comment]
> Problem: Byte \xAE results in ArgumentError invalid byte sequence in UTF-8
> 
> ```
> run post/windows/gather/enum_ad_computers
> 
> [-] Post failed: ArgumentError invalid byte sequence in UTF-8
> [-] Call stack:
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:413:in `split'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:413:in `block in chunk_values'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each_with_index'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `each'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `map'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:410:in `chunk_values'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:395:in `row_to_s'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:125:in `block in to_s'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:121:in `each'
> [-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rex-text-0.2.33/lib/rex/text/wrapped_table.rb:121:in `to_s'
> [-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_ad_computers.rb:143:in `run'
> ```
> 
> Workaround:
> 
> https://github.com/rapid7/metasploit-framework/blob/7020b983cfe36165d1d4dcffa63a79917ab6aed8/modules/post/windows/gather/enum_ad_computers.rb#L120
> 
> 
> replace with
> ```
> row << field.gsub("\xAE",'')
> ```
> 
> ```
> run post/windows/gather/enum_ad_computers
> 
> Domain Computers
> ================
> 
>  dNSHostName         distinguishedName                                  description  operatingSystem                 operatingSystemServicePack
>  -----------         -----------------                                  -----------  ---------------                 --------------------------
>  DC01.examplead.lan  CN=DC01,OU=Domain Controllers,DC=examplead,DC=lan               Windows Server 2008 Datacenter  Service Pack 1
> ```
> 
> Since I think that is merely a workaround, I did not create a pull request
> 
> For debugging purposes I added:
> 
> ```
>         print("#{field}:#{field.each_byte.map { |b| b.to_s(16) }.join}\n")
> ```
> 
> > DC01.examplead.lan:444330312e6578616d706c6561642e6c616e
> > CN=DC01,OU=Domain >Controllers,DC=examplead,DC=lan:434e3d444330312c4f553d446f6d61696e20436f6e74726f6c6c6572732c44433d6578616d70>6c6561642c44433d6c616e
> > :
> > Windows Server� 2008 Datacenter:57696e646f777320536572766572ae2032303038204461746163656e746572
> > Service Pack 1:53657276696365205061636b2031
> 
> So, for my specific case the byte \xae is the problem
> 
> I think the actual solution would be a transcoding from whatever is used in AD environment to utf8, just dropping the byte is not the right way

Well, this solution worked for me as well! So, thank you!

**Comment by abhay-khattar** [comment]
> > row << field.gsub("\xAE",'')
> 
> hey, I was working on something similar, can you test `row << field.force_encoding("IBM863")`, if it works. Asking coz I don't have to lab to replicate :)
> 
> ```
> irb(main):040:0> puts "Windows Server\xAE 2008".force_encoding("IBM863")
> Windows Server« 2008
> => nil
> ```

I tried using this fix, but it gave the same error as earlier.

**Comment by adfoster-r7** [comment]
I'm guessing that `\xAE` is actually meant to be `\x00\xAE` i.e. `®` - https://charbase.com/00ae-unicode-registered-sign

Metasploit's most likely dropping a null byte intentionally/unintentionally, and as a result the string contains a single invalid byte `\xAE`

**Comment by gwillcox-r7** [comment]
The crash should be fixed in the next release by https://github.com/rapid7/metasploit-framework/pull/16729, which has gone out as of yesterday. If this is still an issue feel free to reopen this.
