### ISSUE TITLE
Auxiliary failed: Metasploit::Framework::PasswordCracker::InvalidWordlist Custom wordlist is not a valid path to a regular file

### ISSUE THREAD

**Issue by dittozyllion** [rapid7/metasploit-framework#14964]
Hi guys, i recently doing my lab work which required us to get user password from the victim's machine.
I able to get the hashdump but i cannot decrypt the hash using JTR.
Here is what i get:
![image](https://user-images.githubusercontent.com/80478010/112879392-a7b85a80-90fb-11eb-89c4-d8713dccbf81.png)
Please help me out and i appreciate that. Have a good day

**Comment by h00die** [comment]
in the meantime you can always do `creds -o /tmp/hashes.jtr` to export the creds and get the assignment done!

**Comment by h00die** [comment]
can confirm on kali, with metasploit at master.
```
msf6 > creds add user:lm_password ntlm:E52CAC67419A9A224A3B108F3FA6CB6D:8846F7EAEE8FB117AD06BDD830B7586C jtr:lm
msf6 > creds add user:nt_password ntlm:AAD3B435B51404EEAAD3B435B51404EE:8846F7EAEE8FB117AD06BDD830B7586C jtr:nt
msf6 > use crack_windows

Matching Modules
================

   #  Name                             Disclosure Date  Rank    Check  Description
   -  ----                             ---------------  ----    -----  -----------
   0  auxiliary/analyze/crack_windows                   normal  No     Password Cracker: Windows


Interact with a module by name or index. For example info 0, use 0 or use auxiliary/analyze/crack_windows

[*] Using auxiliary/analyze/crack_windows
msf6 auxiliary(analyze/crack_windows) > run

[+] john Version Detected: 1.9.0-jumbo-1 OMP
[*] Hashes Written out to /tmp/hashes_tmp20210329-67479-11wf6yk
[-] Auxiliary failed: Metasploit::Framework::PasswordCracker::InvalidWordlist Custom wordlist is not a valid path to a regular file
[-] Call stack:
[-]   /metasploit-framework/lib/metasploit/framework/password_crackers/wordlist.rb:390:in `valid!'
[-]   /metasploit-framework/lib/metasploit/framework/password_crackers/wordlist.rb:376:in `to_file'
[-]   /metasploit-framework/lib/msf/core/auxiliary/password_cracker.rb:119:in `wordlist_file'
[-]   /metasploit-framework/modules/auxiliary/analyze/crack_windows.rb:202:in `run'
[*] Auxiliary module execution completed
msf6 auxiliary(analyze/crack_windows) > version
Framework: 6.0.38-dev-54b4a50365
Console  : 6.0.38-dev-54b4a50365
```

**Comment by h00die** [comment]
you can also create an empty file `touch /tmp/words` and `set custom_wordlist /tmp/words`, and it'll run.

However, still looking into why it blows up w/o a wordlist

**Comment by dittozyllion** [comment]
I appreciate your help. Please do update me if the bug is fixed. Thanks again and have a good day.

**Comment by dittozyllion** [comment]
![image](https://user-images.githubusercontent.com/80478010/112985989-82772b00-9193-11eb-9e27-2784e10c1c33.png)


Hi, it is actually running. However, it has been 2 hours and nothing is showing, is there something wrong or anything i should do in order to run it properly?

Commands i used: 
`use auxiliary/analyze/crack_windows` 
`set CUSTOM_WORDLIST /tmp/words` (I created a word.txt in /tmp/)
`run`

**Comment by h00die** [comment]
that means the cracker made it through the default john wordlist and is now just trying incremental guessing... it will do this forever until you kill it.
