### ISSUE TITLE
NTP Protocol Fuzzer crashing due to Rex library changes

### ISSUE THREAD

**Issue by jra89** [rapid7/metasploit-framework#14990]
## Steps to reproduce

How'd you do it?

1. Start `msfconsole`
2. use fuzzers/ntp/ntp_protocol_fuzzer
3. set RHOSTS 127.0.0.1 (valid ntp target)
4. run
5. crashes shortly after

```
Auxiliary failed: NoMethodError undefined method `ntp_private' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `ntp_control' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `describe' for Rex::Proto::NTP:Module
```

## Were you following a specific guide/tutorial or reading documentation?
I was researching NTP to perform a correct assessment of an NTP time server.
I started the NTP fuzzer and wanted to run it against the server, it crashed directly after running.

## Expected behavior

It should start sending correct NTP requests to the server of different kinds, which it is supposed to do for hours.
Example:

```
[+] 192.168.50.235:123 -- Received '8-byte version 2 mode 7 reply' to 196-byte version 3 mode 7 imp 173 req 35 message: version mismatch
[+] 192.168.50.235:123 -- Received '8-byte version 2 mode 7 reply' to 196-byte version 3 mode 7 imp 173 req 36 message: version mismatch
[+] 192.168.50.235:123 -- Received '8-byte version 2 mode 7 reply' to 196-byte version 3 mode 7 imp 173 req 37 message: version mismatch
[+] 192.168.50.235:123 -- Received '8-byte version 2 mode 7 reply' to 196-byte version 3 mode 7 imp 173 req 38 message: version mismatch
```

## Current behavior

Crashed with one of the below errors

```
Auxiliary failed: NoMethodError undefined method `ntp_private' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `ntp_control' for Rex::Proto::NTP:Module
Auxiliary failed: NoMethodError undefined method `describe' for Rex::Proto::NTP:Module
```

### Metasploit version

```
msf6 > version
Framework: 6.0.38-dev-
Console  : 6.0.38-dev-
```

## Additional Information
I've already fixed the issue and prepared a PR. Creating this issue for reference. If it's absolutely needed then I can undo everything just to run the debug command. Rather not though.

**Comment by adfoster-r7** [comment]
This should be fixed now in framework version 6.0.39 - thanks for the issue + pull request! :+1:
