### ISSUE TITLE
Export auxiliary scanner

### ISSUE THREAD

**Issue by ampf27** [rapid7/metasploit-framework#14993]
For a given scanner is it possible to export only the vulnerable targets to a file? If so, how is that done?

Thank you

**Comment by adfoster-r7** [comment]
@ampf27 If you have connected your [database](https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit), I believe that you should be able to export your database - which will contain vulnerability information - to xml:

```
db_export -h
Usage:
    db_export -f <format> [filename]
    Format can be one of: xml, pwdump
```

You can then programatically extract the information in whichever way you want. Hope this helps :+1:
