### ISSUE TITLE
Does the android payload still work?

### ISSUE THREAD

**Issue by Parshuram2** [rapid7/metasploit-framework#14999]
## Summary
I tried running the android pen test after a couple of years now. I generated the payload using the standard msfvenom command. Everything works as it should, however, when Installing the apk, the warning shows up saying that this was built for an older version of android.
## Relevant information
I ignored that, however when I dropped into the android shell from the meterpreter prompt, all I got was "oat" and could not see
the processess running or any of the files. Is this how it should be now? Is there a later version of the payload? Thanks.

`ps` shows this

```
 PID   Name  User
 ---   ----  ----
 2656  sh    u0_a512
 2659  ps    u0_a512
```

shell shows only this
```
meterpreter > shell
Process 3 created.
Channel 3 created.
ls
oat
```

**Comment by Parshuram2** [comment]
I never got any response to the question. Does the msfvenom payload work on Android 10/11? I have posted the required information, cannot get an android shell with the payload. Is it just me, or is it an issue. That was the question. I don't yet know, if it is an issue.

**Comment by timwr** [comment]
This is the normal behaviour on 10/11. The ps command is only showing a limited number of processes
