### ISSUE TITLE
Cannot receive the license key email of Metasploit Pro

### ISSUE THREAD

**Issue by RiotGamesU** [rapid7/metasploit-framework#14995]
I have tried many different mailboxes, but I can't receive it

**Comment by ccondon-r7** [comment]
Hi there! This is for Metasploit Framework-related issues. Metasploit Pro customers should request support using the resources here: https://www.rapid7.com/for-customers/

**Comment by RiotGamesU** [comment]
> Hi there! This is for Metasploit Framework-related issues. Metasploit Pro customers should request support using the resources here: https://www.rapid7.com/for-customers/

thanks
