### ISSUE TITLE
Go module not working

### ISSUE THREAD

**Issue by iNoSec2** [rapid7/metasploit-framework#15003]
I'm seeing errors for Go modules, when starting msfconsole, such as
 
 ```
 [!] The following modules could not be loaded!
 [!]     /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go
```
Go is installed and i have a working installation since i use a lot of go tools and install all of them with go get.

Any ideas?? it start to be an error since the last update, before all was working without any errors

MSF version:
Framework: 6.0.37-dev
Console  : 6.0.37-dev

**Comment by adfoster-r7** [comment]
Attaching logs etc might provide more insight; Feel free to reach out via the metasploit slack and we could investigate this more closely

**Comment by iNoSec2** [comment]
> Attaching logs etc might provide more insight; Feel free to reach out via the metasploit slack and we could investigate this more closely

For sure, my bad, i will do that Monday, thanks for your time

**Comment by iNoSec2** [comment]
Sorry for the delay, the problem has resolved itself with an update but the logs said that:
`
[e(0)] core: <snip>/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError  Try running file manually to check for errors or dependency issues.
[e(0)] core: Unexpected output running <snip>$Metasploit_path/modules/auxiliary/scanner/msmail/exchange_enum.go:
<snip>$Metasploit_path/modules/auxiliary/scanner/msmail/exchange_enum.go:8:2: package metasploit/module is not in GOROOT (/usr/lib/go/src/metasploit/module)
<snip>$Metasploit_path//modules/auxiliary/scanner/msmail/exchange_enum.go:9:2: package msmail is not in GOROOT (/usr/lib/go/src/msmail)
`

But like i said this morning, after updating yesterday, all errors were gone.

Thanks for your time
