### ISSUE TITLE
`on_session_open` and `on_session_close` event handlers are not getting called

### ISSUE THREAD

**Issue by pingport80** [rapid7/metasploit-framework#15013]
## Summary
`on_session_open` and `on_session_close` are event handlers which should be called when sessions are opened and closed. However these methods are not being called when sessions start and exit.
  
Useful Links:
  - [/lib/msf/core/session_event.rb](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/session_event.rb)

## Steps to reproduce
```
msf6> edit lib/msf/core/session_event.rb
```
* Add some simple statements for checking, like below.
```
  #
  # Called when a session is opened.
  #
  def on_session_open(session)
    puts('session open')
  end

  #
  # Called when a session is closed.
  #
  def on_session_close(session, reason='')
    puts("session close")
  end

  #
  # Called when the user interacts with a session.
  #
  def on_session_interact(session)
    puts("session interact")
  end
```

```
msf6 > reload_lib lib/msf/core/session_event.rb
msf6 > handler -H 127.0.0.1 -P 4444 -p linux/x64/meterpreter_reverse_tcp
[*] Meterpreter session 1 opened (127.0.0.1:4444 -> 127.0.0.1:57636) at 2021-04-07 18:37:03 +0530
msf6 > sessions -i 1
[*] Starting interaction with 1...

session interact
session interact
meterpreter > quit
[*] Shutting down Meterpreter...

[*] 127.0.0.1 - Meterpreter session 1 closed.  Reason: User exit
msf6 >
```
Notice, `session open` and `session close` strings did not get printed when the session was opened and closed. However `session interact`(and also others like download, upload, command) got printed.

### Metasploit version

```
Framework: 6.0.39-dev-da6c575966
Console  : 6.0.39-dev-da6c575966
```
## OS
```
kali 2021.1 (Cloned from Github)

**Comment by dwelch-r7** [comment]
Hey @pingport80 I don't think this is an issue, it looks like the events are behaving as intended You can see here: https://github.com/rapid7/metasploit-framework/blob/776455d10a8628777106dedddb4e544892d7c2eb/lib/msf/ui/console/framework_event_manager.rb#L32
That the `Meterpreter session 1 opened` message you get is triggered by an event, the reason you get printouts for `on_session_interact` but not the rest is that the other have been overridden but `on_session_interact` has not

**Comment by pingport80** [comment]
Yeah right! It's getting overridden, my bad. Anyway thanks for reviewing it @dwelch-r7 . I guess this issue can be closed now.
