### ISSUE TITLE
msfvenom dont work on mac os

### ISSUE THREAD

**Issue by Astra321** [rapid7/metasploit-framework#15012]
pcs-MacBook-Air:bin pc$ ./msfconsole
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient/open_pipe.rb:63: warning: already initialized constant Rex::Proto::SMB::SimpleClient::OpenPipe::STATUS_BUFFER_OVERFLOW
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client/open_pipe.rb:63: warning: previous definition of STATUS_BUFFER_OVERFLOW was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient/open_pipe.rb:64: warning: already initialized constant Rex::Proto::SMB::SimpleClient::OpenPipe::STATUS_PIPE_BROKEN
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client/open_pipe.rb:64: warning: previous definition of STATUS_PIPE_BROKEN was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb:21: warning: already initialized constant Rex::Proto::SMB::SimpleClient::CONST
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client.rb:13: warning: previous definition of CONST was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb:22: warning: already initialized constant Rex::Proto::SMB::SimpleClient::CRYPT
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client.rb:14: warning: previous definition of CRYPT was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb:23: warning: already initialized constant Rex::Proto::SMB::SimpleClient::UTILS
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client.rb:15: warning: previous definition of UTILS was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb:24: warning: already initialized constant Rex::Proto::SMB::SimpleClient::XCEPT
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client.rb:16: warning: previous definition of XCEPT was here
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb:25: warning: already initialized constant Rex::Proto::SMB::SimpleClient::EVADE
/opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simple_client.rb:17: warning: previous definition of EVADE was here
Traceback (most recent call last):
	47: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
	46: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	45: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
	44: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:60:in `driver'
	43: from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:60:in `new'
	42: from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:157:in `initialize'
	41: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
	40: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
	39: from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
	38: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	37: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	36: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	35: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
	34: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:168:in `each'
	33: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
	32: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:244:in `load_modules'
	31: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/directory.rb:33:in `each_module_reference_name'
	30: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/directory.rb:33:in `foreach'
	29: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/directory.rb:43:in `block in each_module_reference_name'
	28: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rex-core-0.1.16/lib/rex/file.rb:132:in `find'
	27: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rex-core-0.1.16/lib/rex/file.rb:132:in `catch'
	26: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rex-core-0.1.16/lib/rex/file.rb:133:in `block in find'
	25: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/directory.rb:52:in `block (2 levels) in each_module_reference_name'
	24: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:245:in `block in load_modules'
	23: from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:190:in `load_module'
	22: from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:108:in `on_module_load'
	21: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:208:in `add_module'
	20: from /opt/metasploit-framework/embedded/framework/lib/msf/core/payload_set.rb:208:in `new'
	19: from /opt/metasploit-framework/embedded/framework/modules/payloads/stagers/windows/x64/bind_named_pipe.rb:21:in `initialize'
	18: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `require'
	17: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	16: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `block in require'
	15: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	14: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	13: from /opt/metasploit-framework/embedded/framework/lib/msf/core/handler/bind_named_pipe.rb:23:in `<top (required)>'
	12: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `require'
	11: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	10: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `block in require'
	 9: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 8: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 7: from /opt/metasploit-framework/embedded/framework/lib/rex/proto/smb.rb:8:in `<top (required)>'
	 6: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `require'
	 5: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	 4: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies.rb:291:in `block in require'
	 3: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 2: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `tap'
	 1: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:38:in `block in require'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded': expected file /opt/metasploit-framework/embedded/framework/lib/rex/proto/smb/simpleclient.rb to define constant Rex::Proto::SMB::Simpleclient, but didn't (Zeitwerk::NameError)

**Comment by dwelch-r7** [comment]
Hey thanks for raising this issue
it looks like you ended up with duplicate copies of simpleclient here  `/lib/rex/proto/smb/simpleclient.rb` and here `/lib/rex/proto/smb/simple_client.rb`
This file was renamed some time ago and unfortunately it seems like the update process failed to remove the old file, I would recommend fully removing then reinstalling framework to make sure you only have the most up to date files

**Comment by adfoster-r7** [comment]
Closing this, for now the solution is to uninstall and reinstall metasploit framework
