### ISSUE TITLE
win10 installation error

### ISSUE THREAD

**Issue by RiotGamesU** [rapid7/metasploit-framework#15039]
![image](https://user-images.githubusercontent.com/67886642/114520516-1bb63f00-9c74-11eb-8e68-77a73bf825ec.png)

win10latest

**Comment by bcoles** [comment]
Run the installer with administrator privileges.

https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+"ended+prematurely"

**Comment by RiotGamesU** [comment]
> Run the installer with administrator privileges.
> 
> [https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+"ended+prematurely](https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+%22ended+prematurely)"

thanks
