### ISSUE TITLE
How do I create username/password?

### ISSUE THREAD

**Issue by S3j5b0** [rapid7/metasploit-framework#15083]
Hi, this might be a tad basic, but i'm hacing a really hard time finding info about this anywhere.

I'm running ubuntu 20.04, and trying to set up metasploit.
So following your guide (https://docs.rapid7.com/metasploit/installing-the-metasploit-framework/) I run this command:

`/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && ./msfinstall`

and now, I am able to run mfsconsole easily just by typing `mfsconsole`.
I then read that I should connect a database for it to work properly, so I check the database connection:

```
msf6 > db_status
[*] postgresql selected, no connection
```

Ok, cool so I should set it up. On this page(https://docs.rapid7.com/metasploit/no-database-connection/) I find this command:
`
msf > db_connect your_msfdb_user:your_msfdb_pswd@127.0.0.1:5432/msf_database
`

Where it looks as if I need to have a username and a password for metasploit. I have no idea what this is, how i create it, or if I have it.

What do i do?
Also, the part that says "msf_database" I have no idea what to do with, should I point to a db file? an installation of something?

EDIT:

I now also tried stopping msfconsole, running "service postgresql start" and then running the msf again, with no effect

**Comment by adfoster-r7** [comment]
Have you ran ran the `msfdb init` command?

https://www.offensive-security.com/metasploit-unleashed/using-databases/

https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit

**Comment by S3j5b0** [comment]
thanks! running seems to work fine, however now when I run the mfsconsole, it starts with this line:'

`No local database connected, meaning some Metasploit features will not be available. `

And db_status is still the same

Am I missing some last step?  judging by the tutorials it should work now

**Comment by adfoster-r7** [comment]
What is the output of `msfdb init` ?

**Comment by S3j5b0** [comment]
This is the entire output:

```
ask@garser:~$ msfdb init
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.5/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
====================================================================
Running the 'init' command for the database:
Creating database at /home/ask/.msf4/db
Starting database at /home/ask/.msf4/db...success
Creating database users
Writing client authentication configuration file /home/ask/.msf4/db/pg_hba.conf
Stopping database at /home/ask/.msf4/db
Starting database at /home/ask/.msf4/db...success
Creating initial database schema
====================================================================

====================================================================
Running the 'init' command for the webservice:
[?] Initial MSF web service account username? [ask]: xxx
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...success
MSF web service started and online
Creating MSF web service user ask

    ############################################################
    ##              MSF Web Service Credentials               ##
    ##                                                        ##
    ##        Please store these credentials securely.        ##
    ##    You will need them to connect to the webservice.    ##
    ############################################################

MSF web service username: ask
MSF web service password: devver
MSF web service user API token: f91f66e29988fffe2268a214b378e59ac4fa2122ab39dd6bfe7ff9a1d0fe5d36e8273b2a53f83c6d


MSF web service configuration complete
The web service has been configured as your default data service in msfconsole with the name "local-https-data-service"

If needed, manually reconnect to the data service in msfconsole using the command:
db_connect --name local-https-data-service --token f91f66e29988fffe2268a214b378e59ac4fa2122ab39dd6bfe7ff9a1d0fe5d36e8273b2a53f83c6d --cert /home/ask/.msf4/msf-ws-cert.pem --skip-verify https://localhost:5443

The username and password are credentials for the API account:
https://localhost:5443/api/v1/auth/account

====================================================================
```

**Comment by S3j5b0** [comment]
I have now tried running this command in the msfconsole, as advised by the output of ´msfdb init´

`db_connect --name local-https-data-service --token f91f66e29988fffe2268a214b378e59ac4fa2122ab39dd6bfe7ff9a1d0fe5d36e8273b2a53f83c6d --cert /home/ask/.msf4/msf-ws-cert.pem --skip-verify https://localhost:5443`

To which I get this response:
`

[-] No local database connected, meaning some Metasploit features will not be available. A full list of the affected features & database setup instructions can be found here: https://github.com/rapid7/metasploit-framework/wiki/msfdb:-Database-Features-&-How-to-Set-up-a-Database-for-Metasploit`

So, still no succes

**Comment by adfoster-r7** [comment]
@S3j5b0 That's unexpected, I'll see if I can replicate later today with a fresh ubuntu 20.04 box :+1:

**Comment by adfoster-r7** [comment]
Just created a new ubuntu 20.04 image, and installed everything successfully:

```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
>   chmod 755 msfinstall && \
>   ./msfinstall
```

```
msfdb reinit
```

```
msfconsole
```

It might be worth deleting everything you have at the minute with:
```
msfdb delete
rm -rf ~/.msf4
rm -rf /opt/metasploit-framework
```

Then trying again the install steps above again. If you're still running into issues, feel free to reach out to me on the metasploit slack to take a further look :+1:

**Comment by S3j5b0** [comment]
I did the same with ubunutu 18 in a vm, and things worked perfectly there as well

Thats all I need to do to completely wipe metasploit and msfconsole from my machine?
