### ISSUE TITLE
python/meterpreter/reverse_http dies after changing transport

### ISSUE THREAD

**Issue by theguly** [rapid7/metasploit-framework#15098]
Having a python/meterpreter/reverse_http handled by a web_delivery, it runs for a while (minutes) until the debug output on the agent shows a:
```[*] changing transport to: http://192.168.1.1:5555/apparently_random_string/```
and the agent stops working. after every command received debug shows:
```Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()
```

and msfconsole shows:
```[*] Running 'find /var/www/ -name foo' on meterpreter session 3 ()
[-] Operation timed out
```

Note1: I tracked down using PythonMeterpreterDebug because of an issue similar to what has been reported at #15097

Note2: I have a similar issue also with linux/x86/meterpreter even if it breaks after more time, but reading a 10minute strace is not as easy as reading the small meterpreter debug. i suspect the issue is not on agent itself but on the handler

## Steps to reproduce

1. setup a web_delivery with default options
2. run python command on a linux host
3. try to interact, wait for ~5 minutes or like and see

to enable debug agent-side, on web_delivery set PythonMeterpreterDebug true

## Expected behavior

the agent should work until he dies, or msf handler is killed

### Metasploit version

6.0.39 (Pro trial)

**Comment by theguly** [comment]
today i made a quick test using a 6.0.40-dev running on a kali box setting up multi/handler and the results are the same: after a few minutes agent debug prints:
```[*] changing transport to: http://192.168.1.1:4545/multi_py/QjO4CAMEoRbEV9FDpNGkAgfgP7Rqc1NkXYMhRSmxtz-n9-jB_3GV9IgdCdArmMgzxZ1am6mqpTht_dWMCDTrmo/
Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()```

**Comment by smcintyre-r7** [comment]
I was able to reproduce this with and without the `web_delivery` module. There appears to be an issue in either the handler or (more likely) the Python Meterpreter itself. After a session has been open for about 10 minutes, issuing a command will cause the TypeError to be thrown with the stack trace in the debug logs.

```
Traceback (most recent call last):
  File "<string>", line 897, in get_packet
  File "<string>", line 889, in decrypt_packet
  File "<string>", line 1651, in met_aes_decrypt
  File "met_aes", line 45, in __init__
TypeError: object of type 'NoneType' has no len()
```

**Comment by smcintyre-r7** [comment]
This got closed out automatically but fixing payloads is actually a two step process. Once the framework-side gem bump is complete (#15143) this will be fully patched.
