### ISSUE TITLE
auxiliary/analyze/crack_databases uses john when setting action to hashcat

### ISSUE THREAD

**Issue by Serverhamster** [rapid7/metasploit-framework#15103]
## Steps to reproduce

```
msf6 auxiliary(analyze/crack_databases) > set action hashcat
action => hashcat
msf6 auxiliary(analyze/crack_databases) > run
[-] Auxiliary aborted due to failure: bad-config: John the Ripper JUMBO patch version required.
```

## Expected behavior

hashcat is a possible action for the `crack_databases` module.

hashcat should be used when set.

## Current behavior

The module throws an error about John the Ripper's JUMBO patch

### Metasploit version

* Framework: 6.0.38-dev
* Console  : 6.0.38-dev

## Additional Information

John the Ripper actually has the JUMBO patch applied

Output with loglevel 3.
```
[-] Auxiliary aborted due to failure: bad-config: John the Ripper JUMBO patch version required.  See https://github.com/magnumripper/JohnTheRipper
[*] Auxiliary module execution completed
```

**Comment by h00die** [comment]
This was fixed in #14996. you'll need to update to either 6.0.40 or 6.0.41 to get the fix.
