### ISSUE TITLE
Wmap stops with `[*] Using code '404' as not found.`

### ISSUE THREAD

**Issue by S3j5b0** [rapid7/metasploit-framework#15101]
Hi, i'm trying to run Wmap for my own little website.

I have msfconsole running, on ubuntu 20.04 and have it connected to a database, no issues there. 

Whenever I havde had my machine shut down, and then turn it on again, it prompts me with this view:

```

unning the 'init' command for the webservice:
[?] Initial MSF web service account username? [ask]: ask
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
MSF web service PID file found, but no active process running as PID 13636
Deleting MSF web service PID file /home/ask/.msf4/msf-ws.pid
Attempting to start MSF web service...failed
[!] MSF web service failed and returned the following message:
MSF web service expects authentication. If you wish to reinitialize the web service account you will need to reinitialize the database.
Please see /home/ask/.msf4/logs/msf-ws.log for additional webservice details.

```
I usually type in the credentials that I set when I initiallly set the application up. And as you can see it tells me that it can't start webservices.
I'm not sure whether this has anything to do with the issue i'm about to show, but I have a hunch.

Then I want to run Wmap, So I run the following commands:

```

msf > load wmap
msf > wmap_sites -a http://172.16.194.172 // not the actual ip I use
msf > wmap_targets -t http://172.16.194.172/mutillidae/index.php // also not actual ip
msf > wmap_run -t
msf > wmap_run -e
```

Everything up until "wmap_run -e" runs just fine, where it just hangs at:

`[*] Using code '404' as not found.`

So it just freezes, I can't escape it by "Ctrl+C", the only way I can escape it is by closing the terminal.

**Attemps at solving** 

I found someone having the same issue online (https://security.stackexchange.com/questions/179108/metasploit-wmap-run-e-hangs-with-using-code-404-as-not-found) who solved it by running 

`
mv /usr/share/metasploit-framework/modules/auxiliary/scanner/http/brute_dirs.rb /usr/share/metasploit-framework/modules/auxiliary/scanner/http/brute_dirs.rb.bak `

Which I changed such that it fit my installation-path and ran. This had no effect

**Edit**

just tried recreating on another ubuntu 20.04 machine. Same issue.

**second Edit**

I have now tried on different sites, from friends computers and so on. And the same problem keeps popping up

**Comment by adfoster-r7** [comment]
Looks like the brute_dirs module is very inefficient, and doesn't surface any information to the user that it's making progress. I don't think this is an issue per se, I think it just runs for a very long time?

If you run `set verbose true`, i think it will provide progress updates - but I haven't verified this
https://github.com/rapid7/metasploit-framework/blob/cc5647897d3e192f56e2753f0a31dd5d110ff084/modules/auxiliary/scanner/http/brute_dirs.rb#L160-L169
