### ISSUE TITLE
Metasploit cannot start *.py

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#15127]
Steps to reproduce

Start msfconsole

I received the following message

[!] The following modules could not be loaded!../
[!]     /data/data/com.termux/files/home/Metasploit/modules/auxiliary/gather/office365userenum.py
[!] Please see /data/data/com.termux/files/home/.msf4/logs/framework.log for details.
![Screenshot_20210501_124152](https://user-images.githubusercontent.com/61009000/116771013-a1aaf600-aa7a-11eb-95a9-845bd71ff561.jpg)

Error message：
It is office365userenum.py

Question: How can I hide or not display this information at startup？

**Comment by cgranleese-r7** [comment]
Hey @ghost!
There is already an [issue](https://github.com/rapid7/metasploit-framework/issues/14705) open for this.

So you can follow any updates there :+1:
