### ISSUE TITLE
E: Unable to locate package metasploit-framework

### ISSUE THREAD

**Issue by Sxpherr** [rapid7/metasploit-framework#15137]
when I’m trying to install the framework it logs: 
`E: Unable to locate package metasploit-framework`
when I run
 `curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall ` 

is it my problem?

**Comment by bcoles** [comment]
What is the full output of `./msfinstall` ? What operating system are you using?

**Comment by Sxpherr** [comment]
I’m using Ubuntu

**Comment by Sxpherr** [comment]
and I’m on Windows 10

**Comment by GetRektBoy724** [comment]
try
```
wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall 
```

**Comment by GetRektBoy724** [comment]
> and I’m on Windows 10
> I’m using Ubuntu
so you're using Ubuntu or Windows 10? :joy:

**Comment by sinisterd0lls** [comment]
I'm currently experiencing the same problem with the Nightly Installer. I'm on a Ubuntu 18.04 LTS VM (aarch64). The suggestion from @GetRektBoy724 still gives the same "E: unable to locate package metasploit-framework" error. Also having a "File has unexpected size 417 =/= 418" error to go with it.

**Comment by bcoles** [comment]
What is the full output of `./msfinstall` ?

**Comment by sinisterd0lls** [comment]
It seems my problem has disappeared without me doing anything since ./msfinstall initially had no output but is now acting as normal, possibly due to a fix upstream? Thanks for the help regardless!

**Comment by Sxpherr** [comment]
I’m using windows 10. I mean I’m using Ubuntu as terminal... 😂😂😂 it’s fixed

**Comment by 0xomar** [comment]
> try
> 
> ```
> wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall 
> ```

That did work. Thanks!

**Comment by alone152021** [comment]
@GetRektBoy724 
./msfinstall: 1: Checking: not found
./msfinstall: 2: Reading: not found
./msfinstall: 3: Building: not found
./msfinstall: 4: Reading: not found

**Comment by DARK-02** [comment]
> try
> 
> ```
> wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall 
> ```

lol thx

**Comment by abhayofc** [comment]
> try
> 
> ```
> wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall 
> ```

THanks

**Comment by Srmonestry** [comment]
No such file or directory

**Comment by pujith748** [comment]
Iwhen i am trying to install metasploit in termux 
Error : unable to locate package metasploit
How to fix it 
I am using termux in Android version 12

**Comment by bcoles** [comment]
> Iwhen i am trying to install metasploit in termux

Termux is not officially supported. #11023

**Comment by Ahmedsalehnawaz** [comment]
Metaspoit didn't installing why .

**Comment by gwillcox-r7** [comment]
This topic is getting way off topic now. Closing and locking this thread.
