### ISSUE TITLE
error when execute msfconsole 

### ISSUE THREAD

**Issue by secfung** [rapid7/metasploit-framework#15155]
I got below error when execute msfconsole in Kali Linux:

root@kali:~# msfconsole
Traceback (most recent call last):
	5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
	4: from <internal:gem_prelude>:1:in `require'
	3: from /usr/lib/ruby/vendor_ruby/rubygems.rb:1348:in `<top (required)>'
	2: from /usr/lib/ruby/vendor_ruby/rubygems.rb:1348:in `require'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
Information:
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux

=======================================
Tried:

1. Re-install Metasploit framework
2. run apt-get upgrade once

Any clue to address this problem? thank you!

**Comment by Shubh-theknight007** [comment]
Did u tried updating ruby version??
If not maybe its not updated update it and then try msfconsole again.

**Comment by secfung** [comment]
Finally, I re-installed Ruby and metasploit. Problem fixed, thanks!!
