### ISSUE TITLE
pcaprub  '0.13.0' help

### ISSUE THREAD

**Issue by KevinF4** [rapid7/metasploit-framework#15166]
Microsoft Windows [10.0.19041.546]

C:\Users\Kevin>cd C:\metasploit-framework-6.0.42

C:\metasploit-framework-6.0.42>bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies............
Using rake 13.0.3
Using Ascii85 1.1.0
Using concurrent-ruby 1.0.5
Using i18n 1.8.10
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.5
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.5.2
Using nokogiri 1.11.3 (x64-mingw32)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.9.1
Using rails-html-sanitizer 1.3.0
Using actionview 5.2.5
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 5.2.5
Using activemodel 5.2.5
Using arel 9.0.0
Using activerecord 5.2.5
Using public_suffix 4.0.6
Using addressable 2.7.0
Using afm 0.2.2
Using arel-helpers 2.12.0
Using ast 2.4.2
Using aws-eventstream 1.1.1
Using aws-partitions 1.446.0
Using aws-sigv4 1.2.3
Using jmespath 1.4.0
Using aws-sdk-core 3.114.0
Using aws-sdk-ec2 1.234.0
Using aws-sdk-iam 1.52.0
Using aws-sdk-kms 1.43.0
Using aws-sdk-s3 1.93.1
Using bcrypt 3.1.16
Using bcrypt_pbkdf 1.1.0 (x64-mingw32)
Using bindata 2.4.9
Using bson 4.12.0
Using bundler 2.1.4
Using byebug 11.1.3
Using coderay 1.1.3
Using cookiejar 0.3.3
Using daemons 1.3.1
Using diff-lcs 1.4.4
Using unf_ext 0.0.7.7 (x64-mingw32)
Using unf 0.1.4
Using simpleidn 0.2.1
Using dnsruby 1.61.5
Using docile 1.3.5
Using ed25519 1.2.4
Using eventmachine 1.2.7 (x64-mingw32)
Using em-socksify 0.3.2
Using http_parser.rb 0.6.0
Using em-http-request 1.1.7
Using factory_bot 6.1.0
Using method_source 1.0.0
Using thor 1.1.0
Using railties 5.2.5
Using factory_bot_rails 6.1.0
Using faker 2.17.0
Using faraday-excon 1.1.0
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.1.0
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.4
Using faraday 1.4.1
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Using faye-websocket 0.11.0
Using filesize 0.2.0
Using fivemat 1.3.7
Using hashery 2.1.2
Using hrr_rb_ssh 0.3.0.pre2
Using io-console 0.5.9
Using reline 0.2.5
Using irb 1.3.5
Using rkelly-remix 0.0.7
Using jsobfu 0.4.2
Using json 2.5.1
Using memory_profiler 1.0.0
Using metasm 1.0.4
Using metasploit-concern 3.0.1
Using metasploit-model 3.1.3
Using pg 1.2.3 (x64-mingw32)
Using recog 2.3.19
Using webrick 1.7.0
Using metasploit_data_models 4.1.3
Using net-ssh 6.1.0
Using rex-core 0.1.16
Using rex-socket 0.1.29
Using rubyntlm 0.6.3
Using rubyzip 2.3.0
Using metasploit-credential 4.0.3
Using metasploit-payloads 2.0.44
Using metasploit_payloads-mettle 1.0.9
Using mqtt 0.5.0
Using msgpack 1.4.2
Using nessus_rest 0.1.6
Using net-ldap 0.17.0
Using network_interface 0.0.2
Using nexpose 7.3.0
Using sawyer 0.8.2
Using octokit 4.20.0
Using openssl-ccm 1.2.2
Using openvas-omp 0.0.4
Fetching pcaprub 0.13.0
Installing pcaprub 0.13.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c
C:/Ruby27-x64/bin/ruby.exe -I C:/Ruby27-x64/lib/ruby/2.7.0 -r
./siteconf20210507-2324-2cgfvy.rb extconf.rb

[*] Running checks for pcaprub_c code...
platform is x64-mingw32
checking for -lws2_32... yes
checking for -liphlpapi... yes
checking for windows.h... yes
checking for winsock2.h... yes
checking for iphlpapi.h... yes
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... yes
checking for pcap_open_live() in -lwpcap... no
checking for pcap_setnonblock() in -lwpcap... no
creating Makefile

current directory:
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c
make "DESTDIR=" clean

current directory:
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0/ext/pcaprub_c
make "DESTDIR="
generating pcaprub_c-x64-mingw32.def
compiling pcaprub.c
pcaprub.c:11:10: fatal error: pcap.h: No such file or directory
   11 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:244: pcaprub.o] Erro 1

make failed, exit code 2

Gem files will remain installed in
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/pcaprub-0.13.0 for inspection.
Results logged to
C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/pcaprub-0.13.0/gem_make.out

An error occurred while installing pcaprub (0.13.0), and Bundler cannot
continue.
Make sure that `gem install pcaprub -v '0.13.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  metasploit-framework was resolved to 6.0.42, which depends on
    packetfu was resolved to 1.1.13, which depends on
      pcaprub

C:\metasploit-framework-6.0.42>

**Comment by jmartin-r7** [comment]
To install `pcaprub` on windows requires library headers from `winpcap` to be found in the build environment.

`pcaprub` is a dependency gem not maintained directly by the `metasploit-framework` project.  Please review documentation for https://github.com/pcaprub/pcaprub.  

The nightly installer for windows makes these files available to on the path used during the gem install process as well.  See: https://github.com/rapid7/metasploit-omnibus/blob/2d289bf4831e2d8103bf6df5e5ad7a2a1e908aed/config/software/winpcap-devpack.rb
