### ISSUE TITLE
Error while installing on Termux

### ISSUE THREAD

**Issue by Grey-Sloth** [rapid7/metasploit-framework#15169]
~/metasploit-framework $ bundle install --gemfile Gemfile.local

[!] There was an error parsing `Gemfile.local`: No such file or directory @ rb_sysopen - /data/data/com.termux/files/home/metasploit-framework/Gemfile.local. Bundler cannot continue.

Help........

**Comment by Shubh-theknight007** [comment]
I think it is caused by outdated version of Ruby gem installed in termux.
Update it by running     _gem update --system_   and try again .
