### ISSUE TITLE
APP WAS BUILT FORAN OLDER VERSION OF ANDROID

### ISSUE THREAD

**Issue by 0Ptic0P** [rapid7/metasploit-framework#15177]
After creating a apk file and running it on a android 10 there is an error that says "App was built for an older version of android" plz help me in this :)

**Comment by timwr** [comment]
This is just a warning message right? Can't you just click OK and carry on as usual?

**Comment by 0Ptic0P** [comment]
No the app doesnt open after clicking it

**Comment by timwr** [comment]
The app doesn't have a GUI, so you won't see anything once it's opened

**Comment by 0Ptic0P** [comment]
> The app doesn't have a GUI, so you won't see anything once it's opened

Thx man

**Comment by manoj-narasimha** [comment]
but the session dies. It's true that this app doesn't have any GUI but, In the console it says session 0 closed reason: Died.

**Comment by timwr** [comment]
The battery saver is probably killing it. Try follow the instructions for you device at https://dontkillmyapp.com

**Comment by Naim120** [comment]
> The battery saver is probably killing it. Try follow the instructions for you device at https://dontkillmyapp.com

@timwr can u pls tell me, why the battery saver killing the session? And is there any way that the payload will bypass itself from battery saver?

**Comment by timwr** [comment]
Did you visit the website? https://dontkillmyapp.com/
It explains both why the battery saver kills the app (phone manufacturers prefer battery life over background app functionality) and how to bypass it.

**Comment by Naim120** [comment]
Yes I did check the website. I was asking, if payload could do it automatically by itself, not manually by me. Anyway, thanks for reply.

**Comment by jcbrave** [comment]
> but the session dies. It's true that this app doesn't have any GUI but, In the console it says session 0 closed reason: Died.

I am facing the same problem, Did you found your problem solution? Please let me know eagerly waiting for yours response

**Comment by dedshit** [comment]
> > but the session dies. It's true that this app doesn't have any GUI but, In the console it says session 0 closed reason: Died.
> 
> I am facing the same problem, Did you found your problem solution? Please let me know eagerly waiting for yours response

sir why dont you manually insert the payload into legitimate apps that are asking permission at runtime ?

**Comment by jcbrave** [comment]
Because we need a persistant Connection and i think its not possible through Inserting a payload into another App.

**Comment by KnownBlackHat** [comment]
hey devs we need update which should fix older version error

**Comment by sapankotak** [comment]
Hello Guys, 
I am also facing the same problem and did not connect any seasons.
What should I do about it, can anyone help me with it?

**Comment by h00die** [comment]
> why metasploit not working with android 14 ,anyone has any solution for it?

https://github.com/rapid7/metasploit-framework/issues/19154
