### ISSUE TITLE
Make sure that `gem install racc -v '1.5.2' --source 'https://rubygems.org/'` succeeds before bundling.

### ISSUE THREAD

**Issue by Amalax** [rapid7/metasploit-framework#15176]
I want to install the racc but it meet in error how should I install it,It is showing
 sudo gem install racc -v '1.5.2'
Building native extensions. This could take a while...
ERROR:  Error installing racc:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/racc-1.5.2/ext/racc/cparse
/usr/bin/ruby2.5 -r ./siteconf20210509-2206-1ort0s1.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/racc-1.5.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/arm-linux/2.5.0/racc-1.5.2/gem_make.out

**Comment by bcoles** [comment]
You may need to install Ruby development packages.

```
sudo apt install ruby-dev
```
