### ISSUE TITLE
What's the lateSt Android version this APK will run meterpreter with and can someone please send me the script for it so far I have mobdroid APK but it won't allow me to share via Dropbox or drive anyone who has solutions please help

### ISSUE THREAD

**Issue by shane89420** [rapid7/metasploit-framework#15183]
What's the lateSt Android version this APK will run meterpreter with and can someone please send me the script for it so far I have mobdroid APK but it won't allow me to share via Dropbox or drive anyone who has solutions please help

**Comment by GetRektBoy724** [comment]
> What's the lateSt Android version this APK will run meterpreter with and can someone please send me the script for it so far I have mobdroid APK but it won't allow me to share via Dropbox or drive anyone who has solutions please help

Firstly,dont be a fucking skid
Second,the DropBox software probably already predict that some skid is going to use their service for spreading malwares,so they implement a virus scanner at their end to stop skids like you.
Third,sorry for being rude and calling you skid.
*skid : script kiddie

**Comment by shane89420** [comment]
Firstly don't be a condescending asshole.if someone don't know and asks a question an answer that is relevant to that question is what is supposed to be on this.

**Comment by GetRektBoy724** [comment]
> Firstly don't be a condescending asshole.if someone don't know and asks a question an answer that is relevant to that question is what is supposed to be on this. Weconnnect you're good to go...stfu about script kiddie this condescending asshole that.

Oh sorry,is that hurts you?

**Comment by gwillcox-r7** [comment]
@shane89420 Sorry for the disruption, do you have the APK in question? Usually APKs include a manifest file that specifies which versions they can run on.

**Comment by shane89420** [comment]
Not hurt just saying it how it is
I'm sure everyone started learning somewhere..I just thought I'd share

**Comment by shane89420** [comment]
Mr Willcox no I don't sorry when using mobdroid it's automatically generated I'm not sure how to get this

**Comment by gwillcox-r7** [comment]
You can use something like https://m.apkpure.com/search and search for the package name, then click the Download APK button.

**Comment by shane89420** [comment]
Yeah but it was not an actual functional app I used mobdroid to generate it

**Comment by GetRektBoy724** [comment]
> Yeah but it was not an actual functional app I used mobdroid to generate it

sorry, I just askin', What is MobDroid?

**Comment by gwillcox-r7** [comment]
> Yeah but it was not an actual functional app I used mobdroid to generate it

Sorry somehow GitHub didn't show this comment when I answered; apologies for that! When `mobdroid` generates the APK, assuming the code is from the link above, there should be a directory named `output` that contains the resulting APK that is generated.

**Comment by shane89420** [comment]
I'll check ...if I have it saved is there an email I can send it to

**Comment by shane89420** [comment]
And yes that would be the mobdroid I referred to

**Comment by shane89420** [comment]
> > Firstly don't be a condescending asshole.if someone don't know and asks a question an answer that is relevant to that question is what is supposed to be on this. Weconnnect you're good to go...stfu about script kiddie this condescending asshole that.
> 
> Oh sorry,is that hurts you?

LMFAO hurts not quite...but people like you who have no respect or etiquette don't belong on a platform that is designed to educate and collaborate not be a fuckin stooge

**Comment by gwillcox-r7** [comment]
@shane89420 @GetRektBoy724 Please keep conversations civil and free of swearing and harassment. If you can't conduct yourself in a professional manner, then please take your conversations elsewhere or don't comment at all; such comments are not welcome in this community.

**Comment by shane89420** [comment]
Sorry Mr Wilcox I said my piece and will refrain from using such language in future. I was just making a point..I asked for help not condescending arrogance.

**Comment by GetRektBoy724** [comment]
> @shane89420 @GetRektBoy724 Please keep conversations civil and free of swearing and harassment. If you can't conduct yourself in a professional manner, then please take your conversations elsewhere or don't comment at all.

yea I'm so so so so sorry :pray:

**Comment by shane89420** [comment]
this is the manifest in question...i have some i generated in fatrat that are very similar...if you send me an email address i will send the apk direct as they wont let me drag n drop

**Comment by gwillcox-r7** [comment]
@shane89420 Can send it to msfdev AT metasploit DOT com

**Comment by shane89420** [comment]
Mr Wilcox...highhappyhealthy....let me know if you didn't get it. Thanx

**Comment by gwillcox-r7** [comment]
> Mr Wilcox...highhappyhealthy....let me know if you didn't get it. Thanx

Yeah sorry didn't get anything over here.

**Comment by shane89420** [comment]
> > Mr Wilcox...highhappyhealthy....let me know if you didn't get it. Thanx
> 
> Yeah sorry didn't get anything over here.

hmmm ill try again?

**Comment by shane89420** [comment]
sent through wetransfer it should be there highhappyhealthy@outlook.com

> > Mr Wilcox...highhappyhealthy....let me know if you didn't get it. Thanx
> 
> Yeah sorry didn't get anything over here.

**Comment by shane89420** [comment]
![Screenshot_20210614-135238.png](https://user-images.githubusercontent.com/59754615/121936778-80a41900-cd39-11eb-95eb-dc08cc93124b.png) grant Wilcox

**Comment by gwillcox-r7** [comment]
Ah sorry I think we ended up deleting the old one as it got picked up as spam. Got the latest copy so all good 👍

**Comment by shane89420** [comment]
Thanx mr Wilcox I appreciate it.

**Comment by shane89420** [comment]
> Ah sorry I think we ended up deleting the old one as it got picked up as spam. Got the latest copy so all good 👍 

So...what's going on any solutions? And does anyone know how to automatically hook payloads...I'm having trouble
