### ISSUE TITLE
No local database connected

### ISSUE THREAD

**Issue by thejoker3000** [rapid7/metasploit-framework#15207]
I started noticing that metasploit isn't working properly when I was trying to use github.com/trustedsec/unicorn to generate payload. When I tried to run **msfconsole**, I was getting errors. So these are the things I did:
1- Ran **msfdb reinit** and run **msfconsole** again but same thing happened
2- Reinstalled metasploit, rebooted, checked **postgresql** status (which was active), executed **msfconsole**, still nothing
3- Gave up

![image](https://user-images.githubusercontent.com/53082621/118402900-3cefbe00-b66c-11eb-970b-43ad162474e8.png)

-----------------------------
Here is the log file that it prompts: https://gist.githubusercontent.com/thejoker3000/46d3028f27b72ab64c3de10be475aa25/raw/fb43b64ce8558e8b187442e03dbb5a1e5da2f41e/metasploit-errors.log

**Comment by thejoker3000** [comment]
Also, I noticed that it's using the file **.msf4**
but the version is 
![image](https://user-images.githubusercontent.com/53082621/118403458-b5f01500-b66e-11eb-96a1-32b1cda9c07a.png)

**Comment by thejoker3000** [comment]
I've tried it again but using username **msf** and password **msf** but same error happens when I start metasploit
![image](https://user-images.githubusercontent.com/53082621/118403597-6827dc80-b66f-11eb-878a-aa10827768c4.png)

**Comment by adfoster-r7** [comment]
@thejoker3000 Those are all warnings and can safely be ignored. The first warning appears when you don't have a running database correctly configured, and is safe to ignore. The other warnings are caused by Go not being installed, and can also be safely ignored.

Hope this helps, I can reopen this if this was stopping you from using the unicorn functionality :+1:

**Comment by adfoster-r7** [comment]
We're hoping to make tweaks to these warning messages too, so it's more apparent that they can be safely ignored

**Comment by thejoker3000** [comment]
OK, thanks! I didn't know this.
