### ISSUE TITLE
Meterpreter Python 3xx

### ISSUE THREAD

**Issue by KevinF4** [rapid7/metasploit-framework#15228]
I am using the latest version of metasploit pro to generate a python meterpreter, I would like to know if it is compatible with python 3.9.5, because I have seen in some places that metasploit uses python 2.7, has this changed?

**Comment by adfoster-r7** [comment]
It should be compatible with python 3.9.5, but if you run into any issues - raising a [bug report](https://github.com/rapid7/metasploit-framework/issues/new?assignees=&labels=bug&template=bug_report.md) will help us fix it :+1:
