### ISSUE TITLE
msfconsole command isn't running..can anyone help?

### ISSUE THREAD

**Issue by nutankhangar145** [rapid7/metasploit-framework#15221]
$ msfconsole
Error:
CANNOT LINK EXECUTABLE "ruby": library "/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so"

$ ./msfconsole
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/data/data/com.termux/files/usr/lib/ruby/gems/3.0.0/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
Could not find rake-12.3.1 in any of the sources
Run bundle install to install missing gems.
..
After $bundle install
It shows:
ttfunk-1.5.1 requires ruby version ~> 2.1, which is
incompatible with the current version, ruby 3.0.1p64

Please help! What should i do?
![Screenshot_2021-05-19-21-08-28-213_com termux](https://user-images.githubusercontent.com/84459505/118843224-797b1e00-b8e7-11eb-8874-2fc567d3477c.jpg)
![Screenshot_2021-05-19-21-08-14-180_com termux](https://user-images.githubusercontent.com/84459505/118843238-7ed86880-b8e7-11eb-8773-3444bfd83ae5.jpg)

**Comment by Gargeeshar19** [comment]
>msfconsole 
Could not find mini_portile2-2.5.3 in any of the sources
Run `bundle install` to install missing gems.

> Bundle install 

> Bundle update nokogiri
