### ISSUE TITLE
Msfconsole not opening on Mac os big sur

### ISSUE THREAD

**Issue by Pitchblende21** [rapid7/metasploit-framework#15249]
<img width="1407" alt="Screen Shot 2021-05-24 at 10 14 01 PM" src="https://user-images.githubusercontent.com/65574625/119442923-88920f80-bcdd-11eb-97c2-0ee0c4e823e0.png">

**Comment by adfoster-r7** [comment]
Hi, could you attach the full output please? :+1:

Metasploit works on big sur, so I believe this might be a local environment issue

**Comment by Pitchblende21** [comment]
nevermind, I think I knew what was wrong, and it works now. But I will report future problems, Thank you!

**Comment by adfoster-r7** [comment]
No problem, thank you for the update :+1:
