### ISSUE TITLE
msfdb not starting system.not booted with ....

### ISSUE THREAD

**Issue by NOAHnNAOMI** [rapid7/metasploit-framework#15256]
┌──(kali㉿localhost)-[~]
└─$ sudo msfdb init                                           System has not been booted with systemd as init system (PID 1). Can't operate.                                              Failed to connect to bus: Host is down
[+] Starting database                                         System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[i] The database appears to be already configured, skipping initialization

**Comment by adfoster-r7** [comment]
This looks like an issue with your environment, rather than being an issue with Metasploit itself. Are you running Kali on WSL?
https://github.com/microsoft/WSL/issues/6102
