### ISSUE TITLE
How to disable Window Defender real time protection from powershell command?

### ISSUE THREAD

**Issue by Korto9** [rapid7/metasploit-framework#15259]
Hi,

I wanted to know if its possible to disable Window Defender with only 1 powershell command since its very difficult for me to make it FUD. I tried this but it doesn't work. 

Set-MpPreference -DisableRealtimeMonitoring $true

Thank you in advance

**Comment by GetRektBoy724** [comment]
> Hi,
> 
> I wanted to know if its possible to disable Window Defender with only 1 powershell command since its very difficult for me to make it FUD. I tried this but it doesn't work.
> 
> Set-MpPreference -DisableRealtimeMonitoring $true
> 
> Thank you in advance

yes,`Set-MpPreference` cmdlet need admin privilege
maybe you can try [my Powershell crypter](https://github.com/GetRektBoy724/BetterXencrypt) ;)

**Comment by smcintyre-r7** [comment]
Closing this since it's off-topic for Metasploit.
