### ISSUE TITLE
Is it possible to use fzf in msfconsole for auto-completion?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [rapid7/metasploit-framework#15250]
Is it possible to use fzf in msfconsole for auto-completion?

Is it possible to set a shortcut key to enable fzf?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Or can you write a function to provide auto-completion?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
In Plugin?

**Comment by bcoles** [comment]
> 
> 
> Or can you write a function to provide auto-completion?

`msfconsole` has auto-completion.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> > 还是可以编写一个提供自动完成功能的函数？
> 
> `msfconsole` 具有自动补全功能。

Is there a way to extend the default completion function?
