### ISSUE TITLE
Could not execute get_local_subnets: ArgumentError wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by xiaoliuwa** [rapid7/metasploit-framework#15269]
meterpreter > run get_local_subnets 

[!] Meterpreter scripts are deprecated. Try post/multi/manage/autoroute.
[!] Example: run post/multi/manage/autoroute OPTION=value [...]
[-] Could not execute get_local_subnets: ArgumentError wrong number of arguments (given 2, expected 0..1)

meterpreter > run autoroute -p

[!] Meterpreter scripts are deprecated. Try post/multi/manage/autoroute.
[!] Example: run post/multi/manage/autoroute OPTION=value [...]
[-] Could not execute autoroute: ArgumentError wrong number of arguments (given 2, expected 0..1)

MSF命令报错，怎么解决

**Comment by smcintyre-r7** [comment]
Meterpreter scripts have been deprecated for years and we don't have any plans to maintain them anymore. If you want to describe what you're trying to do, we may be able to suggest an alternative instead.

**Comment by bingling123** [comment]
请问这个问题解决了吗？我也出现了这个问题
