### ISSUE TITLE
Handler failed to bind to 0.0.0.0:xxxx due to The address is already in use

### ISSUE THREAD

**Issue by henna-parrot** [rapid7/metasploit-framework#15274]
I'm running Metasploit on Kali Linux 2020.1 and  i created a backdoor apk with android/meterpreter/reverse_tcp, I'm having trouble with binding to a specific port  while listening. the port 4041 in my case which was in use by ngrok session. inorder for msf start to listen i must kill ngrok session which is not correct because if i kill ngrok i cant listen to external 

![Screenshot from 2021-05-28 02-51-50](https://user-images.githubusercontent.com/67507469/119994221-65e04f00-bf9a-11eb-80d0-210b4aa5fad3.png)

**Comment by bcoles** [comment]
The options you're looking for are `ReverseListenerBindAddress` and`ReverseListenerBindPort`.

Set `LHOST` and `LPORT` to your public IP and public port. Set `ReverseListenerBindAddress` and `ReverseListenerBindPort` to your local IP and local port.

```
set LHOST <your public IP address which your target will connect to>
set ReverseListenerBindAddress <your local IP address for a network interface>
```

Reference:

* https://www.corelan.be/index.php/2014/01/04/metasploit-meterpreter-and-nat/

**Comment by gwillcox-r7** [comment]
Going to close this as @bcoles posted a solution and I haven't heard any updates since. If your still having an issue, feel free to comment and I'll look into reopening this issue.
