### ISSUE TITLE
Problem backdooring telegram apk

### ISSUE THREAD

**Issue by adilobob** [rapid7/metasploit-framework#15276]
## Summary
I want to use telegram app to create a backdoor for android device. The injection is successful and the app can be installed in my device. The problem withe telegram app is that i recieve an error: API_ID_PUBLISHED_FLOOD.
I know it's about telegram policy about using their api ,so ihave to request my own api. I don't have an idea how to use the api in this case.
Is there any way to bypass this problem?

**Comment by V3rB0se** [comment]
this isn't related to Metasploit framework [It is forbidden to pass this value to third parties](https://github.com/NixOS/nixpkgs/issues/55271)
