### ISSUE TITLE
Run the command sudo ruby elm327_relay.rb -s /dev/ttyUSB0 but get nothing response

### ISSUE THREAD

**Issue by chenxiaohe** [rapid7/metasploit-framework#15308]
## Steps to reproduce

How'd you do it?

1.  run with command `sudo dmesg |grep ttyS*`
![image](https://user-images.githubusercontent.com/20987383/121118198-06acf500-c84c-11eb-87b2-1dd03e9f990f.png)

2. run with command `cd /usr/share/metasploit-framework/tools/hardware`
3. run with command `sudo ruby elm327_relay.rb -s /dev/ttyUSB0`

## Were you following a specific guide/tutorial or reading documentation?

I follow this guide  `https://www.rapid7.com/blog/post/2017/02/08/car-hacking-on-the-cheap/`

## Expected behavior

after run with command  `sudo ruby elm327_relay.rb -s /dev/ttyUSB0` , it show us `Connected. Relay is up and running...` just like the guide 
![image](https://user-images.githubusercontent.com/20987383/121117909-81294500-c84b-11eb-85bf-74760bd17544.png)

## Current behavior

after run with command  `sudo ruby elm327_relay.rb -s /dev/ttyUSB0` , it show us nothing and dosen't abort until I shut it down manually 
![image](https://user-images.githubusercontent.com/20987383/121118715-ecbfe200-c84c-11eb-80fa-c0f3ea57a3a9.png)
![image](https://user-images.githubusercontent.com/20987383/121118744-f9443a80-c84c-11eb-8d1a-df5373d3ce99.png)

### Metasploit version

Framework: 6.0.46-dev

**Comment by pbarry-r7** [comment]
Hi, @chenxiaohe.  The Hardware Bridge code isn't maintained these days.  Closing as such.
