### ISSUE TITLE
我如何卸载metasploiy framework 6.0.46?它始终提示我需要6.0.46的msi安装包，同时还阻止更新，从官网没找到46版的安装包

### ISSUE THREAD

**Issue by Benson3020955820** [rapid7/metasploit-framework#15336]
[](url)

**Comment by adfoster-r7** [comment]
Please run the installer as an administrator, and ensure that A/V is disabled on your windows machine :+1:

Alternatively, running Metasploit framework from a Kali VM may be an easier approach
