### ISSUE TITLE
Increase Upload/Download timeouts in Meterpreter

### ISSUE THREAD

**Issue by init5-SF** [rapid7/metasploit-framework#15353]
Hello,

How do I increase the timeout for actions like this:
```
meterpreter > upload /opt/ops/sharphound.exe
[*] uploading  : /opt/ops/sharphound.exe -> sharphound.exe
[-] Error running command upload: Rex::TimeoutError Operation timed out.
```
Thanks!

**Comment by h00die** [comment]
why not use the bloodhound/sharphound post module?

**Comment by init5-msft** [comment]
> why not use the bloodhound/sharphound post module?

I do, sharphound.exe in this case is just an example.
Most of the time I am uploading/downloading custom binaries and this is when it fails. Same thing happens when I PowerShell_Import a big script (i.e. PowerView).

**Comment by zeroSteiner** [comment]
Have you tried the global (get|set)_timeouts commands? The Comm timeout value might help in this case.
