### ISSUE TITLE
New method to capture screen on Android

### ISSUE THREAD

**Issue by ghost** [rapid7/metasploit-framework#15373]
The function "screenshot" in android meterpreter is capturing the current activity's screen buffer and saving it to bitmap.

However,this way is limited by android sandbox(When I want to capture another activity snap) . Thus, it needs root.

So, the best way to capture any screen without root is to use MediaProjectionManager interface(it opened in android 5.0 and later).

It just pops up a "permission asking" and later saves bitmap like old way.

Do you have any idea about adding this little function?

reference:https://github.com/goodbranch/ScreenCapture

**Comment by V3rB0se** [comment]
bump
