### ISSUE TITLE
auxiliary/admin/mysql/mysql_sql: Auxiliary failed: NoMethodError undefined method `encoding' for nil:NilClass

### ISSUE THREAD

**Issue by asathish2k** [rapid7/metasploit-framework#15387]
Auxiliary failed: NoMethodError undefined method `encoding' for nil:NilClass
![Screenshot from 2021-07-03 20-54-27](https://user-images.githubusercontent.com/50549378/124359068-d2daaa80-dc12-11eb-80ce-d06961716146.png)

**Comment by adfoster-r7** [comment]
Looks like this is the shield room on HTB?

**Comment by bcoles** [comment]
https://github.com/rapid7/metasploit-framework/issues/16387#issuecomment-1080416902
