### ISSUE TITLE
I deleted everything and now everything is broken

### ISSUE THREAD

**Issue by yoram123** [rapid7/metasploit-framework#15388]
hello, i was trying to downgrade ruby to version 1.9.3 so i deleted ruby completely from my machine. 
rm -rf /usr/local/lib/ruby
rm -rf /usr/lib/ruby
rm -f /usr/local/bin/ruby
rm -f /usr/bin/ruby
rm -f /usr/local/bin/irb
rm -f /usr/bin/irb
rm -f /usr/local/bin/gem
rm -f /usr/bin/gem

after that i tried to install again and currently my version is -
>ruby -v
ruby 2.7.2p137 
now gem and msfconsoe and pattern_create for example doesnt work all with this error - 
Traceback (most recent call last):
        2: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- did_you_mean (LoadError)

also - rvm isnt working properely 
>type rvm | head -n 1
rvm is hashed (/root/.rvm/bin/rvm)
i can fix it with 
>source /etc/profile.d/rvm.sh
but it works only for the current terminal
i dont know what to do, is the best solution is to uninstall everything and than install again? if so how it is a smart way to it?

**Comment by bcoles** [comment]
Generally it is better to purge your operating system packages rather than vaporize everything with `rm`.

Once you've installed Ruby and Rubygems for your system you will also need to install the Ruby gems required by Metasploit. If you're using Metasploit cloned from the git repository then you can do this with `bundle install` from within the metasploit directory.

Or, if you're using the metasploit-framework package for your operating system then you could try reinstalling the package.

**Comment by yoram123** [comment]
when i run 
>ruby -v 
i get the version ruby 2.7.2p137
but when trying to run ruby i get the same error as i got from running metasploit and gem 
2: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- did_you_mean (LoadError)
also, i cant run bundle install due to the same error

**Comment by bcoles** [comment]
You may need to also install Rubygems. Then `gem install did_you_mean`. Then install the bundler gem.

**Comment by yoram123** [comment]
thank you, i upgraded ruby and it worked for me 
>apt-get upgrade ruby 
everything is working as before
