### ISSUE TITLE
Meterpreter Does Not Currently Check if the User Is SYSTEM When getsystem Is Run

### ISSUE THREAD

**Issue by gwillcox-r7** [rapid7/metasploit-framework#15381]
## Steps to reproduce

How'd you do it?

1. Get a Meterpreter shell on a Windows machine as `SYSTEM`
2. Run `getsystem`

## Were you following a specific guide/tutorial or reading documentation?

Found whilst doing unrelated research into improving some library code.

## Expected behavior

Meterpreter should immediately stop and realize that the current session is already `SYSTEM`, so there is no need to elevate permissions as nothing would change.

## Current behavior

Meterpreter attempts to elevate its privileges again, which results in output similar to the following:

```
meterpreter > getsystem
[-] stdapi_sys_config_getprivs: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
[-] Named Pipe Impersonation (RPCSS variant)
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > 
```

### Metasploit version

Framework: 6.0.51-dev-95e5830bc8
Console: 6.0.51-dev-95e5830bc8

**Comment by gwillcox-r7** [comment]
For reference the code that would need to be updated is the `cmd_getsystem` code defined at https://github.com/rapid7/metasploit-framework/blob/04e8752b9b74cbaad7cb0ea6129c90e3172580a2/lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb#L75

**Comment by Nzarite** [comment]
@gwillcox-r7 hey I think I got the bug and I can do some resolutions for it but I am a newbie on open source. Can you help me with how to begin? I think my solution could work.

**Comment by gwillcox-r7** [comment]
@Nzarite Sure, if you have Slack feel free to jump on at https://join.slack.com/t/metasploit/shared_invite/zt-juutactu-xHoKE3ii7vdmuleDIXfaAw and I can help walk you through getting set up and common pitfalls :) Username should be `gwillcox-r7`
