### ISSUE TITLE
Can someone help me fix metasploit?

### ISSUE THREAD

**Issue by supernuts** [rapid7/metasploit-framework#15427]
I'd rather not revert my VM, but I somehow broke Metasploit. I was doing some tryhackme labs and I changed something related to rubygems to try and get a program working (it didn't). Someone had suggested to change the version number in a file to get an app to work but it didn't work, so all I did was change one number. Much later I tried launching Metasploit but now am getting errors and I suspect it's the file I changed before but can't remember what I did and can't seem to find help on google. Here are the errors I get.

```
# msfconsole
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.

bundle install
Could not locate Gemfile
```

I tried updating ruby and gems but nothing seems to be working.

**Comment by bcoles** [comment]
The answer to your problems is to do the opposite of whatever you did to break your setup.

> Could not locate Gemfile

`bundle install` needs to be run from within the Metasploit root directory where there is a Gemfile present.

Any additional help will require knowledge of how you installed Metasploit. It is impossible to give guidance on fixing a Metasploit install without knowing how it was installed.

**Comment by supernuts** [comment]
Thanks for the reply, I ran from /usr/share/metasploit-framework and it works now. Metasploit came pre-installed with the Kali VMWare ISO from the official website.
