### ISSUE TITLE
Auxiliary scanner not saving to .msf4/loot/

### ISSUE THREAD

**Issue by Sil3ntgh0st** [rapid7/metasploit-framework#15433]
I was running a scanner module on this latest version 6.0.52-dev and this is the result I'm getting. 

![Kali_msfloot](https://user-images.githubusercontent.com/36464922/125803923-5adca401-499c-480f-b247-a17de7b42806.PNG)

However, when running an older version, on a different operating system (6.0.44-dev, ParrotOS), I'm getting a different result where the file gets pasted to the .msf4/loot folder as seen in the image below

![Parrot_msfloot](https://user-images.githubusercontent.com/36464922/125804384-193e32d2-6be4-48df-957f-f1a6ec62c887.PNG)

I'd like to continue using the kali virtual machine rather than using HTB's Parrot OS since I have personalized tools on Kali. Is there a config I must do to have outputs saved to .msf4/loot/? I've asked the question on a couple of cybersecurity discords and haven't received any feedback, so I'm trying here.

Edit: Both instances are using the same exact options without errors

**Comment by bcoles** [comment]
Those are two different results. The first failed. The second was successful.

**Comment by Sil3ntgh0st** [comment]
I'm not understanding why the first one is failing. I can successfully curl the website. The options are set the same and I even connected to HTB's ovpn in-case it could be a network issue. I'd post screenshots of the run command after the "show options" output too but I wouldn't want to leak how to do the section of the module. But both options have identical inputs and one doesn't output.

**Comment by bcoles** [comment]
A common issue is failure to `set ssl true` in instances where SSL/TLS is required.

If you `set verbose true` you will see verbose output. The module will print a message indicating failure: `Nothing was downloaded. You can try to change the DEPTH parameter or verify the correct filename.` or `Server did not respond in an expected way.`.

At a guess, it is possible that the response is so large that the connection times out before retrieving the entire file, in which case you should notice a delay of approximately 15 -25 seconds, and the error `Server did not respond in an expected way.`.

If you `set HttpTrace true` you will get very verbose output - the entire HTTP request and response will be dumped to terminal. (warning: this could be very large). This may help you understand what is going wrong.

**Comment by Sil3ntgh0st** [comment]
I didn't know about the `set verbose true` bit, and yeah, I'm getting `Server did not respond in an expected way`

Appreciate the help! I'm going to close this.

**Comment by adfoster-r7** [comment]
@Sil3ntgh0st Here's a post with additional debugging/workflow tips too :+1:
https://www.rapid7.com/blog/post/2020/12/23/metasploit-tips-and-tricks-for-haxmas-2020-2/
