### ISSUE TITLE
Wmiexec module error  'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by thisguy23** [rapid7/metasploit-framework#15439]
https://github.com/rapid7/metasploit-framework/blob/d0b2ea632f017821a4b66c7f5464f99e01b164d0/modules/auxiliary/scanner/smb/impacket/wmiexec.py#L124

![image](https://user-images.githubusercontent.com/5863477/126005282-a035a5ad-b135-41c4-88d6-a46a4b0f6bed.png)

can work around by just deleting .decode('utf-8')

**Comment by thisguy23** [comment]
also need to turn off output for it to run some cmds it would seem.

**Comment by adfoster-r7** [comment]
Potentially a python2/3 error 🤔

**Comment by adfoster-r7** [comment]
@thisguy23 Would you mind testing if the PR https://github.com/rapid7/metasploit-framework/pull/15443 resolves your issue? :+1:

**Comment by thisguy23** [comment]
I'm still seeing an issue when I enable command output. It just hangs but it seems the str error I reported is fixed with that pull. thank you.

**Comment by dwelch-r7** [comment]
@thisguy23 that's weird I thought I had that problem too and _thought_ I solved it, can you provide any more information on the issue you're experiencing?
