### ISSUE TITLE
SSL Handler Not Supporting Older SSL/TLS Versions

### ISSUE THREAD

**Issue by zeroSteiner** [rapid7/metasploit-framework#15435]
I'm having an issue getting a `cmd/windows/powershell_reverse_tcp` session to be established and I tracked it down to the Reverse TCP SSL handler not supporting older TLS versions.

Some important versions:
* Metasploit host OS: Fedora 34
* Metasploit: 6.0.53-dev-09fe84faed
* Ruby's OpenSSL::VERSION: 2.1.2
* Ruby's OpenSSL::OPENSSL_VERSION: OpenSSL 1.1.1i FIPS  8 Dec 2020
* Target host OS: Windows 7 SP1
* Target host Powershell Version: 2.0

I'm basing this on the output I see in Wireshark where I can tell that the connection is being attempted:

![image](https://user-images.githubusercontent.com/2058303/125830593-c5f1203b-d955-4ca3-b53b-58b5b9077618.png)
In this image 192.168.159.11 is the Windows 7 target and 192.168.159.128 is the Metasploit host. See the Metasploit host replying with "Fatal, Description: Protocol Version".

Additionally, I can verify using `sslscan` that only TLSv1.2 and TLSv1.3 are enabled:
```
sslscan 192.168.159.128:4444
Version: 2.0.6-static
OpenSSL 1.1.1g  21 Apr 2020

Connected to 192.168.159.128

Testing SSL server 192.168.159.128 on port 4444 using SNI name 192.168.159.128

  SSL/TLS Protocols:
SSLv2     disabled
SSLv3     disabled
TLSv1.0   disabled
TLSv1.1   disabled
TLSv1.2   enabled
TLSv1.3   enabled
```

Finally, editing Rex::Socket:Ssl's `#makessl` method to add `ctx.ssl_version = :SSLv23` fixed the issue by enabling TLSv1.0 and TLSv1.1 (but oddly not SSLv3 as I thought the name would imply).

I don't think the hack I used for testing is something we'd want to incorporate into production since it's downgrading security settings. I do think it probably makes a lot of sense though to downgrade the security settings on handlers since we want to be able to receive those settings. Either way it seems like it should be a configurable setting like `SSLVersion` is for SSL client sockets. `SSLVersion` is an accepted hash parameter to `Rex::Sockets::Parameters` however it doesn't appear to have any effect on server sockets which seems like a problem.

## Steps to reproduce

1. `use payload/cmd/windows/powershell_reverse_tcp`
2. `to_handler`
3. Take the payload generated from `generate -f raw` and try to run it on the target
4. See that no session is established

**Comment by bcoles** [comment]
#14960 is probably similar
