### ISSUE TITLE
Windows 10 - No database driver installed

### ISSUE THREAD

**Issue by Kazem-ma79** [rapid7/metasploit-framework#15453]
Installed latest version of MSF and everything works fine expect db_status tells:
[-] No database driver installed.

Tried `msfdb init` and it gives "Attempting to start MSF web service...failed" but database service has started and working fine.
Also db_connect not working (no driver installed error).

metasploit version: 6.0.35-dev
os: windows 10 21H1 - 19043

**Comment by GAYJx** [comment]
I also encountered this problem,but i have installed pgsql.

**Comment by Kazem-ma79** [comment]
Anyway to fix ?

**Comment by Kazem-ma79** [comment]
UP
