### ISSUE TITLE
Can build from source but can't run msfconsole on ubuntu 20

### ISSUE THREAD

**Issue by STashakkori** [rapid7/metasploit-framework#15475]
I pull down source and can build just fine on Ubuntu 20. However have tried on both branch master and gh-page to run ./msfconsole. I get the following error:

<Added by Sina --> Lots of similar warnings above here>
/usr/lib/ruby/2.7.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/var/lib/gems/2.7.0/gems/psych-4.0.1/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
Traceback (most recent call last):
	18: from ./msfconsole:18:in `<main>'
	17: from ./msfconsole:18:in `require'
	16: from /home/sinadev/omni/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
	15: from /home/sinadev/omni/metasploit-framework/lib/msfenv.rb:17:in `require'
	14: from /home/sinadev/omni/metasploit-framework/config/environment.rb:2:in `<top (required)>'
	13: from /home/sinadev/omni/metasploit-framework/config/environment.rb:2:in `require'
	12: from /home/sinadev/omni/metasploit-framework/config/application.rb:1:in `<top (required)>'
	11: from /home/sinadev/omni/metasploit-framework/config/application.rb:1:in `require'
	10: from /var/lib/gems/2.7.0/gems/railties-5.2.6/lib/rails.rb:14:in `<top (required)>'
	 9: from /var/lib/gems/2.7.0/gems/railties-5.2.6/lib/rails.rb:14:in `require'
	 8: from /var/lib/gems/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:3:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:3:in `require'
	 6: from /usr/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'
	 5: from /usr/lib/ruby/2.7.0/yaml.rb:4:in `require'
	 4: from /usr/lib/ruby/2.7.0/psych.rb:20:in `<top (required)>'
	 3: from /usr/lib/ruby/2.7.0/psych.rb:20:in `require'
	 2: from /usr/lib/ruby/2.7.0/psych/parser.rb:2:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/psych/parser.rb:33:in `<module:Psych>'
/usr/lib/ruby/2.7.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)

Please assist. Thank you so much

**Comment by adfoster-r7** [comment]
From the metasploit-framework folder, does this work for you?
```
bundle install
bundle exec ./msfconsole
```

**Comment by STashakkori** [comment]
Thank you @adfoster-r7 

Same mismatch Mark issue it seems.

bundle install works. bundle exec ./msfconsole does not work. I get this:

/var/lib/gems/2.7.0/gems/psych-4.0.1/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/usr/lib/ruby/2.7.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/var/lib/gems/2.7.0/gems/psych-4.0.1/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
bundler: failed to load command: ./msfconsole (./msfconsole)
TypeError: superclass mismatch for class Mark
  /usr/lib/ruby/2.7.0/psych/parser.rb:34:in `<class:Parser>'
  /usr/lib/ruby/2.7.0/psych/parser.rb:33:in `<module:Psych>'
  /usr/lib/ruby/2.7.0/psych/parser.rb:2:in `<top (required)>'
  /usr/lib/ruby/2.7.0/psych.rb:20:in `require'
  /usr/lib/ruby/2.7.0/psych.rb:20:in `<top (required)>'

**Comment by adfoster-r7** [comment]
Looks like there might be a problem with your gems, does this workaround help? https://github.com/rapid7/metasploit-framework/issues/12763#issuecomment-569392505

**Comment by STashakkori** [comment]
Roger that mothership. That did the trick.

Thank you @adfoster-r7 and take care. Signing off for now

**Comment by adfoster-r7** [comment]
Thanks! :+1:
