### ISSUE TITLE
Payload executes, but nothing shows up in msfconsole

### ISSUE THREAD

**Issue by yesimxev** [rapid7/metasploit-framework#15504]
## Steps to reproduce

How'd you do it?

1. Create a payload with msfvenom (reverse_tcp, reverse_http/s exe, ps1)
2. Set up a listener with multi/handler
3. Execute payload

Win7 x86 (VM, and 2 bare metals) to Kali desktop, or NetHunter

## Expected behavior

Session should show up

## Current behavior

Nothing happens

### Metasploit version

Framework: 6.0.47-dev
Console  : 6.0.47-dev

## Additional Information
Tried various ways and payloads, using Kali desktop and NetHunter. I can see msf auth fail but actually the db seems right (could reinit)
![Screenshot_20210731-113938_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737510-4005a4d0-24e4-4ee1-8cf0-7992628a835d.png)
![Screenshot_20210731-111630_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737508-7a69c093-21e5-4af2-940a-119192d6f589.png)
![Screenshot_20210731-113943_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737513-8e106b87-f765-405c-a2a3-44c635f078aa.png)
![Screenshot_20210731-113954_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737514-94f9f37b-8bfa-406a-9335-73cfe0acddf2.png)
![Screenshot_20210731-114002_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737517-3faeae09-15d0-46aa-8660-391752004c87.png)
![Screenshot_20210731-114006_NetHunter_Terminal](https://user-images.githubusercontent.com/23633302/127737521-0c6bc7c1-6237-40d2-88e2-4ff8c98d1133.png)

**Comment by timwr** [comment]
I think this is Kali nethunter not termux btw. Maybe a networking problem? What happens if you connect to the handler socket with netcat?

**Comment by yesimxev** [comment]
This is just an ssh session to Kali desktop from NetHunter terminal. Sorry for the confusion, replacing the screenshots now
