### ISSUE TITLE
post/windows/gather/enum_domains crashes

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#15541]
## Steps to reproduce

Run the `windows/gather/enum_domains` module against a psexec session with a windows 2012 r2 target host. I haven't verified with if the host/user impacts the crash:

```
use windows/gather/enum_domains
run session=-1
```

Metasploit 6:

```
msf6 > use windows/gather/enum_domains
msf6 post(windows/gather/enum_domains) > run session=1


[-] ERROR_NO_BROWSER_SERVERS_FOUND
[-] Post failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /Users/user/Documents/code/metasploit-framework/modules/post/windows/gather/enum_domains.rb:27:in `run'
[*] Post module execution completed
```

## Additional Information

```
 version
Framework: 6.1.0-dev-83a1ff750a
Console  : 6.1.0-dev-83a1ff750a
```

**Comment by bcoles** [comment]
```diff
diff --git a/modules/post/windows/gather/enum_domains.rb b/modules/post/windows/gather/enum_domains.rb
index 1921c36e24..63160e2f89 100644
--- a/modules/post/windows/gather/enum_domains.rb
+++ b/modules/post/windows/gather/enum_domains.rb
@@ -23,6 +23,7 @@ class MetasploitModule < Msf::Post
 
   def run
     domains = net_server_enum(SV_TYPE_DOMAIN_ENUM)
+    return if domains.nil?
 
     domains.each do |domain|
       print_status("Enumerating DCs for #{domain[:name]}")
```

Why it fails may be a separate issue.

**Comment by bcoles** [comment]
`ERROR_NO_BROWSER_SERVERS_FOUND` (`0x000017E6 [6118]`) constants defined here:

https://github.com/rapid7/metasploit-framework/blob/50c1f7b77547f544ab0a1c727c534ae35433bc57/lib/msf/core/post/windows/net_api.rb#L19

https://github.com/rapid7/metasploit-framework/blob/50c1f7b77547f544ab0a1c727c534ae35433bc57/lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/api_constants.rb#L35909

Defined by [Microsoft docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d) as "The list of servers for this workgroup is not currently available".

From [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/api/lmserver/nf-lmserver-netserverenum#remarks): "The NetServerEnum function depends on the browser service being installed and running. If no browser servers are found, then NetServerEnum fails with ERROR_NO_BROWSER_SERVERS_FOUND."

The issue can be reproduced by disabling `Computer Browser` service:

![Computer Browser](https://user-images.githubusercontent.com/434827/151526253-35ec410d-e79f-47c6-84aa-a18d9f983f03.png)


> against a psexec session with a windows 2012 r2 target host

As for why you encountered this error on Windows 2012, I'm not sure. Was the `Computer Browser` service dead? Is the issue reproducable on the target system?

Presumably your psexec session was a Meterpreter session.


> I haven't verified with if the host/user impacts the crash:

From [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/api/lmserver/nf-lmserver-netserverenum#remarks): "No special group membership is required to successfully execute the NetServerEnum function."

The module queries `SV_TYPE_DOMAIN_ENUM`:

https://github.com/rapid7/metasploit-framework/blob/50c1f7b77547f544ab0a1c727c534ae35433bc57/modules/post/windows/gather/enum_domains.rb#L25

https://github.com/rapid7/metasploit-framework/blob/50c1f7b77547f544ab0a1c727c534ae35433bc57/lib/msf/core/post/windows/net_api.rb#L10

Defined by [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/api/lmserver/nf-lmserver-netserverenum) as "The primary domain."

This should return at least one domain (ie, not `nil`) on any networked system regardless of whether it is domain joined or in a workgroup.

The `post/windows/gather/enum_domains` module uses Railgun and receives `ERROR_NO_BROWSER_SERVERS_FOUND` directly from the OS. As this is unrecoverable and the module already prints an error message (as a result of `print_error` in the Post mixin), I'm inclined to simply make the module bail out.

https://github.com/rapid7/metasploit-framework/blob/50c1f7b77547f544ab0a1c727c534ae35433bc57/lib/msf/core/post/windows/net_api.rb#L75
