### ISSUE TITLE
MSFRPCD json-rpc server don't work

### ISSUE THREAD

**Issue by ilovesusu** [rapid7/metasploit-framework#15569]
## Steps to reproduce

How'd you do it?

1. msfrpcd
```
# msfrpcd -U msf -P msf -f                                                                                                                        1 ⨯
[*] MSGRPC starting on 0.0.0.0:55553 (SSL):Msg...
[*] MSGRPC ready at 2021-08-18 17:39:32 +0800.
```
2. msfrpcd
```
# msfrpcd -U msf -P msf -j -f
[-] It doesn't appear msfdb has been run; please run 'msfdb init' first.
```
or
```
# msfrpcd -j -f                                                                                                                                   1 ⨯
[-] It doesn't appear msfdb has been run; please run 'msfdb init' first.

```

os:Kali GNU/Linux Rolling

merasploit version

Framework: 6.1.0-dev
Console  : 6.1.0-dev

How Do I start MSFRPCD json-rpc server

**Comment by adfoster-r7** [comment]
From the error message, it looks like `msfdb init` is required to be run first. Were you able to run that command successfully?

**Comment by ilovesusu** [comment]
first,run `openssl req -newkey rsa:2048 -nodes -keyout msf-ws-key.pem -x509 -days 365 -out msf-ws-cert.pem` in ~/.msf4/
then ,run `msfrpcd -U msf -P msf -f `  it's work
