### ISSUE TITLE
Subnet forward

### ISSUE THREAD

**Issue by Huibuh2010** [rapid7/metasploit-framework#15576]
Hey Folks,

i have successfully test a lot of my Lab but now i will learn next Step -> How to forward a Subnet.

Portforwarding on one Target works fine but no Subnet Route.

If i use Autoroute Modul, Route print looks Ok but i cant ping any of the 3 Targets...

IPv4 Active Routing Table
Subnet 192.168.1.0
Netmask 255.255.255.0
Gateway Session 2

![Unbenannt](https://user-images.githubusercontent.com/83202082/130185011-c08d3416-a1ce-4cc5-9f46-0245ba7d34b7.PNG)

**Comment by adfoster-r7** [comment]
Instead of `ping` you can use metasploit modules which pivot through the 192.168.179.99 host. For example:

```
use scanner/portscan/tcp
run rhosts=192.168.1.152 ports=1-1024
```

**Comment by Huibuh2010** [comment]
> 
> 
> Instead of `ping` you can use metasploit modules which pivot through the 192.168.179.99 host. For example:
> 
> ```
> use scanner/portscan/tcp
> run rhosts=192.168.1.152 ports=1-1024
> ```

Hey Foster,

thanks but i didnt see the result.

```
msf6 auxiliary(scanner/portscan/tcp) > run rhosts=192.168.1.152 ports=445

[*] 192.168.1.152:         - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by Huibuh2010** [comment]
after days intense google and view tutorials, now i found one nad it works :)

https://axontechnologies.com/how-to-implement-pivoting-and-relaying-techniques-using-meterpreter.html

**Comment by adfoster-r7** [comment]
Awesome, good to hear!

Will close this issue for now :+1:
