### ISSUE TITLE
Metasploit cache files

### ISSUE THREAD

**Issue by NightRaidGamer** [rapid7/metasploit-framework#15581]
when metasploit is started for the first time, it creates a folder called .msf4, in users, how do I change the location of this folder? for example I want to create in the root of the metasploit folder

**Comment by adfoster-r7** [comment]
You can set an environment variable `MSF_CFGROOT_CONFIG` to change the directory

https://github.com/rapid7/metasploit-framework/blob/5f6112766ad19e309f6a25a28b4c7e6266b89868/lib/msf/base/config.rb#L30-L34

**Comment by NightRaidGamer** [comment]
> directory?

give me an example, how would the lines look if the location of the .msf4 was in the "metasploit-framework" folder?

**Comment by adfoster-r7** [comment]
I'm not sure where your metasploit-framework folder is located, or what operating system you're using.

This is a potential solution for ubuntu. Create the folder where you want to store your configuration folder:
```
mkdir /Users/user/Documents/metasploit-framework/.msf4-config
```

Update your `.bashrc` file to with this line to configure metasploit to use your new config folder
```
export MSF_CFGROOT_CONFIG=/Users/user/Documents/metasploit-framework/.msf4-config
```

Open a new terminal, run `msfconsole`, and verify the new config folder is used

**Comment by NightRaidGamer** [comment]
> I'm not sure where your metasploit-framework folder is located, or what operating system you're using.
> 
> This is a potential solution for ubuntu. Create the folder where you want to store your configuration folder:
> 
> ```
> mkdir /Users/user/Documents/metasploit-framework/.msf4-config
> ```
> 
> Update your `.bashrc` file to with this line to configure metasploit to use your new config folder
> 
> ```
> export MSF_CFGROOT_CONFIG=/Users/user/Documents/metasploit-framework/.msf4-config
> ```
> 
> Open a new terminal, run `msfconsole`, and verify the new config folder is used

thanks it worked I used: SET MSF_CFGROOT_CONFIG=C:\MetasploitDevEnvironment\metasploit-framework\.msf4
