### ISSUE TITLE
Update of sessions table on load stdapi

### ISSUE THREAD

**Issue by russokiwi** [rapid7/metasploit-framework#15615]
Defender AMSI/ETW even though bypassed initially detects the instant loading of stdapi.  If you delay it however, it works fine and doesn't trigger.  The problem is 2 things.  1 the sessions table view doesn't get updated even if stdapi is loaded (later) and it's really hard to guess which session is which when you've got like 20 or more.  Could the sessions table get updated on load stdapi of each session? The 2nd thing is automation.  I'd like to have an autorunscript that on connection waits 20 seconds and then loads stdapi.  How is this achievable (I know sleep command is reserved for something else)..  Thanks!

**Comment by timwr** [comment]
Deja vu https://github.com/rapid7/metasploit-framework/issues/13243 :trollface:

**Comment by FunnyWolf** [comment]
https://github.com/rapid7/metasploit-framework/blob/a1eef6a2c194284fe5e90be602eaa6417db51651/lib/msf/base/sessions/meterpreter.rb#L170

![image](https://user-images.githubusercontent.com/17685281/131289533-acd01267-1afa-4db3-9a5c-5d1d4959f1b6.png)

msf only update sysinfo when AutoLoadStdapi and AutoSystemInfo is True.

**Comment by russokiwi** [comment]
awesome! thanks very much!

**Comment by smcintyre-r7** [comment]
The other part of your question was about adding a delay. You're right the `sleep` Meterpreter command will disconnect the session, wait the specified number of seconds and then reconnect. If you're writing a Meterpreter or RC script, you should be able to embed a Ruby sleep though doing:

```
msf6 post(linux/gather/gnome_keyring_dump) > cat /tmp/test.rc
[*] exec: cat /tmp/test.rc

date
<ruby>
sleep 10
</ruby>
date
msf6 post(linux/gather/gnome_keyring_dump) > resource /tmp/test.rc
[*] Processing /tmp/test.rc for ERB directives.
resource (/tmp/test.rc)> date
[*] exec: date

Wed Sep  1 10:19:01 AM EDT 2021
[*] resource (/tmp/test.rc)> Ruby Code (9 bytes)
resource (/tmp/test.rc)> date
[*] exec: date

Wed Sep  1 10:19:12 AM EDT 2021
msf6 post(linux/gather/gnome_keyring_dump) >
```

**Comment by russokiwi** [comment]
perfect! we live another day!  thanks again)
