### ISSUE TITLE
Installed gems are not found

### ISSUE THREAD

**Issue by sfjuocekr** [rapid7/metasploit-framework#15641]
`
msf6 > sudo gem install lab
[*] exec: sudo gem install lab

Building native extensions. This could take a while...
Successfully installed aliyun-sdk-0.8.0
Successfully installed fog-aliyun-0.3.19
Successfully installed fog-1.36.0
Successfully installed lab-0.2.7
Parsing documentation for aliyun-sdk-0.8.0
Installing ri documentation for aliyun-sdk-0.8.0
Parsing documentation for fog-aliyun-0.3.19
Installing ri documentation for fog-aliyun-0.3.19
Parsing documentation for fog-1.36.0
Installing ri documentation for fog-1.36.0
Parsing documentation for lab-0.2.7
Installing ri documentation for lab-0.2.7
Done installing documentation for aliyun-sdk, fog-aliyun, fog, lab after 26 seconds
4 gems installed
msf6 > load lab
[-] Failed to load plugin from /opt/metasploit-framework/embedded/framework/plugins/lab: WARNING: Lab gem not found, Please 'gem install lab'
`

Am I doing something wrong?

**Comment by adfoster-r7** [comment]
Are you following a tutorial/resource? It's not entirely clear what your intent is :+1:

**Comment by sfjuocekr** [comment]
No, I was curious of what the lab was and typed: load lab.

But this holds true for all the gems that you install manually.
