### ISSUE TITLE
How can i save to variable username in <ruby> </ruby>

### ISSUE THREAD

**Issue by ForDockerImage** [rapid7/metasploit-framework#15648]
Hello,
maybe there are people who can help me.

```
<ruby>
run_single("getuid")
</ruby>
```

In this example how can I store resulte into a variable? 
The function run_single() only returns true/false,  there are other functions that return the result to a variable ??
PS: I WILL BE VERY GRATEFUL FOR AN EXAMPLE :)

**Comment by adfoster-r7** [comment]
Resource file:
```
$ cat resource.rc 
<ruby>
result = client.sys.config.getuid
puts "The result was: #{result}"
</ruby>
```

msfconsole:
```
meterpreter > resource ./resource.rc
[*] Processing ./resource.rc for ERB directives.
[*] resource (./resource.rc)> Ruby Code (67 bytes)
The result was: www-data @ 544acefb4380 (uid=33, gid=33, euid=33, egid=33)
```

Hope this helps :+1:

**Comment by adfoster-r7** [comment]
For clarity;  knew which method to call as the `getuid` comment is implemented here as the naming convention for console commands in msfconsole are `def cmd_{COMMAND_NAME_HERE}`

https://github.com/rapid7/metasploit-framework/blob/50330c155957b00528d4b6c6ac16ba55fb6e170a/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb#L464-L469

The resource file interacts with the 'client' object, which is your current session.

Here's examples of interacting with sessions, looping, if statements, etc:
```ruby
cat resource.rc
<ruby>
puts "All session uids:"
framework.sessions.each_value do |session|
  result = session.sys.config.getuid
  puts "The result was: #{result}"
end

puts "Last session uid:"
last_session = framework.sessions.get(-1)
if last_session
  result = last_session.sys.config.getuid
  puts "The result was: #{result}"
else
  puts "No last active session"
end
</ruby>
```
