### ISSUE TITLE
MeterpreterPrompt user and hostname variables

### ISSUE THREAD

**Issue by totolastiko** [rapid7/metasploit-framework#15672]
Hello, 

I try to customize meterpreter prompt, and use %U to have user information about current session

ex : 
%U on meterpreter linux : 
root @ "hostname" (uid=0, gid=0, euid=0, egid=0)

I find it too long and would just like to have as information user@hostname (without uid,gid,euid,egid informations)

Do you think it's possible to have new variable(s) in order to have just "user@hostname" and / or "user" and "hostname" in set MeterpreterPrompt variables please ?

Best Regards,
Totolastiko.

**Comment by zeroSteiner** [comment]
That should be what `%U` and `%H` do already. Are you saying that's not the case? See PR #12438 for more information on the custom Meterpreter prompt.

**Comment by zeroSteiner** [comment]
Yeah, I looked into it and this is a bug. The mettle implementation of Metepreter returns more information in the string value returned by the `sys.config.getuid` function which is ultimately where the `%U` comes from. This is an inconsistency that should be addressed.

**Comment by zeroSteiner** [comment]
The PHP meterpreter also returns more information in that field. Python and Java do what I would have expected which is just return the string value of the username.

```
msf6 payload(linux/x64/meterpreter/reverse_tcp) > sessions

Active sessions
===============

  Id  Name  Type                      Information                                                                       Connection
  --  ----  ----                      -----------                                                                       ----------
  3         meterpreter java/linux    smcintyre @ localhost.localdomain                                                 192.168.159.128:4444 -> 192.168.159.128:49050 (192.168.159.128)
  4         meterpreter python/linux  smcintyre @ localhost.localdomain                                                 192.168.159.128:4444 -> 192.168.159.128:49052 (192.168.159.128)
  5         meterpreter php/linux     smcintyre (1000) @ localhost.localdomain                                          192.168.159.128:4444 -> 192.168.159.128:49060 (192.168.159.128)
  6         meterpreter x64/linux     smcintyre @ localhost.localdomain (uid=1000, gid=1000, euid=1000, egid=1000) ...  192.168.159.128:4444 -> 192.168.159.128:49062 (192.168.159.128)

msf6 payload(linux/x64/meterpreter/reverse_tcp) > pry
[*] Starting Pry shell...
[*] You are in the "payload/linux/x64/meterpreter/reverse_tcp" module object

[1] pry(#<#<Class:0x000000000b4d0de0>>)> framework.sessions.values.map { |session| session.sys.config.getuid }
=> ["smcintyre", "smcintyre", "smcintyre (1000)", "smcintyre @ localhost.localdomain (uid=1000, gid=1000, euid=1000, egid=1000)"]
[2] pry(#<#<Class:0x000000000b4d0de0>>)>
```

I have everything I need to fix this, thanks for reporting it. I'm going to switch it from a feature suggestion to a bug.

**Comment by timwr** [comment]
I wonder if in the future it would be worth having a new explicit sys.config.getuser or sys.config.getusername function. I guess getenv(USER) works for now.
I'll go ahead and land the two meterpreter pull requests to keep things consistent.
