### ISSUE TITLE
Please do update the metasploit RPC Documentation

### ISSUE THREAD

**Issue by parrothacker1** [rapid7/metasploit-framework#15687]
## Summary
So I had written a metasploit RPC client for rust. But when I looked into pymetasploit3 for reference,I found that there are some API fucntions which are not in RPC Documentation and I checked if they work and they do work. So please do update the Documentation with all new API functions too

**Comment by adfoster-r7** [comment]
Which functions / use cases / examples would you like documented?

**Comment by parrothacker1** [comment]
The db API functions . 'db.hosts' etc. I need to write a description upon these. Rest are the same . There were some new in modules group which i figured out except the result method.So if you tell about it in the comment section it would be nice

**Comment by adfoster-r7** [comment]
There's inline comments in the source code for using `db.hosts` here: https://github.com/rapid7/metasploit-framework/blob/b7fd61c92a085fcc6cc98a57857295fa2e0cd75f/lib/msf/core/rpc/v10/rpc_db.rb#L370-L394
As well as generated documentation here: https://rapid7.github.io/metasploit-framework/api/Msf/RPC/RPC_Db.html#rpc_hosts-instance_method

Is that the documentation useful for your scenario?

**Comment by parrothacker1** [comment]
Yeah perfect . Thank you !
