### ISSUE TITLE
Windows setup installs to E: every time

### ISSUE THREAD

**Issue by Nightblade** [rapid7/metasploit-framework#15688]
## Steps to reproduce

1. Download latest Windows installer https://windows.metasploit.com/metasploitframework-latest.msi
2. Run the downloaded `.msi` file
3. Click `Next` x2
3. Watch as it installs to `E:\metasploit-framework` instead of `C:\`.  It also ignores whatever install dir you select

## Were you following a specific guide/tutorial or reading documentation?

no

## Expected behavior

Should install to selected directory.

## Current behavior

Installs to `E:\metasploit-framework` every time.

### Metasploit version

`6.1.7 Setup Wizard`
Framework: `6.1.7-dev-b7fd61c92a085fcc6cc98a57857295fa2e0cd75f`
Console  : `6.1.7-dev-b7fd61c92a085fcc6cc98a57857295fa2e0cd75f`

## Additional Information

Window Pro x64 

C: has 257 GB free
E: has 472 GB free

**Comment by bcoles** [comment]
Issues with the Metasploit installer are tracked on the `metasploit-omnibus` repository.

This is being tracked over here: rapid7/metasploit-omnibus#115.
