### ISSUE TITLE
NOT WORKING IN MY CASE. ANDROID 11

### ISSUE THREAD

**Issue by HarshCodesYT** [rapid7/metasploit-framework#15741]
I ASLO SHARED THE APP ON ANDROID 9 VERSION STILL NOT WORKING.
GAVE ALL PERMISSIONS BUT SESSION IS NOT GETTING.

DOES ANYONE HAS ANY SUGGESTION????

**Comment by gwillcox-r7** [comment]
Please unlock your caps lock in future and use the template as requested. Closing due to lack of information and for not following the template as requested.
