### ISSUE TITLE
Metasploit Pro - Error

### ISSUE THREAD

**Issue by maroevtech** [rapid7/metasploit-framework#15789]
Hi Rapid7,

Good day!

Seeking for your assistance. I did some version update from 4.19 April 16, 2021 to 4.20 Sept 27, 2021.
When I clicked one of my project I received an error. Some projects are working but the others are not.
Please check the photo below for more information.

![image](https://user-images.githubusercontent.com/92976686/138419180-d13d9511-471f-46c2-ae40-89daab98904c.png)

Thank you.

Regards,

**Comment by gwillcox-r7** [comment]
This is a issue tracker for Metasploit Framework. We do not provide support for Metasploit Pro here or via Slack. Please contact your assigned support provider at https://www.rapid7.com/for-customers/ for help with Metasploit Pro as we are unable to provide assistance via these channels.
