### ISSUE TITLE
Unable to run msf on windows 10

### ISSUE THREAD

**Issue by rosariokt** [rapid7/metasploit-framework#15817]
Hi

I cannot run metasploit on windows 10 machine 

My Machine : Windows 10
Metasploit-Framework v6.1.12

My Logs

> $ msfconsole
C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        48: from C:/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `<main>'
        47: from C:/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `require'
        46: from C:/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `<top (required)>'
        45: from C:/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `require'
        44: from C:/metasploit-framework/embedded/framework/config/environment.rb:4:in `<top (required)>'
        43: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `method_missing'
        42: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `public_send'
        41: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/application.rb:391:in `initialize!'
        40: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        39: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        38: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        37: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        36: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `call'
        35: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each'
        34: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        33: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        32: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        31: from C:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        30: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        29: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `run'
        28: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        27: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        26: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
        25: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
        24: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
        23: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
        22: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
        21: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
        20: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
        19: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
        18: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
        17: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
        16: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        15: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        14: from C:/metasploit-framework/embedded/framework/lib/msf/core/rpc/json/request.rb:1:in `<top (required)>'
        13: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        12: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        11: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/em-http-request-1.1.7/lib/em-http-request.rb:1:in `<top (required)>'
        10: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         9: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         8: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/em-http-request-1.1.7/lib/em-http.rb:1:in `<top (required)>'
         7: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         6: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         5: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         3: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         2: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
C:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)

**Comment by gwillcox-r7** [comment]
Is the AV disabled on the Windows 10 machine that you have installed Metasploit on, and it was it disabled at install? If the AV was  enabled any time after Metasploit was installed, its likely that it removed several files and therefore corrupted your install.
