### ISSUE TITLE
kali linux password problem

### ISSUE THREAD

**Issue by faran131yt** [rapid7/metasploit-framework#15827]
Hy I have a problem: i have kali linux in my asus laptop and i forgot the password how can i change it.

**Comment by bcoles** [comment]
Hello and welcome to Metasploit issue tracker. The Metasploit issue tracker is for tracking issues with Metasploit.

Kali is a Linux distribution and not related to Metasploit. If you're not using full disk encryption you can reset the root password like you would any other Linux operating system.
