### ISSUE TITLE
Notes data in database

### ISSUE THREAD

**Issue by P-T-I** [rapid7/metasploit-framework#15835]
For a research project I'm connecting directly to the postgres database and retrieving certain values for further processing; I'm currently stumbling upon the data in the notes tables. These data entries are encoded / serialized when they are stored; I'm not a ruby guy at all so I'm having a hard time figuring out how they are stored, and how they could be reverted to a string for further processing. Data looks like base64 but decoding them doesn't give me proper data to work with. 

Could anybody give me any pointers? 

My project is written in python, so I'm eventually looking for a way to decode and de-serialize the data from within the python codebase.

**Comment by adfoster-r7** [comment]
It uses a base64 serializer:
https://github.com/rapid7/metasploit_data_models/blob/06cdd2dfc637e5177f8616c8dadbca154bdc6137/app/models/mdm/note.rb#L110

Which uses also Ruby's marshal support:
https://github.com/rapid7/metasploit_data_models/blob/master/lib/metasploit_data_models/base64_serializer.rb#L57

There may be an existing Python parser which can deserialize this format for you, or writing your own is quite easy. 

If you plan to write your own, the [Ruby Marshal docs](https://ruby-doc.org/core-2.7.1/doc/marshal_rdoc.html) are quite detailed on the binary format, there's also a tutorial on how to [write your own Ruby Marshal parser](https://ilyabylich.svbtle.com/ruby-marshalling-from-a-to-z) - you would need to translate that into Python of course.

Depending on what data you're wishing to extract, you may run into issues handling the instantiation of classes etc - as out of the box there won't be an equivalent in Python. But strings, hashes, ints, arrays, etc, should be trivial.

**Comment by P-T-I** [comment]
@adfoster-r7 Thank you for your detailed answer! I'll get on this right away!

**Comment by adfoster-r7** [comment]
Awesome, good luck on your project :+1:

Closing for now
