### ISSUE TITLE
"msfconsole" instead of /opt/metasploit-framework/bin/msfconsole 

### ISSUE THREAD

**Issue by fazlialtunn** [rapid7/metasploit-framework#15836]
Hello to everyone,

My problem is very simple.I am using Macbook Pro. I installed the metasploit but when I write "msfconsole" on terminal it says "command not found" but if  I write "/opt/metasploit-framework/bin/msfconsole" it works. How can ı solve this problem? I want it to run when I type msfconsole.

**Comment by bcoles** [comment]
Add `/opt/metasploit-framework/bin/` to your PATH.

```sh
export PATH="$PATH:/opt/metasploit-framework/bin/"
```

**Comment by fazlialtunn** [comment]
> Add `/opt/metasploit-framework/bin/` to your PATH.
> 
> ```shell
> export PATH="$PATH:/opt/metasploit-framework/bin/"
> ```

Thank you very much

**Comment by fazlialtunn** [comment]
> Add `/opt/metasploit-framework/bin/` to your PATH.
> 
> ```shell
> export PATH="$PATH:/opt/metasploit-framework/bin/"
> ```

When I open a new terminal the problem strikes again. How can I make it permanent?

**Comment by bcoles** [comment]
> 
> 
> > Add `/opt/metasploit-framework/bin/` to your PATH.
> > ```shell
> > export PATH="$PATH:/opt/metasploit-framework/bin/"
> > ```
> 
> When I open a new terminal the problem strikes again. How can I make it permanent?

You'll need to set the path in your shell config. This depends on which shell you're using.

See section "Set your PATH permanently" at https://opensource.com/article/17/6/set-path-linux

This describes setting the PATH for Bash on Linux but the same principal applies for all shells.

**Comment by Stagefright071** [comment]
make a soft link fot the binary to /usr/bin
```bash
ln -s /opt/metasploit-framework/bin/msfconsole /usr/bin/msfconsole
```

**Comment by Alireza1369newi** [comment]
>

**Comment by Alireza1369newi** [comment]
> Add `/opt/metasploit-framework/bin/` to your PATH.
> 
> ```sh
> export PATH="$PATH:/opt/metasploit-framework/bin/"
> ```
> 
- [

**Comment by Alireza1369newi** [comment]
> > Add `/opt/metasploit-framework/bin/` to your PATH.
> > 
> > ```shell
> > export PATH="$PATH:/opt/metasploit-framework/bin/"
> > ```
> 
> Thank you very much

**Comment by bcoles** [comment]
> Hi, I have one question.
> 
> How I can implement this command export PATH="$PATH:/opt/metasploit-framework/bin/" to stay permanently working on my MacBook? because if I restart my MacBook I need past this command again on terminal.

Edit your shell configuration to include that line. Possibly `~/.bash_profile`. Apparently OSX also supports `/etc/paths`:

* https://stackoverflow.com/questions/22465332/setting-path-environment-variable-in-osx-permanently
