### ISSUE TITLE
New Auxiliary Module Suggestion: Discover attack surface with FullHunt.io

### ISSUE THREAD

**Issue by mazen160** [rapid7/metasploit-framework#15857]
## Summary

I built FullHunt.io, the attack surface security platform, and this week, we finally launched the FullHunt Public API. The FullHunt API can be used to discover the attack surface and public surface of all assets. We continuously scan the Internet and collect data about the attack surface of organizations around the world.

A Redditor on /r/netsec suggested an idea of a Metasploit module for Fullhunt, and it sounded great. 

FullHunt does not just collect passive data; our engines scan the Internet for exposed network services, we collect DNS records, metadata, and various data points and only show-case vetted results.

There are so many use-cases that can be possible.

**Comment by gwillcox-r7** [comment]
No update on this and we would likely need a more comprehensive overview of what such an integration would entail before we would consider integrating this in. I'm going to close this until such a proposal can be put forwards that would explain exactly how this would be integrated into Metasploit in more detail and what benefit such integration would bring over the tools that we already have in the framework.

When such a proposal is made we can consider opening this up again and explore this further.
