### ISSUE TITLE
Metasploit in Ubuntu // 

### ISSUE THREAD

**Issue by theycallmex** [rapid7/metasploit-framework#15865]
I can't get session lists, coz Handler failed to bind xxx.
i used ngrok to  turrnel and alrady install  vir.apk on android.( even so many warning)
i can't get it. where did i miss? 

i'm just script kiddy. just testing.. 
![Screenshot from 2021-11-12 16-08-58](https://user-images.githubusercontent.com/94163043/141446720-e5b3e1a3-c579-4bda-bc0a-3ef6d096ff8b.png)

## Ubuntu
##Metasploit
##Android ##Android_Hacking

**Comment by TommyDjango** [comment]
Im far from an expert so i might be totally wrong but ive picked up some tricks!
Your ngrok is been diverted to your localhost at 8080 - not the post you want.

try set the listener to 8080 and see what happens then

**Comment by bcoles** [comment]
> i can't get it. where did i miss?

The value you have set for `LHOST` is not a valid IP address for any of your network interfaces.

The options you're looking for are `ReverseListenerBindAddress` and`ReverseListenerBindPort`.

Refer to:

* https://www.corelan.be/index.php/2014/01/04/metasploit-meterpreter-and-nat/

> I can't get session lists, coz Handler failed to bind xxx.

Ctrl+C to kill the job. You can run a job in the background with `run -jz`. This will allow you to continue to use `msfconsole` while the job runs in the background.
