### ISSUE TITLE
GoLang modules could not be loaded

### ISSUE THREAD

**Issue by znre** [rapid7/metasploit-framework#15877]
## Steps to reproduce

How'd you do it?

1. Just open up metasploit that was recently updated: **msfconsole**

## Were you following a specific guide/tutorial or reading documentation?

N/A

## Expected behavior

Metasploit would open up as normal and the Go modules would load up properly. (**Go** is already installed)
![image](https://user-images.githubusercontent.com/70197545/141755068-01bf9243-9e01-479d-ac96-60bf0be636af.png)

## Current behavior

These messages started appearing when I open metasploit after I updated to the latest version using sudo apt update.
![image](https://user-images.githubusercontent.com/70197545/141755210-a247b680-4e4a-4196-a9aa-eb40e92b0aaf.png)

These are the related logs from framework.log:
![image](https://user-images.githubusercontent.com/70197545/141753586-dc95921c-d714-4378-a2a8-e803b9ab061d.png)

This is what happens when I tried running the files as suggested from framework.log:
![image](https://user-images.githubusercontent.com/70197545/141756211-c0b1ab00-17d2-4d48-bac6-c3d487942c54.png)

### Metasploit version

Framework: 6.1.14-dev
Console  : 6.1.14-dev
![image](https://user-images.githubusercontent.com/70197545/141756599-0c874402-72c8-438a-a50e-5d7ba1db9449.png)

**Comment by adfoster-r7** [comment]
@znre Are these modules you would like to run? If not, the warnings can safely be ignored :+1:

**Comment by adfoster-r7** [comment]
Tracked and fixed as part of https://github.com/rapid7/metasploit-framework/issues/15932#issuecomment-984653388

**Comment by adfoster-r7** [comment]
Thanks for raising an issue report :+1:
