### ISSUE TITLE
Android MAC address

### ISSUE THREAD

**Issue by NightRaidGamer** [rapid7/metasploit-framework#15921]
Could someone tell me, how do I change the mac address using meterpreter? with or without root..

**Comment by timwr** [comment]
I feel like this is the sort of question that is best suited for Google, rather than the issue tracker here.

**Comment by NightRaidGamer** [comment]
> I feel like this is the sort of question that is best suited for Google, rather than the issue tracker here.

I can't find anyone teaching how to change the mac address using meterpreter, all the tutorials on google, they say to install external apps like: busybox, terminal emulator, among others...
