### ISSUE TITLE
Need SUPPORT from a better pentester than meRIGHT NOW

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#15985]
- Issue: Meterpreter Windows Reverse HTTPS Stager payload doesn't connect back to the listener, it's sending signals to my ngrok channel but no session opens on msfconsole;
- Attacker machine: Kali Linux 2021 subsystem (installed on VirtualBox) on Bridged Connection adapter
- Target system: Windows XP SP3 installed on VBox:

More details: **Reverse TCP  Meterpreter works fine against this WinXP system**, but Reverse HTTPS doesn't, let me know how I can deal with this please someone. Problem is just with Reverse HTTPS stagers.

**Comment by czonta96** [comment]
Also, reverse HTTPS is working against target Windows 10 Home OS, issue is just related to target Windows XP SP3 subsystem behind NAT.

**Comment by bert128** [comment]
Just a thought, is your HTTPS channel requiring newer encryption ciphers or versions of TLS that are not supported by XP?
Most of the ciphers supported by XP are considered insecure and are disabled by default in most places these days.

**Comment by czonta96** [comment]
Channel is running over ngrok which forces TLS 1.3 I can't edit that option becouse it's a public settings, issue is affecting just reverse HTTPS, reverse HTTP and reverse TCP are working as expected

**Comment by bert128** [comment]
That will be it then, XP does not support TLS 1.3.
HTTP and TCP will work because they do not use TLS at all.

**Comment by czonta96** [comment]
So issue can be solved just by upgrading manually certificates on target system nothing I can do by console to make HTTPS work feels bad it is the most secure channel for tunnelling MP
Thank you man

**Comment by bert128** [comment]
It's not the certificates, it's the version of TLS and ciphers supported by XP. Using that same XP machine you would be unable to browse a lot of modern websites using any browser that uses the system SSL libs (firefox for instance has its own ssl implementation which may be newer). Microsoft do not make a newer TLS implementation available for XP, for TLSv1.3 support you need a recent win10 or 11.
Only way round it is to support old versions and ciphers (eg TLSv1.0 and RC4 or 3DES) or to stick to unencrypted channels. The SSL tester on ssllabs.com will show you if a given website is compatible with XP. According to that, even www.microsoft.com is no longer accessible over HTTPS on IE8/XP.

**Comment by czonta96** [comment]
So you are telling me HTTPS is not working even on windows 7/8? I do not know their network specs, do they support TLS 1.3?

**Comment by bcoles** [comment]
The `reverse_https` payloads support a `SSLVersion` option to control the version of SSL/TLS used.

```
   SSLVersion             Auto              yes       Specify the version of SSL/TLS to be used (Auto, TLS and SSL23 are auto-negotiate) (Accepted:
                                                      Auto, TLS, SSL23, SSL3, TLS1, TLS1.1, TLS1.2)
```

However, if ngrok does not support tunneling TLS1.0/TLS1.1/TLS1.2 then you're out of luck. Windows XP does not support TLS1.3.

> So you are telling me HTTPS is not working even on windows 7/8? I do not know their network specs, do they support TLS 1.3?

You can try connecting to https://tls13.1d.pw/ to test TLS 1.3 support.

On Windows 7, this should work in Firefox which has its own TLS/SSL implementation as per bert's comment above. However, the connection will fail in IE using Windows native SSL.

**Comment by bert128** [comment]
I believe win7 only supports up to TLSv1.2. XP only supports 1.0. 
Are you sure your server requires 1.3 and not 1.2? According to ssllabs, www.ngrok.com does not even support tlsv1.3 - they only support 1.2. I only tested their main site and didn't sign up, their tunnelling service may have different options - you should test yours yourself to see exactly what it supports.
They also require SNI support (which XP also doesn't have) and the AES family of cipher suites (which XP doesn't have). They're also lacking IPv6 support (which XP actually has if you turn it on).

If you're conducting remote testing over the internet, probably best to use a box with a proper connection and not try to struggle with a partial connection stuck behind NAT.

**Comment by czonta96** [comment]
Yes I confirm all, this system is forgotten by the entire universe no one is giving a fuck apart from Mypal developers, very kind of you guys, thanks
