### ISSUE TITLE
Does MSF v6.1.20 for Win have log4shell_scanner auxiliary?

### ISSUE THREAD

**Issue by ZhiboWong** [rapid7/metasploit-framework#16004]
I have downloaded and installed  MSF v6.1.20 for Win on Dec.17th 2021. I want to use  log4shell_scanner by MSF. However, when I input `msf6 >use auxiliary/scanner/http/log4shell_scanner`,the error feedback is :
`
[-] No results from search
[-] Failed to load module: auxiliaryuse
`
When I input `msf6 >search log4shell`,the error feedback is :
`[-] No results from search`

## Summary
So I suspect MSF v6.1.20 for Win does not have log4shell_scanner auxiliary. Is that true?
If true, what should I do in order to using log4shell_scanner?

**Comment by bcoles** [comment]
The module will land in Metasploit eventually.

There's a typo in your command. This is invalid:

```
msf6 >use auxiliaryuse auxiliary/scanner/http/log4shell_scanner
```

Try:

```
msf6 >use auxiliary/scanner/http/log4shell_scanner
```

**Comment by bcoles** [comment]
#15958 was merged on 2021-12-17. It should be in Metasploit v6.1.21 released on 2021-12-24.

**Comment by ZhiboWong** [comment]
Thx. I have corrected the typo. And I successfully installed v6.1.22, which has log4shell_scanner.
