### ISSUE TITLE
LoadError when starting msfconsole for the first time

### ISSUE THREAD

**Issue by Gully-Ranger** [rapid7/metasploit-framework#16002]
XXXXX@MacBook-Pro ~ % /opt/metasploit-framework/bin/msfconsole
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- rex/powershell/output (LoadError)...*(Full output below)

OS: Monterey v12.0.1

	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-powershell-0.1.94/lib/rex/powershell.rb:4:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/rex.rb:50:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/rex/service_manager.rb:3:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `public_send'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/railties-6.1.4.4/lib/rails/railtie.rb:207:in `method_missing'
	from /opt/metasploit-framework/embedded/framework/config/environment.rb:4:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `<top (required)>'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `require'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `<main>'

**Comment by gwillcox-r7** [comment]
@Gully-Ranger Do you have any AV on the system in question that might have removed files or otherwise quarantined them? Reason I ask is that the issue appears to be a missing file issue, specifically for the `rex/powershell/output` file/directory and Zeitwerk is a framework to help us load various dependencies and files quicker.

**Comment by Gully-Ranger** [comment]
@gwillcox-r7 Ah that does make a lot of sense. Yea there is an AV that has been causing me issues with other scripts. Don't know how it didn't cross my mind. Thanks!

**Comment by gwillcox-r7** [comment]
No problem @Gully-Ranger, I'm going to close out this issue as resolved for now, but if your still having issues, feel free to leave a comment and ping me and I can reopen this issue and take another look :)

**Comment by DasaniBottled** [comment]
I’m having a similar issue, I’m new to this side of IT but I’m trying to run metasploit on windows 10 and when I go to run the console .bat file I get a similar error “cannot load such file — rex/powershell/psh_methods (LoadError)

**Comment by adfoster-r7** [comment]
@DasaniBottled Could you raise a new issue please with the issue template filled out, thanks!

**Comment by Vaz003** [comment]
For me it helped, just adding the psh_methods File to the C:\metasploit-framework\embedded\lib\ruby\gems\3.2.0\gems\rex-powershell-0.1.100\lib\rex\powershell Folder. The missing ruby file can, for example, be found here: https://github.com/rapid7/rex-powershell/blob/master/lib/rex/powershell/psh_methods.rb
