### ISSUE TITLE
Add tab completion for supported protocols

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#16019]
## Summary

An idea generated by https://github.com/rapid7/metasploit-framework/pull/16015

We should give affordance to the user when performing tab completion that `file:`, `http:` and friends can be used within msfconsole: https://github.com/rapid7/metasploit-framework/pull/16015#pullrequestreview-845503262

**Comment by shmarsy** [comment]
hello,
I want to contribute in this issue.

**Comment by JustAnda7** [comment]
@adfoster-r7 I would like to contribute to this issue.

**Comment by JustAnda7** [comment]
@adfoster-r7 I had a question regarding the issue that, what should the suggestions to the tab completion to 'http' and other protocols be from something like the hosts table from the database?

**Comment by adfoster-r7** [comment]
Good question; I think this is more complicated than the `easy` label suggests it would be. I'll attic this for now :+1:
