### ISSUE TITLE
Need help for my backdoor

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16031]
I made a FUD backdoor for target all Windows OSes and all work perfectly;
The generated artifact bypass all Windows Defender features on a target Windows 10 system, with one exception:

When I try to spawn a privileged cmd shell on target system Defender Behaviour Shield wakes up and flag my payload as Win32/Meterpreter
What I'm concerned about is what Defender found of anomalous in order to flag this attempt as a Meterpreter Behaviour, becouse when I run most commands my backdoor doesn't get flagged. I can run sysinfo, capture screenshot, capture keystrokes... Also I'm using the better msf stagers... I tried the HTTPS stager with Google cert spoofed certificates, I tried the RC4 encryption stager, all of them get flagged by behaviour shield just when I try to spawn a privileged cmd on target system. In all other situations all is fine, but access to Windows cmd is needed as you gain 100% of control over target system if you succeed at that.

Specs of target: Windows 10 Home x86 (32 bit system)

**Comment by timwr** [comment]
@czonta96 presumably you mean when the meterpreter session is running as `SYSTEM`, `meterpreter > shell` will be detected by the behaviour shield? I suspect this is simply windows defender behaving as expected. You could try modify the code here:
https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/stdapi/server/sys/process/process.c#L110 to make it less suspicous?
Alternatively how about using `meterpreter > powershell_execute` to perform the same actions?

**Comment by czonta1996** [comment]
Where is the meterpreter folder located on Kali Linux in order to paste this code? I will try out if it works

**Comment by timwr** [comment]
/usr/share/metasploit-framework or /opt/metasploit-framework/?
