### ISSUE TITLE
msfconsole not work

### ISSUE THREAD

**Issue by jitesh-eng** [rapid7/metasploit-framework#16069]
┌──(root💀kali)-[/home/kali/Desktop]
└─# msfconsole 
Traceback (most recent call last):
        35: from /usr/bin/msfconsole:18:in `<main>'
        34: from /usr/bin/msfconsole:18:in `require'
        33: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        32: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `require'
        31: from /usr/share/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        30: from /usr/share/metasploit-framework/config/environment.rb:2:in `require'
        29: from /usr/share/metasploit-framework/config/application.rb:23:in `<top (required)>'
        28: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        27: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        26: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        25: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        24: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        23: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.4/lib/action_controller/railtie.rb:4:in `<top (required)>'
        22: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        21: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        20: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        19: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        18: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        17: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.4/lib/action_controller.rb:5:in `<top (required)>'
        16: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
        15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
        13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        12: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
        11: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/actionpack-6.1.4.4/lib/action_controller/metal/strong_parameters.rb:8:in `<top (required)>'
        10: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
         9: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
         8: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
         7: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
         6: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
         5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:4:in `<top (required)>'
         4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
         3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
         2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
         1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.3/lib/zeitwerk/kernel.rb:35:in `require': /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:194: syntax error, unexpected end-of-input, expecting `end' (SyntaxError)

**Comment by jitesh-eng** [comment]
plz solve my error

**Comment by bcoles** [comment]
> require': /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:194: syntax error, unexpected end-of-input, expecting `end' (SyntaxError)

It looks like there's a syntax error in one of the source files which does not bode well.
