### ISSUE TITLE
sessions -K does not account for pivoted sessions

### ISSUE THREAD

**Issue by zeroSteiner** [rapid7/metasploit-framework#16084]
The `sessions -K` command that kills all sessions does not account for the fact that one may be forward through another. This means if session 2 is forwarded through session 1, when `sessions -K` is issued, session 1 will be killed first and session 2 will never receive the shutdown command. This causes session 2 to continue to run.

To reproduce this:

- [ ] Obtain a session through some means
- [ ] Start a reverse_http handler on that session, using the `ReverseListenerComm` option is probably the easiest way
- [ ] Start a second session through the pivoted host (using the Python Meterpreter in the foreground and debugging on will be the easiest way to validate that it's still running later on)
- [ ] From the Metasploit console, kill all the sessions using `sessions -K`
- [ ] See that the session 1 process is not running any more but session 2 is

The easiest thing to do might be to kill the sessions in the reverse order that they were received. This may not be fully accurate though if through using the `transport` command a session with a lower ID can be tunneled through a session with a higher ID. IIRC though changing the transport causes the session to be "closed" and reopened, thus incrementing it's ID. The solution should be tested for this scenario.

**Comment by timwr** [comment]
Killing the sessions in reverse order might be the simplest fix here.
Even without the pivoting issue, killing in reverse order seems preferable as new sessions are more likely to be responsive and the older sessions are more likely to timeout.
