### ISSUE TITLE
App created by payload is not supported!!

### ISSUE THREAD

**Issue by BanaPankaj** [rapid7/metasploit-framework#16122]
I have created an apk file using payload.
Everthing was fine but when i installed it in my android it was unable to run and error was this app is not supported by your android version.
Because my android version is 11 and app is not working with this higher version.

Any solution or alternative of this method?

**Comment by bcoles** [comment]
Apk payloads generated with msfvenom should work on Android 11.

What error message did you get exactly?

**Comment by bcoles** [comment]
Does the message say "This app was built for an older version of Android" ?

If so, this is a warning and can be ignored.

**Comment by vic131** [comment]
> Does the message say "This app was built for an older version of Android" ?
> 
> If so, this is a warning and can be ignored.

What if you dont want the message to show up ? Is possible to recompile with apktool changing the android version ?
