### ISSUE TITLE
wiki/Nightly-Installers: number of archived builds incorrect

### ISSUE THREAD

**Issue by neutric** [rapid7/metasploit-framework#16126]
The number of archived macOS nightly installer builds stated on https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers seems outdated. Instead of the last 10 builds, https://osx.metasploit.com/ only lists 8.

**Comment by adfoster-r7** [comment]
Hi there; Which versions would you want to have available?

**Comment by neutric** [comment]
@adfoster-r7 Good question, sorry for being imprecise. I was seeking to get the docs updated, but if you could leave a few more builds available, you'd help downstream projects such as Homebrew (see https://github.com/rapid7/metasploit-framework/issues/12936 or discussion in https://github.com/Homebrew/homebrew-cask/pull/117348).
