### ISSUE TITLE
Command alias in config file

### ISSUE THREAD

**Issue by ChocolateOverflow** [rapid7/metasploit-framework#16120]
## Summary

I want to be able to configure command aliases like with `bash`. This could as simple as aliasing command to command or going as far as "command with arguments" to command. This should be stored in a config file (with a standard location or a custom location to be specified) that would be automatically run every time `msfconsole` is started, much like with `bash` and `vim`.

### Basic example

```sh
alias r=run
alias s=set
alias sg=setg
alias st="set LHOST tun0"
```

### Motivation

I just want common commands to be shorter and thus faster and easier to use.

**Comment by bcoles** [comment]
Metasploit supports an `alias` plugin and associated console command. There's some discussion here: #5107

You could achieve configuration file functionality by started `msfconsole` with a resource script containing your aliases.

![aliases](https://user-images.githubusercontent.com/434827/151657768-61f2df17-67b5-47b5-843f-bd1cc5bb3198.png)

**Comment by timwr** [comment]
Additionally: ~/.msf4/msfconsole.rc Is loaded by msfconsole automatically upon startup, so you can put your aliases there.
