### ISSUE TITLE
Metasploit .apk File Issue 

### ISSUE THREAD

**Issue by MaxLinuxa** [rapid7/metasploit-framework#16129]
#i have created  new Payload file for android 
While i install the Apk file .. Getting this issue on target mobile  ..... "this app was built for an older version of android and may not work properly.try checking for updates or contact the Developer  "
--> Help me Please

**Comment by bcoles** [comment]
> "this app was built for an older version of android

This is a warning and can be ignored.

**Comment by MaxLinuxa** [comment]
okay but after that section not connected @bcoles

**Comment by 2986085886** [comment]
![Uploading Screenshot_20220205_220153.jpg…]()
