### ISSUE TITLE
Install in Arch 

### ISSUE THREAD

**Issue by yashsinghchauhan-formal** [rapid7/metasploit-framework#16144]
im using arch linux. how can i install msf in arch 

PS: pacman version and AUR versions are outdated so please don't suggest those

**Comment by AtmegaBuzz** [comment]
@yashsinghchauhan-formal pacman and aur are the only mode you can install latest packages. if msf is outdated there then you have to install it manually by cloning msf. 
According to what i know.
But current metasploit version available on arch wiki  is 6.1.28
and 6.1.7 v is where the current msf is. I dont know what functionality do you need which isnt in the older version. if you can elaborate.

**Comment by 3V3RYONE** [comment]
Hello @yashsinghchauhan-formal , as said by @AtmegaBuzz , if you need the very latest version of msf, you can follow this [guide](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment) to setup MSF in your machine
