### ISSUE TITLE
Failed to fetch https://kali.itsec.am/kali/pool/main/m/metasploit-framework/metasploit-framework_6.1.28-0kali1_amd64.deb  Error reading from server - read (5: Input/output error)

### ISSUE THREAD

**Issue by slyg3nius** [rapid7/metasploit-framework#16165]
## Steps to reproduce

How'd you do it?

1. ```bash 
    $ sudo apt-get install metasploit-framework
    ```

Results: 
```
Get:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1 [135 MB]                                   
Ign:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1                                            
Get:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1 [135 MB]                                   
Ign:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1                                            
Get:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1 [135 MB]                                   
Ign:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1                                            
Err:11 https://kali.itsec.am/kali kali-rolling/main amd64 metasploit-framework amd64 6.1.28-0kali1                                            
  Error reading from server - read (5: Input/output error)
Fetched 17.6 MB in 2min 31s (117 kB/s)          
E: Failed to fetch https://kali.itsec.am/kali/pool/main/m/metasploit-framework/metasploit-framework_6.1.28-0kali1_amd64.deb  Error reading from server - read (5: Input/output error) 
```

**Comment by bcoles** [comment]
Your host failed to contact the kali package repository for some reason. Check your network connection.

**Comment by slyg3nius** [comment]
My network connection is okay but only this repository cannot download well.
