### ISSUE TITLE
stdapi_webcam_start: Operation failed: 1

### ISSUE THREAD

**Issue by MURSHIG** [rapid7/metasploit-framework#16222]
My payload is android/meterpreter/reverse_tcp;
When I trying exec webcam_snap 1 on the Android under 6, it running normal and taking pic
But when android version is higher than 6 - webcam, activity_start and app_run not working

**Comment by bcoles** [comment]
Issue #16313 is a dupe of this issue. Both issues discuss the same commands.

This issue was create first, but closing this issue as #16313 contains additional information.

**Comment by ayush169** [comment]
I am having the same issue.
