### ISSUE TITLE
Started getting warnings apt repo on kali about apt-key deprication. Any ideas?

### ISSUE THREAD

**Issue by tanja84dk** [rapid7/metasploit-framework#16263]
## Summary
Just updated all apt packages and got a warning about possible apt-key changes.
And my question is how do I fix it on my system?

This is the warning I got and I haven’t got it before, also I do believe my apt version just got upgraded when I upgraded all installed packages

“””
W: http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/kali/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
“””

I have added the manual also from apt-key just in case it makes any sense for someone

## Relevant information

From man apt-key:
“””
DEPRECATION
       Except for using apt-key del in maintainer scripts, the use of apt-key is
       deprecated. This section shows how to replace existing use of apt-key.

       If your existing use of apt-key add looks like this:

       wget -qO- https://myrepo.example/myrepo.asc | sudo apt-key add -

       Then you can directly replace this with (though note the recommendation
       below):

       wget -qO- https://myrepo.example/myrepo.asc | sudo tee
       /etc/apt/trusted.gpg.d/myrepo.asc

       Make sure to use the "asc" extension for ASCII armored keys and the "gpg"
       extension for the binary OpenPGP format (also known as "GPG key public
       ring"). The binary OpenPGP format works for all apt versions, while the
       ASCII armored format works for apt version >= 1.4.

       Recommended: Instead of placing keys into the /etc/apt/trusted.gpg.d
       directory, you can place them anywhere on your filesystem by using the
       Signed-By option in your sources.list and pointing to the filename of the
       key. See sources.list(5) for details. Since APT 2.4, /etc/apt/keyrings is
       provided as the recommended location for keys not managed by packages. When
       using a deb822-style sources.list, and with apt version >= 2.4, the
       Signed-By option can also be used to include the full ASCII armored keyring
       directly in the sources.list without an additional file.

“””

**Comment by brandontan** [comment]
I am having the same issue : Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by aryanguenthner** [comment]
# This works! Tested on Kali 2022.1

wget http://apt.metasploit.com/metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg
sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/
apt update

**Comment by aryanguenthner** [comment]
If all else fails this should do the job. 
mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/

**Comment by x21gunsx** [comment]
@aryanguenthner Your commands solved my issue, thank you sir!

**Comment by tanja84dk** [comment]
True it does fix it but I would say it’s still not fixing it actually because even if you do a fresh install with the script in the repo it still gives that warning because I guess metasploit is somewhat un maintained I guess

**Comment by Aunonno-2022** [comment]
> # This works! Tested on Kali 2022.1
> 
> wget http://apt.metasploit.com/metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/ apt update

> # This also works in Ubuntu! Tested on Ubuntu 22.04 LTS

**Comment by peketravieso** [comment]
[aryanguenthner](https://github.com/aryanguenthner) commented [on 9 Mar](https://github.com/rapid7/metasploit-framework/issues/16263#issuecomment-1063687165)
This works! Tested on Kali 2022.1

wget http://apt.metasploit.com/metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg
sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/
apt update


working in KALI 
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.2
Codename:       kali-rolling

**Comment by agenteph** [comment]
> # This works! Tested on Kali 2022.1
> wget http://apt.metasploit.com/metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/ apt update

This Works for me! up!

**Comment by imazes** [comment]
just need this
```
cd /etc/apt
sudo cp trusted.gpg trusted.gpg.d
```

**Comment by Kevlog** [comment]
> # This works! Tested on Kali 2022.1
> wget http://apt.metasploit.com/metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/ apt update

And this work on WSL2 Kali LIinux:
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:          2022.3
Codename:     kali-rolling

**Comment by luannutels** [comment]
Works! ty
