### ISSUE TITLE
The most stable version for Metasploit running on Windows?

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16274]
.

**Comment by adfoster-r7** [comment]
We generally recommend running on a unix environment such as [Kali](https://www.kali.org/get-kali/). The latest version of metasploit framework should work on windows, but please raise an issue if you hit anything specific.

**Comment by czonta96** [comment]
Yes, windows/manage/persistence_exe not working as intended:
Expectation: uploading an exe on remote system.

What it does (just on Windows): it upload a 1 kb file which does nothing.

**Comment by adfoster-r7** [comment]
Please raise a new issue following the issue template and we can take a look for you :+1:
