### ISSUE TITLE
Winrm Port is not working as expected

### ISSUE THREAD

**Issue by flamecopper** [rapid7/metasploit-framework#16289]
There is an Error with RPORT of this script. When I tried to set 5986, really the winrm of the port it is not working.

   RPORT             5985             yes       The target port (TCP)
   SSL               false            no        Negotiate SSL/TLS for outgoing
                                                 connections
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credentia
                                                l works for a host
   THREADS           1                yes       The number of concurrent threa
                                                ds (max one per host)
   URI               /wsman           yes       The URI of the WinRM service
   USERNAME          administrator    no        A specific username to authent
                                                icate as
   USERPASS_FILE                      no        File containing users and pass
                                                words separated by space, one
                                                pair per line
   USER_AS_PASS      false            no        Try the username as the passwo
                                                rd for all users
   USER_FILE                          no        File containing usernames, one
                                                 per line
   VERBOSE           true             yes       Whether to print output for al
                                                l attempts
   VHOST                              no        HTTP server virtual host

msf6 auxiliary(scanner/winrm/winrm_login) > set RHOSTS 172.25.170.110
RHOSTS => 172.25.170.110
msf6 auxiliary(scanner/winrm/winrm_login) > set RPORT 5986
RPORT => 5986
msf6 auxiliary(scanner/winrm/winrm_login) > run
^C
[*] Caught interrupt from the console...
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/winrm/winrm_login) > set RHOSTS 172.25.170.170
RHOSTS => 172.25.170.170
msf6 auxiliary(scanner/winrm/winrm_login) > run

[-] 172.25.170.170: - LOGIN FAILED: WORKSTATION\administrator:123456 (Unable to Connect: A socket error occurred.)
[-] 172.25.170.170: - LOGIN FAILED: WORKSTATION\administrator:password (Unable to Connect: A socket error occurred.)
[-] 172.25.170.170: - LOGIN FAILED: WORKSTATION\administrator:12345678 (Unable to Connect: A socket error occurred.)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/winrm/winrm_login) > search rdp

**Comment by bcoles** [comment]
> When I tried to set 5986, really the winrm of the port it is not working.
> Unable to Connect: A socket error occurred.

WinRM port 5986 is the encrypted SSL/TLS port, hence the socket connection error. You will need to `set SSL true`.
