### ISSUE TITLE
VNC Capture server module's JtR output isn't parsed by JtR

### ISSUE THREAD

**Issue by smashery** [rapid7/metasploit-framework#16296]
The VNC capture module (`auxiliary/server/capture/vnc`) writes out John the Ripper files according to the `JOHNPWFILE` parameter. Files created by this module are not read in my JtR.

## Steps to reproduce

1. `use auxiliary/server/capture/vnc`
2. `set JOHNPWFILE /tmp/vnc_jtr`
3. `run`
4. `use auxiliary/scanner/vnc/vnc_login`
5. `set rhosts 127.0.0.1`
6. `set username user`
7. `set password p@s5w0rd`
8. `run`
9. `john /tmp/vnc_jtc_vnc`

At this point, I'd expect it to crack the hashes. Instead, it reports:

```
Using default input encoding: UTF-8
No password hashes loaded (see FAQ)
```

### Sample output

```
msf6 auxiliary(scanner/vnc/vnc_login) > run

[*] 127.0.0.1:5900        - 127.0.0.1:5900 - Starting VNC login sweep
[+] 127.0.0.1:40801 - Challenge: 00112233445566778899aabbccddeeff; Response: 6feb3cb1f07b66151656b5832341f223
[!] 127.0.0.1:5900        - No active DB -- Credential data will not be saved!
[-] 127.0.0.1:5900        - 127.0.0.1:5900 - LOGIN FAILED: :p@s5w0rd (Incorrect: Authentication failed)
[+] 127.0.0.1:37849 - Challenge: 00112233445566778899aabbccddeeff; Response: b7b9c87777661a7a2299733209bfdfce
[-] 127.0.0.1:5900        - 127.0.0.1:5900 - LOGIN FAILED: :password (Incorrect: Authentication failed)
[*] 127.0.0.1:5900        - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

```
root@msfdevubuntu:~# cat /tmp/vnc_jtr_vnc 
$vnc$*00112233445566778899aabbccddeeff*6feb3cb1f07b66151656b5832341f223
$vnc$*00112233445566778899aabbccddeeff*b7b9c87777661a7a2299733209bfdfce
```

### Suggested fix

JtR Seems to expect uppercase hexadecimal. Converting the file to uppercase bears this out:

```
└─$ john --wordlist=wordlist converted_to_uppercase
Created directory: /home/kali/.john
Using default input encoding: UTF-8
Loaded 2 password hashes with 2 different salts (VNC [DES 32/64])
Press 'q' or Ctrl-C to abort, almost any other key for status
p@s5w0rd         (?)
password         (?)
2g 0:00:00:00 DONE (2022-03-07 16:18) 100.0g/s 100.0p/s 200.0c/s 200.0C/s p@s5w0rd..password
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by h00die** [comment]
Being that creds are stored in the database, which includes an export to John and hashcat functionality, is it not a duplicate feature here (minus actually needing a database connected)? 

PS, (I?) should double check the creds are stored in the DB or exported from the DB in a working manner. I suspect the same problem there as well

**Comment by smashery** [comment]
Not familiar with that feature; can you give me some commands to try it?

This bug report refers to the `JOHNPWFILE` parameter that exports the hash to file for later processing with JtR while the module is running. Given that the code for this module passes the hash to the database in the same form that it's written to file, I'd presume that any functionality that uses the cred stored in the database in association with JtR will likely have the same issue, though the same fix.

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/wiki/Hashes-and-Password-Cracking#exporting-passwords-and-hashes

although I now speculate that we'll need to add in code to handle VNC type
