### ISSUE TITLE
hosts -S not working when specifying sth.

### ISSUE THREAD

**Issue by Elan0r** [rapid7/metasploit-framework#16301]
## Steps to reproduce

How'd you do it?

working with Workspaces and connected postgresql DB

hosts -S 'string'

is not working as expected -> no output, but an error.

IF

hosts -S 'IPv4'
it is working as expected.

## Expected behavior

returning all hosts with the defined search string

## Current behavior

just an error

### Metasploit version

6.1.28-dev - 6.1.30-dev & 6.1.32-dev

6.1.27-dev is latest working

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.1.32-dev
Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: apt install from Kali Repo on Kali Linux
```

</details>
<details>
<summary>Screens</summary>
![Screenshot 2022-03-07 at 13 05 41](https://user-images.githubusercontent.com/85351442/157033702-8111d4d9-c9df-43b0-a7f5-d70333270119.png)
![Screenshot 2022-03-07 at 13 06 56](https://user-images.githubusercontent.com/85351442/157033728-505d16b5-5e6e-438a-ba89-ac0aa14c8d8c.png)
![Screenshot 2022-03-07 at 13 25 35](https://user-images.githubusercontent.com/85351442/157034514-8b804834-aa99-4cb6-9f3a-606e94cdbd5e.png)

</details>

**Comment by smcintyre-r7** [comment]
Yup this is a bug. I'll have a patch up for it shortly, it's an easy fix. Thanks for reporting it to us.

```
msf6 auxiliary(server/capture/smb) > hosts

Hosts
=====

address          mac  name             os_name       os_flavor           os_sp  purpose  info  comments
-------          ---  ----             -------       ---------           -----  -------  ----  --------
192.168.159.1                          Unknown                                  device
192.168.159.11        WIN-9NSI4A6AIHJ  Windows 7     Professional        SP1    client
192.168.159.27        192.168.159.27   ubuntu        Ubuntu 20.04.2 LTS         server
192.168.159.86        DESKTOP-RTCRBEV  Windows 10                               client
192.168.159.87        DESKTOP-SRAQBLH  Windows 10                               client
192.168.159.89        DESKTOP-QO2FTHF  Windows 10                               client
192.168.159.90        DESKTOP-ML76VPN  Windows 10                               client
192.168.159.96        WIN-3MSP8K2LCGC  Windows 2019  Standard                   server
192.168.159.128                        Unknown                                  device
192.168.159.221                        Unknown                                  device

msf6 auxiliary(server/capture/smb) > hosts -S ubuntu
[-] Invalid host parameter, ubuntu.
msf6 auxiliary(server/capture/smb) > hosts -S Win
[-] Invalid host parameter, Win.
msf6 auxiliary(server/capture/smb) > hosts -S IPv4
[-] Invalid host parameter, IPv4.
msf6 auxiliary(server/capture/smb) > hosts -S Windows
[-] Invalid host parameter, Windows.
msf6 auxiliary(server/capture/smb) >
```
