### ISSUE TITLE
Android: Commands not working: app_run/app_install/app_uninstall/activity_start/webcam_snap

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16313]
Payload used: android/meterpreter/reverse_tcp (Metasploit 6.1.32 on Windows 10 x64 20H02)
Target: Android 11 no root -  Linux 4.9.227-22722052 (armv8l)
Meterpreter: dalvik/android

Action performed: tried to just open an app running with low privileges (clash of clans), meterpreter give me the output:
**[+] Main Activity for 'com.supercell.clashofclans' has started.**

But in the real phone, it doesn't start. App_install and app_uninstall are not sending requests to the remote target.
Then, always against the same target:
 webcam_snap
**[*] Starting...
[*] Stopped
[-] stdapi_webcam_start: Operation failed: 1**

All these commands worked on Android 6.0.1, so it could be that Metasploit is not really optimized to execute commands on modern Android version or I don't know. I striked the issues as bugs anyway.

**Comment by MURSHIG** [comment]
listen: solution: it don't solve webcam_snap cause it just block while u don't use app,but u can solve app_run, etc problems, 
just decompile apk with apktool, at AndroidManifest.xml u could delete all the <uses-permission> strings and put my text from file 
[msfpermissions.txt](https://github.com/rapid7/metasploit-framework/files/8474240/msfpermissions.txt)
