### ISSUE TITLE
Session TLV Logging doesn't work with Windows Encrypted Shells

### ISSUE THREAD

**Issue by sjanusz-r7** [rapid7/metasploit-framework#16348]
## Steps to reproduce

Although the encrypted shells advise you to use a DB, it did not change the logs not showing up.

1. `setg sessiontlvlogging true` or `setg sessiontlvlogging console`
1. `use payload/windows/x64/encrypted_shell/reverse_tcp`
1. `set` LHOST and LPORT
1. `generate -f exe -o {output_name}`
1. Run the executable on the victim machine
1. `sessions -i -1` and run `pwd` as an example command

## Expected behavior

Seeing TLV logs in the console.

## Current behavior

No logging is being done.

### Metasploit version

Framework: 6.1.34-dev-c0185f65bf
Console  : 6.1.34-dev-c0185f65bf

**Comment by smcintyre-r7** [comment]
Do shell sessions use TLVs? I thought that protocol was specific to Meterpreter.

**Comment by adfoster-r7** [comment]
Sync'd up with @sjanusz-r7 and it looks like this ticket isn't required :+1:
