### ISSUE TITLE
msfconsole hangs forever in 100% cpu loop

### ISSUE THREAD

**Issue by dotysan** [rapid7/metasploit-framework#16355]
## Steps to reproduce

How'd you do it?

```
$ msfconsole

 ** Welcome to Metasploit Framework Initial Setup **
    Please answer a few questions to get started.


Would you like to use and setup a new database (recommended)? y
[?] Would you like to init the webservice? (Not Required) [no]: 
Clearing http web data service credentials in msfconsole
```

At the [no] prompt above, I simply hit enter. Then it hung forever.

After awhile I put a strace on the spinning proc. It was stuck in this loop:
```
write(1, "Please answer yes or no.\n", 25) = 25
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, 0x7ffe7d3c81b0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(0, "", 1)                          = 0
write(1, "Please answer yes or no.\n", 25) = 25
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, 0x7ffe7d3c81b0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
read(0, "", 1)                          = 0
...
```

## Were you following a specific guide/tutorial or reading documentation?

Yes. Pristine install following here: https://fedoraproject.org/wiki/Metasploit_Penetration_Testing_Framework

## Expected behavior

It looks like it was trying to prompt me to make a choice. (Or it should have used the assumed [no] choice.) But definitely shouldn't have hung in that ENOTTY loop.

### Metasploit version

6.1.34+20220317102557~1rapid7-1.el6

## Additional Information

Was in ssh terminal on Fedora 35.

**Comment by adfoster-r7** [comment]
I haven't confirmed this, but I can envision this being caused by the initial setup call to `msfconsole` loading `msfconsole` again to [persist/clear db credentials](https://github.com/rapid7/metasploit-framework/blob/5faf25dbe3798ddefdacb340d5fab1fe344be4ef/msfdb#L670-L675), which ends up asking the same setup questions again

If you're happy having no database for now, you can answer `no` to have msfconsole load as expected

**Comment by syscrsh** [comment]
Have you executed the "msfdb init" command (as non-root) on the shell before ?

I had the exact same problem and this fixed it for me.

**Comment by gwillcox-r7** [comment]
Went through this issue with @sneakerhax over a call last night and we found this was the solution for his situation. Seems to be related to @adfoster-r7's point r.e clearing web credentials:

```
su - msf -c "echo no | msfconsole -qx 'db_disconnect --clear; exit'"
su - msf -c "msfdb init --component database"
msfconsole -x "db_connect msf@msf"
```

We did note that the `db_disconnect --clear` command had to be run as the `msf` user in his case not as the `root` user so this is also something else to note. Supposedly the nightly installer was meant to be doing this but it didn't seem to be working this way in his case.

This should allow you to get database connectivity back if your in need of it though we will likely want to check deeper and see if we can't fix this bug in the code itself.

**Comment by KeparYTbcc** [comment]
i got same problem, simply do:

```
sudo msfconsole
```

**Comment by CalfCrusher** [comment]
I have the exact problem. Solutions provided doesn't work for me

**Comment by Zopolis4** [comment]
Also having the same issue, neither of the solutions provided work, was able to simply answer yes to initing the webservice as a workaround.

**Comment by adfoster-r7** [comment]
A fix for this has landed, and should be available in a few days: https://github.com/rapid7/metasploit-omnibus/pull/169

**Comment by CalfCrusher** [comment]
After 1 year on a Raspberry, msfconsole is totally unstable. It hangs always. 100% CPU all night long

**Comment by adfoster-r7** [comment]
@CalfCrusher That sounds like a different problem to the original issue with the database initialisation bug that this ticket is originally about

If you raise a separate issue and describe the symptoms/replication steps etc, there's a higher chance of your issue being resolved

**Comment by tkbstudios** [comment]
I have the same issue (RPI 4B 8GB NVM.e SATA ||| SSD main drive) and it alsways hangs with **every** metasploit command. `msfdb init`, etc..

always stuck on `Clearing http web data service credentials in msfconsole`

**Comment by adfoster-r7** [comment]
@tkbstudios Please raise a new issue :+1:
