### ISSUE TITLE
msfdb doesn't work with proxychains4 

### ISSUE THREAD

**Issue by Jay-null** [rapid7/metasploit-framework#16365]
Hi guys, I have got a problem with metasploit database and proxychains, and I can't use them together (on Kali Linux)

First of all I type this commands:

sudo service tor start
msfdb delete
msfdb init	
cp /usr/share/metasploit-framework/config/database.yml /root/.msf4/
sudo service postgresql
sudo service postgresql restart
sudo proxychains4 msfconsole

then:

msf6 > db_status
[proxychains] DLL init: proxychains-ng 
[proxychains] DLL init: proxychains-ng 
[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:5432 <--denied
[*] postgresql selected, no connection   
[proxychains] DLL init: proxychains-ng 
[proxychains] DLL init: proxychains-ng 
[proxychains] DLL init: proxychains-ng 

but if I run msfconsole without proxychains4 (type everything similar to previous, except proxychains4 in the last line) I got this answer: 

msf6 > db_status
[*] Connected to msf. Connection type: postgresql.

Seems like it works, another apps are running with proxychains4 pretty good
I probably missing some important information about this case, that is my first question on forums, so, sorry for my English, and if you need to know something else, feedback, and I send you anything you needed very quick

[proxychains] Dynamic chain  ...  127.0.0.1:9050  ...  127.0.0.1:5432 <--denied
May be this is cause of my problem, but I have no line "127.0.0.1 5432" in proxychains.conf, and don't know anything about this port, glad to get any help

**Comment by 3V3RYONE** [comment]
Hello @Jay-null, the problem you are experiencing might have occured because here proxychain is tunneling connections to the postgresql service. And because of which, metasploit may not be able to communicate with postgres, so fails to start the db.

`5432` is the default port for postgresql socket. So, `127.0.0.1:5432` would be the postgresql service. 

Could you try to stop tunneling your proxy connections to the `localhost` and check if it works by the following steps :

-> Open your `proxychains.conf` file
-> Add the line `localnet 127.0.0.1 000 255.255.255.255` to the file. This will stop proxy-connections to the localhost.
-> Save it, and restart msfconsole to check db_status.

**Comment by Jay-null** [comment]
Hi @3V3RYONE, thanks for your answer. I forgot to mention that I already googled my question, and didn't find something useful, I already tried to do the same instructions that you gave, and I got this error: 
root@kali # sudo proxychains4 msfconsole

[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
error: invalid item in proxylist section: localnet 127.0.0.1 000 255.255.255.255

I also tried to replace "localnet ..." line in proxychains.conf to the top of the file (in the previous sample localnet is located right in the proxy enumerating list), now I got this:
root@kali # sudo proxychains4 msfconsole
   
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
localnet format error

I found the same problem description, here on github, and it's closed, but the solution doesn't work for me (https://github.com/rofl0r/proxychains-ng/issues/47), they said to put localnet on top of file. Thank you for any info about this case

**Comment by 3V3RYONE** [comment]
Ah I see, Could you once post the contents of your `/etc/proxychains.conf` file?

**Comment by Jay-null** [comment]
Sure, it works without first line #

#localnet 127.0.0.1 000 255.255.255.255
dynamic_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks4  127.0.0.1 9050

**Comment by 3V3RYONE** [comment]
Hey @Jay-null , just to confirm, you are using the proxychains with first line uncommented right? Which is resulting in the above error I suppose?

If so, then delete the first line & try to comment the `socks4 127.0.0.1 9050` line and then run msfconsole & check db_status.

If that also fails, try adding `socks5 127.0.0.1 36363` line in-place of `socks4 127.0.0.1 9050` and check if it works?

**Comment by Jay-null** [comment]
Hi @3V3RYONE, I tried to use both (with #, and without), but it works only when the first line is commented. When it's uncommented I see this error: "localnet format error".

If I comment line "socks4 127.0.0.1 9050", I get this when I try to start msfconsole with proxychains-ns: "error: no valid proxy found in config", so I couldn't check out db_status, cause msf didn't started.

If I replace port from 9050 to 36363, I get this: 
```
# sudo proxychains4 msfconsole
[proxychains]` Dynamic chain  ...  127.0.0.1:36363  ...  timeout
!!!need more proxies!!!
msf6 > db_status
[proxychains] Dynamic chain  ...  127.0.0.1:36363  ...  timeout
!!!need more proxies!!!
[*] postgresql selected, no connection
```
May be I should check out the log files?

**Comment by 3V3RYONE** [comment]
Ahh I see, yes please, the log files could help in debugging.. Can you post the log files?
