### ISSUE TITLE
How can I edit android backdoor

### ISSUE THREAD

**Issue by karpiyon** [rapid7/metasploit-framework#16363]
When I run msfvenom to generate a stand alone payload, there are some modifications I'd like to make to the backdoor, E.g. make it open a website when clicked on.
Can I edit the source code of the backdoor apk before it is compiled and if yes how.

I refer to something like this:
[https://github.com/giovannicolonna/msfvenom-backdoor-android](url)

If msfvenom is using a similar code where is t on kali linux?

Thanks

**Comment by bcoles** [comment]
> Can I edit the source code of the backdoor apk before it is compiled and if yes how.

Try using an existing APK file as a template with `msfvenom -x`.

Or, once compiled, you can decompile the compiled APK with apktool, make whatever changes you want, then recompile it.

If you know Ruby, you can modify msfvenom to do as you please before the APK is compiled.

**Comment by karpiyon** [comment]
Thanks, I have treid all that but apktool does not provide you with java to edit.

**Comment by bcoles** [comment]
Android payload code in in the `metasploit-payloads` repository.

https://github.com/rapid7/metasploit-payloads/tree/master/java/androidpayload

**Comment by karpiyon** [comment]
thanks. where is it on my kali Linux
________________________________

**Comment by bcoles** [comment]
> thanks. where is it on my kali Linux

```
# find /var/ -name metasploit-payloads 
/var/lib/gems/2.7.0/gems/metasploit-payloads-2.0.77/lib/metasploit-payloads
```

**Comment by karpiyon** [comment]
@bcoles 
Thanks, I already tried searching for it.
it's not there, at least on my kali 2021.
I run as admin:
`find /var/ -name metasploit-payloads` found nothing

I did find this but it does not contain any payloads:
`/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-payloads-2.0.75/lib/
`

**Comment by shouxindehai** [comment]
> Android payload code is in the `metasploit-payloads` repository.
> 
> https://github.com/rapid7/metasploit-payloads/tree/master/java/androidpayload

非常感谢 很有帮助。我目前在调研一些关于apk木马免杀的技术，非常希望能添加您的email向您请教有关msf-android-payload相关代码信息（毕竟源码中缺少一些必要注释）。

**Comment by gwillcox-r7** [comment]
Closing as this issue seems to have been resolved now.
