### ISSUE TITLE
Add library for Windows version normalization and version comparison

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#16389]
A library for Windows version normalization and version comparison would be useful.

Framework contains a lot of code that looks like this:

```ruby
/(7|8|8\.1|10|11|2008|2012|2016|2019|2022|1803|1903|1909|2004)/
```

Mostly modules, but also core libraries:

https://github.com/rapid7/metasploit-framework/blob/283dda8172939dd64da56e553c6733b8ae0da3e2/lib/msf/core/post/windows/priv.rb#L148

Usually for detecting whether a target system supports functionality or is vulnerable. This is error prone and not future proof.

Code which uses the version for feature detection must be updated regularly. See:

* #16064
* #14309
* https://github.com/rapid7/metasploit-framework/pull/11573
* https://github.com/rapid7/metasploit-framework/pull/10419
* https://github.com/rapid7/metasploit-framework/pull/10326

**Comment by timwr** [comment]
Can't we just invert the logic in priv.rb? e.g return false for < Vista and then run the enable_lua check for everything else?

**Comment by bcoles** [comment]
> Can't we just invert the logic in priv.rb? e.g return false for < Vista and then run the enable_lua check for everything else?

Maybe.

This issue is about a systemic issue in framework.
