### ISSUE TITLE
Use msfvenom code to create my own android backdoor

### ISSUE THREAD

**Issue by karpiyon** [rapid7/metasploit-framework#16380]
Hi,
I am trying to generate my own app, using android studio and generate my own backdoor based on this one:
[https://github.com/rapid7/metasploit-payloads/tree/master/java/androidpayload](url)

I assume, well rather hope, that I can copy this code to my project and make it work.
For started I don't see where I replace the LHOST & LPORT which should be the 2 parameter required for teh backdoor to function.

I did notice a placeholder under:
[https://github.com/rapid7/metasploit-payloads/tree/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java](url)

Can anyone suggest where I set my LHOST & LPORT in that code?

Thanks

**Comment by timwr** [comment]
So the LHOST and LPORT is encoded into the configBytes, which is parsed here:
https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java#L108
It roughly equivalent to the Windows meterpreter configuration: 
https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Configuration

You can define your own transport url (e.g tcp://192.168.0.1:4444) and put it here:
https://github.com/rapid7/metasploit-payloads/blob/00bc3a202090bd5f8f6526a4f1ca3932475ed934/java/androidpayload/app/src/com/metasploit/stage/Payload.java#L123
You may also need to set some of the other options, e.g the Context, the retry intervals, the path. You're better off generating a real working config (with msfvenom) and then just patching the url.
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/android.rb#L65
