### ISSUE TITLE
Meterpreter session 1 is not valid and will be closed

### ISSUE THREAD

**Issue by ANONYMOUs-x-hash** [rapid7/metasploit-framework#16407]
![Problem](https://user-images.githubusercontent.com/64018520/161448667-8352be19-d98b-4662-98a9-4b76b2bb3a1b.png)
I keep encountering this issue whenever i create a payload and listen for incoming connection(s), my meterpreter session keeps closing for a reason i don't understand. happens to my Staged and Stageless payloads.

1. I create my payload using Msfvenom. I even try it with Veil
2. Set up  my listening port with all options matching the created payload (Mostly python payloads because for some reasons windows payload don't even execute on target machine, shows some message, "This app can't run on your PC . To find a version for your PC.....".
3. I transfer the payload to target machine with all Anti Virus bodies turned off. Just for testing purposes
4. I execute, and i get this error message on my 'multi/handler' " Meterpreter session 1 is not valid and will be closed "

## Were you following a specific guide/tutorial or reading documentation?

NO

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

## Expected behavior

I expect a meterpreter session

## Current behavior

Meterpreter session keeps closing for a reason i don't know, shows; " Meterpreter session 1 is not valid and will be closed "

### Metasploit version

Version: 6.1.27-dev.
 
Please I'd really appreciate a response
![Problem](https://user-images.githubusercontent.com/64018520/161448805-65f48cd4-dee6-4cec-ad40-a3f669ec64c3.png)

**Comment by bcoles** [comment]
The session was closed as it was not valid.

There is insufficient information to reproduce this issue.

What payload? What *exact* commands did you use to generate the payload? 

What target operating system?

What *exact* commands did you use for the `multi/handler` ?

**Comment by gwillcox-r7** [comment]
Insufficient information has been provided for this issue and no additional information has been provided to reproduce. Closing.
