### ISSUE TITLE
There are other problems discussed here: https://github.com/termux/termux-packages/issues/715

### ISSUE THREAD

**Issue by TonieyX** [rapid7/metasploit-framework#16429]
Mine keep saying this when l launch metasploit framework

~/metasploit-framework $ msfconsole
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.                                /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:74:in `rescue in validate': The gemspec at /data/data/com.termux/files/home/metasploit-framework/metasploit-framework.gemspec is not valid. Please fix this gemspec. (Gem::InvalidSpecificationException)                                          The validation error was 'duplicate dependency on net-smtp (>= 0), (>= 0) use:                          add_runtime_dependency 'net-smtp', '>= 0', '>= 0'
'                                                         from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:69:in `validate'                      from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:162:in `validate_spec'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:176:in `block in load_spec_files'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:170:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:170:in `load_spec_files'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:105:in `local_specs'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:113:in `specs'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:600:in `specs_for_source_changed?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:585:in `specs_changed?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:629:in `block in converge_paths'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:628:in `any?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:628:in `converge_paths'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:119:in `initialize'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `to_definition'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:13:in `evaluate'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:34:in `build'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:195:in `definition'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `block in <top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:17:in `<main>'
/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/specification_policy.rb:478:in `error': duplicate dependency on net-smtp (>= 0), (>= 0) use: (Gem::InvalidSpecificationException)
    add_runtime_dependency 'net-smtp', '>= 0', '>= 0'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/specification_policy.rb:171:in `validate_duplicate_dependencies'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/specification_policy.rb:91:in `validate_required!'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/specification_policy.rb:44:in `validate'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/specification.rb:2584:in `validate'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:70:in `block in validate'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:70:in `validate'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:162:in `validate_spec'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:176:in `block in load_spec_files'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:170:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:170:in `load_spec_files'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:105:in `local_specs'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/source/path.rb:113:in `specs'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:600:in `specs_for_source_changed?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:585:in `specs_changed?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:629:in `block in converge_paths'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:628:in `any?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:628:in `converge_paths'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:119:in `initialize'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `new'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:234:in `to_definition'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:13:in `evaluate'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/definition.rb:34:in `build'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:195:in `definition'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `block in <top (required)>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/home/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfconsole:17:in `<main>'

**Comment by TonieyX** [comment]
Please someone should help 🥺

**Comment by smcintyre-r7** [comment]
Termux is not supported, see: #11023.
