### ISSUE TITLE
Which is better for a stable session?

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#16444]
Are the Metasploit Meterpreter sessions more stable on WAN if used with regular IP addresses as LHOSTS or with the local loopback 127.0.0.1 as multi/handler listener and a VPS?

**Comment by bcoles** [comment]
what do you mean

**Comment by Reversing26** [comment]
Basically 127.0.0.1 vs regular IP as listener

**Comment by bcoles** [comment]
Whichever has the most stable connection and static IP address will be more stable.
