### ISSUE TITLE
Error: apksigner not found. If it's not in your PATH, please add it.

### ISSUE THREAD

**Issue by JunGkOogOppA** [rapid7/metasploit-framework#16452]
Can anyone know how to fix Error: apksigner not found. If it's not in your PATH, please add it. Please tell me how to fix this sucker :'(
![Screenshot_20220414-135806](https://user-images.githubusercontent.com/96369229/163345724-a67d15f2-abf1-4eaa-b185-8737f14c94eb.png)

**Comment by bcoles** [comment]
You need `apksigner` to be in your system path.

It is possible that you have not installed `apksigner`. On Kali, you can install `apksigner` with `apt-get install apksigner`.
