### ISSUE TITLE
Which type of payload is less prone to network crash/failures? Staged or Stageless?

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#16464]
.For ie high latency

**Comment by bcoles** [comment]
Stageless are generally more reliable; however, it depends how they are executed as stageless isn't always an option.

* https://www.offensive-security.com/metasploit-unleashed/payload-types/
* https://buffered.io/posts/staged-vs-stageless-handlers/
* https://blog.spookysec.net/stage-v-stageless-1/

Once an encrypted connection is successfully established they are equally susceptible to network issues.

**Comment by Reversing26** [comment]
Are the commands SessionExpirationTimout=0 and SessionCommunicationTimout=0 actually helpful to "keep alive" the connection? Or there is something better that can be done?

**Comment by bcoles** [comment]
> Are the commands SessionExpirationTimout=0 and SessionCommunicationTimout=0 actually helpful to "keep alive" the connection? Or there is something better that can be done?

https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Timeout-Control
