### ISSUE TITLE
Metasploit installation error... Pls help

### ISSUE THREAD

**Issue by darknight71** [rapid7/metasploit-framework#16469]
![Screenshot_2022-04-19-01-56-22-73_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/103964340/163872552-951fc6df-1cad-4b0c-badf-d49ef052d8ea.jpg)

**Comment by bcoles** [comment]
Looks like a Ruby 3 issue. Metasploit does not yet fully support Ruby 3.
