### ISSUE TITLE
Tried to apply a self-fix to stageless python meterpreter rev_https but the code logic breaks and session dies

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#16532]
A bug caused by a deprecation of "imp" module in favour of "importlib" may cause an unwanted cmd dialog to popup. I decoded the stageless payload from base64 here, and tried to place imporlib over "imp", but the code logic breaks and session dies (line 1704)
[Code.txt](https://github.com/rapid7/metasploit-framework/files/8627950/Code.txt)

**Comment by adfoster-r7** [comment]
Thanks for raising an issue; Do you have an example of the unwanted cmd dialog?

**Comment by Reversing26** [comment]
A dialog popups claiming:<string>:1704: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

The point is, session works despite the deprecation, but this dialog breaks the stealthy factor of the payload. Furtherly, by closing the dialog manually, session dies. I've tried to fix manually by replacing "imp" with "importlib", but after doing it the payload breaks and stop working. A major skilled tech support is required to fix this, sorry.

**Comment by adfoster-r7** [comment]
Thanks for raising an issue, this should be fixed in the next release - in a week or so from now. Or you can apply the patch to your local install before then :+1:
