### ISSUE TITLE
Cant update metasploit, i think server is leaked

### ISSUE THREAD

**Issue by SkylerVR** [rapid7/metasploit-framework#16534]
![Screenshot_2022-05-05_15-38-31](https://user-images.githubusercontent.com/44336897/166916034-27305e86-1991-4c0b-8d0a-0f68602ff4fa.png)
how i can fix it?

**Comment by bcoles** [comment]
Possible solution for Kali:

https://stackoverflow.com/questions/46616164/use-apt-get-update-e-failed-to-fetch-http-file-has-unexpected-size

**Comment by gwillcox-r7** [comment]
Marking this issue as closed as solution appears to have been posted above, however if this doesn't solve it feel free to comment and we can investigate further.
