### ISSUE TITLE
OSX mettle + x64/xor encoder = bad rebase opcode 239

### ISSUE THREAD

**Issue by enty8080** [rapid7/metasploit-framework#16577]
## Bug decription

Mettle fails to execute after being encoded with `x64/xor` encoder.

## Steps to reproduce

```
msfvenom -p osx/x64/meterpreter_reverse_tcp -f macho -e x64/xor > /tmp/mettle
```

```
chmod 777 /tmp/mettle
/tmp/mettle
```

## Error

```
dyld: bad rebase opcode 239 in /tmp/mettle
zsh: abort      /tmp/mettle
```

## Additional information

It is also worth mentioning that meterpreter successfully executes without being encoded.

After an analysis I found that you encoding the whole executable with xor and then msfvenom wraps it with another one. Why are you doing this?

`x64/xor` encodes the whole macho executable and then it just adds it to another macho template. So it looks like an encrypted executable file in another executable file. Thats kinda strange, isn't it?

**Comment by enty8080** [comment]
30 days of inactivity on such important problem, okay, I can deal with that. Mettle can not be encoded, so that's the problem.

Thanks.

**Comment by adfoster-r7** [comment]
I haven't looked into this particular area before, but if you're able to resolve the issue contribute a fix - that would be appreciated! :+1:

**Comment by enty8080** [comment]
@adfoster-r7 It is not possible, because mettle can not be encoded, just remove an ability to encode it from msfvenom, because it is not possible to encode an executable, which mettle is.
