### ISSUE TITLE
can´t start metasploit on Kali!

### ISSUE THREAD

**Issue by mmuncan1980** [rapid7/metasploit-framework#16574]
$ sudo msfdb init && msfconsole
[sudo] Passwort für jamy: 
Metasploit running on Kali Linux as root, using system database
A database appears to be already configured, skipping initialization
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.
┌──(jamy㉿r00t)-[~]

rvm has been reinstalled, but the error is still there...

**Comment by dedshit** [comment]
installing rake will fix your problem
