### ISSUE TITLE
Escape equal sign in meterpreter run command

### ISSUE THREAD

**Issue by ohphee2lo9Oh** [rapid7/metasploit-framework#16586]
## Relevant information

I would like to run such command `meterpreter > run post/windows/manage/execute_dotnet_assembly DOTNET_EXE=Seatbelt.exe ARGUMENTS=-group=all`

But the ARGUMENTS param get splitted because of the equal sign for `-group=all`. And Seatbelt executable receives only `-group` argument.

Is there a way to escape equal sign ? Couldnt find any.

**Comment by adfoster-r7** [comment]
Looks like a duplicate of https://github.com/rapid7/metasploit-framework/issues/16578 - the work around posted over there should work :+1:

Out of interest, are you doing a lab/room/tutorial?

**Comment by ohphee2lo9Oh** [comment]
Oh sorry I encountered the issue a few weeks ago and didnt find corresponding issue, took me some time pull that one.
The workaround does work, it is just more convenient to do it oneline :smile: 
I'm playing with metasploit doing offensive security lab.

**Comment by adfoster-r7** [comment]
Thanks for the update :+1:

I believe you should be able to do it in two lines from the main msfconsole as well:

```
use post/windows/manage/execute_dotnet_assembly
run DOTNET_EXE=/tmp/Seatbelt.exe ARGUMENTS="-group=all"
```

**Comment by adfoster-r7** [comment]
I'll close this as a duplicate and keep the previous ticket around. Thanks for raising this :+1:
