### ISSUE TITLE
Python/Meterperter/Reverse_TCP - Change ‘Require’ setting under advanced option 

### ISSUE THREAD

**Issue by joeyblack3** [rapid7/metasploit-framework#16594]
Hi guys. I really need some help. I want to modify some settings under the advanced options on the payload of Python/Meterperter/Reverse_TCP. How do I change the ‘Required’ option from no to yes? 
![BD03CD7F-42D6-4E3A-A45A-A3657DE088E7](https://user-images.githubusercontent.com/88906231/169337862-5a0160ed-eff2-42c1-ab6d-b9698fdd11a0.jpeg)

**Comment by dwelch-r7** [comment]
You can't, not without altering the code anyway, any options that are `Required` are necessary for the payload to function correctly, maybe someone here can help you out if you provide some details on what option you're struggling with and why you need it to not be required?

**Comment by adfoster-r7** [comment]
Also answered over here by someone else on the Metasploit reddit:

> Required just means you have to set the value for the script to run.
> You are not meant to change the value of "required" between yes and no, only change the value of the settings
> https://www.reddit.com/r/metasploit/comments/ut50bk/how_do_i_change_the_settings_under_the_required/

Closing :+1:
