### ISSUE TITLE
How to add the label "not stale" to keep my issue open?

### ISSUE THREAD

**Issue by ZhiboWong** [rapid7/metasploit-framework#16609]
My another issue  is stale now in this repo . I do not see the settings icon.Is this because the owner of the repo set others can not add labels?
![811b36e513922bf87c0e09b85cceb6f](https://user-images.githubusercontent.com/52378662/169956658-9fc06c84-c67a-429c-b85b-08059796bb8f.png)

**Comment by bcoles** [comment]
> My another issue is stale now in this repo . I do not see the settings icon.Is this because the owner of the repo set others can not add labels?

Only contributors can set the `not stale` label.

The question asked in #16427 has been answered.
