### ISSUE TITLE
cloud_lookup with censys

### ISSUE THREAD

**Issue by e2002e** [rapid7/metasploit-framework#16656]
In auxilliary/gather/cloud_lookup.rb
line 172: "www.censys.io" must be replaced with "search.censys.io"
line 177: the uri must be "/api/v2/hosts/search"

Finally, line 299: records.each do |ipv4| must be replaced with records['hits'].each do |ipv4|

**Comment by Arpit-mohankar** [comment]
@e2002e hey can i work on this issue?

**Comment by bcoles** [comment]
> @e2002e hey can i work on this issue?

This issue should already be resolved.
