### ISSUE TITLE
hashdump.rb:47:in `run'

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#16652]
meterpreter > run  post/windows/gather/hashdump

[*] Obtaining the boot key...
[-] Post failed: NoMethodError undefined method `unpack' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:47:in `run'

**Comment by adfoster-r7** [comment]
I assume your Meterpreter process is running without the permissions to read the bootkey here

https://github.com/rapid7/metasploit-framework/blob/e79161c236037c4a5b9f6ad6a46cb421869d9376/lib/msf/core/post/windows/priv.rb#L241-L257

And we're missing a nil check here:
https://github.com/rapid7/metasploit-framework/blob/e79161c236037c4a5b9f6ad6a46cb421869d9376/modules/post/windows/gather/hashdump.rb#L44-L48

We'd require additional insight into exact replication steps, i.e. target information + session information

**Comment by adfoster-r7** [comment]
If you modify https://github.com/rapid7/metasploit-framework/blob/e79161c236037c4a5b9f6ad6a46cb421869d9376/modules/post/windows/gather/hashdump.rb#L98 to be:

```ruby
        $stderr.puts users[rid]
        credential_data[:username] = users[rid][:Name].to_s.downcase
```

It should fix the crash, and also log out the user's object. If you'd like to share what's in that object we may be able to provide a better solution

**Comment by kokxxoo** [comment]
[*] Obtaining the boot key...
[*] Calculating the hboot key using SYSKEY e3b840a9af9c95f8771783af867b6d4a...
[*] Obtaining the user list and keys...
[*] Decrypting user keys...
[-] Unknown user hash revision: 243
[*] Dumping password hints...

No users with password hints on this system

[*] Dumping password hashes...


[-] Post failed: NoMethodError undefined method `downcase' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:98:in `block in run'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:93:in `each'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:93:in `run'
