### ISSUE TITLE
smb_login module fails to highlight Administrators

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#16745]
## Steps to reproduce

1. use auxiliary/scanner/smb/smb_login
2. Login with local admin creds

## Expected behavior

AccessLevel should be set to Administrator and console output should show Administrator

## Current behavior

No output indicating an admin is identified. An exception is rescued and therefore hidden:

"undefined method add_file for [tree.permissions]"

### Metasploit version

6.1.39-dev

## Additional Information

An admin has permissions such as `:read_data=>1` or `:write_data=>1`

Code responsible:

https://github.com/rapid7/metasploit-framework/blob/5b8680ee91d181f82a232f3c7f1695e96ff20e15/lib/metasploit/framework/login_scanner/smb.rb#L108-L116

**Comment by Meatballs1** [comment]
It looks like ruby_smb is returning a file access mask rather than a directory access mask:

https://github.com/rapid7/ruby_smb/blob/master/lib/ruby_smb/smb2/bit_field/file_access_mask.rb

vs 

https://github.com/rapid7/ruby_smb/blob/5feba411750ca08755e7fedbc8ebd266d438b2b7/lib/ruby_smb/smb2/bit_field/directory_access_mask.rb#L14

**Comment by adfoster-r7** [comment]
cc @cdelafuente-r7 - Would you have any thoughts on this? 👀

**Comment by cdelafuente-r7** [comment]
I confirmed the issue and fixed it in https://github.com/rapid7/ruby_smb/pull/235. Thanks @Meatballs1 for reporting this! Please, let me know if this fixes it in your environment.
