### ISSUE TITLE
./metasploit[...].run 2: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by Vettl5** [rapid7/metasploit-framework#16787]
I have an issue with installing the metasploit framework on my Kali Distribution.
My actuall Kali Version is the 2022.2. 

I followed the steps installing MSF from this site (German Version):  https://www.linuxcapable.com/de/how-to-install-metasploit-framework-on-ubuntu-20-04/#Install_Metasploit_for_Ubuntu_2004

I used the following commands: 
1. wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run
2. sudo chmod +x ./metasploit-latest-linux-x64-installer.run (for giving executing rights to the user)
3. sudo ./metasploit-latest-linux-x64-installer.run

And the last command is where the error appeared. (see the image)
![metasploit issue](https://user-images.githubusercontent.com/100218653/179741574-3b23bd8f-8b3d-4359-9d57-430d967e3e80.png)

I would be very gratefull, if anyone could help me properly. 
Kind regards :)

**Comment by bcoles** [comment]
Are you using a 64-bit system? What is the output of `uname -m` ?

Did the file download correctly? What is the output of  `file` and `md5sum` ?

```
$ file metasploit-latest-linux-x64-installer.run 
metasploit-latest-linux-x64-installer.run: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, no section header
```

```
$ md5sum metasploit-latest-linux-x64-installer.run 
82afe7bc724d4a99fc903d73c2150fff  metasploit-latest-linux-x64-installer.run
```

**Comment by Vettl5** [comment]
The output of uname -m is 'x86_64'.
The file downloaded, as far as i noticed, correctly (no errors were thrown). 

I am not quiet sure, what i am supposed to do with the code that md5sum responded (aebd6f4775420bd503365756f9715041)

**Comment by bcoles** [comment]
> The file downloaded, as far as i noticed, correctly (no errors were thrown).

What is the output of `file metasploit-latest-linux-x64-installer.run` ? Is it a valid 64-bit ELF?

> I am not quiet sure, what i am supposed to do with the code that md5sum responded (aebd6f4775420bd503365756f9715041)

Can you try downloading the file again? The md5sum should match mine shown above `82afe7bc724d4a99fc903d73c2150fff`.

**Comment by bcoles** [comment]
> I tried deleting and downloading it again several minutes ago, but the error remains.
> 
> The output of `file metasploit-latest-linux-x64-installer.run` is "HTML Document, ASCCII text, with very long lines"

Whatever you downloaded is not the Metasploit installer. You have downloaded a HTML document.

I suggest double checking that you are using the correct URL and downloading the file using some other means. Use a web browser if possible. It is possible that a content filtering proxy has blocked the file and you have downloaded a warning page. If the file is small you could try opening it in a text editor. Alternatively: `head -n 100 metasploit-latest-linux-x64-installer.run`.

**Comment by Vettl5** [comment]
Just to make sure; could you send in the right url please? I am not too lazy to google for it, but i don't want to have any further installing problems (just in case).

**Comment by bcoles** [comment]
You could also try downloading using HTTPS, which is less likely to be blocked by a content filtering proxy, although may still be blocked if access to `downloads.metasploit.com` is forbidden.

```
wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run
```

**Comment by Vettl5** [comment]
Nice, thanks. I am back in a minute
