### ISSUE TITLE
Msfconsole is not working and throwing error

### ISSUE THREAD

**Issue by Shivam352** [rapid7/metasploit-framework#16780]
Hello guys,

After updating kali to latest version, I got this error. Can someone provide help here?
```
└─$ msfconsole
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError) from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in class:EcdsaSha2Nistp256'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:10:in <class:ServerHostKeyAlgorithm>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:9:in class:Transport'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:8:in <module:HrrRbSsh>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:7:in <top (required)>'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm.rb:19:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:16:in <top (required)>'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in <top (required)>'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in default_version_string'
from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in initialize' from /usr/share/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in initialize'
from /usr/share/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in initialize' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in new'
from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in block (2 levels) in recalculate' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in each_pair'
from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in block in recalculate' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in each_pair'
from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in recalculate' from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in block in load_modules'
from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in each' from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in load_modules'
from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in block in load_modules' from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in each'
from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in load_modules' from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in block in add_module_path'
from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in each' from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in add_module_path'
from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in block in init_module_paths' from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in each'
from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in init_module_paths' from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:160:in initialize'
from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in new' from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in driver'
from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in start' from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in start'
 from /usr/bin/msfconsole:23:in `<main>'
```

**Comment by Pri3st** [comment]
Same thing for me.

**Comment by h00die** [comment]
Possibly related to #16767 or its fix, but untested.

**Comment by Shivam352** [comment]
> Hello guys,
> 
> After updating kali to latest version, I got this error. Can someone provide help here?
> 
> ```
> └─$ msfconsole
> /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError) from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in class:EcdsaSha2Nistp256'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:10:in <class:ServerHostKeyAlgorithm>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:9:in class:Transport'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:8:in <module:HrrRbSsh>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:7:in <top (required)>'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm.rb:19:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:16:in <top (required)>'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in <top (required)>'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in <top (required)>' from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require'
> from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in require' from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in default_version_string'
> from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in initialize' from /usr/share/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in initialize'
> from /usr/share/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in initialize' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in new'
> from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in block (2 levels) in recalculate' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in each_pair'
> from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in block in recalculate' from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in each_pair'
> from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in recalculate' from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in block in load_modules'
> from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in each' from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in load_modules'
> from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in block in load_modules' from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in each'
> from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in load_modules' from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in block in add_module_path'
> from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in each' from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in add_module_path'
> from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in block in init_module_paths' from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in each'
> from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in init_module_paths' from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:160:in initialize'
> from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in new' from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in driver'
> from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in start' from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in start'
>  from /usr/bin/msfconsole:23:in `<main>'
> ```

So I found a workaround. Make sure you are under folder where you want metasploit db to be created. We can use it until we get any update. Follow below mentioned steps

```
1. apt-get remove metasploit-framework     -> also remove if there are any folder in /usr/share/metasploit...
2. curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
3. chmod 755 msfinstall && \
4. ./msfinstall
```

**Comment by loneicewolf** [comment]
same thing here; thanks for workaround.

**Comment by loneicewolf** [comment]
> The crash should be fixed in last week's 6.2.8 release - as noted by [#16767 (comment)](https://github.com/rapid7/metasploit-framework/issues/16767#issuecomment-1185395510)

Okay; thanks for the heads up!
#### no stress; you guys doing great !

:+1:

**Comment by ksaadDE** [comment]
someone put a report on kali bugtracker as well^^ 
https://bugs.kali.org/view.php?id=7804

**Comment by carlpadilla** [comment]
Thank you for the workaround!

**Comment by adfoster-r7** [comment]
Closing as duplicate; This patch should work for now if you are on Kali - https://github.com/rapid7/metasploit-framework/issues/16767#issuecomment-1185395510

**Comment by loneicewolf** [comment]
THANKS!

**Comment by OtojonKhudayarov** [comment]
same problem with me , i think kali's latest version holds some broken packages.Try reinstall =>`  `$ sudo apt-get remove metasploit-framework`         and  `$ sudo apt install metasploit-framework `
           and it worked for me :)

**Comment by scriptkid2222** [comment]
> mesmo problema comigo, acho que a versão mais recente do kali contém alguns pacotes quebrados. Tente reinstalar => ` `$ sudo apt-get remove metasploit-framework ` and `$ sudo apt install metasploit-framework ` e funcionou para mim :)

Это сработало

**Comment by Muxitdinovich** [comment]
apt update
apt upgrade
apt clean
apt install --reinstall metasploit-framework

try

**Comment by Muxitdinovich** [comment]
```
apt update
apt upgrade
apt clean
apt install --reinstall metasploit-framework
```

try 2
