### ISSUE TITLE
Typo in zsh completion file _msfvenom causes error on --arch completion

### ISSUE THREAD

**Issue by FalcoGer** [rapid7/metasploit-framework#16838]
## Issue

There is a typo in [/external/zsh/_msfvenom](https://github.com/rapid7/metasploit-framework/blob/d6738c3b1832d7c007a4091ba34033a638706663/external/zsh/_msfvenom#L234) on line 234.

```text
{-a,--arch}"[The architecture to use for --payload and --encoders (use --list archs to list)]:architecture:_msfvenom_archs" \
```
should be
```text
{-a,--arch}"[The architecture to use for --payload and --encoders (use --list archs to list)]:architecture:_msfvenom_arch" \
```

This causes the lookup to fail.

## Steps to reproduce

1. Enable the ZSH completion script for msfvenom
2. Type `msfvenom --arch ` and hit tab
3. ??
4. No profit.

## Expected behavior

I'm presented with a list to pick from

## Current behavior

```text
msfvenom --arch …_msfvenom_archs: command not found
_msfvenom_archs: command not found
_msfvenom_archs: command not found
```

**Comment by smcintyre-r7** [comment]
Yup, I was able to reproduce this. I'll get a fix submitted shortly.
