### ISSUE TITLE
Windows installer doesn't appear to actually install anything

### ISSUE THREAD

**Issue by robotski** [rapid7/metasploit-framework#16855]
## Steps to reproduce

(Running Windows 10 with antivirus disabled)
Run metasploit-framework 6.2.11 msi installer.

The installer runs for a decent amount of time, and claims to have completed successfully, but there's no sign of the framework anywhere.
Nothing in Program Files.
C:\metasploit-framework doesn't exist, and if I make it manually then there's nothing in there after running the installer.
Nothing dumped on the root of my hard drive.

## Were you following a specific guide/tutorial or reading documentation?

[Official install guide.](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html#installing-metasploit-on-windows)

## Expected behavior

msfconsole starts

## Current behavior

'msfconsole' is not recognized as an internal or external command, operable program or batch file.

### Metasploit version

6.2.11

**Comment by Alexlcr** [comment]
Hi did you tried to lauch the "msfconsole.bat" in C:\metasploit-framework\bin ? it work for me
