### ISSUE TITLE
Windows Meterpreter does stack spoofing by default?

### ISSUE THREAD

**Issue by GetRektBoy724** [rapid7/metasploit-framework#16874]
I was messing around with Windows Meterpreter (generated from MSF v6.2.9-dev) with Process Hacker, the Meterpreter was idling and when I checked the Meterpreter thread stack, I saw this.
![image](https://user-images.githubusercontent.com/41237415/183278584-9d8196e9-d422-4f9b-9a03-a963555c2192.png)
All of the function call before `ws2_32.dll!select+0x137` is an invalid address or don't contain any relevant `call` or `jmp` instruction.
And then I decided to do another test, this time I let the Meterpreter doesn't connect to the listener.
![image](https://user-images.githubusercontent.com/41237415/183278791-d63e8f44-76fe-4db9-acf3-1de8b881973c.png)
Again, all of the function call before `ws2_32.dll!connect+0x9b` is an invalid address or don't contain any relevant `call` or `jmp` instruction. So, is this a valid stack spoofing or just a piece of accidental luck?

**Comment by smcintyre-r7** [comment]
There's no intentional stack spoofing. It's probably an artifact left over from the stager.
