### ISSUE TITLE
Sip Invite Spoof not working?

### ISSUE THREAD

**Issue by Archilla1** [rapid7/metasploit-framework#16886]
## Relevant information

Hi! I am currently learning a bit about Metasploit. I am currently working on Sip Invite Spoof, but it seems I cannot get it to work. I might be doing something wrong, but right now I have no clue. I am trying to send it to my own phone just to understand how it works. This is what I have:

```
Module options (auxiliary/voip/sip_invite_spoof):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   DOMAIN                      no        Use a specific SIP domain
   EXTENSION                   no        The specific extension or name to target
   MSG        Private Number   yes       The spoofed caller id to send
   RPORT      5060             yes       The target port (UDP)
   SRCADDR    192.168.0.17     yes       The sip address the spoofed call is coming from
   THREADS    5                yes       The number of concurrent threads (max one per host)

msf6 auxiliary(voip/sip_invite_spoof) > run
[*] Auxiliary module execution completed
msf6 auxiliary(voip/sip_invite_spoof) > 
```

IP address is taken from my phones network info (connected to Wi-Fi). From what I have seen from different people on videos and the current class I'm taking, there is a scanning right before that [*] Auxiliary module..... command. So far I have not received anything. Tried a different IP and still nothing. Any help? Thank you all!

**Comment by h00die** [comment]
I would start by opening a packet capture utility like wireshark to capture packets to determine if any are being sent out, and if they're in a correct format (aka wireshark can parse it).  You never hit this statement: https://github.com/rapid7/metasploit-framework/blame/master/modules/auxiliary/voip/sip_invite_spoof.rb#L73 so something seems to have died before that.

https://github.com/rapid7/metasploit-framework/blame/master/modules/auxiliary/voip/sip_invite_spoof.rb
This module hasn't had a meaningful code check in ~10 years.  On top of that, I know at least some of the sip udp stuff doesn't work (#10796).

It could be a protocol update/change, could be smarter phones sending a pingback or something... hard to tell, you'll have to investigate on your own and report back!

**Comment by Archilla1** [comment]
okay! ill figure it out and come back! I will close! Thank you
