### ISSUE TITLE
automotive / Identify modules bug

### ISSUE THREAD

**Issue by dmgciubotaru** [rapid7/metasploit-framework#16916]
## Overview

There are several problems with the `automotive/identifymodules` module:

#### Logic error inside the code
This error prevents the code from running
https://github.com/rapid7/metasploit-framework/blame/master/modules/post/hardware/automotive/identifymodules.rb#L35
The list iteration should be done if the `res["Packets"]` is not empty, so the line should be `next if res["Packets"].empty?`

#### Response validation
The code identify the modules only if there is a nevative response on the request, but most of the ECUs are supporting the service $10 and would respond with a valid response.
So the check on https://github.com/rapid7/metasploit-framework/blame/master/modules/post/hardware/automotive/identifymodules.rb#L37

Should check for both negative resonse (0x03, 0x7f, 0x10, 0xXX) [Negative response format](https://uds.readthedocs.io/en/latest/pages/knowledge_base/diagnostic_message.html#negative-response-message)
And positive responses (0xXX, 0x40, 0x01, 0xYY ... ) [Positive response format](https://uds.readthedocs.io/en/latest/pages/knowledge_base/diagnostic_message.html#positive-response-message)
The first extra byte is from (ISOTP header)[https://en.wikipedia.org/wiki/ISO_15765-2] used as transport layer for UDS protocol

## Steps to reproduce

Inside `msfconsole` run 
```
use auxiliary/server/local_hwbridge
set uripath trycanbus
set SRVPORT 8099
run

use auxiliary/client/hwbridge/connect
set targeturi trycanbus
set RPORT 8099
run

use post/hardware/automotive/identifymodules
set CANBUS can0
set SESSION 1
set STARTID 1792
set ENDID 2047
run
```

## Expected behavior

The  `automotive/identifymodules` should be able to run and also detect the modules that supports $10

### Metasploit version

This problem is present in the code since 2016

**Comment by adfoster-r7** [comment]
Thanks for raising an issue; If you're happy sending a pull request, that would be great!
I don't think there's anyone actively working on these modules currently

**Comment by dmgciubotaru** [comment]
I would like to but I'm not allowed due to my company policy.
I guess you can do that, right ? 
https://pastebin.com/MLeVmdzM
