### ISSUE TITLE
Metasploit-framework v6.2.13 setup wizard ended prematurely even with exclusion to C:\metaspliot-framework

### ISSUE THREAD

**Issue by MarkAppprogrammer** [rapid7/metasploit-framework#16919]
## Steps to reproduce

How'd you do it?

1. download Metasploit for windows
2. create exclusion for C:\metaspliot-framework
3. open file metasploitframework-latest

## Expected behavior

Should have installed correctly

## Current behavior

Does not install no matter the times you try.

### Metasploit version

v6.2.13

## Additional Information

none

**Comment by bcoles** [comment]
Run the installer with administrator privileges.

**Comment by 2096779623** [comment]
![image](https://user-images.githubusercontent.com/57583560/189827768-da22efce-33b0-4e0b-8641-f4ba361c8e51.png)

**Comment by TMGboy** [comment]
same issue v6.3.48
