### ISSUE TITLE
ignoring updates?

### ISSUE THREAD

**Issue by archuser555** [rapid7/metasploit-framework#16956]
Yes, I Think This Would Be HelpFull, because my data plan can't update msf every 2 weeks, i think this feature can let me go deeper with ruby and cyber security, Thanks!

**Comment by smcintyre-r7** [comment]
I'm not aware of any automatic update functionality so if you'd like to ignore updates, I'd suggest you simply don't update.

Let me know if there is an automatic update feature somewhere that I'm not aware of.
