### ISSUE TITLE
To install metasploit in Ubuntu use this 

### ISSUE THREAD

**Issue by HocasPocas** [rapid7/metasploit-framework#16951]
<h4>Use the command in Ubuntu</h4>
<p>apt -y install git ruby ruby-dev make clang autoconf curl wget libsqlite-dev postgresql libpcap-dev libffi-dev libxslt-dev pkg-config; git clone https://github.com/rapid7/metasploit-framework; cd metasploit-framework; gem install bundler; sudo bundle install</p>

**Comment by adfoster-r7** [comment]
We have installation steps here: https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html#linux

Is there anything missing from that page?

**Comment by HocasPocas** [comment]
Um well in am new to hacking so don't mind it and if it has an error so you
can also delete that issue.
thanks for giving your precious time
Thankyou

**Comment by gwillcox-r7** [comment]
Closing this issue as existing documentation already exists as per Alan's comment. If you believe this documentation is insufficient or wrong, please let us know and we'll be happy to reopen this and investigate further.

**Comment by HocasPocas** [comment]
Thanks for replying me. As i appreciate metasploit more and I have already
searched many of the websites to install metasploit in Ubuntu while I have
found a method which I showed using issues in GitHub.
Thankyou
