### ISSUE TITLE
what is the point of killav if all av have anti-tampering and self-defense?

### ISSUE THREAD

**Issue by czonta96** [rapid7/metasploit-framework#16971]
.

**Comment by bcoles** [comment]
The [killav](https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/manage/killav.rb) module is a port of the `killav` script which was originally written in 2006.

It takes a list of process names as input and terminates all running processes with these names. The [av_hips_executables.txt](https://github.com/rapid7/metasploit-framework/blob/master/data/wordlists/av_hips_executables.txt) wordlist is used by default.

The default word list includes many products, include anti-virus/anti-malware software and host firewall software.
