### ISSUE TITLE
iax2  Auxiliary failed: NameError uninitialized constant

### ISSUE THREAD

**Issue by somavovodowe55** [rapid7/metasploit-framework#16997]
**i try to use use auxiliary/scanner/voice/recorder on msfconsole** 
i was set all options good  with out any error 
but on i run i have this 

msf6 auxiliary(scanner/voice/recorder) > run

[-] Auxiliary failed: NameError uninitialized constant Rex::Proto::IAX2::Client::IAX2_DEFAULT_PORT
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24:in `initialize'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/iax2.rb:38:in `new'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/iax2.rb:38:in `connect'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/voice/recorder.rb:28:in `run'
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/voice/recorder) >

how i can solve this error

**Comment by adfoster-r7** [comment]
Hi there, thanks for raising an issue. Does this code change fix the module crash for you?

https://github.com/rapid7/metasploit-framework/pull/16998

**Comment by somavovodowe55** [comment]
I am looking for a solution to the problem . so how i can fix it

**Comment by bcoles** [comment]
> I am looking for a solution to the problem . so how i can fix it

Apply the changes in #16998

https://github.com/rapid7/metasploit-framework/pull/16998/files

**Comment by somavovodowe55** [comment]
same error

**Comment by somavovodowe55** [comment]
Is there a command in Metasploit to save updates on the client file?
and activate it on the project

**Comment by bcoles** [comment]
> Is there a command in Metasploit to save updates on the client file? and activate it on the project

For modules, you can run `reload_all` to reload all modules or `use` a module then run `reload`.

However, these changes are for a library. You can run `edit lib/rex/proto/iax2/client.rb`  from within `msfconsole`. This will open the library file in a text editor. When you close the editor the library will be reloaded automatically.

**Comment by somavovodowe55** [comment]
[root@G07E42 ~]# msfconsole
/opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24: warning: key :server_port is duplicated and overwritten on line 25

**Comment by bcoles** [comment]
> [root@G07E42 ~]# msfconsole /opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24: warning: key :server_port is duplicated and overwritten on line 25

That's unrelated. It is expected that existing variables will be overwritten when reloading a library.

**Comment by somavovodowe55** [comment]
how to reloading a library . the command reload is not found

**Comment by bcoles** [comment]
> how to reloading a library

You can run `edit lib/rex/proto/iax2/client.rb`  from within `msfconsole`. This will open the library file in a text editor. When you close the editor the library will be reloaded automatically.

> the command reload is not found

`reload` must be run from within `msfconsole`. `reload` does not reload libraries.

**Comment by somavovodowe55** [comment]
how i can save file after edit using >> edit lib/rex/proto/iax2/client.rb sir ?

**Comment by bcoles** [comment]
> how i can save file after edit using >> edit lib/rex/proto/iax2/client.rb sir ?

The same way you would save any other file with your text editor. For `vim`, use `:wq`.

**Comment by somavovodowe55** [comment]
/opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24: warning: key :server_port is duplicated and overwritten on line 25

**Comment by bcoles** [comment]
> /opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24: warning: key :server_port is duplicated and overwritten on line 25

That's unrelated. It is expected that existing variables will be overwritten when reloading a library.

**Comment by somavovodowe55** [comment]
now i edit file good and i  reload lib using this command 

msfconsole 
msf6 > reload_lib /opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb
msf6 > use auxiliary/scanner/voice/recorder


msf6 auxiliary(scanner/voice/recorder) > run iax_host=xxx.xxx.xxx.xxx targets=1-555-555-5555 output_path=/root/Desktop/xx

[-] Auxiliary failed: NameError uninitialized constant Rex::Proto::IAX2::Client::IAX2_DEFAULT_PORT
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/proto/iax2/client.rb:24:in `initialize'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/iax2.rb:38:in `new'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/iax2.rb:38:in `connect'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/voice/recorder.rb:28:in `run'
[*] Auxiliary module execution completed

i have same error
