### ISSUE TITLE
Does anyone have a copy or link to download the last published x86 version of Metasploit?

### ISSUE THREAD

**Issue by boopxyz** [rapid7/metasploit-framework#16996]
Need to run Metasploit on an x86 machine (no I can't make it x64), does anyone have the latest version released for x86 by any chance?

**Comment by Okta16** [comment]
msf support for x86 ended in 2016 if i'm not wrong

**Comment by gwillcox-r7** [comment]
@Okta16 is correct. See https://docs.rapid7.com/metasploit/support-for-32-bit-operation-systems/ for more details. We no longer provide 32 bit versions of the installers. If you would like to set up a development environment which will allow you to run Metasploit on an x86 system, please see https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html
