### ISSUE TITLE
Module "rollback_defender_signatures" Options Error - Case Sensitive

### ISSUE THREAD

**Issue by diggidong** [rapid7/metasploit-framework#16999]
![2022-09-09_10-01-27](https://user-images.githubusercontent.com/9928172/189302527-6b530957-411c-4e2a-8826-fc3215396222.png)

## Steps to reproduce

How'd you do it?

1. Having a Meterpreter Session "1"
2. Loading module "windows/manage/rollback_defender_signatures"
3. Setting Session "set SESSION 1"
4. Checking options: "ACTION" is set to "Rollback" but "Description says "Accepted: rollback, update" (case sensitive!)
5. Running module
6. Getting Error: "[-] Post failed: Msf::OptionValidateError One or more options failed to validate: ACTION."
7. Setting option "ACTION" to lower case "rollback": "set ACTION rollback"
8. Running module
9. Works

## Expected behavior

Should work as expected, as all mandatory options have been set correctly.

## Current behavior

Getting Error: "[-] Post failed: Msf::OptionValidateError One or more options failed to validate: ACTION."

### Metasploit version
```
Framework: 6.2.15-dev
Console  : 6.2.15-dev
```

**Comment by Hemanthbysani** [comment]
This is a simple fix i guess, changing the file [https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/manage/rollback_defender_signatures.rb](url) which contains `OptEnum.new('ACTION', [ true, 'Action to perform (Update/Rollback)', 'Rollback', ['rollback', 'update']])` to `OptEnum.new('ACTION', [ true, 'Action to perform (Update/Rollback)', 'rollback', ['rollback', 'update']])` fixes it.
![image](https://user-images.githubusercontent.com/23504605/189491980-c6fca60c-10ed-45f7-8d8a-a29e5e66ee50.png)

**Comment by Hemanthbysani** [comment]
@smcintyre-r7 I guess we can close this issue?

**Comment by smcintyre-r7** [comment]
The change should be merged in before closing the issue. I'll see about opening a PR to fix it.
