### ISSUE TITLE
Could not find rake-13.0.6 in any of the sources

### ISSUE THREAD

**Issue by saheredelgadom** [rapid7/metasploit-framework#17039]
does not start neither msfdb nor msfconsole error

$msfdb init or msfconsole

**Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.**

The gems are installed, I already did bundle install, all dependencies were installed, uninstall and install metasploit again, ubuntu system is up to date, I don't know what else to do.

**Comment by jsmit260** [comment]
I'm having the same experience on a Ubuntu box:
5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
