### ISSUE TITLE
msfdb init does not work

### ISSUE THREAD

**Issue by Sergiosteles** [rapid7/metasploit-framework#17037]

**Comment by bcoles** [comment]
What does "does not work" mean?

**Comment by Sergiosteles** [comment]
I have been doing tests with the command msfdb init, reinit, delete, start, etc... and when I execute msfdb to activate the storage of the scans that I do with smfconsole in a database right after the message at the beginning "creating initial database schema" points out a bug:

/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/pg-1.4.3/lib/pg/connection.rb:602: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]

Then it shows a lot of information "Control frame information" and finally an error in /usr/bin/msfdb line 67 33177 aborted bundle exec rake db:migrate > /dev/null

I've restarted the postgresql service and tried to access msfconsole, but I can't do it with a connected database, although it does allow me to access msfconsole without connecting it.

**Comment by Sergiosteles** [comment]
> What does "does not work" mean?

I have been doing tests with the command msfdb init, reinit, delete, start, etc... and when I execute msfdb to activate the storage of the scans that I do with smfconsole in a database right after the message at the beginning "creating initial database schema" points out a bug:

/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/pg-1.4.3/lib/pg/connection.rb:602: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]

Then it shows a lot of information "Control frame information" and finally an error in /usr/bin/msfdb line 67 33177 aborted bundle exec rake db:migrate > /dev/null

I've restarted the postgresql service and tried to access msfconsole, but I can't do it with a connected database, although it does allow me to access msfconsole without connecting it.
