### ISSUE TITLE
Module web_vulndb.rb

### ISSUE THREAD

**Issue by saheredelgadom** [rapid7/metasploit-framework#17043]
This module has an option that is:

VULNCSV yes Path of vulnerabilities csv file to use

how to build a csv file to fulfill this need?

Does this file have a specific format?

what should go inside it?

Could you please give me a format as this file should be?

**Comment by h00die** [comment]
This file (https://github.com/rapid7/metasploit-framework/commits/master/modules/auxiliary/scanner/http/web_vulndb.rb) and previously named (https://github.com/rapid7/metasploit-framework/commits/7964d0f38a44033da1b5e721c3b5d39a9124e944/modules/auxiliary/scanner/http/wmap_web_vulndb.rb?browsing_rename_history=true&new_path=modules/auxiliary/scanner/http/web_vulndb.rb&original_branch=master) hasn't had a meaningful update in 13 years. There is no module docs (that wasn't a thing back then), and I don't see an original PR that included this.  Googling around, https://seclists.org/metasploit/2010/q1/103 is the best thing I can find that has any information at all.  They say there is a default file, I don't see it in the framework anymore so it was either lost to the sands of time, or deleted for a reason at some point.

If you're able to find any information, please let us know!

**Comment by Techno-Fox** [comment]
I would be interested in this as well. I remember when I was trying to update the openvas plugin, then greenbone security broke everything. Might try that again, but yea not much docs for wmap_web_vulndb, nor updates (i'm surprised)

**Comment by bcoles** [comment]
This module is a naive threaded spray and pray poor man's nikto/nuclei vulnerability scanner. You could also think of it as dirbuster/gobuster with response context text matching.

> Does this file have a specific format?
> what should go inside it?
> Could you please give me a format as this file should be?

A quick test and read of the source reveals the format should be:

```csv
path to something that is known to be vulnerable,text expected to exist in the response,notes/comment about why this is interesting/vulnerable
```

For example:
```csv
/awesomePhpSoftware?page=https://google.com/,Google,Awesome PHP Software page parameter RFI vulnerability
```

CSV parsing:

https://github.com/rapid7/metasploit-framework/blob/234949bff8641e128cea5ab363093d5acba938b7/modules/auxiliary/scanner/http/web_vulndb.rb#L123-L127

`puts textarr.inspect` reveals the CSV parsing format:

![web_vulndb](https://user-images.githubusercontent.com/434827/202881087-3d814ec3-edf8-4019-911e-0f1db1799125.png)

Like other content discovery tools (dirbuter/gobuster), the module features 404 detection. Presumably leaving the text matching field empty will simply match `200` status code.

This module was added when the wmap plugin and metasploit database integration were new. The module stores matched URLs in the database as `notes`. The intention was likely to integrate this with `wmap` (which has been neglected for over a decade).

> how to build a csv file to fulfill this need?

The email thread h00die linked above implies that the database is supposed to be automatically generated. There's also a hint that the format may be similar to that of nikto. The format is similar but not identical.

I'm not convinced that there was ever a default CSV file. Maybe.

I'm not sure that any tool to automatically generate the database was ever developed.

However, you should be able to convert existing wordlists to CSV fairly easily; ie:

* https://github.com/xmendez/wfuzz/tree/master/wordlist/vulns
* https://github.com/tennc/fuzzdb/blob/master/attack-payloads/rfi/rfi.txt
