### ISSUE TITLE
meterpreter screenshotting/screensharing in real time not working

### ISSUE THREAD

**Issue by Slavfucious** [rapid7/metasploit-framework#17106]
Hi, so when i get a session so lets say windows 10, when i try to get a screenshot i get a black square as a photo, like 900p or somewhere there. I tried with post module for screenshareing, same shit. i updated my kali with apt update and apt upgrade, metasploit is latest version. Tryed On LAN windows and WAN windows too, no luck

Tryed on VM and it works there (Another Kali install)

Can it be becausue i use windows/meterpreter/reverse_tcp and not /meterpreter/x64/ ? (The windows's are 64bit)

**Comment by bcoles** [comment]
There is not much information to go on. You're suggesting that the captured screenshot is a black square and the session may or may not be on a Windows 10 host of no particular version.

Was the Windows screensaver on when you took the screenshot?

How are you taking screenshots?

* `screenshot` Meterpreter command
* post/multi/manage/screenshare
* post/windows/gather/screen_spy
* something else?

I tried all of the above as a local Administrator on Windows Server 2016. I also tried the `screenshot` command and `post/multi/manage/screenshare` on Windows 11. All worked fine.

What user is the session running as? What type of session? PowerShell / Shell / Meterpreter.

> Tryed on VM and it works there (Another Kali install)

If it works on one VM but not on another then the answer to your question is highly likely to be found within the differences between the two.

> Can it be becausue i use windows/meterpreter/reverse_tcp and not /meterpreter/x64/ ? (The windows's are 64bit)

That shouldn't matter, but you can easily verify this yourself.

**Comment by Slavfucious** [comment]
Hi, i tried screenshot/post-screenshare/screenspy  types of screenshot on meterpreter. the winwows version is 21h2 or somewhere there (not the newest). windows session is running as nt authority.

**Comment by Slavfucious** [comment]
Well, on the vm i am able to do every method for screenshotting or sharing without problem directly from the meterpreter on nt auth. rn i am at work and when i get back imma try to migrate and see if this gets fixed
