### ISSUE TITLE
[Question] Current documentation for Meterpreter's transport layer security?

### ISSUE THREAD

**Issue by HuskyHacks** [rapid7/metasploit-framework#17109]
## Summary
Hello! I'm doing some research on different C2 methods for transport layer security and want to examine the current mechanisms in play with Meterpreter.

I'm looking to answer a simple question: why can I read, in plain text, the I/O for shell_reverse_tcp, but cannot do the same for meterpreter_reverse_tcp under identical circumstances?

I understand that shell_reverse_tcp is a simple /bin/sh piped over a network socket. What I don't understand is what is at play with Meterpreter to prevent its traffic from being seen in cleartext.

shell_reverse_tcp, clear text /bin/sh piped over a network socket. Makes total sense ✅
![image](https://user-images.githubusercontent.com/57866415/194101134-74c944bc-6426-4032-8d54-817a53348ed3.png)

Following the TCP stream of a single Meterpreter command reveals no readable text 🤔:
![image](https://user-images.githubusercontent.com/57866415/194101883-3404de2b-b56e-4a85-a44b-056e32c0477e.png)

I'd appreciate it if someone could point me at the documentation or even the source code for Meterpreter's transport layer encoding/encryption mechanism. Thank you!

## Relevant information

I've read the documentation in and around the Advanced => Meterpreter section [here](https://docs.metasploit.com/docs/using-metasploit/advanced/meterpreter/meterpreter.html) but can't seem to find anything on Meterpreter's TCP en[coding||cryption] on the wire.

**Comment by adfoster-r7** [comment]
If you enable Meterpreter's network logging within msfconsole:

https://docs.metasploit.com/docs/using-metasploit/advanced/meterpreter/meterpreter-debugging-meterpreter-sessions.html#log-meterpreter-tlv-packets

You'll see the very first step is to negotiate aes encryption:

```
msf6 payload(osx/x64/meterpreter_reverse_tcp) > 
SEND: #<Rex::Post::Meterpreter::Packet type=Request         tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=16 command=core_negotiate_tlv_encryption>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="42570622910394272501963662085320">
  #<Rex::Post::Meterpreter::Tlv type=RSA_PUB_KEY     meta=RAW        value="0\x82\x01\"0\r\x06\t*\x86H\x86\xF7\r\x01\x01\x01\ ...">
]>

RECV: #<Rex::Post::Meterpreter::Packet type=Response        tlvs=[
  #<Rex::Post::Meterpreter::Tlv type=UUID            meta=RAW        value="#\xFD\xD8C\x93\xAE\xCD\xF0\xA9\xBD\xA0\xBF\xCA\x8 ...">
  #<Rex::Post::Meterpreter::Tlv type=COMMAND_ID      meta=INT        value=16 command=core_negotiate_tlv_encryption>
  #<Rex::Post::Meterpreter::Tlv type=REQUEST_ID      meta=STRING     value="42570622910394272501963662085320">
  #<Rex::Post::Meterpreter::Tlv type=RESULT          meta=INT        value=0>
  #<Rex::Post::Meterpreter::Tlv type=SYM_KEY_TYPE    meta=INT        value=1>
  #<Rex::Post::Meterpreter::Tlv type=ENC_SYM_KEY     meta=RAW        value="\xAAk\xA2\x01\xE4\xD3}V7zZ\x10\x06\x98=\x9F\xC4H\ ...">
]>
```

This means plaintext strings won't appear in the network traffic that's been sent over the wire, as the data was placed into TLV packets, then encrypted with the negotiated aes encryption key

**Comment by HuskyHacks** [comment]
@adfoster-r7 precisely what I was looking for. Thank you!
