### ISSUE TITLE
post/windows/gather/enum_chrome: Operation Failed: Access is denied

### ISSUE THREAD

**Issue by Slavfucious** [rapid7/metasploit-framework#17126]
Steps to reproduce

How'd you do it?

by running post/windows/gather/enum_chrome on nt auth remote meterpreter

Were you following a specific guide/tutorial or reading documentation?
yes
If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.
https://null-byte.wonderhowto.com/how-to/hacking-windows-10-steal-decrypt-passwords-stored-chrome-firefox-remotely-0183600/

Expected behavior
get chrome dumps

What should happen?

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).
msf6 > version
Framework: 6.1.39-dev
Console  : 6.1.39-dev

RUNNING THE MODULE WITH METERPRETER 
![image](https://user-images.githubusercontent.com/113849805/194780202-5fdf054b-bbd2-4d56-9de0-4cd4d88d2475.png)
![image](https://user-images.githubusercontent.com/113849805/194780228-2ee96bba-1520-4ed6-a541-4f90c344d1a5.png)

**Comment by Reversing26** [comment]
I have same issue, I am running as explorer.exe, that's anomalous, maybe they update chrome security policy again to prevent password dumping?

**Comment by Slavfucious** [comment]
well, somehow i made it run no idea how, i get to the masterkey part, and i get line errors
