### ISSUE TITLE
msfconsole command will not work. 

### ISSUE THREAD

**Issue by dragonslayer771** [rapid7/metasploit-framework#17138]
the command msfconsole "is not found" even though i have metasploit-framework installed. Ive tried uninstalling metasploit-framework though theres "no formula with that name". Ive tried installing agian but "it already exists".  could anyone help?

**Comment by bcoles** [comment]
`msfconsole` is located in the Metasploit directory.

**Comment by dragonslayer771** [comment]
so what should i do? im very new to this.

**Comment by bcoles** [comment]
```
C:\Users\User>cd ..\..
C:\>cd metasploit-framework
C:\metasploit-framework>cd bin
C:\metasploit-framework\bin>msfconsole.bat
```

**Comment by gwillcox-r7** [comment]
I assume your using Brew to install given your output above. The installation script at https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/metasploit.rb suggests that `/opt/metasploit-framework/bin/` may be where some of the files are installed for the executables. I would recommend searching `/opt/metasploit-framework` for the `msfconsole` binary and seeing if you need to add the path where that is located to your PATH environment variable.

**Comment by gwillcox-r7** [comment]
No response or additional info given so closing out this issue due to lack of sufficient information to reproduce things.
