### ISSUE TITLE
Option to retry SSH login scanner when connection closed

### ISSUE THREAD

**Issue by ajmeese7** [rapid7/metasploit-framework#17178]
## Summary

One one of the HTB boxes I am currently working on, the remote host will sporadically refuse SSH connections. When that happens in the `scanner/ssh/ssh_login` module a few times, the process will die instead of retrying the username and password combination. I think an option to add the retry behavior would be beneficial for situations such as this.

**Comment by adfoster-r7** [comment]
Which HTB box?

**Comment by ajmeese7** [comment]
@adfoster-r7 it's the "Cult Meeting" box in the Hack the Boo 2022 CTF. Trying to SSH into the box runs a shell script that takes user input as opposed to a standard SSH login, which is why the connections are refused.

Brute forcing the login was obviously not the route to take, as that's rarely how HTB/CTF challenges work, but I still think that it's something that could be improved about the tool in general. I don't want to go into too much detail since the CTF is still live for another 4 days, but after it has ended I can add any more details that you think are relevant.

**Comment by adfoster-r7** [comment]
Looks like there's a hard coded 10 connection failures that can be raised before the module stops scanning:

https://github.com/rapid7/metasploit-framework/blob/8e9061c86d325a573a10ed06bf4810121cc7d702/lib/metasploit/framework/login_scanner/base.rb#L245-L251

Would it make sense to allow the connection failures count to be user defined?

**Comment by ajmeese7** [comment]
Good find, thanks!

In my opinion, there should be options to:

a. Set a specified number of failures
b. Set an unlimited number of failures
c. Make the failed connections retry with the same settings, instead of just breaking

**Comment by 3V3RYONE** [comment]
Hello, I'd like to work on implementing this suggestion feature. Is it up for grabs?

**Comment by ajmeese7** [comment]
@3V3RYONE as far as I'm aware it is, go for it! I'd love to do it myself if I had the time, but life has a way of getting busy.

**Comment by gwillcox-r7** [comment]
Completed with https://github.com/rapid7/metasploit-framework/pull/17727
