### ISSUE TITLE
SMB capture not working

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#17180]
![image](https://user-images.githubusercontent.com/101843356/197370074-5e918a29-98cb-4516-a01a-9ce2c710626c.png)
Despite I'm running msfconsole as Administrator I have permission denied

**Comment by cdelafuente-r7** [comment]
Since `SRVPORT` is 445 (below 1024), does the account used to run Metasploit have enough privileges?

**Comment by smcintyre-r7** [comment]
I'm highly confident that this is not a bug. You need to run metasploit with the privileges necessary to bind to the desired port. This is most easily done by running msfconsole with root using sudo, or you could do something fancier like reconfigure the kernel with `net.ipv4.ip_unprivileged_port_start=0` or `CAP_NET_BIND_SERVICE` on the Ruby binary.

The latter 2 options are really outside the support of what we offer in Metasploit though. Try running it with sudo or as root.
