### ISSUE TITLE
How to create unstaged payloads from staged?

### ISSUE THREAD

**Issue by fastchain** [rapid7/metasploit-framework#17199]
## Reason

Staged payloads can't handle reconnect properly: on reconnect server sends stages to client, that already staged. So sessions can not be reestablished after a network glitch.

## Summary
Is there any guide or description how to create unstaged payloads from staged?  It seems to be not a rocket sience, but since I can't find low-level tech description of payloads architecture, it's getting tough.  I would like to make unstaged version of  windows/x64/meterpreter/reverse_tcp_rc4

Thank you!

## Relevant information

Example of unstaged payload:

windows/x64/meterpreter_reverse_tcp

Example of staged payload:

windows/x64/meterpreter/reverse_tcp_rc4  (can't  handle reconnects)

**Comment by smcintyre-r7** [comment]
> Staged payloads can't handle reconnect properly: on reconnect server sends stages to client, that already staged. So sessions can not be reestablished after a network glitch.

Meterpreter payloads should be able to reconnect and reestablish their connection if the transports were configured correctly. If that's not the case then I think this is a regression.

**Comment by fastchain** [comment]
@smcintyre-r7  thank you for your comment, I'll try to reproduce once more. Also may be you know how to create unstaged payloads? Or  recommend direction for research?

**Comment by smcintyre-r7** [comment]
The payload that are named `meterpreter_` (as opposed to `meterpreter/`) are not staged. So if you want the unstaged version of `windows/meterpreter/reverse_tcp` you'd use `windows/meterpreter_reverse_tcp` etc.

Not all payloads have an unstaged equivalent, but Meterpreter's coverage is pretty good IIRC.

**Comment by fastchain** [comment]
@smcintyre-r7 thank you!
I would like to have unstaged reverse_tcp_rc4 . Is it possible somehow?
