### ISSUE TITLE
auxiliary/scanner/http/phpmyadmin_login : URI not friendly

### ISSUE THREAD

**Issue by RobinLanglois** [rapid7/metasploit-framework#17215]
## Steps to reproduce

1. `use auxiliary/scanner/http/phpmyadmin_login`
2. Fill the different options. If you're using `LAMP`, your path to phpadmin should be `localhost/phpmyadmin`, so you set `TARGETURI` to `/phpmyadmin`
3. You got the error message "PhpMyAdmin is not available"
4. After spending some time, you realize that you need to put a trailing `/` at the end of the URI, e.g `/phpmyadmin/`

Tested on Kali Linux VM

## Expected behavior

This should work without the trailing `/`, or be very clear on the documentation.

## Current behavior

It didn't work and I got an error message.

### Metasploit version

 v6.2.23

**Comment by adfoster-r7** [comment]
I think this would be hard to fix intuitively for the user; as in some scenarios `/custom_directory` may work without the need for a trailing `/`
