### ISSUE TITLE
i started a listener but its not opening sessions

### ISSUE THREAD

**Issue by nobiDebian** [rapid7/metasploit-framework#17224]
I manually embedded a payload into original apk and i also  use my router as a portforwading. but when im starting a listener it doesn't open any sessions, even if i open the payload app into my second device. Can you guys help me? Btw im using Kali Nethunter

**Comment by bcoles** [comment]
I suggest verifying your network configuration first. Ensure the port forwarding is working correctly. Try to connect to the listener from a remote host with netcat.

**Comment by gwillcox-r7** [comment]
Closing this due to lack of information to replicate.
