### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by Mikivirus1** [rapid7/metasploit-framework#17251]
It gives me :

D:/metasploit-frameworl/embedded/lib/ruby/3.0.0/open3.rb:221:in 'spawn' no such file or directory - git (Errno::Enoent)

I downloaded it on D drive as the installer always downloaded it on there, even when I chose C. 

I've already disabled my antivirus as well.

What could be the cause of the issue?

**Comment by bcoles** [comment]
Something is trying to run the `git` executable for some reason, but it can't find the `git` executable in the system path.

What were you trying to do?

**Comment by Mikivirus1** [comment]
I just ran the command "msfconsole" then it gave me this error

**Comment by bcoles** [comment]
Is there more to that stack trace?

**Comment by Mikivirus1** [comment]
Yes, it goes like this.

![IMG_20221111_104223.jpg](https://user-images.githubusercontent.com/117945731/201271650-b0d2ba54-6b1e-4945-a66b-ef32cd7fb700.jpg)
Please help me in any way you can.

**Comment by bcoles** [comment]
This looks like a bug. Metasploit should check if `git` is available.

> Please help me in any way you can.

The easiest approach is to ensure Git is installed and the `git` executable is in your system `PATH` environment variable.

Alternatively, you could patch the `modified_files` method in `lib/msf/ui/console/command_dispatcher/developer.rb`.

Alternatively, use Linux or Mac.

**Comment by Mikivirus1** [comment]
Would you recommend using virtual box for Linux?

**Comment by bcoles** [comment]
> Would you recommend using virtual box for Linux?

Either VirtualBox (free and open source) or VMware (free for non-commercial use).

**Comment by adfoster-r7** [comment]
Looks like a regression issue caused by https://github.com/rapid7/metasploit-framework/pull/17223

I would echo bcole's suggestion as well, but as a work around comment you can modify the `lib/msf/ui/console/command_dispatcher/developer.rb` file here:

https://github.com/rapid7/metasploit-framework/blob/bcf8c961282861b580581718ae8162821163fd22/lib/msf/ui/console/command_dispatcher/developer.rb#L22-L26

To instead be:

```ruby
  def initialize(driver)
    super
    @modified_files = []
  end
```

**Comment by adfoster-r7** [comment]
The fix should be available in the next release, or use one of the two workarounds above - i.e. modifying `lib/msf/ui/console/command_dispatcher/developer.rb` yourself - or using a Kali/Linux VM with Git available.
