### ISSUE TITLE
Presistence Android Payload (android versions above 10)

### ISSUE THREAD

**Issue by AR99X** [rapid7/metasploit-framework#17287]
Hi guys, 
**(1)** I cant make Android Payload keep working on background or make it (autostart),
I tried many methods to make the payload presistence but it always fail 
and this script not working anymore on androids above 10,0. (I'm testing on my phone android 11)

**(2)** How can i make the payload Display over apps, they call it (Draw over apps) because commands **Screenshot, Screenshare** not working when the app isn't interface.

**(3)** Webcam commands not working always **Operation Failed (1)** and when open the Camera from my phone the Payload stopped automatically.
**

```
> #!/bin/bash
> while :
> do am start –user 0 -a android.intent.action.MAIN -n com.metasploit.stage/.MainActivity
> sleep 20
> done
```

**

### **I would be grateful to anyone who tries to help me, thanks everyone**

**Comment by bcoles** [comment]
>  I cant make Android Payload keep working on background or make it (autostart),

https://github.com/rapid7/metasploit-framework/issues/16349#issuecomment-1068774955. See https://dontkillmyapp.com/ for more information.
