### ISSUE TITLE
apksigner not found. If it's not in your PATH, please add it.

### ISSUE THREAD

**Issue by johnmrh** [rapid7/metasploit-framework#17290]

**Comment by johnmrh** [comment]
it gives me                                                         [-] no platform was selected,choosing Msf::Module::platform:: android from payload and [-] no arch selected, selecting arch:dalvik from the payload and ERROR:apksigner not found.If its not in your path,please add it

**Comment by bcoles** [comment]
Install apksigner.

```
apt-get install apksigner
```
