### ISSUE TITLE
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload [-] No arch selected, selecting arch: dalvik from the payload No encoder specified, outputting raw payload Payload size: 10234 bytes Error: No such file or directory @ rb_sysopen - /root/storage/downloads/trojan.apk

### ISSUE THREAD

**Issue by mohamed1515i** [rapid7/metasploit-framework#17320]
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10234 bytes
Error: No such file or directory @ rb_sysopen - /root/storage/downloads/trojan.apk

**Comment by bcoles** [comment]
Error: No such file or directory @ rb_sysopen - /root/storage/downloads/trojan.apk

**Comment by gwillcox-r7** [comment]
Closing due to lack of use of the issue template and answer provided above.

**Comment by liubin-123** [comment]
Do you have a solution？

**Comment by bcoles** [comment]
> Do you have a solution？

This issue was closed many months ago.

The original issue was user error. The user attempted to access a file which did not exist. The solution is to specify a file which exists.
