### ISSUE TITLE
Why only android/meterpreter/reverse_https is slow and timing out ?

### ISSUE THREAD

**Issue by legilimency31** [rapid7/metasploit-framework#17328]
I am testing a connection between 2 android devices over the internet ( not Lan), and it works perfectly if i use `android/meterpreter/reverse_tcp`, but `android/meterpreter/reverse_https` is very slow and i got timeout very fast. Somtimes, just 1 sec after sent the first command.

Note: 

- i am using `ngrok tcp 444` to connect ( because i gave up trying to bypass my router firewall)
- metasploit is the latest version from github

So why that happens ? Is it because the ngrok connection is a tcp connection ? 
If i could bypass my router to use metasploit, i would prefer this way, but it seems impossible.

**Comment by timwr** [comment]
I wonder if this is android doze
Can you try
`meterpreter > activity_start 'intent:package:com.metasploit.stage#Intent;action=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS;end'`
Please?
