### ISSUE TITLE
Post #write_file Does Not Return Failure Indicator On Unix

### ISSUE THREAD

**Issue by smcintyre-r7** [rapid7/metasploit-framework#17365]
The [`#write_file`](https://github.com/rapid7/metasploit-framework/blob/c9aab1201c3a0b3cfc6dfc279b35228448bb0b52/lib/msf/core/post/file.rb#L498-L522) method provided by the post file mixin is documented as returning a boolean indicator. However when it forwards to `#_write_file_unix_shell` it returns true always regardless of whether or not the operation succeeded. Based on `#_write_file_meterpreter` I'm pretty sure the intention is to return `true` when the operation succeeds and false otherwise.

The `#write_file` method likely needs to be updated to propagate the return values of the functions it calls, like [`#append_file`](https://github.com/rapid7/metasploit-framework/blob/c9aab1201c3a0b3cfc6dfc279b35228448bb0b52/lib/msf/core/post/file.rb#L524-L547) does. Additionally, the methods that are called, including `#_write_file_unix_shell` (and possibly others like `_write_file_powershell`, `_win_ansi_write_file` and `_win_bin_write_file`) should be updated to return a boolean indicator for the result. For `#_write_file_unix_shell` specifically, a possible solution is likely to use a verification token and execute `&& echo #{verification_token}` with every command, then checking for the output.

This issue is manifesting itself as false positives when invoked from the Shell sessions, upload command:

```
msf6 payload(linux/x64/shell_reverse_tcp) > sessions -i -1
[*] Starting interaction with 1...

upload /etc/resolv.conf /etc/shadow

[!] The file </etc/shadow> already exists on the target machine

Overwrite the target file </etc/shadow>? [y/N]  y
[*] Max line length is 65537
[*] Writing 927 bytes in 1 chunks of 3481 bytes (octal-encoded), using printf
[+] File </etc/shadow> upload finished
```

In this case it failed because the current user doesn't have the permissions to write to `/etc/shadow`. The same success message is displayed if the file fails because the parent directories don't exist like this:

```
upload /etc/resolv.conf /this/path/does/not/exist/resolv.conf
[*] Max line length is 65537
[*] Writing 927 bytes in 1 chunks of 3481 bytes (octal-encoded), using printf
[+] File </this/path/does/not/exist/resolv.conf> upload finished
```

Once this bug is fixed, the status should be used by [`#cmd_upload`](https://github.com/rapid7/metasploit-framework/blob/c9aab1201c3a0b3cfc6dfc279b35228448bb0b52/lib/msf/base/sessions/command_shell.rb#L467).

**Comment by bcoles** [comment]
Seems `read_file`, `write_file` and `append_file` could do with some tests. These methods have improved incrementally over the past few years (#12603 #15897 #17172) but apparently still have issues.
