### ISSUE TITLE
problem with setting up the metasploit database correctly.

### ISSUE THREAD

**Issue by SKYR3X7000** [rapid7/metasploit-framework#17418]
after launching metasploit for the first time and using it i saw that the db was not usable after trying the "vulns" command. after verification on forums i can't find any solution. when i do "msfdb init" everything is set automatically and it tell me "Overridding user environment variable 'OPENSSL_CONF' to enable legacy functions." then when i do db_status it tells me that postgresql is selected but there is no connection. same after i try the "db start" command. help me

**Comment by gwillcox-r7** [comment]
There is a lack of information here. Specifically you haven't told us what OS you are using and what steps you have taken and their order, as well as what version of PostgreSQL you are trying to use for testing and the version of Metasploit that you are using. Please provide this information you we can better assist you.

You can run `db_connect` from within the console after you have started Metasploit to attempt to connect to a PostgreSQL database after Metasploit has started. Have you tried this, and if so, did you encounter any issues?

**Comment by SKYR3X7000** [comment]
i'm on kali linux, vmware version. i already tried that command with the user:pass that was in the database.yml file. after restarting postgresql and doing the db init, the db_status command tells me that it is connected to msf with postgresql. but when i try to use db_nmap it tells me that the database is not connected, and sometimes the scan works but it is when i try the vulns command that it tells me again that the database isn't connected.

**Comment by gwillcox-r7** [comment]
Going to need to see console output or pictures of the steps you have taken to root cause this further. Unfortunately its not possible to reproduce the issue given the information you have sent over so far. The database is notoriously a fiddly bit of software to debug when it goes awry so this is why I really need to see this level of detail in order to determine what is potentially missing.

**Comment by gwillcox-r7** [comment]
Closing issue due to lack of info provided. If more information is provided I can reopen this issue.
