### ISSUE TITLE
scanner/smb/smb_enumshares truncates file names

### ISSUE THREAD

**Issue by AlanFoster** [rapid7/metasploit-framework#17436]
## Steps to reproduce

When running the `modules/auxiliary/scanner/smb/smb_enumshares.rb` module, large file names are truncated automatically 

```
msf6 auxiliary(scanner/smb/smb_enumshares) > run smbuser=foo smbpass=bar smbdomain=baz rhost=x.x.x.x spidershares=true showfiles=true 
... etc ...
 FILE  NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  524288
 FILE  NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  2018-02-07T22:05:26-05:00  524288
... etc ...
[+] x.x.x.x:445       - info saved in: /home/kali/.msf4/loot/20230104205414_default_x.x.x.x_smb.enumshares_897937.txt
```

It's not possible to view the full file name, as it's truncated even before being placed into the generated csv file:

```
$ cat /home/kali/.msf4/loot/20230104205414_default_x.x.x.x_smb.enumshares_897937.txt

... etc ...
x.x.x.x\Users\etc\NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...
x.x.x.x\Users\etc\NTUSER.DAT{a0d1b9b4-af87-11e6-9658-...
... etc ...
```

The stored file name should not be truncated when being saved to disk, potentially at all

The bug is here:
https://github.com/rapid7/metasploit-framework/blob/9d866a378481ff276b48cff0118df3b60d6ed87f/modules/auxiliary/scanner/smb/smb_enumshares.rb#L258-L259

## Expected behavior

No truncation in the written file

## Current behavior

Truncation

### Metasploit version

```
msf6 auxiliary(scanner/smb/smb_enumshares) > version
Framework: 6.2.33-dev-e9f86ce6e8
Console  : 6.2.33-dev-e9f86ce6e8
```

**Comment by prabhatjoshi321** [comment]
Hi, may I take on this bug?

**Comment by gwillcox-r7** [comment]
@prabhatjoshi321 Go for it, I'll assign you to this ticket so long 👍

**Comment by prabhatjoshi321** [comment]
Thanks
