### ISSUE TITLE
metasploit bind:failed

### ISSUE THREAD

**Issue by slayerhacker** [rapid7/metasploit-framework#17469]
im having this error please anyone help me to get solve this error
![Screenshot from 2023-01-13 07-10-50](https://user-images.githubusercontent.com/122613947/212321870-d508d510-3cc2-4f7e-bf87-44918f17223f.png)

**Comment by bcoles** [comment]
Is something already listening on port 8080?

```
lsof -i :8080
```

**Comment by slayerhacker** [comment]
i don't know what service is running in the port 8080, if the port is
already listening something ,how could i stop the service ,kindly help me
to solve this

**Comment by prabhatjoshi321** [comment]
You can use `ss` to check for the services listening on ports
`sudo ss -tulpan`
after that you can use fuser tool to kill the process that is using that port
`sudo fuser -k <port>/<protocol>`
Eg.: 
`fuser -k 8080/tcp`
Be careful as this will kill the process running on that port

**Comment by slayerhacker** [comment]
ohh thank you so much for your reply and help,i'll definitely try to solve
this ,incase any issues again ,i'll mail u as soon as possible
             THANK YOU...!

**Comment by slayerhacker** [comment]
i cleared the before error bind failed, i overcomed but then i updated
metasploitable then i run same commands i face this type of error,please
help me to get out of this
