### ISSUE TITLE
Error while install on ubuntu 22.04

### ISSUE THREAD

**Issue by MR-MKZ** [rapid7/metasploit-framework#17478]
Hello thanks for this very good tool but after running msfinstall it says apt install metasploit -> metasploit not found
How can i fix it?

**Comment by adfoster-r7** [comment]
There's installation steps here - https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html

I would recommend installing Kali in a virtual machine to get started with metasploit - https://www.kali.org/get-kali/
