### ISSUE TITLE
about Empire

### ISSUE THREAD

**Issue by slayerhacker** [rapid7/metasploit-framework#17508]
i installed Empire in my kali ,it successfully installed but it will not run as i expected please help me to solve this..!  
![Screenshot from 2023-01-19 13-39-20](https://user-images.githubusercontent.com/122613947/213533469-1934775a-966d-4349-a7cd-ca3a982aa4a3.png)
THANK YOU

**Comment by h00die** [comment]
Have you ever gotten food at one restaurant, then traveled to a different restaurant and asked what the recipe was for the food you brought in and to cook that food a little longer, and give you a side of condiments?

This git is for metasploit, not empire.  If you want empire or kali help you'll need to go https://github.com/EmpireProject/Empire / https://github.com/BC-SECURITY/Empire or https://www.kali.org/community/
