### ISSUE TITLE
Windows installer incorrectly installs on D: drive instead of default/specified C: drive

### ISSUE THREAD

**Issue by AlexHimself** [rapid7/metasploit-framework#17555]
## Steps to reproduce

How'd you do it?

1. Use a fully updated Windows 10 computer that has both a `C:` (primary) drive and a `D:` (secondary, storage) drive, and uses Windows Defender for AntiVirus.
2. Make NO changes to Windows Defender and attempt to install with defaults, confirming `C:\` drive is default.
3. Various Defender security errors appear. Add exception for `C:\metasploit-framework`.
4. Uninstall/reinstall, confirming `C:\` drive is specified location.
5. More defender errors. Verify no contents in `C:\metasploit-framework`. Inspect `D:\` drive and see file/folders were created there, despite location being specified as `C:\` drive.

Alternatively:

1. Use a fully updated Windows 10 computer that has both a `C:` (primary) drive and a `D:` (secondary, storage) drive, and uses Windows Defender for AntiVirus.
2. Install using defaults, confirming `C:\` drive is selected
3. Files are installed to `D:\` drive.

![image](https://user-images.githubusercontent.com/10466466/214945548-fe28fdb2-9f02-4fa1-a589-7044b3345d69.png)

![image](https://user-images.githubusercontent.com/10466466/214945633-557395b7-4915-45ac-b561-e72bf1bafa46.png)

## Expected behavior

Metasploit should install in specified location, not `D:\` drive randomly.

## Current behavior

Metasploit installs in wrong location.

### Metasploit version

Framework: 6.2.37-dev-8368accd5592392a6d8449490f222f4b269e3a3c
Console  : 6.2.37-dev-8368accd5592392a6d8449490f222f4b269e3a3c

**Comment by gwillcox-r7** [comment]
This is probably more of an issue to raise within https://github.com/rapid7/metasploit-omnibus, as it is specific to that installer vs an issue with Metasploit Framework itself. Would you mind raising the issue over there instead? We'd need to try replicating this and I'm fairly sure this is an issue, just want to make sure we are tracking it in the right place so the right people can see it.

**Comment by AlexHimself** [comment]
I just now found https://github.com/rapid7/metasploit-omnibus/issues/144 , but it's lacking details. Should I submit a new issue or what's the best way to send it?

**Comment by AlexHimself** [comment]
Closed and commented on this issue https://github.com/rapid7/metasploit-omnibus/issues/144
