### ISSUE TITLE
Unable to run Metasploit Framework on Kali Linux After reinstallation

### ISSUE THREAD

**Issue by titancomputinglegend** [rapid7/metasploit-framework#17552]
I tried to uninstall and reinstall msfconsole in linux and I got ended up with:

_> Could not find pcaprub-0.13.1, ruby-oci8-2.2.12 in any of the sources
> Run `bundle install` to install missing gems._

I tried to:

_

> cd /usr/share/metasploit-framework
> sudo bundle install

_

But yet still the same issue.

**Comment by gwillcox-r7** [comment]
https://stackoverflow.com/questions/11885398/is-there-a-fix-for-the-could-not-find-gem-in-any-of-the-sources-error-that-d

**Comment by titancomputinglegend** [comment]
> https://stackoverflow.com/questions/11885398/is-there-a-fix-for-the-could-not-find-gem-in-any-of-the-sources-error-that-d

Nothing helped me here :-(

**Comment by gwillcox-r7** [comment]
Are you using Ruby Version manager such as RVM or rbenv?

Also you shouldn't be running `sudo bundle install` but rather `bundle install`. If you run `bundle` with `sudo` or `root` permissions there is a good chance you'll end up creating two separate installation states on your system which will cause you to run into issues like this one.
