### ISSUE TITLE
Android 14 to block old API versions

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#17620]
https://gizmodo.com/android-14-6-block-old-apps-play-store-sideloading-pixe-1850025518

Just heard about this, sounds like it'll roll out blocking up to version 6, then later up that to 12.  Not sure how our payload stuff for android is, but may be something that needs to be looked into. @timwr

**Comment by bcoles** [comment]
From that article:

> It looks like device makers will be able to make the block more lenient (by allowing apps aimed at some older versions but not others) or disable it entirely, but the base install you’ll get on Pixel devices will have it fully enabled.

Ideally we will continue to support old apps so long as the maintenance burden for doing so is not unreasonably high.

On a related note, msevenom uses `apktool` which will likely also have similar issues due to dropping support for AAPT1. (#17694)

**Comment by Akhilesh9148** [comment]
I want to work on this issues please assign me this issue

**Comment by h00die** [comment]
moving to rollup
