### ISSUE TITLE
Fix Broken Logic for 64 bit Systems when using enum_ad_users.rb

### ISSUE THREAD

**Issue by gwillcox-r7** [rapid7/metasploit-framework#17629]
Whilst trying to fix the Railgun definitions in https://github.com/rapid7/metasploit-framework/pull/17562, we have been trying to use `post/windows/gather/enum_ad_users.rb` to do our testing. However we have honestly run into so many issues that are not Railgun specific with that module we thought it was about time we put them into a separate ticket since this module needs a good bit of reworking at the moment to work on anything outside of a limited set of payloads and host types.

Note that all testing requires one to use a payload type where extapi extension is not loaded, such as a Python Meterpreter payload, as otherwise the RailGun backend will not be used and some of these issues won't be hit.

Also in case you wondering why we just don't use the Net::LDAP library, which is something I raised as a concern, apparently we want to still support authenticating as the current user so we are using https://learn.microsoft.com/en-us/windows/win32/api/winldap/nf-winldap-ldap_bind_sa with `LDAP_AUTH_NEGOTIATE` which allows us to do this: `To log in as the current user, set the dn and cred parameters to NULL.`.

Here are some of the issues that were encountered:
1. https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/windows/ldap.rb#L267 is trying to read what appears to be a https://learn.microsoft.com/en-us/windows/win32/api/winldap/ns-winldap-ldapmessage structure however it fails to account for the fact that some elements may be 64 bit pointers, so this will fail on x64 systems.
2. We appear to be doing some operations on https://learn.microsoft.com/en-us/windows/win32/api/winldap/ns-winldap-berelement however the MSDN documentation lists this structure as being opaque. Despite this, we appear to be trying to play around with this at https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/windows/ldap.rb#L279-L286 for reasons unknown.
3. The logic at https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/windows/ldap.rb#L282 is working on architectures incorrectly. If we use a Python session the arch will be ARCH_PYTHON which won't match things. We should be using the `native_arch` attribute like https://github.com/rapid7/metasploit-framework/blob/e26ab2c202fe6bc6b90e383bee6e20233966c6e5/lib/rex/post/meterpreter/extensions/stdapi/railgun/multicall.rb#L77 does. 
4. Currently https://github.com/rapid7/metasploit-framework/blob/86fc6172591616dccedbe9bb4c8abbcc27fdcd4f/lib/msf/core/post/windows/ldap.rb#L130 is broken when called from a 64 bit Meterpreter session without the `extapi` extension loaded.
 

## Steps to reproduce

How'd you do it?

1. Get a session on a x64 system with a Python Meterpreter shell.
2. Try run the `post/windows/gather/enum_ad_users` module, set the `DOMAIN` value to your domain, and the `SESSION` to your Python session.
3. You should encounter some of the issues noted above. Note that you may need a debugging session to force some of the code paths so you can test edge cases and see that some of the logic might not be working.

## Were you following a specific guide/tutorial or reading documentation?

Found whilst doing testing for https://github.com/rapid7/metasploit-framework/pull/17562

## Expected behavior

The `enum_ad_users.rb` module should work on x64 systems even if the `extapi` extension is not loaded.

## Current behavior

It will fail in a variety of fashions listed above, plus potentially extra we haven't encountered yet.

### Metasploit version

6.3.1-dev-e26ab2c202

**Comment by gwillcox-r7** [comment]
Some info for how to fix point 1:

```
V - ULONG lm_msgid
V - ULONG lm_msgtype
V - PVOID lm_ber (should be 64 bit compatible here, error!)
V - struct ldapmg * lm_chain (should be 64 bit compatible here, error!)
V - struct ldapmsg * lm_next (should be 64 bit compatible here, error!)
V - ULONG lm_time
V - PLDAP Connection (should be 64 bit compatible here, error!)
V - PVOID Request (should be 64 bit compatible here, error!)
V - ULONG lm_returncode
v - USHORT lm_referral
C - BOOLEAN lm_chased
C - BOOLEAN lm_eom
C - BOOLEAN ConnectionRefused
```

**Comment by JosigaS** [comment]
I would like to contribute to this issue. Kindly assign me to this issue

**Comment by gwillcox-r7** [comment]
Hi @JosigaS feel free to work on this, assignment is mostly used for internal tracking. When you have put up the PR to fix one of these issues I'd be happy to assign you as appropriate. Additionally this issue is likely going to need multiple PRs to fix so not sure that assigning someone makes sense here vs making the multiple PRs and then backlinking here to say "person X is working on fixing issue Y".

**Comment by gwillcox-r7** [comment]
@JosigaS Also for context we specifically didn't label this as `easy` or `newbie-friendly` since there is a lot of nuance to these particular issues. Your still welcome to give them a shot if your curious and use the guide at https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html to set up a development environment though if your interested, just wanted to make you aware of what is involved here.

Alternatively you could also look at our list of beginner friendly issues over at https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+is%3Aopen+label%3Aeasy or https://github.com/rapid7/metasploit-framework/issues?q=is%3Aissue+is%3Aopen+label%3Anewbie-friendly to find some good candidates to begin working on developing Metasploit Framework.

**Comment by smcintyre-r7** [comment]
I've got a solution for this pretty much done, just waiting for #17562 to be landed first.
