### ISSUE TITLE
Metasploit in iSH

### ISSUE THREAD

**Issue by HKTangyuan** [rapid7/metasploit-framework#17659]
I tried to run metasploit on the iSH_app of the iPad, but I found that some problems with iSH would get stuck during the startup of msfconsole. Is there any way to solve this problem? Thank you
https://user-images.githubusercontent.com/109419998/219646882-49a9ede1-93e5-4d27-9dc1-f6c2842fb201.MOV

**Comment by gwillcox-r7** [comment]
@HKTangyuan Metasploit is not presently supported to be run as a host on mobile devices. Whilst we do provide payloads for mobile devices the act of running `msfconsole` and the attacker portions of the platform on a mobile device is not supported.
