### ISSUE TITLE
If someone is new and he wants to know all about it so how should be he guided?

### ISSUE THREAD

**Issue by FAHEEM405** [rapid7/metasploit-framework#17752]

**Comment by bcoles** [comment]
* https://docs.rapid7.com/metasploit/getting-started/
* https://www.offsec.com/category/metasploit-unleashed-training/
* https://github.com/rapid7/metasploit-framework/tree/master/documentation

**Comment by gwillcox-r7** [comment]
Marking as resolved, above information should be sufficient to get started. I'd also add that looking over the code with Sourcegraph from https://sourcegraph.com/search can also help with navigating between the multiple code bases that Metasploit uses. Can find some tutorials on this product at https://docs.sourcegraph.com/tutorials
