### ISSUE TITLE
Infinite - Starting the MetasPloit Framework console.../

### ISSUE THREAD

**Issue by Frintezza1337** [rapid7/metasploit-framework#17768]
Hello! when I'm connected to vpn When I start msfconsole, metasploit doesn't start if I disable vpn, it starts up in +- 10 seconds, what is the reason for this? how can i fix it? infinite -- Starting the MetasPloit Framework console.../

6.1.0-kali5-amd64
Framework Version: 6.3.5-dev-

**Comment by adfoster-r7** [comment]
You can install `strace` and use `strace msfconsole` to see what system calls are being made when msfconsole boots up. That might give more insight into what's happening.

If it loads successfully you should see the msfconsole prompt write and read:

```
write(1, "\33[4mmsf6\33[0m \33[0m> ", 19msf6 > ) = 19 <-- Printing the msfconsole prompt
read(0,  <-- Waiting for user input
```

If after 20 seconds it's stuck on something else, or you notice a pattern of retrying network requests, we should be able to take a closer look

**Comment by Frintezza1337** [comment]
I see repetitive 

`openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/reline-0.3.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/io-console-0.6.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/io-console-0.6.0/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/daemons-1.4.1/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/cookiejar-0.3.3/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/coderay-1.1.3/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/byebug-11.1.3/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bson-4.15.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bson-4.15.0/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bindata-2.4.15/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bcrypt_pbkdf-1.1.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bcrypt_pbkdf-1.1.0/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bcrypt-3.1.18/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/bcrypt-3.1.18/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-s3-1.119.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-kms-1.62.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-iam-1.75.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-ec2-1.364.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sdk-core-3.170.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/jmespath-1.6.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-sigv4-1.5.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-partitions-1.707.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/aws-eventstream-1.2.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/ast-2.4.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/arel-helpers-2.14.0/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/afm-0.2.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/addressable-2.8.1/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/public_suffix-5.0.1/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=35591, ...}) = 0
close(6)                                = 0
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/reflection.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 6
fcntl(6, F_SETFL, O_RDONLY)             = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=35591, ...}) = 0
ioctl(6, TCGETS, 0x7ffd1185e020)        = -1 ENOTTY (Inappropriate ioctl for device)
read(6, "# frozen_string_literal: true\n\nr"..., 8192) = 8192
read(6, "backs run, and they find a belon"..., 8192) = 8192
read(6, "cord_primary_key\n      end\n\n    "..., 8192) = 8192
read(6, "n_key\n      end\n\n      def join_"..., 8192) = 8192
read(6, "f scope\n        scope_chain\n    "..., 8192) = 2823
read(6, "", 8192)                       = 0
close(6)                                = 0
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/framework/lib/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/framework/app/models/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/framework/app/concerns/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/framework/app/validators/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/metasploit-credential-6.0.2/app/concerns/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/metasploit-concern-5.0.1/lib/active_record/serialization.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/metasp`

and something like this

`fstat(6, {st_mode=S_IFREG|0644, st_size=1545, ...}) = 0
close(6)                                = 0
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
openat(AT_FDCWD, "/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/activerecord-7.0.4.2/lib/active_record/no_touching.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 6
fcntl(6, F_SETFL, O_RDONLY)             = 0
fstat(6, {st_mode=S_IFREG|0644, st_size=1545, ...}) = 0
ioctl(6, TCGETS, 0x7ffd1185e020)        = -1 ENOTTY (Inappropriate ioctl for device)
read(6, "# frozen_string_literal: true\n\nm"..., 8192) = 1545
read(6, "", 8192)                       = 0
close(6)                                = 0
`

**Comment by adfoster-r7** [comment]
That output is all fine; you can see it's just loading files from your filesystem

**Comment by bcoles** [comment]
> I recreated the database and reconnected and everything seems to be working, how can this be related to this, please tell me? If you know

As a complete guess, if the database was not initialized a different code path would be called to initialize it. The initialization may require a TTY (prompts for user input during init?), and your shell and/or environment variables did not have have a compatible TTY setup for some reason, resulting in `ENOTTY` error.

Perhaps you were running Metasploit in a shell using `sudo` or `su`?

**Comment by Frintezza1337** [comment]
postgres was running and yes I ran metasploit from sudo
