### ISSUE TITLE
Commits to login_scanner are breaking SSH private key module

### ISSUE THREAD

**Issue by mdevegas** [rapid7/metasploit-framework#17762]
## Steps to reproduce
Use the ssh_pubkey_login module on current release

1. I configured and used the module

It appears that while the updating of the ssh_login module has been maintained, the other SSH modules are broken as a result of this commit:

https://github.com/rapid7/metasploit-framework/commit/599642bbb9ad1933c026143081e580fd320263e4

## Were you following a specific guide/tutorial or reading documentation?

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.

## Expected behavior

SSH spraying using private keys

## Current behavior

MetaSploit dies due to ```Metasploit::Framework::LoginScanner::Invalid Max consecutive error count can't be blank, Max consecutive error count is not a number (Metasploit::Framework::LoginScanner::SSH)```

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

## Additional Information
If your version is less than `5.0.96`, please update to the latest version and ensure your issue is still present.

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

1. Start `msfconsole`
2. Run the command `set loglevel 3`
3. Take the steps necessary recreate your issue
4. Run the `debug` command
5. Copy all the output below the `===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===` line and make sure to **REMOVE ANY SENSITIVE INFORMATION.**
6. Replace these instructions and the paragraph above with the output from step 5.

**Comment by rohitkumarankam** [comment]
`Metasploit::Framework::LoginScanner::Invalid Max consecutive error count can't be blank, Max consecutive error count is not a number, Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)` this error only occurs when specified directory or file in `KEY_PATH` is not readable by Metasploit.
