### ISSUE TITLE
Sign macOS pkg

### ISSUE THREAD

**Issue by razvanazamfirei** [rapid7/metasploit-framework#17772]
## Summary

Sign macOS application

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

macOS on ARM requires applications to be signed. Unsigned applications create difficulties in keeping it up-to-date in homebrew casks.
 
Homebrew/homebrew-cask/pull/142981

**Comment by gwillcox-r7** [comment]
@razvanazamfirei If this is specifically for the nightly installers for Metasploit Framework, aka the Omnibus installers, you should ask this over at https://github.com/rapid7/metasploit-omnibus where your question can be better served. This repository is not in charge of installers for Metasploit in any regard and therefore we cannot help you with such matters here. 

If this is for Metasploit Pro, please raise an issue with your designated contact. https://github.com/rapid7/metasploit-omnibus may be able to help you in this case but its not guaranteed.
