### ISSUE TITLE
Drop support for Ruby 2.7

### ISSUE THREAD

**Issue by tekwizz123-mobile** [rapid7/metasploit-framework#17811]
## Summary

Ruby 2.7 is expected to EOL at the of this month. We currently support most releases of Ruby 3 so we should probably drop support for Ruby 2.7 as part of our policy on EOL software.

## Relevant information

https://www.ruby-lang.org/en/downloads/branches/

**Comment by tekwizz123-mobile** [comment]
Note left this as a question since this may involve a discussion on the best timing for this, however feel free to update as relevant.

**Comment by adfoster-r7** [comment]
I think we'll remove Ruby 2.7 when it's technical overhead to continue to support it rather than pre-emptively marking ourselves as incompatible. Will close this for now :+1:

**Comment by tekwizz123-mobile** [comment]
> I think we'll remove Ruby 2.7 when it's technical overhead to continue to support it rather than pre-emptively marking ourselves as incompatible. Will close this for now :+1:

My understanding was we have a few things waiting on 2.7 support to end before we can do some reworks of the code base but I'm happy to leave this as is for now if the technical overhead is too high; just wanted to open this as a reminder and to encourage discussion.
