### ISSUE TITLE
I hope there is information about "check supported" in the rpc info return value.

### ISSUE THREAD

**Issue by Ryuuuuu** [rapid7/metasploit-framework#17829]
## Summary

I hope there is information about check supported in the rpc info return value.

### Basic example

msfconsole supports info that cotains "check supported" information.
![image](https://user-images.githubusercontent.com/33323678/228157022-816267c5-fb49-4ae6-84f7-c979890696c7.png)

but in msfrpc i can't find the information of "Check supported."

### Motivation

If the check support function works in rpc, it will be of great help to people who automate using metasploit rpc.

**Comment by adfoster-r7** [comment]
Would adding this metadata to the `module.info` rpc command be suitable for your requirements?
https://github.com/rapid7/metasploit-framework/pull/17833
