### ISSUE TITLE
v6.3.14 PG::Coder.new(hash) is deprecated

### ISSUE THREAD

**Issue by teemuhak** [rapid7/metasploit-framework#17957]
## Steps to reproduce

How'd you do it?

1. Starting or exiting Metasploit in Linux after updating to version 6.3.14 (ruby version 3.1.2p20)
2. Error message when starting or exiting Metasploit:
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980:in `new'

## Current behavior

Error message when starting and exiting Metasploit when the PostgreSQL database is running, it seems that Metasploit is working normally.

### Metasploit version

6.3.14-dev

**Comment by adfoster-r7** [comment]
Thanks for raising an issue; Looks like this issue will be fixed by ActiveRecord, a library we depend on - https://github.com/rails/rails/pull/48048

The error can be ignored for now and shouldn't cause any issues.

**Comment by adfoster-r7** [comment]
This will be fixed in the next release - 6.3.22
