### ISSUE TITLE
Meterpreter ZIP UNZIP command

### ISSUE THREAD

**Issue by MrHax0rUI** [rapid7/metasploit-framework#17971]
Hello,
How to zip or unzip folder/file in meterpreter?

**Comment by bcoles** [comment]
Meterpreter does not have a command to zip/unzip files/directories. You will need to use native `zip` / `unzip` commands on the host or `download` the files then unzip them.

**Comment by MrHax0rUI** [comment]
> 

Oh okay..thanks..
I think it would be more perfect if meterpreter can do zip and unzip
