### ISSUE TITLE
auxiliary/gather/get_user_spns does not output a breakable encryption format of Kerberos AS-REP message

### ISSUE THREAD

**Issue by dadoyan** [rapid7/metasploit-framework#17988]
## Steps to reproduce
Nothing special, just use auxiliary/gather/get_user_spns to perform ASREPRosting attack to break the password of a user with preauthentication disabled. 

The encrypted AS_REP using as a key the nt hash should be breakable. The attack is working in the same setup lab with impacket GetNPUsers.py but not with metasploit module.

Possible cause --> Different formats for hashcat

metasploit output has number 18 in the encryption ($krb5asrep$18): 

> [+] 10.20.30.229 - User: "asrep" does not require preauthentication. Hash: $krb5asrep$ 18$asrep@MARVEL.LOCAL:e55958ef14ffeeac15e685cf45fd0055$16acdacee9300127b8de96b31908291189bae698343a839fa47830a8721ec90bfeb1aeab02fda8f6fd63aa8d19fd15fdc1ccd0507ce53b08d9e33888552bca764ab2f3437ca8c17312f3db3717c5d0f72fb7a74247347e0eae944ba0179ece4520c46a3e1929d141c3b27837afb7e64f07b16f7785ab39f92356cd839f2c018cbdfe96644500b1b0d8507ffeb42f511a9f0e09523f4acaddc54a3e7dc8e07522a74275eb319543af2d3e810a730595a4eead49ff0e1f5ce38cf6002b14c944d61f15366b1da9181df7b2ac18c546ab0185b3b58ed0262739539df99ec67a041391315cbb3c85a4667142305f16ca8417996cac620034bfb2318468ddbe87dc  

Impacket GetNPUsers output has number 23 in the encryption ($krb5asrep$23) and has more bytes: 
> $krb5asrep$ 23$asrep@MARVEL.LOCAL:25467ccad28d361022ffb544bec42898$338e5d814ed500db12a57fbabdfdb78d937c9264beb0429755f9b8e88b4602d4415c99fac9ad635617ff299d0fe3966a2dd6405918a550cc153ccd724202cca266eddf89dee1763c4482630da9cf623f49c79783d48499203ce1fd61adc001f18de6fdc08bfbecf810fb49a95a2daf16851ed6adb192b774378ecfe605338fb74e732e470a6187913aaa30fc810f6a49461c907961060a9ef7bb5941d92cec899621d55fe8aabe433c67dc493dfdb0af9f47a5f3c9a1d5e9f2e9ce5b7627dd15f04ad9f00102a89cfb491b609b2bdfedaea9ee6c6d8a9bb36654bf47bc619285ed5140f4b698adb29551a1e3

## Were you following a specific guide/tutorial or reading documentation?
Based on the metasploit documentation

https://docs.metasploit.com/docs/pentesting/active-directory/kerberos/kerberos_login.html

## Expected behavior
Hashcat should be able to break the key as it is in my dictionary (Nt password pash).

## Current behavior
Hashcat cannot break the key (Nt password pash).

### Metasploit version
Framework Version: 6.3.4-dev

**Comment by smashery** [comment]
I'm having a look at this one. I think there was maybe a small mixup (or maybe a behaviour change since this issue was created): the AS-REP-roasting behaviour described above is in the `kerberos_login` module, not the `get_user_spns` module (which is TGS-REP-roasting). Just to be sure, I checked the latter, and couldn't find any issues, whereas the ASREP-roasting functionality in `kerberos_login` has exactly the problem described - so I'm going to proceed with fixing that issue.
