### ISSUE TITLE
payload APK won't download on Android

### ISSUE THREAD

**Issue by tommyblue91** [rapid7/metasploit-framework#18045]
Hello,
I'm new here, 

I keep running into an issue, I hope this community can help me with...
I've succesfully created an APK using msfvenom and I can find the create APK when i -ls
<img width="303" alt="Screenshot 2023-05-31 at 02 51 58" src="https://github.com/rapid7/metasploit-framework/assets/39204875/e0c824c4-2fc8-441c-87d5-ef9d399e9c52">

but when i go to my phone (Samsung Galaxy 21) and I open chrome browser, and enter the IP address and APK extension, the phone simply doesnt want to load the page or download the APK.

Apk should be found at:  192.168.141.128/omg.apk

my phone just gets stuck loading the page...

what am I doing wrong here?
![WhatsApp Image 2023-05-31 at 02 49 11](https://github.com/rapid7/metasploit-framework/assets/39204875/62f89090-8d13-4433-aab6-bf3d00b9ff06)

**Comment by mod94** [comment]
> Hello, I'm new here,
> 
> I keep running into an issue, I hope this community can help me with... I've succesfully created an APK using msfvenom and I can find the create APK when i -ls <img alt="Screenshot 2023-05-31 at 02 51 58" width="303" src="https://user-images.githubusercontent.com/39204875/242130892-e0c824c4-2fc8-441c-87d5-ef9d399e9c52.png">
> 
> but when i go to my phone (Samsung Galaxy 21) and I open chrome browser, and enter the IP address and APK extension, the phone simply doesnt want to load the page or download the APK.
> 
> Apk should be found at: 192.168.141.128/omg.apk
> 
> my phone just gets stuck loading the page...
> 
> what am I doing wrong here? ![WhatsApp Image 2023-05-31 at 02 49 11](https://user-images.githubusercontent.com/39204875/242130643-62f89090-8d13-4433-aab6-bf3d00b9ff06.jpeg)
run in the directory with your apk 
python -m http.server 8000
Check your browser at http://your_ip:9000

**Comment by bcoles** [comment]
> what am I doing wrong here? 

Check your network routes.

If you phone is not on the same subnet it will not be able to connect to the web server.

If you're running Metasploit in a virtual machine, your phone won't be able to connect unless the network adapter is bridged.
