### ISSUE TITLE
RPI4B 8GB: always stuck on `Clearing http web data service credentials in msfconsole`

### ISSUE THREAD

**Issue by tkbstudios** [rapid7/metasploit-framework#18155]
## Steps to reproduce

How'd you do it?

1. install metasploit using the command from the docs:
```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```  
2. run any metasploit command (`msfdb init`, `msfconsole`)  

Install: [Install docs](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html)  

I was following [metasploit basics docs](https://docs.metasploit.com/docs/using-metasploit/basics/)  

## Expected behavior

Open metasploit meterpreter and show welcome message with ability to execute payloads after.  

## Current behavior

`Clearing http web data service credentials in msfconsole`. 
I tried and let it for 4 hours running and didn't change anything.  

### Metasploit version

Unable to execute due to all metasploit commands not working.  
Clean install: yesterday 06-01-2023

## Additional Information
I installed it on a raspberry pi 4 Model B 8GB with a gigabit connection and NVM.e boot drive. (Running docker containers)

I tried on a VPS hosted at Linode (Ubuntu 22.04 LTS Pro) and it worked flawlessly

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

Unable to execute debug log inside msfconsole.

**Comment by dwelch-r7** [comment]
I wasn't able to replicate this issue
![image](https://github.com/rapid7/metasploit-framework/assets/19910435/7f50fcdb-a5ec-457b-9779-96bf28c7b854)
![image](https://github.com/rapid7/metasploit-framework/assets/19910435/9d56788d-d9d3-40a8-a5f9-7d12a0b737d5)

Both `msfconsole` and `msfdb init` worked for me on a fresh raspbian install on my raspberry pi 4 

Can you think of any further steps I should try to replicate this? When it asked me >Would you like to use and setup a new database (recommended)?
I declined but maybe if at that stage you responded 'Yes' then it's that workflow that's the problem?

**Comment by tkbstudios** [comment]
I use Ubuntu Server 22.04 LTS Pro

**Comment by tokalek** [comment]
and i have this problem too,
![Снимок экрана от 2023-07-13 08-16-55](https://github.com/rapid7/metasploit-framework/assets/25418389/dfb28f83-b332-437d-9c66-951b807b0a8b)

**Comment by st4rry** [comment]
rm -rf  /home/<youruser>/.msf4/
sudo systemctl restart postgresql 
sudo systemctl status postgresql

then...

msfdb init -d
