### ISSUE TITLE
Junk link in README

### ISSUE THREAD

**Issue by cold-nagai** [rapid7/metasploit-framework#18183]
https://resources.metasploit.com/ from README seems to be useless. Consider removing it.
![image](https://github.com/rapid7/metasploit-framework/assets/126972909/a9b6a4f0-3063-4839-b3c9-5dcb5f195d0d)

**Comment by adfoster-r7** [comment]
Thanks for the suggestion; We'd accept a PR to remove the link from the documentation :+1:

And on our side we will have to investigate redirecting that link to somewhere more useful

**Comment by bcoles** [comment]
> Thanks for the suggestion; We'd accept a PR to remove the link from the documentation 👍

The link is self-referencing. The README is in the [metasploit.github.io repo](https://github.com/metasploit/metasploit.github.io). `resources.metasploit.com` is `metasploit.github.io`.

```
$ dig +short cname resources.metasploit.com
metasploit.github.io.
```


> And on our side we will have to investigate redirecting that link to somewhere more useful

As far as I'm aware, GitHub pages does not support 302 redirects for the entire subdomain; however, redirects can be achieved with `<meta>` refresh HTML tags or JavaScript `window.location` in `index.html`, or using [external-sites.json](https://docs.github.com/en/contributing/writing-for-github-docs/configuring-redirects#configuring-external-redirects).
