### ISSUE TITLE
dump_whatsapp feature in Meterpreter

### ISSUE THREAD

**Issue by TheBigBossYoyo** [rapid7/metasploit-framework#18202]
Hi
I would like to propose you add a dump_whatsapp_sms and a dump_whatsapp_media command in Meterpreter like the dump_sms feature. I found an app that can do that : https://www.imyfone.com/transfer-backup-restore-whatsapp/. I don't know how difficult it would be and I don't even know if you want to do it but if it's too much work for you don't do it you already do something amazing with Metasploit.
Thanks in advance

**Comment by TheBigBossYoyo** [comment]
Hi why did you close it it's a good idea

**Comment by adfoster-r7** [comment]
Thanks for your contribution to Metasploit Framework! We've looked at this issue, and unfortunately we do not currently have the bandwidth to prioritize this issue.

Pull requests are welcome :+1:
