### ISSUE TITLE
Ubuntu 20.4 - after install getting no such file or dir

### ISSUE THREAD

**Issue by agent733** [rapid7/metasploit-framework#18215]
## Steps to reproduce

How'd you do it?

1. ...Installed into Ubuntu 20.4 with the following command wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall
2. ...Then as per instructions did /opt/metasploit-framework/bin/msfconsole, as other variations  of this, but getting following error bash:  /opt/metasploit-framework/bin/msfconsole

## Were you following a specific guide/tutorial or reading documentation?

https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html
Installing Metasploit on Linux / macOS
Once installed, you can launch msfconsole as /opt/metasploit-framework/bin/msfconsole from a terminal window,

## Expected behavior

Launch metasploit

## Current behavior

getting following error bash:  /opt/metasploit-framework/bin/msfconsole

### Metasploit version

I did the command wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall last night

**Comment by bcoles** [comment]
> I did the command wget https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb && chmod +x msfinstall &&./msfinstall last night

This is not the same as the command in the documentation.

```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```


> getting following error bash: /opt/metasploit-framework/bin/msfconsole

Did the installation complete correctly?

Was the `/opt/metasploit-framework/bin/` directory created?

**Comment by agent733** [comment]
Yes, the command in the documentation didn’t work so to install  I used the one at the following https://github.com/rapid7/metasploit-framework/issues/15137 .

The directory it created was located at C:\metasploit-framework\bin . When I typed in command C:\metasploit-framework\bin\msfconsole I now get the following 
C:metasploit-frameworkbin command not found

**Comment by bcoles** [comment]
> Yes, the command in the documentation didn’t work so to install I used the one at the following #15137 .
> 
> The directory it created was located at C:\metasploit-framework\bin . When I typed in command C:\metasploit-framework\bin\msfconsole I now get the following C:metasploit-frameworkbin command not found

You're using Windows now instead of Ubuntu?

```
C:\>cd C:\metasploit-framework\bin
C:\metasploit-framework\bin>msfconsole.bat
```
