### ISSUE TITLE
portfwd  can't handle more then one session. 

### ISSUE THREAD

**Issue by fastchain** [rapid7/metasploit-framework#18227]
## Steps to reproduce

Hello!

1. Run msf in docker. Version metasploit v6.3.3-dev.
2. get valid meterpreter session. 
3. setup portfwd:

```
meterpreter > portfwd flush
[*] Successfully stopped TCP relay on 127.0.0.1:80
[*] Successfully flushed 1 rules
meterpreter > 
meterpreter > portfwd list

No port forwards are currently active.

meterpreter > portfwd add -L 127.0.0.1 -l 80 -p 80 -r 172.22.22.22
[*] Forward TCP relay created: (local) 127.0.0.1:80 -> (remote) 172.22.22.22:80
meterpreter > portfwd list

Active Port Forwards
====================

   Index  Local            Remote        Direction
   -----  -----            ------        ---------
   1      172.22.22.22:80  127.0.0.1:80  Forward

1 total active port forwards.

meterpreter > 
meterpreter > bg
[*] Backgrounding session 1...
msf6 post(windows/gather/arp_scanner) > curl http://127.0.0.1 -v
[*] exec: curl http://127.0.0.1 -v

*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.80.0
> Accept: */*
> 

(freeze)
```

And then there are two problems:
1. Local host is in "remote" column
2. This forwarding works fine, but  just for first http request (by curl utility),  all further requests freezing  (curl can't get response), and the only  fix is restart of whole meterpreter session.  Successful request was omitted from the listing.

## Were you following a specific guide/tutorial or reading documentation?

https://docs.metasploit.com/docs/using-metasploit/intermediate/pivoting-in-metasploit.html#pivoting-external-tools

## Expected behavior

Working port forwarding for more then one http request.

## Current behavior

What happens instead?

### Metasploit version

```
Framework: 6.3.3-dev
Console  : 6.3.3-dev
```

**Comment by fastchain** [comment]
Can't reproduce on other systems. seems to be an environment problems.

**Comment by adfoster-r7** [comment]
Thanks for the update @fastchain :+1:

**Comment by w4po** [comment]
Same problem, trying to forward to SSH (port 22),
the first try works just as expected, any further connects hang (connected but hanging).

same for curl with HTTP requests.

Metasploit v6.4.7-dev on Windows Server 2019 machine (1809)
