### ISSUE TITLE
Database system is shut down!

### ISSUE THREAD

**Issue by FokhrulSabel** [rapid7/metasploit-framework#18323]
When i try to start msfdb , it's failed. And show this error.

```
Clearing http web data service credentials in msfconsole
Running the 'start' command for the database:
Starting database at /home/kali/.msf4/db...failed
LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
```

And when i reinit it's also show this error.

```
Clearing http web data service credentials in msfconsole
Running the 'reinit' command for the database:
MSF web service is no longer running
Database is no longer running at /home/kali/.msf4/db
Deleting all data at /home/kali/.msf4/db
Creating database at /home/kali/.msf4/db
Creating db socket file at /tmp
Starting database at /home/kali/.msf4/db...failed
Creating database users
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:696:in `async_connect_or_reset': SCRAM authentication requires libpq version 10 or above (PG::ConnectionBad)
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:824:in `connect_to_hosts'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:759:in `new'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg.rb:63:in `connect'
        from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:148:in `create_db_users'
        from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:37:in `init'
        from msfdb:201:in `init_db'
        from msfdb:339:in `reinit_db'
        from msfdb:946:in `invoke_command'
        from msfdb:1086:in `<main>
```

**Comment by ILPlais** [comment]
Hi!

I've got the same problem. Under `msfconsole` when I type:
```
msf6 > msfdb start
```
I have:
```
[*] exec: msfdb start

Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Clearing http web data service credentials in msfconsole
Running the 'start' command for the database:
Starting database at /home/ilp/.msf4/db...failed
LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
```
And, when I try to reinitializing my database, I've got this:
```
msf6 > msfdb reinit
[*] exec: msfdb reinit

Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
[?] Would you like to delete your existing data and configurations? []: yes
Clearing http web data service credentials in msfconsole
Running the 'reinit' command for the database:
MSF web service is no longer running
Database is no longer running at /home/ilp/.msf4/db
Deleting all data at /home/ilp/.msf4/db
Creating database at /home/ilp/.msf4/db
Creating db socket file at /tmp
Starting database at /home/ilp/.msf4/db...failed
Creating database users
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:696:in `async_connect_or_reset': SCRAM authentication requires libpq version 10 or above (PG::ConnectionBad)
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:824:in `connect_to_hosts'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:759:in `new'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg.rb:63:in `connect'
        from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:148:in `create_db_users'
        from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:37:in `init'
        from msfdb:201:in `init_db'
        from msfdb:339:in `reinit_db'
        from msfdb:946:in `invoke_command'
        from msfdb:1086:in `<main>'
```

I'm with metasploit v6.3.37-dev-, and PostgreSQL 16.0 (Debian 16.0-2) under Kali.

**Comment by 4rr0w** [comment]
Encountering the same error

`msf6 > msfdb start
[*] exec: msfdb start

Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Clearing http web data service credentials in msfconsole
Running the 'start' command for the database:
Starting database at /home/arrow/.msf4/db...failed
LOG:  database system is shut down
[!] Your database may be corrupt. Try reinitializing.
`
`msf6 > msfdb init
[*] exec: msfdb init

Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
Clearing http web data service credentials in msfconsole
Running the 'init' command for the database:
Creating database at /home/arrow/.msf4/db
Creating db socket file at /tmp
Starting database at /home/arrow/.msf4/db...failed
Creating database users
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:696:in `async_connect_or_reset': SCRAM authentication requires libpq version 10 or above (PG::ConnectionBad)
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:824:in `connect_to_hosts'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg/connection.rb:759:in `new'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pg-1.5.3/lib/pg.rb:63:in `connect'
	from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:148:in `create_db_users'
	from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/pg_ctl.rb:37:in `init'
	from msfdb:201:in `init_db'
	from msfdb:946:in `invoke_command'
	from msfdb:1086:in `<main>'`
	
It was working fine for few days then encountered this error and it got solved after multiple re-installations and purging metasploit, and postgresql. Now getting the same error again. Is there specific reason for this.

**Comment by 4rr0w** [comment]
@ILPlais  
I read somewhere that we have to stop portgresql and then reinit db. It is working after that. 

`service postgresql stop`
`msfdb reinit`

Does anyone know reason for this?
