### ISSUE TITLE
An error with message "undefined method `search_modules' for Msf::WebServices:Module" when call REST API

### ISSUE THREAD

**Issue by TLGKien** [rapid7/metasploit-framework#18472]
## Steps to reproduce

How'd you do it?

1. I have installed Metasploit Framework and set up the Metasploit web server (for using REST API).
2. Send a request to http `GET /api/v1/modules`

## Were you following a specific guide/tutorial or reading documentation?

Yes, I was following this docs [https://docs.metasploit.com/docs/using-metasploit/advanced/metasploit-web-service.html](https://docs.metasploit.com/docs/using-metasploit/advanced/metasploit-web-service.html)

## Expected behavior

It should return modules matching keywords with appropriate metadata.
![Screenshot from 2023-10-19 21-27-57](https://github.com/rapid7/metasploit-framework/assets/63689509/26072c09-60ed-46a5-a7ce-6b7f5e937f2c)

## Current behavior

It returned an error with message: "There was an error completing the module search: undefined method `search_modules' for Msf::WebServices:Module" and code 500
![Screenshot from 2023-10-19 21-30-36](https://github.com/rapid7/metasploit-framework/assets/63689509/8fb77e7d-8496-4c47-90f2-fb8b5bc613bc)

### Metasploit version

`Framework Version: 6.3.39-dev-`

## Additional Information
I updated to the latest version but my issue is still present.

## Suggestion
"I found this API calling the method `Msf::WebServices.search_modules()` (in file `/framework/lib/msf/core/web_services/servlet/module_search_servlet.rb` line 21), but this method `search_modules()` is not defined in module `Msf::WebServices`. I think `search_modules()` might be mothod in module `Msf::WebServices::ModuleSearch` (because the method `search_modules`() is defined in module `Msf::WebServices::ModuleSearch` in the file `framework/lib/msf/core/web_services/module_search.rb` line 3)". 

I have modified the source code, but I don't know how to rebuild it. It would be great if you could provide a guide for me to edit the code and rebuild the project on my own.

**Comment by adfoster-r7** [comment]
> I have modified the source code, but I don't know how to rebuild it. It would be great if you could provide a guide for me to edit the code and rebuild the project on my own.

You should be able to stop and start the server for it to pick up the latest code changes :+1:
