### ISSUE TITLE
Ubuntu 22.04 - apt upgrade E: Failed to fetch http://downloads.metasploit.com/.../metasploit-framework_6.3.40...

### ISSUE THREAD

**Issue by BeetleChunks** [rapid7/metasploit-framework#18473]
I am attempting to install Metasploit using the commands suggested in the [Docs](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html).
```bash
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```

This results in an error like the one in [issue 18192](https://github.com/rapid7/metasploit-framework/issues/18192).
```
Err:1 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid/main amd64 metasploit-framework amd64 6.3.40+20231020102649~1rapid7-1
  404  Not Found [IP: 23.64.152.106 80]
E: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/pool/main/m/metasploit-framework/metasploit-framework_6.3.40%2b20231020102649%7e1rapid7-1_amd64.deb  404  Not Found [IP: 23.64.152.106 80]
```

I think I have identified the problem and that is the version within the link is not available. When I navigate to `http://downloads.metasploit.com/data/releases/metasploit-framework/apt` and look under `pool/main/m/metasploit-framework` the latest available version is `6.3.39`. If you look back to the error message I am getting, you will see the version requested is `6.3.40`.

I am not sure why this would be happening. This is part of an automated build pipeline that hasn't given me any errors before, so I am hesitant to think it is something I am doing. Please let me know if more information is needed.

**Comment by EdwardDali** [comment]
same problem

**Comment by GiovanniMounir** [comment]
Same problem on various distributions, all of the files listed here are also giving a 404 (maybe a server issue?): http://downloads.metasploit.com/data/releases/metasploit-framework/apt

**Comment by mushpitlab** [comment]
I'm unable to install Metasploit from Knightly official installer...

**Comment by lsclsclsc** [comment]
same problem

**Comment by adfoster-r7** [comment]
Should be resolved now, the latest build 6.3.40 wasn't pushed up as expected - only 6.3.39 was available as spotted by some folk

**Comment by Hackndo** [comment]
Same problem with metasploit-framework_6.3.41%2b20231101102717%7e1rapid7-1_amd64.deb

**Comment by EdwardDali** [comment]
same problem...again

**Comment by adfoster-r7** [comment]
I'm not sure what's causing the flakiness/race condition with the release process just yet, but I believe this is working again now.
