### ISSUE TITLE
Stuck on Channel 1 created

### ISSUE THREAD

**Issue by Drjacky** [rapid7/metasploit-framework#18511]
<img width="145" alt="Screenshot 2023-11-04 at 13 47 51" src="https://github.com/rapid7/metasploit-framework/assets/2296754/5777ebc6-2974-4dce-bef4-93c9a7f6735b">

## Steps to reproduce

How'd you do it?

1. Get meterpreter session
2. Run shell command

## Expected behavior
Access device shell

## Current behavior
Stuck on Channel 1 created

### Metasploit version

metasploit v6.3.42-dev-5b888c49cb022a2c532d1e4296e93c614c211cba

Android 9

**Comment by Drjacky** [comment]
![image](https://github.com/rapid7/metasploit-framework/assets/2296754/5dfd4aa4-5795-4eab-a767-8b786a6a798f)

**Comment by timwr** [comment]
@Drjacky this is working as expected, try typing a command.

I suggest we:
1. Remove the channel/process logging
2. Default to a pty shell on compatible meterpreters?

**Comment by timwr** [comment]
For 1. maybe we can sneak this change in without @wvu noticing: https://github.com/rapid7/metasploit-framework/pull/11982
