### ISSUE TITLE
Error when I try to update via apt on Ubuntu 

### ISSUE THREAD

**Issue by vitich** [rapid7/metasploit-framework#18510]
Err:1 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid/main amd64 metasploit-framework amd64 6.3.42+20231103102631~1rapid7-1
  404  Not Found [IP: 23.214.234.164 80]
E: Failed to fetch http://downloads.metasploit.com/data/releases/metasploit-framework/apt/pool/main/m/metasploit-framework/metasploit-framework_6.3.42+20231103102631~1rapid7-1_amd64.deb  404  Not Found [IP: 23.214.234.164 80]

The same error on a fresh install:
```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```

**Comment by TwistedKnee** [comment]
I am having the same issue while trying to apt upgrade

**Comment by adfoster-r7** [comment]
This should be fixed now; Closing as a duplicate of https://github.com/rapid7/metasploit-framework/issues/18473
