### ISSUE TITLE
Gain SSH Access to Servers by Brute-Forcing Credentials null-byte (Metasploit)

### ISSUE THREAD

**Issue by auscorey91** [rapid7/metasploit-framework#18525]
Am trying to follow the walkthrough in the title for this post and have come across an issue that I need someone to teach me how to fix and the cause of the problem... When I am changing the options for the ssh login scanner I receive the following error.... 
[-] Msf::OptionValidateError The following options failed to validate: USER_FILE, PASS_FILE
I assume it is because I am meant to have these files somewhere and it cant find them because they dont exist. The only difference between the article walkthrough is they have ms5 and I have a later version of kali with ms6.

**Comment by bcoles** [comment]
> [-] Msf::OptionValidateError The following options failed to validate: USER_FILE, PASS_FILE

Set `USER_FILE` and `PASS_FILE`.
