### ISSUE TITLE
cmd_exec fails when SSH'd onto a windows box

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#18546]
## Steps to reproduce

Technically the underlying issue isn't cmd_exec's fault, but it's an edgecase to consider

1. SSH onto a windows box with the `scanner/ssh/ssh_login_pubkey` module
2. The session platform will be identified as a Windows box, even though the shell type is actually unix-based
3. Run a post module and verify that `cmd_exec` doesn't work:
```
[5] pry(#<Msf::Modules::Post__Windows__Gather__Enum_chocolatey_applications::MetasploitModule>)> cmd_exec("whoami")
=> ""
```

The reason for this is, we identify the host platform as windows via the SSH `id` command here result here:

https://github.com/rapid7/metasploit-framework/blob/56016cb3e7b19af439d5007e868f5870f03227fb/lib/metasploit/framework/ssh/platform.rb#L86-L119

When calling `cmd_exec` the logic here chooses between windows commands or linux commands:

https://github.com/rapid7/metasploit-framework/blob/56016cb3e7b19af439d5007e868f5870f03227fb/lib/msf/core/session/provider/single_command_shell.rb#L87-L94

As a result of the platform type being identified as 'windows', even though the shell type is technically linux, the final command run is:

```
echo vuxouoUqoorBOQpKqzsTjobEbUHtIHSY&whoami&echo vuxouoUqoorBOQpKqzsTjobEbUHtIHSY\n
```

Which leads to an empty `cmd_exec` result, as `&` backgrounds tasks instead of chaining commands like on an actual windows shell

You can see the current shell semantics and dialect here:

```
sessiomsf6 auxiliary(scanner/ssh/ssh_login_pubkey) > sessions -i -1
[*] Starting interaction with 1...

echo $SHELL
/bin/sh
echo $(whoami)
ec2amaz-pdsmq8l\vagrant
echo a && echo b
a
b
```

But the 'platform' is obviously windows:

```
msf6 auxiliary(scanner/ssh/ssh_login_pubkey) > sessions -i -1
[*] Starting interaction with 2...
systeminfo


Host Name:                 EC2AMAZ-PDSMQ8L
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          EC2
Registered Organization:   Amazon.com
```

## Expected behavior

Post modules work. 

Potentially the native platform is identified as windows, but the shell session type is unix based.

## Current behavior

Post modules do not work.

## Work around

Force linux as the platform:

```
msf6 post(windows/gather/enum_chocolatey_applications) > irb -i -e 'puts framework.sessions.values.last.platform = "linux"'
[*] You are executing expressions in #<Msf::Ui::Console::CommandDispatcher::Developer:0x00007fabbe5b21f8>
linux
```

Now cmd_exec works:

```
msf6 post(windows/gather/enum_chocolatey_applications) > run session=-1

[!] SESSION may not be compatible with this module:
[!]  * incompatible session platform: linux
[*] Targets Chocolatey version: 1.4.0
[*] Getting chocolatey applications.
[+] Successfully grabbed all items
Installed Chocolatey Applications
=================================

 Name                                Version
 ----                                -------
 7zip                                23.1.0
 7zip.install                        23.1.0
 ...etc...

[*] Post module execution completed
```

### Metasploit version

```
msf6 post(windows/gather/enum_chocolatey_applications) > version
Framework: 6.3.41-dev-ea41ec7a5d
Console  : 6.3.41-dev-ea41ec7a5d
```

**Comment by adfoster-r7** [comment]
Any thoughts on this one @h00die ? 🤔

**Comment by adfoster-r7** [comment]
I wonder if there's any existing conventions to follow here, similar to what we do for Python/Java sessions

**Comment by h00die** [comment]
`platform.rb` is an unfortunate mess of things we'll never be able to keep up with. It was born before my time, and I've simply kept it nourished with things I find. I wish there was a better way, but as pervasive as SSH is on so many platforms/architectures, I don't have a good solution.
