### ISSUE TITLE
`plugin.load` command does not properly load extensions with correct parameters

### ISSUE THREAD

**Issue by Lorenyx** [rapid7/metasploit-framework#18545]
## Steps to reproduce

In terminal:
```
$ msfrpcd -a 127.0.0.1 -P root
[*] MSGRPC starting on 127.0.0.1:55553 (SSL):Msg...
[*] MSGRPC ready at 2023-11-16 22:07:52 -0600.
$ msfrpc -a 127.0.0.1 -P root
...
>> rpc.call('core.version')
=> {"version"=>"6.3.43-dev-", "ruby"=>"3.0.2 x86_64-linux 2021-07-07", "api"=>"1.0"}
>> rpc.call('plugin.load', 'msfd', {'ServerHost'=> '192.168.10.100', 'ServerPort'=>44444})
=> {"result"=>"success"}
>> exit
$ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:55553         0.0.0.0:*               LISTEN      9444/msfrpcd   # IP and port for msfrpcd
tcp        0      0 127.0.0.1:55554         0.0.0.0:*               LISTEN      9444/msfrpcd   # Wrong IP and port for msfd
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:5433          0.0.0.0:*               LISTEN      6510/postgres 
```

## Expected behavior

Load `msfd` with the provided parameters

## Current behavior

Loads `msfd` with its default parameters

### Metasploit version

`6.3.43-dev-`

## Likely Cause of Problem

The line below in `rpc_plugin.rb` converts all the options to symbols however not all plugins (specifically `msfd`, `msgrpc`, `socket_logger`, `sounds`, and `wmap`) expect the options' keys to only be symbols but rather strings.

```ruby
# rpc_plugin.rb
def rpc_load(path, xopts = {})
    opts = {}

    xopts.each do |k, v|
      if k.class == String
        opts[k.to_sym] = v   #  Line in question
      end
    end
```

Example from plugin `msfd.rb` where string is expected instead of symbol:

```ruby
    def initialize(framework, opts)
      super

      # Start listening for connections.
      self.server	= Rex::Socket::TcpServer.create(
        'LocalHost' => opts['ServerHost'] || DefaultHost,
        'LocalPort' => opts['ServerPort'] || DefaultPort,
        'SSL' => opts['SSL']
      )
```

## Potential Solution

Update the `initialize` method in the above specified plugins to check both the string and symbol option in case only one is provided and maintain compatibility with being loaded from the command line. 

Example solution:

```ruby
host = opts['ServerHost'] || opts[:ServerHost] || DefaultHost
# Instead of ...
host = opts['ServerHost'] || DefaultHost
```

**Comment by adfoster-r7** [comment]
I think we might be able to swap this to use https://api.rubyonrails.org/v4.2/classes/ActiveSupport/HashWithIndifferentAccess.html - and avoid any of the extra steps of converting between symbols/strings:

```
def rpc_load(path, xopts = {})
    opts = {}.with_indifferent_access
```

Does that solution work for you? If so, pull requests are definitely welcome 🎉

**Comment by Lorenyx** [comment]
This solution works for me. I didn't realize that type of object existed but it would make the least amount of diffs.

I can create a PR within the day unless its easier for you to commit the change.

**Comment by adfoster-r7** [comment]
A PR sounds good to me, you already did the hard work of finding out what the problem might be! 💯

**Comment by Lorenyx** [comment]
Took a little longer than I expected due to figuring out how `require` works in ruby but I created a PR.

https://github.com/rapid7/metasploit-framework/pull/18583
