### ISSUE TITLE
Can´t start db metasploit on Kali!

### ISSUE THREAD

**Issue by myshuker** [rapid7/metasploit-framework#18551]
System: Kali
Hi friend I have problem to run db in metasploit, 

┌──(kali㉿kali)-[~]
└─$ db_status       
db_status: command not found
             
┌──(kali㉿kali)-[~]
└─$ sudo msfdb init           
Metasploit running on Kali Linux as root, using system database
A database appears to be already configured, skipping initialization

Thought Postgresql is running :

msf6 > service postgresql status
[*] exec: service postgresql status

● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; disabled; preset: d>
     Active: active (exited) since Fri 2023-11-17 19:49:24 EST; 22min ago
    Process: 3252 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 3252 (code=exited, status=0/SUCCESS)
        CPU: 1ms

Nov 17 19:49:24 kali systemd[1]: Starting postgresql.service - PostgreSQL RDBMS.>
Nov 17 19:49:24 kali systemd[1]: Finished postgresql.service - PostgreSQL RDBMS.
lines 1-9/9 (END)

**Comment by h00die** [comment]
`db_status` is a metasploit command, not a console command.

**Comment by myshuker** [comment]
msf6 > db_status
[*] postgresql selected, no connection
msf6 > Interrupt: use the 'exit' command to quit

**Comment by myshuker** [comment]
msf6 > db_status
[*] postgresql selected, no connection
