### ISSUE TITLE
Encoder removal

### ISSUE THREAD

**Issue by Lamm-nguy** [rapid7/metasploit-framework#18554]
How to remove shikata-ga-nai encoder from my computer?
What do i need to remove it?

**Comment by bcoles** [comment]
Why would you want to remove a specific encoder?

The `modules/encoders/x86/shikata_ga_nai.rb` file defines the encoder:

* https://github.com/rapid7/metasploit-framework/blob/56016cb3e7b19af439d5007e868f5870f03227fb/modules/encoders/x86/shikata_ga_nai.rb
