### ISSUE TITLE
DECRYPTING printed when specs are run

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#18562]
https://github.com/rapid7/metasploit-framework/blob/dd701c1cfafdabc99eb6c03bde51e7ec652027d6/spec/lib/rex/proto/kerberos/crypto/aes256_cts_sha1_spec.rb#L90

When specs are running the console prints:

```
Rex::Proto::Kerberos::Crypto::Aes256CtsSha1 .........

DECRYPTING

...
```

that can most likely8 be removed

**Comment by adfoster-r7** [comment]
Oops; Should be good to remove :+1:
