### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by Zhengyscla** [rapid7/metasploit-framework#18624]
## Steps to reproduce

How'd you do it?

1. Normal installer.
2. Run "msfconsole"

I'm using Debian12 operating system.

## Current behavior

```
root on debian in /home/debian
$ msfconsole 
Metasploit tip: Writing a custom module? After editing your module, why not try 
the reload command
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:622:in `match': stack level too deep (SystemStackError)
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:622:in `block in in_addr'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `inject'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `in_addr'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:580:in `initialize'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:332:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:332:in `block in nameservers='
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:328:in `each'
	 ... 11217 levels...
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `driver'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
root on debian in /home/debian
$ 

``` 

### Metasploit version

```
$ msfconsole --version
Framework Version: 6.3.48-dev-
```

**Comment by Jiemook** [comment]
Same here

**Comment by Vortigern-The-Grey** [comment]
I also have this exact issue. Debian 12, normal install, same response.

**Comment by edwin-liew** [comment]
hi guys, 
good day!

have you manage to solve the problem? i have been trying to google for resolution.

**Comment by adfoster-r7** [comment]
Hi there, could you add logging to your framework like this:

https://github.com/rapid7/metasploit-framework/issues/18574#issuecomment-1865029818

And let us know what the results are

**Comment by Zhengyscla** [comment]
> Hi there, could you add logging to your framework like this:
> 
> [#18574 (comment)](https://github.com/rapid7/metasploit-framework/issues/18574#issuecomment-1865029818)
> 
> And let us know what the results are

Hello, I'm sorry for not replying to your question in time, I've tried to reinstall debian, the problem still appears, and then follow your instructions, it repeatedly outputs Attempting to resolve: ```["fe80::1%enp1s0"]``` when it runs, and the problem still appears.

**Comment by Zhengyscla** [comment]
Sorry for the misoperation that closed the issue

**Comment by Zhengyscla** [comment]
Sorry for the misoperation that closed the issue

**Comment by Zhengyscla** [comment]
> 嗨，大家好，美好的一天！
> 
> 你设法解决了这个问题吗？我一直在尝试谷歌寻找解决方案。

Sorry the problem was not resolved, I have tried to reinstall the software or even reinstall the system.

**Comment by edwin-liew** [comment]
Hi,
Hardly anything in Google.
I removed it completely, reinstalled, and do a apt get update

Ed

On Saturday, December 30, 2023, 12:27 PM, Zhengyscla ***@***.***> wrote:





嗨，大家好，美好的一天！

你设法解决了这个问题吗？我一直在尝试谷歌寻找解决方案。


Sorry the problem was not resolved, I have tried to reinstall the software or even reinstall the system.

**Comment by Zhengyscla** [comment]
> Hi, Hardly anything in Google. I removed it completely, reinstalled, and do a apt get update Ed On Saturday, December 30, 2023, 12:27 PM, Zhengyscla ***@***.***> wrote: 嗨，大家好，美好的一天！ 你设法解决了这个问题吗？我一直在尝试谷歌寻找解决方案。 Sorry the problem was not resolved, I have tried to reinstall the software or even reinstall the system. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Hello, thank you for working on this issue even though it didn't work out.

**Comment by edwin-liew** [comment]
Hi,
Someone posted changing the nameserver in /etc/resolv.conf to point to 1.1.1.1
Just a temp workaround. 
Its not persistent after reboot though.
But 


Ed

On Sunday, December 31, 2023, 10:58 PM, Zhengyscla ***@***.***> wrote:





Hi, Hardly anything in Google. I removed it completely, reinstalled, and do a apt get update Ed On Saturday, December 30, 2023, 12:27 PM, Zhengyscla @.> wrote: 嗨，大家好，美好的一天！ 你设法解决了这个问题吗？我一直在尝试谷歌寻找解决方案。 Sorry the problem was not resolved, I have tried to reinstall the software or even reinstall the system. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>


Hello, thank you for working on this issue even though it didn't work out.

**Comment by C1ph3r0x** [comment]
I've had the same issue.
overwrite the existing ipaddr.rb with the content of this file: https://github.com/ruby/ipaddr/blob/master/lib/ipaddr.rb
I did work for me.
Best,

**Comment by dalimahjoub-07** [comment]
https://www.linuxcapable.com/how-to-install-metasploit-framework-on-debian-linux/ 
it work for me ( debian 12 )

**Comment by DFC302** [comment]
@dalimahjoub-07 I originally installed this way, when I received the error. I have since purged, reboot, and re-installed again and still having the same issue. (Debian 12).

@C1ph3r0x I found multiple "ipaddr.rb" files. Do you know the path of the file you specifically overwrote?

**Comment by dalimahjoub-07** [comment]
@DFC302 Try to purge Ruby, purge Metasploit, reboot and reinstall Metasploit, I do it, but I don't think that ruby commade matter, if it works for you then it does

**Comment by Zhengyscla** [comment]
> sudo apt purge metasploit-framework
> 
> sudo apt purge ruby
> 
> reboot
> 
> Install it like this website say https://www.linuxcapable.com/how-to-install-metasploit-framework-on-debian-linux/
> 
> it work for me ( debian 12 )

I did exactly what the site did, but the problem still appeared.
But when I execute ```sudo apt install curl ca-certificates apt-transport-https software-properties-common lsb-release postgresql -y``` I installed these software, and completely uninstalled the metasploit framework and reinstalled, the problem is still there.

> I've had the same issue. overwrite the existing ipaddr.rb with the content of this file: https://github.com/ruby/ipaddr/blob/master/lib/ipaddr.rb I did work for me. Best,

Your help solved my problem and it worked thank you very much.

**Comment by Zhengyscla** [comment]
Although it didn't solve my problem, I also appreciate the help of others

**Comment by adfoster-r7** [comment]
This will be fixed in the next release of framework

**Comment by rootpentesting** [comment]
> I've had the same issue. overwrite the existing ipaddr.rb with the content of this file: https://github.com/ruby/ipaddr/blob/master/lib/ipaddr.rb located here: /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb It did work for me. Best,

Thanks alot this worked fine!

**Comment by rootpentesting** [comment]
> @rootpentesting What version of metasploit framework are you using? This should be fixed on version 6.4.5

metasploit v6.4.6-dev- i installed it with the one-liner on the official website, so i assumed it would've fetched the newest version.

**Comment by adfoster-r7** [comment]
If it's still crashing for you; could you add this additional logging here: https://github.com/rapid7/metasploit-framework/issues/18574#issuecomment-1865029818

Or share the stacktrace that's getting logged out when msfconsole is crashing; we should be able to fix the bug if we have more details available

**Comment by B1aK2** [comment]
> I've had the same issue. overwrite the existing ipaddr.rb with the content of this file: https://github.com/ruby/ipaddr/blob/master/lib/ipaddr.rb located here: /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb It did work for me. Best,

thanks,it's usefuly

**Comment by rootpentesting** [comment]
> If it's still crashing for you; could you add this additional logging here: [#18574 (comment)](https://github.com/rapid7/metasploit-framework/issues/18574#issuecomment-1865029818)
> 
> Or share the stacktrace that's getting logged out when msfconsole is crashing; we should be able to fix the bug if we have more details available

overwriting the ipaddr.rb worked perfectly for me.
