### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by AnonymousRonin** [rapid7/metasploit-framework#18637]
I'msure you're aware as I assume it's by design but I couldn't find the free version on your website.  I hate companies who aren't open about all their options in hope they spend money they don't need to so I call them out publically.

**Comment by h00die** [comment]
![image](https://github.com/rapid7/metasploit-framework/assets/752491/c1194f5f-f0bc-4a2b-be6e-747ce893962b)

its literally the first option, not sure what more you're hoping for?
