### ISSUE TITLE
No Listener Payload Option For Android In Metasploit Pro Web GUI !

### ISSUE THREAD

**Issue by gjuttg** [rapid7/metasploit-framework#18641]
I am using metasploit pro web gui . i can generate a payload for android but there is **no payload listener option for android** in Persistent Listeners option of Global settings. How i can get a reverse tcp meterpreter session if i am unable to start a android listener?

screenshot attached ??

![Screenshot 2023-12-28 001817](https://github.com/rapid7/metasploit-framework/assets/147945529/a509e2c9-400c-4784-92f9-43096ad25363)

**Comment by sempervictus** [comment]
Interesting... thanks for the heads up. Wonder if its some ARCH filter or the like tripping that up.

**Comment by gjuttg** [comment]
> Interesting... thanks for the heads up. Wonder if its some ARCH filter or the like tripping that up.

So what is the solution to this problem?

**Comment by adfoster-r7** [comment]
This is a issue tracker for Metasploit Framework. We do not provide support for Metasploit Pro here or via Slack. Please contact your assigned support provider at https://www.rapid7.com/for-customers/ for help with Metasploit Pro as we are unable to provide assistance via these channels.
