### ISSUE TITLE
Scripts like msfconsole and msfvenom fail to retrieve the current working directory on MacOS when the directory name contains spaces.

### ISSUE THREAD

**Issue by youngsiiimba** [rapid7/metasploit-framework#18654]
**Steps to reproduce:**

1. Go to a directory that has a space. My example shown in the screenshot is `~/Documents/Projects/ctf/htb/windows/Medium/9. Scrambled`.  
2. Next run one of the Metasploit scripts like `msfconsole` or `msfvenom` and you'll get an error saying "No such file or directory". Please refer to the screenshot below.
![Screenshot 2024-01-03 at 09 34 57](https://github.com/rapid7/metasploit-framework/assets/24194556/efa9b078-aae5-41e6-8ec4-f642da1bb88b)

**Quick fix:** 
Open up the `msfconsole` or `msfvenom` script and replace line 14 which has the following line `cd $CWD` with this line `cd "$(dirname "$CWD")"`

The following video shows the problem and the quick fix. I just don't understand the code base enough to add this fix to the master branch.

https://github.com/rapid7/metasploit-framework/assets/24194556/4cac06f5-e252-4b9b-9348-97c4403e116a

**Comment by bcoles** [comment]
Thanks. This appears to be a valid bug in the installer ([rapid7/metasploit-omnibus](https://github.com/rapid7/metasploit-omnibus)).

Tracked here:

* https://github.com/rapid7/metasploit-omnibus/issues/134
* https://github.com/rapid7/metasploit-omnibus/issues/137

A fix was proposed here:

* https://github.com/rapid7/metasploit-omnibus/pull/186

For some reason this PR was not reviewed or merged.

**Comment by adfoster-r7** [comment]
Thanks for the error report; this should be fixed by https://github.com/rapid7/metasploit-omnibus/pull/186 - and available by default in a day or so from now when the next automated build is released :+1:
