### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by YaBoiFluffie** [rapid7/metasploit-framework#18659]
me@device:~ $ sudo msfupdate
Adding metasploit-framework to your repository list..Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Updating package cache..OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
metasploit-framework is already the newest version (6.3.48+20231219104627~1rapid7-1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
me@device:~ $ msfconsole
This copy of metasploit-framework is more than two weeks old.
 Consider running 'msfupdate' to update to the latest version.
Illegal instruction

what the fuck is this?

**Comment by alasalamont** [comment]
To be honest, with your attitude, no one will answer for you :) Learn to be humble, remember you are nothing

**Comment by h00die** [comment]
>  Illegal instruction
> 
> what the fuck is this?

an instruction that runs on the wrong side of the law.

If you want help, I would advise you to fill out the issue form as you were prompted to do, then erased it thinking you knew better.

So far, from what you've given, best I can say is "works for me"

```
└─$ msfconsole -q
Overriding user environment variable 'OPENSSL_CONF' to enable legacy functions.
[*] Starting persistent handler(s)...
[msf](Jobs:0 Agents:0) > version
Framework: 6.3.49-dev
Console  : 6.3.49-dev
```

Why can't we help you?

You haven't provided enough information. Things that would be helpful that you previously ignored when deleting the issue template:

1. what OS is this (looks like linux, could be mac, could be android)
2. is this termux?
3. what version of ruby are you using?
4. what was your metasploit installation method?

With this information, it'll be possible to better narrow down the problem, and thus solution.

There is a big difference between ruby 1.0 running on Android through Termux vs ruby 3.1.x on Kali.  One is triple not supported, the other is.

**Comment by timwr** [comment]
Illegal instruction often means it's the wrong architecture

**Comment by YaBoiFluffie** [comment]
Everythings good, i just reinstalled and voila, it just fucking works! Thanks for your help! 😘
