### ISSUE TITLE
Metasploit is not working anymore after trying to update.

### ISSUE THREAD

**Issue by MrUndead13** [rapid7/metasploit-framework#18671]
Hello everyone.

So I was using metasploit yesterday (on my MBA M1 on MacOS Ventura) and when launching it I was told it was outdated. So I used msfupdate. I use version (6.3.48-dev-a4d602669b5a0db74b39107135ecbc4e6809746c).

I got the download and then it said it was successful but after reusing msfconsole, I was told it was still outdated and it crashed with multiple errors:
```
/opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1087:in `foreach': Too many open files @ rb_sysopen - /etc/resolv.conf (Errno::EMFILE)
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:651:in `in6_addr': invalid address (IPAddr::InvalidAddressError)

... (I can't put them all it is too long)

/opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:598:in `rescue in initialize': invalid address: fe80::5239:2fff:fe70:bb20%en0 (IPAddr::InvalidAddressError)
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:651:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
```

So I tried others ways to launch the update (deactivated my antivirus, sudo etc...) nothing changed.

I decided to reinstall metasploit with the installer but still the same errors. The first error was:
```
/opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1087:in `foreach': Too many open files @ rb_sysopen - /etc/resolv.conf (Errno::EMFILE)
```

For this I changed the memory for ruby and I only have that error now:
```
/opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:214:in `new': stack level too deep (SystemStackError)
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:214:in `initialize'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1128:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1128:in `block in nameservers_from_name'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1127:in `each'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1127:in `nameservers_from_name'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:334:in `rescue in block in nameservers='
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:331:in `block in nameservers='
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:328:in `each'
	 ... 11217 levels...
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `driver'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
```

Coud anyone help me with this ?

I'm sorry my zsh don't have the debug command and I don't really know how to use it...

Thanks in advance

Best

**Comment by Esonhugh** [comment]
Same here.

**Comment by Esonhugh** [comment]
Ok maybe it just because your `/etc/resolv.conf` has some problem. I clean up the file and it works now.

**Comment by MrUndead13** [comment]
Thanks for you help !
What do you mean by cleaning it ? Do I need to delete it or to see if there are issues in there ?


By the way I took my computer out of sleeping mode and I'm back to the first case, before I changed the allocated memory.

**Comment by Esonhugh** [comment]
> Thanks for you help ! What do you mean by cleaning it ? Do I need to delete it or to see if there are issues in there ?
> 
> By the way I took my computer out of sleeping mode and I'm back to the first case, before I changed the allocated memory.

I make file empty and it works. It should work if only deleted the nameserver block.

**Comment by MrUndead13** [comment]
It worked !! Thank you so much for this !!

**Comment by adfoster-r7** [comment]
This should be fixed in the latest release; by https://github.com/rapid7/metasploit-framework/pull/18662
