### ISSUE TITLE
mssql version/info module

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#18684]
## Summary

We need a MSSQL version scanner. Many other modules like this for different protocols, but we don't have one for MSSQL. 

### Basic example

I think something similar to the nmap script would be good: https://nmap.org/nsedoc/scripts/ms-sql-info.html

### Motivation

Lots of mssql out there, right now we have no way to identify it.

**Comment by adfoster-r7** [comment]
Is that what the mssql_ping module is for?
https://github.com/rapid7/metasploit-framework/blob/ffbaf3b141ca9f9a126f02a3ab9ccb89be4d57b6/documentation/modules/auxiliary/scanner/mssql/mssql_ping.md

It'd need to be updated to support checking for TCP, not just UDP though

**Comment by h00die** [comment]
Sure, just needs TCP retooling like you mebtioned

**Comment by adfoster-r7** [comment]
Sounds good - we should probably rename this to mssql_version then too if we/anyone else wants to pick this up :+1:
