### ISSUE TITLE
BUNDLER_CONFIG_ARGS variable mismatch in Dockerfile

### ISSUE THREAD

**Issue by upsidedwn** [rapid7/metasploit-framework#18693]
Doesn't seem to have any particular impact in terms of functionality, but thought to highlight a small issue in the Dockerfile.

Argument is defined as BUNDLER_CONFIG_ARGS here
https://github.com/rapid7/metasploit-framework/blob/63e1b49da1ad5bfbf388c74b336617958a9d975a/Dockerfile#L4

But used as BUNDLER_ARGS here
https://github.com/rapid7/metasploit-framework/blob/63e1b49da1ad5bfbf388c74b336617958a9d975a/Dockerfile#L36

**Comment by adfoster-r7** [comment]
Good spot; Pull requests are welcome 💯

**Comment by upsidedwn** [comment]
Sure, I have created a PR #18701 . However, I am not very familiar with Ruby, do let me know if there are any issues with it.

**Comment by upsidedwn** [comment]
Committed into a new branch, as advised in #18701.
