### ISSUE TITLE
Swapped terms in yard documentation 

### ISSUE THREAD

**Issue by Sh3llSp4wn** [rapid7/metasploit-framework#18695]
![oops](https://github.com/rapid7/metasploit-framework/assets/88262053/69009539-8fbd-47f1-b731-ff0a8494b7aa)

## Summary

There is a typo in the yard documentation that relates to the public and private components of credentials. The terms appear to be swapped. 

Username is referred to as the private component and the password is referred to as the public component. 

[Here is a link to the page in question](https://docs.metasploit.com/api/Metasploit/Framework/Credential.html)

**Comment by adfoster-r7** [comment]
Good spot; Pull requests welcome to help improve things here :+1:

**Comment by adfoster-r7** [comment]
Closed by https://github.com/rapid7/metasploit-framework/pull/18702
