### ISSUE TITLE
Could not connect to session: undefined local variable or method `sysinfo'

### ISSUE THREAD

**Issue by nounouthereal** [rapid7/metasploit-framework#18694]
## Steps to reproduce

How'd you do it?

1. From MacOS Sonoma open a meterpreter session on Windows 10 in a QTM (UTM) VM.
2. Run persisten command on meterpreter

## Were you following a specific guide/tutorial or reading documentation?

Nope

## Expected behavior

Do persistence stuff

## Current behavior

<img width="1337" alt="Screenshot 2024-01-12 at 21 52 19" src="https://github.com/rapid7/metasploit-framework/assets/100050693/a2ff8aeb-30a7-423d-9f5c-0d61f2a2c961">

### Metasploit version

Framework: 6.3.48-dev-a4d602669b5a0db74b39107135ecbc4e6809746c
Console  : 6.3.48-dev-a4d602669b5a0db74b39107135ecbc4e6809746c

**Comment by adfoster-r7** [comment]
Should be fixed by https://github.com/rapid7/metasploit-framework/pull/18667
