### ISSUE TITLE
Metasploit-framework v6.3.48 setup wizard ended prematurely

### ISSUE THREAD

**Issue by TMGboy** [rapid7/metasploit-framework#18707]
## Steps to reproduce

How'd you do it?

1. Followed Guide installation for Windows
2. Installation Failed

I have followed the installation guide , added folder to exclusion give the folder full rwx permissions runs the msi from powershell and with double click all lead to the same result

## Were you following a specific guide/tutorial or reading documentation?

Yes, https://docs.rapid7.com/metasploit/installing-the-metasploit-framework/

## Expected behavior

Succeful installation of MSF 

## Current behavior

Failed Installation with Error : ENDED PREMATURELY"

### Metasploit version

MSF v6.3.48 

## Additional Information

**Logs**

```Property(C): AdminUser = 1
Property(C): Privileged = 1
Property(C): USERNAME = Windows User
Property(C): DATABASE = E:\Downloads\metasploitframework-latest.msi
Property(C): OriginalDatabase = E:\Downloads\metasploitframework-latest.msi
Property(C): SOURCEDIR = E:\Downloads\
Property(C): VersionHandler = 5.00
Property(C): UILevel = 5
Property(C): ACTION = INSTALL
Property(C): EXECUTEACTION = INSTALL
Property(C): ROOTDRIVE = C:\
Property(C): CostingComplete = 1
Property(C): OutOfDiskSpace = 0
Property(C): OutOfNoRbDiskSpace = 0
Property(C): PrimaryVolumeSpaceAvailable = 0
Property(C): PrimaryVolumeSpaceRequired = 0
Property(C): PrimaryVolumeSpaceRemaining = 0
Property(C): INSTALLLEVEL = 1
=== Logging stopped: 15/01/2024  23:12:46 ===
MSI (c) (B4:28) [23:12:46:810]: Note: 1: 1708 
MSI (c) (B4:28) [23:12:46:810]: Note: 1: 2205 2:  3: Error 
MSI (c) (B4:28) [23:12:46:810]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1708 
MSI (c) (B4:28) [23:12:46:811]: Note: 1: 2205 2:  3: Error 
MSI (c) (B4:28) [23:12:46:811]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (B4:28) [23:12:46:811]: Product: Metasploit-framework v6.3.48 -- Installation failed.

MSI (c) (B4:28) [23:12:46:815]: Windows Installer installed the product. Product Name: Metasploit-framework v6.3.48. Product Version: 6.3.48.1. Product Language: 1033. Manufacturer: Rapid7 Release Engineering <r7_re@rapid7.com>. Installation success or error status: 1603.

MSI (c) (B4:28) [23:12:46:819]: Grabbed execution mutex.
MSI (c) (B4:28) [23:12:46:820]: Cleaning up uninstalled install packages, if any exist
MSI (c) (B4:28) [23:12:47:162]: MainEngineThread is returning 1603
=== Verbose logging stopped: 15/01/2024  23:12:47 ===```

**Comment by adfoster-r7** [comment]
Are you running the installer as an administrator?

**Comment by ekalinichev-r7** [comment]
I've tested 6.3.48 installer without running it as administrator and got same result as reported, but when I applied the [workaround from similar report before](https://github.com/rapid7/metasploit-framework/issues/11560#issuecomment-475590324) installation completed successfully.

Documentation needs to be updated to make it more clear that Administrator privileges are required for installation and how to obtain them.

**Comment by adfoster-r7** [comment]
Documentation has been updated now; Please Metasploit on Windows with the 'Run as administrator' functionality

**Comment by Elmagodelasteclas** [comment]
no work for me
