### ISSUE TITLE
Auxiliary::UDPScanner seems to be broken

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#18711]
#16886
#10796

UDPScanners seem to never call `scanner_process`.

## Steps to reproduce

In addition to the previous posts details, today I tried the `scanner/ubiquiti/ubiquiti_discover` module. I'm using kali rolling updated yesterday, metasploit merged to master yesterday (january 16, 2024).  I'm running with `sudo`.

```
msf6 > use 2
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > set rhosts 1.1.1.255
rhosts => 1.1.1.255
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > set verbose true
verbose => true
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > run

[*] Sending probes to 1.1.1.255->1.1.1.255 (1 hosts)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > set rhosts 1.1.1.1/24
rhosts => 1.1.1.1/24
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > run

[*] Sending probes to 1.1.1.0->1.1.1.255 (256 hosts)
[*] Scanned 256 of 256 hosts (100% complete)
[*] Auxiliary module execution completed
```

Looking at the traffic with wireshark, the probes all go out, and 1 device does respond w/ data:
![Screenshot_2024-01-17_04-36-52](https://github.com/rapid7/metasploit-framework/assets/752491/59dd9474-65e0-4259-80ad-642c43091944)

I added a debug statement to `scanner_process` [here](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb#L36-L37):
```
  def scanner_process(data, shost, sport)
    puts data
    offset = 0
```

and nothing prints. This leads me to believe the mixin is broken and not receiving data. I hope it isn't, as it hasn't been touched in [7 years](https://github.com/rapid7/metasploit-framework/commits/master/lib/msf/core/auxiliary/udp_scanner.rb), however when the module's aren't getting their `scanner_process` function called, they assume no data came back (even though wireshark shows it has).

**Comment by bcoles** [comment]
Try running Metasploit as root? #9244

**Comment by adfoster-r7** [comment]
Works for me pointing at a ncat udp listener:

```
$ ncat -ulv 2115
Ncat: Version 7.94 ( https://nmap.org/ncat )
Ncat: Listening on [::]:2115
Ncat: Listening on 0.0.0.0:2115
aaaaaaaa # My buffered buffered write

Ncat: Connection from 127.0.0.1:62718 # After running the module
```

My breakpoint triggers after changing rhost and rport to match the above listener:

```
From: /Users/user/metasploit-framework/modules/auxiliary/scanner/ubiquiti/ubiquiti_discover.rb:38 Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule#scanner_process:

    33:     @probe = "\x01\x00\x00\x00"
    34:   end
    35: 
    36:   def scanner_process(data, shost, sport)
    37:     require 'pry-byebug'; binding.pry
 => 38:     offset = 0
    39:     if data.length < 4
    40:       return
    41:     end
    42: 
    43:     type, length = data.unpack("vn")

```

Confirmed working on an OSX host; Maybe my mock target setup doesn't have the same semantics as yours

**Comment by adfoster-r7** [comment]
On Kali linux it's able to detect the socket write via `io.select` too:

```ruby
msf6 auxiliary(scanner/ubiquiti/ubiquiti_discover) > run rhost=192.168.123.1 rport=2115

From: /home/kali/metasploit-framework/lib/msf/core/auxiliary/udp_scanner.rb:175 Msf::Auxiliary::UDPScanner#scanner_recv:

    170:     queue = []
    171:     start = Time.now
    172:     while Time.now - start < timeout do
    173:       readable, _, _ = ::IO.select(@udp_sockets.values, nil, nil, timeout)
    174:       require 'pry-byebug'; binding.pry
 => 175:       if readable
    176:         for sock in readable
    177:           res = sock.recvfrom(65535, timeout)
    178: 
    179:           # Ignore invalid responses
    180:           break if not res[1]

[1] pry(#<Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule>)> readable
=> [#<Socket:fd 9>]
```

It looks like it can bail early here though; do you have a workspace boundary set maybe?

https://github.com/rapid7/metasploit-framework/blob/39b094313f9fb3d53b667691bd2f30aea99e42fa/lib/msf/core/auxiliary/udp_scanner.rb#L187-L188

```ruby
From: /home/kali/metasploit-framework/lib/msf/core/auxiliary/udp_scanner.rb:189 Msf::Auxiliary::UDPScanner#scanner_recv:

    184: 
    185:           # Trim the IPv6-compat prefix off if needed
    186:           shost = res[1].sub(/^::ffff:/, '')
    187: 
    188:           # Ignore the response if we have a boundary
 => 189:           next unless inside_workspace_boundary?(shost)
    190: 
    191:           queue << [res[0], shost, res[2]]
    192: 
    193:           if queue.length > datastore['ScannerRecvQueueLimit']
    194:             break

[3] pry(#<Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule>)> shost
=> "192.168.123.1"
[4] pry(#<Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule>)> inside_workspace_boundary?(shost)
=> true
[5] pry(#<Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule>)> method(:inside_workspace_boundary?)
=> #<Method: Msf::Modules::Auxiliary__Scanner__Ubiquiti__Ubiquiti_discover::MetasploitModule(Msf::Auxiliary::Report)#inside_workspace_boundary?(ip) /home/kali/metasploit-framework/lib/msf/core/auxiliary/report.rb:113>  
```

Eventual implementation code:

https://github.com/rapid7/metasploit-framework/blob/39b094313f9fb3d53b667691bd2f30aea99e42fa/app/concerns/mdm/workspace/boundary_range.rb#L15-L37

**Comment by h00die** [comment]
`sudo` and `root` don't have workspaces or a DB connection. My previous post for the `sip` stuff was done on a different laptop (still Kali rolling)

**Comment by Flash7100** [comment]
All these Metasploit framework is bullshit. None of these so called IT gurus and hackers can fix Metasploit. All over the internet these so called IT gurus uploads a bunch of bullshit everywhere claiming this work and that work. Fuck off you amateur IT shits
