### ISSUE TITLE
Python meterpreter fails to download/upload large files (up to 10 MB) - Bug?

### ISSUE THREAD

**Issue by Admin9961** [rapid7/metasploit-framework#18717]
My msf version: "metasploit v6.3.44-dev-"
my OS: Linux
My network rate speed: 100 GBps
Target OS: Windows 10, equipped with Python3.12. The error happened on Unix VMs with various python versions aswell. I tried to compile the .py in an .exe using Pyinstaller to see how it behaves with various Python versions, and it keeps crashing. Possibly a bug

The error is a timeout exception, the verbose output says to increase the delays, but it doesn't work (keep crashing even when increasing delays).

This doesn't happen with all other meterpreter variants, just with all python meterpreter payloads.

Additional configuration:
msfvenom command `msfvenom -p python/meterpreter/reverse_tcp lhost=IP lport=myownport -f raw -o output.py`

![image](https://github.com/rapid7/metasploit-framework/assets/121270287/43617b80-5761-43d2-8025-99db2668b914)

**Comment by adfoster-r7** [comment]
If you log the TLV packets, does that help shed any light?

https://github.com/rapid7/metasploit-framework/blob/master/docs/metasploit-framework.wiki/Meterpreter-Debugging-Meterpreter-Sessions.md#log-meterpreter-tlv-packets

Note that the logging may clutter up your msfconsole

**Comment by Admin9961** [comment]
Upon running command "ls" and "download" I get this error in the debug console, only if output.py is ran from Python 3.12 on Windows. On MSF side is "stdapi_fs_stat: Operation failed: Unknown error"
"DEBUG:root:Traceback (most recent call last):
  File "<string>", line 1717, in create_response
  File "ext_server_stdapi.py", line 2084, in stdapi_fs_stat
  File "ext_server_stdapi.py", line 897, in get_stat_buffer
struct.error: 'I' format requires 0 <= number <= 4294967295"

With Python 3.8 ( before upgrading to 3.12) I didn't get errors in running these commands, but upon downloading large files (say 10-15 MB with a good connection) the download did randomly failed, and it never did that with native C Meterpreter. I think the python stager is made for an older version of Python that faced a deprecation library issue... Maybe the 2.7 variant... I don't have much time to investigate this, sadly.

**Comment by adfoster-r7** [comment]
Thanks for taking a look!

When you say 10mb, do you mean 10gb? 👀

**Comment by Admin9961** [comment]
Nope, 10 mb. It can still transfer small size file ranging from 2 mb to 5-6 mb with no problems. Large downloads ( 10 mb or more will 100% fail with a timeout error) I pinpoint again, I have 100 GBps connection speed. The C variant x86/x64 can download 300 MB with no issues.
