### ISSUE TITLE
6.3.48 Unable to upgrade and install a higher version

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#18724]
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
Command installation has always been version 6.3.48, with the latest Linux manual installation metasploit-framework-6.3.48+20231220112659

**Comment by Zhengyscla** [comment]
There should be no newer version rolled out.

**Comment by adfoster-r7** [comment]
Thanks for the issue report; There has been an issue on our side for releasing new versions - I can see here that Metasploit 6.3.53 should have been released by now:

https://github.com/rapid7/metasploit-framework/blob/37e82384e4eb7f99258245c30cc0fa7f8da5accc/lib/metasploit/framework/version.rb#L35

Will look into resolving this

**Comment by adfoster-r7** [comment]
New versions should be available now, thanks for the report :+1:

**Comment by maverick-fox** [comment]
I have the same issue . I always got  the message "This copy of metasploit-framework is more than two weeks old.
 Consider running 'msfupdate' to update to the latest version." After msfupdate command , I get the message:"Switching to root user to update the package
Adding metasploit-framework to your repository list. File «/usr/share/keyrings/metasploit-framework.gpg» exists. Overwrite? (y/N)" and nothing happens. Still the same version: metasploit v6.4.49-dev- on Ubuntu 24.04.2 LTC
