### ISSUE TITLE
Why  is it impossible for the value of the ebx register to change after calling ReflectiveLoader?

### ISSUE THREAD

**Issue by struce2** [rapid7/metasploit-framework#18736]
code https://github.com/rapid7/metasploit-framework/blob/6.1.43/lib/msf/core/payload/windows/meterpreter_loader.rb#L46

After executing this line, ebx point to the ReflectiveLoader function, then the function was called.

Inline 50, https://github.com/rapid7/metasploit-framework/blob/6.1.43/lib/msf/core/payload/windows/meterpreter_loader.rb#L50 , using the ebx register to calculate the end position of the dll, will ebx not be modified in the ReflectiveLoader function?

If it will definitely not be modified, why?

**Comment by upsidedwn** [comment]
By convention, ebx is not a volatile register, hence compiler generated code will ensure that the original value stored in the register is preserved after the call.

**Comment by struce2** [comment]
Thanks, I found a microsoft abi document [callercallee-saved-registers](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#callercallee-saved-registers)
