### ISSUE TITLE
Msfconsole error

### ISSUE THREAD

**Issue by Pradeesh2007** [rapid7/metasploit-framework#18756]
~ $ msfconsole
Metasploit tip: You can upgrade a shell to a Meterpreter session on many
platforms using sessions -u <session_id>
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'                                                                          from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'                                                         from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'                                                            from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'
~ $

Please help me to fix this error

**Comment by tirthajyotideka020** [comment]
![Screenshot_2024-01-27-23-31-03-75_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/6169b234-9e50-4745-aaac-7fec03b3b6d7)
Same Problem

**Comment by tirthajyotideka020** [comment]
How to solve the error ???????????
🤔🤔

**Comment by Pradeesh2007** [comment]
🤷

**Comment by Pradeesh2007** [comment]
🤷

**Comment by Pradeesh2007** [comment]
Anybody can solve the problem

**Comment by tirthajyotideka020** [comment]
![Screenshot_2024-01-28-22-59-35-28_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/61c25fa0-a866-437a-9789-4fc1ada7ca5c)
Problem Solved

**Comment by Pradeesh2007** [comment]
How bro 
Please help me to solve the problem

**Comment by tirthajyotideka020** [comment]
Step 1:  Create the config file using this command -
~$  **nano /data/data/com.termux/files/usr/etc/resolv.conf**
![Screenshot_2024-01-29-10-41-19-80_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/3a4417e7-0e78-49a7-abd2-ec7778fe37e7)
Avoid Step 1 if file already exists.

Step 2:  Edit this1 file by using this command -
~$  **nano /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb**
![Screenshot_2024-01-29-11-19-13-23_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/5f0188e7-15a7-476b-9d80-0cd86c5d4a5a)
Replace the config_file (line:98) directory with "/data/data/com.termux/files/usr/etc/resolv.conf"

Step 3:  Edit another file by using this command -
~$  **nano /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb**
![Screenshot_2024-01-29-11-22-35-94_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/a639edff-4805-4a8d-85f7-449293de530b)
Replace the config_file (line:17) directory with "/data/data/com.termux/files/usr/etc/resolv.conf"

Step 4: Restart the Metasploit using this command -
~$  **msfconsole**
![Screenshot_2024-01-29-11-15-46-34_84d3000e3f4017145260f7618db1d683](https://github.com/rapid7/metasploit-framework/assets/106372179/69ad60b2-9407-4f82-9975-86ab1a58cdcc)

**Comment by Pradeesh2007** [comment]
Bro it's working.
Thanks for your help.

**Comment by adfoster-r7** [comment]
Will be patched in an upcoming release by https://github.com/rapid7/metasploit-framework/pull/18760
