### ISSUE TITLE
Add the current status of features to the debug command output

### ISSUE THREAD

**Issue by dwelch-r7** [rapid7/metasploit-framework#18793]
Realised when looking at #18791 that the debug command output doesn't have the feature flag status included 
We should add another section to the debug command output containing something similar to the output of the `features` command within msfconsole 

``````
## Framework config

The following framework config was set before the issue occurred:

<details>
<summary>Collapse</summary>

```
Features
========

   #   Name                         Enabled
   -   ----                         -------
   0   wrapped_tables               true
   1   fully_interactive_shells     false
   2   manager_commands             true 
   3   datastore_fallbacks          true 
   4   metasploit_payload_warnings  true 
   5   defer_module_loads           false
   6   smb_session_type             true 
   7   postgresql_session_type      false
   8   mysql_session_type           false
   9   dns_feature                  true 
   10  hierarchical_search_table    true
```
</details>

``````
 
This will be particularly useful when trying to replicate issues that may or may not be affected by a feature flag (in the case of #18791 the error only occurs when `defer_module_loads` is set to `false` for example)

**Comment by snehalchaudhari98** [comment]
Hi! I want to try to fix the issue. It's the first time I'm contributing to an open-source project, so I think I would be able to fix it and contribute something. Could you please assign this issue to me?
