### ISSUE TITLE
Multiple psnuffle bugs

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#18805]
## Steps to reproduce

Multiple psnuffle modules don't work correctly in certain scenarios; the HTTP/SMB/IMAP/POP3 modules have bugs as shown here:

https://github.com/rapid7/metasploit-framework/pull/18398#issuecomment-1892493283

POP3 bug:

https://github.com/rapid7/metasploit-framework/issues/18625

**Comment by nrathaus** [comment]
Fix suggestion: https://github.com/rapid7/metasploit-framework/pull/19059
