### ISSUE TITLE
Gitlab login scanner ignoring user and pass files.

### ISSUE THREAD

**Issue by p3tr0v** [rapid7/metasploit-framework#18831]
## Steps to reproduce

How'd you do it?

Using `scanner/http/gitlab_login`, set `RHOST` with a valid Gitlab endpoint.
Then set username and password (or user_file and pass_file), then run.
Inspecting the Wireshark, we can see the module fully ignoring the user and password set. 

![giterror](https://github.com/rapid7/metasploit-framework/assets/28512249/004cc453-db3b-4604-90b8-256a68807341)

## Expected behavior
Use user and password set by the analyst.

### Metasploit version
Framework: 6.3.56-dev-
Console  : 6.3.56-dev-

**Comment by adfoster-r7** [comment]
It looks like the module is using the `HttpUsername` and `HttpPassword` options for this value, not the `USERNAME` and `PASSWORD` options

**Comment by Takahiro-Yoko** [comment]
PR: https://github.com/rapid7/metasploit-framework/pull/19381
