### ISSUE TITLE
something's wrong

### ISSUE THREAD

**Issue by patatessss121aq** [rapid7/metasploit-framework#18917]
So why can't I upgrade to the top version?

msf6 > sudo apt update; apt install metasploit-framework
[*] exec: sudo apt update; apt install metasploit-framework

Hit:1 http://kali.download/kali kali-rolling InRelease
Hit:2 http://kali.download/kali kali-bleeding-edge InRelease
Hit:3 http://kali.download/kali kali-experimental InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
metasploit-framework is already the newest version (6.3.55-0kali2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by adfoster-r7** [comment]
This should be fixed in the latest version of Metasploit

**Comment by patatessss121aq** [comment]
I tried to update but it didn't work

**Comment by adfoster-r7** [comment]
What version of Metasploit are you running?

**Comment by patatessss121aq** [comment]
This is my version of metasploit v6.3.55-dev

**Comment by patatessss121aq** [comment]
> What version of Metasploit are you running?

I just realized something new

maybe it can help you figure it out

**Comment by adfoster-r7** [comment]
I think if you install the latest version of Metasploit (v6.5.58 I believe) it should work; someone else was running into this issue and it was resolved when they updated their metasploit version

https://github.com/rapid7/metasploit-framework/issues/18856

**Comment by patatessss121aq** [comment]
I managed to update it, but now it cannot find the database with the armitage tool, but there are database files, but it claims that it does not exist, how can I solve this problem or is there a more appropriate place where I can ask these questions instead of asking them here?
 
 I can not find a database.yml file. I *really need it. Here's how to fix this:

1. Try setting MSF_DATABASE_CONFIG to a file that exists.

2. Did you use sudo to start this program? Try sudo -E

3. Kali Linux users, try this:

msfdb init

**Comment by patatessss121aq** [comment]
Anlıyorum sağolun birde metasploiti kali linuxun reposundan indiremiyorum bunu çözeminin bir yolu var mı

msf6 > sudo apt update; apt install metasploit-framework
[*] exec: sudo apt update; apt install metasploit-framework

Hit:1 http://kali.download/kali kali-rolling InRelease
Hit:2 http://kali.download/kali kali-bleeding-edge InRelease
Hit:3 http://kali.download/kali kali-experimental InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
metasploit-framework is already the newest version (6.3.55-0kali2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by adfoster-r7** [comment]
It looks 6.3.58 will be available for Kali at some point in the future: https://gitlab.com/kalilinux/packages/metasploit-framework/-/commit/ec517c76e0da818cc901ca289023746ec050d049

**Comment by ADHDgithub** [comment]
how has this still not been solved yet in newest update?

**Comment by adfoster-r7** [comment]
I'm not sure when the release will be available in Kali; You can apply this patch locally as a workaround https://github.com/rapid7/metasploit-framework/pull/18871

**Comment by ADHDgithub** [comment]
> I'm not sure when the release will be available in Kali; You can apply this patch locally as a workaround #18871

That fix is for auxiliary. Not for the database.yml not found issue.

**Comment by jmartin-tech** [comment]
@patatessss121aq, while the originally posted issues can be addressed with manual application of #18871, the latest edit to the description now asks a very different question.

> So why can't I upgrade to the top version?

Metasploit Framework as installed by default on Kali is a fork maintained [here](https://gitlab.com/kalilinux/packages/metasploit-framework/) by the Kali team and not the nightly build of this repository.  Each released version's tag is imported and merged to the Kali fork by that team often resulting in some lag.

**Comment by patatessss121aq** [comment]
> @patatessss121aq, while the originally posted issues can be addressed with manual application of #18871, the latest edit to the description now asks a very different question.
> 
> > So why can't I upgrade to the top version?
> 
> Metasploit Framework as installed by default on Kali is a fork maintained [here](https://gitlab.com/kalilinux/packages/metasploit-framework/) by the Kali team and not the nightly build of this repository. Each released version's tag is imported and merged to the Kali fork by that team often resulting in some lag.

Thank you
