### ISSUE TITLE
Is there a way to permanently set "color" to true?

### ISSUE THREAD

**Issue by znre** [rapid7/metasploit-framework#18913]
## Summary
I just want to have color be permanently set to true.

**Comment by adfoster-r7** [comment]
You can use `setg` and `save` to persist default configuration values in msfconsole

**Comment by znre** [comment]
I have tried `setg color true` and then `save` but the color doesn't persist.

I can confirm that my environment persists the environment because it immediately goes back to the module I'm using when I start it up again (after exiting). The `color` config just won't save for some reason.

**Comment by adfoster-r7** [comment]
Can you provide exact replication steps please :+1:
