### ISSUE TITLE
update DEPRECATION 

### ISSUE THREAD

**Issue by sec13b** [rapid7/metasploit-framework#18942]
you can permanently resolve this DEPRECATION in the DEPRECATION section of apt-key(8) for details.

google it for solution , save problem 

ubuntu@sakerhet:~/jet$ sudo apt update -y
Hit:1 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: http://downloads.metasploit.com/data/releases/metasploit-framework/apt/dists/lucid/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
ubuntu@sakerhet:~/jet$

**Comment by nrathaus** [comment]
Fix suggested here: https://github.com/rapid7/metasploit-omnibus/pull/192
