### ISSUE TITLE
MSF not writing run-time errors in a spool file.

### ISSUE THREAD

**Issue by kashyap-sodha** [rapid7/metasploit-framework#18953]
Hi,
I'm trying to verify MSF runtime errors like `Msf::OptionValidateError` but it doesn't seem to be writing neither in the spool file nor in `framework.log`.

## Steps to reproduce

How'd you, do it?

1. Go to `msfconsole`
2. ` use auxiliary/scanner/ftp/ftp_version`
3. Set RHOSTS to any random file.
4. Spool an output file.
5. Run it.
6. You should see the Validation error in the msfconsole. Though it is not present in the spooled output file.

<img width="932" alt="msfconsole_output" src="https://github.com/rapid7/metasploit-framework/assets/156705198/ea94fef8-bb86-40b4-ace0-eb5b7857fc68">
<img width="928" alt="spooled_output_file" src="https://github.com/rapid7/metasploit-framework/assets/156705198/cb2eb347-2a12-4219-8c33-bc556da81eb4">

This error does not get logged to `framework.log` regardless of the log level being set. [Log](https://docs.metasploit.com/docs/development/developing-modules/libraries/how-to-log-in-metasploit.html)
<img width="821" alt="framework_log" src="https://github.com/rapid7/metasploit-framework/assets/156705198/c3ea322f-e86f-402a-8539-8f654fff53a4">

### Metasploit version

Framework: 6.3.27-dev
Console: 6.3.27-dev

**Comment by kashyap-sodha** [comment]
It was for some internal use which I can't disclose much about. But yeah, if that's intentional and can't be moved to logging, I can close this issue in that case. Thanks!

**Comment by adfoster-r7** [comment]
Pull request:

**Comment by kashyap-sodha** [comment]
> Pull request: #18954
> 
> @kashyap-sodha If you're able to apply those changes locally, does that meet your expectations?

Hey @adfoster-r7 That seems to be working fine. Thanks!
