### ISSUE TITLE
Unable to rebuild apk with apktool 

### ISSUE THREAD

**Issue by RahulTarafder** [rapid7/metasploit-framework#18976]
![Screenshot_2024_0320_102924](https://github.com/rapid7/metasploit-framework/assets/109901628/c4b1ca20-0742-41b3-91dc-912472ac7a80)

**Comment by bcoles** [comment]
This issue has been posted on the Apktool issue tracker a few times:

* https://github.com/iBotPeaches/Apktool/issues?q=is%3Aissue+exec+code+%3D+132+is%3Aclosed


> Exit code 132 is illegal instruction, which normally means you are running on an unsupported architecture

**Comment by adfoster-r7** [comment]
Looks like this can be closed, thanks!
