### ISSUE TITLE
Can't run msfupdate in metasploitframework/metasploit-framework:latest docker image

### ISSUE THREAD

**Issue by CaledoniaProject** [rapid7/metasploit-framework#18975]
I'm trying to use the docker version of metasploit,

```
docker run -it metasploitframework/metasploit-framework:latest
```

The image is 3 months ago, so I need to run msfupdate, but the default configuration won't allow me to do that.

```
9c97e058b502:/usr/src/metasploit-framework$ ./msfupdate
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[-] ERROR: User running msfupdate does not own the Metasploit installation
[-] Please run msfupdate as the same user who installed Metasploit.
```

Please fix the permissions by changing all file owners to the same user, the current owner is root.

**Comment by adfoster-r7** [comment]
A new docker release is available now; I don't think `msfupdate` will ever work in the official docker images - potentially it should be updated to make that more clear

**Comment by CaledoniaProject** [comment]
@adfoster-r7 In that case, can we do a nightly automatic build of docker images?

**Comment by adfoster-r7** [comment]
Good call - hoping to have that wired that up this year, it's definitely on the TODO list 💯
