### ISSUE TITLE
Version 6.3.16 C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-core-0.1.31/lib/rex/compat.rb:381: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead  api issue

### ISSUE THREAD

**Issue by PIG-BOY** [rapid7/metasploit-framework#18981]
C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/rex-core-0.1.31/lib/rex/compat.rb:381: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
An error is reported when the latest version is running
<img width="1222" alt="Snipaste_2024-03-21_13-53-38" src="https://github.com/rapid7/metasploit-framework/assets/60567381/835f197d-023f-4a4e-8282-9ca7b5528e09">

**Comment by adfoster-r7** [comment]
Thanks for reporting; The warning is safe to ignore :+1:
