### ISSUE TITLE
Race condition in RPC session API

### ISSUE THREAD

**Issue by FenixH** [rapid7/metasploit-framework#19013]
Sessions are registered at the framework here: https://github.com/rapid7/metasploit-framework/blob/0e3e7b594e5b16a0de592452c9cb09a05af8057b/lib/msf/core/handler.rb#L267

This is an issue as not all initital logic for the session has been run. For example, bootstrap functions by the session handler, auto-run scripts and custom event handlers. The issue is that the API server lists sessions as soon as they are registered: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/rpc/v10/rpc_session.rb#L31

Apart from the obvious issue of a user/script running a command in a session based on what the API server lists (before the session is ready) there are also race conditions possible by simply calling the session get parameters - which are called by the ```rpc_list``` command. 

For example, ```session.tunnel_peer``` can easily be set to ```127.0.0.1``` for an interactive session if it is called too early: https://github.com/rapid7/metasploit-framework/blob/7a3d031b1567686d6148ee968dc62d0195d916ab/lib/msf/core/session/interactive.rb#L65
This causes a number of issues, for example, related to routing.

I am a bit uncertain on the best-practice method to solve this issue. I present two example alternatives:

- One way would be to move https://github.com/rapid7/metasploit-framework/blob/0e3e7b594e5b16a0de592452c9cb09a05af8057b/lib/msf/core/handler.rb#L267 further down, perhaps just before ```session_waiter_event.notify(session)```. I am unsure regarding the consequences to other parts of the framework if this is done though. 
- Another way is to allow the rpc session API to listen to session events (```framework.events.add_session_subscriber(self)```) and  have its own internal list of "ready" sessions.

I am happy to provide a patch for either solution, should you deem it useful.

**Comment by nrathaus** [comment]
@FenixH can you provide a PR for this bug? also can you give some steps to reproduce? I think I am experiencing similar issues when I call Metasploit via pymetasploit3 - I artificially added a `wait` (sleep) before calling additional calls to the session that was created
