### ISSUE TITLE
Slack channel available?

### ISSUE THREAD

**Issue by nrathaus** [rapid7/metasploit-framework#19025]
A slack server/channel is referenced here:
[https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html](https://docs.metasploit.com/docs/development/get-started/setting-up-a-metasploit-development-environment.html)

Specifically links to:
[https://www.metasploit.com/slack](https://www.metasploit.com/slack)

Is this still supported? the link shows as expired

**Comment by bcoles** [comment]
Slack is still supported. These Slack invitation links are no longer valid:

* https://www.metasploit.com/slack
* https://metasploit.com/help

**Comment by bcoles** [comment]
Here's a temporary invite: https://join.slack.com/t/metasploit/shared_invite/zt-2fqz701bq-UoCQ_nSUqzt2W6qoF9_9qQ

**Comment by nrathaus** [comment]
Thanks
