### ISSUE TITLE
mah7

### ISSUE THREAD

**Issue by Mah7xk** [rapid7/metasploit-framework#19027]
No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10236 bytes
حاولت كثيرا بحل هذه المشكلهه ولكن لم اصل لحل   ارجو مساعدتي

**Comment by bcoles** [comment]
> حاولت كثيرا بحل هذه المشكلهه ولكن لم اصل لحل ارجو مساعدتي

There is no problem here. Metasploit output the raw payload. To output to file, use the `-o` flag: `-o filename.apk`.

**Comment by Mah7xk** [comment]
شكراا جزيلا لك


في السبت، ٣٠ مارس ٢٠٢٤ ٤:١٠ ص bcoles ***@***.***> كتب:
