### ISSUE TITLE
Problem of integrating Metasploit into CI/CD pipeline

### ISSUE THREAD

**Issue by IGNFIfortrue** [rapid7/metasploit-framework#19049]
Hello guys,

I am new to metasploit, I wish to integrate it into our CI/CD pipeline but I am stuck since it is a framework with interactive CLI.

I am currently think about use docker to run it, with such commands:

`
docker run --rm -it -v /tmp/:/tmp/ --network=host metasploitframework/metasploit-framework ./msfconsole -r docker/msfconsole.rc -x "use dos/http/flexense_http_server_dos; set RHOSTS target_url; run"
`
But I cannot ouput the scan results, because it asks me to set up the database, am I in the wrong way?
Do you have better methods to run it in pipeline?
Thanks a lot

**Comment by nrathaus** [comment]
I believe on your first run of `metasploit` should run the command `msfdb init`

It would be very cost "expensive" to do that every CI/CD, it may be a good idea to have a persistent volume between CI/CD - in a nutshell `msfdb init` creates some empty tables, and a `.msf4/` folder for some logs and other stuff

So maybe keeping a record of whats in this initial DB and `.msf4` folder and using it in your own base image is a good idea to make the CI/CD run faster

**Comment by adfoster-r7** [comment]
Not sure if I understand the question; Changing to:

```diff
- docker run --rm -it -v /tmp/:/tmp/ --network=host metasploitframework/metasploit-framework ./msfconsole -r docker/msfconsole.rc -x "use dos/http/flexense_http_server_dos; set RHOSTS target_url; run"
+ docker run --rm -it -v /tmp/:/tmp/ --network=host metasploitframework/metasploit-framework ./msfconsole -r docker/msfconsole.rc -qx "use dos/http/flexense_http_server_dos; set RHOSTS 127.0.0.1; run; exit"
```

Works as expected for me, without needing a database enabled

**Comment by nrathaus** [comment]
```
    -q, --quiet                      Do not print the banner on startup
    -x, --execute-command COMMAND    Execute the specified console commands (use ; for multiples)
```

**Comment by nrathaus** [comment]
We can close this thread

**Comment by adfoster-r7** [comment]
> if I dont use database, is there any way I can output the scan results in xml?

Unfortunately there's not a holistic solution that would work for multiple modules sorry; a database would very likely be required if you don't want to export captured results from the database as XML

Maybe in the future we could standardise what modules return programmatically if you were to use the [RPC functionality](https://docs.metasploit.com/docs/using-metasploit/advanced/RPC/); or you could write your own Metasploit plugin to cause database calls to be output as XML/JSON as a module runs - but I don't believe there's anything that would work out of the box

**Comment by adfoster-r7** [comment]
Will close this; pull requests/suggestions for future improvements are welcome
