### ISSUE TITLE
Support Ruby 3.1

### ISSUE THREAD

**Issue by navjotjsingh** [rapid7/metasploit-framework#19043]
Ruby 3.0 has reached EOL. https://www.ruby-lang.org/en/downloads/branches/ 

Plus it doesn't support OpenSSL 3.0 which means it takes a lot of workarounds to get it working if you want to install it using the source code.

It's high time we should update Metasploit to work with Ruby 3.1. 

Also meanwhile this happens, we should at least immediately add support for Ruby 3.0.6 which is the last stable 3.0.x version.

**Comment by adfoster-r7** [comment]
Metasploit-framework supports Ruby 3.1 and OpenSSL 3.x transparently; were there specific issues/bugs you were hitting?

**Comment by navjotjsingh** [comment]
The .ruby-version file says Ruby 3.0.5 is required which causes issues when you try to install because it requires OpenSSL 1.1.1 to work.

**Comment by adfoster-r7** [comment]
You should be able to change that locally and everything should work 🤞

**Comment by adfoster-r7** [comment]
We'll be enabling Ruby 3.1 by default soon enough, but for now you can change that file yourself and everything should work without issues

**Comment by adfoster-r7** [comment]
Ruby 3.1 is enabled by default now: https://github.com/rapid7/metasploit-framework/pull/19189

Will close this off
