### ISSUE TITLE
timeout everytime

### ISSUE THREAD

**Issue by 12yearsoldcoder** [rapid7/metasploit-framework#19057]
using Metasploit in 2 device(Linux and windows) and using eternal blue
I tried to scan first. and I always get a timeout. the port is 445
here are the options(Linux and windows are the same)

```
Module options (auxiliary/scanner/smb/smb_ms17_010):

   Name         Current Setting                                                            Required  Description
   ----         ---------------                                                            --------  -----------
   CHECK_ARCH   true                                                                       no        Check for architecture on vulnerable hosts
   CHECK_DOPU   true                                                                       no        Check for DOUBLEPULSAR on vulnerable hosts
   CHECK_PIPE   false                                                                      no        Check for named pipe on vulnerable hosts
   NAMED_PIPES  C:/metasploit-framework/embedded/framework/data/wordlists/named_pipes.txt  yes       List of named pipes to check
   RHOSTS       192.168.137.230                                                            yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.html
   RPORT        445                                                                        yes       The SMB service port (TCP)
   SMBDomain    .                                                                          no        The Windows domain to use for authentication
   SMBPass                                                                                 no        The password for the specified username
   SMBUser                                                                                 no        The username to authenticate as
   THREADS      1                                                                          yes       The number of concurrent threads (max one per host)


View the full module info with the info, or info -d command.
```

what is the matter? it sometimes refuses. 

```
[-] 192.168.137.230:445   - Rex::ConnectionTimeout: The connection with (192.168.137.230:445) timed out.
[*] 192.168.137.230:445   - Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

what is the problem? please help.

**Comment by adfoster-r7** [comment]
From the output you've provided - your target IP address is most likely wrong, or not accessible. Ensure your VMs/environment are setup correctly, and that the IPs are correct

**Comment by 12yearsoldcoder** [comment]
> From the output you've provided - your target IP address is most likely wrong, or not accessible. Ensure your VMs/environment are setup correctly, there's no firewalls present, and that the IPs are correct. If you're using virtual box, it is a common mistake to misconfigure the networking side of things for VMs to communicate successfully with eachother

I am not using VM using real computer. The IP is correct. Is this because of firewall?

**Comment by adfoster-r7** [comment]
I'm not sure what your local network setup would be, it might be firewalls, or your router might be configured to not allow computers to communicate with eachother, or other issues.

**Comment by 12yearsoldcoder** [comment]
> I'm not sure what your local network setup would be, it might be firewalls, or your router might be configured to not allow computers to communicate with eachother, or other issues.

OK. thx for replying 😀
