### ISSUE TITLE
Install fails citing GPG Error

### ISSUE THREAD

**Issue by edrapac** [rapid7/metasploit-framework#19077]
## Steps to reproduce

How'd you do it?

1. Follow the [documented steps to installing Metasploit on Linux](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html)
```
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall
```

2.  Receive the following error message
```
 curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && chmod 755 msfinstall && sudo ./msfinstall
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6144  100  6144    0     0  33081      0 --:--:-- --:--:-- --:--:-- 33210
Adding metasploit-framework to your repository list..Updating package cache..W: GPG error: http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CDFB5FA52007B954
E: The repository 'http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease' is not signed.
OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package metasploit-framework
```

## Were you following a specific guide/tutorial or reading documentation?

If yes link the guide/tutorial or documentation you were following here, otherwise you may omit this section.
Yes, the metasploit official docs: https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html

## Expected behavior

What should happen?
The installer should run successfully

## Current behavior

What happens instead?
The installation fails, citing a GPG error
### Metasploit version
N/A - I attempted this install on 10 - April - 2024 and 11 - April 2024

Running this on  Ubuntu 22.04.4 LTS "jammy"

**Comment by nrathaus** [comment]
The error you are seeing seems related to you not doing things as expected, see this old issue:
https://github.com/rapid7/metasploit-framework/issues/7336

It specifically talks about your gpg key issue (missing key)

**Comment by edrapac** [comment]
Hi @nrathaus Could you explain a bit more when you say I am not doing things as expected? As far as I understand it, the steps I outlined to reproduce are the steps outlined by the official documentation to install metasploit-framework

**Comment by nrathaus** [comment]
Can you verify that this: `/usr/share/keyrings/metasploit-framework.gpg`

Exists?

This is where the key is stored - it seems this step failed

**Comment by nrathaus** [comment]
We can close this one - there is no response from @edrapac

**Comment by adfoster-r7** [comment]
Maybe a regression introduced by https://github.com/rapid7/metasploit-omnibus/pull/192
