### ISSUE TITLE
Will rapid7 continue to release Debian style packages for Metasploit?

### ISSUE THREAD

**Issue by Trenix25** [rapid7/metasploit-framework#19074]
I am using Debian Linux 11.7.  I currently have the Metasploit package for March 25, 2024.  apt says there is one update available for March 26, 2024, but nothing after that.  Will rapid7 continue to release Debian style packages or have you stopped supporting that?  There should be a version available for March 27th or some time after that, but it isn't showing up.  It would be a real bummer if the March 25th package was the last one.  Should I be downloading the current version of Metasploit some other way instead?

My /etc/apt/sources.list.d/metasploit-framework.list file contains:
deb https://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main

Do I need to update this file to say something else instead?

**Comment by FalcoGer** [comment]
I would also like to know what is going on. `6.4.1+20240326102606~1rapid7-1` seems to be the latest version in the repository, which is now 2 weeks out of date. I really like the convenience of updating through the apt package manager and not fuff about with docker and the like. Is this a bug/problem and will there be new updates or is there some other method now to get the framework?

**Comment by nrathaus** [comment]
Any news?

**Comment by adfoster-r7** [comment]
> Will rapid7 continue to release Debian style packages for Metasploit?

Yes; will need to investigate this issue :+1:

**Comment by FalcoGer** [comment]
Just checked, got a new update for msf 6.4.4 in the apt repository.
Thank you.

**Comment by Trenix25** [comment]
Thank goodness.  I just updated to 6.4.4 released on April 12th.  Just out of curiosity, what time zone does the version use in the version number?  At what time of day in that time zone does rapid7 typically release the newest version?  I generally look for it after 1300 UTC.

**Comment by adfoster-r7** [comment]
> At what time of day in that time zone does rapid7 typically release the newest version? I generally look for it after 1300 UTC.

It runs daily at ~6 AM CDT but takes an hour or two to build; and sometimes a daily release fails due to upstream dependencies having network connectivity issues etc, but the build would get picked up again the next day. In this case - it died a lot more than once in a row

**Comment by adfoster-r7** [comment]
All the installers are up to date, should be able to close this now - thanks for reporting the issue :+1:
