### ISSUE TITLE
Unreachable URLs when trying to download Metasploit into Kalilinux image

### ISSUE THREAD

**Issue by IGNFIfortrue** [rapid7/metasploit-framework#19091]
Hello guys,

I am trying to install Metasploit in Kalilinux-rolling image, with 'apt install', but everytime there are a few unreachable URLS leads to build failure, here are some URLs I collected:
•	http://20.xxx.xxx.101/UserCheck/PortalMain?IID=A62B18BC-1C03-878D-1F03-DCC27CFE202F&origUrl=aHR0cDovL2thbGkuZG93bmxvYWQva2FsaS9wb29sL21haW4vci9ycGNzdmMtcHJvdG8vcnBjc3ZjLXByb3RvXzEuNC4zLTFfYW1kNjQuZGVi
•	http://20.xxx.xxx.101/UserCheck/PortalMain?IID=08856F48-0623-CCC9-DCB0-43F5A95033D9&origUrl=aHR0cDovL2thbGkuZG93bmxvYWQva2FsaS9wb29sL21haW4vci9ydWJ5LW5ldC10ZWxuZXQvcnVieS1uZXQtdGVsbmV0XzAuMi4wLTFfYWxsLmRlYg
•	http://20.xxx.xxx.101/UserCheck/PortalMain?IID=713CFFEC-B240-501D-57CE-11D6DF00708B&origUrl=aHR0cDovL2thbGkuZG93bmxvYWQva2FsaS9wb29sL21haW4vci9ydWJ5LWRlZmF1bHRzL3J1YnlfMy4xX2FtZDY0LmRlYg
•	http://20.xxx.xxx.207/UserCheck/PortalMain?IID=14FBAD0C-57FD-30CD-3077-7BBFDDA8DCA9&origUrl=aHR0cDovL2thbGkuZG93bmxvYWQva2FsaS9wb29sL21haW4vbi9uYXNtL25hc21fMi4xNi4wMS0xX2FtZDY0LmRlYg

May I ask if you know how to solve this issue? I use `curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall`

and found similar issue as well.

thanks a lot in advance,
Jin

**Comment by jmartin-tech** [comment]
A quick check suggests that you are attempting install on a system managed behind a [CheckPoint](https://www.checkpoint.com/) firewall that attempting to intercept or proxy the requests. This is not a Metasploit issue it is a restriction in the network your environment is connected to.

**Comment by adfoster-r7** [comment]
Will mark this as closed, as it looks like an issue with firewall config :+1:
