### ISSUE TITLE
Undocumented parameter in "notes" command

### ISSUE THREAD

**Issue by pwndad** [rapid7/metasploit-framework#19128]
## Summary

`notes -h `
states that we can use this example command 
`notes -S 'nmap.nse.(http|rtsp)'`
[Example documentation](https://github.com/search?q=repo%3Arapid7%2Fmetasploit-framework%20%22notes%20-S%20%27nmap.nse.(http%7Crtsp)%27%22&type=code)

But this flag is neither documented here
[missing documentation for search parameter](https://github.com/rapid7/metasploit-framework/blob/71ce80730095506a532fde58976cb4b2818a67c4/spec/lib/msf/ui/console/command_dispatcher/db_spec.rb#L176)
nor is it working correctly when used like this.

Acutally there seems to be code handling the `-S` parameter:
[existing code for handling undocumented parameter](https://github.com/rapid7/metasploit-framework/blob/71ce80730095506a532fde58976cb4b2818a67c4/lib/msf/ui/console/command_dispatcher/db.rb#L1278)

### Motivation

To be consistent between parameter documentation, examples and code behind.

## Steps to resolve this issue

EITHER
- Remove the example from usage and the corresponding code which handles `search_term`
OR
- Document the `-S` parameter additionally to the example and test it accordingly e.g. 

### Draft the doc

`-S, --search <filter>                  Search string to filter by`

### Open a pull request

Sorry for not proposing a PR but I could not figure out why the undocumented parameter is not working as expected.

**Comment by smcintyre-r7** [comment]
Fixed in #19129 which will be included in the next regularly scheduled release, 6.4.6 which should be posted tomorrow.
