### ISSUE TITLE
Grafana SQL Injection "feature"

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#19167]
## Summary

SQL Injection in Grafana, as a "feature", so likely won't get patched

### Basic example

https://fdlucifer.github.io/2024/04/22/grafana-sql-injection/ looks thorough enough to create a module with

### Motivation

Grafana is pretty popular

**Comment by HamidouTlili** [comment]
i want to work on this  as a cyber security project  , any further instructions or  informations except for this https://fdlucifer.github.io/2024/04/22/grafana-sql-injection/

**Comment by h00die** [comment]
@HamidouTlili are you still working on this?

**Comment by h00die** [comment]
"grafana team dose not think this is a vulnerability"

This is just abusing the SQL plugin to execute SQL commands. So I'm agreeing there isn't a vulnerability here. Closing.
