### ISSUE TITLE
msfvenom - parameter 'android:exported="true"' is missing for trojan definition - installation fails on android

### ISSUE THREAD

**Issue by RoseDeSable** [rapid7/metasploit-framework#19232]
Hi,
I build the trojan meterpreter with msfvenom in an app. If I try to install this new app by "adb install" on android, I receive the following message:

adb: failed to install Calculator_8.6 (612662282)_APKPure_meterpreter.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1440181840.tmp/base.apk (at Binary XML file line [0000079](https://bugs.kali.org/view.php?id=79)): com.google.android.calculator.nnvlj.Xnpjr: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

If I upload the app on my android and try to install it directly: the installation also fails.

The error obviously is, that in the manifest the additional entry 'android:exported="true"' is missing on this location:

```
<receiver android:label="Xnpjr" android:name="com.google.android.calculator.nnvlj.Xnpjr">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
    </intent-filter>
</receiver>
```

I can't analyse this more nearer, because I can de-compile but not compile the app with apktool. But this also is the case, if i de-compile and try to compile the original app without the trojan.

----

used versions:

-  metasploit-framework 6.4.9-0kali1
-  apktool 2.9.3  <== is used by path definition in msfvenom

apk

Best Regards
Rose

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
