### ISSUE TITLE
Error on database init

### ISSUE THREAD

**Issue by artemk92** [rapid7/metasploit-framework#19299]
## Steps to reproduce

1. Type 'msfdb init (or reinit)' 
2. Done! 

## Environment 

My distro is Kali Linux with 6.8.11-amd64 kernel running on VirtualBox VM. Same problem was on 6.5.0-kali kernel too. PostgreSQL's version is 16+260, all other packages are up to date. Metasploit had been installed from default kali repo and from repo provided in installation guide with no difference. 

## Expected behavior

Creating and initializing database 

## Current behavior

I'm prompted for postgres password but it immediately skips like someone pressed enter button. Obviously, it causes psql authentication error. After this program trying to create db user and nothing more happens

### Metasploit version

v6.4.16-dev-

## Additional Information
I've tried to follow dozens of instructions and manuals, reinstalled postgres and metasploit many times with no effect

**Comment by artemk92** [comment]
Fixed my problem by setting database up manually with following commands in app directory (after absolutely clean reinstallation of postgres and metasploit):
`bundle exec rake db:create`
`bundle exec rake db:migrate`
But command `msfdb init` still demonstrates weird behavior described above.  PostgreSQ` works fine, i can connect to db from terminal and other programs.

**Comment by tekwizz123** [comment]
@artemk92 Feel free to close this issue if resolved, otherwise @adfoster-r7 pinging you as this seems to be a resolved issue.

**Comment by adfoster-r7** [comment]
Looks like this can be closed, thanks!
