### ISSUE TITLE
`DidYouMean::SPELL_CHECKERS.merge` Deprecation

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#19316]
On a new kali install, using a git checkout of msf, and installed gems. 

While there are several issues which mention the issue in passing, none address it directly.

When running `msfconsole`, `msfdb`, the following output (warning) is observed:

`Calling 'DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call 'DidYouMean.correct_error(error_name, spell_checker)' instead.`

**Comment by adfoster-r7** [comment]
This will be resolved by a bundler version bump; which I think we're just about ready to support - we just need to tweak a few internal things first

Here's the placeholder [PR](https://github.com/rapid7/metasploit-framework/pull/19184) for the bundler bump it's closed for now, but will be re-opened soon

The R7 nightly installers are already bumped via [bundler.patch](https://github.com/rapid7/metasploit-omnibus/blob/0718cf40604e2d9688218003c4c3ced5624a39b3/config/patches/metasploit-framework/bundler.patch) and Kali can do the same if they want to apply this as one of their [custom gitlab patches](https://gitlab.com/kalilinux/packages/metasploit-framework/-/tree/c18a5c42a13cea1ce2f6943f8dff312c85307f33/debian/patches) ahead of time if they want to remove the noise sooner
