### ISSUE TITLE
I don't understand how to recompile from scratch android meterpreter from source code

### ISSUE THREAD

**Issue by Admin9961** [rapid7/metasploit-framework#19379]
I was looking at https://github.com/rapid7/metasploit-payloads/tree/master/java , where I found some docs for the Java/Android meterpreter, I opened a raw .apk payload in android studio but I can just debug... What I'm missins is: how do metasploit do generate the apk?

Let's say I don't want to use msfvenom, how to generate the payload without it? **Is the original  android met. source code just meant to work with msfvenom?** I can't even find the `build.gradle` dependancy

**Comment by timwr** [comment]
The options from msfvenom are inserted into the final apk here:

https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/payload/android.rb#L140
