### ISSUE TITLE
`searchlist=': Wrong argument format, neither String nor Array (ResolverArgumentError)

### ISSUE THREAD

**Issue by MickeyCho630** [rapid7/metasploit-framework#19516]
Windows11 Pro 64-bit system installation after the following error, how to solve it?
![image](https://github.com/user-attachments/assets/5ee69d92-7b0f-4a91-a8e7-65ba591d62c5)

**Comment by adfoster-r7** [comment]
Hi there; Could you comment out this line of code:

https://github.com/rapid7/metasploit-framework/pull/19474/files#diff-8ecd7f93790e21c32dd64d5c7150266d4c090da543f64e62a56b30dfae477eb3

And when msfconsole boots up, could you provide the output for `irb -e 'puts Win32::Resolv.get_resolv_info.inspect'` - example:

```
msf6 > irb -e 'puts Win32::Resolv.get_resolv_info.inspect'
[["localdomain"], ["192.168.123.2"]]
```

**Comment by MickeyCho630** [comment]
Does this return result mean that the configuration is correct?
![image](https://github.com/user-attachments/assets/04a963cf-ecd6-432b-a716-f9a32de04ecd)
![image](https://github.com/user-attachments/assets/d2338770-842a-4b30-bc52-906f727d22e5)

**Comment by MickeyCho630** [comment]
In Windows, some errors occur during the input of the command line but cannot be deleted. How can I solve this problem?

**Comment by adfoster-r7** [comment]
Thanks for the picture; that helps us a lot! :+1:

**Comment by adfoster-r7** [comment]
> some errors occur during the input of the command line but cannot be deleted

Sorry to hear that; Could you attach the output of the `debug` command - and let me know what version of windows you're using? it should be available via `systeminfo`, i.e. for my system the output would be:

```
C:\Users\vagrant>systeminfo

Host Name:                 WINDEV
OS Name:                   Microsoft Windows Server 2016 Standard Evaluation
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
```

And whether or not you're running via WSL or similar

**Comment by MickeyCho630** [comment]
Thank you for your answer. I have found the cause of this problem. The application protection of Windows real-time protection or security software may affect this software.
`Host name: THINKBOOK
OS name: Microsoft Windows 11 Professional
OS version: 10.0.22631 Build 22631 is temporarily missing
OS Manufacturer: Microsoft Corporation
OS configuration: Independent workstation
OS build type: Multiprocessor Free`
![image](https://github.com/user-attachments/assets/02f5d593-1949-40b8-8905-665379bcdda3)
