### ISSUE TITLE
Refusal to install

### ISSUE THREAD

**Issue by OMAR-ALDOKHINI** [rapid7/metasploit-framework#19556]
E: Unable to locate package metasploit

**Comment by bcoles** [comment]
Try `metasploit-framework`

**Comment by Gazmancyber** [comment]
Unable to locate package metasploit

**Comment by bcoles** [comment]
Try `metasploit-framework`

**Comment by Gazmancyber** [comment]
Thank you for your response

**Comment by Gazmancyber** [comment]
how to install termux on my pc

**Comment by bcoles** [comment]
> how to install termux on my pc

This is the Metasploit issue tracker. [Termux](https://termux.dev/en/) software is unrelated. You may want to start here: https://wiki.termux.com/wiki/Main_Page
