### ISSUE TITLE
system make ' failed Metasploit & Oracle (ruby-oci8)

### ISSUE THREAD

**Issue by sanu-on-kali** [rapid7/metasploit-framework#19655]
_**msf > use auxiliary/admin/oracle/oracle_login am using this module i got this**_

msf6 auxiliary(admin/oracle/oracle_login) > run

[-] Failed to load the OCI library: cannot load such file -- oci8
[-] Try 'gem install ruby-oci8'
[*] Auxiliary module execution completed
[-] Failed to load the OCI library: cannot load such file -- oci8
[-] Try 'gem install ruby-oci8'[*] Auxiliary module execution completed

_**then i did installed ruby-oci8**_

msf6 > gem install ruby-oci8
[*] exec: gem install ruby-oci8

msf6 > sudo gem install ruby-oci8
[*] exec: sudo gem install ruby-oci8

[sudo] password for kali:
Fetching ruby-oci8-2.2.14.gem
Building native extensions. This could take a while...
Successfully installed ruby-oci8-2.2.14
Parsing documentation for ruby-oci8-2.2.14
Installing ri documentation for ruby-oci8-2.2.14
Done installing documentation for ruby-oci8 after 0 seconds
1 gem installed

_**but still that module not works**_ 

msf6 auxiliary(admin/oracle/oracle_login) > run

[-] Failed to load the OCI library: cannot load such file -- oci8
[-] Try 'gem install ruby-oci8'
[*] Auxiliary module execution completed

_**so decided to install it manually**_

[]https://leonjza.github.io/blog/2014/08/17/kali-linux-oracle-support/(url) _**used this page**_

_**last stage make ///how to ride this error**_ ?

ruby -w setup.rb setup
---> lib
---> lib/oci8
<--- lib/oci8
---> lib/dbd
<--- lib/dbd
<--- lib
---> ext
---> ext/oci8
make
make[1]: Entering directory '/opt/oracle/ruby-oci8-ruby-oci8-2.1.7/ext/oci8'
compiling attr.c
In file included from attr.c:7:
oci8.h:215:9: warning: "ALWAYS_INLINE" redefined
215 | #define ALWAYS_INLINE inline attribute((always_inline))
| ^~~~~~~~~~~~~
In file included from /usr/include/ruby-3.1.0/ruby/defines.h:73,
from /usr/include/ruby-3.1.0/ruby/ruby.h:25,
from /usr/include/ruby-3.1.0/ruby.h:38,
from oci8.h:10:
/usr/include/ruby-3.1.0/ruby/backward/2/attributes.h:85:10: note: this is the location of the previous definition
85 | # define ALWAYS_INLINE(x) RBIMPL_ATTR_FORCEINLINE() x
| ^~~~~~~~~~~~~
attr.c: In function ‘oci8_get_rowid_attr’:
attr.c:63:22: error: passing argument 1 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
63 | return rb_ensure(get_rowid_attr, (VALUE)&arg, rowid_ensure, (VALUE)&arg);
| ^~~~~~~~~~~~~~
| |
| VALUE ()(rowid_arg_t ) {aka long unsigned int ()(rowid_arg_t )}
In file included from /usr/include/ruby-3.1.0/ruby/ruby.h:40:
/usr/include/ruby-3.1.0/ruby/internal/iterator.h:425:25: note: expected ‘VALUE ()(VALUE)’ {aka ‘long unsigned int ()(long unsigned int)’} but argument is of type ‘VALUE (*)(rowid_arg_t )’ {aka ‘long unsigned int ()(rowid_arg_t )’}
425 | VALUE rb_ensure(VALUE (b_proc)(VALUE), VALUE data1, VALUE (e_proc)(VALUE), VALUE data2);
| ~~~~~~~~^~~~~~~~~~~~~~
attr.c:63:51: error: passing argument 3 of ‘rb_ensure’ from incompatible pointer type [-Wincompatible-pointer-types]
63 | return rb_ensure(get_rowid_attr, (VALUE)&arg, rowid_ensure, (VALUE)&arg);
| ^~~~~~~~~~~~
| |
| VALUE ()(rowid_arg_t ) {aka long unsigned int ()(rowid_arg_t )}
/usr/include/ruby-3.1.0/ruby/internal/iterator.h:425:62: note: expected ‘VALUE ()(VALUE)’ {aka ‘long unsigned int ()(long unsigned int)’} but argument is of type ‘VALUE ()(rowid_arg_t )’ {aka ‘long unsigned int ()(rowid_arg_t *)’}
425 | VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE data2);
| ~~~~~~~~^~~~~~~~~~~~~~
make[1]: *** [Makefile:246: attr.o] Error 1
make[1]: Leaving directory '/opt/oracle/ruby-oci8-ruby-oci8-2.1.7/ext/oci8'
'system make ' failed
Try 'ruby setup.rb --help' for detailed usage.
make: *** [Makefile:10: build] Error 1

**Comment by adfoster-r7** [comment]
Does this documentation help at all? https://github.com/rapid7/metasploit-framework/blob/4a13b09767c3f7f91b0b0169e53dad99ff9fa504/docs/metasploit-framework.wiki/How-to-get-Oracle-Support-working-with-Kali-Linux.md

It's potentially be outdated and needs a refresh, but it might point you in the right direction

**Comment by h00die** [comment]
I just updated the instructions, they were more or less correct, just needed updated version numbers and URLs. See #19773

My guess is you missed https://github.com/rapid7/metasploit-framework/blob/df0aa98e8bf0d4a1a797e3c8f2f3c567435221a5/docs/metasploit-framework.wiki/How-to-get-Oracle-Support-working-with-Kali-Linux.md?plain=1#L88
