### ISSUE TITLE
msfconsole creds command cannot create Login objects

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/metasploit-framework#3740]
See #3728 for some discussion.

**Comment by shuckins-r7** [comment]
@jlee-r7 This should be fairly straightforward to add to the creds command based on the recent changes to report_auth_info: https://github.com/rapid7/metasploit-framework/pull/4535/files#diff-bc11ab19537f682411e222eeb1e2ac53R223

**Comment by todb-r7** [comment]
I marked this resolved, @jlee-r7 nope'd that, with:

> No, you still can't create Metasploit::Credential::Logins; there's still no way to link a user/pass (i.e. Metasploit::Credential::Core) to an Mdm::Service from msfconsole.

And now @shuckins-r7 is assigned. What do we need to do now to get this moving? Shall I just resolve this again? Probably could use a proper use case step-through to test this anyway.

**Comment by shuckins-r7** [comment]
@todb-r7 I don't have any updates for you here, feel free to take it away. Will likely get resolved faster than going through other prioritization routes.

**Comment by jlee-r7** [comment]
My main issue is that I don't have a great way to deal with this from a UX perspective. The `creds` command is overloaded now with the new model and really has too many jobs; it has to deal with `Metasploit::Credential::Core`s, all of the various `Metasploit::Credential::Private`s and `Metasploit::Credential::Public`s, and `Metasploit::Credential::Login`s.

One way to do it is just to create a new command for `Login`s and only show `Core`s with `creds`.

**Comment by darkbushido** [comment]
can we close this? #7892 landed and it lets you create logins with the creds command

**Comment by busterb** [comment]
Yep.
