### ISSUE TITLE
Framework should call post modules, not scripts, for console commands

### ISSUE THREAD

**Issue by hdm** [rapid7/metasploit-framework#3792]
A number of msfconsole commands still depend on scripts, not post modules, to implement their functionality. This is inconsistent with our advice to contributors and has resulted in usability issues for commands like `sessions -u` since there is no way to pass options into the script (LHOST, etc). Any use of scripts within Framework should be moved to post modules.

**Comment by bcook-r7** [comment]
I'll own this for now.

**Comment by todb-r7** [comment]
@bcook-r7 is still owning this. :)

**Comment by hmoore-r7** [comment]
@bcall-r7 is still owning things :)

**Comment by egypt** [comment]
`sessions -u` uses `post/multi/manage/shell_to_meterpreter` now. I don't know of any other places where a console command uses a script.

**Comment by wvu-r7** [comment]
#4581 is unfixed.
