### ISSUE TITLE
Save workspace

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#3804]
Allow "save" to save the currently used workspace to allow restarting msfconsole without having to remember to change workspaces

**Comment by todb-r7** [comment]
@wvu-r7 I choose you! This seems like a no brainer, just save the current workspace to the usual ~/.msf4 file.

**Comment by wvu-r7** [comment]
:(

**Comment by todb** [comment]
I suppose recovering the workspace is the real trick, and handling the case
where the workspace isn't available anymore.

-- 
Sent from a tiny computer.

**Comment by wvu-r7** [comment]
@jlee-r7 showed me the ```WORKSPACE``` datastore option, but it's really not as ideal as it sounds.

**Comment by todb-r7** [comment]
bumping this. Not *quite* as easy as it sounded but still quite doable.

**Comment by wvu-r7** [comment]
Well, that was kinda easy. :/
