### ISSUE TITLE
Need rspec for Msf::Util::EXE without magic file

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3807]
*This issue was [RM8723](https://dev.metasploit.com/redmine/issues/8723), filed by @totaldowner*

This was attempted to be fixed in #2793, but alas, the magic file is still wanging up on various operating systems.

The most recent symptom from @shuckins-r7 was:

````
Msf::Util::EXE ................................F..........................................................................
  1) Msf::Util::EXE.to_executable_fmt with platform=windows returns an executable when given arch=x86_64, fmt=loop-vbs
     Failure/Error: verify_bin_fingerprint(format_hash, bin)
       expected: /ASCII/
            got: "/dev/stdin: YAC archive data\n" (using =~)
       Diff:
       @@ -1,2 +1,2 @@
       -/ASCII/
       +/dev/stdin: YAC archive data

     # ./spec/support/shared/contexts/msf/util/exe.rb:91:in `verify_bin_fingerprint'
     # ./spec/lib/msf/util/exe_spec.rb:69:in `block (6 levels) in <top (required)>'
````

**Comment by bcook-r7** [comment]
I think the best bet is to just add a deterministic seed to the payload generator and ensure that for a given  input, we get the same output. That does a better job of checking for regressions anyway. If someone makes a change to the payloads that cause this to break and it isn't in error, the payloads need to be tested live anyway.

**Comment by todb-r7** [comment]
Let's pretend we're a really crappy anti-virus and just signature on easy stuff for now, and enhance over time. Basically, I just want to know that when you're generating an EXE, you're not actually generating a PowerShell file or something.

**Comment by bcook-r7** [comment]
We fixed the basic issue by deleting the test, will make a new issue describing what we want.
