### ISSUE TITLE
MSSQL login and command exec should support multiple instances and clusters

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3810]
_This issue was [RM8817](https://dev.metasploit.com/redmine/issues/8817), filed by @todb-r7 on behalf of @recrudesce_

Came up on a Twitter complaint from @recrudesce: https://twitter.com/recrudesce/status/481033295418109952
After a brief chat on IRC, it looks like our MSSQL mixin doesn't do much at all with different instances, or handle cluster mappings very well. It may be high time for a rework to handle more complex MSSQL installations.

**Comment by bcook-r7** [comment]
We would need an MSSQL environment first in order to test this.

**Comment by shuckins-r7** [comment]
@bcook-r7 We definitely have one of those, hit me up if you need details.

**Comment by todb-r7** [comment]
I need to come up with a customer/user who actually wants this? This feature request has been hanging out here forever with not a lot of :+1: action. I think the request is valid, but I'm having a hard time prioritizing this against other features.

So... that's my action item.

**Comment by todb-r7** [comment]
Still ought to do this. Well, someone should, anyway. :) If it's a huge missing piece you'd think some kind person from open source land would volunteer to take this on.
