### ISSUE TITLE
Defaults defined with "DefaultOptions" don't come back after set/unset

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3811]
_This issue was [RM8814](https://dev.metasploit.com/redmine/issues/8814), filed by @jlee-r7_

Repro:
-  use windows/browser/ms09_072_style_object
- set HTTP::compression \* see "gzip" 
- set HTTP::compression deflate
- unset HTTP::compression
- show evasion

See that HTTP::compression has become "none" instead of going back to the default of "gzip"

**Comment by bcook-r7** [comment]
cool! let's do it!

**Comment by wchen-r7** [comment]
yeah srsly

**Comment by wchen-r7** [comment]
Well so I started trying to write code for this, and then I realized you can't actually reset a datastore option if it's not originally from the module. Like for example, if the option is registered by HttpServer, that information won't be found in active_module, but I think that's the only thing you get to work with. Does anybody have any idea how to do that? I think you have to somehow find a way to inspect all the mixins a module is using, and then find last registered option. I don't think you can do that with active_module.

**Comment by limhoff-r7** [comment]
@wchen-r7, you should be able to use module_instance.class.ancestors to get the order of Module and Class ancestors in-order to check for their version of the registered option.  The first ancestor with a default value should be the default value to use.

**Comment by limhoff-r7** [comment]
Ok, so that won't work because register_option stores the option at the instance level and not on the owner (self.class).

**Comment by hmoore-r7** [comment]
+1 for a new reset command (including reset all / resetg all).

**Comment by mubix** [comment]
++1

-- 
Sent from botnet
