### ISSUE TITLE
x64 Service Payloads Not Working

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3819]
*This issue was [RM8811](https://dev.metasploit.com/redmine/issues/8811), filed by @Meatballs1*

Originally suspected to be a result of #2657. Followup comment from @Meatballs1 was:

> I don't think this is a result of that pull request. x64 service payloads appear to work fine on Windows2k8, but fail on 2k12. PTR Truncation? Cant see anything in the source...

**Comment by bcook-r7** [comment]
Please reopen if the problem still exists @Meatballs1.
