### ISSUE TITLE
Client Side Zlib compression

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3820]
*This issue was [RM8806](https://dev.metasploit.com/redmine/issues/8806), filed by Stu Kennedy*

> Client side compression of files and folders on a target for quicker downloading. I'm sure there are many other benefits of having this too. I have had a play at trying to implement this feature because the ZLib libraries are already included in metasploit/meterpreter but still haven't been successful.

The resounding opinion today is that this does, in fact, exist, and we need to double check.

**Comment by bcook-r7** [comment]
Sounds like a good idea to me.

**Comment by todb-r7** [comment]
This is already implemented. Huzzah!
