### ISSUE TITLE
nmap parser doesn't parse "SSL/HTTPS?" output

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3821]
*This issue was [RM8805](https://dev.metasploit.com/redmine/issues/8805), filed by @wchen-r7 on behalf of @sho-luv*

The following nmap xml example shows a Apache web service running on port 443 with SSL, but the name parameter doesn't say "https", it says "http"

```xml
<port protocol="tcp" portid="443"><state state="open" reason="syn-ack" reason_ttl="52"/><service name="http" product="Apache httpd" tunnel="ssl" method="probed" conf ="10"><cpe>cpe:/a:apache:http_server</cpe></service></port>
```

If you import that to Metasploit it'll be treated as HTTP and not HTTPS.

**Comment by bcook-r7** [comment]
@todb-r7 just noting that this survived to the next triage meeting :)

**Comment by todb-r7** [comment]
Great.
