### ISSUE TITLE
Metasploit Framework should prompt to update

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3824]
*This issue was [RM8781](https://dev.metasploit.com/redmine/issues/8781), originally filed by @ckirsch-r7*

During the SVN era of Metasploit Framework, the product prompted whether the user wanted to update when the software was more than 30 days out of date, e.g.

> Would you like to update Metasploit Framework now? (Y/n)

This feature seems to have dropped out of the release since the move to GitHub. I recommend we reinstate it and reduce the grace period to 7 days.

----

There is some dead code that still relies on SVN:

````
$ grep -r "days" .
./msf/core/framework.rb:  RepoUpdatedDays     = ::Msf::Util::SVN.days_since_update
./msf/util/svn.rb:  def self.days_since_update
./msf/util/svn.rb:    diff = self.days_since_update
./msf/util/svn.rb:        "%red#{diff.to_i} days ago%clr" 
./msf/util/svn.rb:        "#{diff.to_i} days ago" 
````

This should be removed as well.

**Comment by bcook-r7** [comment]
Maybe we should just delete the old svn code and move on.

**Comment by FireFart** [comment]
would also be a good idea to check for a `.noupdate` file or smth in the root to supress this warning. This way kali and other distros can disable the checking feature so you will always install their packages

**Comment by bcook-r7** [comment]
We're thinking about just implementing a local timer that reminds you to check for updates up to 7 days since the last time msfupdate was run, or the first time msfconsole was started. This should be disabled from a pro context perhaps.

**Comment by bcook-r7** [comment]
The wrapper code in the omnibus packages does this after a couple of weeks:

https://github.com/rapid7/metasploit-omnibus/blob/master/config/templates/metasploit-framework-wrappers/msfwrapper.erb#L80

Sufficient? Maybe we just need to cleanup the svn code and can call this a day.

**Comment by bcook-r7** [comment]
I'm going to call the omnibus check good enough for this.
