### ISSUE TITLE
There should be a 'MSF' identifier for modules to reference

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3826]
*This issue was [RM8708](https://dev.metasploit.com/redmine/issues/8708), originally filed by @wchen-r7*

`reference.rb` should add a 'MSF' for Metasploit. Not sure if this should go to the pull request, security street, redmine, or whatever. Open for discussion. Proof that even @hmoore-r7 is waiting for this to be implemented: https://github.com/rapid7/metasploit-framework/commit/ffd91793b90e5f872073718ff3cb5f2da8be2575

**Comment by bcook-r7** [comment]
We have decided to table this.
