### ISSUE TITLE
Rename root directory msf4 or simply msf instead of msf3

### ISSUE THREAD

**Issue by tanawts** [rapid7/metasploit-framework#3842]
The Metasploit framework has been at version 4 for -years- now yet the tarball still unzips to msf3... Can we please make the minor change of updating the root directory to extract to msf or msf4 rather than continuing to use msf3?

I understand that its a commercial product downstream which neatly bundle and build on the behalf of the customer base, but this is a minor gripe, but those of us who maintain ports of this project -do- have to see msf3 every time we work on the code.

Thank you.

**Comment by todb-r7** [comment]
So, the tarball download is no longer available on http://www.rapid7.com/products/metasploit/download.jsp , and the GitHub release tarballs now expand to whatever the version number is.

Right now, only the binary installers use `/opt/.*/msf3` afaik. I'll bug them to change this some day.
