### ISSUE TITLE
Modules should not alter their own datastores without normalization

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3853]
*This issue was [RM7234](https://dev.metasploit.com/redmine/issues/7234), originally filed by @todb-r7*

Currently, there are 98 instances of modules that modify the datastore at runtime, according to msftidy:
````
tools/msftidy.rb modules/ | grep datastore > datastore.txt ; cat datastore.txt | wc -l
98
````

This is asking for trouble in many cases, because it means that modules are getting values stuffed in their datastores that may or may not have been normalized. Also, there are concerns that altering a datastore option at runtime will have unexpected effects on modules that run after the datastore altering.

There should be a way to do this kind of assignment that guarantees normalization (there are several OO strategies to chose from), or developers should be prohibited from altering the datastore at runtime altogether.

See PRs #2300 and #3841, as well as @wchen-r7's [documentation](https://github.com/rapid7/metasploit-framework/wiki/How-to-use-datastore-options#modifying-datastore-options-at-run-time).

**Comment by bcook-r7** [comment]
Module should possibly make copies of options. @wchen-r7 has ideas

**Comment by wvu-r7** [comment]
https://gist.github.com/wvu-r7/f78bb0d5d2370a207eeb

**Comment by hmoore-r7** [comment]
The framework already "forks" the module during each run (replicant), so @wvu-r7's gist is working as expected. The problem with using the datastore as a scratch pad is that it doesn't normalize the values. For example:
```
self.datastore['RPORT'] = "GiantBanana"
```

This will break all of the code that depends on a Fixnum.

**Comment by wvu-r7** [comment]
Aha, totally fair. Thanks, @hmoore-r7.

**Comment by todb-r7** [comment]
So it sounds to me like this can be solved by writing some setters and getters on changing the datastore at runtime. That way you can be sure that your datastore values are going to be typed.

**Comment by hmoore-r7** [comment]
Or just dont use the datastore as a scratch pad =)

**Comment by todb-r7** [comment]
If we enforce typing and the use of a real setter, then we can keep the msftidy check -- direct assignments will be no bueno, but something like `set_datastore(:RHOST, 1234)` will be acceptable.

If we just say it's bad code and is going to screw up modules unless the type matches, we can drop the msftidy check and just use committer eyeballs to make sure the datastore isn't being abused.

I prefer the automated solution; but my main goal is to get the msftidy warnings to zero so we can move forward on failing builds that introduce msftidy warnings.

**Comment by wvu-r7** [comment]
IMHO, this is the nature of the beast with a dynamically typed language like Ruby.
