### ISSUE TITLE
Some of the encoders refer to an unavailable exception class "InvalidPayloadSizeException"

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3861]
*This issue was [RM8801](https://dev.metasploit.com/redmine/issues/8801), originally filed by @jvennix-r7*

Grep for `InvalidPayloadSizeException`, it is defined as a nested class but is referenced ~4 unrelated modules. Looks like copypasta.

**Comment by wchen-r7** [comment]
This is no longer an issue:

https://github.com/rapid7/metasploit-framework/search?utf8=%E2%9C%93&q=InvalidPayloadSizeException
