### ISSUE TITLE
HttpClient should remember my cookie

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3877]
_This issue was [RM8706](https://dev.metasploit.com/redmine/issues/8706), originally filed by @wchen-r7_

When a cookie is set by the server, I want HttpClient to remember it. That way in my module I don't have to manually extract it, and then set it. Can get annoying.

**Comment by adfoster-r7** [comment]
This functionality is implemented nowadays with the http cookiejar support that was added https://github.com/rapid7/metasploit-framework/blob/ad8243706765460fb513ac294e57df286a23da66/docs/metasploit-framework.wiki/How-to-Send-an-HTTP-Request-Using-HttpClient.md#cookies--cookiejars
