### ISSUE TITLE
PsExec with local account credentials in a windows domain

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3878]
*This issue was [RM8698](https://dev.metasploit.com/redmine/issues/8698), originally filed by Donny Maasland*

First of all, this is the test setup used to recreate this issue:
- Windows Domain
- 2008R2 servers and functional level
- Using (renamed) local admin account credentials on any server but the domain controller
- No other GPO settings modified

Problem:

Using local administrative credentials with a psexec module (psexec, psexec_psh, psexec_command)on a server 2008 r2 server joined to a domain fails with STATUS_LOGON_FAILURE. Using an account from the domain works just fine.
How to replicate (Do this on any server joined to the domain, except the domain controller):

- Verify the credentials work with the smb_login module, setting just SMBUser and SMBPass. This returns a successful login.
- Use one of the psexec modules on the server with local administrative credentials. This will fail with STATUS_LOGON_FAILURE. Setting the domain to either "", ".", "WORKGROUP" or "<Victim IP>" makes no difference. On a side note, his module seems to be missing settings for enabling NTLMv2 (show advanced, smb_login does show these settings). Then try with an administrative domain account, this will work just fine.
- Use another psexec implementation with same same credentials. I've used impackets "psexec.py" successfully with SMBDomains "<empty>", ".", "WORKGROUP" or "Victim IP".

----

[RM8698](https://dev.metasploit.com/redmine/issues/8698) also has several pcaps attached.

**Comment by Meatballs1** [comment]
Looking at the PCAPs the two differences are:

Impacket negotiates SMBv2, Metasploit SMBv1
Impacket negotiates NTLMv2, Metasploit NTLMv1

Its probably down to the NTLM version. Win2k8 R2 will default to use only NTLMv2 auth - but 2k8 R2 Domain controllers will allow LM, NTLM, NTLMv2 still. The domain user approach probably works due to that?

**Comment by Meatballs1** [comment]
I think NTLMv2 is being correctly negotiated now... so probably fixed.

**Comment by egypt** [comment]
Sounds like this was resolved some time ago.
