### ISSUE TITLE
enum_cred_store x64

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#3916]
Thinks there are a million stored creds. Probably pulling back a QWORD for the count and needs truncating :|

```[*] 4702111233380188160 credentials found in the Credential Store```

**Comment by bcook-r7** [comment]
What a weird number. 2**62.02

**Comment by bcook-r7** [comment]
If we treat a PDWORD as a PDWORD, it works as expected:

```
--- a/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb
+++ b/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb
@@ -318,10 +318,7 @@ class DLL
       buffer = rec_out_only_buffers[buffer_item.addr, buffer_item.length_in_bytes]
       case buffer_item.datatype
         when "PDWORD"
-          # PDWORD is treated as a POINTER
-          return_hash[param_name] = buffer.unpack(native).first
-          # If PDWORD is treated correctly as a DWORD
-          return_hash[param_name] = buffer.unpack('V').first if return_hash[param_name].nil?
+          return_hash[param_name] = buffer.unpack('V').first
         when "PCHAR"
           return_hash[param_name] = asciiz_to_str(buffer)
         when "PWCHAR"
```

**Comment by Meatballs1** [comment]
Yarp but that breaks all the modules that rely on it as a POINTER :)

**Comment by OJ** [comment]
My feeling is that enumeration of the store belongs on the Meterp side. It'd avoid the chattiness of the module and (hopefully) avoid the issue completely.

Danger here I guess is that if this module is busted, there's gotta be others!

**Comment by bcook-r7** [comment]
There are 'only' 62 modules using railgun. I'll assume it won't be too quixotic to audit them all :)

**Comment by jvazquez-r7** [comment]
Also, the underlying issue is being tracked here: #4455
