### ISSUE TITLE
Msftidy should generaate a warning when Gemfile* is changed

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3957]
This is almost never intended, so msftidy should check to see if the Gemfile has been changed. It shouldn't error and halt the commit, though, because occasionally it _is_ intended.

For background, see: https://github.com/rapid7/metasploit-framework/pull/1831#issuecomment-18813735 among others.

**Comment by jmartin-r7** [comment]
We tend to handle Gemfile changes well in review now so closing this.
