### ISSUE TITLE
CTRL+arrows key not moving cursor in the msfconsole

### ISSUE THREAD

**Issue by maaaaz** [rapid7/metasploit-framework#3997]
The CTRL+arrows (left/right etc.) Bash shortcuts are convenient to move your cursor backward or forward in an expression.
It would great whether the msfconsole could properly handle them instead of printing the textual keybinding.

Step to reproduce:
1. Type an expression in your msfconsole, like `set RHOSTS file://my/local/file`
2. Realize you made a mistake in your path, and you would like to go backward
3. Press CTRL+LEFT ARROW
4. See `set RHOSTS file://my/local/file;5C` in your console
5. Rage

Cheers.

**Comment by wvu-r7** [comment]
I just use Ctrl/Alt-B/F.

**Comment by egypt** [comment]
Making ruby-readline work the same as real readline is a pretty hairy task that I really don't think is worth the effort involved. As a workaround, you can start `msfconsole` with the `-L` flag to use your system's readline, which makes (almost) everything work just like in bash.
