### ISSUE TITLE
HTTP modules should always provide (and use) a URI or similar datastore option

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#4007]
See #3982/#3983 for some of the history, but `HttpClient` does not provide a standard option for the user to specify a URI.  This results in at least the following problems:
- Module writers end up picking a different datastore option for configuring the URI, like `TARGET_URI`, `TARGETURI` or `PATH`
- Some modules hardcode the URI, making it a pain for users to change it (they have to modify the module)
- Some modules appear to try to use a URI datastore option but fail to use it consistently throughout the module

My two main reasons for filing this and wanting to see it fixed are:
- Consistency
- Flexibility.  As discussed with @wchen-r7 in the above listed items, while the majority of the time the user won't need to change the default URI, oftentimes the target applications/servers can be behind a proxy of some sort which can change the default URI, making it impossible to target these installations with msf without modifying each module individually

**Comment by egypt** [comment]
@wchen-r7 @jhart-r7 Does our current approach with `TARGETURI` solve this ticket?

**Comment by jhart-r7** [comment]
@egypt sorry, unknown.   what has changed wrt `TARGETURI` since this was opened?  I've been out of the loop here so may need to rely on @wchen-r7.

**Comment by wchen-r7** [comment]
Nothing much has changed. We have been registering TARGETURI from the module's level, and then we try enforce this writing style during code review. This documentation explains how we want people to do it: https://github.com/rapid7/metasploit-framework/wiki/How-to-Send-an-HTTP-Request-Using-HTTPClient#uri-parsing

**Comment by fsacer** [comment]
as this is more of a guideline this issue can probably get closed @wvu-r7
