### ISSUE TITLE
none of the darwin templates have source

### ISSUE THREAD

**Issue by kernelsmith** [rapid7/metasploit-framework#4017]
```
$ ls data/templates/ | grep darwin
template_armle_darwin.bin
template_ppc_darwin.bin
template_x64_darwin.bin
template_x86_darwin.bin

$ ls data/templates/src/
elf
msi
pe
```

I blame @hmoore-r7

**Comment by hdm** [comment]
I am pretty sure its the same C template for all of these

**Comment by timwr** [comment]
This one https://github.com/rapid7/metasploit-framework/blob/master/data/templates/src/pe/exe/template.c ?
I'm not sure because the binary appears to call mmap and memcpy.

**Comment by kernelsmith** [comment]
Wow, talk about a blast from the past

**Comment by hdm** [comment]
It looks like the source is indeed missing (730b27eed1611f4bd1c0248f7de3466067dfdf02), a bit late to fix now though (11 years ago).

**Comment by timwr** [comment]
Yeah it's probably a bit late (and pointless) to fix this, for completeness the following source can be used to build it
https://github.com/rapid7/metasploit-framework/blob/master/data/templates/template_x64_darwin.bin

```
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/mman.h>

char payload[8000] = "PAYLOAD:";
int main() {
    void *ptr = mmap(0, sizeof(payload), PROT_EXEC | PROT_WRITE | PROT_READ, MAP_ANON | MAP_PRIVATE, -1, 0);
    if (ptr == MAP_FAILED) {
        return;
    }
    memcpy(ptr, payload, sizeof(payload));
    int (*sc)() = ptr;
    sc();
    return 0;
}
```
I'd be interested if someone has an M1 mac and wants to test an arm64 meterpreter.

**Comment by kernelsmith** [comment]
@timwr I might get access to an M1 in the next month or so if you don't find anyone to test the arm64 meterpreter
