### ISSUE TITLE
Some mixins don't provide for SSL23

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#4027]
While reviewing #4024, the autonegotiate SSL option for the various SSL mixins, it was noticed that some mixins don't provide for SSL23 as an option.

This should be remedied, because on many (but not all) systems, SSL23 will really try TLSv1, SSLv3, then SSLv2. However, this does not impact the effectiveness of #4024, the Poodle-inspired fix; it's unrelated, possibly missing, functionality.

**Comment by bcook-r7** [comment]
We fixed this a couple of months ago. Will lookup the commit refs in a bit.
