### ISSUE TITLE
Changed/missing options in creds command

### ISSUE THREAD

**Issue by swtornio** [rapid7/metasploit-framework#4033]
creds used to have the -S search option for all fields. The -u and -p options have replaced some of the functionality, but the plaintext search on private_type doesn't seem to be available, to display only Password or NTLM hash entries.

Also, creds -h does not list -d as an option. One of the most useful manipulations of credentials is to eliminate machine accounts, and it can be accomplished with "creds -u \\\$ -d" but that can't be determined from the help text. Adding an entry for -d would help, and adding the specific command to delete machine accounts to the examples would make it obvious.

**Comment by shuckins-r7** [comment]
MSP-11999 added

**Comment by shuckins-r7** [comment]
We've got some duplication. This issue encompasses:
 * Search by private type - this has been fixed: https://github.com/rapid7/metasploit-framework/pull/4539
 * help desc update - this was already a bug: https://github.com/rapid7/metasploit-framework/issues/3790

Going to close this one out accordingly.
