### ISSUE TITLE
Link to vulnerable VMs is down in users_guide_4.3.pdf

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4090]
Under "Downloading the Vulnerable VMs" (page 9), the torrent link is down. Needs an update.

Metasploitable2 can be found here: http://sourceforge.net/projects/metasploitable/files/Metasploitable2/

If there's already something in progress, please feel free to reject this issue. Thanks.

**Comment by tdoan-r7** [comment]
Broken link is fixed here: https://help.rapid7.com/metasploit/#getting-started/setting-up-test-env.html
