### ISSUE TITLE
LHOST. SRVHOST, and other "local IP address" datastore options should pre-populate

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#4121]
PR #3633 from @iquaba was an attempt at solving this, but it doesn't seem to be mergable in its current form. I'd *like* to use network_interfaces to maintain some backwards compat with 1.9, but that's kinda silly since 1.9.x goes away forever after February 2015.

**Comment by wvu-r7** [comment]
Should be a one-word change to update ```LHOST``` tab completion for ```SRVHOST```. Will PR.
