### ISSUE TITLE
Use of autoload is neutered with "include" that immediately follows.

### ISSUE THREAD

**Issue by jduck** [rapid7/metasploit-framework#4195]
@limhoff-r7 et al,

Why do we use "autoload" in these cases instead of just "require" ?

PS. has there been any progress made on reducing the number of things in $: ? In my experimentation this is the single largest cause for slow down due to tons of unnecessary/failing system calls. If you want, I can create a separate ticket to track an effort to improve the situation here.

**Comment by busterb** [comment]
I'm looking forward to a PR that implements something here. In the mean time, closing.
