### ISSUE TITLE
Port Metasploit Pro's workspace zip to Framework

### ISSUE THREAD

**Issue by trevrosen** [rapid7/metasploit-framework#4199]
Extend db_export/import to support the workspace zip format previously only available in Metasploit Pro/Express.

This zip contains a mixture of XML, CSV, and file data. This will accommodate "one-shot" import/export of 4.10+ credentials data as well as all other data persisted in legacy import/export formats.

**Comment by bcook-r7** [comment]
I think this would be useful @lsato-r7
