### ISSUE TITLE
Credentials exported from pre-4.10 can't be reimported

### ISSUE THREAD

**Issue by strasharo** [rapid7/metasploit-framework#4214]
It looks like something changed recently in the metasploit storage of credentials in a database. I'm using metasploit with a postgresql backend and after some of the recent updates "creds" no longer shows the stored old credentials, although they're still present in the database. Is there a way to convert the entries stored in the "old" format to the new one in order to have them recognized by the recent versions of metasploit?

Thank you!

**Comment by jvazquez-r7** [comment]
ping @trosen-r7 / @strasharo, is it a thing still? I see some of the issues referenced in this issue are already closed, so updating this issue would be helpful :)

**Comment by strasharo** [comment]
Unfortunately I accidentally lost the database with the old creds and can no longer test it. Thanks a lot for your help.
