### ISSUE TITLE
Update user-agent fingerprinting for IE11 and Windows 10

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#4248]
See http://msdn.microsoft.com/en-us/library/ie/hh869301(v=vs.85).aspx

**Comment by wchen-r7** [comment]
IE11 detection was added here: https://github.com/rapid7/metasploit-framework/commit/5ffcfb22fa045fbac639004ec38b830c8c8e8797

I'll do the Win 10 patch in a bit.
