### ISSUE TITLE
Optimization: Reduce the number of elements in the load path

### ISSUE THREAD

**Issue by jduck** [rapid7/metasploit-framework#4257]
In my experimentation, this is the single largest cause for slow down due to tons of unnecessary/failing open(2) system calls. Reducing or eliminating this wasted computation greatly reduces start up time.

**Comment by bcook-r7** [comment]
Hey @acammack-r7, I think this feeds your interests

**Comment by acammack-r7** [comment]
While we do spend a lot of time in `require` (mostly the fault of rails and our gem deps), we spend a lot more time in our own custom `find` implementation looking for modules:
<img width="618" alt="screen shot 2016-05-25 at 11 21 01" src="https://cloud.githubusercontent.com/assets/16652544/15547801/0a420e4e-226b-11e6-9ecc-f452ccdeaede.png">
(absolute and relative times slightly skewed by tracing)

One thing we could do to make `require` faster is to use `require_relative` more within framework, although that could get ugly fairly quick.

**Comment by jduck** [comment]
As you can read from the past comments, this optimization turned out to be far less impactful than just minimizing what gets loaded automatically (aka msfex.rb).

**Comment by busterb** [comment]
We're at 130 gems currently. I don't see that going down a ton. Just don't think this is really impactful to work on 3 years later - we have some bigger ideas for how to scale metasploit that are outlined in the 2017 roadmap in the wiki.
