### ISSUE TITLE
Remove msfpayload and msfencode

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4326]
They need to go. This is one of the reasons why we created msfvenom in 2011. I guess you can say msfvenom has been in "beta" mode for more than 3.5 years... it has gone through a lot of testing and fixes.

An important step to do is we need to have a grace period. I think we need to do the following to make sure 3rd party tools (such as SET) or even trainings (such as OSCP) to have time to move away from them:

- [x] Add a deprecation message in those two utilities
- [x] On June ~~8th~~ 2015, have a pull request that removes msfpayload and msfencode, which should also close this issue.
- [x] Stop accepting patches for them
- [x] Maybe a blog post to announce this decision.

How long the grace period should be is up for discussion, I say 6 months.

**Comment by corelanc0d3r** [comment]
Perhaps it would be a good idea to also mention how to use "BufferRegister" with msfvenom (and explain that the behaviour of creating alpha_* encoded payloads is different in msfpayload/msfencode   vs   msfvenom.   (It won't have GetPC in msfvenom by default, so payload won't work by default)

**Comment by mubix** [comment]
@corelanc0d3r thanks for the catch, I use alpha_* encoders quite a bit and haven't tried it with msfvenom yet. Have you got some suggestions on fixes?

**Comment by wchen-r7** [comment]
@mubix The current workaround is this:

```
./msfvenom -p windows/meterpreter/bind_tcp -e x86/alpha_mixed AllowWin32SEH=nope -f raw
```

You must set AllowWin32SEH to false. (case sensitive)

But I am working on a fix to make this more consistent.

**Comment by wchen-r7** [comment]
So that problem has been resolved. You don't need the temporary workaround anymore. By default it should behave like msfencode now.

**Comment by wchen-r7** [comment]
Assigning this to myself so June 8th I will pull the trigger.

**Comment by wchen-r7** [comment]
We're delaying the June 8th deadline until Jive comes back online.
