### ISSUE TITLE
Potentially incorrect TLV type for enum_cred_store

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#4331]
I've noticed this a couple of times now:

```
[*] 4702111233380188160 credentials found in the Credential Store
[*] Decrypting each set of credentials, this may take a minute...
```
We might have an issue with mismatched TLV types or something. I'll investigate further, but this causes the module to spin for a rather long time.

**Comment by Meatballs1** [comment]
Duplicate https://github.com/rapid7/metasploit-framework/issues/3916
