### ISSUE TITLE
Add Apache Karaf Modules

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#4358]
http://karaf.apache.org/manual/latest-2.2.x/users-guide/remote-console.html

There is a default karaf/karaf user available by default in 2.x - 4.x that can be accessed over an SSH instance on 8081/TCP. The shell is a Karaf wrapper that allows everything from shell commands to OSGI stuff and gathering system information. Numerous useful modules could come from this. Write them.

**Comment by nstarke** [comment]
What is the best way to display the output of a command successfully run via SSH? I've got a karaf module in the works that will probably be an auxiliary module for running user specified commands. I'm having trouble with retrieving command output via Net::SSH::CommandStream, though.  Any guidance would be greatly appreciated.  Thanks in advance!

**Comment by bcook-r7** [comment]
I actually have the working module for this - totally forgot about it. I think @dmohanty-r7 worked on a while back, so I can't really take credit for the module, just being a pack-rat!

https://github.com/bcook-r7/metasploit-framework/commit/115c63e4baed8b787013fb16735fff0837d372e3

**Comment by bcook-r7** [comment]
It's just a login scanner, but of course use it for writing all of the other modules if it's helpful.

**Comment by nstarke** [comment]
This is exactly what I needed.  Thank you!!!!

**Comment by nstarke** [comment]
The module I submitted needs some work, but it is functioning.

**Comment by wchen-r7** [comment]
It would probably also be nice to add "karaf" to:
https://github.com/rapid7/metasploit-framework/blob/master/data/wordlists/unix_passwords.txt
and
https://github.com/rapid7/metasploit-framework/blob/master/data/wordlists/unix_users.txt

Maybe?
