### ISSUE TITLE
WtfError yelling "wtf!" or "lame" isn't a useful message

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4382]
They're not meaningful so please don't do that:

https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/peparsey/pebase.rb#L1199
https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/peparsey/pebase.rb#L1208

**Comment by jvazquez-r7** [comment]
@wchen-r7 is going to help with this one :) thanks @wchen-r7 !
