### ISSUE TITLE
convert Sessions "-d" option to simply detach the session

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#4423]
Not sure what the original option was supposed to do, but the `detach` option inside of meterpreter would great for checking live-ness of `reverse_http(s)` payloads.

Suggest replacing current code path for `sessions -d` with something like:
```
framework.sessions.each_value(&:shutdown_passive_dispatcher)
```

**Comment by jvazquez-r7** [comment]
Apparently this code was forgotten when ```data/msfweb``` was deleted, and prolly should be cleaned, because hasn't a lot of sense from the console point of view. 

We concluded that while reviewing with @todb-r7 , @wvu-r7 , @wchen-r7 and someone else.

We would love someone else to double check if we can safely delete the detach code now which the msfweb is out :-) ping @hmoore-r7 (maybe @jlee-r7 if he has some minutes and could be helpful here :P)

**Comment by mubix** [comment]
Would love if the `sessions -d` command could be converted into actually detaching a session or list of sessions. Would save a lot of time of interacting with each session and typing "detach"

**Comment by bcook-r7** [comment]
I have been playing with this using reverse_http - it seems to just kill the session. How is this different than -k ? IOW, I do not quite understand what 'detach' from a meterpreter session does that is different than 'exit', or what its use is.

**Comment by hmoore-r7** [comment]
Detach removes the registered session and the HTTP handler, but does not send an "exit" to the Meterpreter. Its largely pointless now in light of new changes.

**Comment by hmoore-r7** [comment]
@mubix The argument against detach is that since the payload will automatically reconnect, it doesn't really change anything, it just puts the old session into a new session ID.

**Comment by hmoore-r7** [comment]
Once the new transport stuff is landed, it might be nice to have a sessions -t to redirect all sessions to a new transport/listener.

**Comment by bcook-r7** [comment]
OK. The most reasonable thing then is to just remove this altogether along with 'detach' in the session itself.

**Comment by mubix** [comment]
@hmoore-r7 I use detaching a lot to know if they are still alive or not. It's easier than interacting with each one and trying to run commands. If they come back, they are still alive ;-)

**Comment by mubix** [comment]
@bcook-r7 Please don't remove detach until there is a good replacement for the usecase

**Comment by hmoore-r7** [comment]
@mubix To determine if a session is alive, you might start using client.core.machine_id(timeout) instead, the detach command no longer makes sense as a way to detach sessions.

**Comment by hmoore-r7** [comment]
@mubix Also of note, look at ```sessions -l -v``` in #5297 (CheckIn time)
