### ISSUE TITLE
Nessus XML-RPC interface appears out of date

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [rapid7/metasploit-framework#4447]
I'm trying to connect my MSF to Nessus using:
 
_$ nessus_connect user:pass@127.0.0.1:8834 ok
(tried with and without "ok"/SSL)
 
Error (terminal output):

```
Error connecting/logging to the server!
[-] Error while running command nessus_connect: undefined method `root' for nil:NilClass
 
 
Call stack:
/usr/share/metasploit-framework/lib/nessus/nessus-xmlrpc.rb:147:in `login'
/usr/share/metasploit-framework/plugins/nessus.rb:445:in `nessus_login'
/usr/share/metasploit-framework/plugins/nessus.rb:431:in `cmd_nessus_connect'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:200:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:30:i n `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'
```

I've been trying to solve this for two days! What I tried:
 
- Restarted service (nessusd, metsploit, postgresql)
- Restarted system
- Ran msfupdate
- Re-installed Nessus
- Re-installed Metasploit (+ PostgreSQL)
- Restored a clean VM snapshot
- Re-installed the entire VM
 
Nothing worked.
 
I'm using Kali Linux as root (only user). I have a previous experience with both products and have a successful history connecting them. It's just not working now on my latest install of the system (nor the re-install). All are latest versions.
 
Note: I CAN log in the web UI of Nessus using same creds supplied to Metasploit.
Note: I DID "load nessus"

**Comment by vasubesimple** [comment]
does this problem has solved , I have the same problem, if it is fixed , I cam upgrade the plugins

**Comment by void-in** [comment]
I am working on the new connector. The plugins/nessus.rb and lib/nessus/nessus-xmlrpc.rb needs to be updated. So far I have implemented nessus_connect, user_add, list_policies, list_users, list_folders, and nessus_admin commands. You can view the changes in the above two files in my fork.

**Comment by void-in** [comment]
The files plugin/nessus.rb and lib/nessus/nessus-xmlrpc.rb has been updated in my github repo and is working fine. However, I am using the ruby Faraday gem from HTTP communication. 

@wchen-r7  Can you have a look at it and see if the same can be implemented in Rex HTTP client?

Files changed:
Gemfile
plugin/nessus.rb
lib/nessus/nessus-xmlrpc.rb

**Comment by wchen-r7** [comment]
> @wchen-r7 Can you have a look at it and see if the same can be implemented in Rex HTTP client?

Pretty sure you can.

**Comment by void-in** [comment]
@wchen-r7 The same has been implemented using net/http. Please have a look at https://github.com/rapid7/metasploit-framework/pull/4690. I have added a few remaining APIs as well. One thing I need to look at is when the report is downloaded to the framework how we can populate the DB from its data. Other than that, everything should work properly in the next commit.

**Comment by wchen-r7** [comment]
Yeah I am looking at it right now actually. I have time today.

Normally we want people to implement HTTP in Rex, because that way framework can manage it. In some rare cases, we don't actually care if framework should manage or not. I need to actually dig into Rex and decide if this is that case again (not familiar with Rex HTTP enough).

**Comment by void-in** [comment]
Alright great. Initially I tried to replicate it through the send_request_cgi or send_request_raw on which you have some wonderful documentation over the wiki. However, it would always complain about the missing datastore options. 

The way I understood at that time was the Rex would be helpful in case we need to route the traffic through compromised hosts as well. However, in this case since we only need to directly interact with the Nessus server, we wouldn't need it (sorry I have a very limited knowledge so if you think that is not the case, you let me know and I will implemented it in any other way suggested).

**Comment by wchen-r7** [comment]
> Rex would be helpful in case we need to route the traffic through compromised hosts as well

Yeah, that's one of the biggest reasons.

I need to look into this before coming up with a better yes/no answer, sorry. Working on it.

**Comment by jvazquez-r7** [comment]
This is related to https://github.com/rapid7/metasploit-framework/pull/4690, @wchen-r7 is already working on it.

**Comment by rosh59** [comment]
hi can you help me 

Call stack:
/opt/metasploit/apps/pro/msf3/plugins/nessus.rb:444:in `nessus_login'
/opt/metasploit/apps/pro/msf3/plugins/nessus.rb:431:in `cmd_nessus_connect'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/shell.rb:200:in `run'
/opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/console.rb:38:in `start'
/opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'

Can you define for me the required files in update

**Comment by void-in** [comment]
This PR has been landed but since you are using the stable branch, it might not have been pushed as yet. Two files were updated as you can see at https://github.com/rapid7/metasploit-framework/pull/4690. The lib/nessus/nessus-xmlrpc.rb and plugins/nessus.rb. You can manually download the two files from the mentioned PR, replace the ones you already have and then give it a try. If you encounter any errors, report it here.

**Comment by wchen-r7** [comment]
Pro users don't get updates from git. A properly QA'd update package is released periodically so you will have to wait for that.

**Comment by rosh59** [comment]
thank you  (void + wchen) 
i'ts work now

**Comment by vasubesimple** [comment]
hello , 

now I am able to connect nessus via msf but when I tried to load policies or reports , it is showing this error , Void in can you please check this ?

 nessus_policy_list
[-] Error while running command nessus_policy_list: undefined method `each' for nil:NilClass

Call stack:
/usr/share/metasploit-framework/plugins/nessus.rb:1354:in `cmd_nessus_policy_list'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:200:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'

**Comment by wchen-r7** [comment]
Line 1354 points to this in cmd_nessus_family_list:

```ruby
if args[0] == "-h"
```

cmd_nessus_policy_list uses #each here:

```ruby
list["policies"].each { |policy|
```

However, there is a check before that loop:

```ruby
        unless list["policies"]
          print_error("No policies found")
          return
        end
```

In addition, I was the one who added the check:

https://github.com/rapid7/metasploit-framework/commit/e8ba0b7c31ed57f7364840d55e616794fe8bf843#diff-16b3b9e17c3cef3112161f74c8c15b28R1478

So @vasubesimple, it sounds like for some reason you don't have the latest update. If the plugin you have can talk to the latest Nessus server, but you're getting that error, it sounds like you for some reason picked a commit from that pull request or something weird like that. Please double check.

**Comment by void-in** [comment]
@vasubesimple I think a better solution would be for you to wait for the official update package as @wchen-r7 mentioned in the previous comment. If you know what you are doing, then take the files from the https://github.com/rapid7/metasploit-framework repo. That way you will get the final version of the files.

**Comment by invisiblethreat** [comment]
You may want to consider leaving the old XMLRPC lib and adding the new REST lib as well. 5.2.8(XMLRPC), and 6.2.1(REST) are both still supported. Deprecating one in favor of the other may just create additional issues until the 5.2.x branch goes EOL.

**Comment by wchen-r7** [comment]
Where do you download the old Nessus version running xmlrpc?

**Comment by wchen-r7** [comment]
When I was working this nessus PR, I hit a lot of broken code. So I need an old version of Nessus to test when I bring back the old code.

**Comment by invisiblethreat** [comment]
I'll need to dig in. Only seeing 6.x right now in "home feed". Unsure if 5.x is available without a subscription.

**Comment by void-in** [comment]
Nessus 5.2.8 is still available for download for the Pro feed users. I am not sure why they are keeping the old version since if a customer has a Pro feed license, he can update to the latest version free of cost. 

@wchen-r7 I have asked the Nessus support about version 5 support, If they are doing to support it for an extended period of time, I will send you the v5.2.8 version setup. Just waiting a response from their end.

**Comment by wchen-r7** [comment]
@void-in very nice. thanks!

**Comment by void-in** [comment]
@wchen-r7 Got the following reply from the Nessus support:

> Nessus version 5 and version 6 have different API calls, so the customers, who use old API from version 5 and currently not willing to update their API utility scripts, can still use version 5, while the customers, who is using newer API from version 6, has updated to the newest version of Nessus. There is no license restrictions to keep people not update to the latest version, and we are encourage our customer using the latest version of Nessus as it has new features and has bug be fixed.

Which means we don't have to keep the old XML API as all the customers can update to the latest version without any restriction.

**Comment by wchen-r7** [comment]
I see, thanks for contacting Nessus Support @void-in. So it looks like it's pretty straight forward to upgrade from version 5 to 6, people can just do that. @invisiblethreat, so based on what Nessus says, I currently will do nothing to support version 5. But if there's still a large population of users who are still on version 5, and refuse to upgrade for some reason (I'd like know why), then I will try again. Or if you want, we can make the plugin a little more obvious that it's for Nessus 6 (basically I think would probably be just an one-line change for PLUGIN_DESCRIPTION), so people will not be confused about that.
