### ISSUE TITLE
Railgun and x64 pointers

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4455]
Are a world of pain.

It currently uses PDWORDs, but I don't think it differentiates between the POINTER and the DWORD when it comes to the size of the values. Modules use PDWORD for actual PDWORD values, but also for buffers which will contain a pointer.

E.g. the Pointer may be a QWORD (on x64), but the value would still be a DWORD. I think this may cause some issues when it comes to inout, out buffers.

I think we need to add another a UNIT_PTR data type to railgun or to handle LPVOID in inout/out buffers.

**Comment by bcook-r7** [comment]
Sounds like a plan. Is there an easy way to identify all of the current PDWORD-as-pointer users?

**Comment by fsacer** [comment]
as that was more of a guideline this should be closed @wvu-r7
