### ISSUE TITLE
Windows 8 NtApphelpCacheControl() priv escalation bug

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#4486]
Someone want's to implement it in metasploit?
https://code.google.com/p/google-security-research/issues/detail?id=118

**Comment by wchen-r7** [comment]
I completely forgot there's actually a ticket for this. PR for this should be: https://github.com/rapid7/metasploit-framework/pull/4562

**Comment by wchen-r7** [comment]
This is in master, just forgot the keyword to close this automatically.
