### ISSUE TITLE
Double check respond_to? for Ruby 2.1 compat

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#4507]
In [this comment](https://github.com/rapid7/metasploit-framework/issues/4219#issuecomment-66727019), @jlee-r7 raised a concern about the usage of `respond_to?` and how it may affect 2.1 functionality.

There are 14 uses in `modules/` and 132 uses in `lib/`. Let's validate that we're not going to suddenly cause 2.1 breakage there.

Note that nearly all developers have been on 2.1 since early November if they [followed these instructions](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#moving-to-ruby-21x), so it seems unlikely that there are remaining breakages, but let's be (more) sure.

**Comment by todb-r7** [comment]
Note, don't close #4506 until this gets resolved. Again, likely no actual code changes, but eyeballs should sweep over those instances.

**Comment by todb-r7** [comment]
Note, this grep indicates there's some lingering pre-2.1 codesmell, too. Mostly around metasm and rex:

````
todb@mazikeen:~/git/rapid7/metasploit-framework$ grep -ril "1\.9" lib/ tools/ | wc -l
40
````

**Comment by wchen-r7** [comment]
Since respond_to?() respects Ruby's access control, and send() doesn't. Basically if I see this type of coding style, I treat it as unsafe, and I set the include_all flag (2nd argument) for respond_to?() to true so that both methods (respond_to? and send) agree to the same access control.
