### ISSUE TITLE
Metasploit Console fails to start if it cant write to $install/log/

### ISSUE THREAD

**Issue by ZeroChaos** [rapid7/metasploit-framework#4511]
MSP-11942

```
Rails Error: Unable to access log file. Please ensure that /usr/lib64/metasploit9999/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
```
Grab a copy from github as root, install it to the system, and I get this error when I try to run as a user.

**Comment by hmoore-r7** [comment]
The config/application.rb file is not setting config.logger, therefore the default Rails logging is used, which creates a directory called "logs" in the install path, and inside there creates production.log. This breaks a few things:
* The user running metasploit has to have write access to the install directory (bad)
* The production.log file may be created with insecure permissions
* The logs are now desynced from the standard ~/.msf4/logs/ directory

To fix this, the Rails::Application instance needs to be configured to store logs in the same directory as the rest of the framework ($HOME/.msf4/logs/).

**Comment by hmoore-r7** [comment]
A quick and dirty fix would be:
```diff
diff --git a/config/application.rb b/config/application.rb
index f4eaab5..4990239 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -35,6 +35,9 @@ module Metasploit
       include Metasploit::Framework::CommonEngine
 
       config.paths['config/database'] = [Metasploit::Framework::Database.configurations_pathname.try(:to_path)]
+      if ENV['HOME']
+       config.logger = Logger.new(File.join(ENV['HOME'], ".msf4", "logs", (ENV['RAILS_ENV'] || "production") + ".log"))
+      end
     end
   end
 end
```

**Comment by limhoff-r7** [comment]
@hmoore-r7 your fix does not cover all the places that `Msf::Config` searches when determining config_root in `Msf::Config.get_config_root`.  The code already has a thorough approach for falling back to different location for 'config/database', so I'll apply the same approach to setting config.logger's path.
