### ISSUE TITLE
Aux::Scanner::Oracle::oracle_login and nmap parser

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4522]
oracle_login is trying to get `:port_script` events from the nmap parser. However

db.emit was removed from the parser so script `&blocks` only return `:host` events now:

https://github.com/rapid7/metasploit-framework/commit/5cc98b7ded1f15b7d5ea2222426d02ca14c9d75b 

Most data doesn't seem to be returned to a block anymore making the Auxiliary::Post::NMAP mixin less useful. Ideally it should be yielding all sorts of data so the module can parse Ports/Scripts/Hosts etc?

**Comment by ccondon-r7** [comment]
Closing since this is supa-dupes old, but if you wanna reconfirm and reopen, gopher it!
