### ISSUE TITLE
Ruby 2.0 compat -> Iconv

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4525]
There's a number of calls that use iconv in Rex::Text. Some have workarounds if iconv isn't available by the looks of it.

They should be removed for proper 2.0+ compatibility?

**Comment by todb-r7** [comment]
Can you give an example, @Meatballs1 ? I don't want to force 2.0+ only if we don't actually have to, at least not for a little while yet. Basically, we're gunning for a) No breakage in 2.0+, b) no longer test on 1.9.3-, c) start using 2.0-only functionality, with reasonable timing between each step.

**Comment by Meatballs1** [comment]
Yeah they shouldn't break anything as they fallback to other techniques. Just wanted to highlight them:

The following should probably have logic reversed if using 2.0+ as a base:

```
425   def self.to_ebcdic(str) 
426     begin 
427       Iconv.iconv("EBCDIC-US", "ASCII", str).first 
428     rescue ::Iconv::IllegalSequence => e 
429       raise e 
430     rescue 
431       self.to_ebcdic_rex(str) 
432     end 
433   end 
```

```
438   def self.from_ebcdic(str) 
439     begin 
440       Iconv.iconv("ASCII", "EBCDIC-US", str).first 
441     rescue ::Iconv::IllegalSequence => e 
442       raise e 
443     rescue 
444       self.from_ebcdic_rex(str) 
445     end 
446   end 
```

**Comment by todb-r7** [comment]
Okay, so it looks like the fallbacks will become dead code once we're 2.1. IOW, nothing breaks, these just become a needless rescue. I know we have a handful of other things like this to accommodate back to 1.8.6 which will never get tripped on anything modern.

Let me mark this delayed until after the real cutover to 2.1 (which should be last week of Jan). It doesn't seem to be blocking 2.1.

**Comment by hmoore-r7** [comment]
Removing the delayed tag, adding ruby-2.1 since its past January :smile:

**Comment by todb-r7** [comment]
Taking a stab at this, it seems less far reaching then I thought. Pretty much the only thing that seems to use Iconv are EBCDIC translations, and right now, that's all limited to DRDA (for DB2).

**Comment by todb-r7** [comment]
Well that's a PITA. `Iconv` is deprecated in favor of `String#encode`, but there's no definition for `EBCDIC-US` in `Encodings`:

```
Encoding.list.map {|x| x.to_s}.select {|x| x =~ /EBCDIC/} #=> []
```

So.. what @Meatballs1 suggested in reversing the logic is partially correct. We basically never want to use Iconv. It's dead to us. In fact, it gets complained about, like here:

https://bbs.archlinux.org/viewtopic.php?id=160369
