### ISSUE TITLE
Lost DB_ALL_USERS feature in LoginScanner modules

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4530]
The DB_ALL_USERS option doesn't work. No users are appended from the database into the list credentials.

The following uses smb_login to demonstrate the problem. Expected result DB_ALL_USERS should add a user:password for each database user against SMBPass and against every password from PASS_FILE.

creds add-password user '' '' domain
use auxiliary/scanner/smb/smb_login
set RHOST 192.168.1.1
set DB_ALL_USERS true
set SMBPass parp
run

**Comment by wchen-r7** [comment]
Looks like it affects all LoginScanner modules?

**Comment by Meatballs1** [comment]
yeah, the creds/loginscanner stuff is a world of uber confusion for me. :o

**Comment by wchen-r7** [comment]
Updated the title and modified the description a little bit to make it more clear that this is a more widespread problem.

**Comment by Meatballs1** [comment]
Resolved with https://github.com/rapid7/metasploit-framework/pull/4540

**Comment by Meatballs1** [comment]
Related https://github.com/rapid7/metasploit-framework/issues/4530
