### ISSUE TITLE
Lost DB_ALL_PASS feature in LoginScanner modules

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4532]
DB_ALL_PASS is an option that adds all collected passwords in the current database to the try list. It is offered as a datastore option by Msf::Auxiliary::AuthBrute, but LoginScanner modules don't actually touch this option because they don't rely on Msf::Auxiliary::AuthBrute to build credentials, so basically this option doesn't do anything. It looks like it's a lost feature.

The following should demonstrate the problem:

1 - I smb_login with a valid user/pass so that it will store my password:

```
msf auxiliary(smb_login) > run

[*] 192.168.1.80:445 SMB - Starting SMB login bruteforce
[+] 192.168.1.80:445 SMB - Success: 'WORKSTATION\Administrator:mypassword' Administrator
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) >
```

2 - I unset the SMBPass option so the module won't use that as a source

```
msf auxiliary(smb_login) > unset SMBPass
Unsetting SMBPass...
```

3 - I set DB_ALL_PASS to true because I want it to try the stored one

```
msf auxiliary(smb_login) > set DB_ALL_PASS true
DB_ALL_PASS => true
```

4 - I run the scan again, this time no password is tried:

```
msf auxiliary(smb_login) > run

[*] 192.168.1.80:445 SMB - Starting SMB login bruteforce
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(smb_login) >
```

**Comment by dmaloney-r7** [comment]
@wchen-r7 it should be doing it right here https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/smb/smb_login.rb#L103-L104

there are methods in the auth_brute mixin that check that datastore option and if it is set append existing DB creds into the cred collection

**Comment by dmaloney-r7** [comment]
ohhh i see, we use DB_ALL_CREDS but there's a seperate DB_ALL_PASS and DB_ALL_USERS option
 that are not respected

**Comment by wchen-r7** [comment]
Yeah, DB_ALL_CREDS works nicely.

**Comment by dmaloney-r7** [comment]
well, crud

**Comment by jhart-r7** [comment]
On a related note, after an internal discussion yesterday I am working on a few improvements to the authbrute mixin.  While the work shouldn't overlap, it does come close.  One thing that it has now that you could probably immediately benefit from is a partial unit test of a few critical portions of authbrute.  Let me know if you want me to fast track that or drop a copy to whoever ends up taking #4532

**Comment by dmaloney-r7** [comment]
@jhart-r7 unit testing of metasploit module mixins is difficult/complicated/ugly. if you want to try, be my guest. but it's generally not a good time
