### ISSUE TITLE
Refactor AuthBrute to account for common module patterns and mixin problems

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#4541]
Of the 83 AuthBrute modules, there are two patterns that are used when it comes to building up a set of credentials and then scanning with them:
- ~31 modules (`grep -i AuthBrute modules/auxiliary -rl |xargs -n1 grep -L each_user_pass` for examples) use a `CreentialCollection` and pass it to a `LoginScanner`, all doing nearly the exact same thing like:

```
cred_collection = Metasploit::Framework::CredentialCollection.new(
        blank_passwords: datastore['BLANK_PASSWORDS'],
        pass_file: datastore['PASS_FILE'],
        password: datastore['PASSWORD'],
        user_file: datastore['USER_FILE'],
        userpass_file: datastore['USERPASS_FILE'],
        username: datastore['USERNAME'],
        user_as_pass: datastore['USER_AS_PASS'],
    )

    cred_collection = prepend_db_passwords(cred_collection)

    scanner = Metasploit::Framework::LoginScanner::Something.new 
   ...
    scanner.scan! do |result|
      <nearly identical block each time>
   end
```

The credentials returned by the `CredentialCollection` are utilized by the associated `LoginScanner` by calling `CredentialCollection#each` which creates and yields each credential in turn.  

The only general variance between the modules that use this technique is the value for `realm`, which looks to be `DATABASE` or `DOMAIN` from `datastore`, or nil or a random value.
- 52 (`grep -i AuthBrute modules/auxiliary -rl |xargs -n1 grep -l each_user_pass` for examples) are often generally more primitive or use other client code but non seem to have a `LoginScanner` and instead utlize `AuthBrute#each_user_pass`.  `AuthBrute#each_user_pass`, under the hood, calls `build_credentials_array` and `adjust_credentials_by_max_user`` to build up the list of credentials that will be passed to the modules block responsible for checking the validity of a login.

That first pattern results in a lot of copy-pasta in the scanner modules  -- nearly every one has the exact same block of code that is blindly copied from one module to another.  To further complicate matters, as `CredentialCollection` evolves (or has evolved, I guess), that evolved functionality often may not make its way down into the affected modules due to a missing option in the call to `CredentialCollection.new`.  This essentially guarantees that any improvement made to `CredentialCollection` or `AuthBrute` stands a chance of requiring individual module work.  This is a headache and causes maintenance problems.

The second pattern is probably just a result of modules that have not yet been converted to the new model, but in doing so highlights another problem here, in general.  `CredentialCollection#each` and `AuthBrute#each_user_pass` are each responsible for building the list of credentials that'll be used by the block or yielded, and each theoretically builds that list of passwords the same way, but they are separate pieces of code.  This means that in situations like we can see in #4540, fixes for `AuthBrute` often require make the same style of changes in very similar but separate bits of code.  This is a headache and causes maintenance problems.

Topping it all off, `AuthBrute` has no unit tests, so aside from hoping we can carefully select affected modules to test and carefully monitor their behavior before/after `AuthBrute` changes, there is no guarantee that seemingly simple fixes will benefit all users of the mixin. See #4530 for an example.

Minimally, the code responsible for generating the list of potentially-to-be-tried credentials should be unified, and a unit test added for `AuthBrute` that ensures that the two patterns used for working with credentials get the same credentials when using identical `datastore` options.

**Comment by todb-r7** [comment]
@jhart-r7 did https://github.com/jhart-r7/metasploit-framework/commit/aba31f3db151652b27693a991abe02f54cbe5a02 actually fix this?

**Comment by todb-r7** [comment]
Ah nm it's in your branch, and #4545 was closed. So, nm. Deleting these comments.

**Comment by wchen-r7** [comment]
I think we've been in the process to deprecate AuthBrute, but your points are valid.

The repeated credential reporting code might need to be a separate issue. What you want is actually what currently [report_auth_info is doing](https://github.com/rapid7/metasploit-framework/blob/dca2607d54fdeb6a6c70133610b2f2ab74c02ccc/lib/msf/core/auxiliary/report.rb#L180), but it's recommended to use the Metasploit::Credential methods directly instead.
