### ISSUE TITLE
Kerberos Service Principal Tickets for Offline Brute Forcing

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4556]
Using the Kerberos library it would be awesome if we could create an aux scanner/gather module which pulled down Kerberos tickets for offline brute force password attacks, ala https://github.com/nidem/kerberoast

It could also be implemented as a Post module using the Kiwi extension...

**Comment by ccondon-r7** [comment]
Attic-ing for now!
