### ISSUE TITLE
Openvas DB Import Erroring out

### ISSUE THREAD

**Issue by nstarke** [rapid7/metasploit-framework#4571]
Hello,
I am having trouble importing OpenVAS report results using openvas_report_import in the openvas plugin.  Every time I try to run the openvas_report_import, I receive this error:

https://gist.github.com/nstarke/aabe781c6967a7f03adb

Here is an XML copy of the report:

https://gist.github.com/nstarke/d94e71adfac22f5a28fa

I can reproduce the issue by trying to run db_import on the XML file, as well.  

I believe this is a problem specific to the data I pulled back - something perhaps to do with the fact that all hosts have only an IP - no hostnames assigned.  That's just a guess though.  Please let me know how I can be of assistance in fixing this problem!

**Comment by nstarke** [comment]
Sorry, I was mistaken, I CANNOT reproduce the issue by trying to run db_import.

**Comment by nstarke** [comment]
More information: This failure only happens when the instance I am running on does not have an external hostname.  For example, when I connect my VM to a network that automatically assigns a hostname via DHCP, there is no problem.  However, on a network that does not have this feature, the problem exists and CAN be reproduced via db_import.

**Comment by wchen-r7** [comment]
Yeah, I believe you by looking at the backtrace. I'm guessing the host is nil, but I'll have to take a deeper look and decide how to fix it properly.

**Comment by nstarke** [comment]
Please let me know if I can assist in any way with the fix.  I tried debugging this morning without much luck; will probably have another crack at it over the next few days.  Cheers.

**Comment by nstarke** [comment]
in ```lib/rex/socket.rb:181```, the 'hostname' argument's value is '0192.168.0.10', which does NOT match the regex MATCH_IPV4 - it is then erroneously failing the check on line 177 and falling through to 181.  

I tried to figure out where that leading '0' is coming from this morning.  

At a certain point,
```lib/rex/parser/openvas_nokogiri.rb:94```
variable '@text' is set to '0Network Source Interfacesource_iface2015-01-12T01:24:27Z2015-01-12T01:24:46Z15192.168.0.10', and then on line 128, @state['host'] is automagically set to '0192.168.0.10'.  Not sure where the transform is happening.  If you have any ideas on where I could look I'd be happy to continue investigating.

**Comment by wchen-r7** [comment]
Good analysis.

You know, I am not actually seeing the connection between the string ```"0Network Source Interfacesource_iface2015-01-12T01:24:27Z2015-01-12T01:24:46Z15192.168.0.10"```, and what you actually get for host: ```"0192.168.0.10"```... I don't actually see an exact match.

I see there are two places that cause :host being assigned. Line 89 and line 94, are you sure line 94 is the last one before the you see it in record_vuln()?

**Comment by nstarke** [comment]
So looking at line 89, I can see '0192.168.0.10' being assigned to `@state['host']`, but where is `@text` ever assigned a value?  Trying to track down how that value is being set now.

**Comment by wvu-r7** [comment]
Probably some Nokogiri magic, @nstarke.

**Comment by nstarke** [comment]
I will push a new commit for this issue tonight.  Sorry for the delay!
