### ISSUE TITLE
Tab complete on a valid file path can cause msfconsole to exit unexpectedly

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4574]
To be able to reproduce this issue, follow this:

```
$ echo hello > /tmp/test.txt
$ ./msfconsole -q
msf > db_import /tmp/t[TAB]
```

```[TAB]``` means you should press the tab key.

And then you should get this backtrace:

```
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:8438:in `lstat': No such file or directory @ rb_file_s_lstat - /Users/sinn3r/rapid7/msf/db_import /tmp/test.txt (Errno::ENOENT)
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:8438:in `append_to_match'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:6812:in `rl_complete_internal'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:6851:in `rl_complete'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:4322:in `_rl_dispatch_subseq'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:4311:in `_rl_dispatch'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:4727:in `readline_internal_charloop'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:4801:in `readline_internal'
	from /Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rb-readline-0.5.1/lib/rbreadline.rb:4823:in `readline'
	from /Users/sinn3r/rapid7/msf/lib/rex/ui/text/input/readline.rb:132:in `readline_with_output'
	from /Users/sinn3r/rapid7/msf/lib/rex/ui/text/input/readline.rb:86:in `pgets'
	from /Users/sinn3r/rapid7/msf/lib/rex/ui/text/shell.rb:184:in `run'
	from /Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/console.rb:38:in `start'
	from /Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:48:in `<main>'
```

Note: if you don't create /tmp/test.txt first, you won't be able to reproduce this issue.

**Comment by Viss** [comment]
I found out about this today! good fun!

**Comment by wchen-r7** [comment]
msfconsole terminating unexpectedly is always a catastrophic problem -_-

**Comment by wchen-r7** [comment]
Initial analysis:

The rl_complete_internal method calls gen_completion_matches to find a match in the string. When the file path is valid, gen_completion_matches returns this match ["db_import /tmp/test.txt", nil, nil], and then pass the first element to method append_to_match. The append_to_match() method will expand the file name first, which will end up being "/Users/sinn3r/rapid7/msf/db_import /tmp/test.txt", and then pass that to a File.lstat method to check. Obviously, the file path is never valid, and then lstat will raise Errno::ENOENT, which will not be handled by anything, and this causes msfconsole to die.

**Comment by wchen-r7** [comment]
Oh wait, I am hitting an old bug. It was already reported here:
https://github.com/rapid7/metasploit-framework/issues/4128

**Comment by wchen-r7** [comment]
Well, actually let me reopen this... a similar problem was reported, HD submitted a patch, and then the patched was applied. Maybe the patch only fixed #4128, but this is another new bug?

**Comment by hmoore-r7** [comment]
The vendor never shipped the patch in a new gem, as another ticket states. Still open basically.

**Comment by hmoore-r7** [comment]
This is still #4128
