### ISSUE TITLE
Add threading to owa_login

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#4575]
Is there a chance that adding threads to this could be possible? It would likely greatly speed up bruteforcing. Especially when you have a few hundred thousand potential words built with something like cewl + mutator.

**Comment by wchen-r7** [comment]
Hmm what do you mean, is the THREADS datastore option not working?

**Comment by Viss** [comment]
it appears in console to be doing one at a time. Let me verify this.

**Comment by Viss** [comment]
hrm, well the target I have for this right now is in sweden, and the UI scrolls one line at a time - I can't rightly tell if its actually using threads or just going really really slow.

**Comment by wchen-r7** [comment]
Let me dig into the code a little bit more... brb

**Comment by wchen-r7** [comment]
@Viss So the function of THREADS is to allow MSF to try the module against multiple hosts at the same time, one thread per host. It does not actually make the brute-forcing process any faster for each host, and sounds like that's what you want right? To achieve that the module will have to do this on its own. We can add this feature for sure.

**Comment by wchen-r7** [comment]
Changing bug to feature.

**Comment by Viss** [comment]
ah - yeah - thats exactly what I'm looking for - hammer the host with a bunch of threads. I tend to only use this to hit one host at a time anyway, not multiple hosts, but that's just me.

**Comment by wchen-r7** [comment]
Yeah that makes sense.

**Comment by Viss** [comment]
Typically, a company will only have one owa setup - and if they have more, then they're all probably still authing against the same AD backend, so for OWA specifically it seems like one wouldn't need to brute more than one host at a time :D

**Comment by ccondon-r7** [comment]
Sticking in the attic for now.
