### ISSUE TITLE
Find udp_scanner_template.rb a new home (or have it removed)

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4577]
While browsing the auxiliary tree, I find this udp_scanner_template.rb. A template that really isn't meant to be used for any practical real world scenarios, unlike the rest of Metasploit modules. It's really random and out of place to put this in auxiliary/scanner/.

We used to have a "samples" directory specifically for this kind of stuff, but because of #4286, we don't anymore. So I see two possible actions:
1. We bring back the samples folder, and then put udp_scanner_template.rb. All the removed samples should be brought back too.
2. udp_scanner_template.rb shares the same fate like the rest of the samples - removed. Maybe convert it as a wiki doc instead.

What do you guys want to do?

**Comment by todb-r7** [comment]
@wchen-r7 I was convinced by the arguments in the original PR, #4113. Looks like you weren't on that conversation, @wchen-r7. I was also willing to consider moving it out if needed. Want to review that PR and come back with your opinion, @wchen-r7?

**Comment by wchen-r7** [comment]
I looked at the main reason the module ended up being in the modules dir. If I'm not mistaken this is why: https://github.com/rapid7/metasploit-framework/pull/4113#issuecomment-62083758

And then it was suggested just land it first and figure it out later... which is actually what we're doing now.

First off, I think that saying documentation/samples/modules isn't a strong argument. Most modules end up old and forgotten by devs, I'm sure eventually so will this template. Some of my templates in the private repo can be considered as outdated or undesirable to use too. That's just what happens.

Second, if you want a template to be loadable/interactive, why not just set --module-path when you run msfconsole? When I write a new module, 99% of the time I will never actually bother to load the template. I will always copy the template first for sure, and then I will modify it, and then I will load the modified one. I MIGHT want to load the template if I have never ever written that type of module, but after playing with it once or twice, I'll never bother to do that again. I would not trade better organization for this. If this is a really heavily used feature, then you should seriously consider add a templates directory as a new default load path. Templates just don't deserve the same spot as modules for real attacks.

And that's my opinion.

**Comment by jhart-r7** [comment]
Feel free to move this wherever you want but please don't delete it.  UDPScanner modules had been quiet messy and this was put there to hopefully fix things, so that if someone wants to write a UDPScanner they have a known-good example to start with.  There are plenty of other module patterns and mixins with similar problems (```AuthBrute```` -- #4541).

I'd support moving this and all things like it to a dedicated directory so long as there is documentation on how to use them (```--module-path``` may be enough) and they work enough as-is to be usable.

**Comment by wchen-r7** [comment]
Relocating is the preferred choice.

@todb-r7 Do you want just a new directory, or as a new branch?

**Comment by todb-r7** [comment]
If you drop it in a new git branch, it'll be guaranteed to wither away. I'd go for a sane directory structure.

documentation/samples/modules/ seems okay by me, just drop a README.md in there somewhere that makes the `--module-path` argument obvious.
