### ISSUE TITLE
Add post module support for sessions -s

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4581]
Have we talked about this before? Feels like we have, but I can't remember. It looks like sessions -s only supports meterpreter scripts, but we don't recommend or encourage meterpreter scripts anymore. sessions -s for post modules would be more convenient than irb, multi_post.rc, or post/multi/manage/multi_post.

**Comment by hmoore-r7** [comment]
Related to #3792

**Comment by todb-r7** [comment]
@wchen-r7 suggested closing this as a dupe of #3792, no need to track both. Sounds good.
