### ISSUE TITLE
32-bit processes on 64-bit targets may not see expected registry data on 64-bit targets due to WoW64

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#4589]
For example, if the registry of a 64-bit target is accessed from Meterpreter, which is 32-bit, and HKLM\software\something is accessed, the code in question will be silently given HKLM\Software\WoW6432Node\something instead. While this may be OK and even desired in some cases, it results in missed keys/data in some situations (like software/patch enumeration, for example).

**Comment by bcook-r7** [comment]
For meterpreter sessions, we could extend the API to explicitly state which view is desired explicitly (default, 32-bit, or 64-bit).

For shell sessions, I don't see a way to do something similar using the 'reg' command: http://technet.microsoft.com/en-us/library/cc742028.aspx

**Comment by kernelsmith** [comment]
even if you specifically invoke the 64-bit version of reg.exe?

On Wed, Jan 14, 2015 at 5:19 PM, Brent Cook <notifications@github.com>
wrote:

> For meterpreter sessions, we could extend the API to explicitly state
> which view is desired explicitly (default, 32-bit, or 64-bit).
>
> For shell sessions, I don't see a way to do something similar using the
> 'reg' command: http://technet.microsoft.com/en-us/library/cc742028.aspx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapid7/metasploit-framework/issues/4589#issuecomment-70012666>
> .
>



-- 
- Josh

**Comment by bcook-r7** [comment]
Correction, there is a way via the /reg:32 | /reg:64 flags.

**Comment by kernelsmith** [comment]
yeah, it should be application-specific, so if reg32 then 32-bit view, if
reg64, then 64-bit view:
http://msdn.microsoft.com/en-us/library/windows/desktop/aa384129(v=vs.85).aspx,
so you should be able to just make sure which reg.exe one calls.  You can
also use the undocumented c:\windows\sysnative "alias" in case the
redirector is screwing the absolute path up "for you".

On Thu, Jan 15, 2015 at 11:20 AM, Joshua Smith <lazydj98@gmail.com> wrote:

> even if you specifically invoke the 64-bit version of reg.exe?
>
> On Wed, Jan 14, 2015 at 5:19 PM, Brent Cook <notifications@github.com>
> wrote:
>
>> For meterpreter sessions, we could extend the API to explicitly state
>> which view is desired explicitly (default, 32-bit, or 64-bit).
>>
>> For shell sessions, I don't see a way to do something similar using the
>> 'reg' command: http://technet.microsoft.com/en-us/library/cc742028.aspx
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rapid7/metasploit-framework/issues/4589#issuecomment-70012666>
>> .
>>
>
>
>
> --
> - Josh
>



-- 
- Josh

**Comment by bcook-r7** [comment]
thanks @kernelsmith 

It looks like I can append the new parameter to the appropriate stdapi_registry_* requests, and existing meterpreters will safely ignore it until they are updated.  So adding this won't require a meterpreter flag day :)

**Comment by kernelsmith** [comment]
nice!

On Thu, Jan 15, 2015 at 11:49 AM, Brent Cook <notifications@github.com>
wrote:

> thanks @kernelsmith <https://github.com/kernelsmith>
>
> It looks like I can append the new parameter to the appropriate
> stdapi_registry_* requests, and existing meterpreters will safely ignore it
> until they are updated. So adding this won't require a meterpreter flag day
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rapid7/metasploit-framework/issues/4589#issuecomment-70128719>
> .
>



-- 
- Josh

**Comment by wvu-r7** [comment]
Fixed in #4614.
