### ISSUE TITLE
bypassuacx86.exe command ?

### ISSUE THREAD

**Issue by lei720** [rapid7/metasploit-framework#4595]
hi, i want to upload the bypassuacx86.exe to the victim's 32 bit win7 machine ,and execute the "bypassuacx86.exe elevate /c veil.exe"  manually ,,,but i aways failt ... it return nothing .....any one can tell   
how to do it?? thacks very much...

**Comment by void-in** [comment]
Github issues are only to report bugs. Please use https://community.rapid7.com for such questions.
