### ISSUE TITLE
lots of railgun calls, e.g. running the golden ticket module #4388 run in a loop with a minimal railgun buffer, eventually causes meterpreter to free a bad pointer

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/metasploit-framework#4622]
Per the discussion on #4388, stressing railgun appears to eventually cause a crash on x86.
# Steps to Reproduce

run post/windows/escalate/golden_ticket module using steps outlined in #4388 repeatedly against Windows 7 x86 until the meterpreter session dies. For me, it takes about 30 tries.

**Comment by OJ** [comment]
From the testing I've done with the registry stuff (prior to you making fixes!) it does appear double-frees happen. Not cool!

**Comment by ccondon-r7** [comment]
@busterb Still an issue?
