### ISSUE TITLE
Fix 6,000 trailing comma msftidy warnings

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#4626]
As a result of #4593, we now have 6139 new msftidy info messages.

This is nonideal.

```
todb@mazikeen:~/git/rapid7/metasploit-framework$ tools/msftidy.rb modules/ | cut -f 2 -d "]" | cut -f 1 -d ":" | sort | uniq -c | sort -rn
   6139  Extraneous comma
     99  datastore is modified in code with '='
     12  datastore is modified in code with '<<'
      1  Explicitly requiring/loading rubygems is not necessary
```

Can you come up with a fix for these?

There is a lingering desire for msftidy.rb to be able to automatically fix things, too, but having test code modify code is always a scary thing. That said, this is an ideal test case. :)

**Comment by todb-r7** [comment]
/cc @wvu-r7 

and I agree with @jhart-r7 rubocop is much better suited for this sort of thing. :/ Its current level of noisiness and the difficulty in configuring it to be more surgical is the reason why it's not running automatically yet.

**Comment by todb-r7** [comment]
Note, a fix of rolling back #4593 is totally acceptable.

**Comment by todb-r7** [comment]
Vaguely related to #3853. Until this change, we had only datastore-class messages, which @wvu-r7 is once again actively attacking. I would like to get the msftidy complaints down to 0 so I can have travis start treating msftidy fails as real fails, and fail the build accordingly.

**Comment by FireFart** [comment]
Currently busy :( What about changing them to info or introduce a new category only shown when run with --verbose?
