### ISSUE TITLE
Blank username can cause an "undefined method `username'" error for the creds -u command

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4634]
I have some creds on my database, and then when I do this:

```
msf > creds -u Administrator
```

I get the following:

```
[-] Error while running command creds: undefined method `username' for nil:NilClass

Call stack:
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:872:in `block (2 levels) in creds_search'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:866:in `block in creds_search'
/Users/sinn3r/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:861:in `creds_search'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:973:in `cmd_creds'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/shell.rb:200:in `run'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/console.rb:38:in `start'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

**Comment by todb** [comment]
@wchen-r7, how did the creds get in the database? Can you provide some
reproduction steps?

**Comment by wchen-r7** [comment]
@todb-r7 When I reported the bug I didn't know much, either. It was a little tricky to figure out how to reproduce, but I figured out:

1. First, install TightVNC: http://www.tightvnc.com/ (Our module doesn't seem to work for RealVNC)
2. Use auxiliary/scanner/vnc/vnc_login
3. Make sure you get a successful login
4. Do ```creds -u Administrator```, and you should get that error.

It looks like what happens here is the vnc_login module creates a credential without a username (because VNC doesn't have one), and this results in core.public being nil, and then when db.rb reaches this code:

```
        # Exclude creds that don't match the given user
        if user_regex.present? && !core.public.username.match(user_regex)
          next
        end
```

core.public.username triggers ```undefined method `username' for nil:NilClass```

What's actually nasty about this is that if you have one bad ```core.public```, the creds -u command is completely useful (does not even show results partially)

**Comment by jlee-r7** [comment]
`nil` public is supposed to be fine in the data model. I see two options to fix this: 
- just make sure `core.public` exists before doing this check. This is the faster/simpler option, but allows the same bug to crop up elsewhere later.
- add a helper method to `Metasploit::Credentail::Core` for matching the username so we can change the offending line in `command_dispatcher/db.rb` to be something like 
```ruby 
if user_regex.present? && !core.public_match?(user_regex)
```

**Comment by todb-r7** [comment]
Tagging this as `jira` to remind myself to open a jira bug on this and direct @shuckins-r7's and @trosen-r7's attention to this bug. In the meantime, we (over here in open source land) need to get a lot better at triaging and fixing this kind of thing.

**Comment by trosen-r7** [comment]
@jlee-r7 I'm happy w/ your second idea on the fix here.

**Comment by todb-r7** [comment]
ya me too. Also unlabelling as jira b/c this is purely a msfconsole bug, not a cred model or cred handling bug outside of msfconsole, looks like.

**Comment by trosen-r7** [comment]
Looks like a relatively simple change to metasploit-credential to make this happen, no?

**Comment by jlee-r7** [comment]
Yeah, working on a PR for it now.

**Comment by todb-r7** [comment]
thanks @jlee-r7!
