### ISSUE TITLE
socks5 support as a server

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#4644]
As of right now Metasploit doesn't have a socks5 server (just aux/server/socks4a). Many tools are dropping support (or never had it |Burp Suite|) for socks4a. It would be nice to have a socks5 compliant server to proxy into Metasploit with

**Comment by jeffmcjunkin** [comment]
+1 and bump. Any thoughts from the Rapid7 team on this feature? Remote DNS and Burp integration are both nice wins for some common pivoting workflows.

**Comment by vysec** [comment]
+1

**Comment by mubix** [comment]
I've attempted this a couple of times but never could get it working correctly. SOCKS5 is much more complicated than 4a

**Comment by s00ner** [comment]
+1 SOCKS5 would be helpful.

**Comment by busterb** [comment]
Adam is working on this.

**Comment by fsacer** [comment]
auxiliary/server/socks5 exists so this can be closed.

**Comment by jeffmcjunkin** [comment]
Agreed, this issue can be closed. However, it looks like socks5 support is broken right now, per https://github.com/rapid7/metasploit-framework/issues/11513. 

At least in my testing and gboisec's, going through Windows 10 x64 1803 and some Linux system.

**Comment by ccondon-r7** [comment]
@jeffmcjunkin We fixed that a month or two ago and a couple folks tested it. If you run into any issues, please do open up a new issue and let us know! I'm gonna close this issue out, though as @acammack-r7 noted, UDP support and proper DNS tunneling (bigger Framework issue, I guess!) are good for us to keep in mind for the future.
