### ISSUE TITLE
Allow msfvenom -l to be more grepable

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4662]
So when you do this:

```
msfvenom -l payloads | grep -i windows
```

You can't grep because msfvenom is using stderr. This should be stdout.

See:
https://twitter.com/_sinn3r/status/560593357672427520

Edit: Some descriptions are also too long which make them not grep-friendly.

**Comment by bcook-r7** [comment]
Sounds good to me, though its easy to get around:

```
msfvenom -l payloads 2>&1 | grep -i windows
```

On a related 'grepability' node, quite a few of the descriptions do not fit on a line or even in a 'regular' window width. Would it be OK to clean those up too?

**Comment by wchen-r7** [comment]
> On a related 'grepability' note, quite a few of the descriptions do not fit on a line or even in a 'regular' window width. Would it be OK to clean those up too?

How do you do that without modifying the modules?

**Comment by wvu-r7** [comment]
1. ```|&```
2. ```fmt -80```

**Comment by wchen-r7** [comment]
How do you do that on Windows?

**Comment by wvu-r7** [comment]
You don't. :)

**Comment by wchen-r7** [comment]
Is there a Ruby way?

**Comment by wvu-r7** [comment]
I'm kinda with @bcook-r7 on this one. Using your filters is the Unix Way. The output should be stdout to begin with, though. I'll merge #4663 in a bit.

**Comment by bcook-r7** [comment]
something like this would be nice to make the descriptions parseable too:

```
diff --git a/msfvenom b/msfvenom
index 67c6c4c..7b8077c 100755
--- a/msfvenom
+++ b/msfvenom
@@ -208,7 +208,7 @@ require 'msf/core/payload_generator'
             ])

     framework.payloads.each_module { |name, mod|
-      tbl << [ name, mod.new.description ]
+      tbl << [ name, mod.new.description.split.join(' ') ]
     }

     "\n" + tbl.to_s + "\n"
```

**Comment by wchen-r7** [comment]
Yeah I'll do that.

**Comment by wvu-r7** [comment]
Thanks, guys.

**Comment by kernelsmith** [comment]
I believe stderr was used on purpose so people could redirect stdout to a file. If you add to stdout you will corrupt payloads created with that technique. I realize people should be using -o for that but I don't think everyone does

**Comment by wchen-r7** [comment]
I'm kind of confused. But when you're using -l you never use -p, so you don't generate a payload, how do they end up conflicting with each other?

**Comment by wvu-r7** [comment]
What @wchen-r7 said.

**Comment by kernelsmith** [comment]
I think you can safely get away with it for this specific case, but I'm guessing the initial approach was to send everything to stderr that was not payload so as to avoid problems.  If -l short circuits the arg processing and the -p is never really run, then I imagine it's fine

**Comment by kernelsmith** [comment]
The more important question is whether grepable should be spelled with two p's or one ;)
Also applies to grippable which came up in college when the water polo team was getting shirts that said "we have grippable balls" (my roommate was on the team)

**Comment by wchen-r7** [comment]
greppable.

**Comment by wvu-r7** [comment]
FWIW, I used "greppable" in the commit message.

**Comment by wvu-r7** [comment]
Changed. :3

**Comment by kernelsmith** [comment]
lol
