### ISSUE TITLE
The upload command cannot rename the destination file

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4665]
This scenario is for uploading something to a windows box.

This example works fine:
```
meterpreter > upload /tmp/blah.exe C:\\
```

But this example doesn't. You will get "[-] core_channel_open: Operation failed: The system cannot find the path specified."
```
meterpreter > upload /tmp/blah.exe C:\\what.exe
```

This example works again.
```
meterpreter > upload /tmp/blah.exe C:\\blah.exe
```

So it looks like you can't change the destination filename when you upload.

**Comment by bcook-r7** [comment]
for this command:
```
upload HACKING  MONKEY
```

meterpreter gets told to open a channel to a file called:
```
MONKEY\HACKING
```
which fails, because there is no folder called MONKEY on the target

**Comment by wchen-r7** [comment]
So when I do: ```meterpreter > upload /tmp/blah.exe C:\\what.exe```, I am actually telling meterperter to upload my file to a C:\\what.exe\\ folder?

**Comment by bcook-r7** [comment]
Yeah. It eventually calls File.upload in lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb, which is documented as doing this:

```
225   #
226   # Upload one or more files to the remote remote directory supplied in
227   # +destination+.
228   #
229   # If a block is given, it will be called before each file is uploaded and
230   # again when each upload is complete.
231   #
232   def File.upload(destination, *src_files, &stat)
```

That's a little different than the way one would expect a filesystem to behave - maybe upload should stat dst and do upload_file or upload depending on if dst is a directory or not. That fail if someone changed the file between stat and upload, but would diminish the 'principal of least surprise' here.

**Comment by bcook-r7** [comment]
oh, in the case of the destination not being specified, it does the more expected thing, sure.

**Comment by bcook-r7** [comment]
This should be improved in #4666

**Comment by anonymous012** [comment]
the right command:  meterpreter > upload /tmp/blah.exe C:\\blah.exe

i get uploading...
uploaded...

when i go into shell i can't find the folder i uploaded 

some help please..

**Comment by bcook-r7** [comment]
if you are using the '\' character, be sure to escape it like this:

upload /tmp/blah.exe C:\\blah.exe

or, you can use the / character just as well:

upload /tmp/blah.exe C:/blah.exe

I suspect your file got uploaded with a name where the file has a \b character embedded in it.

**Comment by anonymous012** [comment]
so i have so seach for /b(file) ?

**Comment by nuriyavuz** [comment]
> 
> 
> This scenario is for uploading something to a windows box.
> 
> This example works fine:
> 
> ```
> meterpreter > upload /tmp/blah.exe C:\\
> ```
> 
> But this example doesn't. You will get "[-] core_channel_open: Operation failed: The system cannot find the path specified."
> 
> ```
> meterpreter > upload /tmp/blah.exe C:\\what.exe
> ```
> 
> This example works again.
> 
> ```
> meterpreter > upload /tmp/blah.exe C:\\blah.exe
> ```
> 
> So it looks like you can't change the destination filename when you upload.

Try  inc /etc directory or another writable directory,i mean the problem is about permission.
