### ISSUE TITLE
screenshot -v will never work because the option is hardcoded as false

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4672]
If you do the following:

```
meterpreter > screenshot -v true
```

You will see that the -v flag does not automatically open the file for you. The problem is really simple: the view variable is always false (default as false, the only assignment for it is false), so it's always false. Bug here:

https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/ui.rb#L153

**Comment by wvu-r7** [comment]
Wow, haha. Nice bug.
