### ISSUE TITLE
enum_cred_store misbehaves on x64

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#4696]
This happens for me on most x64 sessions:
```
msf post(enum_cred_store) > run

[*] 4702111233380188160 credentials found in the Credential Store
[*] Decrypting each set of credentials, this may take a minute...
```
In this case it's a Windows 2012 machine. The credential number is clearly incorrect, and here it just hangs as if it is actually looping through that many credentials.

I'll try looking into this a bit more shortly and come up with a fix unless someone else beats me to it.

**Comment by OJ** [comment]
Goddamit. i've already submitted this, and it was a dup that time too!. Closing.

**Comment by kernelsmith** [comment]
LOL

**Comment by jlee-r7** [comment]
#3916
