### ISSUE TITLE
GetPC routine is missing for x86/alpha_mixed when using msfvenom

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4717]
I don't have a lot of information at the moment, but to reproduce, first do this:

```
./msfvenom -p windows/meterpreter/bind_tcp -e x86/alpha_mixed -f raw
```

Your payload will look like this:

![screen shot 2015-02-06 at 12 53 31 am](https://cloud.githubusercontent.com/assets/1170914/6075572/9f7a0418-ad9a-11e4-811d-bbdcddbf935a.png)

But if you do this with msfpayload and msfencode:

```
./msfpayload windows/meterpreter/bind_tcp R |./msfencode -e x86/alpha_mixed -t raw
```

You will get:

![screen shot 2015-02-06 at 12 54 17 am](https://cloud.githubusercontent.com/assets/1170914/6075578/c4ebdf14-ad9a-11e4-8dbd-eaab7b749914.png)

As you can see, msfpayload/msfencode one contains some non-alphanumeric bytes in the beginning, that's the getpc routine. The one generated by msfvenom doesn't have this.

**Comment by wchen-r7** [comment]
Ah I sort of figured out.

When I am using msfvenom, the AllowWin32SEH option is always kicking in.

When I am using msfencode, it does not. And that actually gives me what I want.

**Comment by wchen-r7** [comment]
Here's a workaround for that:

```
./msfvenom -p windows/meterpreter/bind_tcp -e x86/alpha_mixed allowwin32seh=no -f raw
```

And you will see getpc again.

**Comment by corelanc0d3r** [comment]
so setting that option to no by default, inside msfvenom, fixes the problem then ? ;-)

**Comment by wchen-r7** [comment]
Looks that way.

I need to look into if there are any side effects if I change this default behavior.

**Comment by wchen-r7** [comment]
It looks like some people are disagree on what the default should be:

Over here in Msf::Encoder::Alphanum, you can see that AllowWin32SEH is false by default:
https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/encoder/alphanum.rb#L22

And then in the alpha_mixed and alpha_upper encoder modules, they decide to override that by hardcoding AllowWin32SEH to true all the time:
https://github.com/rapid7/metasploit-framework/blob/master/modules/encoders/x86/alpha_mixed.rb#L63

**Comment by wchen-r7** [comment]
@corelanc0d3r, I think the question comes down to this:

When you know your encoder is for Windows, why should it not use AllowWin32SEH?

**Comment by wchen-r7** [comment]
Fix in progress.
