### ISSUE TITLE
Rework the sounds plugin

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4733]
I think people can improve this. Somebody should either voice it, or just redo the sound effects. Ideally they should be short also (keep the sound files small please)

Your sound is magic, and may become the most memorable feature people will remember for years. Use your creativity.

If you are looking for ideas, here are some pretty successful sound effects:

1. In a BMW, this is always the first thing you hear, and according to BMW people find this pleasant and want to drive the car:
https://www.youtube.com/watch?v=__0Od--6_FE

2. If you were an ICQ fan in the 90s, this sound is stuck in your brain forever:
https://www.youtube.com/watch?v=6iCPIUGnHQ8

3. AOL: "You've got mail!" Used by Hollywood multiple times.
https://www.youtube.com/watch?v=DGOgSPVBmIE

If there are multiple submissions, we'll let the community decide. If possible, we can merge submissions too.

If you don't have a dev environment setup, here's how:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

If you have Kali, maybe it's a little bit easier (you need to create a github account first, fork rapid7's msf framework, and then clone your fork):
https://www.youtube.com/watch?v=IBGb_uOzJqs

Here's how to submit a pull request (submission):
https://help.github.com/articles/using-pull-requests/

**Comment by wvu-r7** [comment]
People actually use this? I've used it once... I think we discussed having William Shatner voice it, but my hopes aren't high. :)

**Comment by wvu-r7** [comment]
[![Sabataage](https://img.youtube.com/vi/nlOTRxt-dIw/0.jpg)](https://www.youtube.com/watch?v=nlOTRxt-dIw)

**Comment by wchen-r7** [comment]
It was cool to come up with the plugin. I don't use it because I can't stand the computer generated voice. Especially when I keep getting shells, the voice drives me nuts. Popping shells is supposed to be a pleasant/happy/exciting thing but the sound effect doesn't reflect this.

**Comment by wchen-r7** [comment]
Samuel Westerfeld is interested in this PR and has asked me some questions. I don't know his Github account yet so I can't tag him here, but if anybody else is interested in working with Samuel, you can find him here: https://twitter.com/swesterfeld

**Comment by wvu-r7** [comment]
For the time being, I'm using Siri's voice.

**Comment by todb-r7** [comment]
I have a fantasy of shipping Jen Ellis' voice. Or someone else who sounds British and smart.

**Comment by kernelsmith** [comment]
I vote for Homer Simpson

**Comment by wchen-r7** [comment]
Lack of momentum in this feature request, please feel free to reopen if interested. Thanks for the comments.
