### ISSUE TITLE
uninitialized constant SocialEngineering

### ISSUE THREAD

**Issue by godescbach** [rapid7/metasploit-framework#4734]
Had just start Metasploit and tried to search at the console prompt got the following errors.  Appears to be new issue according to chat on metasploit channel with wvu & DaemeonZane.

msf > db_status
[*] postgresql connected to msf3
msf > search spooler
[!] Database not connected or cache not built, using slow search
[-] Error while running command search: uninitialized constant SocialEngineering

Call stack:
/opt/metasploit/apps/pro/modules/auxiliary/pro/social_engineering/email_track.rb:39:in `initialize'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:54:in `new'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:54:in `create'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:27:in `[]'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:75:in `block in each'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:74:in `each'
/usr/share/metasploit-framework/lib/msf/core/module_set.rb:74:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1493:in `block in cmd_search'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1486:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1486:in `cmd_search'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:200:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'

**Comment by void-in** [comment]
Not a new issue. It was earlier reported at https://github.com/rapid7/metasploit-framework/issues/3797. In that case a reboot of the machine did the trick. It is a bit strange to go away with the suggested solution however it worked for multiple people.

**Comment by hmoore-r7** [comment]
cc @todb-r7

**Comment by wvu-r7** [comment]
Issue opened for posteriority, apparently. Reboot fix worked for @godescbach. Closing.

**Comment by hmoore-r7** [comment]
Is rebooting considered a fix? Is this the case of an update applied, but prosvc not being restarted?

**Comment by wvu-r7** [comment]
@hmoore-r7: Yeah, that seems to be the case. Multiple people have reported the same problem, and rebooting cleared things up. Problem referenced in #3797, #4407, and #4464.

**Comment by hmoore-r7** [comment]
@wvu-r7 thanks!
