### ISSUE TITLE
shodan_search fails with "NameError unitialized constant Net::DNS"

### ISSUE THREAD

**Issue by kartoch** [rapid7/metasploit-framework#4764]
msf > use auxiliary/gather/shodan_search
    msf auxiliary(shodan_search) > check
    [-] Check failed: The following options failed to validate: SHODAN_APIKEY, QUERY.
    msf auxiliary(shodan_search) > set SHODAN_APIKEY ABCDEF123456 # (using a valid pro key)
    SHODAN_APIKEY => ABCDEF123456
    msf auxiliary(shodan_search) > set DATABASE true
    DATABASE => true
    msf auxiliary(shodan_search) > set MAXPAGE 99999
    MAXPAGE => 99999
    msf auxiliary(shodan_search) > set OUTFILES shodan.txt
    OUTFILES => shodan.txt
    msf auxiliary(shodan_search) > set QUERY net:1.2.3.0/24
    QUERY => net:1.2.3.0/24
    msf auxiliary(shodan_search) > run
    
    [-] Auxiliary failed: NameError uninitialized constant Net::DNS
    [-] Call stack:
    [-]   /usr/share/metasploit-framework/modules/auxiliary/gather/shodan_search.rb:88:in `shodan_rhost'
    [-]   /usr/share/metasploit-framework/modules/auxiliary/gather/shodan_search.rb:99:in `run'
    [*] Auxiliary module execution completed
    msf auxiliary(shodan_search) >

**Comment by wchen-r7** [comment]
eh, yeah, that's a bug for sure.

**Comment by wchen-r7** [comment]
Patch is up as #4767. @kartoch, if you'd like, please feel free to test that patch, and then we'll merge it asap.

**Comment by wchen-r7** [comment]
Oh never mind, someone is working on it! :-)
