### ISSUE TITLE
msfrpc/msfrpcd forgets the auth token after a set period of time

### ISSUE THREAD

**Issue by kernelsmith** [rapid7/metasploit-framework#4821]
start msfrpcd:

```Shell
ruby msfrpcd -U lameuser -P lamepass
```
connect w/msfrpc

```Shell
ruby msfrpc -U lamepass -P lamepass -a YERIP
```
wait for 5-10 mins, run any rpc call:

```Ruby
>> rpc.call("console.list")
Msf::RPC::ServerException: Msf::RPC::Exception Invalid Authentication Token ["lib/msf/core/rpc/v10/service.rb:148:in `process'", "lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `call'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:365:in `dispatch_request'", "lib/rex/proto/http/server.rb:299:in `on_client_data'", "lib/rex/proto/http/server.rb:158:in `block in start'", "lib/rex/io/stream_server.rb:48:in `call'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:192:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:190:in `each'", "lib/rex/io/stream_server.rb:190:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `call'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:100:in `call'", "lib/msf/core/thread_manager.rb:100:in `block in spawn'"]
	from /home/ks/gits/metasploit-framework/lib/msf/core/rpc/v10/client.rb:76:in `call'
	from (irb):10:in `<main>'
	from /home/ks/gits/metasploit-framework/lib/rex/ui/text/irb_shell.rb:47:in `rescue in block in run'
	from /home/ks/gits/metasploit-framework/lib/rex/ui/text/irb_shell.rb:44:in `block in run'
```

**Comment by kernelsmith** [comment]
I'm sure this is related to the proper functioning of the auth timeout functionality, but it's very unexpected when you have an active msfrpc session.

**Comment by kernelsmith** [comment]
ahh, yeah, it's the following expected behavior from service.rb:

```
self.token_timeout      = self.options[:token_timeout] || 300
```
Maybe we can expose an option to either initiate with a permanent token, or consider local connections to be permanent, or maybe increase the timeout for locally-connected tokens?

**Comment by hmoore-r7** [comment]
There is an API call for creating a permanent token, so the expected process would be the authenticate with username/password, get your temporary token, use that token to create a permanent token, and skip the login process going forward. For local connections, the timeout could probably be increased as well (assuming the idle client does something every X seconds, it stays alive though).

**Comment by kernelsmith** [comment]
ok, yeah I figured I wasn't conforming to the expected pattern, thanks for explaining the expected process, super useful.  I don't think this is really a bug, maybe a feature request at best, so Ima close
