### ISSUE TITLE
Capture mixin capture_sendto() is causing packet loss

### ISSUE THREAD

**Issue by hdm** [rapid7/metasploit-framework#4825]
While testing the nbns_spoof module on a remote system accessed over SSH, each time `capture_sendto()` is called, I temporarily lose network access to the machine. A ping command running on the remote system confirms that all outbound traffic is being dropped during this operation:

```
25 packets transmitted, 17 received, 32% packet loss, time 24009ms
```

File shares are being disconnected as well when this happens:

```
[2130247.366473] CIFS VFS: Server 192.168.0.240 has not responded in 120 seconds. Reconnecting...
```

The problem seems to be triggered by `lookup_eth()`. The odd part is that the "dropped" traffic is being received by the interface (according to tcpdump). The system in question uses a round-robin bonded NIC pair, so there is some chance that the issue is configuration specific.

**Comment by hmoore-r7** [comment]
Confirmed that this issue is not present when using non-bonded NICs (bond-mode 0).

**Comment by adfoster-r7** [comment]
Attic'ing as it looks like other community members haven't run into this issue since it was originally raised
