### ISSUE TITLE
Issues with http_login module and NTLM authentication to OWA

### ISSUE THREAD

**Issue by rwhitcroft** [rapid7/metasploit-framework#4841]
These issues stem from trying to use the http_login module to authenticate against an SSL service using NTLM (e.g. /ews/ - Exchange web service).

Issue 1: lib/metasploit/framework/login_scanner/http.rb considers only code 200 as a successful login; however, in the case of EWS and likely others, a 302 or 403 may also indicate a successful login.

Issue 2: on servers where multiple auth mechanisms are supported (e.g., Basic and NTLM), lib/rex/proto/http/client.rb will authenticate against the first mechanism as set in the if/else chain, preventing NTLM authentication where Basic is also offered, for example, as Basic is tested first.

**Comment by hmoore-r7** [comment]
Solving this would require adding options to prefer NTLM over Basic and allowing non-200 response codes to indicate success.
