### ISSUE TITLE
Msf::Payload::Generic does not handle --platform for msfvenom

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4866]
An example:

```
$ ./msfvenom -p generic/shell_reverse_tcp --platform windows --arch x86 -f raw
A platform could not be determined by the generic payload
```

Here's what you actually need to do to pass that information:

```
$ ./msfvenom -p generic/shell_reverse_tcp platform=windows -f raw
```

But you will get another error, a different bug (filed separately). But by passing the datastore option, you should see that value in Msf::Payload::Generic.

I can't decide if this is actually a bug or not. It feels like --platform should set that for me.

**Comment by bcook-r7** [comment]
Setting --platform satisfies the principal of least-surprise. I agree!
