### ISSUE TITLE
Meterpreter and Large PIDs

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4869]
Trying to use payload_inject but was getting some invalid PID error. 

The machine had probably been up a long time as the PIDs generated were > 102496. Even specifying a pid in the payload_inject module did not work.

Is the PID value being treated as an int rather than a uint or not a large enough datatype?

**Comment by Meatballs1** [comment]
Prod @OJ

**Comment by Meatballs1** [comment]
Don't think its an x64 issue as system was only x86.

**Comment by Meatballs1** [comment]
Looks like its being handled properly as a DWORD in meterpreter and ruby source, so not a clue.

**Comment by OJ** [comment]
That does look strange. We have another issue with `payload_inject` on fully patched Windows 8.1 too https://github.com/rapid7/metasploit-framework/issues/4845 However I doubt it's related.

**Comment by Meatballs1** [comment]
Or isit due to being on x86 and the HANDLE is being cast as a QWORD?

```
	if (handle)
		packet_add_tlv_qword(response, TLV_TYPE_HANDLE, (QWORD)handle);

```

**Comment by OJ** [comment]
_THAT_ looks fishy :)

**Comment by OJ** [comment]
I'm starting to think that we're going to have to add a new `TLV_META_TYPE` that matches the target arch.

**Comment by OJ** [comment]
@Meatballs1 are you still seeing this in your envs? I can't repro it on my side.

**Comment by Meatballs1** [comment]
I cant reproduce in normal VMs, this was on a job with a long running system which must have been going through a lot of processes and somehow was getting really large PIDs.

Maybe could reproduce by scripting something to start a lot of processes over and over?

**Comment by OJ** [comment]
> Is the PID value being treated as an int rather than a uint or not a large enough datatype?

The PID is a DWORD, which is exactly what the Windows API expects, so this isn't the issue.

> Or isit due to being on x86 and the HANDLE is being cast as a QWORD?

Nope, as long as it's cast back at the right time, we're good.

I'm raising this from the dead as it has been up for discussion behind the scenes. Pretty sure this isn't an issue any more. So I'm going to close it and if someone has issues similar to this we can fire up another issue and chase it down.
