### ISSUE TITLE
Handler says I'm sending the stage to myself

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4872]
This appears to be a minor issue, I just think it's a little weird.

Please do this:

1. Generate a windows/meterpreter/reverse_tcp executable with msfpayload or msfvenom
2. Drag and drop the executable to a Windows machine
3. Start msfconsole
4. Set up a multi-handler for windows/meterpreter/reverse_tcp
5. Double-click on the executable to get a shell
6. Pay close attention to what msfconsole says where the stage is sent to. The IP is actually the attacker's IP, not the victim's IP.

Screenshot - as you can see my victim's IP is 192.168.1.128, so on msfconsole shouldn't it say "Sending stage (770048 bytes) to 192.168.1.128"?

![screen shot 2015-03-03 at 9 21 47 pm](https://cloud.githubusercontent.com/assets/1170914/6477655/752aaf5e-c1eb-11e4-8354-3b2fd07df044.png)

**Comment by bcook-r7** [comment]
No proxy?

**Comment by wchen-r7** [comment]
No.

**Comment by OJ** [comment]
Is the victim a VM on the same machine and you're using NAT?

**Comment by wchen-r7** [comment]
Oh!

Oops, yeah I just noticed I've been on NAT the whole time. Usually I'm on bridged.

I should close this now. There's nothing wrong.

**Comment by OJ** [comment]
```
\o/
 | 
/ \
```

**Comment by bcook-r7** [comment]
Nice!  I've got stockholm/virtualbox syndrome and didn't expect NAT to work correctly to the host from the VM :)
