### ISSUE TITLE
Payload size calculations should normalize the datastore first

### ISSUE THREAD

**Issue by hdm** [rapid7/metasploit-framework#4931]
Payload sizes are determined by calling payload_module.new.size, this operation doesn't apply normalization to the datastore for the module's options, which results in invalid behavior.

For example, any OptBool datastore options will always be set to true, since `"false"` is truthy. The fix would be to determine whether the datastore has been normalized in the `size()` method and normalize it if needed. This would remove the need for a bunch of existing hacks, but will require some sane defaults to be set for things like `LHOST`, otherwise the normalization will fail due to option validation errors.

**Comment by hmoore-r7** [comment]
A recent example of where this was a problem, commit hash 0d12ca49a7c684ed3acfc9a44c828d409e99bb9e.

**Comment by busterb** [comment]
I don't think this is actually required anymore, at least not for bool, since OptBool returns a true/false without normalization, not a string.
