### ISSUE TITLE
Make User-Agent easier to control across modules and more consistent

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#4933]
Source http://blog.didierstevens.com/2015/03/16/quickpost-metasploit-user-agent-strings/

**Comment by Chiggins** [comment]
Not knowing much about the source and how options are handled, but what if Metasploit had one default User-Agent string and all modules used that, unless otherwise specified via set/setg?

**Comment by hmoore-r7** [comment]
That is mostly the case today, but some modules redefine the default, this ticket would be to clear those defaults and rely on a consistent option (such as the one the HttpClient mixin offers).

**Comment by OJ** [comment]
Could be fun to have a generator that generates UA strings so that each case is different :)

**Comment by pyrohaz4good** [comment]
@hmoore-r7 Didier's post is very must the exact reason for #4984 :-)

**Comment by wchen-r7** [comment]
Some modules don't really need to redefine the user-agent. But it looks like most of them are pretty old so it's kind of hard to find the vulnerable software and verify (especially the memory corruption ones).

**Comment by bcook-r7** [comment]
We added a common user agent list to meterpreter, closing.
