### ISSUE TITLE
Help please! :( 

### ISSUE THREAD

**Issue by andreevpix** [rapid7/metasploit-framework#4979]
root@kali:/usr/share# service postgresql start
[ ok ] Starting PostgreSQL 9.1 database server: main.
root@kali:/usr/share# service metasploit start
[ ok ] Starting Metasploit rpc server: prosvc.
[....] Starting Metasploit web server: thin/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:62:in `gemspec': There are no gemspecs at /opt/metasploit/apps/pro/msf3. (Bundler::InvalidOption)
	from /opt/metasploit/apps/pro/Gemfile:29:in `eval_gemfile'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:32:in `instance_eval'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:32:in `eval_gemfile'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/dsl.rb:10:in `evaluate'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/definition.rb:25:in `build'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler.rb:155:in `definition'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler.rb:118:in `setup'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/bundler-1.8.5/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/metasploit/apps/pro/ui/scripts/ctl.rb:30:in `start_thin'
	from /opt/metasploit/apps/pro/ui/scripts/ctl.rb:47:in `<main>'
root@kali:/usr/share# service metasploit status
[FAIL] Metasploit rpc server is not running ... failed!
[FAIL] Metasploit web server is not running ... failed!
[FAIL] Metasploit worker is not running ... failed!
root@kali:/usr/share#

**Comment by void-in** [comment]
Use https://community.rapid7.com for community support. This is the issues page for reporting bugs.

**Comment by OJ** [comment]
+1 @void-in. @andreevpix please use the link provided above.
