### ISSUE TITLE
x509 certification generation in Rex:Socket:SSLTcpServer is suspicious looking

### ISSUE THREAD

**Issue by pyrohaz4good** [rapid7/metasploit-framework#5009]
Rex:Socket:SSLTcpServer generates a certificate based upon a random set of characters for a CN as well as a fake domain name. This looks suspicious network monitoring. There's a good blog post about this at http://www.netresec.com/?page=Blog&month=2011-07&post=How-to-detect-reverse_https-backdoors.

Fortunately the reverse_https payload allows you to specify your own PM file in advanced settings, although I don't think this is widely used. 

Would it be worthwhile to have a slightly more realistic generation mechanism? Or alternatively, add additional options so the user can specify a few parameters for the certificate that they would like to use and then generate it when setting up the handler?

Willing to work on this if someone comes up with a clever way to deal with it.

**Comment by void-in** [comment]
The certificate can be easily created through openssl if custom parameters are required. Everything the framework produce is randomized in order to defeat static signatures. I don't think it is easier to generate a cert with user defined CN and other parameters by setting multiple datastore options when the same can be done through the openssl in a single command and then configured in the handler.

**Comment by pyrohaz4good** [comment]
Fair enough.

What about randomizing the certificate validity? It's currently statically
set to 1 week.

**Comment by hmoore-r7** [comment]
@pyrohaz4good We redid SSL generation last fall so that generated certificates now match default "snakeoil" certificates on common Linux distributions. You can set a global ```HandlerSSLCert``` option in msfconsole if the random default does not appeal. Marking as closed since we already addressed the main issue.

**Comment by hmoore-r7** [comment]
@pyrohaz4good The article is really out of date (expiration dates were changed a long time ago as well)
