### ISSUE TITLE
Several auxiliary scanner modules produce error "column web_vulns.category does not exist"

### ISSUE THREAD

**Issue by reider-roque** [rapid7/metasploit-framework#5022]
Platform/Version information:
```
root@kali:/tmp# lsb_release -d
Description:	Kali GNU/Linux 1.1.0
root@kali:/tmp# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kali:/tmp# apt-cache show metasploit-framework | grep Version
Version: 4.11.1-2015031701-1kali0
```

I stumbled upon this error while exploring the *wmap* plugin. The following command sequence initiates scanning of OWASP Mutillidae webapp. The output contains four *'column web_vulns.category does not exist'* errors:
```
load wmap
wmap_sites -a http://192.168.33.102
wmap_targets -t http://192.168.33.102/mutillidae/index.php
wmap_run -e
```

Apparently those errors are produced by the modules when they can't add found vulnerabilities into the DB (`wmap_vulns -l` returns no output after the scan is done). Checking the *msf3.web_vulns* database schema with `psql` I can confirm that it doesn't have *category* column; I see only *category_id* field.

The four modules producing errors in this wmap scan case are:
```
auxiliary/scanner/http/scraper
auxiliary/scanner/http/brute_dirs
auxiliary/scanner/http/dir_scanner
auxiliary/scanner/http/files_dir
```

Running `auxiliary/scanner/http/scraper` module manually produces the same error:
```
msf> use auxiliary/scanner/http/scraper
msf> set RHOSTS 192.168.33.102
msf> run
[*] [192.168.47.129] / [Metasploitable2 - Linux]
[*] Error: 192.168.47.129: ActiveRecord::StatementInvalid PG::UndefinedColumn: ERROR:  column web_vulns.category does not exist
LINE 1: ...name" = '' AND "web_vulns"."name" = 'scraper' AND "web_vulns...
                                                             ^
: SELECT  "web_vulns".* FROM "web_vulns"  WHERE "web_vulns"."web_site_id" = 3 AND "web_vulns"."path" = '/' AND "web_vulns"."method" = 'GET' AND "web_vulns"."pname" = '' AND "web_vulns"."name" = 'scraper' AND "web_vulns"."category" = 'scraper' AND "web_vulns"."query" = '' LIMIT 1
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed

```

**Comment by bcook-r7** [comment]
The issue appears to be incompatible schemas between the Pro and Framework databases. A workaround could be to drop the existing database and recreate, handle this exception directly, or to unify the schemas between Pro and Framework.

**Comment by hydhyd** [comment]
Also on Kali 1.1.0; can confirm that dropping msf3 and restarting msfconsole seems to be a working fix.

**Comment by bcook-r7** [comment]
Hmm, then could also just be a database migration problem too. Thanks for the note.

**Comment by wchen-r7** [comment]
Ok so.... what do you guys think we should do next? We use the workaround (dropping msf3) and close this ticket, or we add a patch that can handle this type of stuff better? Maybe @limhoff-r7 has an opinion?

**Comment by hmoore-r7** [comment]
We either need to port the wmap* modules to the Pro schema, change the Pro schema not to step on framework, or remove the offending modules.

**Comment by hmoore-r7** [comment]
Nevermind, re-read the ticket backlog, just a bad local schema

**Comment by hmoore-r7** [comment]
@wchen-r7 The user would have to rebuild the schema, a helper command for purge/rebuild within msfconsole might make this easier.

**Comment by trosen-r7** [comment]
Tracking internally as MSP-12840

**Comment by trosen-r7** [comment]
I'm looking now at the impact of just moving these migrations from Pro to metasploit_data_models

**Comment by trosen-r7** [comment]
After some investigation, i think that this is due to bad state in the end user's environment. It is currently possible to "accidentally" boot the version of Metasploit Pro that ships w/ Kali. This will be moot in about a month. I'm going to close this due to that fact and the fact that there is a workaround available.
