### ISSUE TITLE
Banner error

### ISSUE THREAD

**Issue by g33xter** [rapid7/metasploit-framework#5053]
I'm getting this error after executing 'banner' cmd.

**Comment by wvu-r7** [comment]
Not seeing this. Can you provide more details about your setup?

**Comment by todb-r7** [comment]
Looks like Kali

**Comment by todb-r7** [comment]
pre-emptively deleting your screenshot @g33xter, i suspect infoleak

**Comment by g33xter** [comment]
Yea, it is kali linux 1.1.0‎ Moto. After updating today I'm getting that error.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Tod BeardsleySent: Thursday, April 2, 2015 00:10To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)Looks like Kali

—Reply to this email directly or view it on GitHub.

**Comment by g33xter** [comment]
What? Info leak?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: Tod BeardsleySent: Thursday, April 2, 2015 00:12To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)pre-emptively deleting your screenshot @g33xter, i suspect infoleak

—Reply to this email directly or view it on GitHub.

**Comment by todb-r7** [comment]
The bug implies that you either do not have a logos_directory, or you don't have permissions for it. Are you running as root, as is normal in Kali-land?

**Comment by todb-r7** [comment]
Talking about the infoleak will further exacerbate the infoleak. :) Just look at your screenshot carefully. Also, testing on Kali right quick.

**Comment by g33xter** [comment]
I do have a logos directory & even I've my own banners in that directory. And yea I'm running as a root.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Tod BeardsleySent: Thursday, April 2, 2015 00:16To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)The bug implies that you either do not have a logos_directory, or you don't have permissions for it. Are you running as root, as is normal in Kali-land?

—Reply to this email directly or view it on GitHub.

**Comment by g33xter** [comment]
The other day metasploit gems were giving error because of ruby 2.1.x. As in new gems will nit run on 1.9.x.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Tod BeardsleySent: Thursday, April 2, 2015 00:18To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)Talking about the infoleak will further exacerbate the infoleak. :) Just look at your screenshot carefully. Also, testing on Kali right quick.

—Reply to this email directly or view it on GitHub.

**Comment by todb-r7** [comment]
What version are you on? I'm unable to reproduce. What does `version` say?

**Comment by todb-r7** [comment]
FWIW the latest I have on Kali is: v4.11.1-2015032401

Though I suspect the 64-bit version is being built now.

**Comment by g33xter** [comment]
My kali linux is 1.1.0 & my metasploit version is 4.11 which is pulled from git.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Tod BeardsleySent: Thursday, April 2, 2015 01:08To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)What version are you on? I'm unable to reproduce. What does version say?

—Reply to this email directly or view it on GitHub.

**Comment by void-in** [comment]
Can't reproduce at my end as well. Kali latest x64 and git fetch upstream.

**Comment by g33xter** [comment]
What is the ruby version you're using?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: void-inSent: Thursday, April 2, 2015 10:59To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)Can't reproduce at my end as well. Kali latest x64 and git fetch upstream. 

—Reply to this email directly or view it on GitHub.

**Comment by void-in** [comment]
@g33xter Ruby version 2.1.5. I believe you are running 2.1.5 as well?

**Comment by g33xter** [comment]
Yeah, but getting errors after executing msfconsole                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   From: void-inSent: Thursday, April 2, 2015 11:13To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)@g33xter Ruby version 2.1.5. I believe you are running 2.1.5 as well?

—Reply to this email directly or view it on GitHub.

**Comment by todb-r7** [comment]
> My kali linux is 1.1.0 & my metasploit version is 4.11 which is pulled from git

Ah ha.

If you pulled metasploit-framework from git, but are still seeing messages about errors coming up in /opt/, you are almost certainly running into a mixed environment problem.

To isolate your git checkout, see: http://r-7.co/MSF-DEV, now with 100% more Kali friendliness.

This is strongly feeling like a can't reproduce problem. If you have something more on this, though, please feel free to update the bug and I'll reopen (no need to open another bug, watchers still get updates on closed bugs).

**Comment by g33xter** [comment]
Thanks so much. I'll have look on that.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    From: Tod BeardsleySent: Friday, April 3, 2015 01:19To: rapid7/metasploit-frameworkReply To: rapid7/metasploit-frameworkCc: g33xterSubject: Re: [metasploit-framework] Banner error (#5053)
My kali linux is 1.1.0 & my metasploit version is 4.11 which is pulled from git


Ah ha.

If you pulled metasploit-framework from git, but are still seeing messages about errors coming up in /opt/, you are almost certainly running into a mixed environment problem.

To isolate your git checkout, see: http://r-7.co/MSF-DEV, now with 100% more Kali friendliness.

This is strongly feeling like a can't reproduce problem. If you have something more on this, though, please feel free to update the bug and I'll reopen (no need to open another bug, watchers still get updates on closed bugs).

—Reply to this email directly or view it on GitHub.

**Comment by todb-r7** [comment]
Incidentally, when replying by e-mail, feel free to stop quoting the message in your mail client. I have to delete them from the comments every time. This ain't Outlook. :)

**Comment by g33xter** [comment]
Sorry for that.�
