### ISSUE TITLE
Reopening issue #5055

### ISSUE THREAD

**Issue by after100** [rapid7/metasploit-framework#5060]
**bump** issue #5055 *reopen* at @todb-r7's request.

ive added more detail - able todo it every time on a clean 1.0.9a & 1.1.0a.
bug is still there!!!

i shouldnt be so scared at running `apt-get dist-upgrade` and seeing an update to the metasploit package
this isnt the first 'bug' ive had. or the kali community
there was the whole issue of wanting ruby 2, but kali only had ruby 1.9.x...
before then there was the database upgrade from 4.10 to 4.11 and messing up postgresql

i would take a stable bi-weekly/monthly update, rather than what feels to be a 'bleeding' edge weekly update. if i did what that i would git clone rather than use the repository package 

i get its a open source & free project.. but there is a commercial side, msf pro. kali is meant to be the os that you (rapid 7) guys support with it. seems far from it. feels like theres little (or non) testing on the packages

on to that the fact i reported the bug. then someone reported they are able to replicate it. then they couldnt & closes it. feels odd.

happy to give any more information, if i knew where to look. i just dont see any documentation on troubleshooting where log files are stored/what to check where stuff isnt working. true of any open source project, shouldnt be with commercial.

**Comment by todb-r7** [comment]
Hi @after100 -- I'm going to paste these comments over on #5055 and reopen it. No need to open new bugs for this.
