### ISSUE TITLE
support for ruby1.9 has ended

### ISSUE THREAD

**Issue by shibumi** [rapid7/metasploit-framework#5063]
Dear metasploit-team,
first of all I want to say thank you for this great piece of software.
I just want you inform that the support for ruby1.9 has ended now, there will be no security fixes or other stuff in future. 

https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

Are there any plans to port metasploit for ruby2?

best regards

Chris

**Comment by OJ** [comment]
@shibumi MSF currently requires Ruby 2 to function correctly. Most of the developers have been running it on Ruby 2 for a while already. On this machine, for example,
```
~/c/metasploit-framework git:master ❯❯❯ ruby --version                                                      ◼
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
```
On my desktop
```
metasploit-framework git:master > ruby --version                                                      ◼
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
```

You should be able to install ruby 2.1.5 and have it run without issues. Thanks.

**Comment by shibumi** [comment]
Awesome!
