### ISSUE TITLE
Meterpreter:execute command failed

### ISSUE THREAD

**Issue by cstmr** [rapid7/metasploit-framework#5064]
When run execute -f cmd.exe -i -H, Meterpreter gave me an error:

    [-] stdapi_sys_process_execute: Operation failed: 1

What is causing this, and how to resolve it?

**Comment by OJ** [comment]
Try using `shell` instead, or adding `-c` to the parameter list.

**Comment by wchen-r7** [comment]
if 1 is the windows error code, then it means: ERROR_INVALID_FUNCTION.

**Comment by jlee-r7** [comment]
`1` is also the generic error returned by PHP and Java meterpreters, since they don't have `GetLastError()`

**Comment by kernelsmith** [comment]
Which begs the question, is there any context you can provide?  Like maybe the type of meterpreter you're running and on what target OS?

**Comment by wchen-r7** [comment]
@cstmr Any more info you can provide?

**Comment by bcook-r7** [comment]
There is not enough information.
