### ISSUE TITLE
SSH - Starting bruteforce Name Error unintialized  in auxiliary/scanner/ssh/ssh_login

### ISSUE THREAD

**Issue by vasubesimple** [rapid7/metasploit-framework#5085]

**Comment by vasubesimple** [comment]
IS this a bug or some mis configuration? 
Auxiliary failed: NameError uninitialized constant Net::SSH::Transport::Session::COMPAT_OLD_DHGEX
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/net/ssh/transport/session.rb:104:in `initialize'
[-]   /usr/share/metasploit-framework/lib/net/ssh.rb:186:in `new'
[-]   /usr/share/metasploit-framework/lib/net/ssh.rb:186:in `start'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/ssh.rb:75:in `block in attempt_login'
[-]   /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/ssh.rb:74:in `attempt_login'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:210:in `block in scan!'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:167:in `block in each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:177:in `block (2 levels) in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:170:in `each_line'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:170:in `block in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:169:in `open'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:169:in `each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:129:in `each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:192:in `scan!'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login.rb:122:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'

**Comment by wvu-r7** [comment]
Not enough details.

**Comment by vasubesimple** [comment]
check it now !!! what else do you need?

**Comment by wvu-r7** [comment]
Thanks!!

**Comment by wvu-r7** [comment]
@vasubesimple: It also helps to know what you were doing. :)

**Comment by vasubesimple** [comment]
@wvu-r7  ok just let me know ! if you need more info

**Comment by wvu-r7** [comment]
Looks like ```COMPAT_OLD_DHGEX``` was removed from ```lib/net/ssh/transport/constants.rb```. Is bug.
