### ISSUE TITLE
Meterpreter's `reg deletekey` command doesn't work

### ISSUE THREAD

**Issue by reider-roque** [rapid7/metasploit-framework#5099]
Platform/Version information:
```
root@kali:/tmp# lsb_release -d
Description:	Kali GNU/Linux 1.1.0
root@kali:/tmp# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kali:/tmp# apt-cache show metasploit-framework | grep Version
Version: 4.11.1-2015040202-1kali1
```

`reg deletekey -k keyname` doesn't seem to work (though I don't know if this is a platform specific issue; the victim is Windows XP SP2 Eng, no patches)
```
# Get a Meterpreter shell first

meterpreter > reg createkey -k HKLM\\software\\test
Successfully created key: HKLM\software\test
meterpreter > reg deletekey -k HKLM\\software\\test
[-] stdapi_registry_delete_key: Operation failed: The system cannot find the file specified.
```

Also I am curious what justifies adding registry editing functionality into meterpreter itself when you can drop into the *cmd* with `shell` command and use regular Windows `reg add/delete` commands. If there is something that justifies this addition, then why not keep the same command names that WIndows uses? I mean there are `reg add` and `reg delete`, but Meterpreter creates new names for the same commands -- `reg createkey\setval` and `reg deletekey\deleteval`. That just complicates things in my opinion.

**Comment by kernelsmith** [comment]
It is justified because post modules need to be able to script certain functionality w/o dropping into a shell.  The shell commands are used when in shell sessions.  Additionally, resource files need to be able to script certain functionality as well, which is why it is exposed in msfconsole directly.  I don't know whey the names aren't the same, but it's probably because not everyone is a fan of most Windows' CLI usages.

**Comment by reider-roque** [comment]
@kernelsmith, I appreciate the explanation.

**Comment by bcook-r7** [comment]
Interesting, I'll take a look.

**Comment by bcook-r7** [comment]
The problem isn't that delete_key is broken in meterpreter or the internal API (no modules are affected). It is that the UI is using the API incorrectly. If you pass 'HKCU\Monkey', it opens 'HKCU\Monkey', then tries to delete sub-key 'Monkey', or in effect it tries to delete 'HKCU\Monkey\Monkey'
