### ISSUE TITLE
Have Meterpreter `edit` command create and open a text file if specified file doesn't exist

### ISSUE THREAD

**Issue by reider-roque** [rapid7/metasploit-framework#5104]
Feature request.

Have Meterpreter `edit` command create and open for editing a text file if specified file doesn't exist. That's what `vim` does by default. Or perhaps add a `-c` flag for that.

For the record, now if file doesn't exist `edit` returns *The system cannot find the file specified.* error.

Platform/Version information:
```
root@kali:/tmp# lsb_release -d
Description:	Kali GNU/Linux 1.1.0
root@kali:/tmp# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kali:/tmp# apt-cache show metasploit-framework | grep Version
Version: 4.11.1-2015040202-1kali1
```

**Comment by timwr** [comment]
+1 this would be awesome
