### ISSUE TITLE
metasploit  heartbleed  look for help

### ISSUE THREAD

**Issue by xsy418** [rapid7/metasploit-framework#5108]
I want to use metasploit to test the heartbleed Information Leak
use auxiliary/scanner/ssl/openssl_heartbleed 
set RHOSTS (....IP)
set RPOSTS 443
set VERBOSE true 
run
but the results have some questions,it shows that
（...IP）:443 -sending Client Hello...
{
      SSL record #1
       ..... 
}
the above part has passed without questions
but when it comes to : 
（...IP）:443 -sending Heartbeat....
NO heartbeat response...
looks like there isn't leak information ...
scanned 1 of 1 hosts(100%complete)
auxiliart module execution completed 
I want to know how to solve it ,hope someone can help me

**Comment by wvu-r7** [comment]
Not vulnerable?

**Comment by FireFart** [comment]
This means the server tested does not support the heartbeat extension. So it's not vulnerable

**Comment by xsy418** [comment]
but I have installed openssl-1.0.1 on the server ,
openssl version 
openssl-1.0.1 14 Mar 2012
it should be vulnerable,

**Comment by FireFart** [comment]
try rebooting your machine. Also the application you are trying to test needs to use the ssl libraries from openssl

**Comment by xsy418** [comment]
![1](https://cloud.githubusercontent.com/assets/11863973/7063833/93b126d4-dedc-11e4-848b-b3659b666222.png)
the above ssl libraries have any questions？

**Comment by hmoore-r7** [comment]
Github issues aren't for support questions, try jumping on IRC (#metasploit / irc.freenode.net).
