### ISSUE TITLE
modules/auxiliary/scanner/rdp/ms12_020_check.rb not storing vulns in database

### ISSUE THREAD

**Issue by SonnyJim** [rapid7/metasploit-framework#5160]
Pretty obvious bug this one, the author has put 'report_goods' after the return in a function so it never gets called, thus found vulns never get added to the database:

https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/rdp/ms12_020_check.rb#L163

**Comment by hmoore-r7** [comment]
Seems valid, thanks!

**Comment by wvu-r7** [comment]
Looks like it was broken in c611249723f4481e8f69a1e30d1e7f3ee828e744.

**Comment by bcook-r7** [comment]
Thanks. Dead code detection would have been nice here.
