### ISSUE TITLE
Meterpreter Stage Fails to Detect User Proxy Settings

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#5208]
I was attempting to use meterpreter/reverse_https to use the user's IE proxy settings and connect back to a host. 

This worked fine for the initial connection. However when the meterpreter stage takes over it is unable to connect. It is attempting to perform a direct connection to the host ignoring the proxy which gets blocked by the firewall.

I assume this is something to do with @OJ's changes to WinHTTP (which wont pick up the proxy settings like WinINET). I'm not into the blame game but I'm going to ping @hmoore-r7 and @bturner-r7's as they have also been involved with reverse_http(s) changes and proxy settings :black_joker: . I thought that the WinHTTP stage would either inherit the proxy settings from WinINET stager or attempt to detect them itself? 

I reverted back to 1b3dfe66352dd3b32da58 and things started working again. 

Note that unless your test target is actually firewalled correctly it can be difficult to spot this behaviour. E.g. the proxy will show a CONNECT, you get a session, then it falls back to a direct connection but you dont notice...

**Comment by Meatballs1** [comment]
n.b. in this scenario SYSTEM default proxy settings are not available:

`netsh winhttp show proxy` -> Direct Access

**Comment by Meatballs1** [comment]
To create a windows host firewall to block 443 to your msfconsole:

`netsh advfirewall firewall add rule name="Block MSF 443" dir=out action=block protocol=TCP remoteport=443 remoteip=192.168.0.77`

**Comment by Meatballs1** [comment]
MSDN docs re user proxy settings:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384075%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#setting_the_proxy_configuration_on_a_session

The call to `WinHttpGetIEProxyConfigForCurrentUser` only appears in the stdapi get_proxy_config call. So unless it is manually receiving the proxy settings from Registry or elsewhere it wont use them :(

**Comment by bcook-r7** [comment]
I'm working on harmonizing the WinHttpOpen flags between the reverse_http stager and meterpreter.

**Comment by Meatballs1** [comment]
title is probably more accurate now

**Comment by OJ** [comment]
Pfff.. yeah like this has anything to do with me! \*whistles\* ...

I'll take a look at it today :) Thanks @Meatballs1.

**Comment by OJ** [comment]
OK so it turns out that using the WinInet settings in WinHTTP is a little bit of a pain. More details [here on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384075(v=vs.85).aspx#setting_the_proxy_configuration_on_a_session). It's going to make the stager a little bigger, but for now I'll get it working in Metsrv first, then at least we can pair up a `reverse_http/s` stager with a version of `metsrv` and we'll get proxy functionality back to something usable.

Including in the `reverse_winhttp/s` stager will come later.

**Comment by Meatballs1** [comment]
TBH I don't expect reverse_winhttp stagers to pick up the proxy settings, which is why I would stick with reverse_https for all kinds of phishing/social engineering attempts.

**Comment by OJ** [comment]
Ok cool. I've almost got meterpreter using the proxy stuff via WinHTTP. I'd
appreciate the help with some testing when fixed if that's OK.

**Comment by Meatballs1** [comment]
Sure I have an environment where it currently fails ready to roll :D

**Comment by hmoore-r7** [comment]
It looks like passing WINHTTP_ACCESS_TYPE_DEFAULT_PROXY to WinHttpOpen may be enough for both the user and service cases.

**Comment by OJ** [comment]
That's what we do now both in meterpreter and the stagers, neither of which
works :(

**Comment by hmoore-r7** [comment]
Ah, lame, I guess we need to add  WinHttpGetIEProxyConfigForCurrentUser() instead

**Comment by OJ** [comment]
Yes. And the result of that requires a few other changes too. If wpad is
used it's not so bad, but if its a custom proxy that requires auth I can't
yet see how to get it to use the creds automatically.

**Comment by Meatballs1** [comment]
Most of the time the auth will be NTLM and should be automatic based on user token?

**Comment by OJ** [comment]
True, but not so for basic auth.

**Comment by busterb** [comment]
While there is still a ticket for adding stager support that needs more review, the Windows meterpreter bits are now in place. Thanks everyone.
