### ISSUE TITLE
SessionLogging should include timestamps

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#5215]
It indicates when logging starts and ends, but doesn't timestamp commands.

:crying_cat_face:

**Comment by bcook-r7** [comment]
I'm grabbing this for the intern later.

**Comment by bcook-r7** [comment]
This is not really looking as appropriate as I first thought, ungrabbing.

**Comment by jrobles-r7** [comment]
Closed by #5573
