### ISSUE TITLE
sqlmap_new_task fails to start a new task

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#5222]
msf > sqlmap_connect testphp.vulnweb.com 80
    [+] Set connection settings for host testphp.vulnweb.com on port 80
    msf > sqlmap_new_task 
    [-] Error while running command sqlmap_new_task: 757: unexpected token at '<html>
    <head><title>404 Not Found</title></head>
    <body bgcolor="white">
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.4.1</center>
    </body>
    </html>
    
    
    
    
    
    
    '

    Call stack:
    /home/notfound/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
    /home/notfound/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
    /home/notfound/sectools/metasploit-framework/lib/sqlmap/sqlmap_manager.rb:11:in `new_task'
    /home/notfound/sectools/metasploit-framework/plugins/sqlmap.rb:255:in `cmd_sqlmap_new_task'
    /home/notfound/sectools/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
    /home/notfound/sectools/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
    /home/notfound/sectools/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
    /home/notfound/sectools/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
    /home/notfound/sectools/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
    /home/notfound/sectools/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
    /home/notfound/sectools/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    ./msfconsole:48:in `<main>'

**Comment by brandonprry** [comment]
Is testphp.vulnweb.com on port 80 running the sqlmap API server?

Looks like it isn't.

**Comment by brandonprry** [comment]
```
msf > load sqlmap
[*] Sqlmap plugin loaded
[*] Successfully loaded plugin: Sqlmap
msf > sqlmap_connect
[-] Need a host, and optionally a port
msf > sqlmap_connect 127.0.0.1
[+] Set connection settings for host 127.0.0.1
msf > sqlmap_new_task
[+] Created task: 1
msf > sqlmap_set_option 1 url testphp.vulnweb.com
[*] Success: true
```

**Comment by all3g** [comment]
Thanks a lot.  First, we need a api server as follow.
    
    $ python /path/to/sqlmapapi.py -s 
    [01:56:10] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..

**Comment by brandonprry** [comment]
I think this issue can be closed.

**Comment by wvu-r7** [comment]
Boom.
