### ISSUE TITLE
Can't make metasploit working, 2 computers on 1 network.

### ISSUE THREAD

**Issue by PaulBorensztein** [rapid7/metasploit-framework#5228]
Hey guys,

I've been trying to use metasploit and meterpreter to get the remote control of a computer. I have 2 computers, one running a Windows 7 version and another running Kali. They both are on the same network, using the same AP. I really don't know what i'm missing because every time i start the servers on my Kali computer, i can't access it (using the local IP) with the other one : 

![screenshot - 042215 - 20 16 53](https://cloud.githubusercontent.com/assets/11718935/7281869/8cb30cbc-e92c-11e4-9f3b-b85bb1ccf939.png)
I'm being stuck here.

Few more infos : 
I'm running Kali with crouton on a chromeOS chromebook, the IP is 192.168.1.73
I'm running Win 7 on a regular laptop, the IP is 192.168.1.96

I've been looking for answers and yet i didn't fix my problem. If you guys have any ideas or fixes, and i bet you have, to make this work that would be wonderfull !

Sorry for my lame english, hope you will understand what i mean..
Thanks,
Cheers !

**Comment by void-in** [comment]
@PaulBorensztein This is not the right place to ask for support queries. A better option would be post the question to https://community.rapid7.com. Also the question is related to basic networking which I don't think anyone can troubleshoot for you.

**Comment by PaulBorensztein** [comment]
Oh sorry if i'm in the wrong place. I know it's basic networking tho i really can't see what's being the problem because i can ping each computers without problems..
