### ISSUE TITLE
POODLE scanner returning false positives

### ISSUE THREAD

**Issue by shuckins-r7** [rapid7/metasploit-framework#5248]
## Setup
Configure a test server, SSLv3 turned off. Apache example:
```
sudo vi /etc/apache2/mods-available/ssl.conf
# Make sure this is in place:
SSLProtocol ALL -SSLv2 -SSLv3
#
sudo /etc/init.d/apache2 restart
# Verify that SSL3 is indeed off:
openssl s_client -connect IP-ADDRESS-OF-SERVER:80 -ssl3 # Could be 443 vs 80 depending on host config
# You should get something about handshake failure
```

## Repro
```
use auxiliary/scanner/http/ssl_version
set RHOSTS x.x.x.x  # IP of above server
run
```

You should get an indication that the server is not vulnerable. Instead:
```
[*] Workspace:Test Progress:1/2 (50%) Scanning x.x.x.x-x.x.x.x
[+] x.x.x.x:80 accepts SSLv3
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Jira: MSP-12511

**Comment by shuckins-r7** [comment]
https://github.com/rapid7/metasploit-framework/blame/master/modules/auxiliary/scanner/http/ssl_version.rb#L58-66 is presuming that if we can connect then SSL of the version specified must be accepted. In reality, a connection to a non-SSL HTTP service will also pass this.

**Comment by wchen-r7** [comment]
@parzamendi-r7 Ran into something similar once. He told me he was comparing it with a 3rd party tool, but I can't remember the name right now. Pete let us know again?

**Comment by wvu-r7** [comment]
I couldn't repro this. Will do more testing in a bit. Can you try, @wchen-r7?

**Comment by FireFart** [comment]
I think this is one way to reproduce it:
```
msf > use auxiliary/scanner/http/ssl_version
msf auxiliary(ssl_version) > set RHOSTS google.at
RHOSTS => google.at
msf auxiliary(ssl_version) > set RPORT 80
RPORT => 80
msf auxiliary(ssl_version) > set SSL false
SSL => false
msf auxiliary(ssl_version) > run

[+] 64.15.113.40:80 accepts SSLv3
[+] 64.15.113.24:80 accepts SSLv3
[*] Scanned  2 of 17 hosts (11% complete)
[+] 64.15.113.54:80 accepts SSLv3
[+] 64.15.113.55:80 accepts SSLv3
[*] Scanned  4 of 17 hosts (23% complete)
[+] 64.15.113.50:80 accepts SSLv3
[+] 64.15.113.25:80 accepts SSLv3
[*] Scanned  6 of 17 hosts (35% complete)
[+] 64.15.113.29:80 accepts SSLv3
[*] Scanned  7 of 17 hosts (41% complete)
[+] 64.15.113.20:80 accepts SSLv3
[+] 64.15.113.34:80 accepts SSLv3
[*] Scanned  9 of 17 hosts (52% complete)
^C[*] Caught interrupt from the console...
[*] Auxiliary module execution completed
msf auxiliary(ssl_version) >
```

**Comment by shuckins-r7** [comment]
@wchen-r7 Yeah check out the Jira ticket (12511), that is from @parzamendi-r7, same issue :-)  I added here because the issue is with the ssl_version scanner module.

@wvu-r7 Please add some detail, what happened when you tried to repro? The Jira ticket mentions a case where a non-SSL http service returned as being vulnerable, should be pretty straightforward.

**Comment by wvu-r7** [comment]
```set SSL false``` did the trick.
