### ISSUE TITLE
services -R broken

### ISSUE THREAD

**Issue by jabra-** [rapid7/metasploit-framework#5293]
Currently, the services -R functionality is not working. This was verified using smb_version module and services -p 445 -u -R when there were several hosts in the DB that had 445 open.

You can manually set the RHOSTS variable:

set RHOSTS file:/tmp/list.txt and this works just fine, but using -R doesnt work.

**Comment by void-in** [comment]
Have you updated Metasploit to the latest github snapshot? The error was reported earlier and was fixed in https://github.com/rapid7/metasploit-framework/pull/5261. If you are using github checkout, please pull the latest commits in and check again.
