### ISSUE TITLE
fix bind_tcp linux metasm stager to work with StagerCloseListenSocket=false

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/metasploit-framework#5310]
This is the default from msfvenom, which jumps into some invalid code soon after starting and dies.

**Comment by bcook-r7** [comment]
Got the fix, testing to PR soon.

**Comment by OJ** [comment]
Ah! That explains it. This code has been removed from the multi transport
PR.

Nice catch mate. Thanks for fixing up my mess again. I'll be reinstating
the metasm port but will make sure this isn't broken. Cheers!
