### ISSUE TITLE
enum_domain_group_users is not properly identifying the domain

### ISSUE THREAD

**Issue by jabra-** [rapid7/metasploit-framework#5318]
After doing some recent testing of modules/post/windows/gather/enum_domain_group_users.rb in the lab, I found the module does not properly identify the windows domain.

**Comment by rwhitcroft** [comment]
Works fine for me. Can you paste `show options` and whatever output you're getting?

**Comment by jabra-** [comment]
I cant post the direct output. However, as an example it just prints:

\username1
\username2
\username3
\username4
...

The group was set as "Domain Admins" and session was set as 1.

**Comment by rwhitcroft** [comment]
What does `getuid` return? What about `net config workstation` from a shell?

**Comment by jabra-** [comment]
It's running as SYSTEM. It would be a better approach to not parse cmd-output since it's highly error prone.

C:\Windows\system32>net config workstation
net config workstation
System error 1312 has occurred.
---
C:\Windows\system32>net view /domain
net view /domain
Domain

-------------------------------------------------------------------------------                
ACME              
WORKGROUP            
The command completed successfully.

------
