### ISSUE TITLE
update linux meterpreter migration payload generation

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/metasploit-framework#5346]
It needs some updating as of #5300 to generate a correct payload with a config block.

**Comment by OJ** [comment]
Again, apologies for this. I knew I was breaking stuff in the process, but I wasn't able to get any migration working with Linux before anyway.

There is already code for generating the configuration block for the windows version that can be reused for the posix version. I am happy to at least put this in place, but will need help with testing from other folks.

Do you think we should disable the `migrate` command for POSIX in the short term?

Thanks for logging this issue Brent.

**Comment by bcook-r7** [comment]
We could, though I don't think it will be too hard to fix. If you can describe what needs to happen on this line (or what is the function to generate the config block in the client context), I think I could take it from there.

https://github.com/bcook-r7/metasploit-framework/commit/5548724270e4989ab9e3b1f5d693686435ec24a8#diff-e4aacd68bc172543871b949dc769e152R709

**Comment by OJ** [comment]
I had forgotten that the linux meterpreter needs to generate everything on the MSF side. The Windows version does the transport configuration grunt work on the target with MSF just serving up a new metserv depending on the arch.

So the transport configuration needs to contain the full list of transports that are currently in place. They can be queried directly from meterpreter using the `transport list` command. So perhaps we need to execute that, and use that information to generate the transport configs. Take a look at `lib/msf/core/payload/transport_config.rb` to see the way those configurations are constructed.

I'll piece together some code to help. Cheers!

**Comment by bcook-r7** [comment]
Hi, any update? If you point out the right spot, I'm sure I can patch it back together.

**Comment by OJ** [comment]
I'll get on this today! Sorry for the delay, was trying to get the uuid
payloads done.

**Comment by bcook-r7** [comment]
No worries, we were doing triage: no issue gets uncommented :) (at least not until the hour is up)

**Comment by bcook-r7** [comment]
posix payloads will be getting a makeover soon; going to close this out as wont-fix in its current form
