### ISSUE TITLE
Sending a shell session to background from meterpreter causes it to respawn

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#5356]
When attempting to background a system (UID) shell session from meterpreter (in wow64 mode), the following occurs:

```
C:\Windows\system32>^Z
Background channel 1? [y/N]  y
[-] Failed to spawn shell with thread impersonation. Retrying without it.
Process 760 created.
Channel 2 created.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>
```

I've not tracked down why its even thinking of attempting to spawn anything while it should just be switching context, but this has been an issue on and off for a year if not more. I'm running brand new meterp bins (built today with all outstanding PRs). R7 bins do no better, though i've not tried this in upstream framework (yet).

**Comment by OJ** [comment]
The reason for this is sometimes exceptions are thrown due to thread impersonation failing. Rather than just not spawning a shell, we re-attempt it without thread impersonation.

We need to be able to tell the difference between that and the backgrounding of the channel.

**Comment by Meatballs1** [comment]
Have seen this when `exit`ing from cmd.exe as well.

**Comment by bcook-r7** [comment]
For some reason, I remember this being related to readline.

**Comment by hmoore-r7** [comment]
^Z/^C handled are variably broken across different platforms. See #4555 for the ticket to fix this.

**Comment by bcook-r7** [comment]
This issue also was discussed in https://github.com/rapid7/meterpreter/issues/113

**Comment by bcook-r7** [comment]
Let's close this one and continue discussion on #4555

**Comment by sempervictus** [comment]
Ive added traps into the console driver almost a year ago to address the
Ctrl+... issues, guess I never PRed that. Currently out on contract but
should be able to push that at the end of the week. The problem appears to
be in the windows side though, as traps resolved all the console issues on
the framework side.
