### ISSUE TITLE
msfupdate error

### ISSUE THREAD

**Issue by g33xter** [rapid7/metasploit-framework#5365]
I have installed msf by github, I can't able to update by "msfupdate" cmd. But I can git pull requests & execute "msfconsole". It says "ERROR: User running msfupdate does not own the Metasploit installation
[-] Please run msfupdate as the same user who installed Metasploit." This is the same user while I was installing. 
![screenshot from 2015-05-17 22 18 44](https://cloud.githubusercontent.com/assets/8503135/7674696/bf3b0fda-fce2-11e4-9da1-1bb5a6874f04.png)

**Comment by wvu-r7** [comment]
Hey, we use issues for bug reports, not support questions. If you hop on IRC, I'm sure someone can help you swiftly! :)

P.S. You probably need to be root, since you're running ```msfupdate``` from ```/opt/metasploit-framework```. Cheers!

**Comment by g33xter** [comment]
If I user root then this warning message will come, ''Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine".

**Comment by wvu-r7** [comment]
@g33xter That's because you installed in ```/opt``` to begin with. :)
