### ISSUE TITLE
Metasploit RPC/WEB services are failing after initial startup 

### ISSUE THREAD

**Issue by ramganesh19** [rapid7/metasploit-framework#5384]
uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

msf > version
Framework: 4.11.2-2015051401
Console  : 4.11.2-2015051401.15168

service metasploit status
[FAIL] Metasploit rpc server is not running ... failed!
[FAIL] Metasploit web server is not running ... failed!
[ ok ] Metasploit worker is running.

I am trying to enable community version of MetaSploit and appreciate your help in resolving this issue 

RPC fails first and WEB Fails next

/opt/metasploit/apps/pro/ui/log/thin.log file details

>> Writing PID to log/thin.pid
>> Using rack adapter
>> Writing PID to log/thin.pid
>> Using rack adapter
>> Exiting!
/opt/metasploit/apps/pro/msf3/lib/rex/sync/thread_safe.rb:36:in `select': execution expired (Metasploit::Database::MigrationTimeoutError)
        from /opt/metasploit/apps/pro/msf3/lib/rex/sync/thread_safe.rb:36:in `select'
        from /opt/metasploit/apps/pro/msf3/lib/rex/sync/thread_safe.rb:76:in `sleep'
        from (eval):3:in `sleep'
        from /opt/metasploit/apps/pro/ui/lib/metasploit/database.rb:142:in `block (2 levels) in wait_until_migrated'
        from /opt/metasploit/apps/pro/ui/lib/metasploit/database.rb:137:in `loop'
        from /opt/metasploit/apps/pro/ui/lib/metasploit/database.rb:137:in `block in wait_until_migrated'
        from /opt/metasploit/ruby/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
        from /opt/metasploit/ruby/lib/ruby/2.1.0/timeout.rb:101:in `call'
        from /opt/metasploit/ruby/lib/ruby/2.1.0/timeout.rb:101:in `timeout'

**Comment by hmoore-r7** [comment]
@ramganesh19 Hello! This tracker is for issues with the open source framework. It appears that you are using either Metasploit Pro or Community Edition. If you are a Pro customer, please contact Rapid7 support, otherwise please head to https://community.rapid7.com/ and ask there. Offhand, it looks like your install is corrupted or something bad happened to your database.
