### ISSUE TITLE
Metasploit RPC server failing to start on Kali

### ISSUE THREAD

**Issue by kgray-r7** [rapid7/metasploit-framework#5423]
Issue https://github.com/rapid7/metasploit-framework/issues/5055 has evolved from an issue with the go_pro command on Kali to an issue wherein Metasploit RPC server fails to start. This ticket is to report the current failure and keep everything a bit more streamlined. 

From @cr0bar:

I'm still experiencing similar issues even after updating to the latest build:

```
root@hacker:~# date && service metasploit status
Thu Apr 23 19:06:13 UTC 2015
[ ok ] Metasploit rpc server is running.
[ ok ] Metasploit web server is running.
[ ok ] Metasploit worker is running.

root@hacker:~# date && service metasploit status
Thu Apr 23 19:06:49 UTC 2015
[FAIL] Metasploit rpc server is not running ... failed!
[ ok ] Metasploit web server is running.
[ ok ] Metasploit worker is running.
```
```
       =[ metasploit v4.11.1-2015042001 [core:4.11.1.pre.2015042001 api:1.0.0]]
```
```
msf > go_pro
[*] Starting the Metasploit services. This can take a little time.
[*] Starting PostgreSQL 9.1 database server: main.
[*] Starting Metasploit rpc server: prosvc.
[*] Metasploit web server already started.
[*] Metasploit worker already started.
........................................................................................................................................................................................................
[!] For some reason, Community / Pro didn't start in a timely fashion.
[!] You might want to restart the Metasploit services by typing
[!] 'service metasploit restart'. Sorry it didn't work out.
```
```
root@hacker:~# date && service metasploit status
Thu Apr 23 19:23:57 UTC 2015
[FAIL] Metasploit rpc server is not running ... failed!
[FAIL] Metasploit web server is not running ... failed!
[ ok ] Metasploit worker is running.
root@hacker:~# uname -a
Linux hacker 3.18.9-v7 #1 SMP PREEMPT Sat Mar 7 07:12:24 EST 2015 armv7l GNU/Linux
root@hacker:~# 
```
```
root@hacker:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux 1.1.0
Release:	1.1.0
Codename:	moto
root@hacker:~# date && service metasploit status
Thu Apr 23 19:35:07 UTC 2015
[FAIL] Metasploit rpc server is not running ... failed!
[FAIL] Metasploit web server is not running ... failed!
[FAIL] Metasploit worker is not running ... failed!
```

**Comment by kgray-r7** [comment]
Repro steps from @bcook-r7:

This is how I was able to provoke either working or broken states from a system already in either state.

First, do this to get the system back into an initial state:
 * service metasploit stop
 * su postgres
 * psql
 * type 'drop database msf3;'
 * type 'drop owned by msf3;'
 * type 'drop role msf3;'
 * exit psql back to the root user - ctrl-d, ctrl-d
 * run /opt/metasploit/reconfigure_script
 * run service metasploit start
 * run service metasploit status (note all services say running)

Depending on which state you want to test, perform one of the next series of steps.
To recreate a broken system, do the next step immediately:
 * run msfconsole (note that the database we dropped above gets recreated here)
 * type 'go_pro' (note that it says the services will take a while to start, dots appear for a long time, then timeout)
 * exit msfconsole, type 'service metasploit status' and note some or all 3 services are failed
 * service metasploit start (note the services are green again)
 * wait a minute or 2, check status again until all services have died.

To have a working system, perform the next step after waiting a couple of minutes for the metasploit service to start:
 * run msfconsole (note there are no database creation messages)
 * type 'go_pro' (note that it starts immediately and pops up a web browser)
 * exit msfconsole, type 'service metasploit status' and note all 3 services are running

It might be nice to add a 'service metasploit reinit' that reinitializes the database and starts everything from 'just installed' state to make resetting things easier. Of course, there may already be something like that I just don't know about :)

**Comment by wchen-r7** [comment]
Hey what's the current progress fellas? @bcook-r7 @kgray-r7

**Comment by jeepers58** [comment]
bump on this issue, 
1. fresh install kali 1.1.0 things seem to be working fine
2. apt-get update && apt-get dist-upgrade. Afterwords msfconsole will not start with errors surrounding ruby gems, ruby libs as detailed above.

**Comment by bcook-r7** [comment]
I suspect your error is different @jeepers58 than the item being tracked here. Is this closer to what you are seeing? https://community.rapid7.com/thread/7388

**Comment by jeepers58** [comment]
Spot on ! Cheers bcook !

**Comment by bcook-r7** [comment]
See #5055
