### ISSUE TITLE
Metasploit won't start after update

### ISSUE THREAD

**Issue by DrDinosaur** [rapid7/metasploit-framework#5432]
After the recent Kali update, I believe something messed up metasploit and/or postgresql. The latest update made postgresql unable to start in both my Kali VM and nethunter device. I got postgresql working on my home VM by trying to remove and reinstall postgresql and metasploit, but I haven't had the same luck on my nethunter device. Anyone else have this issue or know how to really fix it? 
Here's the error message:
service postgresql start
[....] Starting PostgreSQL 9.1 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2015-05-25 19:52:06 HST LOG: could not bind IPv6 socket: Cannot assign requested address 2015-05-25 19:52:06 HST HINT: Is another postmaster already running on port 5432? If not, wait a few seconds and retry. 2015-05-25 19:52:06 HST LOG: database system was interrupted; last known up at 2015-05-25 13:33:04 HST 2015-05-25 19:52:06 HST LOG: incomplete startup packet 2015-05-25 19:52:07 HST FATAL: could not open file "/etc/ssl/certs/ssl-cert-snakeoil.pem": Permission denied 2015-05-25 19:52:07 HST LOG: s[FAILp process (PID 3609) exited with exit code 1 2015-05-25 19:52:07 HST LOG: aborting startup due to startup process failure ... failed!
failed!

**Comment by bcook-r7** [comment]
Metasploit does not maintain the postgresql package distributed with Kali linux. If the postgresql server fails to start, this is a Kali linux issue. It looks like your question was already answered there:

https://forums.kali.org/showthread.php?25638-Postgresql-won-t-start&p=45712

**Comment by DrDinosaur** [comment]
Good, someone answered it. Didn't get an email notification. Thanks for the reminder.
