### ISSUE TITLE
Error when "run vnc" over meterpreter

### ISSUE THREAD

**Issue by sft-hardwork** [rapid7/metasploit-framework#5443]
![1](https://cloud.githubusercontent.com/assets/5676511/7898038/ad8acd4e-071d-11e5-8c0d-bff5f3642bf8.PNG)
![2](https://cloud.githubusercontent.com/assets/5676511/7898039/ad8b10c4-071d-11e5-9559-ecf486c1247b.PNG)
![3](https://cloud.githubusercontent.com/assets/5676511/7898043/d1ccbc1c-071d-11e5-90e5-bdc521400a20.PNG)

In picture is the error when "run vnc" meterpreter.
Plz help me !

**Comment by bcook-r7** [comment]
The metasploit-framework open source project is not a support forum for Metasploit Pro. Please use https://community.rapid7.com for these kinds of questions.

**Comment by hmoore-r7** [comment]
@sft-hardwork The vncviewer command installed on your system doesn't accept the standard -viewonly argument. You can still connect manually using a vnc client (localhost:4545)
