### ISSUE TITLE
Sessions doesn't indicate the new user after migration

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#5465]
If you migrate a session into a process owned by another user, there would be no way to `rev2self` and obtain the original user the session started on.

However running `sessions` does not dynamically update the current user name from the main process token. I guess the `migrate` command should check and update the username?

It would be even better if we could show the current username of the impersonated token as well (maybe in brackets, or maybe within `sessions -v` output. This would probably need to be done in incognito extension though.

**Comment by wchen-r7** [comment]
We'll move this to the meterpreter repo in a bit.

**Comment by Meatballs1** [comment]
I consider it more framework side, as it is the output from the UI rather than a meterpreter issue itself?

**Comment by wchen-r7** [comment]
@Meatballs1 Well, the incognito isn't in framework anymore though. It's in the [meterpreter repo](https://github.com/rapid7/meterpreter/tree/master/source/extensions/incognito).

**Comment by Meatballs1** [comment]
migrate and steal_token aren't part of incognito? :)

**Comment by wchen-r7** [comment]
Um, sorry I'm a little confused. So what do you want us to do with with incognito extension code?

**Comment by Meatballs1** [comment]
#### Verification

* PSEXEC onto box
* `sessions`
- [ ] You should see the user listed as NT AUTHORITY\SYSTEM
* Migrate into a specific user process
* `sessions`
- [ ] You should STILL see the user listed as NT AUTHORITY\SYSTEM - but you are not that user anymore, and you cant `rev2self` back to that user.

**Comment by wchen-r7** [comment]
Thanks.

My brain failed to process this ticket properly when I first read this.

**Comment by hmoore-r7** [comment]
Makes this, this is done during session initialization, but isn't re-run after a migrate.
