### ISSUE TITLE
The decryption method for post/windows/gather/credentials/razorsql is outdated

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#5469]
It looks like post/windows/gather/credentials/razorsql's decryption method no longer works for the latest version. I didn't try very hard to see if the decryption can be updated, so this is how much I know.

**Comment by jvazquez-r7** [comment]
I'm going to grab this one as we decided today!

**Comment by jvazquez-r7** [comment]
Fix ready here: https://github.com/wchen-r7/metasploit-framework/pull/30

I'm adding the patch to the PR https://github.com/rapid7/metasploit-framework/pull/5468 from @wchen-r7 since it's related to creds. In this way we avoid conflicts =)

**Comment by wchen-r7** [comment]
Resolved in https://github.com/wchen-r7/metasploit-framework/commit/eb39eaac1d00aec1cada9056a5f543704c8262f6
