### ISSUE TITLE
Automatic tagging a scan is applied to entire workspace

### ISSUE THREAD

**Issue by mixmatch** [rapid7/metasploit-framework#5495]
In the metasploit community web GUI checking the "Automatically tag by OS" for a scan causes the scan to perform "Normalizing and tagging" on the entire workspace, rather than the list of IP addresses included in scan.

**Comment by hmoore-r7** [comment]
@mixmatch Thanks! This isn't the right forum for these kinds of bugs, please use https://community.rapid7.com/. I think the behavior you are experiencing is expected.

**Comment by shuckins-r7** [comment]
@mixmatch Thanks for the report. Please submit Community edition related bugs to [our community forums](https://community.rapid7.com/community/metasploit). This repository only covers Metasploit Framework. 

In this case, however, I can let you know this is not a bug. When we complete a scan in Pro, we run through a normalization method that involves checking information on hosts in the workspace that are not necessarily included in the scan. This is to ensure data quality and integrity.

**Comment by mixmatch** [comment]
So, by design, metasploit does not scale:
"Progress:6767/13013"
"Elapsed: about 18 hours"

At least you have a free version so these kinds of limitations can be identified before investing any money in the platform...

PS no interesting in joining your forum for issues like these. If you want feed back from github users create a place for these issues on github.

**Comment by eyilmaz-r7** [comment]
@mixmatch I wanted to say we do appreciate the time you took to provide us feedback. We try to keep the issue reporting separate and use a separate platform because it helps us manage our defects, and provide visibility to other community / express / pro users in case some one else experienced the same problem. Additionally, I completely understand that you do not want to join the forum.

Once again we do appreciate your report and your findings. I have taken a note and will investigate accordingly.

Thanks and have a nice day.

**Comment by hmoore-r7** [comment]
@mixmatch On the scaling side, best bet is to get a trial and speak with a sales engineer. Metasploit Pro is intentionally not fast at single-host brute force, but scales really well when you have large networks of hosts that can be tested in parallel.

**Comment by mixmatch** [comment]
This isn't the only performance issue I've seen with the platform. It takes an hour to use rsync to completely migrate an ubuntu box with metasploit set up. Importing an XML of the workspace (10k+) hosts takes days+ (cancelled after over 3 days, so can't verify that the xml import even works). That's sad.

**Comment by hmoore-r7** [comment]
@mixmatch I appreciate the feedback, but this isn't the right forum for it.

**Comment by mixmatch** [comment]
You realize that:
a) The site you are referencing was 404 when I reported this issue (linked from ? -> Community)
b) The site you are referencing has no bug reporting system

**Comment by hmoore-r7** [comment]
@mixmatch If you are evaluating the commercial product, our sales engineering staff will support any issues that come up. For Community Edition, there is a discussion forum under each product at the community web site, the one you are looking for is at [Metasploit - Discussions](https://community.rapid7.com/community/metasploit/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D). The Community web site was recently migrated (last Saturday), apologies for the confusion. The Pro/CE products are not open source and not a good fit for Github as a result.
