### ISSUE TITLE
some strange problem with MSFRPCD

### ISSUE THREAD

**Issue by darkr4y** [rapid7/metasploit-framework#5514]
I always use Cobaltstrike with msf , and things always goes right until I update the msf.
![image](https://cloud.githubusercontent.com/assets/4407382/8053475/a7427088-0ec3-11e5-9154-2e8544ebabca.png)
the code ref
class MsgRpcImpl - https://code.google.com/p/armitage/source/browse/trunk/src/msf/MsgRpcImpl.java?r=1091
server.sl - https://github.com/ccdc/armitage/blob/master/scripts/server.sl
I test it in my local kali,  its ok. but in my vps's ubuntu , it shows that.
I also use msfrpc client to test when cobaltstrike's teamserver start
msfrcp -U someone -P givemepass -a 127.0.0.1 -p 55554
and it returns blank , stop responsing 
is that msfrpcd api changed ?

**Comment by void-in** [comment]
Are you able to connect to the port 55554 on the VPS remotely? I just checked and can connect to the msfrpcd service remotely without any problem.

**Comment by OJ** [comment]
Can you please use IRC or community.rapid7.com for support issues?

Thanks.
