### ISSUE TITLE
Meterpreter ABI changes breaks sniffer and custom extensions

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#5516]
Since sniffer uses supporting libraries which are closed source, it cannot be recompiled by users and updated to the new ABI. Recent changes to meterpreter are now causing sniffer to fail on x86 and x64 systems (native or WOW64 execution).

```
meterpreter > load sniffer 
success.
meterpreter > sniffer_interfaces 

[*] 192.168.1.10 - Meterpreter session 2 closed.  Reason: Died
```

Results are the same from W7 x86 & x64, 2008r2, and 2012r2.

@devs: any chance you guys could recompile the sniffer DLLs and push them into one of the payload gems or back into the appropriate framework dir structure?

**Comment by void-in** [comment]
And possibly open source it as well :)

**Comment by sempervictus** [comment]
@void-in:  There's some history to the library on which both modules run, if you're bored, might be a fun research project. Suffice to say that it's not likely to happen even after the 9th circle freezes over.

@community/devs: to reproduce this, you'll need to pull the current framework from git, and build the current meterpreters from source.

**Comment by sempervictus** [comment]
After discussion with @hmoore-r7 in IRC, we determined that common.lib has changed on the meterp side (so this is the wrong place for the issue). Sleep has broken every extension not built against the current common.lib....

**Comment by hmoore-r7** [comment]
@sempervictus made that determination, but.. yes, if your custom extension is not working, rebuild.

**Comment by wchen-r7** [comment]
The sniffer code is here: https://github.com/rapid7/meterpreter/tree/master/source/extensions/sniffer, so I'm gonna move this ticket to that repo later.

**Comment by hmoore-r7** [comment]
@wchen-r7 FYI, @jlee-r7 was looking into this, it sounds like the sniffer extension is fine, but any third-party extension need to be rebuilt, which is expected. If sniffer is working, we can close this ticket.

**Comment by wchen-r7** [comment]
Oh ok, thanks!

**Comment by sempervictus** [comment]
This is resolved, thanks.
