### ISSUE TITLE
Telnet capture module not working properly from Linux clients

### ISSUE THREAD

**Issue by void-in** [rapid7/metasploit-framework#5525]
The module modules/auxiliary/server/capture/telnet currently don't work with Linux clients. The behavior is as follows:

On the MSF side, setup the telnet capture module:
```ruby
msf > use auxiliary/server/capture/telnet
msf auxiliary(telnet) > run
```
From a Linux machine, connect to the telnet server:
```bash
root@kali: telent 1.1.1.1
Trying 1.1.1.1...
Connected to 1.1.1.1.
Escape character is '^]'.

Welcome.

Login: root
Password:

Login failed

Connection closed by foreign host.
```
As soon as the username is entered, the connection is dropped. Line 109 is currently sending the WILL ECHO command to the client.
```ruby
c.put "\xff\xfb\x01" # WILL ECHO
```
If the code is changed to WON'T ECHO:
```ruby
c.put "\xff\xfc\x01" # WON'T ECHO
```
the module works fine but the password is echo'd back to the user when typing. Will generate a PR once a proper working code is identified to be send to the telnet client.

Note that the module is currently working fine with Windows clients such as Putty. But telnet-ing from Kali result in the problem above.

**Comment by wchen-r7** [comment]
This thing is currently handled by @void-in
