### ISSUE TITLE
Meterpreter session flagged invalid when using SSH tunnel

### ISSUE THREAD

**Issue by sweetsoftware** [rapid7/metasploit-framework#5534]
I'm using a meterpreter handler on my laptop (no public IP), which is SSH remote port forwarded through a VPS. When a meterpreter payload connects to the VPS IP on the forwarded port, the handler correctly receives the connection on my laptop but exits after a few seconds:

`
meterpreter > 
[-] Meterpreter session 9 is not valid and will be closed
`
However when setting AutoVerifySession to false everything is fine. Seems like the verification procedure wrongly assumes the meterpreter session is invalid.

 According to this post (https://twitter.com/hdmoore/status/598142217031688193) it may be caused by an invalid LHOST value, but the same error occurs when LHOST is set to localhost, remote IP, or 0.0.0.0 and AutoVerifySession to true

**Comment by OJ** [comment]
Which payload is this? Http/s or TCP? I'm guessing the former based on your
comment.

Meterpreter sessions work fine over SSH. If you have a session validation
problem it is usually related to something else.

Make sure that LHOST is the same in both the payload and the listener. Make
sure that LPORT is the same in both the payload and the listener. If you
are port forwarding to a different port then you need to make sure you set
ReverseListenerBindPort to the port you need to bind to locally.

If all of those pieces are in place then it could be that things are slow
and lagging, you could try turning off auto session verification.

Ultimately, this has nothing to do with SSH tunneling.

**Comment by sweetsoftware** [comment]
Payload is reverse HTTP.
LHOST is set to VPS IP and the same port is used in both the payload and the listener. The port forwarding is also set to the same port.

I guess it comes from the slow connection then, since it works when turning auto session verification to false, and the payload takes quite some time to be functional.

**Comment by OJ** [comment]
Thanks for the response. I've seen similar issues over laggy connections. I
also had auto verify kill of a python she'll yesterday. I think we may need
to expose the verify timeout as a payload setting of we haven't already.

Got a flight this morning, I'll take a look.
