### ISSUE TITLE
Update smb_version / etc to obtain fingerprints from NTLM_CHALLENGE responses

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#5586]
Today, `smb_version` will only obtain a matching fingerprint if the login succeeds, in which case the fingerprint is based off the Native OS or Native LAN Manager fields from the successful login.  Most systems will return the same data earlier on in the authentication process, specifically as part of the NTLM_CHALLENGE responses that precede authentication.  

This means that `smb_version` or any code like it will not be able to fingerprint the OS in the following situations:

* If no `SMBUser` and `SMBPass` are specified and the target blocks null sessions
* If an invalid `SMBUser` or `SMBPass` are specified -- many SMB services will still happily give up the Native OS and Native LAN Manager values before authentication succeeds anyway, at least as seen in NTLM_CHALLENGE response packets.

**Comment by hmoore-r7** [comment]
Fixed in #5977
