### ISSUE TITLE
Bug: domain_hashdump to work locally

### ISSUE THREAD

**Issue by jabra-** [rapid7/metasploit-framework#5640]
The post/windows/gather/credentials/domain_hashdump will allow you to pull down the domain hashes via VSS.  The problem is that the module wont work against current sessions it only works remotely. It would be great if there was an easier method to do this locally if you have a session on one of the DCs.

**Comment by mubix** [comment]
```
Module options (post/windows/gather/credentials/domain_hashdump):

   Name       Current Setting  Required  Description
   ----       ---------------  --------  -----------
   RHOST      localhost        yes       Target address range
   SESSION    1                yes       The session to run this module on.
   SMBDomain                   no        The Windows domain to use for authentication
   SMBPass                     no        The password for the specified username
   SMBUser                     no        The username to authenticate as
   TIMEOUT    60               yes       Timeout for WMI command in seconds
```

Works just fine for me on 2008 R2: 
```
msf post(domain_hashdump) > sessions

Active sessions
===============

  Id  Type                   Information                Connection
  --  ----                   -----------                ----------
  1   meterpreter x64/win64  NT AUTHORITY\SYSTEM @ DC1  172.16.102.1:4444 -> 172.16.102.15:51830 (172.16.102.15)
```

Can you paste some failure output?

**Comment by OJ** [comment]
I had this module crash on me on a recent engagement :(

**Comment by busterb** [comment]
Hmm, I wonder if it was something I broke. There were a lot of instances of the pattern strncpy(dst, src, sizeof(src)) that I fixed up, but I suspect there may be a buffer overrun still lurking killing it with some data sets.

**Comment by jabra-** [comment]
Framework: 4.11.0-dev
Console  : 4.11.0-dev.15168

--
```
Post failed: RuntimeError WMIC: User credentials cannot be used for local connections
Call stack:
/root/metasploit/lib/msf/core/post/windows/wmic.rb:31:in `wmic_query'
/root/metasploit/lib/msf/core/post/windows/shadowcopy.rb:173:in `start_vss'
/root/metasploit/modules/post/windows/gather/credentials/domain_hashdump.rb:57:in `copy_database_file'
/root/metasploit/modules/post/windows/gather/credentials/domain_hashdump.rb:35:in `run'
[*] Post module execution completed
```

@OJ when it crashed did that affect the server at all?

**Comment by OJ** [comment]
@jabra- Thankfully the session wasn't in a super critical process, so I got away with it. But it did leave some mess on the disk that I had to sort out manually. I'm not sure what caused the failure, but the whole Meterpreter session was vapourised. I didn't chase it up any more because I was on an engagement and didn't want to make any more noise.

**Comment by jabra-** [comment]
@OJ roger that. thanks! Do you have more details you could share? I think this would make sense as a different ticket. Clearly there is more work to be done on this module before I would consider it really stable.

**Comment by OJ** [comment]
@jabra- Let me have a dig through my logs/docs and see what I can find. If there's anything I can add here to help I'll be sure to do so!

**Comment by jabra-** [comment]
@OJ would you mind creating new ticket so we can keep track of the issues?

**Comment by OJ** [comment]
@jabra- sure, as soon as I have some detail I will do so.

**Comment by bcook-r7** [comment]
It's unclear to me why this switches from a feature request to bug. I see two issues: one asking for the ability to run this locally, I guess against a local .dit file? The other issue is the crash that OJ is seeing. Is this correct?

**Comment by jabra-** [comment]
I updated it based on mubix's feedback that it worked for him but didnt for me.

**Comment by OJ** [comment]
I'll see if I can repro somewhere.

**Comment by jabra-** [comment]
@OJ any updates?

**Comment by OJ** [comment]
Sorry @jabra-, haven't been able to repro.

**Comment by dmaloney-r7** [comment]
This bug looks like it was caused by SMBUser datastore options not having been properly deregistered at the time, making the WMIC code think that it was trying to make a remote connection instead of operating locally. This is no longer the case, and this issue should be resolved. If you re-encounter this issue please let us know.
