### ISSUE TITLE
Problem while starting msfpro :(

### ISSUE THREAD

**Issue by nsonaniya2010** [rapid7/metasploit-framework#5673]
root@Kali:~# msfpro
DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /opt/metasploit/apps/pro/ui/lib/metasploit/pro/ui.rb:16)
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `async_exec': PG::UndefinedColumn: ERROR:  column tasks.state does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "tasks".* FROM "tasks"  WHERE "tasks"."state" = 'runn...
                                             ^
: SELECT "tasks".* FROM "tasks"  WHERE "tasks"."state" = 'running'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:798:in `exec_no_cache'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `select'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:25:in `select_all'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/query_cache.rb:64:in `select_all'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/querying.rb:36:in `find_by_sql'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:587:in `exec_queries'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:471:in `load'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:220:in `to_a'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:12:in `each'
	from /opt/metasploit/apps/pro/engine/config/application.rb:153:in `update_defunct_tasks!'
	from /opt/metasploit/apps/pro/engine/config/application.rb:111:in `block in <class:Application>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /opt/metasploit/apps/pro/engine/config/environment.rb:5:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:189:in `require_environment!'
	from /opt/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:49:in `require_environment!'
	from /opt/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:65:in `start'
	from /opt/metasploit/apps/pro/engine/msfpro:17:in `<main>'

When i start pro from msfconsole i got error like this

 go_pro
[*] Starting the Metasploit services. This can take a little time.
[-] Error while running command go_pro: no implicit conversion of nil into String

Call stack:
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:3290:in `join'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:3290:in `start_metasploit_service'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:3202:in `cmd_go_pro'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/sbin/msfconsole:48:in `<main>'

I have the latest version as shown

msf > version 
Framework: 4.11.3-2015063001
Console  : 4.11.3-2015063001.15168
msf > date
[*] exec: date

Tue Jul  7 03:14:03 IST 2015

latest Rails version 

root@Kali:~# rails -v
Rails 4.2.3

**Comment by bcook-r7** [comment]
Thanks for the report. This issue appears to be identical to #5625, so I am going to close this one in favor of us tracking the issue there.
