### ISSUE TITLE
metasploit dev setup guide error

### ISSUE THREAD

**Issue by techgod52** [rapid7/metasploit-framework#5704]
In the 'Run Specs' section, rake rspec doesn't work, but rake spec does.
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

**Comment by bcook-r7** [comment]
Hi, we could not find any references to 'rake rspec' in the wiki. Please make sure you are referring to a recent version. Thanks!

**Comment by techgod52** [comment]
It has been fixed
