### ISSUE TITLE
Reading Meterpreter over RPC: Session busy?

### ISSUE THREAD

**Issue by alexcwatt** [rapid7/metasploit-framework#5747]
I would ask this on the mailing list, but it seems to be down...

I'm trying to use [this method](https://github.com/rapid7/metasploit-framework/blob/e749733eb6118a4b089e288fc81050f76c8db5ed/lib/msf/core/rpc/v10/rpc_session.rb#L151) (via the msfrpc API), but the fact that I can't tell if the remote (e.g., Meterpreter) session is busy is giving me trouble. I can look at a console and see the prompt, data, and busy-ness, but whenever that console has an active remote session, it always says it is busy... which is not too helpful for what I want.

I would like to know when a task has finished in Meterpreter over RPC — when it is safe to issue a new command, because all the required data has been returned. I'm not having any issues reading the data, but right now have no way of knowing that what I have read is or is not the complete response, if that makes sense.

Any suggestions? I'd be happy to work on code for this if someone can point me in the right direction; I'm pretty unfamiliar with the codebase.

**Comment by rsmudge** [comment]
I don't think there's a good way to do what you want. I had to develop heuristics for my Armitage tool to figure out when a command is done or not. Some of my heuristics rely on time to determine if a command is done. Others rely on an expected number of successful reads. 

https://github.com/rsmudge/armitage/blob/master/src/msf/MeterpreterSession.java

**Comment by alexcwatt** [comment]
@rsmudge Interesting... Thought about doing something like that too.

For the moment, I've added the following to `#busy` in [`WebConsole`](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/web/console.rb):

```
if self.console.active_session
  return self.console.active_session.console.busy
end
```

This does seem to allow me to know if the Meterpreter session is actually busy. Unfortunately, it doesn't work for other types of shells, and now I'm experiencing an issue where the prompt being sent is not correct (e.g., sometimes `msf >` when it should be `meterpreter >` and vice versa)...

**Comment by alexcwatt** [comment]
I'm closing this, since I understand that the original behavior is expected, and I see [another issue](https://github.com/rapid7/metasploit-framework/issues/5756) addresses the incorrect prompt problem...
