### ISSUE TITLE
Typo in DNS Fuzzer

### ISSUE THREAD

**Issue by crsanders** [rapid7/metasploit-framework#5755]
dns_fuzzer.rb, located in modules/auxiliary/fuzzers/dns/, appears to have a typo at line 343 which results in module failure.  The line currently reads:

@fuzz_rr     = datastore['RR'].blank ? fuzz_rr_queries : datastore['RR']

which results in NoMethodError: undefined method 'blank' for "":String on my system.  I believe the line should read

@fuzz_rr     = datastore['RR'].blank? ? fuzz_rr_queries : datastore['RR']

**Comment by void-in** [comment]
Yes. The current statement is incorrect. Would you like to generate a PR?

**Comment by crsanders** [comment]
I have submitted a [pull request](https://github.com/rapid7/metasploit-framework/pull/5759), please let me know if any additional information is required.
