### ISSUE TITLE
Payload generation returns nil with generic/shell_bind_tcp for fritzbox_echo_exec

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#5761]
Originally reported in https://github.com/rapid7/metasploit-framework/pull/3467#issuecomment-123957520

If generic/shell_bind_tcp is used, the generate_payload_exe method returns nil:

```ruby
  def generate_cmdstager(opts = {}, pl = nil)
    select_cmdstager(opts)

    self.exe = generate_payload_exe(:code => pl)

    if exe.nil?
      raise ArgumentError, 'The executable could not be generated'
    end
...
```

**Comment by wchen-r7** [comment]
As far as I can tell, the generic one returns the same raw payload as the MIPS one. The difference is that the first is labeled as "generic" and the self.to_executable method doesn't know what to do with that, therefore we end up with:

https://github.com/rapid7/metasploit-framework/blob/dc07938668b0a0b61b6502c46d95eb5e96cd8b65/lib/msf/util/exe.rb#L153

**Comment by wvu-r7** [comment]
#5718 is related.
