### ISSUE TITLE
Windows Meterpreter no longer shows PPID with ps output

### ISSUE THREAD

**Issue by rsmudge** [rapid7/metasploit-framework#5773]
This makes me a sad panda. Windows Meterpreter no longer shows the PPID column in its ps output. This is a key piece of information for some offensive actions. 

For example, I might want to see which process kicked off my current payload and would use the PPID information to see the parent of my meterpreter's session PID. I do a bit of meddling with Internet Explorer and its to my advantage to know which iexplore.exe is the parent of all others. The PPID information is necessary to do this. I suspect I'm not the only affected by this change.

This is showing in the latest MSF package on Kali Linux.

**Comment by bcook-r7** [comment]
It's just missing in the display output, meterpreter is passing the data correctly still. I'll fix this.
