### ISSUE TITLE
WMIC Post Library should use Extapi.WMI.Query

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#5803]
However, extapi doesn't support remote hosts yet so it should fall back to wmic until it does.

**Comment by OJ** [comment]
Ummm... Pretty sure it does support remote hosts already! There's an extra
parameter you can pass in.

I'll verify when I'm back home :-)

**Comment by Meatballs1** [comment]
Ah but not with creds passed to it on the command line etc. It can use tokens etc however afaik.

**Comment by Meatballs1** [comment]
Although I have never tested if that works!

**Comment by OJ** [comment]
Ah yup. Definitely need to add credential support.
