### ISSUE TITLE
msfcli and msfpayload missing ?

### ISSUE THREAD

**Issue by aymeric75** [rapid7/metasploit-framework#5804]
Hi,

  I just installed metasploit using this tutoriel http://www.darkoperator.com/installing-metasploit-in-ubunt/

And when i type msfcli or msfpayload in my terminal it says that it does not exit.

Do i have to install those two modules manually ?

Cheers

Aymeric

**Comment by OJ** [comment]
* msfcli no longer exists: https://community.rapid7.com/community/metasploit/blog/2015/07/10/msfcli-is-no-longer-available-in-metasploit
* msfpayload and msfencode no longer exist: https://community.rapid7.com/community/metasploit/blog/2015/06/08/msfpayload-and-msfencode-are-being-removed-from-metasploit

Cheers!

**Comment by aymeric75** [comment]
Thanks, i'm now trying to use whois, so i start msfconsole then type: whois some_site.com

But it says that this command does not exist. It has been remove too ?

**Comment by busterb** [comment]
whois is not a metasploit command at all. This something that is installed in your operating system.

Run: ```sudo apt-get install whois``` to install whois on Ubuntu.

**Comment by aymeric75** [comment]
Indeed, thanks
