### ISSUE TITLE
Server header exposing nginx version, wmap doesn't care?

### ISSUE THREAD

**Issue by ShadeLotus** [rapid7/metasploit-framework#5810]
Hi, after running a wmap_run -e against chadfurman.com on port 80 (my server, feel free), I get that the homepage is vuln because it says nginx.  However, the server header also says nginx (and the version!) and wmap_vuln -l doesn't mention it?  

https://github.com/rapid7/metasploit-framework/blob/master/plugins/wmap.rb

**Comment by hmoore-r7** [comment]
@ShadeLotus The WMAP maintainer hasn't been active in a while, we may look at removing this functionality entirely.

**Comment by ShadeLotus** [comment]
No!  That's sad!  Leave it in and tell anyone who complains to fix it themselves.

plx plx.
