### ISSUE TITLE
Add ability to kick off nexpose import via rest API

### ISSUE THREAD

**Issue by amngibson** [rapid7/metasploit-framework#5827]
Please add the ability to kick off a nexpose import via the rest API. 

Example RPC call that needs to be ported to REST. 

rpc_client.call('pro.start_import', {'workspace' => workspace_name, 'DS_NEXPOSE_CONSOLE' => nexpose_console_name, 'DS_NEXPOSE_SITE' => workspace_name})

**Comment by hmoore-r7** [comment]
This tracker is for Metasploit Framework development. Metasploit Framework does not expose a REST API. To request Pro features, please contact support and file a Request for Enhancement.
