### ISSUE TITLE
Please add ability to kick off a web scan via REST API

### ISSUE THREAD

**Issue by amngibson** [rapid7/metasploit-framework#5828]
Please add ability to kick off a web scan via REST API

Example RPC call that needs to be ported over to REST. 

rpc_client.call('pro.start_webscan', {'workspace' => workspace_name, 'DS_URLS' => device_ip_to_scan})

**Comment by hmoore-r7** [comment]
This tracker is for Metasploit Framework development. Metasploit Framework does not expose a REST API. To request Pro features, please contact support and file a Request for Enhancement.
