### ISSUE TITLE
Please add ability to create new workspace via REST API

### ISSUE THREAD

**Issue by amngibson** [rapid7/metasploit-framework#5829]
Please add ability to create new workspace via REST API

Example RPC call that needs to be ported over to REST

rpc_client.call('pro.workspace_add', {'name' => workspace_name}

**Comment by hmoore-r7** [comment]
This tracker is for Metasploit Framework development. Metasploit Framework does not expose a REST API. To request Pro features, please contact support and file a Request for Enhancement.
