### ISSUE TITLE
Please add ability to kick off web audit via REST API

### ISSUE THREAD

**Issue by amngibson** [rapid7/metasploit-framework#5830]
Please add ability to kick off web audit via REST API

Example RPC call that needs to be ported over to REST. 

rpc_client.call('pro.start_webaudit', { "workspace" => workspace_name,
      "DS_URLS" => urls_from_webscan_job,
      "DS_MAX_REQUESTS" => 1000,
      "DS_MAX_MINUTES" => 3,
      "DS_MAX_THREADS" => 5,
      "DS_MAX_INSTANCES" => 3})

**Comment by hmoore-r7** [comment]
This tracker is for Metasploit Framework development. Metasploit Framework does not expose a REST API. To request Pro features, please contact support and file a Request for Enhancement.
