### ISSUE TITLE
stdapi/sys/registry calls send_packet instead of send_request

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#5852]
The `Registry.close_key` calls `client.send_packet(request)` instead of `client.send_request(request)`.

This appears to be incorrect as only a very few places call `send_packet` directly... 

@bcook-r7 @OJ is this at all related to the hanging handles you were seeing with registry in meterpreter?

**Comment by Meatballs1** [comment]
The other places that do a close (e.g. process/thread/channel) do a `send_request(request, nil)` at least. There's not much practical difference at present but I think both are causing problems at present.

**Comment by Meatballs1** [comment]
https://github.com/rapid7/metasploit-framework/pull/5851

**Comment by bcook-r7** [comment]
Fixed a while back.
