### ISSUE TITLE
DLL injection always uses x86 assembly

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/metasploit-framework#5866]
I discovered when fixing exe injection for x64 that `SegmentInjector` also ignores architecture of the target and assumes x86 when injecting into DLLs. https://github.com/rapid7/metasploit-framework/blob/2b0f6e723d76802f534d82b1ee951a7b00ef304d/lib/msf/core/exe/segment_injector.rb#L103-L119

**Comment by hmoore-r7** [comment]
This is true, we never added 64-bit support for appended or injected segments on DLLs.
