### ISSUE TITLE
comma separated targets in mssql_login

### ISSUE THREAD

**Issue by iwm911** [rapid7/metasploit-framework#5869]
hi,

mssql_login (and pretty much all other aux modules) get rhosts as CIDR or single host.

it would be grate if it would be possible to enter a comma separated list of targets (like the one i get after scanning for a specific port).

Thanks!

**Comment by jlee-r7** [comment]
`RHOSTS` already accepts any number of nmap host notation strings separated by space, e.g.:
```
set RHOSTS 192.168.0-3.1,254 10.0,1.0,1.1,254
```
