### ISSUE TITLE
payload handler not starting on kali sana 2.0

### ISSUE THREAD

**Issue by amainyebriggs** [rapid7/metasploit-framework#5878]
payload handler freezes and never starts

**Comment by void-in** [comment]
@amainyebriggs As I mentioned at https://github.com/rapid7/metasploit-framework/issues/5877, ask support questions at https://community.rapid7.com. The github issues pages are used to report bugs in Metasploit. What you are experiencing is either a configuration option or a Kali issue both of which don't apply here.

**Comment by hmoore-r7** [comment]
This is not a support forum. If you can provide details on a given issue, please open a ticket. You might benefit from either the Kali forums or https://community.rapid7.com/
