### ISSUE TITLE
window 7 msf console: msfvenom unknown command 

### ISSUE THREAD

**Issue by codekraft-studio** [rapid7/metasploit-framework#5883]
is supported msfvenom in windows 7? actually i type msfvenom in msf console and it says **Unknow command**, I looked through the program folders and actually I got that file ..\metasploit\apps\pro\msf3\msfvenom

**Comment by bcook-r7** [comment]
Yes, msfvenom works on Windows 7 in general (I was recently testing it with the metasploit-omnibus package), but there may be an issue with how it is packaged with the Rapid7-supplied commercial installer.

Please direct questions like this to https://community.rapid7.com . This tracker is for issues or enhancement requests with metasploit-framework itself. Thanks!
