### ISSUE TITLE
Android L Payload Error

### ISSUE THREAD

**Issue by comertcimen** [rapid7/metasploit-framework#5901]
I have a meterpreter session on Android L (Samsung Galaxy Note 4)
But ls command not working sdcard
When i command ls on shell (in sdcard) it says opendir failed, Permission denied.

**Comment by wchen-r7** [comment]
That doesn't sound like a bug. It just means your privilege is low.

**Comment by bcook-r7** [comment]
Yes, this is expected behavior.
