### ISSUE TITLE
Permission denied exec

### ISSUE THREAD

**Issue by 8ob578** [rapid7/metasploit-framework#5903]
When I try to use the command ./msfvenom it comes up with: [-] Permission denied exec: ./msfvenom.
Same thing happens when I try to list all payloads:  msf > ./msfvenom -l payloads

**Comment by wchen-r7** [comment]
I'd say chmod your msfvenom. But you probably have a bigger problem than that.

**Comment by bcook-r7** [comment]
How did you get metasploit-framework, and what OS are you using?

**Comment by jlee-r7** [comment]
You probably want `msfconsole` to get the installed bin.

**Comment by wchen-r7** [comment]
So we've concluded that this isn't a bug in Metasploit, but an issue in your environment.

If you'd like to set up your own dev env, please make sure to follow this:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment

If you're not setting up your own dev env, you can try Kali:
https://www.kali.org/

Thank you.
