### ISSUE TITLE
Inconsistent msgpack string serialization

### ISSUE THREAD

**Issue by brandonprry** [rapid7/metasploit-framework#5904]
I recently picked up an older project I hadn't touched in a while and some stuff didn't work anymore. I realized that msgpack was not deserializing data in the same way it used to, treating some of the strings as pure binary data.

Eventually wiresharking msfrpcd with -S to disable SSL, I realized that the strings I was having trouble with are serialized as 8-bit binary (0xC4), as opposed to the strings that do work which are FixedRaw (0xA5 & 0xF0).

Notice in the partial response body below, LPORT is of type 0xA5 which is a Fixed raw of length 5. The string WORKSPACE on the other hand is type 0xC4 with a length of 0x09.

```
0000000: de00 22c4 0957 4f52 4b53 5041 4345 85c4  .."..WORKSPACE..
0000010: 0474 7970 65c4 0673 7472 696e 67c4 0872  .type..string..r
0000020: 6571 7569 7265 64c2 c408 6164 7661 6e63  equired...advanc
0000030: 6564 c3c4 0765 7661 7369 6f6e c2c4 0464  ed...evasion...d
0000040: 6573 63c4 2553 7065 6369 6679 2074 6865  esc.%Specify the
0000050: 2077 6f72 6b73 7061 6365 2066 6f72 2074   workspace for t
0000060: 6869 7320 6d6f 6475 6c65 c407 5645 5242  his module..VERB
0000070: 4f53 4586 c404 7479 7065 c404 626f 6f6c  OSE...type..bool
0000080: c408 7265 7175 6972 6564 c2c4 0861 6476  ..required...adv
0000090: 616e 6365 64c3 c407 6576 6173 696f 6ec2  anced...evasion.
00000a0: c404 6465 7363 c41f 456e 6162 6c65 2064  ..desc..Enable d
00000b0: 6574 6169 6c65 6420 7374 6174 7573 206d  etailed status m
00000c0: 6573 7361 6765 73c4 0764 6566 6175 6c74  essages..default
00000d0: c2a5 4c50 4f52 5486 c404 7479 7065 c404  ..LPORT...type..
00000e0: 706f 7274 c408 7265 7175 6972 6564 c3c4  port..required..
00000f0: 0861 6476 616e 6365 64c2 c407 6576 6173  .advanced...evas
0000100: 696f 6ec2 c404 6465 7363 c40f 5468 6520  ion...desc..The 
0000110: 6c69 7374 656e 2070 6f72 74c4 0764 6566  listen port..def
0000120: 6175 6c74 cd11 5cc4 0552 484f 5354 86c4  ault..\..RHOST
```

I am researching what is causing this, and I am not sure if this is something that has changed in msgpack-cli or metasploit, I have no idea how long the strings have been serialized this way.

**Comment by brandonprry** [comment]
Seems the fixed raw strings can only be up to 16 bytes long (0-f) and the best solution might be to make all strings serialize as an actual string type or as a binary type all of the time.

**Comment by hmoore-r7** [comment]
@brandonprry This serialization is outside of the control of Metasploit (its automatic in the msgpack libary). A better fix would be for the .NET library to treat both types as strings.

**Comment by brandonprry** [comment]
Yeah, that's ok.
