### ISSUE TITLE
Meterpreter sysinfo should report the real OS major/minor/build on Windows 10+

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#5923]
Currently, sysinfo() may return a fake version on Windows 8+ due to changes in GetVersionEx. Since the sysinfo() result is used to populate the database and fingerprint the system, it needs to provide an accurate response. Related links:
* https://social.msdn.microsoft.com/Forums/windowsdesktop/en-us/6f22c643-7a33-4581-9fbb-5462c1602f8b/windows-10-getversionex
* http://www.codeproject.com/Articles/678606/Part-Overcoming-Windows-s-deprecation-of-GetVe
* https://msdn.microsoft.com/en-us/library/windows/desktop/ms724358(v=vs.85).aspx (via PEB method in the comments)

**Comment by bcook-r7** [comment]
Fix merged, thanks.
