### ISSUE TITLE
DB error on kali 2.0 development environment (git)

### ISSUE THREAD

**Issue by g33xter** [rapid7/metasploit-framework#5954]
My setup is kali linux 2.0 & msf development environment, I have already connected db to postgresql but after search it showing no db connected. I have attached screen shot.

![screenshot from 2015-09-09 02 36 03](https://cloud.githubusercontent.com/assets/8503135/9758486/c17cbfce-569b-11e5-81cf-596147ca96a2.png)

**Comment by all3g** [comment]
It's same to me.  We can reconnect to database manually.

```
msf > db_status 
[*] postgresql connected to msfdb
msf > search wordpress
[!] Database not connected or cache not built, using slow search
^C[-] Error while running command search: 
msf > db_disconnect 
msf > db_connect -y /home/notfound/.msf4/database.yml
[*] Rebuilding the module cache in the background...
msf > search wordpress

Matching Modules
================

   Name                                                           Disclosure Date  Rank       Description
   ----                                                           ---------------  ----       -----------
   auxiliary/admin/http/wp_custom_contact_forms                   2014-08-07       normal     WordPress custom-contact-forms Plugin SQL Upload
   auxiliary/admin/http/wp_easycart_privilege_escalation          2015-02-25       normal     WordPress WP EasyCart Plugin Privilege Escalation
   auxiliary/admin/http/wp_wplms_privilege_escalation             2015-02-09       normal     WordPress WPLMS Theme Privilege Escalation
   auxiliary/dos/http/wordpress_long_password_dos                 2014-11-20       normal     WordPress Long Password DoS
   auxiliary/dos/http/wordpress_xmlrpc_dos                        2014-08-06       normal     Wordpress XMLRPC DoS
....
```

**Comment by g33xter** [comment]
I have tried this earlier but no any luck.
![screenshot from 2015-09-09 03 01 41](https://cloud.githubusercontent.com/assets/8503135/9759028/2d84e270-569f-11e5-8b8d-1d684079d1e1.png)

**Comment by all3g** [comment]
Please remove development record, and try it again. My database.yml:

```
production: &pgsql
    adapter: postgresql
    database: msfdb
    username: msfuser
    password: msfpass
    host: 127.0.0.1
    port: 5432
    pool: 5
    timeout: 5
```

**Comment by g33xter** [comment]
Still same error though.
![screenshot from 2015-09-09 03 08 53](https://cloud.githubusercontent.com/assets/8503135/9759174/1e1f1ca0-56a0-11e5-9448-f7300b79dfeb.png)

**Comment by all3g** [comment]
Please try it in a new msfconsole, not in the same shell.

**Comment by g33xter** [comment]
Already tried :(

**Comment by bcook-r7** [comment]
This appears to be broken beyond kali too.

**Comment by bcook-r7** [comment]
Not sure if the Kali package has pulled in the fix yet, but it should at least be addressed in metasploit now.

**Comment by bogdy1976** [comment]
I've copied the database.yml file located on "/opt/metasploit/apps/pro/ui/config" on "/root/.msf4" and now it seams it work..
![screenshot from 2015-10-30 10 31 12](https://cloud.githubusercontent.com/assets/5390784/10842384/7685ab10-7ef1-11e5-81ed-a73e9fe814a3.png)

**Comment by honest2129** [comment]
msf > db_status
[*] postgresql connected to msf
msf > db_rebuild_cache
[*] Purging and rebuilding the module cache in the background...

Works Great for me :)

**Comment by honest2129** [comment]
msf > search voip

Matching Modules
================

   Name                                     Disclosure Date  Rank    Description
   ----                                     ---------------  ----    -----------
   auxiliary/voip/asterisk_login                             normal  Asterisk Manager Login Utility
   auxiliary/voip/cisco_cucdm_call_forward                   normal  Viproy CUCDM IP Phone XML Services - Call Forwarding Tool
   auxiliary/voip/cisco_cucdm_speed_dials                    normal  Viproy CUCDM IP Phone XML Services - Speed Dial Attack Tool
   auxiliary/voip/sip_deregister                             normal  SIP Deregister Extension
   auxiliary/voip/sip_invite_spoof                           normal  SIP Invite Spoof
