### ISSUE TITLE
post/osx/manage/webcam does not save the snapshot

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#5963]
The post/osx/manage/webcam module takes a snapshot with the webcam, but saves an empty png file.

Also, Juan and I also this warning: "DL is deprecated, please use Fiddle". We're on Ruby 2.1.6

**Comment by wchen-r7** [comment]
@MSadek-r7 Can you test this right quick?

**Comment by wvu-r7** [comment]
@wchen-r7: I tested this last week and got the same result.

**Comment by wchen-r7** [comment]
@wvu-r7 Ok, damn :-(

**Comment by joevennix** [comment]
This may very well be broken in Ruby 2.1.6. A good temporary measure would be to update the module to call the system Ruby, which always lags a little ways behind. That will buy you some time.

One long-term fix will be to rewrite this piece of shit: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/core/post/osx/ruby_dl.rb

To use fiddle proper. But then we will break back-compat with Ruby versions bundled with older OSX versions. I really don't want to add *another* compatibility layer on top of all this crap, that's what makes it so annoying to work with in the first place.

Another probably more sane approach would be to just write this as a standalone obj-c executable, and drop it to disk and execute. We would lose the "diskless" advantage of the current approach (the entire Ruby script is stringified and passed to Ruby with `-e`) but it's probably worth it, and if there is ever an OSX meterpreter, we could make it a dylib and load it into the meterpreter process on-demand.

**Comment by joevennix** [comment]
Actually, given the way its currently written (dlopen and pray), it may be straightforward-ish to port into C that gets compiled at runtime with metasm, then put that in an executable. That would avoid committing another binary to the repo.

**Comment by joevennix** [comment]
I rewrote this in C, and it works okay when compiled locally:

https://gist.github.com/joevennix/352c144b73d66ec69718

But I am stuck on the fact that `dlopen` and `dlsym` are not linked in the OSX macho msf executable template, and are not loaded by Metasm's macho generation code.
