### ISSUE TITLE
Whitelisting UUIDs for reverse_tcp_uuid handlers

### ISSUE THREAD

**Issue by silverqx** [rapid7/metasploit-framework#5975]
reverse_tcp's handlers doesn't contain **IgnoreUnknownPayloads** setting.

**Comment by hmoore-r7** [comment]
Updating the description to clarify that this should be for the ``reverse_tcp_uuid`` handlers.

**Comment by bcook-r7** [comment]
This is similar to issue #5986 , or did I misinterpret it?

**Comment by hmoore-r7** [comment]
@bcook-r7 A little different; SSL pinning is for whether Meterpreter trusts Metasploit, UUIDs are for whether Metasploit trusts a given Meterpreter (or stage).

**Comment by szachara** [comment]
@hmoore-r7 Exactly as wrote.
