### ISSUE TITLE
TLS Certificate Pinning for reverse_tcp stagers

### ISSUE THREAD

**Issue by szachara** [rapid7/metasploit-framework#5986]
Add **StagerVerifySSLCert** option for the reverse_tcp stagers.

**Comment by bcook-r7** [comment]
Maybe we could simply do reverse_http for the staging portion and switch to reverse_tcp for the rest. Assuming that TLS is TLS regardless of what's underneath, this would be possible to implement on Windows at least, maybe OS X. More difficult with OpenSSL-using systems.

**Comment by hmoore-r7** [comment]
It might significantly increase the size of the payloads to build a full HTTP request as well.

**Comment by busterb** [comment]
This isn't going to happen since we're not using OpenSSL for reverse_tcp anymore. UUIDs would be more feasible, or preshared keys, which are on the roadmap.
