### ISSUE TITLE
Gem::InstallError: metasploit-concern requires Ruby version >= 2.1. 

### ISSUE THREAD

**Issue by ishakahmaro** [rapid7/metasploit-framework#6024]
Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
An error occurred while installing metasploit-concern (1.0.0), and Bundler
cannot continue.
Make sure that `gem install metasploit-concern -v '1.0.0'` succeeds before
bundling.

MacBook-alkhas-b-Max:metasploit-framework max$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies............
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.11.2
Using thread_safe 0.3.5
Using tzinfo 0.3.44
Using activesupport 4.0.13
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.0.13
Using mime-types 2.6.1
Using mail 2.6.3
Using actionmailer 4.0.13
Using activemodel 4.0.13
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using activerecord 4.0.13
Using arel-helpers 2.1.0
Using ffi 1.9.8
Using childprocess 0.5.5
Using diff-lcs 1.2.5
Using gherkin 2.12.2
Using multi_test 0.1.2
Using cucumber 1.3.19
Using rspec-expectations 2.99.2
Using aruba 0.6.2
Using bcrypt 3.1.10
Using bundler 1.10.6
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using xpath 2.0.0
Using capybara 2.4.4
Using coderay 1.1.0
Using thor 0.19.1
Using railties 4.0.13
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.0.13
Using cucumber-rails 1.4.2
Using docile 1.1.5
Using factory_girl 4.5.0
Using factory_girl_rails 4.5.0
Using fivemat 1.2.1
Using rkelly-remix 0.0.6
Using jsobfu 0.2.1
Using json 1.8.3
Using metasm 1.0.2
Installing metasploit-concern 1.0.0

Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
An error occurred while installing metasploit-concern (1.0.0), and Bundler
cannot continue.
Make sure that `gem install metasploit-concern -v '1.0.0'` succeeds before
bundling.

please help me

**Comment by bcook-r7** [comment]
type 'ruby --version' and check that you have Ruby version >= 2.1 installed before proceeding.

If you want an easy OS X installer that already includes the correct ruby version, see these instructions:

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#os-x
