### ISSUE TITLE
mssql_idf

### ISSUE THREAD

**Issue by schlpr0k** [rapid7/metasploit-framework#6028]
Module:  metasploit-framework/modules/auxiliary/admin/mssql/mssql_idf.rb 

Trying to execute the module against a MSSQL 2008 Server with valid credentials returns the following error message: 

msf auxiliary(mssql_idf) > run

[-] Auxiliary failed: NoMethodError undefined method \`[]' for nil:NilClass
[-] Call stack:
[-] /auxiliary/admin/mssql/mssql_idf.rb:101:in \`run'
[*] Auxiliary module execution completed

**Comment by wvu-r7** [comment]
Since you said valid creds, this might be indicative of a bigger problem (in the mixin) than just a ```nil``` bug.

**Comment by wvu-r7** [comment]
Yeah, I'm getting the same error with 2012.

**Comment by wvu-r7** [comment]
@schlpr0k: Please create a new issue when you run into the next stack trace.
