### ISSUE TITLE
payload/linux/x64/shell/reverse_tcp broken

### ISSUE THREAD

**Issue by r-ku** [rapid7/metasploit-framework#6040]
Stager does not receive any data and tries to execute empty buffer resulting in segfault. No special steps needed to reproduce.

**Comment by bcook-r7** [comment]
This is broken in commit 0d56b3e - the handler stops sending a payload at that point.

**Comment by OJ** [comment]
Dammit.

**Comment by OJ** [comment]
Not sure about the UUID thing to be honest. By default the listeners only wait for UUIDs when told to wait. The x64 stuff hasn't yet been ported to metasm, and still doesn't have any UUID related stuff in it, hence the listener should default to _not_ waiting for the UUID.

I'll dive into this.

**Comment by bcook-r7** [comment]
Thanks, and I agree, there weren't any changes in the stagers that looked problematic.

This fixes it:
```
--- a/modules/payloads/stagers/linux/x64/reverse_tcp.rb
+++ b/modules/payloads/stagers/linux/x64/reverse_tcp.rb
@@ -14,6 +14,14 @@ module Metasploit3
   include Msf::Payload::Stager
   include Msf::Payload::Linux

+  #
+  # By default, we don't want to send the UUID, but we'll send
+  # for certain payloads if requested.
+  #
+  def include_send_uuid
+    false
+  end
+
   def initialize(info = {})
     super(merge_info(info,
       'Name'          => 'Reverse TCP Stager',
```

but I thought the UUID should actually default to off at the mixin level. So, dunno how that happened.

**Comment by OJ** [comment]
I was about to push that exact change! Feel free to PR and I'll land it.

Odd, it should default to false. Grrr..

**Comment by OJ** [comment]
@bcook-r7 I think I'm going to refactor this slightly so that it does default to `false` when it's not included, and those that specifically want it have to opt in. Clearly I failed at that the last time.

You cool with that?

**Comment by bcook-r7** [comment]
Yeah, that's the right way to go.

**Comment by bcook-r7** [comment]
Thank you man!
