### ISSUE TITLE
Error while running command db_connect: can't dup NilClass

### ISSUE THREAD

**Issue by macubergeek** [rapid7/metasploit-framework#6043]
I've installed github version of metasploit on mac os x Yosemite
when I launch msfconsole I get error:
[*] Processing /Users/james.kelly/.msf4/msfconsole.rc for ERB directives.
resource (/Users/james.kelly/.msf4/msfconsole.rc)> db_connect -y /Applications/GITLIST-PACKAGES/metasploit-framework/config/database.yaml
[-] Error while running command db_connect: can't dup NilClass

Call stack:
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/msf/core/db_manager/connection.rb:39:in `dup'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/msf/core/db_manager/connection.rb:39:in `connect'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1989:in `cmd_db_connect'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/msf/ui/console/driver.rb:480:in `load_resource'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/msf/ui/console/driver.rb:231:in `initialize'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Applications/GITLIST-PACKAGES/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
resource (/Users/james.kelly/.msf4/msfconsole.rc)> workspace -a YourProject
[-] Database not connected

When I connect manually:
msf > db_status
[*] postgresql selected, no connection
msf > db_connect msf_user:msf_user@127.0.0.1:5432/msf_database
[*] Rebuilding the module cache in the background...
msf > db_status
[*] postgresql connected to msf_database
msf > 

Shouldn't the last line read postgresql connected to msg_database?

how do I fix this?

**Comment by wvu-r7** [comment]
Your ```database.y{,a}ml``` file is insufficient. Looks like it's missing a ```production``` definition.

**Comment by wvu-r7** [comment]
Here's the relevant definition: https://github.com/rapid7/metasploit-framework/blob/master/config/database.yml.example#L20.
