### ISSUE TITLE
Long URLs

### ISSUE THREAD

**Issue by savetree** [rapid7/metasploit-framework#6047]
Hi, is it possible to turn off UUID feature or make Metasploit to use short URLs (4 chars max) for stager and meterpreter connection? In reverse_http(s) payloads.

**Comment by OJ** [comment]
It isn't possible to turn off the UUID feature, and it is not possible to go back to the "old" way of doing things (eg. using the likes of `INITM`).

You can reduce the length of the URI when generating payloads but 4 chars isn't enough. You'd have to hack your own functionality to support that.

**Comment by hmoore-r7** [comment]
5-byte URLs are used (without UUID, like before) if the payload doesn't have space for more. You can generate these by passing a small ``space`` value to msfvenom, like so:
```msfvenom -s 100 <stuff>```
