### ISSUE TITLE
Java RMI scanner stack traces against Metasploitable2

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#6050]
```
msf auxiliary(java_rmi_server) > run

[-] Auxiliary failed: Rex::Java::Serialization::DecodeError Failed to unserialize content
[-] Call stack:
[-]   /work/msf-hdm/lib/rex/java/serialization/model/contents.rb:17:in `decode_content'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:127:in `block in decode_class_fields'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:123:in `each'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:123:in `decode_class_fields'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:109:in `decode_class_data'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/new_object.rb:37:in `decode'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/contents.rb:29:in `decode_content'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/stream.rb:43:in `decode'
[-]   /work/msf-hdm/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/return_value.rb:40:in `decode'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/element.rb:30:in `decode'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/return_data.rb:38:in `decode_return_value'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/element.rb:58:in `block in decode'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/element.rb:56:in `each'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/element.rb:56:in `decode'
[-]   /work/msf-hdm/lib/rex/proto/rmi/model/element.rb:30:in `decode'
[-]   /work/msf-hdm/lib/msf/java/rmi/client.rb:112:in `recv_return'
[-]   /work/msf-hdm/modules/auxiliary/scanner/misc/java_rmi_server.rb:81:in `run_host'
[-]   /work/msf-hdm/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /work/msf-hdm/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /work/msf-hdm/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
msf auxiliary(java_rmi_server) > 
```

**Comment by Andrewbarmer** [comment]
I have the same issue:

[-] Auxiliary failed: Rex::Java::Serialization::DecodeError Failed to unserialize Utf
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/utf.rb:33:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_class_desc.rb:48:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/contents.rb:43:in `decode_content'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/class_desc.rb:26:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:32:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/contents.rb:29:in `decode_content'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:127:in `block in decode_class_fields'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:123:in `each'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:123:in `decode_class_fields'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:109:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:37:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/contents.rb:29:in `decode_content'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:127:in `block in decode_class_fields'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:123:in `each'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:123:in `decode_class_fields'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:109:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:105:in `decode_class_data'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/new_object.rb:37:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/contents.rb:29:in `decode_content'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/stream.rb:43:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/java/serialization/model/element.rb:18:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/return_value.rb:40:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/element.rb:30:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/return_data.rb:38:in `decode_return_value'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/element.rb:58:in `block in decode'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/element.rb:56:in `each'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/element.rb:56:in `decode'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rmi/model/element.rb:30:in `decode'
[-]   /usr/share/metasploit-framework/lib/msf/java/rmi/client.rb:112:in `recv_return'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/misc/java_rmi_server.rb:81:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'

**Comment by jvazquez-r7** [comment]
Thanks @hmoore-r7 and @Andrewbarmer, proposed fix here: https://github.com/rapid7/metasploit-framework/pull/6070

@hmoore-r7 I can reproduce your stacktrace, but not exactly the one reported by @Andrewbarmer. I'd bet the root cause is the same, so hopefully #6070 helps in both cases.
