### ISSUE TITLE
pop3_version EOFError

### ISSUE THREAD

**Issue by Andrewbarmer** [rapid7/metasploit-framework#6064]
If i run i get:

EOFError ["/usr/share/metasploit-framework/lib/rex/io/stream.rb:203:in `get_once'", "/usr/share/metasploit-framework/modules/auxiliary/scanner/pop3/pop3_version.rb:29:in `run_host'", "/usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'", "/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'", "/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'"]

**Comment by wvu-r7** [comment]
See https://github.com/rapid7/metasploit-framework/issues/6063#issuecomment-146674311.

**Comment by Andrewbarmer** [comment]
Thank you. There was another service on this port
