### ISSUE TITLE
Metasploit_Override

### ISSUE THREAD

**Issue by BacteriaLambda** [rapid7/metasploit-framework#6109]
Unable to handle kernel NULL pointer dereference at virtual address 0xd34db33f
EFLAGS: 00010046
eax: 00000001 ebx: f77c8c00 ecx: 00000000 edx: f77f0001 esi: 803bf014 edi: 80237f84 esp: 80237f60 ds: 0018 es: 0018 ss: 0018
Process Swapper (Pid:   0, Process nr: 0, stackpage=80377000)

Code:  00 00 00 00 M3 T4 SP L0 1T FR 4M 3W OR K! V3 R5 I0 N4 00 00 00 00

Aiee, killing Interrupt handler
Kernel panic: Attemt to kill the idle task!
In Swapper task - not syncing

I Overrided the Framework with a secret...
looking for some fixers... i think its not possible to fix this bug

sudo su
~sudo sh
#su (mwtasploit)
~killall su

stay tuned
greez TaChYoN

**Comment by void-in** [comment]
Can't understand what you are trying to ask.

**Comment by BacteriaLambda** [comment]
I say its easy to override metasploit!
with bin bash
Am 20.10.2015 11:33 schrieb "Waqas Ali" <notifications@github.com>:

**Comment by BacteriaLambda** [comment]
whole framework lais down if i overrode it like this...
Am 20.10.2015 11:36 schrieb "alexandros hostettler" <
hostettleralexandros@gmail.com>:

I say its easy to override metasploit!
with bin bash
Am 20.10.2015 11:33 schrieb "Waqas Ali" <notifications@github.com>:

**Comment by BacteriaLambda** [comment]
or like this xoxo
Am 20.10.2015 11:40 schrieb hostettleralexandros@gmail.com:

whole framework lais down if i overrode it like this...
Am 20.10.2015 11:36 schrieb "alexandros hostettler" <
hostettleralexandros@gmail.com>:

I say its easy to override metasploit!
with bin bash
Am 20.10.2015 11:33 schrieb "Waqas Ali" <notifications@github.com>:

**Comment by BacteriaLambda** [comment]
i talk about an infinity loop in binbash....
if u sudo 4 su
the  su 4 sh and su again.. have to send a killall ini in su and a new
shell will be born worx fine no cache no files only access to everything
without msf xp
everyone is allowed by the cernel to access and init0 and the whole
framework... root.cern.ch has also the same bug in theyr linux cernell...
Am 20.10.2015 12:34 schrieb "Waqas Ali" <notifications@github.com>:

**Comment by BacteriaLambda** [comment]
i made a picture....
this is fucking replication!!!!
and its free!!4all!!!!
Am 20.10.2015 15:43 schrieb "alexandros hostettler" <
hostettleralexandros@gmail.com>:

**Comment by BacteriaLambda** [comment]
i made a picture....

i talk about an infinity loop in binbash....
if u sudo 4 su
the  su 4 sh and su again.. have to send a killall ini in su and a new
shell will be born worx fine no cache no files only access to everything
without msf xp
everyone is allowed by the cernel to access and init0 and the whole
framework... root.cern.ch has also the same bug in theyr linux cernell...
Am 20.10.2015 12:34 schrieb "Waqas Ali" <notifications@github.com>:

**Comment by OJ** [comment]
Please stop now. If you have a security issue or concern, then please reach out via the community page at https://community.rapid7.com/

**Comment by BacteriaLambda** [comment]
im so glade that there is no interest...

not my problem if your linux is not perfectly running...

recognize it self...

sudo su
then sh
then su again
in su killall su

trust me there is nothing and it will never bee anything...

**Comment by BacteriaLambda** [comment]
sorry for this ugly brain storming im doing, need to tell!!! this is too
impossible please dont wast yout time and look at the pic i senf you

i created some msf bots in my shell
look at the pic... thy work similary to each other..

hope i are interest....
i can repeat every programm if i got the source....

here is the pic
Am 20.10.2015 16:39 schrieb "alexandros hostettler" <
hostettleralexandros@gmail.com>:

im so glade that there is no interest...

not my problem if your linux is not perfectly running...

recognize it self...

sudo su
then sh
then su again
in su killall su

trust me there is nothing and it will never bee anything...

**Comment by void-in** [comment]
@OJ Don't worry about this. I am locking this conversation.

**Comment by wvu-r7** [comment]
wat
