### ISSUE TITLE
ActiveRecord CharacterNotInRepertoire

### ISSUE THREAD

**Issue by averagesecurityguy** [rapid7/metasploit-framework#6123]
ActiveRecord is having trouble processing UTF8. There are a couple of issues ope already related to a Post module and Meterpreter. This is affecting password bruteforcing.

    [-] 192.168.199.146:22 SSH - Failed: 'root:?ankees'
    [*] Error: 192.168.199.146: ActiveRecord::StatementInvalid PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0x81
    : SELECT  "metasploit_credential_privates".* FROM "metasploit_credential_privates"  WHERE "metasploit_credential_privates"."data" = '?ankees'  ORDER BY "metasploit_credential_privates"."id" ASC LIMIT 1

A second issue is that Metasploit is doing a DB lookup even on a failed password. Doesn't that slow down the bruteforcing process?

**Comment by jlee-r7** [comment]
@averagesecurityguy Can you give us the actual bytes you used for that password, please?

**Comment by jlee-r7** [comment]
I used U+0178 and it seems to work for me:
```
[*] 192.168.1.1:22 SSH - Starting bruteforce
[-] 192.168.1.1:22 SSH - Failed: 'root:Ÿankees'
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by averagesecurityguy** [comment]
I used hashcat's --stdout flag along with the 500 worst passwords and the best64 rules to create a password list. The best I can tell these are the bytes that were sent to the sever.

8161 6e6b 6565 730a

**Comment by averagesecurityguy** [comment]
BTW, I'm using metasploit v4.11.4-2015090201

**Comment by bcook-r7** [comment]
Hmm, I wonder if this is a kali specific issue. Can you share what your locale command shows? Are you using tmux or screen?
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

Might also be something specific to how msfdb initiailizes the database on Kali linux systems. We should also peek at how Kali's postgresql is built.

**Comment by averagesecurityguy** [comment]
Sorry, I don't have access to the Kali box anymore. It was built by a client and has been taken offline now. I've used that same list before on other Kali boxes and have never had a problem, so it could have been a build specific issue.

If I run across the issue again, I'll try to collect more info.

**Comment by bcook-r7** [comment]
Suspecting this was a database setup issue on second glance. I am going to close the issue for now, but please add a new one if you see it again. Thanks!
