### ISSUE TITLE
Ugly backtraces on Ctrl-C for most of the msf ruby scripts

### ISSUE THREAD

**Issue by reider-roque** [rapid7/metasploit-framework#6170]
Enhancement request. 

Many msf ruby scripts take their time to do their job (or just to start). And there is a higher probability of user hitting Ctrl-C during waiting time (e.g. because while waiting user noticed that provided options were not correct; I do it all the time). And when you do it you are presented with a long and ugly ruby backtrace.

One way to solve the problem is to insert the `begin` keyword in the beginning of the script and the following block of code in the very end --

``` ruby
rescue Interrupt
  $stderr.puts "\nAborted!"
  exit 1
end
```

The solution is probably not elegant (it may be better to insert rescue blocks in particular places in the script) but it gives you a starting point.

I didn't try it with every msf ruby script, but no more backtraces for msfvenom on my machine! Till the next overwriting metasploit update at least :smiley:

**Comment by wchen-r7** [comment]
You mean the tool scripts, right?

**Comment by reider-roque** [comment]
Right. For example, nasm_shell.rb, pattern_create.rb, etc.

**Comment by pingport80** [comment]
I would like to work one this issue, Can you please assign me this?
