### ISSUE TITLE
meterpreter_reverse_tcp.rb/meterpreter_bind_tcp.rb "NameError uninitialized constant Msf::Sessions::MeterpreterOptions"

### ISSUE THREAD

**Issue by qgrosperrin** [rapid7/metasploit-framework#6174]
Not sure if this issue is related to my environment (it seems like related errors could be environment dependant, but can't find a solution to this particular problem).

Upon loading msfconsole I get the following warning:
```
sudo msfconsole -q
[-] WARNING! The following modules could not be loaded!
[-]     /opt/metasploit-framework/modules/payloads/singles/python/meterpreter_reverse_tcp.rb: NameError uninitialized constant Msf::Sessions::MeterpreterOptions
[-]     /opt/metasploit-framework/modules/payloads/singles/python/meterpreter_bind_tcp.rb: NameError uninitialized constant Msf::Sessions::MeterpreterOptions
```

Versions
```
msf > version
Framework: 4.11.5-dev-7f19d95
Console  : 4.11.5-dev-7f19d95.15168

msf > uname -a
[*] exec: uname -a

Linux **removed** 3.13.0-43-generic #72~precise1-Ubuntu SMP Tue Dec 9 12:14:18 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
The OS is running Ubuntu 12.04.5 LTS.

My postgres db is also connected
```
msf > db_status
[*] postgresql connected to msf
```

I have tried rebuilding the cache (`db_rebuild_cache`), disconnecting then reconnecting the db (`db_disconnect` then `db_connect msf:msf@localhost:5432/msf`), and also disconnecting the db, exiting msfconsole then reloading msfconsole. However, none of that worked.

`reload_all` appears to work properly, because the warning message does not appear when run.

**Comment by void-in** [comment]
A require statement:
```ruby
require 'msf/base/sessions/meterpreter_options'
```
should be included before
```ruby
require 'msf/core/payload/python/meterpreter_loader'
```
since it including the mixin at https://github.com/rapid7/metasploit-framework/blob/7f19d95ad830f11788c7174d08f62a0a3b2c3ee2/lib/msf/core/payload/python/meterpreter_loader.rb#L17
