### ISSUE TITLE
KeeFarce - Extracts passwords from a KeePass 2.x database, directly from memory. 

### ISSUE THREAD

**Issue by strasharo** [rapid7/metasploit-framework#6188]
I think this would be a very good addition to metasploit as a plugin:
https://github.com/denandz/KeeFarce

Thank you. :)

**Comment by OJ** [comment]
Thanks. This has indeed crossed our radar. I'm looking at ways to incorporate this. My guess is that it won't be a plugin, probably just a `post/windows/gather` module.

**Comment by strasharo** [comment]
Either way will do, as long as a binary doesn't touch the disk, because AV is already flagging the file as malicious.

**Comment by luisfontes19** [comment]
we can send and execute the exe in ram with the “execute” command but it has some dll dependencies that need to be in the same folder that the exe. Is there a way to overcome that issue?
