### ISSUE TITLE
Add ability to import masscan results

### ISSUE THREAD

**Issue by jlmurray** [rapid7/metasploit-framework#6208]
Add capability to import masscan results using db_import and  db_masscan commands (like current nmap capability). 

Masscan results are similar to nmap but it runs asynchronously, operating more like scanrand, unicornscan, and ZMap.
- Homepage: [https://github.com/robertdavidgraham/masscan](https://github.com/robertdavidgraham/masscan)
- Tested on: Masscan 1.0.3 (Mac OS 10.10.5, Kali Linux 2.0.0 (VirtualBox VM))
- Usage: 
  - install Masscan (comes with Kali Linux)
  - run db_import with a masscan xml file or db_masscan to import masscan results into msf database

```
msf > db_masscan -p80 192.168.1.0/24

```

OR

```
$ masscan -p80 192.168.1.0/24 -oX output.xml

msf > db_import output.xml
```

**Comment by jhart-r7** [comment]
The masscan output is supposed to be compatible with nmap output, but https://github.com/robertdavidgraham/masscan/issues/100 prevents this from working.  I've submitted https://github.com/robertdavidgraham/masscan/pull/199 to hopefully get that fixed. 

Once that PR is landed we can re-evaluate whether or not this issue and #6219 are needed at all.  For now, I'm closing the later and keeping the former open but as delayed.

**Comment by nixawk** [comment]
@jhart-r7 Is that a valid way to make db_import support the masscan xml ? ex: 

```
$ sudo masscan -v -p80 -oX 192.168.0.0-masscan-80.xml -sS 192.168.0.0/16  
```

**Comment by wvu-r7** [comment]
I decided to move forward with this, since it's been bugging me lately. Thanks for your time toward debugging this, @jhart-r7 && @jlmurray. Until https://github.com/robertdavidgraham/masscan/pull/199 lands, we're going with a stopgap fix.
