### ISSUE TITLE
Support apk format for msfvenom -x (custom template)

### ISSUE THREAD

**Issue by Megaeloelo** [rapid7/metasploit-framework#6229]
Can anyone give me the command to create android payload with custom template ? All my commands only create apk file with 8000 bytes . Sorry for bad english .

**Comment by Megaeloelo** [comment]
Anyone can help? I use latest version of metasploit framework .

**Comment by bcook-r7** [comment]
I do not believe that msfvenom currently works with arbitrary .apk templates yet. Someone did write a standalone script that can do something similar (which we aspire to integrate into msfvenom at some point). See #5932

**Comment by Megaeloelo** [comment]
Problem solved .

**Comment by nvcnon** [comment]
> مشکل حل شده.

How ?

**Comment by bcoles** [comment]
https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/android/meterpreter/injection.md
