### ISSUE TITLE
Automatically elog when print_error is used

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#6244]
I have been thinking we should do elog() when print_error is used. That way modules won't have to manually do it and miss logging important debugging information in framework.log. What do you guys think?

**Comment by void-in** [comment]
@wchen-r7 The method for raw logging should be rlog(). Currently it is show rlow() in the link.

**Comment by wchen-r7** [comment]
@void-in Nice catch, thanks! (Fixed)
