### ISSUE TITLE
Feature Request - Add input file and output file option to all auxiliary/scanner modules

### ISSUE THREAD

**Issue by wintermute4316** [rapid7/metasploit-framework#6253]
In cases where you have several hosts (fifty or more) across many different subnets, it would be a great feature to allow a file input to the auxiliary/scanner modules formatted either with an ip address/fqdn (ie RHOSTS) one per line or ip address/fqdn:port (ie. RHOSTS:RPORT) one per line, depending on the inputs for that scanner module.

Also, allowing an output file option so all console output from the scanner module is written to a file.

**Comment by JohnMartinelli** [comment]
I can write this. Does anyone else want to help?

**Comment by JohnMartinelli** [comment]
Currently locked out of my GitHub account due to 2-factor authorization :/
new phone number. I'll get replies in my email though and im DYING to start
contributing !

On Wed, Nov 18, 2015 at 9:52 AM, John Martinelli <johnnymartinelli@gmail.com

**Comment by void-in** [comment]
@wintermute4316 The RHOSTS option already take file as an input through the file://<file path> syntax. Also, if you want to output the console output to a text file, just set the spool option and all the console output will be saved in a file.

**Comment by wintermute4316** [comment]
Thanks @void-in.  That file:// input for RHOSTS, I'm assuming that only allows a list ip addresses or fqdn's one per line but not the accompanying RPORT?  For example, for http scanners you may have web servers that listen on many different ports (80, 443, 8080, 8443, etc...) and it would beneficial to specify a file with RHOSTS:RPORT for each since the ports can vary.  If there are other required input parameters for a particular scanner module, those could also be allowed in this delimited input file, which saves a lot of time if you're scanning many hosts across different subnets where these parameters (port, etc..) vary and where you may already have the data available that you can easily massage into a file format for input.  On the output option, the spool option works.  Thanks.
