### ISSUE TITLE
vncinject

### ISSUE THREAD

**Issue by kokoown2** [rapid7/metasploit-framework#6295]
I looked at the source of vncinject code, and i want to use without the metasploit...
is there a way to call the dll functions with my arguments?
tried rundll32.exe vncdll.dll,Init / ReflectiveLoader

**Comment by kokoown** [comment]
Maybe there is a way to make a satgeless vncinjector?

**Comment by hdm** [comment]
The Init function needs to be called with a socket handle as the argument.

**Comment by kokoown2** [comment]
i have setup a socket that connect to the computer and pass it in the args...
but how should i start the reverse listener? i tried vncviewer -listen, connect via the socket but it doesnt send the packets.. i was that metasploit use tightvnc to setup the listener
how should i do that?

**Comment by hdm** [comment]
Github tickets are not for support requests, try IRC or https://community.rapid7.com/
