### ISSUE TITLE
hello ! im install the msf 3.7.2 verison because i love this verison and it is easy .... but i have proplem i cant add host in armitage 

### ISSUE THREAD

**Issue by ali1997** [rapid7/metasploit-framework#6310]

**Comment by ali1997** [comment]
![screenshot_25](https://cloud.githubusercontent.com/assets/15728518/11598333/2bf58c78-9a76-11e5-8b43-d1ba919f7979.png)

**Comment by wchen-r7** [comment]
Hello @ali1997, this seems to be a packaging problem for Armitage. We can't really help you because we didn't develop this Armitage. Please find support there. Thanks!

**Comment by ali1997** [comment]
thanks my bro im fix this proplem  yesterday ! but i forget  delete it   but i want tell me how i can find rdp and vnc sources code ?? and thank you !

**Comment by wchen-r7** [comment]
@ali1997 VNC is open source, you can easily find this. You can find RDP clients [open source](http://www.rdesktop.org/) too, but not the Microsoft implementation.

Also, for future technical community support or questions, please use the [Rapid7 Community website](https://community.rapid7.com/community/metasploit/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D). If you actually have a bug to report, or would like to submit a feature request, Github would be the appropriate place. Thank you!

**Comment by ali1997** [comment]
thanks my bro you are very helpful
