### ISSUE TITLE
warning: string literal in condition

### ISSUE THREAD

**Issue by iKurniawan** [rapid7/metasploit-framework#6311]
MSF console always throws this warning when its start :
/opt/metasploit/apps/pro/ui/app/controllers/sessions_controller.rb:311: warning: string literal in condition

My quick & dirty fix :
```
--- sessions_controller.rb-orig	2015-12-05 02:11:07.406214309 +0700
+++ sessions_controller.rb	2015-12-05 02:02:30.139253853 +0700
@@ -275,7 +275,7 @@
           end
         end
 
-        if @session.stype == 'shell' || 'powershell'
+        if @session.stype == 'shell' || @session.stype == 'powershell'
 
           max = 64 * 1024
           cnt = 0
```

**Comment by jhart-r7** [comment]
Hello and thanks for the report @iKurniawan.  This is actually a Metasploit Pro issue that i can confirm.  I don't believe it has been reported yet so I've gone ahead and one that for you and closed this.
