### ISSUE TITLE
Support migrating by process name

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#6313]
Perhaps there is an existing, better way of doing this, but I don't know any.  It is annoying to have to locate an appropriate process to migrate to (say, a 64-bit one) and then get its PID to pass to `migrate`, when most of the time you probably know exactly which process name you want to migrate to given that there is presumably a common process name (like vmtoolsd.exe) that suits your needs.  I don't see why `migrate` couldn't take a non-integer value (perhaps optionally) and search through `ps` for the right process.

**Comment by OJ** [comment]
What about:

meterpreter> run migrate -n bloop.exe

?

**Comment by jhart-r7** [comment]
Yeah, that seems like it should work, so I guess this task is more about evening out this bit of functionality between the two different ways of migrating.
