### ISSUE TITLE
Problem with Metasploit Developer Environment Setup

### ISSUE THREAD

**Issue by cybergoof** [rapid7/metasploit-framework#6314]
On this page: https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#install-the-base-dev-packages, I also needed to install libgmp3-dev or ffi 1.9.8 would not build. 

I am installing on a very clean Xubuntu image.

**Comment by wvu-r7** [comment]
That dep list is kinda cargo-culted. I can update it if you'd like.
