### ISSUE TITLE
vncinject - setup the reverse listener

### ISSUE THREAD

**Issue by kokoown2** [rapid7/metasploit-framework#6321]
i'm trying to make a stand alone vncinject module.
i have setup a socket that connect to the server and pass it in the socket in init function.
but how should i start the reverse listener? i tried "vncviewer -listen", it does connect via the socket but it doesnt send the vnc packets.. i saw that metasploit use tightvnc to setup the listener
how should i do that? i tried use the tightnvc myself and it didnt work

**Comment by OJ** [comment]
Sorry, but github isn't a support forum. Please use community.rapid7.com
