### ISSUE TITLE
hello ! i want  install nexpse for windows 32 ? but not availible !! can install it in other way ?

### ISSUE THREAD

**Issue by ali1997** [rapid7/metasploit-framework#6324]
If you'd like to propose a feature, describe what you'd like to see. Mock ups of console views would be great.

If you're reporting a bug, please be sure to include the expected behavior, the observed behavior, and steps to reproduce the problem. Resource scripts, console copy-pastes, and any background on the environment would be appreciated.

For tips, see http://r-7.co/MSF-CONTRIB

**Comment by wvu-r7** [comment]
32-bit is not supported. Please consult http://www.rapid7.com/products/nexpose/system-requirements.jsp and see https://community.rapid7.com/community/nexpose/blog/2013/05/08/announcement-end-of-life-for-nexpose-32-bit-versions for the EOL announcement.

**Comment by ali1997** [comment]
ok  bro !  where the old verisons of nexpose ? if the old verison suppurt 32 bit please send it to me :)

**Comment by wvu-r7** [comment]
Don't think they are available anymore!

**Comment by ali1997** [comment]
ok bro !! thank you :(

**Comment by wvu-r7** [comment]
Sorry! :(

**Comment by ali1997** [comment]
no proplem :(  but i have q i can install windows 64 in vmware or virtual box O.o and my native system it is 32 ?

**Comment by wvu-r7** [comment]
No.

**Comment by ali1997** [comment]
ok thank you :)
