### ISSUE TITLE
Improving Linux payload support?

### ISSUE THREAD

**Issue by elitest** [rapid7/metasploit-framework#6334]
I was wondering if there was an appetite out there for improving linux based payloads?

I was thinking about how a reverse_https would even work on linux, given that resources analogous to wininet are not present on every linux system, curl maybe?.  I've taken a look at how payload/windows/reverse_http and payload/windows/reverse_https to learn how they work.

Maybe a reverse_ssh payload?  How would the authentication work? I imagine reusing the same ssh key pairs would probably be a bad idea if nothing more than for detection reasons.  Maybe just have payloads send arbitrary usernames and passwords and then not care what they are?

I'm no linux x86 assembly expert, but it might be an interesting learning experience.

**Comment by wvu-r7** [comment]
I'm very much with you on improving *n?x payload support. :)

**Comment by bcook-r7** [comment]
Sure! Note you don't even have to know x86 assembly; look at the payloads under modules/payloads/singles/cmd/unix

**Comment by bcook-r7** [comment]
we do need to put the linux meterpreter into the preference list

**Comment by busterb** [comment]
Mettle has a reverse_http / reverse_https ability, just need to PR the payload bits into metasploit. I'm going to close this because that's on my todo list this week.
