### ISSUE TITLE
[Feature Request] Python module run in background

### ISSUE THREAD

**Issue by psychomario** [rapid7/metasploit-framework#6369]
Unless I'm missing something, it doesn't seem to be possible to run a python script in the background, either via `python_import -f`, `EXTINIT=python,`, or any python based method (`multiprocessing`).

It would be very nice to have this support as it would then be possible to implement proxies etc which meterpreter traffic could be tunneled through.

I'm not sure if meterpreter's internals allow for separate threads but this would definitely be useful.

**Comment by psychomario** [comment]
Turns out I was wrong, the presence of `multiprocessing` doesn't help. Daemon processes exit when he parent does, so it won't run while we're inside the meterpreter business post extinit

**Comment by OJ** [comment]
So if you run something on a background thread in Python, you're saying it doesn't run while Meterpreter is doing its thing?

**Comment by OJ** [comment]
Would you mind providing an example I can work off?

**Comment by psychomario** [comment]
Apologies, my code is on my work laptop which I can't get to until Monday. The general idea would be to do:
```
def runsforever():
   ...

main = multiprocessing.Process(target=runsforever)
main.daemon = True
main.start()
```
Based on the [docs](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.daemon), `main` will be killed when the script finishes, which is right when `python_import` times out.

**Comment by OJ** [comment]
OK mate, that gives me something to go on. I'm packing up my house right as I'm moving this weekend, so I'll check in again on the other side. Cheers.
