### ISSUE TITLE
msfpayload ins't working 

### ISSUE THREAD

**Issue by ChaitanyaHaritash** [rapid7/metasploit-framework#6407]
OS : BackBox 4.4 32bit 
Metasploit version : 
                                    Framework: 4.11.4-dev-fc09eaf5
                                    Console  : 4.11.4-dev-fc09eaf5.15168

Error : 

msf > msfpayload
[*] exec: msfpayload

/var/lib/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:345:in `block in replace_bin_path': can't find executable msfpayload (Gem::Exception)
	from /var/lib/gems/2.1.0/bin/msfpayload:23:in `<main>'
msf >

**Comment by void-in** [comment]
msfpayload is no longer shipped with Metasploit. Use msfvenom instead. Further details can be found at https://community.rapid7.com/community/metasploit/blog/2014/12/09/good-bye-msfpayload-and-msfencode

Use Kali as BT is no longer the supported OS from offensive security folks as well. I am closing this issue now. If you have further support queries, please use https://community.rapid7.com

**Comment by ChaitanyaHaritash** [comment]
and and msfvenom got same commands as msfpayload got earlier ? :)

**Comment by void-in** [comment]
Not exactly the same. The blog post linked above has the details. You can also run msfvenom -h to get the help.
