### ISSUE TITLE
php meterpreter downloads are truncated to 64k

### ISSUE THREAD

**Issue by sho-luv** [rapid7/metasploit-framework#6414]
When using "php/meterpreter/reverse_tcp" the download meterpreter command seems to be truncating all downloads to 64k for some reason.

**Comment by wchen-r7** [comment]
Confirmed bug. Seems to be just for PHP.

**Comment by FireFart** [comment]
Is the response code `HTTP 100/Continue`?

**Comment by wchen-r7** [comment]
@FireFart You got me. I actually don't know what you are talking about. At what point does meterpreter get an HTTP response?

**Comment by FireFart** [comment]
aaaaaaaaaa it's `reverse_tcp` my fault. Thought it was `_http` :D

**Comment by wchen-r7** [comment]
I've been looking into this bug and I will try to fix it.

**Comment by wchen-r7** [comment]
OK, patch coming up in a bit.

**Comment by wchen-r7** [comment]
Hmmm I have code that can overcome this specific issue, but it has another regression bug.

I can tell you that I was trying to fix here:
https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb#L320

When you're using a php meterpreter, for some reason you cannot call #read twice. The second time you will hit an EOFError (raised by https://github.com/rapid7/metasploit-framework/blob/master/lib/rex/post/meterpreter/channels/pool.rb#L84). With Windows meterpreter though, this works fine.

So I tried:

```ruby
src_file = '/tmp/junk.txt'
stat = client.fs.filestat.new(src_file)
f = client.fs.file.new(src_file, 'rb')
buf = ''
unless f.eof?
  begin
    buf = f.read(stat.size)
  rescue EOFError
  end
end
f.close
```

You can run this in irb. This code addresses this particular problem, but it tends to timeout and have other problems. My guess is this isn't where the bug should be patched, might be somewhere else.

**Comment by bcook-r7** [comment]
Thanks for the analysis @wchen-r7 . I took and look and found a missing return-by-ref in PHP meterpreter. The above PR should fix it.
