### ISSUE TITLE
Android payload doesn't work if target is on mobile network.

### ISSUE THREAD

**Issue by SonerAbay** [rapid7/metasploit-framework#6419]
I'm trying android payload over WAN but If victim's connected to 3G / 4G / Mobil Network, payload doesn't work. It gives a session but you can't do anything with it and dies quickly. However, if the victim is connected to WiFi, Hotspot etc. Payload works fine.

I've opened port and forwarded my local IP for Metasploit. But it only works on non-mobile internet. It doesn't work data network of the phone. Yes, I'm sure nothing wrong with port and my dns forwarding. I've tried it on plenty of devices. It works only if the target's device connected to a wifi internet. If the phone on mobile data network, it also gives session but I can't do anything with it(help command doesn't list proper android payload commands) and it dies quickly.

Which payloads I've tried so far:
1) android/meterpreter/reverse_https
2) android/meterpreter/reverse_https
3)android/meterpreter/reverse_tcp

/ haven't tried http but they are no different I guess /

Here are some snaps:

1) Payload, if victims on mobile network / 3G (help command output):

http://img.wonderhowto.com/img/74/54/63587242037782/0/metasploit-doesnt-work-mobile-data-network.w654.jpg

2)The same payload if victims on WiFi etc. (help command output):

http://img.wonderhowto.com/img/66/66/63587242212334/0/metasploit-doesnt-work-mobile-data-network.w654.jpg
As you can see the same payload acts differents depend on network type. About 6 months ago I was using same payload on mobile network and there was no problem. I don't know what has changed but doesn't work if victims on mobile internet. I asked a few people to try it and they also couldn't get successfull meterpreter session. 

Operating system: Parrot OS 2.0.5 (32-bit).
Target-1: Android 4.4.1 Galaxy Note 2
p.s. I don't know the android versions of the other devices I've tried so far.

**Comment by timwr** [comment]
@casperass I can't reproduce this. I can get a workable (but slow) android/meterpreter/reverse_tcp session over 3G and 4G. I tested with https://github.com/rapid7/metasploit-framework/commit/88ef307 and an older version. Do you get anything in the device log (```adb logcat```)?

**Comment by timwr** [comment]
This might make a difference to reverse_tcp: https://github.com/rapid7/metasploit-payloads/commit/d62085658934eb90bdc2d420a84dde0ac522648e

**Comment by OJ** [comment]
That's a pretty key change right there. The socket requires the ability to timeout during read, and so that should really be put back in.

@timwr what PR was that part of?

**Comment by timwr** [comment]
@OJ https://github.com/rapid7/metasploit-payloads/pull/67

**Comment by OJ** [comment]
Thanks dude.

**Comment by busterb** [comment]
I'm not sure if we can totally finger this problem on the removal of the socket timeout. The above change was only merged 7 days ago, but this ticket is over a month old.

**Comment by charankrishna** [comment]
Hey do you find any solution when victim is on mobile data? I am not getting response when i am trying to connect when when it is on data.

**Comment by Lartsch** [comment]
A little late to the party, but this is also important for the reverse_tcp payload to work with android device on mobile data:
If the phone is in **data saver mode**, it will restrict the installed app and the connection wont succeed or fail shortly after succeeding. So, to guarantee your app will work in any circumstances, enable unlimited mobile data usage for it through the settings, even if data is restricted.
