### ISSUE TITLE
metasploit-framework/modules/post/windows/manage/enable_rdp.rb

### ISSUE THREAD

**Issue by vysec** [rapid7/metasploit-framework#6423]
Is it meant to be "FORDWARD"? as opposed to "FORWARD"?

**Comment by void-in** [comment]
It's a typo. Thanks for noticing. Since it is an easy change, would you like to generate a PR?

**Comment by vysec** [comment]
Hi there,

https://github.com/rapid7/metasploit-framework/pull/6426

Thanks :)

V
