### ISSUE TITLE
Unable to get more than 120 screenshots

### ISSUE THREAD

**Issue by bcallar** [rapid7/metasploit-framework#6436]
I have an issue with meterpreter (windows/x86).
After 120 screenshots (with the command screenshot) exactly i get a timeout error.

Also, if i want more screenshot, i need to exit meterpreter and launch it again.

Is There a limitation into meterpreter to allow only 120 screenshots ?

Best regards,

**Comment by bcook-r7** [comment]
Heh, possible memory or other leak is my first guess.

**Comment by OJ** [comment]
Let's not forget that each time a screenshot is taken, a DLL is reflectively injected!

**Comment by ccondon-r7** [comment]
Closing this because it's been so long since it was active, but feel free to reopen if you reconfirm!
