### ISSUE TITLE
Module is recognized but does not load

### ISSUE THREAD

**Issue by guitarmanj** [rapid7/metasploit-framework#6438]
I've been using a set of custom modules for a few years now and starting today, I can find the module through search but cannot use the module. I keep receiving the error: [-] Failed to load module: auxiliary/scanner/http/module_name

**Comment by all3g** [comment]
Could you paste the whole error message ?

**Comment by guitarmanj** [comment]
This is what i get from the console:


msf > search page_collector

Matching Modules
================

   Name                                   Disclosure Date  Rank    Description
   ----                                   ---------------  ----    -----------
   auxiliary/scanner/http/page_collector                   normal  HTTP Page Collector


msf > use auxiliary/scanner/http/page_collector
[-] Failed to load module: auxiliary/scanner/http/page_collector
msf >





________________________________

**Comment by wvu-r7** [comment]
Are you sure you have it? I don't have it.

**Comment by void-in** [comment]
@wvu-r7 He mentioned this is a custom module he has been using. That's why we don't have it. I doubt we are going to debug this issue without the module code.

**Comment by wvu-r7** [comment]
Works for me with https://web.archive.org/web/20150325232529/http://www.securestate.com/Documents/page_collector.rb.

**Comment by guitarmanj** [comment]
very interesting. I haven't changed my configuration at all other than an update yesterday and it worked just fine up until then.


________________________________

**Comment by wvu-r7** [comment]
Is that the right module?

**Comment by guitarmanj** [comment]
yessir


________________________________

**Comment by wvu-r7** [comment]
@guitarmanj: Anything in ```~/.msf4/logs/framework.log```?

**Comment by guitarmanj** [comment]
here you go!

Thanks for you help


root@ShadowmanKali2:~/projects/bigy# cat ~/.msf4/logs/framework.log | grep "page_collector"
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
[10/14/2015 11:58:20] [e(0)] core: Auxiliary failed: Errno::ENOENT No such file or directory @ rb_sysopen - .0./page_collector
[10/14/2015 11:58:31] [e(0)] core: Auxiliary failed: Errno::ENOENT No such file or directory @ rb_sysopen - .0./page_collector
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:160:in `write_threadsafe'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:91:in `block in run_host'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `each'
/root/.msf4/modules/auxiliary/scanner/http/page_collector.rb:81:in `run_host'
[10/22/2015 17:29:47] [e(0)] core: Auxiliary failed: Errno::ENOENT No such file or directory @ rb_sysopen - .0./page_collector
[10/22/2015 17:29:53] [e(0)] core: Auxiliary failed: Errno::ENOENT No such file or directory @ rb_sysopen - .0./page_collector




________________________________

**Comment by wvu-r7** [comment]
@guitarmanj: Can you post the full stack trace instead of just the ```grep```?

**Comment by bcook-r7** [comment]
where do you have page_collector.rb in your filesystem? What OS / distribution are you using?

**Comment by guitarmanj** [comment]
Hey Brent,

I'm running Kali 2 and the .rb file is kept '/root/.msf4/modules/auxiliary/scanner/http/'


________________________________

**Comment by void-in** [comment]
@guitarmanj Just tried the same procedure on Kali 2.0 and everything works fine.
```ruby
root@kali:/opt/void-in/metasploit-framework# ./msfconsole -q
msf > use auxiliary/scanner/http/page_collector
msf auxiliary(page_collector) > show options

Module options (auxiliary/scanner/http/page_collector):

   Name     Current Setting                  Required  Description
   ----     ---------------                  --------  -----------
   LPATH    /root/.msf4/logs/http_scan.html  yes       The local filename to store the html file
   PORTS    80,443,8080,8443                 yes       Ports to scan (e.g. 22-25,80,110-900)
   Proxies                                   no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS                                    yes       The target address range or CIDR identifier
   THREADS  1                                yes       The number of concurrent threads
   VHOST                                     no        HTTP server virtual host

msf auxiliary(page_collector) >

```
I have this feeling that this issue is something related to your environment and not a generic bug. It would be much better to ask this at https://community.rapid7.com rather than here.

**Comment by guitarmanj** [comment]
roger that. Thanks for the help guys!


________________________________

**Comment by wvu-r7** [comment]
@guitarmanj: Check out the nightly installers if you'd like a prepackaged environment: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers. Should work cleanly. Thanks!

**Comment by guitarmanj** [comment]
Thank you for the help, much appreciated



Sent from my T-Mobile 4G LTE Device


-------- Original message --------
