### ISSUE TITLE
Need responsible parties for enforcement identified in code of conduct

### ISSUE THREAD

**Issue by scriptjunkie** [rapid7/metasploit-framework#6439]
At the end it says, "All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances." We probably need to say who will be taking those responses, I assume maintainers for the lesser offenses. But maybe for actions against a maintainer or outright bans final discretion belongs to the community manager.

**Comment by todb-r7** [comment]
In the Committer-Rights wiki, the [Metasploit triumvirtate](https://github.com/rapid7/metasploit-framework/wiki/Committer-Rights#how-to-gain-commit-rights) is mentioned. I'd assume it'd be them.

**Comment by jlee-r7** [comment]
Addressed in #6469
