### ISSUE TITLE
Msf* Commands Don't Work On Metasploit Framework

### ISSUE THREAD

**Issue by zmajevi** [rapid7/metasploit-framework#6442]
http://www.darkoperator.com/installing-metasploit-in-ubunt/

I did every step right like it says in the link above when i type in msfconsole at terminal it starts fine but when i type in an msf* command when i'm in msfconsole it just doesn't work i don't get any errors it simply doesn't respond. Any ideas about what might be wrong ?

**Comment by zmajevi** [comment]
bundle install

bundle binstubs metasploit-framework --path=$(dirname $(which msfconsole)) --force

https://github.com/rapid7/metasploit-framework/issues/4602

I tried typing these commands i found in the link above now when i type in msfconsole at terminal i get this error:

 /home/user/.rbenv/versions/2.1.7/lib/ruby/2.1.0/forwardable.rb:186: stack level too deep (SystemStackError)

**Comment by vysec** [comment]
Don't type it in the framework console? Maybe I am understanding you wrong,  but this works as intended for me.

**Comment by zmajevi** [comment]
I didn't type them in framework console

**Comment by jlee-r7** [comment]
Use the official installers instead. https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
