### ISSUE TITLE
can't open msfconsole after updating metasploit on kali 2.0

### ISSUE THREAD

**Issue by mostafataliza** [rapid7/metasploit-framework#6460]
After an update of matasploit framework by apt-get upgraed I got it crashed and will not open any more here is screenshots:
http://s10.postimg.org/dv8e6w0a1/Screenshot_from_2016_01_10_10_51_29.png

http://s1.postimg.org/ng91f2ti7/Screenshot_from_2016_01_10_10_50_32.png

**Comment by busterb** [comment]
Hmm, I could not reproduce, but this sort of issue is usually due to a missing require and the somewhat nondeterministic order in which we load things. Will PR a fix for a few of these later.

**Comment by busterb** [comment]
Hmm, looking at your kali package, it appears you upgraded from Kali 1.0 - the package you're listing there is not actually installed, nor is it even supplied with Kali 2.0 any more, note the 'rc' flag at the front. 

The Kali 2.0 Metasploit package is now called 'metasploit-framework'

**Comment by mostafataliza** [comment]
O.K I got it fixed by installing it again
