### ISSUE TITLE
Rspec takes way too long in an external environment

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#6476]
`rspec --exclude-pattern "**/login_scanner/*_spec.rb"` takes about 3m30s on my crummy little single proc Ubuntu VM (one processor, 8 gb memory, Ubuntu 14.04 on a temporary MacBook Air).

`rspec spec/lib/metasploit/framework/login_scanner/glassfish_spec.rb` by itself takes about 35 seconds to fail out, and is blocking on network calls. Is there a way to lump these LoginScanner tests into one group and just skip them entirely by default, but have Travis do something useful with them? 

Running all the tests with a plain `rspec` takes over a half hour, and even then I get bored of it and Ctrl-C out.

AFAIK, @lsanchez-r7 is the current Rspec Brute Squad.

**Comment by todb-r7** [comment]
BTW, the tests are hanging up almost entirely on trying `nosuchplace.metasploit.com` and some malformed IP addresses that are getting handled as DNS names (like `192.168.1.1.5.localdomain.`). It'd be great to have one test for that that, rather than repeating them all over the place for every LoginScanner.

cc @dmaloney-r7

**Comment by bcook-r7** [comment]
co.co might be a good replacement that fails faster?
