### ISSUE TITLE
Update "dev setup how to" to account for ruby 2.1.7 install error

### ISSUE THREAD

**Issue by jhale85446** [rapid7/metasploit-framework#6492]
# Background

While setting up the dev environment for Kali Rolling that just came out today, I received an error installing Ruby 2.1.7.  After some research (links [here](https://github.com/rvm/rvm/issues/3529) and [here](https://github.com/rvm/rvm/issues/3548). I found out that openssl libs have been updated to drop support of sslv3 while Ruby is still using it.  The error I received is exactly the same as in the links.

# Update Suggestion

## Install RVM
(From [RVM's site](https://rvm.io/))
```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
\curl -sSL https://get.rvm.io | bash -s stable --autolibs=enabled
```

## Configure Gnome Terminal to use RVM
"Same as is already present"

## Install Ruby 2.1.7 with patch
```
wget https://github.com/ruby/ruby/commit/801e1fe46d83c856844ba18ae4751478c59af0d1.diff -O openssl.patch
rvm install --patch ./openssl.patch 2.1.7
```

`gem install bundler`

And go on from there.

I was able to get msfconsole running from my cloned fork at that point.  Hope this helps someone else avoid the struggle.

**Comment by jhale85446** [comment]
Looks like "rake spec" doesn't like the patch as any ssl related item is failing...

**Comment by bcook-r7** [comment]
Thanks! As a note, ruby 2.3.0 doesn't seem to have problems with this.

We probably also need to redo the SSL scanner, as it gets less useful all the time when it depends on what the system OpenSSL happens to have enabled.

**Comment by jhale85446** [comment]
Thanks, I try using ruby 2.3.0 instead.

**Comment by mathieujobin** [comment]
2.1.8 and 2.2.4 does not have this problem
you will need the same patch for older release 2.0.0, 2.1.7 and 2.2.3

**Comment by bcook-r7** [comment]
We have since moved to Ruby 2.3.1, which can gracefully handle SSLv3 being missing. Thanks for the report.
