### ISSUE TITLE
Travis not working for PRs?

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#6495]
can someone please check this? It seems travis is not kicking in on new PRs (just check the last ones). Maybe there is a permission problem and someone needs to reenable the travis hook.

**Comment by bcook-r7** [comment]
Hmm, I wonder if it is still working on master.

**Comment by bcook-r7** [comment]
Hmm, the toggle switch was turned off. I turned it back on again.

**Comment by FireFart** [comment]
awesome thx!
