### ISSUE TITLE
Add a 'localtime' command (or something similar)

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#6504]
Hi all,

Another idea for discussion. While on a job I'm often interested in the local time of the machine that I have a session on. Right now I just drop into a shell and use `time /t`, and this gives me the local time. This is fine and useful, but I think we can do better.

I think a `localtime` command should be added that not only shows the time but the timezone as well.

Thoughts?

**Comment by all3g** [comment]
+1, **os language** can be also added to ```localtime```.

**Comment by jlee-r7** [comment]
This seems like a useful thing to have. Would it make sense to add it to `sysinfo`?

**Comment by OJ** [comment]
So the problem with adding this command to `sysinfo` is that the result of calling `sysinfo` is cached locally (ie. we don't invoke it in Meterp again after the first call). So the date/time will remain as is for the duration of the session. This is actually a problem right now for the `Logged On Users` parameter, as that could change, though it's not really serious.

Two options:

1. Change it so that `sysinfo` is invoked on Meterp each time it's called
1. Add a `localtime` command.

I think I'd prefer the latter.

**Comment by OJ** [comment]
How about something like this:
```
meterpreter > sysinfo 
Computer        : WIN-7CH5RT177BA
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/win64
meterpreter > localtime 
Local Date/Time: 2016-08-01 22:18:08.333 E. Australia Daylight Time (UTC+10)
```

**Comment by OJ** [comment]
Turns out that doing this nicely cross-platform is a total clusterf**k when it comes to timezones.

Initial work has begun here though:

* https://github.com/OJ/metasploit-framework/tree/add-localtime-cmd
* https://github.com/OJ/metasploit-payloads/tree/add-localtime-cmd

**Comment by bcook-r7** [comment]
I agree, localtime should be independent.

Rather than sending a formatted timezone, can we just send 64-bit UTC epoch time? That is, do we actually care about the remote timezone at all? I'd rather just show the time in msfconsole in local time rather than remote.

**Comment by bcook-r7** [comment]
Of note, I only _just_ added the sysinfo caching support. Was that the wrong thing to do? I forgot that logged-on-users was in there, or I might switch that to be a separate call too.

The driver for caching sysinfo is we use stuff like 'os' and 'arch' all over the place, and it is unlikely to change within a session.

**Comment by OJ** [comment]
64-bit UTC epoch time, doesn't that defeat the purpose? I can calculate that locally without talking to Meterpreter, and doesn't give me any information that I don't already have? Am I missing something?

I think caching sysinfo does make sense, given that it's everywhere. Perhaps the logged on users value isn't a `sysinfo` value at all?

Perhaps we could add a `force` parameter to the call, and set that to `true` when the user invokes it from the console?

**Comment by bcook-r7** [comment]
I guess I totally misunderstood the purpose - it's to show the target timezone? OK, makes sense then.

**Comment by busterb** [comment]
Fixed here, thanks @OJ: https://github.com/rapid7/metasploit-framework/pull/7423
