### ISSUE TITLE
Generate/test SSH public keys from publicly available github public keys

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#6534]
Github publishes the SSH public keys configured for a particular user's SSH access to github at the following location: `https://github.com/<github_username>.keys`.  It would be neat to have a way to obtain keys in bulk and use them as part of `ssh_identify_pubkey`'s run.

**Comment by wvu-r7** [comment]
Speaking of using the module lately, that's exactly what I was doing. :D
