### ISSUE TITLE
NoMethodError undefined method `strip' for nil:NilClass in enum_chrome

### ISSUE THREAD

**Issue by mchao-r7** [rapid7/metasploit-framework#6569]
Setup:
* Windows XP SP3 with Chrome

```
[-] Post failed: NoMethodError undefined method `strip' for nil:NilClass
[-] Call stack:
[-]   /Users/[user]/rapid7/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:314:in `run'
```

**Comment by FireFart** [comment]
It looks like the `USERNAME` environment variable is not set:
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/enum_chrome.rb#L314 (assigned here https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/enum_chrome.rb#L288)

**Comment by wchen-r7** [comment]
@mchao-r7 and I ran into this bug during an internal training, I guess I'll fix it.
