### ISSUE TITLE
Kill process by name in Meterpreter

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#6582]
Functionally like `pkill` or `killall` (not of the Solaris sort :).

**Comment by bcook-r7** [comment]
Well, maybe a DoS module for Solaris killall :P

**Comment by sempervictus** [comment]
I did this in a post module via PSH for a quick'n'dirty implementation a while back, and we did discuss moving this to meterp itself.
I think for ease of implementation, we should still handle logic on the framework side via:
cmd_ps -> filter -> get list of pids -> exclude current session's PID -> issue kills -> cmd_ps again -> validate all required PIDs are gone.
That should work across implementations without modification to the payloads repo, and be reasonably forward-portable.

**Comment by busterb** [comment]
Added in https://github.com/rapid7/metasploit-framework/pull/8117
