### ISSUE TITLE
Create templates for new issues and PRs

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#6586]
From the [Dear Github issue](https://github.com/isaacs/github/issues/99#issuecomment-185339511):

Just add a file called `issue_template.md` or `pull_request_template.md` and populate as desired.

**Comment by todb-r7** [comment]
It'd also be nice to have pointers in the sub-projects that point here for issues, assuming that's what you want.

**Comment by FireFart** [comment]
@todb-r7 https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by FireFart** [comment]
I also like the `.github` folder to keep the root clean. So maybe also move the other files?

**Comment by bcook-r7** [comment]
Done
