### ISSUE TITLE
Python Meterpreter subsequent download file size issue

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#6593]
Python Meterpreter on victim OSX
```
Listing: /private/tmp/repo
==========================

Mode              Size      Type  Last modified              Name
----              ----      ----  -------------              ----
100644/rw-r--r--  64996323  fil   2016-02-18 21:12:29 -0500  bob.dmg

meterpreter > download bob.dmg
[*] downloading: bob.dmg -> bob.dmg
[*] download   : bob.dmg -> bob.dmg

```
Results in a full download of all 64MB, performed again on the same file after removing the file from disk:
```
meterpreter > download bob.dmg
[*] downloading: bob.dmg -> bob.dmg
[*] download   : bob.dmg -> bob.dmg
meterpreter >
```
I get:
```
-rw-r--r-- 1 root root 4.7M Feb 18 21:12 bob.dmg
```
I have tested this with reverse_tcp and reverse_https, also with different files and folder options, second file and going forward.

**Comment by zeroSteiner** [comment]
@mubix I was also able to reproduce this issue on Linux with python/meterpreter/reverse_tcp, looking into a fix now.

**Comment by zeroSteiner** [comment]
So as I've said I've been able to reproduce this problem. While debugging it on the Python side it looks to me like Metasploit is calling the `core_channel_close` method prematurely causing the file and channel to be closed. I confirmed that if I actually modify the Python source to comment out the logic to close the file handle and delete the channel that it works as expected. I'm still in the process of tracking down why the framework side of things is trying to close the channel early.

**Comment by mubix** [comment]
@zeroSteiner cool, thanks, in the meantime, I've simply been kicking myself a new shell whenever I want to download anything ;-)

**Comment by mubix** [comment]
@zeroSteiner any luck on this front? got another such time to use it in the not so distant future

**Comment by zeroSteiner** [comment]
@mubix Yes with the help of brent I was able to track down the issue. What is happening is the `finalize` method in channel.rb is causing the channel to be closed twice. This coupled with the fact that the Python Meterpreter reissues closed channel IDs (which this Windows meterpreter does not) is causing the newly opened channel 0 to be prematurely closed as the previous channel (also 0 but also explicitly closed) is garbage collected.

As an interim fix, I'll look at submitting a PR to change the Python meterpreter to not reissue channel IDs even after they have been closed but ultimately there is a bug causing channels to be closed twice, once explicitly and a second time when garbage collected. When I create the PR I'll tag you so you can track it's progress.

**Comment by bcook-r7** [comment]
Updated payloads with the workaround - followup issue is #6634. Thanks all!
