### ISSUE TITLE
Openvas Metasploit Report problem 

### ISSUE THREAD

**Issue by agrebinoor** [rapid7/metasploit-framework#6595]
I'm having trouble generating the scan report when i use openvas with metasploit. Whenever i download it in PDF or HTML format, i only get an empty file. only the XML format works, while i need it to be PDF. Is there a way to fix it ? and properly generate a report in PDF format.

I tried using OpenVas as a stand-alone, i couldn't get the Report ID to download it with omp --get-report

**Comment by void-in** [comment]
Edit the call on line https://github.com/rapid7/metasploit-framework/blob/b868f7cc89bee907e3c3e007947b65aadde105a0/plugins/openvas.rb#L192  and pass on the true option for debug like:
```ruby
ov = OpenVASOMP::OpenVASOMP.new(user, pass, host, port,true)
```
Then run the plugin and paste all the debug output you receive. Unfortunately the plugin is very old and hasn't been touched in a while.

**Comment by void-in** [comment]
@agrebinoor Are you still having the problem? If yes, can you generate the debug output as suggested above?

**Comment by bcook-r7** [comment]
@brandonprry , could you take a look?

**Comment by brandonprry** [comment]
Sounds like the user hasn't configured OpenVAS properly to generate PDF reports. This is a sticky subject with OpenVAS.

```
I tried using OpenVas as a stand-alone, i couldn't get the Report ID to download it with omp --get-report
```

That sounds like OpenVAS is the problem, not Metasploit. Make sure you can generate PDF reports with OMP before trying to make Metasploit do it.

**Comment by dmaloney-r7** [comment]
Thanks for the feedback @brandonprry , closing this ticket as it does not appear to be a metasploit issue
