### ISSUE TITLE
msfupdate error

### ISSUE THREAD

**Issue by tthtlc** [rapid7/metasploit-framework#6631]
usr/local/rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
    from /usr/local/rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from ./msfupdate:188:in `update_git!'
    from ./msfupdate:137:in `block in run!'
    from ./msfupdate:135:in `chdir'
    from ./msfupdate:135:in `run!'
    from ./msfupdate:292:in `<main>'

And version:

CentOS Linux release 7.2.1511 (Core)
Derived from Red Hat Enterprise Linux 7.2 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
cpe:/o:centos:centos:7

**Comment by all3g** [comment]
```cannot load such file -- bundler (LoadError)```,   ```bundler``` needs to be installed.  please try:

```
$ rvm use ruby-2.1.7
$ gem install bundler
$ bundle install
$ ./msfupdate
```

**Comment by bcook-r7** [comment]
I'd argue there's no reason to even run 'msfupdate' if you just checked the code out with git.

Contemplating just deleting msfupdate from this repository. The version packaged with 'pro' builds is already different, the one with omnibus packages is also different. Kali users should just run 'apt-get dist-upgrade' anyway (and that's all that msfupdate does there anyway).

**Comment by wvu-r7** [comment]
Nice, ```msfupdate``` doesn't even check for ```bundler``` before using it.

**Comment by wvu-r7** [comment]
@bcook-r7: I'll support that decision. For now, I've provided the workaround referenced above.
