### ISSUE TITLE
Kali Sources in Wiki are incorrect

### ISSUE THREAD

**Issue by webhat** [rapid7/metasploit-framework#6641]
The apt sources for Kali in the wiki point to an outdated location. I've added a diff correcting this.

```
    # Kali apt sources:
    deb http://http.kali.org/kali kali main non-free contrib
    deb-src http://http.kali.org/kali kali main non-free contrib
    deb http://security.kali.org/kali-security kali/updates main contrib non-free
    deb-src http://security.kali.org/ kali/updates main contrib non-free
```

<pre>
diff --git a/dev/Setting-Up-a-Metasploit-Development-Environment.md b/dev/Setting-Up-a-Metasploit-Development-Environment.md
index bc401d5..d22f855 100644
--- a/dev/Setting-Up-a-Metasploit-Development-Environment.md
+++ b/dev/Setting-Up-a-Metasploit-Development-Environment.md
@@ -59,10 +59,10 @@ So let's get started!
 
 ----
 ```bash
-echo deb http://http.kali.org/kali kali main non-free contrib> /etc/apt/sources.list &&
-echo deb-src http://http.kali.org/kali kali main non-free contrib>> /etc/apt/sources.list &&
-echo deb http://security.kali.org/kali-security kali/updates main contrib non-free>> /etc/apt/sources.list &&
-echo deb-src http://security.kali.org/ kali/updates main contrib non-free>> /etc/apt/sources.list &&
+echo deb http://http.kali.org/ kali-current main non-free contrib > /etc/apt/sources.list &&
+echo deb-src http://http.kali.org/ kali-current main non-free contrib >> /etc/apt/sources.list &&
+echo deb http://security.kali.org/kali-security kali-current/updates main contrib non-free >> /etc/apt/sources.list &&
+echo deb-src http://security.kali.org/ kali-current/updates main contrib non-free >> /etc/apt/sources.list &&
 apt-get clean &&
 rm -rf /var/lib/apt/lists;
 apt-get update &&
@@ -75,10 +75,10 @@ apt-get -y upgrade
 First, you need to know where all the Linux goodness lives. Your `/etc/apt/sources.list` should have these sources listed:
 
 ```
-deb http://http.kali.org/kali kali main non-free contrib
-deb-src http://http.kali.org/kali kali main non-free contrib
-deb http://security.kali.org/kali-security kali/updates main contrib non-free
-deb-src http://security.kali.org/ kali/updates main contrib non-free
+deb http://http.kali.org/ kali-current main non-free contrib
+deb-src http://http.kali.org/ kali-current main non-free contrib
+deb http://security.kali.org/kali-security kali-current/updates main contrib non-free
+deb-src http://security.kali.org/ kali-current/updates main contrib non-free
 ```
 
 If you have a lot of extra sources, you are almost certain to cause conflicts. [Don't do that][kali-sources]. However, you may want to pick a more appropriate mirror from the [mirrorlist]. Once you're set with sources, clean out any cruft, get the latest Kali signing key, and go to town:

 ----
 ```bash
-echo deb http://http.kali.org/kali kali main non-free contrib > /etc/apt/sources.list &&
-echo deb-src http://http.kali.org/kali kali main non-free contrib >> /etc/apt/sources.list &&
-echo deb http://security.kali.org/kali-security kali/updates main contrib non-free >> /etc/apt/sources.list &&
+echo deb http://http.kali.org/ kali-current main non-free contrib > /etc/apt/sources.list &&
+echo deb-src http://http.kali.org/ kali-current main non-free contrib >> /etc/apt/sources.list &&
+echo deb http://security.kali.org/kali-security kali-current/updates main contrib non-free >> /etc/apt/sources.list &&
 apt-get clean &&
 rm -rf /var/lib/apt/lists;
 apt-get update &&

</pre>

**Comment by void-in** [comment]
@webhat Instead of a diff, a pull request would be much easier to review and land.

**Comment by FireFart** [comment]
@void-in you can't PR a wiki page on github :(

**Comment by FireFart** [comment]
This is the page:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#update-kali-linux

**Comment by wvu-r7** [comment]
That entire doc needs to be rewritten.. again.

**Comment by wvu-r7** [comment]
Fixed in https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment/4662a0ac38d48bd54d432a2617f5e85f7e6eb56c.

**Comment by webhat** [comment]
@void-in Sorry about not leaving a PR, github wouldn't let my fork the repo.

**Comment by void-in** [comment]
@webhat Yeah. I realized this after @FireFart's comment. Thanks for reporting it.

**Comment by wvu-r7** [comment]
It's all good.
