### ISSUE TITLE
bcrypt error while trying to install bundles

### ISSUE THREAD

**Issue by necony286** [rapid7/metasploit-framework#6660]
An error occurred while installing bcrypt (3.1.11), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.11'` succeeds before bundling.

**Comment by necony286** [comment]
gem install bcrypt -v '3.1.11'
Building native extensions.  This could take a while...
Successfully installed bcrypt-3.1.11
Parsing documentation for bcrypt-3.1.11
Done installing documentation for bcrypt after 0 seconds
1 gem installed
and when i try ./msfupdate again same output from above

**Comment by bcook-r7** [comment]
you are missing the ruby development packages for your OS. Without knowing what OS you are using, we cannot help further. That is what the missing '/usr/lib/ruby/include/ruby.h' error message is saying.

**Comment by necony286** [comment]
im rolling kali rolling 2016.1, and i run gem install bundler and run the ./msf update again it got fixed 
(but i had the bundler installed 100% i dont know what happend)

**Comment by bcook-r7** [comment]
no worries, glad it worked.

**Comment by Spl01ter** [comment]
On macOS, you need xcode in able to install bcrypt.
