### ISSUE TITLE
XOR key randomization broken

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#6678]
## Steps to reproduce

1. Start a clear-text meterpreter session such as pymet or wininet
2. Open up wireshark and look for the bytes "d4:ca:6d:7c:68:aa" in the TCP stream of your session.

## Expected behavior

Each packet in the stream should be uniquely encoded without exposing static byte ranges which can be signed for.

## Current behavior

Packets contain the byte array of "d4:ca:6d:7c:68:aa" which can be easily signed for.

### Metasploit version

HEAD @ 87074c0638886dc8bd85d3f612a7f6a734c9f735
(Payloads are from today as well)

### I installed Metasploit with:

- [ ] Source install MRI 2.1.8

### OS

Something which started as Ubuntu

### Notes

Discussed this with @OJ, tagging him here for assignment.

**Comment by OJ** [comment]
Thanks for the report @sempervictus. I'll put this near the top of the priority list. If the packets are looking the same then something is up both on the Meterp side and the MSF side.

**Comment by sempervictus** [comment]
This appears to be related to RVM and bundler hating me and each other. Closing until i can confirm on a clean host.

**Comment by OJ** [comment]
I admit I'm relieved to hear it :) Please keep me posted. Cheers!
