### ISSUE TITLE
LLMNR module ignores TTL option

### ISSUE THREAD

**Issue by Lexus89** [rapid7/metasploit-framework#6681]
It seems the LLMNR module ignores the TTL option and has it set static on 30

`OptInt.new('TTL', [ false, "Time To Live for the spoofed response", 300]),
`

This occurs at two places, one of them is below:

```
case question.qType.to_i
      when ::Net::DNS::A
        dns_pkt.answer << ::Net::DNS::RR::A.new(
          :name => name,
          :ttl => 30,
          :cls => ::Net::DNS::IN,
          :type => ::Net::DNS::A,
          :address => spoof.to_s
        )
```

**Comment by wvu-r7** [comment]
Can you submit a patch?

**Comment by wvu-r7** [comment]
FYI, this is ```auxiliary/spoof/llmnr/llmnr_response```.
