### ISSUE TITLE
HTTPNTLM Relay Response printing error

### ISSUE THREAD

**Issue by Lexus89** [rapid7/metasploit-framework#6682]
Framework Version: 4.11.13-dev-5d64346

When running this module with HTTP_GET it gives the following error printing the result on screen:

> [-] [2016.03.16-13:54:09] Exception handling request: no implicit conversion of Rex::Proto::Http::Response into String

```

I changed the print code to resp.to_s and now it works, is this a good fix or..?

# Type3 processing
    if type3
      # check if auth was successful
      if resp.code == 401
        print_error("Auth not successful, returned a 401")
      else
        print_status("Auth successful, saving server response in database")
      end
      vprint_status(resp.to_s)
    end
    return
```

**Comment by void-in** [comment]
The patch is correct however I would suggest you change the vprint_status line to print something more useful before printing the full response:
```ruby
vprint_status("Response code #{resp.code} received. Server sent #{resp.body}")
```

**Comment by wvu-r7** [comment]
If you have a patch, please submit it.

**Comment by Lexus89** [comment]
Unfortunately i am unable to do so right now, ill send a pull request when i can (since its only a very small modification i wouldn't mind someone else doing it quickly if there's a hurry).

**Comment by wvu-r7** [comment]
Okay, thanks!

**Comment by Lexus89** [comment]
@wvu-r7 Fixed a pull request, sorry for the delay. @void-in I will check the module again when i have some more time and improve the printing. Thanks for the headsup!

**Comment by wchen-r7** [comment]
#6706 has been closed, so I will close this issue too. Thanks.
