### ISSUE TITLE
Socket create calls do not consistently return IO objects

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#6693]
## Steps to reproduce

How'd you do it?

1. Create meterpreter session and pivot a route over it containing one of its L3 interface addresses
2. Create a UDP socket locally - Rex::Socket::Udp.create with a LocalHost of 127.0.0.1
3. Write connect another UDP socket to the local one and write data such that the first socket has something in its read bufffer.
4. Call IO.select with the pending socket as the first argument, see it return the waiter array.
5. Repeat the UDP socket pair creation steps on the remotely pivoted L3 address of the compromised host (see RC script in #6692).
6. Repeat the IO.select op on the pivot sockets. Enjoy the stack trace.

## Expected behavior

All objects returned from create calls into the socket namespace should be sockets, not channels.

## Current behavior

Only TCPClientChannels return a selectable IO abstraction when LocalHost is a remote address.
Other calls can return objects with completely different behaviors and possible a file descriptor.

## Symptomatic expression

Stateless socket consumers in Rex and above cannot reliably serve responses to requests as the individual server classes for DHCP, TFTP, and DNS (#6611) implement IO.select on the UDP listener to determine if it has data available. 

-----

## Solution path

#6292 moves Stream abstraction functionality into simpler Socket abstractions which mix into Gram and Stream abstractions providing their own transport-specific objects and semantics in initialisers and send/recv behaviors. Similarly, Channels in the Post namespace have been restructured to create per-transport channel types allowing for the socket abstraction prior to implementing those channels as pivot overlays for the transport in question (UDP/TCP). Details of the work are logged in the PR itself.

**Comment by bcook-r7** [comment]
Thanks for fixing this! See #6692
