### ISSUE TITLE
Feature Request: inbound shell messages to console should reflect what job/port/etc the shell is phoning home to.

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#6715]
Currently, the messages that the console produces to tell the user that a shell came in only tell the user what port the shell phoned home to if the shell actually connects. 
If something tries to talk to the open port and it either isn't a shell (webscanner? bizzare errant tcp connection?), the messages don't give you much of a clue as to what port it's trying to talk on, or what listener it is - this is confusing if you are running more than one listner (in this instance I have 5.)
here's an example output: http://pastebin.com/Wr1ayKUK

it says what port the connection is coming FROM, but not where it's trying to land.

**Comment by Viss** [comment]
Oh - also: a timestamp would be SUPER USEFUL in these messages.
Currently the 'timestamp' seen in these messages is the date on the shell - the one here seems to indicate 7-27-2015.. so I guess a shell from nearly a year ago is trying to phone home?

**Comment by OJ** [comment]
If you set `TimestampOutput` to `true` then you'll see timestamps on events:
```
[*] [2016.03.25-12:00:14] Sending stage (957999 bytes) to XXX.XXX.XXX.XXX
```

**Comment by Viss** [comment]
oh, rad! thats helpful :D

**Comment by egypt** [comment]
Note that `TimestampOutput` is a global option, so if you're `use`ing a module, you have to `setg` instead of `set`.
