### ISSUE TITLE
Mac OS X 'hosts -S' error

### ISSUE THREAD

**Issue by CastleCorp** [rapid7/metasploit-framework#6734]
## Steps to reproduce

In msfconsole:
`hosts -S something`

It spits out this error: 
```
Currently, Active Record recognizes the table in the string, and knows to JOIN the comments table to the query, rather than loading comments in a separate query. However, doing this without writing a full-blown SQL parser is inherently flawed. Since we don't want to write an SQL parser, we are removing this functionality. From now on, you must explicitly tell Active Record when you are referencing a table from a string:

    Post.includes(:comments).where("comments.title = 'foo'").references(:comments)

```
## Expected behavior

Return hosts that match the search term.

## Current behavior

This error is repeated many times in the console:

Currently, Active Record recognizes the table in the string, and knows to JOIN the comments table to the query, rather than loading comments in a separate query. However, doing this without writing a full-blown SQL parser is inherently flawed. Since we don't want to write an SQL parser, we are removing this functionality. From now on, you must explicitly tell Active Record when you are referencing a table from a string:

    Post.includes(:comments).where("comments.title = 'foo'").references(:comments)

Followed by:

Hosts
=====

address  mac  name  os_name  os_flavor  os_sp  purpose  info  comments
-------  ---  ----  -------  ---------  -----  -------  ----  --------

### Metasploit version

Framework: 4.11.20-dev-5873803
Console  : 4.11.20-dev-5873803

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install (please specify ruby version)
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]

### OS

OS X Yosemite 10.10.5

**Comment by sempervictus** [comment]
I haven't had the time/inclination to bisect where in the commit-chain this started, but if its happening on earlier Ruby builds, it might have actually slipped by the CI + QA process. #6744 addresses this warning in the manner described in its text (as i understand it).

**Comment by bcook-r7** [comment]
Thanks. I can't repro with the bundled ruby in omnibus (2.1.8), so it is seems to be something that hasn't shown up until recently. It looks likely there are more places to fix as well.

**Comment by dmaloney-r7** [comment]
This issue was correctly addressed in https://github.com/rapid7/metasploit-framework/pull/6744
