### ISSUE TITLE
Feature Request PLZ!(TONE LOC 4 EVA)

### ISSUE THREAD

**Issue by andlogic** [rapid7/metasploit-framework#6746]
PLZ CONSIDER THIS LOGO its cool and shit
![tone_loc_4_eva](https://cloud.githubusercontent.com/assets/6843523/14236025/161b1286-f9dc-11e5-8a9e-1c8f38697019.png)

**Comment by andlogic** [comment]
SENSEI!!!!!!

**Comment by andlogic** [comment]
Do it for bruce!!!!!
![bruce](https://cloud.githubusercontent.com/assets/6843523/14236166/06d7ab24-f9df-11e5-9d3e-1904f36d1931.png)

**Comment by andlogic** [comment]
He died along time ago

**Comment by andlogic** [comment]
Its cool metasploit is like https://en.wikipedia.org/wiki/Phantom_Access

**Comment by bcook-r7** [comment]
consider it considered
