### ISSUE TITLE
Add Windows 10 to lib/msf/core/post/windows/priv.rb#is_uac_enabled?

### ISSUE THREAD

**Issue by litsnarf** [rapid7/metasploit-framework#6775]
## Steps to reproduce

1. meterpreter > run post/windows/gather/win_privs

## Expected behavior

On Windows 10 session it should return true (if enabled).

## Current behavior

Since the is_uac_enabled? check doesn't contain Windows 10, the script always returns "False"

Like 93 should contain "10" in the if:
```if winversion =~ /Windows (Vista|7|8|2008|2012|10)/```

### Metasploit version

Framework: 4.11.5-2016010401
Console  : 4.11.5-2016010401.15168

**Comment by OJ** [comment]
Thanks. It may well have been faster to PR it yourself :)

**Comment by zeroSteiner** [comment]
The fix for this issue has been landed. Thanks for reporting it @litsnarf and for the PR @OJ.
