### ISSUE TITLE
Powershell Import

### ISSUE THREAD

**Issue by vysec** [rapid7/metasploit-framework#6788]
![image](https://cloud.githubusercontent.com/assets/3596242/14655491/700e0e56-067a-11e6-97b7-d38040634ad4.png)

## Steps to reproduce

Open a reverse_https stager
Stage
> load powershell
> powershell_import /usr/share/PowerTools/PowerUp/PowerUp.ps1

## Expected behavior

I expected it to load the script.

## Current behavior

What happens instead?

![image](https://cloud.githubusercontent.com/assets/3596242/14655522/93a1f7d8-067a-11e6-9a86-9445332dfcfe.png)

Error displayed as the screenshot.

### Metasploit version

![image](https://cloud.githubusercontent.com/assets/3596242/14655536/a759920e-067a-11e6-9a2d-fbea7c0f7d99.png)

### I installed Metasploit with:
git clone https://github.com/rapid7/metasploit-framework

### OS

KALI 2.0

**Comment by vysec** [comment]
Nevermind I think there's just an issue with the script being complex or something. Tested with a simpler script and it worked fine.

**Comment by OJ** [comment]
This is still interesting though. Complex scripts should still work. I
tried out a bunch of tools such as powerview, but didn't try powerup. I'll
take a look anyway.

Can you please reopen this?

**Comment by OJ** [comment]
Reopening, because this should work unless there's a horrid chain of dependencies in the script you're running. I'll take a look.

**Comment by vysec** [comment]
No worries. I think I made a mistake and something was wrong with the script even after git fetch && git pull. I had to remove the whole directory and re git clone it. Worked fine afterwards.

Perhaps an issue with older powershell scripts?

**Comment by egypt** [comment]
@OJ are you still working on this?  If it was actually a problem with the imported script (and not with importing in general) can we close this?

**Comment by OJ** [comment]
Hey @egypt yeah I think it was a busted script too. So far things work fine for me. So I'll go ahead and close it for now.
