### ISSUE TITLE
AV getsystem Start Register Detection! 

### ISSUE THREAD

**Issue by kainpark7894** [rapid7/metasploit-framework#6798]
Matasploit Version 4.1.1.22

ESET NOD32 AntiVirus getsystem command runtime regedit service detect view

AV getsystem command bypass possible?

AV option ->hips start application Activation check image

![getsystem](https://cloud.githubusercontent.com/assets/18137745/14715465/d59822fc-0823-11e6-9e8b-f5b311ffdb98.png)

**Comment by mubix** [comment]
Just migrate into a SYSTEM process if possible, or use steal_token to steal the token of an admin process.

**Comment by kainpark7894** [comment]
migrate & steal token &getsystem
In order for elevation getsystem=steal tokon = migrate 
The same function?
thank you for mubix

**Comment by mubix** [comment]
If you are admin and trying to elevate your token to SYSTEM, you can do so by:

1. Using `steal_token 420` (420 being a SYSTEM process ID)
2. Migrate into that process instead

**Comment by OJ** [comment]
Sorry, this isn't a bug or issue with MSF. Closing. For general questions about stuff like this, the [community](https://community.rapid7.com) is a better option.
