### ISSUE TITLE
registry_enumkeys does not work for certain keys?

### ISSUE THREAD

**Issue by vysecurity** [rapid7/metasploit-framework#6800]
## Steps to reproduce

1) reg_vals = registry_enumkeys('HKLM\\SOFTWARE\\Microsoft\\EMET')
    reg_vals.each do |x|
        puts x
    end

No ouptut

2) reg_vals = registry_enumkeys('HKLM\\SOFTWARE\\Microsoft\\DirectShow')
    reg_vals.each do |x|
        puts x
    end

Has output

See below:

![image](https://cloud.githubusercontent.com/assets/18501679/14724493/6851b68c-080e-11e6-8c50-85969b7e7717.png)

## Expected behavior

I expect both to give output as they are both similar in the tree.

![image](https://cloud.githubusercontent.com/assets/18501679/14724477/5331ab36-080e-11e6-82b1-b93f69fddee0.png)

## Current behavior

EMET does not give output. Other paths do. I have access rights to read the registry from regedit.exe.

## Version of Metasploit

I'm using the one on git.

**Comment by vysec** [comment]
Thanks to @Meatballs1, I have confirmed that this is due to the registry being queried using 32 bit registry.

Is there any way to tell a 64 bit machine to use the 64 bit registry? It's running 32 bit meterpreter, but if its on a 64 bit system it should still be able to use a 64 bit registry query.

**Comment by vysec** [comment]
Current workaround -> migrate to 64 bit process.

**Comment by bcook-r7** [comment]
The second argument of registry_enumkeys specifies the view you want. By default it uses the process view (so 32-bit on 32-bit process, 64-bit on 64-bit processes)

Specify REGISTRY_VIEW_32_BIT or REGISTRY_VIEW_64_BIT to specify a specific view.
