### ISSUE TITLE
File upload broken with stdapi

### ISSUE THREAD

**Issue by bcook-r7** [rapid7/metasploit-framework#6815]
## Steps to reproduce

Open a meterpreter session and try to use the upload command to send a file

## Expected behavior

It doesn't throw an error.

## Current behavior

[16:28:28]  <AlienTrooper>	[-] Error running command upload: NoMethodError undefined method `exists?' for #<Class:0x007f84c0e92ab8>

### Metasploit version

4.11.22 and later

### I installed Metasploit with:
- [X] Source install (please specify ruby version)

**Comment by deanMKD** [comment]
i also can confirm this bug with latest Metasploit v4.11.22-dev:

> meterpreter > upload fb.apk
> [-] Error running command upload: NoMethodError undefined method `exists?' for #<Class:0x000000109d5db8>
> Did you mean?  exist?

Please fix this asap. This is most used feature.

**Comment by bcook-r7** [comment]
The Metasploit omnibus packages already have the fix, as does the latest git head. It is up to your particular distro (Kali, etc) to pull in the change now.
