### ISSUE TITLE
enum_chrome script reports "This version of Meterpreter is not supported with this Script"

### ISSUE THREAD

**Issue by strasharo** [rapid7/metasploit-framework#6817]
## Steps to reproduce

How'd you do it?

1.  Execute enum_chrome inside a meterpreter session:

## Expected behavior
Script should start enumerating chrome without errors

## Current behavior
Receiving the following error:

meterpreter > run enum_chrome
[-] This version of Meterpreter is not supported with this Script!
meterpreter >

### Metasploit version

msf > version
Framework: 4.11.23-dev-f28d280
Console  : 4.11.23-dev-f28d280
msf >

### I installed Metasploit with:
- [* ] Source install (please specify ruby version)
=* ruby-2.1.9 [ x86_64 ]
### OS

What OS are you running Metasploit on?
Fedora Server 22 x86_64

**Comment by bcook-r7** [comment]
```
if client.platform !~ /win32/
  print_error("This version of Meterpreter is not supported with this Script!")
```
are you running it on a win32 meterpreter? I think that's expected behavior if not.

**Comment by strasharo** [comment]
Yup, that's the case, I'm using windows/x64/meterpreter/reverse_tcp . 
Thanks for the tip, I guess the message can be changed to something more descriptive. :)

**Comment by wchen-r7** [comment]
@strasharo That's true, but we no longer maintain meterpreter scripts. Please try to use the post module version instead. Also if there's anything wrong in the post module one, please let us know. Thanks!

**Comment by strasharo** [comment]
Will do, thanks sinn3r.

**Comment by internauta-maromba** [comment]
you can specify the path, >> run post/windows/gather/enum_chrome
