### ISSUE TITLE
msfvenom not working with WhatsApp

### ISSUE THREAD

**Issue by arjunbahl** [rapid7/metasploit-framework#6847]
Everything's fine with Metasploit, but some how while signing APK(WhatsApp) with jarsigner , when i install APK while verifying number it doesn't happen. WhatsApp says "Please contact whatsapp blah blah".
Although when i install without msfvenom tampering it goes all well.

Any help?

**Comment by bcook-r7** [comment]
Can you show more of the steps you used, more specifically the exact wording of the error?

**Comment by bcook-r7** [comment]
I think for backdooring specific vendor APKs, you may need to do some individual research work. I don't think we'll be able to help other than in the case of a general problem with the tool.
