### ISSUE TITLE
PacketFu support for PCAP-NG (also, ownership change warning)

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#6863]
Given that our friend @claudijd has been much more active on PacketFu, and I've met him several times in real life, he's now a gem publisher for that library. As a result, you're likely to see upstream changes a little more often.

Right this moment we're looking to deploy a development version of PacketFu that handles the new(ish) PCAP-NG format, over at packetfu/packetfu#152. This particular change is merely a point release (old format will still be supported), but expect more exciting changes as time goes on.

At any rate, if you alter Metasploit's gemset to track the next dev change once that issue is resolved (via a new gem update), it would be super handy to validate the file format changes.

cc @kgray-r7 @lsanchez-r7

**Comment by claudijd** [comment]
Thanks @todb-r7, the pre-release version is now out for feedback.

**Comment by bcook-r7** [comment]
Doesn't seem like there has been much movement with packetfu since this announcement. Anything we can do here to help usher 1.1.12 into the world?

**Comment by claudijd** [comment]
@bcook-r7 sorry for the delay here, I was traveling and on vacation for a while and I'm just now catching my breath.  As per the per the pre-release, we really haven't gotten much feedback good/bad/meh.  Since the feature doesn't actually affect default parsing logic, I think we can probably move forward with a prod release soon.

**Comment by busterb** [comment]
Gemset updated a month ago, we now have pcap-NG support. Who knew!? Thanks @todb and @claudijd
