### ISSUE TITLE
Docker Remote API Unauthenticated Access

### ISSUE THREAD

**Issue by nixawk** [rapid7/metasploit-framework#6881]
Please read the documentation - [Build a Swarm cluster for production](https://docs.docker.com/swarm/install-manual/).  

> Configure and start Engine so it listens for Swarm nodes on port 2375.

```
$ sudo docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
```

This is not a bug, just a misconfiguration. Docker binds `0.0.0.0:2375`, attackers can access your lab/code/data with [simple api requests](https://docs.docker.com/engine/reference/api/docker_remote_api/).  Please redirects to [here](http://drops.wooyun.org/papers/15892) for details.

**Comment by h00die** [comment]
the drops.wooyun.org paper seems to not be working.  The page is just a jpg or other non-text object and google translate can't do anything with it.  Maybe its a 404 or something?

**Comment by bcoles** [comment]
I'm not sure what happened to the drops.wooyun.org paper, but it's still up on the Internet Archive:

* http://web.archive.org/web/20160519200612/http://drops.wooyun.org/papers/15892

**Comment by mpizala** [comment]
PR #8768 implements this open issue.

**Comment by dmohanty-r7** [comment]
Thank you for the contribution, @mpizala.
