### ISSUE TITLE
Wiki Page: Setting-Up-a-Metasploit-Development-Environment Adjustment

### ISSUE THREAD

**Issue by silascutler** [rapid7/metasploit-framework#6903]
## Steps to reproduce

How'd you do it?
See Wiki Page: Setting-Up-a-Metasploit-Development-Environment.  During system setup:
Once that's done, fix your current terminal to use RVM's version of ruby:

source ~/.rvm/scripts/rvm
cd ~/git/metasploit-framework
rvm install .ruby-version

----------------
rvm --install .ruby-version

works for me.

## Expected behavior

Current version of Ruby should be installed

## Current behavior

ruby-2.3.1 is not installed.
Could not determine which Ruby to use; . should contain .rvmrc or .versions.conf or .ruby-version or .rbfu-version or .rbenv-version, or an appropriate line in Gemfile. ( see: 'rvm usage' )

### Metasploit version

Currentl:

### I installed Metasploit with:

In the process of installation
### OS

What OS are you running Metasploit on?

Ubuntu 14.04
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

------------------------------

During setup, following the wiki page Setting-Up-a-Metasploit-Development-Environment causes an error on the ruby installation step.  Adding /--/ allowed me to fix it, so it may help others. 

[Sorry if this is the wrong place for this.  Github doesn't allow for pull requests on wiki pages. :neutral_face:  }

**Comment by bcook-r7** [comment]
Updated the wiki, thanks for the detailed note @silascutler! Let me know if you spot any thing else out-of-place.

**Comment by silascutler** [comment]
Absolutely.  Thanks @bcook-r7
