### ISSUE TITLE
msfvenom silent failure

### ISSUE THREAD

**Issue by digininja** [rapid7/metasploit-framework#6915]
## Steps to reproduce

Someone just came on the Hak5 forum complaining that this command wasn't creating any output

```
./msfvenom -a x86 --platform OSX -p osx/x86/isight/bind_tcp -b "\x00" -f elf -o exportedFile
```

## Expected behavior

As you can't create an elf binary for OSX it should fail with an error rather than looking like it has completed successfully.

## Current behavior

It outputs this which looks like it succeeded when really it didn't

```
Found 10 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 171 (iteration=0)
x86/shikata_ga_nai chosen with final size 171
Payload size: 171 bytes
```

### Metasploit version

I reproduced it with this version, no idea what the OP was using

2e88eb528760852f3bd2103abc6e0a911ef88eb9 Merge branch 'zeroSteiner-fix-tab-stageencoder'

### I installed Metasploit with:
- [x ] Source install (please specify ruby version)

ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]

### OS

Debian, assume OP was OSX

**Comment by bcook-r7** [comment]
This should be addressed now. Thanks for the note!

**Comment by digininja** [comment]
Yes, can confirm that is now giving an error.
