### ISSUE TITLE
eliminate use of tzinfo-data

### ISSUE THREAD

**Issue by ZeroChaos-** [rapid7/metasploit-framework#6967]
## Steps to reproduce

How'd you do it?
1. try to install metasploit without tzinfo-data
2. ...
## Expected behavior

Not have duplicate copies of tzdata
## Current behavior

tzdata-info is required
### Metasploit version

head, and a few releases
### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X ] Source install ruby21
### OS

Linux

Is there a reason that metasploit can't just use tzinfo and system tz data?

**Comment by ZeroChaos-** [comment]
also, if users want to install it, they can install it and it will automatically be used by tzinfo.  No reason to hard require it that I can see.

**Comment by bcook-r7** [comment]
Windows. Maybe we can make it conditional?

**Comment by ZeroChaos-** [comment]
that would be cool.  it's hardly a crisis for me to sed out, but I'd imagine most linux users just don't need this and having two different versions of tzinfo could lead to unexpected behavior.

**Comment by busterb** [comment]
Tried this, couldn't safely remove for other packaging reasons. You'll need to stick with local workarounds for now. Sorry about that!
