### ISSUE TITLE
[windows/gather/enum_chrome] Fails to decrypt, no specific error

### ISSUE THREAD

**Issue by Vastrix** [rapid7/metasploit-framework#6972]
## Current behavior

What happens instead?
Note that the text files are created, the relevant fields however are encrypted..

[Mini StackTrace](http://pastebin.com/3ku4HMtu)

## System stuff

Kali linux (Latest)

### Metasploit version

Kali linux didn't show any updates (distr or otherwise)
So probably the latest 

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Kali Linux

**Comment by Vastrix** [comment]
Thanks pbarry-r7 ;)

**Comment by pbarry-r7** [comment]
Will do, thanks, @Vastrix!!  :)

**Comment by simonpunk** [comment]
Hey, I have encountered same issue on my win10, but I did succeeded to extract the decrypted content on win7. And both of my test machine is using latest chrome version.

So just my guess, my win10 machine is running Chinese language while win7 is running English by default, and I already knew there are some incompatible command not able to be executed in meterpreter such as 'ls', I remember the command fails to show anything when the path exists chinese named files. So I just wonder if you have the same case as mine.

so in my opinion, my best bet is the incompatible language over the OS.

**Comment by Vastrix** [comment]
@simonpunk Hmm...
I tried it on 2 (non-english) win7 systems and 1 English Win10 system..
All with the same result..

So yea, it might be an issue with win10 and non-english win7 systems? :s 
Thanks for confirming tho ;)

**Comment by pbarry-r7** [comment]
Thanks again for the info, y'all.  I have a tiny PR out to avoid the exception, but it appears Chrome has moved extension info in the preferences file, so there might be additional work I need to do there...

@Vastrix, could you provide an example or two of some of the 'not decrypted' fields in the retrieved text files?  Want to make sure I'm addressing your problem (other than the exception, itself).  Thanks much!

**Comment by Vastrix** [comment]
@pbarry-r7 Here ya go, all column names from the **Login** .sqlite extraction :)
![](http://puu.sh/pzDtC/0efc56c43b.png)

origin_url
action_url
username_element
username_value
password_element
password_value
submit_element
signon_realm
ssl_valid
preferred
date_created
blacklisted_by_user
scheme
password_type
possible_usernames
times_used
form_data
date_synced
display_name
icon_url
federation_url
skip_zero_click
generation_upload_status

META
key
value

STATS
origin_womain
username_walue
dismissal_count
update_time

If you want the column names from the other files as well, just ask ;)

**Comment by pbarry-r7** [comment]
This is perfect, thanks, @Vastrix.  I have the same in my login data, I'll dig into the module to see what's going on...

**Comment by Vastrix** [comment]
Awesome, Cheers mate ;)

**Comment by pbarry-r7** [comment]
Hey @Vastrix, apologies for the delay on this issue.  I believe the decryption problem was fixed with the [PR landed](https://github.com/rapid7/metasploit-framework/pull/6997) a few days ago that took care of the exception you were hitting (which, itself, prevented the module from reaching the 'write decrypted data to disk' logic).  I realize you're on Kali, but if you have interest in verifying you could clone the metasploit-framework and check it out.

FWIW, here's output from my run:

```
msf post(enum_chrome) > run

[*] Impersonating token: 1604
[*] Running as user 'WINDOWS81-PB\Pearce'...
[*] Extracting data for user 'Pearce'...
[*] Downloaded Web Data to '/home/pbarry/.msf4/loot/20160623145736_default_10.6.0.122_chrome.raw.WebD_491198.txt'
[*] Downloaded Cookies to '/home/pbarry/.msf4/loot/20160623145737_default_10.6.0.122_chrome.raw.Cooki_101239.txt'
[*] Downloaded History to '/home/pbarry/.msf4/loot/20160623145737_default_10.6.0.122_chrome.raw.Histo_604020.txt'
[*] Downloaded Login Data to '/home/pbarry/.msf4/loot/20160623145738_default_10.6.0.122_chrome.raw.Login_633330.txt'
[*] Downloaded Bookmarks to '/home/pbarry/.msf4/loot/20160623145739_default_10.6.0.122_chrome.raw.Bookm_619550.txt'
[*] Downloaded Preferences to '/home/pbarry/.msf4/loot/20160623145739_default_10.6.0.122_chrome.raw.Prefe_084677.txt'
[*] Decrypted data saved in: /home/pbarry/.msf4/loot/20160623145741_default_10.6.0.122_chrome.decrypted_932173.txt
[*] Post module execution completed
```

```
pbarry@ubuntu-1604-pbarry:~$ cat /home/pbarry/.msf4/loot/20160623145741_default_10.6.0.122_chrome.decrypted_932173.txt
Decrypted data
==============

 Name                     Decrypted Data  Origin
 ----                     --------------  ------
 dummymymy                <PASSWORD IN PLAINTEXT HERE>          https://www.<REDACTED>.com/
 testytest@<REDACTED>.net  <PASSWORD IN PLAINTEXT HERE>       https://www.<REDACTED>.com/account/signup
```

Thanks!

**Comment by Vastrix** [comment]
@pbarry-r7 
Awesome! 
I verified it and you are ~~indeed~~ ofcourse correct! :)
The module runs without any issue now.

Thank you very much for this fast fix!

**Comment by pbarry-r7** [comment]
Thanks much for the verify, @Vastrix.  Cheers!

**Comment by pbarry-r7** [comment]
For future ticket viewers (in case pastebin expires the post), here's the stacktrace referenced in the original description above:

```
[*] Running as user 'PC-395\REDACTED'...
[*] Extracting data for user 'REDACTED'...
[*] Downloaded Web Data to '/root/.msf4/loot/20160614113342_default_192.168.2.250_chrome.raw.WebD_237576.txt'
[*] Downloaded Cookies to '/root/.msf4/loot/20160614113343_default_192.168.2.250_chrome.raw.Cooki_382540.txt'
[*] Downloaded History to '/root/.msf4/loot/20160614113343_default_192.168.2.250_chrome.raw.Histo_146527.txt'
[*] Downloaded Login Data to '/root/.msf4/loot/20160614113346_default_192.168.2.250_chrome.raw.Login_702580.txt'
[*] Downloaded Bookmarks to '/root/.msf4/loot/20160614113346_default_192.168.2.250_chrome.raw.Bookm_508046.txt'
[*] Downloaded Preferences to '/root/.msf4/loot/20160614113346_default_192.168.2.250_chrome.raw.Prefe_203254.txt'
[*] Extensions installed: 
[-] Post failed: NoMethodError undefined method `each' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:89:in `parse_prefs'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:140:in `block in process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:138:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:138:in `process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:329:in `block in run'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:326:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:326:in `run'
[*] Post module execution completed
```
