### ISSUE TITLE
port forwarding issue

### ISSUE THREAD

**Issue by Hami19** [rapid7/metasploit-framework#6985]
i try to add port forward in router but i get this error

Error code: 26106
The IP address is not in the same subnet with LAN IP address.

My virtual machine ip address is 192.168.43.128

and in DHCP setting of router
Start IP Address:	
192.168.0.100
End IP Address:	
192.168.0.199
Default Gateway:	
192.168.0.1

i want to add port=4444 and ip address=192.168.43.128 in port forwarding...

Plz help me i have no idea what can i do!!!

**Comment by mubix** [comment]
This is a general networking question and not specific to Metasploit. I will close this issue, but basically your router is saying that the IP isn't in the same subnet, which isn't (192.168.43 vs 192.168.0). You probably need to switch your VM into "bridged" mode for what you are trying to do to work. Please take future questions to StackOverflow or your router's support forum.

Thanks!
