### ISSUE TITLE
db_export XML

### ISSUE THREAD

**Issue by Phexcom** [rapid7/metasploit-framework#7008]
Metasploit fails to export database to XML

msf > hosts 

Hosts
=====

address         mac                name       os_name  os_flavor  os_sp  purpose  info  comments
-------         ---                ----       -------  ---------  -----  -------  ----  --------
127.0.0.1                          localhost                 3.X    server         
   

msf > db_export -f xml /root/msf/report.xml
[*] Starting export of workspace localhost to /root/msf/report.xml [ xml ]...
[*]     >> Starting export of report
[-] Error while running command db_export: Couldn't find all Mdm::Notes with 'id': (first, {:conditions=>{:ntype=>"pro.system.compromise"}}) [WHERE "notes"."host_id" = ?] (found 0 results, but was looking for 2)

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:467:in `find_some'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:71:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:99:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:141:in `find'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:128:in `block in extract_host_entries'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:127:in `extract_host_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:115:in `extract_target_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:48:in `to_xml_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1804:in `block in cmd_db_export'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1771:in `cmd_db_export'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

**Comment by caino** [comment]
I've this problem too.

`msf > db_export nsc
[*] Starting export of workspace nsc to nsc [ xml ]...
[*]     >> Starting export of report
[-] Error while running command db_export: Couldn't find all Mdm::Notes with 'id': (first, {:conditions=>{:ntype=>"pro.system.compromise"}}) [WHERE "notes"."host_id" = ?] (found 0 results, but was looking for 2)

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:467:in `find_some'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:71:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:99:in `find'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:141:in `find'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:128:in `block in extract_host_entries'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:127:in `extract_host_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:115:in `extract_target_entries'
/usr/share/metasploit-framework/lib/msf/core/db_export.rb:48:in `to_xml_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1804:in `block in cmd_db_export'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1771:in `cmd_db_export'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'`

**Comment by pbarry-r7** [comment]
# Release Notes

Cannot export the msf database in XML format (PR-7008) - The msfconsole **db_export** command would no longer successfully export the database in XML format due to a compatibility issue with a recently-updated Active Record gem.  This fix updates the **db_export** command to use new calls Active Record is happy with.

**Comment by tdoan-r7** [comment]
@pbarry-r7 Nice work! Thank for writing release notes! :)

**Comment by pbarry-r7** [comment]
@tdoan-r7 and next time, I'll make sure to put it on the PR where it belongs!!  :P

**Comment by tdoan-r7** [comment]
@pbarry-r7 So close!
