### ISSUE TITLE
Database System Not Starting OS X Elcaptian

### ISSUE THREAD

**Issue by theman480** [rapid7/metasploit-framework#7013]
## Steps to reproduce

The database system is not starting on OS x El Captian.
I am having the following error:
`[-] Failed to connect to the database: FATAL:  the database system is shutting down
``

I need help to start postgres on OS x with the free nightly package installer, i don't  know how the postgres was installed with this package, so i don't know how to restart this.

Thank you in advice!
### OS

What OS are you running Metasploit on?

Os x El Captian

**Comment by busterb** [comment]
We recently found the cause for this. It's Cylance!

Update the “Memory Actions” exclusion list (found in Device Policies) with *absolute file paths*. Directory paths are not sufficient - it needs the specific file path to the binaries/libraries that are being blocked.

For current omnibus installer, exclude these files:
```
/opt/metasploit-framework/embedded/lib/libpq.5.9.dylib
/opt/metasploit-framework/embedded/lib/libpq.5.7.dylib
/opt/metasploit-framework/embedded/postgresql-prev/lib/libpq.5.7.dylib
/opt/metasploit-framework/embedded/bin/psql
/opt/metasploit-framework/embedded/postgresql-prev/bin/psql
/opt/metasploit-framework/embedded/bin/postgres
/opt/metasploit-framework/embedded/postgresql-prev/bin/postgres
```
