### ISSUE TITLE
msfconsole doesn't worked after update metasploit in kali rolling

### ISSUE THREAD

**Issue by lizardpunk** [rapid7/metasploit-framework#7036]
msfconsole
/usr/lib/ruby/2.3.0/openssl.rb:13:in `require': /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference - /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so (LoadError)
	from /usr/lib/ruby/2.3.0/openssl.rb:13:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from /usr/bin/msfconsole:48:in `<main>'

**Comment by lizardpunk** [comment]
i just fixed, apt-get remove metasploit-framework   then apt-get install metasploit-framework, then apt-get install ruby, then  apt-get install openssl  then cd  /usr/share/metasploit-framework# bundle install, thats it

**Comment by Tinydile** [comment]
I could successfully installed by:
# apt-get install ruby openssl
# apt-get install zlib1g-dev libssl-dev
# apt-get install metasploit-framework

**Comment by Tinydile** [comment]
I successfully installed by:
```
# apt-get install ruby openssl
# apt-get install zlib1g-dev libssl-dev
# apt-get install metasploit-framework
```

**Comment by Sanya1991** [comment]
After I installed veil-evasion (apt-get install veil-evasion) I got the same error. I've read Tinydile post, and I tried this: apt-get install openssl. The problem was gone, metasploit is working, veil-evasion as well.

**Comment by femskey** [comment]
database appears to be already configured, skipping initialization
/usr/lib/ruby/2.3.0/openssl.rb:13:in `require': /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference - /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so (LoadError)
	from /usr/lib/ruby/2.3.0/openssl.rb:13:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from /usr/bin/msfconsole:48:in `<main>'
root@kali:~# 






pls  my metaspoit is not working  and beef and some others , help me plsssssssssssssss

**Comment by busterb** [comment]
try #kali-linux on freenode. sounds like you didn't do 'apt-get dist-upgrade', or you caught kali in the middle of a package update and should try again later.

**Comment by femskey** [comment]
i have try apt-get dist-upgrade ,apt-get upgrade and apt-get update noting happen

root@kali:/usr/share/metasploit-framework# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Could not load OpenSSL.
You must recompile Ruby with OpenSSL support or change the sources in your Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL
using RVM are available at http://rvm.io/packages/openssl.



root@kali:/usr/share/metasploit-framework# gem install bundler
ERROR:  Loading command: install (LoadError)
	/usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference - /usr/lib/i386-linux-gnu/ruby/2.3.0/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by busterb** [comment]
There is not much we can do from here, this is an issue with your Linux distribution. I suggest reaching out to the Kali Linux support channels.

**Comment by femskey** [comment]
ok thanks

**Comment by vsxen** [comment]
sometimes   you may need apt upgrade

**Comment by 1m0r74l17y** [comment]
i did apt upgrade, apt-get remove metasploit-framework, apt-get install metasploit-framework, apt-get install ruby, apt-get install openssl, cd /usr/share/metasploit-framework, bundle install, and it worked :)

**Comment by busterb** [comment]
If you have to do this, then Kali is messed up. Please raise it on their forums.
