### ISSUE TITLE
Small addition needed for the Setting Up a Metasploit Development Environment page

### ISSUE THREAD

**Issue by taishi8117** [rapid7/metasploit-framework#7057]
In the [Run Specs](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#run-specs) --- for those who install and set up the development environment for the first time, `rake db:schema:load` needs to be executed to prepare the database before the `rake spec` command. 

In the [Msftidy](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#msftidy) --- 

```
cd $HOME/git/metasploit-framework
ln -sf ../../tools/dev/pre-commit-hook.rb .git/hooks/pre-commit
ln -sf ../../tools/dev/pre-commit-hook.rb .git/hooks/post-merge
```
needs to be changed to
```
cd $HOME/git/metasploit-framework
ln -sf tools/dev/pre-commit-hook.rb .git/hooks/pre-commit
ln -sf tools/dev/pre-commit-hook.rb .git/hooks/post-merge
```

**Comment by bcook-r7** [comment]
Thanks for the note, fixed.
