### ISSUE TITLE
ifconfig and ipconfig commands don't work in python/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7073]
In python/meterpreter/reverse_tcp, ifconfig and ipconfig should display the interfaces of the compromised machine:

```
meterpreter > help
...
Stdapi: Networking Commands
===========================

    Command       Description
    -------       -----------
    ifconfig      Display interfaces
    ipconfig      Display interfaces
    portfwd       Forward a local port to a remote service
    resolve       Resolve a set of host names on the target
...
```

But it looks like they don't actually do anything:

```
meterpreter > getuid
Server username: root
meterpreter > ifconfig
[-] stdapi_net_config_get_interfaces: Operation failed: Unknown error
meterpreter > ipconfig
[-] stdapi_net_config_get_interfaces: Operation failed: Unknown error
meterpreter > 
```

Commands executed as root, so permission should not be a problem. Tested on OS X.

**Comment by wvu-r7** [comment]
Looks like we're using Homebrew Python. Try /usr/bin/python? The system Python should have ```SystemConfiguration```.

**Comment by pbarry-r7** [comment]
To @wvu-r7 's point, ifconfig works on my Ubuntu 16.04 x64 instance via the python/meterpreter/reverse_tcp (using python 2.7).

**Comment by wvu-r7** [comment]
I forgot I was going to do this.

**Comment by wvu-r7** [comment]
Fixed in https://github.com/rapid7/metasploit-payloads/pull/145. Thanks, @zeroSteiner. I didn't even have to do anything!
