### ISSUE TITLE
Add KB for multi/http/caidao_php_backdoor_exec

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7136]
Add KB for multi/http/caidao_php_backdoor_exec

**Comment by tdoan-r7** [comment]
For instructions on how to write documentation for modules, see https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation.

**Comment by shipcod3** [comment]
I would love to take on this one.

**Comment by JohnMartinelli** [comment]
Id be willing to help.

**Comment by shipcod3** [comment]
@wchen-r7 and @JohnMartinelli, this has been taken care off. Lemme know what needs to be edited or added.
