### ISSUE TITLE
Add KB for php/meterpreter/reverse_tcp

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7141]
Add KB for php/meterpreter/reverse_tcp

**Comment by tdoan-r7** [comment]
For instructions on how to write documentation for modules, see https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation.

**Comment by kkirsche** [comment]
This looks like it was completed in #7712 / https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/php/meterpreter/reverse_tcp.md

Should this be closed?

**Comment by bcoles** [comment]
Closing as completed.

**Comment by Crisprs9** [comment]
`<>`
