### ISSUE TITLE
android meterpreter multi target

### ISSUE THREAD

**Issue by salamsalamabc** [rapid7/metasploit-framework#7150]
How to save each target's data in their folders separately after run meterpreter command  automatically.
for example: run download file from session 1 save to folder 1 and run download file from session 2 save to folder 2

tnx for all

**Comment by salamsalamabc** [comment]
can any one help me?

**Comment by bcook-r7** [comment]
if you want the 'download' command to save data from each android meterpreter session automatically, you would create a script that does this, and connect it with the 'AutoRunScript' advanced option.

**Comment by bcook-r7** [comment]
There are lots of tutorials online for how to do this. See https://offensiveinfosec.wordpress.com/tag/autorunscript/ for instance. You will likely need to write a little ruby code to setup the local directory per-session. See ./scripts/meterpreter/multicommand.rb or ./scripts/meterpreter/multiscript.rb for examples.

Github really isn't a help forum though, it's for bugs reports and feature requests, so I'm going to close this one out. Thanks!

**Comment by salamsalamabc** [comment]
Thanks for your guide Man.
