### ISSUE TITLE
Feature Request: Get child pids

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#7167]
During engagements it would be nice to see any processes that are left running that are child processes of the current shell's PID

**Comment by OJ** [comment]
Nice idea. Should we support nesting as well?

**Comment by wvu-r7** [comment]
It'd be cool to have an ASCII tree, too.

**Comment by wchen-r7** [comment]
This looks more like a Meterpreter feature because ```client.sys.process.processes``` simply doesn't have this info. For example:

```
>> client.sys.process.processes.last
=> {"pid"=>1200, "ppid"=>1664, "name"=>"test.exe", "path"=>"C:\\Documents and Settings\\sinn3r\\Desktop\\test.exe", "session"=>0, "user"=>"SINN3R-4345996F\\sinn3r", "arch"=>"x86"}
```

**Comment by bcook-r7** [comment]
"ppid" is the Parent PID. You just nest children in their respective PPID's

**Comment by wvu-r7** [comment]
Sniped! Beat me to it. :)

**Comment by bcook-r7** [comment]
I shall do you the honor of implementing this. Sounds like a super nice thing to have.

**Comment by wvu-r7** [comment]
Just implemented it. Will PR in a sec. :D
