### ISSUE TITLE
New feature - HTTP TRACE file

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#7170]
Hi all,
what do you think of adding a new advanced option to the httpclient mixin: HTTPTRACE

My thoughts where to write out all requests before sending and responses after receiving for further investigation. This would help track down some issues and can be provided on bug reports.

Thoughts?

**Comment by egypt** [comment]
I think it would be useful. When I'm debugging I often add print statements to see request/response. Might be handy to have options for `headers` or full `body`.

**Comment by FireFart** [comment]
that's exactly what I'm always doing and it can be painful :)

**Comment by wchen-r7** [comment]
Just to print the requests and responses? Yeah I need to see that when I'm writing a Metasploit module.... I'll up for it.
