### ISSUE TITLE
Windows Secure Boot Keys Leaked

### ISSUE THREAD

**Issue by zero77** [rapid7/metasploit-framework#7198]
Microsoft has accidentally leaked the Secret keys that allow anyone to unlock devices protected by UEFI.

Can you add these keys to the metasploit framework.

https://thehackernews.com/2016/08/uefi-secure-boot-hack.html

**Comment by bwatters-r7** [comment]
It does not appear to be actual keys, but a method by which you can alter the boot process to bypass the protections of a properly-signed bootloader. through side-loading of a supplemental policy.  Relevant portion of the original disclosure <autoplay audio> (https://rol.im/securegoldenkeyboot/):

**Comment by zero77** [comment]
Yes, I think both would be useful, although as two separate post modules.

**Comment by bcook-r7** [comment]
This is kind of a heavy lift for a feature request. It could potentially be an entire project on its own.
