### ISSUE TITLE
tomcat_mgr_login module no longer displays the IP for the system its trying to loginto

### ISSUE THREAD

**Issue by purehate** [rapid7/metasploit-framework#7202]
When scanning for default tomcat logins, the module used to display the IP of the box so if you scanned lots of boxes you would know which one you found default creds to. That is no longer the case.

[-] TOMCAT_MGR - LOGIN FAILED: admin:admin (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: admin:manager (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: admin:role1 (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: admin:root (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: admin:tomcat (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: admin:s3cret (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:admin (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:manager (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:role1 (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:root (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:tomcat (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: manager:s3cret (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:admin (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:manager (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:role1 (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:root (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:tomcat (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: role1:s3cret (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:admin (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:manager (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:role1 (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:root (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:tomcat (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: root:s3cret (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: tomcat:admin (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: tomcat:manager (Incorrect: )
[-] TOMCAT_MGR - LOGIN FAILED: tomcat:role1 (Incorrect: )

### Metasploit version
msf auxiliary(tomcat_mgr_login) > version
Framework: 4.12.19-dev-280216d74dae28fc0e8a2f1cadee1ce6fe438c59
Console  : 4.12.19-dev-280216d74dae28fc0e8a2f1cadee1ce6fe438c59
Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Source install (please specify ruby version)
msf auxiliary(tomcat_mgr_login) > ruby -v
[*] exec: ruby -v

ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-linux]
### OS
root@TAP:~# cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

**Comment by wvu-r7** [comment]
Repro'd here. This seems to be a problem with ```vprint_*``` as used by ```AuthBrute```.

**Comment by wchen-r7** [comment]
@wvu-r7 This is related to https://github.com/rapid7/metasploit-framework/pull/6950

**Comment by wvu-r7** [comment]
Just tested - definitely related.

**Comment by wchen-r7** [comment]
👍
