### ISSUE TITLE
Problem running post-install step. Installation may not complete correctly

### ISSUE THREAD

**Issue by trueb0t** [rapid7/metasploit-framework#7206]
I'm using Ubuntu 12.04LTS/amd64. Ruby version `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`, rubygems version 2.5.1. After unpacking have this two errors.

![_229](https://cloud.githubusercontent.com/assets/20445217/17650222/4db1cf2c-6251-11e6-96e2-8ef44f39fb78.png)
![_230](https://cloud.githubusercontent.com/assets/20445217/17650223/54558ad0-6251-11e6-9655-70cfcc263149.png)
Also, after finish installation run `msfconsole`, but do nothing 15 minuts. 
How i can run MSF?

**Comment by bcook-r7** [comment]
It appears you are installing the 32-bit version of the package on a 64-bit version of Ubuntu. Please use the 64-bit (x64) version of the installer, as the 32-bit installers should be going away soon (CC @cdoughty-r7).

The version of Ruby that you use with the rest of the system does not matter for the Metasploit Pro installer.

**Comment by drnextgis** [comment]
I've faced with the same issue. Hopefully helps some future googlers:

```
/opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in `require': cannot load such file -- rbconfig (LoadError)
	from /opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

**Comment by bcook-r7** [comment]
Was it resolved for you, or still an issue?

**Comment by drnextgis** [comment]
After using `metasploit-latest-linux-x64-installer.run` instead `metasploit-latest-linux-installer.run` problem is gone.
