### ISSUE TITLE
ssh_identify_pubkey not working

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#7234]
I ssh with a known user and ssh private key and it logs in fine `ssh -i FILE user@HOST`

Using ssh_identify_pubkeys:

```
set RHOSTS HOST
set USERNAME user
set KEY_FILE FILE
```

returns:

`User x does not accept key 1`

Key isn't encrypted or anything.

**Comment by wvu-r7** [comment]
Repro'd here on latest and with #7232 landed.

**Comment by bcook-r7** [comment]
This should be fixed now. The module had to be largely rewritten with a custom state machine in #7232

**Comment by bcook-r7** [comment]
That is, #7339 fixes it.
