### ISSUE TITLE
auxiliary/scanner/smb/smb_login ignoring CPORT directive

### ISSUE THREAD

**Issue by attackdebris** [rapid7/metasploit-framework#7236]
## Steps to reproduce

I'm attempting to run an auxiliary/scanner/smb/smb_login with a CPORT defined e.g. 9000

## Expected behavior

The smb login attempt should be conducted via source port 9000 (or whatever CPORT is defined)

## Current behavior

The smb login attempt is being conducted via arbitrary source ports even when CPORT is defined. Confirmed via several different packet captures / different CPORTs (all being ignored).

### Metasploit version
Framework: 4.12.21-dev

### I installed Metasploit with:
- [x ] Kali package via apt

### OS
Kali Rolling Linux

**Comment by bwatters-r7** [comment]
Thanks for the catch @attackdebris !

**Comment by wvu-r7** [comment]
Closing manually.
