### ISSUE TITLE
Feature Request: Disable SMB detection of "any credential" detection

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#7237]
The SMB_LOGIN module checks automatically if "any" credentials could be used to authenticate to the target. While this is important for validation it also adds a possible indicator of compromise without any warning or option to turn off. 

Basically it would be nice if there was an advanced feature that "Enable detection systems accepting any authentication" that was enabled by default but would have the ability to disable it.

**Comment by wvu-r7** [comment]
Yuck, it does run by default:

```
 90     bogus_result = @scanner.attempt_bogus_login(domain)
 91     if bogus_result.success?
 92       if bogus_result.access_level == Metasploit::Framework::LoginScanner::SMB::AccessLevels::GUEST
 93         print_status("This system allows guest sessions with any credentials")
 94       else
 95         print_error("This system accepts authentication with any credentials, brute force is ineffective.")
 96         return
 97       end
 98     end
```

Fixing. Can you merge quickly?

**Comment by wvu-r7** [comment]
Doesn't hurt to let other eyes check it. Up to you.
