### ISSUE TITLE
Feature request: reverse_http_rc4

### ISSUE THREAD

**Issue by User0815** [rapid7/metasploit-framework#7243]
When attacking an internal network where the command&control server is on the internet, you sometimes  can't use reverse_tcp_rc4 because  external servers can only be reached via a HTTP proxy, and you also can't use reverse_http or reverse_https if they inspect the traffic on the proxy and the clients trust the corporate CA. Encrypting the data inside the HTTP requests (e.g. with RC4) should solve this.

**Comment by busterb** [comment]
Reverse HTTP now always encrypts with AES as of a couple of years ago, so this is effectively implemented. Thanks for the suggestion!
