### ISSUE TITLE
John error in mac os 

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#7260]
**use auxiliary/analyze/jtr_mysql_fast**
run

[*] Wordlist file written out to /var/folders/k5/n1bnf5d57lj_b_zz8zyxrdn80000gn/T/jtrtmp20160831-66863-yn5egi
[*] Hashes Written out to /var/folders/k5/n1bnf5d57lj_b_zz8zyxrdn80000gn/T/hashes_tmp20160831-66863-gz6l4v
[*] Cracking mysql hashes in normal wordlist mode...
Unknown option: "--nolog"
[*] Cracking mysql hashes in single mode...
Unknown option: "--nolog"
[*] Cracking mysql hashes in incremental mode (Digits)...
Unknown option: "--nolog"
[*] Cracked Passwords this run:
Unknown option: "--pot=/Users/*/.msf4/john.pot"
[*] Cracking mysql-sha1 hashes in normal wordlist mode...
Unknown option: "--nolog"
[*] Cracking mysql-sha1 hashes in single mode...
Unknown option: "--nolog"
[*] Cracking mysql-sha1 hashes in incremental mode (Digits)...
Unknown option: "--nolog"
[*] Cracked Passwords this run:
Unknown option: "--pot=/Users/*/.msf4/john.pot"
[*] Auxiliary module execution completed

**my system**
mac os X10.11.6

**my John:**
john
John the Ripper password cracker, version 1.8.0
Copyright (c) 1996-2013 by Solar Designer
Homepage: http://www.openwall.com/john/

Usage: john [OPTIONS] [PASSWORD-FILES]
--single                   "single crack" mode
--wordlist=FILE --stdin    wordlist mode, read words from FILE or stdin
--rules                    enable word mangling rules for wordlist mode
--incremental[=MODE]       "incremental" mode [using section MODE]
--external=MODE            external mode or word filter
--stdout[=LENGTH]          just output candidate passwords [cut at LENGTH]
--restore[=NAME]           restore an interrupted session [called NAME]
--session=NAME             give a new session the NAME
--status[=NAME]            print status of a session [called NAME]
--make-charset=FILE        make a charset, FILE will be overwritten
--show                     show cracked passwords
--test[=TIME]              run tests and benchmarks for TIME seconds each
--users=[-]LOGIN|UID[,..]  [do not] load this (these) user(s) only
--groups=[-]GID[,..]       load users [not] of this (these) group(s) only
--shells=[-]SHELL[,..]     load users with[out] this (these) shell(s) only
--salts=[-]N               load salts with[out] at least N passwords only
--save-memory=LEVEL        enable memory saving, at LEVEL 1..3
--node=MIN[-MAX]/TOTAL     this node's number range out of TOTAL count
--fork=N                   fork N processes
--format=NAME              force hash type NAME: descrypt/bsdicrypt/md5crypt/
                           bcrypt/LM/AFS/tripcode/dummy

**Comment by wvu-r7** [comment]
I assume you used Homebrew to install John the Ripper. Try ```brew install john-jumbo```. It has ```--nolog```

**Comment by wvu-r7** [comment]
I assume you used Homebrew to install John the Ripper. Try ```brew install john-jumbo```. It has ```--nolog```.

**Comment by hktalent** [comment]
thanks 
brew uninstall john
brew install john-jumbo
so is ok

Cracking mysql-sha1 hashes in incremental mode (Digits)...
Invalid options combination or duplicate option: "--incremental=Digits"
Warning: passwords printed above might not be all those cracked
Use the "--show" option to display all of the cracked passwords reliably
