### ISSUE TITLE
Pivoting with linux/x86/meterpreter/reverse_tcp - error "session closed.  Reason: Died"

### ISSUE THREAD

**Issue by user843** [rapid7/metasploit-framework#7297]
Pivoting using the route or portfwd command makes the linux/x86/mterpreter/reverse_tcp die.
## Steps to reproduce
1. Get a linux/x86/meterpreter/reverse_tcp  session.
2. Add a route or portfwd, for example: portfwd add -l 80 -r SOME_REMOTE_HOST -p 80
3. Open a web browser and navigate to http://attacker_ip:80
## Expected behavior

Being able to route traffic through the meterpreter session on the compromised host.
## Current behavior

After a few packets the meterpreter session dies with the following error:

"Meterpreter session 4 closed.  Reason: Died"

The result is the same even if I try to use an auxiliary scanner module after adding a route using the "route" command... the meterpreter session suddenly dies after few packets sent by the scanner.
### Metasploit version

v4.12.23-dev
### I installed Metasploit with:
- [x] Kali package via apt
### OS

Kali Linux 2016.2

I even tried on other two operating systems (two different attacking hosts and two different victims) but the result is the same.

**Comment by wvu-r7** [comment]
Thanks for the bug report. Linux Meterpreter isn't exactly stable to begin with.

**Comment by ch1kpee** [comment]
I'm having the exact same issue (trying to portfwd to an internal-only website, Linux meterpreter dies every time).

**Comment by busterb** [comment]
this should be resolved now as of #8279

**Comment by wvu-r7** [comment]
Damn right it is!
