### ISSUE TITLE
domain_hashdump hanging after NTDS repair

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#7323]
@Slurpgeit reported this on IRC. Details forthcoming? This is a placeholder issue.

**Comment by Slurpgeit** [comment]
I hereby promise to provide details soon :)

**Comment by Slurpgeit** [comment]
Ok, so I did my best, but I couldn't get any really relevant info. I tried replicating it on my test domain, but it did not do anything weird.

I did do an engagement this week where it sort-of happened. After running the module it stopped after dumping the first hash (there were about 200 users, nothing too major):

```
21-09-2016 11:02:51 msf post(domain_hashdump) > run

[*] [2016.09.21-11:02:55] Volume Shadow Copy service not running. Starting it now...
[+] [2016.09.21-11:02:56] Volume Shadow Copy started successfully.
[*] [2016.09.21-11:02:58] Software Shadow Copy service not running. Starting it now...
[+] [2016.09.21-11:02:58] Software Shadow Copy started successfully.
[*] [2016.09.21-11:03:32] NTDS database copied to C:\Windows\Temp\MUYJfBzTvBw\Active Directory\ntds.dit
[*] [2016.09.21-11:03:32] Repairing NTDS database after copy...
[*] [2016.09.21-11:03:43] 
Initiating REPAIR mode...
        Database: C:\Windows\Temp\MUYJfBzTvBw\Active Directory\ntds.dit
  Temp. Database: TEMPREPAIR4788.EDB


Checking database integrity.


                     Scanning Status (% complete)

          0    10   20   30   40   50   60   70   80   90  100
          |----|----|----|----|----|----|----|----|----|----|
          ...................................................



Integrity check successful.



Note:
  It is recommended that you immediately perform a full backup
  of this database. If you restore a backup made before the
  repair, the database will be rolled back to the state
  it was in at the time of that backup.

Operation completed successfully in 10.844 seconds.

[+] [2016.09.21-11:03:44]           Administrator (Built-in account for administering the computer/domain)
          Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          Password Expires: r
          Last Password Change: 1:54:12 PM Tuesday, July 29, 2014
          Last Logon: 7:05:37 AM Wednesday, September 21, 2016
          Logon Count: 65535
           - Password Never Expires

          Hash History:
          Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Administrator:500:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I can't share the ntds file for obvious reasons. This is the DC in question:

```
address        mac                name  os_name          os_flavor   os_sp  purpose  info  comments
-------        ---                ----  -------          ---------   -----  -------  ----  --------
xxx.xxx.xxx.x  00:00:00:00:00:00  XXXX  Windows 2008 R2  Enterprise  SP1    server   
```

For what it's worth, it was running McAfee VSE

**Comment by wvu-r7** [comment]
Thanks, @Slurpgeit!

**Comment by dwendt** [comment]
Happens in my case as well, but it never gets to the first hash. The ntds.dit in this situation is ~800mb.

```
[*] Volume Shadow Copy service not running. Starting it now...
[+] Volume Shadow Copy started successfully.
[*] Software Shadow Copy service not running. Starting it now...
[+] Software Shadow Copy started successfully.
[*] NTDS database copied to C:\Windows\Temp\pessgIAo\Active Directory\ntds.dit
[*] Repairing NTDS database after copy...
[*]
Initiating REPAIR mode...
        Database: C:\Windows\Temp\pessgIAo\Active Directory\ntds.dit
  Temp. Database: TEMPREPAIR6004.EDB

Checking database integrity.

                     Scanning Status (% complete)

          0    10   20   30   40   50   60   70   80   90  100
          |----|----|----|----|----|----|----|----|----|----|
          ...................................................


Integrity check successful.

Note:
  It is recommended that you immediately perform a full backup
  of this database. If you restore a backup made before the
  repair, the database will be rolled back to the state
  it was in at the time of that backup.

Operation completed successfully in 5.141 seconds.

[-] Post interrupted by the console user
[*] Post module execution completed
```

Of course, the post module wasn't interrupted by me. The meterpreter session is hanging, presumably while it parses the massive file....

```
meterpreter > channel -l

    Id  Class  Type
    --  -----  ----
    5   3      extapi_ntds

meterpreter > ps
[-] Error running command ps: Rex::TimeoutError Operation timed out.
```

If doing it on a remote server is too stressful for the machine, maybe it's better to pull the file down to the metasploit server and parse it...

**Comment by busterb** [comment]
CC @dmaloney-r7, what we probably need is a more realistic environment to test this against. Sounds like we're getting hung up on something specific to this DC.

**Comment by dmaloney-r7** [comment]
@dwendt What OS is the server? It shouldn't be pegging the CPU either. It does not parse the entire NTDS.dit file, that's the whole point of this system. It connects to the database using the JET Engine and pulls the hashes out in batches. This would be impossible to do on your local machine unless you happen to be running Metasploit on Windows for some reason. Downloading NTDS.dit and parsing it locally would require actually parsing the raw file, rather than connecting to it as a database as it's meant to. It is supposed to avoid the exact situation you're describing. We're definitely hitting some kind of performance issue, and i'm wondering if something is throwing the whole thing into a closed loop.

Any details you can provide would be helpful.

**Comment by dmaloney-r7** [comment]
well size has nothing to do with it afaict. I just dumped a domain with ~5k users in under 2 minutes

**Comment by dmaloney-r7** [comment]
well number of suers anyways, even with 5k users, it's still only about 27mb, but I don't think that's the right avenue since @Slurpgeit ran into this with only 200 suers so probably a pretty small database.

I've also checked to see if it had a problem when the samaccountname has a space in it...it worked fine

@Slurpgeit would this happen to be a Non english environment? wondering if it might be a unicode issue?

**Comment by dmaloney-r7** [comment]
tested with Arabic and Tamil characters in both the name and username fields and it still worked fine...

**Comment by dmaloney-r7** [comment]
![screen shot 2017-06-06 at 10 42 09 am](https://user-images.githubusercontent.com/1146440/26838219-218415b2-4aa5-11e7-893d-504683d3fb45.png)

In the above image we can see users with high ascii and some different unicode sets all working, even with crazy space arrangements

**Comment by fsacer** [comment]
@wvu-r7 as per low reproducability not sure if it's worth keeping the issue open
