### ISSUE TITLE
Make msfconsole a command inside of msfconsole

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#7330]
Many new users of metasploit have made the mistake of starting msfconsole inside of msfconsole and it would be nice if there was a warning instead of allowing it to get passed to the shell.

**Comment by wvu-r7** [comment]
@bpatterson-r7:

```export PATH+=:.``` will help you repro. Do this TEMPORARILY. Even though it's at the end, you really don't want ```.``` in ```$PATH```.

You'll want to look inside ```lib/msf/ui/console/driver.rb```, ```lib/msf/ui/console/command_dispatcher/core.rb```, and ```lib/rex/ui/text/dispatcher_shell.rb```, but only one file will need to be modified.

Cheers!
