### ISSUE TITLE
HVNC Module Request

### ISSUE THREAD

**Issue by zero77** [rapid7/metasploit-framework#7331]
Can you create a hidden vnc module for metasploit.

This blog post explains how it works and has some pos code: 
https://www.malwaretech.com/2015/09/hidden-vnc-for-beginners.html

Thanks

**Comment by wwebb-r7** [comment]
A hidden VNC module, while not technologically infeasible, would be ridiculous, akin to digging a tunnel with a ball peen hammer.  It would be better handled as a Meterpreter extension.  You can submit a pull request with some code here if you'd really like to see it https://github.com/rapid7/metasploit-payloads

Closing this and your other recent issue for the same reason
