### ISSUE TITLE
GPG error when updating, key expired

### ISSUE THREAD

**Issue by pr0letariat** [rapid7/metasploit-framework#7336]
## Steps to reproduce

`sudo apt-get update`

## Expected behavior

Metasploit updates.

## Current behavior

```
Err:13 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease
  The following signatures were invalid: KEYEXPIRED 1474234115  KEYEXPIRED 1474234115  KEYEXPIRED 1474234115
Fetched 98.2 kB in 0s (150 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease: The following signatures were invalid: KEYEXPIRED 1474234115  KEYEXPIRED 1474234115  KEYEXPIRED 1474234115
```

## System stuff

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -a
Linux me 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

### Metasploit version

```
msf > version
Framework: 4.12.26-dev-030e09c9c68b055309e170ec9551c4ee476ca221
Console  : 4.12.26-dev-030e09c9c68b055309e170ec9551c4ee476ca221
```

### Other information:

```
$ cat /etc/apt/sources.list.d/metasploit-framework.list
deb http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main

```

**Comment by nixawk** [comment]
@pr0letariat please try following commands:

```
$ sudo echo 'deb http://apt.metasploit.com/ lucid main' >> /etc/apt/sources.list.d/metasploit-framework.list
$ sudo wget -O - http://apt.metasploit.com/metasploit-framework.gpg.key | apt-key add -
$ sudo apt-get update
$ sudo apt-get -y install metasploit-framework
```

**Comment by pr0letariat** [comment]
@nixawk  That worked, thanks.

**Comment by wvu-r7** [comment]
@nixawk:

I think you meant to use ```sudo tee```, since ```sudo echo >``` doesn't elevate the redirection.

**Comment by wvu-r7** [comment]
@nixawk: I think you meant to use ```sudo tee```, since ```sudo echo >``` doesn't elevate the redirection.

**Comment by pbarry-r7** [comment]
And I believe the second step needs the **sudo** moved from the wget over "after the pipe" (preceding the apt-key command), like such:

`wget -O - http://apt.metasploit.com/metasploit-framework.gpg.key | sudo apt-key add -`

**Comment by pbarry-r7** [comment]
And thanks for hopping in on this one, @nixawk!!

**Comment by 78bash** [comment]
Hey, looks like this issue is back. After sudo apt update:
`Err:1 http://apt.metasploit.com lucid InRelease                                          
  The following signatures were invalid: EXPKEYSIG CDFB5FA52007B954 Metasploit <metasploit@rapid7.com>`
The previous solutions aren't working.

**Comment by Frisch12** [comment]
@78bash The APT-Key of msf expired. Use --allow-unauthenticated transitionally

**Comment by Matir** [comment]
Yep, key has expired again:

```pub   rsa4096 2012-12-06 [SC] [expired: 2019-09-02]
      09E55FAF4F7862CD6D558997CDFB5FA52007B954
uid           Metasploit <metasploit@rapid7.com>
sub   rsa4096 2012-12-06 [E] [expired: 2019-09-02]
```

**Comment by MCStreet** [comment]
Hi, yes, key has expired again:

pub   rsa4096 2012-12-06 [SC] [expired: 2019-09-02]
      09E5 5FAF 4F78 62CD 6D55  8997 CDFB 5FA5 2007 B954
uid           [ expired] Metasploit <metasploit@rapid7.com>


msf5 > version
Framework: 5.0.43-dev
Console  : 5.0.43-dev


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.3
Codename:	kali-rolling

**Comment by McTemplar** [comment]
This is the solution :

apt-key adv --keyserver keys.gnupg.net --recv-keys CDFB5FA52007B954

Good Game !! ;)

**Comment by itsecurityco** [comment]
> apt-key adv --keyserver keys.gnupg.net --recv-keys CDFB5FA52007B954

I got this error:
`~$ sudo apt-key adv --keyserver keys.gnupg.net --recv-keys CDFB5FA52007B954
Executing: /tmp/apt-key-gpghome.dQG4XRBlRw/gpg.1.sh --keyserver keys.gnupg.net --recv-keys CDFB5FA52007B954
gpg: keyserver receive failed: Server indicated a failure`

**Comment by itsecurityco** [comment]
> keyserver receive failed: Server indicated a failure

Solved adding _hkp_ to keyserver
`sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys CDFB5FA52007B954`

**Comment by CitizenFour90** [comment]
> > keyserver receive failed: Server indicated a failure
> 
> Solved adding _hkp_ to keyserver
> `sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys CDFB5FA52007B954`

Worked here!

**Comment by bi0sec** [comment]
> This is the solution :
> 
> apt-key adv --keyserver keys.gnupg.net --recv-keys CDFB5FA52007B954
> 
> Good Game !! ;)

this worked for me too

**Comment by anachnu** [comment]
My goodness that site https://www.fosslinux.com/19213/how-to-install-metasploit-on-ubuntu.htm was the only one to provide the solution ,so many bla bla bla talks all over the Net no solutions.

**Comment by Anonymus-M** [comment]
> @pr0letariat please try following commands:
> 
> ```
> $ sudo echo 'deb http://apt.metasploit.com/ lucid main' > /etc/apt/sources.list.d/metasploit-framework.list
> $ sudo wget -O - http://apt.metasploit.com/metasploit-framework.gpg.key | apt-key add -
> $ sudo apt-get update
> $ sudo apt-get -y install metasploit-framework
> ```

THANKS YOU!!!

**Comment by aryanguenthner** [comment]
# Tested on Kali 2022.1

wget http://apt.metasploit.com/metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --import metasploit-framework.gpg.key
gpg --no-default-keyring --keyring ./metasploit-framework_keyring.gpg --export > ./metasploit-framework.gpg
sudo mv ./metasploit-framework.gpg /etc/apt/trusted.gpg.d/
apt update

**Comment by aryanguenthner** [comment]
If all else fails this should do the job. 
mv /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/

**Comment by noraj** [comment]
# 2026

Any `apt-key` was not working for me. What worked is using gpg directly.

```sh
sudo gpg --keyserver keyserver.ubuntu.com --recv-keys C048F0B49DEEC457
sudo gpg --export C048F0B49DEEC457 | sudo tee /usr/share/keyrings/metasploit-framework.gpg > /dev/null
```
