### ISSUE TITLE
msfvenom using the x86/nonupper encoder appears to be busted

### ISSUE THREAD

**Issue by pbarry-r7** [rapid7/metasploit-framework#7337]
## Steps to reproduce

How'd you do it?
1. try to create an encoded payload (e.g. `./msfvenom -p windows/meterpreter/bind_tcp -e x86/nonupper -f c`)
2. hit the following error:

```
$ ./msfvenom -p windows/meterpreter/bind_tcp -e x86/nonupper -f c
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/nonupper
x86/nonupper failed with Encoding failed due to a nil character
Error: An encoding exception occurred.
```
## Expected behavior

Expected an unsigned char array containing the encoded payload.
## Current behavior

The above error.
### Metasploit version

ec63f8feaf3bf88ace248feb732de44cea795788 Land #7113, check fix for drupal_restws_exec
### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (ruby 2.3.1p112)
### OS

Ubuntu 16.04 (64-bit)

**Comment by wvu-r7** [comment]
Confirmed on OS X.

**Comment by bwatters-r7** [comment]
Did this ever work?  I pulled a few old releases of Framework, and it behaves the same in all.  Oldest was Sept 2015.  If this was a regression, it has been around a while.

**Comment by pbarry-r7** [comment]
Good question, @bwatters-r7.  I hit this while we were working on some Rex breakup, @dmaloney-r7 could probably say (certainly it sounded like it's expected to work)...

**Comment by bwatters-r7** [comment]
@dmaloney-r7 ?

**Comment by dmaloney-r7** [comment]
I don't know when this actually stopped working but it was broken before we did the Rex Breakup. It looks like it has been busted for a long time

**Comment by thesp0nge** [comment]
Guys any news on this?

**Comment by wvu-r7** [comment]
I don't think anyone has looked at this since 2016.

**Comment by egypt** [comment]
I don't think I've ever had need of this encoder. I can't say for certain that nothing uses it but, since it's been broken since at least 2016, I'm guessing nothing uses it.
