### ISSUE TITLE
OptEnum wiki example wrong

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#7354]
https://github.com/rapid7/metasploit-framework/wiki/How-to-use-datastore-options
The example shows:
`OptEnum.new('FRUIT', [ true, 'Set a fruit', ['apple', 'orange'], 'apple' ])`
however, the array and the default value are mixed up in order, it should be:
`OptEnum.new('FRUIT', [ true, 'Set a fruit', 'apple', ['apple', 'orange']])`

As can be seen on: https://github.com/rapid7/metasploit-framework/blob/adb275520b9552d6760eae50d0cd8074976d215b/modules/post/windows/manage/driver_loader.rb#L51

**Comment by bcook-r7** [comment]
Fixed, thanks.

**Comment by void-in** [comment]
@bcook-r7 Please update another section as well. Although it is a little typo, it is confusing on first read. Currently the document is reading:
```
However, like we said earlier, if the user sets a model-level option, no other components will see it...
```
It should be:
However, like we said earlier, if the user sets a **module-level** option, no other components will see it...

**Comment by busterb** [comment]
Roger, updated.
