### ISSUE TITLE
Error in metasploit  - Help me please

### ISSUE THREAD

**Issue by netdestroyer** [rapid7/metasploit-framework#7358]
hi guys , i have KALI Rolling 2.0 
when prompt in terminal :  
[root:~]# msfconsole
Please run msfdb as a non-root user
/usr/bin/msfconsole: 106: [: /opt/metasploit-framework/bin/../embedded/framework/msfconsole: unexpected operator
/opt/metasploit-framework/bin/../embedded/bin/ruby: No such file or directory -- /opt/metasploit-framework/bin/../embedded/bin/msfconsole (LoadError)

help me please :*

**Comment by bcook-r7** [comment]
KALI Rolling 2.0..... are you sure? I don't think you can have both 'Rolling' and '2.0'

Can you give a little more detail about what you did before this?

**Comment by h00die** [comment]
[2016.2 rolling](https://www.kali.org/news/kali-linux-20162-release/)
Anyways, try an `apt-get update` `apt-get upgrade`, maybe a new package will fix it. mine loads fine and im on 2016.2 and just updated within the last 5min

**Comment by netdestroyer** [comment]
i try apt-get update apt-get dist-upgrade but i have a same errors

**Comment by nixawk** [comment]
@netdestroyer Please redirect to [GPG error when updating, key expire](https://github.com/rapid7/metasploit-framework/issues/7336)

**Comment by netdestroyer** [comment]
thanks @nixawk 
now i have another error like this 

[root:~]# msfconsole
Please run msfdb as a non-root user
/opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in `require': cannot load such file -- rbconfig (LoadError)
	from /opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

**Comment by bcook-r7** [comment]
Ah, so if you're running on Kali, please stick to Kali's packaging. Please perform the following commands to restore the Kali-specific package on your installation.

```
rm /etc/apt/sources.list.d/metasploit-framework.list
apt-get update
apt-get install --reinstall metasploit-framework
```

**Comment by bcook-r7** [comment]
As you can see from the error above, it is saying not to run msfdb as root, but the '[root:~]#' prompt indicates that you are running the command as root anyway.

If you switch to Kali's package instead, it is designed to use the system installation of postgresql, and its copy of msfdb expects to be run as root like other Kali Linux tools.

**Comment by bcook-r7** [comment]
If someone wants to submit a PR to make the omnibus package work with a root user, the repo and script are here: https://github.com/rapid7/metasploit-omnibus/blob/master/config/templates/metasploit-framework/msfdb.erb

It's designed to work this way because postgresql itself refuses to run as root, and the omnibus package doesn't add any users to the system, since this might step on other packages, since the omnibus packages are distribution-agnostic.
