### ISSUE TITLE
registry_persistence module unicode bug

### ISSUE THREAD

**Issue by Slurpgeit** [rapid7/metasploit-framework#7373]
The registry_persistence module doesn't work currently due to a unicode bug. In short, meterpreter writes to the registry using the wrong encoding. For more details and a possible work-around, please refer to: https://diablohorn.com/2016/09/27/meterpreter-registry-unicode-quirk-work-around/

**Comment by OJ** [comment]
This is already being tracked in the Payloads repo. Thanks @Slurpgeit . https://github.com/rapid7/metasploit-payloads/issues/127
