### ISSUE TITLE
Failure to upload

### ISSUE THREAD

**Issue by kevinclaassens** [rapid7/metasploit-framework#7426]
I am using Kali Linux 2.0 with virtualbox.
I am doing some tests and I am able to gain a meterpreter session on the device. I then dropped into shell to try and upload a file. I am unable to upload a file using the upload command. Ex I used it like this 'upload file.jpg' keeping in mind that the file.jpg is on my desktop. I then tried it like this 'upload root/Desktop/file.jpg' with both of those commands saying "sh: <stdin>[8]: upload: not found". Would you please be able to assist me?

**Comment by bcook-r7** [comment]
You cannot upload files from a shell session. please background the shell and upload from the meterpreter prompt instead.

Also, please ask questions about metasploit usage on community.rapid7.com, not the github project.
