### ISSUE TITLE
auxiliary/scanner/redis/file_upload

### ISSUE THREAD

**Issue by xl7dev** [rapid7/metasploit-framework#7463]
msf auxiliary(file_upload) > run

[_] Scanned  33 of 256 hosts (12% complete)
[_] Scanned  56 of 256 hosts (21% complete)
[_] Scanned  86 of 256 hosts (33% complete)
[_] Scanned 106 of 256 hosts (41% complete)
[_] Scanned 128 of 256 hosts (50% complete)
[+] 10.11.102.134:6379    - 10.11.102.134:6379    -- saved 402 bytes inside of redis DB at /root/.ssh/authorized_keys
[-] Auxiliary failed: NoMethodError undefined method `split' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/redis/file_upload.rb:58:in`send_file'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/redis/file_upload.rb:164:in `run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:135:in`block (2 levels) in run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:100:in`block in spawn'
[_] Auxiliary module execution completed

**Comment by xl7dev** [comment]
@dmohanty-r7 
> cat foo.txt|redis-cli -h 10.11.102.163 -x set foo
(error) READONLY You can't write against a read only slave

I have solved it in other ways.
Slave-read-only=1, default slave-read-only=0

**Comment by wchen-r7** [comment]
@dmohanty-r7 Do you mind testing this patch? https://github.com/rapid7/metasploit-framework/pull/7592

The way I see it, the problem is really because the module isn't using ```redis_command``` correctly. I also fixed other things that could potential break the sam way.

**Comment by dmohanty-r7** [comment]
sure thing @wchen-r7
