### ISSUE TITLE
Meterpreter x64 crashes whether injected into process or manually ran by the user in metasploit framework

### ISSUE THREAD

**Issue by Spyro289** [rapid7/metasploit-framework#7474]
I was compromised a windows 7 machine but realised that I could not escalate myself to system level
because all the process had an x64 architecture ,with the process list opened in armitage I attempted to inject a "a x64 version of the reverse_tcp Meterpreter" into explorer.exe which had an x64 architecture
but explorer.exe crashed realising this I manually dropped the payload onto the virtual machine and manually executed it but it gave me the following error in METERPRETER CRASH.PNG this issue arises in 
metasploit v4.12.34-dev and updated via apt in Kali linux 2016.2

1. generate a "payload/windows/x64/meterpreter/reverse_tcp"
2. Run the payload on a windows 7 machine with firewall disabled
3. it should give you the same Error in METERPRETER CRASH.PNG

image here:
https://cloud.githubusercontent.com/assets/20989997/19618518/2bf6007e-9898-11e6-9981-b9760c28dcb3.PNG

Also this is Problem signature form the PNG
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	PAYLOAD.exe
  Application Version:	0.0.0.0
  Application Timestamp:	4bc63c7d
  Fault Module Name:	PAYLOAD.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	4bc63c7d
  Exception Code:	c0000005
  Exception Offset:	0000000000004013
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	3081
  Additional Information 1:	f520
  Additional Information 2:	f520678ee6c181a908e465faa6ababb8
  Additional Information 3:	f559
  Additional Information 4:	f5598e60d0be42508aa1542d06ad89a7

**Comment by OJ** [comment]
My money is on at least one of the following:

* Injecting into an x64 process when running as an x86.
* Launching x64 payloads that connect back to an x86 handler.

If you're doing either of the above, it'll crash.

For future reference, please use the [Rapid7 community](https://community.rapid7.com/) when you are having issues using the software. Github issues are intended for bug reports only. Thanks.
