### ISSUE TITLE
Updating Latest Mimikatz Support

### ISSUE THREAD

**Issue by c0d3xpl0it** [rapid7/metasploit-framework#7494]
Hello,

Is there a roadmap for upgrading the Mimikatz to latest version by @gentilkiwi which supports Windows 10 Anniversary update & Windows Server 2016 (1607 - build 14393) ?

**Comment by OJ** [comment]
We're actively working on this at the moment (and this issue is a duplicate of a few others, so I'm going to close this one). Thanks.
