### ISSUE TITLE
Cannot override payload in shell_to_meterpreter.rb 

### ISSUE THREAD

**Issue by truekonrads** [rapid7/metasploit-framework#7504]
The shell_to_meterpreter.rb  has a two bugs:
1) There is a typo on line 119:
It says: 

``` ruby
    payload_name = datastore['PAYLOAD_OVERWRITE'] if datastore['PAYLOAD_OVERWRITE']
```

When it should say:

``` ruby
    payload_name = datastore['PAYLOAD_OVERRIDE] if datastore['PAYLOAD_OVERRIDE']
```

as On 41-42 it says:

``` ruby
      OptString.new('PAYLOAD_OVERRIDE',
        [false, 'Define the payload to use (meterpreter/reverse_tcp by default) .', nil]),
```

Second, when that's "fixed", upgrade of x64 psh shell to a x64 meterpreter doesn't work (x64 psh to x86 meterpreter works tho),  I can't repro that bug on that environment as I don't have access to the target anymore.

**Comment by wvu-r7** [comment]
Feel free to submit a patch!
