### ISSUE TITLE
Meterpreter https not handling requests after some time

### ISSUE THREAD

**Issue by valerianrossigneux** [rapid7/metasploit-framework#7513]
Hi, I'm running a reverse_https meterpreter on a server and I have clients successfully connecting to it, I can see the sessions being created etc. 

I have observed that *after some time*, if I run the client again, I don't see anything on the server, the request is not handled. If I restart the handler then it works again.

I'm wondering what would be the cause of that, any idea ? The only thing I saw in the logs is that the meterpreter handler is hit from time to time by some robots on port 443 resulting into some "Unknown request to ...", but I don't think it could be the root cause.

P.S: another weird thing I have observed is that the handler has the commmand set_timeouts -x 3600, but all my sessions as always listed with "sessions", I never see them "killed".

**Comment by mubix** [comment]
cc: #7101 I've observed the same issue recently, no indication at all on the handler side that anything has gone wrong

**Comment by mubix** [comment]
Being tracked in #7101
