### ISSUE TITLE
WARNING! The following modules could not be loaded! (phoenix_command.rb)

### ISSUE THREAD

**Issue by 404Ghost99** [rapid7/metasploit-framework#7539]
i'm pulling metasploit from github # git pull and i'm running msfupdate command, than i'm running metasploit console but i've got this error like in the screenshot...

please fixed the script **phoenix_command.rb:218** thanks :)

![screenshot from 2016-11-07 11-23-14](https://cloud.githubusercontent.com/assets/8980647/20046844/ec579248-a4e0-11e6-8f79-19895f0b2ef6.png)

**Comment by wvu-r7** [comment]
Crap. They forgot a ```?```. Missed this in review. Thanks for the catch!

**Comment by wvu-r7** [comment]
Broken in #7537. Fixed in https://github.com/rapid7/metasploit-framework/commit/4eb42a91715a737bc7a6e73bd0611edd8ee5efed.

**Comment by 404Ghost99** [comment]
:dancing_men:
