### ISSUE TITLE
set_timeouts -x 3600 is not honored and has no effect

### ISSUE THREAD

**Issue by valerianrossigneux** [rapid7/metasploit-framework#7598]
## Steps to reproduce

metasploit v4.13.0

Changing the timeout has no effect on the session. after a successful meterpreter connection I ran a set_timeouts -x 3600 as shown below:

```
[*] https://X.X.X.X:443 handling request from X.X.X.X; (UUID: x2ximptq) Staging Native payload...
[*] Meterpreter session 1 opened (X.X.X.X:443 -> X.X.X.X:8881) at 2016-11-22 13:20:21 +0800
[*] Session ID 1 (X.X.X.X:443 -> X.X.X.X:8881) processing AutoRunScript 'multi_console_command -rc /root/attack_tools/auto.rc'
[*] Running Command List ...
[*]     Running command upload /root/attack_tools/install.bat C:\\windows\\addins\\install.bat
[*] uploading  : /root/attack_tools/install.bat -> C:\windows\addins\install.bat
[*] uploaded   : /root/attack_tools/install.bat -> C:\windows\addins\install.bat
[*]     Running command execute -f "C:\\windows\\addins\\install.bat" -H
Process 756 created.
[*]     Running command set_timeouts -x 3600
Session Expiry  : @ 2016-11-22 14:20:34
Comm Timeout    : 300 seconds
Retry Total Time: 3600 seconds
Retry Wait Time : 10 seconds
```

But this session never expires, it will still show under sessions days after without activity.

## Expected behavior

Session should expire accordingly.

## Current behavior

Session never expire

**Comment by busterb** [comment]
The session expiration is handled on the meterpreter side, framework just tells the meterpreter what to do. For us to help, we'd first need to know which meterpreter you were running.

**Comment by OJ** [comment]
```
handling request from X.X.X.X; (UUID: x2ximptq) Staging Native payload...
```
It's a Windows payload for sure.

**Comment by OJ** [comment]
OK so I think it's important to note that session expiry isn't detected on the MSF side with HTTP/S payloads. If you check for comms, you'll see that Meterp will definitely shut itself down. However, MSF isn't aware that the session isn't calling back any more. Instead, you'll notice that when you run `sessions -x` the last checkin time for the session will be REALLY long.

So in short, Meterp is shutting down. MSF doesn't know that the session is dead. This is a side-effect of the transport.

**Comment by valerianrossigneux** [comment]
Understood.

**Comment by OJ** [comment]
Cool thanks :) If you try it with `reverse_tcp` you'll see it actually terminate on the MSF side too.

**Comment by busterb** [comment]
I would have thought the keep-alive function would have noticed, regardless of the transport.
