### ISSUE TITLE
Linking Metasploit installation folder

### ISSUE THREAD

**Issue by kbeflo** [rapid7/metasploit-framework#7618]
Cloned metasploit-framework from `rapid7/metasploit-framework` to `/opt/` after that I did  `bundle install`.

After installation I linked metasploit-framework to `/usr/local/bin/`

    sudo bash -c 'for MSF in $(ls msf*); do ln -s /opt/metasploit-framework/$MSF /usr/local/bin/$MSF;done'`

Will there be any issue/disadvantage if I linked `metasploit-framework` instead of installing it into `bin`?

**Comment by kbeflo** [comment]
github pls

**Comment by busterb** [comment]
Are you trying to delete evidence of this issue existing?
