### ISSUE TITLE
Msfvenom apk

### ISSUE THREAD

**Issue by raaafaaaaaaa** [rapid7/metasploit-framework#7620]
I need help, how can i make a automatically hiding apk in msfvenom without having to open a meterpreter session, the app automatically hides after installing it, like before.

I'm on Kali Linux/Parrot OS with metasploit framework console v4.13.0-dev.

**Comment by timwr** [comment]
@raaafaaaaaaa unfortunately we removed the automatic hiding of the icon because it was confusing to people. We've added a hide_app_icon command to do it manually. If you wish to automatically have it run you can do the following before starting your handler:
```
echo "hide_app_icon" > hide.rc
set AutoRunScript multi_console_command -rc hide.rc
```

**Comment by raaafaaaaaaa** [comment]
Ok thanks ;)
