### ISSUE TITLE
"auxiliary/scanner/http/cisco_ssl_vpn" fails even if server is responsive

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7640]
## Steps to reproduce

How'd you do it?

1. `run auxiliary/scanner/http/cisco_ssl_vpn`
2. `set RHOST 127.0.0.1`
3. `run`

```
msf auxiliary(cisco_ssl_vpn) > run

[+] Server is responsive...
[-] Connection failed, Aborting...
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

## Expected behavior
The module should continue but it aborted.

### Metasploit version
msf auxiliary(cisco_ssl_vpn) > version
Framework: 4.13.3-dev-b6bb199
Console  : 4.13.3-dev-b6bb199

### OS

Ubuntu 14.04

**Comment by jinq102030** [comment]
Should be fixed by PR #7641

**Comment by wvu-r7** [comment]
@jinq102030: For your next PR: https://github.com/blog/1506-closing-issues-via-pull-requests. :)

**Comment by jinq102030** [comment]
That's nice tip! Thanks @wvu-r7
