### ISSUE TITLE
Feature Request: Add a sort option to the services command

### ISSUE THREAD

**Issue by jnqpblc** [rapid7/metasploit-framework#7642]
It would be extremely stellar if someone would add a sort option to MSF's internal services command.

Example (Order by column): 
msf >  services -O 2

**Comment by wvu-r7** [comment]
Any other commands?

**Comment by jnqpblc** [comment]
Not that I can think of at the moment.

**Comment by wvu-r7** [comment]
There is a ```grep``` command.

**Comment by jnqpblc** [comment]
Look at that, there sure is a grep command... now only if there was a sort command... :D

**Comment by wvu-r7** [comment]
Ah, misread you, lol. You meant a ```sort``` command *like* the ```grep``` command. Got it.

**Comment by jnqpblc** [comment]
The only feature I am asking for is a sort option within the services command, but will leave the implementation up to someone smarter as to what is a better; a global sort command or just a services sort option. Thanks!

**Comment by wvu-r7** [comment]
I'm pretty familiar with the code in question, so I'll grab this. No guarantees. ;)

**Comment by wvu-r7** [comment]
@jnqpblc: Please let me know if https://github.com/wvu-r7/metasploit-framework/tree/feature/sort suits your fancy.

**Comment by jnqpblc** [comment]
You, sir, are badass. It works perfectly. Thank you.
