### ISSUE TITLE
Module scanner/http/etherpad_duo_login gives stack trace if HTTP server response doesn't have Server header

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7650]
## Steps to reproduce

How'd you do it?

1. `run scanner/http/etherpad_duo_login`
2. `set RHOSTS 127.0.0.1`
3. `set USERPASS_FILE userpass.lst`
4. `run`

```
msf auxiliary(etherpad_duo_login) > run

[-] Auxiliary failed: NoMethodError undefined method `include?' for nil:NilClass
[-] Call stack:
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/etherpad_duo_login.rb:61:in `is_app_epaduo?'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/etherpad_duo_login.rb:32:in `run_host'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version
msf auxiliary(etherpad_duo_login) > version
Framework: 4.13.3-dev-b6bb199
Console  : 4.13.3-dev-b6bb199

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### OS

Ubuntu 14.04.05

**Comment by jinq102030** [comment]
Hi @wvu-r7 , I meant to say making the change according to what YOU has suggested but I put it down as Wei.  Sorry. Thanks for the comment.

**Comment by wvu-r7** [comment]
Hahaha. :)
