### ISSUE TITLE
if you call msfrpc methods with incorrect arguments (e.g. string instead of hash), the resulting backtrace does not help diagnose the problem 

### ISSUE THREAD

**Issue by aoighost** [rapid7/metasploit-framework#7684]
## Steps to reproduce

How'd you do it?

Try to call db.hosts from rpc. Note this appears to be a problem rife in the code related to db and rpc.

## Expected behavior

It should return a list of hosts.

## Current behavior

Upon trying to gather a list of hosts or other things in the database, an error like this occurs:
https://i.imgur.com/GP4cr0S.png

### Metasploit version

Framework: 4.12.23-dev
Console  : 4.12.23-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali

**Comment by bcook-r7** [comment]
Hi, got a way to reproduce with msfrpc ? Here's a sample run that seems to work:
```
$ ./msfrpc -S -P blah -a 127.0.0.1
[*] The 'rpc' object holds the RPC client interface
[*] Use rpc.call('group.command') to make RPC calls

>> rpc.call('console.create')
=> {"id"=>"1", "prompt"=>"msf > ", "busy"=>false}
>> rpc.call('db.hosts', {workspace: "default"})
=> {"hosts"=>[{"created_at"=>1479421794, "address"=>"127.0.0.1",
```

Are you passing db.hosts a hash with workspace: specified as a key? It seems that if you're not exact about passing it the right argument type, it doesn't handle argument parsing very well. I don't think this has anything to do with obsolete ruby methods.

**Comment by aoighost** [comment]
I'll do more experimentation, I'm using a derivative of https://github.com/VolatileMindsLLC/metasploit-sharp and trying to get it working and expanded for use in a tool I'm working on, let me take a further look.

**Comment by aoighost** [comment]
This is my current C# code:
```
 public Dictionary<object, object> ListHosts(string workspacename)
        {
            return _session.Execute("db.hosts", workspacename);
        }


```

**Comment by aoighost** [comment]
Here is my current call code:

```
 void listHosts()
            {

            Dictionary<object, object> response = db.ListHosts(msfWorkspace);
            Debug.Log("Host List:");
            Debug.Log(response);
            foreach (KeyValuePair<object, object> pair in response)
                Debug.Log(pair.Key + ": " + pair.Value);

            Debug.Log("hosts listed...");
                host_CreatedAt = response["created_at"] as string;
                host_Address = response["address"] as string;
                host_Mac = response["mac"] as string;
                host_Name = response["name"] as string;
                host_State = response["state"] as string;
                host_OSName = response["os_name"] as string;
                host_OSFlavor = response["os_flavor"] as string;
                host_OS_SP = response["os_sp"] as string;
                host_OS_Lang = response["os_lang"] as string;
                host_updatedAt = response["updated_at"] as string;
                host_purpose = response["purpose"] as string;
                host_info = response["info"] as string;
                Debug.Log("host_CreatedAt: " + host_CreatedAt);
                Debug.Log("host_Address: " + host_Address);
                Debug.Log("host_Mac: " + host_Mac);
                Debug.Log("host_Name: " + host_Name);
                Debug.Log("host_State: " + host_State);
                Debug.Log("host_OSName: " + host_OSName);
                Debug.Log("host_OSFlavor: " + host_OSFlavor);
                Debug.Log("host_OS_SP: " + host_OS_SP);
                Debug.Log("host_OS_Lang: " + host_OS_Lang);
                Debug.Log("host_updatedAt: " + host_updatedAt);
                Debug.Log("host_purpose: " + host_purpose);
                Debug.Log("host_info: " + host_info);
        }
```

**Comment by aoighost** [comment]
I've confirmed it is tossing a workspace value of "default" to the variable, I'm not sure why it's breaking.

**Comment by bcook-r7** [comment]
I think you're calling the RPC API incorrectly though. The argument to db.hosts is not a string, it's a dictionary like this: {"workspace": "default"}. This has nothing to do with metasploit calling incorrect ruby methods I believe.

**Comment by bcook-r7** [comment]
I can get the same error from msfrpc if I call the method like this:

rpc.call('db.hosts', "default")

rather than like this:

rpc.call('db.hosts', {workspace: "default"})

**Comment by aoighost** [comment]
That fixed it, thanks @bcook-r7. For the sake of preserving my philosophy of code sharing, I'll attach working C# code for metasploit-sharp and Unity3D in the hopes others can learn from my derpery.

`    public Dictionary<string, object> ListHosts(string workspacename)
    {
        Debug.Log("listing hosts under workspace name: " + workspacename as string);

        return _session.Execute("db.hosts", workspacename);
    }
`

`void listHosts()
        {
            Debug.Log("Host List workspace: " + msfWorkspace);
            workspaceDict["workspace"] = msfWorkspace;
            Dictionary<string, object> hostList = db.ListHosts(workspaceDict);
            Debug.Log("listing hosts under workspace name: " + msfWorkspace as string);
            Debug.Log("Host List:");
            Debug.Log("Response = " + hostList);

            foreach (var host in hostList as IDictionary<string, object>)
                foreach (KeyValuePair<string, object> pair in hostList)
                {
                    int deviceNumber = 0;

                    foreach (var obj in host.Value as IList<object>)
                    {
                        deviceNumber = deviceNumber + 1;
                        Debug.Log("devicenumber: " + deviceNumber);

                        if (obj is IDictionary<string, object>)
                        {
                            foreach (var p in obj as IDictionary<string, object>)
                            {
                                Debug.Log(p.Key + ": " + p.Value);
                                switch (p.Key)
                                {
                                    case "created_at":
                                        host_CreatedAt = p.Value as string;
                                        Debug.Log("host_CreatedAt : " + host_CreatedAt);
                                        break;
                                    case "address":
                                        host_Address = p.Value as string;
                                        Debug.Log("host_Address : " + host_Address);
                                        break;
                                    case "mac":
                                        host_CreatedAt = p.Value as string;
                                        Debug.Log("host_Mac : " + host_Mac);
                                        break;
                                    case "name":
                                        host_Name = p.Value as string;
                                        Debug.Log("host_Name : " + host_Name);
                                        break;
                                    case "state":
                                        host_State = p.Value as string;
                                        Debug.Log("host_State : " + host_State);
                                        break;
                                    case "os_name":
                                        host_OSName = p.Value as string;
                                        Debug.Log("host_OSName : " + host_OSName);
                                        break;
                                    case "os_flavor":
                                        host_OSFlavor = p.Value as string;
                                        Debug.Log("host_OSFlavor : " + host_OSFlavor);
                                        break;
                                    case "os_sp":
                                        host_OS_SP = p.Value as string;
                                        Debug.Log("host_OS_SP : " + host_OS_SP);
                                        break;
                                    case "os_lang":
                                        host_OS_Lang = p.Value as string;
                                        Debug.Log("host_OS_Lang : " + host_OS_Lang);
                                        break;
                                    case "updated_at":
                                        host_updatedAt = p.Value as string;
                                        Debug.Log("host_updatedAt : " + host_updatedAt);
                                        break;
                                    case "purpose":
                                        host_purpose = p.Value as string;
                                        Debug.Log("host_purpose : " + host_purpose);
                                        break;
                                    case "info":
                                        host_info = p.Value as string;
                                        Debug.Log("host_info : " + host_info);
                                        break;
                                }
                            }
                            hm = new HostManager();
                            hm.addDevice(host_CreatedAt, host_Address, host_Mac, host_Name, host_State, host_OSName, host_OSFlavor, host_OS_SP, host_OS_Lang, host_updatedAt, host_purpose, host_info);
                        }
                        else
                            Debug.Log(obj);
                    }
                }
            Debug.Log("hosts listed...");
        }
`

**Comment by busterb** [comment]
Thanks!

**Comment by smarttang** [comment]
`root@7081ed90ad2b:/tmp/data# /usr/bin/msfrpc -P msf -n -f -a 0.0.0.0 -p 9881
[*] The 'rpc' object holds the RPC client interface
[*] Use rpc.call('group.command') to make RPC calls

>> rpc.call('db.hosts',{})
Traceback (most recent call last):
        7: from /opt/metasploit-framework/bin/../embedded/framework/msfrpc:92:in `<main>'
        6: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
        5: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
        4: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
        3: from (irb):1:in `<main>'
        2: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:105:in `call'
        1: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:158:in `send_rpc_request'
Msf::RPC::ServerException (ActiveRecord::ConnectionNotEstablished ActiveRecord::ConnectionNotEstablished ["lib/active_record/connection_handling.rb:109:in `connection_pool'", "lib/msf/core/rpc/v10/rpc_db.rb:319:in `rpc_hosts'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.5.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])
>> rpc.call('db.connect')
Traceback (most recent call last):
        7: from /opt/metasploit-framework/bin/../embedded/framework/msfrpc:92:in `<main>'
        6: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
        5: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
        4: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
        3: from (irb):2:in `<main>'
        2: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:105:in `call'
        1: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:158:in `send_rpc_request'
Msf::RPC::ServerException (ArgumentError wrong number of arguments (given 0, expected 1) ["lib/msf/core/rpc/v10/rpc_db.rb:1816:in `rpc_connect'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.5.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])
>> rpc.call('console.create')
=> {"id"=>"9", "prompt"=>"", "busy"=>false}
>> rpc.call('db.hosts', {workspace: "default"})
Traceback (most recent call last):
        7: from /opt/metasploit-framework/bin/../embedded/framework/msfrpc:92:in `<main>'
        6: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
        5: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
        4: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
        3: from (irb):4:in `<main>'
        2: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:105:in `call'
        1: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:158:in `send_rpc_request'
Msf::RPC::ServerException (ActiveRecord::ConnectionNotEstablished ActiveRecord::ConnectionNotEstablished ["lib/active_record/connection_handling.rb:109:in `connection_pool'", "lib/msf/core/rpc/v10/rpc_db.rb:319:in `rpc_hosts'", "lib/msf/core/rpc/v10/service.rb:153:in `block in process'", "lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'", "lib/ruby/2.5.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:33:in `catch'", "lib/ruby/2.5.0/timeout.rb:108:in `timeout'", "lib/msf/core/rpc/v10/service.rb:153:in `process'", "lib/msf/core/rpc/v10/service.rb:91:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:197:in `each'", "lib/rex/io/stream_server.rb:197:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:106:in `block in spawn'"])`

**Comment by smarttang** [comment]
hello, i can't get db.hosts info??
in v5.10...

**Comment by smarttang** [comment]
![image](https://user-images.githubusercontent.com/4961402/54070955-9e07f400-42a1-11e9-89f7-fccca7d08a01.png)
