### ISSUE TITLE
Silent exit when running module error_sql_injection

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7691]
## Steps to reproduce

1. `use auxiliary/scanner/http/error_sql_injection`
2. `set RHOSTS 127.0.0.1`
3. `run`

Silent exit, no traffic sent.

## Expected behavior

Should give an error message if user didn't config a necessary parameter.  This is especially bad when `show missing` shows there is nothing missing.

**Comment by wvu-r7** [comment]
Fixed in #7692.
