### ISSUE TITLE
Metaspoilt apk

### ISSUE THREAD

**Issue by MrMalfunction** [rapid7/metasploit-framework#7700]
I am a Rookie at Kali.
Well I used the steps here http://null-byte.wonderhowto.com/how-to/hack-android-using-kali-updated-and-faq-0164704.
But the app gets installed on the phone but it does not work in the background.
I used Metaspoilt in Kali(live boot).
The phone and my computer are connected on the same network.
Please help.

**Comment by bcook-r7** [comment]
Sorry, github is not the place to ask for support. Try community.rapid7.com
