### ISSUE TITLE
macbook install metasploit-framework, but exec msfconsole fail.

### ISSUE THREAD

**Issue by yywf** [rapid7/metasploit-framework#7705]
please help me.   my steps:
1. git clone 'this branch‘ 
2. ./msfupdate and install packages from error information
3. ./msfconsole  error as follows

➜  metasploit-framework git:(master) ✗ msfconsole
/usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:16:in `require': incompatible library version - /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt_ext.bundle (fatal)
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:16:in `rescue in <top (required)>'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/lib/bcrypt.rb:12:in `<top (required)>'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `require'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /usr/local/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from /usr/local/bin/msfconsole:48:in `<main>'
➜  metasploit-framework git:(master) ✗

**Comment by void-in** [comment]
Download the appropriate installer from https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers. If you encounter any problem during the installation, please use https://community.rapid7.com as this place is to report bugs and feature requests, not support queries. Thanks
