### ISSUE TITLE
macbook install metasploit-framework use  OS X quick installation , but exec msfconsole fail.

### ISSUE THREAD

**Issue by yywf** [rapid7/metasploit-framework#7708]
yesterday I use void-in 's method to install metasploit , link is 'https://github.com/rapid7/metasploit-framework/issues/7705'. and follow link is 'https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers'

details steps is.   
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

but still error as follow , I know nothing about ruby and gem, it make me headache。。。。 please help me again ， thanks。

 

  metasploit-framework ls
LICENSE               LICENSES              bin                   embedded              version-manifest.json version-manifest.txt
➜  metasploit-framework cd bin 
➜  bin ls
msfbinscan  msfconsole  msfd        msfdb       msfelfscan  msfmachscan msfpescan   msfremove   msfrop      msfrpc      msfrpcd     msfupdate   msfvenom
➜  bin msfconsole 
Your bundle is locked to rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (12.0.0) has removed it. You'll need to update your bundle to a different version of rake (12.0.0) that hasn't been removed in order to install.
Run `bundle install` to install missing gems.
➜  bin sudo bundle install
Password:
/Users/adhan/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'bundler' (>= 0) among 13 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/adhan/.gem/ruby/2.1.0:/Users/adhan/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0', execute `gem env` for more information
	from /Users/adhan/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:320:in `to_spec'
	from /Users/adhan/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Users/adhan/.rvm/gems/ruby-2.1.5/bin/bundle:22:in `<main>'
	from /Users/adhan/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/adhan/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
➜  bin 
➜  bin

**Comment by thecarterb** [comment]
As the error code says: `Could not find 'bundler'`

You need to install the `bundler` gem by running the following command: `gem install bundler`, then run `bundle install`

**Comment by bcook-r7** [comment]
It should not be required to install any gems with this method!

It looks like you are not actually running the binaries that come with the package. Try typing 'which msfconsole' and could you show what the output is?

**Comment by bcook-r7** [comment]
I suspect you have actually installed metasploit multiple times in multiple places, and this error is not coming from the omnibus package, but some other installation. Please try running msfconsole like this instead:

/opt/metasploit-framework/bin/msfconsole

**Comment by bcook-r7** [comment]
If you have any further issues, please see community.rapid7.com

**Comment by yywf** [comment]
thanks for you help. @all . I am working now . and I will do as you say when i go home.

**Comment by yywf** [comment]
I remove all installation, and use OS X graphical installation. and info as follow



➜  bin ls
msfbinscan  msfdb       msfpescan   msfrpc      msfvenom
msfconsole  msfelfscan  msfremove   msfrpcd
msfd        msfmachscan msfrop      msfupdate
➜  bin which is msfconsole
is not found
msfconsole not found
➜  bin ./msfconsole
Could not find rake-12.0.0 in any of the sources
Run `bundle install` to install missing gems.
➜  bin sudo bundle install
Password:
Don't run Bundler as root. Bundler can ask for sudo if it is needed,
and installing your bundle as root will break this application for
all non-root users on this machine.
Could not locate Gemfile
➜  bin  bundle install
There was an error while trying to write to
`/opt/metasploit-framework/bin/.bundle/config`. It is likely that
you need to grant write permissions for that path.
➜  bin sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed,
and installing your bundle as root will break this application for
all non-root users on this machine.
Could not locate Gemfile
➜  bin

**Comment by busterb** [comment]
no, please run the command:
```
which msfconsole
```
not 'which is msfconsole'
