### ISSUE TITLE
New console changes gobble the last line of meterpreter command output

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#7709]
This issue appears to have come about as a result of the latest async console output changes. The problem is that any output from a Meterpreter command (such as `cat C:\file.txt`) that ends up without a newline at the end gets gobbled by this new change.

## Replication

* Create a file on a Windows system that has text in it but does NOT end in a newline (eg. `C:\file.txt`).
* Get a meterpreter session running on the same box.
* Run `cat C:\file.txt`.

You'll see that the single line of output is overwritten by the `meterpreter >` prompt.

**Comment by OJ** [comment]
This might also be mucking with home/end keys as well.

**Comment by bwatters-r7** [comment]
@dmaloney-r7 
<sigh>

**Comment by bwatters-r7** [comment]
@OJ Dumb question; do you have fix https://github.com/rapid7/metasploit-framework/pull/7670 merged in?

**Comment by OJ** [comment]
@bwatters-r7 yes I do indeedy.

**Comment by dmaloney-r7** [comment]
@bwatters-r7 *sigh* indeed

**Comment by dmaloney-r7** [comment]
@oj cannot reproduce 
```
meterpreter > cat test.txt
This line has a new line
This one does not
meterpreter >
```

![screen shot 2016-12-15 at 1 21 48 pm](https://cloud.githubusercontent.com/assets/1146440/21238663/7d59aa78-c2c9-11e6-9b7f-da93a3e04a01.png)

This sounds like the exact problem fixed by https://github.com/rapid7/metasploit-framework/pull/7670

**Comment by dmaloney-r7** [comment]
@oj are you still encountering this?

**Comment by bwatters-r7** [comment]
@OJ, did https://github.com/rapid7/metasploit-framework/pull/7739 fix this?

**Comment by OJ** [comment]
I'll take a look at HEAD some time today and let you guys know @bwatters-r7 @dmaloney-r7.

**Comment by bwatters-r7** [comment]
@OJ....... cough, cough.  Youtwo! Youtwo! Lookuphere! Lookuphere!  (Let's see if you get the reference....)

**Comment by OJ** [comment]
@bwatters-r7 I just did some more testing then and this does look at lot better. Thanks!
