### ISSUE TITLE
keep meterpreter commands alive

### ISSUE THREAD

**Issue by Naramsim** [rapid7/metasploit-framework#7714]
## Steps to reproduce

How'd you do it?

1. start a meterpreter session
2. execute a custom meterpreter script ([like](https://www.offensive-security.com/metasploit-unleashed/functions/#Execute_List_of_Commands))

## Expected behavior

What should happen?

The commands in the meterpreter script should continue to run, even if the meterpreter session get closed (maybe the server went down)

## Current behavior

If the server closes the connection of our meterpreter session, the commands running by our meterpreter script are stopped.

### Metasploit version

fa016de78ac119eeb88adc1edafb7c0f014411c2 Land #7634, Implement universal HTTP/S handlers for 

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
- [x] Docker image

### OS

What OS are you running Metasploit on?

Debian Jessie 8.6

**Comment by OJ** [comment]
> The commands in the meterpreter script should continue to run, even if the meterpreter session get closed (maybe the server went down)

Are you suggesting that commands should still execute inside Meterpreter even when it's no longer running?

**Comment by Naramsim** [comment]
Yes, is there a way to do it? @OJ

**Comment by OJ** [comment]
No, if Meterpreter isn't running it can't possibly execute commands.

**Comment by Naramsim** [comment]
ok, thanks
