### ISSUE TITLE
MSfvenom error with -x apktool injection

### ISSUE THREAD

**Issue by islamTaha12** [rapid7/metasploit-framework#7725]
I ran the following command and I got this error. 
![screenshot from 2016-12-18 11-52-06](https://cloud.githubusercontent.com/assets/17981089/21293346/14281ffe-c52a-11e6-8acf-165546596ff3.png)

##App source file:
https://apkpure.com/facebook/com.facebook.katana

##Version:
Framework Version: 4.13.7-dev-f0dca7abbf747a922ebfc945c84c852b817caab3

##OS:
Ubunut 16.04

**Comment by timwr** [comment]
The Facebook app does some crazy stuff due to the dex limit. You might be able to add the hook point to the Application class instead.

**Comment by islamTaha12** [comment]
@timwr How can I do this?

**Comment by islamTaha12** [comment]
The same issue with Uber:
![screenshot from 2016-12-19 15-31-13](https://cloud.githubusercontent.com/assets/17981089/21314566/707b46ba-c600-11e6-9171-8a12b8ffac39.png)

**App source**
https://apkpure.com/uber/com.ubercab

**Comment by islamTaha12** [comment]
same with Candy Crash
![screenshot from 2016-12-19 18-02-21](https://cloud.githubusercontent.com/assets/17981089/21319331/81892f52-c615-11e6-8c64-57e7bf12483b.png)

**Comment by timwr** [comment]
Thanks for reporting. I'll see what I can do
