### ISSUE TITLE
generate error on wmap_sites module in msfconsole

### ISSUE THREAD

**Issue by spidyyyy** [rapid7/metasploit-framework#7755]
## Steps to reproduce

How'd you do it?

whenever i put some site that is url target in it it shows unable to create site error

```
msf > wmap_sites -h
[*] Usage: wmap_sites [options]
	-h        Display this help text
	-a [url]  Add site (vhost,url)
	-d [ids]  Delete sites (separate ids with space)
	-l        List all available sites
	-s [id]   Display site structure (vhost,url|ids) (level)
```

when i used  the -a option to add it showed an error i tried putting up domain name  as well as 
ip in it please help.

## Expected behavior

What should happen?

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
i am using msfconsole on ubuntu 16.04

**Comment by bcook-r7** [comment]
what error did you get? '-h' just shows the help output and this is expected.

**Comment by spidyyyy** [comment]
-h is working but it is not creating the site
when i want to add asite using -a it is showing site not created error and
i tried using different ip's
what else to do?

**Comment by h00die** [comment]
@bcook-r7 was hoping you'd give some more details to better use his very busy time/dev schedule.  What would be useful is a copy paste of the commands, and their output.  Redacting client data as needed.  Maybe it wasn't working because you did `wmap_sites -a asdfasdfdsfs76686875875;;;::::::'''[-00`--`-`-`-`-`-`\n\n\n\n\n\`.  That would be easy to diagnose.  Maybe you put things in correctly, and there is a bug, or maybe it isn't handling port correctly etc.  More details helps devs give you a quicker, and better quality result.

With that said, I ran the first portion from [metasploit-unleashed](https://www.offensive-security.com/metasploit-unleashed/wmap-web-scanner/), since i'm unfamiliar with wmap.
```
# ./msfconsole 
       =[ metasploit v4.13.10-dev-2856facdf0              ]
msf > load wmap

.-.-.-..-.-.-..---..---.
| | | || | | || | || |-'
`-----'`-'-'-'`-^-'`-'
[WMAP 1.5.1] ===  et [  ] metasploit.com 2012
[*] Successfully loaded plugin: wmap
msf > wmap_sites -a www.google.com
[-] Unable to create site
msf > wmap_sites -a http://172.16.194.172
[-] Unable to create site
```

that 172 address isn't valid for me, however I don't think it does a check (or its VERY fast) to make sure the host/port/proto is alive.

**Comment by wvu-r7** [comment]
@spidyyyy: Is your database connected?

**Comment by h00die** [comment]
it wasn't on mine, however i'd argue that if that's a requirement, and hence why it wasn't able to create the site, it should say that in the error message

**Comment by wvu-r7** [comment]
Already have a patch for it. Will push soon.

**Comment by h00die** [comment]
@wvu-r7 ![wvu](http://img.memecdn.com/superman-vs-the-foo_o_1254459.jpg "wvu")

**Comment by wvu-r7** [comment]
@spidyyyy: I'll reopen this if your bug is valid. However, I wasn't able to repro with a connected database. Make sure your IP is a valid one, though, since ```Rex::Socket.getaddress``` needs to pass.

**Comment by spidyyyy** [comment]
ip is  valid but it still shows the message i am stuck here!! unable to
make site map -this is the error.

**Comment by h00die** [comment]
have you pulled the latest copy from git?  There can be a time delay between a git commit and a release, then propagation to various platforms

**Comment by spidyyyy** [comment]
ok sure i am researching  on vulnerabilities now do you know about them?

**Comment by h00die** [comment]
This ticket is only related to the bug.  Please only add on to this ticket if you believe the bug has not been properly fixed.

**Comment by spidyyyy** [comment]
its still not working properly
always shows the messaqe site not created!!!
what to do with that?

**Comment by spidyyyy** [comment]
i have sent you my output .jpg file too!!!

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/issues/7755#issuecomment-269993628

**Comment by spidyyyy** [comment]
whats the problem with that why it is not connecting with any site ?

**Comment by wvu-r7** [comment]
@spidyyyy: Is your database connected or not?

**Comment by spidyyyy** [comment]
its not connecting either!! shows an error with that too

**Comment by wvu-r7** [comment]
You're doing it wrong.
