### ISSUE TITLE
Auto complete missing for show info

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#7756]
How'd you do it?
1. Load any auxiliary module.
2. show (tab 2x)
3. show info - missing

### Metasploit version
Framework: 4.13.8-dev
Console  : 4.13.8-dev

### I installed Metasploit with:
Part of Kali.

### OS
Kali Linux 2016.2 rolling

**Comment by wvu-r7** [comment]
@leebaird: Can you explain a bit what you'd like to see? Kinda confused here, sorry.

**Comment by wvu-r7** [comment]
Gotcha.

**Comment by wvu-r7** [comment]
@leebaird: There's a ```show missing```, so I was confused. Thanks.
