### ISSUE TITLE
firefox_creds module problem

### ISSUE THREAD

**Issue by greenhand2learn** [rapid7/metasploit-framework#7817]
```
platform: kali rolling

meterpreter > getuid 
Server username: uid=0, gid=0, euid=0, egid=0, suid=0, sgid=0

meterpreter > run post/multi/gather/firefox_creds 

[*] Checking for Firefox profile in: /home/root/.mozilla/firefox/
[-] No users found with a Firefox directory
meterpreter > cd /root/.mozilla/firefox/w05fgz2r.default
meterpreter > pwd
/root/.mozilla/firefox/w05fgz2r.default
```

the module post/multi/gather/firefox_creds, it will download the creds from firefox, but there is a problem, if the user is root, it will go to /home/root/.mozilla/firefox/, but the directory doesn't exists. if the user is normal user, it will return OK

**Comment by wvu-r7** [comment]
```/home/root```, wat?

**Comment by void-in** [comment]
@wvu-r7 I think the root case is handled correctly. https://github.com/rapid7/metasploit-framework/blob/fd1c5fbce774328d03e712ecf833bdd9681d1df2/modules/post/multi/gather/firefox_creds.rb#L253. I will test it at my end as well to make sure everything works correctly. 

There is another problem with the module as well. The line https://github.com/rapid7/metasploit-framework/blob/fd1c5fbce774328d03e712ecf833bdd9681d1df2/modules/post/multi/gather/firefox_creds.rb#L252 is replacing every occurrence of space with a new line. Which means that if the username is "void in", the module is going to search in /home/void and /home/in which is both incorrect while the valid one i.e. /home/void in/ will be skipped.

**Comment by wvu-r7** [comment]
I remember working on that module. It's a disaster of complexity.

**Comment by pbarry-r7** [comment]
Say @greenhand2learn, what OS was your target running?  I was looking at the module code, and it appears that we could end up looking for /home/root if the `id` command is returning something different than we expect...

**Comment by greenhand2learn** [comment]
@pbarry-r7 　target OS is kali linux

**Comment by pbarry-r7** [comment]
Cool, thanks, @greenhand2learn.  Could you tell me which meterpreter you were using?  I've got a Kali (rolling) VM that I've tried the python and java meterpreters with, they appear to be acting OK (just FWIW).  Thanks!

**Comment by pbarry-r7** [comment]
Ah, I tried the linux meterpreter (x86), and appears that's the culprit (and it looks like the mettle payload also might be doing the same thing).  More digging...

**Comment by greenhand2learn** [comment]
@pbarry-r7  Yes. it's  linux meterpreter (x86)

**Comment by pbarry-r7** [comment]
Apologies for the churn on checkins there, I should've left off the "Fixes" comment until really ready.  I think I have the module working better now, am testing on various platforms (and with both meterpreter and shell sessions, since the module supports both).

**Comment by pbarry-r7** [comment]
OK, [PR is up](https://github.com/rapid7/metasploit-framework/pull/8019).  I believe it addresses the main issue you had, @greenhand2learn, as well as ensuring proper behavior when encountering directories (including user home directories) which contain spaces (per @void-in's comments; thx!).

That said, the module appears to have some unexpected behavior when trying to use the decrypt functionality (unrelated to my changes), but I'll leave that for another day.
