### ISSUE TITLE
Outlook credentials  module problem 

### ISSUE THREAD

**Issue by jwed** [rapid7/metasploit-framework#7818]
Hi,

I tried to use outlook module on Windows 7 to get the credential but it's show me a message that's tell 
 
```
meterpreter > run post/windows/gather/credentials/outlook 
[*] Searching for Microsoft Outlook in Registry...
[*] Microsoft Outlook not installed or Exchange accounts are being used.
[*] Complete
```

what does this message mean and how can I get the credential in this case !!

Metasploit version: 4.12.23-dev

### I installed Metasploit with:
- [x] Kali package via apt

### OS
- Kali linux

Thank you

**Comment by h00die** [comment]
a little more detail may help someone determine the problem.
What version of Outlook is installed?  Is it set to use Exchange, or other provider?

**Comment by wvu-r7** [comment]
Looks like your Outlook...
😎 
Isn't installed.

**Comment by jwed** [comment]
@h00die 
the Outlook version is 2007, 
and about the exchange I'm using the default setting with Hotmail mails.

**Comment by jwed** [comment]
@wvu-r7 
I don't think so I'm already accessing my emails.

**Comment by h00die** [comment]
Follow this registry out and see where it doesn't match: https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/credentials/outlook.rb#L72
