### ISSUE TITLE
how "workspace" display hosts Number services Number

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#7828]
how "workspace" display 

workspace   hostsNumber servicesNumber
eg
workspace          hostnum  servicsnum
 php                      30         3232
  szswdx               332       3435333
  szjc                      22          99

**Comment by wvu-r7** [comment]
What?

**Comment by hktalent** [comment]
workspace hosts count Number services count  Number
php             30                               3232
szswdx       332                             3435333

**Comment by wvu-r7** [comment]
Ah, I see.
