### ISSUE TITLE
shell by metasploit and meterpreter show "symbols"

### ISSUE THREAD

**Issue by xxxcrow** [rapid7/metasploit-framework#7831]
language of victim system is russian
http://image.prntscr.com/image/d7eb5f41eec94ee08d07422ae37a1700.png

**Comment by wvu-r7** [comment]
cc @bwatters-r7

**Comment by OJ** [comment]
This is a known issue. Channelised stuff knows nothing about unicode/encoding/etc. It just shuffles bytes back and forth. I looked into this a while ago and I can't remember what roadblock I hit.

This is going to be painful to fix, FYI!
