### ISSUE TITLE
The joomla_plugins module has some code that's strange

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7854]
Saw the following code in joomla_plugins module.   It's strange to require the size of ```res.body``` to change after ```res.body.gsub!(/[\r|\n]/, ' ')```

```
      plugin_search(tpath, papp, ip, res.body.size)
    end
  end

  def plugin_search(tpath, papp, ip, osize)
    res = send_request_cgi({
      'uri' => "#{tpath}#{papp}",
      'method' => 'GET'
    })
    return if res.nil?

    res.body.gsub!(/[\r|\n]/, ' ')
    nsize = res.body.size

    if (res.code == 200 and res.body !~/#404 Component not found/ and res.body !~/<h1>Joomla! Administration Login<\/h1>/ and osize != nsize)
      print_good("Plugin: #{tpath}#{papp} ")
      report_note(
```
Thanks to @wchen-r7 to confirm this suspicion.

**Comment by wvu-r7** [comment]
That is strange. Looks wrong.

**Comment by jinq102030** [comment]
The "res" in the invocation of function "plugin_search" is for HTTP request, ```'uri' => path,``` ,  in the definition of function "plugin_search", "res" is for a different HTTP request ```'uri' => "#{tpath}#{papp}",```. 
I guess the author just wants to say the responses are different, but it looks a little odd to use their sizes as the criteria.

**Comment by jinq102030** [comment]
Figured it out, the intention here is to make sure the sizes of http response body for the following two requests are different:

http://<host>/<targetPath>  
http://<host>/<targetPath>/<plugin>
