### ISSUE TITLE
feature request: populate hosts table with db_nmap script output

### ISSUE THREAD

**Issue by rkachowski** [rapid7/metasploit-framework#7891]
In the current db_nmap implementation (as of 0388c02) db_nmap doesn't populate the hosts table with information discovered from nse scripts and instead bundles all the output into the notes table where it stored as string data.

The output in msfconsole currently looks like this

```
msf > hosts

Hosts
=====

address     mac                name  os_name  os_flavor  os_sp  purpose  info  comments
-------     ---                ----  -------  ---------  -----  -------  ----  --------
10.11.1.5   00:50:56:89:7e:0d        Unknown                    device         
10.11.1.31  00:50:56:89:4a:c6        Unknown                    device         
10.11.1.73  00:50:56:89:37:47        Unknown                    device         

msf > notes
[*] Time: 2017-01-30 12:59:09 UTC Note: host=10.11.1.31 type=nmap.nse.nbstat.host data={"output"=>"NetBIOS name: RALPH, NetBIOS user: <unknown>, NetBIOS MAC: 00:50:56:89:4a:c6 (VMware)"}
[*] Time: 2017-01-30 12:59:10 UTC Note: host=10.11.1.5 type=nmap.nse.nbstat.host data={"output"=>"NetBIOS name: ALICE, NetBIOS user: <unknown>, NetBIOS MAC: 00:50:56:89:7e:0d (VMware)"}
[*] Time: 2017-01-30 12:59:10 UTC Note: host=10.11.1.73 type=nmap.nse.nbstat.host data={"output"=>"NetBIOS name: GAMMA, NetBIOS user: <unknown>, NetBIOS MAC: 00:50:56:89:37:47 (VMware)"}
[*] Time: 2017-01-30 13:00:08 UTC Note: host=10.11.1.31 type=nmap.nse.smb-os-discovery.host data={"output"=>"\n  OS: Windows Server 2003 3790 Service Pack 1 (Windows Server 2003 5.2)\n  OS CPE: cpe:/o:microsoft:windows_server_2003::sp1\n  Computer name: ralph\n  NetBIOS computer name: RALPH\n  Workgroup: THINC\n  System time: 2017-01-30T06:41:35-06:00\n"}
[*] Time: 2017-01-30 13:00:08 UTC Note: host=10.11.1.5 type=nmap.nse.smb-os-discovery.host data={"output"=>"\n  OS: Windows XP (Windows 2000 LAN Manager)\n  OS CPE: cpe:/o:microsoft:windows_xp::-\n  Computer name: alice\n  NetBIOS computer name: ALICE\n  Domain name: thinc.local\n  Forest name: thinc.local\n  FQDN: alice.thinc.local\n  System time: 2017-01-30T05:38:47+00:00\n"}
[*] Time: 2017-01-30 13:00:08 UTC Note: host=10.11.1.73 type=nmap.nse.smb-os-discovery.host data={"output"=>"\n  OS: Windows 7 Professional 7601 Service Pack 1 (Windows 7 Professional 6.1)\n  OS CPE: cpe:/o:microsoft:windows_7::sp1:professional\n  Computer name: gamma\n  NetBIOS computer name: GAMMA\n  Workgroup: WORKGROUP\n  System time: 2017-01-29T23:45:05-08:00\n"}
```

I feel it would be useful to have specific information from successful script runs included in the hosts table, this would include (for example)

1. Include NETBIOS computer name - if found - from the output of `nbstat.nse` in the 'name' column of the hosts table
2. Include os_flavor / name if found from the output of `smb-os-discovery.nse` in the appropriate columsn of the hosts table
3. Update the comments field for any hosts entry to display the fact that there's info available in the `notes` table for this host when nmap script output is stored

If I was to prepare a pull request for this feature, with parsing of the script data on a case by case level, is it something that would be considered for inclusion?

Also I note that the legacy nmap parser used to do something similar to this for the vulnerability output of the (deprecated) `smb-check-vulns.nse` script - [link here](https://github.com/rapid7/metasploit-framework/blob/b87911bd0bc2a7bae855c0f09ab21ee850d13fc2/lib/msf/core/db_manager/import/nmap.rb#L173). I would implement something similar to this, except encapsulate it outside of the core parsing.

**Comment by wvu-r7** [comment]
I think it's a great idea. Consider updating the `services` table as well, if you require.

**Comment by darkbushido** [comment]
What type of hosts were you scanning that db_nmap wasn't giving any info?
