### ISSUE TITLE
Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.

### ISSUE THREAD

**Issue by 765uyg** [rapid7/metasploit-framework#7898]
Linux 3.2.6  i686 GNU/Linux

When I upgraded with msfupdate, there were the following tips, but I don't know how to upgrade ruby,please help me

Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
An error occured while installing nokogiri (1.7.0.1), and Bundler cannot continue.

**Comment by 765uyg** [comment]
Some people say
sudo apt-get install ruby2.1.1

but it's not work
Couldn't find package ruby2.1.1

where I can download package

**Comment by wvu-r7** [comment]
Use RVM (https://rvm.io/) or rbenv (https://github.com/rbenv/rbenv). 2.3.3 is the currently supported version.
