### ISSUE TITLE
 Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank error if you dont set a password

### ISSUE THREAD

**Issue by carnal0wnage** [rapid7/metasploit-framework#7899]
## Steps to reproduce

ssh_login

set USERPASS_FILE but dont set a password

```
msf auxiliary(ssh_login) > run

[*] SSH - Starting bruteforce
[*] Error: 1.2.3.4: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)
```
if you set a PASSWORD it will sort of work unless of course the module doesnt take a password like ssh_login_pubkey
```
msf auxiliary(ssh_login_pubkey) > run

[*] 1.2.3.4:22 SSH - Testing Cleartext Keys
[*] SSH - Testing 6 keys from /Users/CG/hackershit/bad-ssh-keys
[*] Error: 1.2.3.4: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)
[*] Scanned 1 of 1 hosts (100% complete)
```
```
> version
Framework: 4.13.19-dev-321fa91
Console  : 4.13.19-dev-321fa91
```
git pull today

**Comment by mubix** [comment]
Confirmed / reproduced

**Comment by busterb** [comment]
Would you folks be willing to check out the fix above?

**Comment by mubix** [comment]
Fixed, however when no options are set except the RHOST/RPORT this isn't an informative error to the user:
```
Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)
```

**Comment by busterb** [comment]
Seems like the module should be able to better read the tea-leaves coming from the loginscanner class.

**Comment by egypt** [comment]
Still affects `ssh_login_pubkey` on master:

```
[*] 192.168.99.129:22 SSH - Testing Cleartext Keys
[*] SSH - Testing 1 keys from /home/egypt/.ssh/msfadmin.priv
[*] Error: 192.168.99.129: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::SSH)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by ka1n4t** [comment]
I've set pass_file, but it still raise this problem

**Comment by AkshayJainG** [comment]
This problem still exists

**Comment by Sumner072** [comment]
Problem still seems to exist, however I'm new to Metasploit Framework, so there may also be some user error.

**Comment by jmartin-r7** [comment]
@ka1n4t , @AkshayJainG, @Sumner072, if you are experiencing a similar issue please open a new issue with detailed environment and reproduction steps and reference this issue #.

There may be a regression, there may be a new issue, or there may simply be an invalid user expectation, however detailed reproduction steps are needed to validate. The original issue specified was tested as resolved when #7939 landed.

**Comment by Anonimocerca** [comment]
Issue still present! Same as before

**Comment by lavaicer** [comment]
Issue still present! Same as before

**Comment by ManuFelo** [comment]
try to the set the USERPASS_FILE
msf auxiliary(ssh_login) > set USERPASS_FILE   <wordlist with user - pass>
I did it like:

msf6 auxiliary(scanner/ssh/ssh_login) > set USERPASS_FILE /usr/share/wordlists/metasploit/piata_ssh_userpass.txt 
USERPASS_FILE => /usr/share/wordlists/metasploit/piata_ssh_userpass.txt 

This works for me

**Comment by jbhntr86** [comment]
I did that and this is what I got

msf6 auxiliary(scanner/afp/afp_login) > run

[ Msf::OptionValidateError The following omsf6 auxiliary(scanner/afp/afp_login) > run

Do I need to get my own wordlist and set the path to it?

**Comment by SwunPyae** [comment]
> try to the set the USERPASS_FILE msf auxiliary(ssh_login) > set USERPASS_FILE <wordlist with user - pass> I did it like:
> 
> msf6 auxiliary(scanner/ssh/ssh_login) > set USERPASS_FILE /usr/share/wordlists/metasploit/piata_ssh_userpass.txt USERPASS_FILE => /usr/share/wordlists/metasploit/piata_ssh_userpass.txt
> 
> This works for me

**Comment by HucksApp** [comment]
It means Ur login credentials isn't complete. You only set a password File , No username File but u need both to login.
solution... set USERPASS_FILE where u have one pair per line of username and password seperated by space

..........set  USERNAME  if its specific, or you  set USER_FILE with possible username file path

**Comment by manishmshiva** [comment]
Found the same error. Set "SMB_USER" field to a username. This error occurs when Metasploit doesn't have any users to check the password list with.

**Comment by selfi123** [comment]
include userpass_file
