### ISSUE TITLE
reverse_hop_http broken

### ISSUE THREAD

**Issue by Wack0** [rapid7/metasploit-framework#7907]
## Steps to reproduce

The `reverse_hop_http` payload is broken. It relies on the RECV POST functionality which was removed back in [December of 2015](https://github.com/rapid7/metasploit-payloads/commit/1061df8b8d286329cf929a3ce8eec795135ca66b).

Instead of creating a session, it just constantly waits, with HTTP requests being made from both systems.

I'm attempting a fix, but my fix is so hacky and horrible I doubt it'll be of use.

## Expected behavior

Using `reverse_hop_http` should open a session

## Current behavior

No sessions open, HTTP requests are made from both sides.

### Metasploit version

Framework: 4.13.19-dev-23c2787d57fc99783331ff5ab58926ee65908048
Console  : 4.13.19-dev-23c2787d57fc99783331ff5ab58926ee65908048

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [ ] Kali package via apt
- [*] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Windows

**Comment by OJ** [comment]
Yup, this doesn't surprise me at all. We pushed on ahead with the other changes knowing that this was probably going to break. Might be easier to get @scriptjunkie involved here as he was the original author of that.

**Comment by scriptjunkie** [comment]
Man @OJ, stop breaking muh stuff. In all seriousness, is there a way I can add a reverse hop test to the standard tests so when somebody fries it in the future the build will fail? 
@Wack0, would you mind sharing your fix attempt so far? Even if not great I'm sure it will speed up getting a real fix in.

**Comment by OJ** [comment]
Pretty sure that I knew it was breaking, but due to $PRIORITIES we just pushed on.

I'm assuming the fix will be pretty easy given that the core requirement is about supporting a `GET` instead of a `POST` for the initial requests.

**Comment by Wack0** [comment]
@scriptjunkie I basically did it really hackily: adding back the old "RECV" functionality, then sending that on HTTP GET to the php script; then setting up the UUID properly so that stdapi would send properly.

**Comment by Radrigo** [comment]
Hay gays. How can i fix this?

**Comment by busterb** [comment]
@Wack0 feel free to PR if you like, we can de-hack in review.

**Comment by fsacer** [comment]
any updates on this?

**Comment by scriptjunkie** [comment]
The hop isn't too hard to convert to the non-RECV POST functionality, but the stage generation looks like it will need changes too.
