### ISSUE TITLE
Permission denied exec: msfvenom

### ISSUE THREAD

**Issue by klaszlo8207** [rapid7/metasploit-framework#7919]
I am on Windows 10, yesterday I installed the framework, than I run the Metasploit Pro Console

"successfully loaded plugin: pro"

after I do this command: 

msfvenom

I got this:

Permission denied exec: msfvenom

What is the probleme? Have to run something else before I go with metasploit console?

Thanks

**Comment by busterb** [comment]
'msfvenom' is not a command exposed at all in Metasploit Pro. CC: @cdoughty-r7

If you want a Windows package that includes msfvenom, please use the open-source installer instead:
https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#windows 

Also, note that 'msfvenom' is not a command for the console at all. It is a standalone program. If you want to generate a payload from msfconsole, it is much more efficient to run `use payload/....` then use the `generate` command.
