### ISSUE TITLE
HttpTrace not working correctly with Chunked encoding

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#7921]
I just noticed this when testing a module against a Virtual Box VM.

If the Response from a HTTP request contains a `Transfer-Encoding: chunked` the output is completely messed up.

It looks smth. like this:
```
2
= 
7
'16px';
8

       
1
 
5
    }
8

       
4
 })(
3
);

1
 
1
 
8
  }
</sc
3
rip
6
t>    
3
</b
9
ody>
</ht
3
ml>
1


0
```

The problem lies in the `Packet::to_s` method.

If the `Transfer-Encoding` is `chunked` the `chunk` method is called:
https://github.com/rapid7/metasploit-framework/blob/cab19dc63c4fe67e2199b6215c105d49efff7b87/lib/rex/proto/http/packet.rb#L198

The `chunk` method itself prints the number of bytes in the chunk and the content in a loop:
https://github.com/rapid7/metasploit-framework/blob/cab19dc63c4fe67e2199b6215c105d49efff7b87/lib/rex/proto/http/packet.rb#L161

That's where the strange output comes from.

Any idea how to fix this? Is the `chunk` call on the `to_s` correct (because it looks a little bit weird)?

**Comment by FireFart** [comment]
PS: HTTP `Request` and `Response` both inherit `Packet` but I think the chunked stuff only makes sense on a `Request` object, not on a `Response`.

**Comment by wvu-r7** [comment]
Hmm, I saw this very recently.

**Comment by FireFart** [comment]
@wvu-r7 i created a possible fix here: https://github.com/rapid7/metasploit-framework/pull/8197

**Comment by wvu-r7** [comment]
So, turns out I noticed this for the `to_s` case, which #8197 doesn't address. I think you did the right thing by leaving it alone, @FireFart.

I can use `to_terminal_output` with my non-`HttpTrace` chunked responses for now.

Also, it appears that the `HTTP::chunked` evasion option was never implemented.
