### ISSUE TITLE
Persistence error? 

### ISSUE THREAD

**Issue by Anonymousismyname** [rapid7/metasploit-framework#7955]
K so all things work fine with persistence but when i dont listen or quit msfconsole. I see that the victim pc gets error "windows script host"  line 29 char 2.the system cannot find the file specified. And my victim  pc win 7 on vm can see the file location as it pops on the dialog box. If this is normal then persistence is of no use? Im i doing something wrong?

**Comment by void-in** [comment]
Did you use the persistence script or the post module?

**Comment by Anonymousismyname** [comment]
I used persistence script.

**Comment by wvu-r7** [comment]
Use a module.
