### ISSUE TITLE
Add a plugin to notify a new session via text

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#8026]
When a session is obtained, it would be nice to notify via text

**Comment by busterb** [comment]
@darkoperator has had something like this for a while: https://github.com/darkoperator/Metasploit-Plugins/blob/master/twitt.rb

**Comment by Chiggins** [comment]
I'd also argue adding other push notification services, ex. Pushover and Slack. Like make some kind of notification class/mixin that makes it pretty modular to work with adding additional services? 

Few of examples of service on this page: https://github.com/jreese/znc-push
