### ISSUE TITLE
add or clarify database creation step to developer docs

### ISSUE THREAD

**Issue by bermannoah** [rapid7/metasploit-framework#8042]
This might seem like a small thing but would it be possible to add something like 

"Now, run `rake db:create db:migrate db:test:prepare`."

After this section:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#create-the-databaseyml

And before this section:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment#run-specs

(...or include extra documentation related to the "The next time you start `./msfconsole`..." section. As it stands, it does not appear to be creating the database when the command is run. I could be doing something horribly wrong, of course.) 

I've run into this as an issue on both Kali Linux (latest version) and Ubuntu (latest version). Clean installs, with the dev version set up as per the metasploit docs.

**Comment by busterb** [comment]
thanks, will look at this

**Comment by bermannoah** [comment]
@busterb cheers, let me know if there's anything I can do to help

**Comment by rwhitcroft** [comment]
That guide does seem pretty long-winded/intimidating for what most users are looking for. You can definitely get away with just running `createuser`, `createdb`, and modifying database.yml.

**Comment by darkbushido** [comment]
if you want to create the test database it should be
`rake db:create:all db:migrate db:test:prepare`

**Comment by busterb** [comment]
this now magically works more intuitively as of #8234
