### ISSUE TITLE
Stacktrace for arris_dg950

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#8062]
## Steps to reproduce
```
resource (external/master.rc)> use auxiliary/scanner/snmp/arris_dg950
resource (external/master.rc)> run
[-] Auxiliary failed: SNMP::RequestTimeout host 10.0.0.104 not responding
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/snmp/manager.rb:241:in `get'
[-]   /usr/share/metasploit-framework/lib/snmp/manager.rb:262:in `get_value'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/snmp/arris_dg950.rb:32:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```
### Metasploit version
v4.14.0-dev

### I installed Metasploit with:
Kali package via apt

What OS are you running Metasploit on?
Kali 2016.2 rolling

**Comment by leebaird** [comment]
Another example

resource (/root/master.rc)> use auxiliary/scanner/snmp/arris_dg950
[-] Auxiliary failed: SNMP::RequestTimeout host 10.40.13.126 not responding
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/snmp/manager.rb:241:in `get'
[-]   /usr/share/metasploit-framework/lib/snmp/manager.rb:262:in `get_value'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/snmp/arris_dg950.rb:32:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'

**Comment by h00die** [comment]
I'm surprised https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/snmp/arris_dg950.rb#L140 didn't handle it correctly
