### ISSUE TITLE
run getgui

### ISSUE THREAD

**Issue by acinelit** [rapid7/metasploit-framework#8091]
I'll ask about run getgui

when i use run getgui -e i found error
[!] Meterpreter scripts are deprecated. Try post/windows/manage/enable_rdp.
[!] Example: run post/windows/manage/enable_rdp OPTION=value [...]
[-] This version of Meterpreter is not supported with this Script!

i use kali linux 2016.2
Framework: 4.13.19-dev
Console  : 4.13.19-dev

Thanks

**Comment by timwr** [comment]
Why not try what the script suggests? `run post/windows/manage/enable_rdp` ?
