### ISSUE TITLE
Can metasploit be classified as munition? 

### ISSUE THREAD

**Issue by pat556** [rapid7/metasploit-framework#8093]
Can metasploit be classified as munition?

**Comment by h00die** [comment]
Pro required an address for export restrictions, not sure about community though

**Comment by busterb** [comment]
Complex subject and not really appropriate as a github issue.

Being open source does allow the project to avoid regulation through the commerce dept. Read more https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States or https://en.wikipedia.org/wiki/United_States_Munitions_List.

IANAL, and your local regulations may differ.
