### ISSUE TITLE
Broken on ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by Swiftb0y** [rapid7/metasploit-framework#8097]
I can't run anything metasploit related anymore (just msfupdate but not msfconsole or msfvenom):

Error when starting:
`/var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- robots (LoadError)
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework.rb:18:in `<top (required)>'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `each'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `inject'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /home/pi/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
`
i couldn't find any logs.

Metasploit version:
437cba84b0563fb067757bb1ec03db9e01ed4579 Revert "Land #8090, support rails usage of spec files list"

### I installed Metasploit with:
Git.
Ruby_version: ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabihf]
### OS
Raspbian

**Comment by thecarterb** [comment]
As the beginning of the error message says:
>cannot load such file -- robots (LoadError)

You need to install the `robots` gem, so do `sudo gem install robots`.
Also for future issues, use #metasploit on IRC instead of GitHub Issues :)

**Comment by barnabyjack777** [comment]
This looks like your getting strong armed

**Comment by Swiftb0y** [comment]
Thanks for the help. I assumed it couldn't be a missing gem since bundler is supposed to install them. And thanks for the IRC tipp.
And where is the .msf4 folder located? I am not able to find it.

**Comment by thecarterb** [comment]
the `.msf4` directory is a hidden directory that is made in the home directory(`$HOME`) after metasploit is run for the first time. If metasploit hasn't ran yet, you wont have it

**Comment by Swiftb0y** [comment]
I have Metasploit run multiple times but it isnt there. even if i do a find | grep ".msf4" in / it doesn't return anything

**Comment by thecarterb** [comment]
In your home directory, try `ls -a`

**Comment by Swiftb0y** [comment]
already tried it:
.              .dbus                    Music              .ssh
..             Desktop                  .netrc             .teensy
.arduino       Documents                .npm               Templates
Arduino        Downloads                oldconffiles       .themes
.arduino15     .gconf                   .oracle_jre_usage  .thumbnails
.asoundrc      .gem                     payload.surge.sh   Videos
AutoRun.rb     .gitconfig               pi@192.179.178.40  .wireshark
.bash_history  .gnome                   Pictures           .WolframEngine
.bash_logout   .gstreamer-0.10          .pip               .Xauthority
.bashrc        .idlerc                  .pki               .xchat2
BMI_funcs.py   .java                    .profile           .xsession-errors
.bundle        .jssc                    Public             .xsession-errors.old
.cache         .kde                     python_games       .zenmap
classes.py     .local                   referatTest.py
.codeblocks    modules_arrays_loops.py  sketchbook
.config        .mozilla                 sketch_jan29a

**Comment by thecarterb** [comment]
Hm, I suggest doing the following things:

1. Run `msfupdate`
2. If `#1` doesn't work, uninstall and reinstall Metasploit

Also, how did you install metasploit?

**Comment by Swiftb0y** [comment]
I used Git and msfupdate didn't fix it before. Thats not so important anymore. I'm trying my luck on the IRC channel

**Comment by thecarterb** [comment]
@Swiftb0y Okay cool. (Don't forget to close the issue)

**Comment by Swiftb0y** [comment]
like this?

**Comment by wvu-r7** [comment]
@Swiftb0y: Thanks for the chat. Best of luck.
