### ISSUE TITLE
How add own payload module?

### ISSUE THREAD

**Issue by Radrigo** [rapid7/metasploit-framework#8106]
## Steps to reproduce

Hi guys!
How i can add own payload module in msf? 
If i create ~/.msf4/modules/payloads/stagers/windows/test.rb i can't see it in msf. And when i create in /usr/share/metasploit-framework/modules/payloads/stagers/windows/test.rb i have same resulte.
I need your help.

**Comment by busterb** [comment]
This isn't a support channel. Try community.rapid7.com or #metasploit on IRC
