### ISSUE TITLE
Metasploit (Pro) - Persistence??

### ISSUE THREAD

**Issue by GabrielTK** [rapid7/metasploit-framework#8112]
Hey Guys, sorry, I need some help using post/windows/manage/persistence_exe (or even post/pro/multi/agent or something else) to keep a meterpreter shell persistant now that scripts are deprecated. I've tried both but I can't figure out how they work!

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [X ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Kali Linux (installed MSFPRO through website)

Thank you,
Gabriel

**NOTE: It would be good if i could use it with Macros**

**Comment by void-in** [comment]
@GabrielTK This isn't a support forum. For pro, use their dedicated support channel. For MSF help, use https://community.rapid7.com.

**Comment by GabrielTK** [comment]
Ok, thx :D

On Mar 15, 2017 5:42 AM, "Waqas Ali" <notifications@github.com<mailto:notifications@github.com>> wrote:

@GabrielTK<https://github.com/GabrielTK> This isn't a support forum. For pro, use their dedicated support channel. For MSF help, use https://community.rapid7.com.
