### ISSUE TITLE
Metaspolit Console crashes !

### ISSUE THREAD

**Issue by Ex911** [rapid7/metasploit-framework#8125]
I've Installed Metasploit Pro on Windows 10 .. but everytime I run "Console" it crashes with errors ..
such as ruby ... etc.

and Web working with me . idk where's the problem exactly .. and I've installed it for 4 times XD 

### OS
Windows 10

Any help ? XD

**Comment by wvu-r7** [comment]
If you are a Pro user, and you are a customer, you should contact support first.

**Comment by Ex911** [comment]
I've tried customer user first .. but got the same issue . 
so .. "Pro" or "customer" doesn't make a difference for OS .. I guess. ^^

**Comment by wwebb-r7** [comment]
Perhaps a screenshot of the errors you're receiving is in order.

**Comment by pbarry-r7** [comment]
@Ex911, I think what @wvu-r7 is getting at is that if you're a Rapid7 customer, your best route for help would be contacting Rapid7 support.

**Comment by wvu-r7** [comment]
No response from OP, so I'm closing this.

**Comment by busterb** [comment]
Note, when the 64-bit version of Metaploit Pro is released for Windows, the console command will be just a 'cmd.exe' window rather than the odd terminal emulator it ships with today. This should increase compatibility with modern versions of Windows.
