### ISSUE TITLE
Mac metasploit errors after update

### ISSUE THREAD

**Issue by UtilityDocket** [rapid7/metasploit-framework#8142]
### This morning I updated metasploit and while it was working fine, after the update it started throwing this:

http://pastebin.com/raw/ZgKWUDKY

### Metasploit version
Latest as of today.
### OS
Mac - El Capitan

**Comment by busterb** [comment]
Hi. Do you have any idea what you upgraded from?

**Comment by UtilityDocket** [comment]
Not sure what you mean by that question. Metasploit told me to update with msfupdate, which I did. Now it doesn't work.

**Comment by busterb** [comment]
I meant when was the last time you updated? 6 months ago? 2 weeks ago?

**Comment by UtilityDocket** [comment]
I last updated 2 days ago when I made this post.

**Comment by busterb** [comment]
Sorry, I'm miscommunicating.  Let me try asking another way: do you remember what version you were on _before_ you upgraded. You should be able to reset your database easily with 'msfdb reinit' but I'd like to be able to take a look at your ~/.msf4/db directory somehow.

The reason why I care about what the previous release you were on is, about 2 months ago we upgraded the package from postgresql 9.4 to 9.6. And, I'd like to know if the upgrade caused the issue you're having.

**Comment by busterb** [comment]
I'd suggest moving your old database out of the way with 'mv ~/.msf4/db ~/.msf4/db.bak` and then running 'msfdb reinit'. It looks like your database is corrupt, but it's hard, without more info, to guess why or to suggest a resolution. If there's nothing in there that you don't mind sharing, you could send us a tarball of the database to msfdev@metasploit.com for analysis.
