### ISSUE TITLE
db_import fails to import Nikto XML

### ISSUE THREAD

**Issue by Kalaratri** [rapid7/metasploit-framework#8170]
## Steps to reproduce

I created a Nikto XML file from scan, then used db_import, but it fails:

## Current behavior
b_import lab_nikto_http.xml
[*] Importing 'Nikto XML' data
[-] Failed to import /mnt/hgfs/KaliShare/pwk_exercises/14.2.3/lab_nikto_http.xml due to malformed XML:
[-] REXML::ParseException: No close tag for /niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan
Line: 6716
Position: 421622
Last 80 unconsumed characters:

I've tried to recreate the issue with a much smaller nikto scan of my loopback address and this time the import works fine.

An nmap XML import also works fine.

### Metasploit version

Framework: 4.14.5-dev
Console  : 4.14.5-dev

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Linux kali 4.6.0-kali1-686 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux

--------------------------------------------------------------------------
Nikto Versions
---------------------------------------------------------------------------
File                               Version      Last Mod
-----------------------------      --------     ----------
Nikto main                         2.1.6
LibWhisker                         2.5
db_404_strings                     2.003        
db_content_search                  2.000        
         nary                      1.0
db_drupal                          1.00         
db_embedded                        2.004        
db_favicon                         2.010        
db_headers                         2.008        
db_httpoptions                     2.002        
db_multiple_index                  2.005        
db_outdated                        2.017        
db_parked_strings                  2.001        
db_realms                          2.002        
db_server_msgs                     2.006        
db_subdomains                      2.006        
db_tests                           2.021        
db_variables                       2.004        
nikto_apache_expect_xss.plugin     2.04         
nikto_apacheusers.plugin           2.06         
nikto_auth.plugin                  2.04         
nikto_cgi.plugin                   2.06         
nikto_clientaccesspolicy.plugin    1.00         
nikto_content_search.plugin        2.05         
nikto_cookies.plugin               2.05         
nikto_core.plugin                  2.1.5        
nikto_dictionary_attack.plugin     2.04         
nikto_drupal.plugin                1.00         
nikto_embedded.plugin              2.07         
nikto_favicon.plugin               2.09         
nikto_fileops.plugin               1.00         
nikto_headers.plugin               2.11         
nikto_httpoptions.plugin           2.10         
nikto_ms10_070.plugin              1.00         
nikto_msgs.plugin                  2.07         
nikto_multiple_index.plugin        2.03         
nikto_negotiate.plugin             2.00         
nikto_outdated.plugin              2.09         
nikto_parked.plugin                2.00         
nikto_paths.plugin                 2.00         
nikto_put_del_test.plugin          2.04         
nikto_report_csv.plugin            2.07         
nikto_report_html.plugin           2.05         
nikto_report_nbe.plugin            2.02         
nikto_report_sqlg.plugin           2.00         
nikto_report_text.plugin           2.05         
nikto_report_xml.plugin            2.05         
nikto_robots.plugin                2.06         
nikto_shellshock.plugin            2.01         
nikto_siebel.plugin                1.00         
nikto_sitefiles.plugin             2.00         
nikto_ssl.plugin                   2.01         
nikto_subdomain.plugin             2.01         
nikto_tests.plugin                 2.04

**Comment by pbarry-r7** [comment]
Hmm, at an initial blush, sounds like the XML is missing a tag:

```
[-] REXML::ParseException: No close tag for /niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan/niktoscan
```

Could you try validating the XML with another program?  If you don't have something installed, you can try something like https://www.samltool.com/prettyprint.php (paste your XML in, press the "turn pretty" button), and if it's valid XML, you'll see it show up pretty-printed at the bottom of the page.  If it's not valid, you'll see an error message stating "ERROR WHEN LOADING THE XML".

If you are able to validate that it is valid XML, then it'd be helpful for us to see a copy of it if you'd be willing to share (you could email it to msfdev@metasploit.com.  Thx!

**Comment by Kalaratri** [comment]
Hi, thanks, for user I get a ERROR WHEN LOADING THE XML when trying the above, so it looks like Nikto isn't outputting XML as expected...

**Comment by pbarry-r7** [comment]
Thanks for the follow up.  I'm going to close this issue for now, but please reopen if you do encounter a scenario where the Nikto XML output passes validation but fails msfconsole's **db_import**  command.
