### ISSUE TITLE
Build Metasploit nightly builds as Linux snap 

### ISSUE THREAD

**Issue by KINGSABRI** [rapid7/metasploit-framework#8196]
Hello guys, 
As we know, Metasploit community is doing great effort to contribute, maintain and package metasploit nightly builds. 

As [snap](https://snapcraft.io) project come, it makes our life much easier since we can use metasploit without any missing gems, with configure database(maybe), with an easy update, and unified build. No deb, rpm packaging, just push it to snap store. 

I believe it much better to use an official rapid7 account for that matter as it name gets registered under the username. 

So what you think? 

**Resources**
- [Official website](https://snapcraft.io/)
- [Create a snap](https://snapcraft.io/create/)
- [Snap Store (Ubuntu Store)](https://snapcraft.io/docs/core/store)

**Comment by busterb** [comment]
We already maintain native packages for a few different OSes, the benefit of the Omnibus platform being it works with Windows and OS X too. We now also have automatic Docker builds now. I'm just not super keen of diluting the Rapid7 packaging efforts any more.

Feel free to investigate further though, maybe we'll rethink it in the future.
