### ISSUE TITLE
missing shell comands android. Help pls

### ISSUE THREAD

**Issue by Techscq** [rapid7/metasploit-framework#8198]
there cant use cp, pull, push, sh an others commands,¿ we need make it by our self like a script? or anyone know how to get acces to these commands?

also i was getting time issue on reverse_https payloads some connections die after 10 mins sometimes less is for a android device fault?

im using Payload android/meterpreter/reverse_https and multi handler 

PD: My english is poor but i hope make sense my question, and you can understand if anyone know pls let me know how to, i will appreciate it too much.

**Comment by wvu-r7** [comment]
Patches welcome.
