### ISSUE TITLE
Modify extapi to check for dependencies

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#8199]
As per the discussion on https://github.com/rapid7/mettle/pull/70 we should have support in the `extapi` extension loading to check dependencies for the underlying functions. This is required to stop commands appearing in the Meterpreter menu that aren't actually supported by the underlying session.

**Comment by timwr** [comment]
@OJ I can grab this if you like. I'm sure you have bigger things :)

**Comment by OJ** [comment]
If you feel like it, sure :)
