### ISSUE TITLE
Metasploit fails to load - /tmp/module file collision - Multi-user environment

### ISSUE THREAD

**Issue by rwincey** [rapid7/metasploit-framework#8226]
## Steps to reproduce

Run msfconsole on the same system under two nonprivileged users.

## Expected behavior

Metasploit starts

## Current behavior

The following stack trace is the result of a file getting created by a user upon startup in the /tmp directory that is never deleted. Thus when a second user tries to run metasploit, it tries to clobber that file and metasploit fails to load. I'm not sure of the purpose of this class so outside of deleting the /tmp/module file after it serves it's purpose I cannot propose the appropriate fix. Please confer with acammack-r7.

/opt/metasploit-framework/embedded/framework/lib/msf/core/modules/external/shim.rb:12:in `initialize': Permission denied @ rb_sysopen - /tmp/module (Errno::EACCES)
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/external/shim.rb:12:in `open'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/external/shim.rb:12:in `generate'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/executable.rb:85:in `read_module_content'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:126:in `load_module'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:237:in `block in load_modules'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/executable.rb:51:in `block (2 levels) in each_module_reference_name'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-0.1.8/lib/rex/file.rb:133:in `block in find'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-0.1.8/lib/rex/file.rb:132:in `catch'
        from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rex-core-0.1.8/lib/rex/file.rb:132:in `find'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/executable.rb:42:in `block in each_module_reference_name'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/executable.rb:31:in `foreach'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/executable.rb:31:in `each_module_reference_name'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/modules/loader/base.rb:236:in `load_modules'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:117:in `each'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        from /opt/metasploit-framework/embedded/framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
        from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
        from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
        from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:219:in `initialize'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'

### Metasploit version

latest

### I installed Metasploit with:
- [ ] Omnibus installer (nightly)

### OS

Ubuntu 16.04.2 LTS

**Comment by busterb** [comment]
Thanks, we'll get this fixed soon.

**Comment by rwincey** [comment]
Thanks for the quick fix.
