### ISSUE TITLE
Wmap Fails to Load with Ruby 2.4

### ISSUE THREAD

**Issue by n0l3ptr** [rapid7/metasploit-framework#8235]
## Steps to reproduce
./msfconsole
load wmap

## Expected behavior
wmap plugin should load

## Current behavior
I receive the following error message:
Failed to load plugin from /home/shawn/git/metasploit-framework/plugins/wmap: cannot load such file -- xmlrpc/client

### Metasploit version
Framework: 4.14.11-dev-ced1412
Console  : 4.14.11-dev-ced1412

### I installed Metasploit with:
Source install (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux])

### OS

What OS are you running Metasploit on?
16.04.1-Ubuntu 

### Comments
I'm not sure if this helpful but it seems wpsscan had similar issues. [https://github.com/wpscanteam/wpscan/issues/1044](https://github.com/wpscanteam/wpscan/issues/1044)

**Comment by busterb** [comment]
Thanks, easy to fix.

**Comment by busterb** [comment]
See #8236 , it should fix it for you.
