### ISSUE TITLE
meterpreter, incognito and german windows

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#8240]
We had the following problem on a recent pentest:
We got a meterpreter session to the target via MSSQL and tried to escalate our privileges using rotten potato. We got the impersonation token, but the full name of the account on a german windows server (it was 2008) the account is named: `NT-AUTHORITÄT\SYSTEM`.
Meterpreter can not handle the `Ä` as you can see in the following screenshot and it was not possible to use the impersonation token because of this special character.
![screen](https://cloud.githubusercontent.com/assets/105281/25037013/1df1fc7a-20f7-11e7-8873-697095304ff0.png)

Furthermore other commands like `ps -s` are also not working on the german windows (even with SYSTEM privs) because of the name.

PS: we used the `add_user` and `add_localgroup_user` as a workaround as these do need the Account name.

What do you think about prefixing the account name from `list_tokens` with a number so the user can also enter the number instead of the full account name?

**Comment by wwebb-r7** [comment]
It's an umlaut, with the pronunciation of ah becoming ehh.  I have no idea how to help you with this computer hocus pocus though.


![](https://i.ytimg.com/vi/GD6qtc2_AQA/maxresdefault.jpg)

**Comment by busterb** [comment]
This looks like an issue with your terminal emulator. What OS were you running metasploit under?

**Comment by busterb** [comment]
The best approach IMO is to convert the related APIs under Meterpreter where we're still using ASCII versions to Unicode. It's not too hard to do once they're identified.

One of the hard things about supporting numbered lists is maintaining state consistency between displaying the list and processing the command.

**Comment by busterb** [comment]
Looks like we're doing a lot of comparisons of account names with the string literal 'NT AUTHORITY' too - we should switch those to use SID, which is consistent across localizations.

**Comment by FireFart** [comment]
@busterb Unicode in meterpreter would be awesome! In this example we used the default `windows/meterpreter/reverse_tcp` payload.
I thought the SID was already used for every account compare being made :/

So this issue can be split in two parts:
- Support Unicode in meterpreter
- Switch account compares to SID instead of the name

**Comment by busterb** [comment]
Yep. I'm elbow deep into unicode conversions:
```
$ git diff |diffstat
 hash_stealer.c |   21 ++++++++--------
 incognito.c    |   40 +++++++++++++++++--------------
 list_tokens.c  |   62 ++++++++++++++++++++++++------------------------
 list_tokens.h  |   28 ++++++++++-----------
 token_info.c   |   73 +++++++++++++++++++++++++++------------------------------
 token_info.h   |   10 +++----
 6 files changed, 119 insertions(+), 115 deletions(-)
```

**Comment by busterb** [comment]
Fixed, thanks!
