### ISSUE TITLE
ms17_010 error

### ISSUE THREAD

**Issue by yf007** [rapid7/metasploit-framework#8265]
https://localhost:3790/workspaces/1/tasks/new_module_run/auxiliary/windows/smb/smb_ms17_010

Communication Error

Problem Description

The Pro Service returned a server-side error. This may be caused by a badly behaving target system or session.The specific error was Msf::RPC::Exception Invalid Module (["lib/msf/core/rpc/v10/rpc_base.rb:25:in `error'", "lib/msf/core/rpc/v10/rpc_module.rb:408:in `_find_module'", "lib/msf/core/rpc/v10/rpc_module.rb:221:in `rpc_options'", "lib/msf/core/rpc/v10/service.rb:152:in `block in process'", "lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'", "lib/ruby/2.3.0/timeout.rb:33:in `block in catch'", "lib/ruby/2.3.0/timeout.rb:33:in `catch'", "lib/ruby/2.3.0/timeout.rb:33:in `catch'", "lib/ruby/2.3.0/timeout.rb:106:in `timeout'", "lib/msf/core/rpc/v10/service.rb:152:in `process'", "lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'", "lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "lib/rex/proto/http/server.rb:368:in `dispatch_request'", "lib/rex/proto/http/server.rb:302:in `on_client_data'", "lib/rex/proto/http/server.rb:161:in `block in start'", "lib/rex/io/stream_server.rb:48:in `on_client_data'", "lib/rex/io/stream_server.rb:192:in `block in monitor_clients'", "lib/rex/io/stream_server.rb:190:in `each'", "lib/rex/io/stream_server.rb:190:in `monitor_clients'", "lib/rex/io/stream_server.rb:73:in `block in start'", "lib/rex/thread_factory.rb:22:in `block in spawn'", "lib/msf/core/thread_manager.rb:100:in `block in spawn'"]) 

Problem Solution

This problem may resolve itself on its own. If this continues to appear, try restarting the Metasploit services or contacting customer support. 

### I installed Metasploit with: 
windows 10 64 bit 
metasploit pro

**Comment by busterb** [comment]
Hi, the error says 'Invalid Module' - this means that we have not actually released Metasploit Pro with that module yet. Pro could probably do a better job communicating this, but your best bet for now is to either grab a nightly framework build, or wait until the next Pro release in a day or two.
