### ISSUE TITLE
RHOSTS Validation

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#8273]
Just stumbled across this when scanning a large ip set with `auxiliary/scanner/smb/smb_ms17_010`.

If you set the `RHOSTS` to `10.0.0.0/8` and execute an `run` metasploit tries to resolve every IP address via DNS before starting the real scan.

Is there a trick to skip the DNS lookups?

**Comment by busterb** [comment]
I suspect that's happening inside of rex-socket when it sets up Rex::Socket::RangeWalker, but I'm not seeing it here. What's your environment?

**Comment by FireFart** [comment]
@busterb I'm on a freshly installed kali switchted to multiuser.target, `/etc/resolv.conf` link to NetworkManager was deleted and added a new file with 2 nameservers in the scanned range and a fixed ip address in `/etc/network/interfaces`:
```
auto eth0
iface eth0 inet static
        address 10.x.x.x
        netmask 255.255.252.0
        gateway 10.x.x.x
        dns-nameservers 10.x.x.x 10.x.x.x
        dns-search xxxx.yyyy aaaa.yyyy bbbbb.yyyyy
```

**Comment by FireFart** [comment]
@busterb can't reproduce any more :/ I think this was caused by some background noise on the virtual machine.

Will close this issue and if it occurs again, I will open it again
