### ISSUE TITLE
can't make database in metasploit 

### ISSUE THREAD

**Issue by chansook** [rapid7/metasploit-framework#8276]
hello, 

I just recently installed metasploit framework on my mac os x sierra and i neglected to create a database when prompted to do so  / now i'm trying to create a database and i'm not really sure how to do that / any and all help would be greatly appreciated. thanks, chansook

**Comment by busterb** [comment]
type 'msfdb init'

**Comment by chansook** [comment]
thanks!! much appreciated!!

**Comment by chansook** [comment]
another question, though!! after i enter 'msfdb init' i get this message: Found a database at /Users/poo/.msf4/db, checking to see if it is started Database already started at /Users/poo/.msf4/db --then when i check to hit 'db_status' i get this: postgresql selected, no connection !!!  what gives here??

**Comment by chansook** [comment]
another question, though!! after i enter 'msfdb init' i get this message:
Found a database at /Users/poo/.msf4/db, checking to see if it is started
Database already started at /Users/poo/.msf4/db --then when i check to hit
'db_status' i get this: postgresql selected, no connection !!! what gives
here??

**Comment by busterb** [comment]
Do you have Cylance installed? It kills postgresql
Other than that, I can recommend 'msfdb reinit' to reinitialize the database if it is corrupt.
You might also check the logs under .msf4/db/

**Comment by chansook** [comment]
maybe i should reinstall metasploit/ what is the command to uninstall the
program??
thanks

**Comment by chansook** [comment]
i keep getting this message after i start metasploit: [-] Failed to connect
to the database: could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5433?
could not connect to server: Connection refused
    Is the server running on host "localhost" (fe80::1) and accepting
    TCP/IP connections on port 5433?
could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5433?

this is after i tried 'msfdb reinit' don't know what to think of this, i
think to reinstall might be a better idea

**Comment by busterb** [comment]
cat .msf4/db/log

**Comment by busterb** [comment]
If I can't see your logs, I'm flying blind. Reinstalling would be unlikely to help. Maybe drop by #metasploit on IRC time and I can walk you through debugging.

**Comment by chansook** [comment]
what would be a good time?? i'm on Hawaii Pacific time

**Comment by busterb** [comment]
I can be around this afternoon CST if you want to drop in.
