### ISSUE TITLE
powershell_execute and python_execute timeout too quickly

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-framework#8289]
These commands use the default 15 second command timeout, but when using advanced scripts, it is highly possible that they will take longer to complete. This is the case, for instance, with BloodHound.ps1. It would be nice if as long as meterpreter was responsive that the command would not timeout until it actually completed.

In another case, it is often useful to run a script in the background. While you can setup a channel for this and background, it would also be good to just be able to run in the background in the first place, e.g. when using something like responder, or even a simple http server running inside of the Meterpreter payload.

**Comment by OJ** [comment]
Absolutely +1 to this. It's been on my TODO list to fix properly for ages. It'll be great to come up with a strategy to solve this across the board, as there are other commands that might take a long time, or that could be backgrounded.

**Comment by busterb** [comment]
This duplicated #6274, closing
