### ISSUE TITLE
CredentialCollection requires password source, but Credentials do not require a password

### ISSUE THREAD

**Issue by brandonprry** [rapid7/metasploit-framework#8304]
I have a module I have written that bruteforces usernames only, given an information disclosure issue in a login form. To efficiently brute force potential usernames, I build a LoginScanner for the web application.

It turns out that a CredentialCollection requires some password source, even if it is ```blank_passwords: true```.

For instance, the following line of code will cause the module to not run.

```
113     cred_collection = ::Metasploit::Framework::CredentialCollection.new(
114       user_file: datastore['USER_FILE'],
115       username: datastore['USERNAME'],
116     )
```

Attempting to run will result in the following error:

```
[*] Error: 192.168.56.103: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank
```

To work around this, you can pass ```blank_passwords: true``` to the cred collection like so.

```
113     cred_collection = ::Metasploit::Framework::CredentialCollection.new(
114       user_file: datastore['USER_FILE'],
115       username: datastore['USERNAME'],
116       blank_passwords: true
117     )
```

However, this will cause a 'valid' credential (which is just a username) to be saved with a blank password instead of a nil password, which is not technically correct. So even though a Credential can be saved with just a username, just a password, or just a realm, the cred collection requires at least a username and password source.

Thanks to @darkbushido for the help in tracking this down.

**Comment by adfoster-r7** [comment]
I believe this was solved by `nil_passwords: true` https://github.com/rapid7/metasploit-framework/blob/1b6efbbcd6199d1705cde2b0863798fd32ddf0a8/lib/metasploit/framework/credential_collection.rb#L16-L19 - will pre-emptively close
