### ISSUE TITLE
Module Docs Not Working - MSF Install from Kali Repo

### ISSUE THREAD

**Issue by sn0wfa11** [rapid7/metasploit-framework#8314]
## Overview

MSF installed standard on Kali does not show the Knowledge Base module docs when using `info -d`. The module docs do show up for the Dev Environment setup from Github.

Not sure if this is an MSF packaging issue or if it is a Kali repo issue, but wanted to start here.

Just ran Parrot OS 3.5 on live ISO and it has the same issue as described below. (MSF v.4.14.0-dev)

## Steps to reproduce

1. Fire up the standard install of Metasploit-Framework on Kali.  (Not the Github based dev environment ) 
2. Use a module that is known to have module docs. (post/windows/manage/priv_migrate or post/windows/manage/hashcarve as examples.)
3. Type `info -d`. No Knowledge Base document is displayed, only the default module Overview.

## Expected behavior
SS taken from Dev Environment with module docs working correctly.  (post/windows/manage/priv_migrate)

![image](https://cloud.githubusercontent.com/assets/12484685/25507011/3813ab08-2b6f-11e7-8fd7-994bde16def9.png)

## Current behavior
SS taken from standard install on Kali. (post/windows/manage/priv_migrate)

![image](https://cloud.githubusercontent.com/assets/12484685/25507039/5e98d49c-2b6f-11e7-8147-adfc83fd8acb.png)

## Doc Location
In the standard install on Kali, the module docs are being placed in `/usr/share/doc/metasploit-framework/modules/` and it does not look like the framework is looking in this location when it generates the docs into HTML. If I copy the "Documentation" folder from the Metasploit-Framework github account into `/usr/share/metasploit-framework/` then the module docs work correctly.

 Also, some of the doc files are not being decompressed correctly either.

![image](https://cloud.githubusercontent.com/assets/12484685/25507229/5c200e6e-2b70-11e7-8c79-e8b4c0f328fe.png)

### Metasploit version
v4.14.14-dev

### I installed Metasploit with:
- Kali package via apt

### OS
Kali Rolling 2017.1 (x86 and x64)

**Comment by busterb** [comment]
Works as expected with the latest Rapid7 omnibus packages too. I wonder why Kali doesn't package metasploit with the same layout we have in the source tree.

**Comment by busterb** [comment]
This sounds like something that should be filed on the Kali bug tracker instead. They're receptive to fixes.

**Comment by sn0wfa11** [comment]
Ok, I'll contact OffSec and go from there.

**Comment by busterb** [comment]
Thanks @sn0wfa11 - I'll close this one for now.

**Comment by sn0wfa11** [comment]
The issue was fixed by Kali as of version 4.14.15 on 5-3-17.

**Comment by busterb** [comment]
Nice, thanks for the update.
