### ISSUE TITLE
Metasploit error

### ISSUE THREAD

**Issue by KigothoWilson** [rapid7/metasploit-framework#8328]
I'm having the error below when I start my Metasploit. I guess the problem started when I was installing Beef framework:

/opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require': libruby-1.9.1.so.1.9: cannot open shared object file: No such file or directory - /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/bundler/gems/pcaprub-c18d552b3095/lib/pcaprub.so (LoadError)
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/bundler/gems/pcaprub-c18d552b3095/lib/pcaprub/ext.rb:1:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/bundler/gems/pcaprub-c18d552b3095/lib/pcaprub.rb:5:in `<module:PCAPRUB>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/bundler/gems/pcaprub-c18d552b3095/lib/pcaprub.rb:1:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `block in require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/dependencies.rb:251:in `require'
	from /opt/metasploit/apps/pro/ui/lib/metasploit/pro/ui.rb:24:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `rescue in block in require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:82:in `block in require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /opt/metasploit/apps/pro/msf3/config/application.rb:10:in `<top (required)>'
	from /opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/base.rb:55:in `require'
	from /opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/base.rb:55:in `require_environment!'
	from /opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/base.rb:81:in `start'
	from /opt/metasploit/apps/pro/msf3/msfconsole:22:in `<main>'

How do I solve this?

**Comment by busterb** [comment]
That would appear to be a 3+ year old version of Metasploit commercial edition in /opt/metasploit.

I'd just uninstall /opt/metasploit or at least move it out of the way. This isn't a support forum though, this is for bugs in metasploit-framework. Try #metasploit on IRC please.

**Comment by busterb** [comment]
If you want an up-to-date copy of metasploit framework, please choose https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers for something up-to-date and compatible with current software.
