### ISSUE TITLE
Publish the Docker Image

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#8349]
This issue should track the steps needed to publish the Docker image to docker hub.

I think after https://github.com/rapid7/metasploit-framework/pull/8310 is merged the image is ready to be published. The image can be run via `docker-compose` if you have the git version ready or also with a
```
docker build -f docker/Dockerfile .
docker run --rm -it IMAGE_ID
```
The last command will run without a database but it can be attached manually. Once the image is published it will be a `docker pull rapid7/metasploit-framework` instead of building it.

Things to do:
- [x] Merge https://github.com/rapid7/metasploit-framework/pull/8310 
- [x] Add `metasploit-framework` to the Rapid7 Organization on docker hub (I can help you maintain it if you like) as a git repository. This will automatically rebuild the image on every commit to a tracked branch.
- [x] Create a repository link to `ruby`. This will also rebuild the image every time the base image changes (new ruby version, updates, ..)
- [ ] Spread the word

**Comment by busterb** [comment]
Sounds good to me! I'll make an internal ticket so this gets tracked for the team that manages our Docker stuff.

**Comment by fang3anny** [comment]
Thx ur share.nice to meet you.

**Comment by nyanloutre** [comment]
I have a problem with the building of the image. It's about the line "/usr/sbin/setcap cap_net_raw,cap_net_bind_service+eip /usr/local/bin/ruby"
It seem setcap is not supported by all Docker configurations

**Comment by ilyaglow** [comment]
Hey, @nyanloutre what is your host OS and docker version?

**Comment by FireFart** [comment]
@nyanloutre what's the exact error? Can you please open a new issue about this?

**Comment by FireFart** [comment]
@busterb any news on this?

**Comment by busterb** [comment]
Getting control of `rapid7` on docker cloud was a no-go, so I created 'metasploitframework' instead. I added someone named `firefart`, hope that was you!

**Comment by FireFart** [comment]
@busterb jep that's me :)

**Comment by busterb** [comment]
Cool. Then you're an owner now too. So you should be able to push images up now. Then we can update the README / docs to point to that. I think we can probably get the build automation doing it as well. Would having Travis publish on successful master merges make sense? Something else?

**Comment by FireFart** [comment]
if we link the master branch on github to the repository it will be automatically built on each commit so there is no need to trigger it from travis.

**Comment by FireFart** [comment]
@busterb https://docs.docker.com/docker-cloud/builds/automated-build/#service-users-for-team-autobuilds

Should we create a service user to link to the Github Repo? Or do you want to link a personal account to the organization?

**Comment by busterb** [comment]
I think it makes sense to create a service user. We don't have any already created as far as I can see. Would you like to do that?

**Comment by FireFart** [comment]
as you like. If you want to keep the user in rapid 7 you need to create it (because of the password). But I can also create it.

**Comment by busterb** [comment]
Makes sense, I'll go ahead and create it so we can keep it with the other service accounts.

**Comment by FireFart** [comment]
awesome! So you need to link it on https://cloud.docker.com/swarm/metasploitframework/settings "Source providers". After that we can create the automated build

**Comment by busterb** [comment]
it turns out I don't have privileges to perform the link directly, but I put in a new request to get it done. will update when I hear something.

**Comment by busterb** [comment]
We should be good to go now.

**Comment by FireFart** [comment]
@busterb looks like the new user does not have permissions on the metasploit git repo :/

**Comment by FireFart** [comment]
Jep:
https://docs.docker.com/docker-cloud/builds/automated-build/#service-users-for-team-autobuilds
```
Note: Only members of the Owners team can set up automated builds for teams.
```
and
```
This service account should have access to any repositories that will be built, and must have administrative access to the source code repositories so it can manage deploy keys. If needed, you can limit this account to only a specific set of repositories required for a specific build.
```

**Comment by busterb** [comment]
OK, tweaked. Does it look good now?

**Comment by FireFart** [comment]
still can only see the own repos of the user. Can you try to login to https://hub.docker.com/ with the user and try the create-->automated build option in the top right corner? That's how I did my other autoamated builds

**Comment by FireFart** [comment]
@busterb I created the automated build sucessfully. I think we need to move the Dockerfile to root for this to work correctly :/ On docker cloud you can specify a build context, but that's currently not working. Will set up a PR for the Dockerfile

**Comment by FireFart** [comment]
Docker image built successfully:
https://hub.docker.com/r/metasploitframework/metasploit-framework/ (Build logs: https://hub.docker.com/r/metasploitframework/metasploit-framework/builds/bldxwfcxupbqdjcewyxctke/)

Next up: documentation on how to run it

**Comment by FireFart** [comment]
final docker changes:
https://github.com/rapid7/metasploit-framework/pull/9252

Last things to do:
Update the metasploit wiki how to use the docker image.
It will be smth like
```
wget https://raw.githubusercontent.com/rapid7/metasploit-framework/master/docker-compose.yml
docker-compose run --rm --service-ports ms
```
or checkout the Github repo and use the binstubs. I think that should be an easy way for people to get started using metasploit without installing everything manually.
I also need to document how to expose additional ports and so on (which is already covered in `docker/README.md`.

Future work could be for example to provide a docker container for the community edition as well.

**Comment by busterb** [comment]
I'm going to close this since it looks like we finished it. If not feel free to reopen.
