### ISSUE TITLE
post/windows/capture/keylog_recorder / Meterpreter keyscan API

### ISSUE THREAD

**Issue by mapagm** [rapid7/metasploit-framework#8359]
Hi,

I used to use a _**post/windows/capture/keylog_recorder**_ module. From some time my output file looks like this:

```
Keystroke log from rundll32.exe on USER with user XXX\SYSTEM started at 2017-05-08 13:45:45 +0200

**
-[ C:\Program Files\Microsoft Office\Office14\WINWORD.EXE
-[ @ monday, may 8 2017 11:57:50 UTC
**
bla bla bla

**
-[ C:\Program Files\Microsoft Office\Office14\EXCEL.EXE
-[ @ monday, may 8 2017 11:58:02 UTC
**
bla bla bla

**
-[ C:\Program Files\Microsoft Office\Office14\WINWORD.EXE
-[ @ monday, may 8 2017 11:58:30 UTC
**
bla bla bla

**
-[ C:\Program Files\Microsoft Office\Office14\WINWORD.EXE
-[ @ monday, may 8 2017 11:58:32 UTC
**
bla bla bla

**
```

Is this output file format configurable? First issue is that the time zone in the output file is incorrect (UTC instead CET in my case). Second is that i don't need a process name and time stamp in the output file - especially when time interval to save keystrokes is set on **5 seconds and module works whole day**... I tried 'show options' and 'show advanced' but there's no options of output file format... 

Is it possible to make a simple config or switch or sth to disable/enable additional information (process names and time stamps) in the output file? If not than the best solution would be a non verbose output.

**Comment by wwebb-r7** [comment]
I suspected this might be an issue to someone somewhere when I added it, but stopped short of adding it due to time.  I'll definitely take a look into adding a switch to turn it off soon though.

**Comment by mapagm** [comment]
Great! After an hour of keylog_recorder module action my output file with this aditional informations:
```
**
-[ C:\Program Files\process_name
-[ @ time stamp
**
```
has thousands of lines, of which only about 10% contains captured keystrokes. So I'm waiting for the update. Thanks.

**Comment by wwebb-r7** [comment]
For the time being, you could try something like this as a workaround:

`awk '!/^\-\[ |^\*\*$/' < log.txt > cleanlog.txt`

That will leave you with some whitespace, but things should be much more readable.

**Comment by wwebb-r7** [comment]
@mapagm the changes to Meterpreter were merged, so you should see the behavior you want from `keyscan_start` now.
