### ISSUE TITLE
Documentation update (wiki)

### ISSUE THREAD

**Issue by J0hn-** [rapid7/metasploit-framework#8362]
Hi!
I found a little mistake while I was translating the wiki page [How to get started with writing an auxiliary module](https://github.com/rapid7/metasploit-framework/wiki/How-to-get-started-with-writing-an-auxiliary-module)
"gathers" in the main categories of auxiliary modules doesn't exist anymore, it's "gather"

Furthermore, I think the « crawler » category should be removed with the only module it contains. In fact, my pr #8100 showed that the module is obsolete. The `auxiliary/scanner/http/crawler` seems to be better!

Thanks for reading!

**Comment by wvu-r7** [comment]
https://github.com/rapid7/metasploit-framework/wiki/How-to-get-started-with-writing-an-auxiliary-module/78e6b77d6b466303163c2f9f61bad378d086efb6

https://github.com/rapid7/metasploit-framework/wiki/How-to-get-started-with-writing-an-auxiliary-module/ce95afe24d0986ee8a20924d5a3a6bc0385781e9
