### ISSUE TITLE
Implement TCP UUID support in Linux stagers

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-framework#8389]
Currently, this is missing, which makes it hard to support paranoid mode with reverse_tcp. Of course, we may want to entirely rethink whether this is important, or if reverse_tcp staging is kind of an anachronism (it's hard to enhance it without breaking a lot of things that just assume 'connect and shell')

**Comment by jeffmcjunkin** [comment]
I'm completely an outsider here, but I think reverse_https is the only stager that I'd ever expect or want to use paranoid mode with.

**Comment by OJ** [comment]
The requirement for UUID support goes deeper than _just_ paranoid mode.

**Comment by busterb** [comment]
Hey, we have this! Nice!
