### ISSUE TITLE
fatal: needed a single revision

### ISSUE THREAD

**Issue by NnB01** [rapid7/metasploit-framework#8398]
## Steps to reproduce

How'd you do it?

1. sudo msfconsole

## Expected behavior

start metasploit-framework without any errors.

## Current behavior

terminal says: 
"**fatal: Needed a single revision**" and metasploit starts loading normally. 
I'm not really sure if this fatal error is able to disrupt metasploits normal operation even though it starts normally.

### Metasploit version

**metasploit v4.14.17-dev-**

### I installed Metasploit with:

ParrotSec OS 3.6 x64 bit ISO

### OS

**Parrot 3.6 JollyRoger 64-bit**

**Comment by wvu-r7** [comment]
Try posting a screenshot. That error sounds like it's coming from `git rebase`, which is a strange thing to be seeing when you start `msfconsole`.

**Comment by busterb** [comment]
If this is a native 'ParrotSec OS' package, please contact the maintainer rather than us. It sounds like they have a problem with how Metasploit is packaged. If they are packaging Metasploit without the .git directory, they need to apply a patch like this:

https://github.com/rapid7/metasploit-omnibus/blob/master/config/patches/metasploit-framework/no-git.diff

**Comment by wvu-r7** [comment]
Yeah, this is definitely not a Metasploit bug.

**Comment by NnB01** [comment]
![github](https://cloud.githubusercontent.com/assets/21063734/26136889/466dd40a-3ac7-11e7-93a1-a62658362d4c.png)

This is exactly what happens. I made also another test to make sure that this is not a maintainer problem, i ran same iso on a live usb and ran metasploit, no message like this appeared. Also i'm pretty sure that this started when i downloaded and installed other tools with git method (like MITMf-framework).

**Comment by wvu-r7** [comment]
`strace` it. ¯\\\_(ツ)\_/¯

**Comment by busterb** [comment]
Pretty sure the patch above is at least part of the answer.

**Comment by NnB01** [comment]
No doubt, but how can i use that please?

**Comment by wvu-r7** [comment]
The diff above is for our Omnibus package. If you want to use it, you want to talk to the package maintainer for your distro.

**Comment by 5P4D3** [comment]
still waiting for the fix :(

**Comment by busterb** [comment]
I think I showed you what to do, and the fix isn't likely to come from us - it's in your distro packager. Can you point where the ParrotSec bug tracker is? I'll file a report there.

**Comment by Calabrase** [comment]
Am sorry, I am a novice to Linux.  After problems with the git repo. Am now having this error above 'fatal: Needed a single revision. You pointed to talk with Package maintainer. How can I reach mine, for same distro

**Comment by busterb** [comment]
go here: https://community.parrotsec.org/ post a message
