### ISSUE TITLE
Some issue on every Auxiliary modules parsing RHOSTS

### ISSUE THREAD

**Issue by BlackMathIT** [rapid7/metasploit-framework#8408]
Every auxiliary module fails to validate RHOSTS passing a file or single occurrency when one or more of the target machine aren't available on the network, receiving the "Auxiliary failed:Msf::OptionValidateError The following options failed to validate: RHOSTS" error.

We suppose the module have some issue when it encounters a not solved dnsname as unique entry or inside a file list, so this stops the start of the module without parsing anything. 
Obviously we would like to expects to skip the bad entry or entries and then go on when it happen..

## Steps to reproduce
msf auxiliary(smb_ms17_010) > set rhosts fakeMachineName, rightMachineName
msf auxiliary(smb_ms17_010) > run
[-] Auxiliary failed: Msf::OptionValidateError The following options failed to validate: RHOSTS.

### Metasploit version
Framework: 4.14.16-dev
Console  : 4.14.16-dev

same on:
Framework: 4.14.17-dev
Console  : 4.14.17-dev

### I installed Metasploit with:
- [x] Kali package via apt

### OS
 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux

**Comment by busterb** [comment]
@clee-r7 / @darkbushido this fits right in your wheelhouse

**Comment by BlackMathIT** [comment]
We thing there is something wrong because if we want to scan a list of machines entries of a domain it's unbeliveable that we have to check if they are alive on the net before....

**Comment by busterb** [comment]
It don't believe it checks if they are alive, it just tries to convert the DNS entries into IP addresses. I'm guessing your file contains a list of hostnames?

**Comment by BlackMathIT** [comment]
You right, as we have written in the first post "We suppose the module have some issue when it encounters a not solved dnsname" so we are telling the same... in any case yes we have a list of hostnames

**Comment by carnal0wnage** [comment]
ran into this awhile back. here is my workaround  http://carnal0wnage.attackresearch.com/2015/08/metasploit-vhosts-in-mass.html
