### ISSUE TITLE
Fix file download to avoid timeouts

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-framework#8427]
If you're operating within a Meterpreter session that is using a slow or stateless transport (such as HTTPS), and you attempt to download a large file (eg. 5MB) then the Meterpreter `download` command will time out.

Instead of operating the same way as a typical command, the `download` command should probably make use of channels, or have some kind of batching interface in place so that the command does not time out.

**Comment by busterb** [comment]
Hey @OJ we had a fix for this that we then backed out because it then caused packet ordering problems with reverse_tcp.

**Comment by busterb** [comment]
See #7993

**Comment by OJ** [comment]
Ooh yeah! Sorry about that.

**Comment by OJ** [comment]
I think it's fair to say that the download issue that I was having has been fixed in the recent change to the downloads command that does adaptive downloading. Closing.
