### ISSUE TITLE
sessions -u should work on meterpreter sessions

### ISSUE THREAD

**Issue by timwr** [rapid7/metasploit-framework#8436]
Currently sessions -u doesn't work on meterpreter sessions.
I suggest we do the following:
1. Fix shell_to_meterpreter to support armle, x64, etc, linux meterpreter
2. Create a new module called upgrade_meterpreter that attempts to launch a bare mettle meterpreter session that is as close to target architecture/platform as possible, e.g:
Android meterpreter -> armle/x86/x64 linux meterpreter
Java meterpreter (on Windows) -> windows meterpreter
Java meterpreter (on Linux) -> armle/x86/x64 linux meterpreter
Python meterpreter (on Linux) -> armle/x86/x64 linux meterpreter
If you're already on the closest match it could simply open a new session of the same type.

**Comment by fsacer** [comment]
That was annoying as hell, had to drop executables in order to get fully featured windows meterpreter from java one (i think it was tomcat or something from metasploitable3). This should really be fixed.
