### ISSUE TITLE
Fail to load module (syntax error)

### ISSUE THREAD

**Issue by tijnar33** [rapid7/metasploit-framework#8440]
after I added the smb_ms17_010 script file into my metasploit framework and load the msfconsole I got the error like this (see image). I am running kalilinux rolling.
![screenshot from 2017-05-23 12-30-53](https://cloud.githubusercontent.com/assets/25560324/26341489/cea87a28-3fb3-11e7-8654-82e2c7088f15.png)

**Comment by void-in** [comment]
Dup of https://github.com/rapid7/metasploit-framework/issues/8441
