### ISSUE TITLE
Fail to load module (syntax error)

### ISSUE THREAD

**Issue by tijnar33** [rapid7/metasploit-framework#8441]
after I added the smb_ms17_010 script file into my metasploit framework and load the msfconsole I got the error like this (see image). I am running kalilinux rolling.
![screenshot from 2017-05-23 12-30-53](https://cloud.githubusercontent.com/assets/25560324/26341592/4d899822-3fb4-11e7-9f8c-74bd8f656bcd.png)

**Comment by void-in** [comment]
You have downloaded the html file that is displayed on the Github page. The module has been merged within the msf tree and should be available to Kali users as well. Run msfupdate or apt-get update and Kali should pick up the updated version.

If you have other support queries, please use https://community.rapid7.com
