### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by 5P4D3** [rapid7/metasploit-framework#8443]
Everytime i open my Metasploit.. it always shows this

`fatal: Not a git repository (or any of the parent directories): .git`

How to fix this?

**Comment by 5P4D3** [comment]
My MSF Version

```
Framework: 4.14.21-dev
Console  : 4.14.21-dev
```
![screenshot at 2017-05-23 21-04-03](https://cloud.githubusercontent.com/assets/18681023/26355492/88018978-3ffb-11e7-96ce-fa43bdd83d29.png)

**Comment by h00die** [comment]
While it's a different error, please check https://github.com/rapid7/metasploit-framework/issues/8398 they're most likely related, the fix may also work, or please put in a ticket with the OS creator

**Comment by wvu-r7** [comment]
You need to provide more details, @5P4D3. What distro? How did you install Metasploit?

**Comment by wvu-r7** [comment]
Oh, it's Parrot. Please file a ticket with them.

**Comment by FireFart** [comment]
Just a hint: the metasploit gemspec file contains a `git ls` to get the repository files (`git ls` uses `.gitignore` so non repo files are omitted). You will see the same message when using the docker image. There is also this issue where we tried to get rid of it but it caused problems with omnibus and metasploit pro: https://github.com/rapid7/metasploit-framework/pull/8048

**Comment by 5P4D3** [comment]
its Parrot Sec 3.6 - Jolly Roger

**Comment by Calabrase** [comment]
I also have the same error and I'm still waiting for the answer. It was pre installed and I ran the updates

**Comment by busterb** [comment]
You will have to insist that the ParrotSec packager either fix the issue remotely, or at least update to a later version of metasploit, where we added ParrotSec-specific workarounds (see PR above). Not much more we can do here.
