### ISSUE TITLE
/usr/bin/msfupdate:275:in `update_apt!': undefined method `blank?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by NitroMS** [rapid7/metasploit-framework#8448]
## Steps to reproduce

run msfupdate from kali linux 2017.1

I have metasploit v4.14.21-dev in kali linux 2017.1, when i try msfupdate this is what i get.
![msfupdate](https://cloud.githubusercontent.com/assets/28870268/26416917/ca01f3aa-40b7-11e7-94cd-161672890b4e.png)

**Comment by busterb** [comment]
workaround - there's no reason to run 'msfupdate' on kali at all. It's a normal package, just use `apt-get update; apt-get upgrade`

**Comment by NitroMS** [comment]
@busterb Thanks, i will try that

**Comment by FireFart** [comment]
@busterb what do you think about opening an issue on the kali bugtracker so msfupdate will be removed from the package if it's not needed? The current rule file is available from https://pkg.kali.org/pkg/metasploit-framework (https://pkg.kali.org/media/packages/m/metasploit-framework/rules-4.14.21-0kali1)

**Comment by busterb** [comment]
Yeah, that seems reasonable to me.

**Comment by FireFart** [comment]
@busterb can you do it or should we add the bug?

**Comment by busterb** [comment]
Please do @FireFart , I totally forgot what my Kali bugtracker credentials are.

**Comment by FireFart** [comment]
@busterb done: https://bugs.kali.org/view.php?id=4039

**Comment by FireFart** [comment]
@busterb msfupdate should be gone in the next release: https://bugs.kali.org/view.php?id=4039
