### ISSUE TITLE
The Nightly's are broken

### ISSUE THREAD

**Issue by BustedSec** [rapid7/metasploit-framework#8454]
trying to update a nightly build with apt-get update on ubuntu 16.04 and 17.04 fails due to file not found.  Browsing https://apt.metasploit.com/ shows the actual links themselves are broken as well, 

Using fresh install of ubuntu 16.04 with doing curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall &&   chmod 755 msfinstall &&   ./msfinstall produces this output:

sudo apt-get install -y --force-yes metasploit-framework
[sudo] password for havok: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package metasploit-framework

 cat /etc/apt/sources.list.d/metasploit-framework.listdeb http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid main

uname -a
Linux Bustedsec 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by busterb** [comment]
Should be good to go again. We had one job stepping on the other, which is why the arm package indexes were valid, but the x86 ones were empty. I merged them into one. Thanks @BustedSec

**Comment by BustedSec** [comment]
@busterb thanks for fixing so quick.

**Comment by CamPerry** [comment]
This appears to be happening again with the latest nightly installers. Running into the same exact issue when attempting to use the nightly installer on Ubuntu 16.04.
