### ISSUE TITLE
Kali Linux - msfupdate error.

### ISSUE THREAD

**Issue by Mas0x** [rapid7/metasploit-framework#8463]
Command msfupdate - Kali Linux (Rolling)

root@kali:~# msfupdate
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via the APT repository
[*] Note: expect weekly(ish) updates using this method
/usr/bin/msfupdate:275:in `update_apt!': undefined method `blank?' for nil:NilClass (NoMethodError)
	from /usr/bin/msfupdate:140:in `block in run!'
	from /usr/bin/msfupdate:134:in `chdir'
	from /usr/bin/msfupdate:134:in `run!'
	from /usr/bin/msfupdate:326:in `<main>'

I read somewhere that Kali is 1 month behind the latest releases?

**Comment by FireFart** [comment]
@Mas0x this was discussed here: https://github.com/rapid7/metasploit-framework/issues/8448
msfupdate is not needed on kali linux. We also filled a bug so the msfupdate binary will be removed so people will not try to update via it.

**Comment by hougomartim** [comment]
root@sulands:~# msfupdate
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via the APT repository
[*] Note: expect weekly(ish) updates using this method
W: GPG error: http://http.kali.org kali-rolling Release: The following signatures were invalid: KEYEXPIRED 1425567400 KEYEXPIRED 1425567400 KEYEXPIRED 1425567400


how i can fix it?

**Comment by FireFart** [comment]
@hougomartim please see the comment above yours

**Comment by busterb** [comment]
Hmm, looks like Kali's GPG key has expired. Raise the issue with the Kali support forums.

**Comment by LordReaperY** [comment]
Traceback (most recent call last):
        3: from ./msfupdate:315:in `<main>'
        2: from ./msfupdate:136:in `run!'
        1: from ./msfupdate:136:in `chdir'
./msfupdate:145:in `block in run!': Cannot determine checkout type: `.' (RuntimeError)

**Comment by pr0b3r7** [comment]
> Traceback (most recent call last):
> 3: from ./msfupdate:315:in `<main>' 2: from ./msfupdate:136:in `run!'
> 1: from ./msfupdate:136:in `chdir' ./msfupdate:145:in `block in run!': Cannot determine checkout type: `.' (RuntimeError)

I'm suffering from this at the moment as well on macOS
