### ISSUE TITLE
Metasploit Not updating in Kali Linux 2017 Version

### ISSUE THREAD

**Issue by P3t3rp4rk3r** [rapid7/metasploit-framework#8469]
$ sudo apt-get update & apt-get upgrade
$msfupdate 
it's not working fine 
Please find the below image
[
![msferror](https://cloud.githubusercontent.com/assets/7028794/26517761/108e841c-42bd-11e7-8129-007047f74650.PNG)
](url)

**Comment by busterb** [comment]
There is no reason to run msfupdate. apt-get upgrade already updated you to the latest package in Kali Linux.

**Comment by mddypaul** [comment]
root@kali:~# msfupdate
msfupdate is no longer supported when Metasploit is part of the operating
system. Please use 'apt update; apt install metasploit-framework'

Now What I will do? Please help me

**Comment by busterb** [comment]
It says what to do: _Please use 'apt update; apt install metasploit-framework'_

**Comment by blackghostt** [comment]
wont work cause apt-secure gives me an error on certificate risk , sombeody know how ti disable this risk on apt secure  ?
