### ISSUE TITLE
msfupdate error user.name is not set in your global git configuration

### ISSUE THREAD

**Issue by macbook47** [rapid7/metasploit-framework#8472]
cannot update metasploit through msfupdate, got error : 
[-] ERROR: user.name is not set in your global git configuration
[-] Set it by running: 'git config --global user.name "NAME HERE"'

Metasploit version: v4.14.22-dev-18f5203
OS : MacOs 10.10.5  Yosemite Darwin Kernel Version 14.5.0

**Comment by busterb** [comment]
Have you tried doing what it says?

**Comment by S9pY** [comment]
git config --global user.name "your github username"
git config --global email.name "your github primary email"
./msfupdate :)

**Comment by Budiono55** [comment]
I already do that, but still, it says

[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via git
[*] Note: Updating from bleeding edge
[-] ERROR: user.email is not set in your global git configuration
[-] Set it by running: 'git config --global user.email "email@example.com"'

**Comment by armalitedev** [comment]
> I already do that, but still, it says
> 
> [_] Attempting to update the Metasploit Framework... [_]
> 
> [_] Checking for updates via git [_] Note: Updating from bleeding edge
> [-] ERROR: user.email is not set in your global git configuration
> [-] Set it by running: 'git config --global user.email "[email@example.com](mailto:email@example.com)"'

same problem here
