### ISSUE TITLE
Post Module (gnome_keyring_dump) - stdapi_railgun_api error.

### ISSUE THREAD

**Issue by upgoingstar** [rapid7/metasploit-framework#8479]
## Steps to reproduce
Gain a linux meterpreter shell on a x86/x64 bit linux box. 
How'd you do it?

1. Took a meterpreter session on linux box using msfvenom - elf type payload.
2. Used meterpreter to run the gnome_keyring_dump module.

## Expected behavior

Should have executed the post module without error and dump gnome keys. 

## Current behavior

Throwing an error.

meterpreter > sysinfo
Computer     : 192.168.1.108
OS           : Kali kali-rolling (Linux 4.9.0-kali3-amd64)
Architecture : x64
Meterpreter  : x64/linux
meterpreter > run post/linux/gather/gnome_keyring_dump

[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_railgun_api: Operation failed: 1
[-] Call stack:
[-]   /usr/local/share/metasploit-framework-master/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:266:in `process_function_call'
[-]   /usr/local/share/metasploit-framework-master/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:84:in `call_function'
[-]   /usr/local/share/metasploit-framework-master/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll_wrapper.rb:24:in `method_missing'
[-]   /usr/local/share/metasploit-framework-master/modules/post/linux/gather/gnome_keyring_dump.rb:195:in `run'

### Metasploit version - 

 metasploit v4.14.22-dev

### I installed Metasploit with:
- [ ] Source install (please specify ruby version)                                                                              
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

### OS

MacOS Sierra

**Comment by upgoingstar** [comment]
Looks like I was trying with wrong meterpreter, this works with python meterpreter only.

**Comment by void-in** [comment]
Re-opening since this is an issue with the native meterpreter. IIRC the railgun API is only available on the python meterpreter at the moment so the platform of the module should be changed from linux to python. /cc @zeroSteiner

**Comment by Hyperion101010** [comment]
hi there i am an undergrad in computer science , i am looking forward to contribute for metasploit
what is there to contribute in for this bug ,can i help ?

**Comment by h00die** [comment]
Absolutely!  While Rapid7 owns the project and has a bunch of developers that do much of the main work, LOTS of the code is from volunteers (like myself).  Check out the awesome docs on how to get started here: https://github.com/rapid7/metasploit-framework/wiki/Contributing-to-Metasploit

If you need further help, check the IRC channel.

**Comment by d4v3y0rk** [comment]
everything I am finding about railgun says it is a windows only post feature... that would make sense since it is trying to use DLLs and as far as I know linux systems don't use Windows DLLs. Also in the railgun.rb file it references windows and the railgun.rb file itself is in the `core/post/windows` folder.
