### ISSUE TITLE
creds -R fails with error

### ISSUE THREAD

**Issue by tfriesen** [rapid7/metasploit-framework#8496]
## Steps to reproduce

1. msfconsole
2. creds -R

Fails with or without creds in the db and with or without other options to 'creds'.

## Expected behavior

All hosts stored in the creds db are added to RHOSTS, same as 'services' and 'hosts' commands

## Current behavior

```
msf > creds -R
Credentials
===========

host  origin  service  public  private  realm  private_type
----  ------  -------  ------  -------  -----  ------------

[-] Error while running command creds: undefined method `set_rhosts_from_addrs' for #<Msf::Ui::Console::CommandDispatcher::Creds:0x00559e16659258>

Call stack:
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:493:in `block in creds_search'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:383:in `creds_search'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:110:in `cmd_creds'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
msf > 
```

### Metasploit version

Framework: 4.14.22-dev
Console  : 4.14.22-dev

### I installed Metasploit with:
- [X] Kali package via apt

### OS

Kali-rolling (up to date).

It seems that lib/msf/ui/console/command_dispatcher/creds.rb fails to properly include the 'set_rhosts_from_addrs' function from lib/msf/ui/console/command_dispatcher/db.rb. Function is called on line 493 in creds.rb, and is defined on line 1726 in db.rb.

**Comment by wvu-r7** [comment]
#7655

**Comment by tfriesen** [comment]
[#8493](https://github.com/rapid7/metasploit-framework/pull/8493)

This is what I get for putting off reporting a bug for a day, and then not checking the pull requests first :)

**Comment by wvu-r7** [comment]
Oops, this is actually related to #7804. Similar issue, though.
