### ISSUE TITLE
unable to start metasploit errors

### ISSUE THREAD

**Issue by tehseensagar** [rapid7/metasploit-framework#8497]
Unable to start metasploit keep getting following errors

root@local:/opt/metasploit-framework# ./msfconsole
/opt/metasploit-framework/config/boot.rb:19: undefined method `to_path' for #<Pathname:/opt/metasploit-framework/Gemfile> (NoMethodError)
        from /opt/metasploit-framework/config/boot.rb:15:in `each'
        from /opt/metasploit-framework/config/boot.rb:15
        from ./msfconsole:45:in `require'
        from ./msfconsole:45

metasploit version latest:
ruby -v : ruby 1.8.7
gem -v : 1.3.7
bundle -v : Bundler version 1.15.0

ubuntu 14

Looking forward to your kind response guys,

Regards

**Comment by busterb** [comment]
Ruby 1.8.7 is definitely not supported. 2.4 is preferred. Try installing at least ruby 2.1, or grabbing our pre-built packages: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
