### ISSUE TITLE
msfconsole on UTF-8 terminal does not echo back text correctly on tab-completion, backspace

### ISSUE THREAD

**Issue by dougives** [rapid7/metasploit-framework#8505]
## Steps to reproduce

I'm using msfconsole on kali-rolling with urxvt from kali's repos. When using a utf-8 terminal, tab-completion will overwrite a displayed character. Using backspace also causes inconsistencies. Occasionally tabbing will also clear the screen, but I could not reproduce it. Inputting single-byte characters will cause this effect.

## Expected behavior

Console echos expected input.

## Current behavior

See video: http://dou.gives/msbug.mp4 (I know it's tough to gauge what I'm inputting. 'set' at :35 is affected by backspace, along with the following 'use'. Let me know if you have any questions.)

When hitting tab for completion, characters are dropped from the displayed buffer, but retained when entering the command. It's very confusing.

### Metasploit version

4.14.23-dev

### I installed Metasploit with:
- [ x ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

linux 4.9.0-kali4-amd64, kali-rolling, current as of 2 July 2017.

Also, I am using fcitx, and the problem occurs when using US English input. I have pinyin input installed, but have not tried using it with msfconsole.

I believe this issue is related: https://github.com/rapid7/metasploit-framework/issues/7986

**Comment by dougives** [comment]
I happened to set up msf from source on ubuntu server 17.04 this morning with urxvt and scim instead, and it does not have this issue.

**Comment by busterb** [comment]
Seems this is probably resolved with latest. Reopen if not.

**Comment by dehinde007** [comment]
Hi @busterb i'm using windows 7 and running metasploit version 4.17.0 on a 32 bit system. When i load into the msfconsole and get to type something, i cannot backspace or delete my text. Also when i try to set my RHOST option, it doesn't allow me write a full ipaddress. I tried pasting the ipaddress but it just put more random numbers.
