### ISSUE TITLE
smb_login issue: RubySMB::Error::NetBiosSessionService NBSS Header is missing

### ISSUE THREAD

**Issue by shawndeckerr** [rapid7/metasploit-framework#8521]
## Steps to reproduce
The auxiliary/scanner/smb/smb_login module throws a RubySMB error when used. This works perfect on my previous version of Kali Linux until I installed a new version and updated Metasploit.

Issue: Using the auxiliary/scanner/smb/smb_login module, the scanner comes up with a RubySMB error that reads: 
[*] Error: 192.168.20.203 RubySMB::Error::NetBiosSessionService NBSS Header is missing

Expected behavior: The usual / expected output reads:
[+] 192.168.20.203:445      - SMB - Success: 'Test\administrator:password' - Administrator

The output in .msf4/logs/framework.log is:
[06/07/2017 07:49:28] [e(0)] core: Error running against host 192.168.20.203: NBSS Header is missing
usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/dispatcher/socket.rb:49:in `recv_packet'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/client.rb:229:in `send_recv'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/client/authentication.rb:264:in `smb2_ntlmssp_authenticate'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/client/authentication.rb:191:in `smb2_authenticate'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/client/authentication.rb:19:in `authenticate'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/ruby_smb-0.0.17/lib/ruby_smb/client.rb:187:in `login'
/usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/smb.rb:101:in `attempt_login'
/usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/smb.rb:72:in `attempt_bogus_login'
/usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_login.rb:84:in `run_host'
/usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'

System Details include:
- Currently using Metasploit Framework version 4.14.23-dev on Kali Linux version '4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64'. 
- Installed this and updated a day ago. The ruby version is ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

**Comment by dmaloney-r7** [comment]
@shawndeckerr what kind of target system are you running this against, and can you provide a pcap of it happening?  I cannot reproduce this issue

**Comment by shawndeckerr** [comment]
@dmaloney-r7 I'm running this on a Windows Server 2008 Standard server and a Windows 7 PC. 
Looking at the pcaps, I see the status shows a LOGON_FAILURE but Metasploit returns a NBSS Header error. Also I noticed that this issue happens when I run the module against multiple targets. I ran this against 11 targets. For instance:
_set RHOSTS 192.168.20.23 192.168.20.24 192.168.20.25 192.168.20.26 192.168.20.27 ..._

However, when I run the module by setting a single target, I obtain the expected result.
[test.zip](https://github.com/rapid7/metasploit-framework/files/1079126/test.zip)
![image](https://user-images.githubusercontent.com/29239818/27203726-7d948220-526a-11e7-9729-0ff3af161d94.png)

I'll do a bit more testing over the weekend and try to pinpoint where this happens as it appears a bit unstable to reproduce.

**Comment by shawndeckerr** [comment]
Did some more testing on this and found out that for some reason, when I have a large number of hosts in my RHOSTS, I get these errors, so I had to throttle down a notch. Started with one IP in the RHOSTS and ramped up to 4 in a go. And this appears to work around the issue. Keen to hear others' opinions.
