### ISSUE TITLE
modules/auxiliary/gather/konica_minolta_pwd_extract.rb

### ISSUE THREAD

**Issue by ss23** [rapid7/metasploit-framework#8522]
## Steps to reproduce

How'd you do it?

1. Run modules/auxiliary/gather/konica_minolta_pwd_extract.rb against a Konica Minolta C654
2. Observe an error:
```
[*] Attempting to extract username and password from the host at 192.168.x.x:50001
[+] SMB Account:User=redacted:Password=redacted:Host=redacted-fs01:Port=139
[*] Error: 192.168.x.x: ActiveRecord::StatementInvalid PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "redacted-fs01"
: SELECT  "hosts".* FROM "hosts" WHERE "hosts"."address" = $1 AND "hosts"."workspace_id" = $2  ORDER BY "hosts"."id" ASC LIMIT 1
```

When fixing this bug, it might also be useful to add C654 to the list of supported printers.

I was able to easily work around this issue by changing the "register_creds" to simply return before execution.

### Metasploit version

Framework: 4.14.24-dev
Console  : 4.14.24-dev

### I installed Metasploit with:
Kali via apt

**Comment by wvu-r7** [comment]
I think it needs to be an IP. The module is scraping the result straight from XML.
