### ISSUE TITLE
many modules assume the Windows target language is English

### ISSUE THREAD

**Issue by nexusbruno2001** [rapid7/metasploit-framework#8537]
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/credentials/steam.rb

You need to make us able to change the _Path_

For example mine it's not **C:\Program Files (x86)\**

It's **C:\Programas (x86)\**

**Comment by h00die** [comment]
This is actually all over the place, just a few examples of where it would need to also be fixed:
https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/credentials/smartermail.rb#L73
https://github.com/rapid7/metasploit-framework/blob/97095ab3113de2f046e64a64c461a1f888554401/modules/post/multi/manage/dbvis_add_db_admin.rb#L168
https://github.com/rapid7/metasploit-framework/blob/97095ab3113de2f046e64a64c461a1f888554401/modules/post/multi/manage/dbvis_query.rb#L159
https://github.com/rapid7/metasploit-framework/blob/97095ab3113de2f046e64a64c461a1f888554401/modules/post/windows/gather/credentials/bulletproof_ftp.rb#L243

**Comment by bcoles** [comment]
Yeah there's a bunch of these.

For post modules, there's a few ways to retrieve the directories, but they too may only work on English systems.

It seems most post modules use one or more of these environment variables:

* `%ProgramFiles%`
* `%ProgramFiles(x86)%`
* `%ProgramW6432%`

Like so:

```
progfiles_env = session.sys.config.getenvs('ProgramFiles(X86)', 'ProgramFiles')
```

Perhaps it would be best to allow users to specify the directory as a fallback.

**Comment by nexusbruno2001** [comment]
Thank's
