### ISSUE TITLE
chinese character in meterpreter has become garbnle

### ISSUE THREAD

**Issue by kerlingcode** [rapid7/metasploit-framework#8552]
i need to download a file in Chinese
but the response is
![pics](https://user-images.githubusercontent.com/21171415/27085242-510f1c46-5081-11e7-8fd5-e97a86cd0de2.png)

it is my bad on configuring the client?

**Comment by wvu-r7** [comment]
Are you running Metasploit on Windows?

**Comment by kerlingcode** [comment]
yep ,i'm running on the windows by the pentestbox  
and the target is also running on the windows7 system
what should i do?

**Comment by busterb** [comment]
This is an intentional default setting for windows, since the command prompt used to not support Unicode. You can try `set EnableUnicodeEncoding false` in before you start the session. I'm not sure what terminal Pentestbox uses, it might work.
