### ISSUE TITLE
mysql_login issue

### ISSUE THREAD

**Issue by CubanCigar** [rapid7/metasploit-framework#8583]
> msf auxiliary(mysql_login) > run 
> 
> [*] 192.168.56.102:3306     - 192.168.56.102:3306 - Found remote My SQL version 5.0.51a
> [*] Error: 192.168.56.102: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::MSSQL)
> [*] Scanned 1 of 1 hosts (100% complete)
> [*] Auxiliary module execution completed

## Expected behavior

https://www.offensive-security.com/metasploit-unleashed/using-databases/#Creds
Following this and it should successfully complete but its not.

Can't figure out whats wrong? Can anyone please advise?

### Metasploit version
v4.14.25-dev

### OS
VM VirtualBox

Thanks

**Comment by void-in** [comment]
How have you configured the module? run ```show options``` before running the module and paste the output. It seems you haven't configured the username/password (or username/password lists) of the module.

**Comment by CubanCigar** [comment]
Here you go:

```
msf auxiliary(mysql_login) > show options

Module options (auxiliary/scanner/mysql/mysql_login):

   Name              Current Setting  Required  Description
   ----              ---------------  --------  -----------
   BLANK_PASSWORDS   false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false            no        Add all passwords in the current database to the list
   DB_ALL_USERS      false            no        Add all users in the current database to the list
   PASSWORD                           no        A specific password to authenticate with
   PASS_FILE                          no        File containing passwords, one per line
   Proxies                            no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            192.168.56.102   yes       The target address range or CIDR identifier
   RPORT             3306             yes       The target port (TCP)
   STOP_ON_SUCCESS   false            yes       Stop guessing when a credential works for a host
   THREADS           1                yes       The number of concurrent threads
   USERNAME                           no        A specific username to authenticate as
   USERPASS_FILE                      no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false            no        Try the username as the password for all users
   USER_FILE                          no        File containing usernames, one per line
   VERBOSE           true             yes       Whether to print output for all attempts
```

**Comment by CubanCigar** [comment]
I tried that still same issue:
```
msf auxiliary(mysql_login) > run

[*] 192.168.56.102:3306   - 192.168.56.102:3306 - Found remote MySQL version 5.0.51a
[-] 192.168.56.102:3306   - 192.168.56.102:3306 - LOGIN FAILED: root:root (Incorrect: Access denied for user 'root'@'192.168.56.1' (using password: YES))
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by void-in** [comment]
That is the intended behavior. The root:root isn't the correct credential of the MySQL configured on the target server. If you have problem understanding the functionality of the module, please ask at https://community.rapid7.com

**Comment by CubanCigar** [comment]
Ok thank you for taking time to help me out - I will check it out - cheers.

**Comment by MathiasHaudgaard** [comment]
Instead of setting the password, you can easily set BLANK_PASSWORDS to true. This will cause the module to try a blank password for all the users and you should be able to continue the tutorial.

**Comment by flintcave** [comment]
I don't know if this will help anyone, but I'm going through the same tutorial using msf5 and this is what I had to set to get this specific step in the tutorial to work.

set BLANK_PASSWORDS true
set USERNAME root
set PASSWORD ""
