### ISSUE TITLE
Timestomp error

### ISSUE THREAD

**Issue by jtingkir** [rapid7/metasploit-framework#8588]
## Steps to reproduce
I did timestomp to a windows 7 32 bit file located in "c:\" from a reverse_http meterpreter. Before I've loaded the priv and also do getsystem.
I ran several timestomp command
step 1. timestomp text.txt -c "[dates]"
step 2. timestomp text.txt -b
step 3. timestomp text.txt -v 

Timestomp result error as following:
step 1. Error running command timestomp: NoMethodError undefined method 'match' for nil:NilClass Did you mean? catch
step 2. no error, but didn't blank the MACE
step 3. no error (MACE didn't change).

![timestomp_issue](https://user-images.githubusercontent.com/7327767/27353386-b54d7c78-55fb-11e7-81cc-40f9a6526ab6.png)

note: timestomp -f didn't work either
![timestomp_issue 2](https://user-images.githubusercontent.com/7327767/27353468-fedd2df2-55fb-11e7-8f32-30db59052200.png)

### Metasploit version
4.14.25
Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
kali 2017.1

**Comment by busterb** [comment]
I'll take a look, I touched this code last = new timestomp maintainer :)

**Comment by jtingkir** [comment]
I don't know if this will help or not, but:
1. timestomp -f original_file target_file => works on user directory (desktop, documents) not so much on any other directory below c:\
2. timestomp target_file -f original_file => didn't work anywhere
3. timestomp target_file -b & timestomp -b target_file => didn't work anywhere
4. timestomp target_file -c "01/01/01 01:01:01 AM" => didn't work anywhere

I don't know why number (1) works, but getsystem had no problem, and migrating to SYSTEM process  had no problem too.

**Comment by busterb** [comment]
The problem appears to be with the argument parser. It assumes that the file always comes at the _end_, not the beginning. So, when it parses

`timestomp test.txt -c "01/01/2001 01:01:01"`

it sees "01/01/2001 01:01:01" as the filename and removes it from the argument string 👎 
As a workaround, reverse your arguments: timestomp -c "01/01/2001 01:01:01" test.txt

**Comment by busterb** [comment]
This doesn't appear to have been a regression, but the usage was not very intuitive. I submitted a PR above to make the usage more robust regarding path placement.
