### ISSUE TITLE
Meterpreter has difficulty backgrounding channels on bad connections

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#8619]
![image](https://user-images.githubusercontent.com/1756255/27567468-be1781a6-5aa0-11e7-8c26-adc6bc57c553.png)

On a gig, where the target laptop is owned by a person who goes to lots of meetings, shell sessions will hang when they shut their mac and get in an elevator. When I hit control-z to background that channel, meterpreter seems to choke, and has quite a lot of trouble backgrounding a channel and letting me move on to other sessions which are still connected. 

The 'hung state' takes probably ~2 minutes to get out of, and so far the only thing I've found that works is essentially buttonmashing control-z, and control-c, whereby at some point I get the meterpreter> prompt back again and I can continue to use metasploit.

**Comment by busterb** [comment]
So, we should be able to background in the background! I often use Ctrl-\ subconsciously, but should implement a real way out.

**Comment by fsacer** [comment]
close @busterb
