### ISSUE TITLE
bug report:post/windows/gather/forensics/browser_history

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#8636]
metasploit v4.14.27-dev-55f0edb732 

meterpreter > sysinfo\r
Computer        : 2012-0705-1726
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : zh_CN
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows
sysinfo\r
Computer        : 2012-0705-1726
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x64
System Language : zh_CN
Domain          : WORKGROUP
Logged On Users : 1
Meterpreter     : x64/windows

run post/windows/gather/forensics/browser_history\r

[*] Gathering user profiles
[*] Checking for Chrome History artifacts...
[+] Chrome History directory found Administrator
[*] Downloading C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\History
[-] Post failed: NoMethodError undefined method `[]' for nil:NilClass
[-] Call stack:
[-]   /Users//metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb:376:in `download_file'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:94:in `block in download_artifact'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:87:in `each'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:87:in `download_artifact'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:48:in `block (2 levels) in run'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:48:in `each'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:48:in `block in run'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:47:in `each'
[-]   /Users//metasploit-framework/modules/post/windows/gather/forensics/browser_history.rb:47:in `run'

**Comment by wchen-r7** [comment]
This bug seems legit. I will pick it up. Thanks.

**Comment by wchen-r7** [comment]
Patch is in the queue for review.
