### ISSUE TITLE
Auxiliary jboss_vunlscan good print_status hard-coded verb 

### ISSUE THREAD

**Issue by frankabjr** [rapid7/metasploit-framework#8651]
## Steps to reproduce

On the module jboss_vulnscan, there is an option to set a different HTTP VERB to try to bypass the jboss authentication. 

If you set a different HTTP verb to try the authentication bypass, the print_status still showing the default option (HEAD), instead of showing the current configured one. 

## Expected behavior

The module should print the current configured VERB value, instead of the default one. 

## Current behavior

Currently the module is always printing the message "Checking for verb tampering (HEAD)"

## System stuff

metasploit-framework/blob/master/modules/auxiliary/scanner/http/jboss_vulnscan.rb
line: 188

### Metasploit version

Framework: 4.15.0-dev-aceeedc
Console 4.15.0-dev-aceeedc

### OS

Debian

**Comment by wvu-r7** [comment]
If you have a patch, submit a pull request!
