### ISSUE TITLE
Feature Request: Domain Fronting for meterpreter/mettle

### ISSUE THREAD

**Issue by Viss** [rapid7/metasploit-framework#8656]
It would be really amazing to allow meterpreter, when using the http or https transports, to take advantage of domain fronting. This SHOULD only require the addition of a custom host header to the outbound requests. I am not familiar enough with the meterpreter internals to be able to say if it affects other components of meterpreter, or would cause a problem, though.

Just wishful thinking :D

**Comment by sempervictus** [comment]
Ping @OJ: this shouldn't be too hard on the transport side, right? Error handling for inaccessible hosts on the shared front end might be hairy, but the concept just requires tls to the front end with http host request targeting something other than the original TLS endpoint. Not sure how that plays on wininet/winhttp though - do they have faculties for http requests being separate from the TLS init?

**Comment by OJ** [comment]
I need to look into it. It has been on my to-do list for a while to add
support for arbitrary headers in web requests. We need to give more
flexibility there. The Host header might be a different beast though, for
obvious reasons. I'll be looking into this a bit more next week.

**Comment by busterb** [comment]
libcurl in mettle lets you do whatever you want with headers, it's pretty flexible (having done this before). I think we even have it wrapped via a header API, just need to expose to framework.
