### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space in java/meterpreter/bind_tcp

### ISSUE THREAD

**Issue by firefart** [rapid7/metasploit-framework#8661]
Funny bug I just encountered:
* Create a payload for `java/meterpreter/bind_tcp`:
```
msfvenom -p java/meterpreter/bind_tcp -f jar -o test.jar RHOST=0.0.0.0
```
* Run the jar:
```
java -jar test.jar
```
* In another window connect via `netcat` and send a random string:
```
root@host:~# nc localhost 4444
asd
java.lang.OutOfMemoryError: Java heap space
        at metasploit.Payload.bootstrap(Unknown Source)
        at metasploit.Payload.main(Unknown Source)
```

As the payload is staged it expects a meterpreter stage and seems to hit some strange code. 
Connecting via a `multi/handler` works as intended.

**Comment by timwr** [comment]
My guess is that it's expecting a stage, and the asd string causes to allocate 'asd\r' (as an int) bytes of memory.  You realise even after the fix this won't produce a workable shell (1. because it's meterpreter, 2. because it's staged)? java/shell_reverse_tcp should work though.

**Comment by FireFart** [comment]
@timwr sure it will never work but currently the bind shell completly crashes if smth. tries to connect to it (like a nmap with version detection). Handling non staged traffic should make the bind shell more reliable against unusual traffic so it waits for the "real" connection.

**Comment by timwr** [comment]
agreed. Ok let me fix the crash. We can just catch the exception and retry. Having a max allocation size for the stage would work too.
