### ISSUE TITLE
Apache Struts2 S2-048

### ISSUE THREAD

**Issue by nixawk** [rapid7/metasploit-framework#8662]
- https://cwiki.apache.org/confluence/display/WW/S2-048
- http://bobao.360.cn/news/detail/4219.html
- http://fisheye.apache.org:8060/browse/struts/apps/showcase/src/main/java/org/apache/struts2/showcase/integration/SaveGangsterAction.java?r1=59f4f31a7f3800a540c168abc67b8800db3f2f97&r2=73da12e723c2737bd515946588ddcd898acf584a
- https://github.com/nixawk/labs/issues/8

<img width="1111" alt="screen shot 2017-07-07 at 10 21 49" src="https://user-images.githubusercontent.com/7352479/27962244-48c2c322-62ff-11e7-8256-18af05be9e9c.png">

**Comment by sasqwatch** [comment]
Another source different shorter payload - http://pentestit.com/apache-struts2-showcase-remote-code-execution-s2-048/

**Comment by h00die** [comment]
#8727 fixed this
