### ISSUE TITLE
msfvenom not reading arguments

### ISSUE THREAD

**Issue by MidnightSeer** [rapid7/metasploit-framework#8665]
## Steps to reproduce: msfvenom bla

Everytime I try to run ANY msfvenom commands i get:
Error: Invalid option

Then it display the help menu and lists the available commands.  This happens regardless of flags.

i.e. msfvenom -l or msfvenom --help-formats produces the same result

### Metasploit version
Framework Version: 4.15.0-dev-

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
----I also tried to run it straight from github (clone) --that gave me some gem errors...I'm afraid of Ruby so I stopped troubleshooting
"Your bundle is locked to rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of rake (12.0.0) has removed it. You'll need to update your bundle to a different version of rake (12.0.0) that hasn't been removed in order to install.
Run `bundle install` to install missing gems."

bundle install > 
/usr/local/bin/bundle:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/bundler-1.13.6/exe/bundle (LoadError)
	from /usr/local/bin/bundle:23:in `<main>'

----I also removed, then installed again and it did not fix the problem
### OS
What OS are you running Metasploit on?
Linux Unknown 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux

**Comment by busterb** [comment]
This doesn't look like a bug in the code here, and I couldn't reproduce with your instructions. That you have things in /usr/local/ makes me think you have some odd things on your Kali instance.

Github is not good as a support forum. Please try #metasploit or #kali-linux on IRC. Ask your question, wait a couple of hours and someone will likely see it and be able to help.
