### ISSUE TITLE
broken mailing list link in README.md

### ISSUE THREAD

**Issue by emanuelb** [rapid7/metasploit-framework#8691]
from README.md file
> Questions and suggestions can be sent to: https://lists.sourceforge.net/lists/listinfo/metasploit-hackers

The sourceforge link return 'Page not found'

**Comment by busterb** [comment]
Oops, how embarrassing! How about https://groups.google.com/forum/#!forum/metasploit-hackers if we want a mailing list again?

**Comment by emanuelb** [comment]
sourceforge mailing list is mentioned also in:
1. metasploit-framework.gemspec
>  spec.email = ['metasploit-hackers@lists.sourceforge.net']
2. CONTRIBUTING.md
> \[metasploit-hackers]:https://lists.sourceforge.net/lists/listinfo/metasploit-hackers
