### ISSUE TITLE
Use github api instead of parsing html from github website

### ISSUE THREAD

**Issue by emanuelb** [rapid7/metasploit-framework#8700]
function get_pull_request_from_commit parse html from request to github.com as:
```
url = URI.parse("https://github.com/#{repository}/branch_commits/#{sha}")
```

is there a reason to not use the github api as provided by git_client variable (it use the Octokit library)?

The same can be accomplished by search api via the method:
https://octokit.github.io/octokit.rb/Octokit/Client/Search.html#search_issues-instance_method
with using repo search qualifier in q parameter, more information about the search api in:
https://developer.github.com/v3/search/#search-issues

**Comment by busterb** [comment]
I think the intent was to allow the functionality to work without needing the API key to be set. But, if this functionality doesn't get called unless the key is set in the first place, it's a moot point.

**Comment by emanuelb** [comment]
current approach has the privacy advantage as it don't use the API key which is related to github account, but has reliability disadvantage as the [returned HTML|URI-Path] can change any-time?
I guess metasploit may setup a proxy for the github requests on behalf of the user (while also caching the results?) thus don't require having github account, and proxy can use the API key always.

**Comment by bcoles** [comment]
I like the idea of not providing an API key. Suggest the best way to resolve this issue is;

* Fall back to scraping if API key isn't provided.
* Strict error checking on the scraping method, and bail out if the layout of the response HTML has changed.

That said, I have no idea which module is being discussed here. It does not appear to exist in the framework.

**Comment by adfoster-r7** [comment]
I assume this is in reference to the pull request finder logic

https://github.com/rapid7/metasploit-framework/blob/2dc5a94ab7b2a29e0d8e0383e1236f4b185c2254/lib/msf/util/document_generator/pull_request_finder.rb#L143-L164

Or the copy/paste here:

https://github.com/rapid7/metasploit-framework/blob/2dc5a94ab7b2a29e0d8e0383e1236f4b185c2254/tools/modules/file_pull_requests.rb#L105-L130

Either way; Pull requests welcome :+1:
