### ISSUE TITLE
Question - Pull information from connected Android Phone (using MTP or PTP)

### ISSUE THREAD

**Issue by NJHacker** [rapid7/metasploit-framework#8726]
Hello,

After setting up a meterpreter on Windows 7 PC, I was wondering if someone could grab sensitive information from a connected Android smartphone.
I created a test in my lab which in it I've connected a phone into an infected Win7 PC. When I tried to navigate to my connected Android smartphone, I understood that it did not have a drive letter. I googled the subject and eventually understood that the connection of MTP or PNP device (like the newer Android smartphones work) is unreachable from the cmd. Moreover, I coulndn't find a script in Metasploit which does it.
My question is if there's any chance of collecting information (even as simple as photos) from a connected smartphone using MSF.

An explanation would be very much appreciated.

**Comment by sempervictus** [comment]
@timwr: ping...
@njhacker:  the device protocol needs to be supported on the host os, not sure how windows handles this internally but at least for mtp they should have a handler - cameras need it. Off the bat, don't think we have the railgun code for this, but it would definitely be useful to be able to tap winapi for these access paths directly. Id wait for a better informed response from @timwr if he fan weigh in though, defacto owner of android space in framework far as I'm concerned.
Alternatively you could try powershell for a host-local approach, though IMO railgun may expose unsafe ops via direct api calls more readily (.net can do all the same stuff just that undocumented functions outside the managed memory space can be a pain to marshal safely).

**Comment by wwebb-r7** [comment]
Windows exposes both MTP and PTP through IPortableDevice iirc, at least for 8+.  I've used MTP devices on 7 before so I'm sure it has some support, I'm just not clear on the API.

Regardless of that, as mentioned, there is nothing currently in framework that allows you to do this.  Your best bet for a quick fix IMO would be searching for CLI forensics utilities that might support it.  I can't imagine most Windows 7 users ever needing to access their phones from the command line, but I can see dfir investigators needing to do so quite a bit.

**Comment by timwr** [comment]
I'll have to look into this. Both this and adb support (which would allow installing meterpreter onto the phone itself) would be good additions to the framework.
