### ISSUE TITLE
how search and download all file

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#8743]
# 1、how search and download all file?

meterpreter> download -f *.doc?;*.ppt?;*.xls? -r -ldir /usr/data/${mac}/${ip}

ldir =  local dir
download and recurse=true

thanks

# 2、have...but
run post/windows/gather/enum_files FILE_GLOBS=*.doc? SEARCH_FROM=C:\\ 
but
20170720141508_gs0621_192.168.28.230_host.files_605466.bin
how do
dir1/dir2/goodFileName.doc

**Comment by busterb** [comment]
I don't understand what you are asking. You can ask in Chinese if it helps.

**Comment by hktalent** [comment]
@busterb 
下载的文件没有保留原来的目录路径和文件名啊？

**Comment by busterb** [comment]
Ah, you would like the file to download with the original path name / folder structure.

**Comment by hktalent** [comment]
# ./lib/msf/core/auxiliary/report.rb
'''
def store_loot(ltype, ctype, host, data, filename=nil, info=nil, service=nil)
    if ! ::File.directory?(Msf::Config.loot_directory)
      FileUtils.mkdir_p(Msf::Config.loot_directory)
    end

    ext = 'bin'
    if filename
      parts = filename.to_s.split('.')
      if parts.length > 1 and parts[-1].length < 4
        ext = parts[-1]
      end
    end

'''
如果后缀超过长度3，例如：pptx，docx、xlsx
后缀就变成了.bin

建议修改为
'''
if parts.length > 1
'''
@busterb

**Comment by hktalent** [comment]
@busterb 增强功能就更好了,建议实现这样的功能
'''
run post/windows/gather/enum_files FILE_GLOBS=*.xls?|*.doc?|*.ppt?|*.pdf SEARCH_FROM=show_mount

'''
下载后保留原来的文件名、后缀，使用随机数作为前缀
hostip_mac/fileName_random.ext

**Comment by bwatters-r7** [comment]
Is this code we should add?  Is this code problematic? @hktalent

**Comment by bwatters-r7** [comment]
ping @hktalent

**Comment by hktalent** [comment]
@bwatters-r7 我本来修改了的，但是更新后被覆盖了，建议你们修改为上面的建议

**Comment by hktalent** [comment]
@bwatters-r7 @darmansyahsembiring  @busterb  
now is suport, in my fork
https://github.com/hktalent/metasploit-framework/blob/master/modules/post/windows/gather/enum_files.rb

**Comment by bwatters-r7** [comment]
Would you like help in submitting a pull request?

**Comment by hktalent** [comment]
@

**Comment by hktalent** [comment]
> Ah, you would like the file to download with the original path name / folder structure.

解决批量过滤、下载，且保留原来目录结构和文件扩展名
Resolve batch filtering, download, and retain the original directory structure and file extension

**Comment by Green-m** [comment]
@hktalent 
Do you mind submitting a pull request with your change in your fork? After that, the enhancement could be merged into `master`, everyone would enjoy it!
I am a chinese too, feel free to ask.

你可以把你修改的代码通过 `pull request` 提交到主分支，合并后每个人都能使用！ 
我是中国人，有任何问题可以直接和我沟通。

**Comment by Green-m** [comment]
@hktalent 
Close that PR in order to cooperate with others.

根据规范，不能直接从 `master` 主分支提交PR，必须新建一个分支提交，这样便于多人合作。
你可以新建一个分支然后重新提交。
