### ISSUE TITLE
WAN

### ISSUE THREAD

**Issue by BlaacckK** [rapid7/metasploit-framework#8746]
Hi,
i m using an android tcp payload which works fine when the target device is on the same network.
But, when i try it over wan meterpreter sessions doesn't last long it dies
whenever i try to dump something session dies.
Is it because i am using tcp payload over wan?

**Comment by timwr** [comment]
Can you try the `wakelock` command and see if it helps?

**Comment by BlaacckK** [comment]
what actually wakelock does?

**Comment by timwr** [comment]
It prevents the device from sleeping the meterpreter service. Does it make a difference? If so I can enable it by default
