### ISSUE TITLE
Armitage say "The Parallel GC can not be combined with -XX:ParallelGCThreads=0"

### ISSUE THREAD

**Issue by MrXMisX** [rapid7/metasploit-framework#8749]
Hello everyone this is my first post and i hope this is correct section.Anyway this is my problem.I did clean kali linux 2017.1 installation to my HP Paviolion DV7 laptop.I saw few new updates and i updated but then i tried to start armitage.I open my terminal and write 1) service postgresql start 2) msfdb init and 3) armitage and my terminal say this: "The Parallel GC can not be combined with -XX:ParallelGCThreads=0" i don't have any clue what that means.Last 5 hours i been searching help on google and other forums but no.No any help.i reinstalled whole armitage/metasploit but still say that same message.I'm totally out of ideas.
Here is my specs: 
Gnome Version 3.22.2
Memory 7.0 GiB
Processor AMD® A8-5550m apu with radeon(tm) hd graphics × 4 
Graphics AMD® Aruba
Base System Kali GNU/Linux Rolling 64-bit
Disk 61.7 GB

**Comment by sempervictus** [comment]
Armitage is not Metasploit, this issue is coming from the Java runtime of that product. Suggest seeking support from the author

**Comment by MrXMisX** [comment]
The problem is that Google didn't give any working solutions. And authors not give support. Armitage is one of my most used app. I installed Parrot os yesterday and same problem with Armitage. Only os where Armitage works is Kali Sana

**Comment by sempervictus** [comment]
I don't speak for anyone but myself when I say this (I'm not an r7 staffer, just a community member with a few commits), but as I see it, the author effectively sells a wrapper for our work without contribution to the core project. Under that premise, this is the categorically wrong place to seek help for what if effectively a parasitic commercial effort... Suggest you learn how to use the framework itself - GUI tools to point and click pre canned actions is not going to show you how the protocols, data structures, and interactions create vulnerable contexts. Its like learning to drive a car using an automatic transmission with steer by wire and traction control enabled - misses the point by a mile and a half.

**Comment by wwebb-r7** [comment]
I'm sorry that you're having all of these problems, but we have a high enough workload without having to troubleshoot issues with broken, abandoned software that we don't use and didn't write.  Sounds like you'll have to figure it out on your own.  I suggest looking at it as a learning opportunity.

**Comment by busterb** [comment]
First page of hits when searching for "armitage XX:ParallelGCThreads=0" will yield considerable discussion about this. Please refer to those links.

**Comment by symtaser** [comment]
https://www.youtube.com/watch?v=3u_d0byNa0M
