### ISSUE TITLE
how add display MAC address 

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#8758]
how add
post/meterpreter/extensions/kiwi.rb
funciton
wifi_parse_shared
add display MAC address 
```

meterpreter>wifi_list_shared
Name                MAC address       Auth     Type     Shared Key
----                ----     ----     ----     ----------
2513xwq        00:c2:c6:cd:b5:09     WPA2PSK  Unknown  xiongweiqian
25FWaiWang     00:c2:c6:cd:b5:09     WPA2PSK  Unknown  cd87706855
 
```

**Comment by jvoisin** [comment]
You might want to rephrase your question, I fail to understand what you're trying to do :/

**Comment by hktalent** [comment]
就是说我希望得到wifi的列表，包含mac地址，最好针对mac能够反向跟踪到城市、区域地址
meterpreter>wifi_list_shared
Name                MAC address       Auth     Type     Shared Key
----                ----     ----     ----     ----------
2513xwq        00:c2:c6:cd:b5:09     WPA2PSK  Unknown  xiongweiqian           chinabeijing
25FWaiWang     00:c2:c6:cd:b5:09     WPA2PSK  Unknown  cd87706855     xxxx
