### ISSUE TITLE
bcrypt problem in gnunroot debain

### ISSUE THREAD

**Issue by Ashish882** [rapid7/metasploit-framework#8764]
I have load a metasploit to my sdcard and I install all pkg which I need to install metasploit frameworks
In android by gnuroot debain.

I am get error when I put this command at end
bundle install
<code>
Gem::Ext::BuildError: ERROR: Failed to build gem
native extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
/data/data/com.termux/files/usr/bin/ruby -r
./siteconf20170725-15087-16cvats.rb extconf.rb
creating Makefile

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
make "DESTDIR=" clean

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11/ext/mri
make "DESTDIR="
compiling bcrypt_ext.c
make: aarch64-linux-android-clang: Command not
found
make: *** [Makefile:243: bcrypt_ext.o] Error 127

make failed, exit code 2

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11
found
make: *** [Makefile:243: bcrypt_ext.o] Error 127

make failed, exit code 2

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/bcrypt-3.1.11
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/aarch64-linux/2.4.0/bcrypt-3.1.11/gem_make.out

An error occurred while installing bcrypt
(3.1.11), and Bundler cannot continue.
Make sure that `gem install bcrypt -v '3.1.11'`
succeeds before bundling.

In Gemfile:
metasploit-framework was resolved to 4.15.4,
which depends on
    bcrypt </code>

This above error of bcrypt

I had try all command and tips to install bcrypt but I fail every time plz guide me so I can come of this problem

Plzpzl

**Comment by timwr** [comment]
> aarch64-linux-android-clang: Command not found
`apt-get install clang` ?

**Comment by Ashish882** [comment]
Does it it need clang also

**Comment by timwr** [comment]
I think so

**Comment by Ashish882** [comment]
Thanks you right
