### ISSUE TITLE
[question]need [HELP]extra charecter is added at the end of the commands !!

### ISSUE THREAD

**Issue by narutowindy** [rapid7/metasploit-framework#8770]
## Steps to reproduce
any command
msf> ls \r
.....
.....
msf>search blah \r
.....
....

every command is adding  "\r" char at the end of it ??
acesssing history making it difficult..

## Current behavior
NO logs found !!

### Metasploit version
4.15

### OS
Arch official pkg.

**Comment by bcoles** [comment]
This issue was due to an issue with the rb-readline  dependency. It was reported as #8339 and patched in #8732.

If you're using Metasploit from GitHub, you can resolve this issue with `git pull` and `bundle install`.
