### ISSUE TITLE
Missing line in scripts/meterpreter/multi_console_command.rb

### ISSUE THREAD

**Issue by rami418** [rapid7/metasploit-framework#8773]
## Steps to reproduce
Launch multi_console_command.rb

Multi console command is not working and printing help.
You provided the correction here but i open this issue to help other finding it until it's fixes ;) 
https://community.rapid7.com/thread/10121

Thanks ;)

**Comment by sn0wfa11** [comment]
Looks like this is related to changes in how the argument parser manages multi-char arguments that PR #8622 addressed. This one was missed. I just tested it with dropping all of the arguments down to single chars and everything worked fine. I'll get a PR out for this tonight or tomorrow and see if anything else was missed.

**Comment by bcoles** [comment]
Was this closed by #8802 ?

**Comment by sn0wfa11** [comment]
Yes, it was.
