### ISSUE TITLE
How do i install msfvenom?

### ISSUE THREAD

**Issue by Wolfleader101** [rapid7/metasploit-framework#8776]
how do i install msfvenom on kali linux?
I am new to kali linux and am trying to open a backdoor onto my android phone. I need to install msfvenom as said on this post:
http://www.hackingarticles.in/hack-android-phone-using-backdoor-apk/

**Comment by void-in** [comment]
msfvenom is part of Metasploit. Install Metasploit through any of the available installation options (git repo, Omni installer, Kali package) and use msfvenom to generate binaries.

For further support queries, please use IRC or https://community.rapid7.com

**Comment by Wolfleader101** [comment]
How do i install via Kali package?

**Comment by Wolfleader101** [comment]
Ah nevermind i fixed that issue,
Now i am wondering how i can use msfvenom with backdoor APK to access an android phone on a different ip address

**Comment by ExiledNarwal28** [comment]
For anyone stumbling upon this and, like me, looking for an actual solution : `sudo apt-get install metaploit-framework`.

`msfvenom` will then be available :100:

**Comment by DJSicn55** [comment]
Even that didn't work.

**Comment by SGC-GamerZ** [comment]
> For anyone stumbling upon this and, like me, looking for an actual solution : `sudo apt-get install metaploit-framework`.
> 
> `msfvenom` will then be available 💯

wrong word! it should be `sudo apt-get metasploit-framework`.

**Comment by Allong12** [comment]
> 


`sudo apt-get install metasploit-framework`

**Comment by dakshsain** [comment]
sudo apt-get install metasploit-framework

**Comment by dakshraman** [comment]
sudo apt install metasploit-framework

**Comment by ZombieGeeK0** [comment]
sudo apt install metasploit-framework

**Comment by iamchutiya520** [comment]
No superuser binary detected.
Are you rooted?
 
I got this

**Comment by meria2** [comment]
how can i generate the binary from msfvenom when im using msfconsole i want to open webcam of metasploit from kali linux

**Comment by Eyad736** [comment]
Hey guys msvenom itis a important tool to hack wirte msvenom and show options and use it it is important tool

**Comment by Prathmeshgurav** [comment]
hello
