### ISSUE TITLE
Access android phone remotely

### ISSUE THREAD

**Issue by Wolfleader101** [rapid7/metasploit-framework#8777]
Now i am wondering how i can use msfvenom with backdoor APK to access an android phone on a different ip address.
Also i get an error saying the following on Backdoor APK: 
[!] Check your environment and configuration. Couldn't find: jarsigner

**Comment by timwr** [comment]
You can fix this problem yourself with Google. I believe in you :)
Just install java (it will depend on what OS you're on).
Hint: `sudo apt-get install default-jre` ?

**Comment by Wolfleader101** [comment]
oh it is that simple to install java........ i was trying to install java jdk ( it was just a file my fault)

**Comment by Wolfleader101** [comment]
I still cannot find anything on google about accessing a android phone remotely!

**Comment by Wolfleader101** [comment]
Hello i can still not figure out how to access android phones remotely though
