### ISSUE TITLE
Packaging request for Termux 

### ISSUE THREAD

**Issue by Auxilus** [rapid7/metasploit-framework#8780]
As you guys might have already heard , there is an app called Termux which emulates Linux(Unix) environment. It has all the dependencies available to run metasploit ( some gems need modifications )
I installed and succeed to run metasploit, but the manual installation process is lengthy, ( which you can check [here](wiki.termux.com/wiki/metasploit) ).

Also we are getting tons of error with some phones( in installation process )

I need something like `apt install metasploit-framework` for this app, If you can package it for this app then please let me know.

Git issue on Termux git repo : https://github.com/termux/termux-packages/issues/715
Link for Termux app : https://play.google.com/store/apps/details?id=com.termux

Thanks for your attention

![meta](https://user-images.githubusercontent.com/23075789/28660147-8b0dcc9c-72cf-11e7-8555-9b27e4a0e0f5.jpg)

**Comment by narutowindy** [comment]
rb-readline dependency missing ??  
#8732

**Comment by Auxilus** [comment]
Aye looks like it it , :p

**Comment by Auxilus** [comment]
How can we fix it ?

**Comment by timwr** [comment]
You can use msfconsole -L as a workaround for now

**Comment by busterb** [comment]
I'm going to close this here to be continued in the Termux repo. The network_interfaces changes are in place now.

**Comment by Yisus7u7** [comment]
Metasploit fue eliminado de los repo de termux, pero aún podría ser instalado, pero termux actualizo ruby a la versión 3.0.0, Metasploit es compatible sonó col ruby 2.7.2, cuando habrá soporte para la versión 3.0.0?

**Comment by bcoles** [comment]
> cuando habrá soporte para la versión 3.0.0?

There is no firm date for Ruby 3 support yet. Perhaps Summer 2021.

#14666
https://github.com/rapid7/metasploit-framework/issues/14666#issuecomment-771003373
https://github.com/rapid7/metasploit-framework/issues/14666#issuecomment-771456215

**Comment by Yisus7u7** [comment]
Well, then I play wait, because I didn't find any compilation of ruby 2.7.2 for termux
