### ISSUE TITLE
port forwarding stops working after some time or activity

### ISSUE THREAD

**Issue by kayaker-msf** [rapid7/metasploit-framework#8787]
I'm sorry for not having exact repro steps at the moment but maybe we can use this as a starting point and you can help me to debug it a little further.

These are my initial impressions:
What I've noticed, and with older versions also happended as I recall, is that after some time port forwarding stops working.
"some time" being random normal activity, sessions opened, closed, killed, time outs, background jobs running, timed out, killed etc.

What happens after some time is portforwarding stops working, it connects metasploit side, I see telnet/putty/etc connected locally to ruby but no packet goes out meterpreter side.
pressing enter in telnet/putty it seems to consume packets/keys but again no packet goes out victim side (verified with wireshark nothing out to forwarded host from meterpreter host).

And no matter if I open brand new meterpreter sessions and in different victims, it does not work anymore, so It seems some kind of problem, some structure or something not cleaned up or properly handled over time metasploit side.
If I close metaspoit console and open it again, and after session came back alive again it seems it works again.

I'm using metasploit on windows, latest dev versions (but I think this is an older issue), meterpreter payload usually reverse_https (not the best for ssh stream forwarding but I can keep with the delay) but also tried the reverse_tcp and it also doesn't work after the problem.

How can I debug it a little further (whenever it seems to happen again) as to be more hepful to you guys?

Anyone also noted some similar behaviour ?

**Comment by Vigeant** [comment]
I confirm that I have seen the same behavior.
