### ISSUE TITLE
update error:bundle install for 'rbnacl-libsodium 1.0.11' Stay for a long time....

### ISSUE THREAD

**Issue by z977780633** [rapid7/metasploit-framework#8798]
OS:windows 10

> ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

> gem -v
2.6.12

_________________________________
> msfconsole

Could not find rbnacl-libsodium-1.0.11 in any of the sources
Run `bundle install` to install missing gems.

> bundle install
....
....
Fetching rbnacl-libsodium 1.0.11
Installing rbnacl-libsodium 1.0.11 with native extensions

Then, wait for a long time ......
no next step
what happened?

**Comment by busterb** [comment]
You just need to wait - it takes a while. Alternately, we rebuild all of the windows packages nightly.
