### ISSUE TITLE
Metasploit put \r after every writen command?

### ISSUE THREAD

**Issue by DrMTR** [rapid7/metasploit-framework#8820]
## Steps to reproduce

Simple activate Metasploit by write : msfconsole in Kali Linux 02.2017

## Expected behavior

I expect do not put that \r after every entered command.

## Current behavior

Place \r after every metasploit command. That is not happening in other terminal windows.

## System stuff

Kali Linux 02.2017 build, fresh upgraded.

### Metasploit version

v4.14.28-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

Kali Linux 2017
![screenshot from 2017-08-10 19-15-57](https://user-images.githubusercontent.com/23032630/29182765-60be2248-7e00-11e7-9177-4ecfdd5557b8.png)

**Comment by busterb** [comment]
This is already fixed - you'll need a newer version of metasploit-framework than 4.14.28

**Comment by hexig** [comment]
i have still having this issue ...!!!

**Comment by Gowtham610** [comment]
i am not able to find metasploit for 32 bit kali
but having the same error
