### ISSUE TITLE
auxiliary/scanner/mdns/query module returns no results

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#8828]
The mDNS query module returns no results, while `nmap` and `mdns-scan` return several results.

```
# ./msfconsole -x 'use auxiliary/scanner/mdns/query; run'
[...]
[*] Sending mDNS PTR IN queries for _services._dns-sd._udp.local to 224.0.0.251->224.0.0.251 port 5353 (1 hosts)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

```
# mdns-scan 
+ garryhost [08:62:66:47:51:cd]._workstation._tcp.local
+ garryhost._udisks-ssh._tcp.local
+ vulnvoip [00:0c:29:38:58:4a]._workstation._tcp.local
^Cowsing ... -           
```

```
# nmap --script broadcast-dns-service-discovery 

Starting Nmap 7.50 ( https://nmap.org ) at 2017-08-13 05:31 EDT
Pre-scan script results:
| broadcast-dns-service-discovery: 
|   224.0.0.251
|     9/tcp workstation
|       Address=10.1.1.158 fe80:0:0:0:a62:66ff:fe47:51cd
|     9/tcp workstation
|       org.freedesktop.Avahi.cookie=4011151281
|       Address=10.1.1.112
|     22/tcp udisks-ssh
|_      Address=10.1.1.158 fe80:0:0:0:a62:66ff:fe47:51cd
WARNING: No targets were specified, so 0 hosts scanned.
Nmap done: 0 IP addresses (0 hosts up) scanned in 7.29 seconds
```

**Comment by bcoles** [comment]
The bug was introduced somewhere between September 2015 and January 2017.

There haven't been many changes to the mDNS module or mDNS library.

At a guess, this is due to changes to the udp_scanner library which didn't account for broadcast UDP.

The mDNS query module works with the udp_scanner library rolled back to [this commit](https://github.com/rapid7/metasploit-framework/commit/fc9a75719435f0549e86c0feca9d12df873148ba) (Sep 27, 2015).

And stopped working with the udp_scanner library rolled back to [this commit](https://github.com/rapid7/metasploit-framework/commit/4f0569c6ce4ba7a6f12bcb70539ba239a368fc7b) (Jan 2, 2017).

As an aside, `scanner_recv` gets called in a loop, however this method calls a clean up routine which destroys the UDP socket in `@udp_sockets`. As a result, the following iterations have no socket for `::IO.select` and will never receive data.

**Comment by busterb** [comment]
One issue is that we probably need to add SO_REUSEADDR/PORT with multicast listener sockets - https://github.com/openframeworks/openFrameworks/issues/2937

Another might be that multicast is unlikely to work over a pivot anyway, so maybe it makes sense to just revert back to the original behavior in scanner_recv. Really I added this when I noticed pivoting over UDP didn't work very well without manual intervention via CHOST/CPORT bindings.

**Comment by bcoles** [comment]
It looks like this issue may also affect the auxiliary/scanner/upnp/ssdp_msearch module.

**Comment by busterb** [comment]
I think I fixed it. Mind checking out #8875 ?

**Comment by bcoles** [comment]
@busterb - works for me. mDNS query module returns the expected results.
