### ISSUE TITLE
metasploit from source unable to run outside its folder

### ISSUE THREAD

**Issue by peterpt** [rapid7/metasploit-framework#8833]
## Steps to reproduce

How'd you do it?

1. clone metasploit git
2. install rvm
3. install ruby 2.4.1
4. install bundle and go to metasploit folder and write "bundle install"
5. create symlink to /usr/local/sbin/  msfconsole & msfupdate from metasploit original path
6. go to / and write msfconsole

Metasploit works perfectly if runs on its folder even calling the symlink , but if i change to root folder
first message i get is to install bundler , and then start to warning that needs the specific gems already installed before in metasploit folder .
![msfconsole](https://user-images.githubusercontent.com/7487321/29295928-ceaa4394-811c-11e7-93b8-faae85f8c904.png)

* Note

If i manually install every asked gem from root folder then metasploit will start , however when i get the next update from msfupdate , it will ask me again for some more gems !

**Comment by timwr** [comment]
I think this is a problem with rvm. If you use rbenv instead you won't have this problem.

**Comment by peterpt** [comment]
Bingo !!! , you are right .
The solution is to remove rvm and remove any ruby installation made by it .
and then install rubyenv following these instructions on digital ocean : 
https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-14-04

i am not using ubuntu , but it is also a debian distribution which also works perfectly .

Another important thing is to remove the gem binary from /usr/bin .
This way every time an user write gem , it will run from rbenv path .
