### ISSUE TITLE
msf update fails

### ISSUE THREAD

**Issue by Titaniumtown** [rapid7/metasploit-framework#8865]
every time i run msfupdate i get this error:

[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via git
[*] Note: Updating from bleeding edge
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- os (LoadError)
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /var/lib/gems/2.2.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /opt/metasploit-framework/msfupdate:153:in `git_globals_okay?'
	from /opt/metasploit-framework/msfupdate:202:in `update_git!'
	from /opt/metasploit-framework/msfupdate:143:in `block in run!'
	from /opt/metasploit-framework/msfupdate:136:in `chdir'
	from /opt/metasploit-framework/msfupdate:136:in `run!'
	from /opt/metasploit-framework/msfupdate:316:in `<main>'

please help!!!

**Comment by busterb** [comment]
If you are going to be running bleeding-edge, please use the correct version of ruby. You're using 2.2 which is end of life in a few months. Upgrade to 2.4 use rvm to manage it.

Alternately, just run `bundle install`
