### ISSUE TITLE
sqlmap dump issue

### ISSUE THREAD

**Issue by winY2k** [rapid7/metasploit-framework#8870]
Hi,
I'm trying to dump using sqlmap, I have 3 columns:
name,lastname,userid
I have 9000 entries in each.
when i just --dump the table, it will start from 1 to 9000.
now, I don't want all the 9000, how can I tell him to start from 5000 and stop at 9000?
I tried the --start= and --stop= but it didn't help.

Thanks

**Comment by void-in** [comment]
Not related to Metasploit. Closing.
