### ISSUE TITLE
sqlmap won't dump speific column

### ISSUE THREAD

**Issue by winY2k** [rapid7/metasploit-framework#8874]
Hi,

I have a machine with SQL 2008, when I try to dump any column from table1, I success.
but, when I only have issue with 1 specific column in this table, every time I try to dump I get this:

[INFO] fetching entries of column(s) 'm005' for table 'table1' in database 'dbtest'
[INFO] retrieved: 6654
[INFO] fetching number of distinct values for column 'm005'
[INFO] retrieved: 0
[CRITICAL] all column name(s) provided are non-existent

This column name is 100% exist.
if I dump another column from table1, I retrieve the data with no problem.
What can be wrong?

**Comment by void-in** [comment]
I have closed your other issue as well. This is MSF issues page and you are having problems with sqlmap. Please report it to the appropriate forum.

**Comment by bcoles** [comment]
[sqlmapproject/sqlmap: Automatic SQL injection and database takeover tool](https://github.com/sqlmapproject/sqlmap)
