### ISSUE TITLE
msfvenom can't find hook in a xamarin.android compiled apk. Also injecting it manually crashes the app

### ISSUE THREAD

**Issue by Code-Apprentice** [rapid7/metasploit-framework#8879]
Using msfvenom with the apk as an input file and the payload being android/meterpreter/reverse_tcp

I should get an injected apk out but it can't find the hook point, which is in a folder inside the smali folder named with some hash. I also tried manually creating a payload and decompiling both apks and copying the files myself. (I signed and zipaligned the final file too)

Here is the MainActivity.smali file https://pastebin.com/jjX8TCMy. As you can see, on line 171 I injected the invoke static which should have started the payload. Instead the app crashes.

I have tried inserting the payload with scripts (apkwash, apkinjector, ruby apk embed), msfvenom, manually, but to no avail.

The payload does work if I install the payload apk by itself on my phone. Only when I try to inject it in my app created using Xamarin.Android it fails to work and crashes the app.

**Comment by timwr** [comment]
@Code-Apprentice Sorry for the delay. Can you provide an APK?

**Comment by Code-Apprentice** [comment]
Sorry for the delay on my part too, I didn't get a notification that my issue had been replied to. Anyway, here is an APK.

https://drive.google.com/file/d/0B_9NEl71NPGfR1FXUzI2Q203Q1k/view?usp=sharing

This problem is easily replicated by just creating a blank xamarin.android app and then archiving it in Visual Studio to create the apk. The apk I provided is just blank with a mainactivity,

**Comment by timwr** [comment]
What a strange APK: the uppercase characters in the packagename `SleepGuardian.SleepGuardian` is causing problems.

**Comment by timwr** [comment]
@Code-Apprentice thanks for reporting this! It should be fixed in #8946

**Comment by Code-Apprentice** [comment]
No problem. Anyway this was a blank project with a name of an app I never started. So if I change the package name to something standard (like com.x), will it work?
