### ISSUE TITLE
INSTALLING METASPLOIT ON PINEBOOK

### ISSUE THREAD

**Issue by cephasiii** [rapid7/metasploit-framework#8881]
I am having a problem installing Metasploit on my Pinebook, using Ubuntu Mate. I have downloaded both the 32 and 64 bit scripts and receive the same errors.

     uname -a > Linux pinebook 3.10.105-bsp-1.2-ayufan-59 #1 SMP PREEMPT Sat May 13 12:39:31 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

I have downloaded the install scripts for both 32 & 64 bit:
wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run

I then made them executable
chmod +x metasploit-latest-linux-x64-installer.run 

I then tried to run the script and this is where the problem came in.
sudo metasploit-latest-linux-x64-installer.run
sudo: metasploit-latest-linux-x64-installer.run: command not found

./metasploit-latest-linux-x64-installer.run 
bash: ./metasploit-latest-linux-x64-installer.run: No such file or directory

sudo ./metasploit-latest-linux-x64-installer.run
./metasploit-latest-linux-x64-installer.run: 1: ./metasploit-latest-linux-x64-installer.run: Syntax error: Unterminated quoted string

sudo ./metasploit-latest-linux-installer.run 
./metasploit-latest-linux-installer.run: 1: ./metasploit-latest-linux-installer.run: Syntax error: "(" unexpected

Lastly, I also tried using the "Nightly Installers" guidance, to no avail.
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5394  100  5394    0     0   2369      0  0:00:02  0:00:02 --:--:--  2370
Switching to root user to update the package
Updating package cache..OK
Checking for and installing update..
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package metasploit-framework

I have been researching a solution for a day now but have not been able to find a fix. Any assistance would be appreciated. Thank you.

**Comment by cbrnrd** [comment]
have you tried building from source?

**Comment by cephasiii** [comment]
cbrnrd, thank you for the response. No, I haven't tried installing from source. Can you provide me with the process? I know metasploit has a lot of dependencies and I want to ensure I do this right the first time. Thanks.

**Comment by cbrnrd** [comment]
Dark operator has a pretty good walk through here:
https://www.darkoperator.com/installing-metasploit-in-ubunt/

in short, clone the repo then `bundle install` for non db use

**Comment by cbrnrd** [comment]
and the package dependencies are listed [here](https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment)

**Comment by busterb** [comment]
A Pinebook is an Arm CPU. The Metasploit Pro packages you tried to download above are for x86.

For Arm builds, please use our nightly installers:
https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

**Comment by busterb** [comment]
Hmm, actually it looks like our arm builds haven't published in a bit, which is why you got the second error.

In that case, your best bet is to grab the packages for Kali Linux. Alternately, https://github.com/rapid7/metasploit-omnibus has full build instructions for new platforms. Either way, this isn't really the right place to be asking for installation help, since this Github project isn't about packaging either for Metasploit Pro or for the omnibus packages.

**Comment by cephasiii** [comment]
Thanks. I am in the middle of installing rubies using dark operators instructions. So far no errors. I will fall back on the Omnibus project if I have issues. Thanks for entertaining my questions and getting me on the right path.

**Comment by busterb** [comment]
armhf and arm64 packages are now published again for omnibus - the automated publishing script was missing them for some reason:

                ├── metasploit-framework_4.16.0+20170823092910~1rapid7-1_amd64.deb
                ├── metasploit-framework_4.16.0+20170823093038~1rapid7-1_i386.deb
                ├── metasploit-framework_4.16.0+20170823133518~1rapid7-1_arm64.deb
                └── metasploit-framework_4.16.0+20170823133616~1rapid7-1_armhf.deb

**Comment by elraro** [comment]
Again is missed the .deb for arm @busterb

**Comment by busterb** [comment]
Hmm, @jmartin-r7 any ideas?

**Comment by busterb** [comment]
Hmm, maybe there isn't a template :) I manually updated anyway, and the packages should be there now.

**Comment by jmartin-r7** [comment]
@busterb, I will double check the regular daily template should pick up the previous day arm builds due to the time they take to generate.
