### ISSUE TITLE
undefined method `[]' for nil:NilClass when injecting into an existing .apk file on windows

### ISSUE THREAD

**Issue by dan3s2020** [rapid7/metasploit-framework#8887]
![undefinernilnilclass1](https://user-images.githubusercontent.com/25185856/29692037-b10f7eae-8936-11e7-9293-13761060ae38.png)

Any ideea?

**Comment by busterb** [comment]
what is 'Wapp.apk'? what is the metasploit version you are running?

**Comment by dan3s2020** [comment]
v4.14 on windows 10, the wapp.apk is the whatsapp apk file,first i received the error to path the jarsigner and then the zipalign error so i downloaded the file from https://forum.xda-developers.com/showthread.php?t=2214583  i pasted the .exe here \AndroidSdk\tools\zipalign.exe and then i got the error for apktool and i downloaded this https://ibotpeaches.github.io/Apktool/install/ and finally i received that Error undefined method `[]' for nil:NilClass

**Comment by idanc15** [comment]
Same for me

**Comment by kerohero** [comment]
Any update on this? I've the same proplem...

**Comment by Green-m** [comment]
@idanc15 @kerohero 

This issue should be a quota problem. 
Fix in PR https://github.com/rapid7/metasploit-framework/pull/10440

**Comment by kerohero** [comment]
@Green-m Then we should just wait? Is there is anyway to edit that code by ourselves and get it running?!

**Comment by Green-m** [comment]
@kerohero  

It's recommanded to wait util the PR merged. and download the lastest version.

Also you can edit the changed file according to this PR by yourself, just a  temporary approach.

**Comment by Green-m** [comment]
Merged https://github.com/rapid7/metasploit-framework/pull/10440
