### ISSUE TITLE
Could not find Ascii85-1.0.2 in any of the sources

### ISSUE THREAD

**Issue by iCoreX0812** [rapid7/metasploit-framework#8890]
Hey,
i have a little problem,
if i type "msfconsole" then it comes this error:

`
Could not find Ascii85-1.0.2 in any of the sources
Run `bundle install` to install missing gems.
`

I tried already to install Ascii85

`sudo apt-get install ruby-ascii85
`
And i tried to reinstall my server.

But the problem is still there on Ubuntu 16.04.

Can someone help me please?

**Comment by wvu-r7** [comment]
How did you install Metasploit? Did you try what it told you to do?

**Comment by iCoreX0812** [comment]
I installed Metasploit so:

`cd /opt
sudo git clone https://github.com/rapid7/metasploit-framework.git
sudo chown -R `whoami` /opt/metasploit-framework
cd metasploit-framework

cd metasploit-framework

rvm --default use ruby-${RUByVERSION}@metasploit-framework

gem install bundler
bundle install

cd metasploit-framework
sudo bash -c 'for MSF in $(ls msf*); do ln -s /opt/metasploit-framework/$MSF /usr/local/bin/$MSF;done'`

**Comment by busterb** [comment]
tell you what, save a lot of time and to this:

```
sudo rm -fr /opt/metasploit-framework
sudo rm /usr/local/bin/msf*
```

Then follow the instructions here https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

**Comment by iCoreX0812** [comment]
Thanks, its working.
