### ISSUE TITLE
mssql_login auxiliary not working

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#8915]
## Steps to reproduce
Tried multiple password files, including one with two passwords.

1. 
root@kali:~# cat 1433-mssql.rc
setg RHOSTS 10.0.0.179
setg THREADS 1
setg RPORT 1433
use scanner/mssql/mssql_login
set PASS-FILE /root/passwords
run
2. resource /root/1433-mssql.rc

## Expected behavior
Show when a password works/fails.

## Current behavior
10.0.0.179:1433 - 10.0.0.179:1433 - MSSQL - Starting authentication scanner.
[*] 10.0.0.179:1433  - Error: 10.0.0.179: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::MSSQL)

### Metasploit version
Framework: 4.16.2-dev
Console  : 4.16.2-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali fully patched.

**Comment by busterb** [comment]
What version of MSSQL? Also doesn't seem like you have a username set.

**Comment by wvu-r7** [comment]
And maybe you want `PASS_FILE` instead of `PASS-FILE`.

**Comment by bcoles** [comment]
Fake news.

```
msf > use auxiliary/scanner/mssql/mssql_login 
rhost => 172.16.191.166
msf auxiliary(scanner/mssql/mssql_login) > set rhosts 172.16.191.166
rhosts => 172.16.191.166
msf auxiliary(scanner/mssql/mssql_login) > run

[*] 172.16.191.166:1433   - 172.16.191.166:1433 - MSSQL - Starting authentication scanner.
[*] Error: 172.16.191.166: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::MSSQL)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/mssql/mssql_login) > set username sa
username => sa
msf auxiliary(scanner/mssql/mssql_login) > set PASS_FILE /root/secret
PASS_FILE => /root/secret
msf auxiliary(scanner/mssql/mssql_login) > run

[*] 172.16.191.166:1433   - 172.16.191.166:1433 - MSSQL - Starting authentication scanner.
[!] 172.16.191.166:1433   - No active DB -- Credential data will not be saved!
[-] 172.16.191.166:1433   - 172.16.191.166:1433 - LOGIN FAILED: WORKSTATION\sa:password (Incorrect: )
[+] 172.16.191.166:1433   - 172.16.191.166:1433 - Login Successful: WORKSTATION\sa:password1
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/mssql/mssql_login) > 
```

Admittedly the error output sucks. It's awfully repetitive:

`[*] 10.0.0.179:1433 - Error: 10.0.0.179: Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::MSSQL)`

This could be improved by rescuing from the `run_host` method with something like:

```ruby
  rescue Metasploit::Framework::LoginScanner::Invalid => e
    if e.message.start_with?("Cred details can't be blank")
      print_error 'No valid username and password combinations were provided.'
    end
  end
```

Ideally the username and password combinations should be checked prior to launching the module against any hosts.

**Comment by wvu-r7** [comment]
Closing this.
