### ISSUE TITLE
metasploit/lib/msf/core/payload/uuid.rb:46:in `<class:UUID>': uninitialized constant Msf::Payload::UUID::ARCH_R (NameError)

### ISSUE THREAD

**Issue by bill-e-ghote** [rapid7/metasploit-framework#8920]
[err.txt](https://github.com/rapid7/metasploit-framework/files/1275997/err.txt)
## Steps to reproduce

How'd you do it?

1. just run msfconsole

See attached err.txt file, which is the output from stderr from running:
[err.txt](https://github.com/rapid7/metasploit-framework/files/1275995/err.txt)

msfconsole 2>err.txt

### Metasploit version

From github, latest rev.

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).
... unfortunately, msfconsole won't run.
git log -1 --pretty=oneline >
6051a1a1c103a274285b3dbd7d1bd74bc2ff2de4 (HEAD -> master, origin/master, origin/HEAD) Land #8910, Use meta redirect instead of JS redirect in 2 modules

### I installed Metasploit with:
... this will put me on my own, unfortunately.
Gentoo / Pentoo, Package installed from git using net-analyzer/metasploit-9999
Numerous local dev-ruby packages installed using local repository due to Pentoo lagging Ruby dependencies.

### OS
What OS are you running Metasploit on?

Gentoo / Pentoo.

### General comment.
I'm happy to debug this further on my end, but running beyond my own Ruby experience to debug it...
Thanks for any feedback.

**Comment by bill-e-ghote** [comment]
[err.txt](https://github.com/rapid7/metasploit-framework/files/1276002/err.txt) stderr output as described in the issue text.

**Comment by timwr** [comment]
Did you update properly?
Try:
```
gem install bundler
bundle
```

**Comment by busterb** [comment]
yeah, you are somehow behind a revision on the rex-arch gem

**Comment by bill-e-ghote** [comment]
Thanks for the pointer. I've not been using bundle to update (trying to keep Gentoo portage update clean system, more or less), but have apparently lost track of latest versions of more than a few gems. Will update using bundle from a user perspective and see what I can manage.

**Comment by bill-e-ghote** [comment]
So, "updating" rex-arch was insufficient, but uninstalling and reinstalling it fresh fixed it.
Thanks, please consider this case closed.
