### ISSUE TITLE
NTP Protocol Fuzzer returns "Auxiliary failed: NoMethodError"

### ISSUE THREAD

**Issue by vnebelung** [rapid7/metasploit-framework#8947]
**Steps to reproduce**

1. Start Kali linux
2. Update with `apt-get update` + `apt-get upgrade` + `apt-get dist-upgrade`
3. `root@kali:~# msfconsole`
4. `msf > use auxiliary/fuzzers/ntp/ntp_protocol_fuzzer`
5. `msf auxiliary(ntp_protocol_fuzzer) > set RHOSTS 192.168.2.104` // Target IP
6. `run`
`[*] 192.168.2.104:123 fuzzing short version and mode combinations`
`[-] Auxiliary failed: NoMethodError undefined method 'size' for #<Rex::Proto::NTP::NTPGeneric:0x0055749b6f31e0>`
`[-] Call stack:`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:167:in 'block (2 levels) in fuzz_version_mode'`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:159:in 'each'`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:159:in 'block in fuzz_version_mode'`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:158:in 'each'`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:158:in 'fuzz_version_mode'`
`[-]   /usr/share/metasploit-framework/modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb:87:in 'run_host'`
`[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in 'block (2 levels) in run'`
`[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in 'block in spawn'`
`[*] Auxiliary module execution completed`

**Comment by elenoir** [comment]
Hello,

Can you post the results of : 

`show options`

and : 

`show advanced`

Thanks !

**Comment by busterb** [comment]
I think the 'size' needs to be replaced with 'num_bytes' here.

**Comment by vnebelung** [comment]
**Options**

`msf auxiliary(ntp_protocol_fuzzer) > show options`

`Module options (auxiliary/fuzzers/ntp/ntp_protocol_fuzzer):`

`   Name     Current Setting  Required  Description`
`   ----     ---------------  --------  -----------`
`   RHOSTS   192.168.2.104    yes       The target address range or CIDR identifier`
`   RPORT    123              yes       The target port (UDP)`
`   SLEEP    0                yes       Sleep for this many ms between requests`
`   THREADS  1                yes       The number of concurrent threads`
`   WAIT     250              yes       Wait this many ms for responses`

**Advanced**

`msf auxiliary(ntp_protocol_fuzzer) > show advanced`

`Module advanced options (auxiliary/fuzzers/ntp/ntp_protocol_fuzzer):`

`   Name                    Current Setting  Required  Description`
`   ----                    ---------------  --------  -----------`
`   CHOST                                    no        The local client address`
`   CPORT                                    no        The local client port`
`   FuzzChar                X                yes       Sets the character to use for generating long strings`
`   FuzzTracer              MSFROCKS         yes       Sets the magic string to embed into fuzzer string inputs`
`   MODES                                    no        Modes to fuzz (csv)`
`   MODE_6_OPERATIONS                        no        Mode 6 operations to fuzz (csv)`
`   MODE_7_IMPLEMENTATIONS                   no        Mode 7 implementations to fuzz (csv)`
`   MODE_7_REQUEST_CODES                     no        Mode 7 request codes to fuzz (csv)`
`   ShowProgress            true             yes       Display progress messages during a scan`
`   ShowProgressPercent     10               yes       The interval in percent that progress should be shown`
`   VERBOSE                 false            no        Enable detailed status messages`
`   VERSIONS                2,3,4            no        Specific versions to fuzz (csv)`
`   WORKSPACE                                no        Specify the workspace for this module`
