### ISSUE TITLE
very slow keyboard repeat rate in windows msfonsole

### ISSUE THREAD

**Issue by kayaker-msf** [rapid7/metasploit-framework#8959]
It seems nobody uses windows, but I'm one of the few and this is very annoying to me.

Somewhere between 4.15.0 and 4.15.14 (not 100% sure but close) something happened with msfonsole in windows and keyboard repeat rate has become very slow.
Deleting a long commands pressing del key takes some time (certainly more than one is used to)

It is still happening with latest version 4.16.7.
I'm running msfoncole.bat directly in a cmd.exe (in cmd.exe repeat rate is ok)
I was waiting to somebody to notice but nothing so far, so I came here to generate an issue.
Please, please, can somebody take a look at it?

### I installed Metasploit with:
.msi installer

### OS
What OS are you running Metasploit on?
WINDOWS

**Comment by busterb** [comment]
Sorry to hear that. The only thing I can think of that updated recently for terminal handling is bumping rb-readline. Do you know how to change that to see if it is the problem?

**Comment by busterb** [comment]
seems pokey in 4.15.4, but I'm not sure if I recall when it wasn't

**Comment by timwr** [comment]
It's worth checking if `msfconsole.bat -L` makes a difference (although I'm not sure it's supported on Windows).

**Comment by kayaker-msf** [comment]
I've tried -L, it makes no difference.
repro (in my case at least) it's simple.
I've tested in a couple of machines, fire up msfconsole.bat inside a cmd.exe and press a key and keep it down, repeat rate is painfully slow. try to delete a long typed command and it's painful.

crappy sample
![slow](https://user-images.githubusercontent.com/29690404/30458067-57626362-9980-11e7-947f-a505b66f4bb0.gif)

**Comment by wwebb-r7** [comment]
I poked at this some today with a somewhat older release and honestly I can't reproduce it - not that I think ruby applications run great on Windows in the first place, but it wasn't painfully slow like that.

Which Windows versions have you experienced this on?  I have a strong feeling it doesn't matter but I'll try to replicate one of your environments.

**Comment by kayaker-msf** [comment]
Windows Server 2012 & Windows Server 2012R2
is there some wait time somwhere I can tweak ? I don't mind.

**Comment by wwebb-r7** [comment]
Alright, it doesn't really help you out but I did reproduce it on Windows 10 Enterprise with 4.16.8, and I'll agree that it's fairly unacceptable compared to behavior in older versions.

**Comment by kayaker-msf** [comment]
That's good news, we're halfway there then ... :-)

**Comment by busterb** [comment]
I started a regular command shell on Windows 10 and saw similar behavior with psql.exe. I wonder if this is a Windows regression. Felt like being on a 1200 bps modem

**Comment by kayaker-msf** [comment]
Problem is not related or limited to latests windows.
I've tested since 4.15.4 and it happens in Windows Server 2008R2 , Windows Server 2012 and Windows Server 2012R2.

**Comment by Junohea** [comment]
I can add to this that the issue occurs in Windows 7 as well. 
4.15-2-dev no problems with repeat-rate
4.16.14 repeat-rate issue returns

Also, historically Metasploit's console on Windows has always had this weird lag issue. (so much so that I moved to using metasploit in a docker container to alleviate it); however, after updating the Windows installation of Metasploit to version 4.15-2-dev the lag disappeared. Since updating recently to 4.16.14 the lag is back.

**Comment by wwebb-r7** [comment]
I can't say it's my top priority but I will be looking into this

**Comment by SelfLeaker** [comment]
Current versions (free/pro) still have this issue. Any updates on this topic?

**Comment by NoPurposeInLife** [comment]
Current versions (free) still have this issue. Any updates on this topic?
