### ISSUE TITLE
msfvenom uninitialized constant ApplicationController (Name Error)

### ISSUE THREAD

**Issue by Tynem01** [rapid7/metasploit-framework#8966]
I need help
So I type msfvenom and this happens:

    msf > msfvenom
    [*] exec: msfvenom

    /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:471:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:471:in `block in eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:469:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:469:in `eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:346:in `eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.3/config/environment.rb:5:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.3/lib/msfenv.rb:18:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.3/lib/msfenv.rb:18:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.3/msfvenom:10:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.3/msfvenom:10:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `load'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `<main>'

I have tried removing metasploit framework and getting it again, but this keeps happening
I am also a complete noob at this

**Comment by h00die** [comment]
msfvenom should be run from a command prompt, not an MSF prompt.
However, i think it would be nice if venom told you such. exit msf, run it again, enjoy!

**Comment by Tynem01** [comment]
okay so i ran msfvenom from command prompt and it worked, showed the info for it, but right above that it says   Error: no options

**Comment by h00die** [comment]
Perfect, that's expected behavior since you ran it without options. Either jump on IRC or check out metasploit unleashed to learn more about how to use msfvenom
