### ISSUE TITLE
MINIMUM_LIBSODIUM_VERSION

### ISSUE THREAD

**Issue by borela** [rapid7/metasploit-framework#8972]
## Steps to reproduce

How'd you do it?

1. Run msfconsole

## Expected behavior

Not get the warning message.

## Current behavior

```
C:/Metasploit/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION
C:/Metasploit/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: previous definition of MINIMUM_LIBSODIUM_VERSION was here
C:/Metasploit/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2
C:/Metasploit/embedded/lib/ruby/gems/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: previous definition of MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2 was here
```

### Metasploit version

```
Framework: 4.15.7-dev-9aba360f2b68310b017f38f2b1991efdd5ebcc9c
Console  : 4.15.7-dev-9aba360f2b68310b017f38f2b1991efdd5ebcc9c
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Windows 10 x64

I already had ruby installed before installing metasploit, conflict maybe?

**Comment by sempervictus** [comment]
@busterb: this hit me on Arch too, with the binary installer...

**Comment by avast1** [comment]
Same here installed the Windows MS package  metasploit-4.14.1-windows-x64-installer.exe

Getting the same errors on startup.

**Comment by Andrew8127** [comment]
I'm having the same issue 

`C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION
C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:10: warning: previous definition of MINIMUM_LIBSODIUM_VERSION was here
C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: already initialized constant RbNaCl::Sodium::Version::MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2
C:/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:11: warning: previous definition of MINIMUM_LIBSODIUM_VERSION_FOR_ARGON2 was here`

**Comment by busterb** [comment]
I'll take a look. This is probably OS-dependent due to a require order.

**Comment by lupor0x** [comment]
I'm get those errors too

**Comment by dmknght** [comment]
Hi! I am on Parrot OS 3.10 and i am having this problem (metasploit framework). I checked log and i saw libsodium18 has been replaced by libsodium23.
