### ISSUE TITLE
meterpreter getsystem timeout when elevating from local administrator

### ISSUE THREAD

**Issue by Rogdham** [rapid7/metasploit-framework#8981]
## Steps to reproduce

1. Connect on a Windows machine as a local administartor
2. Use the “run as administrator” function to get a meterpreter session (e.g. after having created a `windows/meterpreter/reverse_tcp` exe file with msfvenom)
3. Use the `getsystem` command from the meterpreter session to elevate privileges to `NT AUTHORITY\System`

Note: tested on Windows 7 32 and 64 bits, French editions.

## Expected behavior

As in Kali live (kali-linux-2016.2-amd64.iso), version `4.12.22-dev`:

```
meterpreter > sysinfo
Computer        : BROCCOLINI
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x86
System Language : fr_FR
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x86/win32
meterpreter > getuid
Server username: broccolini\admin
meterpreter > getsystem
...got system via technique 1 (Named Pipe Impersonation (In Memory/Admin)).
meterpreter > getuid
Server username: AUTORITE NT\Système
meterpreter >
```

*Edit: it worked also on `kali-linux-2017.1-amd64.iso`, version `4.14.10-dev`.*

## Current behavior

The `getsystem` command timeouts, although it works.

```
meterpreter > sysinfo
Computer        : BROCCOLINI
OS              : Windows 7 (Build 7601, Service Pack 1).
Architecture    : x86
System Language : fr_FR
Domain          : WORKGROUP
Logged On Users : 4
Meterpreter     : x86/windows
meterpreter > getuid
Server username: broccolini\admin
meterpreter > getsystem
[-] Error running command getsystem: Rex::TimeoutError Operation timed out.
meterpreter > getuid
Server username: AUTORITE NT\Système
meterpreter >
```

### Metasploit version

- `4.16.6-dev`, Kali rolling via apt
- `4.16.6-dev`, Kali LiceCD `kali-linux-2017.2-amd64.iso`
- `4.16.7-dev`, Arch Linux via pacman

**Comment by Rogdham** [comment]
Not an issue on https://github.com/rapid7/metasploit-payloads side: I replaced the `elevator.*.dll` on old kali-linux-2016.2-amd64.iso, and `getsystem` is not timeouting.

I'm trying to look at the history of files that were possibly impacted in metasploit, but no luck so far.

**Comment by Rogdham** [comment]
So it works on `kali-linux-2017.1-amd64.iso` but not on `kali-linux-2017.2-amd64.iso`, meaning that the problem was introduced between version `4.14.10-dev` and `4.16.6-dev`.

**Comment by mapagm** [comment]
I have the same issue with getsystem -> timeout.

**Comment by OJ** [comment]
Ok this is concerning. I'll put some time into it.

**Comment by Rogdham** [comment]
I found a system where metasploit was installed in version `4.16.1-dev`, and the issue is not present.

So the problem was introduced between `4.16.1-dev` and `4.16.6-dev`.

**Comment by OJ** [comment]
Looks like other commands suffer this too (such as `getprivs`).

**Comment by busterb** [comment]
I tried a bisect, and it appears to land somewhere in the middle of named pipe pivot territory. Unfortunately that area is a little hard to narrow down due to some ABI changes that kill the sessions without the corresponding binaries. git bisect left me with:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
abc80655b7746fa0e812ca0864f55d7b181c74a5
e3de01219a5763790568cadf60feea4acec63e47
816e78b6f6206de52b96f3ffaec7b969f4b038ad
fdc9864b61dc0ea656cdb461de8d060446a6eb6c
7acd772c10cbe971acc0616e814e24419aa11543
We cannot bisect more!

**Comment by OJ** [comment]
WHy am I not surprised? :)

**Comment by OJ** [comment]
FOUND IT!

I AM STUPID!

REALLY REALLY STUPID!

![image](http://www.reactiongifs.com/r/hmmrhed.gif)

Fix coming very shortly.

**Comment by OJ** [comment]
Sorry about this, fixed in https://github.com/rapid7/metasploit-framework/pull/9011, requires changes in Meterpreter too.

**Comment by Rogdham** [comment]
I'm confirming #9011 fixes the issue with `getsystem` and `getprivs`.

Thanks @OJ for the fix, now you can continue on your mission to make getsystem great again!

**Comment by OJ** [comment]
Awesome thanks for testing @Rogdham. Goddammit this troll is going to be the death of me! :trollface:
