### ISSUE TITLE
Auto hide main activity after first launch

### ISSUE THREAD

**Issue by BlaacckK** [rapid7/metasploit-framework#8995]
hello,
I was wondering how the main activity can be hidden after first launch.i know there is an option in meterpreter but i want it to hide self automatically after first launch.

**Comment by wwebb-r7** [comment]
I'm afraid we don't have anything to hide the main activity.  Perhaps we're having a language barrier issue here.  Apologies if so.  If you are referring to stealth/evasions and/or persistence, please rephrase your question and resubmit.  Thanks.
