### ISSUE TITLE
meterpreter client source code ( C# )

### ISSUE THREAD

**Issue by tomsmith17** [rapid7/metasploit-framework#9002]
Hi,
Where I can find meterpreter client source code ( C# )?
The code which run on victim system to connect to metasploit listener.

**Comment by pbarry-r7** [comment]
Hi @tomsmith17, Meterpreter payloads can be found in the https://github.com/rapid7/metasploit-payloads and https://github.com/rapid7/mettle repos.  For the current Windows Meterpreter, you are probably looking for https://github.com/rapid7/metasploit-payloads/tree/master/c/meterpreter.

Feel free to hop on the #metasploit IRC channel or [R7 forum](https://kb.help.rapid7.com/discuss/) if you have additional questions.

**Comment by OJ** [comment]
Bear in mind there is no C# implementation.
