### ISSUE TITLE
Android meterpreter timeouts when downloading lots of large files

### ISSUE THREAD

**Issue by harshil2105** [rapid7/metasploit-framework#9003]
After getting a meterpreter shell on a Android and I use the command " Download -r sdcard/Media/a.img the problem is after some time it downloads one or two images then it says "timeout error" and stops downloading.....what should I do if I want to. Download a large file from a target phone to my server(without getting a timeout error)????

**Comment by BlaacckK** [comment]
"Download -r sdcard/Media/a.img" a.img is a file not a directory.If you are trying to download a directory use "Download -r sdcard/Media" .The error maybe because target's screen turns off.Trying using "wakelock" command.

**Comment by timwr** [comment]
I think this was fixed with https://github.com/rapid7/metasploit-framework/pull/10442 (https://github.com/rapid7/metasploit-payloads/pull/293)
