### ISSUE TITLE
Meterpreter Mimikatz Extension - Issues with German Windows

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#9007]
Again a problem with german windows (NT 4.0) caused by this check:
https://github.com/rapid7/metasploit-framework/blob/b10d6b8b63b333e386c9d4a8f2d5bb489b050356/lib/rex/post/meterpreter/ui/console/command_dispatcher/mimikatz.rb#L162

In a german Windows the User Account is named "NT AUTHORITÄT\SYSTEM" and this check fails even if we have system rights. Is there a better way to check for SYSTEM rights?

**Comment by FireFart** [comment]
Little update from irb:
```
>> client.sys.config.getuid
=> "NT-AUTORIT\xC4T\\SYSTEM"
>> client.sys.config.getsid

[*] 10.x.x.x - Meterpreter session 4 closed.  Reason: Died
```

So there would be an `is_system?` method in https://github.com/rapid7/metasploit-framework/blob/b10d6b8b63b333e386c9d4a8f2d5bb489b050356/lib/rex/post/meterpreter/extensions/stdapi/sys/config.rb#L50 which checks on the SID but the call to `getsid` results in a meterpreter crash :/

**Comment by OJ** [comment]
The `getsid` option is definitely the way it should be done, but I have no idea why it kills Meterp. I'll see if I can dig up a VM and take a look.

**Comment by OJ** [comment]
Ah ha, this would be it. Check it out. MSF does [this](https://github.com/rapid7/metasploit-framework/blob/b10d6b8b63b333e386c9d4a8f2d5bb489b050356/lib/rex/post/meterpreter/extensions/stdapi/sys/config.rb#L50-L52):
``` ruby
  def is_system?
    getsid == SYSTEM_SID
  end
```
Which invokes [this](https://github.com/rapid7/metasploit-payloads/blob/c2ef6da12f59b902bbf2252e8b4034f211e35591/c/meterpreter/source/extensions/stdapi/server/sys/config/config.c#L142-L173) in Meterpreter:
``` c
DWORD request_sys_config_getsid(Remote* pRemote, Packet* pRequest)
{
	DWORD dwResult;
	BYTE tokenUserInfo[4096];
	LPSTR pSid = NULL;
	Packet *pResponse = packet_create_response(pRequest);

	do
	{
		dwResult = get_user_token(tokenUserInfo, sizeof(tokenUserInfo));
		if (dwResult != ERROR_SUCCESS)
		{
			break;
		}

		if (!ConvertSidToStringSidA(((TOKEN_USER*)tokenUserInfo)->User.Sid, &pSid))
		{
			BREAK_ON_ERROR("[GETSID] Unable to convert current SID to string");
		}

	} while (0);

	if (pSid != NULL)
	{
		packet_add_tlv_string(pResponse, TLV_TYPE_SID, pSid);
		LocalFree(pSid);
	}

	packet_transmit_response(dwResult, pRemote, pResponse);

	return dwResult;
}
```
Note the use of `ConvertSidToStringSidA`, which according to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa376399(v=vs.85).aspx):

![image](https://user-images.githubusercontent.com/28896/30895212-15f31974-a38c-11e7-9354-20c7448f4fd1.png)

So for this to work, we'd need to find an alternative function. Either that or we return the raw SID back to MSF and let MSF do it.

Thoughts? Worth the effort?

**Comment by OJ** [comment]
Hmmm, according to [OSR](http://www.osronline.com/showThread.cfm?link=10387):
```
Remarks
The ConvertSidToStringSid function uses the standard S-R-I-S-S... format =
for
SID strings. For more information about SID string notation, see SID
Components.

Requirements =

  Windows NT/2000: Requires Windows 2000.
  Header: Declared in Sddl.h.
  Library: Use Advapi32.lib.
  Unicode: Implemented as Unicode and ANSI versions on Windows 2000.
```
MSDN contradicts this though. My guess is that it'd be fine in 2k but not NT.

**Comment by OJ** [comment]
From the same thread, perhaps we can rely on `RtlConvertSidToUnicodeString`:
```
NTSYSAPI
NTSTATUS
NTAPI
RtlConvertSidToUnicodeString (
    IN OUT PUNICODE_STRING UnicodeString,
    IN PSID Sid,
    IN BOOLEAN AllocateString
    );

It is implemented in both kernel and user mode.
And at least from NT 4.
```

**Comment by FireFart** [comment]
@OJ from my local `sddl.h`:
```
#if (_WIN32_WINNT >= 0x0500)
_Success_(return != FALSE)
BOOL
WINAPI
ConvertSidToStringSidA(
    _In_  PSID     Sid,
    _Outptr_ LPSTR  *StringSid
    );

_Success_(return != FALSE)
BOOL
WINAPI
ConvertSidToStringSidW(
    _In_ PSID Sid,
    _Outptr_ LPWSTR * StringSid
    );

#ifdef UNICODE
#define ConvertSidToStringSid  ConvertSidToStringSidW
#else
#define ConvertSidToStringSid  ConvertSidToStringSidA
#endif // !UNICODE
```

According to https://msdn.microsoft.com/en-us/library/6sehtctf.aspx `0x0500` is Windows 2000 so I think it's only supported from Win2k onwards.

**Comment by OJ** [comment]
OK, there's a branch with a rather hopeful fix for this here @FireFart https://github.com/OJ/metasploit-payloads/tree/getsid-fix-nt4

The commit that's got the changes in it can be found here: https://github.com/OJ/metasploit-payloads/commit/7be08ed4309857cc47a552e624ca8006caa32477

In short, I'm using `Rtl*` functions for SID to String conversion instead of the later APIs that aren't present. If you could give this a spin that'd be great. From there, we can adjust the mimikatz code that checks to see if the current session is system using the `is_system?` function.

**Comment by busterb** [comment]
This should be fixed now.
