### ISSUE TITLE
Travis docker-compose Build Jobs failed with timeouts

### ISSUE THREAD

**Issue by mpizala** [rapid7/metasploit-framework#9019]
## Steps to reproduce

Trigger travis builds with a commit and docker-compose job failed with a timeout.

Details: https://travis-ci.org/rapid7/metasploit-framework/jobs/281087764

**Comment by FireFart** [comment]
Thanks taking a look into this!

**Comment by FireFart** [comment]
@mpizala fix is here: #9020 Thanks for reporting!

**Comment by mpizala** [comment]
@FireFart Thanks for fixing!
