### ISSUE TITLE
Error in payload/linux/x86/shell_bind_tcp

### ISSUE THREAD

**Issue by Nakomoto** [rapid7/metasploit-framework#9022]
1.Go to (`use payload/linux/x86/shell_bind_tcp`)
2.and write 
(`generate -e x86/shikata_ga_nai -b /xff -i 3 -lpot=5555`) 
 || 
( `generate -e x86/shikata_ga_nai -b /xff -i 3 -lport=5555`)

**Expected**
Payload generation failed: The argument could not be parsed correctly.

**Comment by pbarry-r7** [comment]
Please don't open new issues for help.  See 9021 for details.
