### ISSUE TITLE
Metasploit problem "spool" problem

### ISSUE THREAD

**Issue by yorondahacker** [rapid7/metasploit-framework#9025]
Hello please i need help to fix this
when i open metasploit i get this error : 

[*] Processing /root/.msf4/msfconsole.rc for ERB directives.
resource (/root/.msf4/msfconsole.rc)> “spool /root/msf_console.log”
[-] Unknown command: “spool.

here is a screenshot

![screenshot from 2017-09-30 00-31-21](https://user-images.githubusercontent.com/30133055/31036956-84bcfc1a-a53c-11e7-8e2d-a2fd8f25cf2f.png)

so please help me as fast as you can

**Comment by h00die** [comment]
What is the contents of `msfconsole.rc`?  most likely the first line is that spool command.

**Comment by wvu-r7** [comment]
Looks like you have a stray double quote.

**Comment by wvu-r7** [comment]
Or two.

**Comment by yorondahacker** [comment]
@h00die i opened msfconsole.rc
thats whats in it 
“spool /root/msf_console.log”

**Comment by wvu-r7** [comment]
Remove the quotes. Try again.

**Comment by yorondahacker** [comment]
@wvu-r7 yep lol it's working now
thank you very much

**Comment by wvu-r7** [comment]
np!
