### ISSUE TITLE
looks like successful, but actually not. what I can do?

### ISSUE THREAD

**Issue by lgy194** [rapid7/metasploit-framework#9037]
## Steps to reproduce

set ATTACK STOPCPU
set RHOST 10.10.*.*
set RPORT 44818
run

[*] 10.10.*.*:44818 - 10.10.10.95:44818 - CIP - Running RESETETHER attack.
[*] 10.10.*.*:44818 - 10.10.10.95:44818 - CIP - Got session id: 0xd020d
[*] 10.10.*.*:44818 - 10.10.10.95:44818 - CIP - RESETETHER attack complete.
[*] Auxiliary module execution completed

looks successful. However, the system is still working. Wireshark shows Malformed Package. it looks like the unit can know it's an attack pack and ignore it. that's mean attack action unsuccessful.

### Metasploit version
[4.16.7]
### OS
Kali

I hope to have a successful attack. How can I deal with it? thanks.

**Comment by h00die** [comment]
Can be helpful to know what module was run.
It successful sent the packets, but most likely didn't check to see if the service had crashed or not.
If the service or server didn't crash it's not vulnerable.
