### ISSUE TITLE
wlan_geolocate API error

### ISSUE THREAD

**Issue by YSpoof** [rapid7/metasploit-framework#9042]
Screenshoot:

http://i.imgur.com/U4S0qAo.png

MSF:

Framework: 4.16.9-dev

Console  : 4.16.9-dev

Payload:

android/meterpreter/reverse_tcp

OS:

Kali Linux 2017.02
#8928

**Comment by h00die** [comment]
#9033 is the fix. Try it, let me know if it works for you.

**Comment by YSpoof** [comment]
Thanks @h00die !! Worked.
