### ISSUE TITLE
'color false' not affecting the prompt

### ISSUE THREAD

**Issue by glezo1** [rapid7/metasploit-framework#9096]
I love running msf as a service (msfd) an using netcat as a thin client rather than msfconsole, as nc is up in less than one second. 
So, working with nc, I always set 'color false', and I came to realize that the prompt is not honouring the color false directive.

## Steps to reproduce
>msfd -q -a 0.0.0.0
>nc 127.0.0.1 55554
nc>color false
nc>set PROMPT _msf_

After setting the prompt, you can see that nc receives from the server:
<prompt>
0x20 [blank]
0x01 [SOH, start of header]
0x02 [SOT, start of text]
0x3E [>] 
0x20 [blank]

The issue lays on removing the 0x01 and 0x02 from the prompt when 'color false' has been stablished.

## Expected behavior
<prompt>
0x20 [blank]
0x3E [>] 
0x20 [blank]

## Current behavior
<prompt>
0x20 [blank]
0x01 [SOH, start of header]
0x02 [SOT, start of text]
0x3E [>] 
0x20 [blank]

### Metasploit version
framework: 4.16.7-dev
console: 4.16.7-dev

### OS
kali 2017.2

thanks!

**Comment by wvu-r7** [comment]
Sounds like you have a fix. Mind submitting a patch?

**Comment by timwr** [comment]
I think I ran into this many moons ago with pymetasploit and msfrpcd: https://github.com/allfro/pymetasploit/pull/5

**Comment by timwr** [comment]
Ah you can just fix this with `set PROMPTCHAR >`:
e.g
```
color false
set PROMPT nc
set PROMPTCHAR >
```

**Comment by wvu-r7** [comment]
Try setting `PromptChar` when `Prompt` isn't set. You get #2160. I'm going to fix that one day...

**Comment by glezo1** [comment]
set PROMPTCHAR >
is a good enough (perfect, indeed) workaround for my needs.
Thank u all!

**Comment by wvu-r7** [comment]
#9102
