### ISSUE TITLE
Screenshot command for Android is not working with a reverse tcp connection

### ISSUE THREAD

**Issue by mahmoudissam** [rapid7/metasploit-framework#9112]
## Steps to reproduce
Run the command: "screenshot" on a reverse TCP connection, give you the error:
[-] stdapi_ui_desktop_screenshot: Operation failed: 1

## Expected behavior
To capture the screen or save it somewhere.

## Current behavior
Gets the error: [-] stdapi_ui_desktop_screenshot: Operation failed: 1

## System stuff
Tested on : Android 6.0.1 - Linux 3.10.61-8299335 (armv8l) - Samsung J7 dual sim.

### Metasploit version
metasploit v4.16.11-dev

### I installed Metasploit with:
Kali package via apt

### OS
What OS are you running Metasploit on?
Kali Linux 2017.2

**Comment by timwr** [comment]
Unfortunately this command only works if you injected into an apk and the APK activity is in the foreground. Let me add a more verbose error to avoid confusion.

**Comment by mahmoudissam** [comment]
Thanks timwr, but that works fine on galaxy s8

**Comment by Ordana** [comment]
Same problem here :/

**Comment by busterb** [comment]
If any of you happened to have 'adb logcat' running, you could look at what  the error message is and possibly debug it. 'Operation failed: 1' isn't very helpful.

**Comment by timwr** [comment]
@Ordana  the `meterpreter> screenshot` command on Android is sandboxed and can only capture the apps own framebuffer and the default android meterpreter payload has no UI (so there is no buffer to capture).
I'll fix the error message to say something sensible.

**Comment by morgensterne** [comment]
Same here.
