### ISSUE TITLE
db_import does not import: Tags, Comments, Arch, Info Columns 

### ISSUE THREAD

**Issue by RickTorresJr** [rapid7/metasploit-framework#9116]
## Steps to reproduce

How'd you do it?

1. Manually added Tag, Comment and Info:

`hosts --tag tag-test 10.0.1.1`
`hosts --comment 'Test Comment' 10.0.1.1`
`hosts --info 'Fake info' 10.0.1.1`

2. Confirm all commands populated:
`hosts -u -c address,name,service_count,vuln_count,os_name,os_flavor,os_sp,arch,purpose,comments,tags`

3. Export the database to XML:
`db_export -f xml db_export_test.xml`

4. Exit msfconsole and purge the old database:
`exit`
`msfdb reinit`

5. Open msfconsole and import the XML:
`msfconsole -q`
`db_status`
`db_import db_export_test.xml`

6. Confirm all data was populated (Fails):
`hosts -u -c address,name,service_count,vuln_count,os_name,os_flavor,os_sp,arch,purpose,comments,tags`

## Expected behavior
Tags, Comments and Info from the XML file should be imported using db_import.

## Current behavior
Tags, Comments and Info from the XML file are not being imported using db_import.

What happens instead?
Tags, Comments and Info are empty.

### Metasploit version
Framework: 4.16.11-dev
Console  : 4.16.11-dev

### I installed Metasploit with:
- [X ] Kali package via apt (came installed)

### OS

What OS are you running Metasploit on?
Kali Linux Rolling x64

**Comment by nicmilot** [comment]
This is a big problem for me. So I found an alternative until rapid7 fix the problem. We can use postgresql to export and import.

Command to export will look like that:

```bash
pg_dump -U msf -h localhost -d msf -f /path/to/your/new/export/database.sql
```

It will ask you a password which you can find in `/usr/share/metasploit-framework/config/database.yml`


But, it still a too long process, so to help my workflow I made a bash script. You will have to modify for you scenario. I know is not the best solution and coding but I just want something quick that actually work.


```bash
#!/bin/bash

# Why ? Because when using built-in db_export of metasploit, it doesnt export all columns.
# How ? Postgresql! We grab posgresql password and export with pg_dump.
# We will take the date as backup file name

dbFile="/usr/share/metasploit-framework/config/database.yml"
exportPath="/path/to/your/export/folder"
backupName=$(date "+%e%b%Y")

# We will find the 3 lines starting with passwords and selecting the 4th word of the 2nd line
# Which is suppose to be the production pasword
PGPASS=$(grep 'password' ${dbFile} | head -2 | tail -1 | cut -d " " -f 4)

function pgcmd() {
  PGPASSWORD=${PGPASS} pg_dump -U msf -h localhost -d msf -f ${exportPath}/${backupName}.sql
# verify that our new export is there.
  ls -lat ${exportPath}
}

pgcmd
```
