### ISSUE TITLE
Add additional version checks for 'modules/auxiliary/scanner/lotus/lotus_domino_version'

### ISSUE THREAD

**Issue by 0xdevalias** [rapid7/metasploit-framework#9130]
Currently there are a number of files checked for version numbers:
* https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/scanner/lotus/lotus_domino_version.rb

The following list of additional endpoints will allow the version number to be extracted as well, and provide better detail for v9:

* `Help/help9_admin.nsf`
* `Help/help9_client.nsf`
* `Help/help9_designer.nsf`

Looking at other tools, similar files seem to exist for older versions as well:
* https://github.com/coldfusion39/domi-owned/blob/master/domi_owned/data/domino_endpoints.txt

```
help4.nsf
help5_admin.nsf
help5_client.nsf
help5_designer.nsf
help65_admin.nsf
help65_client.nsf
help65_designer.nsf
help65_iwa_en.nsf
help6_admin.nsf
help6_client.nsf
help6_designer.nsf
help70_iwa_en.nsf
help7_admin.nsf
help7_client.nsf
help7_designer.nsf
help80_iwa_en.nsf
help8_admin.nsf
help8_client.nsf
help8_designer.nsf
```

Additionally, the REST API lists the version number:
* http://203.6.182.24/api

```
{
  "services":[
    {
      "name":"Data",
      "enabled":false,
      "version":"9.0.1",
      "href":"\/api\/data"
    },
    {
      "name":"Calendar",
      "enabled":false,
      "version":"9.0.1",
      "href":"\/api\/calendar"
    },
    {
      "name":"Core",
      "enabled":true,
      "version":"9.0.1",
      "href":"\/api\/core"
    }
  ]
}
```

## Expected behavior

List the version as `9.0.1`

## Current behavior

Lists the version as `7.0.1.0`

**Comment by ccondon-r7** [comment]
Hi there! We're closing this because it hasn't been active in a while. If you want to reconfirm and re-open, feel free to do so.
