### ISSUE TITLE
post/windows/manage/migrate - AV

### ISSUE THREAD

**Issue by shaneshuford** [rapid7/metasploit-framework#9138]
## Steps to reproduce

How'd you do it?
use post/windows/manage/migrate

## Expected behavior

Migrate to an EXISTING process.

## Current behavior

Create a process, then migrate to it...
Detected by AV.

### Metasploit version

Latest

### I installed Metasploit with:
git

### OS
ubuntu server

**Comment by h00die** [comment]
Please give us more information.
What version of msf, what antivirus, what version of the av, what signature hit, what definitions update/number was it, what was the payload being migrated, what was it being migrated from, what was it being migrated to, what were the accounts (and permissions), what was the OS version.

You've not given enough info to even begin attempting to re-create this to determine what is being caught and figure out if there is a way around it.

**Comment by void-in** [comment]
Related https://github.com/rapid7/metasploit-payloads/issues/36

**Comment by busterb** [comment]
Duplicate, not much info provided here.
