### ISSUE TITLE
Re-add Sniffer Extension (POSIX METERPRETER)

### ISSUE THREAD

**Issue by realoriginal** [rapid7/metasploit-framework#9148]
## Information

I fairly believe the sniffer extension *used* to exist by memory, and searching commits, I'm fairly sure it did in the POSIX meterpreter? example PR https://github.com/rapid7/metasploit-framework/commit/77be5d3e0ae2caeae92a7170071edc9a715f9d33

## Request
Would it be possible to re-incorporate this once again (if im correct that it used to xD) into at least x86 & x64, if not all POSIX meterpreters' ?

**Comment by pbarry-r7** [comment]
We're PR'ing a new sniffer module for the new POSIX Meterpreter (Mettle) today, as a matter of fact.  :)  So it's not a re-incorporation, but rather a new version.
