### ISSUE TITLE
[BUG] shell_read, Create Android Module

### ISSUE THREAD

**Issue by CorrM** [rapid7/metasploit-framework#9172]
## Steps to reproduce

How'd you do it?

1. run module with session.shell_command Method in **android Module**

the problem is in 'shell_read' method,
if this method run one time more than the string must return
the meterpreter will freeze, and any command will return timeout
and after some seconds the payload will stop in android device
and can't use any shell method like shell_write at the same time
in the same module after shell_command called

at all i detect the problem in 'shell_read' method.
if i start command like session.shell_command('pwd')
will return what should return, but the problem will happen
and can't use shell anymore and also the meterpreter will freeze
and get timeout for any command expect 'help, exit' command
or any local command, but server side can't send or get response

My Example Module :
https://pastebin.com/N6yq0Pma

you can test shell_commandx method with '1.times'
all things will work good,
but if u change to some thing like 10.times,
will not work and problem will happen
**OR**
directly u can use any command not return any value
like
session.shell_command('session.shell_command('cd /')')
Problem will happen after that

and meterpreter return:
[-] Post interrupted by the console user

i test it in irb mode and retrun :
>> client.shell_command('pwd')
=> "/data/data/com.metasploit.stage/files\n"
>> client.shell_command('pwd')
Rex::TimeoutError: Operation timed out.
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:225:in `send_request'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:247:in `_write'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:214:in `write'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:234:in `shell_write'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:255:in `shell_command'
	from (irb):4:in `cmd_irb'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:541:in `cmd_irb'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:460:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:196:in `run'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:563:in `_interact'
	from /usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
	from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1380:in `cmd_sessions'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:460:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:206:in `run'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:48:in `<main>'

### Metasploit version
Last Version

### I installed Metasploit with:
- Kali package via apt

### OS

What OS are you running Metasploit on?
Kali 2016.2

**Comment by timwr** [comment]
This is an android/meterpreter/reverse_tcp session right? Can you try `cmd_exec` instead?

**Comment by CorrM** [comment]
This is an android/meterpreter/reverse_tcp session right?
yes.

Can you try cmd_exec instead?
it's `Work`. 👍 , Thank You Man <3
===============================
but this bug must solve.

i updated the issue with irb mode test
