### ISSUE TITLE
[Problem] Can't add new command to meterpreter

### ISSUE THREAD

**Issue by CorrM** [rapid7/metasploit-framework#9173]
## Steps to reproduce

How'd you do it?

**1**. add new item in command function in

> '/lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb'

![2nd Step](https://image.prntscr.com/image/0CTAp3EvRoOC11kqCJ31rA.png)

**2**. in the same path add function cmd_corrm
![1st Step](https://image.prntscr.com/image/wcuKr8enQY2PJhkc5quDpw.png)

**3**. add corrm function to 

> /lib/rex/post/meterpreter/extensions/android/android.rb

![3th Step](https://image.prntscr.com/image/HtKxBjsTRDarDxS_1tUGKg.png)

**After all of that it's not in** 'help'
![](https://image.prntscr.com/image/LPy0hI5NT5yBq5_6XLBM5Q.png)
and
![](https://image.prntscr.com/image/VWjSbVtGQzOzGKWsDtl3pw.png)

## Help

so, what to do to complete this thing,

and i need to run module when i enter 'corrm' command 

### Metasploit version
Last Version

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?
Kali 2016.2

#

**Comment by timwr** [comment]
Have you added `android_corrm` to meterpreter? If not filter_commands will filter it out.

**Comment by CorrM** [comment]
how to add .?

**Comment by timwr** [comment]
Try print `all` instead of `reqs.to_s`, it's not returned.
Here is an example of adding the screenshot command:
https://github.com/rapid7/metasploit-payloads/pull/182/files

**Comment by CorrM** [comment]
What Steps to change the local metasploit payload
or i must clone metasploit-payloads and what to do to make it the
base for msfvenom
,,,
and no way to add command form my side only, because that's mean
i need to change all victims payloads !
,,,
and what's about create command category like webcam Like That:
![](https://image.prntscr.com/image/wNBa9k9vTDyWm-5U-sT7Dw.png)

**Comment by CorrM** [comment]
???????? @timwr

**Comment by timwr** [comment]
To build the Android meterpreter you can follow the Android instructions here:
https://github.com/rapid7/metasploit-payloads/blob/master/java/README.md
(basically just clone it next to the framework, cd metasploit-payloads/java, `mvn package -Dandroid.sdk.path=${ANDROID_HOME} -Dandroid.ndk.path=${ANDROID_NDK_HOME} -Dandroid.release=true -P deploy`
This will automatically be picked up my msfvenom (you should see: `WARNING: Local files may be incompatible with the Metasploit Framework`).
To create a whole new command section is a bit more fiddly but you can use these files an example:
./lib/rex/post/meterpreter/extensions/android/android.rb
./lib/rex/post/meterpreter/ui/console/command_dispatcher/android.rb
Why not join our IRC channel? You'll get a much quicker response

**Comment by CorrM** [comment]
i will join 😄

**Comment by CorrM** [comment]
@timwr 
i do every thing but no change happened !!
1- there is a problem when compile
![](https://image.prntscr.com/image/TdlP0pbDTVSym0EL_4EI9g.png)
2- i change some codes in andoid payload and no change saved !!
i removed all registerCommand and delete `android_check_root.java`
and in msf i run check_root and the command give me `Device is rooted` !! HOW !!
![](https://image.prntscr.com/image/RJZoWE5_Qzy5_3BaXdVBwg.png)
3- i checked if it's realy move `AndroidManifest.xml` And `classes.dex`
to
>/usr/share/metasploit-framework/data/android/apk

and yes it's move to metasploit but payload not have the changes !!

Please, Say to me what to do !!
i need to edit the payload and add some commands !!

**Comment by timwr** [comment]
Did you install the android sdk and the component it needs?
```
echo y | android update sdk --filter tools --no-ui -a
echo y | android update sdk --filter platform-tools --no-ui -a
echo y | android update sdk --filter build-tools-23.0.0 --no-ui -a
echo y | android update sdk --filter android-10 --no-ui -a
echo y | android update sdk --filter android-19 --no-ui -a
echo y | android update sdk --filter android-3 --no-ui -a
```

**Comment by CorrM** [comment]
@timwr 
Now i Get BUILD SUCCESS,
but there is problem in msf:
```
[*] Sending stage (63858 bytes) to 192.168.1.5
[*] Meterpreter session 2 opened (192.168.1.9:5000 -> 192.168.1.5:22321) at 2017-11-08 02:15:01 -0500
[-] Failed to load extension: No module of the name ext_server_android.jar found
```
i'm so sorry for all this things but i want to make some good stuff for android hacking with **msf**

**Comment by CorrM** [comment]
I solve the problem by copy
> '/usr/share/metasploit-payloads/java/androidpayload/library/target/Metasploit-AndroidLibrary.jar'

to :
> '/usr/share/metasploit-framework/data/meterpreter/ext_server_android.jar'

and the problem now solved

Thanks @timwr

**Comment by zaramhara** [comment]
i need some help with editing payloads can anyone help me ?
