### ISSUE TITLE
enum_chrome error

### ISSUE THREAD

**Issue by OneDollarr** [rapid7/metasploit-framework#9176]
Problem when starting the module enum_chrome. fter the appearance of the session and getting the rights of the system, I run the module to grab passwords with google chrome.

And I get this error:

[*] Impersonating token: 1612
[*] Running as user 'PC\VENTEL_1982'...
[*] Extracting data for user 'PC$'...
[-] Web Data not found
[-] Cookies not found
[-] History not found
[-] Login Data not found
[-] Bookmarks not found
[-] Preferences not found
[-] Post failed: TypeError no implicit conversion of nil into String
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:80:in `initialize'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:80:in `open'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:80:in `parse_prefs'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:138:in `block in process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `process_files'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:327:in `block in run'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `each'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `run'
[*] Post module execution completed

**Comment by hxrofo** [comment]
try this:
pgrep explorer
migrate "explorer ID here"
then re-run enum_chrome with migrate set to "false".
i hope it works

**Comment by OneDollarr** [comment]
YEAH! Profit! Thank you!! ^_^

**Comment by OneDollarr** [comment]
YEAH! Profit! Thank you!! ^_^

**Comment by jmartin-r7** [comment]
Closing as answered.
