### ISSUE TITLE
mssql_login crashes mid run on invalid host

### ISSUE THREAD

**Issue by digininja** [rapid7/metasploit-framework#9181]
## Steps to reproduce

How'd you do it?

1. load up a list of RHOSTS, some of which may not be MSSQL boxes
2. run the module

## Expected behavior
When it hits invalid servers it should alert but continue on to the rest of the RHOSTS in the list rather than crashing.

## Current behavior
Instead it fails like this and does not complete the RHOST list.

```
[-] Auxiliary failed: RuntimeError Unable to parse encryption req during pre-login, this may not be a MSSQL server
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/mssql/client.rb:637:in `mssql_prelogin'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/mssql/client.rb:47:in `mssql_login'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/mssql.rb:50:in `attempt_login'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:154:in `block in each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/mssql/mssql_login.rb:71:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version

Framework: 4.16.14-dev
Console  : 4.16.14-dev

### I installed Metasploit with:
- [x ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
Kali

**Comment by digininja** [comment]
With this fix in place, if I rescan the servers it crashed on, will it now
check them or can it not check them if they don't support encryption?

**Comment by wvu-r7** [comment]
It should be able to check them if encryption is not supported.

**Comment by digininja** [comment]
Thanks.

**Comment by wvu-r7** [comment]
FYI, I did not test this. Let me know if the eyeballed change is insufficient. Thanks.

**Comment by wvu-r7** [comment]
Honestly, the `raise` looked misplaced. It was throwing away `encryption_mode` for no reason.

**Comment by digininja** [comment]
Will do.
