### ISSUE TITLE
gem error after today's pull

### ISSUE THREAD

**Issue by g33xter** [rapid7/metasploit-framework#9188]
I'm running msf on macOS sierra with ruby 2.4.2. After today's git pull I'm getting this error. I've tried installing manually that gem but got this error then [Error installing rex-ole: rex-text requires Ruby version >= 2.2.0.]. But metasploit need ruby 2.4.2. How to solve this issue?
![screen shot 2017-11-08 at 00 38 50](https://user-images.githubusercontent.com/8503135/32539195-7f901b46-c41d-11e7-8211-96820f28ec8e.png)

**Comment by pbarry-r7** [comment]
`bundle install` is what we typically do to handle gem dependencies when working off a git clone checkout.

For support items, please join us on [IRC](https://metasploit.help.rapid7.com/docs/joining-the-metasploit-irc-channel) or visit the [Rapid7 Knowledge Base](https://kb.help.rapid7.com/discuss).

**Comment by g33xter** [comment]
I tired that, even after that I'm getting same error.
