### ISSUE TITLE
How to modify the "download_exec. rb" file？

### ISSUE THREAD

**Issue by derain2012** [rapid7/metasploit-framework#9251]
The module post/linux/manage/download_exec。This module only have "curl" and "wget", my target machine is freebsd, the system did not install "curl" and "wget", only "fetch". How to modify the source code(download_exec.rb) to make "fetch" work? I tried to change the "curl" or "wget" of the source code to "fetch"，So that only the files can be downloaded but it(abc. sh) can not be executed.

**Comment by wvu-r7** [comment]
Literally working on this module.

**Comment by wvu-r7** [comment]
Since this was a programming question, I'll answer it.

You want to modify the `search_http_client` method to add a new check for `fetch`. I'll address this in the rewrite. Thanks.

**Comment by wvu-r7** [comment]
#10337

**Comment by wvu-r7** [comment]
Closing permanently, since this was just a programming question. If anything happens with this module, it'll be in a PR. Thanks.
