### ISSUE TITLE
Issue during upgrades on Fedora (27)

### ISSUE THREAD

**Issue by jeo3489** [rapid7/metasploit-framework#9281]
## Problem

When there is an upgrade for Metasploit (DNF update after it's been installed), and Metasploit gets upgraded, the binaries aren't linked correctly (Bash command not found when attempting metasploit commands). In a new install the commands work (eg, msfconsole).

Actual binaries are in /opt/metasploit-framework/bin/, symlinked to /etc/alternatives, symlinked to /usr/bin in a fresh install, and everything works. After any upgrade (usually there is a new version every day), the symlinks are no longer found in /usr/bin or /etc/alternatives, so the commands don't work.

## Expected behavior

Binaries correctly linked after updates, and commands to work eg. by typing msfconsole in terminal.

### Metasploit version

  metasploit-framework.x86_64 4.16.17+20171206113637~1rapid7-1.el6              

As well as at least the last 4 updates (possibly more)

### I installed Metasploit with:

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
The quick install for linux

### OS
Fedora 27

Also, someone else said they were having the same issue on the issue thread on the Fedora subreddit

**Comment by Chilinot** [comment]
I am also experiencing this now. I was able to use metasploit without issues after a new install. Now the commands are no longer found.

I manually added the "/opt/metasploit-framework/bin" path to my PATH as a workaround.

**Comment by busterb** [comment]
Verified. The package symlinks are handled automatically by the omnibus package system. The code itself is abstract, so this could be a bug in the underlying package builder:

https://github.com/rapid7/metasploit-omnibus/blob/master/config/software/metasploit-framework-wrappers.rb

We should try just updating the dependencies to see if this is fixed upstream. We do also build this on an old VM that maybe builds incompatible packages with current RPM systems? I'm not a frequent RPM package user, and this same build recipe works fine on Debian/Ubuntu based systems.

**Comment by bby-bishopclark** [comment]
Take a look at the RPMs you're building.  It's entirely possible to build RPMs on older machines that run perfectly well on newer boxes; the reverse is harder.  My oldest went 14 years before needing a rebuild, but it's an extreme case.
