### ISSUE TITLE
PHP Meterpreter sessions get close instantly

### ISSUE THREAD

**Issue by verura123** [rapid7/metasploit-framework#9291]
Hello there,
it is something relating to mentioned here: https://github.com/rapid7/metasploit-framework/issues/7638 but he didnt mentioned how he was able to solve it. My big sorry for not mentioning thing in prescribed proforma.
Having the same issue, establish the connection and then it dies instantly with using php then multi/handler and set the payload as **windows**/meterpreter/reverse_tcp rather then php/meterpreter/reverse_tcp. But in both the scenario it went upto sending stage and then dies. tried on stage as well as stageless.
One thing I am really still curious that does this work on client side not the server side (i.e. to the victim direct open link and I can interact and can shell as shown in this video https://www.youtube.com/watch?v=ba_n79RIKHg) is it possible? if so then how? I have tried various combinations but failed to get the exact result.
Thank U for reading my issue.

**Comment by chris948** [comment]
That issue was fixed for me with a 4.16.13-dev

What version are you running?

**Comment by busterb** [comment]
Hi, why would you set the payload to windows/meterpreter/reverse_tcp, but have a stager with php? It's not going to work.

In the above youtube video, it looks like the user had some parameters saved in his or her global config already, so it looks like they skipped a step but really didn't. If you use the `save` command, it lets you save parameters for a module that automatically get set the next time you use that module.

**Comment by verura123** [comment]
@chris948 Thank U for Ur time taken in reply. I am using the same version = metasploit v4.16.13-dev
@busterb Thank U too for Ur time taken on reply. So does that mean that we cannot acquire windows powershell through a click on a PHP link without any extra effort from victim side?

**Comment by verura123** [comment]
Hello there,
Is there anything I am not suppose to question here? I mean is my query wrong?
please help me to sort this out.
Thank You

**Comment by chris948** [comment]
You're confusing the payloads and listeners, they have to be the same.

Honestly, theres a metasploit book out there, David Kennedy, he goes into payloads and listeners. I would recommend something like that, start with the basics.
