### ISSUE TITLE
ANDRIOD Meterpreter session missing commands

### ISSUE THREAD

**Issue by sleepingspy999** [rapid7/metasploit-framework#9306]
## Steps to reproduce

Got connection from target , interact with session only get core commands no android commands.
But if i use the phone with wi-fi connection with the attack machine connected to the same network,
the connection i get back shows my wi-fi public IP what is what youd expect but i get a full session with that connection, Android commands and all ???

## Expected behavior
Should get android commands

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces

## System stuff
Kali Linux 2017.3 
### Metasploit version
Framework: 4.16.22-dev
Console  : 4.16.22-dev

### I installed Metasploit with:
- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

**Comment by sleepingspy999** [comment]
Just To add I tested the same backdoored APK's with msf listener from metaspliot v4.13.15-dev and everything works fine android commands and all ??

**Comment by timwr** [comment]
Can you help me reproduce this? Is the payload generated from the same (latest) version of metasploit? Can you post a full (redacted if you want) log?
Maybe you can also try the `AndroidMeterpreterDebug=true` option for msfvenom and post the adb logcat logs?

**Comment by sleepingspy999** [comment]
This seems to be a recurring problem for many users of the latest ver  4.16.22-dev works on any version up to this one, what seems to be happening is the Payload handler is not starting so you dont get a full session just sits there waiting for payload handler.

**Comment by timwr** [comment]
How are you generating the payload? How are you starting the listener? Can you post the log? You're not providing enough information and it's working as normal for me here.
