### ISSUE TITLE
PDB files for msfvenom-generated PE payloads 

### ISSUE THREAD

**Issue by levyjm** [rapid7/metasploit-framework#9309]
Feature request? I'm wondering if there is a way to create a pdb file with a PE file generated via msfvenom? My goal is to be able to more easily debug it.

**Comment by OJ** [comment]
The short answer is no :)

**Comment by wchen-r7** [comment]
@levyjm We don't really provide the pdb file, however, you can create it yourself. Here's what you need to do:

1. `git clone` the metasploit-payloads repository from Rapid7
2. Open the meterpreter.sln file (in the workspace directory) with Visual Studio 2013 (yup, it has to be VS 2013)
3. Under the Solution Explorer (on the right), you should see **msetsrv**. Right click on that, and click on **Properties**
4. Go to **Configuration Properties** -> **Linker** -> **Debugging**, and choose **Yes /Debug** for **Generate Debug Info**.
5. Right click on **msetsrv**, and click **Build**
6. After building, you should see a **vc120.pdb** in workspace\metsrv\Release\Win32. That's it!

When you load the DLL with IDA, it should automatically find the symbol file, and then ta-da:

![screen shot 2018-02-14 at 10 26 06 am](https://user-images.githubusercontent.com/1170914/36216697-1f1afc9a-1175-11e8-99ed-1f2c8784d187.png)
