### ISSUE TITLE
get_cookies mishandles cookies that lack a trailing semicolon

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#9332]
## Steps to reproduce

As pointed out in https://github.com/rapid7/metasploit-framework/pull/7784#issuecomment-270998701 and https://github.com/rapid7/metasploit-framework/pull/9316#issuecomment-353202026, `get_cookies` mishandles a `Set-Cookie` header which has a cookie that lacks a trailing semicolon at the very end.

For example, the follow `Set-Cookie` header:

```
k1=v1; k2=v2;k3=v3
```

Would be parsed as:

```
k1=v1; k2=v2
```

## Expected behavior

k1, k2 and k3 should be found.

## Current behavior

What happens instead?

only k1 and k2 are found.

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [/] Source install (2.4.2)

### OS

OS X

**Comment by wvu-r7** [comment]
I still intend to fix the regex further, but we should migrate to `get_cookies_parsed` regardless. Thanks for handling this.

**Comment by jhart-r7** [comment]
@wvu-r7 👍 .  I tried and failed at fixing the regex 😑

**Comment by wvu-r7** [comment]
Honestly, I tried for a non-zero number of minutes and failed as well, since the way it scans for key-value pairs is insane. I will give it another shot but probably have to rework the regex (ugh) completely. Zalgo awaits.
