### ISSUE TITLE
Sounds Plugins not playing.

### ISSUE THREAD

**Issue by robot321** [rapid7/metasploit-framework#9338]
Sounds not playing.

I've loaded sounds modules by typing `load sounds`
Also tried `load sounds verbose=true`
I've got that the Plugin loaded successully 

But when session a started nothing plays no error nothing, but it spawns meterpreter.
I'm doing it on WAN, but i think that doesn't matter to sounds plugin.

metasploit v.4.16.22-dev

OS : Kali Linux 2017

There may be errors in this post because this is my first one.

**Comment by wvu-r7** [comment]
IIRC, the `sounds` plugin calls `Rex::Compat.play_sound`, which uses `aplay` on Linux. I had to install the `alsa-utils` package on Kali for a different reason: I wanted `alsamixer`. That should fix your problem, though.

**Comment by wvu-r7** [comment]
Just a hunch. Or your sound is muted.

**Comment by robot321** [comment]
I'll try it, Thanks man :)
Nope i double checked sounds :/

**Comment by robot321** [comment]
It worked, Thanks a lot!
