### ISSUE TITLE
Android Reverse TCP screenshot not working.

### ISSUE THREAD

**Issue by robot321** [rapid7/metasploit-framework#9339]
After i've got a successfull meterpreter shell, I could issue commands (some of them) Successfully. But when i try `screenshot` it gives me a error like this,

`stdapi_ui_desktop_screenshot: Operation Failed: 1` 

Checked the command both on Rooted and Non-Rooted devices, But still gives me that error, Looked it up couldn't find anything useful. (Both on WAN and LAN)

But i could get managed to get screenshot by using android shell (`shell`). But only on rooted devices.
Oh i almost forgot, But i could use 'screenshot' command on Binded apps, but only when the Target is in that app. I tried using deafault android app "MainActivity" but it also doesn't work.
I think that the app is running on a Sandbox. But i don't know exactly.

metasploit v.4.16.22-dev
Kali Linux 2017.2

Thanks!

**Comment by chrisstone07** [comment]
This only works within the app , I.e u can only take screenshot of the screen when your app is open. Yes to take screenshot of other screens you need root permissions and run post/android/capture/screen.

**Comment by robot321** [comment]
I checked that also on a rooted device, But i got an error about saying that "Permission is Denided" 
Is there a command to grant permissions in that module.

**Comment by chrisstone07** [comment]
Well the first thing that u pointed out is an awkward error, it should work well on rooted devices. Try these steps on a rooted device

First drop into shell then, 
cd /system/bin
screencap - h and you'll see a list of available options.

Regarding permission Yes depending on the version of Android your using it varies, for 6.0 and above it doesn't ask any extra permissions. For 4.4 I think you need to give these permissions exclusively

**Comment by timwr** [comment]
Closing, thanks @chrisstone07

**Comment by hudzzz01** [comment]
thanks @chrisstone07
