### ISSUE TITLE
Error in accessing metasploit

### ISSUE THREAD

**Issue by kashifcap** [rapid7/metasploit-framework#9343]
I tried to install metasploit in termux
After executing "./msfconsole" following error occured
Could not find nokogiri- 1.8.0 in any of the sources
After running bundle install error came
An error occurred while installing network_interface
(0.0.1), and Bundler cannot continue.
Make sure that `gem install network_interface -v
'0.0.1'` succeeds before bundling.
Please help to solve this.

**Comment by busterb** [comment]
Please grab a newer checkout of metasploit, we've been on 'network_interface' 0.0.2 for months, which fixes builds for Android systems.
