### ISSUE TITLE
Metasploit not updating past 4.14.8-dev

### ISSUE THREAD

**Issue by afarney** [rapid7/metasploit-framework#9367]
## Expected behavior

What should happen?
I cant seem to get metasploit to reflect an update

## Current behavior

What happens instead?
I am fully updated according to apt:
![image](https://user-images.githubusercontent.com/18471935/34528370-5c6bd628-f06e-11e7-89ad-50ab0a546261.png)

When I launch msfconsole I get:

![image](https://user-images.githubusercontent.com/18471935/34528407-80f09fec-f06e-11e7-9b6e-76ee8cf2e603.png)

### Metasploit version

![image](https://user-images.githubusercontent.com/18471935/34528467-a5791ae2-f06e-11e7-8999-8e00c23d5ee4.png)

### I installed Metasploit with:
- [X ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Kali

**Comment by afarney** [comment]
Fixed, I was able to navigate to /usr/share/metasploit and run the ./msfconsole there and it returned the correct version.

**Comment by pbarry-r7** [comment]
Good deal.  :+1:
