### ISSUE TITLE
Failed to connect to the database: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by me009** [rapid7/metasploit-framework#9386]
Hi all,

I need some help here with this metasploit db issue on a kali box. 
When I start metasploit, here are the error messages that comes up..

 root@localhost:/home# msfconsole
[-] Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

and 	
	msf > db_status 
[*] postgresql selected, no connection

I realise this might be a common issue but all the steps to resolve it after almost 2 days of googling has not yielded results.. 
Other commands I have run and their output below

root@localhost:/# service postgresql status
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
   Active: active (exited) since Mon 2018-01-08 02:23:44 GMT; 10h ago
  Process: 6344 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 6344 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/postgresql.service

Jan 08 02:23:44 localhost.localdomain systemd[1]: Starting PostgreSQL RDBMS...
Jan 08 02:23:44 localhost.localdomain systemd[1]: Started PostgreSQL RDBMS.
Jan 08 13:22:53 localhost.localdomain systemd[1]: Started PostgreSQL RDBMS.
Jan 08 13:23:00 localhost.localdomain systemd[1]: Started PostgreSQL RDBMS.

This command gives a blank output
root@localhost:/# ss -lntp | grep post

Here, it seems the postgresql is not listening
root@localhost:/# ps -aux | grep post
root      6402  0.0  0.3   6224  3496 pts/0    S    12:39   0:00 su postgres
postgres  6403  0.0  0.3   5704  3576 pts/0    S    12:39   0:00 bash
root      6868  0.0  0.0   4756   864 pts/0    S+   13:24   0:00 grep post

## You might also want to check the last ~1k lines of `~/.msf4/logs/framework.log` for relevant stack traces
	TCP/IP connections on port 5432?

[01/08/2018 13:20:46] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

[01/08/2018 13:20:46] [e(0)] core: DB.connect threw an exception: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

### Metasploit version
Framework: 4.16.31-dev-
Console  : 4.16.31-dev

### OS

What OS are you running Metasploit on? Kali Linux

Can someone please help me resolve this and identify what I am not doing correctly ?

**Comment by busterb** [comment]
Try this: https://docs.kali.org/general-use/starting-metasploit-framework-in-kali

**Comment by me009** [comment]
Hi @busterb,

Thanks for the link but when I run **ss-ant**  I see port 5432 is not listening. How do I resolve this ?

root@localhost:/# ss -ant
State       Recv-Q Send-Q                      Local Address:Port                                     Peer Address:Port              
LISTEN      0      128                               0.0.0.0:57436                                         0.0.0.0:*                  
LISTEN      0      128                               0.0.0.0:111                                           0.0.0.0:*                  
LISTEN      0      128                                  [::]:111                                              [::]:*                  
LISTEN      0      128                                  [::]:55345                                            [::]:*

**Comment by siza3x** [comment]
same problem bro

**Comment by nilay121** [comment]
The error is :-
-------------------------------------------------------------------------------------------
msfconsole
[-] Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
--------------------------------------------------------------------------------------------
FULLY WORKING SOLUTION


Type the following commands


1.root@kali:~# cd /usr/share/metasploit-framework/config/

2.root@kali:/usr/share/metasploit-framework/config# ls
application.rb  database.yml          database.yml.vagrant
boot.rb         database.yml.example  environment.rb
cucumber.yml    database.yml.travis   environments

3.root@kali:/usr/share/metasploit-framework/config# cat database.yml
development:
  adapter: postgresql
  database: msf
  username: msf
  password: 2OjgyhT0tacdnxrYIKC8BgDel7tbY=
  host: localhost
  port: 5432
  pool: 5
  timeout: 5

production:
  adapter: postgresql
  database: msf
  username: msf
  password: 2O/UYGBP3jgyjgYuIT0tacdnxrYIKC8BgDel7tbY=
  host: localhost
  port: 5432
  pool: 5
  timeout: 5

test:
  adapter: postgresql
  database: msf_test
  username: msf
  password: 2O/UYGBP3nAhfhffhhyfh0tacdnxrYIKC8BgDel7tbY=
  host: localhost
  port: 5432
  pool: 5
  timeout: 5
------------------------------------------------------------------------------------

NOW CHANGE THE PORT NUMBER FROM 5432 TO 5433 ,THIS IS THE MAIN STEP SO DON'T MISS IT
------------------------------------------------------------------------------------
4.root@kali:/usr/share/metasploit-framework/config# nano database.yml

5.root@kali:/usr/share/metasploit-framework/config# cp database.yml /root/.msf4/

6.root@kali:/usr/share/metasploit-framework/config# cd ~/.msf4/

7.root@kali:~/.msf4# ls
  database.yml  history  local  logos  logs  loot  modules  plugins

8.root@kali:~# /etc/init.d/postgresql start

9.root@kali:~# msfconsole

-----------------------------------------
CONGO YOUR DONE
-----------------------------------------

**Comment by susanbhattrai** [comment]
Problem still remain doesnt work if i change the port to 5433
It is still throwning same error

**Comment by yehgdotnet** [comment]
Don't change the port. 

Copy database.yaml /root/.msf4
Restart the postgre

**Comment by jacksparrow01495** [comment]
solution from nilay worked for me thanks a lot

**Comment by thereavercode** [comment]
i need help on the same issue. the database connection problem
and if i may ask is it important to connect to the database

**Comment by jamesblond47** [comment]
BRO TRUST ME
just wait for few more minutes the metasploit automatically starts and you can start using msfconsole 
proof 
![screenshot 166](https://user-images.githubusercontent.com/46217192/51628481-1a9d7800-1f6b-11e9-9b96-1730b424e0b6.png)

**Comment by Rushabhgedam** [comment]
Thanks... Post helped a lot...

**Comment by clintryan413211** [comment]
Im trying to see if my wife is cheating on me but i dont understand this that well.  Ive installed phonesploit but unabe to connect her ip

**Comment by h00die** [comment]
Unless your target has consented, this would be a violation of law. Another violation of law is posting an unrelated question for guidance to a closed issue on GitHub.

**Comment by bcoles** [comment]
> 
> 
> Im trying to see if my wife is cheating on me but i dont understand this that well. Ive installed phonesploit but unabe to connect her ip

[https://www.reddit.com/r/relationships/](https://www.youtube.com/watch?v=4MPw4vlQt0Y)

**Comment by gkhan496** [comment]
service postgresql start

**Comment by divstech** [comment]
Thanks alot 
Problem solved

**Comment by nzanoa** [comment]
### Perfect Solution
1. **Start PostGreSQL**: # **systemctl** _restart_ postgresql
- Make sure it is **working properly**: # **systemctl** _status_ postgresql
- Now you should be **listening** on ports **5432** & **5433**: # **ss** -ant
2. **Reinitialize DB Settings** (user, config files, msfdb): # **msfdb** _reinit_
3. Finally, **launch MSF**: # **msfconsole**

**Comment by havilson** [comment]
I've done everything listed in here, nothing worked.

**Comment by JoeAJLaw** [comment]
I have tried everything here and followed numerous videos, but can't seem to resolve this. Any other suggestions? 

Below are some pics of results from after following steps: 

![image](https://user-images.githubusercontent.com/22789766/76142192-1a731580-6063-11ea-9a32-cb05cb348309.png)

![image](https://user-images.githubusercontent.com/22789766/76142176-05968200-6063-11ea-92c6-02fda1efede9.png)

**Comment by jhfmiguel** [comment]
The solution from nilay worked for me too, thanks a lot!

**Comment by Lorenz11x** [comment]
@nilay121 
I solved the problem exactly by following the guide, it's perfect !!
;)

**Comment by Rengend** [comment]
But I am using windows 10 to use metasploit (I also got same problem....) , what should I do

**Comment by RichCompton** [comment]
Stack trace in /root/.msf4/logs/framework.log says no password was supplied.. wtf is the password lol. I thought this was automatic

**Comment by sg552** [comment]
I met the same problem.

my Postgres is running at port 5432 but when running `bundle exec rake db:create` in the root folder of metasploit-framework, it gives error " localhost 5433 is not running Postgres", 

so this is the clue and I grep for 5433, found that there are 2 place has `5433` code: 

- msfdb 
- HOME_FOLDER/.msf/database.yml 

so I change these 2 files from `5433` to `5432`, problem solved!
