### ISSUE TITLE
keyscan dump error

### ISSUE THREAD

**Issue by ther4d4r** [rapid7/metasploit-framework#9403]
Hi I'm using Kali Linux 3.0, I'm trying to keylog my own pc with reverse_https but when i keyscan_dump i get this error: 
[-] stdapi_ui_get_keys_utf8: Operation failed: Incorrect function.
I have no idea of what could it be

**Comment by fsacer** [comment]
as that isn't reproducible, can probably be closed @busterb

**Comment by fsacer** [comment]
@wvu-r7 ?

**Comment by pavankalyannv** [comment]
How to store keyscan_dump to a particular file

**Comment by BlackLinux88** [comment]
**keyscan_start**
then
**keyscan_dump**
finally u can get every thing he type
and don't forget to type keyscan_dump after 1 min or as u want

lastly if u want to stop the keylogger
**keyscan_stop**
