### ISSUE TITLE
scanner/http/epmp1000_reset_pass: Port number hardcoded

### ISSUE THREAD

**Issue by ajaxtpm** [rapid7/metasploit-framework#9415]
https://github.com/rapid7/metasploit-framework/blob/e6de25d63b2eacc2876b3d0e8a19fc0400734550/lib/msf/core/auxiliary/epmp.rb#L163

Port number is included into cookie name and is hardcoded to 80, but should be taken from RPORT option. epmp1000 devices may be configured to run web server on any other port.

**Comment by bcoles** [comment]
No idea if this is really a bug. Created #14472 to address this. Untested.

**Comment by juushya** [comment]
hola, guys. IIRC this port # in cookie did not make a difference. Cookie was accepted regardless of target port number / ssl.

**Comment by bcoles** [comment]
> 
> 
> @bcoles IIRC this port # in cookie did not make a difference. Cookie was accepted regardless of target port number / ssl.

Thanks. I guessed that might be the case. On the other hand, using the correct cookie would probably make the traffic stand out less, so it's probably a good idea to implement (?) Couldn't hurt?

**Comment by juushya** [comment]
Yeah, it'd be a good idea to implement the change (80 to rport). It probably wouldn't break any epmp modules..
