### ISSUE TITLE
https://localhost:3790 Setup Error

### ISSUE THREAD

**Issue by MrAppAndCrap** [rapid7/metasploit-framework#9426]
OS Windows 7.
Issue:  https://kb.help.rapid7.com/discuss/5a5edad55d8acb003cbc94e8
Just error log: https://pastebin.com/Dc1pyjj5

**Comment by pbarry-r7** [comment]
Looks like issue was resolved.

For future support items, please join us on [Slack](http://r-7.co/metaSlack), [IRC](https://metasploit.help.rapid7.com/docs/joining-the-metasploit-irc-channel), or visit the [Rapid7 Knowledge Base](https://kb.help.rapid7.com/discuss).
