### ISSUE TITLE
auxiliary/scanner/vnc/ard_root_pw

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#9428]
## Steps to reproduce
use auxiliary/scanner/vnc/ard_root_pw
setg RHOSTS file:/root/5900.txt
set RPORT 5900
run

## Current behavior
Scanned half of the list then failed.
```
[-] Auxiliary failed: NoMethodError undefined method `set_key' for #<OpenSSL::PKey::DH:0x00007f34c4829a38>
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/rex/proto/rfb/cipher.rb:87:in `encrypt_ard'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rfb/client.rb:243:in `negotiate_ard_auth'
[-]   /usr/share/metasploit-framework/lib/rex/proto/rfb/client.rb:111:in `authenticate_with_type'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/vnc/ard_root_pw.rb:80:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```
### Metasploit version
v4.16.31-dev

### I installed Metasploit with:
Kali package via apt

### OS
Kali 2017.3 rolling

**Comment by bcoles** [comment]
Someone should probably look into this. Removed stale label.

**Comment by dwelch-r7** [comment]
I can't seem to replicate this issue with the latest version of framework @leebaird is this still a problem you run into? if so can you give more detailed replication steps please (both how you setup your msfconsole and your target if possible)

**Comment by bcoles** [comment]
Closing as dupe of #9418.
