### ISSUE TITLE
Getsystem and getprivs is not working 

### ISSUE THREAD

**Issue by Gowtham610** [rapid7/metasploit-framework#9450]
meterpreter >   getsystem
[-] priv_elevate_getsystem: Operation failed: Access is denied. The following was attempted:
[-] Named Pipe Impersonation (In Memory/Admin)
[-] Named Pipe Impersonation (Dropper/Admin)
[-] Token Duplication (In Memory/Admin)
meterpreter > run post/windows/gather/win_privs

[-] Post interrupted by the console user

**Comment by busterb** [comment]
getsystem only works if you are already running as a user who is an administrator. Is this the case?

**Comment by busterb** [comment]
I'm going to close this, but feel free to comment on anything new you have to add. Seems to be working fine here.

**Comment by Gowtham610** [comment]
bro i have tried various techniques but still get system is not working please give me a solution!
