### ISSUE TITLE
Ignoring msgpack

### ISSUE THREAD

**Issue by 5l1v3r1** [rapid7/metasploit-framework#9451]
Hello i am using Kali 2018.1, today after the last update i did, metasploit (metasploit v4.16.32-dev), starts to give a warning like this before starting up

"Ignoring msgpack-1.2.0 because its extensions are not built.  Try: gem pristine msgpack --version 1.2.0" 
I tried gem pristine msgpack --version 1.2.0 and turned me that result:

Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored msgpack-1.2.0

But metasploit still gives me the same warning before starting. What can be done about that?
Thank you and regards

**Comment by archuser555** [comment]
ok lol funny

**Comment by 5l1v3r1** [comment]
> 



> ok lol funny
https://www.youtube.com/watch?v=X6WHBO_Qc-Q kinda neural network
