### ISSUE TITLE
msfdb init fails on Windows

### ISSUE THREAD

**Issue by codewatchorg** [rapid7/metasploit-framework#9453]
## Steps to reproduce

1. I ran the 'msfdb init' command on Windows 10 (Build 16299.125) as well as Windows 7 (Build 7601: SP1) with the latest version of the framework.  This results in the following dialog:

Creating database at C:/Users/username/.msf4/db
Starting database at C:/Users/username/.msf4/db...failed
LOG:  database system is shut down
If your database is corrupt, would you to reinitialize it?:

2. I manually went through the steps in the script and found the following in the Postgres logs:

LOG:  local connections are not supported by this build
CONTEXT:  line 4 of configuration file "C:/Users/username/.msf4/db/pg_hba.conf"
FATAL:  could not load pg_hba.conf
LOG:  database system is shut down

3. The script creates a pg_hba.conf file with a configuration that includes:
local   all             all                                       trust

4. "local" is for Unix-domain sockets and therefore does not work on Windows.  Removing this line and then manually running the commands within the script resulted in successful creation of the database.

## Expected behavior

Metasploit database is initialized correctly.

## Current behavior

Database initialization fails as the configuration is incorrect on Windows and therefore PostgreSQL doesn't start.

## System stuff

OS: Windows 10 and Windows 7
Metasploit Versions:
  1. Win 10: v4.16.32-dev-eb8429cbd350bd1ed476ca64787ed4b3c82f1718
  2. Win 7: v4.16.33-dev-17bf0dcdfb2f0b2a4c4f8b511b9e0d04cfd05efc

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:

The Windows installer at: https://windows.metasploit.com/metasploitframework-latest.msi

### OS

Windows 7 and Windows 10

**Comment by busterb** [comment]
Hmm, I thought we fixed this not long ago...

**Comment by codewatchorg** [comment]
Maybe the issue was reintroduced sometime recently?  I setup a new system two weeks ago, ran into the issue, and tracked down the fix and just now had time to submit the issue here.

I downloaded the latest framework installer today and installed on a Win7 machine just so I could document the exact error messages and other information to report it correctly.

**Comment by busterb** [comment]
This was the recent update to address a similar issue: https://github.com/rapid7/metasploit-omnibus/pull/60

Perhaps we didn't quite fix it correctly.

**Comment by busterb** [comment]
Ah, figured it out. We switched to 4.x branch on the package builder as well, and I forgot to merge the fix there. Now it's all merged up, should be good in the next build (if it isn't, we'll reopen).

https://github.com/rapid7/metasploit-omnibus/tree/4.x

**Comment by codewatchorg** [comment]
Awesome, thanks!
