### ISSUE TITLE
How Can I Install Metasploit In CentOS 6.9 32 Bit

### ISSUE THREAD

**Issue by hashnimmo** [rapid7/metasploit-framework#9460]
Hello, these are the commands that I ran on my VPS so far, it didn't complete the installation. Any help?

> [root@vps ~]# yum update
[root@vps ~]# yum upgrade
[root@vps ~]# curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall &&   chmod 755 msfinstall &&   ./msfinstall
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
101  5394  101  5394    0     0  34953      0 --:--:-- --:--:-- --:--:-- 2633k
Checking for and installing update..
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
  base: centos.usonyx.net
  extras: centos.usonyx.net
  updates: centos.usonyx.net
No package metasploit-framework available.
Error: Nothing to do

**Comment by pbarry-r7** [comment]
Hmm... can you verify if the file `/etc/yum.repos.d/metasploit-framework.repo` exists?  And if it does, can you share the contents of it here?

Also, you could try rerunning the msfinstall as `sh -x ./msfinstall` and share the output of that here, it'll give us a better idea of what's going on.  Thx.

**Comment by pbarry-r7** [comment]
That said, it appears 32-bit package support via RPM might be the issue here.  See the fist paragraph of this page:

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
