### ISSUE TITLE
How to evade gmail virus scan

### ISSUE THREAD

**Issue by simplerat** [rapid7/metasploit-framework#9461]
How can i create a payload that i can send as an attachment using gmail.

**Comment by pbarry-r7** [comment]
GitHub isn't a support forum for us.  Please join us on [Slack](http://r-7.co/metaSlack), [IRC](https://metasploit.help.rapid7.com/docs/joining-the-metasploit-irc-channel), or visit the [Rapid7 Knowledge Base](https://kb.help.rapid7.com/discuss) for questions like this.  Thx.
