### ISSUE TITLE
Insight on Win Meterpreter Named Pipe Pivot

### ISSUE THREAD

**Issue by realoriginal** [rapid7/metasploit-framework#9472]
Curious, hilarously I've only just noticed this command (bummer!), but how would one utilize the `pivot` command in Win meterpreter to pivot over named pipes? I'm aware of the technique, unfortunately I'm unable to find info on it :), was wondering if the devs could provide an example, if not ,all cool :D.

**Comment by OJ** [comment]
Hi @realoriginal please see the documentation in the [original Pull Request](https://github.com/rapid7/metasploit-payloads/pull/226). Thanks.
