### ISSUE TITLE
How Can I resolve this ISSUE.........

### ISSUE THREAD

**Issue by MeanMachine123** [rapid7/metasploit-framework#9477]
/usr/local/lib/ruby/2.4.0/psych/versions.rb:4: warning: already initialized constant Psych::VERSION
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/versions.rb:4: warning: previous definition of VERSION was here
/usr/local/lib/ruby/2.4.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::ANY
/usr/local/lib/ruby/2.4.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF8
/usr/local/lib/ruby/2.4.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
/usr/local/lib/ruby/2.4.0/x86_64-linux/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
/usr/local/lib/ruby/2.4.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/class_loader.rb:65: warning: previous definition of CACHE was here
/usr/local/lib/ruby/2.4.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
/usr/local/lib/ruby/2.4.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
/usr/local/lib/ruby/2.4.0/psych/scalar_scanner.rb:18: warning: already initialized constant Psych::ScalarScanner::INTEGER
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/scalar_scanner.rb:17: warning: previous definition of INTEGER was here
/usr/local/lib/ruby/2.4.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.4.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
/usr/local/lib/ruby/2.4.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
/usr/local/lib/ruby/2.4.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
/usr/local/lib/ruby/2.4.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.4.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
/usr/local/lib/ruby/2.4.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
/usr/local/lib/ruby/2.4.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
/usr/local/lib/ruby/2.4.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
/usr/local/lib/ruby/2.4.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
/usr/local/lib/ruby/2.4.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
/usr/local/lib/ruby/2.4.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
/usr/local/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/visitors/to_ruby.rb:334: warning: previous definition of SHOVEL was here
/usr/local/lib/ruby/2.4.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
/usr/local/lib/ruby/2.4.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.2/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
/usr/local/lib/ruby/2.4.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
	from /usr/local/lib/ruby/2.4.0/psych/parser.rb:33:in `<module:Psych>'
	from /usr/local/lib/ruby/2.4.0/psych/parser.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib/ruby/2.4.0/psych.rb:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faker-1.8.7/lib/faker.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/cert_provider.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/framework.rb:64:in `<class:Framework>'
	from /usr/share/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
	from /usr/share/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/backports-3.11.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/share/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	from /usr/bin/msfconsole:47:in `require'
	from /usr/bin/msfconsole:47:in `<main>'

**Comment by wvu-r7** [comment]
How did you install Metasploit?

**Comment by busterb** [comment]
This looks like Kali linux.

I'd start by removing the copy of ruby you installed under /usr/local entirely and use the bundle version that Kali has, since it has been tweaked specifically for that distribution. This isn't a bug in Metasploit though, so closing this issue.
