### ISSUE TITLE
Meterpreter unable to load any extensions other than stdapi.

### ISSUE THREAD

**Issue by DemonKnight94** [rapid7/metasploit-framework#9520]
Meterpreter unable to load any exception except stdapi
I get this error when I try to load python in a meterpreter session.

meterpreter > load python
Loading extension python...
[-] Failed to load extension: No module of the name ext_server_python.php found

### I installed Metasploit with:
- [ ] Kali package via apt
-
### OS:Kali linux 2016.2(VM)amd64

What OS are you running Metasploit on?
Kali linux 2016.2(VM)amd64

**Comment by OJ** [comment]
The python extension is only supported on native Windows Meterpreter. It
doesn't work in PHP Meterpreter.

I don't think PHP Meterpreter supports any extensions at this point.

**Comment by OJ** [comment]
This currently works perfectly on Windows native Meterpreter as expected. Closing this issue.
