### ISSUE TITLE
Add output file support to vulns

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#9522]
Unlike `hosts`, `notes`, `services` and other console commands that dump database output, `vulns` does not have an option to send the output to a file, which would be very useful.  

Filing here in the event that someone else gets to this before me, or if there is a fundamental reason why this isn't or shouldn't be here, but I'll likely PR an enhancement soon.

**Comment by wchen-r7** [comment]
I'll grab it.
