### ISSUE TITLE
only 4kb/s to download files on meterpreter session android

### ISSUE THREAD

**Issue by daniel1048** [rapid7/metasploit-framework#9541]
First of all , sorry for my english
i don't know why but to download files in  android/meterpreter/reverse_tcp session android i just get 4kb/s of speed.
[*] Downloaded 4.00 KiB of 268.57 KiB (1.49%): IMG-20180127-WA0007.jpg -> IMG-20180127-WA0007.jpg
[*] Downloaded 8.00 KiB of 268.57 KiB (2.98%): IMG-20180127-WA0007.jpg -> IMG-20180127-WA0007.jpg
[*] Downloaded 12.00 KiB of 268.57 KiB (4.47%): IMG-20180127-WA0007.jpg -> IMG-20180127-WA0007.jpg
[*] Downloaded 16.00 KiB of 268.57 KiB (5.96%): IMG-20180127-WA0007.jpg -> IMG-20180127-WA0007.jpg
 i only got this issue attacking to android device, in  windows it works fine
i'm attacking from ubuntu 16.04,kali linux and nethunter and is the same.

**Comment by harshil2105** [comment]
I'm facing the same issue with the speed and after some time the downloading fails, you can't download a large file or a folder full of pictures.

**Comment by WARLAUK** [comment]
Same issue, does anyone have a solution?

**Comment by abdu791** [comment]
Same here.. did anyone fine solution? Please help
