### ISSUE TITLE
metasploit is not connceting to its database

### ISSUE THREAD

**Issue by Gowtham610** [rapid7/metasploit-framework#9545]
root@kali:~# service postgresql start
root@kali:~# msfconsole
[-] Failed to connect to the database: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 7337?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 7337?

**Comment by bcook-r7** [comment]
For information on using Metasploit database on Kali, please see Kali Linux support forums.
