### ISSUE TITLE
Installation issues with rvm

### ISSUE THREAD

**Issue by Smith0197** [rapid7/metasploit-framework#9566]
## Steps to reproduce

1. Installing metasploit using the following bash code:
```
sudo apt-get -y install autoconf bison build-essential curl git-core libapr1 libaprutil1 libcurl4-openssl-dev libgmp3-dev libpcap-dev libpq-dev libreadline6-dev libsqlite3-dev libssl-dev libsvn1 libtool libxml2 libxml2-dev libxslt-dev libyaml-dev locate ncurses-dev openssl postgresql postgresql-contrib wget xsel zlib1g zlib1g-dev
curl -sSL https://rvm.io/mpapis.asc | gpg --import -
curl -L https://get.rvm.io | bash -s stable

if [ "$(id -u)" == 0 ]; then
       	source /usr/local/rvm/scripts/rvm
else
	source ~/.rvm/scripts/rvm
fi
cd /opt/tools/metasploit-framework
rvm --install $(cat .ruby-version)
gem install bundler 
bundle install
yard config --gem-install-yri
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc
echo '[+] Metasploit configured!
```
2. It is run once as a normal user and once as root.
3. `gem install bundler` (in metasploit-framework directory)
4. `bundle install` (in metasploit-framework directory)

## Expected behavior
Metasploit should be able to run as normal user, sudo and as root.

## Current behavior
Firstly, when cd-ing into the metasploit-framework directory - the ruby configuration is not remembered and it only remembers the config when `rvm use $(cat.ruby-version) --default` is used.
 
Secondly, ./msfconsole works when running as a normal user, but when running as sudo or root the following is outputted: `/usr/bin/env: ‘ruby’: No such file or directory`

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (ruby 2.4.3 with rvm)

### OS
Debian 9.3 Stretch

**Comment by busterb** [comment]
If you want rvm to work for all users, you have to install it for all users. That means run rvm as root when installing.

**Comment by busterb** [comment]
Also, there is very little reason to actually run Metasploit as root on Linux in the first place. If you want to be able to capture raw packets / bind lower port numbers, set capabilities instead:

/usr/sbin/setcap cap_net_raw,cap_net_bind_service=+eip $(which ruby)

See the Dockerfile for other similar tips.
