### ISSUE TITLE
SSL warning with Ruby 2.5.0

### ISSUE THREAD

**Issue by vendforce** [rapid7/metasploit-framework#9576]
OS : Arch
DE : Kde plasma
METASPLOIT : v5.0.0-dev-eaca91cad7
RUBY : ruby 2.5.0p0

Not installed from aur , git cloned into /opt directory 

/opt/metasploit/lib/msf/core/opt.rb:55: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated

anyone know how to hide this warning until its fixed upstream i.e patch

**Comment by vendforce** [comment]
I found a solution replacing 
`OpenSSL::SSL::SSLContext::METHODS `
with
`[:TLSv1_2, :TLSv1_1, :TLSv1, :SSLv3, :SSLv23, :SSLv2]`

removes the warning

**Comment by busterb** [comment]
Feel free to submit a PR!

**Comment by h00die** [comment]
Whats it been deprecated for? I don't see a deprecation warning in the [docs](http://ruby-doc.org/stdlib-2.4.2/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html)

**Comment by FireFart** [comment]
@h00die it's about ruby 2.5.0 https://ruby-doc.org/stdlib-2.5.0/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html

**Comment by sempervictus** [comment]
Should we implement runtime version detection? Arch is a popular distro nowadays, and it runs tip everything (with the resulting headache and benefits). If we are to ever support alternate VMs, we might as well support versioning. Thoughts?
