### ISSUE TITLE
Metasploit compatibility with ruby 2.5

### ISSUE THREAD

**Issue by anthraxx** [rapid7/metasploit-framework#9577]
## Steps to reproduce

Right now metasploit doesn't work with ruby 2.5 specifically because of used grpc version.

## Expected behavior

Metasploit should be usable with ruby 2.5. It looks likr grpc 1.9.1 is build and published on rubygems for ruby 2.5. It would be nice to get a travisci rvm bump and grpc Gemfile.lock bump.

## Current behavior

```
Gem::RuntimeRequirementNotMetError: grpc requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.
An error occurred while installing grpc (1.8.3), and Bundler cannot continue.
```

### Metasploit version

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

### I installed Metasploit with:
- [x] Source install (ruby 2.5)

### OS

Arch Linux

**Comment by sempervictus** [comment]
If you update the relevant gem in your gemfile, does it pass spec testing? This is likely a deeper rabbit hole than one gem. Ping @busterb

**Comment by vendforce** [comment]
Temporary work around put it in your bashrc file
```

#### MSFCONSOLE DEPRECIATION WARNING
MSFDIR=$(find / -type f -iname opt.rb -exec grep -q "msf\|Msf" {} \; -exec echo {} \;)
if grep -q -o "OpenSSL::SSL::SSLContext::METHODS" \
$MSFDIR ; then \
sed -i 's/OpenSSL::SSL::SSLContext::METHODS/[:TLSv1_2, :TLSv1_1, :TLSv1, :SSLv3, :SSLv23, :SSLv2]/' \
$MSFDIR; fi

MSFGEMFILE=$(find / -type f -iname Gemfile.lock -exec grep -q 'grpc ([0-9].[0-9].[0-9])' {} \; -exec echo {} \;)

if grep -q -o "grpc (1.8.3)" \
$MSFGEMFILE ; then \
sed -i 's/grpc (1.8.3)/grpc (1.9.1)/' \
$MSFGEMFILE ; fi
```

**Comment by sempervictus** [comment]
I'd be careful with _find /_  with TBs of data on systems, which can be compressed and deduplicated may not be taken kindly. Might wanna go with /opt/m* or something slightly more narrow.
The ruby thing on Arch is pathological, I use it all over... RVM and friends were made for this sort of thing, and its why Pro carries its own bins.

**Comment by vendforce** [comment]
yes I agree, I was just giving that example in case someone clone it into some other folder than /opt

but yes the better approach would be delare MSFOPTFILE & MSFGEMFILE to the exact file locations for that user

**Comment by vendforce** [comment]
> I'd be careful with find / with TBs of data on systems, which can be compressed and deduplicated may not be taken kindly

I've added an exclude gems to the find command to make sure it will be taken kindly

**Comment by anthraxx** [comment]
btw grpc 1.10.0 still works perfectly fine, not just for me but lots of users. i don't see anything holding up a bump.

**Comment by anthraxx** [comment]
works good especially via #9762
