### ISSUE TITLE
Running msfupdate on Windows moves Metasploit onto your OS drive

### ISSUE THREAD

**Issue by Reelix** [rapid7/metasploit-framework#9578]
## Steps to reproduce

How'd you do it?
1.) Acquire a secondary Hard Drive
2.) Install metasploit in a subdirectory on that drive - Eg: R:\Utilities\metasploit-framework\
3.) Wait for an update
4.) Run msfupdate.bat

## Expected behavior

Metasploit updates, and remains in the location it was installed

## Current behavior

Metasploit gets moved to C:\metasploit-framework\

### I installed Metasploit with:

https://windows.metasploit.com/metasploitframework-latest.msi

### OS

Windows 10 Pro x64

**Comment by ibonobo** [comment]
same here

**Comment by jpdoherty** [comment]
I experienced the exact opposite problem. I had it installed to my OS drive, updated, and it moved to a secondary drive. Now, every attempt at install puts it on that same secondary drive, even when C:\ is selected in the installer.

**Comment by franferrax** [comment]
Hi, I think this should be reported in the `metasploit-omnibus` repository. I think this issue shares the root cause with #14071, likely to be reported in rapid7/metasploit-omnibus#115.

**Comment by ibonobo** [comment]
I simply uninstalled metasploit from Windows and use it via WSL
