### ISSUE TITLE
metasploit pro install error on headless server

### ISSUE THREAD

**Issue by vladimirpe00** [rapid7/metasploit-framework#9582]
Hi I download the metasploit file from rapid7 official website, and I'm trying to install it on ubuntu server I followed the official guide to install it oh headless server this what I did:

1. I ran metasploil .run file 
2. on 100% I'm getting postgresql error

Warning: Problem running post-install step. Installation may not complete
correctly
 Error running su postgres -c '"/opt/metasploit/postgresql/bin/pg_ctl" start -w
-l /opt/metasploit/postgresql/postgresql.log': pg_ctl.bin: could not start
server

the postgresql.log is:

LOG:  could not translate host name "localhost", service "7337" to address: Nam$
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  database system is shut down

and I check my host file seems everything is good here is my host file

127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

again I tried to check my resolve.conf file and all DNS are correct

nameserver 8.8.8.8
nameserver 4.2.2.2

I'm using Ubuntu 16.04.3 LTS as a VPS, and I'm installing the msf pro from ssh as I mentioned it's a headless server so can anyone help me ? thanks

**Comment by sempervictus** [comment]
127.0.0.1 needs a hosts definition. Iirc pro uses ipv4

**Comment by busterb** [comment]
Do you not have localhost setup as 127.0.0.1 at all?

**Comment by busterb** [comment]
Add
`127.0.0.1   localhost`
to the beginning of /etc/hosts

**Comment by vladimirpe00** [comment]
thanks for your reply if you read what I posted you will notice that I aleady have 127.0.0.1 locahost in /etc/hosts thanks anyway
