### ISSUE TITLE
msfconsole is not working

### ISSUE THREAD

**Issue by Gowtham610** [rapid7/metasploit-framework#9616]
root@kali:~# msfconsole
Rails Error: Unable to access log file. Please ensure that /root/.msf4/logs/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /root/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/rex/logging/sinks/flatfile.rb:21:in `initialize': Read-only file system @ rb_sysopen - /root/.msf4/logs/framework.log (Errno::EROFS)
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/rex/logging/sinks/flatfile.rb:21:in `new'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/rex/logging/sinks/flatfile.rb:21:in `initialize'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/base/logging.rb:24:in `new'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/base/logging.rb:24:in `init'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/base/simple/framework.rb:111:in `simplify'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/base/simple/framework.rb:73:in `create'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/ui/console/driver.rb:65:in `initialize'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/metasploit/framework/command/console.rb:62:in `new'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/msfconsole:48:in `<top (required)>'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `load'
	from /opt/metasploit1/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `<main>'
root@kali:~# 

![screenshot 25](https://user-images.githubusercontent.com/35193320/36603402-a5dca05e-18e0-11e8-8ecb-e0f293261e92.png)

msfconsole is not working any idea ! try to solve this issue but couldn t find a solution yet can u?

**Comment by busterb** [comment]
Please raise an issue with Kali linux: https://docs.kali.org/community/submitting-issues-kali-bug-tracker

It looks like you may just need to reinstall a much newer version of Kali, I'm sure the 'sana' release has long since gone out of support.
