### ISSUE TITLE
stuck after - Started HTTPS reverse handler , please help me

### ISSUE THREAD

**Issue by SAJJADALIDON** [rapid7/metasploit-framework#9626]
please help me to solve this problem .

![capture3](https://user-images.githubusercontent.com/28814947/36641825-0f8ce83c-19eb-11e8-8ff4-c7c117215717.PNG)

**Comment by h00die** [comment]
I don't get the problem. You asked handler to run as a job, it started it in the background then gave you back a prompt. What is stuck? Did you try hitting enter gain again to show the prompt another time maybe?

**Comment by busterb** [comment]
This is expected, stop whatever process you have that is already listening on port 8080.

**Comment by AliAkhtari78** [comment]
have the same problem.
