### ISSUE TITLE
Implement `Rex::Tar` for working with Tar archives

### ISSUE THREAD

**Issue by bcoles** [rapid7/metasploit-framework#9651]
Implement `Rex::Tar` for creating Tar archives.

The Rex library features `Rex::Zip::Archive.new`, `Rex::Zip::Jar.new` and `Rex::Text.gzip(str)` for working with compressed files, however no functionality exists to work with Tar files.

The current approach taken by [telpho10_credential_dump.rb](https://github.com/rapid7/metasploit-framework/tree/master/modules/auxiliary/admin/http/telpho10_credential_dump.rb) and PR #8539 is to use `Gem::Package::TarReader` which requires `require 'rubygems/package'` within the module.

**Comment by sempervictus** [comment]
Thanks :-).
