### ISSUE TITLE
 auxiliary/scanner/upnp/ssdp_msearch Returns no results

### ISSUE THREAD

**Issue by Zibri** [rapid7/metasploit-framework#9667]
From ubuntu 17.10 if I run the module I get always no results (no hosts found) when there are 3.

My configuration is this:

usb tether to android phone  ip:192.168.42.x
hotspot active (10.42.0.x)

```
msf > use auxiliary/scanner/upnp/ssdp_msearch 
msf auxiliary(scanner/upnp/ssdp_msearch) > set RHOSTS 192.168.42.11/24
RHOSTS => 192.168.42.11/24
msf auxiliary(scanner/upnp/ssdp_msearch) > run

[*] Sending UPnP SSDP probes to 192.168.42.0->192.168.42.255 (256 hosts)
[*] No SSDP endpoints found.
[*] Scanned 256 of 256 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by timwr** [comment]
I'm not sure, but I don't think USB tethering means the Ubuntu computer and Android phone can see each other in the same way they can if you do Wifi tethering. Given you have two different IP addresses I think that is the case.

**Comment by timwr** [comment]
@Zibri do you get the same result if you do a Wifi hotspot?

**Comment by Zibri** [comment]
timwr: Yes.

**Comment by Zibri** [comment]
my linux box is a wifi hotspot and it's connected to a phone (usb tethering) for internet.
multiple upnp devices connect to it in wifi.
if I use nodejs ssd module or if I do:
gssdp-discover -i wlp4s0

I see them.

**Comment by Zibri** [comment]
still not solved.

**Comment by adfoster-r7** [comment]
Closing as I believe this is a specific networking issue with Android rather than the module itself; If anyone else runs into this in a different scenario let us know and we can take another look
