### ISSUE TITLE
Single Session commands

### ISSUE THREAD

**Issue by basicqweasd** [rapid7/metasploit-framework#9679]
I would like to change the following script to affect only selected meterpreter sessions:

require "io/console"

framework.sessions.each_pair do |sid, s|
    if s.ext.aliases['stdapi]'
    s.console.run_single("priv")
    s.console.run_single("getsystem")
   end
end

**Comment by timwr** [comment]
What do you mean by selected sessions? You can just put another if statement within the each_pair loop

**Comment by wvu-r7** [comment]
Programming question answered.
