### ISSUE TITLE
Me Marca esto al iniciar railgun ??????????? :c

### ISSUE THREAD

**Issue by Gasso19** [rapid7/metasploit-framework#9689]
ACTUALIZE TODO Y AUN SIGUE APARECIENDO ESTO.

>> session.railgun.known_dll_names
RuntimeError: Library known_dll_names not found. Known libraries: ["kernel32",
 "ntdll",
 "user32",
 "ws2_32",
 "iphlpapi",
 "advapi32",
 "shell32",
 "netapi32",
 "crypt32",
 "wlanapi",
 "wldap32",
 "version",
 "psapi"]

	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/railgun.rb:297:in `method_missing'
	from (irb):1:in `cmd_irb'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
	from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:541:in `cmd_irb'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
	from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:567:in `_interact'
	from /usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
	from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1380:in `cmd_sessions'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
	from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:48:in `<main>'

**Comment by wvu-r7** [comment]
@asoto-r7 ;)

**Comment by zeroSteiner** [comment]
IIRC I changed `known_dll_names` to something less Windows specific last year as part of the multi-platform railgun changes I made. Not sure if that's relevant but I thought I'd mention it in case the information is helpful.
