### ISSUE TITLE
NoMethodError undefined method `run_single'

### ISSUE THREAD

**Issue by AddaxSoft** [rapid7/metasploit-framework#9691]
I'm trying to create a script that kills all jobs when a sessions is initiated
my script.rb is:
self.run_single("jobs -K")

but when it gets executed inside msf I get: NoMethodError undefined method `run_single'

I'm running metasploit v4.16.10-dev on Unbuntu 14.04

**Comment by wvu-r7** [comment]
Probably because that method doesn't exist on whatever `self` is. You want an `msfconsole` resource script, not a Ruby "session script." Two different things.

**Comment by wvu-r7** [comment]
https://metasploit.help.rapid7.com/docs/resource-scripts

Good luck!

**Comment by AddaxSoft** [comment]
I want to be able to call both scripts upon a session establishment. I can't find any way to do that
