### ISSUE TITLE
PentestBox-warning: already initialized constant Psych::VERSION

### ISSUE THREAD

**Issue by z977780633** [rapid7/metasploit-framework#9695]
PentestBox

D:\PentestBox\bin\metasploit-framework
> ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]

D:\PentestBox\bin\metasploit-framework
> msfconsole

D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/versions.rb:4: warning: already initialized constant Psych::VERSION
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/versions.rb:4: warning: previous definition of VERSION was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/x64-mingw32/psych.so: warning: already initialized constant Psych::Parser::ANY
D:/PentestBox/base/ruby/lib/ruby/2.4.0/x64-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF8
D:/PentestBox/base/ruby/lib/ruby/2.4.0/x64-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
D:/PentestBox/base/ruby/lib/ruby/2.4.0/x64-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:9: warning: previous definition of DATE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:15: warning: previous definition of RANGE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/class_loader.rb:65: warning: previous definition of CACHE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/scalar_scanner.rb:18: warning: already initialized constant Psych::ScalarScanner::INTEGER
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/scalar_scanner.rb:18: warning: previous definition of INTEGER was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/visitors/to_ruby.rb:334: warning: previous definition of SHOVEL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/handler.rb:27: warning: previous definition of OPTIONS was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/handler.rb:30: warning: previous definition of EVENTS was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/visitors/yaml_tree.rb:440: warning: already initialized constant Psych::Visitors::YAMLTree::NULL
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/visitors/yaml_tree.rb:440: warning: previous definition of NULL was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/visitors/yaml_tree.rb:441: warning: already initialized constant Psych::Visitors::YAMLTree::BINARY_RANGE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/visitors/yaml_tree.rb:441: warning: previous definition of BINARY_RANGE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/visitors/yaml_tree.rb:442: warning: already initialized constant Psych::Visitors::YAMLTree::WS_RANGE
D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych/visitors/yaml_tree.rb:442: warning: previous definition of WS_RANGE was here
D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
        from D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/parser.rb:33:in `<module:Psych>'
        from D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych/parser.rb:2:in `<top (required)>'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/2.4.0/psych.rb:15:in `<top (required)>'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/faker-1.8.7/lib/faker.rb:5:in `<top (required)>'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/cert_provider.rb:2:in `<top (required)>'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/framework.rb:64:in `<class:Framework>'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require'
        from D:/PentestBox/base/ruby/lib/ruby/gems/2.4.0/gems/backports-3.11.1/lib/backports/std_lib.rb:9:in `require_with_backports'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        from D:/PentestBox/bin/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        from D:/PentestBox/bin/metasploit-framework/msfconsole:47:in `require'
        from D:/PentestBox/bin/metasploit-framework/msfconsole:47:in `<main>'

### OS

What OS are you running Metasploit on?
Windows 10 PentestBox

**Comment by busterb** [comment]
You might file an issue with Windows 10 PentestBox. We do not maintain this package.
