### ISSUE TITLE
Failed to run scripts after downloading whole project in zip file

### ISSUE THREAD

**Issue by exayyan** [rapid7/metasploit-framework#9711]
## Steps to reproduce

How'd you do it?

1. i downloaded zip whole zip file and just run it.
2. after ./msfvenom i use "bundle install" later on i saw last line "make sure that 'gem install json -v 1.8.0' succeds before bundling

after entering gem install json -v 1.8.0 i got following error:

```
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/json-1.8.0/ext/json/ext/generator
/usr/bin/ruby2.3 -r ./siteconf20180314-3304-mkqprr.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.3.0/gems/json-1.8.0/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /var/lib/gems/2.3.0/gems/json-1.8.0/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^~~~~~~~~~
Makefile:239: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.3.0/gems/json-1.8.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/json-1.8.0/gem_make.out
```

i just wanna add whatsapp dump db and shutdown devices etc features in my metasploit, please help me out.

**Comment by busterb** [comment]
Please use a package from Kali Linux, or the nightly installers https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

If you are contemplating pulling that old whatsapp android meterpreter post module (people try to PR it every few months), it hasn't worked for a few years. Whatsapp is substantially different since it was written. Thanks.

**Comment by busterb** [comment]
If you are doing new development, please refer to the wiki for setting up a development environment: https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
