### ISSUE TITLE
Is there a way to write msf compatible payload?

### ISSUE THREAD

**Issue by kdlsw** [rapid7/metasploit-framework#9715]
I am trying to write my own stager reverse tcp payload that is compatible to other scripts in msf, I assume the msfvenom generated ones open a socket and listen for the stager then decrypt and run, but I am not sure how exactly does it work. I took a look on the msf payload file, the modules it’s calling are complicated and many, I am not too good with ruby.
Any suggestion where or what should I be looking as to start? Or, is there any meterpreter starger reverse tcp payload scripts that are before compiled into exe out there?
Thanks!

**Comment by busterb** [comment]
Rather than writing a new meterpreter, which is a big job, start with a new shell session type. It only needs the ability to read and write to /bin/sh or similar.
