### ISSUE TITLE
Problem using msf console in terminux. 

### ISSUE THREAD

**Issue by Exotic-Algorithms** [rapid7/metasploit-framework#9721]
i have installed all the files but when i type "ls" msfconsole isnt listed under the cd for metasploit-framework. When you type "./msfconsole" it says no such file or directory. Please help. 

Android is a galaxy s8 non rooted.

**Comment by busterb** [comment]
This isn't a support channel for Termux.

**Comment by bcoles** [comment]
Termux is not supported. #11023
