### ISSUE TITLE
how  p2p files in Meterpreter

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#9729]
how  p2p download files or folders in Meterpreter?

**Comment by timwr** [comment]
`meterpreter> download` ?

**Comment by hktalent** [comment]
My pc: A [Lan]
my remote server：B[Wan]
target server：C [Lan]

accese : A > B > C 

how get file p2p（UDP  Peer to Peer） ,so 
get File A > C
now Lan to Lan
@timwr  
thanks

**Comment by timwr** [comment]
Hi @hktalent 
I assume meterpreter is running on target server C.
It depends whether you are running metasploit (msfconsole) on B or A.
If you run metasploit on A, you can pivot the session through B and use `meterpreter > download` as normal.
If you run metasploit on B, you will need to do `meterpreter > download`, to download from C -> B, then manually download the file from B -> A.

p.s github issues are not meant for issues not support. You can find help sooner on IRC or slack.
