### ISSUE TITLE
factory_girl deprecation warning

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#9736]
## Steps to reproduce

1. `rake spec`
2. Note the first bit of output:

```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/todb/git/metasploit-framework/config/application.rb:10)
/home/todb/.rvm/rubies/ruby-2.4.3/bin/ruby -I/home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-core-3.7.1/lib:/home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-support-3.7.1/lib /home/todb/.rvm/gems/ruby-2.4.3@metasploit-framework/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /home/todb/git/metasploit-framework/config/application.rb:10)
Run options: include {:focus=>true}

```
This is on a fresh clone of metasploit-framework.

## Expected behavior

We shouldn't be using gems with deprecation warnings.

## Current behavior

We are currently depending on deprecated gems.

### Metasploit version

26bf96b3ce1e97bfb997432ba532e9823f885750 Land #9723, Require dependencies conditionally in msfvenom

```
todb@mazikeen:~/git/metasploit-framework$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
todb@mazikeen:~/git/metasploit-framework$ gem -v
2.6.14
```

### I installed Metasploit with:

- [ x ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Ubuntu 16.04.4 LTS (lsb_release -a output below)

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by todb-r7** [comment]
On the bright side,

```
Finished in 2 minutes 56.3 seconds (files took 8.17 seconds to load)
10357 examples, 0 failures, 33 pending
```

Not too shabby, all!

**Comment by FireFart** [comment]
Transition to factory_bot is really straight forward:
https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md

**Comment by sempervictus** [comment]
@todb-r7: We need Jaws music for when you come up from lurking to remind us that there's maintenance debt :-p.
@FireFart: I'm pretty sure we said the same thing about democracy when we got into Iraq. ;)
Seriously though, quick grep through lib and modules for factory_girl or FactoryGirl doesnt show anything (at least on my branch). Is this a Pro/CE-specific thing, or used in a supporting gem like MDM/concern?

**Comment by busterb** [comment]
It's only used for testing, so updating any particular project is completely independent of all others.

**Comment by busterb** [comment]
I spent a couple of minutes on this, but thought it would be easy for a newbie to jump aboard and fix it. 

It doesn't really strike me as an urgent update technically, since AFAIK reason the original gem is deprecated is because the developers felt uncomfortable about the name.
