### ISSUE TITLE
payload handler dont start !!HELP!!!

### ISSUE THREAD

**Issue by kakakuko** [rapid7/metasploit-framework#9751]
## Steps to reproduce

How'd you do it?
1. ...LHOST=> 192.168.xxx.xxx
2. ...LPORT => 4444
3. ...PAYLOAD => android/meterpreter/reverse_tcp
4. ... Started reverse TCP handler on 192.168.xxx.xxx:4444

## Expected behavior

LHOST=> 192.168.xxx.xxx
LPORT => 4444
PAYLOAD => android/meterpreter/reverse_tcp
Started reverse TCP handler on 192.168.xxx.xxx:4444
Starting the payload handler...

## Current behavior
LHOST=> 192.168.xxx.xxx
LPORT => 4444
PAYLOAD => android/meterpreter/reverse_tcp
Started reverse TCP handler on 192.168.xxx.xxx:4444
 I Install and click the apk file in the smartphone but nothing happen!

## System stuff
using Evil-Droid-master v0.3

victim Model: Grand X LTE
victim OS: Android 7.0
victim Securit Pacth Level: 5/8/2017

### Metasploit version
Metasploit v4.16.30-dev

### I installed Metasploit with:
- [ x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
kali-linux-2018-vm-amd64

**Comment by h00die** [comment]
The handler is listening, so either you didn't create the payload correctly, there's a networking issue, or other environmental issue (like av). However, this isn't a support are. Please join on IRC for help with troubleshooting.
