### ISSUE TITLE
error while command msfconsole 

### ISSUE THREAD

**Issue by Muhaiminkp** [rapid7/metasploit-framework#9754]
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/tools/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/tools/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------
 iam useing termux

**Comment by wvu-r7** [comment]
> iam useing termux

Please talk to your distro package maintainer. Thanks.

**Comment by bcoles** [comment]
Termux is not supported. #11023

**Comment by smsm9944** [comment]
i have the same problem 
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `grpc.gemspec`: cannot load such file -- grpc/version
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/grpc.gemspec:4
 #  -------------------------------------------
 #  $LOAD_PATH.push File.expand_path('../src/ruby/lib', __FILE__)
 >  require 'grpc/version'
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/data/com.termux/files/home/metasploit-framework/Gemfile:4
 #  -------------------------------------------
 #  #   spec.add_runtime_dependency '<name>', [<version requirements>]
 >  gemspec name: 'metasploit-framework'
 #
 #  -------------------------------------------

**Comment by bcoles** [comment]
@smsm9944 Termux is not supported. #11023

https://wiki.termux.com/wiki/Metasploit_Framework

**Comment by lsonharry18** [comment]
There was an error parsing `Gemfile`: There are no gemspecs at /data/data/com.termux/files/home/metasploit-framework. Bundler cannot continue.

Help to solve
