### ISSUE TITLE
problem auxiliary/server/ftp

### ISSUE THREAD

**Issue by abba95** [rapid7/metasploit-framework#9761]
hi
kali 2018.1
metasploit v4.16.43
i use auxiliary/server/ftp modules to create an FTP server , but i login from windows , i can't upload file.i can only download. i set permission to 777 for /tmp/ftproot and /tmp and i login whith root user.
please help me
![capture](https://user-images.githubusercontent.com/36678197/37892304-f50f3418-30c6-11e8-83b5-34986649ed69.PNG)

**Comment by bcoles** [comment]
The FTP server module does not support writing files.

**Comment by bcoles** [comment]
As an alternative, you could use the [auxiliary/server/tftp module](https://github.com/rapid7/metasploit-framework/blob/master/modules/auxiliary/server/tftp.rb), which supports file upload.
