### ISSUE TITLE
Error when start msfconsole

### ISSUE THREAD

**Issue by fabiosilvamonteiro** [rapid7/metasploit-framework#9793]
Framework: 4.14.28-dev
Console  : 4.14.28-dev
OS: Win 10

Hello guys, I'm with a problem when I start msfconsole sometimes I got a error. I was trying to follow a tutorial that helps me to solve this, but I can't fix, when I typed reload_all like tutorial was suggesting me
I received this error:

![image](https://user-images.githubusercontent.com/6267452/38165742-4318a036-34e6-11e8-81e3-ae32a6a27723.png)

Someone can help me? please?

**Comment by cbrnrd** [comment]
Try using a more recent version of Metasploit. You're using 4.14.28 and the more recent versions are 4.16.x.
