### ISSUE TITLE
Setting time-based banners

### ISSUE THREAD

**Issue by Bry-fi** [rapid7/metasploit-framework#9796]
**This is not an error and more of a question**

I have noticed metasploit shows banners based on time events (pumpkin banner for halloween)

How do you set date-based banners to display on special dates during msf startup? For example I want a specific banner to show when it is my birthday but it will only show on my birthday.

What file do I edit to make this change?

**Comment by timwr** [comment]
I was wondering this myself :)
https://github.com/rapid7/metasploit-framework/blob/840923d59197b15719e4d6d03faba38e9342f724/lib/msf/ui/banner.rb#L50

**Comment by wvu-r7** [comment]
@timwr :+1:

**Comment by Bry-fi** [comment]
Awesome thanks!
