### ISSUE TITLE
Metasploit Hardwarebridge (Post failed: NoMethodError undefined method `[]' for nil:NilClass)

### ISSUE THREAD

**Issue by nakagit** [rapid7/metasploit-framework#9798]
I run 'getvinfo' using Metasploit Hardwarebridge, but I couldn't get vehicle informations.

## Steps to reproduce

Firstly, I connected 'OBDLink SX' and a car and then connected to Metasploit Hardwarebridge as following:
![180326-0005](https://user-images.githubusercontent.com/10558255/38179065-9d773c3a-3659-11e8-8692-27e2f7e1590e.png)
elm327_relay.rb -s /dev/ttyUSB0
Connected. Relay is up and running...

Open new terminal and executed as following:
msfconsole
msf > use auxiliary/client/hwbridge/connect 
msf auxiliary(connect) > run

[*] Attempting to connect to 127.0.0.1...
[*] Hardware bridge interface session 1 opened (127.0.0.1 -> 127.0.0.1) at 2018-xx-xx xx:xx:xx +0900
[+] HWBridge session established
[*] HW Specialty: {"automotive"=>true} Capabilities: {"can"=>true}
[!] NOTICE: You are about to leave the matrix. ALl actions performed on this hardeware bridge
[!]         could have real world consequences. Use this module in a controlled testing
[!]         environment and with equipment youa re authorized to perform testing on.
[*] Auxiliary modlue executeion completed
msf auxiliary(connect) > sessions -i 1
[*] Starting interaction with 1...

hwbridge > supported_buses
Available buses

can0

![180320-0002](https://user-images.githubusercontent.com/10558255/38179051-6670d9ee-3659-11e8-8359-c949c520aa65.png)

hwbridge > run post/hardware/automotive/getvinfo CANBUS=can0

[-] Post failed: NoMethodError undefined method '[]' for nil:NilClass
[-] Call stack: 
[-] /opt/metasploit-framework/embedded/framework/lib/msf/post/hardware/automotive/uds.rb:112:in 'get_current_data_pids'
[-] /opt/metasploit-framework/embedded/framework/modules/post/hardware/automotive/getvinfo.rb:38:in `run'

hwbridge > run post/hardware/automotive/getvinfo CANBUS=can0

[-] Post failed: NoMethodError undefined method 'join' for nil:NilClass
[-] Call stack: 
[-] /opt/metasploit-framework/embedded/framework/lib/msf/post/hardware/automotive/uds.rb:112:in 'get_current_data_pids'
[-] /opt/metasploit-framework/embedded/framework/modules/post/hardware/automotive/getvinfo.rb:38:in 'run'

![180323-0012](https://user-images.githubusercontent.com/10558255/38179059-86cb2a96-3659-11e8-8ff1-bbeab4c0e4cc.png)

## Expected behavior
To get vehicle information.

## Current behavior
Following errors occurred.
- Post failed: NoMethodError undefined method '[]' for nil:NilClass
- Post failed: NoMethodError undefined method 'join' for nil:NilClass

## System stuff
I tested on VMware Fusion environment and physical PC environment. But, both of environments, same errors occurred.

### Metasploit version
metasploit v4.16.14-dev- 

### I installed Metasploit with:
- Omnibus installer (nightly)
or
- Github (https://github.com/rapid7/metasploit-framework/)

### OS
Ubuntu 16.04

**Comment by nakagit** [comment]
Any update on this?

**Comment by abdilahrf** [comment]
![image](https://user-images.githubusercontent.com/6015012/42730825-dbe6264e-8829-11e8-9c08-f6ada88188bb.png)
i got similiar error

**Comment by bcoles** [comment]
@abdilahrf that's a different issue. Please create a new issue for `modules/post/windows/gather/enum_patches`

**Comment by ccondon-r7** [comment]
Closing this because it hasn't been active in a while and the person who wrote the hardware bridge left and isn't maintaining it currently; we may decide to give it a refresh later on!
