### ISSUE TITLE
bug: services -u -p 8080

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#9852]
bug: services -p 8080
list out all port

metasploit v5.0.0-dev-c525bc3c0a
ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
mac os 10.13.4

**Comment by bcoles** [comment]
What is `services -u -p 8080` ?

**Comment by busterb** [comment]
Try the 4.x branch for now `git checkout 4.x`, or `services -S 8080`

Looks like the services command needs to be modified for backward compatibility on the 5.x development tree.
