### ISSUE TITLE
Unhandled exception when `route` command fails to resolve hostname

### ISSUE THREAD

**Issue by asoto-r7** [rapid7/metasploit-framework#9855]
## Steps to reproduce

Using the `route` command (regardless of `add`, `get` or `del`) permits the lookup of a hostname.  If you provide a hostname that doesn't resolve, you get a traceback.  

You can run msfconsole, without a session, and just type the following command to see the traceback.
```
msf5 > route get bad.example.org
[-] Error while running command route: getaddrinfo: nodename nor servname provided, or not known

Call stack:
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket.rb:189:in `gethostbyname'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket.rb:189:in `getaddresses'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket.rb:173:in `getaddress'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket.rb:263:in `resolv_nbo'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket.rb:277:in `resolv_nbo_i'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket/switch_board.rb:233:in `best_comm'
/Users/asoto/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/rex-socket-0.1.10/lib/rex/socket/switch_board.rb:127:in `best_comm'
/Users/asoto/git/r7/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:920:in `cmd_route'
/Users/asoto/git/r7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/Users/asoto/git/r7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/Users/asoto/git/r7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/Users/asoto/git/r7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/Users/asoto/git/r7/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/Users/asoto/git/r7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/asoto/git/r7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'```
```

## Expected behavior

The exception should be caught.  My proposal is currently in `lib/msf/ui/console/command_dispatcher/core.rb` in `cmd_route` [(link here)](https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/core.rb#L860).  Additionally, a somewhat helpful error should be generated to say that the provided hostname could not be resolved from the local machine.

## Current behavior
An ugly traceback.  (See above.)

### Metasploit version
Updated yesterday:
> ```
> Framework: 5.0.0-dev-b83edc0ff6
> Console  : 5.0.0-dev-b83edc0ff6
> ```

### I installed Metasploit with:
- [X] Source install (please specify ruby version)
Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

### OS
Mac OS X 10.13.3

**Comment by Auxilus** [comment]
how about
```
msf5 > route get bad.example.org
[-] getaddrinfo: No address associated with hostname
```

**Comment by Auxilus** [comment]
or does it need to be more informative? I think the error message describes itself...
