### ISSUE TITLE
bash: msfpayload: command not found

### ISSUE THREAD

**Issue by Anonymou2025** [rapid7/metasploit-framework#9861]
msfpayload not working in my kali linux.

root@Anon:~# msfpayload
bash: msfpayload: command not found

It show Me This Error.

when i try to make any payload it also show this error. please help.

Thank You.

I am Using Kali-Linux 2018

**Comment by void-in** [comment]
You must be following a very old tutorial. msfpayload has been removed since long. See https://github.com/rapid7/metasploit-framework/pull/5509

Use msfvenom instead.

**Comment by frcrack** [comment]
jai essay un upgrade :apt-get upgrade msfpayload
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet msfpayload
le package msfpayload na pas etait trouver
