### ISSUE TITLE
I ran metasploit pro version 4.16.49-dev And I get this message/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)

### ISSUE THREAD

**Issue by yf007** [rapid7/metasploit-framework#9909]
## Steps to reproduce

How'd you do it?

Hey
The problem was still the same
Same error message as above

https://github.com/rapid7/metasploit-framework/issues/9035

### I installed Metasploit with:

- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

What OS are you running Metasploit on?  

kali 64

**Comment by busterb** [comment]
If this is the same, let's not create a duplicate ticket. I'll reopen the older one, since it provides a lot more information.
