### ISSUE TITLE
Dalvik/android version of Metasploit is not supported with this script! 

### ISSUE THREAD

**Issue by CrazyCoconut75** [rapid7/metasploit-framework#9950]
I created a payload with **Evil Droid**  in order to bypass anti-virus with an icon and a signature.

Now, after getting on meterpreter, downloading the apk on the phone and all that stuff, I try to run a persistence with **meterpreter's default persistence script.** 

The problem is that it says that 
### **"Dalvik/android version of Metasploit is not supported with this script!"** 

Is there a way to fix it? I don't really want to type a msfvenom prompt.

If not, is there a persistent script to run on the target's phone in order to always have access to the phone even if rebooted?

Thanks!

**Comment by bcoles** [comment]
You'll need a different method of persistence.

The [persistence script](https://github.com/rapid7/metasploit-framework/tree/master/scripts/meterpreter/persistence.rb) supports only Windows Meterpreters, as per:

```ruby
# Check for Version of Meterpreter
unless client.platform == 'windows' && [ARCH_X86, ARCH_X64].include?(client.arch)
  wrong_meter_version(client.session_type)
end
```

Metasploit scripts are no longer maintained. It's unlikely that the script will ever be updated to support different platforms such as Android.

**Comment by CrazyCoconut75** [comment]
I see. Well, thanks a lot

**Comment by timwr** [comment]
If you create an apk with msfvenom it's persistent after a reboot by default.
