### ISSUE TITLE
got problems with nokogiri to build native extensions

### ISSUE THREAD

**Issue by rootkittt** [rapid7/metasploit-framework#9973]
`### rootz@Rootkit-Surf:~$ sudo gem install nokogiri
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native `extension.`

    `current` directory: /var/lib/gems/2.5.0/gems/nokogiri-1.8.2/ext/nokogiri
`/usr/bin/ruby2.5` -r ./siteconf20180504-628-1catn7c.rb `extconf.rb`
`mkmf.rb` can't find header files for ruby at `/usr/lib/ruby/include/ruby.h`

`extconf failed, exit code 1`

`Gemfiles will remain installed in /var/lib/gems/2.5.0/gems/nokogiri-1.8.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/gem_make.out`

if i try to fix it with

`sudo apt-get install build-essential liblzma-dev patch ruby-dev `zlib1g-dev`

i always get this error....

`E: Syntax error /etc/apt/apt.conf.d/999seccomp:1: Extra junk after value`

im using kali on a windows subsystem. and usally it works fine but im going crazy about this error.

if someone can help me that would be soo great.

**Comment by RubyistCTRLDYT** [comment]
Your should try

**Comment by RubyistCTRLDYT** [comment]
You should try     sudo apt-get install ruby-dev        work for me

**Comment by busterb** [comment]
Sounds like the OP actually has corrupted data in the above-referenced file.
